### ISSUE TITLE
Scroll issue. TextField at bottom does not move up to visible area.

### ISSUE THREAD

**Issue by vpdevportal** [hackiftekhar/IQKeyboardManager#1000]
We are not able to see what we typing as TextField at bottom of view doesn't move up but hides behind keyboard.

**Comment by marbeaupa** [comment]
Same problem. 
Moreover in the text bar doesn't appear the two arrows on the left
![iphone7-screenshot1](https://user-images.githubusercontent.com/17100605/30780706-a83eab2c-a111-11e7-9030-c3762ec64217.jpeg)


<img width="413" alt="iphone7-screenshot2" src="https://user-images.githubusercontent.com/17100605/30780693-60c81b02-a111-11e7-9bb9-9bb4c26e67ac.png">

**Comment by hackiftekhar** [comment]
For the left/right arrow, please be sure that textFields are in same superview. If there are different superview then make their superview of class IQPreviousNextView. Check demo how it works.

**Comment by pMalvasio** [comment]
@marbeaupa I fixed that issue (Moreover in the text bar doesn't appear the two arrows on the left) using the last version (5.0.0) because I'm using Xcode 9. Anyways I still have the main issue of this thread: "... not able to see what we typing as TextField at bottom of view doesn't move up but hides behind keyboard."

**Comment by thomasmu** [comment]
Is your form located inside a UIScrollView?

**Comment by marbeaupa** [comment]
no, it is not a scroll view, but adjusting the constraints the screen is moving up when the keyboard enters into the screen

**Comment by hackiftekhar** [comment]
It's fixed with new solution, changes are in `master` branch now.
