### ISSUE TITLE
xcode 9 not done

### ISSUE THREAD

**Issue by g1174117917** [hackiftekhar/IQKeyboardManager#1001]
not show done in xcode9

**Comment by phanisai4u** [comment]
Not showing "Done" button in ios11

**Comment by 991442575a** [comment]
Not showing "Done" button in ios11

**Comment by 287291867** [comment]
To upgrade to the Version 4.0.13 .

**Comment by phanisai4u** [comment]
Thanks @287291867

**Comment by hackiftekhar** [comment]
Upgrade to v5.0.2 since I'm constantly releasing iOS11 and Xcode9 bug fixes frequently.

**Comment by g1174117917** [comment]
Thanks @287291867
