### ISSUE TITLE
iOS 11 has a problem

### ISSUE THREAD

**Issue by BountyProgrammer** [hackiftekhar/IQKeyboardManager#1002]
iOS 11 has a problem when the keyboard is hidden，This is what you see here.（ios10 is right
）
![d5fb7696-c8d4-467b-ada2-1fe6b4e73538](https://user-images.githubusercontent.com/12781172/30795759-acdff49c-a201-11e7-8ee4-7f1d6d9ab0bf.png)
![43062cf9-1a6e-4060-af7e-af222f37a988](https://user-images.githubusercontent.com/12781172/30795771-bc1f38be-a201-11e7-83f8-4dd302850752.png)

**Comment by hackiftekhar** [comment]
You probably testing with simulator. You have to enable software keyboard from Hardware menu of Simulator.

**Comment by ahbou** [comment]
This is a general issue with inputAccessoryViews on iPhone X.
The inputAccessoryView ignores the safeAreaLayoutGuides of its window.

You have to manually add the constraint. I believe Apple is aware of the bug.
In the meantime, I wrote about a quick fix here:
http://ahbou.org/post/165762292157/iphone-x-inputaccessoryview-fix
