### ISSUE TITLE
UITableView have problem. Urgent urgent！Please check demo code.

### ISSUE THREAD

**Issue by huzhiqin** [hackiftekhar/IQKeyboardManager#1003]
**Only deal with something error.**

 You can try this method ：
-(BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    if (IS_IOS_11) {
        UIScrollView.appearance.contentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentNever;
        UITableView.appearance.estimatedRowHeight = 0;
        UITableView.appearance.estimatedSectionFooterHeight = 0;
        UITableView.appearance.estimatedSectionHeaderHeight = 0;
        UITableView.appearance.contentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentNever;
    }
}

[IQ_BUG.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/1328696/IQ_BUG.zip)
![untitled](https://user-images.githubusercontent.com/12080036/30798573-b868d86e-a20c-11e7-88fa-116c2253e66a.gif)

**Comment by hackiftekhar** [comment]
okay, I got your point, I'll check the demo once I have enough time to check, thanks for attaching demo project.

**Comment by Shahbaz-Akram** [comment]
I have same issue any solution please.

**Comment by BountyProgrammer** [comment]
I have same issue any solution please.

**Comment by jaymathew** [comment]
same issue here as well

**Comment by hackiftekhar** [comment]
Can you guys check the demo project and debug it to find out something useful for us?

**Comment by huzhiqin** [comment]
Solve it ourselves. You can try this method ：
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    if (# IS_IOS_11) {
#         UITableView.appearance.contentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentNever;

    }

**Comment by icefall** [comment]
Same issue here!

**Comment by lilianeblima** [comment]
Same issue here!

**Comment by bsavoini-amaro** [comment]
same

**Comment by bsavoini** [comment]
same

**Comment by hackiftekhar** [comment]
It's fixed with new solution, changes are in `master` branch now. Please check and let me know if it doesn't work for you.
