### ISSUE TITLE
Up and down button is invisible in toolbar

### ISSUE THREAD

**Issue by veer9002** [hackiftekhar/IQKeyboardManager#1004]
Up and down(Next and previous) button is invisible in toolbar. Button "Done" is visible in right side of toolbar but at left side up and down button is not visible. I am using Xcode 9. When I create new project and used IQKeyboard manager up and down buttons are visible but in my existing project it's not visible.

**Comment by hackiftekhar** [comment]
Make sure all your textFields are on same superview, otherwise make a workaround using IQPreviousNextView. Search in demo project about how it should be configured.

**Comment by hackiftekhar** [comment]
@veer9002 also please check if you are using any UIAppearance proxy.
