### ISSUE TITLE
iOS 11使用求助

### ISSUE THREAD

**Issue by MyHZ** [hackiftekhar/IQKeyboardManager#1006]
iOS 11上tableviewCell包含UITextView，键盘弹出的时候tableview正常向上偏移，但是键盘下落的时候，每次tableview都自动向下偏移，甚至影响其他界面的collectionView。希望您能帮助我，谢谢！

**Comment by hackiftekhar** [comment]
@MyHZ क्षमा करें, मुझे चीनी भाषा नहीं आती है, क्या आप अंग्रेजी में लिखने का कष्ट करेंगे?

**Comment by MyHZ** [comment]
I'm sorry, I did not notice.My English is not very good. I will use the translation software to explain to you my question.
_**# I used UITextView in uitableviewCell. When the keyboard blocks TextView, Tableview moves up, but the navigation bar moves up.When the keyboard is retracted, Tableview is about 20 pixels more than the last time.**_
This happens in the use of iOS 11 system iPhone6s.In the low version and large-screen phone does not appear on this issue.I guess because the keyboard will not block the TextView in the big screen phone.I set ViewController's View to be the same as the screen ScrollView, the problem is gone.
Although my method can solve the problem. But still hope you can find a more appropriate way.So I sent you an email about how to solve this problem.
Your IQKeyboardManager helped us and we thank you

**Comment by MyHZ** [comment]
![untitled](https://user-images.githubusercontent.com/15187513/30837906-f759f06e-a22d-11e7-9eac-d6e25450364b.gif)

I uploaded a GIF, hoping to express my problem clearly.

Here's my code to solve this problem.

_-(void)loadView
{
     UIScrollView *scrollView = [[UIScrollView alloc] initWithFrame:[[UIScreen mainScreen] bounds]];
    self.view = scrollView;
}
_

**Comment by bendary** [comment]
我之前和你有类似的情况。通过设置scrollview.contentInsetAdjustmentBehavior=UIScrollViewContentInsetAdjustmentNever
解决了我的问题。你可以试试看

**Comment by MyHZ** [comment]
@bendary 你好，我是这样子设置了，但是没有效果的，在视图控制器加上

**Comment by MyHZ** [comment]
这段代码才解决掉

**Comment by MyHZ** [comment]
@bendary _-(void)loadView
{
UIScrollView *scrollView = [[UIScrollView alloc] initWithFrame:[[UIScreen mainScreen] bounds]];
self.view = scrollView;
}
_

**Comment by hackiftekhar** [comment]
@MyHZ This issue shouldn't be happen if you are using UITableView, because in case of scrollView and their subclasses (like UITableView) the library try to adjust it's contentInset property in order to avoiding keyboard hiding. Can you try to upload a demo so that I can take a look what might be wrong?

**Comment by MyHZ** [comment]
@hackiftekhar 
Hello
I wrote a demo, but did not reproduce my problem. But still there will be TableView down offset problem. I uploaded my code to you.
Because my code is more, I can not paste out. So put the key code in the Demo.

[IQTest.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/1335587/IQTest.zip)

**Comment by mikkelam** [comment]
I have this exact problem as well

**Comment by namanhams** [comment]
This is an issue on iOS 11, and while waiting for the official fix, i found a work around. Check it [here](https://github.com/hackiftekhar/IQKeyboardManager/issues/1005)

**Comment by MyHZ** [comment]
@mikkelam The author is now discovering and modifying the problem.You can use the method I made a temporary solution to that.
-(void)loadView
{
UIScrollView *scrollView = [[UIScrollView alloc] initWithFrame:[[UIScreen mainScreen] bounds]];
self.view = scrollView;
}

**Comment by hackiftekhar** [comment]
I'll try to check this in this weekend guys.

**Comment by hackiftekhar** [comment]
@MyHZ The demo project link isn't working. Can you please check again?

**Comment by MyHZ** [comment]
@hackiftekhar I have deleted the Demo. And my demo has no way to reproduce the error. I used UITextView in UITableViewCell. UITableView will be offset each time the keyboard disappears. As in the GIF inside like that.

**Comment by hackiftekhar** [comment]
@MyHZ so what's next for me?
