### ISSUE TITLE
Error in pod install for xcode 9

### ISSUE THREAD

**Issue by iOSamit** [hackiftekhar/IQKeyboardManager#1008]
pod 'IQKeyboardManagerSwift', '5.0.0' if i use above command

[!] Unable to satisfy the following requirements:

- `IQKeyboardManagerSwift (= 5.0.0)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `IQKeyboardManagerSwift (= 5.0.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

if i use this command  pod 'IQKeyboardManagerSwift'
then errors are
<img width="633" alt="screen shot 2017-09-26 at 10 54 27 am" src="https://user-images.githubusercontent.com/12462901/30843814-43bed21e-a2a9-11e7-8bb0-95f136f27492.png">

**Comment by AfrozZaheer** [comment]
Same issue Pod is not installing after xcode 9 up-gradation 
![screen shot 2017-09-26 at 2 43 20 pm](https://user-images.githubusercontent.com/25176835/30853745-1b06fe8a-a2c9-11e7-983e-400ab49ddf4a.png)

**Comment by hackiftekhar** [comment]
Please try running `pod update`

**Comment by Carloph** [comment]
how did you solve this? i have the same problem

**Comment by AfrozZaheer** [comment]
I removed pod repo and than again downloaded it... works for me.. and also for some reason I have to specify branch e.g. 

  s.dependency  "IQKeyboardManagerSwift", '5.0.0'
other than that it's was not working.
