### ISSUE TITLE
UI issue after updating on 4.0.13

### ISSUE THREAD

**Issue by Shahbaz-Akram** [hackiftekhar/IQKeyboardManager#1009]
When i click on textfield then all screen moves to bottom.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/8728903/30848323-3c8f27c8-a2b8-11e7-8d5d-c5b23f5a8866.gif)

**Comment by hackiftekhar** [comment]
Please change `contentInsetAdjustmentBehavior` property to `UIScrollViewContentInsetAdjustmentNever`

**Comment by yangmie** [comment]
Thanks! @hackiftekhar 

I encounter the same issue, but it seems that setting contentInsetAdjustmentBehavior property to UIScrollViewContentInsetAdjustmentNever does't work for me. 

@Shahbaz-Akram have you solved yours now?

**Comment by Shahbaz-Akram** [comment]
Where i change it?

**Comment by hackiftekhar** [comment]
Then I think probably you are the best guy to debug what's actually happening with your tableView. It changing the position or changing contentOffset or contentInset

**Comment by Shahbaz-Akram** [comment]
okay and when i add IQKeyboardManager.sharedManager().enable = false ; in specfic controller then this issue resolved.

**Comment by Shahbaz-Akram** [comment]
Now soultion which i implement is that simple 

viewdidload(){
 IQKeyboardManager.sharedManager().enable = false
}
viewwilldisapear(){
 IQKeyboardManager.sharedManager().enable = true
}
and handle manuallay keyboard on that controller.

**Comment by hackiftekhar** [comment]
It's fixed with new solution, changes are in `master` branch now. Please check and let me know if it doesn't work for you.
