### ISSUE TITLE
Not installing via Cocoapods on xcode 9 

### ISSUE THREAD

**Issue by AfrozZaheer** [hackiftekhar/IQKeyboardManager#1011]
Hi, I recently upgraded to xcode 9 and swift 4, but when I try to install IQKeyboard pod repo seams to not find it. any solution? 

![screen shot 2017-09-26 at 2 48 36 pm](https://user-images.githubusercontent.com/25176835/30854003-d27d069a-a2c9-11e7-9cb1-6bd85fa84df8.png)

**Comment by thomasmu** [comment]
Do you specify any source on your Podfile? Maybe your source has no specification for this pod. Try removing the source, then see if it's work.

**Comment by Jevon718** [comment]
I can get it to install but I have 82 errors

**Comment by Jevon718** [comment]
I got it to work with pod update
