### ISSUE TITLE
AddCustomDoneTarget

### ISSUE THREAD

**Issue by jordancamara** [hackiftekhar/IQKeyboardManager#1013]
Hi,

I was wondering, what happened to the AddCustomerDoneTarget method? I saw that there is a PreviousNextDoneWithTarget method, but that is passing the toolbar and not the sender.

**Comment by jordancamara** [comment]
Also the done action doesn't seem to dismiss the keyboard anymore. Any idea why that is?

**Comment by hackiftekhar** [comment]
See https://github.com/hackiftekhar/IQKeyboardManager/issues/979 https://github.com/hackiftekhar/IQKeyboardManager/issues/994

**Comment by jordancamara** [comment]
Thanks!
