### ISSUE TITLE
"Done" button on toolbar not visible in ios11

### ISSUE THREAD

**Issue by ETGgames** [hackiftekhar/IQKeyboardManager#1014]
It can still be pressed. Using the latest version.

**Comment by hoanglinhkd** [comment]
I have the same issues on v4.x(install through cocapod), but if you install by adding code from lasted release v5.0.2, They have already fix issue on iOS 11.
<img width="738" alt="screen shot 2017-09-27 at 09 56 02" src="https://user-images.githubusercontent.com/5093601/30893825-703f9b9a-a36a-11e7-8523-c85c7ca0adf5.png">

**Comment by hackiftekhar** [comment]
Btw, what’s the issue here?

**Comment by ETGgames** [comment]
"Done" button on toolbar not visible in ios11

**Comment by ETGgames** [comment]
Is there a way to upgrade to a working version with pods?

**Comment by hackiftekhar** [comment]
Please update to v5.0.2

**Comment by ETGgames** [comment]
Ah perfect! Thanks for the hard work, this truly is a great plugin!

**Comment by PatilDhananjay** [comment]
Update Pods
