### ISSUE TITLE
View can not transform identity

### ISSUE THREAD

**Issue by sunnyzl** [hackiftekhar/IQKeyboardManager#1017]
on iOS11, view can not transform identity sometimes

**Comment by sunnyzl** [comment]
When keyboard packed up, it will happen sometime

**Comment by hackiftekhar** [comment]
Not underestand, can you reword by adding some more info?

**Comment by sunnyzl** [comment]
<img width="225" alt="111" src="https://user-images.githubusercontent.com/11400615/30944831-131d3544-a42d-11e7-8fe7-88efb9e3a3b0.png">
just like this, when keyboard packed up. the view can not recovery position somtime

**Comment by hackiftekhar** [comment]
Do you know if you have pinned top layout guide or bottom layout guide constraints?

**Comment by sunnyzl** [comment]
I've already done that

**Comment by hackiftekhar** [comment]
If you pinned then this issue might happen @sunnyzl, for a workaround can you please try replacing that with superview?

**Comment by sunnyzl** [comment]
On latest version framework, it have not happened yet. I will test and observe for a while
