### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by faizashraf** [hackiftekhar/IQKeyboardManager#1019]
Hello, I've been using IQKeyboardManager for iOS 10.
It stopped working correctly after the update of my app to iOS 11 and migrating to Swift 4.
Can you please tell me, is there any version that I can install via CocoaPods that supports Swift 4?
Or maybe you can provide a workaround?

**Comment by hackiftekhar** [comment]
Just to let you know latest version 5.0.2 support swift4
