### ISSUE TITLE
UIButton action does not fire when tapping if a text field is in focus

### ISSUE THREAD

**Issue by dethell** [hackiftekhar/IQKeyboardManager#1021]
I'm using IQKeyboardManager and it works well in most areas of our app, but I have one view where tapping a UIButton doesn't fire when the text field is in focus. I have to tap the UIButton, and then when the keyboard closes tap it again to actually call the button action.

What is odd is the UIButton correctly highlights when tapped so it appears to be receiving the tap, but the action does not fire until the keyboard is closed. This is causing a lot of confusion for the users. I'm pretty sure IQKeyboardManager is set up to let taps to buttons go through, but I can't get this to work.

I'm using a very simple setup where in the app delegate I enabled the manager like this:
`IQKeyboardManager.sharedManager().enable = true`

**Comment by hackiftekhar** [comment]
Have you also set shouldResignOnTouchOutside to YES? If YES, then still library gesture isn't activated for UIControl and UINavigationBar subclasses. I'll check what might be the cause.

**Comment by dethell** [comment]
I have added:
`IQKeyboardManager.sharedManager().shouldResignOnTouchOutside = true`
and it still doesn't fire the UIButton action.

**Comment by hackiftekhar** [comment]
no no I mean I was asking a question that you have set `shouldResignOnTouchOutside` to true or false? I didn't say to change this property to yes. Regarding your original question, can you please share a demo so that I can take a look what might be wrong?

**Comment by yeziahehe** [comment]
same question

**Comment by Sivabalarajan** [comment]
I also have the same issue. I tried setting true and false both to shouldResignOnTouchOutside but have the same issue. The button click works only after the keyboard is dismissed. So the click event is not fired in the first click.

It is working in other screens which are in similar way but it is not working when the screen has TableView and TableViewCells

Does anyone have a solution?

**Comment by salmankaludi** [comment]
Any solution for this?

**Comment by hackiftekhar** [comment]
@Sivabalarajan As per my observations, it looks like the tap event is grabbed by the gesture you created in `hideKeyboardWhenTappedAround` method. That's why things works fine when it is removed. @salmankaludi This may be same situation for you, so please see if you are adding any additional gesture.

**Comment by pjsoftcoUser** [comment]
> Any solution for this?

Did you get a solution for this?
