### ISSUE TITLE
Keyboard size is wrong when XCode 8.3 with iOS 11 is being used

### ISSUE THREAD

**Issue by onursahindur** [hackiftekhar/IQKeyboardManager#1022]
Please check this issue on stackoverflow:
**https://stackoverflow.com/a/46389891/1153503**

Keyboard size is wrong when we use '_UIKeyboardFrameEndUserInfoKey_' instead of '_UIKeyboardFrameBeginUserInfoKey_'.

**Comment by hackiftekhar** [comment]
Xcode 8.3 doesn't support iOS11. right?

**Comment by hackiftekhar** [comment]
thanks for pointing out, I'll check if that's a real issue with public release of of Xcode9

**Comment by onursahindur** [comment]
Yes, XCode 8.3 does not support iOS 11, however users who use iOS 11 still can download a build which is compiled with XCode 8.3. Thanks for the response btw :)

**Comment by onursahindur** [comment]
Sorry for wrong update, the problem I guess is that it is because of the word guess view above keyboard. However I do not know the English meaning of it so I could not find an answer :)
