### ISSUE TITLE
disabled toolbar class seems does not work stable in iPhone X simulator

### ISSUE THREAD

**Issue by NicholasFLee** [hackiftekhar/IQKeyboardManager#1024]
Same code, works fine on my iPhone 6s, but not work on iPhone X simulator.

**Comment by Hoony-HU** [comment]
@NicholasFLee  iPhone 7 with iOS11 not work.

**Comment by NicholasFLee** [comment]
I should say it does not work stable.  sometimes it works, sometimes not.

**Comment by NicholasFLee** [comment]
@Hoony-HU well, It works fine on my iPhone 7 simulator ...
and it randomly works on my iPhone X simulator.

**Comment by Hoony-HU** [comment]
@NicholasFLee  I'm not using an emulator.I think there may be some misunderstanding.My problem is that the Done button has disappeared. emmmmmmmmmmm

**Comment by NicholasFLee** [comment]
I may close this issue because since I have uninstall and reinstall my app,  it works well :D
