### ISSUE TITLE
iOS 11 Issue ToolBar "Done" not showing

### ISSUE THREAD

**Issue by wisemasterwizz** [hackiftekhar/IQKeyboardManager#1026]
Hi , I have the same issue 'iOS 11 Issue ToolBar "Done" not showing' on all my iOS devices, iPhone 7.

I've updated my pod file to pod 'IQKeyboardManagerSwift', :git => 'https://github.com/hackiftekhar/IQKeyboardManager' but this has not worked for me.

I'm running the latest official version of Xcode 9, swift language 3.2. 

How can this be resolved?

Thanks
![img_1440](https://user-images.githubusercontent.com/20397012/30955914-43665410-a42d-11e7-80e2-0f33bb6a0978.jpg)

**Comment by wisemasterwizz** [comment]
fix in https://stackoverflow.com/questions/45686663/done-button-invisible-in-iqkeyboardmanager-library did not work either

**Comment by bryanfortune96** [comment]
having the same issue :)

**Comment by XDB-Chang** [comment]
having the same issue

**Comment by george012** [comment]
having the same issue

**Comment by hackiftekhar** [comment]
If you are using version older than 4.0.12 then you might getting this isuse, please update to latest version of library which is 5.0.2 at the moment.
