### ISSUE TITLE
What's wrong with this? 

### ISSUE THREAD

**Issue by 15017117** [hackiftekhar/IQKeyboardManager#1028]
IQKeyboardManagerSwift`kbManager.unsafeMutableAddressor in Static #1 in static IQKeyboardManager.sharedManager():
    0x109cd6a80 <+0>:  pushq  %rbp
    0x109cd6a81 <+1>:  movq   %rsp, %rbp
    0x109cd6a84 <+4>:  cmpq   $-0x1, 0x80264(%rip)      ; globalinit_33_1804EA4A44CDC62F5B66EAD58B4692DC_token1 + 7
    0x109cd6a8c <+12>: je     0x109cd6aa4               ; <+36> at IQKeyboardManager.swift:172
    0x109cd6a8e <+14>: leaq   0x8025b(%rip), %rdi       ; globalinit_33_1804EA4A44CDC62F5B66EAD58B4692DC_token2
    0x109cd6a95 <+21>: leaq   0x31e44(%rip), %rax       ; globalinit_33_1804EA4A44CDC62F5B66EAD58B4692DC_func2 at IQKeyboardManager.swift
    0x109cd6a9c <+28>: movq   %rax, %rsi
    0x109cd6a9f <+31>: callq  0x109d44098               ; symbol stub for: swift_once
    **0x109cd6aa4 <+36>: leaq   0x80525(%rip), %rax       ; static kbManager : IQKeyboardManagerSwift.IQKeyboardManager in Static #1 in static IQKeyboardManagerSwift.IQKeyboardManager.sharedManager() -> IQKeyboardManagerSwift.IQKeyboardManager**
(Thread Error)
    0x109cd6aab <+43>: popq   %rbp
    0x109cd6aac <+44>: retq   

Debug Area :
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Only run on the main thread!'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000108f9b1cb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010c0b4f41 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000108fa0362 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x000000010bb8f523 -[NSAssertionHandler handleFailureInFunction:file:lineNumber:description:] + 165
	4   UIFoundation                        0x0000000116aee678 -[NSLayoutManager(NSPrivate) _resizeTextViewForTextContainer:] + 1178
	5   UIFoundation                        0x0000000116aee09d -[NSLayoutManager(NSPrivate) _recalculateUsageForTextContainerAtIndex:] + 2232
	6   UIFoundation                        0x0000000116b2501e _enableTextViewResizing + 228
	7   UIFoundation                        0x0000000116b24d09 -[NSLayoutManager setTextStorage:] + 900
	8   UIFoundation                        0x0000000116b54223 -[NSTextStorage addLayoutManager:] + 84
	9   UIKit                               0x000000010da9f582 -[UIFieldEditor initWithTextField:textStorage:] + 739
	10  UIKit                               0x000000010e62053b -[UITextField _fieldEditor] + 186
	11  UIKit                               0x000000010e624c50 -[UITextField _initContentView] + 56
	12  UIKit                               0x000000010e60aee9 -[UITextField initWithFrame:] + 394
	13  UIKit                               0x000000010d9aff66 -[UIView init] + 62
	14  IQKeyboardManagerSwift              0x0000000109d0aec3 _T0So11UITextFieldCABycfcTO + 19
	15  IQKeyboardManagerSwift              0x0000000109ce327c _T0So11UITextFieldCABycfC + 60
	16  IQKeyboardManagerSwift              0x0000000109ce2cad _T022IQKeyboardManagerSwift0aB0CACycfc + 6557
	17  IQKeyboardManagerSwift              0x0000000109ce32a3 _T022IQKeyboardManagerSwift0aB0CACycfcTo + 19
	18  IQKeyboardManagerSwift              0x0000000109ce1300 _T022IQKeyboardManagerSwift0aB0CACycfC + 32
	19  IQKeyboardManagerSwift              0x0000000109d088f4 globalinit_33_1804EA4A44CDC62F5B66EAD58B4692DC_func2 + 20
	20  libdispatch.dylib                   0x0000000110b9543c _dispatch_client_callout + 8
	21  libdispatch.dylib                   0x0000000110b969c7 dispatch_once_f + 297
	22  IQKeyboardManagerSwift              0x0000000109cd6aa4 _T022IQKeyboardManagerSwift0aB0C06sharedB0ACyFZ6StaticL_V02kbB0ACfau + 36
	23  IQKeyboardManagerSwift              0x0000000109cd6a51 _T022IQKeyboardManagerSwift0aB0C06sharedB0ACyFZ + 17
	24  eBeeCare                            0x000000010692869b _T08eBeeCare11AppDelegateC11applicationSbSo13UIApplicationC_s10DictionaryVySC0F16LaunchOptionsKeyVypGSg022didFinishLaunchingWithI0tFyycfU_ + 59
	25  eBeeCare                            0x0000000106928ee0 _T08eBeeCare11AppDelegateC11applicationSbSo13UIApplicationC_s10DictionaryVySC0F16LaunchOptionsKeyVypGSg022didFinishLaunchingWithI0tFyycfU_TA + 80
	26  eBeeCare                            0x0000000106782e79 _T0Ix_IyB_TR + 41
	27  libdispatch.dylib                   0x0000000110b943f7 _dispatch_call_block_and_release + 12
	28  libdispatch.dylib                   0x0000000110b9543c _dispatch_client_callout + 8
	29  libdispatch.dylib                   0x0000000110ba1499 _dispatch_root_queue_drain + 1444
	30  libdispatch.dylib                   0x0000000110ba0e97 _dispatch_worker_thread3 + 132
	31  libsystem_pthread.dylib             0x000000011105c1ca _pthread_wqthread + 1387
	32  libsystem_pthread.dylib             0x000000011105bc4d start_wqthread + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by hackiftekhar** [comment]
Did you call this method on a non-main thread?

**Comment by hackiftekhar** [comment]
I checked and found that you are using sharedManager method in background thread and this library isn't intended to use from background thread.

**Comment by hongzhou85** [comment]
I got this error by following the installation guide to add in the below codes in AppDelegate:

IQKeyboardManager.sharedManager().enable = true
