### ISSUE TITLE
Crashing with Google places search

### ISSUE THREAD

**Issue by dionizb** [hackiftekhar/IQKeyboardManager#1029]
It was running good until i received this error last day.
Here is the error: ** *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndexedSubscript:]: index 0 beyond bounds for empty array' **
 And here is where it crashes 
 if (siblings[0] == textField)
            {
                if (siblings.count == 1)
                {
                    [textField setEnablePrevious:NO next:NO];
                }
                else
                {
                    [textField setEnablePrevious:NO next:YES];
                }
            }
I am using  pod 'IQKeyboardManager’, :git => 'https://github.com/hackiftekhar/IQKeyboardManager', :branch => ‘swift4'

**Comment by dionizb** [comment]
i just removed  :git => 'https://github.com/hackiftekhar/IQKeyboardManager', :branch => ‘swift4', updated the pod and it works now !

**Comment by hackiftekhar** [comment]
You could also use latest version of library which is 5.0.2 and officially support swift4, swift3.2 and swift3.0 as well. The branch swift4 was useful when Xcode was in beta phase.
