### ISSUE TITLE
IQKeyboardManager.sharedManager() not working in swift?

### ISSUE THREAD

**Issue by dducro** [hackiftekhar/IQKeyboardManager#103]
Hey hackiftekhar,

First of all, thanks for this nice keyboard framework!
The toolbar, placeholder and done button worked nice out of the box using pod.

However the prev/next buttons weren't  showing. So I thought it had something to to with my setup in ib. I tried to check if setting the toolbarManageBehaviour setting to IQAutoToolbarByTags and then manually setting all the tags in order would solve the problem.

But it can't find the class IQKeyboardManager in my viewcontrollers.
The below code gives the following error: Use of unresolved identefier 'IQKeyboardManager'

var kbManager = IQKeyboardManager.sharedManager()
kbManager.toolbarManageBehaviour = IQAutoToolbarByTag

I found this strange, because the manager does work.

Do you have any suggestions to solve my issue?
Thanks!

**Comment by lucianovalle** [comment]
Dear haycklftekhar: How  do you add IQKeyboardManager.bundle  to the project property? 
The method I am using, POD, is not working properly, and show the following error:
ld: library not found for -lPods-teste-IQKeyboardManager clang: error: linker command failed with exit code 1 (use -v to see invocation)

Thank you

**Comment by hackiftekhar** [comment]
It looks like Cocoapods setup issue and not by the library. Searching on the stackoverflow may find a solution for this Cocoapods install issue.

**Comment by lucianovalle** [comment]
Dear haycklftekhar: How to Use UIDatePicker with hours ?

Thank you

**Comment by faizan85** [comment]
@lucianovalle I think you should raise a ticket on IQDropDownTextField/IQActionSheetPickerView repo instead of IQKeyboardManager repo.

**Comment by Evana** [comment]
You should provide @3x size image for the arrows in the bundle. In my iPhone 6 arrows are not showing up but on 5s showing perfectly.

**Comment by hackiftekhar** [comment]
@Evana @3x size images added for the arrow in bundle.

**Comment by Evana** [comment]
Thanks

**Comment by narasimhanallamsetty** [comment]
@dducro I have downloaded your sample app which you created. It's working fine.  By following your app I have created another application according to our requirement. In the attached project I have multiple textfields. For nine and ten textfields I have changed inputView to datepickerview. **While entering text on Textfield(nine) it's taking textfield(ten).**  Please check in the attached sample project
[MoveViewUp.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/684091/MoveViewUp.zip)

**Comment by narasimhanallamsetty** [comment]
I have not add constraints yet. Please let me know if you need any additional information from me.

**Comment by dducro** [comment]
@narasimhanallamsetty thanks for checking the sample project.
hackiftekhar also downloaded the project and pointed out that the IQKeyboardManager.bundle was not added to my project. That fixed my issue.
Hope others with similar problems find your sample project useful.

**Comment by narasimhanallamsetty** [comment]
@dducro  yes. My sample project will be useful for whom who is having problem with IQKeyboardManager.bundle. But for me the issue is different. I would be very helpful if you resolve the issue.

**Comment by dducro** [comment]
@narasimhanallamsetty I can look in to it later this week. If you have any additional info of what you want to achieve, that could help to find the problem. It sounds like the problem hasn't something to do with IQKeyboardManager though. But it's more likely the problem lies in a reference.

You can also try this for more control over the buttons:
`// Adding previous/next button to textField`
`let kbManager = IQKeyboardManager.sharedManager()`
`textField.addPreviousNextDoneOnKeyboardWithTarget(self, previousAction: #selector(ViewController.previousAction(_:)), nextAction: #selector(ViewController.nextAction(_:)), doneAction: #selector(ViewController.doneAction(_:)), shouldShowPlaceholder: true)`
`textField.setEnablePrevious(true,next:true)`

And then add the previousAction, nextAction and doneAction methods to your viewController.
(I used this code for a datePicker in a form)
Hope this helps!

For next time, if you have an issue witch is different then the issues on a repo. You can always open a new one.
