### ISSUE TITLE
Not adjusting screen when switching text fields.

### ISSUE THREAD

**Issue by WillBoland** [hackiftekhar/IQKeyboardManager#1030]
It will not adjust the screen to view the text field if, when the view is loaded, the text field has user interaction disabled, but then is enabled while still on the screen. So when I load the view, it has user interaction as disabled. They click edit and it sets the property of the text fields to enabled. They can edit and switch between the text fields, but the screen won't adjust like it normally does so the keyboard doesn't hide the text fields.

**Comment by hackiftekhar** [comment]
Is this problem only happen with iOS11 or you are having issues with previous iOS versions also? If yes then have you pinned any constraint to top layout guide or bottom layout guide which might directly/indirectly affect textField positions?
