### ISSUE TITLE
How to remove quicktype?

### ISSUE THREAD

**Issue by Caeglin** [hackiftekhar/IQKeyboardManager#1031]
I just wanna use this tool for move text field when keyboard appear. So i want to remove thing which is appear up to keyboard. How can i remove?

**Comment by hackiftekhar** [comment]
You could do this manually by changing some native property of UITextField/UITextView.

**Comment by hackiftekhar** [comment]
The quicktype toolbar depends on user settings, this isn't added by library, it does affect with a Device Settings and the autocorrect property of UITextField. You should change it to hide it.
