### ISSUE TITLE
Crash on iOS 10.3

### ISSUE THREAD

**Issue by luis7lucho** [hackiftekhar/IQKeyboardManager#1032]
After updating to 5.0.2 it is crashing in IQToolbar class when appearanceProxy.tintColor = nil
it seems like tintColor property is not optional.
Is anyone else having this issue? 
Wondering if I should modify the file because it is "locked"

Thanks

**Comment by XRadevFRT** [comment]
I have the same issue....

**Comment by hackiftekhar** [comment]
Any finding for a fix from you guys?

**Comment by XRadevFRT** [comment]
..well I just commented the line for now and it works. Don't think its the best solution :D

**Comment by hackiftekhar** [comment]
I've just fixed it 4c19e2ff3531005ea675b15d55c2417cd38e9269
