### ISSUE TITLE
xcode 9 iOS11 runtime warning after migrating to Swift 4

### ISSUE THREAD

**Issue by DisobedientMedia** [hackiftekhar/IQKeyboardManager#1033]
Hi, 

After migrating my project to swift 4 I am seeing this warning appear in the debug console in xcode

Running version 5.0.2 of IQKeyboardManager

`implicit Objective-C entrypoint -[IQKeyboardManagerSwift.IQBarButtonItem isSystemItem] is deprecated and will be removed in Swift 4; add explicit '@objc' to the declaration to emit the Objective-C entrypoint in Swift 4 and suppress this message`

Have I done something wrong in migration, or is this a valid error that needs fixing in IQKeyboardManager?

Thanks

**Comment by luis7lucho** [comment]
I solved this by adding @objc next to var isSystemItem = false in IQBarButtonItem class on line 69. You will have to unlock for editing. Not sure if it the best way but it works :D

**Comment by DisobedientMedia** [comment]
Hi, thanks for the response. I understand I can do this, but wanted to report this so the upstream code could be corrected rather than editing the Pod project directly.
