### ISSUE TITLE
iOS 11, Version 5.0.3 UI Bug

### ISSUE THREAD

**Issue by kylexy32** [hackiftekhar/IQKeyboardManager#1037]
![ezgif com-gif-maker](https://user-images.githubusercontent.com/8315417/31099956-b4dfa3f6-a795-11e7-8a7e-43f0f7153336.gif)

I know several people were having some issues with iOS 11 and the keyboard display causing the UIView to shift down; although, after I updated to latest version (5.0.3) available, I am experiencing a slightly different bug where the view shifts both up and down at the same time as shown in the attached gif.

**Comment by hackiftekhar** [comment]
hmm, this might be due to latest changes I did to fix some issues related to safe area layout margin.

**Comment by kylexy32** [comment]
I have seen a few other people with very similar issues, do you happen to know if this is something that can / will be resolved in a future version? Or is there a temporary fix that you are recommending to people?

**Comment by assembleMHN** [comment]
I too believe that i have a issue related to this.

**Comment by FedinAndriy** [comment]
Same here. 

**Specs:**
IQKeyboardManager v5.0.3, iOS 11, iPhone 7 Plus Simulator.

**Details:**
UITextView in a view, that's an UIContainerView. The container view is on the a controller which is presented modally. 
Everything works perfectly on iOS 10.3.3.

**Issue:**
The view jumps down before keyboard presentation and jumps up before keyboard hiding.

![ezgif-2-c7b2c6e4c4](https://user-images.githubusercontent.com/1835752/31239075-97833888-aa04-11e7-8ee2-0008544e89f0.gif)

**Comment by kylexy32** [comment]
Has anyone been able to identify the root of this issue or a temporary fix? Currently I am unable to update my app for the current version of IQKeyboardManagerSwift has this bug in it.

**Comment by hackiftekhar** [comment]
@FedinAndriy Can you please check where you are calling beginFirstResponder? If you are showing a viewController then this should be called in viewDidAppear and should call [self.view endsEditing]; in viewWillDisappear.

**Comment by kylexy32** [comment]
When I updated to version 5.0.4, this error was fixed but I am brought back to the error that many people experienced with iOS 11 originally whereas the view is displaced every other keyboardDidShow. I am not doing the best job describing this, but you can see by the video recording below. I am able to resolve this issue using the following code in my ViewDidLoad with the corresponding function. If this fix could be implemented into the next updated version, I think it would help resolve many of these UI issues. 


![image](https://user-images.githubusercontent.com/8315417/31537110-000bd552-afcf-11e7-94cb-a4c84760ccbb.png)
![screen shot 2017-10-13 at 4 26 45 am](https://user-images.githubusercontent.com/8315417/31537020-c39a0db4-afce-11e7-83bb-edc2b741afbe.png)
![screen shot 2017-10-13 at 4 26 53 am](https://user-images.githubusercontent.com/8315417/31537022-c3a6cff4-afce-11e7-9003-50341ed597a7.png)

**Comment by hackiftekhar** [comment]
@kylexy32 Looks like you have a chat screen kind of UI, I would suggest you to disable library in that controller and implement solution by your own. Because it does have some complex UI handling and we cannot handle these kind of situations automatically.
