### ISSUE TITLE
"Done" button not Visible on ios 11

### ISSUE THREAD

**Issue by alexbeon22** [hackiftekhar/IQKeyboardManager#1040]
hi. i am using Xcode 9. ios 11. IQKeyboardManager version 5.0.3 (Installed by Cocoapod). In keyboard , done button is not visible. Kindly request you to look into this issue.

**Comment by vijayender1991** [comment]
Yeah same issue for me also. tried with 5.0.3 no use

**Comment by hackiftekhar** [comment]
Are you setting appearance proxy on UIBarButtonItem in your code?

**Comment by alexbeon22** [comment]
No

**Comment by hackiftekhar** [comment]
Are you using version older than 4.0.12?

**Comment by wisemasterwizz** [comment]
I had same issue then I removed all references to IQKeyboardManager from my project and installed pod IQKeyboardManager v5.0.3 and the Done button returned but with some minor issues.

**Comment by Akash136** [comment]
Yeah same issue for me also.....help me.

**Comment by hadwanihardik** [comment]
![image](https://user-images.githubusercontent.com/5634693/59820240-a06df580-9348-11e9-83f8-a85380d51773.png)

This issue come in International keyboards like : hebrew

**Comment by hackiftekhar** [comment]
Can you please share demo in which the toolbar or done Button is not visible?
