### ISSUE TITLE
Large gap between textfield and keyboard 

### ISSUE THREAD

**Issue by wisemasterwizz** [hackiftekhar/IQKeyboardManager#1042]
Hi 

Upgraded to IQKeyboardManagerSwift (5.0.3) and iOS 11 and we have large gap between textfield and keyboard. The gap is very small when viewing from the simulator for IOS11 and the gap is larger on my iPhone 7 device running iOS 11. 

Can this be looked at?

All is OK when running iOS 10.3.
![img_1462](https://user-images.githubusercontent.com/20397012/31177323-97f77c54-a90d-11e7-8ba1-5b665893287e.jpg)

**Comment by kylexy32** [comment]
I am experiencing this problem as well; however, unlike you I also have a similar gap between the textfield and my UITableView that appears when the keyboard is initiated;

**Comment by drieran** [comment]
Confirmed in 6SPlus iOS 11, a big gap. 5C in iOS10 was correctly. I tested 5.0.2 and all was fine.

**Comment by hackiftekhar** [comment]
For a workaround you have to set textField.keyboardDistanceFromTextField to some appropriate value.

**Comment by clowestab** [comment]
Encountering this issue. What exactly is causing the issue that makes this hacky fix a requirement?

**Comment by VatanaChhorn** [comment]
Is there any solution for this?
