### ISSUE TITLE
toolbar not appear for UITextView

### ISSUE THREAD

**Issue by bilawal-liaqat** [hackiftekhar/IQKeyboardManager#1044]
Toolbar not getting appear for UITextView inside UIAlertViewController.
 While using UITextView inside UIViewController, its working perfectly. 

Code : 

func showAlert(){
        let alertController = UIAlertController(title: "Title", message: nil, preferredStyle: UIAlertControllerStyle.alert)
        let rect = CGRect(x: 0, y: 0, width: 270, height: 120.0)
        let customView = UITextView(frame: rect)
       
        alertController.view.addSubview(customView)
         self.present(alertController, animated: true, completion:{})
    }

**Comment by hackiftekhar** [comment]
This is because library not intended to modify UIAlertController UI. Library explicitly added `UIAlertController` to `disabledToolbarClasses` list.
