### ISSUE TITLE
Content shuffling down screen till not visible

### ISSUE THREAD

**Issue by MattSHallatt** [hackiftekhar/IQKeyboardManager#1045]
Here's a GIF showing the problem I'm having. Really not sure how to proceed with this, as I can't tell what the problem is!

https://media.giphy.com/media/3o6nUXz3RRETJT2Bgc/giphy.gif

When I tap in to the fields, and tap done, the whole view controller contents slowly shuffle down until they're completely hidden.

There are no scroll views or table views in the hierarchy.

The only thing I can think might be causing issues is the fact that I have a UINavigationController embedded in another UINavigationController.

**Comment by osteven** [comment]
I had this problem as well.  But upgrading to v5.0.3 fixed it.

**Comment by MattSHallatt** [comment]
Thanks! That totally fixed my problem! If only I'd done a `pod repo update` before I added `IQKeyboardManager`! ;P
