### ISSUE TITLE
Problem with Xcode 9

### ISSUE THREAD

**Issue by tdermaris** [hackiftekhar/IQKeyboardManager#1046]
After updating Xcode, the library didn't work properly. I updated to 5.0 version and everything was ok. All of a sudden after one day I had the same problem again. I updated to 5.0.2 but the problem still exists. Any suggestions?
[Screen Recording.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/1360120/Screen.Recording.zip)

**Comment by arturdev** [comment]
As a quick workaround you can embed all your stuff in a UIScrollView.

**Comment by hackiftekhar** [comment]
@tdermaris can you please check if you've any layout constraint pin to top layout or bottom layout or safe area?

**Comment by tdermaris** [comment]
Actually there was a new design for the app yesterday and that screen is gone.. but I just checked for the constraints and yes there was a uiview pinned to the top and the confirm button pinned to the bottom. But as I told you it was working just fine before the update with these constraints..

**Comment by DogTwoChen** [comment]
@tdermaris i have the same problem have you solve it

**Comment by tdermaris** [comment]
No, I was lucky and they have changed the UI, so no more that screen..
