### ISSUE TITLE
not work in iOS 11 and Xcode 9 objective-c code

### ISSUE THREAD

**Issue by mohammad2015** [hackiftekhar/IQKeyboardManager#1047]
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_IQKeyboardManager", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture x86_64

before update Xcode it work fine now not work

**Comment by tranhieubframgia** [comment]
Do you solve this issue?

**Comment by mohammad2015** [comment]
yes 

Open Build Phases for the correct target, expand Compile Sources and add the missing .m files
