### ISSUE TITLE
not work in iOS 11 and Xcode 9 objective-c code in 4.0.10version

### ISSUE THREAD

**Issue by TYQbag** [hackiftekhar/IQKeyboardManager#1051]
‘DO button’ has gone,please help me

**Comment by wjiuxing** [comment]
@TYQbag where is the 'DO button'? Do you mean the 'Done' button on the right side of toolbar above your keyboard?

**Comment by IrfanMarwat** [comment]
On iOS 11.0 Its not showing Done button. However on 11.0.2 Its showing...

**Comment by atif-khan** [comment]
Facing the same issue of invisible Done button in iOS 11.0. I have checked 4.0.13 to 5.0.3 and no one has resolved this issue. Kindly suggest some quick fix. Thanks

**Comment by hackiftekhar** [comment]
It's already fixed with 4.0.13 and 5.0.3, not sure why you are not seeing it?

**Comment by Pulkit2017** [comment]
Facing the same issue

**Comment by atif-khan** [comment]
Has somebody found the solution?

**Comment by davidhilario** [comment]
I was able to make it work by using the source instead of the pod version. Just Drag and Drop(IQKeyboardManager) and i was back to normal in my case.

**Comment by showchi** [comment]
@hackiftekhar I am using 3.3.7. How can i fix this problem on iOS 11?

**Comment by hackiftekhar** [comment]
There is no solution for older versions, you have to fix it manually on that version by looking at my changes. sorry
