### ISSUE TITLE
Navigation bar shifts down on keyboard appear when hotspot is on

### ISSUE THREAD

**Issue by sidharthoswal** [hackiftekhar/IQKeyboardManager#1052]
It happens only when the view controller is embedded in a navigation controller as root view, and the navigation controller is then presented from a view controller. Attaching a demo project for the same. 

STEPS TO REPRODUCE:
1. Turn on mobile hotspot
2. Run the application
3. Click on `NEXT` button
4. Click on search bar to make it active

[testnav.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/1368194/testnav.zip)

**Comment by vje11** [comment]
I am facing same issue

**Comment by hackiftekhar** [comment]
Thanks @sidharthoswal for the demo project. I'll check it and provide my feedback.

**Comment by hackiftekhar** [comment]
Fixed it! Thanks for this bug report.
