### ISSUE TITLE
Toolbar buttons not respoding

### ISSUE THREAD

**Issue by odedharth** [hackiftekhar/IQKeyboardManager#1053]
I've updated to the last version of the pod, and when testing the app on iOS 11 I run into a problem in which clicking on the toolbar buttons doesn't do anythings. If I click on the "Done" button or the arrow buttons (for switching between text fields) noting is happening. 

How can I fix this?

**Comment by hackiftekhar** [comment]
I'm not sure why you are getting this issue. Can you please be sure you are able to reproduce this issue in a fresh demo project?

**Comment by asifSdSol** [comment]
Buttons are present and responding as i touched and they worked. But buttons are not visible. Fresh project in Xcode 9. 
![simulator screen shot - iphone se - 2017-10-13 at 21 06 13](https://user-images.githubusercontent.com/20966923/31563414-612aa12a-b078-11e7-93fc-f18f6a5dc91b.png)

**Comment by hackiftekhar** [comment]
Can you please update to 5.0.4 and please check if you are setting any appearance proxy for UIBarButtonItem?

**Comment by odedharth** [comment]
Yes, the new version fixed the bug!
