### ISSUE TITLE
bugger Exception

### ISSUE THREAD

**Issue by zhangyuchao** [hackiftekhar/IQKeyboardManager#1054]
_objc_retain 
-[UIView(Hierarchy) subviews] 
-[UIView(CALayerDelegate) _wantsReapplicationOfAutoLayoutWithLayoutDirtyOnEntry:] 
-[UIView(CALayerDelegate) layoutSublayersOfLayer:] 
___CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__

**Comment by zhangyuchao** [comment]
Hierarchy   这个子控件导致的app崩溃么？

**Comment by zhangyuchao** [comment]
Is there any possible that Hierarchy cause the exception in app? I have found in stackoverflow  that  the frame change maybe cause the question ,but i didn't change it in my web view

**Comment by hackiftekhar** [comment]
By looking at your logs it doesn't look like due to my library @zhangyuchao?
