### ISSUE TITLE
issue while goPrevious

### ISSUE THREAD

**Issue by anirudhamahale** [hackiftekhar/IQKeyboardManager#1057]
I have installed IQKeyboardManager 5.0.3.
Then in AppDelegate I enabled it, say suppose I have 4 UITextFields which are firstNameTextField, lastNameTextField, emailTextField and phoneNumberTextField.

Here is the issue, say now by pressing goNext button I reach to the last textField i.e. phoneNumberTextField. Now if I press goPrevious buttons it covers the textField.

This only happens in version 5.0.3, whereas for 4.0.13 it works fine.

![untitled](https://user-images.githubusercontent.com/16848003/31434925-81f25b16-ae9b-11e7-8b7e-263a498b27e5.gif)

**Comment by hackiftekhar** [comment]
Can you please check if you've pinned any constraint with top layout guide or bottom layout guide?

**Comment by anirudhamahale** [comment]
I didn't pin any constraint to top layout guide, I have only pin constraint to bottom layout guide from that Register button. But how it works fine in version 4.0.13? Any major changes you had made?

**Comment by anirudhamahale** [comment]
It's better if you just make a video tutorial how to use it with top layout guide because every time I use it with top layout guide it doesn't scroll well.

**Comment by hackiftekhar** [comment]
It's fixed with new solution, changes are in `master` branch now. Please check and let me know if it doesn't work for you.

**Comment by anirudhamahale** [comment]
Yep I just installed 5.0.7 & it works very fine.
Thanks👍🏻

**Comment by hackiftekhar** [comment]
@anirudhamahale I mean it should work with the master branch changes. I'm not sure if 5.0.7 fixes this for you.
