### ISSUE TITLE
keyboard covers input textfields in iphone 5s. i am using swift 4

### ISSUE THREAD

**Issue by Appsteamvasant** [hackiftekhar/IQKeyboardManager#1059]

**Comment by sudhakar-varma** [comment]
Add scroll view to main view then add view in to scrollView. Then add componets to that view.Please find the attachment for ref
![screen shot 2017-10-11 at 6 51 42 pm](https://user-images.githubusercontent.com/19358372/31442911-864d7a6e-aeb5-11e7-9f00-018ff1ac40d6.png)

**Comment by Appsteamvasant** [comment]
ok thanks it's working

**Comment by Appsteamvasant** [comment]
one more, how to get Done button action on toolbar.

**Comment by sudhakar-varma** [comment]
@Appsteamvasant This method i used in objc ` [yourTextField addRightButtonOnKeyboardWithText:@"LOGIN" target:self action:@selector(toolBarButtonLoginAction:) titleText:@"Click Login to proceed"];` Please search in swift.

**Comment by atalayasa** [comment]
Hello I have same issue and I can not put all the components in scroll view to another view because there are a lot of components and their constraints how can I fix it ? Thanks

**Comment by sudhakar-varma** [comment]
@atalayasa increase the size of storyboard. set similater size as freedom and change the size of storyboard and put all the components. scroll view has property of content size. 
![screen shot 2017-11-28 at 11 16 39 am](https://user-images.githubusercontent.com/19358372/33304239-ac3e1452-d42d-11e7-8f92-aa1d465c39cb.png)
