### ISSUE TITLE
UiCollectionView don't "jump" to cell that show while scrolling

### ISSUE THREAD

**Issue by NorbertSzydlowski** [hackiftekhar/IQKeyboardManager#106]
I see that next arrow don't work for new cells appear.
Is any solution for this?

And sometimes I can't jump to random next cell.
Example from first to second.

**Comment by hackiftekhar** [comment]
Optimized next/previous logic for UITableView/UICollectionView. But still sometimes when top/bottom cell doesn't exist in UITableView due to dequeue logic, then next/previous logic fails and we know it can't be fixed.
