### ISSUE TITLE
Xcode9, iOS 11, the input box prompt text ran to the upper left corner of the screen.

### ISSUE THREAD

**Issue by houyuxin** [hackiftekhar/IQKeyboardManager#1060]
![b96bbcc5a5ce83240ab6c020d9da1a11](https://user-images.githubusercontent.com/15883873/31475847-ab7e6b10-af35-11e7-9ea5-94f842a39f24.jpg)

**Comment by zhenzhenxu** [comment]
我也遇到了  你们怎么解决的呢

**Comment by hackiftekhar** [comment]
This issue happens when you build with Xcode8.3 or below but user is running on iOS11. It's been fixed and will be releasing new bug fixes soon via cocoapods.
