### ISSUE TITLE
Xcode9 iOS 11 right text

### ISSUE THREAD

**Issue by zhangweiwei2830** [hackiftekhar/IQKeyboardManager#1061]
<img width="336" alt="b01e1641-b810-42f5-963f-3069da05b1ce" src="https://user-images.githubusercontent.com/16369739/31476862-4e890c02-af3b-11e7-8482-f4c746402129.png">
when iOS11，the right textColor is white, how to result it?
IQKeyboardManager is 5.0.3

**Comment by hackiftekhar** [comment]
You might be setting tintColor with appearance proxy. please verify once.

**Comment by zhangweiwei2830** [comment]
What do you main? I used IQKeyboardManager with zero code.  You mean i had setted other delegate affected it?

**Comment by hackiftekhar** [comment]
Nope, you might have set UIBarButtonItem proxy, please check if you set it.

**Comment by asifSdSol** [comment]
Same issue, No button showing. Absolutely new project created in Xcode 9.0. 
![simulator screen shot - iphone se - 2017-10-13 at 21 06 13](https://user-images.githubusercontent.com/20966923/31555425-6686e908-b05a-11e7-8fda-98b2cf463205.png)

**Comment by CYQSARA** [comment]
Global search your code is set
" UIBarButtonItem *item = appearance] [UIBarButtonItem
[item setTitleTextAttributes:@{NSForegroundColorAttributeName:[UIColor whiteColor], NSFontAttributeName:[UIFont systemFontOfSize:15]} forState:UIControlStateNormal];"
 please verify @zhangweiwei2830

**Comment by zhangweiwei2830** [comment]
@asifSdSol  to set V 4.0.13

**Comment by NOMBER2011** [comment]
what should I  do ? how can I  write it right ?

**Comment by zhangweiwei2830** [comment]
what's wrong with you? the same issue?

**Comment by NOMBER2011** [comment]
yes, I have set v 4.0.13 , but I don't know it is wrong !please tell me

**Comment by zhangweiwei2830** [comment]
your code is reset  UIBarButtonItem color？
your project.

**Comment by NOMBER2011** [comment]
fix the IQKeyboardManager?

**Comment by NOMBER2011** [comment]
<img width="292" alt="2017-10-16 14 20 50" src="https://user-images.githubusercontent.com/13688441/31597937-a14620e8-b27d-11e7-9065-debc05bc5a8b.png">

**Comment by zhangweiwei2830** [comment]
你自己的项目中 有没有设置 UIBarButtonItem 这个颜色？

**Comment by asifSdSol** [comment]
@zhangweiwei2830 
asifhabib$ pod install
Analyzing dependencies
Downloading dependencies
Using AFNetworking (3.1.0)
Using IQKeyboardManager (4.0.9)
________________________________________
In my project podfile 
# Pods for MyProject
  pod 'AFNetworking', '~> 3.0'
  pod 'IQKeyboardManager'
_______________________________________
I have not IQKeyboardManager version.

**Comment by zhangweiwei2830** [comment]
pod 'IQKeyboardManager', '~> 4.0.13'
@asifSdSol

**Comment by hackiftekhar** [comment]
Please update pod so it will download latest version for you.

**Comment by NOMBER2011** [comment]
thank you

**Comment by Cehae** [comment]
@zhangweiwei2830 完成按钮颜色改变的问题你解决了吗？

**Comment by Cehae** [comment]
@CYQSARA nice

**Comment by zhangweiwei2830** [comment]
@Cehae en

**Comment by Victor1104** [comment]
I don not set UIBarButtonItem .But my button is white ,i cannot change it.Why?

**Comment by Victor1104** [comment]
@CYQSARA  i just set navigationItem.rightBarButtonItem

**Comment by zhangweiwei2830** [comment]
your version to 4.0.13

**Comment by Victor1104** [comment]
Thank you for your reply.
But my version is 4.0.13.

**Comment by Victor1104** [comment]
please look at this issue #1075

**Comment by TimurAykutYildirim** [comment]
@Victor1104 I cannot see any solution, nor useful reference. You just give reference to your own issue which has no solution in it??

**Comment by Victor1104** [comment]
[UIBarButtonItem appearance] setTitleTextAttributes:@{NSForegroundColorAttributeName:[UIColor whiteColor], NSFontAttributeName:[UIFont systemFontOfSize:15]} forState:UIControlStateNormal];
This sentence led to this problem and your version to 4.0.13.
@TimurAykutYildirim

**Comment by Victor1104** [comment]
[[UIBarButtonItem appearance]setBackButtonTitlePositionAdjustment:UIOffsetMake(-600, 0) forBarMetrics:UIBarMetricsDefault];
I use this line of code instead

**Comment by Victor1104** [comment]
The navigation bar returns the text of the button we set to clearColor  the cause of this problem.So I did not change its color but moved it out of the screen

**Comment by zivato** [comment]
How do I download version v 4.0.13,

Is it .    pod 'IQKeyboardManager', '~> 4.0.13'

**Comment by zivato** [comment]
Sorry done it!

**Comment by asifSdSol** [comment]
@zivato how??

**Comment by zivato** [comment]
pod install --repo-update

Then it allowed me to install with,  pod 'IQKeyboardManager', '~> 4.0.13'

**Comment by zivato** [comment]
Great back up and running, such a small thing we take for granted until it's not working then we realise how important it is. Thanks alot  @hackiftekhar you make our lives that little bit less stressful

**Comment by hackiftekhar** [comment]
Please try assigning `toolbarTintColor` to some color
