### ISSUE TITLE
In UIScrollView bottom inset has extra space in iPhone X

### ISSUE THREAD

**Issue by brightsider** [hackiftekhar/IQKeyboardManager#1062]
![31213259-5031287e-a9ae-11e7-9c19-ee951db2d19a](https://user-images.githubusercontent.com/4996231/31530517-bcaeb282-afe9-11e7-9aa2-a8b9a2a5a0d7.png)

**Comment by TeddyCodeDev** [comment]
Also having this issue but extra space between last tableViewCell and keyboard.
![simulator screen shot - iphone x - 2017-12-21 at 08 33 04](https://user-images.githubusercontent.com/30362527/34262527-df73591e-e629-11e7-806c-46e424e644fe.png)

**Comment by hackiftekhar** [comment]
okay, thanks for reporting I'll check what I can do for this.

**Comment by hackiftekhar** [comment]
It's fixed with new solution, changes are in `master` branch now. Please check and let me know if it doesn't work for you.
