### ISSUE TITLE
Add top space above navigation bar

### ISSUE THREAD

**Issue by mink-lparrouy** [hackiftekhar/IQKeyboardManager#1063]
Hello,

Sometimes after dismiss the keyboard, the navigation bar does not find his true place and a big space appears.

Can you help me ?

![img_0004](https://user-images.githubusercontent.com/22906662/31540561-488ac38c-b00c-11e7-95e4-618fb6f1c93b.PNG)

**Comment by hackiftekhar** [comment]
It's fixed with new solution, changes are in `master` branch now. Please check and let me know if it doesn't work for you.

**Comment by mink-lparrouy** [comment]
It doesn't work with your solution but I was able to fix it by adding

`IQKeyboardManager.sharedManager().canAdjustAdditionalSafeAreaInsets = true`

in my AppDelegate. Thank you

**Comment by hackiftekhar** [comment]
You have to try latest master branch version. This property will be removed with 6.0.0 release.

**Comment by kemalekren** [comment]
I got similar issue of it. I'm working swift 4.2 so when i clicked search controller in navigation bar, navigation bar extends its height i couldn't find the solution if it ?
<img width="306" alt="screen shot 2018-12-03 at 13 34 30" src="https://user-images.githubusercontent.com/7187826/49368618-2fdeee80-f700-11e8-85b3-b0d7196fe1e0.png">
