### ISSUE TITLE
Swift Compiler Error - Swift 4 and Xcode 9

### ISSUE THREAD

**Issue by rouviere** [hackiftekhar/IQKeyboardManager#1066]
I am attempting to use IQKeyboardManagerSwift for the first time. 

Running Xcode 9 with Swift 4

I downloaded the IQKeyboardManager-swift4 version and brought it into my app (drag and drop). There were no errors with the first build attempt, but when I add the following line of code to AppDelegate:

`IQKeyboardManager.sharedManager().enable = true`

I get the following error: 

> Use of unresolved identifier 'IQKeyboardManager'

If I attempt to import the framework as follows:

`import IQKeyboardManagerSwift`

I get the following error:

> No such module 'IQKeyboardManagerSwift'

I have not seen other mentions of this error

Either way, I get errors and cannot proceed.
![screen shot 2017-10-13 at 12 57 26 pm](https://user-images.githubusercontent.com/4437546/31561764-2ac0110e-b016-11e7-833c-618a92b23d17.png)

**Comment by NXGieng** [comment]
Hi @rouviere , because you did a `drag and drop` work, you wouldn't have to `import IQKeyboardManager`. Simply just remove it.

**Comment by rouviere** [comment]
Hi @NXGieng, I removed the import reference and now I have a new error. 

Use of unresolved identifier 'IQKeyboarddManager'

Not sure what I am doing wrong here. Any suggestions?

Thanks.

![screen shot 2017-10-14 at 9 09 30 pm](https://user-images.githubusercontent.com/4437546/31581261-5a0946a6-b124-11e7-88f3-e713b45c3d3d.png)

**Comment by itsrawand199** [comment]
click on the folder and add it to target-- it's an xcode bug, i do this manually everytime

**Comment by rouviere** [comment]
What is the best way to do this? Thanks.

**Comment by rouviere** [comment]
Alas, it has been 5 days since I reported this issue and so far no one has been able to help resolve the problem. 

IQKeyboardManager is promoted as a drop-in, no code solution, but after dropping it in every possible way, I still cannot get this to build without an error - see my previous post.

Is there any possibility that someone could take just a minute to provide instructions on how to get this installed properly? 

Thanks in advance!

**Comment by ahmadabudawod** [comment]
itsrawand199  ,Could you please show me the steps to add it as folder ?

**Comment by hackiftekhar** [comment]
He means to make sure that the library files are added in app target. Select files and open right menu, you’ll see some information and targets, tick on the apropriate checkbox target. That’s it.

**Comment by rouviere** [comment]
Please send me a screenshot of how you are doing this because I don’t see any checkboxes next to the targets:

**Comment by IvanivOleg** [comment]
@rouviere If you want to check targets, just select the framework and on the right panel you will see Target Membership view.
<img width="342" alt="screen shot 2017-10-24 at 3 46 26 pm" src="https://user-images.githubusercontent.com/2520289/31943881-d21547de-b8d2-11e7-82dc-80fcc5b88855.png">

**Comment by rouviere** [comment]
Hi Oleg and others,

I am sorry to drag this out so long but this is my first time doing something like this and the “it’s simple” instructions just don’t seem to apply to my situation.

Here is a screenshot of my settings. I have the target membership checked and I still get the error. 

Any additional guidance you can provide will be greatly appreciated.

Thanks.

**Comment by IvanivOleg** [comment]
@rouviere Have you set a proper target in the pod file?

**Comment by rouviere** [comment]
@IvanivOleg - Here is the bigger problem. I am fairly new to iOS development and this is the first time I have attempted to implement something like IQKeyboardManager. So I have not been through the steps and processes that everyone else is so familiar with. 

I am not using Cocoa Pods. I dragged the folder into my project and that is as far as I have gotten. Everything after that is errors.

If someone could provide step by step instructions for adding this to a project I would really appreciate it. 

Thanks.

**Comment by hackiftekhar** [comment]
@rouviere When you drag and drop the folder then on the popup confirmation box you also see the target membership at the bottom, please be sure that the correct target is checked and unwanted targets are unchecked.

**Comment by rouviere** [comment]
@hackiftekhar Thank you for your patience as I work through this. 

I am going to start over and describe the process I am following. Then if I do anything wrong, hopefully you can point me in the right direction.

1. The app is in a working state with no errors.
2. Drag the IQKeyboardManager from the finder to Xcode

![screen shot 2017-10-25 at 7 38 33 pm](https://user-images.githubusercontent.com/4437546/32031047-25ea794e-b9bc-11e7-9501-b13666751f66.png)

3. Create groups and Add to targets:

![screen shot 2017-10-25 at 7 39 39 pm](https://user-images.githubusercontent.com/4437546/32031093-57c2ec08-b9bc-11e7-866a-ebf4193cab95.png)

4. Add the code to AppDelegate.swift:  IQKeyboardManager.sharedManager().enable = true

5. Build - I now get the following errors:

![screen shot 2017-10-25 at 7 41 43 pm](https://user-images.githubusercontent.com/4437546/32031155-ad80624c-b9bc-11e7-9e1c-6a2ae8c07c1d.png)

I am obviously doing something wrong here.

**Comment by NadeemHakim** [comment]
Check Copy if needed let it copy in your folder. 
Please help yourself and install Cocoa Pods [https://guides.cocoapods.org/using/getting-started.html](url)

**Comment by mrsfer** [comment]
I have the same problem :(

**Comment by IvanivOleg** [comment]
@rouviere I just create an empty test project, do the same steps as you described above and everything works. Looks like there is some issue with topMostController(). If you have something like this in your code, try to rename it.

**Comment by hackiftekhar** [comment]
@rouviere you are using old version of library which is having issue with topMostController() method in latest swift version. I would suggest to pick latest version of library.

**Comment by rouviere** [comment]
@hackiftekhar This time it works correctly. I pulled the current Master version (I was using the Swift 4) version before. And this time there are no errors. Just a few warnings, but it still works. 

Thank you for your help and especially for creating this useful too.
![screen shot 2017-11-06 at 7 36 51 pm](https://user-images.githubusercontent.com/4437546/32474599-8bac212a-c32a-11e7-93e0-658f633ddf85.png)

**Comment by hackiftekhar** [comment]
Thanks :) I'll try to fix those warnings

**Comment by hackiftekhar** [comment]
I found no way to suppress these swift warnings, however I fixed some warnings for Obj-C version.

**Comment by sagarsukode** [comment]
Although I have added the "use_frameworks!" at the top of pod file, this error was come for me. So, I have changed the Swift version of this library from "Build Settings". Hope, this may be helpful for you.

![screen shot 2018-01-27 at 4 42 06 pm](https://user-images.githubusercontent.com/15633194/35471801-c0d1a660-0388-11e8-9f1f-521b9696a9ca.png)

**Comment by FlashTang** [comment]
> Hi @rouviere , because you did a `drag and drop` work, you wouldn't have to `import IQKeyboardManager`. Simply just remove it.

this one works ! thanks
