### ISSUE TITLE
IQKeyBoardManger moves wrong UIView and leaves it displaced.

### ISSUE THREAD

**Issue by wisemasterwizz** [hackiftekhar/IQKeyboardManager#1067]
Running IOS 11 IQKeyBoardManger (5.0.4) 

IQKeyBoardManger moves the UIView and after the keyboard is dismissed the UIView positioned incorrectly. Main UIView should move up along UIView holding the UITextView.

This was working OK in version 5.0.3.

This issue is also intermittent but has happened most often than not.

![simulator screen shot - ipad air 2 - 2017-10-13 at 22 46 37](https://user-images.githubusercontent.com/20397012/31567731-d08cb1bc-b068-11e7-88b6-07cecf8d4d95.png)
![simulator screen shot - ipad air 2 - 2017-10-13 at 22 27 52](https://user-images.githubusercontent.com/20397012/31567777-fbd28022-b068-11e7-8aad-ad28c3e1890b.jpg)

Please take a look ASAP.

Thanks

**Comment by snydersaurus** [comment]
I am experiencing a related issue with a custom inputAccessoryView. In my case, I don't want to use the IQ inputAccessoryView and am using my own.....the view gets displaced up the screen.

Reverting to an earlier version fixed the issue.

**Comment by AdnanAsghar** [comment]
![in](https://user-images.githubusercontent.com/23141110/31817038-f1c5984c-b5ab-11e7-8841-d96a151a4cb6.gif)

**Comment by christiygag** [comment]
Same issue happening for me also. It leaves space on the top every time I tap on the done button. Extra space added at the top of the app.

**Comment by yashbedi** [comment]
I'm also facing the same issue, and my app is near to the launch date. 😓
@hackiftekhar 
It would be great if you'll look forward to this issue,
we all would be super thankful as we've using this ultimate library from quite a long time and dont want to replace or not use it 😇.

**Comment by assembleMHN** [comment]
Same problem here

**Comment by hackiftekhar** [comment]
@wisemasterwizz @AdnanAsghar @christiygag @yashbedi @assembleMHN can you please attach any sample code here to debug this issue?

**Comment by christiygag** [comment]
@hackiftekhar When I debugged closely I found that this issue happens only when the text field has correction enabled. When this correction is enabled one suggestion bar will come above the text field and the framework is not handled that properly. U can fix it temporarily by disabling the correction and by changing the content type to unspecified.

**Comment by hackiftekhar** [comment]
It's fixed with new solution, changes are in master branch now. Please check and let me know if it doesn't work for you.
