### ISSUE TITLE
Increase scrolling height

### ISSUE THREAD

**Issue by H03in** [hackiftekhar/IQKeyboardManager#1068]
tanks for your amazing library
its very useful!

is there any way to increase height of scrolling when user clicked on textfield?
for example i need to show login button but its under the keyboard.

**Comment by H03in** [comment]
i found the answer
we can use this to change the distance between keyboard and textfield

IQKeyboardManager.sharedManager().keyboardDistanceFromTextField

**Comment by hackiftekhar** [comment]
Correct keyboardDistanceFromTextField is designed to do the tweak. For global level you could just set the sharedInstance() property as in your comment. It can be textField specific and it should also work if you write textField. keyboardDistanceFromTextField = xxx
