### ISSUE TITLE
my tableView with a section footer ,when i edit a textfiled on cell , my textfild is coverd by the footer .

### ISSUE THREAD

**Issue by Goallying** [hackiftekhar/IQKeyboardManager#1070]
my tableView with a section footer ,when i edit a textfiled on cell , my textfild is coverd by the footer .can you solve this problem? thank you .

**Comment by guyuekk** [comment]
Same

**Comment by guyuekk** [comment]
@Goallying 请问你怎么解决的？

**Comment by CK11FOR333** [comment]
same

**Comment by Faydee1220** [comment]
I have same problem, and temporary I add 
`tableView.shouldIgnoreScrollingAdjustment = true`
now it seems fine
