### ISSUE TITLE
topMostController Issue

### ISSUE THREAD

**Issue by marbeaupa** [hackiftekhar/IQKeyboardManager#1071]
I did a new project with only two textField and one Label, I download the IQKeyboardManager, swift 4, from Xcode I added this directory to my project with the command File/Add Files, I modified the AppDelegate.swift file as described in your manual, I launched the program and this is  window I can see:

![senza titolo](https://user-images.githubusercontent.com/17100605/31619998-5dab955c-b296-11e7-9b71-1ad79f916487.jpeg)

Where am I wrong?

**Comment by hackiftekhar** [comment]
Looks like you aren’t using latest version. Please be sure that you downloaded the version from one of the tag or from master branch.

**Comment by marbeaupa** [comment]
OK, perfect. The right download is from master branch, not from swift4. After running I have now only these warnings:
![senza titolo-1](https://user-images.githubusercontent.com/17100605/31657905-e9d23f56-b32f-11e7-88ed-fd155fc75971.jpeg)

**Comment by hackiftekhar** [comment]
You can ignore these warnings for now.
