### ISSUE TITLE
Holle, IQKeyboardManager (4.0.8)的"Done" Don't show

### ISSUE THREAD

**Issue by 623034345** [hackiftekhar/IQKeyboardManager#1073]

**Comment by MxABC** [comment]
pod 'IQKeyboardManager', '~> 5.0.4', 
iOS11, "Done" Don't show ,less iOS11 show normal

**Comment by AsadJavid** [comment]
same here ... any solution??

**Comment by MxABC** [comment]
I find my code question 

UIBarButtonItem *item = [UIBarButtonItem appearance];
    
    
    
    NSDictionary *attributes = @{NSFontAttributeName:[UIFont systemFontOfSize:0.0001],
                                 
                                 NSForegroundColorAttributeName:[UIColor clearColor]};
    
    [item setTitleTextAttributes:attributes forState:UIControlStateNormal];
    [item setTitleTextAttributes:attributes forState:UIControlStateHighlighted];

this code lead to  "Done" Don't show

**Comment by Victor1104** [comment]
@MxABC   I changed the clearColor to black. But the problem is still there

**Comment by haihoang88** [comment]
Same here.
The buttons (Next, Previous, Done) are still there as I can click on them. But they are not visible on iOS 11, is there any solution?

**Comment by Victor1104** [comment]
[UIBarButtonItem appearance] setTitleTextAttributes:@{NSForegroundColorAttributeName:[UIColor whiteColor], NSFontAttributeName:[UIFont systemFontOfSize:15]} forState:UIControlStateNormal];

This sentence led to this problem and your version to 4.0.13.

[[UIBarButtonItem appearance]setBackButtonTitlePositionAdjustment:UIOffsetMake(-600, 0) forBarMetrics:UIBarMetricsDefault];

I use this line of code instead

The navigation bar returns the text of the button we set to clearColor the cause of this problem.So I did not change its color but moved it out of the screen

@haihoang88

**Comment by andyyangdong** [comment]
@haihoang88   同样的问题， 请问解决了吗

**Comment by hackiftekhar** [comment]
That's the issue with your appearance proxy
