### ISSUE TITLE
3.3.7 & iOS7 Xcode9

### ISSUE THREAD

**Issue by topjx** [hackiftekhar/IQKeyboardManager#1074]
donebutton is gone，my app must support iOS7

**Comment by topjx** [comment]
What should I do?

**Comment by hackiftekhar** [comment]
You don’t have any option except fix the issue in my old library. Since latest version only support iOS8 as minimum deployment target.

**Comment by topjx** [comment]
How do you change the color of this font? I don't want white

![7620b72ae57dc59f8e88055d04050b08](https://user-images.githubusercontent.com/13688627/31717157-67a1fa08-b43d-11e7-921f-b4b4c166c40b.png)

**Comment by topjx** [comment]
I've solved it

**Comment by pratik1311** [comment]
@topjx 

Hey how you solve the issue. Please help me.

**Comment by Victor1104** [comment]
@hackiftekhar 
 My Done button is invisible. But When I click on the area and the hand is not lifted, the button is visible. Why?

**Comment by topjx** [comment]
@pratik1311 应该是你在其它地方设置了[uibarbuttonitem apprence]settincolor:whitecolor];

**Comment by hackiftekhar** [comment]
Please try assigning `toolbarTintColor` to some color

**Comment by gy37** [comment]
我这整个toolbar都不见了，很奇怪啊
[uibarbuttonitem appearance]没有设置过的

**Comment by topjx** [comment]
@gy37  只要没有设置IQKeyboard不可用 都会有的 应该是颜色浅  你没细看 都有的

**Comment by gy37** [comment]
@topjx 
![simulator screen shot - iphone 8 - 2017-10-31 at 16 25 40](https://user-images.githubusercontent.com/18750321/32214036-8882ba9e-be58-11e7-8910-310371e94aff.png)
在iOS11上，我重新下载的3.3.7的demo，也是只显示placeholder，没有箭头也没有完成按钮。

**Comment by topjx** [comment]
@gy37  哥哎 要是直接就显示了 作者还更新干嘛 就是要自己建一个分支出来 自己改着用

**Comment by gy37** [comment]
@topjx  你又改好的没有？让我参考一下，这么多代码，不知道改哪里。

**Comment by topjx** [comment]
@gy37  我也是简单改了一下 实现了我要的效果  不知道是否符合你的要求 你的邮箱多少 我发你
