### ISSUE TITLE
Xode 9.0  iOS 11  IQKeyboardManager4.0.13

### ISSUE THREAD

**Issue by Victor1104** [hackiftekhar/IQKeyboardManager#1075]
My Done button is invisible. But When I click on the area and the hand is not lifted, the button is visible. Why?

**Comment by Victor1104** [comment]
![1](https://user-images.githubusercontent.com/20557527/31707537-3f1269f0-b3b2-11e7-9d0c-d535c8c4db5d.png)
![2](https://user-images.githubusercontent.com/20557527/31707538-3f4b2376-b3b2-11e7-99a1-e36170123a58.png)

**Comment by Victor1104** [comment]
@hackiftekhar can you help me ?

**Comment by Victor1104** [comment]
I sloved it

**Comment by TimurAykutYildirim** [comment]
@Victor1104 how did you manage to solve this?

**Comment by Victor1104** [comment]
[UIBarButtonItem appearance] setTitleTextAttributes:@{NSForegroundColorAttributeName:[UIColor whiteColor], NSFontAttributeName:[UIFont systemFontOfSize:15]} forState:UIControlStateNormal];
This sentence led to this problem and your version to 4.0.13.

**Comment by hackiftekhar** [comment]
Please try assigning `toolbarTintColor` to some color
