### ISSUE TITLE
Question about Demo project

### ISSUE THREAD

**Issue by antoniqhc** [hackiftekhar/IQKeyboardManager#1076]
Hi i downloaded and run Demo swift project on the Special Case is it possible to navigate between textfield 2 and textfied 3? 

![simulator screen shot - iphone se - 2017-10-18 at 15 20 28](https://user-images.githubusercontent.com/4948280/31718626-4b52727a-b419-11e7-99b9-44467b04415d.png)

Thanks :)

**Comment by hackiftekhar** [comment]
You could make the Blue view as IQPreviousNextView and you’ll be done.
