### ISSUE TITLE
textFeild add in keyWindow, not work

### ISSUE THREAD

**Issue by spWang** [hackiftekhar/IQKeyboardManager#1082]
I use the IQversion is 5.0.4, and my iphone system version is iOS 10.3.3. when I add a textField in keyWindow, I found my textField not move, but the viewController in background moved. here is the code, you can paste it test

//add this code in viewController
- (IBAction)btnClick:(UIButton *)sender {
   
    // click btn, then add myView to [UIApplication sharedApplication].keyWindow;
    UITextField *myTextField = [[UITextField alloc] init];
    CGFloat height = 30;
    myTextField.frame = CGRectMake(0, [UIScreen mainScreen].bounds.size.height - height , self.view.bounds.size.width, height);
    myTextField.backgroundColor = [UIColor greenColor];
    [[UIApplication sharedApplication].keyWindow addSubview:myTextField];

}

**Comment by gy37** [comment]
我在window上添加的view，里面的textfield也不调用iqkeyboard

**Comment by hackiftekhar** [comment]
@spWang Adding UITextField directly to UIWindow isn't supported by library, the textField must contain within a UIViewController
