### ISSUE TITLE
IQKeyboardManager objective-c (5.0.4)"Done" Don't show in ios11

### ISSUE THREAD

**Issue by shenyuan000** [hackiftekhar/IQKeyboardManager#1083]

**Comment by hackiftekhar** [comment]
Please use 5.0.4 version, also please check if you are using appearance proxy to set UIBarButtonItem properties.

**Comment by hackiftekhar** [comment]
Please try assigning `toolbarTintColor` to some color

**Comment by Darren-chenchen** [comment]
IQKeyboardManager.sharedManager().toolbarTintColor = UIColor.red
Don't work

**Comment by hackiftekhar** [comment]
hmm then you probably setting textAttributes property of UIBarButtonItem using appearance proxy. Can you please check @Darren-chenchen ?
