### ISSUE TITLE
ios 11 done button not showing 

### ISSUE THREAD

**Issue by imepay** [hackiftekhar/IQKeyboardManager#1084]
we are using IQKeyboardmanager in one of the largest app of Nepal. However the done button in not showing. We are on the verge of submitting our app to app store. Please help and thanks for this amazing Library.

**Comment by Victor1104** [comment]
#1061

**Comment by hackiftekhar** [comment]
Please use 5.0.4 version, also please check if you are using appearance proxy to set UIBarButtonItem properties.

**Comment by 89FengRen** [comment]
the reason is just had setted UIBarButtonItem appearance

**Comment by hackiftekhar** [comment]
That's the 2nd reason

**Comment by andyyangdong** [comment]
使用5.0.4版本，没有使用全局设置UIBarButtonItem属性，还是不显示
