### ISSUE TITLE
No such module 'IQKeyboardManagerSwift'

### ISSUE THREAD

**Issue by ahmadabudawod** [hackiftekhar/IQKeyboardManager#1085]
After tried to test the library through iOS 11 and IQK library with (5.0.3) get this message , Please advise

**Comment by kszuba** [comment]
Swift 4 solution: 
Add at the top of pod file: 
`use_frameworks!` 
additionaly add: 
```
swift4 = ['IQKeyboardManagerSwift']

post_install do |installer|
    installer.pods_project.targets.each do |target|
        swift_version = nil

        if swift4.include?(target.name)
            swift_version = '4.0'
        else
            swift_version = '3.2'
        end

        if swift_version
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = swift_version
            end
        end
    end
end
```
Add to array swift4 all pods witch should build with swift 4

Then add: 
`import IQKeyboardManagerSwift` 
and you can use: 
`IQKeyboardManager.sharedManager().enable = true`

**Comment by pluckq** [comment]
Doesn't work for me

**Comment by sagarsukode** [comment]
This error was comes for me so I have changed the Swift version of this library from "Build Settings". Hope, this may be helpful for you.

![screen shot 2018-01-27 at 4 42 06 pm](https://user-images.githubusercontent.com/15633194/35471438-4f8a29ca-0381-11e8-9d7d-8f85092f812e.png)

**Comment by Vamsi-prog** [comment]
Swift 4.2 Solution
Install pods showing as below
use_frameworks!
pod 'yourPodName' 'version'(if required)

change swift Language version for all pods in Build settings..
