### ISSUE TITLE
导航栏顶部20px经常会黑掉，几率50%

### ISSUE THREAD

**Issue by gwlCode** [hackiftekhar/IQKeyboardManager#1087]
弹起输入框，隐藏输入框后，导航栏顶部20px经常会黑掉，几率50% ，什么原因，怎么解决

**Comment by TheBloodElf** [comment]
我也遇到了，在一个输入源获取焦点后整个视图（包括导航栏）都会上移的界面会出现；
看了源码后，解决方法也是非常简单，在控制器的view适当层次加一个滚动视图包含该输入源即可

**Comment by linbx08** [comment]
@TheBloodElf  你好 我也遇到这个问题 请问具体解决方案是怎样 这个在控制器的 view 适当层次加一个滚动视图包含该输入源即可 有demo最好了.谢谢

**Comment by CoderBt** [comment]
我也遇见了

**Comment by Youngchildren** [comment]
- (void)loadView  
{  
    [super loadView];  
    self.view = [[UIScrollView alloc] initWithFrame:self.view.bounds];  
} 
在视图页面添加上述代码就行。但是最新版本貌似也不行了。返回到3.2.0.3版本就可以了。
