### ISSUE TITLE
ios 11 done button not showing --(Debug 模式)

### ISSUE THREAD

**Issue by JLLJHD** [hackiftekhar/IQKeyboardManager#1088]
ios 11 done button not showing --(Debug 模式)

**Comment by hackiftekhar** [comment]
Please update to latest version

**Comment by Qjune** [comment]
I have used CocoaPods to update to the latest version，but got the same problem.

iOS 11.0.1
Xcode 9.0.1

**Comment by gy37** [comment]
最新版不支持iOS7.0啊，我在做的项目最低要支持iOS7.0

**Comment by hackiftekhar** [comment]
Please use 5.0.4, also please check if you are doing any appearance proxy on UIBarButtonItem.
