### ISSUE TITLE
iOS11 left/right arrow not show on Toolbar

### ISSUE THREAD

**Issue by AshCheng** [hackiftekhar/IQKeyboardManager#1089]
To fit iOS11, pod update to version 5.0.4, the done button show on the toolbar, but the left and right arrow not show on the toolbar

**Comment by verareddy17** [comment]
Hi i facing same issue how to solve  left and right arrow not show on the toolbar

**Comment by huoran323** [comment]
have the same issue

**Comment by arvindkumar-gr** [comment]
same issue

**Comment by hayashi1202** [comment]
I have updated to version 5.0.4, the done button and left/right arrow still not show on the toolbar, but I can click a narrow area to close keyboard on right side.

**Comment by hackiftekhar** [comment]
You might be setting appearance proxy of UIBarButtonItem. please check.
