### ISSUE TITLE
键盘工具栏在ios11上面 Done按钮颜色一直为白色，ios11以下没有问题

### ISSUE THREAD

**Issue by Gallon** [hackiftekhar/IQKeyboardManager#1092]
object-c版本键盘工具栏在ios11上面 Done按钮颜色一直为白色，ios11以下没有问题，版本是5.0.4

**Comment by Darren-chenchen** [comment]
我也发现有这个问题

**Comment by haoXu1990** [comment]
怎么解决的啊， 我是 xcode9，ios11.0.3

**Comment by haoXu1990** [comment]
我的问题解决了，我工程里面有设置 全局的BarButtomItem 的样式，所有这里也被修改了，困惑好久。

**Comment by gy37** [comment]
我也遇到这个问题了，有没有已经解决的，分享一下呗

**Comment by SanlinBlackball** [comment]
我没有设置也遇到了这种问题 你怎么解决的 @gy37

**Comment by gy37** [comment]
@SanlinBlackball  我还没有解决，版本不一样，我的是3.3.7的

**Comment by 18202835972** [comment]
@haoXu1990 请问一下具体是怎么设置的？

**Comment by mmccss123** [comment]
同问一下 怎么解决，貌似说更新一下最新库就OK了？求指导

**Comment by Gallon** [comment]
可能是其他地方设置主题颜色的原因

在 2017-11-06 09:51:04，"gy37" <notifications@github.com> 写道：


@SanlinBlackball 我还没有解决，版本不一样，我的是3.3.7的

**Comment by Gallon** [comment]
我的问题是 其他地方设置主题颜色了

**Comment by polaris0227** [comment]
@haoXu1990 
我看不见完成按钮。
如果你解决了这一问题，请告诉我。
谢谢。

**Comment by haoXu1990** [comment]
@polaris0227  我是在base VC 里面设置了 BarButtomItem 的颜色为白色，而IQkeyborad 用的按钮也 barbuttomitem，所以看不见了。你的具体情况还的自己分析

**Comment by hackiftekhar** [comment]
This issue is already fixed with V5.0.5 https://github.com/hackiftekhar/IQKeyboardManager/blob/master/CHANGELOG.md Please update to latest version of library.
