### ISSUE TITLE
ios  5.0.4  完成按钮不能显示出来

### ISSUE THREAD

**Issue by Darren-chenchen** [hackiftekhar/IQKeyboardManager#1093]
IQKeyboardManager.sharedManager().toolbarDoneBarButtonItemText = "完成"
        
self.drawIputView.textView.addDoneOnKeyboardWithTarget(self, action: #selector(clickDoneBtn))

**Comment by haoXu1990** [comment]
检查是否设置了全局定义的 BarButtonItem

**Comment by andyyangdong** [comment]
ios 5.0.4完成按钮不能显示出来

**Comment by hackiftekhar** [comment]
You might be setting appearance proxy on UIBarButtonItem
