### ISSUE TITLE
In the react native, the Toolbar will disappear after typing a character

### ISSUE THREAD

**Issue by MikeFvv** [hackiftekhar/IQKeyboardManager#1094]
I imported IQKeyboardManager in native, and in the react native project, the Toolbar will disappear after typing a character
我在原生项目导入 IQKeyboardManager， 在react native 项目里面使用的时候， 输入一个字符后Toolbar 就会消失， 每次都一样。 在ios10 或者ios11 ，都会消失。

**Comment by hackiftekhar** [comment]
Are you checking on simulator? I believe this happen with iOS simulator only.

**Comment by a371291536** [comment]
I meet the same problem in react native 0.49 with the IQKeyboardManager(5.0.6) .   And it happens in iphone and  simulator commonly.

**Comment by hackiftekhar** [comment]
I'm not sure if it happens with real devices but it may happen with simulator.
