### ISSUE TITLE
Warning: Umbrela...(Objective-C) with Carthage

### ISSUE THREAD

**Issue by Droppix** [hackiftekhar/IQKeyboardManager#1096]
Hi,

I used the last version of IQKeyboardManager (Objective-C) with Carthage, and I have many warnings "Umbrela..."
I resolved this problem on modify the IQKeyboardManager.h :

#import "IQKeyboardManagerConstants.h"
#import "IQUIView+IQKeyboardToolbar.h"
#import "IQPreviousNextView.h"
#import "IQPreviousNextView.h"
#import "IQUIViewController+Additions.h"
#import "IQKeyboardReturnKeyHandler.h"
#import "IQUIWindow+Hierarchy.h"
#import "IQTextView.h"
#import "IQToolbar.h"
#import "IQUIScrollView+Additions.h"
#import "IQUITextFieldView+Additions.h"
#import "IQBarButtonItem.h"
#import "IQTitleBarButtonItem.h"
#import "IQUIView+Hierarchy.h"

Regards

**Comment by iOSleep** [comment]
meet the same proble @hackiftekhar
