### ISSUE TITLE
Tool bar text issue

### ISSUE THREAD

**Issue by ANSCoder** [hackiftekhar/IQKeyboardManager#1097]
Hello 

I am getting tool bar's text issue in iOS 11 with Objective - C library.

 ![Tool bar UI issue](https://user-images.githubusercontent.com/19596311/32156598-745547de-bd64-11e7-896e-950bc0ddb95c.png)

**Comment by jeremiasdsa** [comment]
So do I.
Did you find a way to solve it?

**Comment by ANSCoder** [comment]
Yes, I fixed it.

this is available in the new update of **IQKeyboard**  and I used first **Xcode 9** checked the issue and solve it.

IQToolbar > func layoutSubviews > add conditions for iOS 11 and iOS 10 or old version.
