### ISSUE TITLE
Adapter safeArea Issues  适配safeArea 异常

### ISSUE THREAD

**Issue by SuperMarioUDLR** [hackiftekhar/IQKeyboardManager#1098]
Hi, When a textField that is constrained to the top of the safe area, then the keyboard covers the textField area. How to solve it.
你好，当设置textField相对于safe area 顶部约束时，键盘会挡住textField区域，请问如何解决。

![150936872859f72398a42df](https://user-images.githubusercontent.com/19200649/32172629-4293cf82-bd4a-11e7-85f1-358e70ff4cca.png)

![150936883759f724054c71b](https://user-images.githubusercontent.com/19200649/32172640-4c7386a0-bd4a-11e7-96ca-6d34f60202ed.png)

**Comment by hackiftekhar** [comment]
It's fixed with new solution, changes are in `master` branch now. Please check and let me know if it doesn't work for you.
