### ISSUE TITLE
adding extra space at top of the view

### ISSUE THREAD

**Issue by sahabe1** [hackiftekhar/IQKeyboardManager#1099]
please see attachment
![img_e0228](https://user-images.githubusercontent.com/1065015/32174151-24a22d54-bda7-11e7-90cd-ccbbb4748cba.JPG)

**Comment by vinisimionato** [comment]
Same problem here

**Comment by vinisimionato** [comment]
![simulator screen shot - iphone se - 2017-10-30 at 19 49 53](https://user-images.githubusercontent.com/10178983/32197470-8f569604-bdab-11e7-9d58-ab1b53faa954.png)

**Comment by MihaiEBS** [comment]
try to use IQKeyboardManager (Objective-C) 
pod 'IQKeyboardManager'

**Comment by pratik1311** [comment]
I have a same problem.

Main view have more space on top When keyboard hide.

Please help me @sahabe1 @vinisimionato

**Comment by hackiftekhar** [comment]
It's fixed with new solution, changes are in `master` branch now. Please check and let me know if it doesn't work for you.
