### ISSUE TITLE
Ios 11 Issue

### ISSUE THREAD

**Issue by girishghoda** [hackiftekhar/IQKeyboardManager#1100]
Hi, some wierd issue in ios 11
![keyboard_bug](https://user-images.githubusercontent.com/19307918/32174337-9376a7e6-bda7-11e7-93ab-e4bf8b255fbe.jpg)

**Comment by alaa001** [comment]
I am facing this issue too. Any solution will be really appreciated

**Comment by alaa001** [comment]
OK, I have fixed it by making sure that I dismiss the keyboard on viewWillDisappear , So I put that on mu base class and It worked, BUT for  UIWebView  you have to put webview.endEditing(true) on viewWillDisappear.
 this way that strange behavior stopped showing

**Comment by hackiftekhar** [comment]
Thanks for pointing out the solution @alaa001 because I wasn't able to figure out why this happens.
