### ISSUE TITLE
Can't switch keyboard

### ISSUE THREAD

**Issue by omarbatao** [hackiftekhar/IQKeyboardManager#1101]
Hi!
i have to fill some textfield in my form and one of that has a datepicker inputview. 

But when i press the "V" button the library doesn't switch the inputview and the system keyboard stay above. (As gif shows)

There are any way to skip that textfield or disable library for only one textfield? 

Thanks!
![2017-10-30 15 43 36](https://user-images.githubusercontent.com/13422180/32177223-06ebf816-bd8a-11e7-9c49-d0bef354d696.gif)

**Comment by omarbatao** [comment]
I'm using 5.0.4 version of IQKeyboardManagerSwift with ios 11 and swift 3.

**Comment by hackiftekhar** [comment]
@omarbatao Firstly you have to resign the currently editing textfield, secondly you might have written your code on textFieldShouldBeginEditing. You have to return NO for that date picker textField. These changes should make it work.

**Comment by omarbatao** [comment]
Thanks @hackiftekhar! It works good now!
