### ISSUE TITLE
ios11 and ios9 scroll issues

### ISSUE THREAD

**Issue by SeRG1k17** [hackiftekhar/IQKeyboardManager#1103]
IQKeyboardManager version 5.0.4(all 5.x too)

I have UIViewController with full screen UITableView(top constraint to superview) and adjust scroll view insets not marked.

![tableViewSettings](https://user-images.githubusercontent.com/13317173/32273269-cdc05c14-bf12-11e7-952e-1de57fcd83f1.png)

Logic of work:
The cell is the delegate of the textfield.
By clicking on the button the next one checks the validity of the field.
Then, in the table dataSource handler (via delegate):
```swift
     func recalculateCell(_ cell: TARegisterFieldCell) {
        
         guard let indexPath = tableView.indexPath (for: cell) else { return }
         tableView.reloadRows (at: [indexPath], with: .automatic)
     }
```

After the awakeFromNib () method, the error text is set, if it exists.

Perhaps this is not the best way to implement it, but it is necessary in this application. 
This works fine for iOS10, but there are the following bugs in other versions of OS.

**ios11:**
![ios11](https://user-images.githubusercontent.com/13317173/32271659-f2f95208-bf0b-11e7-86ad-0a2e4d01fdc5.gif)
Apparently, in iOS 11 for some reason new cell sizes are not taken into account when going to the next textfield.

Here's how it works in **iOS 9-10**:
![ios9](https://user-images.githubusercontent.com/13317173/32271663-0092d18c-bf0c-11e7-821d-d7a2cfbc0663.gif)

However, in **ios9** there is a bug associated with the last textfield (with UIReturnKeyType.done) and here's the code that handles this:

```swift
    func textFieldShouldReturn (_ textField: UITextField) -> Bool {
        
        if IQKeyboardManager.sharedManager (). canGoNext {
            IQKeyboardManager.sharedManager (). GoNext ()
            
        } else {
            textField.resignFirstResponder ()
        }
        
        return false
    }
```

![ios9bottom](https://user-images.githubusercontent.com/13317173/32271664-00af03d4-bf0c-11e7-8274-016a2ab82565.gif)

It feels like the table scrolls up to the height of the keyboard

P.S Sorry for the simulator lags :)
P.S.S There are no problems with empty space from top to table, I just hide the logo

**Comment by hackiftekhar** [comment]
I think reloading tableview causing the issue. Because cell is reload and tableView re-render it.
