### ISSUE TITLE
Increase contentOffset of scrollView

### ISSUE THREAD

**Issue by piercifani** [hackiftekhar/IQKeyboardManager#1106]
I have a form where a user can introduce some text and a button at the bottom of the scrollView anchored that I want to be visible when the user is editing that text so it doesn't have to scroll to the bottom to tap the button. 

You can see the behaviour I'm describing here:
![](https://media.giphy.com/media/l2ZDJGvOAAKK27SiA/giphy.gif)

However, I don't see any way of informing `IQKeyboardManager` that I want that button visible. Is this possible or do I have to "turn off" `IQKeyboardManager` using the `enabled` property and doing it manually?

Thanks a lot!

PS: I'm using the Swift variant of this library

**Comment by hackiftekhar** [comment]
You can set keyboardDistanceFromTextField for that particular textView object.
