### ISSUE TITLE
Declaration of 'NSForegroundColorAttributeName' must be imported from module 'UIKit.NSAttributedString' before it is required

### ISSUE THREAD

**Issue by sadiq81** [hackiftekhar/IQKeyboardManager#1109]
~/Documents/IQKeyboardManager/IQKeyboardManager/IQToolbar/IQBarButtonItem.m:60:20: Declaration of 'NSForegroundColorAttributeName' must be imported from module 'UIKit.NSAttributedString' before it is required
~/Documents/IQKeyboardManager/IQKeyboardManager/IQToolbar/IQBarButtonItem.m:60:52: Assigning to '<pseudo-object type>' from incompatible type 'UIColor *__strong _Nullable'

When building IQKeyboardManager scheme.

**Comment by hackiftekhar** [comment]
Released 5.0.6 with this fix
