### ISSUE TITLE
Crash on build with release mode at device and simulator

### ISSUE THREAD

**Issue by retsohuang** [hackiftekhar/IQKeyboardManager#111]
Here is screenshot
![screen shot 2014-11-05 at 11 29 44 pm](https://cloud.githubusercontent.com/assets/785920/4920247/cba87d2c-6500-11e4-9131-8bf6d110e72f.png)

Two method call have this issue

```swift
UITableViewCellScrollViewClass      = NSClassFromString("UITableViewCellScrollView")
EKPlaceholderTextViewClass          = NSClassFromString("EKPlaceholderTextView")
```

**Comment by hackiftekhar** [comment]
Fixed UITableViewCellScrollView class check and other checks also, but wondering the library is working fine in debug mode and still crashes somewhere in release configuration. :(

**Comment by hackiftekhar** [comment]
Changing "Optimization Level" in Build Settings solved the problem:-
http://stackoverflow.com/questions/3327981/app-runs-as-debug-but-crashes-as-release
http://www.mindjuice.net/2011/11/30/how-to-fix-an-app-that-crashes-in-release-but-not-debug

But I'm still worried about it. If somebody has suggestions, I would love to hear.

**Comment by hdoria** [comment]
+1 for this.

**Comment by Waderoni** [comment]
Is this last bug still an issue? I'd like to use but fear the issue discovered upon release is still not resolved.

**Comment by hackiftekhar** [comment]
Yes, it still an issue and I can't do anything for this. This is beyond my control. All compilation process goes to LLVM compiler.

**Comment by Waderoni** [comment]
Ok I see. Yet, this should work just fine when my app would go to the App Store and downloaded, etc. Right?  It's just the internal issue but it doesn't effect the outcome once the app is available for consumer download I imagine.

**Comment by hdoria** [comment]
I'm really worried about this process.  Is there anything we could do to fix this?

**Comment by hackiftekhar** [comment]
A workaround to change optimization level in settings, but for a fix I'm unable to debug code to find the exact problem. If someone can help or suggest me something, I love to hear.

**Comment by ronaldsmartin** [comment]
I've had issues with `NSClassFromString()` in optimized builds (while not using IQKeyboardManager) in some of my Swift-only apps. Using [`objc_getClass()`](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ObjCRuntimeRef/index.html#//apple_ref/c/func/objc_getClass) instead was what fixed my problem. Hope that helps.

About to try this pod out- it looks great! Thanks for sharing your efforts!

**Comment by hackiftekhar** [comment]
How did you replace NSClassFromString() with objc_getClass()? Can you share a sample code?

**Comment by ronaldsmartin** [comment]
In Swift, both functions have the same type signature, so you can just replace the function name.

Example ([checking class availability in Swift](http://stackoverflow.com/questions/25306561/check-for-class-existence-in-swift)):
```swift
if NSClassFromString("UIAlertController") == nil { // original
    ...
}
```
You would use:
```swift
if objc_getClass("UIAlertController") == nil { // replacement
    ...
}
```
In Obj-C, I think it would just be `objc_getClass("UIAlertController")` instead of `NSClassFromString(@"UIAlertController")` since `objc_getClass` takes a `const char *name`.

**Comment by hackiftekhar** [comment]
It seems As on Xcode 6.3 (Swift 1.2) this crash is not happening in release mode. @retsohuang , @Spilly , @padotj , @hdoria , @Waderoni , @ronaldsmartin , @mythodeia can some of you test the current Swift version with Xcode 6.3 (Swift 1.2) and let me know if it's still hapenning. If it's not happening then I would love to update Swift Version to match latest ObjC version of library.

**Comment by hdoria** [comment]
It's not happening anymore. I'm running fine with Xcode 6.3 and Swift 1.2.

**Comment by mythodeia** [comment]
fine on my end as well

**Comment by hackiftekhar** [comment]
So closing this issue, because this was not relevant to the library and it relevant to Apple Implementation of LLVM compiler.

**Comment by mihirpmehta** [comment]
if this bug is already fixed. Can you fix the ReadME file. because read me file says it is still known issie in swift

**Comment by hackiftekhar** [comment]
Thanks for reminding me. Will surely update. Thanks :)

**Comment by hackiftekhar** [comment]
Readme updated
