### ISSUE TITLE
Issue with Tab Bar and Textview on iPhone X / iOS 11

### ISSUE THREAD

**Issue by JustinBobo** [hackiftekhar/IQKeyboardManager#1112]
Hi,

I've attached screenshots to demonstrate the issue I'm having. Basically, the first time I tap into the textview, the keyboard covers half of the textview, then the color of the navigation bar changes and the tab bar shrinks. However, if I dismiss the keyboard and tap the textview again, it behaves as expected. It's only the initial tap/keyboard that causes this issue.
<img width="294" alt="screen shot 2017-11-04 at 7 01 31 pm" src="https://user-images.githubusercontent.com/25378266/32410275-e279f764-c192-11e7-8ab1-4a8fa6897c4d.png">
<img width="295" alt="screen shot 2017-11-04 at 7 00 55 pm" src="https://user-images.githubusercontent.com/25378266/32410278-e29e4696-c192-11e7-8335-f86e1ab065cc.png">
<img width="298" alt="screen shot 2017-11-04 at 7 01 09 pm" src="https://user-images.githubusercontent.com/25378266/32410277-e2936ed8-c192-11e7-8ab0-262e82f11366.png">
<img width="299" alt="screen shot 2017-11-04 at 7 01 22 pm" src="https://user-images.githubusercontent.com/25378266/32410276-e28672a0-c192-11e7-9646-1c380391738e.png">
<img width="301" alt="screen shot 2017-11-04 at 7 00 37 pm" src="https://user-images.githubusercontent.com/25378266/32410279-e2ab198e-c192-11e7-8c76-bc530f720e39.png">

**Comment by hackiftekhar** [comment]
It looks like you have a chat kind of screen. I would suggest you to disable library in this particular viewController and handle keyboard manually since you might need to do some workaround to make library work in these kind of controllers

**Comment by yashbedi** [comment]
Facing same issue, :(

**Comment by freemadc2** [comment]
I am also facing this issue. Works on all other devices except iPhone X. Maybe not calculating the keyboard height correctly?

**Comment by freemadc2** [comment]
@JustinBobo, @yashbedi, I found a workaround for this issue and thats by adding the line below to viewDidLoad.

IQKeyboardManager.sharedManager().canAdjustAdditionalSafeAreaInsets = true Also set the UIWindow background to white.

**Comment by davecoffin** [comment]
@freemadc2 did you do this in a fork I can check out? What file is this fix in?

**Comment by hackiftekhar** [comment]
It's fixed with new solution, changes are in `master` branch now. Please check and let me know if it doesn't work for you.

**Comment by silver0wn** [comment]
Hi, I am having the same issue...
