### ISSUE TITLE
Xcode 9.1 Compiler Error

### ISSUE THREAD

**Issue by SudhirGadhvi** [hackiftekhar/IQKeyboardManager#1114]
Several errors:
Argument of '#selector' refers to instance method 'refreshPlaceholder()' that is not exposed to Objective-C
Add '@objc' to expose this instance method to Objective-C

**Comment by hackiftekhar** [comment]
Can you please let me know which version of library you are using because @objc is already there on refreshPlaceholder() method.

`
@objc open func refreshPlaceholder() {
        
        if text.characters.count != 0 {
            placeholderLabel?.alpha = 0
        } else {
            placeholderLabel?.alpha = 1
        }
    }
`

**Comment by SudhirGadhvi** [comment]
Thanks that helps.
