### ISSUE TITLE
Strange behaviour if window has more than one view

### ISSUE THREAD

**Issue by sadiq81** [hackiftekhar/IQKeyboardManager#1115]
First of i know this is an edge case. I'm displaying alerts in view that is added to the window.

These alerts sometimes have textviews and textfields

This makes for some strange results when IQKeyboardManager tries to manage view offsets and also tries to reset them.

I would like to contribute to a solution and have checked out the repo. Do you have any pointers for me what to look for?

<img src="https://user-images.githubusercontent.com/1586725/32433841-9e093f9a-c2dc-11e7-8e43-9e732639645f.png" width="150"><img src="https://user-images.githubusercontent.com/1586725/32433842-9e31717c-c2dc-11e7-80ec-ea4b9188ad2f.png" width="150"><img src="https://user-images.githubusercontent.com/1586725/32433843-9e4e3190-c2dc-11e7-87d6-f001dc2dee3e.png" width="150">

<img src="https://user-images.githubusercontent.com/1586725/32433870-b538e422-c2dc-11e7-9c12-c85d3c3c3426.png" width="150"><img src="https://user-images.githubusercontent.com/1586725/32433871-b587f5da-c2dc-11e7-97b5-9722bff325b4.png" width="150"><img src="https://user-images.githubusercontent.com/1586725/32433872-b5a2abaa-c2dc-11e7-861c-92bf58772a83.png" width="150"><img src="https://user-images.githubusercontent.com/1586725/32433873-b5b7df84-c2dc-11e7-9527-2284d95a8c55.png" width="150">

**Comment by hackiftekhar** [comment]
I'm not much sure if if the textField is added directly to the window (without any view controller in the middle then library behave strange. If there is a view controller then I'll need to check what might be the wrong thing.

**Comment by kientux** [comment]
Are you using [SCLAlertView](https://github.com/dogo/SCLAlertView)? If yes then it using its own keyboard manager, so you should disable IQKeyboardManager for `SCLAlertView`:

```
[[IQKeyboardManager sharedManager].disabledDistanceHandlingClasses addObject:[SCLAlertView class]];
```

**Comment by hackiftekhar** [comment]
`SCLAlertView` is subclass of UIViewController so it should be fine to add it to `disabledDistanceHandlingClasses` list
