### ISSUE TITLE
能不能新增在现有view位移的基础上 自由设置偏移的属性

### ISSUE THREAD

**Issue by lovin67** [hackiftekhar/IQKeyboardManager#1117]
RT thx
因为 textfield 在编辑的时候  键盘会遮挡 对于输入内容的提示
比如：  textfield 输入的是数字 下面有一个label 显示 该数字 * 10  的结果  这个时候键盘就会遮挡 label 希望能有一个属性 调整 view 上移 的距离 以适应这种情况 
thx again .

**Comment by hackiftekhar** [comment]
You can set keyboardDistanceFromTextField for your particular textField.
