### ISSUE TITLE
Strange screen jumps when typing in UITextView

### ISSUE THREAD

**Issue by srgzah** [hackiftekhar/IQKeyboardManager#1118]
I have a UITableViewCell that contains the UITextView.
As user enter text, the cell size changes. And tableView updated like this:

```
[tableView beginUpdates];
[tableView endUpdates];
```
![iqkeyboardmanager-bug-ios mov](https://user-images.githubusercontent.com/11830747/32547619-14f864d8-c494-11e7-818e-8133060182f2.gif)

When include your library, screen jumps occur. This is seen only on iPhone 5/5s (iOS 11).

**Comment by srgzah** [comment]
It turned out that this is happening even without your library.
So I close the issue.

**Comment by rafalkitta** [comment]
I have faced the same problem.
@srgzah have you found solution for it?

**Comment by daizhipeng** [comment]
@rafalkitta have you found solution for it?
