### ISSUE TITLE
App crashes after updating IQKeyboardManagerSwift.

### ISSUE THREAD

**Issue by Fengson** [hackiftekhar/IQKeyboardManager#1120]
I've updated library to 5.0.4 because `Done` button isn't showing.
When I open screen that has IQKeyboardManager app crashes on line 2158 in IQKeyboardManager.swift

<img width="1680" alt="crash" src="https://user-images.githubusercontent.com/5645565/32604396-bf002bc8-c54d-11e7-8a8b-15861364b217.png">

**Comment by hackiftekhar** [comment]
Sorry to see this. I’m not sure why it happens. Can you send more details?

Regarding the done button color isue, I’ve released a patch with v5.0.6 that ahould work I believe.

**Comment by Fengson** [comment]
I think it might have been due to a fact that I had both IQKeyboardManager and IQKeyboardManagerSwift.

Once I replaced Objective-C version with a different library and kept IQKeyboardManagerSwift it works. Version 5.0.4 is working fine for me, too.

Thanks for a great library! 👍
