### ISSUE TITLE
If scrollView is as superView, it does't work

### ISSUE THREAD

**Issue by Daemonson** [hackiftekhar/IQKeyboardManager#1123]
If scrollView is as superView, all other views added on the scrollView, it doesn't work. If I set the scrollEnabled property as NO，it works, but the navigation bar also scroll to top. What should I do?

lib version:5.0.6
xcode 9.1
iOS: 10.3.2

**Comment by zzialiuze** [comment]
i meet the same problems! how can i fix it?

**Comment by Daemonson** [comment]
@zzialiuze I rollback my IQKeyboardManager to v3.3.7 to resolve my problem.😆

**Comment by ccSleep** [comment]
scrollView.contentSize = [UIScreen mainScreen].bounds.size;

**Comment by ccSleep** [comment]
hope this line will help.
scrollView.contentSize = [UIScreen mainScreen].bounds.size;

**Comment by hackiftekhar** [comment]
Make sure scrollView is able to calculate it's contentSize or it's forcefully defined like @ccSleep solution.
