### ISSUE TITLE
IQTitleBarButtonItem layout issue in iOS 10

### ISSUE THREAD

**Issue by Kaizi-oo** [hackiftekhar/IQKeyboardManager#1124]
Code like this:
    `            let button = UIButton (frame: CGRect(x: 0, y: 0, width: Theme.Measure.screenWidth - 120, height: 34))
            button.setTitle(" Tap Record", for: .normal)
            button.setImage(#imageLiteral(resourceName: "icon_voice"), for: .normal)
            CYJASRRecordor.share.actionButton = button
            textView.keyboardToolbar.titleBarButton = IQTitleBarButtonItem(customView: button)
    `
I'm using IQKeyboardManagerSwift. version 5.0.6 
First picture is running in iOS 11 
![right](https://kaizi-oo.github.io/WechatIMG2.jpeg)
This picture cut off by iPhone 6 with iOS 10 (same in iPhone 7)
![wrong](https://kaizi-oo.github.io/WechatIMG5.jpeg)

**Comment by hackiftekhar** [comment]
Tha’s not good. Can you share a demo project so that I can look?

**Comment by Kaizi-oo** [comment]
git@github.com:Kaizi-oo/IQKeyboardManagerSwiftTest.git

check it out please. I made it a small demo

**Comment by hackiftekhar** [comment]
I checked with iOS11 and it works great, I'll need to check this with iOS10 as you are saying that it happens with that.

**Comment by hackiftekhar** [comment]
@Kaizi-oo I fixed this issue with fcc22361d2dcd13f0f7af80db5f1ca4d519b7637 but you'll have to do some workarounds to make it work properly.

For customizing title bar button's customView, you'll have to assign a view which can calculate it's internal size. I did it by creating a subclass of UIButton

class TitleButton: UIButton {

    override func sizeThatFits(_ size: CGSize) -> CGSize {
        return CGSize(width: 150, height: 34)
    }
}

and then you can do this
        let button = TitleButton(frame: CGRect.zero)
        //Customize button
        textField.keyboardToolbar.titleBarButton = IQTitleBarButtonItem(customView: button)

I think that should solve the issue with current development code. I'll do a release after couple of more fixes which might take some time.

**Comment by Kaizi-oo** [comment]
get it, 👍
