### ISSUE TITLE
scrollView as superView, will cause a  problem

### ISSUE THREAD

**Issue by zzialiuze** [hackiftekhar/IQKeyboardManager#1127]
If scrollView is as superView, all other views added on the scrollView, it doesn't work. If I set the scrollEnabled property as NO，it works, but the navigation bar also scroll to top. What should I do?

**Comment by lw254605953** [comment]
I have the same problem...

**Comment by souvickcse** [comment]
Hi, Did you get the solution? In my case it is not be possible to make scrollEnabled to NO

**Comment by atalayasa** [comment]
I also got that problem did anyone fix it ?

**Comment by souvickcse** [comment]
There is no solution for this, this code works like that. It take the first scrollEnabled superview for doing the up/down of the view, if there is no scrollEnabled superview it will take the window to do the up/down. 
So you can change the first super scrollview's scrollEnabled to NO. Or you have to change the code, as per my requirement scrollEnabled can not be set to NO, so I am planning to do the changes, if there is any update i will post it here.

**Comment by fengweiru** [comment]
I have the same problem and sovled it.
You could try to set the contentSize about scrollview.

**Comment by hackiftekhar** [comment]
Please be sure your scrollView is calculating your contentSize correctly. Library makes some decisions based on the contentSize of scrollView.

**Comment by atalayasa** [comment]
Actually I solved the problem. I was using picker view and when I select something from that picker I have used view.endediting function it causes a problem. So I use resignFirstResponder now it is working fine.
