### ISSUE TITLE
Ambiguous use of 'topMostController() -Swift4 iOS 9.1

### ISSUE THREAD

**Issue by Junaidtt** [hackiftekhar/IQKeyboardManager#1128]
Ambiguous use of 'topMostController()'  Error while integrating with Swift 4 iOS 9.1﻿

**Comment by BhavikThummar** [comment]
I had same issue, I tried objective-c libraries in swift
 
First drag and drop IQKeyboardManager Objective-C Folder into your project.
Then create Bridging-Header file and import IQKeyboardManager.h file

#import "IQKeyboardManager.h"

Then go to AppDelegate and write
IQKeyboardManager.shared().isEnabled = true

It's Done !!

**Comment by hackiftekhar** [comment]
Please update to latest version, it's already has been fixed.
