### ISSUE TITLE
change right hand button title 

### ISSUE THREAD

**Issue by burkaslarry** [hackiftekhar/IQKeyboardManager#1131]
with respect of addDoneOnKeyboardWithTarget..., how to change the title of the button ?

**Comment by burkaslarry** [comment]
Given my working ; 

    self.txtUsername.addDoneOnKeyboardWithTarget(self, action: #selector(execute), titleText: "Done".localized() )
        // Do any additional setup after loading the view.

**Comment by hackiftekhar** [comment]
There is an addRightButton... similar some method to do that.
