### ISSUE TITLE
setCustomDoneTarget method not Found

### ISSUE THREAD

**Issue by MahipalV12** [hackiftekhar/IQKeyboardManager#1133]
setCustomDoneTarget is showing error and not found in recent update (available till 4.0.8). Is there any other option or method to set Custom Done target on textfield

**Comment by hackiftekhar** [comment]
It's replaced by another mechanism. Duplicate of https://github.com/hackiftekhar/IQKeyboardManager/issues/1016 https://github.com/hackiftekhar/IQKeyboardManager/issues/979
