### ISSUE TITLE
This is only enabled in Swift. Please include in ObjC as well.

### ISSUE THREAD

**Issue by Munchery-CarlosAlcala** [hackiftekhar/IQKeyboardManager#1134]
https://github.com/hackiftekhar/IQKeyboardManager/blob/c38b6c11acb375292412695e47a7bbdbf980cc1b/IQKeyboardManagerSwift/IQToolbar/IQTitleBarButtonItem.swift#L62

**Comment by hackiftekhar** [comment]
It's already there https://github.com/hackiftekhar/IQKeyboardManager/blob/c38b6c11acb375292412695e47a7bbdbf980cc1b/IQKeyboardManager/IQToolbar/IQTitleBarButtonItem.m#L119

**Comment by Munchery-CarlosAlcala** [comment]
The callback `setTitleTarger:action` is not working then, try yourself the function is not recognized.

**Comment by hackiftekhar** [comment]
Okay, I'll check when get some time.
