### ISSUE TITLE
IQKeyboardManagerSwift always be broken at one place

### ISSUE THREAD

**Issue by afraidiot** [hackiftekhar/IQKeyboardManager#1136]
After updated to Xcode 9.1 & Swift 4.0.2
If I have Swift Error and All Exceptions break points
When calling function IQKeyboardManager.init() in IQKeyboardManager.swift
The project always break at line 864
<img width="1405" alt="2017-11-14 3 41 38" src="https://user-images.githubusercontent.com/13517408/32876845-a26753a6-cad9-11e7-9930-70005ae5d7c9.png">
As you see, there isn't any crash, only be broken at line 864, and the code is as below
```
//Loading IQToolbar, IQTitleBarButtonItem, IQBarButtonItem to fix first time keyboard appearance delay (Bug ID: #550)
let textField = UITextField()
```
Only tapping continue button several times could the project run
Please update source code or rebuild the it with Xcode 9.1
Wish your updation

**Comment by Spetruk** [comment]
I have this bug too on obj-c

**Comment by afraidiot** [comment]
@Spetruk 
But I found, when I **using another MacBook Pro**, loading source code from remote server
I can run my project successfully(Xcode 9.1) with both Swift Error and All Exceptions break points
I do think there should need some source code rebuild with Xcode 9.1
But if you don't want be broken every time, you could just try using another MacBook Pro
Hope it help :)

**Comment by Xchn** [comment]
Can you solve it？I have this bug too on objc.

**Comment by afraidiot** [comment]
@Xchn 
My colleague with another MacBook Pro don't have this issue
After changing another MacBook Pro, my project's issue disappeared too
But the project in my old MacBook Pro still there
So before the author rebuild the source code with Xcode 9.1, the only solution I found is: **change another device**, sorry for can't provide a better solution...

**Comment by afraidiot** [comment]
@Xchn 
I think it is related to some cache and source code rebuilding, maybe...
So, If you don't want to blocked by this broken, just try to use another device

**Comment by shaojiankui** [comment]
I have this bug too on obj-c on macmini

**Comment by hackiftekhar** [comment]
It looks to be related to Xcode version + some project configuration. This wasn't happening with older Xcode. One more interesting thing is that it happens with some projects and doesn't happen with some other projects.

**Comment by afraidiot** [comment]
@hackiftekhar 
I don't think so, because the same project, fetching from Git, in my Mac, it appears. My colleague's Mac, not happen
Same Xcode version, same source code
But I agree with you, maybe it related to some project configuration, which it's hard to find out...

**Comment by hackiftekhar** [comment]
Exactly! It's something related to project configuration. Not an issue with library. That's why it's an apple bug and invalid issue for IQKeyboardManager.

**Comment by jlubeck** [comment]
@afraidiot @Spetruk Did you ever found a way to solve this? I'm running into the same issue...
