### ISSUE TITLE
UITextField inside UIPageViewController

### ISSUE THREAD

**Issue by tschleuss** [hackiftekhar/IQKeyboardManager#114]
Hi, i'm having a strange behavior when my UITextField is member of a UIViewController inside a UIPageViewController with Scroll transition style.
I made a sample project to turn that explanation more simple as possible.

When i tap the first UITextField and use arrows to go forward or backward the screen adjustments works very well. But when i tap a UITextField below on screen corner, the screen pan up and back down instantly.

When UIPageViewController transition style is Page Curl, that problem doesn't happen.
Maybe is something related to UIScrollView.

[Link to demo project](https://docs.google.com/uc?id=0B5fHdnrl2mGsNmFHM3BIMzBmbE0&export=download)

A simple gif explanation:

![iqkeyboardmanagertest](https://cloud.githubusercontent.com/assets/2786374/4957875/afc0b09e-66a8-11e4-94b2-3f89e1668af0.gif)

**Comment by hackiftekhar** [comment]
Added expicit check to not detect _UIQueingScrollView as UIScrollView.

**Comment by tschleuss** [comment]
Thanks !!! Works very well .

**Comment by bobintornado** [comment]
Hi! I have a very similar issue with **UITextView** when combined with **UIPageViewController** when using **IQKeybordManagerSwift**, and as stated above, the wired behaviour only happens with **Scroll** transition style. 

@hackiftekhar  I don't quite understand where should I add in this "exlicit check to not _UIQueingScrollView as UIScrollView.", would you mind sharing some hints?

Thanks so much in advance!

**Comment by hackiftekhar** [comment]
I mean I already added a check to determine _UIQueingScrollView (PageView ScrollView) and ignoring that, You don't need to do anything.

**Comment by bobintornado** [comment]
@hackiftekhar I see. But it seems when I using UITextView when combined with UIPageViewController (Scroll transition), IQKeybordManagerSwift still behaves strangely. :/ 

Just to clarify, both Swift and OC versions have been patched right?

**Comment by hackiftekhar** [comment]
I think both versions have been patched. But I need to check if you still getting buggy scroll transition.

**Comment by Marcopt98** [comment]
Never mind, the issue was on my side.
For someone that is facing the same issue with the same View hierarchy check if you're not changing the scroll view contentInset for any reason like zoom feature.
