### ISSUE TITLE
Next Buttons don't appear when added views with textViews inside programmatically

### ISSUE THREAD

**Issue by EugeneGoloboyar** [hackiftekhar/IQKeyboardManager#1140]
Hello, I've the question. 
If I add views from *xib programmatically with textView/textField do I need perform some additional steps to make IQKeyboardManager works?

I have the following view hierarchy for views with textField/textView: 
View (VC's 'root' view) - scrollView - containerView - containerView1 - > viewWithTextField1
View (VC's 'root' view) - scrollView - containerView - containerView2 - > viewWithTextView1
View (VC's 'root' view) - scrollView - containerView - containerView3 - > viewWithTextView2

so I have:
textField
textView1(scrolling is disabled for autogrowing)
textView2(scrolling is disabled for autogrowing)

I would rather use some simpler view structure or tableView but I have 2 "growing textViews".
So don't want to deal with tableView.

Currently I see that autoscrolling works fine, but I cannot find Next/Previous buttons in toolbar. 
My "autogrowing" textView behavior is based on updating its heightConstraint to intristicContentSize.size.height of the textView (scrolling is disabled for it) when text is changed.

Thanks if you'll find time to respond.

Edit:
I see that setting my containerView as subclass of IQPreviousNextView resolved my issue.

**Comment by yashvyas29** [comment]
@EugeneGoloboyar 
Set Class for your **container view** (View (VC's 'root' view) - scrollView - containerView) as **IQPreviousNextView** in Xib or Storyboard or if you are doing it programatically then use **IQPreviousNextView** instead of UIView for **container view**, you will get the **Next/Previous** buttons in toolbar.

**Comment by EugeneGoloboyar** [comment]
thanks, already got it)
