### ISSUE TITLE
iPhone unable to disable the weird magnifier coming on the UITextField

### ISSUE THREAD

**Issue by bharat117** [hackiftekhar/IQKeyboardManager#1143]
I'm trying to disable the magnifier appearing on the UITextField (even on a single tap on the UITextField getting the weird magnifier), I've tried many things like disabling the UILongPressGestureRecognizer with subclassing UITextField also but didn't solved the issue, kindly help.

![2017-11-21](https://user-images.githubusercontent.com/18686304/33091845-436d93f8-cf1e-11e7-913c-ae0efa656969.gif)

**Comment by hackiftekhar** [comment]
I don't know what might be the cause of issue. Can you please check again by removing my library, so we'll be sure it's due to my library or there are any other things causing issue.
