### ISSUE TITLE
IOS 11 textfield Issue

### ISSUE THREAD

**Issue by uditha2233** [hackiftekhar/IQKeyboardManager#1144]
I have the IQKeyboardManager version 5.0.6.  My view is like below. 

![img_0526](https://user-images.githubusercontent.com/9433043/33112768-e29b4112-cf7a-11e7-928d-613845cc76a6.PNG)

If I clicked on a textview for the firsttime, it works fine. See below image 

![img_0527](https://user-images.githubusercontent.com/9433043/33112882-88589afa-cf7b-11e7-9f90-f2281b4f2a09.PNG)

And then if I close the keyboard(by pressing done or return buttons) and click another textview, the textview isn't moving and the keyboarded covers the textview. see below image, 

![img_0529](https://user-images.githubusercontent.com/9433043/33112971-eabd54ba-cf7b-11e7-9f61-73aa15e31e68.PNG)

After that if I close the keyboard, my view is look like the below image,

![img_0530](https://user-images.githubusercontent.com/9433043/33113025-3449a2a0-cf7c-11e7-9623-d7b9312bceff.PNG)

This happens in my all the other similar views as well. But this happens only in IOS 11. I have tested this in a IOS 10 device and IQKeyboardManager worked perfectly.

Could You please tell me whats wrong here?

**Comment by alekye** [comment]
i have the same issue to you

**Comment by ZH3057** [comment]
I met the same issue too.

**Comment by uc-dpt** [comment]
I am also getting same issue. after appearing keyboard textfield not scrolling above keyboard  in IQKeyboardManager version 5.0.6.
![img_0144](https://user-images.githubusercontent.com/5267080/33539116-beed97c8-d8ea-11e7-9641-c41116d10216.jpg)
![img_0145](https://user-images.githubusercontent.com/5267080/33539167-fc2c47e2-d8ea-11e7-839f-911337cb8953.jpg)

**Comment by uditha2233** [comment]
Is there anyone who found a solution for this problem?

**Comment by hackiftekhar** [comment]
@uditha2233 @alekye @ZH3057 @uc-dpt can you please send me sample code to debug it?

**Comment by hackiftekhar** [comment]
It's fixed with new solution, changes are in `master` branch now. Please check and let me know if it doesn't work for you.

**Comment by uditha2233** [comment]
Sorry for late reply. I have installed the IQKeyboared newest version and now its working great again. Thank You so much. :)

**Comment by hackiftekhar** [comment]
My pleasure! v6.0.0 will be released around 13th April.
