### ISSUE TITLE
invisible Done btn

### ISSUE THREAD

**Issue by sazzad7002** [hackiftekhar/IQKeyboardManager#1146]
implement the done with the class but not display in development environment but display in a live environment. also, click event work in both environments. please help me the code was too old and develop by another developer. all condition working proper.
please help to resolve this issue.

**Comment by hackiftekhar** [comment]
Please update to latest version of library.

**Comment by KompoD** [comment]
@hackiftekhar it doesn't work :(

**Comment by KompoD** [comment]
It's WORK!
I just cleaned my project! :)

**Comment by sazzad7002** [comment]
in my code it is implement in obj c. library is to old.
