### ISSUE TITLE
Issues with Main Thread

### ISSUE THREAD

**Issue by ashishke2m** [hackiftekhar/IQKeyboardManager#1150]
Main Thread Checker: UI API called on a background thread: -[UIWindow rootViewController]
PID: 1978, TID: 67722, Thread name: (none), Queue name: NSOperationQueue 0x1c043a240 (QOS: UNSPECIFIED), QoS: 0
Backtrace:
4   IQKeyboardManagerSwift              0x0000000100d4fe50 _T0So8UIWindowC22IQKeyboardManagerSwiftE17topMostControllerSo06UIViewG0CSgyF + 36
5   IQKeyboardManagerSwift              0x0000000100d4ff88 _T0So8UIWindowC22IQKeyboardManagerSwiftE17topMostControllerSo06UIViewG0CSgyFTo + 56
6   IQKeyboardManagerSwift              0x0000000100d4ffd4 _T0So8UIWindowC22IQKeyboardManagerSwiftE21currentViewControllerSo06UIViewG0CSgyF + 40
7   IQKeyboardManagerSwift              0x0000000100d50398 _T0So8UIWindowC22IQKeyboardManagerSwiftE21currentViewControllerSo06UIViewG0CSgyFTo + 56
![screen shot 2017-11-23 at 2 39 35 pm](https://user-images.githubusercontent.com/16642068/33165192-e08fccda-d05b-11e7-9ffe-1c6ccd143722.png)

**Comment by hackiftekhar** [comment]
Can you please also show the Thead 37 call stack? It will help me to findout issue
