### ISSUE TITLE
IQKeyboardReturnHandler next button not working

### ISSUE THREAD

**Issue by godexsoft** [hackiftekhar/IQKeyboardManager#1151]
I have a simple form with textfields and I'm trying to make all but last field's keyboard return button to say "Next". As in the doc i create the instance variable and set it up with the controller. All good so far - the keyboard's return button changes to Next everywhere but last item. However, if you tap that next button the keyboard is dismissed instead of moving focus to the next field. In fact it does move focus to the next field but also hides the keyboard making it in effect do nothing. I was debugging the code and it correctly finds all siblings but it returns TRUE in the end:

 ```
open func textFieldShouldReturn(_ textField: UITextField) -> Bool {
        
        var shouldReturn = true

        if delegate == nil {
            
            // NEVER ENTERS BEYOND THIS LINE FOR ME
            if let unwrapDelegate = textFieldViewCachedInfo(textField)?[kIQTextFieldDelegate] as? UITextFieldDelegate {
                if unwrapDelegate.responds(to: #selector(UITextFieldDelegate.textFieldShouldReturn(_:))) {
                    shouldReturn = unwrapDelegate.textFieldShouldReturn?(textField) == true
                }
            }
        } // ELSE, PERHAPS USE DELEGATE's shouldReturn FUNCTION?

        if shouldReturn == true { // THIS COMES OUT AS ALWAYS TRUE
            goToNextResponderOrResign(textField)
            return true // THIS LINE DISMISSES THE KEYBOARD
        } else {
            return goToNextResponderOrResign(textField)
        }
    }

```

**Comment by godexsoft** [comment]
Anything regarding this issue? Thanks

**Comment by hackiftekhar** [comment]
Haven't looked at this yet.

**Comment by hackiftekhar** [comment]
Can you please also make a breakpoint to `goToNextResponderOrResign` and see what lines it execute @godexsoft ?

**Comment by godexsoft** [comment]
Sorry for the late response. 
It goes thru to 

`//Otherwise fetching all the siblings`

since `superConsideredView` is nil.

Then `textFields` got 4 values. And no sorting is applied so it falls out with a break from the default clause.

`index` is found to be 0 from the 4 possible textfields so this code is executed:

`
if index < (unwrappedTextFields.count - 1) {
    let nextTextField = unwrappedTextFields[index+1]
    nextTextField.becomeFirstResponder()
    return false
} // ...
`

Hope this helps.

**Comment by hackiftekhar** [comment]
Okay I'll try to understand now, thanks for the info.

**Comment by hackiftekhar** [comment]
Hmm, according to me, returning true shouldn't dismiss the keyboard because keyboard should be dismiss on calling `resignFirstResponder` or `view.endEditing(true)`. Can you please search these things and make breakpoints to them to know if you might be resigning keyboard somewhere using these methods?
