### ISSUE TITLE
Toolbar moving to Top

### ISSUE THREAD

**Issue by nthegedus** [hackiftekhar/IQKeyboardManager#1152]
I've a strange issue.

Sometimes, I don't know why, the Toolbar moves to top of my ViewController, and keyboard appears cropped.

![img_0030 1](https://user-images.githubusercontent.com/1063383/33211901-d3906e2a-d107-11e7-9ded-bb2b798421f0.PNG)

I'm using **pod 'IQKeyboardManagerSwift', '~> 5.0.6'**, Xcode 9.1.

It happens on iOS 11

**Comment by nthegedus** [comment]
I found the error

When the keyboard is opened, and the viewcontroller makes a push, pop, the keyboard hides normally.

But when I open the keyboard again, it opens like the screenshot above.

That was my solution, but it's not the best one

```
override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        self.view.endEditing(true)
}
```

Any ideias how to fix it?

**Comment by hackiftekhar** [comment]
It's the best solution @nthegedus because users reported that it happens if we don't dismiss keyboard before moving to another screen.
