### ISSUE TITLE
键盘完成按钮的问题

### ISSUE THREAD

**Issue by YoungBloodn** [hackiftekhar/IQKeyboardManager#1153]
我设置了全局的导航栏颜色为透明色，所以导致上面完成按钮不显示了，如何更改啊

**Comment by chaochaoboy** [comment]
我现在也遇到这个问题，iOS11上完成按钮显示不出来的问题

**Comment by polaris0227** [comment]
我也遇到一样问题。
谁知道如何解决这一问题？

**Comment by yimiaodaren** [comment]
不知道为啥完成按钮会消失。。

**Comment by melson-jao** [comment]
I have the same issue and update to v5.0.6 fix it in my case.

**Comment by dengsss** [comment]
我也遇到了，一大 bug 啊。有大神知道如何修复吗

**Comment by dengsss** [comment]
最新版本的框架作者已经修复这个 bug ，感谢作者！
