### ISSUE TITLE
TextField in CollectionViewCell moving out of window

### ISSUE THREAD

**Issue by ArturGasparyan** [hackiftekhar/IQKeyboardManager#1154]
Hi

I've been using this framework for a few months and it worked great so far. Currently I have a CollectionView with exactly one tile/cell (top left). Inside the tile/cell, there's a TextField. Tapping onto it reveals the Keyboard and IQKeyboardManager animates twice:

First the cell (and the TextField) is animated a little bit up. Then the tile is animated a second time (i.e. the CollectionView is scrolled) again up, but this time the whole cell/tile including the TextField is completely out of the window and not visible anymore!

I can scroll downwards to reveal the cell/tile again.

Here's the debug information, any help would be highly appreciated, thanks!

> IQKeyboardManager: ****** textFieldViewDidBeginEditing started ******
IQKeyboardManager: ****** addToolbarIfRequired() started ******
IQKeyboardManager: Found 1 responder sibling(s)
IQKeyboardManager: ****** addToolbarIfRequired() ended: 0.00107916665729135 seconds ******
IQKeyboardManager: Saving <<ABC.NavigationController: 0x105819a00> 0x0000000105819a00> beginning frame : (0.0, 0.0, 1112.0, 834.0)
IQKeyboardManager: ****** textFieldViewDidBeginEditing ended: 0.00167320831678808 seconds ******
IQKeyboardManager: UIKeyboard Size : (1112.0, 442.0)
IQKeyboardManager: ****** keyboardWillShow started ******
IQKeyboardManager: ****** adjustFrame() started ******
IQKeyboardManager: Need to move: -145.5
IQKeyboardManager: Saving <<UICollectionView: 0x104099600; frame = (0 0; 1112 734); clipsToBounds = YES; autoresize = W+H; gestureRecognizers = <NSArray: 0x1c0246660>; layer = <CALayer: 0x1c0225620>; contentOffset: {0, 0}; contentSize: {1112, 252.60815822002471}; adjustedContentInset: {0, 0, -884, 0}> collection view layout: <UICollectionViewFlowLayout: 0x103d3e6e0> 0x0000000104099600> contentInset : UIEdgeInsets(top: 0.0, left: 0.0, bottom: -884.0, right: 0.0) and contentOffset : (0.0, 0.0)
IQKeyboardManager: <<UICollectionView: 0x104099600; frame = (0 0; 1112 734); clipsToBounds = YES; autoresize = W+H; gestureRecognizers = <NSArray: 0x1c0246660>; layer = <CALayer: 0x1c0225620>; contentOffset: {0, 0}; contentSize: {1112, 252.60815822002471}; adjustedContentInset: {0, 0, -884, 0}> collection view layout: <UICollectionViewFlowLayout: 0x103d3e6e0> 0x0000000104099600> old ContentInset : UIEdgeInsets(top: 0.0, left: 0.0, bottom: -884.0, right: 0.0)
IQKeyboardManager: <<UICollectionView: 0x104099600; frame = (0 0; 1112 734); clipsToBounds = YES; autoresize = W+H; gestureRecognizers = <NSArray: 0x1c0246660>; layer = <CALayer: 0x1c0225620>; contentOffset: {0, 0}; contentSize: {1112, 252.60815822002471}; adjustedContentInset: {0, 0, 442, 0}> collection view layout: <UICollectionViewFlowLayout: 0x103d3e6e0> 0x0000000104099600> new ContentInset : UIEdgeInsets(top: 0.0, left: 0.0, bottom: 442.0, right: 0.0)
IQKeyboardManager: Moving Downward
IQKeyboardManager: Set Optional("<<ABC.NavigationController: 0x105819a00> 0x0000000105819a00>") frame to : (0.0, 0.0, 1112.0, 834.0)
IQKeyboardManager: ****** adjustFrame() ended: 0.00156908336794004 seconds ******
IQKeyboardManager: ****** keyboardWillShow ended: 0.0016419583116658 seconds ******
IQKeyboardManager: ****** keyboardDidShow started ******
IQKeyboardManager: ****** keyboardDidShow ended: 6.79583172313869e-05 seconds ******

**Comment by hackiftekhar** [comment]
Can you please provide some screenshots or sample code if you can. It would be great to debug the issue I think.
