### ISSUE TITLE
It always boken at one place when i run my project.  (Bug ID: #550) Have you met？

### ISSUE THREAD

**Issue by Xchn** [hackiftekhar/IQKeyboardManager#1155]
![jietu20171128-111439](https://user-images.githubusercontent.com/15793487/33300870-914aa20a-d42d-11e7-80cc-4cf35e73c0ac.jpg)

**Comment by Evwen** [comment]
I had the same problem, but I didn't know how to solve it. If it has been solved, please let us know. Thank you

**Comment by Evwen** [comment]
Finally, find the answer and set the global breakpoint for objc instead of all

**Comment by panduranga2016** [comment]
I am facing the same problem, I am getting an exception error stating that "use of undeclared identifier" let textField = UITextField(). can anyone  help me?

**Comment by ywwill** [comment]
I have solved my problem,the error is about xib file in my project, when I build UI with code, the error disappeared.
