### ISSUE TITLE
iOS 10 UISearchController searchBar in UITableView tableHeaderView gets offset to wrong position

### ISSUE THREAD

**Issue by xxtesaxx** [hackiftekhar/IQKeyboardManager#1156]
When using a UISearchController searchBar in a UITableViews tableHeaderView, once presenting the tableView gets offset to an odd position. When dismissing, the wrong position is kept which pushes the whole tableView up a little bit. The next time the search controller is presented it adds up that to a point where the search controller is completely hidden under the navigation bar. 

I attached a sample project to showcase the issue: 
[searchtest.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/1508668/searchtest.zip)

**Comment by hackiftekhar** [comment]
Thanks for the sample project @xxtesaxx, I'll check once I get some free time.

**Comment by hackiftekhar** [comment]
Looks like this issue get's fixed with latest changes.

**Comment by 964562398** [comment]
@hackiftekhar hi i got Problems with UISearchBar，I attached a 
sample project to showcase the issue:
[searchbartest.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/2097721/searchbartest.zip)

**Comment by 964562398** [comment]
@hackiftekhar 
如果键盘的高度低于搜索框的话是没问题的，但是一旦搜索框低于键盘的高度，就会出现问题，可以修改
位于ViewController中设置的高度，将高度改成比如500就不会有问题（这里使用的是iphonex）
[self.testcoll.view mas_makeConstraints:^(MASConstraintMaker *make) {
make.bottom.equalTo(weakself.view.mas_bottom);
make.left.equalTo(weakself.view.mas_left);
make.right.equalTo(weakself.view.mas_right);
make.height.equalTo(@300);
}];

If the height of the keyboard is lower than the search box, no problem, but once the search box is lower than the height of the keyboard, there will be problems that can be modified
The height set in the ViewController file, the height will be changed to 500, for example (iphonex is used here)
[self.testcoll.view mas_makeConstraints:^(MASConstraintMaker *make) {
         make.bottom.equalTo(weakself.view.mas_bottom);
         make.left.equalTo(weakself.view.mas_left);
         make.right.equalTo(weakself.view.mas_right);
         make.height.equalTo(@300);
     }];

**Comment by hackiftekhar** [comment]
I checked and found that you have a complex UI where you've placed your whole view inside a UICollectionViewCell. and when you scroll at last, the UICollectionViewCell get's scrolled and get it's y position in minus that's why it's happening. For complex hierarchy I always suggest to disable library in that particular controller and implement your own solution since library doesn't know much about your hierarchy configurations.
