### ISSUE TITLE
Exception on start

### ISSUE THREAD

**Issue by Jinzhengxuan** [hackiftekhar/IQKeyboardManager#1159]
pod 'IQKeyboardManager', '~> 5.0.6'
I use  IQKeyboardManager but exception happen(not crashed)
            {
                UITextField *view = [[UITextField alloc] init];//exception at init function 
                [view addDoneOnKeyboardWithTarget:nil action:nil];
                [view addPreviousNextDoneOnKeyboardWithTarget:nil previousAction:nil nextAction:nil doneAction:nil];
            }

**Comment by kushankjain13** [comment]
Even I have this issue. This is causing problems on iPad 
https://stackoverflow.com/questions/46740204/what-causes-ios-11-ipad-recent-apps-dock-icon-to-be-grayed-out

Did you find any solution?

**Comment by hackiftekhar** [comment]
I also got this issue sometime but I'm not sure why this issue happens.

**Comment by Spetruk** [comment]
1. remove *.workspace file
2. run pod install
3. profit

**Comment by kushankjain13** [comment]
@Spetruk - did not work. I still hit the exception breakpoint on launching from Xcode. I don't have any crash, if I click on run again then it works normally.

**Comment by InjoyDeng** [comment]
@Spetruk It work for me. thanks

**Comment by Jinzhengxuan** [comment]
@Spetruk It works.many thanks.

**Comment by InjoyDeng** [comment]
The reason is because of the addition of a global breakpoint, deactivate breakpoints to work.
