### ISSUE TITLE
51 errors after pod installation

### ISSUE THREAD

**Issue by lbartekl** [hackiftekhar/IQKeyboardManager#1160]
I just installed pod file with : `pod 'IQKeyboardManagerSwift'`
in my swift4 project and I am getting 51 mostly similar errors like:

> Argument of '#selector' refers to instance method 'refreshPlaceholder()' that is not exposed to Objective-C

> 'init(colorLiteralRed:green:blue:alpha:)' is unavailable: This initializer is only meant to be used by color literals

> Ambiguous use of 'topMostController()'

Any any ideas, what I did wrong..?

**Comment by daurenm** [comment]
As far as I know, the pod is not ready for swift4. If you're in a hurry, you can rewrite those 51 lines yourself, it's easy.

**Comment by hackiftekhar** [comment]
@lbartekl @daurenm pod is compatible for swift3, swift 3.2 and swift 4.0. Looks like you aren't using updated pods. Current latest version if v5.0.7.
