### ISSUE TITLE
Hide keyboard cause a problem with my UI. 

### ISSUE THREAD

**Issue by GokmenAkar** [hackiftekhar/IQKeyboardManager#1166]
Is anybody know why my view is cover by the status bar after I hide the keyboard? 
Actually, first 2 attempts work well, but I don't why the third attempt makes buggy view. I have a complex view, and after the third hide, my view goes up and status bar covers it. 

Have you any idea? thank you.

**Comment by iadxworld** [comment]
Yeah! I have the similar issue. The only difference is my view goes downwards out of the screen frame on dismissing the keyboard. Any fixes for this?

**Comment by GokmenAkar** [comment]
@iadxworld i fixed the problem by giving value to topanchor programmatically. 
if it is iphone x, constant is 40 else 20. I hope it works.

**Comment by iadxworld** [comment]
@GokmenAkar Great! I'll try that! Thanks for the prompt response mate!

**Comment by zhenLuoxiaoming** [comment]
@GokmenAkar I have the same problem,but I don't understand how to deal the question, can you show me the code . thanks a lot .

**Comment by TeddyCodeDev** [comment]
I believe I'm running into the same issue but mine is leaving my tableView background overlaid over the status bar after dismissal.

![simulator screen shot - iphone x - 2017-12-21 at 08 32 49](https://user-images.githubusercontent.com/30362527/34262425-9b5d08a6-e629-11e7-9893-423913b212bf.png)
![simulator screen shot - iphone x - 2017-12-21 at 08 33 04](https://user-images.githubusercontent.com/30362527/34262426-9b6cbdd2-e629-11e7-870a-f1a2d983705d.png)
![simulator screen shot - iphone x - 2017-12-21 at 08 33 08](https://user-images.githubusercontent.com/30362527/34262427-9b7afcbc-e629-11e7-9308-a467dbe08771.png)

**Comment by chonex143** [comment]
Add this code in AppDelegate
 `IQKeyboardManager.shared().canAdjustAdditionalSafeAreaInsets = true`

same issue that i encounter but it fix after adding that code.

**Comment by wangrui460** [comment]
IQKeyboardManager.shared().canAdjustAdditionalSafeAreaInsets = true 

this code can solve the problem, but i think the reason is IQKeyboard changed _UIBarBackground frame sometimes（i printed it），so, if IQKeyboard can solve this problem, we don't need to write up code，especially for novice!

**Comment by hackiftekhar** [comment]
Can you guys share any demo project to debug this issue?

**Comment by hackiftekhar** [comment]
It's fixed with new solution, changes are in `master` branch now. Please check and let me know if it doesn't work for you.
