### ISSUE TITLE
Toolbar is incorrect in iOS 11

### ISSUE THREAD

**Issue by cs-joao-souza** [hackiftekhar/IQKeyboardManager#1167]
I cannot see any of the toolbar button in iOS 11.

Do i need to do something?

**Comment by IMHitesh** [comment]
Facing same issue. 
Any solution...

**Comment by hackiftekhar** [comment]
You need to update pods to latest version, it's 5.0.7 now.

**Comment by ashish-naik** [comment]
Doesnt work for me though i am on 5.0.7

**Comment by joaopedrok** [comment]
It doesnt work for me either. On simulator it doesn't appear.

**Comment by joaopedrok** [comment]
I updates to version 5.0.7 and it worked but there were some modifications that i was not predicting.

**Comment by ashish-naik** [comment]
@hackiftekhar I downloaded the demo and i can see up/down toolbar buttons when i run it. 

However, I am using latest version in my project but up/down toolbar buttons do not appear.

i am checking on simulator and device running  iOS 11.2.5 .

**Comment by ashish-naik** [comment]
@hackiftekhar All my text fields are embedded in stack views. Is that the reason? 

I have another view controller where next/previous buttons show clearly in black color in iOS 10 but appear white in color on iOS 11.

so i suspect stack views. do you have any solution?

How do i solve white color issue on iOS 11?

Thanks
Ashish

**Comment by ashish-naik** [comment]
@hackiftekhar I confirm that stack view is causing issue. 

I added two text fields and didnt embed them in stack view. Next/previous toolbar buttons appear when i tap into these fields.

Is there a solution to this?

I use Chameleon framework so setting toolbarBarTintColor removes white color problem in view that does not have stack view. But "Done" button remain in black. It does not become white.
is there a way to control Done button's tint?

Thanks
Ashish

**Comment by ashish-naik** [comment]
@hackiftekhar yes I checked those properties. 

What about issue with stack views?
