### ISSUE TITLE
Error: 'shared' is unavailable: Use view controller based solutions where appropriate instead.

### ISSUE THREAD

**Issue by luai-kalkatawi** [hackiftekhar/IQKeyboardManager#1168]
I am getting this issue after adding an extension in the pod file.

  target 'OneSignalNotificationServiceExtension' do
      pod 'OneSignal', '>= 2.5.2', '< 3.0'
  end

My Error

> "Error: 'shared' is unavailable: Use view controller based solutions where appropriate instead."

`                    UIApplication.shared.sendAction(barButton.invocation.action!, to: barButton.invocation.target, from: textFieldRetain, for: UIEvent())
`

So please where would be my problem?

Using Swift 4 Xcode 9.1

**Comment by hackiftekhar** [comment]
Can you please check this https://stackoverflow.com/a/34227172/1582217

**Comment by mitulmarsonia** [comment]
I have try given solution but still getting same issue in Swift 5 and xcode 11.1 can you help me out.
