### ISSUE TITLE
Next Buttons Not Appearing On Texfeilds

### ISSUE THREAD

**Issue by HenryGoodwin** [hackiftekhar/IQKeyboardManager#1169]
When i select a textfield i can only see the done button but not the next buttons (arrow button). See Image

![img_4793](https://user-images.githubusercontent.com/16816813/33616065-812fdb4c-da27-11e7-89b9-a6dae9d86f19.PNG)

**Comment by burkaslarry** [comment]
I also find no placeholder text and arrow buttons are present.

**Comment by HenryGoodwin** [comment]
It is embedded in a stackView within a stackView

**Comment by melson-jao** [comment]
I have the same issue and update to v5.0.6 fix it in my case.

**Comment by dk53** [comment]
You should try to add this to your IQKeyboardConfiguration : 

`IQKeyboardManager.shared().toolbarPreviousNextAllowedClasses.add(UIStackView.self)`

**Comment by jap99** [comment]
Hey guys, which file is the code for the IQKeyboardConfiguration that we should add that code to?

**Comment by abdurrahmansanli** [comment]
**Please add solution of dk53 to known issues and to Description 'How to enable custom fields'.**

**Comment by ashish-naik** [comment]
@dk53 I added your suggestion to AppDelegate but didn't work. 

@HenryGoodwin I am also observing this with stack views. Were you able to solve?

**Comment by viratStudyData** [comment]
i had same issue so i give class 'IQPreviousNextView' for the view in which i added textField
