### ISSUE TITLE
Disabling IQKeyboardManager in specific View Controller.

### ISSUE THREAD

**Issue by rhenz** [hackiftekhar/IQKeyboardManager#117]
Hi @hackiftekhar ,

I'm having a weird problem here. 

The IQKeyboardManager doesn't seem to get turn off? No idea why.

What I did is import IQKeyboardManager. In viewDidAppear i have this:

_wasKeyboardManagerEnabled = [[IQKeyboardManager sharedManager] isEnabled];
    [[IQKeyboardManager sharedManager] setEnable:NO];

Then in viewWillDisappear
[[IQKeyboardManager sharedManager] setEnable:_wasKeyboardManagerEnabled];

But upon testing the keyboardManager still exist in that viewController.

**Comment by karthikasdas** [comment]
Hi @hackiftekhar ,

First of all Thank you very much for this library. 

I have an issue of disabling IQKeyboard in particular view controller, I am using swift and used the following code:- IQKeyboardManager.sharedManager().disableInViewControllerClass(CircleTableViewController)
where CircleTableViewController is the class in which IQKeyboard is to be disabled.

Thanks,
Karthika
