### ISSUE TITLE
Status bar and Keyboard zoomed

### ISSUE THREAD

**Issue by narendargit** [hackiftekhar/IQKeyboardManager#1170]
Hi,  I'm using latest IQKeyboardManager in xcode 9.1, but my application was getting zoomed like status bar, keyboard with big font.. can u help me ..

<img width="377" alt="screen shot 2017-12-06 at 10 11 07 am" src="https://user-images.githubusercontent.com/21238943/33644940-24364772-da6e-11e7-8a35-d9e97b5e2a8c.png">
<img width="377" alt="screen shot 2017-12-06 at 10 11 41 am" src="https://user-images.githubusercontent.com/21238943/33644941-2461224e-da6e-11e7-8b07-a210e1a4c1f5.png">

**Comment by hackiftekhar** [comment]
You've to provide correct launch images or you have to use launch storyboard. Please try if that solve this problem. btw this issue isn't related to this library.
