### ISSUE TITLE
Not scrolling in UITableViewController with Static Cells

### ISSUE THREAD

**Issue by WillBoland** [hackiftekhar/IQKeyboardManager#1171]
It will not scroll to show the text field if the keyboard covers the text field in a UITableViewController with static cells. I've looked at apples documentation you provide that says they handle it; however, it also says we have to manually handle scrolling with text fields in a UITableViewController with static cells.

**Comment by WillBoland** [comment]
Fixed it! I commented out `disabledDistanceHandlingClasses.append(UITableViewController.self)`
Leaving this here incase anyone else had this issue.

**Comment by hackiftekhar** [comment]
You might be not calling super.viewWillAppear in your UITableViewController. Actually UITableViewController has it's own mechanism to handle textField and keyboard that's why library is disabled to handle UITableViewController.
