### ISSUE TITLE
key board not goes down on chat view example , also tabbar goes invisible

### ISSUE THREAD

**Issue by kiranravi190** [hackiftekhar/IQKeyboardManager#1172]
I have tried with a demo on chat screen , it makes come fluctuated view to top and down
![simulator screen shot - iphone 7 - 2017-12-09 at 12 22 20](https://user-images.githubusercontent.com/12912263/33793320-f639be24-dcdb-11e7-867e-adb969775418.png)

**Comment by hackiftekhar** [comment]
It's a basic demo app and it might differ from project to project. If you would like to dismiss then you could do some more coding to do it. But I implemented it for a basic level for tutorial only.
