### ISSUE TITLE
I have my textfield place in a UIView, and my textfield won't be moved up automatically 

### ISSUE THREAD

**Issue by junweimah** [hackiftekhar/IQKeyboardManager#1173]
Due to my app UI design, my textfields have to be placed inside of a UIView, something like this 

![image](https://user-images.githubusercontent.com/21700014/33866225-4bfa69fc-df30-11e7-8c33-d3bf969b217e.png)

This is how the storyboard looks like: 

![image](https://user-images.githubusercontent.com/21700014/33866243-61371a54-df30-11e7-9123-5bfdb96f1067.png)

But I have tried to drag a new textfield out, without placing it in a UIView, and it works, the keyboard is not blocking the textfield.

How do I fix this?

**Comment by junweimah** [comment]
According to [this ticket](https://github.com/hackiftekhar/IQKeyboardManager/issues/1140)
I have tried setting the outer most view class to : IQPreviousNextView 

something like this: 
![image](https://user-images.githubusercontent.com/21700014/33866508-08a19f66-df32-11e7-91c4-30c79758c3fa.png)

Now for my textfields, I can see the arrows to move to next textfield, but the keyboard is still blocking the textfieds

Anyone has any idea?

**Comment by hackiftekhar** [comment]
There might be one reason which is some constraint pinned with top or bottom layout guide.

**Comment by meet2011** [comment]
I have scrollview->containerview->textfield. Here only containerview class should be set `IQPreviousNextView`. What should be module name in objective C for class `IQPreviousNextView`. I tried with containerview as `IQPreviousNextView` but it doesn't work. I can see done button but not arrow. 

FYI, arrows are visible in other screen but not on this view.

**Comment by hackiftekhar** [comment]
Arrows will be visible if library determine that you can navigate between other textFields, otherwise if library doesn't get any clue then next/previous button will not be visible. If you put IQPreviousNextView as container then all inner textFields should be navigable using next/previous buttons.

**Comment by hackiftekhar** [comment]
@junweimah @meet2011 can you guys please try latest master version, it contains logical changes which should fix these kind of issues.
