### ISSUE TITLE
New version (tag)

### ISSUE THREAD

**Issue by igor9silva** [hackiftekhar/IQKeyboardManager#1175]
Hi @hackiftekhar, 

Could you please create a new release version (i.e. git tag)?

The latest tag (5.0.6) doesn't contain the fixes from Nov 20, like https://github.com/hackiftekhar/IQKeyboardManager/commit/6ae7bbde526c0d599889f29eb6ebb1ce15de4a54 so Xcode complains about deprecated code.

Thanks in advance!

**Comment by hackiftekhar** [comment]
Released v5.0.7. Cheers!
