### ISSUE TITLE
i want to using  IQLayoutGuideConstraint  with snapkit.

### ISSUE THREAD

**Issue by choiks14** [hackiftekhar/IQKeyboardManager#1178]
i want to using  IQLayoutGuideConstraint  with snapkit.

how can i?

**Comment by hackiftekhar** [comment]
You don't need to use IQLayoutGuideConstraint with snapkit because IQLayoutGuideConstraint should be mapped by the developer of the project and it's only a reference to a contraint in storyboard. You could map that constraint to your viewcontroller and can use with snapkit.
