### ISSUE TITLE
IQKeyboardManager memory warning ? 

### ISSUE THREAD

**Issue by xiaohuaiOS** [hackiftekhar/IQKeyboardManager#1180]
When I use IQKeyboardManager? View memory as the following memory diagram, why IQKeyboardManager related to create so many class
![1513328122885](https://user-images.githubusercontent.com/17583445/34034285-c718dfd0-e1b8-11e7-9b88-8452170360c8.jpg)

**Comment by xiaohuaiOS** [comment]
当我使用IQKeyboardManager 的时候，使用 xcode 查看内存图，为什么会创建这么多个？ 
![1513328122885](https://user-images.githubusercontent.com/17583445/34034323-ed47bef6-e1b8-11e7-9b69-e381534abd9d.jpg)

**Comment by hackiftekhar** [comment]
I'll try to check the memory issues having with these, so that I can fix these memory issues.

**Comment by hshd123** [comment]
thank you !

**Comment by hackiftekhar** [comment]
Most of the issues has been addressed with latest version
