### ISSUE TITLE
IQKeyboard的下一个按钮 和 textfieldshoubeginediting 不允许返回NO

### ISSUE THREAD

**Issue by smallHouseBrother** [hackiftekhar/IQKeyboardManager#1181]
比如我有五个textfield，每个都有delegate，第三个textfieldshoubeginediting  弹个弹窗然后返回NO，其余的返回YES可输入，但是当光标在第二个时点击IQKeyboard的下一个时，弹框也弹出来了，键盘收不回去，光标停留在第二个，一直点击下一个就会一直加弹窗，光标一直停留在第二个  ？

**Comment by hackiftekhar** [comment]
This issue has already been fixed. Please update to latest version of library.
