### ISSUE TITLE
 Deployment target is iOS11 for v5.0.7 release

### ISSUE THREAD

**Issue by tola** [hackiftekhar/IQKeyboardManager#1182]
I had to reverted back to v5.0.6 this morning after I learned that minimum deployment target of v5.0.7  is iOS11.

May I know the reason why bumped in the minimum deployment target to iOS11?

**Comment by schayes04** [comment]
What is giving you this message? This doesn't seem to be true. I am using IQKeyboardManager v5.0.7 on iOS 10 just fine

**Comment by tola** [comment]
My project target is iOS9 and above. When I included this library v5.07 in
the project and using the import statement the Xcode gave the complaint
saying the "the minimum requirement of IQKeyboardManager  is iOS11". So, I
removed it and used 5.0.6 instead and there is no more complaints from
Xcode.

**Comment by schayes04** [comment]
Are you using the Objective C version or the Swift one? This may be the difference

**Comment by tola** [comment]
I'm using Swift.

**Comment by schayes04** [comment]
Hmm looks like it's a Carthage issue instead #1186
