### ISSUE TITLE
2个问题望解答一下

### ISSUE THREAD

**Issue by aimm** [hackiftekhar/IQKeyboardManager#1183]
1.
UICollectionViewFlowLayout *layout = [UICollectionViewFlowLayout new];
layout.scrollDirection = UICollectionViewScrollDirectionHorizontal;
here is the code,and the result is that the colleciton view cell did not get back to its original content offset by y point.
2.
i have set a UITextField 's borderStyle as UITextBorderStyleRoundedRect,then when i tap next button on the toolbar the textfield 's text moved up and down while UITextBorderStyleNone wont.
hope you can understand ! 
1.我设置collectionview为横向滚动，然后cell有输入框，在结束编辑后不会回到原始的Y偏移量
2.当一个输入框的边框样式设置为圆角的时候，输入内容后点击工具条上的下一项按钮，输入框里的内容会跳动一下

**Comment by hackiftekhar** [comment]
1. You have to set `shouldRestoreScrollViewContentOffset` to YES for that particular scrollView (CollectionView in your case).
2. This issue looks to be fix with latest changes. Please take a look at master branch.

**Comment by Raymon1992** [comment]
I have same question.And set shouldRestoreScrollViewContentOffset to YES does not work.I listen for the notifications UIKeyboardWillShowNotification and UIKeyboardWillHideNotification to set CollectionView's scrollEnable it work.But appear a new question,if the navigationController is User-defined,when the keyboard appear,the total view upraise.

**Comment by hackiftekhar** [comment]
Sorry, I didn't understand the question correctly @Raymon1992. Can you please rephrase?
