### ISSUE TITLE
Different behaviour for toolbar on keyboard for iOS 10 & iOS 11

### ISSUE THREAD

**Issue by MaddyRockz2** [hackiftekhar/IQKeyboardManager#1184]
I have found different behaviour for toolbar in keyboard on same screen for iOS 10 & iOS 11, please refer the below screenshot.

Code used to change color:-
> UIBarButtonItem.appearance().setTitleTextAttributes([NSAttributedStringKey.foregroundColor : UIColor.orange, NSAttributedStringKey.font : UIFont.primaryTextFont], for: UIControlState())
        UIBarButtonItem.appearance().setTitleTextAttributes([NSAttributedStringKey.foregroundColor : UIColor.orange, NSAttributedStringKey.font : UIFont.primaryTextFont], for: .highlighted)

Issue:- Toolbar button color is not changing in iOS 10

**Comment by MaddyRockz2** [comment]
![screen shot 2017-12-19 at 1 48 09 pm](https://user-images.githubusercontent.com/34674986/34147627-65939872-e4c4-11e7-9014-84cc826118c6.png)

**Comment by MahipalV12** [comment]
update the pod version : pod 'IQKeyboardManagerSwift’,’~> 5.0.0’

**Comment by hackiftekhar** [comment]
@ MaddyRockz2 can you please share demo project?
