### ISSUE TITLE
电池状态栏变成黑色

### ISSUE THREAD

**Issue by xxalan** [hackiftekhar/IQKeyboardManager#1189]
关于键盘隐藏的问题, 当我弹出键盘, 输入框上移, 消失, 如此反复三次, 然后电池状态栏就会变成黑色

**Comment by deskOfDafa** [comment]
https://github.com/hackiftekhar/IQKeyboardManager/issues/1158 参看我的回答

**Comment by MemoBook** [comment]
试试self.navigationController.view.backgroundColor = [UIColor whiteColor]; 
将顶层控制器的view设置为白色 遮挡一下后面的黑色。
我的问题就是这么解决的。
或许控制器层级顺序不一样。但道理一样的

**Comment by xxalan** [comment]
@MemoBook 非常感谢你的回答, 尝试了一下, 问题没有解决, 只是你导航栏背景颜色就是白色的, 所以可能看不出来 #1158 里面有解决方案

**Comment by hackiftekhar** [comment]
It's fixed with new solution, changes are in `master` branch now. Please check and let me know if it doesn't work for you.
