### ISSUE TITLE
状态栏变透明了

### ISSUE THREAD

**Issue by liangqing1028** [hackiftekhar/IQKeyboardManager#1190]

**Comment by wickey-w** [comment]
Add this code in AppDelegate
IQKeyboardManager.shared().canAdjustAdditionalSafeAreaInsets = true

same issue that i encounter but it fix after adding that code.

**Comment by rdaneshvar95** [comment]
It says "Type 'IQKeyboardManager' has no member 'shared'" and after I change shared() to sharedManager() it says "Value of type 'IQKeyboardManager' has no member 'canAdjustAdditionalSafeAreaInsets'"
@wickey-w

**Comment by rdaneshvar95** [comment]
Thanks a lot
Great solution!
@wickey-w

**Comment by 9SumeetMourya** [comment]
I update the cocoa pod 'IQKeyboardManagerSwift'  (5.0.3)
But could not get canAdjustAdditionalSafeAreaInsets in the current version.

**Comment by wickey-w** [comment]
Please update your version to 5.0.6

**Comment by vahids** [comment]
It has some issue on `UITextView`

**Comment by hackiftekhar** [comment]
It's fixed with new solution, changes are in `master` branch now. Please check and let me know if it doesn't work for you.

**Comment by vahids** [comment]
Master branch fixed issue for me, without `IQKeyboardManager.shared().canAdjustAdditionalSafeAreaInsets = true`
Thanks.

**Comment by AnilkumarRabhasa** [comment]
Still, I am facing this issue in iOS 11.3 and   pod 'IQKeyboardManagerSwift', '6.0.2'
Any suggestions?

**Comment by Prithvi30** [comment]
I'm facing the same issue 

IQKeyboardManager.shared().canAdjustAdditionalSafeAreaInsets = true

canAdjustAdditionalSafeAreaInsets is deprecated.

**Comment by hackiftekhar** [comment]
Canyou please share demo project @Prithvi30?

**Comment by iHarshil** [comment]
Do not set your textfield as firstResponder in your viewController.

For ex:- (in ViewDidLoad Method)
[self.yourTextField becomeFirstResponder];

if you have above set up. Please comment this and then try. All the best.

**Comment by malkabani** [comment]
IQKeyboardManager.shared().layoutIfNeededOnUpdate = true

Thanks for https://github.com/nobird
