### ISSUE TITLE
textview add in keyWindow, not work 

### ISSUE THREAD

**Issue by fanhoucheng** [hackiftekhar/IQKeyboardManager#1191]
Same as #1082 
textview add in keyWindow, not work 

BUT:
The viewcontroller will be push up!

Step:
1.show my viewcontroller1
2.click a button on viewcontroller1 and show a custom view with textview in current keyWindow 
3.when textview got focus,viewcontroller1 will be push up, but textview not work

**Comment by hackiftekhar** [comment]
If a textView or textField is directly part of UIWindow then it doesn't work. It's a limitation of library.
