### ISSUE TITLE
Module Not Building

### ISSUE THREAD

**Issue by mechmatt01** [hackiftekhar/IQKeyboardManager#1193]
I am using IQKeyboardManager 5.0.6 and when trying to build it for iOS 11 using Xcode 9 Swift 4 it says no such module exists in the app delegate. I have tried to a build, clean and quit of Xcode as well as cleared my derived data and it still does not work. Anyone have any suggestions?

**Comment by hackiftekhar** [comment]
I think that solution should work. Not sure why it isn't working.
