### ISSUE TITLE
Not Working with UIWindow

### ISSUE THREAD

**Issue by vickysahujpr** [hackiftekhar/IQKeyboardManager#1197]
I addsubview a UIView (It Contains a UITextField) on UIWindow and show this Window object over UIViewController. The issue become when I clicked on TextField, the keyboard open and the frame is not going up with keyboard.

But If I disrectly addsubview this view over UIViewController without using UIWindow, It Works !!!

________________________________________________________________________
CODE -

medicalPopupView contians a UITextField.

 loadingWindow = [[UIWindow alloc] initWithFrame:[[UIScreen mainScreen] bounds]];
 loadingWindow.windowLevel = UIWindowLevelStatusBar;
 loadingWindow.backgroundColor = [UIColor clearColor];
 [loadingWindow makeKeyAndVisible];
 loadingWindow.hidden = false;
 [self.view addSubview:medicationPopupView];

In that case IQKEYBOARD NOT WORKING

________________________________________________________________________

But In this Case -

[self.view addSubview:medicationPopupView];

It's Working.
________________________________________________________________________

Help me why it is not working with UIWindow.

Thanks !!! :)

**Comment by hackiftekhar** [comment]
If a textField or textView is directly added to UIWindow then it will not work, it's a limitation of library.

**Comment by wei3715** [comment]
现在问题解决了吗

**Comment by vickysahujpr** [comment]
So how to work with this library if I am using a UITextField over UIWindow -> UIView -> UITextField

Please Provide solution

**Comment by hackiftekhar** [comment]
There is no easy solution for now. You have to add it to a UIViewController's view and UIViewController should be in UIWindow hierarchy.

**Comment by IMHitesh** [comment]
Use below patch it will work.


Just create dummy window and viewcontroller for add new view and present it.

  let alertWindow = UIWindow(frame: UIScreen.main.bounds)
            alertWindow.rootViewController = UIViewController()
            alertWindow.windowLevel = UIWindowLevelAlert + 1
            alertWindow.makeKeyAndVisible()
            alertWindow.rootViewController?.present(popUpVC, animated: false)

**Comment by hackiftekhar** [comment]
Yup, that will work since the viewController is part of a UIWindow (Not directly working with UIWindow).
