### ISSUE TITLE
Not working with [[IQKeyboardManager sharedManager] setEnable:NO]

### ISSUE THREAD

**Issue by CBL0123** [hackiftekhar/IQKeyboardManager#1198]
how disable IQKeyboardManager in one  viewcontroller , [[IQKeyboardManager sharedManager] setEnable:NO]; not working

**Comment by czwpro** [comment]
+1

**Comment by hackiftekhar** [comment]
You can register your viewController with `disabledDistanceHandlingClasses` to disable for particular ViewController.
