### ISSUE TITLE
Top text field not visible when in landscape

### ISSUE THREAD

**Issue by Deadpikle** [hackiftekhar/IQKeyboardManager#120]
Hi,

I am showing the user a view with 4 different text fields in it. The next/previous buttons work just fine, but if you put the simulator in landscape, select the top text field, and then go down (hit next) a few times and then back up to the first text field using the next/previous buttons, the top field will only be partially in the screen. This happens in both iOS 7.1 and 8.1. It might be a side effect of having the view set to UIScrollView in the storyboard so that the navigation controller is still shown.

In the following image, the user currently has the top field selected, but it isn't being shown properly.

![ios simulator screen shot nov 23 2014 4 06 23 pm](https://cloud.githubusercontent.com/assets/5092399/5159228/ce30a226-732a-11e4-8b56-1d47c6f981c2.png)
#115's fix may help out here so that the user can manually scroll the page up if the field is hidden. Could the issue be that my text field is simply too close to my other text fields and/or it is too high on the page?

**Comment by maulikpat** [comment]
@hackiftekhar I am facing this same issue in iOS 9.3

**Comment by trupin** [comment]
@hackiftekhar I'm also facing this issue on iOS 9.3 on iPad in landscape mode

**Comment by hackiftekhar** [comment]
Can you guys share a demo?
