### ISSUE TITLE
Items constrained to bottom Safe Area get cut off when keyboard appears

### ISSUE THREAD

**Issue by ETGgames** [hackiftekhar/IQKeyboardManager#1200]
<img width="278" alt="screen shot 2017-12-29 at 01 37 15" src="https://user-images.githubusercontent.com/13756744/34427306-eb00c6b2-ec38-11e7-8f39-3df4c95b8db6.png">

As you can see, the background rises halfway up the keyboard and the text field is half cut off. This happens every 2nd time you bring up the keyboard.

**Comment by hackiftekhar** [comment]
It's fixed with new solution, changes are in `master` branch now. Please check and let me know if it doesn't work for you.
