### ISSUE TITLE
使用IQKeyboardManager，使textField成为第一响应者，键盘不弹出。但是在这个控制器中禁用IQkeyboardManager，键盘就可以弹出。

### ISSUE THREAD

**Issue by Helihua1992** [hackiftekhar/IQKeyboardManager#1201]

**Comment by hackiftekhar** [comment]
It's a simulator implementation, we have to enable soft keyboard from simulator menu. However still keyboard doesn't show then still it's not related to IQKeyboardManager since showing keyboard is managed by iOS.
