### ISSUE TITLE
Doesn't work in UITableview

### ISSUE THREAD

**Issue by abdouoi** [hackiftekhar/IQKeyboardManager#1202]

**Comment by hackiftekhar** [comment]
Please provide more info.

**Comment by abdouoi** [comment]
I have a tableView with some textViews. When I tap in a textView, the keyboard still covers the view.

**Comment by hackiftekhar** [comment]
Are you using UITableViewController?

**Comment by abdouoi** [comment]
Yes

**Comment by hackiftekhar** [comment]
Then can you please make sure you did a super call with viewWillAppear and other life cycle methods you overrided?

**Comment by abdouoi** [comment]
In viewWillAppear I forgot to put the super call. After adding it, everything working and running smooth as butter! Thanks
