### ISSUE TITLE
Crash on iPhone6s Plus(iOS 10.3.3) when textfield begin focused. additionalSafeAreaInsets unrecognized selector sent to instance

### ISSUE THREAD

**Issue by ladmini** [hackiftekhar/IQKeyboardManager#1205]
Hello, 
Thank you very much for bringing me such an amazing library. I used it in many projects, and it works very well.  But recently I met a very unbelievable problem. When I tap a textfield in my app,  it crashed. I try to debug and found it crashed as following

<img width="1005" alt="123" src="https://user-images.githubusercontent.com/5718706/34453272-a99c8db6-ed8a-11e7-917c-eea798df3b47.png">

My iPhone is 6S Plus and system version is iOS 10.3.3, I was included it through Carthage. (github "hackiftekhar/IQKeyboardManager"). I don't know why, I may need your help.

 Thank you very much.

**Comment by hackiftekhar** [comment]
Oops, not sure how the validation has passed because it's returning false in your debugging command but `if` condition passed.

**Comment by ArchieR7** [comment]
My project got same issue with all iOS 10 series versions.

**Comment by Meojr** [comment]
using Cocopod instead of Carthage solves my problem

**Comment by hackiftekhar** [comment]
Honestly I don't know. I can say library validations are correct. But not sure why validation get's passed.
