### ISSUE TITLE
Toolbar can't hidden in the webView  when I set IQKeyboardManager.enable is NO

### ISSUE THREAD

**Issue by luotengotos** [hackiftekhar/IQKeyboardManager#1207]
I write the following code in the method named viewWillAppear.

    [IQKeyboardManager sharedManager].enableAutoToolbar = NO;
    [IQKeyboardManager sharedManager].enable = NO;

but toolBar is also display when textField of html begin editing and keyboard did show. and toolBar cover the textField of html the first time.

And, Console print too many error message about constraint config.

    
    Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
    (
	    <NSAutoresizingMaskLayoutConstraint:0x13bbd0860 _UIToolbarContentView:0x137dea5b0.width == UIToolbar:0x13b95dda0.width>,
	    <NSLayoutConstraint:0x13b968f40 _UIButtonBarStackView:0x13b9627f0.leading == _UIToolbarContentView:0x137dea5b0.leading + 8>,
	    <NSLayoutConstraint:0x13b969090 _UIButtonBarStackView:0x13b9627f0.trailing == _UIToolbarContentView:0x137dea5b0.trailing>,
	    <NSLayoutConstraint:0x13bbb6170 _UIModernBarButton:0x13bc1cfa0.leading >= _UIButtonBarButton:0x13bc1c7e0.leading + 5>,
	    <NSLayoutConstraint:0x13b108da0 _UIButtonBarButton:0x13bc1c7e0.trailing >= _UIModernBarButton:0x13bc1cfa0.trailing + 5>,
	<NSLayoutConstraint:0x13bc1d980 _UIModernBarButton:0x13bbc57c0.leading == _UIButtonBarButton:0x13bbc4e00.leading + 8>,
	<NSLayoutConstraint:0x13bc1db00 _UIButtonBarButton:0x13bbc4e00.trailing == _UIModernBarButton:0x13bbc57c0.trailing + 8>,
	<NSLayoutConstraint:0x13bbcbf70 UILayoutGuide:0x13b963710.leading == _UIButtonBarButton:0x13bc17900.leading>,
	<NSLayoutConstraint:0x13bc2c0e0 UILayoutGuide:0x13b963710.trailing == _UIButtonBarButton:0x13bbc4e00.trailing>,
	<NSLayoutConstraint:0x13bc28330 UIView:0x13bc1c480.leading == _UIButtonBarButton:0x13bc17900.trailing>,
	<NSLayoutConstraint:0x13bbcc0f0 _UIButtonBarButton:0x13bc1c7e0.leading == UIView:0x13bc1c480.trailing>,
	<NSLayoutConstraint:0x13bbcc890 UIView:0x13bbc4aa0.leading == _UIButtonBarButton:0x13bc1c7e0.trailing>,
	<NSLayoutConstraint:0x13bbcccd0 _UIButtonBarButton:0x13bbc4e00.leading == UIView:0x13bbc4aa0.trailing>,
	<NSLayoutConstraint:0x13bbd4080 UIToolbar:0x13b95dda0.width == 0>,
	<NSLayoutConstraint:0x13b963980 UILayoutGuide:0x13b963710.left == _UIButtonBarStackView:0x13b9627f0.left>,
	<NSLayoutConstraint:0x13b963ba0 _UIButtonBarStackView:0x13b9627f0.right == UILayoutGuide:0x13b963710.right>,
    )

**Comment by hackiftekhar** [comment]
It actually doesn't support WebView since webview has their html textFields, neither UITextField nor UITextView.
