### ISSUE TITLE
UITextView/entryfield in general does not getting moved up into visible area when softkeyboard appears

### ISSUE THREAD

**Issue by camdata** [hackiftekhar/IQKeyboardManager#1208]
This worked on previous versions.

**Comment by camdata** [comment]
Solution: With some other commit the ViewWIllAppear method of the TableView containing the CollectionView containing the TextView was no longer called. 

This caused IQKM not to move the underlying view hierarchy.

Be sure to implement ViewWillAppear and make sure the super.ViewWillAppear is also called inside it.

**Comment by hackiftekhar** [comment]
I believe it's inside UITableViewController.
