### ISSUE TITLE
Non-translucent Toolbar

### ISSUE THREAD

**Issue by sadanro100** [hackiftekhar/IQKeyboardManager#1209]
In IQToolbar.swift the toolbar is initialized as follows:

self.isTranslucent = true

How can I have a non-translucent toolbar? I causes a visual glitch if I push or pop a viewController calling becomeFirstResponder on a textField in viewDidLoad, having a solid background for the toolbar solves it but I'm unable to change it in IQKeyboardManager.

Thanks

[glitch.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/1603535/glitch.zip)

**Comment by hackiftekhar** [comment]
Sorry to hear about that @sadanro100. You have to do couple of workaround probably. You can access toolbar using textfield.keyboardToolbar and can change it's translucent property probably. I Hope this will help.
