### ISSUE TITLE
After Keyboard Close View is not Scroll Properly

### ISSUE THREAD

**Issue by amit44405** [hackiftekhar/IQKeyboardManager#1210]
Help me.. When i open keyboard is work excellent but when i close keyboard view is no scroll proper .. see in this image
![simulator screen shot - iphone 8 - 2018-01-05 at 09 57 45](https://user-images.githubusercontent.com/32383405/34595567-0f9c207c-f1ff-11e7-8616-c7f8f825fe70.png)

**Comment by hackiftekhar** [comment]
sorry to hear about this, can you please provide me a demo app? However it looks like you have something like comment page and you might have to adopt your own solution to properly implement this. I would suggest you to read manual management guide and see chat screen section.

**Comment by errabelli09** [comment]
Same issue for me

**Comment by hackiftekhar** [comment]
Looks like you have a textField at the bottom and a textView at the top, in this case IQKeyboardManager will try to up full UIView to make it visible. However I fixed couple of issues recently, please take a look at my recent changes and see if that works.

**Comment by errabelli09** [comment]
No not working

**Comment by tosifkanunga** [comment]
Hello dear,
I am stuck in when keyboard come navigation bar is  goes up and when
dismiss keyboard view stuck in behind navigation bar what I have to do ?

**Comment by hackiftekhar** [comment]
Sorry, I can't help because no one is sharing demo project with me. Can you try with v6.0.0 released today?
