### ISSUE TITLE
Content keyboard dissapiring 

### ISSUE THREAD

**Issue by dromerobarria** [hackiftekhar/IQKeyboardManager#1211]
Hello 

Every time the keyboard is open the content of it disappear, the weird thing is when I press in the  empty space the keyboard detect the characters but for some reason it wont show it correctly as you will see in the photos.

![simulator screen shot - iphone 8 - 2018-01-05 at 15 25 43](https://user-images.githubusercontent.com/5997644/34623655-0cb4618a-f231-11e7-8b71-87ca6acad7b0.png)

![simulator screen shot - iphone 8 - 2018-01-05 at 15 55 58](https://user-images.githubusercontent.com/5997644/34623656-0cdf69f2-f231-11e7-8c9c-e7c4e4c98510.png)

**Comment by hackiftekhar** [comment]
Oops, it looks weird but unfortunately it's not related to library if keyboard UI change. It should be an apple side issue.
