### ISSUE TITLE
 IQLayoutGuideConstraint with CocoaPods or Carthage.

### ISSUE THREAD

**Issue by Fujikatoma** [hackiftekhar/IQKeyboardManager#1214]
"For CoacoaPods or Carthage, IQLayoutGuideConstraints may not be visible in storyboard. For a workaround you should set it programmatically"

Is there any example ? Because i cant see the Keyboardmanager in storyboard

**Comment by hackiftekhar** [comment]
You could try importing `IQUIViewController+Additions.h` file and assign value to that constraint. I think that sould probably work.
