### ISSUE TITLE
View stays scrolled on resign first responder

### ISSUE THREAD

**Issue by dimovskidamjan** [hackiftekhar/IQKeyboardManager#1215]
I have a UITextField on the bottom of a view. When it becomes active, the view is raised to make room for the keyboard as it should. After resign first responder, the view is not lowered back down, but stays up, blocking any further interaction with my app. This happens on iOS 11, Xcode 9, objc version of the pod, running on iPhone X and iPhone 6/7/8.

**Comment by assembleMHN** [comment]
I have a similar issue, i have two textfields in a cell in a horizontal scroll collectionview. When i select a textfield the collection view is scrolled vertical but when the keyboard resigns the cell is not moved into the correct position. And actually i dont want the cell to scroll inside the collectionview, i want the viewcontroller view to be the moving part. In my case it looks stupid that the cell is scrolling inside the collectionview :(

**Comment by hackiftekhar** [comment]
@dimovskidamjan can you please share any demo project to debug this issue?

**Comment by hackiftekhar** [comment]
@assembleMHN you might need to do some workaround to overcome with this situation. You might need to play with scrollEnabled = true/false. If it's false then library ignore that scrollView and consider it as normal UIView and move the viewController view up.

**Comment by dimovskidamjan** [comment]
Changed some constraints to pin the main view to the safe area at the bottom and the issue disappeared. As far as I'm concerned, you can close the issue.

**Comment by hackiftekhar** [comment]
Thanks @dimovskidamjan

**Comment by assembleMHN** [comment]
@hackiftekhar its kinda a big problem to turn off scrolling in a collectionview ;) Vertical scrolling is turned off, but IQKeyboard manager still push the collectionview/cell up, and dont replace it afterwards.

**Comment by Albinzr** [comment]
Still having the same issue!! Any proper fix?
