### ISSUE TITLE
Tableview Not moving

### ISSUE THREAD

**Issue by syedrazackimran** [hackiftekhar/IQKeyboardManager#1217]
in my class, i have table view inside a text field. when I respond text field table view not moving up. kindly do needfully

**Comment by hackiftekhar** [comment]
Are you using UITableViewController?

**Comment by syedrazackimran** [comment]
yes I'm using both UITableViewController and UITableView

**Comment by hackiftekhar** [comment]
If you are using UITableViewController then library is doing nothing and respecting UITableViewController's implementation of handling keyboard.
