### ISSUE TITLE
Not Working With UITableFooterView

### ISSUE THREAD

**Issue by ashishke2m** [hackiftekhar/IQKeyboardManager#1219]
I have added one TextView Inside UITableFooterView, but IQKeyboardManager is not working with it.
It is not able to scroll up a UItableView, Keyboard is appearing above it.

**Comment by hackiftekhar** [comment]
Are you using UITableViewController?

**Comment by jacobo360** [comment]
+1.. you have to manually scroll down after keyboard appears.

**Comment by robertomg** [comment]
This seems to be a problem of `UITableViewController` - I had this as well on my controller with a `tableFooterView`.
