### ISSUE TITLE
iTunes Store Operation Failed

### ISSUE THREAD

**Issue by JayeshPoriya** [hackiftekhar/IQKeyboardManager#1220]
Hi, 
I am using IQKeyboardManager one of my application but I face some issue when I submit the app to App Store. 
![screen shot 2018-01-12 at 3 05 16 pm](https://user-images.githubusercontent.com/16848686/34875008-7d84c52c-f7c1-11e7-8dd9-48ebaec3c113.png)
![screen shot 2018-01-12 at 3 05 22 pm](https://user-images.githubusercontent.com/16848686/34875014-83914080-f7c1-11e7-8777-04011ce91bd7.png)
Can anyone help me to sort out this Issue?

**Comment by hackiftekhar** [comment]
Are you using Carthage @JayeshPoriya ?

**Comment by hackiftekhar** [comment]
Ohh, okay, you are the one who contacted me via email. Just remember to add the workaround you found to fix this problem.

**Comment by mgiroux** [comment]
what is the fix to make it work?

**Comment by hackiftekhar** [comment]
I forgot what was the fix. @JayeshPoriya can you please remind me here?
