### ISSUE TITLE
Toolbar not visible in device

### ISSUE THREAD

**Issue by SMFakhir** [hackiftekhar/IQKeyboardManager#1221]
Hi,

The toolbar is not getting displayed on the device if we show alert view first, before opening keyboard from anywhere.

**Comment by hackiftekhar** [comment]
Can you please provide more info or screenshot or demo app @SMFakhir ?

**Comment by FakhirPwC** [comment]
Hi Iftekhar,

Apologies for the delay, this is not an issue with IQKeyboardManager, there was one more dependency we were using that were messing up with this.

Closing the issue. Thanks.

**Comment by SMFakhir** [comment]
Hi Iftekhar,

Apologies for the delay, this is not an issue with IQKeyboardManager, there was one more dependency we were using that were messing up with this.

Closing the issue. Thanks.

**Comment by usamabinattique** [comment]
@SMFakhir Shared what was wrong with your project, I am facing the same issue.

**Comment by SMFakhir** [comment]
Hi Usama,

There was another library which was overriding the interface orientation of the app.
