### ISSUE TITLE
please look those picture，tips: a viewcontroller, the view cannot scroll.

### ISSUE THREAD

**Issue by shengxianghong** [hackiftekhar/IQKeyboardManager#1223]
![2018-01-15 19 37 03](https://user-images.githubusercontent.com/13196098/34941078-2e01e926-fa2d-11e7-98fa-7f13a134833f.png)
![9cf8b6a1-fc40-4a97-9979-4d9371ade740](https://user-images.githubusercontent.com/13196098/34941093-3eb814a2-fa2d-11e7-809e-3111bacc1f53.png)
![ad9f2147-60b3-4783-b503-10cb86c72ed3](https://user-images.githubusercontent.com/13196098/34941108-47ad419a-fa2d-11e7-93f4-0da649e3a425.png)
![0fec7a95-e816-4022-ac31-c7b04a8768bb](https://user-images.githubusercontent.com/13196098/34941097-417a2a90-fa2d-11e7-8f76-5d0072b311d1.png)

**Comment by Sulemankandornawala** [comment]
Facing the same issue.
![simulator screen shot - iphone se - 2018-01-20 at 12 27 59](https://user-images.githubusercontent.com/35622319/35180879-e0484648-fdde-11e7-9098-f646707d6a33.png)

**Comment by shengxianghong** [comment]
I found a temporary solution.

In your UINavigationController 

- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view.

    UIView *view = [[UIView alloc] initWithFrame:CGRectMake(0, 0, kScreen_Width, 20)];
    view.backgroundColor = MainColor;//your hope color
    [self.view addSubview:view];
}

**Comment by hackiftekhar** [comment]
Can you guys please share any demo project to debug this issue?

**Comment by shengxianghong** [comment]
I‘m just add a view the same color as the color of navigation bar to status bar.

**Comment by errabelli09** [comment]
Same issue for me also

**Comment by hackiftekhar** [comment]
It's fixed with new solution, changes are in `master` branch now. Please check and let me know if it doesn't work for you.
