### ISSUE TITLE
Is there a fix for the minimum deployment target set to 11.0 for IQKeyboardManagerSwift?

### ISSUE THREAD

**Issue by acerts04** [hackiftekhar/IQKeyboardManager#1226]
I have been researching and have not seen a fix for this yet. Anything? Thanks.

**Comment by bengotow** [comment]
Also running in to this - it says it supports back to iOS 8, but when building with Carthage both IQKeyboardManager and IQKeyboardManagerSwift get `MinimumSDKVersion: 11`
