### ISSUE TITLE
IQTextView.editable = NO, The view.toolbar will appear, and no keyboard

### ISSUE THREAD

**Issue by IPOSDai** [hackiftekhar/IQKeyboardManager#1227]
I have a lot of characters，but I don't want to edit them, and textView.editable = NO. So that when I click the textView, the keyboard.toobar will appear, and I double click the textView, it will rolling up to top.

**Comment by IPOSDai** [comment]
I don't know if it is normal, but what I want is that the keyboard.toolbar should not appear, and double click textView should be nothing.

**Comment by hackiftekhar** [comment]
It's iOS who show textField + keyboard + inputAccessoryView (Usually UITabbar), we can't do much thing there.

**Comment by IPOSDai** [comment]
So, when I set textView.editable = NO, I need to set textView.inputAccessoryView = nil. But double click textView,  the content of textView will scroll up, this is normal?

**Comment by hackiftekhar** [comment]
For workaround, it's YES. But at lady I can say, it's all managed by iOS and we can't do anything to fix this issue.

**Comment by IPOSDai** [comment]
OK, Thanks.
