### ISSUE TITLE
IQKeyboardReturnKeyHandler retain cycle

### ISSUE THREAD

**Issue by godexsoft** [hackiftekhar/IQKeyboardManager#1228]
In swift code i have IQKeyboardReturnKeyHandler as per documentation. Just adding the field and creating an instance from (controller: self) makes a retain cycle somehow. Easiest way to check is to add deinit method with a log line. Without IQKeyboardReturnKeyHandler the log line appears, with IQKeyboardReturnKeyHandler it does not - the controller stays in memory.

**Comment by hackiftekhar** [comment]
I'll check the memory and retain cycle issues. Thanks for letting me know about this.

**Comment by hackiftekhar** [comment]
I tried to fix memory issues with v5.0.8, let's see if that works for you.

**Comment by godexsoft** [comment]
unfortunately it's still with the same result. deinit is not executed when creating instance from (controller: self).

**Comment by hackiftekhar** [comment]
You should release the IQReturnKeyHandler object wirh deinit of your ViewController. if it doesn't work then I'll try to take a look again.

**Comment by godexsoft** [comment]
But how can you release it in the deinit if deinit is never executed due to retain cycle? That's exactly the problem :)

**Comment by hackiftekhar** [comment]
okay, let me see then.

**Comment by hackiftekhar** [comment]
I got the point, it's because the IQKeyboardReturnKeyHandler is keeping reference of textField delegate and most of the time it's the ViewController who owns it. A fix is on the way.
