### ISSUE TITLE
The done button's selector isn't be called.

### ISSUE THREAD

**Issue by monkiyang** [hackiftekhar/IQKeyboardManager#1229]
the version is v5.0.7.

the selector wasn't be called when I clicked done button. the code is 
``` 
[_searchBar.keyboardToolbar.doneBarButton setTarget:self action:@selector(doneItemClicked:)];
```

I set some breakpoints in some methods, like `doneAction:`,  `-(IQToolbar *)keyboardToolbar`, and debugged step by step. I found that the barButton's invocation is nil and the keyboardToolbar isn't the same one.

**Comment by monkiyang** [comment]
The author replied that the library is not optimized for searchBar in [#994](https://github.com/hackiftekhar/IQKeyboardManager/issues/994#issuecomment-359170994).

**Comment by hackiftekhar** [comment]
@monkiyang I would like to keep open this issue. I'll try to figure out if I can optimize it for searchBar also.

**Comment by monkiyang** [comment]
@hackiftekhar Ok. Thanks for your cost, and I expect for its optimization.

**Comment by hackiftekhar** [comment]
@monkiyang I started on this fix and just realized, IQKeyboardManager doesn't display any toolbar for searchBar then how keyboard toolbar is appearing in your case?
