### ISSUE TITLE
Black screen at the bottom

### ISSUE THREAD

**Issue by daywalkero** [hackiftekhar/IQKeyboardManager#1232]
When keyboard disappeared, the screen at the bottom of the View stays black, like this thread: 
https://stackoverflow.com/questions/48075934/ios-iqkeyboardmanager-when-keyboard-dismiss-black-screen-at-bottom/48457306
(not my thread!)

Problem occurs from 5.0.0 above in an chat-like view (tableview top, uiview with stackview (with button and textview) at the bottom). IQLayoutConstraint is linked properly.

**Comment by hackiftekhar** [comment]
It's fixed with new solution, changes are in `master` branch now. Please check and let me know if it doesn't work for you.
