### ISSUE TITLE
键盘引起崩溃

### ISSUE THREAD

**Issue by chuango** [hackiftekhar/IQKeyboardManager#1236]
我发现项目自从用了这个类，引发了很多崩溃，常常切换键盘或者点击切换输入框的时候崩溃，查看日志显示此类遍历的时候出了问题，大家有遇到吗？怎么解决很头痛

**Comment by elite-kai** [comment]
我也遇到了这个问题，这个问题感觉不太好测试呀，我的手机没有问题，看的umeng后台错误分析才发现有的用户出现了这个问题

**Comment by ladmini** [comment]
我iOS10.x下面点击输入框的时候闪退必现。我已经提了issue，但是没有解决。

**Comment by hackiftekhar** [comment]
Please use english guys

**Comment by hackiftekhar** [comment]
Are you still getting crashes?

**Comment by sushushu** [comment]
你们把问题相关代码贴上来啊,就这样问谁能帮你们?

You don't post code on the question, so who can help you?
