### ISSUE TITLE
Crash On - [IQKeyboardManagerSwift.IQBarButtonItem invocation]

### ISSUE THREAD

**Issue by harishchopra86** [hackiftekhar/IQKeyboardManager#1238]
Hi, 
Thanks for this wonderful library.
I am using in in my Swift-4.0 project. I am using IQKeyboardManager.framework and installed it via Cartrage.
However, it is crashing randomly on tapping Done button, below are the crash details:
-- [IQKeyboardManagerSwift.IQBarButtonItem invocation]: unrecognized selector sent to instance 0x7fcc8ef5c6f0
 *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[IQKeyboardManagerSwift.IQBarButtonItem invocation]: unrecognized selector sent to instance 0x7fcc8ef5c6f0'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010b09012b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x0000000109d92f41 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010b111024 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x000000010b012f78 ___forwarding___ + 1432
	4   CoreFoundation                      0x000000010b012958 _CF_forwarding_prep_0 + 120
	5   IQKeyboardManager                   0x00000001095f2872 -[IQKeyboardManager doneAction:] + 165
	6   UIKit                               0x000000010cee7972 -[UIApplication sendAction:to:from:forEvent:] + 83
	7   UIKit                               0x000000010d8f9290 __45-[_UIButtonBarTargetAction _invoke:forEvent:]_block_invoke + 154
	8   UIKit                               0x000000010d8f91c1 -[_UIButtonBarTargetAction _invoke:forEvent:] + 181
	9   UIKit                               0x000000010cee7972 -[UIApplication sendAction:to:from:forEvent:] + 83
	10  UIKit                               0x000000010d066c3c -[UIControl sendAction:to:forEvent:] + 67
	11  UIKit                               0x000000010d066f59 -[UIControl _sendActionsForEvents:withEvent:] + 450
	12  UIKit                               0x000000010d065e86 -[UIControl touchesEnded:withEvent:] + 618
	13  UIKit                               0x000000010cf5d807 -[UIWindow _sendTouchesForEvent:] + 2807
	14  UIKit                               0x000000010cf5ef2a -[UIWindow sendEvent:] + 4124
	15  UIKit                               0x000000010cf02365 -[UIApplication sendEvent:] + 352
	16  UIKit                               0x000000010d84ea1d __dispatchPreprocessedEventFromEventQueue + 2809
	17  UIKit                               0x000000010d851672 __handleEventQueueInternal + 5957
	18  CoreFoundation                      0x000000010b033101 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	19  CoreFoundation                      0x000000010b0d2f71 __CFRunLoopDoSource0 + 81
	20  CoreFoundation                      0x000000010b017a19 __CFRunLoopDoSources0 + 185
	21  CoreFoundation                      0x000000010b016fff __CFRunLoopRun + 1279
	22  CoreFoundation                      0x000000010b016889 CFRunLoopRunSpecific + 409
	23  GraphicsServices                    0x0000000112fdd9c6 GSEventRunModal + 62
	24  UIKit                               0x000000010cee65d6 UIApplicationMain + 159
	25  Development                   0x0000000108c05db7 main + 55
	26  libdyld.dylib                       0x0000000110e3ad81 start + 1
	27  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by hackiftekhar** [comment]
Not sure why it gets a crash. A demo would be good source to dig into it.
