### ISSUE TITLE
Retain cycle

### ISSUE THREAD

**Issue by ed-mejia** [hackiftekhar/IQKeyboardManager#1241]
Hi guys,

Calling 
`textFieldForAccountNumber.keyboardToolbar.doneBarButton.setTarget(self, action: #selector(editingFinishForAccountNumber))`

Is generating a retain cycle due to the tuple that store the reference of the target

```
open func setTarget(_ target: AnyObject?, action: Selector?) {
        invocation = (target, action)
    }
    
    /**
     Customized Invocation to be called when button is pressed. invocation is internally created using setTarget:action: method.
     */
    open var invocation : (target: AnyObject?, action: Selector?)
```

Any way to workaround this properly?, currently I'm hacking the controller to assign nil to the target and action once the controller disappears _(not really happy with this solution though)_

**Comment by hackiftekhar** [comment]
@ed-mejia I did some memory issue related fixes with v5.0.8. Please try and and see if that works for you.

**Comment by ed-mejia** [comment]
Hi @hackiftekhar I'm currently stuck with Swift 3.2 so I need to migrate to Swift 4 in order to install the version with the fix.... once I get it done I will come back to confirm. Thanks for the fix 👍

**Comment by hackiftekhar** [comment]
I have a good news for you @ed-mejia, library is compatible with swift4.0/3.2/3.0 and able to compile against swift 3.2.

**Comment by ed-mejia** [comment]
@hackiftekhar that's great, my current pod is 'IQKeyboardManagerSwift', '4.0.13'

What version can I install for a project under swift 3.2? 6.0?

**Comment by hackiftekhar** [comment]
6.0 isn't released yet. It's scheduled to release around 13th April. You can try master branch version.
