### ISSUE TITLE
Please help me how to fix this keyboard issue.

### ISSUE THREAD

**Issue by Topmobile106** [hackiftekhar/IQKeyboardManager#1242]
Hello, I found the IQKeyboard issue, I added IQKeyboard into my project. But I found the serious issue. Please check the following video file.
https://www.dropbox.com/s/cyojaxmtkz6eq2b/20180202.mov?dl=0

And I made a test project to reproduce the issue, but it seems it's a bit different with my main project. Please check test project(testproject.zip).
[testKeyboard.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/1690323/testKeyboard.zip)
Can you please review it and let me know how to fix it?

Thanks

**Comment by jack3010** [comment]
The error because you are using constraint with safe are. Try to use constraint with superview.

**Comment by hackiftekhar** [comment]
It's fixed with new solution, changes are in `master` branch now. Please check and let me know if it doesn't work for you.
