### ISSUE TITLE
It doesn't let the app to build. Help needed.

### ISSUE THREAD

**Issue by Fadedglyph** [hackiftekhar/IQKeyboardManager#1243]
I imported the IQKeyboardManagerSwift to my project and enabled it at AppDelegate. But as I try to run the project, Xcode says **_"ambiguous use of topMostController()"_** and **_"Declarations in extensions cannot override yet."_**
Please help me get rid of these compiler errors.
Thanks!
![screen shot 2018-02-03 at 8 43 56 am](https://user-images.githubusercontent.com/33647367/35762556-6df5f29e-08be-11e8-949b-94052cc8ce76.png)

**Comment by jack3010** [comment]
Please post the code you added IQKeyboard in AppDelegate. Its so hard to help you when you added the image.

**Comment by christophermohammed** [comment]
Having the same issue. the only line that i've added to the app delegate is 

IQKeyboardManager.sharedManager().enable = true 

to the didFinishLaunchingWithOptions function

**Comment by hackiftekhar** [comment]
Please update to latest version
