### ISSUE TITLE
How to avoid pushing the navigation bar up on appearing keyboard?

### ISSUE THREAD

**Issue by jaisan123** [hackiftekhar/IQKeyboardManager#1244]
Thanks for the awesome library.
Right now when the keyboard appears, the top navigation bar is pushed up and it's hidden and after dismissing the keyboard, the navigation bar comes back. I want the navigation bar to be there.How can I achieve it?please help

**Comment by Ethras** [comment]
I add the same issue and found this.

First paragraph  :

https://github.com/hackiftekhar/IQKeyboardManager/blob/master/MANUAL%20MANAGEMENT.md

**Comment by hackiftekhar** [comment]
@jaisan123 @Ethras I'm trying to reimplement the whole keyboard management solution which will fix most of the library issues user getting these days. This is also one of those which will be fix with new changes. If you would like to take a look then check `new_logic` branch.

**Comment by hackiftekhar** [comment]
It's fixed with new solution, changes are in `master` branch now. Please check and let me know if it doesn't work for you.
