### ISSUE TITLE
White space on top

### ISSUE THREAD

**Issue by sz-ashik440** [hackiftekhar/IQKeyboardManager#1246]
I have set `IQKeyboardManager.sharedManager().enable = true` into my `AppDelegate.swift` file.
It almost works on every view perfectly. But some times it shows a white empty space at the top of view which has navigation bar on it. 
If I press down button couples of times and go down and than press done, that white space appears.
For example: image URL(https://i.imgur.com/fXEixjO.png)

 
![issue](https://i.imgur.com/fXEixjO.png)

**Comment by vanessaforney** [comment]
I’m seeing this too. Have you found a workaround? It only happens ~30% of the time the view is shifted for me.

https://imgur.com/a/C8erB

**Comment by hackiftekhar** [comment]
It's due to some layout guides introduced with iOS11. I'm working on some new approach to fix these kind of issues, let's see if that works.

**Comment by sz-ashik440** [comment]
Thanks @vanessaforney for digging things up. I found this issue only when keyboard is returning from UITextView. But after updating into 'IQKeyboardManagerSwift' (5.0.8) and implementing `IQKeyboardManager. sharedManager().canAdjustAdditionalSafeAreaInsets = true`, that top white space is not showing right now. But I think there are some animation glitch while keyboard is appearing  from bottom.

And Thanks @hackiftekhar for making this wonderful library. Eagerly waiting for **v6.0.0**

**Comment by hackiftekhar** [comment]
It's fixed with new solution, changes are in `master` branch now. Please check and let me know if it doesn't work for you.

**Comment by sz-ashik440** [comment]
Just updated `IQKeyboardManagerSwift` from `master`. Works fine with `UITextView`. Also I am not seeing animation glitch which I have mention into my previous comment. 
Thanks @hackiftekhar for the update

**Comment by sz-ashik440** [comment]
@hackiftekhar This issue is happening again on iOS 11.3. I have updated to v6.0.3

**Comment by hackiftekhar** [comment]
Can you please share a demo project so that I can take a look again?

**Comment by sz-ashik440** [comment]
It's strange. I have created a demo project from scratch for recreating the issue. But it works perfectly on demo project. However issue is there on my existing project. I have updated pod as well as change to `IQKeyboardManager.shared.enable = true` into my AppDelegate.

Also I saw that on my new demo project, navigation bar stay still on top position but on my existing project the navigation bar moves out of bounds from screen.

**Comment by hackiftekhar** [comment]
hmm, then are you sure you are using 6.0.3 on your existing project?

**Comment by hackiftekhar** [comment]
@sz-ashik440 It looks like you might not be using 6.0.0 or above since I changed showing of navigationBar always and not move it with the main view which was the previous implementation below 6.0.0. Can you please share demo project?

**Comment by Vikram411** [comment]
This issue is happening on iOS 10.3.2. I have updated to v6.0.4. 

In iPhone 5s
xcode 9.3

![screen shot 2018-08-20 at 6 54 20 pm](https://user-images.githubusercontent.com/39688232/44343579-e1d51080-a4ab-11e8-8566-89f937388eda.png)

**Comment by hackiftekhar** [comment]
Can someone share a demo project?
