### ISSUE TITLE
Safe area constraint and Keyboard Manager 

### ISSUE THREAD

**Issue by ChanchalW** [hackiftekhar/IQKeyboardManager#1247]
I am creating a custom navigation bar in my project and editing text field causing this. 
![error](https://user-images.githubusercontent.com/21195828/35968952-4c96cf8e-0ceb-11e8-9730-ce36b7ee936d.png)
#1166

**Comment by tonistair** [comment]
Did you add  `IQKeyboardManager.sharedManager().canAdjustAdditionalSafeAreaInsets = true` in AppDelegate? This might solve your issue...

**Comment by ChanchalW** [comment]
It's my old project in swift 3.

**Comment by hackiftekhar** [comment]
It's fixed with new solution, changes are in `master` branch now. Please check and let me know if it doesn't work for you.

**Comment by n4jim** [comment]
hello,
its works on textfield, but not in textview !?

**Comment by ohayon** [comment]
Any update on this? I am seeing the same issue with UITextView.

**Comment by hackiftekhar** [comment]
I haven't managed some time to create the demo project. @ohayon @n4jim @ChanchalW can you please upload a demo project?
