### ISSUE TITLE
Disable pushing view

### ISSUE THREAD

**Issue by ryandailey100** [hackiftekhar/IQKeyboardManager#1249]
Is there a way to disable a view (that acts like a nav bar in my case) from getting pushed up when the keyboard gets presented? I tried using the scrollView method but that did not work for me. My view is in a tableView cell , and the cell is the size of the screen. Please get back to me asap, thanks.

**Comment by hackiftekhar** [comment]
If your cell size is larger than required then there is no way to do so.

**Comment by patriksharma** [comment]
@ryandailey100 did you find any solution for this. I have an tableview and its first and second cell is not visible when table view goes Up
