### ISSUE TITLE
Declarations in extensions cannot override yet

### ISSUE THREAD

**Issue by nicospbr** [hackiftekhar/IQKeyboardManager#1250]
I have that issue with xcode 9.2 when trying to add IQKeyboardManager

Any idea on how to solve that?
What about "Ambiguous use" ?

Thanks guys

![image](https://user-images.githubusercontent.com/36362094/36072034-e661539e-0f18-11e8-9d8b-f01eb7f12967.png)

**Comment by hackiftekhar** [comment]
This issue has already been fixed.
