### ISSUE TITLE
Keyboard does not come out when launching the simulator with iphone 6

### ISSUE THREAD

**Issue by son0417** [hackiftekhar/IQKeyboardManager#1252]
Keyboard does not come out when launching the simulator with iphone 6
![2018-02-12 14 30 50](https://user-images.githubusercontent.com/34063746/36085921-965e2fb2-100c-11e8-8b25-0faa2869d0d5.png)

but It works when it is iphone 8
![2018-02-12 15 53 06](https://user-images.githubusercontent.com/34063746/36085972-dd50ef72-100c-11e8-8427-6a393eaedc77.png)

![2018-02-12 15 54 24](https://user-images.githubusercontent.com/34063746/36086002-0dea5c9a-100d-11e8-8985-a8d08705e51a.png)
![2018-02-12 15 54 29](https://user-images.githubusercontent.com/34063746/36086011-132ac730-100d-11e8-8620-434744ac6457.png)
![2018-02-12 15 54 37](https://user-images.githubusercontent.com/34063746/36086017-19d5da34-100d-11e8-869d-5624c9e20ad7.png)

How can I fix it?

**Comment by hackiftekhar** [comment]
It's default behaviour of iOS Simulator
