### ISSUE TITLE
Issue while archiving using carthage xcode 9.3.2

### ISSUE THREAD

**Issue by zeshanhayder** [hackiftekhar/IQKeyboardManager#1253]
Hi,
This error come when i try to archive the project. i am using carthage. On device it runs fine, but not for archiving.
Undefined symbols for architecture armv7:
 "_OBJC_CLASS_$_IQKeyboardManager"
I have added QuartzCore as well. but same result all the time. what i am missing here ? Help would be appreciated.
Note: all other methods works fine i.e. pods, manual but only Carthage does not work. not sure why

**Comment by Vincent-Loi** [comment]
Having the same issue here with a production app. Can someone advise?

![screen shot 2018-02-15 at 9 18 39 am](https://user-images.githubusercontent.com/17518173/36249033-5ea3cc5e-1231-11e8-82ad-6851cf3f297e.png)

@zeshanhayder There is a workaround by setting 'Build active architecture only' to YES' but will drop support for Arm7 devices.

**Comment by zeshanhayder** [comment]
Yes but i thought not to do so, because in POD it works, in manual it works. why only in carthage it has issue.
