### ISSUE TITLE
invalid use of UIKit from a background thread.

### ISSUE THREAD

**Issue by AymenFarrah** [hackiftekhar/IQKeyboardManager#1254]
we have a crash caused by using a UIKit from a background thread
i have the last version of IQKeyboardManager 5.0.7 (objective-c version)

the issue is in the file : IQKeyboardManager.m Line 240 ..  UITextField *view = [[UITextField alloc] init];

```
//Loading IQToolbar, IQTitleBarButtonItem, IQBarButtonItem to fix first time keyboard appearance delay (Bug ID: #550)
            {
                UITextField *view = [[UITextField alloc] init];
                [view addDoneOnKeyboardWithTarget:nil action:nil];
                [view addPreviousNextDoneOnKeyboardWithTarget:nil previousAction:nil nextAction:nil doneAction:nil];
            }
```

**Comment by hackiftekhar** [comment]
Please be sure to don't call IQKeyboardManager.sharedManager() from a background thread.

**Comment by CyberMew** [comment]
@hackiftekhar I am having this problem as well during launch of the app. Same even after updating to 5.0.8. I am using the ObjC version and I do not call any of IQKeyboardManager functions/methods at all. We do not experience a crash but we do experience a breakpoint (we do have **All Exceptions** turned on). The only way to 'fix it' is to turn off exception for a short while and reenable it after the app has launched finished. 

![screen shot 2018-03-19 at 11 47 53 am](https://user-images.githubusercontent.com/4715911/37577213-b5c48eda-2b6b-11e8-8fc0-7ddafb526454.png)

**Comment by hackiftekhar** [comment]
As you can see this is on main thread and we aren't doing anything special. Same code doesn't have issue with previous version of Xcode. So I believe ut's not from our side. To let you know I'm also having same issue but unable to gix tjis since it's beyond our control.

**Comment by hackiftekhar** [comment]
Duplucate of #1136

**Comment by CyberMew** [comment]
Yes, seems like it's some bug with All Exceptions, because if we disabled All Exceptions but still enable the exceptions underneath it, it works.
