### ISSUE TITLE
Toolbar Glitch in iOS 11.2

### ISSUE THREAD

**Issue by satishbabariya2** [hackiftekhar/IQKeyboardManager#1255]
![screen shot 2018-02-22 at 12 47 57 pm](https://user-images.githubusercontent.com/20663566/36525174-d68aa27c-17ce-11e8-8f19-46737ed53ff7.png)

**Comment by sagarnatekar** [comment]
I am having the same issue as above, where the toolbar is misaligned on iOS 11.2, but works with iOS 10.3. Tried with the latest release - 5.0.7. @hackiftekhar Any chance this can be resolved in the next release?.

**Comment by wty302857194** [comment]
me  too

**Comment by hackiftekhar** [comment]
But this issue cannot be solve from our end because it looks a glitch with iOS not with our library.

**Comment by satishbabariya2** [comment]
So any suggestion for solving this issue any how ?

**Comment by hackiftekhar** [comment]
Because I'm not known the cause of this issue that's why I'm not able to suggest something.

**Comment by hackiftekhar** [comment]
However I'm confirmed 90% that this is not due to library logic.
