### ISSUE TITLE
为什么最近感觉使用起来特别卡，5.0.7 版本

### ISSUE THREAD

**Issue by aimm** [hackiftekhar/IQKeyboardManager#1258]
特别是点击toolbar上的按钮的时候，有明显的卡顿，不知道大家有没有同感

**Comment by gusennan** [comment]
**Translated:** 
Title: Why do I feel like lately it's been very laggy, version 5.0.7
Text: Especially when I click on buttons in the toolbar, there's an obvious lag/freeze, I don't know if others have had the same experience.

**Comment by hackiftekhar** [comment]
It's only with simulator, are you getting this problem with real devices also?
Can you please check latest master code since I optimized it for a little bit performance.

**Comment by Janyau** [comment]
There really is a freeze when using a real machine. Strangely, when I click the down button, my third keyboard automatically switches to the native keyboard, That's not what I want.

![keyboardchanged](https://user-images.githubusercontent.com/14040182/37950802-9016ddac-31cc-11e8-8d00-76f27d016be6.gif)

But when using only the native keyboard, the result is normal.

Version 5.0.8
Device: 6s
Xcode: 9.2

**Comment by hackiftekhar** [comment]
Can you please share the demo project with me?
