### ISSUE TITLE
call previous and next button action in current controller

### ISSUE THREAD

**Issue by sreeram780** [hackiftekhar/IQKeyboardManager#1260]
Hi

I need to call current controller action method when next and arrow clicked for particular textfield.
Any Suggestions. Thanks in Advance.

**Comment by hackiftekhar** [comment]
You could register for previous/next/done button callback something like this:-
```
    [textField3.keyboardToolbar.previousBarButton setTarget:self action:@selector(previousAction:)];
    [textField3.keyboardToolbar.nextBarButton setTarget:self action:@selector(nextAction:)];
    [textField3.keyboardToolbar.doneBarButton setTarget:self action:@selector(doneAction:)];
```

**Comment by sreeram780** [comment]
hi

Thanks for your reply.

Thanks&Regards,
T.Sreenivasula Reddy,
MOB: +91 9703889458,
SKYPE: sreenivasulareddy780.
