### ISSUE TITLE
Can you add a custom event when the keyboard pops up/down.

### ISSUE THREAD

**Issue by OneWang** [hackiftekhar/IQKeyboardManager#1261]
Can you add a custom event when the keyboard pops up/down?

**Comment by hackiftekhar** [comment]
You can register Keyboard native notifications to observe these events.

**Comment by OneWang** [comment]
However, IQKeyboardManager is invalid if I have registered the keyboard notificaations.

**Comment by hackiftekhar** [comment]
Nope, IQKeyboardManager still do it's original work.
