### ISSUE TITLE
在xcode 7上使用会报错。xcode 9没有问题。

### ISSUE THREAD

**Issue by huangwenxian** [hackiftekhar/IQKeyboardManager#1262]
这是报错信息。由于是游戏使用，游戏版本只能用xcode 7，麻烦大佬看看
Undefined symbols for architecture arm64:
  "___isOSVersionAtLeast", referenced from:
      -[IQKeyboardManager setRootViewFrame:] in MaoWanSDK(IQKeyboardManager.o)
      ___38-[IQKeyboardManager setRootViewFrame:]_block_invoke in MaoWanSDK(IQKeyboardManager.o)
      -[IQKeyboardManager keyboardWillShow:] in MaoWanSDK(IQKeyboardManager.o)
      ___38-[IQKeyboardManager keyboardWillHide:]_block_invoke.368 in MaoWanSDK(IQKeyboardManager.o)
      -[IQKeyboardManager keyboardDidHide:] in MaoWanSDK(IQKeyboardManager.o)
      -[IQKeyboardManager textFieldViewDidBeginEditing:] in MaoWanSDK(IQKeyboardManager.o)
      -[IQKeyboardManager willChangeStatusBarOrientation:] in MaoWanSDK(IQKeyboardManager.o)
      ...
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by hackiftekhar** [comment]
Looks like MaoWanSDK internally uses IQKeyboardManager. It looks like that
SDK modified the library to fit their needs.

IQKeyboardManager is not using ___isOSVersionAtLeast reference anywhere.

I also discourage developers to use my library within their SDK. It's
clearly mention in readme page. Please contact to MaoWanSDK developers.
