### ISSUE TITLE
Tableview will scroll to top when tap a textfield that place at the bottom of the cell.

### ISSUE THREAD

**Issue by desmond0321** [hackiftekhar/IQKeyboardManager#1263]
Hi, 
I have a UITableViewController and contain a 1200 height cell inside, and I place two textfield at the bottom, around position y : 1000 ++, then when I tap on the textfield, it will scroll to top of the tableview.

Any one know how to solve this issue? And what cost that happen?

It will work normal if the cell is short.

Steps to Reproduce

1. Create a new table view controller in story board
2. Create a super long cell (longer than your phone height)
3. Place text field at the bottom of the cell
4. Run the app and tap the textfield

**Xcode:** 9.2

**Mac OS:** 10.12.0

**Simulator/Device:** 11

**Simulator/Device Name:** iPhone 7 +

**Library Version:** 5.0.7

I have upload a video about the issue.
https://drive.google.com/open?id=1g5-KiB4kiHROUlUzHoITF3qt3B-ucAsa

**Comment by LeonardoGtz** [comment]
I'm having the same issue, did you find any solution?

**Comment by desmond0321** [comment]
@LeonardoGtz No, but I spit the textfield to separate cell, this temp solve my issue, not sure is that able to solve yours as well

**Comment by hackiftekhar** [comment]
@desmond0321 can you please share the demo with me?

**Comment by hackiftekhar** [comment]
If you are using UITableViewController then IQKeyboardManager respect it's own implementation of handling keyboard and textField distance. Library ignore all the things related to distance handling with UITableViewController.
