### ISSUE TITLE
Declarations in extensions cannot override yet

### ISSUE THREAD

**Issue by christophermohammed** [hackiftekhar/IQKeyboardManager#1264]
I have the most recent version and this line is causing an error:

@objc override public func topMostController()->UIViewController?

### Versions

**Xcode:** 9.2

**Mac OS:** 10.12.0

**Simulator/Device:** 11.2

**Simulator/Device Name:** iPhone 5s

**Library Version:** 5.0.7

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by hackiftekhar** [comment]
Please update to latest version
