### ISSUE TITLE
I want IQKeyboardManager to not to move screen upword when textview/textfield is selected

### ISSUE THREAD

**Issue by sameer4** [hackiftekhar/IQKeyboardManager#1265]
I want IQKeyboardManager to not to move screen upward when textview/textfield is selected...i want it to work like whatsapp

`if(tableview.contentsize.height > keyboard.y)
{
 "can move screen upward"
}
else
{
 "don't move screen upward"
}`

**Comment by hackiftekhar** [comment]
Then you need to disable library for that controller and implement your own solution.
