### ISSUE TITLE
Overriding TextField delegate methods

### ISSUE THREAD

**Issue by ajf-sp** [hackiftekhar/IQKeyboardManager#1267]
Hi, this is related to a [previous question](https://github.com/hackiftekhar/IQKeyboardManager/issues/473).

I'm using version 5.0.8. When I set the return key handler as follows:
```
let handler = IQKeyboardReturnKeyHandler.init(controller: self)
handler.delegate = self
```
Navigation through text fields go smoothly. However, **text field delegate methods are not called**. How do I override these delegate methods while making use of IQKeyboard handling? Thanks so much.

If I set my textfield delegates to self, the delegates are called properly; however, **IQKeyboard cannot detect next/previous fields**, forcing the keyboard to hide when tapping on the up/down buttons.

After some debugging, I found out that `IQUIView+Hierarchy`'s `deepResponderViews()` are ignoring my tableview's textfields.

Here's my view structure:
-UIView
---Label
---Tableview
----- 2 custom cells with textfields, 1 cell without textfield
---Button

**Comment by hackiftekhar** [comment]
TableView has cell reusing logic and when you initialize IQKeyboardReturnKeyHandler then table hasn't rendered those cells. That's why library wasn't able to find those 2 textfield.

**Comment by ajf-sp** [comment]
It turns out that the issue was something else entirely. Calling tableView's `reloadData` was automatically resigns first responder, and that's what's interfering with the implementation. Sorry for the trouble!

**Comment by ambrusha** [comment]
Hi
How can I use ```func textField(_ textField: UITextField, shouldChangeCharactersIn range: NSRange, replacementString string: String) -> Bool```
Because in normal case I did as
```
someTextField.delegate = self
func textField(_ textField: UITextField, shouldChangeCharactersIn range: NSRange, replacementString string: String) -> Bool {
    if textField == someTextFields {
        //do something
    }
}
