### ISSUE TITLE
App hangs when typing password in UITextField with secureTextEntry = true

### ISSUE THREAD

**Issue by tuan78** [hackiftekhar/IQKeyboardManager#1268]
### Description

App hangs when typing password in UITextField with secureTextEntry = true.
No problem if i change secureTextEntry = false. Or set IQKeyboardManager.sharedManager().enable = false

### Steps to Reproduce

1. Simple create 2 UITextFields in Storyboard. First is for typing the email, Second is for typing the password with secureTextEntry = true and font size = 16. Just connect to UIViewController as IBOutlet to get the text for later uses (but not yet).
2. Type the email. Then tap on password UITextField.
3. Just type first character (any character, example is number "1") then issue happens.

**Expected behavior:** App does not hang and can type password in UITextField

**Actual behavior:** App hangs for around 5-10 seconds then see the debug logs "Message from debugger: Terminated due to memory issue"

**Reproduces how often:** Always

### Versions

**Xcode:** 9.2

**Mac OS:** 10.13.3

**Simulator/Device:** 11.2.6

**Simulator/Device Name:** iPhone 6s (Real device), and any iPhone in simulator

**Library Version:** 5.0.8

**Comment by tuan78** [comment]
Sorry just recheck, issue also happens with font size <= 14

**Comment by hackiftekhar** [comment]
@tuan78 so it looks like the issue is not with the library. right?

**Comment by tuan78** [comment]
No problem if i disable the using of library with this line of code:
IQKeyboardManager.sharedManager().enable = false

**Comment by hackiftekhar** [comment]
Hmm, it means it might get freeze somewhere in library. Can you please find-out at which place library hangs?

**Comment by tuan78** [comment]
Oh i see. I will try to find-out the issue.

**Comment by tuan78** [comment]
Sorry for late reply, i found that the issue come from my side which makes the app hangs when use your library. I just update my own code and it works fine.

I will close this issue and many thanks for the good library!

**Comment by hackiftekhar** [comment]
I've also pushed v6.0.2 With the same fix at another place.

**Comment by hechukwu** [comment]
@tuan78 I'm having the same issue what did you do to make it work

**Comment by hechukwu** [comment]
@hackiftekhar it's still happening for me

**Comment by tuan78** [comment]
@hechukwu At that time I worked around with constraint layout events and layout rendering events to see what happens (it probably contains an unexpected loop somewhere relates to layout updates).
You could put the debug breakpoint where you override the **layoutSubviews**, **layoutIfNeeded**,.. etc

**Comment by hechukwu** [comment]
I'm not overriding **layoutSubviews, layoutIfNeeded** it's just an email and password textfield. I'm alsousing **MaterialComponents/TextFields** for my textfield if that has anything to do with it.

**Comment by tuan78** [comment]
@hechukwu Okay, so let's try replacing **MaterialComponents/TextFields** with **UITextField** to see what happens. **MaterialComponents** probably overrides the layout events.

**Comment by hechukwu** [comment]
Thanks @tuan78 I updated the pod and it is working fine now, I should have updated it here.
