### ISSUE TITLE
IQKeyboardToolbar disappear on landscape mode with UIPickerview.

### ISSUE THREAD

**Issue by Premal-Khetani** [hackiftekhar/IQKeyboardManager#1271]
### Description

I have added below code for uipicker in uitextfield. 

```
txtUserType.inputView = pickerView
txtUserType.addDoneOnKeyboardWithTarget(self, action: #selector(self.btnDoneTap(_:)))
```

now as I've shown in the GIF the issue is making. 

Please help me as we have support for landscape also. 

### Steps to Reproduce

Shown in GIF

**Expected behavior:** The Tool bar must not disappear. 

**Actual behavior:** The tool bar is disappear while orientation changes to Landscape with only UIPicker as inputview of Textfield.

**Reproduces how often:** 100%

### Versions

**Xcode:** 9.2

**Mac OS:** 10.12.6

**Simulator/Device:** 11.2

**Simulator/Device Name:** iPhone 8 Plus

**Library Version:** 5.0.7

### Additional Information

![iqkeyboard_issue](https://user-images.githubusercontent.com/13691970/37339752-b7c07980-26e1-11e8-95ab-86fccbe2fe00.gif)

**Comment by hackiftekhar** [comment]
Can you please share that demo project?

**Comment by Premal-Khetani** [comment]
sure let me create the demo and share it with you.

**Comment by Premal-Khetani** [comment]
Here  is the demo for the same issue, 
One another issue i am facing as when i am in portrait mode and open keyboard and then goto landscape mode the textfield scrolled up that's fine. Now when again i go to portrait mode with keyboard open and then i dismiss keyboard but the view still scrolled up and i can see black view in the bottom. Please take a look in to Demo Project. : [IQKeyLandScapeIssue.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/1815054/IQKeyLandScapeIssue.zip)

**Comment by hackiftekhar** [comment]
sure! Thanks for the demo.

**Comment by hackiftekhar** [comment]
Please add this line also `pickerView.autoresizingMask = [.flexibleWidth,.flexibleHeight]` this fixes the issue for me.

**Comment by Premal-Khetani** [comment]
Thanks @hackiftekhar  for quick update.

**Comment by Premal-Khetani** [comment]
@hackiftekhar  have you checked that black portion issue at the bottom ?
