### ISSUE TITLE
UI Jumps on iPhone X when text is changed in text field

### ISSUE THREAD

**Issue by Procurares** [hackiftekhar/IQKeyboardManager#1273]
### Description

After starting editing text field ui jumps down, and keyboard cover part of the Text Field.

NOTE: This issue is not reproducible on iPhone 6s and SE

### Steps to Reproduce

1. Focus a text field, so keyboard will be opened
2. Start editing text field

**Expected behavior:** UI Jump

**Actual behavior:** Position of UI must be the same as when the keyboard opened

**Reproduces how often:** Always

### Versions

**Xcode:** 9.2

**Mac OS:** 10.12.0

**Simulator/Device:** 11.2.6

**Simulator/Device Name:** iPhone X

**Library Version:** Latest

### Additional Information

![ezgif com-resize](https://user-images.githubusercontent.com/1181760/37463558-4192c866-285e-11e8-939e-58814c3def66.gif)

**Comment by hackiftekhar** [comment]
Can you please try with `master` branch if that works for you. There are couple of fixes actually and might fix these kind of issues also.

**Comment by hackiftekhar** [comment]
Please also take a look at migration guide from old version to the latest version https://github.com/hackiftekhar/IQKeyboardManager/wiki/IQKeyboardManager-6.0.0-Migration-Guide

**Comment by sz-ashik440** [comment]
I was also facing this issue on `5.06` version not only for iPhone X but also other phones. But with the update from `master` branch it has been gone away

**Comment by farhad01** [comment]
is anyone checked if the bug is fix in version 6.0.0 or not?

**Comment by mafioSSi** [comment]
Hello. I just installed it and I have the same issue on iPhone X. Other iPhones and iPads works good.

**Comment by hackiftekhar** [comment]
Hey @mafioSSi then can you please share a demo project here?

**Comment by aegdevs** [comment]
in version 6.0.0 the problem is still on going.

**Comment by hackiftekhar** [comment]
Then can you please share the demo project?

**Comment by arjavlad** [comment]
[iPhoneX Text jump issue.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/1979538/iPhoneX.Text.jump.issue.zip)
I couldn't reproduce the exact issue in the demo project. But it has the issue where text field gets hidden behind toolbar.
And in my project, I have the exact same issue of UI jump in iPhone X. I other devices it works perfectly.

**Comment by hackiftekhar** [comment]
okay @arjavlad I'll check the demo project to understand the cause of this issue.

**Comment by arjavlad** [comment]
Thanks!

**Comment by encikpulasan** [comment]
Hi, is this problem on iphone X fix yet?
Thanks for the lovely plugins.

**Comment by encikpulasan** [comment]
so currently i solve this issue by setting custom value to`IQKeyboardManager.shared.keyboardDistanceFromTextField`

**Comment by encikpulasan** [comment]
Or you can check if it is an iPhone X, then add some padding between keyboard and textfield by using:
`
    func checkDevice() {
        if UIDevice().userInterfaceIdiom == .phone {
            switch UIScreen.main.nativeBounds.height {
            case 1136:
                print("iPhone 5 or 5S or 5C")
            case 1334:
                print("iPhone 6/6S/7/8")
            case 1920, 2208:
                print("iPhone 6+/6S+/7+/8+")
            case 2436:
                print("iPhone X")
                IQKeyboardManager.shared.keyboardDistanceFromTextField = 200.0
                break
            default:
                print("unknown")
            }
        } else {
            print("iPad")
        }
    }
`

**Comment by hackiftekhar** [comment]
@arjavlad I got what's the issue, it's because the bottom constraint is pinned to bottom layout guide and bottom layout guide on iPhoneX is 34pt by default. Due to this when view is moved, the textField move 34pt less which actually hide textField behind keyboard toolbar.

**Comment by hackiftekhar** [comment]
I applied a temporary fix for iPhoneX, however I can say it's a hack over safe area/layout guide.

**Comment by i0sa** [comment]
This issue is still there in iPHone 11, iOS 14
