### ISSUE TITLE
Missing changelogs

### ISSUE THREAD

**Issue by metisdev** [hackiftekhar/IQKeyboardManager#1275]
### Description

https://github.com/hackiftekhar/IQKeyboardManager/releases is missing changelog information.

### Steps to Reproduce

https://github.com/hackiftekhar/IQKeyboardManager/releases

**Expected behavior:**

Expecting something like : https://github.com/Alamofire/Alamofire/releases

**Actual behavior:** 

No change log

**Reproduces how often:** 

Everytime

### Versions

**Xcode:** 9.2

**Mac OS:** 10.12.0

**Simulator/Device:** 11.2

**Simulator/Device Name:** iPhone 5s

**Library Version:** 5.0.7

**Comment by metisdev** [comment]
Found it here : https://github.com/hackiftekhar/IQKeyboardManager/blob/master/CHANGELOG.md

**Comment by hackiftekhar** [comment]
Updated release notes in release tab. Thanks for pointing out that I was missing this.
