### ISSUE TITLE
General exception breakpoint hit in init()

### ISSUE THREAD

**Issue by GoldenJoe** [hackiftekhar/IQKeyboardManager#1277]
### Description

When initializing in AppDelegate as described in the readme with a Symbolic Breakpoint set to All Exceptions, a breakpoint is hit on line 863 in IQKeyboardManager.swift:
```
//Loading IQToolbar, IQTitleBarButtonItem, IQBarButtonItem to fix first time keyboard appearance delay (Bug ID: #550)
let textField = UITextField()
```
```
libc++abi.dylib`__cxa_throw:
->  0x113c77b86 <+0>:   pushq  %rbp
    0x113c77b87 <+1>:   movq   %rsp, %rbp
    0x113c77b8a <+4>:   pushq  %r15
    0x113c77b8c <+6>:   pushq  %r14
    0x113c77b8e <+8>:   pushq  %r12
    0x113c77b90 <+10>:  pushq  %rbx
    0x113c77b91 <+11>:  movq   %rdx, %r14
    0x113c77b94 <+14>:  movq   %rsi, %r15
    0x113c77b97 <+17>:  movq   %rdi, %rbx
    0x113c77b9a <+20>:  callq  0x113c779e0               ; __cxa_get_globals
    0x113c77b9f <+25>:  movq   %rax, %r12
    0x113c77ba2 <+28>:  callq  0x113c78110               ; std::get_unexpected()
    0x113c77ba7 <+33>:  movq   %rax, -0x60(%rbx)
    0x113c77bab <+37>:  callq  0x113c78143               ; std::get_terminate()
    0x113c77bb0 <+42>:  movq   %rax, -0x58(%rbx)
    0x113c77bb4 <+46>:  movq   %r15, -0x70(%rbx)
    0x113c77bb8 <+50>:  movq   %r14, -0x68(%rbx)
    0x113c77bbc <+54>:  leaq   -0x20(%rbx), %r14
    0x113c77bc0 <+58>:  movabsq $0x434c4e47432b2b00, %rax ; imm = 0x434C4E47432B2B00 
    0x113c77bca <+68>:  movq   %rax, -0x20(%rbx)
    0x113c77bce <+72>:  movq   $0x1, -0x78(%rbx)
    0x113c77bd6 <+80>:  incl   0x8(%r12)
    0x113c77bdb <+85>:  leaq   0x1d(%rip), %rax          ; __cxxabiv1::exception_cleanup_func(_Unwind_Reason_Code, _Unwind_Exception*)
    0x113c77be2 <+92>:  movq   %rax, -0x18(%rbx)
    0x113c77be6 <+96>:  movq   %r14, %rdi
    0x113c77be9 <+99>:  callq  0x113c7a62e               ; symbol stub for: _Unwind_RaiseException
    0x113c77bee <+104>: movq   %r14, %rdi
    0x113c77bf1 <+107>: callq  0x113c77c22               ; __cxa_begin_catch
    0x113c77bf6 <+112>: movq   -0x58(%rbx), %rdi
    0x113c77bfa <+116>: callq  0x113c78151               ; std::__terminate(void (*)())
```
### Steps to Reproduce

1. Add IQKeyboardManager
2. Add `IQKeyboardManager.sharedManager().enable = true` to application(didFinishLaunchingWithOptions:)
3. Set a Symbolic Breakpoint to All Exceptions
4. Run

**Expected behavior:** No exception 

**Actual behavior:** An exception is hit, but the app can continue running

**Reproduces how often:** Every Time

### Versions

**Xcode:** 9.2

**Mac OS:** 10.12.0

**Simulator/Device:** 11.2

**Simulator/Device Name:** Any

**Library Version:** 5.0.8

**Comment by hackiftekhar** [comment]
It actually doesn't belong to library, because it's something with Xcode version since same code was working perfectly on older Xcode.

**Comment by CyberMew** [comment]
I'm having this exact issue as well with ObjectiveC for quite some time now, probably with the newer Xcode versions. I always have All Exceptions enabled. 

Saw this new comment added:
                //If you experience exception breakpoint issue at below line then try these solutions https://stackoverflow.com/questions/27375640/all-exception-break-point-is-stopping-for-no-reason-on-simulator

Definitely not a font issue. I think this is more appropriate with a caveat: https://stackoverflow.com/questions/12861748/how-do-i-know-when-safe-to-ignore-cxa-throw-on-an-all-exceptions-breakpoint
