### ISSUE TITLE
IQKeyboard will make StateBar translucent in some situations

### ISSUE THREAD

**Issue by xiaoyishan** [hackiftekhar/IQKeyboardManager#1278]
### Description

[When the pop-up keyboard is stretched to the trigger screen, it will affect the status bar and make it lose the color of the navigation bar and become transparent. And the navigation bar will shrink up.]

### Steps to Reproduce

1. Down load this Demo: https://github.com/xiaoyishan/IQKeyboadBugCollectionDemo
2. Run and not scrolling
3. Click the different cell.field -> Close keyboard -> Click again

**Reproduces how often:**    100%

### Versions

**Xcode:** 9.2
**Mac OS:** 10.13.1
**Simulator/Device:** 11.2
**Simulator/Device Name:** iPhone 8 
**Library Version:** 5.0.7

**Comment by hackiftekhar** [comment]
Do you have same issue like #1158 #1145 #1223 ?

**Comment by xiaoyishan** [comment]
YES, It is the same phenomenon in my project. I will use those code in  ＃1158 solution at fisrst.
