### ISSUE TITLE
issue fetching with iPhone X 

### ISSUE THREAD

**Issue by senjaliya1989** [hackiftekhar/IQKeyboardManager#1279]
![simulator screen shot - iphone x - 2018-03-23 at 19 13 45](https://user-images.githubusercontent.com/6142742/37832485-bfcaf674-2ece-11e8-9b6d-1c2f939e1176.png)
### Description

how can remove space between keyboard and textfield.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

**Xcode:** 9.2

**Mac OS:** 10.12.0

**Simulator/Device:** 11.2

**Simulator/Device Name:** iPhone 5s

**Library Version:** 5.0.7

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by hackiftekhar** [comment]
For answering your primary question, you can set keyboardDistanceFromTextField property either globally with IQKeyboardManager class or specific to that textField somewhere defined in a category.

However it looks like you have a comment/chat kind of screen, There might be a lot of things get distrubed. I would suggest you to disable library in that screen and implement your own solution on that particular screen only.
