### ISSUE TITLE
iOS 8: conflict with auto layout and modal view controller

### ISSUE THREAD

**Issue by ivanguajana** [hackiftekhar/IQKeyboardManager#128]
We are having an issue with several text fields displayed in a modal view controller where some of them are covered by the keyboard. Apparently the problem is caused by the auto layout computations overriding IQKeyboardManager's `setFrame` call. We patched it with a quick hack to have it work for us (https://github.com/vilea/IQKeyboardManager).

**Comment by tabrez0481** [comment]
This patch works fine with autolayout.. @Vilea Thanks..
