### ISSUE TITLE
Method viewController in UIView subclasses 

### ISSUE THREAD

**Issue by AbrahamEP** [hackiftekhar/IQKeyboardManager#1280]
I used to implement this method in my own custom views and it was very useful, you can see why in the picture, but now I'm starting a new project and that method is missing. I think they removed it from the last version of IQKeyboardManagerSwift :( anyone have any info about this? 

Please hackiftekhar get back that method again !

![captura de pantalla 2018-03-26 a la s 17 37 10](https://user-images.githubusercontent.com/8635335/37938687-60a57408-311c-11e8-8c84-fd505cc90328.png)

**Comment by hackiftekhar** [comment]
I hope this https://github.com/hackiftekhar/IQKeyboardManager/wiki/IQKeyboardManager-6.0.0-Migration-Guide will help you.
