### ISSUE TITLE
Crash issue!

### ISSUE THREAD

**Issue by mikeZhang76521** [hackiftekhar/IQKeyboardManager#1281]
### Description

[Description of the issue]
When I use this manager, there is a crash related created, the crash stack is like below:

CoreFoundation | ___exceptionPreprocess + 124
-- | --
1 libobjc.A.dylib | objc_exception_throw + 56
2 CoreFoundation | -[__NSSingleObjectEnumerator initWithObject:]
3 UIKit | -[UIViewController _traverseViewControllerHierarchyFromLevel:withBlock:] + 200
4 UIKit | +[UIViewController _traverseViewControllerHierarchyWithDelayedRelease:] + 444
5 UIKit | -[UIApplication _performMemoryWarning] + 232
6 UIKit | -[UIApplication _receivedMemoryNotification] + 140
7 libdispatch.dylib | 0x0000000185421000 + 6676
8 libdispatch.dylib | 0x0000000185421000 + 40712
9 libdispatch.dylib | 0x0000000185421000 + 79944
10 libdispatch.dylib | 0x0000000185421000 + 58736
11 CoreFoundation | ___CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 12
12 CoreFoundation | ___CFRunLoopRun + 2012
13 CoreFoundation | CFRunLoopRunSpecific + 436
14 GraphicsServices | GSEventRunModal + 100
15 UIKit | UIApplicationMain + 236
16 RoavCam | 0x0000000104fa8000 + 820524
17 libdyld.dylib | _start + 4

my device complains as below :
NSGenericException
*** Collection <__NSArrayM: 0x1c4058a80> was mutated while being enumerated

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

**Xcode:** 9.2

**Mac OS:** 10.12.0

**Simulator/Device:** 11.2

**Simulator/Device Name:** iPhone 5s

**Library Version:** 5.0.7

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by hackiftekhar** [comment]
This doesn't show any stacktrace from library method call. Looks like issue is somewhere else.
