### ISSUE TITLE
Focus to previous textfield isn't smooth

### ISSUE THREAD

**Issue by PhuocLinh** [hackiftekhar/IQKeyboardManager#1282]
I have a UITableView (inside UIViewController) with each cell contains an UITextField. When I tap on the previous/forward button in `inputAccessoryView`, the UITableView is scrolled and the animation isn't smooth.

This is the video to reproduce: [https://youtu.be/neLN6yTjhXk](url)

Please help me to figure out the solution

**Comment by hackiftekhar** [comment]
Can you please try with the latest master branch version if that fixes the issue?

**Comment by hackiftekhar** [comment]
6.0.0 released!
