### ISSUE TITLE
  the status Bar on the navigation above will disappear.

### ISSUE THREAD

**Issue by CRCimagination** [hackiftekhar/IQKeyboardManager#1283]
### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step]
Click the textfield keyboard to pop up and move the page up.
2. [Second Step]
Click the "finish" button on the keyboard to retrieve the keyboard, and the page resumes its original position
3. [and so on...]
Once again, the page is moved up, and when the keyboard pops up, the status Bar disappears.
**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

**Xcode:** 9.2

**Mac OS:** 10.13.2

**Simulator/Device:** 11.2.6

**Simulator/Device Name:** iPhone SE

**Library Version:** 5.0.7

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

The SE machine clicks the textfield keyboard popup interface and then clicks the "finished" button on the keyboard to retrieve the keyboard. Once again, the status Bar on the navigation above will disappear.

I did some tests, if in your tool, "-(void)setRootViewFrame:(CGRect)frame" in your tool, call Animating content every time you update the frame (Bug ID: #160)
[controller. The view setNeedsLayout];
[controller. The view layoutIfNeeded]; These two methods, then each time will appear the status Bar disappear of the bug. There is a comment to write bug id: #160. I hope it will help you to modify the bug.

**Comment by errabelli09** [comment]
Same Issue for me also

**Comment by CRCimagination** [comment]
Have you solved your problem?

**Comment by hackiftekhar** [comment]
Can you please try with the latest source code in master branch? It does have couple of fixes and might solve this issue already? Let me know if that fix the issue.

**Comment by AsHighAsHonor** [comment]
![image](https://user-images.githubusercontent.com/11377156/38406768-d57af8ce-39b5-11e8-932b-331e69f3e6a5.png)

Hi @hackiftekhar 
  I still have this same issue 

 iOS 11.2.6 
 iPhone 6

 pod  version is " IQKeyboardManager 5.0.8 "

**Comment by CRCimagination** [comment]
Have you solved your problem?

**Comment by hackiftekhar** [comment]
6.0.0 released!
