### ISSUE TITLE
UITextView is covered by keyboard when its height is changed while typing in.

### ISSUE THREAD

**Issue by polaris0227** [hackiftekhar/IQKeyboardManager#1285]
### Description

UITextView is covered by keyboard when its height is changed while typing in.

### Steps to Reproduce

1. UITextView with dynamic height, so its height is increased while typing in. 
2. When focus in the textview at first time, it is shown fully, but if it has multiline text, other text contents except first line are hidden by keyboard.

**Expected behavior:** Textview should move up when content height is increased.

**Actual behavior:** It is fixed.

Any solution?
Thanks.

**Comment by hackiftekhar** [comment]
Library cannot detect changes made dynamically. You'll have to call `reloadLayoutIfNeeded` to notify library to recalculate all the things. Make sure to call this method only when textview height changes occurs

**Comment by polaris0227** [comment]
Thanks for your reply.
I have called textview.layoutIfNeeded(), but no success.
Should I call viewcontroller.view.layoutIfNeeded()?
Thanks.

**Comment by yoimhere** [comment]
reloadLayoutIfNeeded doesn‘t work
