### ISSUE TITLE
Add pickerView on IQKeyboardManager

### ISSUE THREAD

**Issue by PawanManjani** [hackiftekhar/IQKeyboardManager#1286]
Actually I need to show pickerview on button click. So I'm forcefully adding textfield on view without frame to show pickerview on keyboard, but I need to scroll up view even in this scenario. It's not a bug or issue, but I need help...

**Comment by hackiftekhar** [comment]
Can you please clarify the issue, I'm not sure if I understand it correctly.

**Comment by PawanManjani** [comment]
Okay, Can we scrollview view up on buttonclick without textfield or textview. because my button is at bottom of screen so i can't be able to see that button.

**Comment by hackiftekhar** [comment]
if textField is inside tableview then it cannot be achievable. If your textField is outside of tableview then you can set `keyboardDistanceFromTextField` on that textField to make a customized distance for button visibility.

**Comment by PawanManjani** [comment]
No, I'm talking about that How can we achieve a Auto scroll functionality on button click.

**Comment by hackiftekhar** [comment]
You have to use scrollView.
