### ISSUE TITLE
关于键盘弹出引发导航栏被顶出屏幕的问题

### ISSUE THREAD

**Issue by paintingStyle** [hackiftekhar/IQKeyboardManager#1287]
使用xib作为inputView，将它添加到UIViewController，他的父视图为self.view
查看官方的Demo发现键盘弹出没有将导航栏被顶出屏幕的问题，但自己项目使用会造成这个问题，我并不知道如何避免这个问题？

1网络上的解决办法是这样，但是我并不想每个UIViewController都这样干
- (void)loadView { 
    UIScrollView *scrollView = [[UIScrollView alloc] initWithFrame:[[UIScreen mainScreen] bounds]];
    [scrollView setBackgroundColor:[UIColor grayColor]];
    self.view = scrollView;
}

2 我目前的解决办法是这样，注释了IQUIView+Hierarchy.m的部分代码
-(UIViewController *)topMostController
{
    NSMutableArray<UIViewController*> *controllersHierarchy = [[NSMutableArray alloc] init];
    
    UIViewController *topController = self.window.rootViewController;
    
    if (topController)
    {
        [controllersHierarchy addObject:topController];
    }
    
    while ([topController presentedViewController]) {
        
        topController = [topController presentedViewController];
        [controllersHierarchy addObject:topController];
    }
    
    UIViewController *matchController = [self viewController];
    
    // FIXME:textField或者textField的父视图不是scrollview，这种情况下在自动适配键盘高度时，整个控制器页面会被上顶
//    while (matchController != nil && [controllersHierarchy containsObject:matchController] == NO)
//    {
//        do
//        {
//            matchController = (UIViewController*)[matchController nextResponder];
//
//        } while (matchController != nil && [matchController isKindOfClass:[UIViewController class]] == NO);
//    }
    
    return (UIViewController*)matchController;
}

但是这样操作存在隐患，希望作者给给出更好的解决办法，谢谢！

**Comment by hackiftekhar** [comment]
A fix has been made regarding navigation bar issue. For now, please check master branch. Please check the migration guide here https://github.com/hackiftekhar/IQKeyboardManager/wiki/IQKeyboardManager-6.0.0-Migration-Guide this version will be released via CocoaPods around 13th April
