### ISSUE TITLE
No done button appearing on textfields . latest version and version 4.0.13 . issue persists .. please help urgently . 

### ISSUE THREAD

**Issue by iOSDevAkshay** [hackiftekhar/IQKeyboardManager#1288]
### Description

[Description of the issue]

**Expected behavior:**  : Need to show DONE button on keyboard

**Actual behavior:** : Only placeholder of textfield appears .
Versions : 

**Xcode:** 9.2

**Mac OS:** 10.12.0

**Simulator/Device:** 11.2

**Simulator/Device Name:** iPhone 5s

**Library Version:** 5.0.7 / 4.0.13

**Comment by hackiftekhar** [comment]
This issue has been already solved with 4.0.12, if it still reproduce to you then can you please share a demo project here?
