### ISSUE TITLE
When the keyboard pops up, the entire view will have an offset of 20 pixels. More on iPhone X

### ISSUE THREAD

**Issue by DistanceLe** [hackiftekhar/IQKeyboardManager#1289]
### Description

When the keyboard pops up, the entire view will have an offset of 20 pixels. More on iPhone X

**Reproduces how often:** Very often

### Versions

**Xcode:** 9.3

**Mac OS:** 10.12.0

**Simulator/Device:** 11.3

**Simulator/Device Name:** all iPhone and simulator

**Library Version:** 5.0.8

**Comment by hackiftekhar** [comment]
Can you please share screenshot? It will help me to understand your scenario better.

**Comment by qmkl30** [comment]
I found same question on iPhone X.
When the textview become first respond at first time, the subviews are affected by safe area, then the textview resign first respond,subviews's frame don't correct，when pop to rootViewcontroller, the tabbar height is decreased, but I push to editController,click the textview for several times until that textview become first respond and subviews aren't affected by safe area at onetime, then pop to rootViewcontroller,tabbar height is normal.

screenshot：



<img width="329" alt="2c298511-f235-4a8d-b7c6-20899b5ddd93" src="https://user-images.githubusercontent.com/17609839/38285085-10896eee-37f1-11e8-8342-0a470514ea60.png">


<img width="347" alt="60c91e6e-85de-4789-88c7-daced1cda503" src="https://user-images.githubusercontent.com/17609839/38285092-1c67ddb8-37f1-11e8-8fae-d6ec00ad9945.png">


<img width="326" alt="53533ca7-1536-4458-a3e5-4adcd4c1c2bf" src="https://user-images.githubusercontent.com/17609839/38285100-2a134bdc-37f1-11e8-8337-2f8ccce62019.png">


<img width="321" alt="6bfa97a6-ad89-4e5c-ae8f-73b6e1fae132" src="https://user-images.githubusercontent.com/17609839/38285114-383987ee-37f1-11e8-9125-d46da047a603.png">



<img width="338" alt="bacdb735-f7cf-4c6d-ad8f-420016526527" src="https://user-images.githubusercontent.com/17609839/38285128-4c93634a-37f1-11e8-93c1-3b587800de8a.png">



<img width="342" alt="7259fead-e174-423e-a5d4-b5df5903545f" src="https://user-images.githubusercontent.com/17609839/38285137-55588e60-37f1-11e8-88da-0a34ba8e8a16.png">

**Comment by crazytom26** [comment]
![image](https://user-images.githubusercontent.com/12843351/38357871-571b2608-38f6-11e8-808d-d392fddccf24.png)
when popping up and down the keyboard ,the navigationbar left like the screenshot.

**Comment by hackiftekhar** [comment]
Can you please try latest master version if that fix the issue?

**Comment by DistanceLe** [comment]
Yes, the latest code, bugs have been resolved.
You can add release new version.

**Comment by qmkl30** [comment]
OK,I will try latest version later.

**Comment by hackiftekhar** [comment]
The latest changes will be released as 6.0.0 around 13th April.

**Comment by qmkl30** [comment]
Ok

**Comment by hackiftekhar** [comment]
6.0.0 released!
