### ISSUE TITLE
键盘起来过后 可以把背景view随意滑动到屏幕外面去 用户体验非常不好

### ISSUE THREAD

**Issue by tc1993** [hackiftekhar/IQKeyboardManager#1290]
### Description

当父视图为scollView的时候，键盘起来过后 可以把背景scollView随意滑动到屏幕外面去 用户体验非常不好。要怎么解决这个问题呢？
### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

**Xcode:** 9.2

**Mac OS:** 10.12.0

**Simulator/Device:** 11.2

**Simulator/Device Name:** iPhone 5s

**Library Version:** 5.0.7

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by hackiftekhar** [comment]
Your contentSize might be too much according to your content. Please make sure your contentSize is correct according to the content inside your scrollview.
