### ISSUE TITLE
Done next previous button not visible

### ISSUE THREAD

**Issue by gouravgupta72** [hackiftekhar/IQKeyboardManager#1293]
I'm using swift and done, next, previous button colour is not visible

### Versions

**Xcode:** 9.2

**Mac OS:** 10.12.0

**Simulator/Device:** 11.2

**Simulator/Device Name:** iPhone 8

**Library Version:** 4.0.10

![simulator screen shot - iphone 8 - 2018-04-06 at 11 05 11](https://user-images.githubusercontent.com/6007522/38404873-9ecb5f10-398a-11e8-8057-41fdace76591.png)

**Comment by hackiftekhar** [comment]
It's fixed with latest versions. Please update!

**Comment by AAlboghdady** [comment]
This issue still exist in version 6.5.5
