### ISSUE TITLE
IQKeyboardManagerSwift not exposed to Objective-C in Swift 4.1

### ISSUE THREAD

**Issue by alessandro-martin** [hackiftekhar/IQKeyboardManager#1294]
### Description

When using Swift 4.1 the library is not exposed to Objective-C classes.

### Steps to Reproduce

1. Given a mixed Objective-C + Swift Project
2. Using Swift 4.1
3. Import IQKeyboardManagerSwift into Objective-C class

**Expected behavior:** [What you expect to happen]

We should (and used to be) able to see the library's Swift members from Objective-C classes

**Actual behavior:** [What actually happens]

We are not able to call IQKeyboardManagerSwift from Objective-C

**Reproduces how often:** [What percentage of the time does it reproduce?]

Always

### Versions

**Xcode:** 9.3

**Mac OS:** 10.13.4

**Simulator/Device:** N/A

**Simulator/Device Name:** N/A

**Library Version:** 5.0.7

### Additional Information

We'd like to be able to keep adding just IQKeyboardManagerSwift to the project so the public API should be annotated with `@objc`.
It @hackiftekhar agrees I volunteer to create a PR for this issue and fix it.

**Comment by hackiftekhar** [comment]
Thanks @alessandro-martin for helping me on this. I would be glad if you contribute on this project. However there might be some more methods you might miss in PR.

However you can create the PR and I'll merge it. For a suggestion, please search open/public to find public methods.

**Comment by bj97301** [comment]
Has this been released?

**Comment by alessandro-martin** [comment]
@bj97301 Code has been merged into master but no release yet :)
You could point to `c8e5dfb6a4bd15cac85517eaeeb4d2739c3f5cc5`

**Comment by hackiftekhar** [comment]
This will release around 13th April

**Comment by alessandro-martin** [comment]
Thanks @hackiftekhar !

**Comment by hackiftekhar** [comment]
6.0.0 released!
