### ISSUE TITLE
Type 'IQKeyboardManager' has no member 'sharedManager'

### ISSUE THREAD

**Issue by MarkP12** [hackiftekhar/IQKeyboardManager#1297]
### Description

Once the package was imported manually into Xcode, I go into the application did load with options and enter in the code that was provided in the instructions: QKeyboardManager.sharedManager().enable = true
However, I get an error saying that there is no member sharedManager. What can I do so that it will work and the app will run? 

### Versions

**Xcode:** 9.3

**Mac OS:** 10.13.4

**Simulator/Device:** 11.2

**Simulator/Device Name:** iPhone X

**Library Version:** 5.0.7

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by hackiftekhar** [comment]
6.0.0 released!
