### ISSUE TITLE
Ugly black background while keyboard pops up and text field is at bottom of VC

### ISSUE THREAD

**Issue by ETGgames** [hackiftekhar/IQKeyboardManager#1298]
### Description

When there is a text field constrained to the bottom of the safe area, and you touch it so the keyboard pops up, there is a black gap that momentarily appears between my background and the keyboard, which implies that the keyboard is moving up at a different rate to the rest of the view.

**Expected behavior:** top of keyboard stays flush with bottom of safe area (ie the bottom of my background)

**Actual behavior:** Keyboard seems to have to catch up to the bottom of the view as it pops up, causing an ugly black background to appear between the top of the keyboard and the bottom of the view during keyboard popping up and down

**Reproduces how often:** 100%

### Versions

**Xcode:** 9.3

**Mac OS:** 10.12.0

**Simulator/Device:** 11.3

**Simulator/Device Name:** iPhone 7 but also happens on every simulator and real phone

**Library Version:** 5.0.8

### Additional Information

![ezgif-1-36f22d40dd](https://user-images.githubusercontent.com/13756744/38521989-22384604-3c3f-11e8-8e81-82ea7a08fc49.gif)

**Comment by hackiftekhar** [comment]
This shouldn't happen with latest master code, can you please check once with latest master code?

**Comment by ETGgames** [comment]
OK, now it is much less but still there, but now the navigation bar does not move up. Now the keyboard moves up before the text field but also shows a little bit of black background at the end just before the keyboard stops popping up

**Comment by ETGgames** [comment]
[iqkeyboardtest.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/1898349/iqkeyboardtest.zip)
try it on iphone 8 plus sim for example and on a real device

**Comment by hackiftekhar** [comment]
Thanks, I'll check it.

**Comment by hackiftekhar** [comment]
This is looking like animation timings related issue.

**Comment by ETGgames** [comment]
OK cool, let me know when you have found a solution

**Comment by hackiftekhar** [comment]
I'm not sure if this can be fixable because both animations are performing with a slight delay. That's why we are seeing this issue.

**Comment by ETGgames** [comment]
I see. perhaps we can have an option to set the animation time for the keyboard and/or screen moving up time? Or maybe you could change it so the keyboard moves up faster than the screen to ensure there is no black?

**Comment by hackiftekhar** [comment]
Actually it would be a little bit tricky with library because I optimized the adjustFrame method to call only after getting all required information and lesser time than previous versions (v5.0.8 or earlier) to improve performance. That might be the cause of this issue.

However I'll spend more time in future to investigate on this issue to find if there are any workaround..

**Comment by anirudhamahale** [comment]
I found a workaround for this, change the UIWindow's background color.

**Comment by hackiftekhar** [comment]
I spend some time on this but it looks like this situation can't be handled and we have to do some workarounds like @anirudhamahale suggested.

**Comment by omarshamali** [comment]
still happens 2022

**Comment by omarshamali** [comment]
workround, place in your VC viewillappear:
 override func viewWillAppear(_ animated: Bool) {
        if let window = (UIApplication.shared.delegate?.window)! as UIWindow? {
            window.backgroundColor = UIColor.white
        }
    }
