### ISSUE TITLE
why still had property "isAskingCanBecomeFirstResponder" in the IQUIView+Hierarchy ?library versions 4.0.9  from cocoapods.

### ISSUE THREAD

**Issue by Dacover** [hackiftekhar/IQKeyboardManager#1299]
### Description

[why did library contain property "isAskingCanBecomeFirstResponder" in the IQUIView+Hierarchy ? library versions 4.0.9  from cocoapods.]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

**Xcode:** 9.1

**Mac OS:** 10.13.1

**Simulator/Device:** 11.2

**Simulator/Device Name:** iPhone 5s

**Library Version:** 4.0.9

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by hackiftekhar** [comment]
It's removed in latest version.
