### ISSUE TITLE
Use of unresolved identifier 'UIApplication',Use of unresolved identifier 'UIEvent'

### ISSUE THREAD

**Issue by vijay1864** [hackiftekhar/IQKeyboardManager#1300]
### Description
iam getting these errors in swift 4  in xcode 9.2

Use of unresolved identifier 'UIApplication',
Use of unresolved identifier 'UIEvent' in IQInvocation.Swift Class

[Description of the issue]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

**Xcode:** 9.2

**Mac OS:** 10.12.0

**Simulator/Device:** 11.2

**Simulator/Device Name:** iPhone 5s

**Library Version:** 5.0.7

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by hackiftekhar** [comment]
You might be compiling library against other that iOS. Can you please check?

**Comment by hackiftekhar** [comment]
Ahh, I checked and found that `import UIKit` statement was missing. Just added.

**Comment by vijay1864** [comment]
Thank you..
Its working now..
