### ISSUE TITLE
[Improvement] Disable for certain classe

### ISSUE THREAD

**Issue by Lapinou42** [hackiftekhar/IQKeyboardManager#1301]
Hello, 

Is there a way to disable IQKeyboardManager on certain class ? 

Exemple: I would like to handle manually keyboard on my CustomViewController.
So, maybe something like this exists, but I didn't find the way to do this:

`IQKeyboardManager.sharedManager().disable(forClasses: [CustomViewController])`

Thank you for you feed-back.

**Comment by hackiftekhar** [comment]
There is similir property called `disabledDistanceHandlingClasses` And you can add your class to that array. It will work exactlh like you want.

**Comment by Lapinou42** [comment]
Thank you for your quick answer !
Perfect ! I saw this method but I didn’t think it was for that purpose because it’s a read only property... but yes, it’s managed in the sharedInstance... 

Sorry for that ;)
