### ISSUE TITLE
The status bar is missing

### ISSUE THREAD

**Issue by OCAndSwift** [hackiftekhar/IQKeyboardManager#1302]
![screen shot 2018-04-11 at 11 36 43](https://user-images.githubusercontent.com/17612243/38595154-a72d1d92-3d7c-11e8-88f9-8fd44cba6b19.png)

**Comment by hackiftekhar** [comment]
This issue has already been fixed. Can tou please try latest master verson?

**Comment by OCAndSwift** [comment]
What I use is the latest version, the version number is the 6.0.1.
Will also appear such problems, which set will conflict with me?

**Comment by hackiftekhar** [comment]
Can you please share demo project?

**Comment by OCAndSwift** [comment]
git@github.com:OCAndSwift/DEMO.git

**Comment by hackiftekhar** [comment]
I got the issue, it's because of side menu. Due to side menu, the library tries to move side menu up instead of the viewController.

I'll try to expose something to handle this kind issue.

**Comment by hackiftekhar** [comment]
To overcome this situation you have to write some code to tweak this situation.

You have to override `parentIQContainerViewController` method in your side menu controller and return the top view controller from your hierarchy.

For the provided demo project, the Objective-C library was used in swift project, so swift translated the method name as `parentIQContainer` so for the demo project workaround you have to override `parentIQContainer` method like this.
```
class SSASideMenu: UIViewController, UIGestureRecognizerDelegate {

    override func parentIQContainer() -> UIViewController? {
        if let navController = contentViewController as? UINavigationController {
            return navController.topViewController
        } else {
            return contentViewController
        }
    }
    ...
}
```

**Comment by OCAndSwift** [comment]
I didn't understand how to rewrite the method of parentIQContainer?what is the the method of parentIQContainer？what is the the parent of parentIQContainer？

Can you please share project on my demo  project from  git@github.com:OCAndSwift/DEMO.git ?

**Comment by OCAndSwift** [comment]
![2018-07-12 8 56 10](https://user-images.githubusercontent.com/17612243/42607155-10b3699a-85b4-11e8-9c74-dfb32532492b.png)
![2018-07-12 9 12 48](https://user-images.githubusercontent.com/17612243/42607157-13b109c2-85b4-11e8-87ff-556e9a442ec5.png)
How to deal with?

**Comment by hackiftekhar** [comment]
You have to run `pod update` to update it to latest version
