### ISSUE TITLE
Not working when i first focus on TextField

### ISSUE THREAD

**Issue by texmex44** [hackiftekhar/IQKeyboardManager#1303]
### Description
I have 2 texfield at the bottom of my page when i focus one of them for the first time the keyboard cover this one but when i use the KeyboardManager toolbar to pass to the next one it's work the view scroll to the focus.

### Versions
**Xcode:** 9.3
**Swift:** 4

**Comment by hackiftekhar** [comment]
Can you please try latest master version if that fix this issue?

**Comment by texmex44** [comment]
@hackiftekhar finally solved (problem with my parent scrollview)
