### ISSUE TITLE
Touch UITextField in Simulator will crash。

### ISSUE THREAD

**Issue by karson711** [hackiftekhar/IQKeyboardManager#1304]
### Description

Touch UITextField in Simulator will crash。

### Steps to Reproduce

**Log like this：**
2018-04-12 11:20:59.149204+0800 FamilyMachine[55911:9269939] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Please file a radar on UIKit with this log if you see this assertion. selectorString = setTitle:, exercisedImplementations = {
    "setTitle:" =     (
    );
}'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010bd251e6 __exceptionPreprocess + 294
	1   libobjc.A.dylib                     0x000000010d193031 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010bd2a472 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x000000010711664f -[NSAssertionHandler handleFailureInFunction:file:lineNumber:description:] + 165
	4   UIKit                               0x000000010951e9c3 PushNextClassForSettingIMP + 511
	5   UIKit                               0x0000000109528052 __workaround10030904InvokeWithTarget_block_invoke + 26
	6   UIKit                               0x0000000108cbeefa +[UIView _performSystemAppearanceModifications:] + 66
	7   UIKit                               0x0000000109528026 workaround10030904InvokeWithTarget + 771
	8   UIKit                               0x0000000109521f20 applyInvocationsToTarget + 1611
	9   UIKit                               0x0000000109521094 +[_UIAppearance _applyInvocationsTo:window:matchingSelector:onlySystemInvocations:] + 1924
	10  UIKit                               0x0000000108ceab0e __88-[UIView(Internal) _performUpdatesForPossibleChangesOfIdiom:orScreen:traverseHierarchy:]_block_invoke + 63
	11  UIKit                               0x0000000108ceaa99 -[UIView(Internal) _performUpdatesForPossibleChangesOfIdiom:orScreen:traverseHierarchy:] + 184
	12  UIKit                               0x0000000108cea9b4 -[UIView(Internal) _didChangeFromIdiomOnScreen:traverseHierarchy:] + 168
	13  UIKit                               0x0000000108ce9edf -[UIView(Internal) _didMoveFromWindow:toWindow:] + 1600
	14  UIKit                               0x0000000108ce9b98 -[UIView(Internal) _didMoveFromWindow:toWindow:] + 761
	15  UIKit                               0x0000000108e77040 -[UIToolbar _didMoveFromWindow:toWindow:] + 84
	16  UIKit                               0x0000000108cdc114 __45-[UIView(Hierarchy) _postMovedFromSuperview:]_block_invoke + 151
	17  Foundation                          0x000000010706b5a7 -[NSISEngine withBehaviors:performModifications:] + 131
	18  UIKit                               0x0000000108cdc005 -[UIView(Hierarchy) _postMovedFromSuperview:] + 835
	19  UIKit                               0x0000000108ceca2b -[UIView(Internal) _addSubview:positioned:relativeTo:] + 1940
	20  UIKit                               0x0000000109876afc -[UIInputWindowController changeToInputViewSet:] + 1798
	21  UIKit                               0x00000001098777c5 __43-[UIInputWindowController setInputViewSet:]_block_invoke + 57
	22  UIKit                               0x0000000108ce4bca +[UIView(Animation) performWithoutAnimation:] + 90
	23  UIKit                               0x0000000109877527 -[UIInputWindowController setInputViewSet:] + 707
	24  UIKit                               0x000000010986e4a2 -[UIInputWindowController performOperations:withAnimationStyle:] + 50
	25  UIKit                               0x0000000109411f69 -[UIPeripheralHost(UIKitInternal) setInputViews:animationStyle:] + 1637
	26  UIKit                               0x0000000109409dac -[UIPeripheralHost(UIKitInternal) _reloadInputViewsForResponder:] + 2137
	27  UIKit                               0x0000000108e55e02 -[UIResponder(UIResponderInputViewAdditions) reloadInputViews] + 81
	28  UIKit                               0x0000000109937be8 -[UITextField becomeFirstResponder] + 663
	29  UIKit                               0x000000010922cd1c -[UITextInteractionAssistant(UITextInteractionAssistant_Internal) setFirstResponderIfNecessary] + 208
	30  UIKit                               0x00000001091fd2fe -[UITextGestureClusterSelection oneFingerTap:] + 3830
	31  UIKit                               0x000000010921c41b -[UIGestureRecognizerTarget _sendActionWithGestureRecognizer:] + 57
	32  UIKit                               0x00000001092251f0 _UIGestureRecognizerSendTargetActions + 109
	33  UIKit                               0x0000000109222a38 _UIGestureRecognizerSendActions + 307
	34  UIKit                               0x0000000109221c8c -[UIGestureRecognizer _updateGestureWithEvent:buttonEvent:] + 859
	35  UIKit                               0x0000000109206cf0 _UIGestureEnvironmentUpdate + 1329
	36  UIKit                               0x0000000109206773 -[UIGestureEnvironment _deliverEvent:toGestureRecognizers:usingBlock:] + 484
	37  UIKit                               0x0000000109205875 -[UIGestureEnvironment _updateGesturesForEvent:window:] + 281
	38  UIKit                               0x0000000108c9b80b -[UIWindow sendEvent:] + 4064
	39  UIKit                               0x0000000108c3f370 -[UIApplication sendEvent:] + 352
	40  UIKit                               0x000000010958057f __dispatchPreprocessedEventFromEventQueue + 2796
	41  UIKit                               0x0000000109583194 __handleEventQueueInternal + 5949
	42  CoreFoundation                      0x000000010bcc7bb1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	43  CoreFoundation                      0x000000010bcac4af __CFRunLoopDoSources0 + 271
	44  CoreFoundation                      0x000000010bcaba6f __CFRunLoopRun + 1263
	45  CoreFoundation                      0x000000010bcab30b CFRunLoopRunSpecific + 635
	46  GraphicsServices                    0x0000000111c20a73 GSEventRunModal + 62
	47  UIKit                               0x0000000108c240b7 UIApplicationMain + 159
	48  FamilyMachine                       0x0000000106590b5f main + 111
	49  libdyld.dylib                       0x000000010fd20955 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

**Xcode:** 9.3

**Mac OS:** 10.13.4

**Simulator/Device:** 11.3

**Simulator/Device Name:** iPhone 8

**Library Version:** 5.0.7

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by hackiftekhar** [comment]
The logs sats you should file a radar on UIKit. This crash isn't related to library because I fon'tt see any call trace from library.
