### ISSUE TITLE
Weird Behavior on Keyboard Dismiss

### ISSUE THREAD

**Issue by michaelwestbrookstinroof** [hackiftekhar/IQKeyboardManager#1306]
### Description

I have a UIViewController with 4 custom controls that contain UITextfields in each of the view. When I essentially tap on any TextField "above" the fold, the view shifts and renders correctly. When I tap on the last UITextfield, closest to the bottom of the screen, the view does this weird rendering and offsets incorrectly. I have attached photos.

### Steps to Reproduce

I'm not sure if this is a location of the field in the viewController OR the field being a reused field.

### Versions

**Xcode:** 9.2

**Mac OS:** 10.12.6

**Simulator/Device:** 11.0.1

**Simulator/Device Name:** iPhone 6s

**Library Version:** 5.0.8

### Additional Information

Attached are the images

![img_1855](https://user-images.githubusercontent.com/36637602/38677715-115458ba-3e2d-11e8-8104-8a02128723e4.PNG)
![img_1856](https://user-images.githubusercontent.com/36637602/38677716-11681c92-3e2d-11e8-9d03-0ef38a6067f6.PNG)

**Comment by hackiftekhar** [comment]
Hmm, Can you please try with v6.0.0 version and let me know if that works for you? If that doesn't work for you then please share a demo project with me?

**Comment by michaelwestbrookstinroof** [comment]
@hackiftekhar ok will do!

**Comment by michaelwestbrookstinroof** [comment]
@hackiftekhar nope 6.0 didn't work. I will give you access to the repo. It will be coming from a different github account.

Steps to Reproduce:

1. Open App
2. Select Signup
3. Enter Test Credentials on Signup Screen => Use an actual email address as I will be sending you a registration code
4. Go to next screen and provide passwords and registration code
5. select ATHLETE
6. Select Basketball for primary sport and baseball for secondary sport
7. Error happens on this screen where you have to select your position and jersey number; select the second drop down.

**Comment by michaelwestbrookstinroof** [comment]
@hackiftekhar sent you an invite from redroostertech

**Comment by hackiftekhar** [comment]
Hey @michaelwestbrookstinroof I don't get the screen to select position and jersey number. Can you please guide me? hackiftekhar is my Skype. I think it would be better to not discuss project specific things in this chat. Can you please connect me via Skype?
