### ISSUE TITLE
v6.0.0 weird behavior when keyboard popup

### ISSUE THREAD

**Issue by fans3210** [hackiftekhar/IQKeyboardManager#1307]
### Description

[Description of the issue]

### Versions

**Xcode:** 9.3

**Device:** 11.3

**Simulator/Device Name:** iPhone 7

**Library Version:** 6.0.0

### Additional Information

The last version 5.0.8 works fine. I manually disabled the distance checking for this chatvc. Here is the code I used in appdelegate with version 5.0.8

     IQKeyboardManager.sharedManager().enable = true
        IQKeyboardManager.sharedManager().disabledDistanceHandlingClasses = [ChatMessagesVC.self]

And the behaviour is strange in 6.0.0.  Please check the video below:

https://www.dropbox.com/s/zg213q3nd2ehsry/iqkeyboardmanager6.0.0issue.mov?dl=0

And you will find that:
1. the status bar became strange
2. the text input field disappeared randomly when keyboard pops up.
3. the height of the navigation bar changed when the keyboard pops up

The behaviour should be like shown below as in 5.0.8 - there should be no height change in the navigation bar
https://www.dropbox.com/s/su34y5yr7r9df38/ScreenRecording_04-13-2018%2014-14-02.MP4?dl=0 

Would be appreciated if you could give me some tips and guidances. Thanks.

**Comment by fans3210** [comment]
@hackiftekhar thanks for the quick response. For chat screen I already disabled by using this method:

**Comment by fans3210** [comment]
@hackiftekhar , Sorry but I cannot reproduce the issue. I will revert you again once reproduced. Thanks.

**Comment by hackiftekhar** [comment]
Sure!
