### ISSUE TITLE
Infinite loop in method: parentContainerViewController in IQUIView+Hierarchy

### ISSUE THREAD

**Issue by RobBernardini** [hackiftekhar/IQKeyboardManager#1308]
### Description
I have found a bug where an infinite loop is established in the **parentContainerViewController** method in **IQUIView+Hierarchy** of **IQKeyboardManager**. In my case the error presents itself due to my hierarchy but the cause is due to the following code in the parentContainerViewController method.

while (parentController != nil &&
               parentParentController &&
               ([parentParentController isKindOfClass:[UINavigationController class]] == NO &&
                [parentParentController isKindOfClass:[UITabBarController class]] == NO &&
                [parentParentController isKindOfClass:[UISplitViewController class]] == NO))
        {
            parentController = parentParentController;
        }

Initially the parent controller is a UINavigationController and the parentParentController is a SWRevealViewController (though it could be any type of controller that is not a UINavigationController, UITabBarController or UISplitViewController). In the case that both controllers are not nil and the parentParentController is not of the kind shown in the while case it will enter into the loop and assign the parent controller to be the parentParentController. As you can see this will run as an infinite loop. I am assuming that the following line of code is missing in the while statement so that the method can find the root controller: 
**parentParentController = parentController.parentViewController**.

To add to that, to keep things standard, I think that in the while loop it should be:
**while (parentController != nil && parentParentController != nil && ...**
OR
**while (parentController && parentParentController && ...**

Therefore I think the statement should be:

**while (parentController != nil &&
               parentParentController != nil &&
               ([parentParentController isKindOfClass:[UINavigationController class]] == NO &&
                [parentParentController isKindOfClass:[UITabBarController class]] == NO &&
                [parentParentController isKindOfClass:[UISplitViewController class]] == NO))
        {
            parentController = parentParentController;
            parentParentController = parentController.parentViewController;
        }**

### Steps to Reproduce
1. In the storyboard create a UIViewController inside a UINavigationController inside any other controller (in my case I'm using an SWRevealViewController).
2. Add a textfield object inside the view controller.
3. Set up IQKeyboard manager in app delegate in didFinishLaunchingWithOptions, [IQKeyboardManager sharedManager].toolbarManageBehaviour = IQAutoToolbarByTag;
4. Run the app and click on the textfield.

**Expected behavior:** The parentContainerViewController should be obtained.

**Actual behavior:** An infinite loop is established obtaining the parentContainerViewController.

**Reproduces how often:** Always.

### Versions

**Xcode:** 9.3

**Mac OS:** 10.13.3

**Simulator/Device:** 11.3

**Simulator/Device Name:** iPhone 8

**Library Version:**

**Comment by hackiftekhar** [comment]
Hmm, you might probably be correct. I'll try to reproduce this issue and will do the suggested fixes. Thanks for reporting this issue..

**Comment by hackiftekhar** [comment]
You are correct. This logic has correctly been implemented in swift version of library but having issue with ObjC version of library. I'll fix it today.

**Comment by hackiftekhar** [comment]
Released 6.0.1 with this fix since it looks critical.

**Comment by batkov** [comment]
@hackiftekhar Hi, stuck in same method few lines below

<img width="1160" alt="screen shot 2018-04-18 at 3 52 49 pm" src="https://user-images.githubusercontent.com/582671/38933080-aea4c92c-4320-11e8-82b1-19afd25792ae.png">

**Comment by batkov** [comment]
match controller == match parent controller

**Comment by batkov** [comment]
```  matchParentController = matchController.parentViewController;
in line 147 will help

**Comment by hackiftekhar** [comment]
Already fixed in v6.0.1

**Comment by batkov** [comment]
This lock is on v6.0.1. 
Please check lines on screenshot 138-147

**Comment by hackiftekhar** [comment]
okay, sorry, I did the fix at one place but haven't applied this fix at other place at the same method. I fixed that now.

Regarding the release, I went a bit tricky this time. I deleted the v6.0.1 tag and repush v6.0.1 tag by including this new change. I'm not sure if this bypass CocoaPods and by updating your pod list, this new change will include now or not. Can you guys please try and let me know if that works for you (without releasing new version).

If this doesn't work then I can release v6.0.2.

**Comment by batkov** [comment]
@hackiftekhar It worked if someone not installed v6.0.1 yet. But if it is installed, dev should delete whole Pods folder + Podfile.lock and then run
```
pod update
```

**Comment by hackiftekhar** [comment]
Hmm, then I'll release it as v6.0.2
