### ISSUE TITLE
Keyboard not Appearing on click Textfield

### ISSUE THREAD

**Issue by SunnyBamaniya** [hackiftekhar/IQKeyboardManager#1309]
### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step]  Keyboard not Appearing on click Textfield after use the navigation controller.
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen] I am login in my application and want to add some details then textfield will freeze the application.

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?] 100% in side

### Versions

**Xcode:** 9.3

**Mac OS:** 10.12.0

**Simulator/Device:** 11.2

**Simulator/Device Name:** iPhone 5s

**Library Version:** 5.0.7

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by hackiftekhar** [comment]
You might be trying with simulator. right?

**Comment by SunnyBamaniya** [comment]
Hello,

Thanks for the review issue.
I Tested in Both Simulator and Device.


But By using latest verison.
issue got fixed.



Thanks for the Update.




*Thanks*
*Sunny Bamaniya*
