### ISSUE TITLE
Resize TextView issue

### ISSUE THREAD

**Issue by invinciible** [hackiftekhar/IQKeyboardManager#1310]
### Description

Hi, I'm working on resizing textview and when i press return key textView height will grow however cursor will get hidden behind the keyboard.
attaching the screenshot

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** Parent View should adjust

**Actual behavior:** No change in the parent view

### Versions

**Xcode:** 9.3

**Simulator/Device:** 11.3

**Simulator/Device Name:** iPhone 8

**Library Version:** > 6
![simulator screen shot - iphone 8 - 2018-04-18 at 10 43 56](https://user-images.githubusercontent.com/25017046/38912937-c4e8588c-42f5-11e8-8c3e-86ab5a955be2.png)

**Comment by hackiftekhar** [comment]
Technically there is no easy way for library to know when your textView height gets change. So you have to explicitly tell library to recalculate positions by calling `reloadLayoutIfNeeded` or something like this method of IQKeyboardManager.

**Comment by invinciible** [comment]
Kudos, it worked
