### ISSUE TITLE
tableView top hidden

### ISSUE THREAD

**Issue by qqq1010440810** [hackiftekhar/IQKeyboardManager#1311]
When you return to the previous page，the head of tableViwe will hidden a little

[手机QQ视频_20180419092908.mp4.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/1926317/QQ._20180419092908.mp4.zip)

**Comment by qqq1010440810** [comment]
I use IQKeyboardManagerSwift

**Comment by hackiftekhar** [comment]
@qqq1010440810 Not sure what might be the cause. Are you able to manually scroll to correct position or it stick at that position?
