### ISSUE TITLE
new version the bar button like this 

### ISSUE THREAD

**Issue by Easyzhan** [hackiftekhar/IQKeyboardManager#1312]
![661524103328_ pic](https://user-images.githubusercontent.com/8928783/38967261-cd86b790-43b8-11e8-85af-6b0a9c0aa226.jpg)

**Comment by hackiftekhar** [comment]
Can you please desceibe what is the issue with this?

**Comment by Easyzhan** [comment]
I don't know either, but the UIButton I used to customize the button on the navigation bar last night is normal. I guess. Like the code below.

------------fine code-------------
- (void)initNavBar{

    UIButton *add_to_zx = [[UIButton alloc] initWithFrame:CGRectMake(0, 0, 22, 22)];
    [add_to_zx setImage:[UIImage imageNamed:@"bs_detail_icon_add"] forState:UIControlStateNormal];
    [add_to_zx addTarget:self action:@selector(toolbarButtonTapped:) forControlEvents:UIControlEventTouchDown];
    add_to_zx.tag = 1;
    
    UIButton *warning_btn = [[UIButton alloc] initWithFrame:CGRectMake(0, 0, 22, 22)];
    [warning_btn setImage:[UIImage imageNamed:@"bs_detail_icon_warning"] forState:UIControlStateNormal];
    [warning_btn addTarget:self action:@selector(toolbarButtonTapped:) forControlEvents:UIControlEventTouchDown];
    warning_btn.tag = 2;
    
    UIButton *share_btn = [[UIButton alloc] initWithFrame:CGRectMake(0, 0, 22, 22)];
    [share_btn setImage:[UIImage imageNamed:@"bs_common_icon_share"] forState:UIControlStateNormal];
    [share_btn addTarget:self action:@selector(toolbarButtonTapped:) forControlEvents:UIControlEventTouchDown];
    share_btn.tag = 3;
    UIBarButtonItem *btn_add_to_zx = [[UIBarButtonItem alloc] initWithCustomView:add_to_zx];
    UIBarButtonItem *warning_ding = [[UIBarButtonItem alloc] initWithCustomView:warning_btn];
    UIBarButtonItem *share_duang = [[UIBarButtonItem alloc] initWithCustomView:share_btn];
    UIBarButtonItem *negativeRightSpacer = [[UIBarButtonItem alloc]
                                            
                                            initWithBarButtonSystemItem:UIBarButtonSystemItemFixedSpace
                                            
                                            target:nil action:nil];

    negativeRightSpacer.width = -5;
    
    UIBarButtonItem *negativeMidSpacer = [[UIBarButtonItem alloc]
                                          
                                          initWithBarButtonSystemItem:UIBarButtonSystemItemFixedSpace
                                          
                                          target:nil action:nil];
    
    negativeMidSpacer.width = 10;
    
    self.navigationItem.rightBarButtonItems = [NSArray arrayWithObjects:negativeRightSpacer,share_duang , negativeMidSpacer, warning_ding,btn_add_to_zx, nil];
    
}
------------------bad code----------------------------
//- (void)initRightNavItems{
//    UIBarButtonItem *right1 = [[UIBarButtonItem alloc] initWithImage:[[UIImage imageNamed:@"bs_common_icon_share"] imageWithRenderingMode:UIImageRenderingModeAlwaysOriginal] style:UIBarButtonItemStylePlain target:self action:@selector(rightAction:)];
//

//    UIBarButtonItem *right2 = [[UIBarButtonItem alloc] initWithImage:[[UIImage imageNamed:@"bs_detail_icon_warning"] imageWithRenderingMode:UIImageRenderingModeAlwaysOriginal] style:UIBarButtonItemStyleDone target:self action:@selector(rightAction:)];

//    UIBarButtonItem *right3 = [[UIBarButtonItem alloc] initWithImage:[[UIImage imageNamed:@"bs_detail_icon_add"] imageWithRenderingMode:UIImageRenderingModeAlwaysOriginal] style:UIBarButtonItemStyleDone target:self action:@selector(rightAction:)];
//    NSArray *arr = [[NSArray alloc]initWithObjects:right1, right2,right3, nil];
//
//    self.navigationItem.rightBarButtonItems = arr;
//}

**Comment by Easyzhan** [comment]
I guess iOS11 uibarbuttonitem has changed🙄 maybe xcode9.3
