### ISSUE TITLE
Stuck in infinite loop if used in STPopupController

### ISSUE THREAD

**Issue by tylerjames** [hackiftekhar/IQKeyboardManager#1313]
The app gets stuck in an infinite loop if used in a textfield that is contained in an [STPopupController](https://github.com/kevin0571/STPopup). 

This code is where it seems to get trapped inside `[UIView parentContainerViewController]` which is part of the`IQUIView+Hierarchy.h`

```objective-c
while (matchController != nil &&
               matchParentController &&
               ([matchParentController isKindOfClass:[UINavigationController class]] == NO &&
                [matchParentController isKindOfClass:[UITabBarController class]] == NO &&
                [matchParentController isKindOfClass:[UISplitViewController class]] == NO))
        {
            matchController = matchParentController;
        }
```

iOS: 11.2 (Simulator)
Library Version: 6.0

**Comment by hackiftekhar** [comment]
Can you try with 6.0.1?
