### ISSUE TITLE
Working in simulator but not on device

### ISSUE THREAD

**Issue by DanteLaviolette** [hackiftekhar/IQKeyboardManager#1314]
I am using 6.0.1 with swift 4 on Xcode 9.3.
Everything works perfectly in the simulator. Although, when I load the app onto my iphone 7 (ios 11.0.3) I am having a few issues:
- When I tap a textfield it works as expected, although when I begin typing the keyboard covers the textfield.
- When I hit the next button the constraints get weird and a button I have under the textfield covers it, and the keyboard covers the textfield.

Once again, these issues are only happening on my actual device and things are working perfectly in the simulator.
Also, it is worth noting that it was working earlier today and without me editing any code this randomly started happening.

Also `IQKeyboardManager.sharedManager().enable = true` does not work, I get an error saying IQKeyboardManager has no member sharedManager. So I have to use `IQKeyboardManager.shared.enable = true`

**Comment by hackiftekhar** [comment]
Can you please share demo project?

**Comment by DanteLaviolette** [comment]
I’ll post it when I get home from work tonight...thanks for the quick response :)

**Comment by TheEngineerz** [comment]
@DanteLaviolette have you reached home?

**Comment by DanteLaviolette** [comment]
My appologies, I completely forgot to post it...I’ll post it first thing in the morning. Thanks again.

**Comment by JustinBobo** [comment]
Also noticed that tapping "Done" causes a crash on my device but works fine on the simulator

**Comment by DanteLaviolette** [comment]
So, I have tried to create a demo project to post...Although when I create the demo project (Essentially creating a project with one of my view controllers and only having IQKeyboardManager installed) everything works. Also the only difference between between running my app on the simulator vs on my phone is that FirebaseMessaging is disabled on the simulator. This leads me to believe that FirebaseMessaging is causing conflicts with IQKeyboardManager. Although, after completely uninstalling Firebase I am still having the same issues.
Also below is a gif of exactly what is happening:
![error](https://user-images.githubusercontent.com/37600542/39269385-a8ec2bda-48a0-11e8-9366-341ee3c95dee.gif)

**Comment by hackiftekhar** [comment]
This mostly looks like constraint issue but not much due to library logic because when library try to move view in order to keep textField visible, it does it's job perfectly.
