### ISSUE TITLE
IQKeyboardManager.sharedManager() has no member

### ISSUE THREAD

**Issue by carlosguedes** [hackiftekhar/IQKeyboardManager#1316]
Hello Guys, after updating to the latest version update, when initialising on app delegate:

IQKeyboardManager.sharedManager().enable = true

Throw the following error message:

Type 'IQKeyboardManager' has no member 'sharedManager'

Did you guys changed it to: 

IQKeyboardManager.shared.enable = true?

**Comment by aunnnn** [comment]
Got this too.

**Comment by devdebajyotidas** [comment]
You have to change it to the following

IQKeyboardManager.shared.enable = true

**Comment by hackiftekhar** [comment]
https://github.com/hackiftekhar/IQKeyboardManager/wiki/IQKeyboardManager-6.0.0-Migration-Guide
