### ISSUE TITLE
iOS version in 11.2 toolbar "done" next is clearColor

### ISSUE THREAD

**Issue by ICloud0114** [hackiftekhar/IQKeyboardManager#1317]
### Description
when i use you tools, that Toolbar tincolor "done" next is clearColor

in iOS 10.0 is ok

### Versions

**Xcode:** 9.0

**Mac OS:** 10.12.0

**Simulator/Device:** 11.2

**Simulator/Device Name:** iPhone X 、iPhone 6 、iPhone 6Plus

**Comment by hackiftekhar** [comment]
Which version of library you are using?

**Comment by hoangtam101** [comment]
I got the same issues with IQKeyboardManagerSwift (4.0.6)
Thanks,

**Comment by ICloud0114** [comment]
@hackiftekhar  IQKeyboardManager version is 5.0.7

**Comment by hackiftekhar** [comment]
It shouldn't happen with 5.0.7 I believe. Can you please share demo project?

**Comment by sansali** [comment]
IQKeyboardManager (6.0.3) .    ios 11.2.5 .   
I got the same issues
