### ISSUE TITLE
Expected member name or constructor call after type name

### ISSUE THREAD

**Issue by ghouse1** [hackiftekhar/IQKeyboardManager#1318]
I have converted code from swift 2.3 to swift 4.0 
The below which was working good in swift is showing error Expected member name or constructor call after type name

Swift 2.3
IQKeyboardManager.shared().considerToolbarPreviousNext(inViewClass: SubView)
Here SubView is a UIView Class

How to fix this ??

**Comment by hackiftekhar** [comment]
QKeyboardManager.shared.considerToolbarPreviousNext(inViewClass: SubView)

**Comment by ghouse1** [comment]
The below code is working 
IQKeyboardManager.shared().considerToolbarPreviousNext(inViewClass: SubView.self)
