### ISSUE TITLE
Tapping done button on toolbar causes crash

### ISSUE THREAD

**Issue by JustinBobo** [hackiftekhar/IQKeyboardManager#1321]
<img width="1207" alt="screen shot 2018-04-25 at 12 55 01 pm" src="https://user-images.githubusercontent.com/25378266/39260589-f501c746-4887-11e8-83e1-3fcb31151be5.png">

**Comment by hackiftekhar** [comment]
Not sure what might be issue. Is it 100% reproducible? Can I get a demo project to debug this?

**Comment by hackiftekhar** [comment]
Okay, please share demo and I'll try to check.
