### ISSUE TITLE
收起键盘，界面上移问题

### ISSUE THREAD

**Issue by QQpro** [hackiftekhar/IQKeyboardManager#1324]
### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

**Xcode:** 9.2

**Mac OS:** 10.12.0

**Simulator/Device:** 11.2

**Simulator/Device Name:** All

**Library Version:** 6.0.2

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

当我设置 navigationBar.translucent = NO;和TabBar.translucent = NO;
[TextField becomeFirstResponder];成为第一响应的时候；
收起键盘的时候，我的界面就会上移64px
如果不设置[Field becomeFirstResponder]，我的界面就正常了。
能解决这个问题吗？（我的界面内容不多，只有一个TextField）;

**Comment by iamjia** [comment]
you can do this.
self.extendedLayoutIncludesOpaqueBars = YES;

**Comment by lixianhong1992** [comment]
self.extendedLayoutIncludesOpaqueBars = YES;
 It's not work.

**Comment by panjiulong** [comment]
@iamjia  It's doesn't work

**Comment by panjiulong** [comment]
@lixianhong1992 Have you found a solution?

**Comment by panjiulong** [comment]
@lixianhong1992 
I have found a solution.[https://www.jianshu.com/p/aaa49c409621](url)

**Comment by utopia2006** [comment]
@panjiulong  it works for me,thanks

**Comment by littlepriest** [comment]
@panjiulong It doesn't work...😄

**Comment by hackiftekhar** [comment]
@littlepriest are you sure you are using latest version?

**Comment by littlepriest** [comment]
@hackiftekhar I'll check out and try again. Thanks 😄
