### ISSUE TITLE
iOS11.3.1 version no show Done button

### ISSUE THREAD

**Issue by miniLV** [hackiftekhar/IQKeyboardManager#1325]
**Device Name:** iPhone SE
**Library Version:** 5.0.7

**Comment by hackiftekhar** [comment]
Not sure why it's not working because the fix is there already.

**Comment by sunKit-io** [comment]
I also encountered this problem in the iOS 11 system, other systems did not appear this problem.

**Comment by sunKit-io** [comment]
I was mistaken in the configuration of my files.
If this problem occurs, please change the file configuration to this.
→platform :ios, '8.0'
