### ISSUE TITLE
UIAlertController with style UIAlertControllerStyleActionSheet

### ISSUE THREAD

**Issue by swoot** [hackiftekhar/IQKeyboardManager#133]
If I'm editing a textField, then press a button that shows a modal view (i.e. UIAlertController) and close that, then as the keyboard shows I press the done button on the keyboard -> whole app goes down instead of just the view.

Steps to reproduce with the IQKeyboardManager example project:
1. In SpecialCaseViewController.m, line 116, comment out the UIAlertView and insert

```
        UIAlertController* actionSheet = [UIAlertController alertControllerWithTitle:@"test" message:nil preferredStyle:UIAlertControllerStyleActionSheet];

        UIAlertAction* action = [UIAlertAction actionWithTitle:NSLocalizedString(@"cancel", nil) style:UIAlertActionStyleCancel handler:^(UIAlertAction *action) {
        }];
        [actionSheet addAction:action];

        [self presentViewController:actionSheet animated:YES completion:nil];
```
1. Run.
2. Touch a textField
3. Touch the Custom Work button
4. Touch cancel on the UIAlertController
5. Touch "done" in the keyboard
6. boom.

So, am I doing something wrong in general with showing a modal view like that?

**Comment by RuslanKim** [comment]
ios 9/10.0.1 still a bug in IQK 4.0.5

**Comment by hackiftekhar** [comment]
@RuslanKim Can you share any demo?

**Comment by RuslanKim** [comment]
![2016-09-20_16-01-22](https://cloud.githubusercontent.com/assets/5648249/18664207/c3d4ccba-7f4b-11e6-9bb2-0f51b711bb9a.png)
we have no open source yet, but it seems we have a dialog:
let alert = UIAlertController(
			title: title,
			message: message,
			preferredStyle: UIAlertControllerStyle.Alert)
and if we call in editing mode a dialog 
![2016-09-20_16-02-08](https://cloud.githubusercontent.com/assets/5648249/18664163/bb57e9be-7f4b-11e6-9a41-547fc5759d4b.png)

**Comment by hackiftekhar** [comment]
If you cannot share a demo then I would suggest you to dismiss keyboard explicitly before presenting UIAlertController.

**Comment by RuslanKim** [comment]
It seems like it helps, but I hope it would be fixed .)

**Comment by hackiftekhar** [comment]
If you would like it to be fixed then you should share a demo and I can check if issue exist at library side or apple side.

**Comment by Rotdev** [comment]
@hackiftekhar We had the same issue and implemented the suggested workaround which fortuantely works. In principle we could also send you a version of the project with the bug, but I guess this is unpaid. I think it is described pretty accurately in the thread how you can replicate the bug, so from my point of view you/Apple could easily replicate the bug with about an hours worth of work. So I prefer that second solution, let me hear your thoughts. Thanks.

**Comment by hackiftekhar** [comment]
It would be better if you could share a demo project @Rotdev
