### ISSUE TITLE
If UINavigationBar.isTranslucent == false, view moved to under the navigation bar

### ISSUE THREAD

**Issue by konomae** [hackiftekhar/IQKeyboardManager#1330]
### Description

In the DemoSwift target, I added `UINavigationBar.appearance().isTranslucent = false` to the AppDelegate.

```swift
    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        // Override point for customization after application launch.
        
        IQKeyboardManager.shared.enable = true

        UINavigationBar.appearance().isTranslucent = false

        return true
    }
```

And I do swipe back action in the `Full Screen TextViewController`, the textview position is wrong.

### Steps to Reproduce

1. Add `UINavigationBar.appearance().isTranslucent = false` to the AppDelegate's
2. Run DemoSwift app
3. Select `Full Screen TextViewController`
4. Tap text view and show keyboard
4. Do edge swipe back action

**Expected behavior:** [What you expect to happen]

Should not move the textview to under navigation bar.
There should not be a black bar bottom of the view controller.

**Actual behavior:** [What actually happens]

TextView is moved to under the navigation bar.
There is a black bar bottom of the view controller.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

**Xcode:** 9.3

**Mac OS:** 10.13.4

**Simulator/Device:** 11.3

**Simulator/Device Name:** iPhone 8 Plus

**Library Version:** 6.0.2

### Additional Information

![appvideo2](https://user-images.githubusercontent.com/1920783/39577864-6f5941f4-4f1d-11e8-85bb-d6ddbe5ab9b9.gif)

**Comment by iamjia** [comment]
you can do this.
`self.extendedLayoutIncludesOpaqueBars = YES;`

**Comment by konomae** [comment]
Thank you for the reply!
It works!
