### ISSUE TITLE
Unable to upload to app store

### ISSUE THREAD

**Issue by jkiyomu** [hackiftekhar/IQKeyboardManager#1331]
### Description

When i tried to upload to the app store i get some o-mach errors

### Steps to Reproduce

1. try to upload to app store/test flight

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

**Xcode:** 9.3

**Mac OS:** 10.12.0

**Simulator/Device:** 11.2.6

**Simulator/Device Name:** iPhone 6 plus

**Library Version:** 6.0.1

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by hackiftekhar** [comment]
You haven't describe the o-mach errors relation with this library. Can you please do that. Also I believe if it's happening then it's surely some Xcode settings related issue and not due to the library.
