### ISSUE TITLE
Disable in few controller

### ISSUE THREAD

**Issue by BaoLeiLi** [hackiftekhar/IQKeyboardManager#1332]
### Description

I want to disable it in some controller, I wrote it this way "[[[IQKeyboardManager sharedManager] disabledDistanceHandlingClasses] addObject:[HomeViewController class]]" in AppDelegate, but it doesn't work.

**Expected behavior: Just doesn't work in  HomeViewController

**Actual behavior: All controller enable

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

**Xcode:** 9.3

**Mac OS:** 10.13.3

**Simulator/Device:** 11.3

**Simulator/Device Name:** iPhone 6 and iPhone 7 plus 10.3.3

**Library Version:** 5.0.7

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by hackiftekhar** [comment]
It will disable distance handling not the toolbar, there is something similar method to disable toolbar.

Can you please be sure that the library still maintaining distance handling in your HomeViewController?
