### ISSUE TITLE
Done button invocation (action) not called after update to 6.0.0

### ISSUE THREAD

**Issue by dejanskledar** [hackiftekhar/IQKeyboardManager#1333]
### Description

After upgrading to 6.0.0, the doneBarButton invocation is not called any more. The same code works well on 5.0.8.

### Steps to Reproduce

1. Add target to done button on textField:
`textField.keyboardToolbar.doneBarButton.setTarget(self, action: #selector(done))`

2. After tapping the Done button when the textField is focused, the keyboard dismisses, but the `done` method is not called

**Expected behavior:** `done` method should be called.

**Actual behavior:** `done` method is not called.

**Reproduces how often:** Always

### Versions

**Xcode:** 9.3

**Mac OS:** 10.13.4

**Simulator/Device:** 11.3

**Simulator/Device Name:** iPhone 8

**Library Version:** 6.0.0

### Additional Information

I created a clean new project with the new version and the issue is reproducible.

**Comment by muthusabarinathan** [comment]
Hi @hackiftekhar, Me too getting same issue. I too tried with new project and getting same issue.

**Comment by muthusabarinathan** [comment]
Hi @dejanskledar, Did you fixed this issue?

**Comment by dejanskledar** [comment]
No. I could't make it work on 6.0.0.
I reverted to version 5.0.0 for now.

**Comment by muthusabarinathan** [comment]
Hi @hackiftekhar, Any update on this?

**Comment by hackiftekhar** [comment]
No updates, I'll take a look at it when I get some free time.

**Comment by muthusabarinathan** [comment]
Ok Thanks @hackiftekhar

**Comment by hackiftekhar** [comment]
I got the issue, working on a fix....

**Comment by hackiftekhar** [comment]
Pushed v6.0.3
