### ISSUE TITLE
Next and Previous button is not working on nested stackview

### ISSUE THREAD

**Issue by shaharukhs** [hackiftekhar/IQKeyboardManager#1334]
### Description

[Description of the issue]
- UIStackView
     - UITextField
     - UIStackView
           - UITextField
           - UILabel
     - UITextField
     - UITextField

I have one Parent StackView inside that 3 TextFields and 1 StackView with TextField and Label.

Please check attached video for its behaviour.

[test.mp4.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/1973970/test.mp4.zip)

```
        IQKeyboardManager.shared.enable = true
        IQKeyboardManager.shared.toolbarPreviousNextAllowedClasses.append(UIStackView.self)
        IQKeyboardManager.shared.previousNextDisplayMode = .alwaysShow
```

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

**Xcode:** 9.3

**Mac OS:** 10.13.3

**Simulator:** 11.3

**Simulator:** iPhone 5s

**Library Version:** 6.0.1

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by dejanskledar** [comment]
Try setting the common superview (UIView) to `IQPreviousNextView` in the IB. It should find all the textFields in the subviews.
