### ISSUE TITLE
Statusbar background color issue happening in iOS 11.3

### ISSUE THREAD

**Issue by AnilkumarRabhasa** [hackiftekhar/IQKeyboardManager#1335]
Is there any solution for this following issue.

https://github.com/hackiftekhar/IQKeyboardManager/issues/1158

Still, we are facing issue.

**Comment by hackiftekhar** [comment]
have you tried upgrading to 6.0.2?

**Comment by AnilkumarRabhasa** [comment]
Yes, I did, but still issue happening.  
pod 'IQKeyboardManagerSwift', '6.0.2'

**Comment by hackiftekhar** [comment]
Can you please share demo project here?

**Comment by harjeetk** [comment]
Any Solution for this i am facing a same issue on my side as well sometimes the status bar doesn't get return and on second time it returns
