### ISSUE TITLE
Next, Previos, Done buttons are not visible in toolbar?

### ISSUE THREAD

**Issue by IMHitesh** [hackiftekhar/IQKeyboardManager#1337]
### 
Intially, I has used Xcode 8.2 for  project development But now i want to migrate project into Xcode 9.0

All other stuffs are working fine with Xcode 9.0 but Next, Previos and Done buttons are not visible.

I has tried using new IQKeyboardmanager version but still i am facing same issue.

If i will open project in XCode 8.2 then IQKeyboardManager Working fine with same code.

Version:
Language: Obj C
Xcode: 9.0
Mac OS: 10.12.6
Simulator/Device: 11.2
![iqissue](https://user-images.githubusercontent.com/33254089/39907890-20b8744c-5509-11e8-88ac-7463172fce66.png)

**Comment by hackiftekhar** [comment]
Please update library version to latest 6.0.3

**Comment by IMHitesh** [comment]
I had already tried with latest library but unfortunately got same result

**Comment by IMHitesh** [comment]
@hackiftekhar Thanks for the quick response.

I have resolved  issue by some changes in IQKeyboardManger  library. Changes are as below, If it is proper solution then you can also do required changed in library.

Just goto > IQToolbar.m > layoutSubviews

Replace below code with line number 252 to 270
```

      for (UIBarButtonItem *item in self.items)
    {
        if ([item isKindOfClass:[IQTitleBarButtonItem class]])
        {
            //IMHKSIQKeyborad manager fix
            CGRect titleRect;
            if (IS_IOS_10_LATER) {
                NSInteger intToMinus = 150;
                if (IS_LANDSCAP) {
                    intToMinus = 200;
                }
                titleRect = CGRectMake(x, 0,width-intToMinus, self.frame.size.height);
            }else{
                titleRect = CGRectMake(x, 0, width, self.frame.size.height);
            }
            item.customView.frame = titleRect;
            break;
        }
    }
```

**Comment by hackiftekhar** [comment]
It would be better if you could send me the demo project, I'll check my old code with your demo. Because I was sure my code was working for portrait and landscape also.
