### ISSUE TITLE
Done button setTarget:self action:@selector(SomeAction:) not working

### ISSUE THREAD

**Issue by mohammadrezakhatibi** [hackiftekhar/IQKeyboardManager#1339]
### Description

in IQKeyboardManager for objective-c when I press Done button action not call and keyboard just close.
[textfield.keyboardToolbar.doneBarButton setTarget:self action:@selector(SomeAction:)];

P.S I dont use searchBar.

### Versions

**Xcode:** 9.3

**Simulator/Device:** 11.3

**Simulator/Device Name:** iPhone X

**Library Version:** 6.0.3

### Additional Information

for now I solved this problem with: 
-(void) textFieldDidEndEditing:(UITextField *)textField {
    ...
}
but this solution add extrea code, please show me the right solution.

**Comment by hackiftekhar** [comment]
I fixed this issue with 6.0.3 but if it is still reproducible at your end then can you please share demo project with me?
