### ISSUE TITLE
searchbar offset

### ISSUE THREAD

**Issue by anushkmittal** [hackiftekhar/IQKeyboardManager#1341]
### Description
Offset with searchbar when used in solation

### Steps to Reproduce
Simply install the framework with cocoa pods

**Expected behavior:** [What you expect to happen]
the search bar should be completely vision

**Actual behavior:** [What actually happens]
the search bar is half visible

**Reproduces how often:** [What percentage of the time does it reproduce?]
always

### Versions

**Xcode:** 9.2

**Mac OS:** 10.12.0

**Simulator/Device:** 11.2

**Simulator/Device Name:** iPhone 5s

**Library Version:** 5.0.7

### Additional Information
screenshot for reference

![img_3066](https://user-images.githubusercontent.com/13961658/39963140-6886ffa4-5631-11e8-9919-ce8d2050087b.PNG)

**Comment by hackiftekhar** [comment]
Can you please try with latest version and see if that fixes the issue?

**Comment by anushkmittal** [comment]
My bad, I'm actually using `6.0.3`. I've since made this second VC and the reproducibility of the issue has decreased from 100% to ~40% of the times.

**Comment by hackiftekhar** [comment]
Are you using UIScrollView or UITableView or the search bar is at the bottom? It would be better if I get a demo project to reproduce this issue. I would love to see what calculations are going wrong under the hood.
