### ISSUE TITLE
IQTextView right to left placeholder bug

### ISSUE THREAD

**Issue by kaannesinn** [hackiftekhar/IQKeyboardManager#1342]
Hi, 

When I use IQTextView and its placeholder for my textview on a device that is on Arabic language (or right to left languages), placeholder texts are left hand sided (it is shown like left to right side). In IQTextView class, there is an placeholderLabel that has a frame for left to right alignment, not right to left one. 

I cant change its position outside because didLayoutSubViews methods updates its frame when I want to change its frame. 

Is it possible to be fixed for rtl languages? Btw, IQTextView text is normal but its placeholder has this bug.

**Xcode:** 9.3

**Simulator/Device:** 11.3.1

**Simulator/Device Name:** iPhone 5s

**Library Version:** 5.0.8 or 6.0.3 the same

Thanks

**Comment by hackiftekhar** [comment]
@kaannesinn It's now fixed in master branch and will be available in next release.

**Comment by kaannesinn** [comment]
Thanks @hackiftekhar 

I have downloaded pods library with the version 6.0.4 and have tried it. But the placeholder of the textview is still seen on the left side of the view. After user writes sth, text passes to right and continues like rtl. The fix you made is on swift classes only or you made them to objc classes also? Or does the fix contain this property for the placeholders also?

**Comment by hackiftekhar** [comment]
The changes hasn't been pushed to CocoaPods yet.

**Comment by kaannesinn** [comment]
Oh ok as I guess. Waiting for it.

**Comment by crackTheCode** [comment]
I am using iPhone 8
iOS 13.3.1
and IQKeyboardManager 6.5.5

And I am facing the same problem 

And also on iPhone 6
iOS 12.4.5
It is not showing at all in the box
![IMG_17B819CBB761-1](https://user-images.githubusercontent.com/1030014/77324931-c2e9d080-6d17-11ea-9241-dcd516a9f972.jpeg)
![IMG_0024](https://user-images.githubusercontent.com/1030014/77324937-c54c2a80-6d17-11ea-8e4d-3a0e3b7aed29.PNG)
