### ISSUE TITLE
Weird non scrolling behavior when using a UIScrollView with two UITextViews

### ISSUE THREAD

**Issue by jojonarte** [hackiftekhar/IQKeyboardManager#1344]
### Description

I have a UIScrollView with two UITextViews equally positioned vertically inside it. When focusing on the UITextView at the top then focusing to the bottom UITextView the behavior works fine, as it scrolls the UIScrollView upwards upon focus.

The problem comes when at the start you would try to focus on the bottom UITextView first even if it has contents and the cursor has focused way below, the UIScrollview will not scroll the views up.

### Steps to Reproduce

1. Have two UITextViews vertically aligned and equally sized within a UIScrollView
2. Tap/Focus on the bottom UITextView or even fill it up with texts first before focusing
3. The UIScrollview will not scroll as the keyboard shows.

**Expected behavior:** View scrolls upwards when bottom UITextView is focused

**Actual behavior:** View stays  when bottom UITextView is focused

**Reproduces how often:** Always

### Versions

**Xcode:** 9.2

**Mac OS:** 10.12.0

**Simulator/Device:** 11.2

**Simulator/Device Name:** iPad (5th generation)

**Library Version:** 5.0.7

**Comment by light-bo** [comment]
I also come across the problem too.

**Comment by hackiftekhar** [comment]
@light-bo @jojonarte can one of you share a demo project with me. I'll try to check what might be the cause.

**Comment by hackiftekhar** [comment]
@light-bo @jojonarte I haven't received any demo projects from you guys. Can you please attach demo project?
