### ISSUE TITLE
ios10.0数字键盘遮挡输入框

### ISSUE THREAD

**Issue by 410493897** [hackiftekhar/IQKeyboardManager#1345]
### Description

ios 10.0 UITableView 的 cell 中加了一个UITextView，UITextView的键盘类型是UIKeyboardTypeNumberPad，真机上，点击cell 中的 UITextView，进行编辑，键盘盖住UITextView，UITextView键盘类型是其他类型的，就不会遮挡UITextView，ios 11上UITextView的键盘类型是UIKeyboardTypeNumberPad，也不会遮挡UITextView。

### Versions

**Xcode:** 9.0

**Mac OS:** 10.12.6

**Simulator/Device:** 10.0.3

**Simulator/Device Name:** iPhone 7Plus

**Library Version:** 5.0.7

**Comment by hackiftekhar** [comment]
Please use english and give proper description of the issue.
