### ISSUE TITLE
Textfield covered by keyboard when focused by user tapping on it.

### ISSUE THREAD

**Issue by gmann1** [hackiftekhar/IQKeyboardManager#1347]
### Description

Textfield covered by keyboard when focused by user tapping on it. The textfield is at the bottom of the screen. This only fails when the user focuses the textfield by tapping on it. If the user cycles to the textview using the controls on the toolbar then it works as expected.

### Steps to Reproduce

**Expected behavior:** Content to scroll up so keyboard appears under textfield

**Actual behavior:** Content doesn't move and textfield is covered.

**Reproduces how often:** 100%

### Versions

**Xcode:** 9.2

**Mac OS:** 10.12.0

**Simulator/Device:** 11.3.1

**Simulator/Device Name:** iPhone 6

**Library Version:** 6.0.3

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by shemchavez** [comment]
Is it already fix? If yes link how did he/she did it. Thanks! Having this problem also.

**Comment by gmann1** [comment]
@shemchavez I'm having trouble remembering exactly what the issue was, but I do remember it was not an issue with this library. I _think_ it had something to do with me setting up my scrollview incorrectly (possibly bad constraints). Try setting up your scrollview with a content view if you haven't already, that might be it. Sorry I can't be more help- if I remember I'll be sure to comment here.
