### ISSUE TITLE
Double click num pad will input 3 or 6 when keyboard in animation

### ISSUE THREAD

**Issue by icefox57** [hackiftekhar/IQKeyboardManager#1348]
### Description

Double click num pad will input 3 or 6 when keyboard in animation

![wechatimg186](https://user-images.githubusercontent.com/1716737/40401126-a3b60482-5e77-11e8-985a-bbc0bf80caa8.jpeg)

### Steps to Reproduce

1. [First Step]
Double click num pad

2. [Second Step]
keyboard will show and hide
you will found 3 or 6 or 36 have be entered     

**Expected behavior:** [What you expect to happen]

nothing should be enter ,if user not click the num.

### Versions

**Xcode:** 9.2

**Mac OS:** 10.12.0

**Simulator/Device:** 11.2

**Simulator/Device Name:** iPhone 6/7

**Library Version:** 5.0.7

**Comment by hackiftekhar** [comment]
It looks like it's not related to library since library doesn't handle anything with text inputs. It's managed by the standard keyboard itself.
