### ISSUE TITLE
置底的按鈕無法被看見

### ISSUE THREAD

**Issue by azwb10** [hackiftekhar/IQKeyboardManager#1349]
### Description

我有一份demo
https://www.dropbox.com/s/wfcgdktarcqq7qy/IQKeyboardManagerIssue.zip?dl=0

我的tableview cell中有textfield 當開始編輯時 鍵盤往上彈
但superview中的button在編輯中就看不見了 因為不屬於tableview中的物件
(同展示圖 demoimage3)

謝謝 thanks

### Versions

**Xcode:** 9.3

**Mac OS:** 10.13.2

**Simulator/Device:** 11.3

**Simulator/Device Name:** iPhone X

**Library Version:** 5.0.7

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by hackiftekhar** [comment]
That's correct behavior since library doesn't know anything about the button and you have to write some additional logic to do workarounds.
