### ISSUE TITLE
UIPickerView Support

### ISSUE THREAD

**Issue by fwhenin** [hackiftekhar/IQKeyboardManager#135]
A few of my textfields on the page use a UIPickerView instead of UIKeyboard, which then doesn't show the toolbar...any way to support IQKeyboardManager toolbar to this as well

**Comment by GabrielCartier** [comment]
I started having this issue again. Nothing has changed in my code and the toolbard doesn't show on a picker view. 

I only add the UIPickerView to inputView.

Anyone else ran into the problem?
