### ISSUE TITLE
[IQToolbar release]  crash

### ISSUE THREAD

**Issue by bidm** [hackiftekhar/IQKeyboardManager#1350]
i got this crash when i update IQKeyboardManager and launch my app。

“*** -[IQToolbar release]: message sent to deallocated instance 0x101f70bd0”

MacOS 10.13.4
Device iPhone 6  
iOS 10.3.3

Thank you！

**Comment by hackiftekhar** [comment]
Are you always getting this craah or it was just one timer?

**Comment by bidm** [comment]
Every time. Maybe i get a wrong use with podversion

**Comment by hackiftekhar** [comment]
Are you using latest version? If not then try with latest version if yes then can you please send me demo project?

**Comment by hackiftekhar** [comment]
have you solved the problem @bidm ? how?

**Comment by EternalWill** [comment]
[IQToolbar release]: message sent to deallocated instance 0x14c5bf4c0
macOS10.13.6
iphone6 iOS9.3.2
pod 'IQKeyboardManager','6.1.1' 
object-c and swift

**Comment by JimmyGoGoGo** [comment]
@EternalWill 
Hi.Have you solved it?

**Comment by JimmyGoGoGo** [comment]
@bidm 
Hi.Do you have a clear solution?
