### ISSUE TITLE
Done button action not working in Swift

### ISSUE THREAD

**Issue by anil-irestore** [hackiftekhar/IQKeyboardManager#1353]
Thanks for the great library.

But, the button action for Done is not working.

```
    override func viewDidLoad() {
        super.viewDidLoad()
        self.myTextField.keyboardToolbar.doneBarButton.setTarget(self, action: #selector(doneButtonClicked))
}

 @objc func doneButtonClicked(_ sender: Any) {
        //your code when clicked on done
        
    }

```
The above method is not calling after pressing the Done button.

Any suggestions?

**Comment by anil-irestore** [comment]
I have found solution for this.

https://stackoverflow.com/questions/50622053/done-button-action-from-iqkeyboardmanager-not-working-in-swift

**Comment by hackiftekhar** [comment]
Also looks like your action is incorrect. You wrote #selector(doneButtonClicked) however your method signature should be #selector(doneButtonClicked(:)) because you are expecting one argument.

**Comment by anil-irestore** [comment]
I have already found the solution. Issue with version, after updated version to IQKeyboardManagerSwift 6.0.3, its fixed. Thanks anyway for your reply.
