### ISSUE TITLE
keyboard partially appears

### ISSUE THREAD

**Issue by wbarlet** [hackiftekhar/IQKeyboardManager#1354]
### Description

Only the DONE button appears on iPad 5th Generation

### Steps to Reproduce

1. Compile and run on iPad 5th generation

**Expected behavior:** [Keyboard appears when selecting the textfield]

**Actual behavior:** [keyboard partially appears]

**Reproduces how often:** [Always]

### Versions

**Xcode:** 9.4

**Mac OS:** 11.4

**Simulator/Device:** 

**Simulator/Device Name:** iPad 5th generation

**Library Version:** 

### Additional Information

None
![ipad5th](https://user-images.githubusercontent.com/4702059/40919976-318d1024-67d9-11e8-9607-b20881fa7c1b.png)

**Comment by hackiftekhar** [comment]
It's because the iPhone Simulator is connected to hardware keyboard. This will not be an issue with real devices.

**Comment by wbarlet** [comment]
I got it. Thanks
