### ISSUE TITLE
Not working with iPad view

### ISSUE THREAD

**Issue by SatishMavani** [hackiftekhar/IQKeyboardManager#1355]
I just drag and drop IQKeyboardManager folder from sample app to my Objective-C iPad project. When I run it and check the view with text field it does not move up.

### Steps to Reproduce

UIView is added on UIViewcontroller of iPad screen, at the bottom of the UIView UITextField is there when i click on it keyboard completely covers it.

I am using Xcode 9.3 and my iPad is running on iOS 11.3

Am i missing something? pls help.

**Comment by hackiftekhar** [comment]
You aren't missing anything @SatishMavani I'm not sure why it isn't working for you. Can you please again try with latest master branch code because there was some issues if we pinned constraints to top layout guide, bottom layout guide or safe area. So I fixed that one.

**Comment by hackiftekhar** [comment]
@SatishMavani Have you tried with latest version?
