### ISSUE TITLE
ABORT 6 Xcode 10

### ISSUE THREAD

**Issue by Kgroop** [hackiftekhar/IQKeyboardManager#1359]
### Description

<unknown>:0: error: fatal error encountered while reading from module 'IQKeyboardManagerSwift'; please file a bug report with your project and the crash log

*** DESERIALIZATION FAILURE (please include this section in any bug report) ***
result is ambiguous
0  swift                    0x000000010ea22c5a PrintStackTraceSignalHandler(void*) + 42
1  swift                    0x000000010ea22066 SignalHandler(int) + 966
2  libsystem_platform.dylib 0x00007fff54962f5a _sigtramp + 26
3  swift                    0x000000010f4c7008 (anonymous namespace)::DarwinX86AsmBackend::getCompactUnwindRegNum(unsigned int) const::CU32BitRegs + 101254
4  libsystem_c.dylib        0x00007fff547001ae abort + 127
5  swift                    0x000000010bec899b swift::ModuleFile::fatal(llvm::Error) + 1915
6  swift                    0x000000010bf004d2 swift::SILDeserializer::readGlobalVar(llvm::StringRef) + 1890
7  swift                    0x000000010bfaaf9a swift::SerializedSILLoader::getAllForModule(swift::Identifier, swift::FileUnit*) + 234
8  swift                    0x000000010acfddbe performCompile(swift::CompilerInstance&, swift::CompilerInvocation&, llvm::ArrayRef<char const*>, int&, swift::FrontendObserver*, swift::UnifiedStatsReporter*) + 34750
9  swift                    0x000000010acf210f swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*) + 7839
10 swift                    0x000000010ac9bc48 main + 13144
11 libdyld.dylib            0x00007fff54654015 start + 1
12 libdyld.dylib            0x000000000000005f start + 2879045707

### Versions

**Xcode:** 10

**Mac OS:** 10.12.0

**Simulator/Device:** 12

**Library Version:** 6.0.3

**Comment by hackiftekhar** [comment]
Please attach some more information since I'm unable to understand what's the exact problem is.
