### ISSUE TITLE
SetEnable doesn't work

### ISSUE THREAD

**Issue by tupac19861013** [hackiftekhar/IQKeyboardManager#136]
Please try to test this function a bit more....!!! :)

**Comment by hackiftekhar** [comment]
It enable or disable to manage distance between keyboard and textField. If you want to remove toolbar from textFields then you should use enableAutoToolbar. Please let me know if you need more explanation.

**Comment by tupac19861013** [comment]
Sure, I will go through in this detail and will get back to you. Cheers and a Happy New Year...!!! :)

**Comment by hackiftekhar** [comment]
Happy New Year to you too!!! :)

**Comment by KannanAudhi** [comment]
Hi enableAutoToolbar not working.
