### ISSUE TITLE
IQKeyboardManager (5.0.7) ,enableAutoToolbar属性设置无效  ,系统ios11.4

### ISSUE THREAD

**Issue by tuyongjiang** [hackiftekhar/IQKeyboardManager#1360]
### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

**Xcode:** 9.2

**Mac OS:** 10.12.0

**Simulator/Device:** 11.2

**Simulator/Device Name:** iPhone 5s

**Library Version:** 5.0.7

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by hackiftekhar** [comment]
Please provide more information about the bug

**Comment by githubbiao** [comment]
please reset textView or textField setting
```
textField.inputAccessoryView = nil;
[textField reloadInputViews];
```
