### ISSUE TITLE
[BUG] Part of view is missing, when keyboard is showing and swipe back.

### ISSUE THREAD

**Issue by uziwuzzy** [hackiftekhar/IQKeyboardManager#1361]
### Description
When there's navigation controller, everytime keyboard is showing, and swiping back is used, some part of the view is missing.
[Description of the issue]

### Steps to Reproduce

1. Create Two ViewControllers with NavigationBar in it, lets say "FirstVC" and "SecondVC", and then give SecondVC a textfield.
2. FirstVC push to SecondVC
3. Click the textfield to make keyboard show up
4. while keyboard is showing up, swipe slowly a little bit until FirstVC is shown, but don't let the screen move back to firstVC.
5. then the bug occured, where bottom or top layout is black.

**Expected behavior:** [there's no black part, the view should act normal when navigating through swiping]

**Actual behavior:** [everytime keyboard is showing, and swiping back is used, some part of the view is missing]

**Reproduces how often:** [100%]

### Versions

**Xcode:** 9.4

**Mac OS:** 10.13.5 

**Device:** 11.3

**Device Name:** iPhone 5se

**Library Version:** 6.0.3
### Additional Information

This are sample demo, in this sample, the bug will go away when we push the SecondVC again, but In the app that I build, the bug itself always persist eventhough the view reappeared, and it sometimes occured in the top part or the bottom part.
the sampe code:
[TesKyeboard.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/2084476/TesKyeboard.zip)

sample videos how to reproduce:
[bugKeyboard.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/2084467/bugKeyboard.zip)

[bugKeyboardSample.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/2084511/bugKeyboardSample.zip)

**Comment by achalkias** [comment]
Same issue here is there any update with this because it's really frustrating. I am unable to publish my apps as long as this bugs still occurs.
**HOPE FOR A SOLUTION!**

**Comment by pmusolino** [comment]
Same behavior here

**Comment by hackiftekhar** [comment]
okay, let me take a look into this.

**Comment by hackiftekhar** [comment]
I found the cause, unfortunately it's hard to write workaround for that. What actually happens under the hood is, the gesture change the rootViewController.view's frame.

So here is the execution step by step:
- tap on textField.
- Library save view's current origin (0,0) and moves view's origin to (0,-44) to see textField correctly.
- apply pop gesture.
- `keyboardWillHide` called and app restore view's origin to (0,0).
- cancel pop gesture.
- `textFieldViewDidBeginEditing` called and again library tries to save view's current origin. But here the library finds that current view origin is (0,-44). Here is the problem.

Because that origin value comes from view.frame.origin so library think that it should be the correct value for view origin and we should restore view to this origin on textField dismiss.

**Comment by hackiftekhar** [comment]
I wrote a patch to workaround this issue. Now if library detects that user is applying interactivePopGesture of it's navigationController then library will save `topViewBeginOrigin` in `topViewBeginOriginWhilePopGestureRecognizerActive` and `rootViewController` in `rootViewControllerWhilePopGestureRecognizerActive` weak variable.
Now when gesture has ended and next time textField becomes first responder then if `rootViewController == rootViewControllerWhilePopGestureRecognizerActive` we assign `topViewBeginOrigin = topViewBeginOriginWhilePopGestureRecognizerActive`. So it did the tweak.

**Comment by pmusolino** [comment]
@hackiftekhar when do you have in plan to release this new version?

**Comment by hackiftekhar** [comment]
I'm planning to release this in couple of days (after checking/fixing couple of more issues).

**Comment by uziwuzzy** [comment]
any news about the release for this issue?

**Comment by hackiftekhar** [comment]
This is already released I think.

**Comment by calhouncole** [comment]
I'm still able to repro this issue after the latest release (6.2.0). Has this been fixed for anyone else?

**Comment by hackiftekhar** [comment]
Then can you please share demo project @calhouncole ?

**Comment by uziwuzzy** [comment]
For me, the solution is to dismiss the keyboard on viewWillDissappear

**Comment by douglasjunior** [comment]
Any updates on this? 

@hackiftekhar I think that @uziwuzzy have shared a demo project here: https://github.com/hackiftekhar/IQKeyboardManager/files/2084476/TesKyeboard.zip
