### ISSUE TITLE
How to change previous and next button arrows  ?

### ISSUE THREAD

**Issue by X901** [hackiftekhar/IQKeyboardManager#1363]
Hi , 

I want to change previous and next button arrows 
from **Top** and **Bottom** 
to **Right** and **Left** 

is there a way to change the image or text of previous and next button ??

**Comment by hackiftekhar** [comment]
There is an option for changing done button image/title, however currently there is no such workaround exist for previous/next buttons. Will try to add this feature in upcoming release.
