### ISSUE TITLE
Strange behavior with big UITextView

### ISSUE THREAD

**Issue by maxgarmar** [hackiftekhar/IQKeyboardManager#1364]
### Description

Strange animation when there is a really, really big UITextView. Seems like the library try to show the whole UITextView as it was an small one, so it is going up and down really fast.

### Steps to Reproduce

1. Create a big UITextView inside UIScrollView. 2000 as Height for instance, so the scrollview will adjust to be as big as the innerview
2. Fill the UITextView with text at the end of it. You can press enter until you reach the last line and write something on it. Resign the textview, just pressing outside of the textview as your library does by default setting it.
3. Scroll down the Scrollview until you reach the end of the scroll view and also you see the end of the UITextView.
4. Then, press the text in the end of the uitextview so it does the strange behavior I am trying to describe.

**Expected behavior:** 

Act like when the uitextview is small just move the textview above the keyboard.

**Actual behavior:**

It moves up and down the whole uitextview so it makes a strange behavior

**Reproduces how often:**

Always

### Versions

**Xcode:** 9.4

**Mac OS:** 10.13.5

**Simulator/Device:** Any

**Simulator/Device Name:** Any

**Library Version:** Latest by pods

### Additional Information

I will send you a video to the contact email so you can see the what actually happens. Please let me know if you need something else from me to reproduce it. Great library ! keep coding !

Thanks!

**Comment by hackiftekhar** [comment]
@maxgarmar  can you please provide a demo project to reproduce the issue?

**Comment by maxgarmar** [comment]
Hi @hackiftekhar,

First of all, thanks for keeping track of this. Sure, I attach the project here so you can see it. 
The way to reproduce the issue is:

- Start the project in iPhone 8 plus simulator for example
- Activate the keyboard to be shown in simulator
- Activate slow animations to see the issue better
- The UITextView in the end of the scrollView is the one with the issue, so before you press the uitextview, first go until the end of the scrollview so you can see the end of the uitextview. Then, press the uitextview like if you want to edit the last line of the text inside the uitextview, then you see how it goes up and down when the keyboard appears. The expectation for me would be that the uitextview just moves up to be on the top of the keyboard but not doing such of movements before up and down.

Let me know if you need any clarification on this.

Keep Coding !

Thanks!
[demo.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/2149031/demo.zip)

**Comment by hackiftekhar** [comment]
Thanks for the demo project @maxgarmar I'll see the demo.

**Comment by hackiftekhar** [comment]
I checked the demo and the library logic is to move the top most UIScrollView which is your main scrollView in this case. If you don't want to scroll that scrollView when keyboard appears then you have to se `scrollingEnabled=false/true` on scrollView by observing textField active and resign events using delegates.
