### ISSUE TITLE
why can't see previous and next button?

### ISSUE THREAD

**Issue by yushan023** [hackiftekhar/IQKeyboardManager#1366]
### Description

[Description of the issue]
I put the textField in UIView. 
ScrollView can't listen to the inside of the UIView textField.
我的界面层级是   textField放到自定义的UIView里面   然后 scrollView再添加UIView。
这个时候toolbar里面的上一个下一个按钮就出不来了。

<img width="500" alt="image" src="https://user-images.githubusercontent.com/20593532/41336786-d01b11da-6f1f-11e8-9286-51dc45dd7f59.png">

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

**Xcode:** 9.2

**Mac OS:** 10.12.0

**Simulator/Device:** 11.2

**Simulator/Device Name:** iPhone 5s

**Library Version:** 5.0.7

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by hackiftekhar** [comment]
Can you please check the library asset bundle is in your project or not? Because the library asset bundle contains those images.

**Comment by hackiftekhar** [comment]
It might be because your textFields are not in same superview. To workaround this situation, you have to add IQPreviousNextView as superview of all your view. It will add previous/next buttons on textFields which are inside this view.
