### ISSUE TITLE
Navigation bar no longer goes up with rest of screen

### ISSUE THREAD

**Issue by ETGgames** [hackiftekhar/IQKeyboardManager#1368]
In the new version, the nav bar no longer goes up. Is there a special setting for this? It used to, and now it looks bad. Thanks.

**Comment by hackiftekhar** [comment]
It's the new behaviour of library in 6.0.0 since a lot of people requested this feature. Unfortunately there is no way to go back. You have to use older versions to see previous behaviours. If you would like to use new version then please read 6.0.0 migration guide wiki page.
