### ISSUE TITLE
UITextFields in UIViewController

### ISSUE THREAD

**Issue by fwhenin** [hackiftekhar/IQKeyboardManager#137]
I have a login screen of just a UIViewController with 3 UITextfields in them...does IQKeyboardManager support getting the textboxes out of the way then, because that's not happening. Any ideas what I need to do.

Things you should know:
1- I have Constraints between the textboxes, but not constraints to the superView.
2- I tried adding those fields in a UIScrollView and that still doesn't work

**Comment by hackiftekhar** [comment]
May be you are pinning your textField constraint to topLayout guide, if NO, then could you please share demo code?

**Comment by hackiftekhar** [comment]
Any updates or you fixed this issue by fixing your autolayout configuration?

**Comment by fwhenin** [comment]
it hasn't been fixed yet, but I can't really share code since it's a xib file. I removed all constraints except the width of one text field...SHOULD the page be scrolled automatically? maybe I'm expecting this code to do something it doesn't. or maybe I do need a UIScrollView

**Comment by fwhenin** [comment]
![image](https://cloud.githubusercontent.com/assets/1904203/5631410/546787b6-9594-11e4-8a60-a6010d139e11.png)

**Comment by fwhenin** [comment]
![screenshot 2015-01-06 11 06 01](https://cloud.githubusercontent.com/assets/1904203/5631424/6feeb11c-9594-11e4-95f6-97e8e8f211b8.png)

**Comment by hackiftekhar** [comment]
I think you are going right, Library must move textField out of the way, but still I need a demo project to debug it. Could you please create a separate demo project to demonstrate the issue and share with me?

**Comment by fwhenin** [comment]
so I just made a demo project...and it works...something with my code...I have no idea what it could be

**Comment by fwhenin** [comment]
I'm trying to figure out what other pods are conflicting with this...same issue with the UIPickerView not having the accessory bar...I'm using XLForm, but the accessory bar shows up in their textfields normally...and they use a UIViewController

**Comment by hackiftekhar** [comment]
Try adding pod one by one in demo project. seems some issue with your project not in the library, because demo is working fine.

**Comment by fwhenin** [comment]
HOLY CRAP.....yeah, I'm an idiot, I was inheriting from UITableViewController for some reason...once I changed it to UIViewController, everything worked. thank you for your help man. Sorry about that

**Comment by hackiftekhar** [comment]
Thanks bro, I would love to help you when you are in trouble.

**Comment by fwhenin** [comment]
side-note, XLForm conflicts when it comes to a Selector View...the toolbar doesn't show up there...looking into a fix for that
