### ISSUE TITLE
Not able to install the latest version (>6.0.0) of IQKeyboardManager through pods

### ISSUE THREAD

**Issue by ShikharQuovantis** [hackiftekhar/IQKeyboardManager#1370]
### Description

I have installed the latest Xcode 10 beta version and then made the change in the podfile for downloading the specific version of the library pod by writing  'IQKeyboardManagerSwift', '6.0.0'.
However, on running pod install the terminal keeps giving the error "CocoaPods could not find compatible versions for pod "IQKeyboardManagerSwift": On Podfile: IQKeyboardManagerSwift (= 6.0.4)".

How do I install this particular version into my project.

### Steps to Reproduce

**Expected behavior:** 

**Actual behavior:** 

**Reproduces how often:**

### Versions

**Xcode:** Version 10.0 beta 2 (10L177m)

**Mac OS:** 10.13.5 (17F77)

**Simulator/Device:** 11.2

**Simulator/Device Name:** iPhone X

**Library Version:** 6.0.0

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by hackiftekhar** [comment]
Your deployment target might be below iOS8. You may also need to run 'pod update' to update cocoapods list.

**Comment by ShikharQuovantis** [comment]
@hackiftekhar No. My deployment target has always been iOS 11.0

**Comment by hackiftekhar** [comment]
Ten try running pod update.
