### ISSUE TITLE
Previous next distance keep growing

### ISSUE THREAD

**Issue by pgawlowski** [hackiftekhar/IQKeyboardManager#1371]
### Description

On a view with scrollView, when I press a lot up and down buttons the first scroll distance is constantly growing every up down click iteration is causing bigger and bigger bounce effect. 

### Steps to Reproduce

1. Click next
2. Click previous
3. Loop fast - distance is growing

**Expected behavior:** 
Same distance every click

**Reproduces how often:** 
Always

I did some digging in your code. The problem seems to be here. 

![screen shot 2018-06-25 at 13 26 51](https://user-images.githubusercontent.com/9845024/41847774-831b8c06-787b-11e8-8ad1-3952f0c5585e.png)

> Need to move: 174.5
> Need to move: -344.5
> Need to move: 340.5
> Need to move: -510.5
> Need to move: 506.5
> Need to move: -676.5
> Need to move: 672.5
> Need to move: -842.5

Need to move value keeps growing when we press next, previous buttons.

**Comment by hackiftekhar** [comment]
Can you please share a demo project with me?

**Comment by hackiftekhar** [comment]
Thanks @pgawlowski I'll check the demo.

**Comment by hackiftekhar** [comment]
This issue is something related to #1365 we are discussing there.
