### ISSUE TITLE
iPhone X keyboard issue

### ISSUE THREAD

**Issue by preetamjadakar** [hackiftekhar/IQKeyboardManager#1372]
### Description

Tried using `IQKeyboardManagerSwift (6.0.3)` but the issue still persist on iPhoneX
### Steps to Reproduce

Issue Sample:
https://www.dropbox.com/s/7g78ydzf0i9n4m6/NedPay.zip?dl=0

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

**Xcode:** 9.4

**Mac OS:** 10.12.0

**Simulator/Device:** 11

**Simulator/Device Name:** iPhoneX

**Library Version:** 6.0.3

![simulator screen shot - iphone x - 2018-06-27 at 15 44 57](https://user-images.githubusercontent.com/3962731/41968562-6c8eadd0-7a22-11e8-86a2-0d5fbd29c83b.png)

**Comment by hackiftekhar** [comment]
Can you please try with the latest master version, I remembered I fixed this issue however it's not pushed to CocoaPods yet.

**Comment by preetamjadakar** [comment]
Awesome! 
Commit https://github.com/hackiftekhar/IQKeyboardManager/commit/9bb0f564c95fd6f015775c289f4d228658c006de helped.

Thanks.
