### ISSUE TITLE
  The 6.0.4 version sets the keyboardDistanceFromTextField property. When the input box is entered, this property will fail.

### ISSUE THREAD

**Issue by anyifeihewenjie** [hackiftekhar/IQKeyboardManager#1374]
### Versions
**Xcode:** 9.4.1
**Mac OS:** 10.13.5
**Simulator/Device:** 11.1
**Simulator/Device Name:** iPhone 6
**Library Version:**6.0.4

**Comment by hackiftekhar** [comment]
Please explain in more details.
