### ISSUE TITLE
6.0.4 version, when the page has a navigation bar, the keyboardDistanceFromTextField property is set, and the page will be offset when you are entering the page.

### ISSUE THREAD

**Issue by anyifeihewenjie** [hackiftekhar/IQKeyboardManager#1375]
[TestProject.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/2148572/TestProject.zip)

**Describe the bug**
6.0.4 version, when the page has a navigation bar, the keyboardDistanceFromTextField property is set, and the page will be offset when you are entering the page. See demo

**To Reproduce**
1. Click the input box
2. Input content
3. See error
### Versions
**Xcode:** 9.4.1
**Mac OS:** 10.13.5
**Simulator/Device:** 11.1
**Simulator/Device Name:** iPhone 6
**Library Version:** 6.0.4

**Comment by hackiftekhar** [comment]
Thanks for the demo project. I'll take a look at it.

**Comment by hackiftekhar** [comment]
I'm not sure what exactly might be the issue, but to load a customize view for viewController, we load it in `-(void)loadView` method. if you move `self.view = self.loginView;` call from viewWillAppear to loadView method like below, the jumping issue get's solved.
```
- (void)loadView
{
    self.view = self.loginView;
}
```
