### ISSUE TITLE
There is a bug when application enter foreground

### ISSUE THREAD

**Issue by peanutNote** [hackiftekhar/IQKeyboardManager#1377]
**Describe the bug**
The view with textField will restored when application enter foreground.

**To Reproduce**

1. Add a UITextField at the bottom of a view which have navigation bar, when the textField became first responder, IQKeyboardManager will make the view move up.
2. Make the application enter background and back to the foreground, the view just moved restored.

### Versions
**Xcode:** 9.4
**Mac OS:** 10.13.5
**Simulator/Device:** 11.4
**Simulator/Device Name:** iPhone X
**Library Version:** 6.0.4

**Additional context**
My Console Will also prints"+[CATransaction synchronize] called within transaction"sometimes.

**Comment by svyatoslav-reshetnikov** [comment]
Any solutions?

**Comment by praveend123** [comment]
Any resolution on this?

**Comment by AmrAbedal** [comment]
Any solution ?

**Comment by bark1n9** [comment]
@hackiftekhar This issue still seems to be happening, any workarounds?

**Comment by svyatoslav-reshetnikov** [comment]
Hi! I removed this library from my project and wrote code for manage keyboard manually. I know that this isn’t a solution of the problem, but it was the only way for me.

**Comment by shamiulrain** [comment]
@hackiftekhar any workarounds?
or 
Do you have any plan to give us a version where this bug will be fixed?
Thanks in advance.....
