### ISSUE TITLE
Can't find keyplane that supports type 4 for keyboard iPhone-PortraitTruffle-NumberPad; using 6919991127445953680_PortraitTruffle_iPhone-Simple-Pad_Default

### ISSUE THREAD

**Issue by jeffayan** [hackiftekhar/IQKeyboardManager#1379]
Can't find keyplane that supports type 4 for keyboard iPhone-PortraitTruffle-NumberPad; using 6919991127445953680_PortraitTruffle_iPhone-Simple-Pad_Default

**Comment by hackiftekhar** [comment]
That's not something we can do, this message comes from iOS SDK and not by library.
