### ISSUE TITLE
setCanAdjustTextView:NO doesn't work.

### ISSUE THREAD

**Issue by JamalK** [hackiftekhar/IQKeyboardManager#138]
Hello,
Thank you for the amazing control. i'm facing an issue where I have a TextView that keeps scrolling, and adjusting itself, even though, setCanAdjustTextView is no. I tried also to set enable to NO, and it didn't help. How should I go about this?

**Comment by hackiftekhar** [comment]
Let me know what are you trying to achieve. canAdjustTextView adjust the frame of texView when textView height is too big to fit in screen.

**Comment by JamalK** [comment]
I mean, that when the user starts typing in textview, it starts scrolling automatically, even though the scrolling behavior is disabled in the textview.

**Comment by hackiftekhar** [comment]
Could you please demonstrate 2 videos how you want to achieve and where the problem is?

**Comment by JamalK** [comment]
I just fixed it, sorry it was my problem, I suspected the control. Thank you so much for the support :+1:

**Comment by JamalK** [comment]
Sorry, it just happened again, 
This is a link for a gif of what's going on
![gif image] (http://cl.ly/image/462M0a0m382x/Screen%20Recording%202015-01-05%20at%2010.10%20PM.gif)

I want it not to scroll, even though the textview is disabling scroll.

**Comment by hackiftekhar** [comment]
Thanks for the gif, could you please attach demo project so I can debug it?

**Comment by hackiftekhar** [comment]
@JamalK Please provide me example code to debug it.

**Comment by hackiftekhar** [comment]
@JamalK  Any updates regarding textView scrolling issue? Could you please provide me sample code?

**Comment by JamalK** [comment]
I'm sorry, I have been  trying over, and over the reproduce the same bug, but I couldn't. However it still scrolls in my original project, and stops when I remove the dependency.

**Comment by hackiftekhar** [comment]
You may try to debug this method in both demo and original project:-

IQKeyboardManager.m 
-(void)textFieldViewDidChange:(NSNotification*)notification

**Comment by JamalK** [comment]
I just fixed it using.
textView.contentInset=UIEdgeInsetsZero;
 Thank you so much for the support! Really amazing control. I'm going to use it whenever I have issues with keyboard

**Comment by hackiftekhar** [comment]
Thanks @JamalK, let me know if the issue is related to some library code, so I that I'll update it.
