### ISSUE TITLE
Can't find next and previous buttons?

### ISSUE THREAD

**Issue by vamshigupta8** [hackiftekhar/IQKeyboardManager#1380]
**Describe the bug**
Can't find next and previous buttons?

Please find the hierarchy i was using in attachment..
Previous and next buttons are disabled not showing up..
Only i can see the done button..

<img width="344" alt="screen shot 2018-07-05 at 6 36 47 pm" src="https://user-images.githubusercontent.com/39979680/42325104-d45a61b4-8082-11e8-9d97-9effad65fef2.png">

### Versions
**Xcode:**  9.4
**Mac OS:** 10.13.5
**Simulator/Device:** iphone6
**Library Version:** current version

**Comment by hackiftekhar** [comment]
That's because your textFields superview are different. Try to add IQPreviousNextView above your MAIN STACK and it will fix your issues.

**Comment by vamshigupta8** [comment]
Fixed it thanks a lot..
