### ISSUE TITLE
 The controller pops up the keyboard and then returns, and the controller's interface will appear to be black.

### ISSUE THREAD

**Issue by panjiulong** [hackiftekhar/IQKeyboardManager#1381]
**Describe the bug**
 I create a new project and then customize the UINavigationController, set navigationBar.isTranslucent = false. Integrate IQKeyboardManagerSwift. If the page pops up after the keyboard pops up, it will be found that the ViewController's view is moved down when it returns. A black box is getting higher. I found The solution is extendedLayoutIncludesOpaqueBars = true But I want IQKeyboardManagerSwift to adapt itself?
**To Reproduce**
2. Click on ''
3. Scroll down to ''

**Expected behavior**

**Screenshots**

**Demo Project**
If applicable, add demo project.

### Versions
**Xcode:** 9.4.1
**Mac OS:** 10.13.5
**Simulator/Device:** 10.0
**Simulator/Device Name:** iPhone 8
**Library Version:** x.x.x

**Additional context**

**Comment by hackiftekhar** [comment]
Are you trying your textField to becomeFirstResponder from viewDidLoad?
