### ISSUE TITLE
Some problem with using UITextView

### ISSUE THREAD

**Issue by GodWolf** [hackiftekhar/IQKeyboardManager#1382]
**Describe the bug**
In a view controller,i add a UITextView with more than half of the controllerView`s height.When i input some words,the textView will move up some distance until i can`t see the navigation bar。

![image](https://user-images.githubusercontent.com/9720928/42364088-907c2fea-812c-11e8-8a94-43efa611db95.png)
![image](https://user-images.githubusercontent.com/9720928/42364103-995a443a-812c-11e8-9272-bb8b4c34d37d.png)

**Comment by hackiftekhar** [comment]
Which version of library you are using? Can you please try using latest version?

**Comment by GodWolf** [comment]
Thanks for replying! I use CocoaPods to installing,but the latest version is 6.0.3.When i use 6.0.5 by manual,it also exist a problem. The textView`s  cursor is under the navigation bar.
![image](https://user-images.githubusercontent.com/9720928/42496832-e0c8f08e-8459-11e8-90db-f4ee079fdbf1.png)

**Comment by hackiftekhar** [comment]
Can you please share demo project so that I can debug about what might be the cause of this issue?

**Comment by ahmedAlmasri** [comment]
+1

**Comment by hackiftekhar** [comment]
I fixed an issue for non-translucent navigation bar. Can you please check if this solve your problem?
