### ISSUE TITLE
not optimized for iPhone X

### ISSUE THREAD

**Issue by bubblespuggy** [hackiftekhar/IQKeyboardManager#1383]
**Behavior**
When using on iPhone X the textField doesn't move up as much as it should.

**Steps to reproduce the behavior:**
1. Implement IQKeyboardManager in new Project
2. Create UITextField on Storyboard
3. Run application with iPhone X Simulator

**Expected behavior**
Normally it should move a few pixels higher.

**Screenshots**
<img width="354" alt="screen shot 2018-07-07 at 15 06 15" src="https://user-images.githubusercontent.com/32460316/42411155-5a51aa82-81f7-11e8-98cf-6da1ca47729e.png">

### Versions
**Xcode:** 9.4.1
**Mac OS:** 10.13.5
**Simulator/Device:** 11.4
**Simulator/Device Name:** iPhone X
**Library Version:** 5.0.7

**Comment by hackiftekhar** [comment]
Please use latest master for now, it has a fix.

**Comment by damirstuhec** [comment]
@hackiftekhar Could you make a new official release to get those fixes in, so we don't have to reference a branch?
