### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by gilroykilroy** [hackiftekhar/IQKeyboardManager#1384]
In file included from /App/Carthage/Checkouts/IQKeyboardManager/IQKeyboardManager/Categories/IQNSArray+Sort.m:25:
/App/Carthage/Checkouts/IQKeyboardManager/IQKeyboardManager/Categories/IQUIView+Hierarchy.h:117:12: error: definition of 'UIViewController' must be imported from module 'UIKit.UIViewController' before it is required
@interface UIViewController (IQ_UIView_Hierarchy)

**Comment by hackiftekhar** [comment]
Very sorry about this issue. Just pushed v6.0.6 with this fix.
