### ISSUE TITLE
can't find IQKeyboardMangerSwift

### ISSUE THREAD

**Issue by sepandy** [hackiftekhar/IQKeyboardManager#1385]
I was using IQKeyboardMangerSwift which I added with Carthage just find but when I updated my Carthage to add another framework IQKeyboard got upgraded from 6.0.4 to 6.0.6 and since then I got the error that swift can not compile IQKeyboard and in AppDelegat I got the error that the could not find IQKeyboardManagerSwift

**Comment by sepandy** [comment]
I did all I could but could not silence the error I even made another project and copied all my files to that one and then added IQ but still got the swift can not compile error in the end I gave up on it and commented the import IQKeyboardMangerSwift and IQKeyboardManager.shared.enable = true but surprisingly the IQKeyboard still works

**Comment by hackiftekhar** [comment]
Strange, I think this all relates to some of your project configuration or something else.
