### ISSUE TITLE
iPhone 6s 输入框被遮住

### ISSUE THREAD

**Issue by VinlorJiang** [hackiftekhar/IQKeyboardManager#1386]
UITableView custom cell nested UITableView, in which there are multiple UITextField input boxes in the nested UITableView. When the iPhone 6S device is used, a keyboard pops out of the input box, such as:
UITableView自定义cell嵌套UITableView，其中被嵌套的UITableView中有多个UITextField输入框，在iPhone 6s设备使用的时候，出现键盘弹出挡住了输入框，如图：

### Versions
**Xcode: 9.3
**iPhone 6s, iOS 11.2  / iOS 11.4

**Comment by VinlorJiang** [comment]
![Uploading keyboard_show.jpg…]()

**Comment by hackiftekhar** [comment]
@VinlorJiang screenshot hasn't been uploaded correctly. Can you please re-upload?
