### ISSUE TITLE
Wrong keyboard layout when split-view mode is enabled

### ISSUE THREAD

**Issue by av-ivashchenko-sigma** [hackiftekhar/IQKeyboardManager#1388]
Duplicating from [stackoverflow question](https://stackoverflow.com/questions/51325702/iqkeyboardmanager-wrong-keyboard-layout-when-split-view-is-enabled)

**Issue**
I am experiencing a strange issue using IQKeyboardManager when keyboard split mode is enabled.
Keyboard's background isn't transparent: 
[Wrong keyboard's background view (Image link)](https://imgur.com/a/JrJcyjn)

**To Reproduce**
```
//AppDelegate.swift
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
    ...
    IQKeyboardManager.shared.enable = true
    ...
}

//ViewController.swift
override func viewDidLoad() {
    ...
    textField.keyboardDistanceFromTextField = 140 // or any constant
    ...
}
```

**Expected behavior**
Keyboard's background is transparent (like when IQKeyboardManager is not used).
[Correct keyboard's background view (Image link)](https://imgur.com/a/Cq9En4F)

Any suggestions? Thanks!

### Versions
**Xcode:** 9.4.1
**Mac OS:** 10.13.6
**Simulator/Device:** Simulator iPad (5th generation)
**Library Version:** 6.0.4

**Comment by hackiftekhar** [comment]
That's expected, because we have toolbar at top of keyboard. If there will be no toolbar then the area will be transparent.

**Comment by av-ivashchenko-sigma** [comment]
Yes, this helped me:
`IQKeyboardManager.shared.enableAutoToolbar = false`
Thank you!
