### ISSUE TITLE
Tapped the textField in the tableView, and then crash.

### ISSUE THREAD

**Issue by ChiehYiHuang** [hackiftekhar/IQKeyboardManager#1389]
I've read the file "README.md" in IQKeyboardManager.

It said if I wanna use the delegate -textFieldShouldBeginEditing:textField, I have to import IQUIView+Hierarchy.h and check for isAskingCanBecomeFirstResponder.

I cannot find out "isAskingCanBecomeFirstResponder" but "canBecomeFirstResponder" in the method. so I replace "isAskingCanBecomeFirstResponder" to "canBecomeFirstResponder" in my project. 

When I run the project and click the Textfield which I wanna custom activity, in delegate -textFieldShouldBeginEditing:textField will run again and again until crash. 

Does anyone help me figure out the problem? PLZ 

### Versions
**Xcode:** 9.4.1
**Mac OS:** 10.13.5
**Simulator/Device:** 10.3.2
**Simulator/Device Name:** iPhone SE

**Comment by ChiehYiHuang** [comment]
So what should I do to fix the problem?

**Comment by hackiftekhar** [comment]
Remove all the validations and it should work perfectly.
