### ISSUE TITLE
Disable for a ViewController failed

### ISSUE THREAD

**Issue by yidahis** [hackiftekhar/IQKeyboardManager#139]
I create new project and do this:
`- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {`
   ` // Override point for customization after application launch.`
    ` [[IQKeyboardManager sharedManager] setEnable:NO];`
    `return YES;`
`}`
But it doesn't work.

**Comment by hackiftekhar** [comment]
Please note, this will disable managing distance between keyboard and textField, but if you also want to remove toolbar then please use enableAutoToolbar property. Please let me know if you are talking about something else.

**Comment by yidahis** [comment]
On the beginning, i didn't understand this  api and now i get it. Thanks.
