### ISSUE TITLE
App freezes/hangs!

### ISSUE THREAD

**Issue by iamsanketray123** [hackiftekhar/IQKeyboardManager#1390]
**Describe the bug**
App screen freezes sometimes and the keyboard doesn't come up!

**To Reproduce**
Haven't been able to reproduce this on my end. Some users of my app have complained about this. They were using iPhone 6S and 6S+

**Expected behavior**
Keyboard should come up without any lag or hang whatsoever

### Versions
**Xcode:** 9+
**Mac OS:**  High Sierra
**Simulator/Device:** Device
**Simulator/Device Name:** iPhone 6S/ iPhone6S+
**Library Version:**

**Comment by hackiftekhar** [comment]
As I'm having other duties though my day, so usually I don't have much time to spend on creating demo and trying to reproduce issues. I'll need demo project and steps to reproduce from you guys to help on issues. Can you please help me on this?

**Comment by iamsanketray123** [comment]
I understand your pain. Even I was unable to recreate this. The only reason I created this issue was because, I expected maybe you had resolved similar cases earlier. I will try to recreate and get back to you :+1:

**Comment by hackiftekhar** [comment]
sure!

**Comment by iamsanketray123** [comment]
@hackiftekhar Hey, i haven't been able to recreate my issue, but there is a possibility that this happens in "release mode" and not in "debug mode". Do you think its possible. And I came across this post on StackOverflow. Do you think it would help fix the issue? Sorry, I am relatively new to iOS development.
Mine doesn't crash, rather it hangs for some seconds.

https://stackoverflow.com/questions/3327981/app-runs-as-debug-but-crashes-as-release

**Comment by hackiftekhar** [comment]
That might happen. But still I can't do anything without demo.

**Comment by Emailrus** [comment]
@iamsanketray123 Are there any errors in console after that freeze? Something like "Execution of the command buffer was aborted due to an error during execution. Caused GPU Timeout Error" ?
