### ISSUE TITLE
crash when use IQKeyBoardManager

### ISSUE THREAD

**Issue by Manloff** [hackiftekhar/IQKeyboardManager#1391]
**Describe the bug**

When I write some code of IQKeyboardManager, my app will crash. No matter setEnable yes or no.
When I click the textfield for edit it, my app will crash.
like this:
-[UITextField viewContainingController]: unrecognized selector sent to instance 0x10b08d200

**To Reproduce**
* click on a textfield

**Demo Project**
I had write a demo for test, but it don't crash

### Versions
**Xcode: 9.4.1
**Mac OS:10.13.6
**Simulator/Device:iOS 11
**Simulator/Device Name: iPhone 7, iPhone 6p, simulators: iPhone 6s, iPhone 8
**Library Version:6.1.0

**Screenshots**
<img width="846" alt="2018-07-18 3 03 28" src="https://user-images.githubusercontent.com/12522976/42865408-25aff92a-8a9c-11e8-8a3d-a3006c252d3a.png">

**Comment by hackiftekhar** [comment]
Make sure your project include `IQUIView+Hierarchy` files.

**Comment by Manloff** [comment]
yeah, I import it use cocoapods
<img width="818" alt="2018-07-18 5 54 40" src="https://user-images.githubusercontent.com/12522976/42874422-b26fd65c-8ab3-11e8-80f7-4b8351907dd8.png">

<img width="1026" alt="2018-07-18 5 50 41" src="https://user-images.githubusercontent.com/12522976/42874307-5a3afc14-8ab3-11e8-96ab-ffe547af67c6.png">

**Comment by Manloff** [comment]
yeah, I import it use cocoapods
<img width="818" alt="2018-07-18 5 54 40" src="https://user-images.githubusercontent.com/12522976/42874422-b26fd65c-8ab3-11e8-80f7-4b8351907dd8.png">

<img width="1026" alt="2018-07-18 5 50 41" src="https://user-images.githubusercontent.com/12522976/42874307-5a3afc14-8ab3-11e8-96ab-ffe547af67c6.png">

**Comment by hackiftekhar** [comment]
Hmm, then this issue shouldn't happen. Can you please try cleaning project and again run pod commands?

**Comment by Manloff** [comment]
yeah, I had clean project once again, but it still get the error, I think there are any bugs in my project, because my other projects is OK. I will debug it and change any way, try again, thank you

**Comment by Manloff** [comment]
I had installation with source code and solve the problem😀
