### ISSUE TITLE
Prevent emoji on keyboard

### ISSUE THREAD

**Issue by p0tvin29** [hackiftekhar/IQKeyboardManager#1392]
Sorry this is not a bug... I'm just wondering how to hide emoji from the keyboard?

**Comment by hackiftekhar** [comment]
This question is not related to library, but to answer your question you can change it from iOS Keyboard Settings.

**Comment by p0tvin29** [comment]
Ah yes... thanks i just thought there was an option todo it through the library instead of going to each textfield and setting textfield.keyboardType = .asciiCapable

Thanks!
