### ISSUE TITLE
topMostController returns nil for UIWindow.

### ISSUE THREAD

**Issue by potemkinaleksey** [hackiftekhar/IQKeyboardManager#1393]
If topMostController method from IQUIView+Hierarchy called on UIWindow it returns nil. Looks like there is should be check if it is window return controller based on logic that was in IQUIWindow+Hierarcy. By the way: why that category was deleted?

**Comment by hackiftekhar** [comment]
It was removed since it was no longer used in library and according to UIView+Hierarchy logic it does not intended to support UIWindow.

**Comment by potemkinaleksey** [comment]
Ok, thank you.
