### ISSUE TITLE
当输入框的高度大于屏幕的高度时，输入框会被盖住

### ISSUE THREAD

**Issue by hkjin** [hackiftekhar/IQKeyboardManager#1395]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Demo Project**
If applicable, add demo project.

### Versions
**Xcode:** 9.4
**Mac OS:** 10.13.4
**Simulator/Device:** xx.x
**Simulator/Device Name:** iPhone 6
**Library Version:** 11.2.6

**Additional context**

输入框高度大于手机屏幕高度时，输入框不会移动到键盘的上方，而最新版本的keyboardDistanceFromTextField属性无效，因为我下面有一个工具条，需要上移100，但是设置无效。。昨天在这里刚下载的

**Comment by hackiftekhar** [comment]
So that's actually your special configuration regarding bottom options. If something special needs to be achieve then you should disable library in that particular controller and write your own logic.
