### ISSUE TITLE
can't support YYTextView

### ISSUE THREAD

**Issue by LeeFengHY** [hackiftekhar/IQKeyboardManager#1396]
**Describe the bug**
 my project I write code like this:
[[IQKeyboardManager sharedManager] registerTextFieldViewClass:[YYTextView class]
                                  didBeginEditingNotificationName:YYTextViewTextDidBeginEditingNotification
                                    didEndEditingNotificationName:YYTextViewTextDidEndEditingNotification];
in AppDelegate.m
in my tableViewCell I add the YYTextView then init it, when keyboard show can't see the toolbar

I have read your YYTextViewDemo and do it like your in my project.

### Versions
**Xcode:** 9.4
**Mac OS:** 10.13.5
**Simulator/Device:** Device
**Simulator/Device Name:** iPhone X
**Library Version:** 6.1.1

Could you help me to solve this problem,tkx

**Comment by hackiftekhar** [comment]
I just fixed couple of issues with custom TextField/TextView like YYTextView. Please note that custom TextField/TextView will not work with swift version of library.
