### ISSUE TITLE
PreviousNext item  is invalid when textField's supper view at different levels

### ISSUE THREAD

**Issue by guiqiang107** [hackiftekhar/IQKeyboardManager#1397]
![image](https://user-images.githubusercontent.com/8225765/43191253-62dfcf28-902d-11e8-8e14-c8b50f3ee146.png)

![image](https://user-images.githubusercontent.com/8225765/43191200-45637c38-902d-11e8-9b08-da624a75fdcf.png)

**Comment by guiqiang107** [comment]
ok, i'll find the answer in  https://github.com/hackiftekhar/IQKeyboardManager/issues/549, thanks

**Comment by anandbhavsar** [comment]
how to solve that?my textfield and view both are same
