### ISSUE TITLE
Animation Overlap occurs.

### ISSUE THREAD

**Issue by devny** [hackiftekhar/IQKeyboardManager#1398]
Good morning.
I am using the IQKeyboardManager well.
However, when the keyboard is up and the VC is dismissed or popped, the keyboard down animation overlaps the dismiss or pop animation.

### Versions
**Xcode:** 9.4.1
**Mac OS:**  High Sierra 10.13.6
**Simulator/Device:** Any Device
**Library Version:** Recent

**Comment by hackiftekhar** [comment]
It will be overlapped since it's the default behavior I think.
