### ISSUE TITLE
列表滚动时, 列表的fram发生了变化

### ISSUE THREAD

**Issue by LinBrong** [hackiftekhar/IQKeyboardManager#1400]
**Describe the bug**
我将textField加到tableViewHeader中, 在滚动tableView时收起键盘,但此时我的tableView的frame发生了变化,向上偏移了一个NavigationBar的高度. 只在6.0.0以上发现问题, 之前版本未发现问题

**Comment by hackiftekhar** [comment]
Please share demo project.
