### ISSUE TITLE
UICollectionView with Horizontal scrolling with paging or without

### ISSUE THREAD

**Issue by serjooo** [hackiftekhar/IQKeyboardManager#1401]
**Describe the bug**
While using a UICollectionView and having horizontal scrolling, the cells relayout to next page or disappear to make room for the keyboard instead of being offset vertically.

**To Reproduce**
1. Setup a UICollectionView with horizontal scrolling
2. Activate the keyboard on a cell that would be covered by the keyboard
3. The UICollectionViewCell is relayed out in the UICollectionView

**Expected behavior**
Expected for the UICollectionView or its container to shift vertically to make room for the keyboard so that the UITextField would be shown while editing

**Screenshots**
Screen shots from the Demo app. I changed some settings to be able to more clearly show the problem. Check UITextField 0.5 how it becomes on the next page and when you dismiss the keyboard the cells don't fill the UICollectionView anymore.

![simulator screen shot - iphone 8 plus - 2018-08-01 at 23 48 37](https://user-images.githubusercontent.com/7988482/43547965-7d7dcd18-95e5-11e8-8686-e332ec7d62ca.png)
![simulator screen shot - iphone 8 plus - 2018-08-01 at 23 48 52](https://user-images.githubusercontent.com/7988482/43547987-88d0b252-95e5-11e8-98d9-a45221f37a62.png)
![simulator screen shot - iphone 8 plus - 2018-08-01 at 23 54 55](https://user-images.githubusercontent.com/7988482/43548321-4d7f70d4-95e6-11e8-88cd-2904ade01348.png)

### Versions
**Xcode:** 9.4.1
**OS:** 11.4 
**Simulator/Device Name:** iPhone 8 Plus Simulator
**Library Version:** 6.1.1

**Comment by hackiftekhar** [comment]
Okay, can you please share a demo project?

**Comment by hackiftekhar** [comment]
Thanks, I'll check it once I back from my vacation.

**Comment by hackiftekhar** [comment]
@serjooo I found that the UICollectionViewExample is automatically maintaining horizontal scrolling, however there is not much thing we can do to optimize it more.

**Comment by Omarrave** [comment]
here’s what I found: the answer https://patrick-clinch75.github.io/emlyn/
