### ISSUE TITLE
Dyld Message: Library not loaded: @rpath/IQKeyboardManager.framework/IQKeyboardManager + 0

### ISSUE THREAD

**Issue by semnyqu** [hackiftekhar/IQKeyboardManager#1405]
Dyld Message: Library not loaded: @rpath/IQKeyboardManager.framework/IQKeyboardManager + 0
iPhone 6s Plus
iOS 9.3.1 (13E238)

### Versions
**Xcode: 9.1
**Mac OS:10.13.6 (17G65)
**Library Version:5.0.8

**Comment by hackiftekhar** [comment]
This must be something related to your project settings.

**Comment by spraveenk91** [comment]
I have got the same issue in my app.
Device: iPhone 6s
OS: 9.2.1
Library version: 4.0.10

**Comment by hackiftekhar** [comment]
Please clean the project, sometime it happens due to cache. The library is distributed as purely source code so all the framework related issues either are your project related or the cache related.

**Comment by QaziAmmar** [comment]
after Cleaning getting the same error.
