### ISSUE TITLE
Keyboard is not displayed if the UITableview changes it's content.

### ISSUE THREAD

**Issue by asif13** [hackiftekhar/IQKeyboardManager#1406]
When the table view layout changes, the keyboard opens and and closes immediately .
In case of objective-c version of manager, the table view does scroll up to correct position but in case of swift version, the table is not scrolled to correct version.

It happens on the textfields towards the bottom of tableview.

Mitigation tried :

- Calling reloadLayoutIfNeeded after the changes to table view has completed.Still the issue persists

**Comment by hackiftekhar** [comment]
Please share demo project.
