### ISSUE TITLE
the bar arrow direction is wrong！

### ISSUE THREAD

**Issue by dudongdaoqi** [hackiftekhar/IQKeyboardManager#1409]
**Describe the bug**
the bar arrow direction is wrong！

**Code**
+(UIImage*)keyboardNextImage
{                
#ifdef __IPHONE_11_0
    if (@available(iOS 10.0, *))
#else
    if (IQ_IS_IOS10_OR_GREATER)
#endif
   {
        return [UIImage keyboardNextiOS9Image];
    }
    else
    {
        return [UIImage keyboardPreviousiOS9Image];
    }
}

as we see，ios10 is keyboardNextiOS9Image, smaller than ios10 is keyboardPreviousiOS9Image. we should change to keyboardNextiOS10Image and keyboardNextiOS9Image! how do you think?

### Versions
**Xcode:** 9.3
**Simulator/Device:** 11.3
**Library Version:** 6.1.1

**Comment by Jayxiang** [comment]
en

**Comment by hackiftekhar** [comment]
It's fixed btw.
