### ISSUE TITLE
Can I skip the tableview and scroll all the viewController when the keyboard appear?

### ISSUE THREAD

**Issue by gcgc100** [hackiftekhar/IQKeyboardManager#141]
The textfield is in a tablecell of the tableview.
It will scroll the tableview when the keyboard appear. But I want to scroll all the viewController instead of the tableview when the keyboard appear.

**Comment by hackiftekhar** [comment]
No, the library cant modify much user code to do the trick. Developer must have to put all his content over UIScrollView or it's subclass in order to scroll and should maintain when to enable/disable scrolling.
