### ISSUE TITLE
sometimes not working

### ISSUE THREAD

**Issue by CBL0123** [hackiftekhar/IQKeyboardManager#1410]
sometimes，keyboard  doesn't work,  how can I mark sure  It working when app launch？thank you!

**Comment by hackiftekhar** [comment]
Please see the documentation and check if you setupnit correctly.

**Comment by CBL0123** [comment]
I  setup nothing in my project,  it work well usually,but the toolbar dismissed sometimes

**Comment by hackiftekhar** [comment]
Not understanding. Please give some more detail and clear information.

**Comment by CBL0123** [comment]
My project use obj-c,I add IQKeyboardManager files to my project without enter any code , the toolbar not show sometimes ,but the keyboard work well,so I can't close the keyboard whit this situation

**Comment by hackiftekhar** [comment]
Hmm, this shouldn't happen. Please make sure you haven't assigned any custom view to textField.inputAccessoryView.
