### ISSUE TITLE
How to change color of field name shown inside toolbar?

### ISSUE THREAD

**Issue by hamzabinamin** [hackiftekhar/IQKeyboardManager#1413]
**Describe the bug**
How can I change the color of the field name that gets shown inside the toolbar in the middle? By default its gray, is there any way I can change that?

**Comment by hackiftekhar** [comment]
I think currently there is no direct way to change it.

**Comment by hackiftekhar** [comment]
Late posting, but there properties have been added
placeholderColor
placeholderButtonColor

You can use the placeholderColor property of IQKeyboardManager and it will do the tweak for you. Happy Coding!
