### ISSUE TITLE
How should I solve this problem?

### ISSUE THREAD

**Issue by guochao285575** [hackiftekhar/IQKeyboardManager#1414]
**Describe the bug**

![iphone8](https://user-images.githubusercontent.com/16434139/44572522-a3469b00-a7b6-11e8-811d-51a0629e4035.gif)

![iphonex](https://user-images.githubusercontent.com/16434139/44572530-a9d51280-a7b6-11e8-82ae-a85042348f79.gif)

### Versions

**Xcode:** 9.4.1
**Mac OS:** 10.13.5
**Simulator/Device:** Simulator
**Simulator/Device Name:** iPhoneX - 11.4 & iPhone8 - 11.4

Looking forward to your reply!

**Comment by Mehul1437** [comment]
I have Same Issue, Have you any solution about this?

**Comment by guochao285575** [comment]
@Mehul1437 I have no idea.

**Comment by Parth-Patoliya** [comment]
Same here

**Comment by hackiftekhar** [comment]
Please update library
