### ISSUE TITLE
The toolbar jumping x2 of keyboard height

### ISSUE THREAD

**Issue by f0r3s1** [hackiftekhar/IQKeyboardManager#1416]
The toolbar jumping x2 of keyboard height

Bug reproduces around all screens in the app

![img_0010](https://user-images.githubusercontent.com/15886508/44581598-ffa1be80-a7a6-11e8-99f3-201e52d0b357.PNG)

**Comment by dsmm2018** [comment]
same issue

**Comment by barkiiqbal** [comment]
same issue

**Comment by f0r3s1** [comment]
@hackiftekhar have you any solutions to fix that problem?

**Comment by hackiftekhar** [comment]
I think this isn't related to library. Can all of you guys tell me your these settings:
Library version:
Xcode version:
iPhone iOS version:
Minimum deployment target:
Maximum deployment target:

**Comment by HB-Dimple** [comment]
This happens only in iOS 12. Rest seems same. Can anybody help quickly ?

**Comment by barkiiqbal** [comment]
This issue was happening for me on iOS 11 too.

**Comment by alvinjaycosare** [comment]
@hackiftekhar Experiencing the same issue, but inconsistently. Any idea why this happens?

**Comment by hackiftekhar** [comment]
I don't know why this happens

**Comment by zezek** [comment]
same here in iOS 11.

**Comment by GabzTodaro** [comment]
Hey guys,

Any news on this?

**Comment by FaranMushtaq** [comment]
Experiencing the same issue, Please resolve it

**Comment by reececomo** [comment]
Same issue here.

**Comment by alvinjaycosare** [comment]
Hey guys! 

I found a workaround. I noticed that the toolbar only jumps when the app navigates to another screen while the keyboard is still shown. To prevent this, we can do this in the ViewController:

```
override func viewWillDisappear(_ animated: Bool) {
   super.viewWillDisappear(animated)
   view.endEditing(true)
 }
```

Hope it helps :)

**Comment by reececomo** [comment]
Putting this in every view controller seems a bit cumbersome for bigger projects (50+ VCs).

Maybe swizzle it in

**Comment by hackiftekhar** [comment]
Thanks @alvinjaycosare for the workaround. I'lll try to add this in the known issue list.

**Comment by caprapaditu** [comment]
> Thanks @alvinjaycosare for the workaround. I'lll try to add this in the known issue list.

Has been introduced till now in a release? It's still a problem to me

**Comment by hackiftekhar** [comment]
@caprapaditu you have to manually add this workaround in your project.

**Comment by hackiftekhar** [comment]
Added workaround to the Known Issues

**Comment by ankit0812** [comment]
has this been fixed in the updates later?
