### ISSUE TITLE
UITextField hiden behind keyboard on iPhone SE

### ISSUE THREAD

**Issue by elorusso** [hackiftekhar/IQKeyboardManager#1419]
**Describe the bug**
I have form made of UITextFields within a UIScrollView with a pretty significant top edge inset. IQKeyboardManager works perfectly fine on all devices except the small screen on the iPhone SE. On the SE, the textfield is just barely slides behind the keyboard toolbar.  Upon the keyboard showing, the UIScrollView scrolls up appropriately to keep the textfield visible, but then has a secondary adjustment that moves it beneath the toolbar on the keyboard. 

**Screenshots**
![img_0469](https://user-images.githubusercontent.com/4721109/44666046-804dfe00-a9e5-11e8-82dd-f8a9a25a92c3.PNG)

**Additional context**
I tested on iOS 10 and 11, and it makes no difference.  As far as I can tell, it's related to the screen size, and possibly the view stack.  
Note: there is a non-scrolling UICollectionView between the parent UIScrollView and the child UITextField. Not sure, but that could have something to do with it.

Let me know if you need more info.
Thanks

**Comment by RowanG1** [comment]
I am also having this issue. On Iphone 5, on ios 10.3

**Comment by hackiftekhar** [comment]
@elorusso @RowanG1 Can you please check #1365 or #1541 if your issue related to these tickets?
