### ISSUE TITLE
show keyboard in tableview and then scroll tableview, can't scroll tableview to bottom

### ISSUE THREAD

**Issue by thuai** [hackiftekhar/IQKeyboardManager#142]
I have a textview is a subview of UITableViewCell. When i edit in this textview, keyboard auto show. It's correct behavior. 
But if I scroll tableview just once.
I will not be able to scroll tableview bottom, if the keyboard don't dismiss.

How to solve this problem? 
Thank you!

**Comment by hackiftekhar** [comment]
Please be sure you're using latest version of source code. I've already fixed the scrollView bottom scrolling issues. Here are some commit details:-

https://github.com/hackiftekhar/IQKeyboardManager/commit/9b5076b816c07dd634c7e6c31721da756b139ad7
https://github.com/hackiftekhar/IQKeyboardManager/commit/0950d46eda586ba82eee8013d67f91a9c451d6ac

Please check 'UITableView in Container' section in demo project. Let me know if you want to achieve something else.
