### ISSUE TITLE
Memory leak. IQKeyboardManagerSwift (6.1.1)

### ISSUE THREAD

**Issue by Torlopov-Andrey** [hackiftekhar/IQKeyboardManager#1420]
Hello. In my app i am using IQKeyboardManager. Its all working fine. But when i go for profile testing i am facing memory leak. It would be good if this big was fix. Thank you very much!

[image](https://yadi.sk/i/kxc4rbV63afuif)

**Comment by hackiftekhar** [comment]
Unable to access screenshot
