### ISSUE TITLE
UInavigationbar slide up together with the view

### ISSUE THREAD

**Issue by kamenr** [hackiftekhar/IQKeyboardManager#1421]
I using IQkeyboardManager for all my app for a very long time. But recently I am doing something like a chatting page, when the user click on the UItextview, the keyboard appear but in the same time the UInavigationbar will slide up together and gone from the main view.

**Comment by Parth-Patoliya** [comment]
Same here

**Comment by guochao285575** [comment]
Same here

**Comment by jasongaare** [comment]
I believe this is related, but here is what I am experiencing, essentially when the scrollview is moving AND the keyboard is changing visibility it seems the whole navigation controller is moving

https://trello-attachments.s3.amazonaws.com/52a8e54148f28f3e2f0a90ac/5b3d1dc12adc4235ace671f5/22b851393ca0e5f7ba0b7a323a400bb7/movie.mp4

**Comment by jasongaare** [comment]
I have a couple brief observations that provide more insight to my issue.. 

Our app utilizes a wrapping side menu component, so `parentContainerViewController` always returns that view, which is wrapping even the UINavigationController

Secondly, what seems to happen and is causing the issue is this order of events:
1. `keyboardWillShow` is called, and the `_topViewBeginOrigin` is saved
2. Next, the root view is moved (moving upward)
3. `textFieldDidBeginEditing` is called, and the _shifted_ root view's origin is then stored in `_topViewBeginOrigin` (overriding the true origin)
4. When the view is "restored" is it not restored properly

**Comment by kamenr** [comment]
So anyone can help us?? Its been dragging quite some times now....

**Comment by jasongaare** [comment]
While certainly not ideal... here is my current workaround.

In the AppDelegate, I added an observer for `UIKeyboardDidHide` and then added this function to be called whenever the keyboard hides. 

```
@objc func onKeyboardDidHide() {
        // logic duplicated from https://github.com/hackiftekhar/IQKeyboardManager/blob/3414e2da00a11f9ae132816d686852b121e2fdf1/IQKeyboardManagerSwift/Categories/IQUIView%2BHierarchy.swift#L97
        if var rootController = UIApplication.shared.keyWindow?.rootViewController {
            
            while let parentNav = rootController.navigationController {
                rootController = parentNav
            }
            
            var parentController : UIViewController = rootController
            
            while let parent = parentController.parent,
                (parent.isKind(of: UINavigationController.self) == false &&
                    parent.isKind(of: UITabBarController.self) == false &&
                    parent.isKind(of: UISplitViewController.self) == false) {
                        
                        parentController = parent
            }
            
            parentController.view.frame.origin = CGPoint(x: 0, y: 0);
        }
    }
```

I haven't experienced any other side effects from this code, yet... but I wouldn't be surprised if I did encounter one. The solution is definitely a quick hack while waiting for a proper fix.

**Comment by hackiftekhar** [comment]
If you do something like chat screen then I usually suggest to disable library in that particular controller and implement your solution by own, since chat screen have a different kind of layout than regular screens.

**Comment by jasongaare** [comment]
@hackiftekhar I am not doing a chat screen, but a simple checkout form -- name, email and credit card number text inputs in a collectionView. 

Would you have any ideas on how to resolve the issue outlined above?

**Comment by hackiftekhar** [comment]
@jasongaare you are using side menu which does have a different kind of view hierarchy. It prevent library to find it's left/right/center controller. To make a workaround with side menu, you can refer to this issue https://github.com/hackiftekhar/IQKeyboardManager/issues/1302. I believe this user also had similar kind of problem.

**Comment by jasongaare** [comment]
Thanks for the info. I'll have to look into that -- our implementation is different so not sure where I will be placing that override. Thanks again

**Comment by thidayatullah** [comment]
It happens to my Chat screen also. 
I just put all contents inside a scroll view and it seems to fix the problem.
<img width="358" alt="screen shot 2018-09-26 at 12 58 11" src="https://user-images.githubusercontent.com/8704098/46060077-f5028c80-c18b-11e8-9316-9b0054b51fb3.png">

**Comment by hackiftekhar** [comment]
I really not sure how this may fix the problem because usually we shouldn't place a scrollView inside another scrollView. But anyhow good news.
