### ISSUE TITLE
Done button not being translate 

### ISSUE THREAD

**Issue by pranavpari** [hackiftekhar/IQKeyboardManager#1423]
When changing the language for example from Enlish to Arabic, The Done button remain in English only. need to close and open the again and then its working.

**Comment by hackiftekhar** [comment]
Are you doing on demand language change?

**Comment by pranavpari** [comment]
Yes

**Comment by hackiftekhar** [comment]
Then you have to change done title of IQkeyboardManager class ehile changing language.

**Comment by pranavpari** [comment]
Ok Thanks

**Comment by danchokobo** [comment]
> Then you have to change done title of IQkeyboardManager class while changing language.

how?
