### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by zyizyiz** [hackiftekhar/IQKeyboardManager#1424]
**Describe the bug**
UICompatibilityInputViewController
objc[10453]: Cannot form weak reference to instance (0x7f8d48da36b0) of class UICompatibilityInputViewController. It is possible that this object was over-released, or is in the process of deallocation.

**Expected behavior**
The keyboard retracts twice and flashes back

### Versions
**Xcode:** 9
**Mac OS:** 10.13.6
**Simulator/Device:** All
**Simulator/Device Name:** All
**Library Version:** latest

**Comment by hackiftekhar** [comment]
It doesn't look like feom the library. Can younplease share demo project?

**Comment by zyizyiz** [comment]
sorry. This is my corporate product.I can't share this project in public.

**Comment by hackiftekhar** [comment]
Then I can say UICompatibilityInputViewController is not referenced from my library, it's from UIKit SDK and you should contact Apple for that.

**Comment by lforme** [comment]
I think it might be that you rewrote the dealloc method.
