### ISSUE TITLE
View pushed off screen (does not return)

### ISSUE THREAD

**Issue by FSurani** [hackiftekhar/IQKeyboardManager#1425]
**Describe the bug**
I currently have a simple UIViewController and on it there is a vertical stackview. Each stackviewitem is an UITextView. 
Once I select the bottom most textview everything pushes up (as expected) and the top most uitextview is also pushed out of the view (as expected). However I have no way of accessing the top most view any more. 

I am not using the prev/next uitoolbar because I have a custom inputaccessory view. Will I need to use a UIScrollview to solve this? 

### Versions
**Library Version:** Latest

**Comment by hackiftekhar** [comment]
Probably Yes.

**Comment by FSurani** [comment]
So any idea how I should have my view laid out in order to use this library optimally? I liked the idea of not having to use a UIScrollView,

**Comment by hackiftekhar** [comment]
Due to your layout hierarchy, you can't access top textView, and you also removed the option of next/prev buttons. However if you have space in your toolbar then you could add yiur own prev/next button to achieve same feature of navigating between textView.

Looks like you probably cannot adopt a better layout according to your requirement.

**Comment by FSurani** [comment]
Even if I put my entire containerview inside a scroll view I still get the same issue. Seems like the entire view is being pushed (the view controllers view) instead of the contents. So if my heirarchy is something like:

`View
       ScrollView
            StackView
                  TextView
                  TextView
`

When the keyboard is showing it doesn't allow the user the self scroll back up.

**Comment by hackiftekhar** [comment]
Then not sure what might be the cause of issue. Please share a demo and I'll try to check late thus month. I'm on my vacation.
