### ISSUE TITLE
Cant set keyboardDistanceFromTextfield

### ISSUE THREAD

**Issue by poomethavornvanit** [hackiftekhar/IQKeyboardManager#1426]
**Describe the bug**
Hi, sorry if this is a redundant question. I cannot seem to set the 'keyboardDistanceFromTextField' to 0.0.

**Expected behavior**
I would like to get rid of the blank white space between the textfield and the keyboard (only for when the user navigates to this chat view controller), otherwise the 'keybaordDistanceFromTextField' can remain the default value.

**Screenshots**
<img width="454" alt="screen shot 2018-09-07 at 4 22 52 pm" src="https://user-images.githubusercontent.com/19563942/45241707-736dbc00-b2bb-11e8-8dc2-52bf55d1bd12.png">
<img width="482" alt="screen shot 2018-09-07 at 4 22 56 pm" src="https://user-images.githubusercontent.com/19563942/45241708-736dbc00-b2bb-11e8-8e64-afc49b5a1fea.png">

### Versions
**Xcode:** 9.4.1
**Mac OS:** 10.13.6
**Simulator/Device Name:** iPhone 8

**Comment by hackiftekhar** [comment]
Minimum value is 0. You can see this code

```
//	Setting keyboard distance from text field.
-(void)setKeyboardDistanceFromTextField:(CGFloat)keyboardDistanceFromTextField
{
    //Can't be less than zero. Minimum is zero.
	_keyboardDistanceFromTextField = MAX(keyboardDistanceFromTextField, 0);

    [self showLog:[NSString stringWithFormat:@"keyboardDistanceFromTextField: %.2f",_keyboardDistanceFromTextField]];
}
```

**Comment by poomethavornvanit** [comment]
I set set the value to 0, but there is still a blank space between the keyboard and the textfield, is there a way to remove the blank space?

**Comment by hackiftekhar** [comment]
If you are referring to your first screenshot then it's the shadow of your TabBar, not the distance you set. With your second screenshot reference, I'm not able to see the blank space.

**Comment by poomethavornvanit** [comment]
![](https://user-images.githubusercontent.com/19563942/45241708-736dbc00-b2bb-11e8-8e64-afc49b5a1fea.png)

right. in this case, how would i be able to get rid of the gap between the keyboard and the textfield? thanks.

**Comment by hackiftekhar** [comment]
It might be due to your own logic or constraint.
Btw, for chat kind of screen, I generally suggest to disable library and write your own logic.

**Comment by poomethavornvanit** [comment]
Okay! thank you. I disabled IQKeyboardManager and was able to figure out an alternative solution

**Comment by hackiftekhar** [comment]
Great!

**Comment by klever34** [comment]
@poomethavornvanit I'm currently having this same issue with Tab, what was your alternative solution?
