### ISSUE TITLE
Found Navigation bar behave strangely on showing and hiding the keyboard from IQKeyboardManager

### ISSUE THREAD

**Issue by SURYAKANTSHARMA** [hackiftekhar/IQKeyboardManager#1427]
**Describe the bug**
Found Navigation bar behave strangely on showing and hiding the keyboard from IQKeyboardManager.
-  First time Status bar and navBar got mix up
![simulator screen shot - iphone x - 2018-09-12 at 15 26 26](https://user-images.githubusercontent.com/6416095/45417845-b99e9300-b6a0-11e8-89bc-e924e73ae068.png)
- Second time white small stripe bar get appear   
![simulator screen shot - iphone x - 2018-09-12 at 15 26 30](https://user-images.githubusercontent.com/6416095/45417984-0edaa480-b6a1-11e8-9fd5-7387bfc01598.png)
- Third time white  stripe bar get bigger to safe area size
![simulator screen shot - iphone x - 2018-09-12 at 15 26 38](https://user-images.githubusercontent.com/6416095/45418015-20bc4780-b6a1-11e8-96e9-741cc681a038.png)
   

**Expected behavior**
This should not be happen ideally. 

### Versions
**Xcode:**  9.41
**Simulator/Device:**  11.4 
**Simulator/Device Name:**  iPhone x
**Library Version:**  5.0.6

**Comment by hackiftekhar** [comment]
Please update to latest version of library. It might solve your problem.

**Comment by SURYAKANTSHARMA** [comment]
Yes it solve the problem by updating pod to latest version. Thanks a lot.
