### ISSUE TITLE
Using a +load method causes a 36ms pre-main delay

### ISSUE THREAD

**Issue by michaeleisel** [hackiftekhar/IQKeyboardManager#1428]
On an iPhone 8 with version 6.0.3 of IQKeyboardManager, the `+load` method takes 36ms. This code is hard to measure because it comes before `main` is run, so here we have a significant delay that many developers will not be aware of and cannot control. It would be great to allow developers to explicitly start it up themselves and remove the `+load` method in IQKeyboardManager.m, so that they:

- are more aware that a significant of setup work is occurring
- can easily measure it
- can control when they want the delay to happen

**Comment by hackiftekhar** [comment]
The library it intended to use without writing any code, that's why you find +load method. My thought was on this is if developer install this library then they are ok with the library logic.
    However I'll try to create some kind of compile-time MACRO validation to respect your thoughts on this. By default it will be ON but user can explicitly disable this feature.
