### ISSUE TITLE
Category method and property name conflicts

### ISSUE THREAD

**Issue by antoinepalazzolo** [hackiftekhar/IQKeyboardManager#1429]
The library has a category on UIView that define properties that conflicts with subclasses of UIView in my project (for example I can't have a searchBar property because it's defined in that category)

The best practice is to add prefix to the method name to avoid that issue:
https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/ProgrammingWithObjectiveC/CustomizingExistingClasses/CustomizingExistingClasses.html#//apple_ref/doc/uid/TP40011210-CH6-SW4
and here : 
https://nshipster.com/namespacing/

**Comment by hackiftekhar** [comment]
Hmm, okay, can you please create a PR after changing in objc and swift both library.
