### ISSUE TITLE
keyboard did't display on ios8 Landscape Left/Right 

### ISSUE THREAD

**Issue by chaoyuan899** [hackiftekhar/IQKeyboardManager#143]
ios8,landscape left/right , present a view which contain the textfield, keyboard didn't display.
 I came to login ControllerVC and I touch the textField,the keyboard exactly display ,but when i came to another controllerVC and present a viewControllerVC which contain a textField and I touch the textField ,the keyboard did'nt display and the whole view can't respone any touch and no log write to debug area.

**Comment by chaoyuan899** [comment]
when I debug the code ,i find loop forever in the below code:(IQUIView+Hierarchy)
while ([controllersHierarchy containsObject:matchController] == NO || matchController == nil)
    {
        do
        {
            matchController = [matchController nextResponder];
            
        } while (matchController != nil && [matchController isKindOfClass:[UIViewController class]] == NO);
    }
so it cann't respone to any touch,but I still not know how to fix it.

**Comment by hackiftekhar** [comment]
Please test your app on real device, it may be simulator settings issue, you can find it on read me file. Please share a demo project if you face this issue on real device too.

**Comment by hackiftekhar** [comment]
Could you please share demo project so that I can debug the loop

**Comment by hackiftekhar** [comment]
@chaoyuan899  could you please share a working demo project?

**Comment by hackiftekhar** [comment]
@chaoyuan899 Any updates?

**Comment by chaoyuan899** [comment]
oh~,so sorry for so late to reply you. since it's the company project，so I cann't offer you the project.I try to recur but failed.I think there are some conflicts with company's .a library.The error is like issue #66
