### ISSUE TITLE
Masonry and UITextField becomeFirstResponder called in ViewDidLoad

### ISSUE THREAD

**Issue by Raydem0n** [hackiftekhar/IQKeyboardManager#1434]
**Describe the bug**
Within a view controller composed by Masonry. While "becomeFirstResponder" of a UITextField is called in ViewDidLoad, the IQKeyboardManager looks fine. But after clicking "Done" and the UITextField resigned first responder, the whole view would be pushed up and under navigation bar and cannot be restored.

**To Reproduce**
1. Composing a view controller using Masonry. 
2. Adding a UITextField to view.
3. Calling "becomeFirstResponder" of the UITextField in ViewDidLoad.
4. Clicking "Done" button of IQKeyboard

**Expected behavior**
The whole view should be keep below the bottom base line navigation bar.

**Screenshots**
Not yet.

**Demo Project**
Not yet.

### Versions
**Xcode:** 9.4, 10
**Mac OS:** 10.13.x
**Simulator/Device:** iOS 11.4, iOS 12
**Simulator/Device Name:** iPhone 6
**Library Version:** 6.1.1

**Additional context**
Not yet.

**Comment by hackiftekhar** [comment]
Technically becomeFirstResponder shouldn't be called from viewDidLoad method. You have to move thet call to either viewWillAppear or viewDidAppear (whichever works).

**Comment by Raydem0n** [comment]
[iqkeyboard.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/2403695/iqkeyboard.zip)


Thanks for the reply. A demo project has been done and uploaded, please check. Launch the demo app, and click right bar item [View] would get the trap.

becomeFirstResponder calls in both viewDidLoad and viewWillAppear both do not work. viewDidAppear or lazy call (by dispatch_after a second) would make through.

**Comment by hackiftekhar** [comment]
Will try to look once get back to work.

**Comment by mediym41** [comment]
I have the same issue

**Comment by hackiftekhar** [comment]
I moved becomeFirstResponder call to viewDidAppear and added resignFirstResponder call in viewWillDisappear and this fixed the issue:-

- (void)viewWillDisappear:(BOOL)animated
{
    [super viewWillDisappear:animated];
    [nameTxf resignFirstResponder];
}
