### ISSUE TITLE
Does it support iOS 12 autofill one time security code?

### ISSUE THREAD

**Issue by himanthmaddi** [hackiftekhar/IQKeyboardManager#1437]
As we know in iOS 12 Apple has introduced autofill one time security code/otp in iOS 12. And I heard that it will only work with system keyboard, not with custom keyboards. So is this feature works in IQKeyboardManger or you are gonna support that?

**Comment by hackiftekhar** [comment]
If keyboard notifications have correct frame value then it will work automatically.

**Comment by udayeega** [comment]
Not working

**Comment by hackiftekhar** [comment]
What exactly isn’t working?
