### ISSUE TITLE
cannot both set toolbarDoneBarButtonItemText and setTarget to doneBarButton

### ISSUE THREAD

**Issue by nuo-xu** [hackiftekhar/IQKeyboardManager#1438]
I'm trying to change the text on the "Done" button by IQKeyboardManager.shared().toolbarDoneBarButtonItemText = "Next"

I also want to customize the "Done" function by setting 
textField.keyboardToolbar.doneBarButton.setTarget(self, action: #selector(nextPressed))

But as long as i set toolbarDoneBarButtonItemText my customized function will never be called. 

How do i set the "Done" button with customized title and action?

**Comment by hackiftekhar** [comment]
Hmm, if that happens then it's a bug. I'll debug it.

**Comment by Elamuruga** [comment]
IQKeyboardManager.shared().toolbarDoneBarButtonItemText = "" . Its not working, I can't assign the text what i need ? Please fix this

**Comment by Eccelor** [comment]
Can confirm that the issue still persists.
