### ISSUE TITLE
some of textfields are up than textfield,I don't want they down to fit the keyboardDistanceFromTextField property. What can I do?

### ISSUE THREAD

**Issue by mushanlianshi** [hackiftekhar/IQKeyboardManager#1439]
some of textfields are up than textfield,I don't want they down to fit the keyboardDistanceFromTextField property. What can I do?

**Comment by hackiftekhar** [comment]
That's a bug from a long time, I'll need to fix it.

**Comment by hackiftekhar** [comment]
This is related to some scrollview related handling. It has ben fixed, new version will be publish soon.
