### ISSUE TITLE
UItableView inside a scrollview

### ISSUE THREAD

**Issue by care2achieve** [hackiftekhar/IQKeyboardManager#144]
I have a table view in side a scroll view. and table view contains textfields, when i try to edit text field table view is scrolling up but i want to scroll up scroll view not table view is it possible?

**Comment by hackiftekhar** [comment]
In short the answer is NO, In details the answer is MAY BE. Actually It may depend on the position UIScrollView and UITableView on the screen to check which object need to scroll.

The logic behind this is, the IQKeyboardManager finds the nearest UIScrollView or it's subclass in textField upper hierarchy till UIWindow. In your case IQKeyboardManager find UITableView as the nearest UIScrollView for textField and scroll the tableView first to satifsy UIKeyboard doesn't hide textField condition. If IQKeyboardManager finds that something more need to scroll to ensure UIKeyboard doesn't hide textField, then it tries to find the nearest UIScrollView of lastScrollView(UITableView in your case) and so on to satisfy UIKeyboard doesnt' hide textField...

**Comment by dipkasyap** [comment]
Have same issue, Have table view inside scroll view, When i edit text inside table view , iq scrolls the table view up but it does not satisfy your saying "If IQKeyboardManager finds that something more need to scroll to ensure UIKeyboard doesn't hide textField, then it tries to find the nearest UIScrollView of lastScrollView(UITableView in your case) and so on to satisfy UIKeyboard doesnt' hide textField..." Even i tried to test on your demo project , Its not working. 

If it is possible to provide solution then please i am waiting.

**Comment by w-i-n-s** [comment]
@dipkasyap Try one strange thing coz it did help me. For some reason in my case keyboard will hide on next/previous.
    
    - (void)viewDidLayoutSubviews {
        if (!self.<scrollView/tableView>.scrollEnabled) {
            return;
        }
        
        [super viewDidLayoutSubviews];
    }
 
![View hierarchy](https://i.imgur.com/HY21die.png)

**Comment by dipkasyap** [comment]
@w-i-n-s  Thanks i will try it out !
