### ISSUE TITLE
Toolbar does not appear in iOS12

### ISSUE THREAD

**Issue by nisarhlis** [hackiftekhar/IQKeyboardManager#1441]
I have used IQKeyboardmanager 6.1.1. 

I have given supported of Arabic language.

When I switch to Arabic language from my App, the toolbar does not appear on any textfield or textview.

I have also tried in English language after Arabic converation, but toolbar does not appear on my app after converted into Arabic Language.

I have done following steps in my App
1. Go to Profile page
2. Tap on Arabic language button and convert it into Arabic
3. Trying to write name in textfield.
4. Toolbar does not appear

I found this issue in iOS 12 only

**Comment by amrboxit4me** [comment]
@nisarhlis what if you closed the app and reopen it again is it visible first time?
I think it is related to UI Thread blocking

**Comment by nisarhlis** [comment]
@amrboxit4me yes if i close the app after changing the language, and reopen it again, then it is working properly.

**Comment by amrboxit4me** [comment]
@nisarhlis check what you doing in ViewWillApp and put it in ViewDidLoad

**Comment by kajalsheth** [comment]
Do we have any update for this issue?

**Comment by amrboxit4me** [comment]
@kajalsheth if it works 2nd time you load the app then you are loading on UI Thread specially in ViewWillAppear

**Comment by olcayertas** [comment]
Same problem, toolbar is not visible and doesn't get visible 2nd time.

**Comment by NirajCapermint** [comment]
Any update on this? In my app it's not showing on any textfields. All I have to do is add this line of code in every class:

`IQKeyboardManager.shared.keyboardDistanceFromTextField = 150`

**NOTE:** I am not using any third party library or any other language keyboard.

**Comment by hackiftekhar** [comment]
hmm, it might be something related to your project. So you might need to debug the root cause. If you get the issue, just post here and keep us update.

**Comment by hackiftekhar** [comment]
Do you guys facing this issue till now?

**Comment by sanket003** [comment]
I'm facing the same issue.

When I'm changing the language i.e. English to Arabic or vice-versa, toolbar will not show and also textfields won't move upwards. 

If I restart the app, it's working fine again.

can someone please help?

**Comment by nisarhlis** [comment]
@sanket003 

Yes, We are facing the same issue.

Can you please change the root controller after changing the language.

**Comment by sanket003** [comment]
@nisarhlis 

Still not working after changing the rootViewController.

**Comment by nisarhlis** [comment]
@sanket003 

Please take views from UIApplication.shared.windows
Remove that views,
And add those views again.
Then change the rootViewController

Now Its working for me,

But if i not change the rootViewController, the issue is remain as it is.

**Comment by sanket003** [comment]
@nisarhlis 

Changing the root controller did work for me.

Thank you so much.

**Comment by nisarhlis** [comment]
Welcome @sanket003 ,

But still there is an issue if we not changing the rootViewController,
We hope that it will be solved in next version. 
:)

**Comment by hackiftekhar** [comment]
This is an application level requirement to change language. Handling application level cases cannot be supported by library. Can you please figure out what might be the issue. Can you please share some screenshots?
