### ISSUE TITLE
Custom button is being clicked

### ISSUE THREAD

**Issue by hunterpp** [hackiftekhar/IQKeyboardManager#1443]
Using swift 4.2

I have a button named "save" this button is only supposed to be enabled when the textfield is not blank....however the "done" button of iqkeyboard causing the

 @IBAction func onSaveClick to be fired.....this is because iqkeyboard resignfirstresponder chose onSaveClick....

I don't understand why onSaveClick was chosen....onSaveClick is only supposed be callable if the textfield is not null. This is to prevent blank data from being entered.

If there was an option to disable or enable the iqkeyboard done button I would use that....but I am stuck. Thank you.

**Comment by hunterpp** [comment]
As a solution, I put the same logic to detect if textfield is blank in onSaveClick....but it is a duplicate amount of code and not elegant. Yes general solution would be nice. thank you. Also...why is resignFirstResponder choosing my onSaveClick button?

**Comment by hackiftekhar** [comment]
I don't know. Please check textField event mapping on storyboard.

**Comment by hackiftekhar** [comment]
So here is some solution. I optimized the toolbar to enable/disable done button by writing something like this:-
`textField.keyboardToolbar.doneBarButton.enabled = NO;`

But I would still prefer if you can return YES/NO by implementing `- (BOOL)textFieldShouldEndEditing:(UITextField *)textField` method and write your logic. This will prevent your textField field to resign if there is no blank text. Off-course you have to write some text validation logic, but it's the best thing.
