### ISSUE TITLE
Keyboard showing slower than textField repositioning while dismissing faster than textField repositioning

### ISSUE THREAD

**Issue by gouen95** [hackiftekhar/IQKeyboardManager#1444]
**EDIT**
I found that the bug only occurs if i use a TabBarController. Is there anyway to fix this?

**Setup**
iOS : 12
IDE : xCode 10 & Swift 4.2
IQKeyboard version : 6.1.1 (latest)

**Describe the bug**
Keyboard showing slower than textField repositioning and leaving a blank screen (UIWindow) behind.
Keyboard dismissing faster than textField repositioning and leaving a blank screen (UIWindow) behind.

**To Reproduce**
Add a collectionView to controller's view
Add a containerView for the textView and constraint left, right and bottom to controller's view, set a height constraint.
Add a subview of textView to the containerView.

**Expected behavior**
Showing and dismissing keyboard leaving no black screen.

**Issue Preview**
![iqissue2](https://user-images.githubusercontent.com/21040866/46267939-5484e180-c56a-11e8-9778-6f5dac093d77.gif)

**Extra Info**
The controller's view is being pushed up when keyboard appears rather than only the containerView itself. Is this a normal behaviour?
![iolxyb](https://user-images.githubusercontent.com/21040866/46269353-2e177400-c573-11e8-85b7-a0397b18b4de.jpg)

**Comment by hackiftekhar** [comment]
This looks to be normal since the library isn't directly handling the animations, library is just using the animations which keyboard uses.
