### ISSUE TITLE
No such module 'IQKeyboardManagerSwift'

### ISSUE THREAD

**Issue by petrovRV** [hackiftekhar/IQKeyboardManager#1446]
Hello.
I installed library 'IQKeyboardManagerSwift'.
terminal print result Using IQKeyboardManagerSwift (6.1.1), my project has Swift version 4.2.
But I can't launch my project because I have the error "**No such module 'IQKeyboardManagerSwift'**".
Also, I check my Pods/Targets and I don't see IQKeyboardManagerSwift.Library only target [IQKeyboardManagerSwift](https://image.ibb.co/bYFQJe/Screen_Shot_2018_10_03_at_13_48_24.png)
 Maybe Who knows how it could fix?

**Comment by petrovRV** [comment]
I installed pod 'IQKeyboardManagerSwift',  '~> 6.0.4', it's working now, but I don't know why pod doesn't work IQKeyboardManagerSwift (6.1.1).

**Comment by ANSCoder** [comment]
@petrovRV you can install the library with `pod 'IQKeyboardManagerSwift'` and its working fine in new **Xcode 10.0 version**. 
It's has taken automatically **IQKeyboardManagerSwift (6.1.1)** and unable to see any kind of error in **Swift 4.2** version. 👍🏼
Once clean and build your project after adding **IQKeyboardManagerSwift** module.

```
Analyzing dependencies
Downloading dependencies
Installing IQKeyboardManagerSwift (6.1.1)
Generating Pods project
Integrating client project
```

**Comment by w-i-n-s** [comment]
Xcode Version 10.1 (10B61)
install by pod: `pod 'IQKeyboardManagerSwift'` have the same issue

**Comment by daniel-hopkins** [comment]
> Xcode Version 10.1 (10B61)
> install by pod: `pod 'IQKeyboardManagerSwift'` have the same issue

perhaps you made the same mistake I did, I copied the first installation line `pod 'IQKeyboardManager'` and then tried to `import IQKeyboardManagerSwift` 
I fixed by adding the proper podfile line `pod 'IQKeyboardManagerSwift'`
