### ISSUE TITLE
Ambiguous use of 'placeholderText'

### ISSUE THREAD

**Issue by retsohuang** [hackiftekhar/IQKeyboardManager#1447]
**Describe the bug**
I want to use AnimatableTextView to configure the placeholder but seems like it can't do that because of the public UIView extensions' `placeholderText` property.

**To Reproduce**
1. Go to the demo project
2. Update Podfile and install `IBAnimatable`
3. Create an AnimatableTextView and set its placeholderText
```swift
let textView = AnimatableTextView()
textView.placeholderText = ""
```

**Expected behavior**
Build success

**Screenshots**
<img width="923" alt="image" src="https://user-images.githubusercontent.com/785920/46424114-cf1c4f80-c76a-11e8-9485-a68bb010e671.png">

### Versions
**Xcode:** Version 10.0 (10A255)
**Mac OS:** 10.4
**Simulator/Device:** xx.x
**Simulator/Device Name:** iPhone xx
**Library Version:** IQKeyboardManagerSwift (6.1.1) with CocoaPods

**Comment by hackiftekhar** [comment]
Looks like both library has same name for that property. I'll rename it.

**Comment by hackiftekhar** [comment]
Renamed here ec11dca0f15651126e5662cbe9579835c56e37d9 Thanks for reporting!
