### ISSUE TITLE
Safe area insets getting set to zero on iPhone X landscape

### ISSUE THREAD

**Issue by jboulter11** [hackiftekhar/IQKeyboardManager#1449]
**Describe the bug**
In landscape on iPhone X or similar devices, safe area is not respected when the keyboard appears on a managed text field.  Please see the demo project.

**To Reproduce**
1. Pin a text field to the leading and trailing safe area
2. Add it to enabled classes for IQKeyboardManager
3. Open project in landscape on phone with notch
4. Touch the field to present the keyboard, see the safe area snap to `CGRect.zero`.
5. Dismiss keyboard with cmd+k and the rect goes back to expected value.

**Expected behavior**
The safe area insets should be unchanged in this case, so the view doesn't snap under the notch.

**Screenshots**
![ss1](https://github.com/jboulter11/IQKeyboardManagerBugTest/blob/master/ss1.png?raw=true)
![ss2](https://github.com/jboulter11/IQKeyboardManagerBugTest/blob/master/ss2.png?raw=true)

**Demo Project**
https://github.com/jboulter11/IQKeyboardManagerBugTest

### Versions
**Xcode:** 10.0
**Mac OS:** 10.14
**Simulator/Device:** 12.0
**Simulator/Device Name:** iPhone X or similar
**Library Version:** 6.0.4 and 6.1.1 tested, 6.1.1 shown in demo

**Additional context**
See readme on the demo and please let me know if you have any questions, comments, or workarounds!  Feel free to let me know if I'm missing something!

**Comment by hackiftekhar** [comment]
You are absolutely correct but the library doesn't change textField x position or width so I need to spend more time to debug this issue.

**Comment by jboulter11** [comment]
As far as I can tell from debugging, it's the safe area insets actually getting changed to [0,0,0,0] instead of their expected value on keyboard presentation.

**Comment by hackiftekhar** [comment]
hmm, might be. Unfortunately I'm too busy with personal things and couldn't check your demo. Regarding your comment I can tell that the library doesn't changing safe area insets at all.

**Comment by adrian-iova** [comment]
any updates on this?

**Comment by andreeasandutmd** [comment]
Hello, did you get a chance to look into this issue? It would be great if you could provide an update.
Thank you!

**Comment by hackiftekhar** [comment]
Nope, but will try to check these github issues tomorrow.

**Comment by hackiftekhar** [comment]
I checked this today, but we have a bad news. I'm able to reproduce this issue without using IQKeyboardManager. I modified the demo a little bit to demonstrate the issue without IQKeyboardManager.

My observation is that when view frame is changed, the safe area inset is changed by it. Currently there is no way to avoid this. Attaching the demo.

[IQKeyboardManagerBugTest-master 2.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/3127829/IQKeyboardManagerBugTest-master.2.zip)

**Comment by Varrry** [comment]
What if change transform instead of frame? For quick-check of this approach I replaced all cases where view's origin is moved with equivalent translation transform (relative to identity). Got almost correct behaviour.
One wrong case left when switch from field requiring adjustment to a field not requiring adjustment - safe area becomes zero; so far I didn't find out that triggers this.

**Comment by Varrry** [comment]
After several hours of experiments and debugging it seems to me that using transform also breaks safe area insets, at least in one case described above. Replacing all `controller.view.frame = ...` with something neutral, like changing view background color, doesn't break safe area. No idea how it depends.
Good thing - bug doesn't appear if embed view controller in navigation controller, even with hidden navbar; this can be a workaround.
