### ISSUE TITLE
iPhone XR in Simulator only shows "Done" bar, no keyboard.

### ISSUE THREAD

**Issue by Retnuh1337** [hackiftekhar/IQKeyboardManager#1451]
**Describe the bug**
The iPhone XR in Simulator doesn't show the IQKeyboard, only the "Done" bar. I tried the iPhone X, XS and XS Max and all work fine, just the XR will not populate the keyboard.

**To Reproduce**
1. select iPhone XR
2. Run Build
3. Click on Text Box
4. Keyboard attempts to come up but stops after the word "Done"

**Expected behavior**
The keyboard should come all the way up and the screen scroll upward.

**Screenshots**
![screen shot 2018-10-08 at 6 19 05 pm](https://user-images.githubusercontent.com/3761176/46637065-88db3d80-cb28-11e8-85f8-a04f8a9bb661.png)

### Versions
**Xcode:** 10.0
**Mac OS:** 10.14.1 Beta
**Simulator/Device:** Version 10.0 (SimulatorApp-869.5 CoreSimulator-572.2)
**Simulator/Device Name:** iPhone XR
**Library Version:** x.x.x

**Comment by Retnuh1337** [comment]
This is not an issue I believe. After clicking on the text field, I toggled the Keyboard and it came up. I didn't have to do that for any other simulator.

**Comment by hackiftekhar** [comment]
Correct!
