### ISSUE TITLE
iqkeyboard crash on  IQKeyboardManager.shared.enable

### ISSUE THREAD

**Issue by Blankz** [hackiftekhar/IQKeyboardManager#1452]
**Describe the bug**
in appdelegate 
IQKeyboardManager.shared.enable = true 

app crash

### Versions
**Xcode:** 10
**Mac OS:** 10.14
**Simulator/Device:** 12
**Simulator/Device Name:** iPhone 5s
**Library Version:** 6.2.0

**Comment by Blankz** [comment]
clean and build it work

**Comment by nitinkarki** [comment]
@Blankz this worked for me, thanks!

**Comment by yovi-ep** [comment]
clean and built project or pod? for me not working. then i downgraded to 6.5.1 and still crashed
