### ISSUE TITLE
when i add a CustomView in UIWindows,the customView contain a UITextField,when i dismiss the customView,IQKeyboard's gesture has conflict with my custom gesture. 

### ISSUE THREAD

**Issue by iFlyK** [hackiftekhar/IQKeyboardManager#1455]
**Describe the bug**

**To Reproduce**
1. Go to TableViewController
2. Click on ‘IQKeyboardManagerDemo’
3. Click on UItextfield
4. then click on space
5.the view hasn't remove from window

**Expected behavior**

**Screenshots**

**Demo Project**
If applicable, add demo project.

### Versions
**Xcode:Xcode 10.0
**Mac OS: 10.13.6
**Simulator/Device:Simulator 6sp
**Simulator/Device Name:Simulator 6sp
**Library Version:iOS 10,iOS 12

**Additional context**

**Comment by hackiftekhar** [comment]
Can you please share more information regarding gesture conflicts?

**Comment by sujalfm** [comment]
I too got this sort of conflict. Here is my case:

I have a long form and on clicking a textfield at the top, I open a google places selector view controller. After selecting a place, this view controller gets dismissed and i get back to my form. Now, on switching down the form, the scroll does not behave properly as desired.

**Comment by iFlyK** [comment]
when i touch uitextfield,UIWindow has a UIView didn't remove from UIWindow

**Comment by iFlyK** [comment]
when touch white space,this is right,I guess there are  conflict with yours gesture.

**Comment by hackiftekhar** [comment]
Ok, I'll check the demo

**Comment by iFlyK** [comment]
the first file is current result,the second file is the result which i expected. I add two file to description

<img width="979" alt="wx20181015-141100 2x" src="https://user-images.githubusercontent.com/5998798/46932866-3350e480-d084-11e8-964e-86f56c528ed5.png">

**Comment by iFlyK** [comment]
> Ok, I'll check the demo

>the first file is current result,the second file is the result which i expected. I add two file to description.
<img width="979" alt="wx20181015-141100 2x" src="https://user-images.githubusercontent.com/5998798/46932896-5bd8de80-d084-11e8-89a7-85274985f56e.png">

**Comment by hackiftekhar** [comment]
Thanks. Unfortunately I'm too busy these days with personal stuffs going with me, not able to check it till now.

**Comment by iFlyK** [comment]
Thank you very much. I have solved the problem now.

**Comment by hackiftekhar** [comment]
How did you solved it?
