### ISSUE TITLE
disableDistanceHandlingInViewControllerClass doesn't work

### ISSUE THREAD

**Issue by ylxieg** [hackiftekhar/IQKeyboardManager#1458]
[[IQKeyboardManager sharedManager] disableDistanceHandlingInViewControllerClass:[self   class]]; 
 doesn't work. 

when i use [IQKeyboardManager sharedManager].enable = NO; 
it worked !

**Comment by hackiftekhar** [comment]
You are using older version of library, please upgrade to latest version and use `disabledDistanceHandlingClasses` property to register classes.
