### ISSUE TITLE
Horizontal textfield screen jumping issue

### ISSUE THREAD

**Issue by hardikdevios** [hackiftekhar/IQKeyboardManager#1459]
Hello Bro,

I have 3 Textfields parallel in a horizontal manner, when I change the responder of the text field the screen keeps jumping up and down, here is the video link

https://www.dropbox.com/s/juf0xoq3sgjk680/ScreenRecording_10-17-2018%2017-43-07.MP4?dl=0

**Comment by hackiftekhar** [comment]
Seems strange, however it shouldn't happen. Are you sure you aren't doing any frame changes or scrollview content offset changes in your own code?

**Comment by hardikdevios** [comment]
It’s just normal UIView with stackview for this horizontal text field

**Comment by hackiftekhar** [comment]
okay, I'll check it once I get some free time.

**Comment by hackiftekhar** [comment]
I tried to reproduce this issue @hardikdevios, but unable to reproduce it with the latest version of the library. Can you please check it once again? If it's still reproducible then can you please send me a demo?

Could you please also let me know if your StackView contains in s ScrollView? If this is the case then #1365, #1508, #1541 fix may have also fix this issue.

**Comment by hardikdevios** [comment]
Not needed now
