### ISSUE TITLE
On iOS 12 IQKeyboardManager adds wrong "empty spaces" (insets) for scrollView. 

### ISSUE THREAD

**Issue by EugeneEl** [hackiftekhar/IQKeyboardManager#1460]
**Describe the bug**
On iOS 12 IQKeyboardManager adds wrong "empty spaces" (insets) for scrollView. 
However on iOS 11.4 it works ok.

**To Reproduce**
1. Create an empty project.
2. Create a view controller A, add child view controller B for it.
3. In childViewController B, add a scroll view, vertical stackView, some text fields. 
4. If you try to scroll several times wrong insets will appear. 

**Expected behavior**
Empty spaces should not appear.

**Screenshots**
on iOS 11.4 is ok: https://www.dropbox.com/s/9k92kgzcthko2su/IQKeyboardManager-ios11_4.mov?dl=0

on iOS 12 we have a bug: https://www.dropbox.com/s/qprno50yohldiyj/IQKeyboardManager-ios12BUG.mov?dl=0

Also I managed to notice some glitches if switch between fields is too fast on iOS 11.
![simulator screen shot - iphone 5s - 2018-10-19 at 16 03 57](https://user-images.githubusercontent.com/7325854/47220087-70d1ac80-d3b9-11e8-8d3c-e5b2b57636e4.png)
 

**Demo Project**
If applicable, add demo project.
I will try to provide a demo project soon.

### Versions
**Xcode:** 10
**Simulator/Device:** iPhone 5SE iOS12
**Library Version:** 6.2.0

**Comment by EugeneEl** [comment]
https://www.dropbox.com/s/cvglb5zbxj4ac4l/DemoWithBug.zip?dl=0

**Comment by hackiftekhar** [comment]
Thanks for the demo. I'll try to take a look at this.

**Comment by kuyazee** [comment]
+1 this also happens on my devices

iPhone XS iOS 12.1
iPhone 6 iOS 12.0

**Comment by hackiftekhar** [comment]
@kuyazee, to let you know, library ignore everything with WKWebView. So that might not be the case.

**Comment by hackiftekhar** [comment]
@EugeneEl I tried reproducing the bug with 12.1 Simulator, but I'm unable to reproduce this bug with your demo app. However I saw your videos and it looks like you are really facing issue. Can you check the demo project again?

**Comment by kuyazee** [comment]
Hi again, on my project I fixed this by setting `.contentInsetAdjustmentBehavior` of the `UIScrollView` to `.never`.

**Comment by hackiftekhar** [comment]
@EugeneEl your issue looks similar to #1365 and #1541, I've added a workaround for this. The changes will be available with our next release.

**Comment by EugeneEl** [comment]
Hi, I definitely encountered with this issue using this hierarchy:
UIScrollView->UIStackView->UITextView.

Thanks for replying.

**Comment by hackiftekhar** [comment]
So you mean you encountered the same problem. right?
If that's the case then I just released v6.3.0 with some temporary fixes.
