### ISSUE TITLE
Lots of analyze warnings with Xcode 10

### ISSUE THREAD

**Issue by Jules2010** [hackiftekhar/IQKeyboardManager#1461]
**Describe the bug**
Pods/IQKeyboardManager/IQKeyboardManager/Categories/IQUITextFieldView+Additions.m:41:13: Converting a pointer value of type 'NSNumber *' to a primitive boolean value; instead, either compare the pointer to nil or call -boolValue

Pods/IQKeyboardManager/IQKeyboardManager/IQToolbar/IQToolbar.m:92:24: nil assigned to a pointer which is expected to have non-null value

Pods/IQKeyboardManager/IQKeyboardManager/IQKeyboardManager.m:1917:23: Value stored to 'invocation' during its initialization is never read

Pods/IQKeyboardManager/IQKeyboardManager/IQKeyboardManager.m:1925:17: Value stored to 'invocation' is never read

Pods/IQKeyboardManager/IQKeyboardManager/IQKeyboardManager.m:1955:23: Value stored to 'invocation' during its initialization is never read

Pods/IQKeyboardManager/IQKeyboardManager/IQKeyboardManager.m:1963:17: Value stored to 'invocation' is never read

/Pods/IQKeyboardManager/IQKeyboardManager/IQKeyboardManager.m:1991:19: Value stored to 'invocation' during its initialization is never read

Pods/IQKeyboardManager/IQKeyboardManager/IQKeyboardManager.m:1999:13: Value stored to 'invocation' is never read

**To Reproduce**
Add `pod 'IQKeyboardManager'` to your pod file.
Use `pod update` from the command line.
Within XCode on the product menu, select Analyze.
Notice the warnings.

**Expected behavior**
No warnings.

**Screenshots**
N/A

**Demo Project**
Easy to reproduce.

### Versions
**Xcode:**  10.0
**Mac OS:** 10.13.6
**Simulator/Device Name:** iPhone 6 plus
**Library Version:** 6.2.0

**Comment by hackiftekhar** [comment]
Okay, I’ll try to fix those warnings

**Comment by hackiftekhar** [comment]
I just fixed all warning messages facing with Xcode 10.2.
