### ISSUE TITLE
isEnableAutoToolbar not working

### ISSUE THREAD

**Issue by CHOIMINSEOK** [hackiftekhar/IQKeyboardManager#1463]
**Describe the bug**

I want to remove toolbar on Keyboard, but I can't.
I just add these code on `AppDelegate`, but it's not working. 

```Swift
IQKeyboardManager.shared().isEnabled = true
IQKeyboardManager.shared().isEnableAutoToolbar = false
```

I also tried `disabledToolbarClasses` like this. but it's not working, too.
```Swift
IQKeyboardManager.shared().disabledToolbarClasses.add(MissionViewControlle.self)
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Demo Project**
If applicable, add demo project.

### Versions
**Xcode:** 10.0
**Mac OS:** 12.0.1
**Simulator/Device:** xx.x
**Simulator/Device Name:** iPhone SE
**Library Version:** 6.1.1

**Additional context**

**Comment by hackiftekhar** [comment]
Only `IQKeyboardManager.shared().isEnableAutoToolbar = false` line should be enough to remove toolbar, I don't know why it doesn't work for you. Can you please share a demo project.
