### ISSUE TITLE
看不到oc的啊

### ISSUE THREAD

**Issue by wzj583585700** [hackiftekhar/IQKeyboardManager#1465]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Demo Project**
If applicable, add demo project.

### Versions
**Xcode:** x.x
**Mac OS:** xx.xx.x
**Simulator/Device:** xx.x
**Simulator/Device Name:** iPhone xx
**Library Version:** x.x.x

**Additional context**

**Comment by littlepriest** [comment]
。。。。。。。。。。。。。。。。。。。。。。。

**Comment by hackiftekhar** [comment]
Please use english

**Comment by faimin** [comment]
In this folder [https://github.com/hackiftekhar/IQKeyboardManager/blob/master/IQKeyboardManager/](https://github.com/hackiftekhar/IQKeyboardManager/blob/master/IQKeyboardManager/)

**Comment by hackiftekhar** [comment]
So what's the issue?
