### ISSUE TITLE
White status bar after end editing

### ISSUE THREAD

**Issue by AndrewGurew** [hackiftekhar/IQKeyboardManager#1466]
Bug on screenshot. How can i fix it? Or second way, how can i move view, after open keyboard, under navigation bar?

i tried IQKeyboardManager.shared.canAdjustAdditionalSafeAreaInsets = true, no results

**To Reproduce**
Open and close keyboard few times in row. In one of the attempts you will reproduce it.

**Screenshots**
![img_1837](https://user-images.githubusercontent.com/15169532/47628425-3ddda480-db81-11e8-8bf4-2c208b131a90.PNG)

### Versions
**Xcode:** 10.0
**Mac OS:** 10.13.6
**Simulator/Device Name:** iPhone 8, iOS 12
**Library Version:** 6.1.1

**Comment by hackiftekhar** [comment]
Can you please share demo project?

**Comment by PD006** [comment]
I've the same issue, status bar will become white in colour after end editing, please help me out ASAP.
Thanks in Advance

**Comment by hackiftekhar** [comment]
Can you please share a demo?
