### ISSUE TITLE
Prevent from hiding keyboard when button inside textField pressed

### ISSUE THREAD

**Issue by skelet2394** [hackiftekhar/IQKeyboardManager#1468]
I've subclassed UITextField to add a secure text entry toggle button in password textField, but every time i click, my keyboard hides, what is not expected behaviour in my case.
Is there any way to keep First Responder for this textField on click? Tried to override shouldResignOnTouchOutsideMode and resignFirstResponder() in button action func.
Thanks forehead!

**Comment by hackiftekhar** [comment]
I think it might be your code logic which is hiding keyboard. Please check again. If not then I can say you can change it on the fly without resigning first responder.

Let me know if you still face problems with this issue.
