### ISSUE TITLE
页面加载textfield就让它获取到焦点，这时收起键盘会把页面上移

### ISSUE THREAD

**Issue by Azraeltulips** [hackiftekhar/IQKeyboardManager#1470]
在初始化textfield就让它获取到焦点，这时收起键盘会把页面上移

**Comment by mashun** [comment]
同样的问题

**Comment by mashun** [comment]
把获取焦点放到viewDidAppear方法里，可以解决这个问题

**Comment by aa335418265** [comment]
我也遇到

**Comment by hackiftekhar** [comment]
Please use english guys so that I can also understand the issue.

**Comment by Azraeltulips** [comment]
> Please use english guys so that I can also understand the issue.

When textfield is initialized, it gets the focus. When the keyboard is removed, the page will move up.

**Comment by Azraeltulips** [comment]
> 把获取焦点放到viewDidAppear方法里，可以解决这个问题

可以，灰常感谢
