### ISSUE TITLE
After upgrading xcode10.1(10B61), click down to close the keyboard for the first time, and then click the screen to crash, indicating Thread 1: EXC_BAD_ACCESS (code=EXC_I386_GPFLT).

### ISSUE THREAD

**Issue by coder-zyy** [hackiftekhar/IQKeyboardManager#1471]
**Describe the bug**

Hello, the author, I After upgrading xcode10.1(10B61), click down to close the keyboard for the first time, and then click the screen to crash, indicating Thread 1: EXC_BAD_ACCESS (code=EXC_I386_GPFLT). I tested it in the simulator (iPhone6 ~ iPhoneXS Max) environment. Please repair it as soon as possible, thank you.

### Versions
**Xcode:** 10.1
**Mac OS:** 10.14
**Simulator/Device:** iPhone6 ~ iPhoneXS Max

**Comment by hackiftekhar** [comment]
Please let me know more information about the crash. Share crash logs if possible.

**Comment by szvarhegyi** [comment]
Hy.

I have same issue.

XCODE Version 10.1 (10B61)
Virtual device: Iphone X

Error message: Thread 1: EXC_BAD_ACCESS (code=EXC_I386_GPFLT)

System.log:

`Nov  9 12:56:36 MacBook-Air com.apple.CoreSimulator.SimDevice.0681E214-40BE-4242-818C-BBAD953A591C[2807] (com.apple.StreamingUnzipService): Unknown key for Boolean: EnableTransactions
Nov  9 12:56:36 MacBook-Air com.apple.CoreSimulator.SimDevice.0681E214-40BE-4242-818C-BBAD953A591C[2807] (com.apple.StreamingUnzipService): Unknown key for Boolean: EnablePressuredExit
Nov  9 12:56:36 MacBook-Air com.apple.CoreSimulator.SimDevice.0681E214-40BE-4242-818C-BBAD953A591C[2807] (com.apple.backboard.display.archive): Unknown key for Boolean: EnableTransactions
Nov  9 12:56:36 MacBook-Air com.apple.CoreSimulator.SimDevice.0681E214-40BE-4242-818C-BBAD953A591C[2807] (com.apple.backboard.display.archive): Unknown key for Boolean: EnablePressuredExit
Nov  9 12:56:36 MacBook-Air com.apple.CoreSimulator.SimDevice.0681E214-40BE-4242-818C-BBAD953A591C[2807] (com.apple.imfoundation.IMRemoteURLConnectionAgent): Unknown key for Boolean: EnableTransactions
Nov  9 12:56:36 MacBook-Air com.apple.CoreSimulator.SimDevice.0681E214-40BE-4242-818C-BBAD953A591C[2807] (com.apple.imfoundation.IMRemoteURLConnectionAgent): Unknown key for integer: _DirtyJetsamMemoryLimit
Nov  9 12:56:36 MacBook-Air com.apple.CoreSimulator.SimDevice.0681E214-40BE-4242-818C-BBAD953A591C[2807] (com.apple.imfoundation.IMRemoteURLConnectionAgent): Unknown key for Boolean: EnablePressuredExit
Nov  9 12:56:36 MacBook-Air com.apple.CoreSimulator.SimDevice.0681E214-40BE-4242-818C-BBAD953A591C[2807] (com.apple.intents.intents-helper): Unknown key for Boolean: EnableTransactions
Nov  9 12:56:36 MacBook-Air com.apple.CoreSimulator.SimDevice.0681E214-40BE-4242-818C-BBAD953A591C[2807] (com.apple.intents.intents-helper): Unknown key for Boolean: EnablePressuredExit
Nov  9 12:56:36 MacBook-Air com.apple.CoreSimulator.SimDevice.0681E214-40BE-4242-818C-BBAD953A591C[2807] (com.apple.uifoundation-bundle-helper): Unknown key for Boolean: EnableTransactions
Nov  9 12:56:36 MacBook-Air com.apple.CoreSimulator.SimDevice.0681E214-40BE-4242-818C-BBAD953A591C[2807] (com.apple.uifoundation-bundle-helper): Unknown key for Boolean: EnablePressuredExit
Nov  9 12:56:36 MacBook-Air DevN2[5611]: assertion failed: 18A384a 16B91: libxpc.dylib + 79599 [F7D4B188-D5C2-3E5E-BB76-BC7C6A368166]: 0x7d`

**Comment by hackiftekhar** [comment]
@szvarhegyi it doesn't look like an issue from our library

**Comment by qbikode** [comment]
I solved the problem by cleaning the project and removing Xcode's `DerivedData` folder.
