### ISSUE TITLE
ScrollView has redundant empty area after keyboard dismiss and navigationBar prefersLargeTitles = true

### ISSUE THREAD

**Issue by seeanhuang** [hackiftekhar/IQKeyboardManager#1473]
**Describe the bug**
When navigationBar prefersLargeTitles set true, the scrollView will show redundant empty area after keyboard dismiss.

**To Reproduce**
1. Scroll to bottom to let view controller title become small.
2. tap textField to show keyboard.
3. tap outside to dismiss keyboard.
4. Issue occur.

**Comment by hackiftekhar** [comment]
okay, will try to take a look at this

**Comment by rroca1982** [comment]
Also having this problem, any news? Workaround?

**Comment by srikanthsrnvs** [comment]
Same issue, temporarily calculating the position of the text label manually to workaround the issue, but would love a fix

**Comment by hackiftekhar** [comment]
Not able to reproduce this issue. Can someone share demo project?

**Comment by npankin** [comment]
Maybe this helps:

![IQKeyboardManager-2](https://user-images.githubusercontent.com/11706490/62049762-988f5400-b218-11e9-82f7-a8cab19a8939.gif)

Steps to reproduce the behavior:
1. Have a table view long enough to scroll. Have a first cell with textfield in there
2. Nav bar is large.
3. Click on text field. 
4. Keyboard appears
5. scroll up. nav bar is regular
6. dismiss the keyboard

Code:
UINavigationBar.appearance().prefersLargeTitles = true
IQKeyboardManager.shared.enable = false
IQKeyboardManager.shared.enableAutoToolbar = false
IQKeyboardManager.shared.enabledDistanceHandlingClasses.append(VC.self)
IQKeyboardManager.shared.enabledToolbarClasses.append(VC.self)

**Comment by antoinepemeja** [comment]
Hello, I have the same issue when I use UIViewController with Large title.

in **AppDelegate.swift** :
`
        IQKeyboardManager.shared().isEnabled = true
        IQKeyboardManager.shared().isEnableAutoToolbar = true
        IQKeyboardManager.shared().shouldToolbarUsesTextFieldTintColor = true
        IQKeyboardManager.shared().toolbarManageBehaviour = IQAutoToolbarManageBehaviour.byPosition
        IQKeyboardManager.shared().shouldResignOnTouchOutside = true
`

**Comment by alihanaktay** [comment]
Same issue happens. Is there any progress about this issue?

**Comment by jerometonnelier** [comment]
Same here ;-) Any news ? Thanks.
