### ISSUE TITLE
iPhone X upside down keyboard problem

### ISSUE THREAD

**Issue by elorusso** [hackiftekhar/IQKeyboardManager#1474]
**Describe the bug**
The keyboard toolbar is not positioned correctly when app is upside down on iPhone X

**Screenshots**
![simulator screen shot - iphone x - 2018-11-05 at 15 45 57](https://user-images.githubusercontent.com/4721109/48025680-199a3e80-e112-11e8-9575-9012069e36e3.png
.

**Comment by hackiftekhar** [comment]
Can you please share a demo project?
