### ISSUE TITLE
Input box and keyboard spacing problem

### ISSUE THREAD

**Issue by isonmal** [hackiftekhar/IQKeyboardManager#1475]
**Describe the bug**
Input box and keyboard spacing problem when I set  vc.hidesBottomBarWhenPushed = true  

**Screenshots**

![c558e286-4da4-4f12-9385-c90502061493](https://user-images.githubusercontent.com/8736851/48113695-0cf32300-e297-11e8-8ef2-e415aa0cf5fa.png)

### Versions
**Xcode:** 10.1
**Mac OS:** 10.14.1
**Simulator/Device:** iPhoneXS 12.1
**Library Version:** 6.2.0

**Comment by saroar** [comment]
hi did you fixed it same problem here too

**Comment by hackiftekhar** [comment]
The spacing looks good to me. What's the exact problem can yo guys please elaborate?
