### ISSUE TITLE
IQ Keybard Keys (Left right and the done button)

### ISSUE THREAD

**Issue by mayankwadhwa111** [hackiftekhar/IQKeyboardManager#1476]
When I use a real device the keys rise above the keyboard as usual but the height to which the keys rise is awkward but they are functional still at the initial position.
![evidence](https://user-images.githubusercontent.com/42866329/48397427-9dbc7980-e743-11e8-9dcb-9ffc665c3226.png)

**Comment by Banck** [comment]
Hello. 
Do you use any libs for transitions, i.e Hero or Motion?

**Comment by mayankwadhwa111** [comment]
> Hello Banck .
> Do you use any libs for transitions, i.e Hero or Motion?

Yeah we use Hero for that

**Comment by Banck** [comment]
Hero doesn’t work well with iqkeyboard. 
You can try to do view.endEditing(true) in viewwilldisappear in previous view controller. It can help you. 
Or replace Hero with Motion, with Motion endEditing in viewwilldisappear works fine

**Comment by mayankwadhwa111** [comment]
Absolutely miraculous Bacn thank you so Much Banck
