### ISSUE TITLE
Extra White Space for iOS devices < iOS 11 for search Bar controller

### ISSUE THREAD

**Issue by geeksweep** [hackiftekhar/IQKeyboardManager#1477]
**Describe the bug**

Search Bar animation doesn't animate correctly up to top of view when selected. Instead its position leaves a white space between the top of the Search Bar and the top of the view. 

The view controller setup is a View Controller with a Navigation Bar with a search Bar controller above a tableView. 

**To Reproduce**
1. Set up a search bar controller with a tableview, all underneath the navigation bar. 
2. When selecting the searchBar the searchBar animates up, as expected, as the navigation bar (and title) disappears but the search bar immediately animates down to its original position, leaving a big white space between the top of the view and the search bar. 
3. This problem appears on devices that are not at least iOS 11.
4. In the simulator, You only get this bug if you disable 'Connect Hardware Keyboard' - i.e. where the simulator keyboard is visible on the simulator. - to simulate what happens on an actual device.

**Expected behavior**
The search bar should stay at the top of the view until the user dismisses it with a 'Done' or similar. 

**Screenshots**
No screenshots as of now

**Demo Project**
None as of now.

### Versions
**Xcode:** 10.0, Swift 4.1
**Mac OS:** 10.13.6
**Simulator/Device:** All Simulators/Devices below iOS 11.0
**Simulator/Device Name:** (See Above)
**Library Version:** ->  **Any version greater than 5.0.8**

**Additional context**
There seems to be something going on with the keyboard animation - how it calculates its height, or the tableview or something. Apple changed how the search bar and its hierarchy worked after iOS 11.0, so I am assuming that something in the code doesn't check for devices that have at least iOS 11.0 installed.

**Comment by jorgeb12** [comment]
Same here. I just disabled using 
    IQKeyboardManager.shared().isEnabled = false in that viewcontroller

**Comment by hackiftekhar** [comment]
Can you please share a demo project?
