### ISSUE TITLE
Error Occurring after migrating to swift 4.2.

### ISSUE THREAD

**Issue by baquer** [hackiftekhar/IQKeyboardManager#1478]
**Migration to swift4.2**

After migrating to swift 4.2  , it is giving this error 
Cannot subscript a value of type '[NSAttributedString.Key : Any]' with an index of type 'String'

**Screenshots**
![screenshot 2018-11-16 at 12 32 06 pm](https://user-images.githubusercontent.com/32494694/48603218-cccd2800-e99b-11e8-9658-35fc22521164.png)

### Versions
**Xcode:** 10.0
**Mac OS:** 10.14
**Simulator/Device Name:** iPhone XR
**Library Version:** 6.0.4.

**Comment by jasonhr13** [comment]
Same issue here, has anything come of this?

**Comment by osianSmith** [comment]
I just removed it from my pod for migration and placed it back in after

**Comment by hackiftekhar** [comment]
There was compile time check. Do you know why it's not working?

**Comment by osianSmith** [comment]
I removed it from my pods, updates pods, put it back in and then update poss so you end back with the swift 4 version

**Comment by osianSmith** [comment]
Any update if that works?

**Comment by Phontaine** [comment]
Error still showing. Any updates?

**Comment by Phontaine** [comment]
Looks like removing it from the podfile then reinstalling works.

**Comment by hackiftekhar** [comment]
Thanks for posting workaround guys. I actually don't k know why this happens, but it should not because I have explicitly added conpile time validations for swift versions.
