### ISSUE TITLE
Main View under navigation bar after closing keyboard

### ISSUE THREAD

**Issue by mediym41** [hackiftekhar/IQKeyboardManager#1479]
After closing keyboard, view move up under navigation bar.  I found this solution https://stackoverflow.com/questions/50095254/iqkeyboardmanager-issue-uiviewcontroller-top-overlapping-status-bar , but it didn't help me. How can i avoid this problem?
Before:
<img width="428" alt="2018-11-16 14 24 37" src="https://user-images.githubusercontent.com/40239114/48632471-a2925f00-e9c9-11e8-9a48-250029290681.png">
After:
<img width="431" alt="2018-11-16 17 23 25" src="https://user-images.githubusercontent.com/40239114/48632365-65c66800-e9c9-11e8-83c6-acbcde272041.png">

**Comment by mediym41** [comment]
on viewDidLoad, changed on viewWillAppear and it work fine. Thank you so much!

**Comment by deveshprk96** [comment]
change 'becomefirstresponder' code in 'viewedidappear' then sometime it will automatically works fine
