### ISSUE TITLE
Placeholder text in toolbar not change

### ISSUE THREAD

**Issue by hugo53** [hackiftekhar/IQKeyboardManager#148]
Hi @hackiftekhar ,

Thank you for this awesome library. It helps me so much. I really appreciate that.

Now I have a problem with placeholder on toolbar. Let me describe and please give me a suggestion:

1. First, I have a textfield, placehoder is "This is address of type A" when the current type is A.
2. Then, I change type A to type B. Now, current type is B, the placeholder text of TextField is set to "This is address of type B". However, placeholder on toolbar of keyboard is still "This is address of type A". Desire text for that should be "This is address of type B".

Please take a look and give me an advice. Thank you so much!

Have a great week,
Hoang Nguyen

**Comment by hackiftekhar** [comment]
Will try to fix, thanks

On Monday, January 19, 2015, Minh-Hoang, Nguyen <notifications@github.com>
wrote:

> Hi @hackiftekhar <https://github.com/hackiftekhar> ,
>
> Thank you for this awesome library. It helps me so much. I really
> appreciate that.
>
> Now I have a problem with placeholder on toolbar. Let me describe and
> please give me a suggestion:
>
>    1. First, I have a textfield, placehoder is "This is address of type
>    A" when the current type is A.
>    2. Then, I change type A to type B. Now, current type is B, the
>    placeholder text of TextField is set to "This is address of type B".
>    However, placeholder on toolbar of keyboard is still "This is address of
>    type A". Desire text for that should be "This is address of type B".
>
> Please take a look and give me an advice. Thank you so much!
>
> Have a great week,
> Hoang Nguyen
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackiftekhar/IQKeyboardManager/issues/148>.
>


-- 
Sent from My iPhone

**Comment by hackiftekhar** [comment]
Fixed placeholder caching logic.

**Comment by hugo53** [comment]
@hackiftekhar  So quick, thank you for your support. Keep moving, bro!

**Comment by RamandeepGosal** [comment]
Hello There, 

Literally its an awesome library , I keep using it in each of my projects.
But what i want to do is change the toolbar text for a certain textfeild in my code. 
lets say i have a textfeild with date picker an I want to show the chosen date there (with year). 
can it be done in any manner ?
can I change the tool bar text in any manner ?

**Comment by hackiftekhar** [comment]
It's already there. There is `placeholderText` in `IQUIView+IQKeyboardToolbar.h` file, please update it according to your requirement for that textField and it will update the toolbar displayed text. :)
