### ISSUE TITLE
5.0.8: orphan keyboard after rotating to landscape (iPhone)

### ISSUE THREAD

**Issue by NeilTaylor** [hackiftekhar/IQKeyboardManager#1480]
**Describe the bug**

5.0.8: kb still showing after rotating to landscape, text field no longer active, kb buttons appear responsive but do nothing.

By rotating back to portrait or navigating to ANY viewcontroller, the kb is still displayed but the kb buttons are still unresponsive. The kb can only be dismissed by selecting a text field (on any viewcontroller) and activating another kb.

This unexpected behavior is on the iPhone only. WIth the iPad the behavior is consistent (the kb is hidden and the text field is no longer active). 

Behavior is different when rotating from landscape to portrait.
With the iPhone, a selected text field remains active and the kb remains displayed when rotating from landscape to portrait. With the iPad, selected text field becomes inactive and kb is dismissed.

**To Reproduce**
5.0.8
This is reproducible with one of my app store apps.

**Expected behavior**
I would expect the kb to dismiss and stay dismissed. Based on the debug showLog(), it appears that the kb is hidden (dismissed?) but is then re-shown.

**iPhone debug:**

IQKeyboardManager: ****** willChangeStatusBarOrientation started ******
IQKeyboardManager: ****** willChangeStatusBarOrientation ended: 0.0005421250243671238 seconds ******
IQKeyboardManager: ****** didChangeStatusBarFrame started ******
IQKeyboardManager: Saving <<Drive_YES_.MainTabBarViewController: 0x109024000> 0x0000000109024000> beginning Frame: (0.0, 0.0, 736.0, 414.0)
IQKeyboardManager: ****** adjustFrame() started ******
IQKeyboardManager: Need to move: 15.0
IQKeyboardManager: Adjusting -15.0 to <<UIScrollView: 0x108881600; frame = (0 0; 414 574); clipsToBounds = YES; autoresize = RM+BM; gestureRecognizers = <NSArray: 0x281ee1f20>; layer = <CALayer: 0x281009720>; contentOffset: {0, 0}; contentSize: {414, 694}; adjustedContentInset: {0, 0, 172, 0}> 0x0000000108881600> ContentOffset
IQKeyboardManager: Remaining Move: 0.0
IQKeyboardManager: <<UIScrollView: 0x108881600; frame = (0 0; 414 574); clipsToBounds = YES; autoresize = RM+BM; gestureRecognizers = <NSArray: 0x281ee1f20>; animations = { bounds.origin=<CABasicAnimation: 0x28105c8a0>; bounds.size=<CABasicAnimation: 0x28105db60>; }; layer = <CALayer: 0x281009720>; contentOffset: {0, 15}; contentSize: {414, 694}; adjustedContentInset: {0, 0, 172, 0}> 0x0000000108881600> old ContentInset : UIEdgeInsets(top: 0.0, left: 0.0, bottom: 172.0, right: 0.0)
IQKeyboardManager: <<UIScrollView: 0x108881600; frame = (0 0; 414 574); clipsToBounds = YES; autoresize = RM+BM; gestureRecognizers = <NSArray: 0x281ee1f20>; animations = { bounds.origin=<CABasicAnimation: 0x28105c8a0>; bounds.size=<CABasicAnimation: 0x28105db60>; }; layer = <CALayer: 0x281009720>; contentOffset: {0, 15}; contentSize: {414, 694}; adjustedContentInset: {0, 0, 494, 0}> 0x0000000108881600> new ContentInset : UIEdgeInsets(top: 0.0, left: 0.0, bottom: 494.0, right: 0.0)
IQKeyboardManager: Moving Upward
IQKeyboardManager: Set Optional("<<Drive_YES_.MainTabBarViewController: 0x109024000> 0x0000000109024000>") frame to : (0.0, 0.0, 736.0, 414.0)
IQKeyboardManager: ****** adjustFrame() ended: 0.003216666664229706 seconds ******
IQKeyboardManager: ****** didChangeStatusBarFrame ended: 0.003565749997505918 seconds ******

IQKeyboardManager: ****** textFieldViewDidEndEditing started ******
IQKeyboardManager: ****** textFieldViewDidEndEditing ended: 9.133334970101714e-05 seconds ******

IQKeyboardManager: ****** textFieldViewDidBeginEditing started ******
IQKeyboardManager: ****** addToolbarIfRequired() started ******
IQKeyboardManager: Found 4 responder sibling(s)
IQKeyboardManager: ****** addToolbarIfRequired() ended: 0.00193425000179559 seconds ******
IQKeyboardManager: ****** adjustFrame() started ******
IQKeyboardManager: Need to move: -20.0
IQKeyboardManager: Adjusting 15.0 to <<UIScrollView: 0x108881600; frame = (0 0; 415.667 272); clipsToBounds = YES; autoresize = RM+BM; gestureRecognizers = <NSArray: 0x281ee1f20>; animations = { bounds.origin=<CABasicAnimation: 0x28105c8a0>; bounds.size=<CABasicAnimation: 0x28105db60>; bounds.origin-2=<CABasicAnimation: 0x2810c39e0>; bounds.size-2=<CABasicAnimation: 0x2810c3a20>; position=<CABasicAnimation: 0x28103c4e0>; bounds.origin-3=<CABasicAnimation: 0x28110d600>; bounds.size-3=<CABasicAnimation: 0x28110d660>; position-2=<CABasicAnimation: 0x28110d700>; }; layer = <CALayer: 0x281009720>; contentOffset: {0, 15}; contentSize: {415.66666666666669, 694}; adjustedContentInset: {0, 0, 494, 0}> 0x0000000108881600> ContentOffset
IQKeyboardManager: Remaining Move: -5.0
IQKeyboardManager: <<UIScrollView: 0x108881600; frame = (0 0; 415.667 272); clipsToBounds = YES; autoresize = RM+BM; gestureRecognizers = <NSArray: 0x281ee1f20>; animations = { bounds.origin=<CABasicAnimation: 0x28105c8a0>; bounds.size=<CABasicAnimation: 0x28105db60>; bounds.origin-2=<CABasicAnimation: 0x2810c39e0>; bounds.size-2=<CABasicAnimation: 0x2810c3a20>; position=<CABasicAnimation: 0x28103c4e0>; bounds.origin-3=<CABasicAnimation: 0x28110d600>; bounds.size-3=<CABasicAnimation: 0x28110d660>; position-2=<CABasicAnimation: 0x28110d700>; bounds.origin-4=<CABasicAnimation: 0x281183be0>; bounds.size-4=<CABasicAnimation: 0x281183c60>; }; layer = <CALayer: 0x281009720>; contentOffset: {0, 0}; contentSize: {415.66666666666669, 694}; adjustedContentInset: {0, 0, 494, 0}> 0x0000000108881600> old ContentInset : UIEdgeInsets(top: 0.0, left: 0.0, bottom: 494.0, right: 0.0)
IQKeyboardManager: <<UIScrollView: 0x108881600; frame = (0 0; 415.667 272); clipsToBounds = YES; autoresize = RM+BM; gestureRecognizers = <NSArray: 0x281ee1f20>; animations = { bounds.origin=<CABasicAnimation: 0x28105c8a0>; bounds.size=<CABasicAnimation: 0x28105db60>; bounds.origin-2=<CABasicAnimation: 0x2810c39e0>; bounds.size-2=<CABasicAnimation: 0x2810c3a20>; position=<CABasicAnimation: 0x28103c4e0>; bounds.origin-3=<CABasicAnimation: 0x28110d600>; bounds.size-3=<CABasicAnimation: 0x28110d660>; position-2=<CABasicAnimation: 0x28110d700>; bounds.origin-4=<CABasicAnimation: 0x281183be0>; bounds.size-4=<CABasicAnimation: 0x281183c60>; }; layer = <CALayer: 0x281009720>; contentOffset: {0, 0}; contentSize: {415.66666666666669, 694}; adjustedContentInset: {0, 0, 172, 0}> 0x0000000108881600> new ContentInset : UIEdgeInsets(top: 0.0, left: 0.0, bottom: 172.0, right: 0.0)
IQKeyboardManager: Moving Downward
IQKeyboardManager: Set Optional("<<Drive_YES_.MainTabBarViewController: 0x109024000> 0x0000000109024000>") frame to : (0.0, 0.0, 736.0, 414.0)
IQKeyboardManager: ****** adjustFrame() ended: 0.013164666685042903 seconds ******
IQKeyboardManager: ****** textFieldViewDidBeginEditing ended: 0.015446250006789342 seconds ******
IQKeyboardManager: ****** keyboardWillHide started ******
IQKeyboardManager: Restoring <<UIScrollView: 0x108881600; frame = (0 0; 415.667 272); clipsToBounds = YES; autoresize = RM+BM; gestureRecognizers = <NSArray: 0x281ee1f20>; animations = { bounds.origin=<CABasicAnimation: 0x28105c8a0>; bounds.size=<CABasicAnimation: 0x28105db60>; bounds.origin-2=<CABasicAnimation: 0x2810c39e0>; bounds.size-2=<CABasicAnimation: 0x2810c3a20>; position=<CABasicAnimation: 0x28103c4e0>; bounds.origin-3=<CABasicAnimation: 0x28110d600>; bounds.size-3=<CABasicAnimation: 0x28110d660>; position-2=<CABasicAnimation: 0x28110d700>; bounds.origin-4=<CABasicAnimation: 0x281183be0>; bounds.size-4=<CABasicAnimation: 0x281183c60>; }; layer = <CALayer: 0x281009720>; contentOffset: {0, 0}; contentSize: {415.66666666666669, 694}; adjustedContentInset: {0, 0, 0, 0}> 0x0000000108881600> contentInset to : UIEdgeInsets(top: 0.0, left: 0.0, bottom: 0.0, right: 0.0) and contentOffset to : (0.0, 0.0)
IQKeyboardManager: Restoring <<Drive_YES_.MainTabBarViewController: 0x109024000> 0x0000000109024000> frame to : (0.0, 0.0, 736.0, 414.0)
IQKeyboardManager: ****** keyboardWillHide ended: 0.0004755416593980044 seconds ******
IQKeyboardManager: ****** keyboardDidHide started ******
IQKeyboardManager: ****** keyboardDidHide ended: 1.0333344107493758e-05 seconds ******

IQKeyboardManager: ****** textFieldViewDidEndEditing started ******
IQKeyboardManager: ****** textFieldViewDidEndEditing ended: 0.00027745834086090326 seconds ******

IQKeyboardManager: UIKeyboard Size : (736.0, 206.0)
IQKeyboardManager: ****** keyboardWillShow started ******
IQKeyboardManager: ****** keyboardWillShow ended: 6.179165211506188e-05 seconds ******
IQKeyboardManager: ****** keyboardDidShow started ******
IQKeyboardManager: ****** keyboardDidShow ended: 1.3999990187585354e-05 seconds ******

**iPad debug:**
IQKeyboardManager: ****** willChangeStatusBarOrientation started ******
IQKeyboardManager: ****** willChangeStatusBarOrientation ended: 0.00024016665702220052 seconds ******
IQKeyboardManager: ****** didChangeStatusBarFrame started ******
IQKeyboardManager: Saving <<Drive_YES_.MainTabBarViewController: 0x10402ca00> 0x000000010402ca00> beginning Frame: (0.0, 0.0, 1024.0, 768.0)
IQKeyboardManager: ****** adjustFrame() started ******
IQKeyboardManager: Need to move: -246.0
IQKeyboardManager: <<UIScrollView: 0x105022800; frame = (0 0; 447.5 854); clipsToBounds = YES; autoresize = RM+BM; gestureRecognizers = <NSArray: 0x2838d4030>; layer = <CALayer: 0x283604c60>; contentOffset: {0, 0}; contentSize: {447.5, 694}; adjustedContentInset: {0, 0, 257, 0}> 0x0000000105022800> old ContentInset : UIEdgeInsets(top: 0.0, left: 0.0, bottom: 257.0, right: 0.0)
IQKeyboardManager: <<UIScrollView: 0x105022800; frame = (0 0; 447.5 854); clipsToBounds = YES; autoresize = RM+BM; gestureRecognizers = <NSArray: 0x2838d4030>; layer = <CALayer: 0x283604c60>; contentOffset: {0, 0}; contentSize: {447.5, 694}; adjustedContentInset: {0, 0, 513, 0}> 0x0000000105022800> new ContentInset : UIEdgeInsets(top: 0.0, left: 0.0, bottom: 513.0, right: 0.0)
IQKeyboardManager: Moving Downward
IQKeyboardManager: Set Optional("<<Drive_YES_.MainTabBarViewController: 0x10402ca00> 0x000000010402ca00>") frame to : (0.0, 0.0, 1024.0, 768.0)
IQKeyboardManager: ****** adjustFrame() ended: 0.0018712083401624113 seconds ******
IQKeyboardManager: ****** didChangeStatusBarFrame ended: 0.0022405833296943456 seconds ******
IQKeyboardManager: ****** keyboardWillHide started ******
IQKeyboardManager: Restoring <<UIScrollView: 0x105022800; frame = (0 0; 703.5 598); clipsToBounds = YES; autoresize = RM+BM; gestureRecognizers = <NSArray: 0x2838d4030>; animations = { bounds=<CABasicAnimation: 0x2836387e0>; position=<CABasicAnimation: 0x283638220>; }; layer = <CALayer: 0x283604c60>; contentOffset: {0, 0}; contentSize: {703.5, 694}; adjustedContentInset: {0, 0, 0, 0}> 0x0000000105022800> contentInset to : UIEdgeInsets(top: 0.0, left: 0.0, bottom: 0.0, right: 0.0) and contentOffset to : (0.0, 0.0)
IQKeyboardManager: Restoring <<Drive_YES_.MainTabBarViewController: 0x10402ca00> 0x000000010402ca00> frame to : (0.0, 0.0, 1024.0, 768.0)
IQKeyboardManager: ****** keyboardWillHide ended: 0.0010562916722847149 seconds ******
IQKeyboardManager: ****** keyboardDidHide started ******
IQKeyboardManager: ****** keyboardDidHide ended: 4.474999150261283e-05 seconds ******

IQKeyboardManager: UIKeyboard Size : (1024.0, 186.0)
IQKeyboardManager: ****** keyboardWillShow started ******
IQKeyboardManager: Saving <<Drive_YES_.MainTabBarViewController: 0x10402ca00> 0x000000010402ca00> beginning Frame: (0.0, 0.0, 1024.0, 768.0)
IQKeyboardManager: ****** adjustFrame() started ******
IQKeyboardManager: Need to move: -417.0
IQKeyboardManager: Saving <<UIScrollView: 0x105022800; frame = (0 0; 703.5 598); clipsToBounds = YES; autoresize = RM+BM; gestureRecognizers = <NSArray: 0x2838d4030>; layer = <CALayer: 0x283604c60>; contentOffset: {0, 0}; contentSize: {703.5, 694}; adjustedContentInset: {0, 0, 0, 0}> 0x0000000105022800> contentInset : UIEdgeInsets(top: 0.0, left: 0.0, bottom: 0.0, right: 0.0) and contentOffset : (0.0, 0.0)
IQKeyboardManager: <<UIScrollView: 0x105022800; frame = (0 0; 703.5 598); clipsToBounds = YES; autoresize = RM+BM; gestureRecognizers = <NSArray: 0x2838d4030>; layer = <CALayer: 0x283604c60>; contentOffset: {0, 0}; contentSize: {703.5, 694}; adjustedContentInset: {0, 0, 0, 0}> 0x0000000105022800> old ContentInset : UIEdgeInsets(top: 0.0, left: 0.0, bottom: 0.0, right: 0.0)
IQKeyboardManager: <<UIScrollView: 0x105022800; frame = (0 0; 703.5 598); clipsToBounds = YES; autoresize = RM+BM; gestureRecognizers = <NSArray: 0x2838d4030>; layer = <CALayer: 0x283604c60>; contentOffset: {0, 0}; contentSize: {703.5, 694}; adjustedContentInset: {0, 0, 86, 0}> 0x0000000105022800> new ContentInset : UIEdgeInsets(top: 0.0, left: 0.0, bottom: 86.0, right: 0.0)
IQKeyboardManager: Moving Downward
IQKeyboardManager: Set Optional("<<Drive_YES_.MainTabBarViewController: 0x10402ca00> 0x000000010402ca00>") frame to : (0.0, 0.0, 1024.0, 768.0)
IQKeyboardManager: ****** adjustFrame() ended: 0.004753958332003094 seconds ******
IQKeyboardManager: ****** keyboardWillShow ended: 0.00550683333131019 seconds ******
IQKeyboardManager: ****** keyboardDidShow started ******
IQKeyboardManager: ****** keyboardDidShow ended: 8.754167356528342e-05 seconds ******
IQKeyboardManager: UIKeyboard Size : (1024.0, 442.0)
IQKeyboardManager: ****** keyboardWillShow started ******
IQKeyboardManager: ****** adjustFrame() started ******
IQKeyboardManager: Need to move: -161.0
IQKeyboardManager: <<UIScrollView: 0x105022800; frame = (0 0; 703.5 598); clipsToBounds = YES; autoresize = RM+BM; gestureRecognizers = <NSArray: 0x2838d4030>; layer = <CALayer: 0x283604c60>; contentOffset: {0, 0}; contentSize: {703.5, 694}; adjustedContentInset: {0, 0, 86, 0}> 0x0000000105022800> old ContentInset : UIEdgeInsets(top: 0.0, left: 0.0, bottom: 86.0, right: 0.0)
IQKeyboardManager: <<UIScrollView: 0x105022800; frame = (0 0; 703.5 598); clipsToBounds = YES; autoresize = RM+BM; gestureRecognizers = <NSArray: 0x2838d4030>; layer = <CALayer: 0x283604c60>; contentOffset: {0, 0}; contentSize: {703.5, 694}; adjustedContentInset: {0, 0, 342, 0}> 0x0000000105022800> new ContentInset : UIEdgeInsets(top: 0.0, left: 0.0, bottom: 342.0, right: 0.0)
IQKeyboardManager: Moving Downward
IQKeyboardManager: Set Optional("<<Drive_YES_.MainTabBarViewController: 0x10402ca00> 0x000000010402ca00>") frame to : (0.0, 0.0, 1024.0, 768.0)
IQKeyboardManager: ****** adjustFrame() ended: 0.0026614166708895937 seconds ******
IQKeyboardManager: ****** keyboardWillShow ended: 0.0028629166627069935 seconds ******
IQKeyboardManager: ****** keyboardDidShow started ******
IQKeyboardManager: ****** keyboardDidShow ended: 6.870832294225693e-05 seconds ******

IQKeyboardManager: ****** keyboardWillHide started ******
IQKeyboardManager: Restoring <<UIScrollView: 0x105022800; frame = (0 0; 703.5 598); clipsToBounds = YES; autoresize = RM+BM; gestureRecognizers = <NSArray: 0x2838d4030>; layer = <CALayer: 0x283604c60>; contentOffset: {0, 0}; contentSize: {703.5, 694}; adjustedContentInset: {0, 0, 0, 0}> 0x0000000105022800> contentInset to : UIEdgeInsets(top: 0.0, left: 0.0, bottom: 0.0, right: 0.0) and contentOffset to : (0.0, 0.0)
IQKeyboardManager: Restoring <<Drive_YES_.MainTabBarViewController: 0x10402ca00> 0x000000010402ca00> frame to : (0.0, 0.0, 1024.0, 768.0)
IQKeyboardManager: ****** keyboardWillHide ended: 0.0018790833273669705 seconds ******
IQKeyboardManager: ****** textFieldViewDidEndEditing started ******
IQKeyboardManager: ****** textFieldViewDidEndEditing ended: 0.0004911666619591415 seconds ******

IQKeyboardManager: ****** keyboardDidHide started ******
IQKeyboardManager: ****** keyboardDidHide ended: 8.691666880622506e-05 seconds ******

**Screenshots**
N/A

**Demo Project**
Maybe later, if I have time

### Versions
**Xcode:** 10.1

**Mac OS:** 10.14.1 (Mojave)

**Simulator/Device:** 
**Simulator/Device Name:** iPhone 8 Plus
**Library Version:** 5.0.8

**Additional context**
This is very minor - to me.

**Comment by hackiftekhar** [comment]
The library doesn't interact or change any internal implementation with the Software keyboard, so if buttons doesn't do anything then probably library isn't responsible for this. May be thats an Apple bug?
