### ISSUE TITLE
6.2.0: inconsistent spacing between views and keyboard

### ISSUE THREAD

**Issue by NeilTaylor** [hackiftekhar/IQKeyboardManager#1481]
**Describe the bug**
Spacing between text views/fields and keyboard are incorrect. I have returned to using 5.0.8, which has perfect spacing.

**To Reproduce**
I was able to reproduce this in all data entry viewcontrollers of one of my apps I was updating.

**Expected behavior**
Expect spacing to be like it was in 5.0.8

**Screenshots**
After I am done with my current development, I may return to trying 6.2.0 to demonstrate with some screenshots.

**Demo Project**
After I am done with my current development, I may return to trying 6.2.0 to demonstrate with a demo project.

### Versions
**Xcode:** 10.1
**Mac OS:** 10.14.1 (Mojave)
**Simulator/Device:** any
**Simulator/Device Name:** any
**Library Version:** 6.2.0

**Additional context**
I turned on debug and attempted to move back and forth between first and second text views. I observed the values displayed in the adjustPosition() method increasing and decreasing with each move. The behavior reflected the increasing and decreasing position adjustments such that the views containing the text views were completely scrolled beyond the bounds of the parent viewcontroller.

**Comment by saroar** [comment]
hi did you fixed it ?

**Comment by DanijelHuis** [comment]
Same problem here, it works perfectly on 5.0.8, but on 6.2.0 it is not working correctly. I am uploading video, there are actually two problems:
1) Switching from c to alpha: spacing changes even though this fields have same vertical positions:
2) Switching next-prev multiple times causes that spacing to decrease over time until it covers the textfield.
![iqkeyboardmanager](https://user-images.githubusercontent.com/5382135/51208627-7c783500-190e-11e9-972d-0d83abfff8f5.gif)

**Comment by hackiftekhar** [comment]
There is a similar issue in past, but I'm unable to find out a workaround for this since I debugged that demo and library calculations were correct. But unfortunately UIScrollView internally change their contentOffset.
