### ISSUE TITLE
Up down arrow not showing for textfields in aloe stackview rows

### ISSUE THREAD

**Issue by sujalshrestha** [hackiftekhar/IQKeyboardManager#1482]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Demo Project**
If applicable, add demo project.

### Versions
**Xcode:** x.x
**Mac OS:** xx.xx.x
**Simulator/Device:** xx.x
**Simulator/Device Name:** iPhone xx
**Library Version:** x.x.x

**Additional context**

**Comment by hackiftekhar** [comment]
You may be added those textfield in different containerView, please see how to use IQPreviousNextView
