### ISSUE TITLE
Main View under navigation bar after closing keyboard (recreated)

### ISSUE THREAD

**Issue by mediym41** [hackiftekhar/IQKeyboardManager#1483]
After closing keyboard, view move up under navigation bar. I found this solution https://stackoverflow.com/questions/50095254/iqkeyboardmanager-issue-uiviewcontroller-top-overlapping-status-bar , but it didn't help me. First problem was when i invoke becomeFirstResponder from viewDidLoad, after i replaced to viewWillAppear and it fixed it, but after short period of time bug appears again. How can i avoid this problem?
before:
<img width="406" alt="2018-11-20 01 34 48" src="https://user-images.githubusercontent.com/40239114/48744605-92e87400-ec70-11e8-8618-bf5f558c9de2.png">
after:
<img width="420" alt="2018-11-20 01 34 56" src="https://user-images.githubusercontent.com/40239114/48744614-9a0f8200-ec70-11e8-935e-64a4c29b9195.png">

**Comment by mediym41** [comment]
[TestIQKeyboard.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/2610587/TestIQKeyboard.zip)
It does not work when vc pushed via nav controller(translucent unchecked) and invoked firstResponsed

**Comment by hackiftekhar** [comment]
Are you invoking becomeFirstResponder in viewDidLoad? If that’s the case then it will not work because calculations doesn’t fit well if becomeFirstResponder call in viewDidLoad.

**Comment by mediym41** [comment]
I invoke in viewWillAppear

**Comment by hackiftekhar** [comment]
Please try to invoke in viewDidAppear.
