### ISSUE TITLE
Navigation bar is not coming back to original position

### ISSUE THREAD

**Issue by AghaShahriyar** [hackiftekhar/IQKeyboardManager#1484]
**Describe the bug**
Navigation bar is not coming back to original position after the dismiss of keyboard

 

### Versions
**Xcode:**10.1
**Mac OS:** 10.14.1 
**Device:** iphone 7 plus

**Library Version:** 6.2.0
Original Image

![img_0031 2](https://user-images.githubusercontent.com/38526436/48775756-ccac8f80-ecef-11e8-9ce8-d1b7747f91a2.jpg)

Keyboard appears

![img_0027 2](https://user-images.githubusercontent.com/38526436/48775581-4db75700-ecef-11e8-84a7-64ee5586f449.jpg)

keyboard dismiss, but navigation bar is not coming back to original position

![img_0028](https://user-images.githubusercontent.com/38526436/48775596-5c9e0980-ecef-11e8-9ec3-06b6e35fc32f.jpg)

**Comment by rpdever** [comment]
I have a similar Problem. NavigationBar with large titles, a textview and a Toolbar. After I inserted new lines, the Navigation Bar is going small, but after I pressed Done, the Navigation Bar is still small, but now with a black bar and the toolBar is only a little bit visible.

**Comment by rpdever** [comment]
#1473 This is my Problem

**Comment by darkbit34** [comment]
Any fixes? News?

**Comment by hackiftekhar** [comment]
I'm not able to reproduce this issue with latest release. Can you guys please share demo project?

**Comment by darkbit34** [comment]
Bug is persistent... please solve it.. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hackiftekhar** [comment]
@darkbit34 I'm not able to reproduce this issue, please share demo project with latest version of library.
