### ISSUE TITLE
Black bar between Keyboard and text field

### ISSUE THREAD

**Issue by iastroleo** [hackiftekhar/IQKeyboardManager#1486]
Hello!

I have the same issue (the black line) as shown in this bug report:

https://github.com/hackiftekhar/IQKeyboardManager/issues/93

While trying to use the solution that is given, xCode returns me the error "Value of type 'IQKeyboardManager' has no member 'preventShowingBottomSpace'"

I am using the 'IQKeyboardManagerSwift' pod running on xCode Version 10.1 (10B61) on Mojave

Thank you!

**Comment by hackiftekhar** [comment]
preventShowingBottomBlankSpace is no longer needed now, if you still can reproduce then share a demo.
