### ISSUE TITLE
setEnableAutoToolbar crash

### ISSUE THREAD

**Issue by SPass8013** [hackiftekhar/IQKeyboardManager#1489]
0 CoreFoundation | ___exceptionPreprocess + 228
-- | --
1 libobjc.A.dylib | objc_exception_throw + 56
2 CoreFoundation | +[_CFXNotificationTokenRegistration keyCallbacks]
3 Foundation | -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 112
4 UIKitCore | -[UIApplication _cachedSystemAnimationFenceCreatingIfNecessary:] + 348
5 UIKitCore | -[UIApplication _systemAnimationFenceCreatingIfNecessary:] + 24
6 UIKitCore | +[UIWindow _synchronizedDrawingFence] + 116
7 UIKitCore | +[_UIKeyboardChangedInformation informationForKeyboardUp:withIAV:] + 104
8 UIKitCore | -[_UIRemoteKeyboards prepareToMoveKeyboard:withIAV:showing:forScreen:] + 776
9 UIKitCore | -[UIPeripheralHost(UIKitInternal) setInputViews:animationStyle:] + 480
10 UIKitCore | -[UIPeripheralHost(UIKitInternal) _reloadInputViewsForResponder:] + 2368
11 UIKitCore | -[UIResponder(UIResponderInputViewAdditions) reloadInputViews] + 80
12 Lessee | -[IQKeyboardManager removeToolbarIfRequired] + 856
13 Lessee | -[IQKeyboardManager setEnableAutoToolbar:] + 276
14 Lessee | __35-[AppDelegate delay:launchOptions:]_block_invoke + 504
15 libdispatch.dylib | _dispatch_call_block_and_release + 24
16 libdispatch.dylib | _dispatch_client_callout + 16
17 libdispatch.dylib | _dispatch_queue_override_invoke + 888
18 libdispatch.dylib | _dispatch_root_queue_drain + 376
19 libdispatch.dylib | _dispatch_worker_thread2 + 156
20 libsystem_pthread.dylib | _pthread_wqthread + 472
21 libsystem_pthread.dylib | start_wqthread + 4

**Comment by hackiftekhar** [comment]
By looking at the crash report, it looks like there was a crash but unfortunately I'm unable to reproduce this crash. Please share a demo project if you can.
