### ISSUE TITLE
White done button

### ISSUE THREAD

**Issue by mkeremkeskin** [hackiftekhar/IQKeyboardManager#149]
Hi;

I'm trying keyboard library alternatives. Yours seems to be the most convenient. But I have a problem. Done button on toolbar appears white. I search other issues and stumbled upon [this](https://github.com/hackiftekhar/IQKeyboardManager/issues/54) and thought that so why the arrows are black and done button is white? 

![screen shot 2015-01-19 at 22 50 07](https://cloud.githubusercontent.com/assets/4717926/5807892/3063e7dc-a030-11e4-8e75-acbbdedf7dde.png)

I'm using the below code to change toolbar attributes. When I change it back to black done button appears black.

``` Objective-C
    [[UIBarButtonItem appearance] setTitleTextAttributes:@{
                                                           NSFontAttributeName: [UIFont fontWithName:@"MyriadPro-Regular" size:14],
                                                           NSForegroundColorAttributeName: [UIColor colorWithWhite:0 alpha:1.0],
                                                           NSShadowAttributeName: shadow,
                                                           } forState:UIControlStateNormal];
```

Is this a bug or is it what is supposed to be?

Thanks already.

**Comment by hackiftekhar** [comment]
This may be a bug, because in this case the arrows should also adopt white color. Culd you please share demo code so I can debug it?

**Comment by hackiftekhar** [comment]
Fixed apperance proxy adoption.
