### ISSUE TITLE
An alert appears in xcode

### ISSUE THREAD

**Issue by CaiZhenGitHub** [hackiftekhar/IQKeyboardManager#1491]
CUIThemeStore: No theme registered with id=0 will appear in the import framework above xcode 10
warning.How to solve this problem?

**Comment by hackiftekhar** [comment]
First of all, this doesn't related to the library. So closing this issue. Secondly peoples suggesting to set swift version to 4.2 to fix this warning.
Reference: https://github.com/SwiftKickMobile/SwiftMessages/issues/235
