### ISSUE TITLE
Navigation Bar Extends Width

### ISSUE THREAD

**Issue by kemalekren** [hackiftekhar/IQKeyboardManager#1492]
<img width="306" alt="screen shot 2018-12-03 at 13 34 30" src="https://user-images.githubusercontent.com/7187826/49368687-674d9b00-f700-11e8-8020-5bbb30776fa2.png">

As you can see the image when i clicked search controller in navigation bar, navigation bar height extends. When i disable the IQKeyboardManager problem will be fixed. So I'm sure this problem related IQKeyboardManager also 

I'm using latest version of IQKeyboard Manager , Swift 4.2

**Comment by hackiftekhar** [comment]
Can you please share the demo project so that I can check what might be the cause?
