### ISSUE TITLE
Getting swift compiler error.

### ISSUE THREAD

**Issue by kalpesh22m** [hackiftekhar/IQKeyboardManager#1495]
**Describe the bug**
When I am trying to build my application I am getting swift compiler error message.

**Screenshots**
![screen shot 2018-12-04 at 4 54 15 pm](https://user-images.githubusercontent.com/3585475/49438929-b4f00380-f7e5-11e8-96a2-964f7e0ca10d.png)

### Versions
**Xcode:** 10.1
**Mac OS:** 10.13.6
**Library Version:** 6.0.0

**Comment by ANSCoder** [comment]
@kalpesh22m  This compiler error looks like **Swift version** migration issues. Please make sure which version are you using for your project then install based on Swift version Cocoa Pod.

**Comment by hackiftekhar** [comment]
I've already checked that my project works for swift 3.0, 3.2, 4.0 and 4.2 version without any change. Please verify you are using latest version of library.
