### ISSUE TITLE
Navigation Bar Overlap with Status bar when keyboard is opened.

### ISSUE THREAD

**Issue by SURYAKANTSHARMA** [hackiftekhar/IQKeyboardManager#1496]
**Describe the bug**
Navigation Bar Overlap with Status bar when keyboard is opened.

**To Reproduce**
Just open the keyboard 
It come seldom but some time all navigation bar got hidden some time status bar background color change to white 

**Screenshots**
![overlapnavigationbarwithstatusbar](https://user-images.githubusercontent.com/6416095/49438936-b6b9c700-f7e5-11e8-8438-0c95ee054514.jpg)

### Versions
**Xcode:** 10.1  Swift 4.2 (Latest)
**Mac OS:** xx.xx.x
**Simulator/Device:** 
**Simulator/Device Name:** iPhone xx
**Library Version:** x.x.x

IQKeyboardManager - 6.1.1

**Comment by SURYAKANTSHARMA** [comment]
@hackiftekhar please look into this

**Comment by SURYAKANTSHARMA** [comment]
Second issue screen shot attached: - Status bar background color turned into white color.
![img_f959ac4e398f-1](https://user-images.githubusercontent.com/6416095/49489835-d814c480-f872-11e8-8d6b-43d6f32b0620.jpeg)

**Comment by SURYAKANTSHARMA** [comment]
you can try once just with given version?
IQKeyboardManager - 6.1.1
Xcode: 10.1 Swift 4.2 (Latest)

**Comment by hackiftekhar** [comment]
Please share a demo project since now a days I can't find some time to create demo projects to find out issues. It would be better if you send me one.
