### ISSUE TITLE
关于iOS12.1使用的问题

### ISSUE THREAD

**Issue by xuejingpeng** [hackiftekhar/IQKeyboardManager#1500]
使用iOS12.1，IQKeyboardManager失效了 在tableview中无法正常使用。

**Comment by OHeroJ** [comment]
我也遇到这个问题

**Comment by ChenYanTao666** [comment]
我也遇见这个问题

**Comment by hackiftekhar** [comment]
Can you please elaborate your problem in english otherwise this issue will be closed.

**Comment by zj381652512** [comment]
textView on tableView's bottom will be coverd when keyboard show
