### ISSUE TITLE
IQKeyboardManager doesn't work with JXPagingView

### ISSUE THREAD

**Issue by ddaabboo** [hackiftekhar/IQKeyboardManager#1501]
When I use JXPagingView, IQ library does't work when the TextFieldView was in a UITableViewCell,which is in a ListView nested in JXPagingView. When the TextFieldView become first responder,  the listView's contentOffset does't change, and the TextFieldView was blocked by keyboard. In this case ,Do I need to handle this my self without IQ library? Thanks a lot if you can give me some tips.

**Comment by hackiftekhar** [comment]
This should handle by yourself because both third party libraries are independent and it's your special case you are integrating both libraries. Please read warning section 2nd bullet in README file.
