### ISSUE TITLE
Extra White Space shown when pop an view controller with keyboard appeared

### ISSUE THREAD

**Issue by retsohuang** [hackiftekhar/IQKeyboardManager#1504]
**Describe the bug**
Extra white space is shown when pop a view controller that embed UITableView, no effect when I use UITableViewController directly.
![screenrecording_12-14-2018 16-38-15](https://user-images.githubusercontent.com/785920/49992777-fb044e80-ffbf-11e8-8b28-0e918b5816ac.gif)

**To Reproduce**
1. Tap start
2. Tap TextField to open the keyboard
3. Swipe back or tap back button

**Expected behavior**
Shouldn't have white space 

**Demo Project**
[IQKeyboardManagerBug.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/2679247/IQKeyboardManagerBug.zip)

### Versions
**Xcode:** 10.1
**Mac OS:** 10.14.1
**Simulator/Device:** 12.1
**Simulator/Device Name:** iPhone XS
**Library Version:** 6.2.0

**Comment by hackiftekhar** [comment]
The library didn’t get any callback when user use pop gesture recognizer to pop. So I’m unable to fix this issue.

**Comment by mjmsmith** [comment]
I ran into this problem, and in one case, more extreme visual glitches. I worked around it by calling endEditing() on the main view:

```
  public override func viewWillDisappear(_ animated: Bool) {
    super.viewWillDisappear(animated)
    self.view.endEditing(true)
  }

```

It's not a perfect solution, but overall I think it looks better than the above.
