### ISSUE TITLE
App with multiple windows

### ISSUE THREAD

**Issue by linarchabibulin** [hackiftekhar/IQKeyboardManager#1506]
One might not consider this as an issue (so if you think it is not - then feel free to close it) as most of the time apps has just one UIWindow instance (which is full screen size). But in case content window size is not equal to device size (app has more than one window or window size is need to be changed for some reason) the frame calculations in `keyboardWillShow` method can be off as it uses UIScreen instead of window size.

**Comment by hackiftekhar** [comment]
Okay, cannyou olease provide more details about the issue with an example or demo?

**Comment by linarchabibulin** [comment]
@hackiftekhar link to demo project - https://github.com/linarchabibulin/KeyboardManagerIssueExample

branch - twoWindows 

try walking between textfields.

**Comment by hackiftekhar** [comment]
Thanks for the demo project @linarchabibulin I'll try to find the cause of the issue you mentioned.
