### ISSUE TITLE
Is there a way to access next and previous button handlers?

### ISSUE THREAD

**Issue by mxp7064** [hackiftekhar/IQKeyboardManager#1507]
Is there maybe a way to implement next and previous button handlers?

Thank you in advance.

**Comment by muhasturk** [comment]
Please read wiki page.

https://github.com/hackiftekhar/IQKeyboardManager/wiki/Manual-Management#full-customise-control-over-previousnextdone-button-for-specific-uitextfielduitextview

**Comment by mxp7064** [comment]
Thank you!
