### ISSUE TITLE
Keyboard covers text field and sometimes it is too far from text field

### ISSUE THREAD

**Issue by mxp7064** [hackiftekhar/IQKeyboardManager#1508]
I have a GUI consisting of a scroll view and content view (IQPreviousNextView class). When I tap on the text fields to switch them everything is working as expected and the keyboard positions itself correctly right below the focused text field but when I am using the next and the previous buttons there are some issues: 
For example when I use the next button and go down through the text fields there is some extra space between the keyboard and the text field. Also in some situations if I try to use the previous button to go upwards, focused text field is covered by the keyboard. I have an example demo here:

https://github.com/mxp7064/DemoProject

Use next and previous buttons through text fields. One example would be: go from email to phone text field with the next button or go from guest comment text view to city text field with the previous button.

Versions
Xcode: 10.1
Mac OS: 10.14
Device: iphone 6 with ios 12.1
IQKeyboardManager version: 6.0.4

I looked at similar issues and there is some talk about how maybe this problem can be caused by the scroll view not calculating its content size correctly - I tried adding fixed height constraints and even tried to set the scroll view's content size programatically but those efforts didn't help.

Thank you in advance.

**Comment by zhenglibao** [comment]
I have same problem in my project. Did you fix it or has any suggestion? @mxp7064

**Comment by mxp7064** [comment]
@zhenglibao Sadly no

**Comment by hackiftekhar** [comment]
Thanks for the demo project. I'll take a look at it and will try to find the cause.

**Comment by mxp7064** [comment]
@hackiftekhar Thank you

**Comment by mxp7064** [comment]
@hackiftekhar Hi, Have you maybe managed to take a look at it?

**Comment by hackiftekhar** [comment]
Hi @mxp7064 I just checked your demo and I'm able to reproduce the issue. Let me debug this so I can give my findings on it.

**Comment by devandanger** [comment]
@hackiftekhar we are noticing this issue as well in our project. Is there anything you learned which could inform a fix for it?  We might have some bandwidth on our team to look into it.

**Comment by hackiftekhar** [comment]
Your issue looks similar to #1365 and #1541 Please have a look at that, I applied the fix.

**Comment by mxp7064** [comment]
@hackiftekhar Thank you! <3

**Comment by hackiftekhar** [comment]
No problem sir!
