### ISSUE TITLE
IQToolbar.previousBarButton  cannot nonnull

### ISSUE THREAD

**Issue by zhuweiDark** [hackiftekhar/IQKeyboardManager#1509]
**Describe the bug**
/**
 IQToolbar for IQKeyboardManager.
 */
@interface IQToolbar : UIToolbar <UIInputViewAudioFeedback>

/**
 Previous bar button of toolbar.
 */
@property(nonnull, nonatomic, strong) IQBarButtonItem *previousBarButton;

/**
 Next bar button of toolbar.
 */
@property(nonnull, nonatomic, strong) IQBarButtonItem *nextBarButton;

but the implement is:
-(void)dealloc
{
    self.items = nil;
    _previousBarButton = nil;
    _nextBarButton = nil;
    _titleBarButton = nil;
    _doneBarButton = nil;
    _fixedSpaceBarButton = nil;
}

-(IQBarButtonItem *)previousBarButton
{
    if (_previousBarButton == nil)
    {
        _previousBarButton = [[IQBarButtonItem alloc] initWithImage:nil style:UIBarButtonItemStylePlain target:nil action:nil];
        _previousBarButton.accessibilityLabel = @"Toolbar Previous Button";
    }
    
    return _previousBarButton;
}

/Users/zhuwei/AntGLocal/skywalker_citripio_ios/Carthage/Checkouts/IQKeyboardManager/IQKeyboardManager/IQToolbar/IQToolbar.m:92:24: warning: nil assigned to a pointer which is expected to have non-null value
    _previousBarButton = nil;
                       ^ ~~~
1 warning generated.

**To Reproduce**

**Expected behavior**
none warning

**Screenshots**
<img width="281" alt="2019-01-04 10 57 15" src="https://user-images.githubusercontent.com/1400179/50671870-87c68900-100f-11e9-8762-11094a3d0b17.png">

**Demo Project**
If applicable, add demo project.

### Versions
**Xcode:**  xcode 10.1
**Mac OS:** 10.13.6 (17G65)
**Simulator/Device:** xx.x
**Simulator/Device Name:** iPhone xx
**Library Version:** x.x.x

**Additional context**

**Comment by hackiftekhar** [comment]
These warnings has been fixed now.
