### ISSUE TITLE
toolbar.barStyle crash

### ISSUE THREAD

**Issue by mythodeia** [hackiftekhar/IQKeyboardManager#151]
Hello
on the following commit:
https://github.com/hackiftekhar/IQKeyboardManager/commit/81a57f356d3fe98055d267707269d146d66a14e7#diff-dd3d05f4b44e2fa3c6d4e9f1ba3c546cR1364
line 1364 the setting of the barStyle is crashing when the inputAccessoryView is not responding to setBarStyle selector. I added a comment there explaining that in my case i do not add a UIToolbar as an inputAccessoryView but a collectionview to show tags. So this crashes.
A possible solution is to check if the inputaccessoryview responds to selector before doing anything else.

thanks a lot

**Comment by hackiftekhar** [comment]
Thanks @mythodeia for your quick report. Thanks again!
