### ISSUE TITLE
IQToolBar displayed in the wrong position

### ISSUE THREAD

**Issue by webMing** [hackiftekhar/IQKeyboardManager#1510]
**Describe the bug**

when I begin  to input something in UITextfiled .  IQToolBar displayed in the wrong position  as follow 

![](
https://github.com/webMing/SFImages/blob/master/SFImages/IMG_2298.PNG?raw=true)

**Additional context**
In my project, there's another third-party library that plays videos,  When the device orientation  is landscape right , tap the home key go background and then  back to app , begin input something in textFiled it arises,  but if  app go background and back again, IQToolBar works well.

I've tried a lot, but it's not working. I hope to provide some ideas.

Thank you in advance.

**Comment by reececomo** [comment]
Same issue here. iOS 12, Swift 4.2.1, Xcode 10.1

**Comment by hackiftekhar** [comment]
There is a workaround for this issue.

According to other peoples, it happens when keyboard is present and then navigating to another page.

Please try to resign your keyboard before navigating to another controller.

For better solution, please try resigning on viewWillDisappear.
