### ISSUE TITLE
Toolbar Accessibility Labels Improperly Configured For VoiceOver

### ISSUE THREAD

**Issue by schayes04** [hackiftekhar/IQKeyboardManager#1512]
**Describe the bug**
The accessibility labels for the toolbar are not setup according to Apple's recommendations for accessibility. Currently the accessibility labels are set to "Toolbar Previous Button", "Toolbar Next Button", "Toolbar Title Button", "Toolbar Done Button". When voice over is used to read the buttons it also appends the accessibility trait for buttons. So when read aloud you hear something like "Toolbar Done Button Button"

**To Reproduce**
Turn on voiceover & navigate to a place where IQKeyboardManager is up & the toolbar is visible with buttons. Tap once on a button to hear "Toolbar Done Button Button"

**Expected behavior**
At a minimum it shouldn't say button twice. Apple's apps also don't seem to mention toolbars. So I'd recommend these labels become "Previous", "Next", "Title", and "Done" respectively.

### Versions
**Xcode:** 10.1
**Mac OS:** 10.14.3
**Simulator/Device:** Device (unfortunately voice-over is not supported on the simulator)
**Simulator/Device Name:** Any
**Library Version:** 6.2.0

**Comment by hackiftekhar** [comment]
Looks like a good recommendation. Will surely do.

**Comment by pawanmMrsool** [comment]
@schayes04 how did you enabled voice over for toolbar?
