### ISSUE TITLE
IQKeyboardReturnHandler.h file not found error

### ISSUE THREAD

**Issue by pavlem** [hackiftekhar/IQKeyboardManager#1513]
**Describe the bug**
There is an issue with library “IQKeyboardManager” (heavily coupled in BaseViewController and in our code base which I inherited). From the start it gave us compile time error problems and also with Jenkins shell build script where we fixed it using fast-lane approach. When trying to make a new test environment (new scheme and build configurations), the compile time error emerged again.

It fails to compile when test environment is selected with new test build configurations (setup as in other environments), while it works with old environments (development and production). Direct Run (build) from XCode can be made to work with deleting derived data and trying again, but Test Environment Archive from Xcode cannot. It is a presumption that it is something deep inside “IQKeyboardManager” library and how it is managed via cocoa pods since derived data error is seen which, when this derived data folder is cleaned, solves the problem for direct XCODE build but not for Archiving. Other libraries are not giving any problems.

**To Reproduce**
1. Create new scheme
2. Create new build configurations
3. Switch to new scheme and set new build confurations for Run and Archive from Edit scheme option
4. The compile time error emerges 
5. Switch back to old scheme, or change to old build configurations in new scheme and error disappears.

Note!!!
All other libraries work fine

**Expected behavior**
Just not to give compile time errors when switching schemes and build configurations

**Screenshots**
<img width="261" alt="screen shot 2019-01-29 at 10 23 26 am" src="https://user-images.githubusercontent.com/14887690/51897996-42983b80-23b0-11e9-81a9-6a25dbba67c9.png">
<img width="845" alt="screen shot 2019-01-29 at 10 23 13 am" src="https://user-images.githubusercontent.com/14887690/51897997-42983b80-23b0-11e9-94f7-42a9b51b5bc3.png">

### Versions
**Xcode:** 10.1
**Mac OS:** 10.14.2 - Mojave
**Simulator/Device:** Simulator and Device
**Simulator/Device Name:** iPhone 8
**Library Version:** latest

**Comment by hackiftekhar** [comment]
hmm, looks like you are the only one who is getting this issue. I checked and this file is in the list of public header in my podspec file. Please check the Pods project and IQKeyboardManager target files list for more information.
