### ISSUE TITLE
Overlap Suggestion text on keyboards key 

### ISSUE THREAD

**Issue by subhashsanghani** [hackiftekhar/IQKeyboardManager#1516]
I am trying to enter some text but with iPhone 7 there is some issue when i try to type something auto suggestion text will overlap on key please check bellow image url of screenshot so you will get better idea. 

[https://imgur.com/a/dtCpVJz](https://imgur.com/a/dtCpVJz)

Please suggest me solution. 

I am using 
pod 'IQKeyboardManager', '~> 6.0.6'

Following are settings
    [[IQKeyboardManager sharedManager] setToolbarManageBehaviour:IQAutoToolbarByPosition];
    [[IQKeyboardManager sharedManager] setEnable:true];
    [[IQKeyboardManager sharedManager] setEnableAutoToolbar:true];

**Comment by hackiftekhar** [comment]
Hmm, I'm not sure if this is related to library since the the autosuggestion toolbar is part of apple private API and IQKeyboardManager doesn't access any private API or manipulate any private UI.
