### ISSUE TITLE
In UIAlertController UI doesn't go back to the original position after closing the keyboard

### ISSUE THREAD

**Issue by piotrros** [hackiftekhar/IQKeyboardManager#1517]
**Describe the bug**
After using keyboard with UITextField in UIAlertController UI doesn't revert to its old position, so it stays on the top of the screen.

**To Reproduce**
1. Create an UIAlertController with custom view using library: https://github.com/sberrevoets/SDCAlertView
2. Add UITextField inside.
3. When you tap the UITextField everything looks fine. It moves the UI to the top so you can enter the text.
4. When you click Done keyboard dismisses, but the UI doesn't go back from the top.

**Expected behavior**
UI should go back from the top to the original position.

**Screenshots**
https://imgur.com/a/Mg51JC3
This is how it looks after keyboard dismissal.

### Versions
**Xcode:** 10.1
**Simulator/Device Name:** iPod Touch 6th gen with iOS 12.1.3
**Library Version:** 6.2.0

**Comment by hackiftekhar** [comment]
Unfortunately this cannot be fixed, since it's developer responsiblity to enable/disable IQKeyboardManager when presenting any third party library. For more information on this, please check the README.md file.

**Comment by piotrros** [comment]
Thanks for the response. In the end, there was a fix on SDCAlertView side so it's working for me now.

**Comment by hackiftekhar** [comment]
Great! Thanks for letting me know :)
