### ISSUE TITLE
Next and Previous arrow not showing

### ISSUE THREAD

**Issue by mohsinalimat** [hackiftekhar/IQKeyboardManager#1519]
Hello,

I implement like below and next previous arrow not showing.
what was the issue?

In AppDelegate.swift

        IQKeyboardManager.shared.enable = true
        IQKeyboardManager.shared.shouldResignOnTouchOutside = true
        IQKeyboardManager.shared.keyboardDistanceFromTextField = 100.0

![simulator screen shot - iphone xr - 2019-02-05 at 18 05 35](https://user-images.githubusercontent.com/973676/52273755-cd5cd580-2970-11e9-9814-6fe754f6bc9e.png)

**Comment by krgauthi** [comment]
What classes do you have added to `toolbarPreviousNextAllowedClasses`? I'm also running into the same issue but I believe its because there's multiple `ORStackView`'s on the page.

**Comment by mohsinalimat** [comment]
this layout I have

![screenshot 2019-02-12 at 10 59 04 am](https://user-images.githubusercontent.com/973676/52613757-3edadd80-2eb5-11e9-8692-74337ef30814.png)

**Comment by hackiftekhar** [comment]
Please check the demoo app about how you can use `IQPreviousNextView` to overcome this situation.

**Comment by mohsinalimat** [comment]
Done thanks :)
