### ISSUE TITLE
IQKehyboardManager ObjC version has memory leaks

### ISSUE THREAD

**Issue by pmurphyjam** [hackiftekhar/IQKeyboardManager#1520]
Run the Xcode memory tool and this library will leak lots of memory.

**To Reproduce**
In your Xcode project scheme, check 'Main Thread Checker', 'Malloc Scribble', 'Malloc Stack'
Now run the application. Click on the Memory tool in the project group folder.
Click on the 3 circles icon at the bottom, App stops, and loads allocations, click on box ! icon, now just shows leaks, and you'll see your framework is leaking lots of memory.
 

**Expected behavior**
Tool should never leak memory.
This causes the App to crash over prolonged usage.

**Screenshots**

**Demo Project**
If applicable, add demo project.

### Versions
Xcode 9 or 10, latest ios11 or ios12
**Xcode:** x.x
**Mac OS:** xx.xx.x
**Simulator/Device:** xx.x
**Simulator/Device Name:** iPhone xx
**Library Version:** x.x.x

**Additional context**

**Comment by mobicity** [comment]
It is highly likely that this is causing bugs in my application.
Here is the crashlytics screenshot for it:

<img width="1110" alt="Screen Shot 2019-04-24 at 10 16 39" src="https://user-images.githubusercontent.com/43755722/56662317-13752b80-667a-11e9-80af-dddbee8d0161.png">

**Comment by mobicity** [comment]
@hackiftekhar can you help us with this?

**Comment by hackiftekhar** [comment]
@pmurphyjam I'll surely take a look with memory leak tool.

**Comment by hackiftekhar** [comment]
@mobicity From the crash logs, it looks like the issue with IQDropDownTextField which is maintained in a different github project here https://github.com/hackiftekhar/IQDropDownTextField please open this issue in that project

**Comment by mobicity** [comment]
@hackiftekhar https://github.com/hackiftekhar/IQDropDownTextField/issues/93 done!

**Comment by hackiftekhar** [comment]
Thank you!
