### ISSUE TITLE
Previous/Next can't work correctly when two textfield was't next to each other

### ISSUE THREAD

**Issue by maomaoshou** [hackiftekhar/IQKeyboardManager#1522]
**Describe the bug**
I have two textfields that have a different superview and their superview are subviews of IQPreviousNextView,when the two textfields's superview are next to each other,Next/Previous button work good.But when their superview are't next to each other,it can't work good.

**Expected behavior**
NEXT/Previous button can't work correctly

**Screenshots**

![error](https://user-images.githubusercontent.com/11499465/52924952-ecdd0080-3369-11e9-999c-525981c31072.gif)

### Versions
**Xcode:** 10.1
**Mac OS:** 10.14
**Simulator/Device:** iOS 12.1
**Simulator/Device Name:** iPhone X

**Comment by lisafly2014** [comment]
Have you solved your problem? I met the same problem in my project.

**Comment by maomaoshou** [comment]
> Have you solved your problem? I met the same problem in my project.

No,I found nothing about this

**Comment by hackiftekhar** [comment]
Please see how to use IQPreviousNextView to solve this issue when two textfields are not on same superview.

**Comment by lisafly2014** [comment]
The two textfields are in the same superview, but between these two textfields there are other parts, which are not textfield, such as a label with a segment controller.

**Comment by maomaoshou** [comment]
> Please see how to use IQPreviousNextView to solve this issue when two textfields are not on same superview.

👌，Thank you for your reply, I would see about IQPreviousNextView.

**Comment by maomaoshou** [comment]
> Please see how to use IQPreviousNextView to solve this issue when two textfields are not on same superview.

I am sorry, do you mean:
<img width="754" alt="Screen Shot 2019-04-28 at 2 51 51 PM" src="https://user-images.githubusercontent.com/11499465/56860111-58c09280-69c5-11e9-9dd8-ccf622cc6309.png">
I have done according this role,I used IQPreviousNextView as all subview's superview

**Comment by lisafly2014** [comment]
Hi,

Now it's not Next/Previous button display problem, it is a new problem.
if  there are other UI between  these two textfields, and click the
Next/Previous button,  the scrollView could not scroll to the correct
position.

Please refer to my test project and related video

https://github.com/lisafly2014/IQKeyboradManagerProblem

Please help have a look. Thanks


















    Best Wishes

    Lisa Liu

**Comment by maomaoshou** [comment]
> Hi, Now it's not Next/Previous button display problem, it is a new problem. if there are other UI between these two textfields, and click the Next/Previous button, the scrollView could not scroll to the correct position. Please refer to my test project and related video https://github.com/lisafly2014/IQKeyboradManagerProblem Please help have a look. Thanks Best Wishes Lisa Liu
> […](#)

Hi,I have looked your demo,I am sorry to help nothing,but I found there is an issue say about this,It's a question,so may be you should't use UIStackView at present,I am sorry for help nothing.
<img width="1009" alt="Screen Shot 2019-04-28 at 4 48 33 PM" src="https://user-images.githubusercontent.com/11499465/56861666-7ac21100-69d5-11e9-9c92-ebffefbed7e1.png">







Best Wishes
Ericach

**Comment by hackiftekhar** [comment]
> The two textfields are in the same superview, but between these two textfields there are other parts, which are not textfield, such as a label with a segment controller.

If that's the case then it should work out of the box.

**Comment by hackiftekhar** [comment]
@maomaoshou can you please check if your issue is related to #1365 and #1541? Please let me know.

**Comment by maomaoshou** [comment]
> @maomaoshou can you please check if your issue is related to #1365 and #1541? Please let me know.

thank you for your reply and update,I updated my podfile and the bug is gone,thank you very much,I will close this issue.
