### ISSUE TITLE
textfield inside uiview(windows subviews) wont trigger the distance or the scrollable behavior

### ISSUE THREAD

**Issue by Sanadbarjawi** [hackiftekhar/IQKeyboardManager#1523]
**Describe the bug**
i have a view which i add to the keywindow as a subview
this view includes a textfield and a two buttons below it,
when i tap on the text field the keyboard hides the buttons and no scrolling is there.

i do have these three lines in AppDelegate :
    
```
     IQKeyboardManager.shared.enable = true
     IQKeyboardManager.shared.enableAutoToolbar = false
     IQKeyboardManager.shared.shouldResignOnTouchOutside = true
     IQKeyboardManager.shared.keyboardDistanceFromTextField = 30
```

**Screenshot**
![img_ffa68c78cf49-1](https://user-images.githubusercontent.com/31387946/53300755-e8c24e80-3853-11e9-9620-5ba58884b63d.jpg)

### Versions
**Xcode:** 10
**Device:** iPhone SE

**Comment by Coder-ZJ** [comment]
@Sanadbarjawi  I have the same problem。How did you solve it？

**Comment by hackiftekhar** [comment]
This library don't support textFields that are directly added to a UIWindow, it must come throught UIViewController or one of it's subclass.
