### ISSUE TITLE
The app is crashed when I edited with UITextView in a VC, then popup VC. 

### ISSUE THREAD

**Issue by LabanL** [hackiftekhar/IQKeyboardManager#1524]
**Describe the bug**
When iOS version less than or equal to 10, the app is crashed when I edited with UITextView in a VC, then popup VC.

**To Reproduce**
1. Go to a ViewController with UITextView
2. Click on UITextView, and popup keyboard, then close keyboard
3. Pop ViewController

**Expected behavior**
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'An instance 0x106a97c00 of class UITextView was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x17062f9e0> (
<NSKeyValueObservance 0x17465f1d0: Observer: 0x106a97c00, Key path: attributedText, Options: <New: YES, Old: NO, Prior: NO> Context: 0x0, Property: 0x17465f200>
<NSKeyValueObservance 0x17465f380: Observer: 0x106a97c00, Key path: bounds, Options: <New: YES, Old: NO, Prior: NO> Context: 0x0, Property: 0x17465f3b0>
<NSKeyValueObservance 0x17465f3e0: Observer: 0x106a97c00, Key path: font, Options: <New: YES, Old: NO, Prior: NO> Context: 0x0, Property: 0x17465f440>
<NSKeyValueObservance 0x17465f2f0: Observer: 0x106a97c00, Key path: frame, Options: <New: YES, Old: NO, Prior: NO> Context: 0x0, Property: 0x17465f500>
<NSKeyValueObservance 0x170844fe0: Observer: 0x106a97c00, Key path: text, Options: <New: YES, Old: NO, Prior: NO> Context: 0x0, Property: 0x170845970>
<NSKeyValueObservance 0x170845a00: Observer: 0x106a97c00, Key path: textAlignment, Options: <New: YES, Old: NO, Prior: NO> Context: 0x0, Property: 0x170845a30>
<NSKeyValueObservance 0x170845b50: Observer: 0x106a97c00, Key path: textContainerInset, Options: <New: YES, Old: NO, Prior: NO> Context: 0x0, Property: 0x170845b80>
)'

### Versions
**Xcode:** 10.1
**Mac OS:**10.14.3
**Simulator/Device:** iPhone6(iOS9), iPhone5s(iOS10.3)
**Library Version:** 6.2.0

**Additional context**
When the system version is greater than or equal to iOS11, it works right.

**Comment by hackiftekhar** [comment]
By looking at the logs, it looks like you probably added observers using addObserver method. It looks like an issue with your project, but not with the library.
