### ISSUE TITLE
Hide keyboard when i am going to login button hit

### ISSUE THREAD

**Issue by rajkumar0143** [hackiftekhar/IQKeyboardManager#1529]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Demo Project**
If applicable, add demo project.

### Versions
**Xcode:** x.x
**Mac OS:** xx.xx.x
**Simulator/Device:** xx.x
**Simulator/Device Name:** iPhone xx
**Library Version:** x.x.x

**Additional context**

**Comment by hackiftekhar** [comment]
Use resignFirstResponder on login action.
