### ISSUE TITLE
Toolbar shows on simulator after app loads

### ISSUE THREAD

**Issue by adamdziedzic** [hackiftekhar/IQKeyboardManager#153]
Hi, after loading app I see tollbar, when there is no field active. "Done" button dismisses it, but I wonder how to fix it or how can I call "Done" programmatically?

**Comment by hackiftekhar** [comment]
You can't call done programmatically, instead you should use
'resignFirstResponder' on textField to dismiss keyboard.

On Tuesday, January 27, 2015, adamdziedzic <notifications@github.com> wrote:

> Hi, after loading app I see tollbar, when there is no field active. "Done"
> button dismisses it, but I wonder how to fix it or how can I call "Done"
> programmatically?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackiftekhar/IQKeyboardManager/issues/153>.
>


-- 
Sent from My iPhone

**Comment by adamdziedzic** [comment]
But there is no keyboard and none of my textFields are first responders.

**Comment by hackiftekhar** [comment]
Could you please share demo project?

**Comment by hackiftekhar** [comment]
Any updates or demo code for this?

**Comment by hackiftekhar** [comment]
Can you share demo project where it seems 'done' button is appearing and there is no first responder?

**Comment by adamdziedzic** [comment]
Sorry, if I find time I'll do it. You can close the issue for now, if I reproduce it I'll ask for re-opening it, ok?
