### ISSUE TITLE
The Down Arrow \/ is Shown pointing to the Right >

### ISSUE THREAD

**Issue by rohantk** [hackiftekhar/IQKeyboardManager#1530]
The Down Arrow \/ in the keyboard's ToolBar is shown pointing to the Right >. 

**Screenshots**
![WhatsApp Image 2019-03-19 at 13 50 51](https://user-images.githubusercontent.com/5189706/54596868-f469f500-4a4e-11e9-91f4-48ad0fbdc69e.jpeg)

**Comment by hackiftekhar** [comment]
Which version of libeary you are using? Can you please try with latest?
