### ISSUE TITLE
works with simulator but in device there is crash

### ISSUE THREAD

**Issue by kaushalpar** [hackiftekhar/IQKeyboardManager#1531]
When i click on UITextField then app get crash with the message.

2019-03-20 14:02:33.698081+0530 CarDealerApp[26518:4382250] -[UIWindow actualSceneBounds]: unrecognized selector sent to instance 0x113e0f3d0
2019-03-20 14:02:33.698565+0530 CarDealerApp[26518:4382250] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIWindow actualSceneBounds]: unrecognized selector sent to instance 0x113e0f3d0'
*** First throw call stack:
(0x1869f3ea0 0x185bc5a40 0x18690cd04 0x1b3a9eb38 0x1869f97b8 0x1869fb45c 0x1b386f878 0x1b3871c54 0x1b387cf60 0x1b387db04 0x1b3f08f40 0x1b387d86c 0x1b3875448 0x1b38f57c0 0x1b38ee9fc 0x1b3aa236c 0x1b3a9dfec 0x1b3f009c8 0x1b3d5cf90 0x1b3d1fe90 0x1b3d0e040 0x1b3687a38 0x1b3690054 0x1b368d8d8 0x1b368cdc0 0x1b36800c8 0x1b367fc34 0x1b367fa04 0x1b3aad3d4 0x1b3a8c6ec 0x1b3b5857c 0x1b3b5af74 0x1b3b53a64 0x1869841cc 0x18698414c 0x186983a30 0x18697e8fc 0x18697e1cc 0x188bf5584 0x1b3a71054 0x1044a0e54 0x18643ebb4)
libc++abi.dylib: terminating with uncaught exception of type NSException

Testing Device : iPhone 6 Plus , SE
OS : iOS 12.1

while using Simulator it is working.

**Comment by kaushalpar** [comment]
> When i click on UITextField then app get crash with the message.
> 
> 2019-03-20 14:02:33.698081+0530 CarDealerApp[26518:4382250] -[UIWindow actualSceneBounds]: unrecognized selector sent to instance 0x113e0f3d0
> 2019-03-20 14:02:33.698565+0530 CarDealerApp[26518:4382250] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIWindow actualSceneBounds]: unrecognized selector sent to instance 0x113e0f3d0'
> *** First throw call stack:
> (0x1869f3ea0 0x185bc5a40 0x18690cd04 0x1b3a9eb38 0x1869f97b8 0x1869fb45c 0x1b386f878 0x1b3871c54 0x1b387cf60 0x1b387db04 0x1b3f08f40 0x1b387d86c 0x1b3875448 0x1b38f57c0 0x1b38ee9fc 0x1b3aa236c 0x1b3a9dfec 0x1b3f009c8 0x1b3d5cf90 0x1b3d1fe90 0x1b3d0e040 0x1b3687a38 0x1b3690054 0x1b368d8d8 0x1b368cdc0 0x1b36800c8 0x1b367fc34 0x1b367fa04 0x1b3aad3d4 0x1b3a8c6ec 0x1b3b5857c 0x1b3b5af74 0x1b3b53a64 0x1869841cc 0x18698414c 0x186983a30 0x18697e8fc 0x18697e1cc 0x188bf5584 0x1b3a71054 0x1044a0e54 0x18643ebb4)
> libc++abi.dylib: terminating with uncaught exception of type NSException
> 
> Testing Device : iPhone 6 Plus , SE
> OS : iOS 12.1
> 
> while using Simulator it is working.

**Comment by hackiftekhar** [comment]
You might be using actualSceneBounds at your project code because library isn't using this API. Please verify with your project.
