### ISSUE TITLE
Xcode 10.2 Warnings

### ISSUE THREAD

**Issue by vahids** [hackiftekhar/IQKeyboardManager#1532]
**Describe the bug**
Pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified)
on 9 files

**To Reproduce**
1. Update to Xcode 10.2
2. Build
3. Open issue navigator
4. See warnings

**Expected behavior**
See no warnings

**Screenshots**
![image](https://user-images.githubusercontent.com/1405424/54977665-abb8bb80-4fbb-11e9-95c8-275633ca535f.png)

### Versions
**Xcode:** 10.2
**Mac OS:** 10.14.3
**Library Version:** 6.2.0

**Comment by WallaceYYLi** [comment]
yes, I have the same problem.

**Comment by hackiftekhar** [comment]
Hmm, okay. I'll download the latest Xcode and will surely fix these warnings. Thanks for the report.

**Comment by hackiftekhar** [comment]
I'm not getting this error with latest Xcode 10.2. Can you please tell which library version you guys are using?

**Comment by vahids** [comment]
> I'm not getting this error with latest Xcode 10.2. Can you please tell which library version you guys are using?

Library Version: 6.2.0

**Comment by hackiftekhar** [comment]
I don't think so since all of them having nullability constants. However I added some more with 6.2.1 today and published the code with Xcode 10.2 and Swift 5.0 optimization.

Can you please see exactly where nullability pointers are missing? Can you please send me that screenshot?
