### ISSUE TITLE
IQKeyboardManager leads to a memory leaks

### ISSUE THREAD

**Issue by ankitsainisoftobiz** [hackiftekhar/IQKeyboardManager#1533]
**Describe the bug**
There is memory leak on IOS 12.1 in iPhone XS Max. Leak is on line number #389 in line let result = super.becomeFirstResponder().

**Screenshots**
Here is the screenshot from instrument:
https://docs.google.com/document/d/10hXEHBQ7aChy_P_WcemPMfWgadFn-JCqgWhY3YXFrsY/edit?usp=sharing

### Versions
**Xcode:** 10.1
**Mac OS:** 10.13.6
**Simulator/Device:**12.1
**Simulator/Device Name:** iPhone XS Max
**Library Version:** 6.0.4

**Comment by hackiftekhar** [comment]
I'll be checking and working on the memory leaks issues soon.

**Comment by ajRiverav** [comment]
@hackiftekhar off the top of your head, is the mem leak still present in v6.5.1?
I assume it is since this issue is open.

**Comment by hackiftekhar** [comment]
I was trying to look into this issue, but the line you mention looks to be from `SkyFloatingLabelTextField` library.
