### ISSUE TITLE
Swift 5 release

### ISSUE THREAD

**Issue by osianSmith** [hackiftekhar/IQKeyboardManager#1534]
Hey, 
Is a release of swift 5 expected soon due to ABI stability?

**Comment by hackiftekhar** [comment]
Yes, I'll download the latest Xcode tomorrow and will try to compile it to see how our library behaves with latest Xcode and Swift version.

**Comment by osianSmith** [comment]
Cheers for a quick reply 👍

**Comment by hackiftekhar** [comment]
@osianSmith 6.2.1 has been published with Swift 5.0 fixes!
