### ISSUE TITLE
Swift 5.0

### ISSUE THREAD

**Issue by YashJadhav** [hackiftekhar/IQKeyboardManager#1538]
@hackiftekhar Please update IQKeyboardManagerSwift to latest version of Swift 5.0

**Comment by hackiftekhar** [comment]
Already did. 6.2.1. Please check.

**Comment by metisdev** [comment]
Please update the change logs as well :)

**Comment by pmusolino** [comment]
I agree with @metisdev. I suggest to remove the changelog file and continue to use the release functionality of Github.
