### ISSUE TITLE
在禁止IQKeyBoardManager的tableview页面中 某一个textfield在弹出键盘后，滑动页面textfield会关闭键盘然后又重新弹出键盘。希望把重新弹出键盘这个问题给解决。

### ISSUE THREAD

**Issue by zcc2o** [hackiftekhar/IQKeyboardManager#1542]
在禁止IQKeyBoardManager的tableview页面中  有一个textfield
点击textfield弹出键盘后 -> 滑动页面textfield会关闭键盘然后**又重新弹出键盘**。
重新弹出键盘这个操作显然是有问题的。而且找不到方法去禁止键盘的第二次弹出。

**Comment by hackiftekhar** [comment]
Please use english for github issues. Also the sliding from left to right and vice versa is not been supported.
