### ISSUE TITLE
Documentation Fix

### ISSUE THREAD

**Issue by alexandresoli** [hackiftekhar/IQKeyboardManager#1543]
**Describe the bug**
The documentation in the wiki tells to import import IQKeyboardManagerSwift

The correct module to import is IQKeyboardManager

**To Reproduce**
1. Go to Wiki
2. Check installation session.

**Expected behavior**
No modul found.

**Screenshots**

**Demo Project**
If applicable, add demo project.

### Versions
**Xcode:** x.x
**Mac OS:** xx.xx.x
**Simulator/Device:** xx.x
**Simulator/Device Name:** iPhone xx
**Library Version:** x.x.x

**Additional context**

**Comment by hackiftekhar** [comment]
For swift version it's IQKeyboardManagerSwift and for ObjC version it's IQKeyboardManager.
