### ISSUE TITLE
IQKeyboard prevent button click when open

### ISSUE THREAD

**Issue by salmankaludi** [hackiftekhar/IQKeyboardManager#1544]
I have implemented cust chat in my  xamarin project.

I have implement the IQKeyboard manager.

The issue when i  click on send button while keyboard is open then keyboard gets hide and again i have to press the send button.

What i can do that i have to press send button one time  @hackiftekhar 

Thanks

**Comment by hackiftekhar** [comment]
You probably enabled the shouldResignOnTouchOutside. This issue has been fixed long time ago. Can you please let me know more thoughts on this?
