### ISSUE TITLE
IQKeyboard Manger EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by chbe89** [hackiftekhar/IQKeyboardManager#1545]
**Describe the bug**

I am getting a the following error when entering a textField `Thread 1: EXC_BAD_ACCESS (code=1, address=0x7fff127e3f54)` 
The error occurs in IQBarButtonItemConfiguration line 447. 
It worked fine with version 6.2.0. I updated to 6.2.1 because of the swift 5 update. Could you please have a look? I had no time to have a detailed look at it. If I can find a fix, I will create a pull request. 

### Versions
**Xcode:** 10.2
**Mac OS:** 10.14.4
**Simulator/Device Name:** iPhone X
**Library Version:** 6.2.1

**Comment by hackiftekhar** [comment]
which line you are talking about. Because there is no file where on line 447 we are using the IQBarButtonItemConfiguration. Please elaborate.

**Comment by chbe89** [comment]
@hackiftekhar It is crashing in File `IQUIView+IQKeyboardToolbar.swift` when setting `done.invocation = toolbar.doneBarButton.invocation` Any idea why this happens?

**Comment by hackiftekhar** [comment]
Not sure why, but would be great if you share a demo project @chbe89

**Comment by BasantAshraf** [comment]
@chbe89 Iam facing same issue, any updates for a solution ?

**Comment by masashi-hasegawa** [comment]
<img width="815" alt="スクリーンショット 2019-05-06 16 29 31" src="https://user-images.githubusercontent.com/25424150/57211747-5b059b00-701c-11e9-986f-d98c2b294852.png">

**Comment by masashi-hasegawa** [comment]
<img width="811" alt="スクリーンショット 2019-05-06 16 35 06" src="https://user-images.githubusercontent.com/25424150/57211913-ef6ffd80-701c-11e9-92a4-1fecf0793cea.png">

**Comment by masashi-hasegawa** [comment]
I do not know why this problem will occur

**Comment by chbe89** [comment]
I didn't find the time to provide a demo Project. Hopefully I can provide one today.

**Comment by chbe89** [comment]
@hackiftekhar Please find the attached Zip. With version 6.3.0 the crash occurs when setting the previousBarButton. Could you please have a look at it? 
[IQKeyboardManagerTest.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/3147774/IQKeyboardManagerTest.zip)

**Comment by hackiftekhar** [comment]
Sure, Give me a try

**Comment by hackiftekhar** [comment]
I found that you have added IQKeyboardManager.framework and IQKeyboardManagerSwift.framework as well. Please only use one and remove other. This will fix your problem.
