### ISSUE TITLE
IQKeyboardManager UICompatibilityInputViewController被释放

### ISSUE THREAD

**Issue by ZClee128** [hackiftekhar/IQKeyboardManager#1546]
Cannot form weak reference to instance (0x1056efdc0) of class UICompatibilityInputViewController. It is possible that this object was over-released, or is in the process of deallocation.

**Comment by hackiftekhar** [comment]
Sorry, but I cannot answer this question because the library doesn't deal with the internal Apple API and UICompatibilityInputViewController looks to be private.

**Comment by ZuhanLin** [comment]
I have the same problem, my testing environment list below：
1、i had installed thirdparty Sogou input method downloaded in App Store
2、i had full pop gesture in the viewcontroller of having textfield
![企业微信截图_90b2fb33-6480-4d93-b9f6-3b2f3b47f37d](https://user-images.githubusercontent.com/5183529/59658934-9bd5ff80-91d7-11e9-9b28-1aa61a935d37.png)

**Comment by ZClee128** [comment]
Yes, that's the problem.

**Comment by BaronWj** [comment]
solve:
  - (void)addKeyboardToolbarWithTarget:(id)target titleText:(NSString*)titleText rightBarButtonConfiguration:(IQBarButtonItemConfiguration*)rightBarButtonConfiguration previousBarButtonConfiguration:(IQBarButtonItemConfiguration*)previousBarButtonConfiguration nextBarButtonConfiguration:(IQBarButtonItemConfiguration*)nextBarButtonConfiguration{
      ...
   To change  “IQToolbar *toolbar = self.keyboardToolbar;”
   for  “ IQToolbar *toolbar = [[IQToolbar alloc]init] ;”
}
