### ISSUE TITLE
Failed to archive using C "language dialect" = C99

### ISSUE THREAD

**Issue by soulsoul666** [hackiftekhar/IQKeyboardManager#1548]
IQKeyBoardManager failed to compile when using C99 Language Dialect in archive.

![image](https://user-images.githubusercontent.com/4212444/57324725-d2036800-70de-11e9-9057-07e5b4861267.png)

Switching to GNU99 fix the problem
![image](https://user-images.githubusercontent.com/4212444/57324962-640b7080-70df-11e9-9121-6a94ac1e7dbb.png)

From https://stackoverflow.com/questions/16999749/expected-at-the-end-of-declaration-list
"C99 does not have a declaration for typeof(), and will assume it returns int. "

**Comment by soulsoul666** [comment]
Replacing all "typeof" to "__typeof__" fix the problem 

PS: __typeof__ is part of all compiler dialects

**Comment by hackiftekhar** [comment]
Thanks @soulsoul666, I'll verified it once and if all is ok, I'll do this change. Thanks again!
