### ISSUE TITLE
Issues with UITextView and is

### ISSUE THREAD

**Issue by trungnguyen1791** [hackiftekhar/IQKeyboardManager#155]
Currently i have a problem with UITextView. Here are the step by step to get this bug

1. Firstly, i have a uitextview on screen, isEditable = No
2. I change isEditable's property to YES then try to touch on the textview, and keyboard show.
3. I touch out to hide keyboard and try to set isEditable to NO.
4. Now if i double tap on textview, the issue appear. The toolbar will show at the bottom of screen ( only toolbar without keyboard). In the right way, it must not be show here. 

Do u have any idea about this issue ?

**Comment by devindresh** [comment]
May be a known issue with iOS Simulator. Could you please look at README.md for known issue section and confirm it is not an iOS Simulator issue.

**Comment by hackiftekhar** [comment]
May be a known issue with iOS Simulator. Could you please look at README.md for known issue section and confirm it is not an iOS Simulator issue.

**Comment by trungnguyen1791** [comment]
No, I'm test on my real device not simulator. 
In this situation, keyboard height return is 44 height only.

**Comment by hackiftekhar** [comment]
Ok, could you please share demo project?

On Friday, January 30, 2015, trungnguyen1791 <notifications@github.com>
wrote:

> No, I'm test on my real device not simulator.
> In this situation, keyboard height return is 44 height only.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackiftekhar/IQKeyboardManager/issues/155#issuecomment-72208633>
> .
>


-- 
Sent from My iPhone

**Comment by trungnguyen1791** [comment]
Ok, here is a simple demo: https://github.com/trungnguyen1791/DemoKeyboard

Firstly, u tap on textview with isEditable = True. The Keyboardhandler working properly.

Secondly, u change isEditable to False with Toggle button. Now double tap on textview. The Keyboardhandler will show only toolbar view

**Comment by hackiftekhar** [comment]
Currently I'm very busy in other works, I will look into the demo in a day or two.

**Comment by hackiftekhar** [comment]
It seems to be an Apple bug/feature. Try removing `IQKeyboardManager` and add these lines in `- (void)viewDidLoad`

````
    UIToolbar *toolbar = [[UIToolbar alloc] init];
    UIBarButtonItem *nilItem = [[UIBarButtonItem alloc] initWithBarButtonSystemItem:UIBarButtonSystemItemFlexibleSpace target:nil action:nil];
    UIBarButtonItem *doneItem = [[UIBarButtonItem alloc] initWithBarButtonSystemItem:UIBarButtonSystemItemDone target:nil action:nil];
    [toolbar setItems:@[nilItem,doneItem]];
    [toolbar sizeToFit];
    self.textView.inputAccessoryView = toolbar;
````

Issue is still there. May be Apple think something different or a known issue for Apple.
Closing issue as this doesn't belong to library and belongs to an Apple bug/feature.
