### ISSUE TITLE
i make chat when start typing view scroll down and hied behind the keyboard 

### ISSUE THREAD

**Issue by abdoqatry** [hackiftekhar/IQKeyboardManager#1552]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Demo Project**
If applicable, add demo project.

### Versions
**Xcode:** x.x
**Mac OS:** xx.xx.x
**Simulator/Device:** xx.x
**Simulator/Device Name:** iPhone xx
**Library Version:** x.x.x

**Additional context**

**Comment by hackiftekhar** [comment]
Please describe the bug.
