### ISSUE TITLE
topLayoutGuide gets messed up

### ISSUE THREAD

**Issue by aaeegg** [hackiftekhar/IQKeyboardManager#1554]
**Describe the bug**
After a certain sequence of operations involving the keyboard, changing to a different view results in topLayoutGuide being set to an incorrect value such as 0 or 151. This causes interface elements which have been aligned to the top layout guide to appear in the wrong place.

The app in question has a container view as the root view controller. The container view has a navigation controller as a subview. The navigation controller switches between several views, one of which has a text field. In the actual app, the container view has multiple subviews, but the demo project has been simplified.

The demo project uses code in viewDidLayoutSubviews to position subviews according to topLayoutGuide. However, the same problem also occurs if using autolayout constraints to position subviews according to the safe area.

**To Reproduce**
Normal behavior, bug not triggered:
1. Start the app.
2. Note that the blue rectangle extends slightly below the bottom of the status bar area, and the red rectangle is completely outside the status bar area.
3. Tap the "Form" button.
4. Tap the "BACK" button.
5. Note that the blue and red rectangles are still in the right place.

Bug 1:
This occurs on all devices.
1. Start the app.
2. Tap the "Form" button.
3. Tap inside the text field to open the keyboard.
4. After the keyboard appears, tap the home button.
5. From the home screen, immediately re-open the app.
6. Tap the "Done" button in the keyboard toolbar to close the keyboard.
7. Tap the "BACK" button.
8. If the bug has triggered, the blue rectangle will now only fill a small part of the status bar area, and the top of the red rectangle will be inside the status bar area. (Or, on some devices, the blue rectangle will extend down to the middle of the screen instead of just slightly below the status bar area.)
9. If the bug did not trigger on the first attempt, repeat steps 2 through 7 one more time.

Bug 2:
With the demo project, this only occurs on some device models. It may be related to the text field position relative to the screen size.
1. Start the app.
2. Tap the "Form" button.
3. Tap inside the text field to open the keyboard.
4. After the keyboard appears, tap the "Done" button in the keyboard toolbar to close the keyboard.
5. Tap inside the text field to open the keyboard again.
6. After the keyboard appears, tap the "Done" button in the keyboard toolbar to close the keyboard.
7. Tap the "BACK" button.
8. If the bug has triggered, the blue rectangle will now only fill a small part of the status bar area, and the top of the red rectangle will be inside the status bar area. (Or, on some devices, the blue rectangle will extend down to the middle of the screen instead of just slightly below the status bar area.)
9. If the bug did not trigger on the first attempt, repeat steps 2 through 7 one more time.

**Expected behavior**
Once the keyboard has been closed, the top layout guide throughout the app should be the same as it was before the keyboard was opened.

**Demo Project**
[kt3.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/3189789/kt3.zip)

### Versions
**Xcode:** 10.1
**Mac OS:** 10.13.6
**Simulator/Device:** 9.3.5, 12.2
**Simulator/Device Name:** iPhone 4S, iPhone 5, iPhone 6, iPhone 6S Plus, iPhone XS Max
**Library Version:** 6.2.1

**Comment by hackiftekhar** [comment]
@aaeegg, I understand what your situation is and I'm also able to reproduce this bug very easily.

But unfortunately this is a bug from Apple that safe area isn't properly managed for childViewController cases. I modified your demo project without using IQKeyboardManager and able to reproduce the issue with same steps. I'm attaching the modified demo project for your view.

[kt3_Without_IQ.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/3191586/kt3_Without_IQ.zip)
