### ISSUE TITLE
当前控制器弹窗键盘后，如果是通过手势滑动返回到上一个控制器，当前控制器的view会下移

### ISSUE THREAD

**Issue by Azraeltulips** [hackiftekhar/IQKeyboardManager#1555]
当前控制器弹窗键盘后，如果是通过手势滑动返回到上一个控制器，当前控制器的view会下移，并和导航栏直接出现空隙。并且发现只有加上tableview且cell上添加了输入框，这种情况下才会出现下移的问题，如果只有tableview且在view上添加输入框，此时键盘弹出来的时候，手势滑动返回时输入框会下移，但view是正常的。想请教一下这是什么原因呢？

**Comment by Azraeltulips** [comment]
demo中UITableview inContainer这个会出现同样的问题

**Comment by hackiftekhar** [comment]
@Azraeltulips which version of library you are using? Are you sure you are on latest version?

**Comment by Azraeltulips** [comment]
最新的6.3.0版本，确定是最新的库，下载的demo里面也是最新的库。经自己测试发现我的工程出现这个项目的原因是我自己给导航栏设置了背景图片导致的，你的demo里面就不知道是不是这个原因了。也不知道是不是这个库的某个属性和导航栏的背景图片设置有什么冲突？

**Comment by nlnlnull** [comment]
@hackiftekhar  Yes, I also have this problem.

**Comment by nlnlnull** [comment]
@hackiftekhar That's it, the latest code. 
![](https://raw.githubusercontent.com/nlnlnull/Figurebed/master/Capto_Capture%202019-07-24_05-27-52_PM%20-%2001.2019-07-24%2017_33_48.gif)

**Comment by deanli08** [comment]
@Azraeltulips  me too

**Comment by lhf90** [comment]
me too

**Comment by Azraeltulips** [comment]
> @Azraeltulips me too

那你解决了吗，我的只要不设置导航栏的背景图片就没有问题了，我最后是自己画了一个导航栏背景图片

**Comment by carlchou00** [comment]
我也出现了这个问题，我用的导航条的第三方库是这个https://github.com/listenzz/HBDNavigationBar
same issue here, I integrated this lib, not sure if it's related.(https://github.com/listenzz/HBDNavigationBar)

**Comment by hackiftekhar** [comment]
In these kind of cases, you should implement `viewWillDisappear:` and endEditing your viewController's view to dismiss keyboard. It should solve the problem.
```objc
-(void)viewWillDisappear:(BOOL)animated
{
    [super viewWillDisappear:animated];
    [self.view endEditing:YES];
}
```
