### ISSUE TITLE
点击 done 导致黑屏问题

### ISSUE THREAD

**Issue by 19aneng** [hackiftekhar/IQKeyboardManager#1556]
Using IQKeyboardManager (6.3.0)

点击 done 导致黑屏问题

![1559274394612198 2019-05-31 11_48_22](https://user-images.githubusercontent.com/22389902/58680359-11e60400-839a-11e9-9dc2-0cd07c54c481.gif)

**Comment by 19aneng** [comment]
https://www.jianshu.com/writer#/notebooks/11816854/notes/47883214/preview
我用了比较笨拙的方法解决了这个问题，可以看一下。

**Comment by hackiftekhar** [comment]
Please remove becomeFirstResponder from viewDidLoad
