### ISSUE TITLE
Does it support security code auto fill?

### ISSUE THREAD

**Issue by aboutyu** [hackiftekhar/IQKeyboardManager#1557]
Hi,

I'm using IQKeyboardManager, well.
I want to make sms security code auto fill using swift language.
How to make it using IQKeyboardManager. Or have do update plan?

**Comment by csc-EricWu** [comment]
me too

**Comment by hackiftekhar** [comment]
That's not a question for IQKeyboardManager. It's a question related to iOS SDK. Please check some forums or blogs how to do this.
