### ISSUE TITLE
Hi Bro,If u have time , please help  .

### ISSUE THREAD

**Issue by Wolfgang89** [hackiftekhar/IQKeyboardManager#1558]
my app just happen this situation，i'm use the system inputKeyBoard. i pod this lib into my project and this bug show, i can't debug SystemKeyBoard. can u help me, thank you every much!
<img width="759" alt="QQ20190605-153250@2x" src="https://user-images.githubusercontent.com/13148042/58938455-6f69be80-87a7-11e9-9f02-bb926e28c65d.png">

 
Xcode:10.2
 
Device:iPhone Max- 12.0.1

Library Version:6.0.3--OC

**Comment by hackiftekhar** [comment]
Hmm, this doesn't look to be from library because library only uses public API's and does not manipulate any apple keyboard frame changes or something like that.
