### ISSUE TITLE
Black space display at bottom in swift 5 when i dismiss the keyboard

### ISSUE THREAD

**Issue by imobdevtech** [hackiftekhar/IQKeyboardManager#1559]
**Describe the bug**
It happened in swift 5 when you dismiss numpad keyboard with **done** button then **black screen will display at bottom.**

**To Reproduce**
1. take text field with numpad keyboard
2. open keyboard and then dismiss with done button 
3. check behaviour black screen will display at bottom

**Expected behavior**
black screen will not be there and my view goes up inside the navigation bar which will not happen

**Screenshots**
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/159933/59041655-acf94500-8896-11e9-9dd2-bc25c6023cbb.gif)

### Versions
**Xcode:** 10.2.1
**Mac OS:** 10.14.4
**Simulator/Device:** Simulator
**Simulator/Device Name:** iPhone Xr
**Library Version:** 6.3.0

**Comment by hackiftekhar** [comment]
Ok, Please share demo project so that I can find out what may be the issue.

**Comment by imobdevtech** [comment]
@hackiftekhar Okay let me create some demo because this is happened in live project and also found the solution for this issue.
I make text field responder in 

> viewDidLoad

**Comment by ahmetsina** [comment]
> @hackiftekhar this is happened in live project and also found the solution for this issue.
> I make text field responder in `viewDidLoad` but if I changed in `viewDidAppear` then working fine

Same issue here. I make text field responder in viewDidAppear but it doesnt solve my issue.

**Comment by hackiftekhar** [comment]
Bottom blank space issues were happening with iOS 13, I fixed this with latest version of the library.

**Comment by OkonovUrmat** [comment]
> > @hackiftekhar this is happened in live project and also found the solution for this issue.
> > I make text field responder in `viewDidLoad` but if I changed in `viewDidAppear` then working fine
> 
> Same issue here. I make text field responder in viewDidAppear but it doesnt solve my issue.

When you use responders you should make your first textfield  to be a first responder, like that:
`override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(true)
        firstTextField.becomeFirstResponder()
    }'

**Comment by niveetom** [comment]
> > > @hackiftekhar this is happened in live project and also found the solution for this issue.
> > > I make text field responder in `viewDidLoad` but if I changed in `viewDidAppear` then working fine
> > 
> > 
> > Same issue here. I make text field responder in viewDidAppear but it doesnt solve my issue.
> 
> When you use responders you should make your first textfield to be a first responder, like that:
> 
> ```swift
> override func viewDidAppear(_ animated: Bool) {
>         super.viewDidAppear(true)
>         firstTextField.becomeFirstResponder()
>     }
> ```

this solution solved my issue.
