### ISSUE TITLE
Will you implement a dark mode?

### ISSUE THREAD

**Issue by JustinDMoore** [hackiftekhar/IQKeyboardManager#156]
Will you support a dark mode to match the UIKeyboard dark mode? As it stands, your toolbar sticks out against the dark mode keyboard.  Thanks

**Comment by mythodeia** [comment]
@JustinDMoore this is already implemented i think. In my own app this is done automatically.
there is code in IQKeyboardManager.m file inside the  ```addToolbarIfRequired``` method.
Do you have an example where this does not work as expected?

**Comment by JustinDMoore** [comment]
I just began using IQKeyboardManager via pods today (latest version). All of my keyboards default to dark mode, but the toolbar is always light. There is no specific example other than it just isn't working for me. Is there a property I need to set that you're aware of? I didn't see one in the documentation. Thanks.

**Comment by JustinDMoore** [comment]
Having looked at the method you mentioned, are you referring to _shouldToolbarUsesTextFieldTintColor?

**Comment by mythodeia** [comment]
there is a 
```
                    case UIKeyboardAppearanceAlert:
                    {
                        toolbar.barStyle = UIBarStyleBlack;
```

**Comment by JustinDMoore** [comment]
![](http://i.imgur.com/7o104Yw.jpg)

**Comment by mythodeia** [comment]
the image below is from the demo project.
![demo](https://cloud.githubusercontent.com/assets/1748458/5997358/eba160a0-aac2-11e4-9ebb-45d8ef87b89d.png)

**Comment by JustinDMoore** [comment]
In my AppDelegate, I set the following:
    [[IQKeyboardManager sharedManager] setShouldShowTextFieldPlaceholder:NO];
    [[IQKeyboardManager sharedManager] setToolbarManageBehaviour:IQAutoToolbarByPosition];
    [[IQKeyboardManager sharedManager] setKeyboardAppearance:UIKeyboardAppearanceAlert];

Is that not correct for the keyboard appearance?

**Comment by mythodeia** [comment]
you should also set the ```overrideKeyboardAppearance```  like this before:
```
            [[IQKeyboardManager sharedManager] setOverrideKeyboardAppearance:YES];
```

**Comment by JustinDMoore** [comment]
Modifying it to include overrideKeyboardAppearance didn't have any effect. Can't understand what is missing.
    [[IQKeyboardManager sharedManager] setOverrideKeyboardAppearance:YES];
    [[IQKeyboardManager sharedManager] setShouldShowTextFieldPlaceholder:NO];
    [[IQKeyboardManager sharedManager] setToolbarManageBehaviour:IQAutoToolbarByPosition];
    [[IQKeyboardManager sharedManager] setKeyboardAppearance:UIKeyboardAppearanceAlert];

**Comment by mythodeia** [comment]
can you try setting the KeyboardAppearance directly to a textfield and see if it works.
if it does then maybe the OverrideKeyboardAppearance is not working as it should

**Comment by JustinDMoore** [comment]
I've tried every combination I could think of.. changing UIKeyboardAppearanceAlert to UIKeyboardAppearanceDark.. with and without setOverrideKeyboardAppearance.. and setting the textfield directly. The keyboard itself will reflect light/dark mode accordingly, but the toolbar never changes.

**Comment by mythodeia** [comment]
maybe @hackiftekhar can help here. I have exhausted all my ideas. 
I tried the following 2 lines in my project as well inside a uitableview full of textfields and all are working fine.
```
    [[IQKeyboardManager sharedManager] setOverrideKeyboardAppearance:YES];
    [[IQKeyboardManager sharedManager] setKeyboardAppearance:UIKeyboardAppearanceAlert];
```

**Comment by hackiftekhar** [comment]
@Justin, actually the pod is not updated yet. Current I'm going with a very busy schedule without having internet connectivity. I'll update the pod when got sometime to update it.

**Comment by hackiftekhar** [comment]
@Mythodia, thanks for the help.

**Comment by mythodeia** [comment]
:+1:

**Comment by JustinDMoore** [comment]
Ok thanks. Good to know I'm not crazy!

**Comment by hackiftekhar** [comment]
Release new cocoapods version 3.2.1.1. This contains the dark mode implementation. Thanks for your patience.

**Comment by JustinDMoore** [comment]
Thanks so much. Updating soon.

**Comment by jbmaxwell** [comment]
My keyboard is switching to Dark Mode, but the "Done" button is black, and therefore pretty much invisible against the background. Is there a simple fix?
