### ISSUE TITLE
IQKeyboardManager (6.3.0) Doesn't allow me to set done button text.

### ISSUE THREAD

**Issue by ClarionAnilKukadeja** [hackiftekhar/IQKeyboardManager#1560]
**Describe the bug**
Hello
I have used IQKeyboardManager in my project and it does not allow me to Customise "Done" Button on toolbar.
I have used this code to change title but not reflecting in UI.

> `[IQKeyboardManager sharedManager].toolbarDoneBarButtonItemText = @"Web";`

upon debugging addToolbarIfRequired method in this method  toolbarDoneBarButtonItemText contains "web" as title. 

 else if (_toolbarDoneBarButtonItemText)
            {
                rightConfiguration = [[IQBarButtonItemConfiguration alloc] initWithTitle:_toolbarDoneBarButtonItemText action:@selector(doneAction:)];
            }

Can you please look into this?

**Comment by Zyfe3rX** [comment]
Same issue here.

**Comment by alfredolucomav** [comment]
Same issue

**Comment by hackiftekhar** [comment]
Then your project might be setting the `toolbarDoneBarButtonItemText` from somewhere else. It works for all other peoples. It would be great if you guys tell more information here so we can find out what might be the cause.
