### ISSUE TITLE
Support for Xcode 11's "Swift Package Manager"

### ISSUE THREAD

**Issue by OkiRules** [hackiftekhar/IQKeyboardManager#1561]
Is support for Xcode 11's "Swift Package Manager" coming?

Thanks

**Comment by kinarobin** [comment]
@OkiRules Sure! See [https://github.com/hackiftekhar/IQKeyboardManager/blob/master/Package.swift](https://github.com/hackiftekhar/IQKeyboardManager/blob/master/Package.swift)

**Comment by OkiRules** [comment]
Thanks!
