### ISSUE TITLE
how to Realize when using UITextContentTypeTelephoneNumber  on ios 10 +

### ISSUE THREAD

**Issue by csc-EricWu** [hackiftekhar/IQKeyboardManager#1562]
![image](https://user-images.githubusercontent.com/13517061/59315603-f90c1580-8cec-11e9-8309-ab2b493f3fe5.png)

**Comment by hackiftekhar** [comment]
This is not a question related to library because library does not tell about these things. Please check UITextField properties/settings.

**Comment by csc-EricWu** [comment]
thanks  I found that some of these models are OK.
