### ISSUE TITLE
iPhone X适配仍然有问题 当键盘下落的时候 self.view的Y坐标被强制改为64,iPhone X上面会被遮挡24pt

### ISSUE THREAD

**Issue by 623034345** [hackiftekhar/IQKeyboardManager#1563]
最新版适配BUG
![image](https://user-images.githubusercontent.com/21259873/59342119-b58cc800-8d3b-11e9-9b9d-aa66333e7a49.png)
键盘弹出正常  但是当键盘下落 VC的self.view 向下偏移的时候 并没有回到导航栏最下面  而是固定的64,这样在iPhone X及以后的机子上导航栏为88pt  这样就有24pt在导航栏下面  无法显示全

**Comment by hackiftekhar** [comment]
Please use english

**Comment by 623034345** [comment]
The latest version of the adaptation BUG. When the UIScroller above multiple textfield. The keyboard pops up normally.
But when the keyboard drops the ViewController's self.view down offset, it doesn't return to the bottom of the navigation bar but is fixed 64.
In this way, the navigation bar on the iPhone X and later machines is 88pt, so 24pt is not displayed under the navigation bar.

**Comment by 623034345** [comment]
> 请用英文

The latest version of the adaptation BUG. When the UIScroller above multiple textfield. The keyboard pops up normally.
But when the keyboard drops the ViewController's self.view down offset, it doesn't return to the bottom of the navigation bar but is fixed 64.
In this way, the navigation bar on the iPhone X and later machines is 88pt, so 24pt is not displayed under the navigation bar.

**Comment by DccRush** [comment]
I also have this problem, and I would like to ask you the same question.

**Comment by DccRush** [comment]
我也遇到了这个问题，你是如何处理的呢？

**Comment by hackiftekhar** [comment]
It would be good if you guys could share a demo project with me, and I will try to give you more thoughts on this.
