### ISSUE TITLE
Library not support with custom class?

### ISSUE THREAD

**Issue by karthisiva** [hackiftekhar/IQKeyboardManager#1564]
I am using your framework with https://github.com/ssowri1/SPPinView. It is not working when tap pinview. See my design 

![Screen Shot 2019-06-13 at 5 35 22 PM](https://user-images.githubusercontent.com/6926979/59431194-e20b1780-8e01-11e9-93d8-df967a73625a.png)

Note : Done button showing if i tap mobile number text field.(Your framework working) and even if i add one more textfield after pinview .

Next and previous icon not showing, If text field embeded with Stackviews.

**Comment by ssowri1** [comment]
Dear Karhi Siva,

Thank you for using [SPPinView](https://github.com/ssowri1/SPPinView). I checked this issue in my tool using [SPKeyBoardAvoiding](https://github.com/ssowri1/SPKeyBoardAvoiding). And It's working well. The SPKeyBoardAvoiding is also one of our product. Kindly check with this framework for better result.

**Thank you for you support!**

**Comment by karthisiva** [comment]
Thanks for your reply!!!..I looked into your **SPKeyBoardAvoiding**. and looks better. Your sample has done with direct scrollview and fields. My actual layouts with multiple stackviews and other controls, In this scenario not working.

**Comment by karthisiva** [comment]
IQPreviousNextView Does the work.

Actually issue was **SPPinView** not supporting because of superview is UIControl.(According to me). I have created new UIView and done everything same as **SPPinView** Now UI has moving up and down. Thanks to Both authors

**Comment by ssowri1** [comment]
Well! Yes as you said the superview is UIControl. And you also archive by
using new UIView with SPPinview. Thank you for your support.

Regards,

Sowrirajan Sugumaran
Sr.iOS Developer
Chennai, India.

ssowri1@gmail.com / +919715167118

 [image: LinkedIn]  <https://htmlsig.com/t/000001D14CNK> [image: Github]
<https://htmlsig.com/t/000001CZ752N>
