### ISSUE TITLE
Using .addDoneOnKeyboard doesn't allow me to set custom donebutton text or color.

### ISSUE THREAD

**Issue by Zyfe3rX** [hackiftekhar/IQKeyboardManager#1566]
Hi,

Using addDoneOnKeyboard  does not allow me to set custom text / color for done button. How do i set this or is this some issue?

Setting addDoneOnKeyboard :-
txtfield.addDoneOnKeyboard(withTarget: self, action: #selector(doneButtonClicked), titleText: "Next")

Setting donebuttongtext :-
IQKeyboardManager.shared().toolbarDoneBarButtonItemText = "Done"

This just makes the title to DONE instead of changing the done button text.

**Comment by hackiftekhar** [comment]
It is expected behaviour because using this method to add toolbar is like adding a custom toolbar in by your code, so IQKeyboardManager will start ignoring toolbar added by these methods manually.
