### ISSUE TITLE
View is not moving up

### ISSUE THREAD

**Issue by stefanosisto** [hackiftekhar/IQKeyboardManager#1567]
Hello.
I have a ParentController that has a container. This container has an height of 30% of the screen, starting from the bottom.
The container has his Controller (let me call ChildController). 
In ChildController I have a UITextView.
If I press on the UITextView, the keyboard cover all my textview, and I can't see what happens.
This is my config in the appDelegate.
        **IQKeyboardManager.shared().isEnabled = true
        IQKeyboardManager.shared().isEnableAutoToolbar = false
        IQKeyboardManager.shared().shouldResignOnTouchOutside = true
        IQKeyboardManager.shared().keyboardDistanceFromTextField = 30**

What i'm doing wrong?

**Comment by palla89** [comment]
Similar situation here, what should we do?

**Comment by Cleversou1983** [comment]
Same here....

**Comment by ph4r05** [comment]
I fixed this in my case by avoiding alignment to safe area of the scroll view. If I instead align the scroll view content to the superview it works.

**Comment by hackiftekhar** [comment]
The library usually works with the containerView. Have you added your containerView using addChildViewController method?
