### ISSUE TITLE
The bottom part of adjustedContentInset of last ScrollView not taken into account

### ISSUE THREAD

**Issue by ycherniavskyi** [hackiftekhar/IQKeyboardManager#1568]
**Describe the bug**
The `bottom` part of `adjustedContentInset` of last ScrollView not taken into account, which leads in the odd additional gap between ScrollView content and keyboard. The problematic layout provided in the Demo Project below.

The issue occur with Objective-C and Swift version.

**To Reproduce**
1. Open and Run the Demo Project 
2. Click on `Search Bar` at the top of table view
3. Scroll down to the end of table view
4. See error - the odd gap between table view content and keyboard

**Expected behavior**
This odd gap must not be there.

**Screenshots**
![image](https://user-images.githubusercontent.com/552025/60169453-65b80180-980f-11e9-84d7-c5a03e28dbab.png)

**Demo Project**
[IQKeyboardManagerIssue.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/3329428/IQKeyboardManagerIssue.zip)

### Versions
**Xcode:** 10.2.1
**Mac OS:** 10.14.5
**Simulator/Device:** 12.2
**Simulator/Device Name:** any
**Library Version:** 6.4.0

**Additional context**
I create a dirty fix for this issue, but not sure that it correctly applied for all cases:
``` diff
diff --git a/IQKeyboardManagerSwift/IQKeyboardManager.swift b/IQKeyboardManagerSwift/IQKeyboardManager.swift
index fa64ced..fd0bcb7 100644
--- a/IQKeyboardManagerSwift/IQKeyboardManager.swift
+++ b/IQKeyboardManagerSwift/IQKeyboardManager.swift
@@ -1257,6 +1257,8 @@ Codeless drop-in universal library allows to prevent issues of keyboard sliding

                     movedInsets.bottom = max(_startingContentInsets.bottom, bottom)

+                    movedInsets.bottom -= lastScrollView.adjustedContentInset.bottom
+
                     if lastScrollView.contentInset != movedInsets {
                         showLog("old ContentInset: \(lastScrollView.contentInset) new ContentInset: \(movedInsets)")
```

**Comment by hackiftekhar** [comment]
@ycherniavskyi Thanks for letting me know about this issue, just to let you know this has been fixed now.
