### ISSUE TITLE
iOS 13 Beta View keeps on top after dismiss

### ISSUE THREAD

**Issue by yahyatabba** [hackiftekhar/IQKeyboardManager#1569]
**Describe the bug**

**To Reproduce**
1. Go to textField and open keyboard
2. The view in moving up.
3. Scroll down to dismiss or click on Done.
4. The view keeps on top like the screen shot.

**Expected behavior**

**Screenshots**
![IMG_58F858AA9B7F-1](https://user-images.githubusercontent.com/23430157/60260463-56ee4f00-98e2-11e9-9b10-0ee56b56f2eb.jpeg)

### Versions
**Xcode:** 10.2.1
**Mac OS:** 10.15 Beta
**Simulator/Device:** xx.x
**Simulator/Device Name:** iPhone 6s
**Library Version:** 6.3.0
**iOS Version:** 13 Beta

**Additional context**

**Comment by hackiftekhar** [comment]
I've fixed this issue with latest version 6.4.0. Please update.

**Comment by JMStack** [comment]
The latest version 6.4.0 not work for me, after the keyboard showed up tap iPhone home button, make sure APP enter background, then make app enter foreground, drag the scrollview where uitextfield consist in,  the keyboard dismissed but toolbar still on there. This issue only exist on iOS13.

![image](https://user-images.githubusercontent.com/12120177/61707300-bb36ee00-ad7c-11e9-9a6f-5ad828b0dade.png)
![image](https://user-images.githubusercontent.com/12120177/61707075-41066980-ad7c-11e9-94a0-8c047cbabc6b.png)

**Comment by sm0nster** [comment]
Same issue for me on version 6.4.2 on 
- Simulator (Xr) iOS 12.2 
- iPhone X iOS 12.4.1
and many more

**Comment by hackiftekhar** [comment]
The toolbar is attached to the software keyboard which is maintained by Apple internal API's. The library does not manipulate toolbar position. If this is happening then it probably be iOS 13 beta issue.
