### ISSUE TITLE
Previous/Next are disabled

### ISSUE THREAD

**Issue by aabanaag** [hackiftekhar/IQKeyboardManager#1572]
**Describe the bug**
Previous and Next buttons are disabled. I have a nested stackviews and read that you need to have IQPreviousNext subclass on the wrapper view which I already added. Also my textfields are a sub-class of UITextField

Also have this on my AppDelegate
```
// Keyboard issue
    IQKeyboardManager.shared.enable = true
    IQKeyboardManager.shared.previousNextDisplayMode = .alwaysShow
```

![image](https://user-images.githubusercontent.com/2245822/60471328-d2f7e680-9c96-11e9-8ab2-02755418ed04.png)

**To Reproduce**
1. Tap first textfield with tag 0
2. Tap second textfield with tag 1

**Expected behavior**
Previous and Next button doesn't enable

**Screenshots**
![image](https://user-images.githubusercontent.com/2245822/60471298-b196fa80-9c96-11e9-8448-fe9f96c565e0.png)

### Versions
**Xcode:** 10.2
**Mac OS:** xx.xx.x
**Simulator/Device:** xx.x
**Simulator/Device Name:** iPhone xx
**Library Version:** x.x.x

**Additional context**

**Comment by hackiftekhar** [comment]
It should work as per your screenshot. If it does not happen then can you please share demo project with me?

**Comment by tadeha** [comment]
Doesn't work for me either when having stack views nested each other.

**Comment by puji26** [comment]
<img width="258" alt="Screen Shot 2019-07-23 at 17 44 50" src="https://user-images.githubusercontent.com/18373289/61706176-a012b100-ad71-11e9-8c78-019b6ca62b93.png">
