### ISSUE TITLE
IQKeyboardManager doesn’t work as expected when using view.safeAreaLayoutGuide

### ISSUE THREAD

**Issue by killmontag** [hackiftekhar/IQKeyboardManager#1576]
**Describe the bug**
I've got a button whose top anchor is: `backButton.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor, constant: 2).isActive = true`
And I've got a text view whose top anchor is : `storyDescription.topAnchor.constraint(equalTo: numOfChapters.bottomAnchor, constant: 16).isActive = true` (I've got elements between these but they don't affect this unusual behaviour) When I tap on the textView it sometimes goes above the view, this only happens when I use `view.safeAreaLayoutGuide`, this does not happen when I use `view.topAnchor`. Btw I am new to Github so I might not have written this issue properly, hope you understand. And again, **This only happens when I use `view.safeAreaLayoutGuide`**

**Screenshots**
![Screen Shot 2019-07-08 at 1 27 04 PM](https://user-images.githubusercontent.com/46274414/60792936-406ab200-a184-11e9-9066-8a455a97c885.png)
![Screen Shot 2019-07-08 at 1 27 17 PM](https://user-images.githubusercontent.com/46274414/60792949-48c2ed00-a184-11e9-9f2b-432359a9b859.png)
![Screen Shot 2019-07-08 at 1 27 29 PM](https://user-images.githubusercontent.com/46274414/60792970-511b2800-a184-11e9-95a6-f5ff0df35c18.png)

**Comment by boyfox** [comment]
I had same issue:
<img width="717" alt="image" src="https://user-images.githubusercontent.com/3168694/63950964-603c9900-ca96-11e9-95af-c1a7a8bdbb7d.png">

![Simulator Screen Shot - iPhone X - 2019-08-29 at 19 53 13](https://user-images.githubusercontent.com/3168694/63951290-ece75700-ca96-11e9-82c6-670d242618cc.png)
![Simulator Screen Shot - iPhone X - 2019-08-29 at 19 53 21](https://user-images.githubusercontent.com/3168694/63951292-ece75700-ca96-11e9-99bf-011947aa1e8b.png)
![Simulator Screen Shot - iPhone X - 2019-08-29 at 19 53 35](https://user-images.githubusercontent.com/3168694/63951293-ece75700-ca96-11e9-9bee-be1881ddf5e9.png)
![Simulator Screen Shot - iPhone X - 2019-08-29 at 19 53 45](https://user-images.githubusercontent.com/3168694/63951294-ed7fed80-ca96-11e9-9b2e-7c476b52981a.png)
![Simulator Screen Shot - iPhone X - 2019-08-29 at 19 53 59](https://user-images.githubusercontent.com/3168694/63951295-ed7fed80-ca96-11e9-968c-9a74edfbff5d.png)
![Simulator Screen Shot - iPhone X - 2019-08-29 at 19 54 09](https://user-images.githubusercontent.com/3168694/63951297-ed7fed80-ca96-11e9-9637-96ee41763120.png)
![Simulator Screen Shot - iPhone X - 2019-08-29 at 19 54 16](https://user-images.githubusercontent.com/3168694/63951298-ee188400-ca96-11e9-81d7-67173a21c806.png)

**Comment by boyfox** [comment]
Problem exists in version >= iPhone X, where exists safe area in screen
