### ISSUE TITLE
searchbar dont have toolbar

### ISSUE THREAD

**Issue by wqforever** [hackiftekhar/IQKeyboardManager#1577]
if (_IQcanBecomeFirstResponder == YES)
    {
        _IQcanBecomeFirstResponder = ([self isUserInteractionEnabled] && ![self isHidden] && [self alpha]!=0.0 && ![self isAlertViewTextField]  && !self.textFieldSearchBar);
    }

if i remove !self.textFieldSearchBar this code ，toolbar show，but not work

**Comment by MandeepSingh1** [comment]
Please provide your whole code as we can not generate this issue at our end. You have to provide full information in your issue. Then we ca help you with that.

**Comment by hackiftekhar** [comment]
@wqforever We have explicitly disabled toolbar for searchBar because it was not looking good in most of the cases. However if you need a toolbar then you can add it by your own for this special case.

**Comment by mrferris** [comment]
Why not just have a boolean that controls whether or not toolbar for searchBar is enabled and have it false by default? 

Making a custom pod just for this purpose complicates upgrades severely.
