### ISSUE TITLE
Stuck on Secure Text Entry

### ISSUE THREAD

**Issue by qstpnv** [hackiftekhar/IQKeyboardManager#1578]
**Describe the bug**
If checkmark Secure Text Entry inside TextField is on and TextField has some text inside - keyboard stuck on hide.

**To Reproduce**
1. Create TextField on View
2. Set Secure Text Entry to true
3. Run project
4. Type something in TextField
5. Press Done in keyboard toolbar
6. Application stuck

**Expected behavior**
Application doesn't stuck

### Versions
**Xcode:** 10.2.1 (10E1001)
**Mac OS:** 10.14.5 (18F132)
**Simulator/Device Name:** iPhone X (iOS 12.3.1)
**Library Version:** 6.2.1 and 6.4.0

**Comment by qstpnv** [comment]
Here is a link with video: https://youtu.be/tUBEfd-aQME

**Comment by MandeepSingh1** [comment]
Can you provide your code, because its working fine at our end and I have used a lot IQKeyboard Manager. And I think its something wrong with the code in your project.

**Comment by qstpnv** [comment]
@MandeepSingh1 have you tried to reproduce this like I have described in comment?
