### ISSUE TITLE
error: no such module `IQKeyboardManagerSwift` => 6.4.0

### ISSUE THREAD

**Issue by lawreyios** [hackiftekhar/IQKeyboardManager#1579]
**Describe the bug**
When archiving the project via Xcode 10.3, 10.2.1, they are working perfectly fine.
However, when archiving build using xcodebuild command, it fails badly. Needing to use xcodebuild command as I am running CI/CD jobs on Jenkins.

```
SupportingFiles/AppDelegate.swift:12:8: error: no such module 'IQKeyboardManagerSwift'
import IQKeyboardManagerSwift
       ^

** ARCHIVE FAILED **


The following build commands failed:
	CompileSwift normal arm64
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)
```

**To Reproduce**
Ran this command:
`xcodebuild -workspace [NAME].xcworkspace -scheme [NAME]-QA -sdk iphoneos -configuration Release-QA CODE_SIGNING_IDENTITY="[NAME]" PROVISIONING_PROFILE="[PROFILE]" archive -archivePath $PWD/build/[NAME].xcarchive`

**Expected behavior**
Archive Succeeded

### Versions
**Xcode:** 10.3
**Mac OS:** 10.14.6
**Library Version:** 6.4.0

**Comment by hackiftekhar** [comment]
May be pods haven't been successfully install or something similar issue? If you are successfully able to build the app using Xcode then it shouldn't be an issue.

**Comment by lawreyios** [comment]
> May be pods haven't been successfully install or something similar issue? If you are successfully able to build the app using Xcode then it shouldn't be an issue.

Pods definitely are properly installed already. I have also tried removing Pods/ folder and workspace so that they can be reinstalled. The results still the same.

**Comment by tritchey** [comment]
You might look at your project's `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` setting. I was running into a similar issue with SwiftKeychainWrapper, and setting that to NO fixed it.

**Comment by kalyan711987kalyan** [comment]
@lawreyios Did you solve the issue. I'm also facing same issue for continues build.

**Comment by daniel-hopkins** [comment]
perhaps you made the same mistake I did, I copied the first installation line `pod 'IQKeyboardManager'` and then tried to `import IQKeyboardManagerSwift` 
I fixed by adding the proper podfile line `pod 'IQKeyboardManagerSwift'`
