### ISSUE TITLE
Do not focus to the next field from the UITextView

### ISSUE THREAD

**Issue by dennygajera** [hackiftekhar/IQKeyboardManager#1580]
**Describe the bug**
Switch(next) between UITextView with TAB key

**To Reproduce**
1. Take two UiTextView.
2. Focus on 1st TextView.
3. Press TAB key. 
4. Don't move to the next field.

**Expected behavior**
It should move to the next field.

### Versions
**Xcode:** 10.2.1
**Simulator/Device Name:** iPAD 12.9 3rd generation
**Library Version:** IQKeyboardManager (6.3.0)

Please help me, how can I achieve this. 
Thank you.

**Comment by hackiftekhar** [comment]
Please check if you are using textViewShouldBeginEditing method and returning NO at some conditions?
