### ISSUE TITLE
Not Working For Text Editors like CKEditor.

### ISSUE THREAD

**Issue by kapilsardana19** [hackiftekhar/IQKeyboardManager#1581]
It does not automatically manage the keyboard scrolling when we start typing in the editor area. 

1. Open any sample project with WebView or WKWebView having CKEditor.
2. Type large content in the editor area, and dismiss the keyboard.
3. Now scroll down without opening the keyboard and now tap somewhere in the textarea
4. The cursor doesn't not come to the exact position where the editor was tapped.

**Comment by hackiftekhar** [comment]
Library does not manipulate or handle any js based or simply say WebView textFields. Library handle textFields created using native iOS API's like UITextField or UITextView and their subclasses.
