### ISSUE TITLE
系统为11.2时 会导致app启动崩溃

### ISSUE THREAD

**Issue by zhanghuichao** [hackiftekhar/IQKeyboardManager#1584]
/*  Automatically called from the `+(void)load` method. */
+ (IQKeyboardManager*)sharedManager
{
	//Singleton instance
	static IQKeyboardManager *kbManager;
	
	static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        
        kbManager = [[self alloc] init];
    });
	
	return kbManager;
}
调用这个方法导致app崩溃

**Comment by kinarobin** [comment]
Maybe, WatchDog kill the current process when the load method cost much time.

**Comment by zhanghuichao** [comment]
UITextField *view = [[UITextField alloc] init];
                [view addDoneOnKeyboardWithTarget:nil action:nil];
                [view addPreviousNextDoneOnKeyboardWithTarget:nil previousAction:nil nextAction:nil doneAction:nil];

Cannot form weak reference to instance (0x122008e00) of class UITextField. It is possible that this object was over-released, or is in the process of deallocation.


> Maybe, WatchDog kill the current process when the load method cost much time.

**Comment by zhanghuichao** [comment]
> Maybe, WatchDog kill the current process when the load method cost much time.

//If you experience exception breakpoint issue at below line then try these solutions https://stackoverflow.com/questions/27375640/all-exception-break-point-is-stopping-for-no-reason-on-simulator
                UITextField *view = [[UITextField alloc] init];
                [view addDoneOnKeyboardWithTarget:nil action:nil];
                [view addPreviousNextDoneOnKeyboardWithTarget:nil previousAction:nil nextAction:nil doneAction:nil];

Cannot form weak reference to instance (0x122008e00) of class UITextField. It is possible that this object was over-released, or is in the process of deallocation.

**Comment by hackiftekhar** [comment]
We are calling the sharedManager method form load using performSelector API with waitUntilDone as NO.
`[self performSelectorOnMainThread:@selector(sharedManager) withObject:nil waitUntilDone:NO];`

sharedManager get's call when MainThread gets free from doing other stuffs.
