### ISSUE TITLE
Next/Previous don't work if textFields are not in the same stackView

### ISSUE THREAD

**Issue by JaroVoltix** [hackiftekhar/IQKeyboardManager#1585]
**Describe the bug**
I have a stackView with Textfields for my register form.
Each textfield is under previous one except for two cases when I want to have 2 textfields in 1 one (house & apartment, postal code & city) so I add these 2 pair into next stackView. 
My xib looks like this
- email
- street
- house | apartment
- postal | city
- province
- phone

When I start on email, next button will go to street -> province -> phone
When I start on house, next button will go to -> apartment -> postal ->city
So there are two cycles of next/previous movement
**To Reproduce**
1. create Xib file
2. add StackView with vertical axis
3. add 2 textfields to vertical stackView
4. add 2 stackviews with horizontal axis to stackView
5. add 2 textfields to each horizontal stackView
6. add 2 textfields to vertical stackView
7. run app
8. select first textfied
9. select next button multiple times

**Expected behavior**
Focus should go into textfields that are into nested stack views

### Versions
**Xcode:** 10.3
**Mac OS:** 10.14.6
**Simulator/Device:** 10.3
**Simulator/Device Name:** iPhone 8
**Library Version:** 6.2.1

**Comment by maksymhusar** [comment]
Are there any solutions or workarounds?

**Comment by hackiftekhar** [comment]
There is a workaround by adding a IQPreviousNext containerView. Please check example app for more details.

**Comment by zarzonis** [comment]
> There is a workaround by adding a IQPreviousNext containerView. Please check example app for more details.

Thanks. This works great!
