### ISSUE TITLE
Not working under certain conditions

### ISSUE THREAD

**Issue by zxs179812234** [hackiftekhar/IQKeyboardManager#1586]
**Describe the bug**
There's a textView on the tableViewCell. When the tableView is initialized, when the textview in the page is outside the screen, slide the textview into the screen. The first time I click on the textView, the page doesn't pop up, creating a situation where the keyboard blocks the textView. If the textView is on the page after tableView initialization, the page will pop up normally

**To Reproduce**
1. tableViewCell contain a textView
2. When the tableView is initialized, when the textview in the page is outside the screen, slide the textview into the screen
3.The first time I click on the textView, the page doesn't pop up, creating a situation where the keyboard blocks the textView
4. If the textView is on the page after tableView initialization, the page will pop up normally

### Versions
**Xcode:** 10.2
**Mac OS:** 10.14.4
**Simulator/Device:** all
**Simulator/Device Name:** 
**Library Version:** 6.4.0 and 6.1.1

**Additional context**

Best wishes
Looking for help

**Comment by zxs179812234** [comment]
ps :
TableViewCell used xib

**Comment by zxs179812234** [comment]
i write a demo bug it is fine . i will check my code

**Comment by zxs179812234** [comment]
It has made two rounds of adjustPosition methods, which will result in incorrect positions. If you have only made one round of adjustPosition methods, there will be no problem.

**Comment by zxs179812234** [comment]
I have commented [self optimizedAdjustPosition] in keyboardWillShow; Method call. Almost. Just a little bit off.

**Comment by hackiftekhar** [comment]
It was because adjustPosition method was calling when keyboard show and also when textfield show. That's why we have written to avoid doing same kind of thing multiple times.
