### ISSUE TITLE
UIWebView Deprecated

### ISSUE THREAD

**Issue by shadiabusamra** [hackiftekhar/IQKeyboardManager#1587]
IQKeyboardManager has UIWebView so should replace it with WKWebView

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

**Comment by tanand7** [comment]
Got mail from Apple after uploading the build.

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information

**Comment by manmal** [comment]
@shadiabusamra I'm also suspecting IQKeyboardManager for this warning, but unless I'm wrong there's actually no UIWebView API usage in the library itself, only in the demo project.

**Comment by hackiftekhar** [comment]
I also checked just now, and I can confirm that there are no UIWebView API usage in the library, I can find 6 comment only but no actual references. Can you please check at your end @shadiabusamra ?

**Comment by jaceklapinski** [comment]
@hackiftekhar but U have comments that include word UIViewView :) this can be a problem. Can you remove it ??

**Comment by manmal** [comment]
@jaceklapinski Comments are not compiled, so they won't be in the app binary.

**Comment by deepak4u2006** [comment]
@manmal I have searched in my entire code, the only occurrence of "UIWebview" is in the IQKeyboardManager as comments, can it be removed?

**Comment by manmal** [comment]
@deepak4u2006 I can't find the SO thread right now. You can find the incriminating library like this:

1. Build the app 
2. Right click on the app binary (Usually in the group `Products`, with name `{TARGET}.app` - Finder should open
3. Command-C on the .app file (it's actually a folder)
4. Open Terminal, type `cd ` and press Command-V, enter.. You should now be within the app bundle
5. Execute this:
```
for framework in Frameworks/*.framework; do
  fname=$(basename $framework .framework)
  echo $fname
  nm $framework/$fname | grep UIWeb
done
```
6. If the command prints a line with `00000000000` and `UIWeb` in it, then that binary contains UIWebView symbols.

**Comment by deepak4u2006** [comment]
@manmal Thanks for the reply,
I tried the same as suggested, getting this:

Alamofire
AlamofireImage
Amplitude_iOS
Analytics
BiometricAuthentication
CommonUISDK
Down
IQKeyboardManagerSwift
KeychainSwift
MiSnapSDK
MiSnapSDKCamera
MiSnapSDKMibiData
MiSnapSDKScience
MobileFlow
PKHUD
Segment_Amplitude
SwiftyJSON
ZendeskCoreSDK
ZendeskProviderSDK
ZendeskSDK
                 U _OBJC_CLASS_$_UIWebView
netkisdk_ios
pop

**Comment by deepak4u2006** [comment]
@manmal thanks for the answer, got to know that **Zendesk** is using UIWebview APIs under the hood.

**Comment by hackiftekhar** [comment]
@deepak4u2006 @manmal @jaceklapinski @shadiabusamra Just to let you know guys, I have already replaced commented "UIWebView" to "WKWebView" in latest release which is v6.4.2.

**Comment by LiamLaverty5** [comment]
@deepak4u2006 How did you resolve this? My output from running the `for frameworks `command is the same as yours..
