### ISSUE TITLE
Layout Constraints Error - When opening keyboard type selector.

### ISSUE THREAD

**Issue by NickMandylas** [hackiftekhar/IQKeyboardManager#1588]
**Describe the bug**
When in UITextfield or UITextView, and when selecting to change keyboard a layout constraint error occurs.

**Error**
`2019-08-31 18:06:43.365859+1000 App[885:124044] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x280030500 'UISV-canvas-connection' UIStackView:0x137e08560.leading == UIInputSwitcherTableCellSegmentView:0x137e7ce80.leading   (active)>",
    "<NSLayoutConstraint:0x2800304b0 'UISV-canvas-connection' H:[UIInputSwitcherTableCellSegmentView:0x137e321c0]-(0)-|   (active, names: '|':UIStackView:0x137e08560 )>",
    "<NSLayoutConstraint:0x2800305a0 'UISV-fill-equally' UIInputSwitcherTableCellSegmentView:0x137e77480.width == UIInputSwitcherTableCellSegmentView:0x137e7ce80.width   (active)>",
    "<NSLayoutConstraint:0x280030be0 'UISV-fill-equally' UIInputSwitcherTableCellSegmentView:0x137e321c0.width == UIInputSwitcherTableCellSegmentView:0x137e7ce80.width   (active)>",
    "<NSLayoutConstraint:0x280030550 'UISV-spacing' H:[UIInputSwitcherTableCellSegmentView:0x137e7ce80]-(9)-[UIInputSwitcherTableCellSegmentView:0x137e77480]   (active)>",
    "<NSLayoutConstraint:0x280030730 'UISV-spacing' H:[UIInputSwitcherTableCellSegmentView:0x137e77480]-(9)-[UIInputSwitcherTableCellSegmentView:0x137e321c0]   (active)>",
    "<NSLayoutConstraint:0x280030000 'UIView-Encapsulated-Layout-Width' UIStackView:0x137e08560.width == 0   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x280030730 'UISV-spacing' H:[UIInputSwitcherTableCellSegmentView:0x137e77480]-(9)-[UIInputSwitcherTableCellSegmentView:0x137e321c0]   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.`

**Screenshots**
![Image of App](https://i.imgur.com/d4Ot7KY.png)

### Versions
**Xcode:** 10.3
**Simulator/Device:** iPhone 7 (Non-Simulator)
**Library Version:** 6.4.1

**Comment by hackiftekhar** [comment]
The library does not use with any private API's of keyboard management. This may be an iOS problem since the problem occurs when user select change keyboard option in software keyboard.
