### ISSUE TITLE
Uitextview inside a uitableview inside a uiviewcontroller.

### ISSUE THREAD

**Issue by kunwar231** [hackiftekhar/IQKeyboardManager#1589]
The controller doesn't scrolls at all when tapped on uitextview. The textfields work fine. 
The uitextview has dynamic height.
It is inside a uitableviewcell in a uitableview with bottom constraint of 50 from uiviewcontroller.

**Comment by kostiag** [comment]
> The controller doesn't scrolls at all when tapped on uitextview. The textfields work fine.
> The uitextview has dynamic height.
> It is inside a uitableviewcell in a uitableview with bottom constraint of 50 from uiviewcontroller.

I had similar issue in my own implementation of keyboard manager, what was the issue for you in this case?

**Comment by kunwar231** [comment]
I just mentioned what was the issue for me in this case.  Why are you asking it again?

**Comment by kostiag** [comment]
I do not see what you did to solve the prioblem? I have exactly same issue
text view inside a cell (not dynamic). Offset works fine when text field in
a cell but not when it is textview.
