### ISSUE TITLE
Next responder method?

### ISSUE THREAD

**Issue by cytryn** [hackiftekhar/IQKeyboardManager#159]
Since creating the returnKeyHandler takes over the delegate I cant implement any method myself.

So I am not using because I need some custom code on the delegate methods.

Is there a way to get the next UITextField so I can set it to be the first responder?

**Comment by hackiftekhar** [comment]
There is a delegate protocol for return key handler too which is nothing
but UITextFieldDelegate and UITextViewDelegate. You could set the delegate
of returnKeyHandler to self and it will work just like you need to
implement.

On Saturday, February 7, 2015, Andre <notifications@github.com> wrote:

> Since creating the returnKeyHandler takes over the delegate I cant
> implement any method myself.
>
> So I am not using because I need some custom code on the delegate methods.
>
> Is there a way to get the next UITextField so I can set it to be the first
> responder?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackiftekhar/IQKeyboardManager/issues/159>.
>


-- 
Sent from My iPhone

**Comment by cytryn** [comment]
This works.

Anyway, it would be great to have a way to know if there ir a next uitextfield or if it's the last one.

Usually people would like to do some custom code when the return key of the very last textfield is hit.

Does that make sense?

**Comment by hackiftekhar** [comment]
Yes, it makes sense. For now you can do it via textFieldShouldReturn by manually checking your lastTextField.

**Comment by cytryn** [comment]
Yeah, thats what I am actually doing.

Thanks for the help on the delegate note.

Hope you guys consider the option for a nextResponder method in the future.

**Comment by hackiftekhar** [comment]
Yes, in future I'll add selector for last textField. Thanks
