### ISSUE TITLE
Automatically reads last user message and showing up

### ISSUE THREAD

**Issue by bhardwajpankaj** [hackiftekhar/IQKeyboardManager#1590]
**I have not set UITextField content type to .oneTimeCode but still last message code shown up on the keyboard**

Automatically reads last user message and showing up

**To Reproduce**
1. Go to your otp sender screen
2. Then come back on other screen which have a textfield
3. then taps on textfield opens up the keyboard with last message
4. See error in screen shot

**Expected behavior**
User message content should not shown up on the keyboard untill user sets .oneTimeCode to the TextField

**Screenshots**
![WhatsApp Image 2019-09-02 at 3 55 10 PM](https://user-images.githubusercontent.com/5277297/64108427-608cab00-cd9a-11e9-835b-6117ebbaddf4.jpeg)

**Comment by hackiftekhar** [comment]
Dear @bharadwajpankaj, this library does not modify or control contentType. It must be on your project?
