### ISSUE TITLE
'Access to UITextField's _placeholderLabel ivar is prohibited. This is an application bug'

### ISSUE THREAD

**Issue by BestiOSDev** [hackiftekhar/IQKeyboardManager#1591]
'Access to UITextField's _placeholderLabel ivar is prohibited. This is an application bug'

**Comment by hackiftekhar** [comment]
So why you are trying to access _placeholderLabel? Can you please share screenshot?

**Comment by qiuyan81** [comment]
Terminating app due to uncaught exception 'NSGenericException', reason: 'Access to UITextField's _placeholderLabel ivar is prohibited. This is an application bug'

this bug ios13 Xcode11,Please fix as soon as possible.

**Comment by hackiftekhar** [comment]
Library does not access any private API's of UITextField or UITextView, you might probably be doing something like
```[textField valueForKeyPath:@"_placeholderLabel.textColor"]```

Please check all your code.

**Comment by mangireddy58** [comment]
@qiuyan81  Have you resolved it?

**Comment by Maja-Taka** [comment]
just replace "_placeholderLabel" with "placeholderLabel"

**Comment by VivekVithlani** [comment]
> just replace "_placeholderLabel" with "placeholderLabel"

Perfect solution
