### ISSUE TITLE
Layout constraint problem, Xcode 11 and iOS 13

### ISSUE THREAD

**Issue by kevint727** [hackiftekhar/IQKeyboardManager#1592]
Using the latest Xcode 11 beta and its' accompanying simulators (and a physical device) running iOS 13,  when trying to type in a UITextField, I get the following layout constraint error. This happens for any TextField on any of my views. I am using the latest version of IQKeyboardManager (6.4.1). I have never seen this before and I have been using the wonderful IQKeyboardManager for quite some time. I realize this is on beta software but just want to make sure this will not be an issue going forward as I've had iPhones (especially older ones) freeze up before in the wild because of layout constraint problems. 
[LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSAutoresizingMaskLayoutConstraint:0x6000004760d0 h=--& v=--& _UIToolbarContentView:0x7f8118925880.width == 0   (active)>",
    "<NSLayoutConstraint:0x6000004ec550 H:|-(0)-[_UIButtonBarStackView:0x7f8118925d50]   (active, names: '|':_UIToolbarContentView:0x7f8118925880 )>",
    "<NSLayoutConstraint:0x6000004eddb0 _UIButtonBarStackView:0x7f8118925d50.trailing == _UIToolbarContentView:0x7f8118925880.trailing   (active)>",
    "<NSLayoutConstraint:0x60000045e170 'TB_Leading_Leading' H:|-(8)-[_UIModernBarButton:0x7f811875eef0'Done']   (active, names: '|':_UIButtonBarButton:0x7f811875eb90 )>",
    "<NSLayoutConstraint:0x60000045e1c0 'TB_Trailing_Trailing' H:[_UIModernBarButton:0x7f811875eef0'Done']-(0)-|   (active, names: '|':_UIButtonBarButton:0x7f811875eb90 )>",
    "<NSLayoutConstraint:0x6000004754a0 'UISV-canvas-connection' UILayoutGuide:0x600001eca5a0'UIViewLayoutMarginsGuide'.leading == _UIButtonBarButton:0x7f811875d850.leading   (active)>",
    "<NSLayoutConstraint:0x600000475540 'UISV-canvas-connection' UILayoutGuide:0x600001eca5a0'UIViewLayoutMarginsGuide'.trailing == _UIButtonBarButton:0x7f811875eb90.trailing   (active)>",
    "<NSLayoutConstraint:0x6000004754f0 'UISV-spacing' H:[_UIButtonBarButton:0x7f811875d850]-(0)-[UIView:0x7f811875dfe0]   (active)>",
    "<NSLayoutConstraint:0x600000475590 'UISV-spacing' H:[UIView:0x7f811875dfe0]-(0)-[_UIButtonBarButton:0x7f811875e140]   (active)>",
    "<NSLayoutConstraint:0x6000004755e0 'UISV-spacing' H:[_UIButtonBarButton:0x7f811875e140]-(0)-[UIView:0x7f811875e8d0]   (active)>",
    "<NSLayoutConstraint:0x600000475630 'UISV-spacing' H:[UIView:0x7f811875e8d0]-(0)-[UIView:0x7f811892cbe0]   (active)>",
    "<NSLayoutConstraint:0x600000475680 'UISV-spacing' H:[UIView:0x7f811892cbe0]-(0)-[UIView:0x7f811875ea30]   (active)>",
    "<NSLayoutConstraint:0x6000004756d0 'UISV-spacing' H:[UIView:0x7f811875ea30]-(0)-[_UIButtonBarButton:0x7f811875eb90]   (active)>",
    "<NSLayoutConstraint:0x6000004d40a0 'UIView-leftMargin-guide-constraint' H:|-(0)-[UILayoutGuide:0x600001eca5a0'UIViewLayoutMarginsGuide'](LTR)   (active, names: '|':_UIButtonBarStackView:0x7f8118925d50 )>",
    "<NSLayoutConstraint:0x6000004c87d0 'UIView-rightMargin-guide-constraint' H:[UILayoutGuide:0x600001eca5a0'UIViewLayoutMarginsGuide']-(0)-|(LTR)   (active, names: '|':_UIButtonBarStackView:0x7f8118925d50 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x60000045e1c0 'TB_Trailing_Trailing' H:[_UIModernBarButton:0x7f811875eef0'Done']-(0)-|   (active, names: '|':_UIButtonBarButton:0x7f811875eb90 )>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2019-09-04 15:23:02.298774-0700 DevSwitcher[99909:4970416] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSAutoresizingMaskLayoutConstraint:0x6000004760d0 h=--& v=--& _UIToolbarContentView:0x7f8118925880.width == 0   (active)>",
    "<NSLayoutConstraint:0x6000004ec550 H:|-(0)-[_UIButtonBarStackView:0x7f8118925d50]   (active, names: '|':_UIToolbarContentView:0x7f8118925880 )>",
    "<NSLayoutConstraint:0x6000004eddb0 _UIButtonBarStackView:0x7f8118925d50.trailing == _UIToolbarContentView:0x7f8118925880.trailing   (active)>",
    "<NSLayoutConstraint:0x60000045d270 'IB_Leading_Leading' H:|-(0)-[_UIModernBarButton:0x7f811875da20]   (active, names: '|':_UIButtonBarButton:0x7f811875d850 )>",
    "<NSLayoutConstraint:0x60000045d2c0 'IB_Trailing_Trailing' H:[_UIModernBarButton:0x7f811875da20]-(>=8)-|   (active, names: '|':_UIButtonBarButton:0x7f811875d850 )>",
    "<NSLayoutConstraint:0x6000004754a0 'UISV-canvas-connection' UILayoutGuide:0x600001eca5a0'UIViewLayoutMarginsGuide'.leading == _UIButtonBarButton:0x7f811875d850.leading   (active)>",
    "<NSLayoutConstraint:0x600000475540 'UISV-canvas-connection' UILayoutGuide:0x600001eca5a0'UIViewLayoutMarginsGuide'.trailing == _UIButtonBarButton:0x7f811875eb90.trailing   (active)>",
    "<NSLayoutConstraint:0x6000004754f0 'UISV-spacing' H:[_UIButtonBarButton:0x7f811875d850]-(0)-[UIView:0x7f811875dfe0]   (active)>",
    "<NSLayoutConstraint:0x600000475590 'UISV-spacing' H:[UIView:0x7f811875dfe0]-(0)-[_UIButtonBarButton:0x7f811875e140]   (active)>",
    "<NSLayoutConstraint:0x6000004755e0 'UISV-spacing' H:[_UIButtonBarButton:0x7f811875e140]-(0)-[UIView:0x7f811875e8d0]   (active)>",
    "<NSLayoutConstraint:0x600000475630 'UISV-spacing' H:[UIView:0x7f811875e8d0]-(0)-[UIView:0x7f811892cbe0]   (active)>",
    "<NSLayoutConstraint:0x600000475680 'UISV-spacing' H:[UIView:0x7f811892cbe0]-(0)-[UIView:0x7f811875ea30]   (active)>",
    "<NSLayoutConstraint:0x6000004756d0 'UISV-spacing' H:[UIView:0x7f811875ea30]-(0)-[_UIButtonBarButton:0x7f811875eb90]   (active)>",
    "<NSLayoutConstraint:0x6000004d40a0 'UIView-leftMargin-guide-constraint' H:|-(0)-[UILayoutGuide:0x600001eca5a0'UIViewLayoutMarginsGuide'](LTR)   (active, names: '|':_UIButtonBarStackView:0x7f8118925d50 )>",
    "<NSLayoutConstraint:0x6000004c87d0 'UIView-rightMargin-guide-constraint' H:[UILayoutGuide:0x600001eca5a0'UIViewLayoutMarginsGuide']-(0)-|(LTR)   (active, names: '|':_UIButtonBarStackView:0x7f8118925d50 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x60000045d2c0 'IB_Trailing_Trailing' H:[_UIModernBarButton:0x7f811875da20]-(>=8)-|   (active, names: '|':_UIButtonBarButton:0x7f811875d850 )>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2019-09-04 15:23:02.310129-0700 DevSwitcher[99909:4970416] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSAutoresizingMaskLayoutConstraint:0x6000004760d0 h=--& v=--& _UIToolbarContentView:0x7f8118925880.width == 0   (active)>",
    "<NSLayoutConstraint:0x6000004ec550 H:|-(0)-[_UIButtonBarStackView:0x7f8118925d50]   (active, names: '|':_UIToolbarContentView:0x7f8118925880 )>",
    "<NSLayoutConstraint:0x6000004eddb0 _UIButtonBarStackView:0x7f8118925d50.trailing == _UIToolbarContentView:0x7f8118925880.trailing   (active)>",
    "<NSLayoutConstraint:0x60000045d7c0 'IB_Leading_Leading' H:|-(>=5)-[_UIModernBarButton:0x7f811875e310]   (active, names: '|':_UIButtonBarButton:0x7f811875e140 )>",
    "<NSLayoutConstraint:0x60000045d810 'IB_Trailing_Trailing' H:[_UIModernBarButton:0x7f811875e310]-(>=5)-|   (active, names: '|':_UIButtonBarButton:0x7f811875e140 )>",
    "<NSLayoutConstraint:0x6000004754a0 'UISV-canvas-connection' UILayoutGuide:0x600001eca5a0'UIViewLayoutMarginsGuide'.leading == _UIButtonBarButton:0x7f811875d850.leading   (active)>",
    "<NSLayoutConstraint:0x600000475540 'UISV-canvas-connection' UILayoutGuide:0x600001eca5a0'UIViewLayoutMarginsGuide'.trailing == _UIButtonBarButton:0x7f811875eb90.trailing   (active)>",
    "<NSLayoutConstraint:0x6000004754f0 'UISV-spacing' H:[_UIButtonBarButton:0x7f811875d850]-(0)-[UIView:0x7f811875dfe0]   (active)>",
    "<NSLayoutConstraint:0x600000475590 'UISV-spacing' H:[UIView:0x7f811875dfe0]-(0)-[_UIButtonBarButton:0x7f811875e140]   (active)>",
    "<NSLayoutConstraint:0x6000004755e0 'UISV-spacing' H:[_UIButtonBarButton:0x7f811875e140]-(0)-[UIView:0x7f811875e8d0]   (active)>",
    "<NSLayoutConstraint:0x600000475630 'UISV-spacing' H:[UIView:0x7f811875e8d0]-(0)-[UIView:0x7f811892cbe0]   (active)>",
    "<NSLayoutConstraint:0x600000475680 'UISV-spacing' H:[UIView:0x7f811892cbe0]-(0)-[UIView:0x7f811875ea30]   (active)>",
    "<NSLayoutConstraint:0x6000004756d0 'UISV-spacing' H:[UIView:0x7f811875ea30]-(0)-[_UIButtonBarButton:0x7f811875eb90]   (active)>",
    "<NSLayoutConstraint:0x6000004d40a0 'UIView-leftMargin-guide-constraint' H:|-(0)-[UILayoutGuide:0x600001eca5a0'UIViewLayoutMarginsGuide'](LTR)   (active, names: '|':_UIButtonBarStackView:0x7f8118925d50 )>",
    "<NSLayoutConstraint:0x6000004c87d0 'UIView-rightMargin-guide-constraint' H:[UILayoutGuide:0x600001eca5a0'UIViewLayoutMarginsGuide']-(0)-|(LTR)   (active, names: '|':_UIButtonBarStackView:0x7f8118925d50 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x60000045d810 'IB_Trailing_Trailing' H:[_UIModernBarButton:0x7f811875e310]-(>=5)-|   (active, names: '|':_UIButtonBarButton:0x7f811875e140 )>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.

**Comment by kevint727** [comment]
I have done some additional experimenting and it appears that the iOS13/Xcode 11 beta software in general is what causes the constraint issues. When running through Xcode 11 beta, you get the constraint issues mentioned above, both on simulators and on device. In addition, the iPhone Xs with iOS13 simulator actually freezes up whenever trying to bring up the keyboard.

**Comment by sameh0** [comment]
Same HERE 

```
Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x600003fca800 'TB_Trailing_Trailing' H:[_UIModernBarButton:0x7fd2bb54bfe0'Done']-(0)-|   (active, names: '|':_UIButtonBarButton:0x7fd2bb54abb0 )>
```

**Comment by kevint727** [comment]
This is still happening in the Xcode 11 GM seed and with using 6.4.2.

**Comment by mobileappdeveloper2019** [comment]
No i have put Mapbox with IQmanager and when ever Mapbox opens the y axis offset of IQkeyboard manger changes and toolbar will not able to show

**Comment by tosbaha** [comment]
You can fix this issue by adding a non empty frame for `UIToolbar` in library code. I am not familiar with how this library initializes the `UIToolbar`. Check the source code make the changes according to below example.

So instead of doing 
```swift
let toolbard = UIToolbar()
```
Do it like below

```swift
let toolbard =  UIToolbar(frame: CGRect(x: 0, y: 0, width: view.frame.size.width, height: 35))
```

**Comment by mobileappdeveloper2019** [comment]
Dear @tosbaha 

Thanks for reply, actually when ever Mapbox opens then keyboradFrameOffset changes from 0 to -260 and it will create problem to IQKeyboardManager toolbar offset. no need to change toolbar frame, I need to know what can I change in Mapbox so that it will fix in IQKeyboard.

[
![Screenshot 2019-09-17 at 5 55 54 PM](https://user-images.githubusercontent.com/49679497/65043488-72fb0d00-d974-11e9-93bf-0e5c871d5fb9.png)
![Screenshot 2019-09-17 at 5 56 03 PM](https://user-images.githubusercontent.com/49679497/65043489-72fb0d00-d974-11e9-832d-dfebda550d36.png)

](url)

**Comment by tosbaha** [comment]
@mobileappdeveloper2019 I am sorry I don't use this library at all. I just commented because I had similar issue on iOS 13. I am not sure but you may try to change 

`let newToolbar = IQToolbar()`

 line with 

```swift
let newToolbar = IQToolbar(frame: CGRect(x: 0, y: 0, width: view.frame.size.width, height: 35))
```

Good luck.

**Comment by fritzgt** [comment]
I had the same issue and I was able to fix it by following this Working with 
Section:
TopLayoutGuide and BottomLayoutGuide (Below v6.0.0)
Link:
https://github.com/hackiftekhar/IQKeyboardManager/wiki/Manual-Management#working-with-toplayoutguide-and-bottomlayoutguide-below-v600
