### ISSUE TITLE
view y issues

### ISSUE THREAD

**Issue by byztl** [hackiftekhar/IQKeyboardManager#1594]
After type first character in TextField, view's frame change back to original. TextField is covered by keyboard.

TextField's superview is shown after i click the tableviewcell by
```
[_telView mas_updateConstraints:^(MASConstraintMaker *make) {
            self.telView.hidden = NO;
            make.top.equalTo(self.view.mas_bottom).offset(-200);
        }];
[UIView animateWithDuration:0.3 animations:^{
        [self.view layoutIfNeeded];
}];
```

### Versions
**Xcode:10.1
**Mac OS: 10.14.2 (18C54)
**Simulator/Device: iPhone8 12.1

Video attached
https://www.dropbox.com/s/cdrjqbhqolaqy7p/%E5%B1%8F%E5%B9%95%E5%BD%95%E5%88%B6%202019-09-10%20%E4%B8%8B%E5%8D%884.15.33.mov?dl=0

**Comment by hackiftekhar** [comment]
It looks like the textField is added to the UIView, not on UITableView. If that's the case then it's expected behavior. Can you please let me know the hierarchy of your views?

**Comment by byztl** [comment]
I put two views in one xib document, and use 
```[[NSBundle mainBundle] loadNibNamed:NSStringFromClass([self class]) owner:self options:nil][0]```
load xib, then the issues occour.
Afterwords i divide views into single xib document.And the problem got be solved,
Maybe there are some baisc issuses that need to be clarified for me. thanks.
