### ISSUE TITLE
IQLayoutGuideConstraint outlet to the NSObject is invalid

### ISSUE THREAD

**Issue by rostopira** [hackiftekhar/IQKeyboardManager#1595]
**Describe the bug**
I'm following [this guide](https://github.com/ayon115/AZAutoGrowingTextView/tree/master/Pods/IQKeyboardManagerSwift), I've linked IQLayoutGuideConstraint to BottomLayout Guide like this 
<img width="472" alt="Screen Shot 2019-09-15 at 14 28 53" src="https://user-images.githubusercontent.com/16724952/64920944-ce3acd00-d7c5-11e9-8aa7-e9f30179ec30.png">
However, when I try to build project I'm receiving this error:
```
Main.storyboard The IQLayoutGuideConstraint outlet from the SupportVC to the NSObject is invalid. Outlets cannot be connected to repeating content.
```

**To Reproduce**
1. Link IQLayoutGuideConstraint to BottomLayout Guide
2. Try to build project

### Versions
**Xcode:** 10.3 (10G8)
**Mac OS:** Catalina beta 7
**Library Version:** 6.4.1

**Comment by hackiftekhar** [comment]
We deprecated the use of IQLayoutGuideConstraint. You are using iOS 6.4.1 you do not need to use IQLayoutGuideConstraint. Otherwise let me know why you need to use IQLayoutGuideConstraint and I'll provide you more information on this.

**Comment by rostopira** [comment]
I were trying to make view controller resizable (fullscreen textfield), but with default behavior everything goes up beyond screen
