### ISSUE TITLE
keyboard not correct working in collectionview

### ISSUE THREAD

**Issue by MansoorJafari9** [hackiftekhar/IQKeyboardManager#1596]
Hello
 I want to use this library in my app
 in collectioview cell not correct working and give me this log

The relevant UICollectionViewFlowLayout instance is <UICollectionViewFlowLayout: 0x1067186d0>, and it is attached to <UICollectionView: 0x10682ee00; frame = (0 0; 375 812); clipsToBounds = YES; autoresize = W+H; gestureRecognizers = <NSArray: 0x281d62d00>; layer = <CALayer: 0x281332360>; contentOffset: {0, 0}; contentSize: {2250, 812}; adjustedContentInset: {0, 0, 335, 0}> collection view layout:

![photo_2019-09-15_23-17-43](https://user-images.githubusercontent.com/52848663/64926129-116d5e00-d80f-11e9-8cfb-d2c04ab968a0.jpg)
![photo_2019-09-15_23-17-35](https://user-images.githubusercontent.com/52848663/64926130-13372180-d80f-11e9-86d1-ce977ceda404.jpg)

please help.

**Comment by myiosemail** [comment]
#import "IQUIScrollView+Additions.h"       
collectionView.shouldIgnoreScrollingAdjustment = YES;
