### ISSUE TITLE
the newest pod version has a bug

### ISSUE THREAD

**Issue by HebeTienCoder** [hackiftekhar/IQKeyboardManager#1597]
**Describe the bug**
the newest pod version cannot change toolbar.tintColor while UIKeyboardAppearanceDark,  previousBarButton/nextBarButton/doneBarButton always BlueColor while UIKeyboardAppearanceDark

**Comment by hackiftekhar** [comment]
This is intentionally, however I'll do the changes to make it a global for dark appearances.

**Comment by HebeTienCoder** [comment]
Thanks & Hopes hurry up.
The demand is not allow BlueColor
