### ISSUE TITLE
'Done' button bar disappears after entering Mapbox NavigationViewController

### ISSUE THREAD

**Issue by tiny0101** [hackiftekhar/IQKeyboardManager#1599]
I am now developing a driving navigation app using Mapbox iOS SDK.
I have detected an issue while using IQKeyboardManager.

When I entered into Mapbox Driving NavigationViewController. then and after then 'Done' button disappears forever for all input fields.
Help me to fix this issue.

**Comment by hackiftekhar** [comment]
Can you please send screenshot of the problem? Also can you please try debugging with UI Hierarchy debugger in Xcode to know where the problem is?

If nothing helps then I may need demo project to get into more detail on this issue.

**Comment by tiny0101** [comment]
Okay. Please check below link.

https://github.com/mapbox/mapbox-navigation-ios/issues/2228

The same thing happens in my app.
However, this blog introduces a workaround way.
But I want to solve this issue more clearly.

**Comment by hackiftekhar** [comment]
It may be due to the mapbox repository, so it would be better if they look into it, otherwise provide me a demo app to debug at my end.
