### ISSUE TITLE
Scrolling Issue in Keyboard i have put every thing inside in scrollView but it wasnt scroll the view 

### ISSUE THREAD

**Issue by AhmadDurrani579** [hackiftekhar/IQKeyboardManager#1601]
![Simulator Screen Shot - iPhone 8 - 2019-09-23 at 13 18 31](https://user-images.githubusercontent.com/46595112/65414407-b20de000-de04-11e9-90c5-7fa1bde57a7a.png)

**Comment by hackiftekhar** [comment]
have you added correct constraints?

**Comment by AhmadDurrani579** [comment]
Yes i have it already but didnt work it i have already upload the screen shot as well as

**Comment by AhmadDurrani579** [comment]
In previous version it was working fine now i am facing this issue after update the iOS 11

**Comment by hackiftekhar** [comment]
From screenshot, it looks like the keyboard had distance with textField. Not able to see the problem.

**Comment by AhmadDurrani579** [comment]
Like the keyboard open bht the textview not scroll in small device the
textfield hide the banner size large thats why i put in scrollview

**Comment by hackiftekhar** [comment]
I'm still not able to understand. Can you please share a video to better understand?

**Comment by jayarajb1116** [comment]
I'm also facing the issue after updating to 6.5.1 version. 
None of the textfields are scrolling up after updating the library.

**Comment by hackiftekhar** [comment]
Can you please share the demo project @jayarajb1116 sir?

**Comment by srikanthkumarmailid07** [comment]
I also facing the same problem in my last project, I think you disable the keyboard inside of the application.

Once search the following line in your application , anywhere you found to make it true

        **IQKeyboardManager.shared.enable = false**
