### ISSUE TITLE
[UICompatibilityInputViewController retain]: message sent to deallocated instance webview  input  crash

### ISSUE THREAD

**Issue by lotawei** [hackiftekhar/IQKeyboardManager#1603]
iOS  8 9 10 11 12 13 
crash when some webview input  value  change keyboard show and dismiss when focus ,
log ---  ***[UICompatibilityInputViewController retain]: message sent to deallocated instance 0x7ff0e94bf5e0 only this  but  i can use iqkeyboard in my project

**Comment by hackiftekhar** [comment]
It looks to be an private API call, The library does not manipulate any private API's. Can you please get more details on it?

**Comment by lotawei** [comment]
i resolve the issue  because   using  category of  the UIViewController and  overwriting dealloc method  by mistake

**Comment by lotawei** [comment]
thanks very much
