### ISSUE TITLE
iOS13, UItableViewCell Add TextField above, click on the input content, there will be a space above the keyboard, it will be normal when sliding tableview

### ISSUE THREAD

**Issue by XinlinLiu** [hackiftekhar/IQKeyboardManager#1608]
iOS13, UItableViewCell Add TextField above, click on the input content, there will be a space above the keyboard, it will be normal when sliding tableview.
version：6.5.0

**Comment by hackiftekhar** [comment]
Please explain or provide screenshot for better understand. I'm not sure I understand it properly.

**Comment by DamianSzejnoch** [comment]
Simulator -> Edit , disable automatically sync pasteboard

**Comment by XinlinLiu** [comment]
> Please explain or provide screenshot for better understand. I'm not sure I understand it properly.
![WX20190927-095743](https://user-images.githubusercontent.com/15344356/65736571-04eddd00-e10e-11e9-914b-48e2f8e9e378.png)

**Comment by hackiftekhar** [comment]
This space should be `keyboardDistanceFromTextField`. Default is 10, and it's expected behavior.
