### ISSUE TITLE
iOS 13 UITextField

### ISSUE THREAD

**Issue by DamianSzejnoch** [hackiftekhar/IQKeyboardManager#1609]
Next button above keyboard not working. Previous button working fine.

**Comment by toptomsk** [comment]
> same problem.
> 
> the reason is UIFieldEditor
> 
> ![1570785623409](https://user-images.githubusercontent.com/12609778/66640617-df072300-ec4b-11e9-81bf-0f6fc149dddc.jpg)
> 
> fix: swizzling the `responderViews` function and remove UIFieldEditors from result
> 
> ```swift
> extension IQKeyboardManager: SwiftInitializable {
>     public static func swiftInitialize() {
>         IQKeyboardManager.exchangeMethod(forClass: IQKeyboardManager.self, methods: .instance(NSSelectorFromString("responderViews"), #selector(_responderViews)))
>     }
>     
>     @objc private func _responderViews() -> [UIView] {
>         let result = self._responderViews()
>         return result.filter { "\(type(of: $0))" != "UIFieldEditor" }    // key
>     }
> }
> ```

Hey bro where do you take protocol  **SwiftInitializable** ? I couldnt find anything like this. Please help.

**Comment by DamianSzejnoch** [comment]
The problem is easy and I think should help for many people. Pod had the name changed. In pod file u should use 
pod 'IQKeyboardManagerSwift'  instead IQKeyboardManager like was used before. 

![Screenshot 2019-10-14 at 15 22 29](https://user-images.githubusercontent.com/44338496/66754520-719b0280-ee96-11e9-94cd-69a497149712.png)

**Comment by toptomsk** [comment]
> The problem is easy and I think should help for many people. Pod had the name changed. In pod file u should use
> pod 'IQKeyboardManagerSwift' instead IQKeyboardManager like was used before.
> 
> ![Screenshot 2019-10-14 at 15 22 29](https://user-images.githubusercontent.com/44338496/66754520-719b0280-ee96-11e9-94cd-69a497149712.png)

Oh thanks, it's my mistake not realize that.

**Comment by ajRiverav** [comment]
I'm not clear now. 

I have this issue and I am using Carthage ver 6.5.1. 

@svenfy, does the provided code snippet fix the issue? I'd like to add the fix to my checked out file.

**Comment by Yelles** [comment]
same problem here, on a objective-c projet.

Lost cursor on my texfields and Next button not working

**Comment by hackiftekhar** [comment]
The issue related to `UIFieldEditor` has been fixed and a new version will be released soon.

**Comment by MrVlad001** [comment]
> same problem here, on a objective-c projet.
> 
> Lost cursor on my texfields and Next button not working

just replace IQKeyboardManager with IQKeyboardManagerSwift in Podfile.
In AppDelegate import 
`#import <IQKeyboardManagerSwift-Swift.h>`

and add to didFinishLaunchingWithOptions next line
`    [[IQKeyboardManager shared] setEnable:YES];`

**Comment by Yelles** [comment]
> > same problem here, on a objective-c projet.
> > Lost cursor on my texfields and Next button not working
> 
> just replace IQKeyboardManager with IQKeyboardManagerSwift in Podfile.
> In AppDelegate import
> `#import <IQKeyboardManagerSwift-Swift.h>`
> 
> and add to didFinishLaunchingWithOptions next line
> ` [[IQKeyboardManager shared] setEnable:YES];`

thank you for the help but I can not use the swift build, this causes more problems because of the configuration of my project. i will wait for the fix.

> The issue related to `UIFieldEditor` has been fixed and a new version will be released soon.

Thanks, any idea when this new version is coming out?

**Comment by Yelles** [comment]
> The issue related to `UIFieldEditor` has been fixed and a new version will be released soon.

Thanks for the update, working now
