### ISSUE TITLE
NavigationBar pushed up when using textview.

### ISSUE THREAD

**Issue by JohnnyTseng** [hackiftekhar/IQKeyboardManager#161]
Hi, Thanks for creating this excellent library, it's really a time saver!
However, I found a little issue, wondering if it's a bug or I didn't implement in a right way.

I got a tableView in a UIViewController, created by pure code, there are 2 textFields and 1 textView in each cell's accessoryView
I've followed the instructions in the README set a scrollView to self.view to disable hidding navigationBar.
It's works on the first 2 textfield, but when focusing on textView, The navigationBar still get pushed up out of the view.

Textfield 1:

![ios simulator screen shot 2015 2 7 15 20 25](https://cloud.githubusercontent.com/assets/2656519/6091249/de8d04be-aedc-11e4-9e1a-cf0d695299cd.png)

Textfield 2:

![ios simulator screen shot 2015 2 7 15 20 25](https://cloud.githubusercontent.com/assets/2656519/6091250/e42cabe0-aedc-11e4-82fc-270b7ddc4ec2.png)

Not working on textView:

![ios simulator screen shot 2015 2 7 15 20 04](https://cloud.githubusercontent.com/assets/2656519/6091247/d0343d88-aedc-11e4-98a9-f4666e5ae65b.png)

Tested on iOS8, iPhone4s, Installed by Cocoapods, latest version.
Implemented
```

- (void)loadView
{
    [super loadView];
    UIScrollView *scrollView = [[UIScrollView alloc] initWithFrame:[[UIScreen mainScreen] bounds]];
    self.view = scrollView;
}
```
in my view controller.

Can you help me to find out what is the problem?
Thank you!

**Comment by hackiftekhar** [comment]
That's the functionality, you've implemented it in a right way.
IQKeyboardManager is responsible for full visibility of your
textField/textView.  Note that your textView height is too big to fit in
screen, if library don't move navigationBar then bottom of textView will be
hide by keyboard, and hiding textView is the major issue while your issue
is minor.

Please let me know for any further queries.

On Saturday, February 7, 2015, Johnny Tseng <notifications@github.com>
wrote:

> Hi, Thanks for creating this excellent library, it's really a time saver!
> However, I found a little issue, wondering if it's a bug or I didn't
> implement in a right way.
>
> I got a tableView in a UIViewController, created by pure code, there a 2
> textFields and 1 textView,
> I've followed the instructions in the README set a scrollView to self.view
> to disable hidding navigationBar. It's works in the first 2 textfield, but
> when focusing on textView, The navigationBar still get pushed up out of the
> view.
>
> Textfield 1:
>
> [image: ios simulator screen shot 2015 2 7 15 20 25]
> <https://cloud.githubusercontent.com/assets/2656519/6091249/de8d04be-aedc-11e4-9e1a-cf0d695299cd.png>
>
> Textfield 2:
>
> [image: ios simulator screen shot 2015 2 7 15 20 25]
> <https://cloud.githubusercontent.com/assets/2656519/6091250/e42cabe0-aedc-11e4-82fc-270b7ddc4ec2.png>
>
> Not working on textView:
>
> [image: ios simulator screen shot 2015 2 7 15 20 04]
> <https://cloud.githubusercontent.com/assets/2656519/6091247/d0343d88-aedc-11e4-98a9-f4666e5ae65b.png>
>
> Tested on iOS8, iPhone4s, Installed by Cocoapods, latest version.
> Implemented
>
>
> - (void)loadView
> {
>     [super loadView];
>     UIScrollView *scrollView = [[UIScrollView alloc] initWithFrame:[[UIScreen mainScreen] bounds]];
>     self.view = scrollView;
> }
>
> in my view controller.
>
> Can you help me to find out what is the problem?
> Thank you!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackiftekhar/IQKeyboardManager/issues/161>.
>


-- 
Sent from My iPhone

**Comment by JohnnyTseng** [comment]
Thanks for replying, Sorry that I misunderstand it :(
I'll close the issue, thanks again!

**Comment by hackiftekhar** [comment]
No problem, I'm always here to help.

**Comment by sandeepdekhdekh** [comment]
Hi 
I am Sandeep I am working on chatting application in which i have one UIcontroller class in which i have one UItableview and at the bottom i have one UItextfield when i click on textfield the IQKeyboard appear which hides UInavigation bar from that screen.But i dont want to hide that bar.Can you please help me to resolved that issue i will be really thank full to you.

**Comment by hackiftekhar** [comment]
I would suggest you to disable IQKeyboardManager in your chat screen and implement it in your own way. because it's gard to implement chat screen with IqKeyboardManager.

**Comment by sandeepdekhdekh** [comment]
Thanks for the quick reply.

**Comment by amitg02** [comment]
i am getting same  issues in my chat application where one is tableview and  at bottom textview when clcik on textview navigation get upside out of screen. @hackiftekhar

**Comment by nguyenhaidang** [comment]
Observer UIKeyboardDidChangeFrame
and call reloadLayoutIfNeeded :)

**Comment by YERUVAKONIREDDY** [comment]
i am also facing issue in chat app.while appearing keyboard that top view going to hide and that too half tableview is going to hide can you help me



![screen shot 2018-01-09 at 12 49 35 pm](https://user-images.githubusercontent.com/30068182/34709083-ac6b8e8a-f53b-11e7-8b3a-eb2059aef8e7.png)
![screen shot 2018-01-09 at 12 49 47 pm](https://user-images.githubusercontent.com/30068182/34709085-acac0afa-f53b-11e7-9650-48a25679d173.png)

**Comment by YERUVAKONIREDDY** [comment]
I would suggest you to disable IQKeyboardManager in your chat screen and implement it in your own way. because it's gard to implement chat screen with IqKeyboardManager.   


how can disable iqkeyboard manger in that specific viewcontroller

**Comment by hackiftekhar** [comment]
@YERUVAKONIREDDY is right, library isn't much optimized for this kind of screens because library doesn't know much about the architecture of the app and thinking of a developer. Library has a common logic to handle normal cases issues. It would be better if you disable library in this particular controller. If you will want to enable library here then please read manual management guide, it does have some tricks to make things work with chat screens.

**Comment by YERUVAKONIREDDY** [comment]
@Mohd Quereshi,

Thank you giving suggestion.i disabled iqkeyboard in that specific
viewcontroller,but i need more properties to manage keyboard in swift.do
you have any thing else,to manage that.please send me if u have.thank you
