### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by yuyedaidao** [hackiftekhar/IQKeyboardManager#1610]
>   ERROR | [iOS] xcodebuild:  IQKeyboardManagerSwift/IQKeyboardManagerSwift/IQKeyboardManager.swift:2036:35: error: enum case 'dark' not found in type 'UIKeyboardAppearance?'
     ERROR | [iOS] xcodebuild:  IQKeyboardManagerSwift/IQKeyboardManagerSwift/IQToolbar/IQUIView+IQKeyboardToolbar.swift:460:23: error: enum case 'dark' not found in type 'UIKeyboardAppearance?'

Swift5.0

**Comment by akshitzaveri** [comment]
+1

**Comment by hulk10425** [comment]
+1

**Comment by Deepjunctiontech** [comment]
+1

**Comment by hackiftekhar** [comment]
Guys, please post in which environment it's not getting compiled? Can you please provide these:-
Xcode: ?
iOS: ?
Swift Version: ?
