### ISSUE TITLE
carthage update issue

### ISSUE THREAD

**Issue by HagerGamal95** [hackiftekhar/IQKeyboardManager#1614]
updating carthage raise error in log file at path "/var/folders/s9/t52k5w3n1_xfkg0pklq0zvwm0000gp/T/carthage-xcodebuild.N0wkc3.log"

described as : 

IQKeyboardManagerSwift/IQKeyboardManager.swift:2036:35: error: enum case 'dark' not found in type 'UIKeyboardAppearance?'
                            case .dark:
                                  ^
                                      ?
/Users/hagergamal/ABKChatbot/Vendor/Carthage/Checkouts/IQKeyboardManager/IQKeyboardManagerSwift/IQToolbar/IQUIView+IQKeyboardToolbar.swift:460:23: error: enum case 'dark' not found in type 'UIKeyboardAppearance?'
                case .dark:
                      ^
                          ?

** ARCHIVE FAILED **

The following build commands failed:
	CompileSwift normal arm64
	CompileSwiftSources normal armv7 com.apple.xcode.tools.swift.compiler
	CompileSwift normal armv7
(3 failures)

**Comment by gilroykilroy** [comment]
Yes, this needs to be in an iOS 13 check.
