### ISSUE TITLE
unable to simultaneously satisfy constraints.

### ISSUE THREAD

**Issue by ROOKIE-lori** [hackiftekhar/IQKeyboardManager#1615]
**Describe the bug**
Unable to simultaneously satisfy constraints, when uitextfield become first responder, on iOS13

**Screenshots**
![图片](https://user-images.githubusercontent.com/6301122/65748459-92ddbe00-e136-11e9-97bd-7d126f6503c6.png)

**Comment by coulCod** [comment]
I have a same issue. But my application some times freezee at this point.

My console output:
2019-09-27 11:45:04.902126+0300 MyProject[4739:385965] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSAutoresizingMaskLayoutConstraint:0x600002d38fa0 h=--& v=--& _UIToolbarContentView:0x7f9584062380.width == 0   (active)>",
    "<NSLayoutConstraint:0x600002d7fd40 H:|-(0)-[_UIButtonBarStackView:0x7f95840626e0]   (active, names: '|':_UIToolbarContentView:0x7f9584062380 )>",
    "<NSLayoutConstraint:0x600002d7f7f0 _UIButtonBarStackView:0x7f95840626e0.trailing == _UIToolbarContentView:0x7f9584062380.trailing   (active)>",
    "<NSLayoutConstraint:0x600002d3d180 'TB_Leading_Leading' H:|-(8)-[_UIModernBarButton:0x7f9580e55c30'Done']   (active, names: '|':_UIButtonBarButton:0x7f9580e54270 )>",
    "<NSLayoutConstraint:0x600002d3d1d0 'TB_Trailing_Trailing' H:[_UIModernBarButton:0x7f9580e55c30'Done']-(0)-|   (active, names: '|':_UIButtonBarButton:0x7f9580e54270 )>",
    "<NSLayoutConstraint:0x600002d38730 'UISV-canvas-connection' UILayoutGuide:0x600003775ce0'UIViewLayoutMarginsGuide'.leading == UIView:0x7f958407db80.leading   (active)>",
    "<NSLayoutConstraint:0x600002d38780 'UISV-canvas-connection' UILayoutGuide:0x600003775ce0'UIViewLayoutMarginsGuide'.trailing == _UIButtonBarButton:0x7f9580e54270.trailing   (active)>",
    "<NSLayoutConstraint:0x600002d387d0 'UISV-spacing' H:[UIView:0x7f958407db80]-(0)-[UIView:0x7f958403f1e0]   (active)>",
    "<NSLayoutConstraint:0x600002d38820 'UISV-spacing' H:[UIView:0x7f958403f1e0]-(0)-[UIView:0x7f9580e54110]   (active)>",
    "<NSLayoutConstraint:0x600002d38870 'UISV-spacing' H:[UIView:0x7f9580e54110]-(0)-[_UIButtonBarButton:0x7f9580e54270]   (active)>",
    "<NSLayoutConstraint:0x600002d7fa20 'UIView-leftMargin-guide-constraint' H:|-(0)-[UILayoutGuide:0x600003775ce0'UIViewLayoutMarginsGuide'](LTR)   (active, names: '|':_UIButtonBarStackView:0x7f95840626e0 )>",
    "<NSLayoutConstraint:0x600002d7de50 'UIView-rightMargin-guide-constraint' H:[UILayoutGuide:0x600003775ce0'UIViewLayoutMarginsGuide']-(0)-|(LTR)   (active, names: '|':_UIButtonBarStackView:0x7f95840626e0 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x600002d3d1d0 'TB_Trailing_Trailing' H:[_UIModernBarButton:0x7f9580e55c30'Done']-(0)-|   (active, names: '|':_UIButtonBarButton:0x7f9580e54270 )>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.

**Comment by coulCod** [comment]
There is no warning message after upgrading lib to 6.5.0.
Thanks to the developers for a quick fix.

**Comment by ROOKIE-lori** [comment]
how can i update lib to 6.5.0.thanks
![图片](https://user-images.githubusercontent.com/6301122/65824469-5035f600-e29c-11e9-9e32-3faf35c87d54.png)

**Comment by gask** [comment]
@coulCod There are no warnings after the update, but the problem persists.. The app freezes upon clicking on the field.. :(

**Comment by gask** [comment]
For anyone that is still experiencing the freeze (but not the warnings anymore), use this:
Disable 'Automatically Sync Pasteboard'.
Simulator -> Edit -> Automatically Sync Pasteboard
