### ISSUE TITLE
I don't want bounce effect when appear keyboard

### ISSUE THREAD

**Issue by aboutyu** [hackiftekhar/IQKeyboardManager#1619]
Hi,

This is very useful open source for me.
I make Chatting View.
The UIView bounces instantly after the keyboard is appearing.
I want to remove the bounce effect applied to the UIView when the keyboard is appearing.

**Comment by hackiftekhar** [comment]
Hi @aboutyu, chat screen is something special kind of screen for the library, so it would be better if you disable the library in your chat controller and implement your solution.
