### ISSUE TITLE
toolbar arrow button issue

### ISSUE THREAD

**Issue by mythodeia** [hackiftekhar/IQKeyboardManager#162]
Hello @hackiftekhar 
 
i tried the demo project to replicate a small issue i am having and its happening there as well.
if you open the textfield demo and tap on the 1st textfield shouldn't the toolbar back button be disabled since its the 1st textfield? 
For the 1st and last textfield the previous and next arrow buttons should respectively be disabled according to textfield position, right?

thanks

**Comment by hackiftekhar** [comment]
If it's happening in github demo app then I'll check, otherwise could you please send me demo.

**Comment by mythodeia** [comment]
yes its happening on the demo project as well, on the textfield demo

**Comment by hackiftekhar** [comment]
Ok, will check. Thanks for the report.

**Comment by hackiftekhar** [comment]
I do not found any issue with the demo project while toolbarManageBehaviour = IQAutoToolbarByPosition. However I've done some random tagging and random subView order in hierarchy to demonstrate IQAutoToolbarBySubviews and IQAutoToolbarByTag. Make sure toolbarManageBehaviour is set to IQAutoToolbarByPosition.

Please let me know if still it's not working.

**Comment by mythodeia** [comment]
maybe i am missing something. i just downloaded the latest version from your library and just opened it and run the textfield demo. when i tap the 1st one i get this screen:
![screen](https://cloud.githubusercontent.com/assets/1748458/6133814/4a3a3d6e-b165-11e4-86df-7c16aa150475.png)
both arrows are enabled and clickable.

**Comment by hackiftekhar** [comment]
Thanks @mythodeia I'll check for the latest source code on the gihub repo. Again Thanks for the help.

**Comment by mythodeia** [comment]
yeap..that did it! thanks for the support

**Comment by hackiftekhar** [comment]
I put a wrong check for toolbar.  Fixed it and pushed the code, it will work fine now.

**Comment by mythodeia** [comment]
i have replied above ... everything is working fine now! thanks again
