### ISSUE TITLE
Crash when launching the app

### ISSUE THREAD

**Issue by LaurentiuUngur** [hackiftekhar/IQKeyboardManager#1622]
**Describe the bug**

As soon as I launch the app, it gives  `EXC_BAD_ACCESS (code=1, address=0x4d100c5f0)`
Code is put into `didFinishLaunchingWithOptions`

**Screenshots**

<img width="717" alt="Screenshot 2019-10-01 at 19 12 40" src="https://user-images.githubusercontent.com/13499785/65980424-ce9ebd80-e47f-11e9-8fc9-da42050e214d.png">

### Versions
**Xcode:** 11.0 (11A420a)
**Mac OS:** 10.14.6 (18G103)
**Device:** iOS 13.1.2
**Simulator/Device Name:** iPhone 11 Pro
**Library Version:** IQKeyboardManagerSwift 6.5.1
**Project:** Latest Swift version and latest SDK is used.

**Additional context**

I've just updated the library from version 6.4.2 and I got this crash.

**Comment by hackiftekhar** [comment]
Please clean project and build again. Hope this help.

**Comment by pcoltau** [comment]
I had the same issue, and a clean project helped 👍

**Comment by harshjoshi096** [comment]
Hello @LaurentiuUngur  did you get any solution for this? As I have tried above suggestions shared by @hackiftekhar  and @pcoltau but my app is still crashing.

**Comment by hackiftekhar** [comment]
Then @harshjoshi096 can you please provide more information on this? It may be that you are having some other issues.
