### ISSUE TITLE
Disable adjusting scrollView which is also inside in a TableView

### ISSUE THREAD

**Issue by mghani** [hackiftekhar/IQKeyboardManager#1623]
I have textField in a scrollView which is also in a tableView. Upon textField tap IQKeyboardManager scrolls the ScrollVIew as well as TableView. Please advise is there a way to only scroll parent TableVIew, scrollView shouldn't be moved.

Versions
Xcode: 11.1
Mac OS: 10.14.5 
Device: iOS 13.1
Simulator/Device Name: IPad Pro
Library Version: IQKeyboardManagerSwift 6.3

**Comment by hackiftekhar** [comment]
@mghani You could set your `scrollview.shouldIgnoreScrollingAdjustment = true` this property is declared in `IQUIScrollView+Additions.swift` file.
