### ISSUE TITLE
In iOS13 toolbar's backgroundColor will become clear when interactivePopGestureRecognizer is triggered

### ISSUE THREAD

**Issue by desmondYing** [hackiftekhar/IQKeyboardManager#1625]
In iOS13, when viewcontroller's interactivePopGestureRecognizer is triggered, the toolbar's backgroundColor will become clear, and the toolbar's separator line will also dismiss.

Then I set:
`IQKeyboardManager.shared.toolbarBarTintColor = .white`

But after this the toolbar will not be translucent.

How can I solve this issue? I'm using Xcode 11.0 and Swift 5.1, and I install IQKeyboardManager by carthage:
`github "hackiftekhar/IQKeyboardManager" ~> 6.5.0`

**Comment by desmondYing** [comment]
Has anyone encountered this problem?

**Comment by BiohazardUA** [comment]
Same

**Comment by hackiftekhar** [comment]
I can confirm that this is not library issue. I'm successfully able to reproduce this issue without including the library and the very basic setup. I hope Apple will fix it soon. I'm attaching the standalone project.
[InteractivePop iOS13 Bug.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/4049389/InteractivePop.iOS13.Bug.zip)
