### ISSUE TITLE
iOS13  textField cannot be input content

### ISSUE THREAD

**Issue by QingQingLi** [hackiftekhar/IQKeyboardManager#1627]
IQKeyboardManager  SDK  version  is  6.5.0
1.There are two input boxes on the login page. When I click to enter the first input box (enter the phone number), and then click the second input box, the second input box cannot input content, when the app starts for the first time. I will encounter this situation
![IMG_BEA52A0776F9-1](https://user-images.githubusercontent.com/14291483/66647098-8be89c80-ec5a-11e9-9935-64f0dd0cee14.jpeg)

2. if i set  code like this 
    [IQKeyboardManager sharedManager].enableAutoToolbar = YES;

Switching between the two input boxes will cause the prompt box to disappear and the keyboard will not pop up.
![WechatIMG2](https://user-images.githubusercontent.com/14291483/66647369-4ed0da00-ec5b-11e9-95ba-c9219b2bd17b.jpeg)

### Versions   6.5.0
**Xcode:11
**Mac OS:** xx.xx.x
**Simulator/Device:iphone 7 plus

**Comment by qs991011** [comment]
我也遇到同样的问题，请问你解决了吗？

**Comment by QingQingLi** [comment]
没有，这个问题太难受了

**Comment by QingQingLi** [comment]
> 我也遇到同样的问题，请问你解决了吗？

没有，这个问题我无从下手，是SDK的问题

**Comment by TML007** [comment]
I also encountered the same problem, the simulator is running, the input box can't be entered, can you solve it?

**Comment by penoty** [comment]
I also have the same problem @hackiftekhar ,version is 6.5.0

**Comment by hackiftekhar** [comment]
Please try this https://github.com/hackiftekhar/IQKeyboardManager/issues/1600#issuecomment-534094279

**Comment by iHamzaaK** [comment]
I tried that workaround but still having the same issue.

**Comment by cqxueyinsong** [comment]
I met the same problem with Xcode 10.2.1, Simulator iPhone 11 Pro.
And I resolved the problem with 
disable Automatically Sync pastedboard and use Simulator iPhone 11 Pro Max.

**Comment by hackiftekhar** [comment]
Use @cqxueyinsong workaround. It works.

**Comment by sandip-singh** [comment]
Tried the workaround. But still facing the issue. I'm using version 6.5.5. Please help to resolve the issue.
