### ISSUE TITLE
iPhoneXR  iOS 13.2  Crash

### ISSUE THREAD

**Issue by wstcyx** [hackiftekhar/IQKeyboardManager#1628]
![3D5D8E9F-D855-47D2-8F5F-73119B8111B1](https://user-images.githubusercontent.com/14196041/66692875-44532680-ecd5-11e9-85b6-6e1b10094140.png)

**Comment by wstcyx** [comment]
Crash occurred when I clicked textview on iPhone XR IOS 13.2

-[UIView(IQToolbarAddition) drawingToolbarPlaceholder] 
-[IQKeyboardManager addToolbarIfRequired]

**Comment by wstcyx** [comment]
IQKeyBoardManager  version is  6.5.0

**Comment by hackiftekhar** [comment]
Is it also happening in simulator?

**Comment by wstcyx** [comment]
it happening in Real iphone

**Comment by wstcyx** [comment]
I've tried that it only happened in our project.

**Comment by wstcyx** [comment]
i don't kown how to fix it

**Comment by wstcyx** [comment]
i have try
    IQKeyboardManager *manager = [IQKeyboardManager sharedManager];
    manager.shouldShowToolbarPlaceholder = NO;
it's run  ok

**Comment by hackiftekhar** [comment]
Do you have any category of UITextView which has `placeholder` property?

**Comment by wstcyx** [comment]
i use swift IQkeyboard and OC IQkeyboard   make project crash

**Comment by hackiftekhar** [comment]
Use only 1 version. Using both versions in a single project will produce a crash. You could use the ObjC version in swift files and vice versa.
