### ISSUE TITLE
Adding view(textfield inside view) to UIApplication.shared.keyWindow not scrolling up

### ISSUE THREAD

**Issue by jayarajb1116** [hackiftekhar/IQKeyboardManager#1629]
this is happening after updating to the version 6.5.1

**Comment by PZXforXcode** [comment]
me too

**Comment by hackiftekhar** [comment]
UITextField/UITextView must be part of a UIViewController. Adding it directly to the UIApplication.shared.keyWindow is not supported by the library.

**Comment by leeqiangzi** [comment]
me too
