### ISSUE TITLE
Hi hackiftekhar

### ISSUE THREAD

**Issue by mahesh789** [hackiftekhar/IQKeyboardManager#1630]
**Describe the bug**
Inside Collection view cell text field is there. That text field is near to navigation bar. when I click on textfield moving to navigation above. This happening in xcode 11 and ios 13.
For resolving this issue i have written code **shouldIgnoreScrollingAdjustment = true**. But this is not a solution. Can you resolve my issue?. This issue is coming only in ios 13 not below versions

### Versions
**Xcode:** 11.0
**Mac OS:** 10.14.6 
**Simulator/Device:** Both
**Simulator/Device Name:** All Devices
**Library Version:** (5.0.8) objective c version

**Comment by mahesh789** [comment]
one more thing big issue. when i touch uitextfield application get freezing.. please resolve this isssue asap. Otherwise i have to remove iqkeyboard manager..

**Comment by hackiftekhar** [comment]
Please make the issue title more clear.

**Comment by hackiftekhar** [comment]
@mahesh789 Please describe the issue more clearly, I'm unable to understand the problem.

The freezing issue is related to the iOS 13 bug. Please follow this post-https://forums.developer.apple.com/thread/122972

Someone suggested a pasteboard workaround, I hope it helps.
