### ISSUE TITLE
There is a bug in installing with SPM

### ISSUE THREAD

**Issue by fanglinwei** [hackiftekhar/IQKeyboardManager#1631]
If I use`SPM` to install, I can't get the resource file in`IQKeyboardManager.bundle`. The button on`IQToolbar` doesn't show up.
<img width="500" alt="BUG_IMG" src="https://user-images.githubusercontent.com/16839723/66921415-ba4de980-f057-11e9-8c95-bd3dcd04b6e9.png">

**Comment by hackiftekhar** [comment]
I did a brief searching and people say, SPM does not support bundle for now. If anyone or you know a way to include bundle using SPM, let me know. I'll do the required changes.

**Comment by fanglinwei** [comment]
@hackiftekhar 
I am sorry, I don't know how to bundle the resource pack. I checked the official documentation and didn't see the solution given by Apple. I saw the resource package in the SDK of IQKeyboardManage, so I want to see how it is bundled, but it seems It is also invalid.

**Comment by hackiftekhar** [comment]
@fanglinwei I also do not know how to do it. :(

**Comment by hackiftekhar** [comment]
I have removed the bundle now and included the .xcasset file. Not sure if this will help, but you guys can try to see if that works for you.

**Comment by fanglinwei** [comment]
@hackiftekhar 
I tested this and still can't do it. It seems to be a bug in SPM. If you solve this problem temporarily, you can try to encode the image into a base64 string or binary, and then unlock it.

**Comment by hackiftekhar** [comment]
Yup, but that solution doesn't look feasible in open source libraries. However, the workaround will work.

**Comment by fanglinwei** [comment]
Can only be temporarily used as a temporary solution, waiting for Apple to fix this bug
