### ISSUE TITLE
Crash after setting enableAutoToolbar = true and tapping a text field

### ISSUE THREAD

**Issue by jefflovejapan** [hackiftekhar/IQKeyboardManager#1632]
**Describe the bug**
Setting `enableAutoToolbar = true` and tapping a text field causes my app to crash 100% of the time. It does not happen with a `UITextView`.

**To Reproduce**
1. In a view controller's `viewDidAppear` method, set `enableAutoToolbar = true`
2. Tap on a text field in that view controller

**Expected behavior**
The text field should become active, and a toolbar should appear above the keyboard.

**Screenshots**
<img width="1512" alt="Screen Shot 2019-10-18 at 12 39 09 AM" src="https://user-images.githubusercontent.com/3140681/67054080-aaabcf00-f143-11e9-8643-d18a5225352b.png">

**Demo Project**
Working on it

### Versions
**Xcode:** 11.1
**Mac OS:** 10.14.5
**Simulator/Device:** 13.1.3
**Simulator/Device Name:** iPhone 11 Pro
**Library Version:** 6.5.1

**Additional context**
We're balancing `viewDidAppear` and `viewWillDisappear` calls in view controllers that have `UITextField`s, calling `startAvoidingKeyboard` and `stopAvoidingKeyboard` respectively:

~~~swift
@objc
extension UIViewController {
    private var keyboardManager: IQKeyboardManager {
        return IQKeyboardManager.shared
    }

    func startAvoidingKeyboard(toolbar: Bool = false) {
        keyboardManager.enableAutoToolbar = toolbar
        keyboardManager.shouldResignOnTouchOutside = true
        keyboardManager.enable = true
    }

    func stopAvoidingKeyboard() {
        keyboardManager.enable = false
        keyboardManager.enableAutoToolbar = false
    }
}
~~~

It's also worth noting that asking the keyboard manager for its `enableAutoToolbar` value will return false, but the toolbar will still appear. We're using Carthage if that makes a difference.

**Comment by hackiftekhar** [comment]
Hi @jefflovejapan, sad to see you are experiencing a crash however, I'm not experiencing this crash. To let you know I haven't tested the library against Xcode 11.1 and iOS 13.3.

I have a suggestion for you on how you can make the call balancing easier. You can register ViewController's to disable distance handling, toolbar and touch resigning.
```
IQKeyboardManager.shared.disabledDistanceHandlingClasses.append(CustomViewController.self)
IQKeyboardManager.shared.disabledToolbarClasses.append(CustomViewController.self)
IQKeyboardManager.shared.disabledTouchResignedClasses.append(CustomViewController.self)
```

**Comment by hackiftekhar** [comment]
However, if you could share a demo project with me then it would be great.

**Comment by hackiftekhar** [comment]
I can see Xcode 11.1 support iOS 13.1 then how are you testing on iOS 13.3?

**Comment by jefflovejapan** [comment]
Hey Mohd, I updated my device after my submitting and saw the same crash.

**Comment by hackiftekhar** [comment]
Hi @jefflovejapan Can you please answer my question?

**Comment by jefflovejapan** [comment]
Sorry Mohd, I thought I did! I originally submitted the bug when I saw was running iOS 13.1 on my device, then updated iOS to see if the issue still happened on 13.3, and it did. Sorry if I'm misunderstanding.

**Comment by jefflovejapan** [comment]
Sorry again Mohd, I'm on 13.1.3, not 13.3. Updated the description.

**Comment by hackiftekhar** [comment]
@jefflovejapan Have you created any demo project for me?

**Comment by jefflovejapan** [comment]
Sorry Mohd, been trying for a few hours and nothing I build exhibits the problem. I can't send you my actual application code because of the web of dependencies it has throughout the app, and anything that I try to peel out of it for you fails to crash the same way. I'm fine to close this because whatever it is must be highly specific to our setup.

**Comment by hackiftekhar** [comment]
That might be true that it is something with your application setup. btw have you tried this solution? https://github.com/hackiftekhar/IQKeyboardManager/issues/1632#issuecomment-543714555

**Comment by maqoo** [comment]
We are too using carthage and IQKeyboardManager and I just started to experience this. Our issue began when started using latest versions of dependencies. The one hint we have is that we are using Tealium iOS SDK and it seems to swizzle UITextField events. Other than this I am still investigating.

**Comment by maqoo** [comment]
We were able to reproduce the crash with tealium-swift 1.9.5 version. Rolling back to version 1.9.4 produced no crash. From a stack trace it seems that there is some DispatchQueue.main.sync {} call somwhere inside Tealium tracking of textfields that triggers this crash. 

For now the only way for this to work is to keep Tealium at version 1.9.4.

**Comment by maqoo** [comment]
Ok so this has nothing to do with the carthage dependencies. Kinda ;)

We had both of the libs (IQKeyboardManager and IQKeyboardManagerSwift) embedded and linked in the project. Leaving only one as linked and embedded solves the issue.
