### ISSUE TITLE
Navigation bar is not coming back to its original position.

### ISSUE THREAD

**Issue by RabiaAwan** [hackiftekhar/IQKeyboardManager#1633]
Describe the bug
Navigation bar is not coming back to original position after the dismiss of keyboard
same this isssue appeared on my side:
https://github.com/hackiftekhar/IQKeyboardManager/issues/1484
Versions
**Xcode:**11.0
Mac OS: 10.14.6
Device: not working on any device

Library Version: 6.4.2

**Comment by mechmatt01** [comment]
Same issue here!

**Comment by sacredsoul** [comment]
I had a similar issue. 'safeAreaInsets' changes to zero when keyboard shows up but not changing back. Try this.
IQKeyboardManager.shared.layoutIfNeededOnUpdate = true
