### ISSUE TITLE
Previous & Next button not appear and I assign above UIView as IQPreviousNextView

### ISSUE THREAD

**Issue by meliksahk** [hackiftekhar/IQKeyboardManager#1634]
![image](https://user-images.githubusercontent.com/6935693/67144010-7a1a8100-f27a-11e9-85ac-941d34fc70ee.png)

As you see in picture I assign UIView as IQPreviousNextView but still dont appear next previous buttons. I try to click , I said maybe only images dont show, but dont work.

in AppDelegate:

```
IQKeyboardManager.shared.enable = true
IQKeyboardManager.shared.previousNextDisplayMode = .alwaysShow
IQKeyboardManager.shared.toolbarPreviousNextAllowedClasses.append(UIStackView.self)
IQKeyboardManager.shared.shouldResignOnTouchOutside = true
IQKeyboardManager.shared.enableAutoToolbar = false
```

**Comment by hackiftekhar** [comment]
You've set enableAutoToolbar = false which hides the toolbar above the keyboard which contains previous/next buttons.

**Comment by meliksahk** [comment]
I change it to "true" but nothing changed.

**Comment by Adakhan** [comment]
same problem

**Comment by hackiftekhar** [comment]
Can you please post the screenshot?

**Comment by PrakashMaharjan** [comment]
I am also facing same issue. Next and Previous button is there but it is not seen. If we tap on left side of toolbar near where button would be there, its switching textfield. So may be button color or image is not seen due to dark mode color change.
Any fixation?

**Comment by hackiftekhar** [comment]
We have already adopted dark mode support in our library. Not sure what might be the cause at your end. But probably you are correct @PrakashMaharjan there might be an issue with either image or the color.

**Comment by Adakhan** [comment]
I solve problem, I changed images of buttons.
IQKeyboardManager.shared.toolbarPreviousButtonImage = UImage(named: "arrowUp")

**Comment by hackiftekhar** [comment]
You've probably installed the library using SPM or Carthage and it does not support Assets or bundle, that's why the images don't load. I just fixed this problem in c00cc17a6f073d96b0025b6954fe628e6647018a and will be available soon.

**Comment by dzungpv** [comment]
@hackiftekhar I use SPM and it not working with the latest, demo app using pod work.

**Comment by hackiftekhar** [comment]
What's not working @dzungpv?

**Comment by meetiosdev** [comment]
`   IQKeyboardManager.shared.enable = true
        IQKeyboardManager.shared.resignOnTouchOutside = true
        IQKeyboardManager.shared.toolbarConfiguration.tintColor = UIColor(named: "AppColorDark")
        IQKeyboardManager.shared.enableAutoToolbar = true
        IQKeyboardManager.shared.toolbarPreviousNextAllowedClasses = [UIScrollView.self,UIView.self,UITextField.self,UITextView.self,UIStackView.self]`
        
        this worked for me 
        
        `  IQKeyboardManager.shared.toolbarPreviousNextAllowedClasses = [UIScrollView.self,UIView.self,UITextField.self,UITextView.self,UIStackView.self]`

**Comment by hackiftekhar** [comment]
@meetiosdev You have override the previous value of toolbarPreviousNextAllowedClasses with your new array.
The old value also contains the IQPreviousNextView in array.

Instead of changing the whole array to new value, you should be adding your view classes to it like below:-
```swift
IQKeyboardManager.shared.toolbarPreviousNextAllowedClasses.append(UIScrollView.self)
IQKeyboardManager.shared.toolbarPreviousNextAllowedClasses.append(UIStackView.self)
...
```
etc
