### ISSUE TITLE
Keyboard Cannot Appearance and  cannot gonext

### ISSUE THREAD

**Issue by SongJasper** [hackiftekhar/IQKeyboardManager#1637]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Demo Project**
If applicable, add demo project.

### Versions
**Xcode:** x.x
**Mac OS:** xx.xx.x
**Simulator/Device:** xx.x
**Simulator/Device Name:** iPhone xx
**Library Version:** x.x.x

**Additional context**

**Comment by hackiftekhar** [comment]
@SongJasper you are trying to make things more complex :). This issue has already been fixed with a standard approach. Technically now the deepResponderViews will not return UIFieldEditor anymore.
