### ISSUE TITLE
complete UI freezes as textfields are tapped in iOS 13.1, devices > iPhone 8Plus 

### ISSUE THREAD

**Issue by Zaheer2** [hackiftekhar/IQKeyboardManager#1638]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Demo Project**
If applicable, add demo project.

### Versions
**Xcode:** x.x
**Mac OS:** xx.xx.x
**Simulator/Device:** xx.x
**Simulator/Device Name:** iPhone xx
**Library Version:** x.x.x

**Additional context**

**Comment by hackiftekhar** [comment]
Please refer to this message, it has the solution. https://github.com/hackiftekhar/IQKeyboardManager/issues/1600#issuecomment-534094279
