### ISSUE TITLE
constraint error in ios  13

### ISSUE THREAD

**Issue by MansoorJafari9** [hackiftekhar/IQKeyboardManager#1639]
Hello 
after opening keyboard give me this warning in xcode output

(
    "<NSAutoresizingMaskLayoutConstraint:0x28189b840 h=--& v=--& _UIToolbarContentView:0x10360eaf0.width == 0   (active)>",
    "<NSLayoutConstraint:0x281866b20 H:|-(0)-[_UIButtonBarStackView:0x10360f130]   (active, names: '|':_UIToolbarContentView:0x10360eaf0 )>",
    "<NSLayoutConstraint:0x2818644b0 _UIButtonBarStackView:0x10360f130.trailing == _UIToolbarContentView:0x10360eaf0.trailing   (active)>",
    "<NSLayoutConstraint:0x281881040 'IB_Leading_Leading' H:|-(0)-[_UIModernBarButton:0x1035aa1f0]   (active, names: '|':_UIButtonBarButton:0x1035aa020 )>",
    "<NSLayoutConstraint:0x281881090 'IB_Trailing_Trailing' H:[_UIModernBarButton:0x1035aa1f0]-(>=8)-|   (active, names: '|':_UIButtonBarButton:0x1035aa020 )>",
    "<NSLayoutConstraint:0x28189ac10 'UISV-canvas-connection' UILayoutGuide:0x28021d180'UIViewLayoutMarginsGuide'.leading == _UIButtonBarButton:0x1035aa020.leading   (active)>",
    "<NSLayoutConstraint:0x28189ac60 'UISV-canvas-connection' UILayoutGuide:0x28021d180'UIViewLayoutMarginsGuide'.trailing == _UIButtonBarButton:0x1035ab430.trailing   (active)>",
    "<NSLayoutConstraint:0x28189acb0 'UISV-spacing' H:[_UIButtonBarButton:0x1035aa020]-(0)-[UIView:0x1035aa7b0]   (active)>",
    "<NSLayoutConstraint:0x28189ad00 'UISV-spacing' H:[UIView:0x1035aa7b0]-(0)-[_UIButtonBarButton:0x1035aa910]   (active)>",
    "<NSLayoutConstraint:0x28189ad50 'UISV-spacing' H:[_UIButtonBarButton:0x1035aa910]-(0)-[UIView:0x1035ab170]   (active)>",
    "<NSLayoutConstraint:0x28189ada0 'UISV-spacing' H:[UIView:0x1035ab170]-(0)-[UIView:0x10360de60]   (active)>",
    "<NSLayoutConstraint:0x28189adf0 'UISV-spacing' H:[UIView:0x10360de60]-(0)-[UIView:0x1035ab2d0]   (active)>",
    "<NSLayoutConstraint:0x28189ae40 'UISV-spacing' H:[UIView:0x1035ab2d0]-(0)-[_UIButtonBarButton:0x1035ab430]   (active)>",
    "<NSLayoutConstraint:0x281866f80 'UIView-leftMargin-guide-constraint' H:|-(0)-[UILayoutGuide:0x28021d180'UIViewLayoutMarginsGuide'](LTR)   (active, names: '|':_UIButtonBarStackView:0x10360f130 )>",
    "<NSLayoutConstraint:0x281866c10 'UIView-rightMargin-guide-constraint' H:[UILayoutGuide:0x28021d180'UIViewLayoutMarginsGuide']-(0)-|(LTR)   (active, names: '|':_UIButtonBarStackView:0x10360f130 )>"
)

**Comment by MansoorJafari9** [comment]
??????

**Comment by lqIphone** [comment]
I also get the constraint error on ios 13  using IQKeyboardManagerSwift, I get this  constraint error when I switch one textField to another one.

**Comment by lqIphone** [comment]
How can I fix it?

**Comment by flohei** [comment]
We're seeing the same issue.

**Comment by hackiftekhar** [comment]
@flohei Have you tried with the latest version of the library? Are you using any custom accessory view with any textField?

**Comment by flohei** [comment]
> @flohei Have you tried with the latest version of the library? Are you using any custom accessory view with any textField?

Looks like it's solved with 6.5.4. Thanks!
