### ISSUE TITLE
use IQKeyboardManager ViewController ’s view overall upward

### ISSUE THREAD

**Issue by ailjiuai** [hackiftekhar/IQKeyboardManager#164]
like this:
![ios simulator screen shot 2015 2 9 5 47 12](https://cloud.githubusercontent.com/assets/8022424/6103910/af9a2a62-b083-11e4-8a00-e11670f5ce5a.png)

**Comment by hackiftekhar** [comment]
How was your actual view before using IQKeyboardManager?
