### ISSUE TITLE
6.5.2 compile errors

### ISSUE THREAD

**Issue by gilroykilroy** [hackiftekhar/IQKeyboardManager#1640]
Carthage/Checkouts/IQKeyboardManager/IQKeyboardManager/IQKeyboardManager.m:350:54: warning: weak instance variable '_textFieldView' is accessed multiple times in this method but may be unpredictably set to nil; assign to a strong variable to keep the object alive [-Warc-repeated-use-of-weak]
        UIViewController *textFieldViewController = [_textFieldView viewContainingController];
                                                     ^~~~~~~~~~~~~~
Carthage/Checkouts/IQKeyboardManager/IQKeyboardManager/IQKeyboardManager.m:355:18: note: also accessed here
            if ([_textFieldView textFieldSearchBar] != nil && [textFieldViewController isKindOfClass:[UINavigationController class]]) {
                 ^~~~~~~~~~~~~~
Carthage/Checkouts/IQKeyboardManager/IQKeyboardManager/IQKeyboardManager.m:448:18: warning: weak instance variable '_textFieldView' is accessed multiple times in this method but may be unpredictably set to nil; assign to a strong variable to keep the object alive [-Warc-repeated-use-of-weak]
            if ([_textFieldView textFieldSearchBar] != nil && [textFieldViewController isKindOfClass:[UINavigationController class]]) {
                 ^~~~~~~~~~~~~~
Carthage/Checkouts/IQKeyboardManager/IQKeyboardManager/IQKeyboardManager.m:430:29: note: also accessed here
    UIView *textFieldView = _textFieldView;
                            ^~~~~~~~~~~~~~
Carthage/Checkouts/IQKeyboardManager/IQKeyboardManager/IQKeyboardManager.m:531:50: warning: weak instance variable '_textFieldView' is accessed multiple times in this method but may be unpredictably set to nil; assign to a strong variable to keep the object alive [-Warc-repeated-use-of-weak]
    UIViewController *textFieldViewController = [_textFieldView viewContainingController];
                                                 ^~~~~~~~~~~~~~
Carthage/Checkouts/IQKeyboardManager/IQKeyboardManager/IQKeyboardManager.m:536:14: note: also accessed here
        if ([_textFieldView textFieldSearchBar] != nil && [textFieldViewController isKindOfClass:[UINavigationController class]]) {
             ^~~~~~~~~~~~~~
Carthage/Checkouts/IQKeyboardManager/IQKeyboardManager/IQKeyboardManager.m:1125:39: warning: weak property 'textFieldView' is accessed multiple times in this method but may be unpredictably set to nil; assign to a strong variable to keep the object alive [-Warc-repeated-use-of-weak]
                CGFloat bottomInset = self.textFieldView.frame.size.height-textViewHeight;
                                      ^~~~~~~~~~~~~~~~~~
Carthage/Checkouts/IQKeyboardManager/IQKeyboardManager/IQKeyboardManager.m:1128:36: note: also accessed here
                    bottomInset -= self.textFieldView.safeAreaInsets.bottom;
                                   ^~~~~~~~~~~~~~~~~~
Carthage/Checkouts/IQKeyboardManager/IQKeyboardManager/IQKeyboardManager.m:1711:10: warning: weak instance variable '_textFieldView' is accessed multiple times in this method but may be unpredictably set to nil; assign to a strong variable to keep the object alive [-Warc-repeated-use-of-weak]
        [_textFieldView respondsToSelector:@selector(isEditable)] && [_textFieldView isKindOfClass:[UIScrollView class]])
         ^~~~~~~~~~~~~~
Carthage/Checkouts/IQKeyboardManager/IQKeyboardManager/IQKeyboardManager.m:1711:71: note: also accessed here
        [_textFieldView respondsToSelector:@selector(isEditable)] && [_textFieldView isKindOfClass:[UIScrollView class]])
                                                                      ^~~~~~~~~~~~~~
Carthage/Checkouts/IQKeyboardManager/IQKeyboardManager/IQKeyboardManager.m:1713:49: note: also accessed here
        UIScrollView *textView = (UIScrollView*)_textFieldView;
                                                ^~~~~~~~~~~~~~
Carthage/Checkouts/IQKeyboardManager/IQKeyboardManager/IQKeyboardManager.m:2009:32: error: property 'accessibilityLabel' not found on object of type 'IQBarButtonItemConfiguration *'
            rightConfiguration.accessibilityLabel = _toolbarDoneBarButtonItemAccessibilityLabel ? : @"Done";
                               ^
Carthage/Checkouts/IQKeyboardManager/IQKeyboardManager/IQKeyboardManager.m:2037:35: error: property 'accessibilityLabel' not found on object of type 'IQBarButtonItemConfiguration *'
                prevConfiguration.accessibilityLabel = _toolbarPreviousBarButtonItemAccessibilityLabel ? : @"Previous";
                                  ^
Carthage/Checkouts/IQKeyboardManager/IQKeyboardManager/IQKeyboardManager.m:2055:35: error: property 'accessibilityLabel' not found on object of type 'IQBarButtonItemConfiguration *'
                nextConfiguration.accessibilityLabel = _toolbarNextBarButtonItemAccessibilityLabel ? : @"Next";
                                  ^
5 warnings and 3 errors generated.

**Comment by hallelujahbaby** [comment]
same issue here, cannot build with carthage

**Comment by hackiftekhar** [comment]
Released 6.5.3 with the fixes.
