### ISSUE TITLE
Cannot upload to AppStore / Testflight - BundleShortVersionString is missing

### ISSUE THREAD

**Issue by pertau** [hackiftekhar/IQKeyboardManager#1642]
### Versions
**Xcode:** 11.1
**Mac OS:** 10.14.6
**Library Version:** v6.5.0

**Comment by ChristianDeckert** [comment]
+1

**Comment by hackiftekhar** [comment]
Can someone share screenshot of error?

**Comment by marisalaneous** [comment]
ERROR ITMS-90057: "The bundle 'Payload/~/Frameworks/IQKeyboardManagerSwift.framework' is missing plist key. The Info.plist file is missing the required key: CFBundleShortVersionString. Please find more information about CFBundleShortVersionString at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleshortversionstring"

**Comment by hackiftekhar** [comment]
Have you installed library using carthage or CocoaPods?

**Comment by pertau** [comment]
Carthage

**Comment by hackiftekhar** [comment]
I checked the info.plist files in our library but noticed that the CFBundleShortVersionString key is present in info.plist file. The same kind of issue also appeared in the past with Apple. Here is the link:-
https://stackoverflow.com/questions/33271789/various-itms-errors-when-trying-to-submit-archive-to-app-store

**WORKAROUND:** For a workaround, please modify the IQKeyboardManagerSwift.framework/Info.plist file manually prior to upload.

**Comment by AlexanderPan** [comment]
Carthage +1

**Comment by sebastian989** [comment]
Any update about this issue?

**Comment by hackiftekhar** [comment]
Please check my comment of 1 November for the workaround.

**Comment by sebastian989** [comment]
@hackiftekhar thanks for answering, you are right, adding the CFBundleShortVersionString key to the .plist solves the issue... the problem that I'm having is in my CI environment when I use the library with Carthage. Thanks in advance.

**Comment by akashnimare** [comment]
@hackiftekhar great project. I'm still getting this error. Is there any plan to fix this?

**Comment by akashnimare** [comment]
> adding the CFBundleShortVersionString key to the .plist solves the issue

@sebastian989 this we need to add after running the build and manually going to the /IQKeyboardManagerSwift.framework/Info.plist, right?

**Comment by sebastian989** [comment]
@akashnimare that's right, but finally I decided to use it with CocoaPods
