### ISSUE TITLE
ITMS-90809: Deprecated API Usage (UIWebView) error from apple

### ISSUE THREAD

**Issue by LBJPilot** [hackiftekhar/IQKeyboardManager#1643]
**Describe the bug**
I am getting the following error message from apple when submitting my app to the app store:
ITMS-90809: Deprecated API Usage

I believe apple is scanning the code for the string: UIWebView

I dont believe I saw the use of the UIWebView in your code, but the string does appear in comments, so I believe that is still causing the error.

Would it be possible to change your comments to something like "UI_WebView" or WebView to remove that string totally from your code. This I hope will correct the issue.

I do not see any other references to "UIWebView" in my code or any other libraries being used so believe your code is the reason for the ALERT/WARNING from apple.

**To Reproduce**
- Submit any application that uses your Code to the App Store

**Expected behavior**
No Errors should be returned about your application using a deprecated API

**Screenshots**
Not Needed

**Demo Project**
If applicable, add demo project.

### Versions
**Xcode:** 10.1
**Mac OS:** xx.xx.x
**Simulator/Device:** xx.x
**Simulator/Device Name:** iPhone xx
**Library Version:** 6.4.1

**Additional context**

**Comment by hackiftekhar** [comment]
I have already removed that string from the comments and released the new versions. Please update the library version.

**Comment by LBJPilot** [comment]
I looked through and did not see a reference in the versions that you did that. I guess i missed it. Thanks. Will get latest
