### ISSUE TITLE
Textfield inside UIAlertController

### ISSUE THREAD

**Issue by lcfrateschi** [hackiftekhar/IQKeyboardManager#1644]
Sorry I'm new to swift, but its component works perfectly in my app, when I try to use it in a texfield inside a uialertcontroler the keyboard always goes over the textfield and your component options don't appear ... could you help me? sorry for bad english.

Thanks

**Comment by hackiftekhar** [comment]
Hi @Icfrateschi, this is expected behaviour. The library explicitly disabled the library for UIAlertController to prevent undesired behaviour.
