### ISSUE TITLE
Wrapped up Hoshi text field not showing siblings

### ISSUE THREAD

**Issue by vineethvijayan** [hackiftekhar/IQKeyboardManager#1645]
Hi, I have wrapped up the Hoshi Text field in a UIView and made a custom text view. It has some icons, separators, etc.

Now the toolbar doesn't show up and down arrow to find next keyboard anyway to fix it?

**Comment by hackiftekhar** [comment]
Please put all of those View in a containerView and make it kind of `IQPreviousNextView`.
