### ISSUE TITLE
ios 13报错 ，CoreUI: RunTimeThemeRefForBundleIdentifierAndName() couldn't find Assets.car in bundle with identifier: '(null)'

### ISSUE THREAD

**Issue by swesome** [hackiftekhar/IQKeyboardManager#1646]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Demo Project**
If applicable, add demo project.

### Versions
**Xcode:** x.x
**Mac OS:** xx.xx.x
**Simulator/Device:** xx.x
**Simulator/Device Name:** iPhone xx
**Library Version:** x.x.x

**Additional context**

**Comment by RiberWang** [comment]
Me too.

**Comment by littleSun** [comment]
Me too.
