### ISSUE TITLE
toolbar run to the top.

### ISSUE THREAD

**Issue by W429** [hackiftekhar/IQKeyboardManager#1647]
iOS 13, click the keychain on the login page, and iqkeyboard's toolbar runs to the top.

**Comment by hackiftekhar** [comment]
@W429, can you please refer to which keychain and login page you are referring to?

**Comment by W429** [comment]
![WechatIMG175](https://user-images.githubusercontent.com/15991494/68836311-02af0480-06f5-11ea-8a52-8f5ecfdb2f7c.jpeg)
After clicking the keychain，toobar toolbar run to the top.

**Comment by hackiftekhar** [comment]
Please also share 2nd screenshot of the issue, however, to let you know this issue may be hard to fix since it's directly not related to the library but related to the Apple implementation.

**Comment by W429** [comment]
![WechatIMG178](https://user-images.githubusercontent.com/15991494/68911198-2030ac80-078f-11ea-8299-0cf988f06c69.jpeg)
Hello, iOS13, after clicking on the keychain, toolbar will run to the top.

**Comment by hackiftekhar** [comment]
okay, thanks for the screenshot, I'll try to reproduce the issue and find if there are any workarounds.

**Comment by Monkeyzc** [comment]
+1

**Comment by god-long** [comment]
+1,  
On the login page, use the account password. When you click to log in, the Apple system will pop up the actionSheet to save the password. Click Cancel, and the toolBar will be displayed at the top of the screen (below the status bar).

**Comment by god-long** [comment]
I found that must use xcode11 to reproduction the issue. xcode10 is not error.

**Comment by 0x1306a94** [comment]
@god-long 感觉是工程里哪有问题, 因为IQKeyboardManager 里的示例程序在 Xcode 11 运行并没出现这个问题, 只是一直没找到 是什么导致的

**Comment by god-long** [comment]
> @god-long 感觉是工程里哪有问题, 因为IQKeyboardManager 里的示例程序在 Xcode 11 运行并没出现这个问题, 只是一直没找到 是什么导致的

弹出苹果系统的保存账号和密码actionSheet了吗？ 或者点钥匙串弹出已保存的账号密码actionSheet。然后toolbar就错乱了

**Comment by 0x1306a94** [comment]
@god-long 我知道 我的意思是 可能是自己的项目里面哪里导致的，因为示例程序是正常的

**Comment by god-long** [comment]
@0x1306a94  貌似真的如此，我新建个工程，模拟完全没问题。但是老工程就是不行，这个工程项目是2014年创建的，但是还是无法定位问题在哪里。。。也有可能是xCode的兼容问题，在xcode10.x上没问题。

**Comment by MichaelYNWA** [comment]
> @0x1306a94 貌似真的如此，我新建个工程，模拟完全没问题。但是老工程就是不行，这个工程项目是2014年创建的，但是还是无法定位问题在哪里。。。也有可能是xCode的兼容问题，在xcode10.x上没问题。

+1，请问有什么好的解决方式吗？

**Comment by Monkeyzc** [comment]
Now I remove auto fill in my project.

```
if (@available(iOS 12.0, *)) {
    v.textField.textContentType = UITextContentTypeOneTimeCode;
} else if (@available(iOS 10.0, *)) {
  v.textField.textContentType = @"";
}

```

**Comment by mzying2013** [comment]
+ 1， 同样的问题。如何解决？

**Comment by mzying2013** [comment]
我找到我项目的问题了，为了兼容 iOS 13。我设置  modalPresentationStyle  = UIModalPresentationFullScreen。导致 keychain 的密码弹框 UIKeyboardHiddenViewController_Autofill 也设置为  UIModalPresentationFullScreen。加上 `[viewControllerToPresent isKindOfClass:[UINavigationController class]]` 判断就好了。

**Comment by 0x1306a94** [comment]
@mzying2013 原来如此 我也是hook了那个

**Comment by god-long** [comment]
@mzying2013  就是这个原因 👍

**Comment by W429** [comment]
> 我找到我项目的问题了，为了兼容 iOS 13。我设置 hook UIViewController 并且 modalPresentationStyle = UIModalPresentationFullScreen。导致 keychain 的密码弹框 UIKeyboardHiddenViewController_Autofill 也设置为 UIModalPresentationFullScreen。加上 `[viewControllerToPresent isKindOfClass:[UINavigationController class]]` 判断就好了。

是这里的问题，修改后好了。

**Comment by ankit0812** [comment]
Any resolutions for this?

**Comment by hackiftekhar** [comment]
Actually, there is no solution because we didn't get much callback about the changes.
