### ISSUE TITLE
Crash in iOS10.3.1

### ISSUE THREAD

**Issue by cs571393** [hackiftekhar/IQKeyboardManager#1648]
error log：
Terminating app due to uncaught exception 'NSInvalidUnarchiveOperationException', reason: 'Could not instantiate class named _UITextLayoutView'

### Versions
**Xcode:** 11.2
**Mac OS:** 10.15.1
**Simulator/Device:** Simulator
**Simulator/Device Name:** iPhone 6 plus
**Library Version:** 6.5.3

**Comment by cs571393** [comment]
I use IQKeyboardManager Swift Demo

**Comment by Sk8er22** [comment]
how you solve it?

**Comment by cs571393** [comment]
It's xcode11.2 bug。

**Comment by cs571393** [comment]
@Sk8er22  It's xcode11.2 bug。

**Comment by hackiftekhar** [comment]
Mistakenly refer #1648 instead of #1646

**Comment by hackiftekhar** [comment]
anyway closing it since @Sk8er22 refer that it's Xcode 11.2 bug and we aren't accessing any private variable named _UITextLayoutView.
