### ISSUE TITLE
Tap textField in grouped tableView in iOS 13 modal causes cell clipped

### ISSUE THREAD

**Issue by MainasuK** [hackiftekhar/IQKeyboardManager#1649]
**Describe the bug**
When using the grouped table view in iOS 13 modal. The textField will move above little and the cell get clipped.

**To Reproduce**
1. Present grouped tableView as modal
2. Click first text field cell
3. See error

**Expected behavior**
Not auto-scroll at first cell.

**Screenshots**
![2019-11-0615 25 47](https://user-images.githubusercontent.com/7940186/68277226-b6871300-00a9-11ea-8ba9-9b4e8ca3f4b0.png)

### Versions
**Xcode:** Version 11.2 (11B52)
**Mac OS:** 10.15.1 (19B88)
**Simulator/Device:** iOS 13.2
**Simulator/Device Name:** iPhone 11
**Library Version:** 6.5.2

**Comment by mukeshydv** [comment]
I'm also getting this issue, did you find any solution?

**Comment by MainasuK** [comment]
Still not. I do not want to use glue code to fix all that case.

**Comment by hackiftekhar** [comment]
@MainasuK @mukeshydv Are you using a subclass of `UITableViewController` or a subclass of `UIViewController embedding a UITableView`?

**Comment by MainasuK** [comment]
I use the embedding `UITableView` in `UIViewController`. And layout it in `viewDidLoad(_:)` like that:

```swift
        tableView.translatesAutoresizingMaskIntoConstraints = false
        view.addSubview(tableView)
        NSLayoutConstraint.activate([
            tableView.topAnchor.constraint(equalTo: view.topAnchor),
            tableView.leadingAnchor.constraint(equalTo: view.leadingAnchor),
            tableView.trailingAnchor.constraint(equalTo: view.trailingAnchor),
            tableView.bottomAnchor.constraint(equalTo: view.bottomAnchor),
        ])
```

**Comment by piercifani** [comment]
Same here, even without UITableView

**Comment by akshitzaveri** [comment]
Same issue here

**Comment by yugochen** [comment]
I'm also getting this issue, did you find any solution?

**Comment by CCAlek** [comment]
I'm also getting this issue, did you find any solution?

**Comment by CCAlek** [comment]
Maybe someone was already able to cope with this problem?

**Comment by CCAlek** [comment]
I used collectionView instead of tableView and it helped me
