### ISSUE TITLE
use IQKeyboardManager ViewController ’s view overall upward

### ISSUE THREAD

**Issue by ailjiuai** [hackiftekhar/IQKeyboardManager#165]
like this:
![ios simulator screen shot 2015 2 9 5 47 12](https://cloud.githubusercontent.com/assets/8022424/6103910/af9a2a62-b083-11e4-8a00-e11670f5ce5a.png)
![ios simulator screen shot 2015 2 9 5 47 24](https://cloud.githubusercontent.com/assets/8022424/6103950/f30d427a-b083-11e4-8a43-33f1d401c215.png)

**Comment by ailjiuai** [comment]
do not use IQkeyboardManager
![ios simulator screen shot 2015 2 9 5 51 59](https://cloud.githubusercontent.com/assets/8022424/6104010/894af048-b084-11e4-921d-2680189d4d78.png)

**Comment by hackiftekhar** [comment]
Could you please share demo project to demonstrate the issue?

**Comment by ailjiuai** [comment]
thanks.now,the function have worked  well , when  i  used this latest library.

**Comment by hackiftekhar** [comment]
I requested you to stop writing things like 'Do not use IQKeyboardManager'. It discourage me to contribute towards my open source library. Note that, in case you find any issue, I'm always here to help.

**Comment by ailjiuai** [comment]
very sorry,hack.I did it just to let you look at the effect is different.

**Comment by ailjiuai** [comment]
this library is wonderful .And thank you very much for contributing.

**Comment by hackiftekhar** [comment]
Thanks @ailjiuai. :)
