### ISSUE TITLE
Crashed at appdelegate file , version 6.5.2 

### ISSUE THREAD

**Issue by ch-muhammad-adil** [hackiftekhar/IQKeyboardManager#1650]
I have updated to version 6.5.2 from 6.5.1 and it has crashed at this line when i try to run the app at iPhone SE, i have not tried it at other simulators, just sharing what i have experienced at iPhone SE 

`IQKeyboardManager.shared.enable = true`

<img width="1280" alt="Screenshot 2019-11-07 at 12 15 17 AM" src="https://user-images.githubusercontent.com/8264639/68330053-5c5f6f80-00f4-11ea-8d86-3035a744f8e5.png">

**Comment by borneadmin** [comment]
+1

**Comment by ch-muhammad-adil** [comment]
For a time being i have downgraded it to 6.5.1. Keeping this issue open so it get fixed for later versions.

**Comment by brurend** [comment]
I have the same issue, also downgraded to 6.5.1

**Comment by hackiftekhar** [comment]
@brurend @ch-muhammad-adil thanks for sharing this with me. However, If you could tell me more about why the crash is happening then I can look into this problem.

**Comment by brurend** [comment]
As soon as the app starts to run it crashs immediately, I don't even have the chance to do any action

**Comment by animeshp** [comment]
It happens to me also on v6.5.0 and Xcode throws the following error:
`Fatal error: Call of deleted method`

**Comment by pierreWagou** [comment]
I have same issue from v6.5.2, also downgraded to 6.5.1.
Error is Thread 1: EXC_BAD_ACCESS (code=1, address=0xdd1008610) and is thrown on AppDelegate.

**Comment by XingGX** [comment]
@ch-muhammad-adil @brurend @animeshp @pierreWagou I clean project and build it work, this issue shouldn't happen.
