### ISSUE TITLE
iOS 13 memory issue and energy impact is high, app stuck when trying to open pickerview or tapping textfield and can happen randomly on screen, I am running on real device(iPhone XR 13.2) Xcode 11.2

### ISSUE THREAD

**Issue by iosdevman** [hackiftekhar/IQKeyboardManager#1652]
**BUG**
Memory issue and energy impact is high, app gets stuck when trying to open pickerview or tapping textfield and can happen randomly on screen, I am running on real device(iPhone XR 13.2) Xcode 11.2
In this screen i have used Tableview and no other customisations have been done to IQKeyboardManager, if I disable IQKeyboardManager then it will work fine

**Expected behavior**
Energy impact should be low, Memory impact should be on low levels, app should not stuck or become irresponsive

Error : Message from debugger: Terminated due to memory issue

![Screenshot 2019-11-08 at 1 28 24 PM](https://user-images.githubusercontent.com/57521187/68459681-07bf1000-022c-11ea-9f69-64ed1112d9ea.png)

**Please do not close this issue before giving any solution**

### Versions
**Xcode: 11.2
**Mac OS: 10.15.1
**Device: iPhone XR
**OS Version: iOS 13.2
**Library Version: Latest, 6.5.3

**Comment by hkjhkjdhs** [comment]
Same issue, Please check also I am using the latest version 6.5.3

**Comment by iosdevman** [comment]
hello @hackiftekhar, have you found anything?

**Comment by iosdevman** [comment]
I had some view's frame updating after layoutSubView() which caused this leak, Sorry for inconvenience..
