### ISSUE TITLE
IQTextView ios13 Crash

### ISSUE THREAD

**Issue by IIIOS** [hackiftekhar/IQKeyboardManager#1653]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Demo Project**
If applicable, add demo project.

### Versions
**Xcode:** x.x
**Mac OS:** xx.xx.x
**Simulator/Device:** xx.x
**Simulator/Device Name:** iPhone xx
**Library Version:** x.x.x

**Additional context**

**Comment by hackiftekhar** [comment]
@IIIOS Please tell more about the crash. When someone opens any issues then the clear and concise description and steps to reproduce must be provided.

**Comment by behrad-kzm** [comment]
same error
"Terminating app due to uncaught exception 'NSGenericException', reason: 'Access to UITextField's _placeholderLabel ivar is prohibited. This is an application bug'"
_placeholderLabel is only used inside IQTextView

**Comment by hackiftekhar** [comment]
Now I changed the "_placeholderLabel" name to something else. If the problem was due to this name then it should be solved in the next release.
