### ISSUE TITLE
Security For NSLog()

### ISSUE THREAD

**Issue by Kaizi-oo** [hackiftekhar/IQKeyboardManager#1654]
To some security case, logging on console with NSLog() is not allowed (Release only).  
The following code will appear every time when I update cocoa-pods .
```NSLog(@"%@",preLog);```
 in line 2434 at file "IQKeyboardManager.m", version - 6.5.3
Could you remove this at the forward version?

**Comment by hackiftekhar** [comment]
@Kaizi-oo This is written for some logging purposes and removing this will remove the logging feature which I use for debugging purposes. Can you please tell me how I can replicate the problem you are getting with NSLog?
