### ISSUE TITLE
Previous and next arrows are not showing using SPM

### ISSUE THREAD

**Issue by kittu4ios** [hackiftekhar/IQKeyboardManager#1657]
**Describe the bug**
I installed SPM version 6.5.4. Previous and next arrows are not showing on tool bar
Added below lines also. No use.
IQKeyboardManager.shared.enable = true
        IQKeyboardManager.shared.toolbarTintColor = UIColor.red
        IQKeyboardManager.shared.previousNextDisplayMode = .alwaysShow

![IMG_0310](https://user-images.githubusercontent.com/5724005/69431816-7d63c980-0d5e-11ea-9f45-8e4d76f42e64.PNG)

### Versions
**Xcode:** 11.0
**Mac OS:** 10.15
**Simulator/Device:** all devices
**Simulator/Device Name:** all devices
**Library Version:** x.x.x

**Comment by kittu4ios** [comment]
but button actions are working.

**Comment by hallelujahbaby** [comment]
Same issue but using Carthage. Buttons becomes colorless (clickable but invisible).

**Comment by kittu4ios** [comment]
looks like resources folder missing

**Comment by hallelujahbaby** [comment]
I rollback to v6.5.3 , no issue. I may just wait for a new update.

**Comment by hackiftekhar** [comment]
This is because SPM does not support assets at the moment. That's why  resources folder is missing.

**Comment by Sidetalker** [comment]
@hackiftekhar I don't believe that limitation should impact the Carthage build which has the same issue

**Comment by thesergeydavydov** [comment]
> I rollback to v6.5.3 , no issue. I may just wait for a new update.

didn't help(

**Comment by tylerjames** [comment]
I have it installed vis SPM, I see the assets in the Resources folder but I do not see the images in the toolbar.

**Comment by hackiftekhar** [comment]
The SPM does not support the assets and resources right now, we may need to modify our library to fully support SPM.

**Comment by Sidetalker** [comment]
@hackiftekhar The recent changes affect Carthage as well - images resources do not show up.

**Comment by hackiftekhar** [comment]
I'll remove the images from the resource directory and will add them as Data within the project. This will be available soon.
