### ISSUE TITLE
Issue in xcode 11.2.1

### ISSUE THREAD

**Issue by AhmadDurrani579** [hackiftekhar/IQKeyboardManager#1658]
I have face this issue in xcode 11.2.1 i have the IQkeyboard dependencies when we add this in appdelete         IQKeyboardManager.shared.enable = true
 Then got this error(type metadata accessor for IQKeyboardManagerSwift.IQKeyboardManager", referenced from:) the app not running

**Comment by philippeauriach** [comment]
having the same problem here, did you find any workaround or some place in the lib code where it could come from ?

**Comment by AhmadDurrani579** [comment]
@philippeauriach  i have face this issue when i have add the library in packages framework then this issue will generate but didnt get the answer yet so i ma revert back to cocoapods yet

**Comment by philippeauriach** [comment]
I had this issue with cocoapods. It is fixed on my side by changing how the singleton is instanciated, but it is kind of weird. Made a fork: https://github.com/philippeauriach/IQKeyboardManager/tree/philippeauriach-patch-1
