### ISSUE TITLE
Tool Bar disappears (Big issue) Keyboard not removed from screen

### ISSUE THREAD

**Issue by naeemAkee** [hackiftekhar/IQKeyboardManager#1661]
Hello Respected, I'm using IQ Keyboard manager. And I'm using just 3 things.

        IQKeyboardManager.shared.enable = true
        IQKeyboardManager.shared.enableAutoToolbar = true
        IQKeyboardManager.shared.shouldResignOnTouchOutside = true

But sometimes it didn't goes out of screen and will create a lot of problems. 

Sir we are using it, and during testing it was done a lot of times in iPhone X, iPhone 8, And If same thing will happens again and again then it will be very irritating and sucks our mind. 

Please fix that issue.

![image_2019_12_02T06_07_42_614Z](https://user-images.githubusercontent.com/43524143/69954825-10022680-151e-11ea-92a6-81c4a3d3b9bc.png)

**Comment by hackiftekhar** [comment]
Can you please confirm that you have not added any other UIView as inputAccessoryView? Can you please share a demo project sir?

**Comment by naeemAkee** [comment]
Error Fixed By just updating pod to 

` pod 'IQKeyboardManagerSwift', '6.5.0'`

I Love it <3. Thank you for your response.
