### ISSUE TITLE
Setting enable to NO can not work for input of WebView

### ISSUE THREAD

**Issue by sdutlyb** [hackiftekhar/IQKeyboardManager#1662]
**Describe the bug**
Setting enable to NO can not work for input of WebView, but native UI and react-native UI is OK.

**To Reproduce**
1. import and enable IQKeyboardManager
2. some page disable IQKeyboardManager via:
    `
     [IQKeyboardManager sharedManager].enable = NO;
    [IQKeyboardManager sharedManager].enableAutoToolbar = NO;
`
or only one line code:
`
    [IQKeyboardManager sharedManager].enableAutoToolbar = NO;
`
3. the input UI in webView still appear with AutoToolbar,  but it worked to native UI.

### Versions
**Xcode:** 11.2.1
**Mac OS:** 10.15.1
**Simulator/Device:** all
**Simulator/Device Name:** iphone X (maybe all devices)
**Library Version:** 6.5.4

**Comment by hackiftekhar** [comment]
The input UI in WebView is not from the library, it's from the iOS WKWebView/UIWebView itself. We do not have any controls over there since the text fields on WebView is not the native iOS UITextField/UITextView.
