### ISSUE TITLE
Choose which view to be move up when keyboard appears

### ISSUE THREAD

**Issue by haihoang88** [hackiftekhar/IQKeyboardManager#1663]
Currently, I have a view structure as follow
UITabBarController -> UIViewController -> UITextField.

I noticed that, when keyboard appears, it pushes  the whole UITabBarController up.
Is there any way I can just push the UIViewController up and leave the UITabBarController alone?

**Comment by hackiftekhar** [comment]
The library pushed the UIViewController instead of UITabBarController. You might be using an older version of the library. Please upgrade to the latest
