### ISSUE TITLE
6.5.4 crashes on launch EXC_BAD_ACCESS 

### ISSUE THREAD

**Issue by ojseven** [hackiftekhar/IQKeyboardManager#1664]
<img width="401" alt="Screen Shot 2019-12-02 at 4 29 33 PM" src="https://user-images.githubusercontent.com/5886323/70003648-0f1ec400-1521-11ea-9ffa-44e968f1ce34.png">
<img width="924" alt="Screen Shot 2019-12-02 at 4 29 17 PM" src="https://user-images.githubusercontent.com/5886323/70003650-104ff100-1521-11ea-8442-9d81a2c4a35e.png">

App crashes on launch.

iPhone 11 pro

<img width="528" alt="Screen Shot 2019-12-02 at 4 31 06 PM" src="https://user-images.githubusercontent.com/5886323/70003685-252c8480-1521-11ea-89b5-3f6b6fc3ec0a.png">

Downgrading to 
https://github.com/hackiftekhar/IQKeyboardManager/tree/v6.4.2
Resolves the issue

**Comment by Isuru-Nanayakkara** [comment]
Encountered the same issue

**Comment by fredpi** [comment]
I experienced the same issue with a CI running Xcode 10.3 where the tests (run on an iPhone 8) all failed because of IQKeyboardManager crashing right away. Downgrading to 6.4.2 fixed it...

**Comment by hackiftekhar** [comment]
Please clean the project and run again.
