### ISSUE TITLE
IOS 13 Warnings

### ISSUE THREAD

**Issue by mattmillen888** [hackiftekhar/IQKeyboardManager#1665]
Im getting Warnings in Xcode 11.2.1 IOS 13, how can i get rid of them?

if let originalKeyWindow = UIApplication.shared.keyWindow,
    (Static.keyWindow == nil || Static.keyWindow != originalKeyWindow) {
    Static.keyWindow = originalKeyWindow
}

Warning I get:
'keyWindow' was deprecated in iOS 13.0: Should not be used for applications that support multiple scenes as it returns a key window across all connected scenes

let statusBarUserInfoKey    = UIApplication.statusBarOrientationUserInfoKey

Warning I get:
'statusBarOrientationUserInfoKey' was deprecated in iOS 13.0: Use viewWillTransitionToSize:withTransitionCoordinator: instead.

let UIApplicationWillChangeStatusBarOrientation = UIApplication.willChangeStatusBarOrientationNotification

Warning I get:
'willChangeStatusBarOrientationNotification' was deprecated in iOS 13.0: Use viewWillTransitionToSize:withTransitionCoordinator: instead.

will this be updated?

**Comment by hackiftekhar** [comment]
I fixed the keyWindow related warnings. But we cannot adopt viewWillTransitionToSize:withTransitionCoordinator: since we really do not have any UIView in our control.

**Comment by mattmillen888** [comment]
Thankyou

**Comment by Khondwani** [comment]
> Thankyou
Did you by any chance get to fixing it your end @mattmillen888 ?? If you do not mind me asking

**Comment by mattmillen888** [comment]
> > Thankyou
> > Did you by any chance get to fixing it your end @mattmillen888 ?? If you do not mind me asking

Yes we just removed it reinstalled and recompiled then it works fine.
