### ISSUE TITLE
Click on the textview crash in ios 13.

### ISSUE THREAD

**Issue by LALALA552** [hackiftekhar/IQKeyboardManager#1666]
![image](https://user-images.githubusercontent.com/13042116/70210674-3a4a2300-176e-11ea-972a-3a698a1589b9.png)

![image](https://user-images.githubusercontent.com/13042116/70210707-5057e380-176e-11ea-93ff-e4785335b7dc.png)
![image](https://user-images.githubusercontent.com/13042116/70210727-62d21d00-176e-11ea-80ed-6f8924a4dc6c.png)

**Comment by LALALA552** [comment]
Objective_C

**Comment by LALALA552** [comment]
Other thing ，cocoapod  can’t search  IQKeyboardManager  6.5.4 version （Objective_C）。

**Comment by hackiftekhar** [comment]
Can you please check if your project has `UITextView+Placeholder.m` file? That might be the reason.
