### ISSUE TITLE
Crashed when keyboard appear

### ISSUE THREAD

**Issue by q195945056** [hackiftekhar/IQKeyboardManager#1668]
Every time I tap a textfield or textView, when the keyboard appear, my app will crashed 
The code all I wrote is 
IQKeyboardManager.shared.enable = true

### Versions
**Xcode:** 11.2.1 (11B500)
**Mac OS:** 10.15.1 (19B88)
**Simulator/Device:** 13.3.3
**Simulator/Device Name:** iPhone 7 Plus
**Library Version:** 6.5.4

**Additional context**
Thread 1 Queue : com.apple.main-thread (serial)
#0	0x000000019bbe1f6c in objc_exception_throw ()
#1	0x000000019bdbbc4c in +[NSException raise:format:arguments:] ()
#2	0x000000019c2400d4 in -[NSAssertionHandler handleFailureInFunction:file:lineNumber:description:] ()
#3	0x000000019fb36364 in PushNextClassForSettingIMP ()
#4	0x000000019fb3e19c in __workaround10030904InvokeWithTarget_block_invoke ()
#5	0x00000001a0385588 in +[UIView _performSystemAppearanceModifications:] ()
#6	0x000000019fb38dd8 in applyInvocationsToTarget ()
#7	0x000000019fb38304 in +[_UIAppearance _applyInvocationsTo:window:matchingSelector:onlySystemInvocations:] ()
#8	0x00000001a03af1b0 in __88-[UIView(Internal) _performUpdatesForPossibleChangesOfIdiom:orScreen:traverseHierarchy:]_block_invoke ()
#9	0x00000001a03af124 in -[UIView(Internal) _performUpdatesForPossibleChangesOfIdiom:orScreen:traverseHierarchy:] ()
#10	0x00000001a03af038 in -[UIView(Internal) _didChangeFromIdiomOnScreen:traverseHierarchy:] ()
#11	0x00000001a03ae444 in -[UIView(Internal) _didMoveFromWindow:toWindow:] ()
#12	0x00000001a03ae1bc in -[UIView(Internal) _didMoveFromWindow:toWindow:] ()
#13	0x000000019f6d6ba8 in -[UIToolbar _didMoveFromWindow:toWindow:] ()
#14	0x00000001a03a2568 in __45-[UIView(Hierarchy) _postMovedFromSuperview:]_block_invoke ()
#15	0x000000019c19109c in -[NSISEngine withBehaviors:performModifications:] ()
#16	0x00000001a03a246c in -[UIView(Hierarchy) _postMovedFromSuperview:] ()
#17	0x00000001a03b0d58 in -[UIView(Internal) _addSubview:positioned:relativeTo:] ()
#18	0x000000019fd17d68 in -[UIInputWindowController changeToInputViewSet:] ()
#19	0x000000019fd1878c in __43-[UIInputWindowController setInputViewSet:]_block_invoke ()
#20	0x00000001a03aa09c in +[UIView(Animation) performWithoutAnimation:] ()
#21	0x000000019fd184c4 in -[UIInputWindowController setInputViewSet:] ()
#22	0x000000019fd12d84 in -[UIInputWindowController performOperations:withAnimationStyle:] ()
#23	0x000000019fa40d84 in -[UIInputResponderController setKeyWindowSceneInputViews:animationStyle:] ()
#24	0x000000019fa404f4 in -[UIInputResponderController setInputViews:animationStyle:] ()
#25	0x000000019fa415c8 in -[UIInputResponderController setInputViews:animated:] ()
#26	0x000000019fa41630 in -[UIInputResponderController setInputViews:] ()
#27	0x000000019fa3f298 in -[UIInputResponderController _reloadInputViewsForKeyWindowSceneResponder:] ()
#28	0x000000019fa3e644 in -[UIInputResponderController _reloadInputViewsForResponder:] ()
#29	0x000000019ff54468 in -[UIResponder(UIResponderInputViewAdditions) reloadInputViews] ()
#30	0x000000019ff4f700 in -[UIResponder becomeFirstResponder] ()
#31	0x00000001a03a204c in -[UIView(Hierarchy) becomeFirstResponder] ()
#32	0x00000001a01e3488 in -[UITextField becomeFirstResponder] ()
#33	0x00000001a0198ae0 in -[UITextInteractionAssistant(UITextInteractionAssistant_Internal) setFirstResponderIfNecessaryActivatingSelection:] ()
#34	0x00000001a0184048 in -[UITextSelectionInteraction oneFingerTap:] ()
#35	0x000000019fb118bc in -[UIGestureRecognizerTarget _sendActionWithGestureRecognizer:] ()
#36	0x000000019fb19e5c in _UIGestureRecognizerSendTargetActions ()
#37	0x000000019fb175f0 in _UIGestureRecognizerSendActions ()
#38	0x000000019fb16b50 in -[UIGestureRecognizer _updateGestureForActiveEvents] ()
#39	0x000000019fb0ac24 in _UIGestureEnvironmentUpdate ()
#40	0x000000019fb0a39c in -[UIGestureEnvironment _deliverEvent:toGestureRecognizers:usingBlock:] ()
#41	0x000000019fb0a160 in -[UIGestureEnvironment _updateForEvent:window:] ()
#42	0x000000019ff5e5ac in -[UIWindow sendEvent:] ()
#43	0x000000019ff3ab78 in -[UIApplication sendEvent:] ()
#44	0x000000019ffb2ef8 in __dispatchPreprocessedEventFromEventQueue ()
#45	0x000000019ffb5454 in __handleEventQueueInternal ()
#46	0x000000019ffae2c8 in __handleHIDEventFetcherDrain ()
#47	0x000000019be377c4 in __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ ()
#48	0x000000019be3771c in __CFRunLoopDoSource0 ()
#49	0x000000019be36eb4 in __CFRunLoopDoSources0 ()
#50	0x000000019be32000 in __CFRunLoopRun ()
#51	0x000000019be318a0 in CFRunLoopRunSpecific ()
#52	0x00000001a5d89328 in GSEventRunModal ()
#53	0x000000019ff22740 in UIApplicationMain ()
#54	0x00000001049eb3d0 in main at /Users/yanmingjun/Documents/Github/ShareEducation/ShareEducation/AppDelegate.swift:20
#55	0x000000019bcbc360 in start ()

**Comment by q195945056** [comment]
![image](https://user-images.githubusercontent.com/4394486/70408885-bac99600-1a84-11ea-969a-37e6069fddde.png)

**Comment by hackiftekhar** [comment]
Hi @q195945056 I do not see any IQKeybaordManager library calls in the stack. I'm not sure if it's due to the IQKeyboardManager library.
