### ISSUE TITLE
TableView slides up when keybaord pops, as attached in the picture

### ISSUE THREAD

**Issue by ravitumu** [hackiftekhar/IQKeyboardManager#1669]
[**Describe]([url](url
![sdfgh](https://user-images.githubusercontent.com/43835148/70453753-4b00de80-1a77-11ea-9998-842f53d4ae31.jpg)
)) the bug**

This is a chat application where I was expecting the tableview top constraint stays obeyed while the lower constraint slides up dragging the textview and button along with the keyboard.

while the latter is happening as expected, that is, textview is sliding up, last text cell also slides up along with the keyboard, but he former part where the top end of the table view is not pinned to the bottom of the navigation tab. it is acting as if the entire view is shifting upwards by the length of the keyboard, and I am not able to scroll all the way to the first text when the keyboard is up as the entire view is shifted up.

**To Reproduce**

**Expected behavior**
I expect the top of the table view is pinned to the bottom of the navigation bar, ideally, I think when the keyboard is up, the height of the table view should shrink by the length of the keyboard.

also, I think this used to be one of the solutions but no longer exists "toplayoutguide"

**Screenshots**

**Demo Project**
If applicable, add demo project.

### Versions
**Xcode:** 11.2
**Mac OS:** Catalina
**Simulator/Device:** ios 13.2
**Simulator/Device Name:** iPhone Xs
**Library Version:** 6.5.4, Swift Packages

**Additional context**

**Comment by hackiftekhar** [comment]
The expected behaviour is correct.However the chat kind of screen is a little bit special. It's having a TableView in the mainView and a textField/textView in the mainView also.
