### ISSUE TITLE
Couldn't be able to Add new button in QKeyboard manager toolbar

### ISSUE THREAD

**Issue by Ahil-NS** [hackiftekhar/IQKeyboardManager#1671]
I Could be able to add a Clear Button of left side of done button in IQKeyboard manager toolbar.
Is there any way to add new button iQKeyboardManager toolbar.
Please help

<img width="400" alt="Screenshot 2019-12-11 at 11 58 12 AM" src="https://user-images.githubusercontent.com/20102675/70590401-8b926080-1c0d-11ea-8099-10abcaa7d450.png">

**Comment by hackiftekhar** [comment]
I don't think there is a way right now, but I'll make some modifications to support this kind of thing.

**Comment by nicolopadovan** [comment]
@dgyiOS doesn't seem like it yet. Hopefully this gets implemented soon

**Comment by i-tengfei** [comment]
Any update?

**Comment by hackiftekhar** [comment]
I tried it one time, but haven't had success. But that would be supercool if I'm able to provide such property like items.
