### ISSUE TITLE
First Responder error

### ISSUE THREAD

**Issue by zengjinzong** [hackiftekhar/IQKeyboardManager#1672]
[**Describe](url
<img width="976" alt="屏幕快照 2019-12-11 下午8 24 27" src="https://user-images.githubusercontent.com/13520124/70621533-cbc90180-1c54-11ea-83fc-0aea46b85d3a.png">
) the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Demo Project**
If applicable, add demo project.

### Versions
**Xcode:** x.x
**Mac OS:** xx.xx.x
**Simulator/Device:** xx.x
**Simulator/Device Name:** iPhone xx
**Library Version:** x.x.x

**Additional context**

**Comment by hackiftekhar** [comment]
By looking at the logs, I can see that all of the mentioned class names belong to Apple Internal classes. The constraint warnings are related to Apple and I hope they may fix it soon.
