### ISSUE TITLE
in scrollview IQ keyboard not working

### ISSUE THREAD

**Issue by androidkeshav** [hackiftekhar/IQKeyboardManager#1674]
**Describe the bug**
I have like this , Scrollview > Scrollview > View1 & View2 in this IqkeyboardManger not working , its pervious and next button not working , also hide textfiled with keyboard

**Comment by hackiftekhar** [comment]
The next/previous button does not show if your one textField is on View1 and other is on View2. To fix this problem, you have to keep both the view's superview as `IQPreviousNextView`.

**Comment by chandniKkpl** [comment]
I have scrollview -> View-> Text Fields. I have around 15 text fields. Whenever I enter data and keyboard dismiss, scrollview stops scrolling
