### ISSUE TITLE
swizzle hook NSArray or NSMutableArray method crash.

### ISSUE THREAD

**Issue by CrazyRoy** [hackiftekhar/IQKeyboardManager#1675]
in iOS 10.3 version

after swizzle NSArray or NSMutableArray  objectAtIndexedSubscript.

init IQKeyboardManager 

addDoneOnKeyboardWithTarget -> IQUIView+IQKeyboardToolbar file line 463 

[toolbar setItems: items]; crash.

**Comment by hackiftekhar** [comment]
So it's your application issue that you swizzle the default implementation of the methods, the library cannot do anything much to fix the crash you are observing.
