### ISSUE TITLE
Pop up keyboard disorder

### ISSUE THREAD

**Issue by gratefulHeart** [hackiftekhar/IQKeyboardManager#1676]
**Describe the bug**

**To Reproduce**

Pop up keyboard disorder
in  iOS 13.1.2 use  IQKeyboardManager 6.4.0
Pop up the keyboard and kill the APP and restart will return to normal.

**Expected behavior**

**Screenshots**

<img width="927" alt="image" src="https://user-images.githubusercontent.com/9955904/70899753-3ea9f200-2032-11ea-9c95-3b062f2d0176.png">

**Demo Project**
If applicable, add demo project.

### Versions
**Xcode:** 10.2.1
**Mac OS:** xx.xx.x
**Simulator/Device:** xx.x
**Simulator/Device Name:** iPhone xx
**Library Version:** x.x.x

**Additional context**

**Comment by hackiftekhar** [comment]
Hi @gratefulHeart, the library does not modify anything that is internal to Apple's API. This issue doesn't look due to the library, can you please try once without the library to see if it's still behaving the same?
