### ISSUE TITLE
Error tabbar and navigation bar position iphone 11

### ISSUE THREAD

**Issue by tuananhnn** [hackiftekhar/IQKeyboardManager#1678]
**Describe the bug**
my app using tab bar and navigation bar. when keyboard show and hide, tab bar and navigation bar position change and error.

**To Reproduce**
1. click to textfield
2. click to done in keyboard
3. See error

**Screenshots**
current screen
![image](https://user-images.githubusercontent.com/48539957/71408549-3b85b600-2671-11ea-8085-ce275ac6f197.png)
after show/hide keyboard
![image](https://user-images.githubusercontent.com/48539957/71408707-bc44b200-2671-11ea-92e9-20974a05fdf5.png)

### Versions
**Xcode:** 11.2.1
**Mac OS:** 10.15
**Simulator/Device:** 13.2.2
**Simulator/Device Name:** iPhone 11
**Library Version:** 6.5.4

**Comment by Sopheak0** [comment]
I've got this error too

**Comment by Sopheak0** [comment]
found the solution. just use **IQKeyboardManager.shared.layoutIfNeededOnUpdate = true**
- reference [(https://github.com/hackiftekhar/IQKeyboardManager/issues/1633#issuecomment-548710640)]
