### ISSUE TITLE
When keyboard is open UIViewcontroller view not updated after pushing

### ISSUE THREAD

**Issue by aherpooja** [hackiftekhar/IQKeyboardManager#1679]
**Describe the bug**
When the keyboard is open, and if I click on button to push new ViewController. The next viewcontroller shows keyboard and then hide it but the black view is displayed. I have added view.endediting true on viewwillappear and disappear. Still it's not working.

**To Reproduce**
1. click on TextField
2. Now without clicking on done button tap on another button which push new ViewController.
3. See error

**Expected behavior**
The pushed ViewController should not show black View at bottom

**Screenshots**
![Simulator Screen Shot - iPhone 8 - 2020-01-02 at 16 30 30](https://user-images.githubusercontent.com/28529058/71663991-4204e380-2d7d-11ea-9bea-87ed2b851b5e.png)

### Versions
Xcode:11.3
Mac OS:10.14.6
Simulator/Device:Error occurred on both simulator and device
Simulator/Device Name: iPhone 7 plus
Library Version:6.5.4

PS: I am using sidemenu library. So when I open viewcontroller by that then only the error occurred

**Comment by hackiftekhar** [comment]
The side menu library might be the cause of this issue. Btw which side menu library you are using?

**Comment by aherpooja** [comment]
jonkykong/SideMenu library. Yes that library was causing the issue. I have resolved it.
