### ISSUE TITLE
Missing Toolbar on keyboard, Missing Done button.

### ISSUE THREAD

**Issue by balram3429** [hackiftekhar/IQKeyboardManager#1683]
**Describe the bug**
The keyboard is not showing the Toolbar and hence missing the done button.
**To Reproduce**
Tap on any TextField which was earlier integrated with the IQkeyboardManager. the same text field will not show the "Done" button

**Expected behavior**
Toolbar shoul;d be visible and the accessory too. 

# Versions
**Xcode:** 11.1=
**Simulator/Device:** iPhone8 plus/ iPhone X (13.2)
**Library Version:** 6.2.1 onwards

**Comment by hackiftekhar** [comment]
You may have probably set `enableAutoToolbar = false`.

**Comment by bovillaios** [comment]
Hi Team,
Thanks for the library. I am facing same issue. I have enabled AutoToolbar, it is working only for UITextview, but not for text fields.

Thanks in advance
