### ISSUE TITLE
Glitches in landscape view iOS 13.3

### ISSUE THREAD

**Issue by amitmoradiya0611** [hackiftekhar/IQKeyboardManager#1684]
When i'm using IQkeyboardmanagerswift in landscape mode the constraints of textfield are changing to superview from safeview layout. It's gone to under notch...

**Comment by amitmoradiya0611** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/59819971/72239632-a0488680-3607-11ea-9064-64d402a70a4d.gif)

**Comment by hackiftekhar** [comment]
I had done some research on it in the past. I found that when we move viewController's view up then it happens. So I assume that it's not related to the library since moving viewController's view up is the original solution library do to uncover textField/textView.

**Comment by amitmoradiya0611** [comment]
But i don't get this type of glitches when i'm not using this library

**Comment by hackiftekhar** [comment]
This is because the library moves viewController's view up to properly show the textField above the keyboard. If you would like to get rid of this issue, then you might probably consider the use of UIScrollView. That will also work out of the box, just embed your view inside a UIScrollView.
