### ISSUE TITLE
点击输入框，闪退

### ISSUE THREAD

**Issue by shen0607** [hackiftekhar/IQKeyboardManager#1685]
**Describe the bug**
pod 'IQKeyboardManager', '6.2.0'
pod 'IQKeyboardManagerSwift','6.5.4'
![Uploading WX20200114-101127@2x.png…]()

IQUIView+IQKeyboardToolbar.swift
`@objc func addKeyboardToolbarWithTarget(target: AnyObject?, titleText: String?, rightBarButtonConfiguration: IQBarButtonItemConfiguration?, previousBarButtonConfiguration: IQBarButtonItemConfiguration? = nil, nextBarButtonConfiguration: IQBarButtonItemConfiguration? = nil)

if let prevConfig = previousBarButtonConfiguration {

                var prev = toolbar.previousBarButton

Thread 1: EXC_BAD_ACCESS (code=2, address=0x600000dac0c0)

`

**To Reproduce**

**Expected behavior**

**Screenshots**

**Demo Project**
If applicable, add demo project.

### Versions
**Xcode:** 11.3
**Mac OS:** 10.14.5
**Simulator/Device:** iOS13.3   iOS12.1.2
**Simulator/Device Name:** iPhone 11 pro max \ iphone7
**Library Version:** x.x.x

**Additional context**

**Comment by shen0607** [comment]
pod 'IQKeyboardManager', '6.2.0'
pod 'IQKeyboardManagerSwift','6.2.0'
is ok!

**Comment by hackiftekhar** [comment]
You should only include a single library, either IQKeyboardManager or IQKeyboardManagerSwift.

**Comment by shen0607** [comment]
My main project is the Swift project(IQKeyboardManagerSwift), and the third-party library introduced relies on OC(IQKeyboardManager), so two versions are introduced at the same time. If both are 6.2.0, it is ok.

**Comment by hackiftekhar** [comment]
Both use the same logic. You do not have to include both of them. Either one of them will work. You can use the Obj-C version in swift classes too and vice versa.
