### ISSUE TITLE
IQKeyboardManager doesn't work in subviews

### ISSUE THREAD

**Issue by whatweneed** [hackiftekhar/IQKeyboardManager#1686]
https://stackoverflow.com/questions/59839689/iqkeyboardmanager-doesnt-work-in-subviews

**Comment by danallen88** [comment]
This is an issue for me as well.  It would be nice to have some documentation on how to handle the situation where you have two sibling UIViews, each containing a UITextField, and how to allow the library to go Next/Previous between them.

**Comment by hackiftekhar** [comment]
Add IQPreviousNextView as the container of both your UIView.

-IQPreviousNextView
--View
---TextField1
--View
---TextField2

**Comment by poojagupta-simformsolutions** [comment]
Not working by using this as well.
