### ISSUE TITLE
Overlap with Navigation Bar Title.

### ISSUE THREAD

**Issue by LilianAlvarez** [hackiftekhar/IQKeyboardManager#1687]
**Describe the bug**
When using the `IQKeyboardManager` on a screen for signing up using a static tableView there is an overlap when the automatic scroll occurs to avoid Keyboard overlapping onto a `UITextField`.

**To Reproduce**
1. Create a scene with a static tableView inside a TableViewController, add UITextField in groupe inset, set the always big title property.
2. Compile the app on a real iPhone 8 device and start filling the several `UITextField`

**Expected behavior**
The overlap of the title should not occurs.

**Screenshots**
<img width="464" alt="Capture d’écran 2020-01-22 à 15 51 04" src="https://user-images.githubusercontent.com/26827633/72904348-0a130f80-3d2f-11ea-8692-8c29d9e26c98.png">

**Demo Project**
If applicable, add demo project.

### Versions
**Xcode:** 11.3
**Mac OS:** xx.xx.x
**Simulator/Device:** iPhone 8 (real device) on iOS 13.3
**Library Version:** 6.5.4

**Comment by dotWasim** [comment]
after hiding the keyboard, safearea become zero. adding this line will fix the issue

IQKeyboardManager.shared.layoutIfNeededOnUpdate = true
