### ISSUE TITLE
TextView pushed down when closing the app while using UINavigationController

### ISSUE THREAD

**Issue by 3llomi** [hackiftekhar/IQKeyboardManager#1688]
**Describe the bug**
TextView gets pushed down if the ViewController is embedded in UINavigationController while closing the app(by swiping) and re-open it again 

**To Reproduce**
1. Go to TextView, the keyboard got pushed up with the TextView
2.swipe up from Device to close the app 
3. re-open the app again and you will see that the keyboard is still showing but the TextView gets pushed down

**Expected behavior**
the TextView's position should be still the same

**Screenshots**
![iq-issue](https://user-images.githubusercontent.com/8546946/73184545-4bd3f980-4125-11ea-9d0e-48282357c26c.gif)

**Demo Project**
[IQ-issue-demo.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/4117656/IQ-issue-demo.zip)

### Versions
**Xcode:** 11.2.1
**Mac OS:** 10.15.1
**Simulator/Device:** XR Simulator 13.2.2 
**Simulator/Device Name:** iPhone SE 12.2
**Library Version:** 6.5.5

**Additional context**
NOTE:this is only happens while embedding ViewController inside UINavigationController

**Comment by mohammed-shakeer** [comment]
Add following code in `AppDelegate`'s `applicationDidBecomeActive` 

`IQKeyboardManager.shared().reloadLayoutIfNeeded()`

**Comment by 3llomi** [comment]
@mohammed-shakeer Thanks man!, it worked
