### ISSUE TITLE
When Keyboard load in UITextField the first letter is always lowercase

### ISSUE THREAD

**Issue by AlexLojewski** [hackiftekhar/IQKeyboardManager#1689]
**Describe the bug**
When the user click to a UITextField the keyboard is always lowercase. I want the first letter upercase. How parameter must i set for this function?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Demo Project**
If applicable, add demo project.

### Versions
**Xcode:** x.x
**Mac OS:** xx.xx.x
**Simulator/Device:** xx.x
**Simulator/Device Name:** iPhone xx
**Library Version:** x.x.x

**Additional context**

**Comment by srikanthkumarmailid07** [comment]
Write the following code inside viewDidLoad() mehod ,for perticular class.

**textField.autocapitalizationType = .none**
