### ISSUE TITLE
Is there a way to make the IQKeyBoardManager work with tab-bars? I found out that if you are using the keyboard manager, and you have a tab-bar at the bottom, there is a significant amount of space between the text and the keyboard.

### ISSUE THREAD

**Issue by GavinWon** [hackiftekhar/IQKeyboardManager#1690]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Demo Project**
If applicable, add demo project.

### Versions
**Xcode:** x.x
**Mac OS:** xx.xx.x
**Simulator/Device:** xx.x
**Simulator/Device Name:** iPhone xx
**Library Version:** x.x.x

**Additional context**

**Comment by Hatoine** [comment]
Hi,
Did you found a solution? I faced the same issue with the tab bar

**Comment by hackiftekhar** [comment]
Could you please let me know how much is space? Can someone share a screenshot?

**Comment by KakeruChang** [comment]
@hackiftekhar 

original:
![image](https://user-images.githubusercontent.com/45992879/102727287-c6ba8a00-435f-11eb-83f6-33c53739677a.png)

with keyboard:
![image](https://user-images.githubusercontent.com/45992879/102727314-f2d60b00-435f-11eb-9839-2b394c0a7bac.png)

**Comment by sovanna** [comment]
I had the same problem. It's due to the TabBar.
I ended up using a workaround from Internet.

You store the bottom tabBar height somewhere,
your view containing the textfield has a bottom constraint and when the keyboard appears/disappears,
you update the constant constraint value accordingly 

```
import UIKit

class ChatViewController: UIViewController {

    @IBOutlet weak var messageTextField: UITextField!
    @IBOutlet weak var viewBottomConstraint: NSLayoutConstraint!
    
    private var tabBarHeight: CGFloat?
    
    override func viewDidLoad() {
        super.viewDidLoad()

        messageTextField.delegate = self
        tabBarHeight = tabBarController?.tabBar.frame.size.height
    }
    
}

// MARK: - UITextFieldDelegate
extension ChatViewController: UITextFieldDelegate {
    
    func textFieldDidBeginEditing(_ textField: UITextField) {
        if let safeTabBarHeight = tabBarHeight {
            viewBottomConstraint.constant -= safeTabBarHeight
        }
    }
    
    func textFieldDidEndEditing(_ textField: UITextField, reason: UITextField.DidEndEditingReason) {
        if let safeTabBarHeight = tabBarHeight {
            viewBottomConstraint.constant += safeTabBarHeight
        }
    }
    
}

```

**Comment by hackiftekhar** [comment]
For the Chat Kind of screen, I generally suggest to use their own implementation instead of going through library. Because the requirement in chat screen is different than how the library works.
