### ISSUE TITLE
Empty Space Below UIScrollViews after textfields resign

### ISSUE THREAD

**Issue by ArvindDangarOpenxcell** [hackiftekhar/IQKeyboardManager#1692]
when we resign from text fields at that time added some extra space in UIScrollViews bottom..... 
![2CF4AE48-38A3-435E-876A-FD56CA3507C5](https://user-images.githubusercontent.com/49636415/73644456-71b84b80-469b-11ea-9e67-91697be62cae.jpg)

**Comment by saitejapanditi67** [comment]
I also have the same issue. and also the keyboard is appearing and disappearing instantly when trying to edit the text view when it is near to the keyboard area.

**Comment by SreejaG** [comment]
Have also the same issue and shows a black space at the bottom of the screen. Randomly occurs in iphone 6s.
![Unknown](https://user-images.githubusercontent.com/17117156/80183351-4acc3e80-8626-11ea-9d06-8945dd8fdeb4.png)

**Comment by KrillioSokolov** [comment]
Same problem

**Comment by KrillioSokolov** [comment]
navigationController?.isNavigationBarHidden = false

**Comment by KrillioSokolov** [comment]
![Uploading Screenshot 2021-01-28 at 17.24.30.png…]()
