### ISSUE TITLE
Empty Space Below UIScrollViews after textfields resign and also the keyboard is appearing and disappearing instantly when trying to edit the text view when it is near to the keyboard area.

### ISSUE THREAD

**Issue by saitejapanditi67** [hackiftekhar/IQKeyboardManager#1694]
Empty Space Below UIScrollViews after textfields resign and also the keyboard is appearing and disappearing instantly when trying to edit the text view when it is near to the keyboard area.
 Please check the below video zip
[bug.mp4.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/4171241/bug.mp4.zip)

**Comment by khushabu29** [comment]
Any Solution?? I am getting the same issue..

**Comment by khushabu29** [comment]
Any idea.. ?? when this issue will get resolved?

**Comment by saitejapanditi67** [comment]
My mistake. 
i have written a code to hide keyboard when tableview is scrolled. because of this code i got this bug. commenting the code resolved the issue.
//    func scrollViewDidScroll(_ scrollView: UIScrollView) {
//        self.createRideTableview.superview?.endEditing(true)
//    }

**Comment by saitejapanditi67** [comment]
My mistake. 
i have written a code to hide keyboard when tableview is scrolled. because of this code i got this bug. commenting the code resolved the issue.
//    func scrollViewDidScroll(_ scrollView: UIScrollView) {
//        self.createRideTableview.superview?.endEditing(true)
//    }

**Comment by khushabu29** [comment]
but I haven't written anything such. I am still facing that issue
