### ISSUE TITLE
Keyboard not behaving properly when UITextField is tapped 

### ISSUE THREAD

**Issue by chelvinn** [hackiftekhar/IQKeyboardManager#1695]
Currently I'm having this issue where it is inconsistent across different devices. Upon tapping the UITextField, the keyboard is shown as in the link. 

**Expected behavior**
Keyboard should be toggled to be something like this. https://imgur.com/a/qoDLv6O

**Screenshots**
Image as attached in the link. https://imgur.com/a/c5QltwS

### Versions
**Xcode:** 11.1
**Mac OS:** 10.14.5 
**Simulator/Device:** 13.3.1
**Simulator/Device Name:** iPhone X
**Library Version:** 6.1.1

**Comment by hackiftekhar** [comment]
Hmm, This is an issue when we are using password textField. We cannot do much to handle this problem.
