### ISSUE TITLE
键盘弹出后,导致键盘联想区域出现位置错乱.

### ISSUE THREAD

**Issue by Vickeywei** [hackiftekhar/IQKeyboardManager#1696]
![IMG_1176 PNG](https://user-images.githubusercontent.com/18063693/74600890-7ab11000-50d2-11ea-82d2-352fba3a6b06.JPG)
问题就是图上展示的样式,不知道是工程中的什么配置导致错误还是,而且是偶现的.

**Comment by hackiftekhar** [comment]
Sorry, I do not understand Chinese language. Please use English otherwise I can't much help with this.

**Comment by hackiftekhar** [comment]
However, by looking at the screenshot, I can see the toolbar is showing some space with the keyboard. Actually, we cannot do much about this because we do not add any tweaks to modify it. We just set the input accessory view of the textField and nothing special.
