### ISSUE TITLE
iOS toolbar hided textview & after close view moved down on second hide.

### ISSUE THREAD

**Issue by pingus-nikalex** [hackiftekhar/IQKeyboardManager#1698]
iOS 13, iPhone XS Max
after tap on UITextField IQKeyboard showed but textfield under the IQKeyboard ToolBar.
Next strange bug - after closed keyboard viewcontroller moved more down before start. If you close and open Keyboard again view show correctly. It's reproduce every 2 open: 1. Open then close - move more down 2. Open then close - move down correct 3. Open then close - move more down .... etc.
If you need I can record video and send you.

**Comment by hackiftekhar** [comment]
@pingus-nikalex it would be good if you share a demo project instead of the video. However, video will be a plus with the demo project.
