### ISSUE TITLE
Issue with Custom View

### ISSUE THREAD

**Issue by laindow** [hackiftekhar/IQKeyboardManager#1699]
**This library not handle keyboard for the custom view**

Hello guys,

I create new component with custom keyboard implementation. I show keyboard and receive input from it but it not handled by this library. Any way to add support for any components which one shown keyboard ? not just for UITextView/UITextField ?

Example

    class UILabelCount: UILabel, UIKeyInput {

    var myText: String = ""
    var keyboardType: UIKeyboardType = .numberPad
    
    override var canBecomeFirstResponder: Bool {
        get{
            return true
        }
    } // default is NO

    @discardableResult
    override func becomeFirstResponder() -> Bool {
        let becameFirstResponder = super.becomeFirstResponder()
        //stylize()
        return becameFirstResponder
    }
    
    @discardableResult
    override func resignFirstResponder() -> Bool {
        let resignedFirstResponder = super.resignFirstResponder()
        //stylize()
        return resignedFirstResponder
    }

    
    func insertText(_ text: String) {
        myText = myText + text
        self.text = myText
    }
    
    func deleteBackward() {
        if myText.count > 0 {
            myText.removeLast()
            self.text = myText
        }
    }
    
    var hasText: Bool {
        get{
            return true
            //return myText.count > 0
        }
    }
}

Best regards,
Konstantin.

**Comment by hackiftekhar** [comment]
I had already tried to implement some way to achieve this and the ObjC version handles it very well. We have to register our customView with below method

```
-(void)registerTextFieldViewClass:(nonnull Class)aClass
  didBeginEditingNotificationName:(nonnull NSString *)didBeginEditingNotificationName
    didEndEditingNotificationName:(nonnull NSString *)didEndEditingNotificationName;
```

But the Swift version cannot handle such thing in a better way. Altho this method is also available in library swift version but perhaps it will not work well.

**Comment by sameer4** [comment]
Any plan to support this?
