### ISSUE TITLE
Issue on Implementing IQkeyboard on ResideMenu

### ISSUE THREAD

**Issue by h3n1v** [hackiftekhar/IQKeyboardManager#170]
Implementing IQkeyboard on ResideMenu (https://github.com/romaonthego/RESideMenu)

Will result in not showing the toolbar of the keyboard (left/right arrow and OK button)
when we try to click 2 times the same view. (the first time is working fine, the second will not show the toolbar)

**Comment by hackiftekhar** [comment]
How you have integrated RESideMenu? Are you trying to add textField on side menu? could you please make a demo and send me with steps to produce the bug?

**Comment by h3n1v** [comment]
I have intergrated IQkeyboard on a view, not itself on the side menu.
When i click on this view, then a textfield, this is working.
When i reclick from the menu on the same view, then a textfield, the toolbar is missing

**Comment by hackiftekhar** [comment]
Please share demo and steps to reproduced

**Comment by h3n1v** [comment]
just sended you a PM on your gmail.

**Comment by hackiftekhar** [comment]
Thanks :), I'll look into demo.

**Comment by hackiftekhar** [comment]
It's working fine at my end. Please check demo code I sent to you via gmail.
