### ISSUE TITLE
IQTextView sometimes display Placeholder incorrectly in iOS 13.3

### ISSUE THREAD

**Issue by quan1910** [hackiftekhar/IQKeyboardManager#1701]
**Describe the bug**
IQTextView placeholder sometimes jump to the center of the view instead of display right under the text

**To Reproduce**
1. Create an iOS 13.3 Simulator
2. Add an IQTextView to the view
3. Use navigation to back and forth between the views
4. Check the placeholder position

**Expected behavior**
Display placeholder correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/32699074/75847322-6d558e80-5e11-11ea-9449-9f8fddc08e6f.png)

**Demo Project**
...

### Versions
**Xcode:** 11.3.1
**Simulator/Device:** xx.x 13.3
**Simulator/Device Name:** iPhone 8 Plus
**Library Version:** 6.5.5

**Additional context**
...

**Comment by hackiftekhar** [comment]
Can you please share a demo project @quan1910 ?
