### ISSUE TITLE
Keyboard Jerking 

### ISSUE THREAD

**Issue by chandaboy786** [hackiftekhar/IQKeyboardManager#1704]
**Describe the bug**

**To Reproduce**
1. I have added textfield's and add IQManager library but right now I am facing this issue.

**Screenshots**

![Issue](https://user-images.githubusercontent.com/57762214/76304601-7947c180-62e5-11ea-9c4c-dde434d9366c.gif)

**Demo Project**
I have added pod 'IQKeyboardManagerSwift' with no version . 

### Versions
**Xcode:** Version 11.3.1 (11C504)
**Mac OS:** xx.xx.x
**Simulator/Device:** iPhone X
**Simulator/Device Name:** iPhone xx
**Library Version:** 6.2.1

**Additional context**

**Comment by chandaboy786** [comment]
Any update of the above issue. 

Kindly let me know.

Thanks

**Comment by netgfx** [comment]
+1

**Comment by hackiftekhar** [comment]
Can you please try to move to the latest version of library?
