### ISSUE TITLE
Xcode11.3.1 Keyboard Toolbar LayoutConstraints Conflict

### ISSUE THREAD

**Issue by leftzhang** [hackiftekhar/IQKeyboardManager#1705]
Xcode11.3.1 Keyboard Toolbar LayoutConstraints Conflict

1. Xcode11.3.1 
2.  [IQKeyboardManager sharedManager].enableAutoToolbar = YES;
3. Editing Keyboard Show ToolBar
4.  [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 

Versions
Xcode: 11.3.1
Simulator/Device: xx.x 13.3
Simulator/Device Name: iPhone6s
Library Version: 6.5.5

Infos:
[LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSAutoresizingMaskLayoutConstraint:0x2802fe3f0 _UIToolbarContentView:0x1057e9a80.width == 0>",
    "<NSLayoutConstraint:0x2802dbc00 _UIButtonBarStackView:0x1057ede10.leading == _UIToolbarContentView:0x1057e9a80.leading>",
    "<NSLayoutConstraint:0x2802db2f0 _UIButtonBarStackView:0x1057ede10.trailing == _UIToolbarContentView:0x1057e9a80.trailing>",
    "<NSLayoutConstraint:0x2802d35c0 _UIModernBarButton:0x1057ec4a0.leading == _UIButtonBarButton:0x1057ec2d0.leading + 8>",
    "<NSLayoutConstraint:0x2802d3570 _UIButtonBarButton:0x1057ec2d0.trailing == _UIModernBarButton:0x1057ec4a0.trailing>",
    "<NSLayoutConstraint:0x2802d2080 UILayoutGuide:0x2818917a0.leading == _UIButtonBarButton:0x1057eaf90.leading>",
    "<NSLayoutConstraint:0x2802d1b80 UILayoutGuide:0x2818917a0.trailing == _UIButtonBarButton:0x1057ec2d0.trailing>",
    "<NSLayoutConstraint:0x2802d08c0 UIView:0x1057eb720.leading == _UIButtonBarButton:0x1057eaf90.trailing>",
    "<NSLayoutConstraint:0x2802d0c30 _UIButtonBarButton:0x1057eb880.leading == UIView:0x1057eb720.trailing>",
    "<NSLayoutConstraint:0x2802d0e10 UIView:0x1057ec010.leading == _UIButtonBarButton:0x1057eb880.trailing>",
    "<NSLayoutConstraint:0x2802d0be0 UIView:0x10579cf80.leading == UIView:0x1057ec010.trailing>",
    "<NSLayoutConstraint:0x2802d0dc0 UIView:0x1057ec170.leading == UIView:0x10579cf80.trailing>",
    "<NSLayoutConstraint:0x2802d0d70 _UIButtonBarButton:0x1057ec2d0.leading == UIView:0x1057ec170.trailing>",
    "<NSLayoutConstraint:0x2802de9e0 UILayoutGuide:0x2818917a0.left == _UIButtonBarStackView:0x1057ede10.left>",
    "<NSLayoutConstraint:0x2802de990 _UIButtonBarStackView:0x1057ede10.right == UILayoutGuide:0x2818917a0.right>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x2802d3570 _UIButtonBarButton:0x1057ec2d0.trailing == _UIModernBarButton:0x1057ec4a0.trailing>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2020-03-12 11:38:53.137671+0800 LawWorksManager[490:78025] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSAutoresizingMaskLayoutConstraint:0x2802fe3f0 _UIToolbarContentView:0x1057e9a80.width == 0>",
    "<NSLayoutConstraint:0x2802dbc00 _UIButtonBarStackView:0x1057ede10.leading == _UIToolbarContentView:0x1057e9a80.leading>",
    "<NSLayoutConstraint:0x2802db2f0 _UIButtonBarStackView:0x1057ede10.trailing == _UIToolbarContentView:0x1057e9a80.trailing>",
    "<NSLayoutConstraint:0x2802c90e0 _UIModernBarButton:0x1057eb160.leading == _UIButtonBarButton:0x1057eaf90.leading>",
    "<NSLayoutConstraint:0x2802ca080 _UIButtonBarButton:0x1057eaf90.trailing >= _UIModernBarButton:0x1057eb160.trailing + 8>",
    "<NSLayoutConstraint:0x2802d2080 UILayoutGuide:0x2818917a0.leading == _UIButtonBarButton:0x1057eaf90.leading>",
    "<NSLayoutConstraint:0x2802d1b80 UILayoutGuide:0x2818917a0.trailing == _UIButtonBarButton:0x1057ec2d0.trailing>",
    "<NSLayoutConstraint:0x2802d08c0 UIView:0x1057eb720.leading == _UIButtonBarButton:0x1057eaf90.trailing>",
    "<NSLayoutConstraint:0x2802d0c30 _UIButtonBarButton:0x1057eb880.leading == UIView:0x1057eb720.trailing>",
    "<NSLayoutConstraint:0x2802d0e10 UIView:0x1057ec010.leading == _UIButtonBarButton:0x1057eb880.trailing>",
    "<NSLayoutConstraint:0x2802d0be0 UIView:0x10579cf80.leading == UIView:0x1057ec010.trailing>",
    "<NSLayoutConstraint:0x2802d0dc0 UIView:0x1057ec170.leading == UIView:0x10579cf80.trailing>",
    "<NSLayoutConstraint:0x2802d0d70 _UIButtonBarButton:0x1057ec2d0.leading == UIView:0x1057ec170.trailing>",
    "<NSLayoutConstraint:0x2802de9e0 UILayoutGuide:0x2818917a0.left == _UIButtonBarStackView:0x1057ede10.left>",
    "<NSLayoutConstraint:0x2802de990 _UIButtonBarStackView:0x1057ede10.right == UILayoutGuide:0x2818917a0.right>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x2802ca080 _UIButtonBarButton:0x1057eaf90.trailing >= _UIModernBarButton:0x1057eb160.trailing + 8>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2020-03-12 11:38:53.143573+0800 LawWorksManager[490:78025] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSAutoresizingMaskLayoutConstraint:0x2802fe3f0 _UIToolbarContentView:0x1057e9a80.width == 0>",
    "<NSLayoutConstraint:0x2802dbc00 _UIButtonBarStackView:0x1057ede10.leading == _UIToolbarContentView:0x1057e9a80.leading>",
    "<NSLayoutConstraint:0x2802db2f0 _UIButtonBarStackView:0x1057ede10.trailing == _UIToolbarContentView:0x1057e9a80.trailing>",
    "<NSLayoutConstraint:0x2802d2a30 _UIModernBarButton:0x1057eba50.leading >= _UIButtonBarButton:0x1057eb880.leading + 5>",
    "<NSLayoutConstraint:0x2802d29e0 _UIButtonBarButton:0x1057eb880.trailing >= _UIModernBarButton:0x1057eba50.trailing + 5>",
    "<NSLayoutConstraint:0x2802d2080 UILayoutGuide:0x2818917a0.leading == _UIButtonBarButton:0x1057eaf90.leading>",
    "<NSLayoutConstraint:0x2802d1b80 UILayoutGuide:0x2818917a0.trailing == _UIButtonBarButton:0x1057ec2d0.trailing>",
    "<NSLayoutConstraint:0x2802d08c0 UIView:0x1057eb720.leading == _UIButtonBarButton:0x1057eaf90.trailing>",
    "<NSLayoutConstraint:0x2802d0c30 _UIButtonBarButton:0x1057eb880.leading == UIView:0x1057eb720.trailing>",
    "<NSLayoutConstraint:0x2802d0e10 UIView:0x1057ec010.leading == _UIButtonBarButton:0x1057eb880.trailing>",
    "<NSLayoutConstraint:0x2802d0be0 UIView:0x10579cf80.leading == UIView:0x1057ec010.trailing>",
    "<NSLayoutConstraint:0x2802d0dc0 UIView:0x1057ec170.leading == UIView:0x10579cf80.trailing>",
    "<NSLayoutConstraint:0x2802d0d70 _UIButtonBarButton:0x1057ec2d0.leading == UIView:0x1057ec170.trailing>",
    "<NSLayoutConstraint:0x2802de9e0 UILayoutGuide:0x2818917a0.left == _UIButtonBarStackView:0x1057ede10.left>",
    "<NSLayoutConstraint:0x2802de990 _UIButtonBarStackView:0x1057ede10.right == UILayoutGuide:0x2818917a0.right>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x2802d29e0 _UIButtonBarButton:0x1057eb880.trailing >= _UIModernBarButton:0x1057eba50.trailing + 5>

**Comment by keyhan76** [comment]
Any solutions yet? I'm facing the same problem on iOS 13.4, Xcode 11.4

**Comment by connerwu** [comment]
I'm facing this problem, too.
And I found the app may get frozen sometimes if focus in input field.

**Comment by dasoga** [comment]
I think updating to `version 6.5.4`
I tested it and it worked.

https://github.com/hackiftekhar/IQKeyboardManager/issues/1639#issuecomment-554884734

**Comment by dingxiaolong** [comment]
I'm facing the same problem on iOS 13.4, Xcode 11.4 SimulatorXr version 6.5.5. I can't input anything and even do anything sometimes

**Comment by IOS785130706** [comment]
楼主，这个问题有解决吗？怎么解决的？

**Comment by himanshu-github** [comment]
facing the same issue in iOS 13.4.1

**Comment by jbarros35** [comment]
Last version and same bug

**Comment by poojagupta-simformsolutions** [comment]
Facing the same issue.

**Comment by tienrocker** [comment]
any update? i have same issue

**Comment by mahesh789** [comment]
any update? i have same issue

**Comment by hackiftekhar** [comment]
With my experience it usually happening when textField hae custom inputView. Do you have same scenario or is it just happening with standard keyboad also?

**Comment by mahesh789** [comment]
For me coming in wenview textfield. Normally its not coming. Can u found
the solution. In my team not accepting constraints issues.

**Comment by shijian123** [comment]
更新至 6.5.6版本，可以解决

**Comment by zuqiu123** [comment]
The problem remains at 6.5.6

**Comment by hackiftekhar** [comment]
This looks to be System issue. Not the library issue.
