### ISSUE TITLE
doneAction: is not called~ plz help

### ISSUE THREAD

**Issue by txkjjordan** [hackiftekhar/IQKeyboardManager#1709]
in my project   
i userd your 'IQKeyboardManager'
it is awsome, thsnk u
but now i find a  bug
in the latest ios 13.4, doneAction: is not called
when i clicked 'done'  
i have set a breakpoint ,   but not go there
but in the earlier version ,  it works
so,  is it not compatible for the 13.4?
plz help me . thanks!!

**Comment by kimbely** [comment]
I have same problem !! How to fix it?

**Comment by hackiftekhar** [comment]
okay, I need to check it.

**Comment by hackiftekhar** [comment]
In my demo project, I tried using 13.4 and it looks to be working. Can you please share more details about how you configured it and if you are using the swift version or objc version?

**Comment by praditkan** [comment]
My problem happen when it's the next textfield's being firstresponder.

Textfield A become firstresponder when view appear.
Then Done button work. 
Then I assign next Textfield B become firstresponder where Done button didn't work.
Neither the previous next button too.

I tried to Assign Textfield B to firstresponder when view appear instead then it's working. 
But next Textfield C didn't wrok.

**Comment by FlyOceanFish** [comment]
me too.I have the same problem

**Comment by aiyub007** [comment]
Same problem in 13.4 

on first attempt it is working fine
Done button is not working second time

**Comment by himanshu-github** [comment]
Same issue is happening in iOS 13.4/13.4.1 as well..

**Comment by poojagupta-simformsolutions** [comment]
Facing the same issue, any update on this?

**Comment by EmanuelDavid** [comment]
> Same problem in 13.4
> 
> on first attempt it is working fine
> Done button is not working second time

Exact behaviour here, on ios 13, on second attempt, textFieldDidEndEditing is not called. on ios 12 all is fine.

**Comment by SSenocico** [comment]
The same for me! 😕

**Comment by mnizar** [comment]
Same problem in iOS 13.5 as well..

**Comment by gardenerYang** [comment]
me too

**Comment by EmanuelDavid** [comment]
As a work around, you can set
 IQKeyboardManager.shared.toolbarDoneBarButtonItemText = "button title" in you're code, and it will work also for ios 13+

**Comment by zubair-ets** [comment]
IQKeyboardManager.shared.toolbarDoneBarButtonItemText = "Done" 
it also works

**Comment by etDev24** [comment]
> As a work around, you can set
> ` IQKeyboardManager.shared.toolbarDoneBarButtonItemText = "Button Title"` in `didFinishLaunchingWithOptions` method from `AppDelegate`, and it will work also for ios 13+

Great Solution.
