### ISSUE TITLE
view's position changed while popViewController

### ISSUE THREAD

**Issue by nol876** [hackiftekhar/IQKeyboardManager#1711]
**Describe the bug**
if set navigationBar's translucent NO, the ViewController's view will move down while popViewController.

**To Reproduce**

`- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    // Override point for customization after application launch.
    
    self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
    self.window.backgroundColor = [UIColor whiteColor];
    [self.window makeKeyAndVisible];
    
    ViewController *vc = [ViewController new];
    UINavigationController *nav = [[UINavigationController alloc] initWithRootViewController:vc];
    nav.navigationBar.translucent = NO;
    self.window.rootViewController = nav;
    
    
    return YES;
}
`

**Expected behavior**

**Screenshots**
![Simulator Screen Shot - iPhone 8 - 2020-04-21 at 16 24 56](https://user-images.githubusercontent.com/17896760/79844221-f9d20580-83ed-11ea-8172-f7a230f0f5bc.png)

**Demo Project**
If applicable, add demo project.

### Versions
**Xcode:** x.x
**Mac OS:** xx.xx.x
**Simulator/Device:** xx.x
**Simulator/Device Name:** iPhone xx
**Library Version:** x.x.x

**Additional context**

**Comment by hackiftekhar** [comment]
This can happen since the navigational related things are not handled by the library.
