### ISSUE TITLE
View jumps back to original position when keyboard appears

### ISSUE THREAD

**Issue by dandepeched** [hackiftekhar/IQKeyboardManager#1712]
**Describe the bug**
I observe that when keyboard appears for the first time, view jumps back to original.
This is NOT reproducible after I hide and call keyboard again.

**To Reproduce**
1. Go to screen with UITextField
2. Click on text field

**Actual result**
Keyboard appears, view is moved up and then jumps back 

**Expected behavior**
Keyboard appears, view is moved up and stays in upper position

### Versions
**Xcode:** 11.4.1
**Mac OS:** 10.15.4
**Device:** 13.4.1
**Device Name:** iPhone 6s
**Library Version:** 6.5.5

**Additional context**
- I use custom UITextField to adjust some bounds (can provide code if needed)
- IQKeyboardManager settings are following:
        IQKeyboardManager.shared.enable = true
        IQKeyboardManager.shared.keyboardDistanceFromTextField = 200
        IQKeyboardManager.shared.shouldResignOnTouchOutside = true

**Comment by gaoshanyu** [comment]
+1

**Comment by netgfx** [comment]
+1

**Comment by QingyuHu** [comment]
My problem is similar.
When keyboard appears, the view moves up perfect.
When I type anything, the view goes back.

**Comment by khushabu29** [comment]
Have any1 found a solution for this? I am also facing the same issue

**Comment by netgfx** [comment]
Same here I believe there is another topic about this.

**Comment by MikhailovAl** [comment]
I get the same problem too.

**Comment by khushabu29** [comment]
any1 found solution?

**Comment by MikhailovAl** [comment]
> any1 found solution?

This bug pops only in the simulator, everything is OK on a real device.
