### ISSUE TITLE
Text is clipping when open text view 

### ISSUE THREAD

**Issue by jagveer-dev** [hackiftekhar/IQKeyboardManager#1713]
when textview become first responder
if textview is on top or if text view is at bottom 
it become clipped
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-24 at 09 33 21](https://user-images.githubusercontent.com/64246729/80181990-87e30180-8623-11ea-915d-250ae3472752.png)
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-24 at 09 32 56](https://user-images.githubusercontent.com/64246729/80182011-8f0a0f80-8623-11ea-9a68-91b08b1416a5.png)

**Comment by jagveer-dev** [comment]
please let me know if any solution for this, i am using IQKeyboardManager for making visible current textview

**Comment by hackiftekhar** [comment]
This might be due to your designs constraints. Also the textView is scrollable, so content will be under it's bounds. If content exceeded the textView bounds, then it will definitely be hidden.
