### ISSUE TITLE
UITextView in collectionViewCell offset error, when collectionView top not zero

### ISSUE THREAD

**Issue by xdkhan** [hackiftekhar/IQKeyboardManager#1714]
**Describe the bug**
One UITextView in CollectionViewCell,
If CollectionView snp.top not zero,
offset will error when keyboard show.

**To Reproduce**
1. run demo project
2. click uitextView bottom line
3. See error

**Screenshots**
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-26 at 15 15 19](https://user-images.githubusercontent.com/15863777/80300631-fca76e80-87d0-11ea-9fa7-02b064afe39d.png)
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-26 at 15 15 24](https://user-images.githubusercontent.com/15863777/80300633-fe713200-87d0-11ea-95a1-fe059d098ec5.png)

**Demo Project**
https://github.com/xdkhan/SwiftTest.git

### Versions
**Xcode:** 11.4
**Mac OS:** 10.15.4
**Simulator/Device:** 13.4
**Simulator/Device Name:** iPhone 11 Pro Max
**Library Version:** 6.5.1

**Comment by hackiftekhar** [comment]
Looks like demo has been removed.
