### ISSUE TITLE
A TextField in generic subview of UIScrollView, IQKeyboardManager will not judge the content offset.

### ISSUE THREAD

**Issue by scubers** [hackiftekhar/IQKeyboardManager#1715]
**Describe the bug**
```
class DemoView<T>: UIScrollView {

}

class DemoView2: UIScrollView {}

func viewDidLoad() {
   let scroll = DemoView<UIView>()
   let textfield = UITextField()
   scroll.addSubview(textfield)
   view.addSubview(scroll)
   // is works use DemoView2

   ...
}
```
with this code, when begin editing, IQKeyboardManager will not judge the scrollView's contentOffset, but just change UIViewController.view's frame. 

hope fix.

Thank you

**Comment by scubers** [comment]
![企业微信截图_e63e7163-b8a4-4392-8b48-f6d32d869ad9](https://user-images.githubusercontent.com/11241903/80510917-f8847800-89ad-11ea-9581-cb5b10e87de2.png)

**Comment by scubers** [comment]
![企业微信截图_ae72db47-1d74-4fe3-93d6-ccc67d42b469](https://user-images.githubusercontent.com/11241903/80565043-15f32980-8a22-11ea-997a-a3d706e7833b.png)

if change the method that get the  class name to `"\(type(of: unwrappedSuperView.self)"`, it works.

hope consider this way to check.

**Comment by lishuanglong521** [comment]
OC出现textview局部弹起，并不是整个view弹起
