### ISSUE TITLE
Keyboard in not showing in iPhone 11

### ISSUE THREAD

**Issue by kolindalanaresh** [hackiftekhar/IQKeyboardManager#1716]
Hi, In iPhone 11 when i click on textfield it is showing like attached screenshot. This issue is appearing in some times. Please help me on this(url
![savefjjad](https://user-images.githubusercontent.com/23052483/80955161-64d30180-8e1c-11ea-8cfd-a37592d79b74.png)
)

**Comment by mclimb** [comment]
I'm having the same issue. Only on the iPhone 11 emulator in Xcode. Works correctly on the iPhone 8 and iPhone 11 Pro emulators though, and on a physical XR.

**Comment by mehyaz** [comment]
Yes, I have same problem. Please fix this bug.

**Comment by hackiftekhar** [comment]
I'm not sure how to reproduce the issue guys. Can you please help me out sending the steps?

**Comment by PiotrFurmanski** [comment]
same story on xcode 12.1 iphone 11 (ios 14)

**Comment by rankinit** [comment]
Was there a fix for this? ... seeing the same issue currently: Iphone 12 Pro Max and ios 14.6

![IMG_20210727_164535](https://user-images.githubusercontent.com/166776/127232175-13acfc8b-89b9-4b96-ac17-de409d5dcfd7.jpg)

**Comment by PiotrFurmanski** [comment]
Used different library;)


Wysłane z Yahoo Mail do iPhone


W środa, lipca 28, 2021, 00:51, rankinit ***@***.***> napisał(-a):




Was there a fix for this? ... seeing the same issue currently: Iphone 12 Pro Max and ios 14.6

**Comment by rankinit** [comment]
@PiotrFurmanski  haha which library did you wind up using? thx!

**Comment by PiotrFurmanski** [comment]
I dont remeber a s would have to look in prokect but im on holodays, it was some quie old objc lib, not very nice to use but works


Wysłane z Yahoo Mail do iPhone


W środa, lipca 28, 2021, 03:38, rankinit ***@***.***> napisał(-a):




@PiotrFurmanski haha which library did you wind up using? thx!

**Comment by rankinit** [comment]
I can reproduce the issue if I place a breakpoints in this method on the getter and setter... if I disable breakpoints then it works normally... the keyboard frame is getting set to zero so not sure why  some users experience the issue and others don't -

    /** To save keyboard rame. */
    internal var keyboardFrame: CGRect {
        get {
            return objc_getAssociatedObject(self, &AssociatedKeys.keyboardFrame) as? CGRect ?? .zero
        }
        set(newValue) {
            objc_setAssociatedObject(self, &AssociatedKeys.keyboardFrame, newValue, .OBJC_ASSOCIATION_RETAIN_NONATOMIC)
        }
    }

**Comment by hackiftekhar** [comment]
Is it only happening on the simulator or with real device also?
