### ISSUE TITLE
UIScrollView unable to recover

### ISSUE THREAD

**Issue by coderHunterLu** [hackiftekhar/IQKeyboardManager#1718]
![WechatIMG14](https://user-images.githubusercontent.com/35336177/81133296-c366bf80-8f83-11ea-8ec9-2065230eec7f.jpeg)
Please see the debug navigator. The scrollview can not be recovered, when I quit the keyboard.

**Comment by hackiftekhar** [comment]
Did you put `becomeFirstResponder` line on viewDidLoad?
