### ISSUE TITLE
Done button and tab button didnt show up in top of the keyboard

### ISSUE THREAD

**Issue by ekapradityagk** [hackiftekhar/IQKeyboardManager#1720]
**Describe the bug**

Hi, my colleague and i try to make an application, i am an objc user, and he is swift user, we make the base of the app using objective c, and ui using swift, my colleague try to use iqkeyboardmanager 
To help him produce the done and tab button on top of the keyboard, but unfortunately the button didnt show up,  he ask me whats wrong, since he didnt have any issue when create in a pure swift project.

I try to create a simple project using objc as the base, and using swift for ui to test it out, but in this new project, the button came out perfectly.. 

Any idea where i should check in out project to make this button appear??
**To Reproduce**
I didnt know how to reproduce since when i try in new project its worked

**Expected behavior**
The arrow to move between textfield and done button should appear on top of the keyboard

**Screenshots**
![C80601F9-6098-4AA4-B2E5-38BCB8D5B23D](https://user-images.githubusercontent.com/6790426/81362595-65fd7a80-910b-11ea-8c02-090748e8e36e.jpeg)
![4DA0C026-FBB9-457F-81FE-E5550CCBAE47](https://user-images.githubusercontent.com/6790426/81362600-68f86b00-910b-11ea-8a80-ed96ff69dbd2.jpeg)

### Versions
**Xcode:** x.x
**Mac OS:** xx.xx.x
**Simulator/Device:** i try from ios 11 to 13 only worked in my test project
**Simulator/Device Name:** iPhone x and xr
**Library Version:** 

**Additional context**
Notes, we’re using iqkeyboardmanager and tpkeyboardavoiding
And even though the arrow button is not shown, i can still tapped in the area and the function is there, i can up and down between textfield when i tap the area..

**Comment by yogeshrathore123** [comment]
Same issue I am also facing. Done button and close button is not showing.

**Comment by salkovich** [comment]
same here, but only on versions lower than iOS 13. Did someone found a solution

**Comment by WisdomWang** [comment]
This problem I am also facing       Done button and close button is not showing.        how can I slove it

**Comment by hackiftekhar** [comment]
Can you guys please see if you have globally set any tintColor of UIBarButtonItem to something?

**Comment by bogdandovgopol** [comment]
Same here
![Screenshot 2020-08-25 at 8 29 58 pm](https://user-images.githubusercontent.com/30866972/91164078-da3b4880-e711-11ea-9cb4-1aff16437e2f.png)
