### ISSUE TITLE
Issue with UITextView on UIScrollView

### ISSUE THREAD

**Issue by Patrashkov** [hackiftekhar/IQKeyboardManager#1723]
**Describe the bug**
Hello, 
I have some issue with UITextView on UIScrollView
when disabling scroll on UITextView (for automatically resize)

**To Reproduce**
1. Go to 'test project'
2. Click on 'select part of the text on the top'
3. drag down to highlight more text
4. after highlight all text move scroll view to bottom 

P.S.
Please watch the video for more detailed playback.

**Video**
[IQKeyboard issue Screen Recording 2020-05-12 at 19.27.48.mov.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/4617056/IQKeyboard.issue.Screen.Recording.2020-05-12.at.19.27.48.mov.zip)

**Demo Project**
[TestKeyboard.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/4617050/TestKeyboard.zip)

### Versions
**Xcode:** 11.4
**Mac OS:** 10.15.3
**Simulator/Device:** 12.2
**Simulator/Device Name:** iPhone xx
**Library Version:** 6.5.5

**Comment by hackiftekhar** [comment]
Gotcha! Now I've put another condition `UIScrollView.isScrollEnabled`. So you have to disable the scroll on UITextView to prevent this happening.
