### ISSUE TITLE
Replacement of UIWebView for WKWebView

### ISSUE THREAD

**Issue by lazaro10** [hackiftekhar/IQKeyboardManager#1724]
**Describe the bug**

Hello, you can include in your correction the replacement of UIWebView by WKWebView, Your Demo project still uses UIWebView, and as we use Carthage to manage our dependencies, all projects are included in our project, and apple is blocking us when we try send to the store.

**To Reproduce**

Go to the demo project and replace the UIWebView

**Expected behavior**

Able to send our app

### Versions
**Xcode:** 11.4.1
**Mac OS:** Catalina, 10.15.4
**Simulator/Device:** all
**Simulator/Device Name:** all
**Library Version:** 6.5.0

**Comment by skovalysh** [comment]
+
Same problem

**Comment by eyupcimen** [comment]
Same problem

**Comment by Agoer** [comment]
Same problem

**Comment by DreamworksCode** [comment]
facing same problem.

**Comment by DDwin** [comment]
Same problem

**Comment by jishuke** [comment]
Same problem

**Comment by hackiftekhar** [comment]
Can you please point out the file and line number where our project uses UIWebView?

I do not find any references.
