### ISSUE TITLE
iOS13.4点击键盘上方‘完成’按钮无法收起键盘

### ISSUE THREAD

**Issue by lc4664456** [hackiftekhar/IQKeyboardManager#1725]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Demo Project**
If applicable, add demo project.

### Versions
**Xcode:** x.x
**Mac OS:** xx.xx.x
**Simulator/Device:** xx.x
**Simulator/Device Name:** iPhone xx
**Library Version:** x.x.x

**Additional context**

**Comment by alokc83** [comment]
@lc4664456 English, please.

**Comment by money-69** [comment]
Are you solved it?, I also appeared this problem.
Xcode:11.6
Device:iphone 7p, 13.7, iphone6 ,13.4

oc+swift Project，IQKeyboardManager 6.5.6，
A strange question, connected to xcode debug it`s ok, but, run the ipa , the "Done" is not working
