### ISSUE TITLE
keyboardDistanceFromTextField error

### ISSUE THREAD

**Issue by springlo** [hackiftekhar/IQKeyboardManager#1726]
**Describe the bug**
When the keyboard pops up, the spacing is wrong

**To Reproduce**
        IQKeyboardManager.shared.enable = true
        IQKeyboardManager.shared.disabledToolbarClasses = [ViewController.self]
        IQKeyboardManager.shared.shouldResignOnTouchOutside = true
        IQKeyboardManager.shared.keyboardDistanceFromTextField = 0

**Demo Project**
[demo.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/4681992/demo.zip)

### Versions
**Xcode:** 11.3
**Mac OS:** 10.15.1
**Simulator/Device:** 13.3
**Simulator/Device Name:** iPhone Pro Max
**Library Version:** 6.5.5

**Additional context**
![222](https://user-images.githubusercontent.com/373580/82898048-306de380-9f8b-11ea-953a-ba4de747ee4f.gif)

**Comment by hackiftekhar** [comment]
I'm able to see the issue in your video but unfortunately in demo project the textField stays at the same position, I'm unable to reproduce the issue.
