### ISSUE TITLE
Navbar transparent when view pushed in SwiftUI

### ISSUE THREAD

**Issue by PedroCavaleiro** [hackiftekhar/IQKeyboardManager#1728]
**Describe the bug**
When the view is pushed the Navigation Bar becomes transparent, this happens in SwiftUI, I don't know if it appears in projects with the UIKit

**To Reproduce**
1. Implement the IQKeyboardManagerSwift
2. Create a view with a NavigationView and the modifier `.navigationBarTitle(Text("some title"))`
3. Add on the top a `Text("just some content")`
3. Add a `TextField` to the bottom of the view
4. Tap the field to start editing
5. The first element would go under the nav bar as expected, but the nav bar is transparent

**Expected behavior**
The nav bar shouldn't be transparent

**Screenshots**
![IMG_3240](https://user-images.githubusercontent.com/1993871/83106382-488d5200-a0b4-11ea-9aee-b6d32c9a9e63.png)
If you take a closer look you will notice that the Group Header is under the page name in this case "Hitman"
### Versions
**Xcode:** 11.5
**Mac OS:** 10.15.5
**Device:** iOS 13.5 / iPadOS 13.5
**Device Name:** iPhone XS Max / iPad 6th gen
**Library Version:** 6.5

**Comment by plbeaudoin** [comment]
I am experiencing the same issue.

Versions
Xcode: 12.2
Mac OS: 10.15.7
Device: iOS 14.2 / iPadOS 14.2
Device Name: iPhone XS Max / iPad Air 4th gen
Library Version: 6.5.6

**Comment by EstiT** [comment]
Same for me with SwiftUI. Seems like this line causes the issue
`IQKeyboardManager.shared.enable = true`

**Versions**
Xcode: 13.0
Mac OS: 11.4
Device: iOS 14.6
Device Name: iPhone 12 mini 
Library Version: 6.5.6

**Comment by Dave181295** [comment]
Any solutions friends?

**Comment by Dave181295** [comment]
> Same for me with SwiftUI. Seems like this line causes the issue `IQKeyboardManager.shared.enable = true`
> 
> **Versions** Xcode: 13.0 Mac OS: 11.4 Device: iOS 14.6 Device Name: iPhone 12 mini Library Version: 6.5.6

I'm implementing this line in ``` onAppear``` If deleting this line, the view won't go up

**Comment by hackiftekhar** [comment]
The library doesn't change any native UI you implemented. This looks like something with the SwiftUI or the iOS.
