### ISSUE TITLE
Tag version crash Xcode 11 while downloading SPM

### ISSUE THREAD

**Issue by Oleh1033** [hackiftekhar/IQKeyboardManager#1729]
Because  tag version contains 'v', it cause crash Xcode while trying to download library as spm

**Comment by hackiftekhar** [comment]
Do not put 'v' like the below screenshot.
![Screenshot 2020-07-18 at 10 21 15 PM](https://user-images.githubusercontent.com/3831495/87857531-25a94c80-c945-11ea-856d-315ab21e132a.png)
![Screenshot 2020-07-18 at 10 21 38 PM](https://user-images.githubusercontent.com/3831495/87857532-27731000-c945-11ea-82c9-135676f180c1.png)
