### ISSUE TITLE
UIScrollView goes very high in iOS8

### ISSUE THREAD

**Issue by hmobdev** [hackiftekhar/IQKeyboardManager#173]
Hello,
I am using IQKeyboardManagerin my application and it was working very smoothly until I used it in iOS8.
The problem I am facing is that my scrollView goes very high even I am using the very first textfield of my view which is having atleast 10 textfields.

Is there any solution for that?
Looking forward to your reply.
Thank you.

**Comment by hackiftekhar** [comment]
Could you please elaborate with screenshot and test demo app. Orcould you please provide a demo app?

**Comment by hmobdev** [comment]
@hackiftekhar  
I have solved this problem,it was the iOS8simulator bug.
Anyway thanks for your quick reply.
