### ISSUE TITLE
KeyboardSize has include  layoutMargins.bottom， Why need add bottomLayoutGuide

### ISSUE THREAD

**Issue by CheckRan** [hackiftekhar/IQKeyboardManager#1731]
CGFloat bottomLayoutGuide = ([textFieldView respondsToSelector:@selector(isEditable)] && [textFieldView isKindOfClass:[UIScrollView class]]) ? 0 : rootController.view.layoutMargins.bottom; 

    CGFloat move =
 MIN(
CGRectGetMinY(textFieldViewRectInRootSuperview)-topLayoutGuide, 
CGRectGetMaxY(textFieldViewRectInWindow)-(CGRectGetHeight(keyWindow.frame)-kbSize.height)+ **bottomLayoutGuide**);

**Comment by hackiftekhar** [comment]
It's a variable name. The code was written before the introduction of layoutMargins, that's why the name was bottomLayoutGuide.

**Comment by YongTaiSin** [comment]
> layoutMargins

这个加上去偏移量会有问题！
