### ISSUE TITLE
XCode 11.5 deprecated warning for statusBarOrientationUserInfoKey

### ISSUE THREAD

**Issue by bluelobe** [hackiftekhar/IQKeyboardManager#1732]
**Describe the bug**
XCode 11.5 deprecated warning for 3 instances:
IQKeyboardManager.swift :
1. #if swift(>=4.2)
        let statusBarUserInfoKey    = UIApplication.statusBarOrientationUserInfoKey
2. func registerAllNotifications ... let UIApplicationWillChangeStatusBarOrientation = UIApplication.willChangeStatusBarOrientationNotification
3. func unregisterAllNotifications....let UIApplicationWillChangeStatusBarOrientation = UIApplication.willChangeStatusBarOrientationNotification

**To Reproduce**
1. Install IQKeyboardManager using Xcode 11.5
2. Build or run
3. See warnings

**Expected behavior**
No warnings

**Screenshots**
Error message

**Demo Project**
If applicable, add demo project.

### Versions
**Xcode:** 11.5
**Mac OS:** 10.15.5
**Simulator/Device:** MacBook Pro 2019
**Simulator/Device Name:** iPad 7th gen simulator
**Library Version:** na
<img width="238" alt="Screen Shot 2020-06-19 at 6 15 32 PM" src="https://user-images.githubusercontent.com/4734161/85122297-e65de200-b258-11ea-8e94-b5a737570950.png">

**Additional context**

**Comment by hackiftekhar** [comment]
The IQKeyboardManager is actually not a UIView or UIViewController, and it cannot adopt viewWillTransitionToSize method. I'm open to suggestion about what changes we can do to get rid of this warnings.
