### ISSUE TITLE
Opening keyboard raises more than just the desired items upwards

### ISSUE THREAD

**Issue by fraander** [hackiftekhar/IQKeyboardManager#1734]
**Describe the bug**
TableView contents are pushed up along with textField

**Expected behavior**
I only want the textField to move up

**Screenshots**
![image](https://user-images.githubusercontent.com/57777918/85213014-ba506880-b30d-11ea-9373-aadd094770ea.png)
![image](https://user-images.githubusercontent.com/57777918/85213018-c1777680-b30d-11ea-96b1-c758cbc4d637.png)

I'm a beginner so I'm assuming I just missed how to do something in the docs.

**Comment by himangirdhar** [comment]
Library is not good if you are developing custom chat. disable iqkeyboard in viewwillAppear and enable it in viewwillDisappear in chat class. And to achieve what you were asking change the bottom constraint  from 0 to desired height. In textfielddidbeginEditing change the bottom constraint to 350(changes with the device size) and in textfieldendEditing again change it to 0.
