### ISSUE TITLE
TextView move down after sceneWillResignActive called

### ISSUE THREAD

**Issue by eslami-mhmd** [hackiftekhar/IQKeyboardManager#1735]
Describe problem:
I have a ViewController that embedded into UINavigationController. In ViewController I have a textview that its bottom anchor constrained to bottom safe area and it is first responder. 
When I double tap on phone home button to switch app and again back to my app, textview moved down and keyboard is open.

Expected behavior:
textview should not move down.

Library version: 6.5.5

**Comment by hackiftekhar** [comment]
This is a known issue. I'll try to solve it soon.
