### ISSUE TITLE
List (grouped style) and Form view broken after keyboard dismiss

### ISSUE THREAD

**Issue by fattidare** [hackiftekhar/IQKeyboardManager#1737]
Hi, I'm experiencing an errore when I use this library in presence of Lists (.listStyle(GroupedListStyle())) and/or Forms.
It seems to appear only on Iphone 11 emulator (never tried on real device) with landscape mode. I wonder if it is not only a problem of this specific emulator or the error is also present on real devices.

Checkout this example project: 
[testKeyboardManager.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/4820771/testKeyboardManager.zip)

**Steps to reproduce the behavior:**
1. Create a list with GroupedListStyle or a Form
2. Create some children (doesn't matter the content)
3. Tap on a TextField which require the view to move up to be shown with the keyboard open
4. Dismiss the keyboard
5. See error: every list/form children goes out of bounds (but the row graphic is kept)

**Expected behavior**
The children view should return to their original sizes

### Versions
**Xcode:** 11.5
**Mac OS:** 10.15.5
**Simulator/Device:** Only on simulator (never tried on real device)
**Simulator/Device Name:** iPhone 11 (not experienced on other kind of emulators)
**Library Version:** 6.5.5 (tried down to 6.5.0)
**Layout mode:** SwiftUI
**iOS Deployment target:** >= 13.0

**Comment by hackiftekhar** [comment]
I'm not seeing any problems with the demo while dismissing the keyboard. Can you please share screenshot and pointing out what the issue is?
