### ISSUE TITLE
My Content is overlapping on navigation bar please help?

### ISSUE THREAD

**Issue by Zeeshan90** [hackiftekhar/IQKeyboardManager#1738]

**Comment by bdjurisic** [comment]
Same here, and it is very strange that this happens every other time when the keyboard is dismissed. The whole safe view goes like 10-15px in under status bar.

**Comment by silaluka** [comment]
@Zeeshan90 @bdjurisic 
You should try to use `.becomeFirstResponder` method in `viewDidAppear` like this:
```
override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(false)
        _ = textField.becomeFirstResponder()
}
```
This trick worked for me.

**Comment by hackiftekhar** [comment]
If you try to call becomeFirstResponder from viewDidLoad. Then it will not behave correctly.
