### ISSUE TITLE
Black line between the keyboard and text field

### ISSUE THREAD

**Issue by malsamari** [hackiftekhar/IQKeyboardManager#1740]
**Describe the bug**
Black line between the keyboard and text field

**Screenshots**
![Imgur](https://i.imgur.com/sD0rqwg.png)

**Demo Project**
A complete working demo project can be found here:
https://github.com/appbrewery/Flash-Chat-iOS13-Completed

### Versions
**Xcode:** 11.5
**Mac OS:** 11.15.5
**Simulator/Device Name:** All I guess, but I tried iPhone 11 Pro Max, SE
**Library Version:** 6.5.5 / 6.5.0

**Comment by hackiftekhar** [comment]
There is a property `keyboardDistanceFromTextField` which you can set to maintain distance between textField and the keyboard. Default is 10, problably reducing it some point should work for you.
