### ISSUE TITLE
Click on textfiled getting Constraints error for IQKeyboardToolBar

### ISSUE THREAD

**Issue by mahesh789** [hackiftekhar/IQKeyboardManager#1741]
Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
[LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSAutoresizingMaskLayoutConstraint:0x600000371c70 h=--& v=--& _UIToolbarContentView:0x7fee31575c50.height == 0   (active)>",
    "<NSLayoutConstraint:0x6000003ddb30 V:|-(0)-[_UIButtonBarStackView:0x7fee31577b80]   (active, names: '|':_UIToolbarContentView:0x7fee31575c50 )>",
    "<NSLayoutConstraint:0x6000003ddae0 _UIButtonBarStackView:0x7fee31577b80.bottom == _UIToolbarContentView:0x7fee31575c50.bottom   (active)>",
    "<NSLayoutConstraint:0x600000372490 UIButtonLabel:0x7fee315a2670'Done'.centerY == _UIModernBarButton:0x7fee315a05d0'Done'.centerY + 0.5   (active)>",
    "<NSLayoutConstraint:0x600000370dc0 'TB_Baseline_Baseline' _UIModernBarButton:0x7fee315a05d0'Done'.lastBaseline == UILayoutGuide:0x600001946300'UIViewLayoutMarginsGuide'.bottom   (active)>",
    "<NSLayoutConstraint:0x600000370e10 'TB_Top_Top' V:|-(>=0)-[_UIModernBarButton:0x7fee315a05d0'Done']   (active, names: '|':_UIButtonBarButton:0x7fee3159f3d0 )>",
    "<NSLayoutConstraint:0x600000370f50 'UIButtonBar.maximumAlignmentSize' _UIButtonBarButton:0x7fee3159f3d0.height == UILayoutGuide:0x60000195e920'UIViewLayoutMarginsGuide'.height   (active)>",
    "<NSLayoutConstraint:0x6000003ddbd0 'UIView-bottomMargin-guide-constraint' V:[UILayoutGuide:0x60000195e920'UIViewLayoutMarginsGuide']-(0)-|   (active, names: '|':_UIButtonBarStackView:0x7fee31577b80 )>",
    "<NSLayoutConstraint:0x600000370d20 'UIView-bottomMargin-guide-constraint' V:[UILayoutGuide:0x600001946300'UIViewLayoutMarginsGuide']-(16)-|   (active, names: '|':_UIButtonBarButton:0x7fee3159f3d0 )>",
    "<NSLayoutConstraint:0x6000003dddb0 'UIView-topMargin-guide-constraint' V:|-(0)-[UILayoutGuide:0x60000195e920'UIViewLayoutMarginsGuide']   (active, names: '|':_UIButtonBarStackView:0x7fee31577b80 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x600000372490 UIButtonLabel:0x7fee315a2670'Done'.centerY == _UIModernBarButton:0x7fee315a05d0'Done'.centerY + 0.5   (active)>

**Comment by FitBoy** [comment]
我的和你一样

**Comment by shijian123** [comment]
同样遇到这个问题，怎么解决？？

**Comment by hackiftekhar** [comment]
enabling Autocorrection usually gives these issues, but it's not due to library.
