### ISSUE TITLE
Previous next button - dismisses the keyboard

### ISSUE THREAD

**Issue by Sonali2009** [hackiftekhar/IQKeyboardManager#1744]
Hello Folks,

I have a textfield in my UITableViewCell. I see the up and down arrow but when I tap on them they dismisses the keyboard rather than moving the cursor up and down. Did it happen to anyone else?

Thanks in advance.

**Comment by yasserosama07** [comment]
i have the same issue

**Comment by hackiftekhar** [comment]
Can you please share the demo project @Sonali2009 @yasserosama07 ?
