### ISSUE TITLE
WIKI on shouldPlayInputClicks out of date

### ISSUE THREAD

**Issue by tcwalther** [hackiftekhar/IQKeyboardManager#1745]
**Describe the bug**
The [wiki states](https://github.com/hackiftekhar/IQKeyboardManager/wiki/Properties-&-Functions#uisound-handling):

> **_@ property BOOL shouldPlayInputClicks_** If YES, then it plays inputClick sound on next/previous/done click. Default is NO.

However, IQKeyboardManager.swift states:
```swift
@objc public var shouldPlayInputClicks = true
```

Either change the default to false, or update the wiki accordingly :).

**Comment by hackiftekhar** [comment]
Fixed!
