### ISSUE TITLE
Textview get scroll up when tap on the textview second time

### ISSUE THREAD

**Issue by chuenwailiew** [hackiftekhar/IQKeyboardManager#1746]
**Describe the bug**
Don't know anyone face a problem that when you have a UITextView inside a UIScrollView, and the text view height is expanding according to the content and the scroll view content size will updated at the same time. The text view will get pushed up when u tap on it again. 

**To Reproduce**
1. Add a text view inside a scroll view
2. Make text view height dynamic according to content input
3. Type long text
4. Dismiss the keyboard
5. Tap on the text view to become first responder
6. Tap on the text view again and the text view will get pushed up

**Screenshots**
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/23472080/88509414-9cb0a600-d013-11ea-9f76-d16a52bf927d.gif)

Xcode: 11.6
Mac OS: 10.15.5
Library Version: 6.5.0

**Comment by ndemie** [comment]
I'm experiencing the same issue (I have the same implementation in regards to UITextView and UIScrollView) however for me the text gets put in the correct position initially and then the scrollview gets scrolled to the top (as with you after your second tap) automatically (without the second tap).

![ezgif-1-3b291d3b0912](https://user-images.githubusercontent.com/5329710/88798892-ecbf7200-d1a5-11ea-90f7-fe14556f2989.gif)

**Comment by zhoumingwu** [comment]
same too

**Comment by focuswei** [comment]
Same problem to meet

**Comment by lebaotrung93** [comment]
Same problem here
Library version : 6.5.6

**Comment by RvAgrawal** [comment]
Any solution for this?

**Comment by razan1994alali** [comment]
hello, any updates on this issue

**Comment by hackiftekhar** [comment]
If you would like to not scroll the scrollView then you could try setting scrollview.shouldIgnoreScrollingAdjustment = true. This is library variable to ignore scrolling adjustment on that particular scrollview. I hope this would solve your cases.
