### ISSUE TITLE
TextView are pushed up and slid down by the keyboard

### ISSUE THREAD

**Issue by 1071273821** [hackiftekhar/IQKeyboardManager#1748]
TextView is placed on top of tableviewCell. TextView is at a high height. If you operate on the video, part of textView will be covered by the keyboard

[重现情况.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/5039544/default.zip)

**Comment by xuau34** [comment]
Same here.
BTW, is it supposed to work on an auto-expanding textView?
