### ISSUE TITLE
Iflypad keyboard pop-up higher than system keyboard blocking input box

### ISSUE THREAD

**Issue by hwenxzhangling** [hackiftekhar/IQKeyboardManager#1749]
**Describe the bug**

**To Reproduce**
1. login
2. Click on the input box
3. Iflyte keyboard blocks input box, while the system keyboard is normal

**Expected behavior**

**Screenshots**

**Demo Project**
If applicable, add demo project.

**Comment by hackiftekhar** [comment]
@hwenxzhangling Can you please describe the issue?

**Comment by hwenxzhangling** [comment]
> @hwenxzhangling Can you please describe the issue?

Click the input box, and the Xunfei input keyboard pops up. The Xunfei input keyboard is 20 pixels higher than the existing keyboard, and then the Toolbar blocks the input field

**Comment by hwenxzhangling** [comment]
> @hwenxzhangling Can you please describe the issue?

Click the input box, and the Xunfei input keyboard pops up. The Xunfei input keyboard is 20 pixels higher than the existing keyboard, and then the Toolbar blocks the input field

**Comment by hwenxzhangling** [comment]
Click the input box, and the Xunfei input keyboard pops up. The Xunfei input keyboard is 20 pixels higher than the existing keyboard, and then the Toolbar blocks the input field

**Comment by hwenxzhangling** [comment]
Click the input box, and the Xunfei input keyboard pops up. The Xunfei input keyboard is 20 pixels higher than the existing keyboard, and then the Toolbar blocks the input field

**Comment by hwenxzhangling** [comment]
I rebuilt a demo without the problem of replicating, which may be another reason for the code in my project.
