### ISSUE TITLE
Replacement for IQLayoutGuideConstraint? Or another way to keep multiple views above the keyboard?

### ISSUE THREAD

**Issue by kevinrenskers** [hackiftekhar/IQKeyboardManager#1750]
I have a login form with 2 text fields. When you focus on the email field, the password field gets hidden by the keyboard (and its toolbar). The return key does bring you to the password field, and tapping outside of a text field dismisses the keyboard, so it's not completely unusable, but it's not very intuitive either.

It would be much better if both fields were kept in view, above the keyboard. With the old version of IQKeyboardManager where was the concept of IQLayoutGuideConstraint which was maybe useful here, but that whole thing is gone now.

Any tips? This is not a tableview nor a scrollview.

![YgUIy](https://user-images.githubusercontent.com/229384/90181944-80ea2580-ddb1-11ea-998a-911911d91080.png)

**Comment by pcKanso** [comment]
Hmm, I guess this is not possible?

**Comment by hackiftekhar** [comment]
You can set custom distance from your specific UITextView/UITextField which will solve the problem.
`textField.keyboardDistanceFromTextField = 30 // or something different`
