### ISSUE TITLE
有疑问问题，如果textView下面有按钮，弹出的键盘会遮挡按钮

### ISSUE THREAD

**Issue by hengHaibo** [hackiftekhar/IQKeyboardManager#1751]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Demo Project**
If applicable, add demo project.

### Versions
**Xcode:** x.x
**Mac OS:** xx.xx.x
**Simulator/Device:** xx.x
**Simulator/Device Name:** iPhone xx
**Library Version:** x.x.x

**Additional context**

**Comment by hackiftekhar** [comment]
You can set custom distance from your specific UITextView/UITextField which will solve the problem.
`textField.keyboardDistanceFromTextField = 30 or something different.`
