### ISSUE TITLE
IQKeyboardManager.shared.enable = false

### ISSUE THREAD

**Issue by johnchoi96** [hackiftekhar/IQKeyboardManager#1752]
**Describe the bug**
I might be missing something here: I only want to use this keyboard for only one UIView. On the view controller for this specific view, I am calling `IQKeyboardManager.shared.enable = true` in the `viewDidLoad()`. This enables the customized keyboard just fine, but when I call `IQKeyboardManager.shared.enable = false` in the `viewDidDisappear()`, it will not disable itself. Is there any other way to do this?

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/33343507/91084239-ada40580-e619-11ea-9563-146364af9039.png)

**Demo Project**
If applicable, add demo project.

### Versions
**Xcode:** 11.6
**Mac OS:** 10.15.6
**Simulator/Device:** iOS 13.6
**Simulator/Device Name:** iPhone 11
**Library Version:** 6.5.6

**Additional context**

**Comment by hackiftekhar** [comment]
You should be doing this in viewWillAppear and viewWillDisappear, not with viewDidLoad and viewDidDisappear.

**Comment by venu-nuncsys** [comment]
DispatchQueue.main.async {
                IQKeyboardManager.shared.enable = true
            }
            
            The above worked for me
