### ISSUE TITLE
keyboard is not coming when clicking on textfield.

### ISSUE THREAD

**Issue by harishthanniruios** [hackiftekhar/IQKeyboardManager#1753]
when i click on textfield only copy/paste option is coming ,keyboard is not appearing. can anyone help me in this.

**Comment by bigNiuSanMao** [comment]
the same question

**Comment by mortenholmgaard** [comment]
iOS 14?
https://github.com/hackiftekhar/IQKeyboardManager/issues/1758

**Comment by hackiftekhar** [comment]
I don't think it's related to any bug in library, it's something in your code.
