### ISSUE TITLE
Constraint violation when changing between text fields with different autocorrect settings

### ISSUE THREAD

**Issue by xsleonard** [hackiftekhar/IQKeyboardManager#1755]
**Describe the bug**
If there are two text fields in the view, each with a different autocorrectionType setting (no, yes), and we switch between them, autolayout constraint errors appear in the console.

**To Reproduce**

Create a UITableView with 2 cells, each has a UITextField, make the first UITextField autocorrectionType = YES, make the second UITextField autocorrectionType = NO.

Run the app and tap on the 2nd text field to open keyboard. Then, change focus to the first UITextField, either using the up/down arrows, or by tapping the first UITextField.

**Expected behavior**

No layout errors.

**Screenshots**

Keyboard types (with autocorrect, without autocorrect):

<img width="379" alt="Screen Shot 2020-09-12 at 6 16 53 PM" src="https://user-images.githubusercontent.com/1879136/92993437-2c5ad700-f524-11ea-9104-68c85928510f.png">
<img width="378" alt="Screen Shot 2020-09-12 at 6 16 49 PM" src="https://user-images.githubusercontent.com/1879136/92993438-2fee5e00-f524-11ea-9b18-08aeaa822da3.png">

**Demo Project**
N/A

### Versions
**Xcode:** 11.7 (11E801a)
**Mac OS:** 10.15.6
**iOS:** iOS 13.7
**Simulator/Device Name:** iPhone 11 Pro (17H22) simulator
**Library Version:** 6.5.6

**Additional context**

Layout error messages:

```
[LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x600001594aa0 'accessoryView.bottom' _UIRemoteKeyboardPlaceholderView:0x7fc36fc37200.bottom == _UIKBCompatInputView:0x7fc37137bab0.top   (active)>",
    "<NSLayoutConstraint:0x6000015dd4f0 'assistantHeight' TUISystemInputAssistantView:0x7fc371449a60.height == 45   (active)>",
    "<NSLayoutConstraint:0x6000015d1040 'assistantView.bottom' TUISystemInputAssistantView:0x7fc371449a60.bottom == _UIKBCompatInputView:0x7fc37137bab0.top   (active)>",
    "<NSLayoutConstraint:0x600001594960 'assistantView.top' V:[_UIRemoteKeyboardPlaceholderView:0x7fc36fc37200]-(0)-[TUISystemInputAssistantView:0x7fc371449a60]   (active)>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x600001594960 'assistantView.top' V:[_UIRemoteKeyboardPlaceholderView:0x7fc36fc37200]-(0)-[TUISystemInputAssistantView:0x7fc371449a60]   (active)>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
```

**Comment by xsleonard** [comment]
This also happens when swiping, which causes the word suggestion box to appear above the keyboard

**Comment by xsleonard** [comment]
I see this was reported in #1616 but closed.

The workaround to disable autocorrect is insufficient due to swiping text prediction

**Comment by hackiftekhar** [comment]
The library don't deal with the UIKeyboard internal things like frames or auto-correct or suggestion bar etc. So it should be apple's bug.
