### ISSUE TITLE
The UItableviewController in this demo is blocked in the iPhone 5s TextView input box. How to set it so that it is not blocked?

### ISSUE THREAD

**Issue by gyyxiaogao** [hackiftekhar/IQKeyboardManager#1756]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Demo Project**
If applicable, add demo project.

### Versions
**Xcode:** x.x
**Mac OS:** xx.xx.x
**Simulator/Device:** xx.x
**Simulator/Device Name:** iPhone xx
**Library Version:** x.x.x

**Additional context**

**Comment by hackiftekhar** [comment]
UITableViewController is ignored by the library because it has it's own approach to correctly show the textField above the keyboard. The demo also shows that it ignore anything related to the UITableViewController, so if it's blocking then it's Apple's bug.
