### ISSUE TITLE
IQKeyboard doesn't work on iOS 14 and the view doesn't scroll up when become first response

### ISSUE THREAD

**Issue by shayan77** [hackiftekhar/IQKeyboardManager#1758]
On iOS14 when text field or text view want to become first responder they can't scroll up the view and the textfields are still behind the keyboard
![Simulator Screen Shot - iPhone 8 - 2020-09-22 at 10 44 39](https://user-images.githubusercontent.com/10570352/93853408-b04d5580-fcc0-11ea-83d1-eb16c19f190c.png)
![Simulator Screen Shot - iPhone 8 - 2020-09-22 at 10 44 48](https://user-images.githubusercontent.com/10570352/93853431-b6dbcd00-fcc0-11ea-998b-e5693ecfaceb.png)

the text field in the bottom of view doesn't scroll up but every thing is fine in iOS 13 and 12

**Comment by MMnasrabadi** [comment]
Yes, I have this problem too. Please provide a solution

**Comment by Kedar-27** [comment]
Critical issue. Please fix this asap @hackiftekhar

**Comment by hasanogliali** [comment]
I have same problem also. Can you please fix this problem @hackiftekhar

**Comment by zhangyakai** [comment]
Yes, I have this problem too. Please provide a solution

**Comment by Q14** [comment]
Yes, I have this problem too. Please provide a solution

**Comment by a758209678** [comment]
Yes, I have this problem too. Please provide a solution

**Comment by Kedar-27** [comment]
@hackiftekhar any updates on this issue? ETA?

**Comment by tthejus** [comment]
@hackiftekhar Any updates on this ?

**Comment by a758209678** [comment]
> Yes, I have this problem too. Please provide a solution

I found the reason for my side, because I added a view on tabbar with Masonry, i changed it to frame resolved the question. This problem only occurs on ios14

**Comment by yuanpc** [comment]
> > Yes, I have this problem too. Please provide a solution
> 
> I found the reason for my side, because I added a view on tabbar with Masonry, i changed it to frame resolved the question. This problem only occurs on ios14

Thanks, I solved the problem

**Comment by hamedpooramiri** [comment]
> > Yes, I have this problem too. Please provide a solution
> 
> I found the reason for my side, because I added a view on tabbar with Masonry, i changed it to frame resolved the question. This problem only occurs on ios14

I have this problem, when I use tabbar my viewContollers view not scroll to up when the textfields becomes first responder ,
can explain in more detail , any suggestion why this happen in iOS 14 ?!

**Comment by hamedpooramiri** [comment]
for me this behavior accrue when I use hostingViewController with UIKit viewController  in navigationStack , when I remove hostingController every thing is okay, any suggestion ?

**Comment by sujeking** [comment]
I have this problem too, On iOS14 click "Done" ,the keyboard do not dismiss ,It not Work,but On iOS13 is worked

**Comment by tiennv157** [comment]
I have this problem too. Then I push all subviews into a UIScrollView, it works!
