### ISSUE TITLE
Toolbar not showing in iOS 14

### ISSUE THREAD

**Issue by Pavan-Unikwork** [hackiftekhar/IQKeyboardManager#1759]
**Describe the bug**
While tapping on TextView some time Toolbar with Done button is not appear in iOS 14

**To Reproduce**
I could not found exact scenario when it happen but Keyboard with toolbar is working fine in TextField but while editing in TextView some time Toolbar is not appear.

**Expected behavior**
I expect every time it should be appear.

**Screenshots**
![Screenshot 2020-09-23 at 10 20 21](https://user-images.githubusercontent.com/58810639/93968191-a726bc00-fd86-11ea-9e94-0fd51632e5fc.png)
![Screenshot 2020-09-23 at 10 20 44](https://user-images.githubusercontent.com/58810639/93968198-aa21ac80-fd86-11ea-8aa8-5431ef5b3c61.png)

.

### Versions
**Xcode:** 11.3
**Mac OS:** 10.15
**Simulator/Device Name:** iPhone XS
**Library Version:** 6.5.6

**Comment by tahamuneeb** [comment]
Experiencing same, issue

**Comment by alihanaktay** [comment]
Same issue.

**Comment by wolimomomo** [comment]
Same issue.

**Comment by vijay0964** [comment]
+1

**Comment by arunlj561** [comment]
Same issue, any solution or work around?

**Comment by umangbista2** [comment]
Any Solution?

**Comment by PrashanthPasi** [comment]
Same issue ☹️ Any solution ?

**Comment by hackiftekhar** [comment]
Not sure what might be the issue, however, I'm able to see it correctly working in iOS 15.
