### ISSUE TITLE
iOS 14 Date Picker empty space

### ISSUE THREAD

**Issue by N0t2Day** [hackiftekhar/IQKeyboardManager#1760]
**Describe the bug**
In iOS 14 appear new date picker and new bug

**To Reproduce**
1. Set date picker with picker mode 'date' as input view to TextField
2. Become first responder

### Versions
**Xcode:** 12.0.1
**Mac OS:** Catalina 

**Simulator/Device:** all with iOS 14
**Library Version:** latest

<img width="456" alt="2020-10-06" src="https://user-images.githubusercontent.com/23290834/95203729-d3f9bb00-07eb-11eb-83cb-e3d6e9d6e198.png">

**Comment by rocxteady** [comment]
There is new property to set the old style date picker but it's still not working.
preferredDatePickerStyle = .wheel
![ss](https://user-images.githubusercontent.com/3393424/95330533-58fad800-08b1-11eb-9f79-22d69747986f.jpg)

**Comment by rocxteady** [comment]
This solution helped me: https://developer.apple.com/forums/thread/651546?answerId=624905022#624905022

**Comment by AntonioFM92** [comment]
I have the same problem. After reading the last URL posted by @rockteady I have found the solution by changing the preferredDatePickerStyle. 

By default the automatic style is `.compact`, and this is showed wrong...  So my solution has been to apply the `.wheels` style:

`if #available(iOS 13.4, *) {
            datePicker.preferredDatePickerStyle = .wheels
        }`
