### ISSUE TITLE
Incorrectly positioned after orientation changes in iOS 14

### ISSUE THREAD

**Issue by KasunNimantha** [hackiftekhar/IQKeyboardManager#1761]
My app restricts orientation support to portrait except one view controller (Image gallery). So If I go to that specific view controller and rotate the device to landscape and dismiss the view and go back to my previous view controller it rotates back to portrait. After that, if I click on a UITextField keyboard will appear correctly but the keyboard Toolbar position is incorrect. 

This issue only comes in iOS 14. I tested this scenario on iOS 13 and it works fine

![Simulator Screen Shot - iPhone 11 Pro - 2020-10-14 at 11 07 50](https://user-images.githubusercontent.com/1871774/95948160-ab864800-0e0d-11eb-8a3a-20c2e911e92d.png)

1). (A) View Controller (support portrait only) --------->  ( B) View Controller(support all orientations)
2). Dismiss B view controller in (landscape) ------ > A Viewcontroller rotate back to Portrait 
3) Click a UITextField on VIew controller (A)
4) keyboard will appear in portrait mode but the keyboard toolbar Incorrectly positioned

**Comment by SFMore** [comment]
I have the same problem

**Comment by ClaudeLi** [comment]
I have the same problem too

**Comment by FycGitHub** [comment]
I have the same problem too

**Comment by sunqishuang** [comment]
I have the same problem too

**Comment by sunqishuang** [comment]
> 我也有同样的问题

How did you solve this problem

**Comment by ClaudeLi** [comment]
I solved the problem, setting the  landscape controller modalPresentationStyle = .overFullScreen

**Comment by sunqishuang** [comment]
> 我解决了这个问题，设置了景观控制器modalPresentationStyle = .overFullScreen

我设置了,不行啊,大兄弟,看你应该是同胞啊

**Comment by ClaudeLi** [comment]
> > 我解决了这个问题，设置了景观控制器modalPresentationStyle = .overFullScreen
> 
> 我设置了,不行啊,大兄弟,看你应该是同胞啊

应该是iOS 14的系统问题，我在h5的<input>标签也遇到了这个问题，发现当设置.fullScreen的横屏控制器(仅支持横屏)打开 再返回时UITextEffectsWindow还处于横屏状态，设置.overFullScreen 时，再返回时UITextEffectsWindow变回竖屏。

如果你打开的控制器支持多个方向，处于横屏时返回遇到这个问题，需要强制转回竖屏再返回 尝试使用下面代码可以试下，我这边是👌的
    NSInvocation *invocation = [NSInvocation invocationWithMethodSignature:[UIDevice instanceMethodSignatureForSelector:@selector(setOrientation:)]];
    invocation.selector = NSSelectorFromString(@"setOrientation:");
    invocation.target = [UIDevice currentDevice];
    int initOrientation = UIDeviceOrientationPortrait;
    [invocation setArgument:&initOrientation atIndex:2];
    [invocation invoke];
    [self dismissViewControllerAnimated:YES completion:nil];

**Comment by MakeForce** [comment]
> I have the same problem
@KasunNimantha @FycGitHub @ClaudeLi  @SFMore @sunqishuang 
```objc
//AppDelegate.h
@interface AppDelegate : UIResponder <UIApplicationDelegate>
......
@property (assign, nonatomic) BOOL isLandscape;
......
@end

//AppDelegate.m
......
- (UIInterfaceOrientationMask)application:(UIApplication *)application supportedInterfaceOrientationsForWindow:(UIWindow *)window {
    if (self.isLandscape == YES) {
        return UIInterfaceOrientationMaskLandscape;
    }
    return UIInterfaceOrientationMaskPortrait;
}
......
```

- 1. A view controller (support portrait only)  
- 2. B view controller (support landscape orientation)
- 3. A view controller present B view controller  
   ```objc
   //AViewController.m
   .....
   - (void)presentViewController {
        BViewController * vc = [[BViewController alloc] init];
        ((AppDelegate *)[UIApplication sharedApplication].delegate).isLandscape = YES;
        [self presentViewController:vc animated:YES completion:nil];
    }
   ```
- 4. B view contoller didmiss  
    ```objc
    //BViewController.m
    ......
   - (void)dismissViewController {
        ((AppDelegate *)[UIApplication sharedApplication].delegate).isLandscape = NO;
        [self dismissViewControllerAnimated:YES completion:nil];
    }
   ```

**Note:** should changed the window orientation，not the viewController orientation

After iOS 14 `UITextEffectsWindow` orientation equivalent to the App keyWindow orientation

**Comment by hackiftekhar** [comment]
It's related to something with the iOS, the library doesn't manipulate any frame with inputAccessoryView itself. So something this needs to be fixed from Apple side.
