### ISSUE TITLE
In version 12.4.8, IQTextView has the wrong placeholder color

### ISSUE THREAD

**Issue by tongningqiushuijianliuxing** [hackiftekhar/IQKeyboardManager#1762]
`#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 130000
            if (@available(iOS 13.0, *)) {
                _IQ_PlaceholderLabel.textColor = [UIColor systemGrayColor];
            } else
        #endif
            {
        #if __IPHONE_OS_VERSION_MIN_REQUIRED < 130000
                _IQ_PlaceholderLabel.textColor = [UIColor lightTextColor];
        #endif
            }`
Error: TextColor is white in version 12.4.8.
Solution: I did not judge the version and assigned the color to systemGrayColor.

**Comment by hackiftekhar** [comment]
Not sure what might be exact issue, but I removed some compile time validation here.
