### ISSUE TITLE
Bug : Apple auto save password 

### ISSUE THREAD

**Issue by eagleonefight** [hackiftekhar/IQKeyboardManager#1763]
https://stackoverflow.com/questions/60804377/disable-save-password-action-sheet-when-exiting-uiviewcontroller

iOS will automatically present an alert to save password if everything setup correctly. Here the compatibility checklist -
* 		Tag fields with correct content types
* 		Remove login fields from the view hierarchy
* 		Clear login fields only after removing from the hierarchy
* 		Check that AutoFill saved to the correct domain

this action sheet is present by _**_SFAppPasswordSavingViewController**_  ，when present action sheet ,  Keyboard appearance notification also send。

when disbale this action sheet , iqkeyboard toolbar will abnormal:
  
![image](https://user-images.githubusercontent.com/13845910/96694336-ee6e8f80-13ba-11eb-9d10-194453a5e2f0.png)

I think this is probably a bug from Apple, but can you make some changes to this IQKeyboardManager ? This problem has been around since ios12

**Comment by ijeffery3** [comment]
how to fix it ?

**Comment by hackiftekhar** [comment]
Can you please share a demo project with me?

**Comment by ijeffery3** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by hackiftekhar** [comment]
@ijeffery3 Can you please provide me a demo project?

**Comment by ijeffery3** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
