### ISSUE TITLE
May be a question on the iOS14

### ISSUE THREAD

**Issue by zhoupIT** [hackiftekhar/IQKeyboardManager#1766]
**Describe the bug**
When Apple review our app,they crashed every time.But the bug can not reappear on my device.I got the crash log,i see the reason may be IQKeyboardManager. Is anyone had the same question?My IQKeyboardManager is the latested 6.5.6.

**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="917" alt="WX20201102-001648@2x" src="https://user-images.githubusercontent.com/14780546/97808425-bbbd7480-1ca1-11eb-877b-ffa7d835ffeb.png">

**Demo Project**
If applicable, add demo project.

### Versions
**Xcode:** 12.1
**Mac OS:** 10.15.5
**Simulator/Device:** xx.x
**Simulator/Device Name:** iPhone xx
**Library Version:** 6.5.6

**Additional context**

**Comment by zinkLin** [comment]
i had the same question

**Comment by hackiftekhar** [comment]
I don't know what might be the issue until I get more information.
