### ISSUE TITLE
Navigation Bar is Scrolling Up I have add a tableview. Inside it i have add a headerview and when i click on IQKeyBoardToolBar Up Down Button it scrollUp the navigation view upwards.

### ISSUE THREAD

**Issue by vinen05** [hackiftekhar/IQKeyboardManager#1768]
i am using iphone 7 and os version is 13.3.1. i have off the user interaction of three textfield.

Here is video of the issue
https://lh3.googleusercontent.com/7FnNTeurqyrcDc7XY6Fxd7eFjHSrvqVSd7OVfjCBo7VXHtagJEB_Twm-SaLaqYtd2e6ExXC2VAuJ2Q=m18

**Comment by hackiftekhar** [comment]
I don't think it should happen. Can you please share a demo project with me?
