### ISSUE TITLE
remove Done button from specific textfield

### ISSUE THREAD

**Issue by Machabeli** [hackiftekhar/IQKeyboardManager#177]
Is it possible to hide or remove Done button from keyboard for specific textfield?

**Comment by hackiftekhar** [comment]
You can set textField.inputAccessoryView = [[UIView alloc] init]; to not
show toolbar over specific textField.

On Wednesday, March 11, 2015, Machabeli <notifications@github.com> wrote:

> Is it possible to hide or remove Done button from keyboard for specific
> textfield?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackiftekhar/IQKeyboardManager/issues/177>.
>


-- 
Sent from My iPhone

**Comment by Machabeli** [comment]
Thanks

**Comment by ram-vinay-yadav** [comment]
Thanks , Working

**Comment by valivarthy** [comment]
when a textview ebabled = false  and when i am selecting my fingure on the typed text the Done button is viewing at the bottom can you check it i am 
![ios-cinrep-07](https://cloud.githubusercontent.com/assets/3027025/25518318/e6fc66e0-2c10-11e7-9b4f-4e490290bb1a.png)

**Comment by gopaldevra** [comment]
Thanks @hackiftekhar . It is very cool utility.
Could you please tell me how to hide the done button only, not the previous and next button.

**Comment by mding5692** [comment]
Swift 3+ version:

textfield.inputAccessoryView = UIView()

**Comment by niravkotecha** [comment]
objective-c
textField.inputAccessoryView = [[UIView alloc] init];
give error because its readonly property

**Comment by cruz0** [comment]
let v = myTextField.inputAccessoryView as? IQToolbar
        v?.doneBarButton.tintColor = UIColor.clear
        v?.doneBarButton.isEnabled = false

**Comment by hackiftekhar** [comment]
Actually this looks like iOS related issue because the toolbar becomes part of keyboard and it's upto iOS to hide keyboard and toolbar. If it's not hiding it then it's something iOS logics and library can't handle this case. btw I also get same issue but there is no solution since we can't handle it at our end.

**Comment by amoradiya** [comment]
> when a textview ebabled = false and when i am selecting my fingure on the typed text the Done button is viewing at the bottom can you check it i am ![ios-cinrep-07](https://cloud.githubusercontent.com/assets/3027025/25518318/e6fc66e0-2c10-11e7-9b4f-4e490290bb1a.png)

Do you get any solution on this ?
