### ISSUE TITLE
largeTitles navigation bars offset issue

### ISSUE THREAD

**Issue by jerometonnelier** [hackiftekhar/IQKeyboardManager#1775]
Describe the bug
When navigationBar prefersLargeTitles set true, the scrollView will show redundant empty area after keyboard dismiss.

To Reproduce

Scroll to bottom to let view controller title become small.
tap textField to show keyboard.
tap outside to dismiss keyboard.
Issue occur.

If you want to test with the example app, use the CollectionViewDemoController, change 20 rows to 10 and add
```
override func viewDidLoad() {
        super.viewDidLoad()
        if #available(iOS 11.0, *) {
            navigationController?.navigationBar.prefersLargeTitles = true
        }
    }
```

After tapping the last textfield, you will see that the scrollview does not restores the large title.

Here are 3 screenshots from my app : the controller, with the keyboard manager in action, and the bug.
You can see on the last image that the bottom is shifted (the button is out of the screen) and an extra space is added at the top (corresponding to the large title I guess) and the large title is not restored
![IMG_0C1CB3F31641-1](https://user-images.githubusercontent.com/1484522/100432595-19bf5b00-309a-11eb-8866-8275fe55a0fa.jpeg)
![IMG_0C1CB3F31641-2](https://user-images.githubusercontent.com/1484522/100432629-25ab1d00-309a-11eb-86e2-3ac91f385422.jpeg)
![IMG_0C1CB3F31641-3](https://user-images.githubusercontent.com/1484522/100432649-2cd22b00-309a-11eb-91f0-ca9d547d12b5.jpeg)

**Comment by Syed-Sahab** [comment]
Try to Add a UIView in storyboard with height of 5, just for change of Large Nav size with the scrolling, when you add the view between Large Navigation bar and scrollView/tableView it will prevent to stop scrolling of Large Navigation Bar. I tried it and it will work Fine.

**Comment by jerometonnelier** [comment]
Ok but I don't want .always for largeTitleMode, I want it to collapse when we scroll :-/
