### ISSUE TITLE
TableView Header Cell hide when press done button on toolbar

### ISSUE THREAD

**Issue by SohaibSiddique** [hackiftekhar/IQKeyboardManager#1776]
**Describe the bug**
I added a table view cell in tableView Header, and a textField in table view cell, when I press the Done button on the keyboard toolbar the table view cell hide.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Demo Project**
not available

### Versions
**Xcode:** 12.2
**Mac OS:** 11.0.1
**Simulator/Device:** 13.5
**Simulator/Device Name:** iPhone 11 pro
**Library Version:** 6.5.0

**Additional context**

**Comment by hackiftekhar** [comment]
Can you please share any video or the demo project of the issue?

**Comment by AdnanAli285** [comment]
I am also facing this issue.
any solution @SohaibSiddique @hackiftekhar
