### ISSUE TITLE
It is recommended to add custom return gesture handling

### ISSUE THREAD

**Issue by QuintGao** [hackiftekhar/IQKeyboardManager#1777]
**Describe the bug**
There is a problem with custom return gesture processing

**Expected behavior**
I customized the navigation bar return gesture, after the operation of the gesture back to the original position, the return will be a problem，After looking at the code, I found that only the system return gesture has been processed internally, so It is recommended to add attributes to handle the custom gesture

**Screenshots**
![image](https://user-images.githubusercontent.com/13514024/102050436-cb41e880-3e1d-11eb-9a59-dc3f2d0c4439.png)

![image](https://user-images.githubusercontent.com/13514024/102050238-62f30700-3e1d-11eb-9fa5-8af0e1cc12e2.png)

### Versions
**Xcode:12.2
**Mac OS:11.1
**Simulator/Device:14.2
**Simulator/Device Name: iPhone 12
**Library Version:6.5.6

**Comment by hackiftekhar** [comment]
It's actually a rare scenario to add a custom navigation bar return gesture. This does not look like the case for 99.9% of users. I would suggest you fork the library and do the customizations for your need. :)
