### ISSUE TITLE
strange behavior in iOS14

### ISSUE THREAD

**Issue by Elephant-Jhon** [hackiftekhar/IQKeyboardManager#1778]
Hi, i'm having a strange behavior when my UITextField is member of a UIViewController inside a UIPageViewController, but this behavior just appear after iOS14

like this：https://cloud.githubusercontent.com/assets/2786374/4957875/afc0b09e-66a8-11e4-94b2-3f89e1668af0.gif

**Comment by hackiftekhar** [comment]
I think this should not happen. Are you sure you are using the latest version of the library?

**Comment by Elephant-Jhon** [comment]
sure, and. this will happen with masonry but it worked with frame 
this question just appear after iOS14

**Comment by Elephant-Jhon** [comment]
![image](https://user-images.githubusercontent.com/20549179/102840176-33578680-443d-11eb-8862-add53d3f6484.png)
this is my latest version

**Comment by thedonat** [comment]
Hello, I have the same issue. any solution for this problem ?

**Comment by hackiftekhar** [comment]
Can you please share the demo project. Since it shouldn't happen.
