### ISSUE TITLE
IQKEYBOARD Navigation issue

### ISSUE THREAD

**Issue by Daffodil-IOS-Developer** [hackiftekhar/IQKeyboardManager#178]
I have used IQkeyboard in my project.
Everything is working fine but when i reached at last text field the arrow at the top for navigation between fields disappears.
Thanks in advance for help.

**Comment by mythodeia** [comment]
can you replicate this in the demo project?

**Comment by Daffodil-IOS-Developer** [comment]
Hi Konstantinos K.,

Thanks for the reply

I have attached some screenshots which clearly tells you the problem.

please find the screenshots in the attachment.

Thanks & Regards,
Akshay Agrawal.

On Thu, Mar 12, 2015 at 6:02 PM, Konstantinos K. <notifications@github.com>
wrote:

> can you replicate this in the demo project?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackiftekhar/IQKeyboardManager/issues/178#issuecomment-78471105>
> .
>



-- 
Feel Consistency

**Comment by mythodeia** [comment]
@Daffodil-IOS-Developer 
no attachments found in your post. Did you try the sample project? Did you find the error there as well?

**Comment by Daffodil-IOS-Developer** [comment]
sorry for inconvenience
Please find the images again.
![ios simulator screen shot 12-mar-2015 6 30 40 pm](https://cloud.githubusercontent.com/assets/11440204/6618932/b9fc4fa4-c8ec-11e4-8ba0-2a44ce88cf22.png)
![ios simulator screen shot 12-mar-2015 6 30 47 pm](https://cloud.githubusercontent.com/assets/11440204/6618941/c668cefc-c8ec-11e4-93a9-01b0ea5a7a7c.png)
![ios simulator screen shot 12-mar-2015 6 30 51 pm](https://cloud.githubusercontent.com/assets/11440204/6618947/cdc640d0-c8ec-11e4-9878-f2e48c5d1621.png)

**Comment by mythodeia** [comment]
@Daffodil-IOS-Developer 
Can you please update to the latest version and see if that works for you?
If you already have the latest version then please test the sample project and see if you can replicate the issue.
if the issue does not occur on the sample project then please provide your own sample so we can test and debug the error.
thanks

**Comment by hackiftekhar** [comment]
@Daffodil-IOS-Developer any updates?

**Comment by Daffodil-IOS-Developer** [comment]
Hi,

Sorry for the delay in response.

I did the same thing in a demo project and everything works fine.
I dont know what is the issue in my previous project.



On Fri, Apr 3, 2015 at 11:49 PM, Mohd Iftekhar Qurashi <
notifications@github.com> wrote:

> Closed #178 <https://github.com/hackiftekhar/IQKeyboardManager/issues/178>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackiftekhar/IQKeyboardManager/issues/178#event-272885051>
> .
>



-- 
Feel Consistency

**Comment by hackiftekhar** [comment]
So may be there were some view hierarchy issue in your previous project.

**Comment by Daffodil-IOS-Developer** [comment]
Yes,I also think so...

On Sun, Apr 5, 2015 at 9:17 AM, Mohd Iftekhar Qurashi <
notifications@github.com> wrote:

> So may be there were some view hierarchy issue in your previous project.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackiftekhar/IQKeyboardManager/issues/178#issuecomment-89710990>
> .
>



-- 
Feel Consistency
