### ISSUE TITLE
pod oc最新版本，数字键盘变形，英文键盘没有按键

### ISSUE THREAD

**Issue by wuwuli** [hackiftekhar/IQKeyboardManager#1780]
我昨天重新pod最新的IQKeyboard,在iOS14.2系统上，一开始运行的时候很正常，退回后台几分钟再进入，数字键盘会变形，英文键盘字母按键没有了。
在iOS 12.2上，一运行，数字键盘就是变形的，英文键盘没有了

**Comment by hackiftekhar** [comment]
The library doesn't manipulate the iOS native keyboard so it doesn't look to be from library.
