### ISSUE TITLE
UITableView inside Container View, not scrolled at right position while editing inside cell

### ISSUE THREAD

**Issue by bhaveshbc** [hackiftekhar/IQKeyboardManager#1781]
**Describe the bug**
IqKeyboard manager not worked properly for container view. I have a container view controller that contains ViewController with tableView.when I try to edit textFiled inside Cell, cell become invisible and Iqkeyboard manager scroll the tableView to next Cell.

**To Reproduce**
1. Go to Demo Swift App
2. Click on ScrollView.storyboard, find viewController with storybordId: TableViewContainerViewController
3. Set containerView Top Constraint to 250
4. run App on a small device(Iphone 5s, SE)

**Expected behavior**
editing cell should be visible and Tableview ContentOffset should set to editing cell, not next Cell.

**Screenshots**

https://user-images.githubusercontent.com/26791435/103200246-dc592200-4912-11eb-81d1-70fd2f4cc9dd.MP4

**Demo Project**
If applicable, add demo project.

### Versions
**Xcode:** 12.2
**Mac OS:** 11.0.1
**Simulator/Device:** Device
**Simulator/Device Name:**Iphone SE 1'st genration
**Library Version:**6.5.0

**Comment by hackiftekhar** [comment]
This is because the keyboard distance from textfield is set to 10 probably
