### ISSUE TITLE
IQKeyboardManager not working with iPhone 11

### ISSUE THREAD

**Issue by duyhct** [hackiftekhar/IQKeyboardManager#1782]
I used the lastest version of this library via pod, it's working fine on almost iPhone, except iPhone 11. I have 1 textfield on the bottom area of device and when i tap on this, the keyboard show but the textfield not slide up (you can see my image). Have anyone get this issue?

![Untitled](https://user-images.githubusercontent.com/2231401/103211813-cc096d00-493b-11eb-81b2-512493523554.png)

![Untitled1](https://user-images.githubusercontent.com/2231401/103211818-d0358a80-493b-11eb-873d-0939e11931aa.png)

**Comment by duyhct** [comment]
@hackiftekhar Can you support for me??

**Comment by afeng159** [comment]
is useful way for the question?

**Comment by duyhct** [comment]
> is useful way for the question?

You can try this: add all objects into the scrollview

**Comment by hackiftekhar** [comment]
Looks like you are trying to implement something like chat. I would suggest to implement all the things manually here.
