### ISSUE TITLE
IQTextView ran on iPhone12 and crashed

### ISSUE THREAD

**Issue by 616900857** [hackiftekhar/IQKeyboardManager#1783]
**Describe the bug**
When input exceeds the view display area, the program enters a loop
It crashes inside the refreshPlaceholder function

![image](https://user-images.githubusercontent.com/8704959/103600618-d41c6a80-4f42-11eb-8beb-96216cbaf6aa.png)

### Versions
Xcode：12.2
Mac OS：10.15.6
Device：14.2.1

Device Name：iPhone 12
Library Version：6.5.6

**Comment by gyyxiaogao** [comment]
I had the same problem, but you solved it

**Comment by zhang10271027** [comment]
I used pod to download version 6.5.6, but the code was still old, could you please update the code to a new version?
