### ISSUE TITLE
Keyboard toolbar does not localise until app restarts

### ISSUE THREAD

**Issue by aledap** [hackiftekhar/IQKeyboardManager#1785]
When the app language is changed, the tool bar "Done" button is not localised until the app completely restarts. For eg, if the language is currently "en", when changed to "ar", the tools bar still shows up with "Done" in English. When the app is completely restarted, it shows up in the correct language. The root of the app is reset after the language is changed.

**Before app restart:**

<img width="400" alt="Screenshot 2021-01-07 at 3 46 12 PM" src="https://user-images.githubusercontent.com/57295019/103883973-bcd6ac00-50ff-11eb-8b0d-46abff75e7bd.png">

**After app restart:**

<img width="407" alt="Screenshot 2021-01-07 at 3 49 31 PM" src="https://user-images.githubusercontent.com/57295019/103884157-fc9d9380-50ff-11eb-9993-8df637183d56.png">

### Versions
**Xcode:** 12.01
**Device:** 14.0
**Device Name:** iPhone SE
**Library Version:** 6.5.6

**Comment by SyedIsmailAhamed** [comment]
IQKeyboardManager.shared.toolbarDoneBarButtonItemText = "button.done".localized
This should work regardless of app state.

**Comment by hackiftekhar** [comment]
Any iOS app native components doesn't support on the fly locale change, app must be restarted to take effect. However you could do the above mention trick to at least localize the done button text.
