### ISSUE TITLE
UITextField is not avoiding keyboard If its in a UITableViewCell on iOS 14

### ISSUE THREAD

**Issue by AfiqRamli** [hackiftekhar/IQKeyboardManager#1786]
**Describe the bug**
UITextField is not avoiding keyboard If its in a UITableViewCell on iOS14

**To Reproduce**
1. Tap on a UITextField inside a UITableViewCell (iOS 14)
2. TextField will be hidden behind the keyboard

**Expected behavior**
TableView should adjusted the view frame to display the UITextField

**Screenshots**
![UITableViewIssues](https://user-images.githubusercontent.com/12848304/104145832-86e93e80-5403-11eb-937b-ce2ef02226bc.gif)

### Versions
**Xcode:** 12.2
**Simulator/Device:** 14.2
**Simulator/Device Name:** iPhone 12Pro
**Library Version:** 6.5.6

**Comment by afeng159** [comment]
你解决了吗

**Comment by RenShengBaiTai** [comment]
iOS 14 确实不行, 估计系统改了什么东西

**Comment by Jayxiang** [comment]
demo 有问题吗？如何复现？

**Comment by vipinsaini0** [comment]
Any update on this issue?

**Comment by hackiftekhar** [comment]
Can someone share a demo project here?
