### ISSUE TITLE
On iPhone XS Max My TextField is of type Secure Entry. When click on textField Keyboard does not appears. 

### ISSUE THREAD

**Issue by kumarlav0** [hackiftekhar/IQKeyboardManager#1787]
On iPhone XS Max, On UI I have taken TextField is of type Secure Entry. When click on textField Keyboard does not appear. 
a blank View show instead of a keyboard. And after a few seconds, Keyboard automatically appears.
![Skype_Picture_2021_01_08T15_09_52_723Z](https://user-images.githubusercontent.com/58595312/104282619-5540a800-54d5-11eb-8575-9290e5c557b6.jpeg)

**Comment by hackiftekhar** [comment]
Looks like the issue doesn't belong to the library since the library doesn't manipulate any UI related to the keyboard display. It must be something related to the iOS itself.
