### ISSUE TITLE
sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.

### ISSUE THREAD

**Issue by furkanvijapura** [hackiftekhar/IQKeyboardManager#1788]
### Throw error without using IQKeyboardManager framework in Share app extension 

**Error**
`sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.`

**To Reproduce**

1. Go to 'Add **Share Extension**'
2. Add some pod-like 
   
```
target 'My-app' do
  **# Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!**




pod 'Alamofire'
pod 'SwiftyJSON'


#Crash analitics
pod 'Firebase/Analytics'
pod 'Firebase/Crashlytics'
#pod "WordPress-Aztec-iOS"

  target 'NoteAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NoteAppUITests' do
    # Pods for testing
  end
  
  target 'Share extension' do
    pod 'Alamofire'
    pod 'SwiftyJSON'
  end
  
end
```
3. Install Pod 
4. Restart Xcode and Rebuild the project 

OUTPUT: error
**sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.**

error file name : IQKeyboardManager.m

screenshot 
![Screenshot 2021-01-13 at 11 43 07 AM](https://user-images.githubusercontent.com/30076950/104414237-f131e880-5595-11eb-8d46-56fa18b30058.png)

### Versions
**Xcode:** 11.3.1 (11C505)
**Mac OS:** 10.14.6 (18G6032)
**Simulator/Device:** Any
**Simulator/Device Name:** iPhone 7/8/11/12
**Library Version:** 'IQKeyboardManager' , '~> _Not added_'

**Expected behavior**
_**Need clean build without any error**_ 

Please need help for resolving it

**Comment by hackiftekhar** [comment]
Now we marked the library unavailable for the app extension
