### ISSUE TITLE
Keyboard flickering on tapping textfield, not able to type.

### ISSUE THREAD

**Issue by sathamkhussain** [hackiftekhar/IQKeyboardManager#1791]
I have a login page, where I click on the text field to enter the email, keyboard start flickering. Due to flickering am not able to type. This not happening all the time.  When I disable the IQkeyboardManager from app delegate it's not flickering. Please help me to resolve this issue. 

Swift version 4.2
Xcode 12.2
ios 14

**Comment by pengfan1993** [comment]
which version of IQkeyboardManager do you use?

**Comment by pengfan1993** [comment]
I also found this problem.

**Comment by sathamkhussain** [comment]
I have tried with the latest and a few previous version.

**Comment by hackiftekhar** [comment]
Please share the demo project here so that I can look into the issue.
