### ISSUE TITLE
Extra unscrollable white space from keyboard after dismissing calendar text field in webview

### ISSUE THREAD

**Issue by sm0nster** [hackiftekhar/IQKeyboardManager#1792]
**Describe the bug**
When you go to calendar field after textfield in webview - keyboard is dissmised but there's extra unscrollable white space that was under keyboard

**To Reproduce**
In webview
1. Tap textfield - keyboard is shown [screen 1]
2. Tap calendar field - keyboard hides, calendar is shown [screen 2]
3. Dismiss calendar (Ok/cancel/tap outer space) - extra blank space after stays on, it's not scrollable [screen 3]

**Expected behavior**
No extra white space left after dismissing 

**Screenshots**
![image](https://user-images.githubusercontent.com/16431843/105191316-38405080-5b37-11eb-879f-7a37fe4bb02d.png)
![image](https://user-images.githubusercontent.com/16431843/105191380-49895d00-5b37-11eb-9a1c-585aac7920aa.png)
![image](https://user-images.githubusercontent.com/16431843/105191424-57d77900-5b37-11eb-9799-3d79faf96fd0.png)

### Versions
**Xcode:** 12.3 (12C33)
**Mac OS:** Big Sur 11.1
**Simulator/Device:** Simulator iPhone 12 - iOS 14.3
**Library Version:** 6.5.6

**Comment by hiteshborse12** [comment]
@sm0nster 
Did you found any solution?

**Comment by sm0nster** [comment]
> @sm0nster
> Did you found any solution?

Unfortunately not :(

**Comment by hackiftekhar** [comment]
The WebView have different textfields so, it is ignored by the library. This issue is not related to the library anyway.
