### ISSUE TITLE
new ios version 14.3,IQKeyboard is not work   the textfiled isnot put up to the visial area

### ISSUE THREAD

**Issue by afeng159** [hackiftekhar/IQKeyboardManager#1793]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Demo Project**
If applicable, add demo project.

### Versions
**Xcode:** x.x
**Mac OS:** xx.xx.x
**Simulator/Device:** xx.x
**Simulator/Device Name:** iPhone xx
**Library Version:** x.x.x

**Additional context**

**Comment by YoungXKing** [comment]
这个库在iOS14上不能用了

**Comment by hackiftekhar** [comment]
I don't understand the issue. Can you please explain a bit more or try to add a demo project?
