### ISSUE TITLE
设置了 textField.inputView = XXView()，textField.inputAccessoryView = nil，但是 toolBar 不显示

### ISSUE THREAD

**Issue by czmCWH** [hackiftekhar/IQKeyboardManager#1794]
设置了 textField.inputView = XXView()，textField.inputAccessoryView = nil

如何让 inputAccessoryView 对应的标准 toolBar 也显示

**Comment by hackiftekhar** [comment]
Don't set any inputAccessoryView, the library will show the toolbar for you.
