### ISSUE TITLE
When the keyboard pops up in landscape, the position is out of order

### ISSUE THREAD

**Issue by S-Freedom** [hackiftekhar/IQKeyboardManager#1795]
**Describe the bug**
Hello, 

When the horizontal screen pops up the keyboard, the position is confused and the white bar appears above the keyboard
Please see the screenshot.

**Screenshots**
![WechatIMG325](https://user-images.githubusercontent.com/12085333/106556940-a59ea900-655b-11eb-9ae6-981f5a098cb2.jpeg)

### Versions
**Xcode:** 12.01
**Simulator/Device:IOS 14.1
**Library Version:6.5.6

**Comment by hackiftekhar** [comment]
Not sure why the white bar appears, it's something related to the iOS because the library doesn't manipulate what iOS draws for keyboards.
