### ISSUE TITLE
the input view will scroll down 

### ISSUE THREAD

**Issue by Jerryshen170918** [hackiftekhar/IQKeyboardManager#1796]
1、keyboard scroll up ，as the input view
2、adding subview on UINavigationController
3、then remove the view from UINavigationController
4、keyboard up ， but the input view scroll down。 

```
- (void)viewDidAppear:(BOOL)animated{
    [super viewDidAppear:animated];
    self.testView = UIView.new;
    self.testView.backgroundColor = UIColor.redColor;
    [self.navigationController.view addSubview:self.testView];
    self.testView.frame = CGRectMake(100, 400, 100, 100);
    
    [self performSelector:@selector(testMethod) withObject:nil afterDelay:2];
}
- (void)testMethod{
    [self.testView removeFromSuperview];
    
}

```

### Versions
**Xcode:** 12.4
**Mac OS:** 10.15.7
**Simulator/Device:** 13.6
**Simulator/Device Name:** iPhone11
**Library Version:** 6.5.6

**Comment by hackiftekhar** [comment]
So what's the problem? where is keyboard or textfield related code?
