### ISSUE TITLE
UINavigation Bar hides when keyboard show (I have IQKeyboardSwift version 6.5.5)

### ISSUE THREAD

**Issue by Mitvariance** [hackiftekhar/IQKeyboardManager#1797]
Hello @iftekhar,

First of all thanks for creating such a wonderful library. All working fine, but I'm facing an issue when the keyboard shows up. UINavigation bar goes up and hides. As you mentioned this issue is fixed in 6.5.0 and up I'm using 6.5.5 and still facing this issue. I've created a dynamic UINavigation bar.

Thank you,
Best Regards

**Comment by hackiftekhar** [comment]
If you have a customized version of the navigation bar behaviour or not using the UINavigationController, then you are likely to face this issue. If you are using the native UINavigationController's and UINavigationBar and still facing the same issue then can you please share a demo project with me?
