### ISSUE TITLE
Keyboard not presented on first click in collection view

### ISSUE THREAD

**Issue by noahbino** [hackiftekhar/IQKeyboardManager#1798]
I've got some textFields in a collectionView and when clicking one for the first time, the keyboard doesn't appear. IQKeyboard manager still shifts the view up but the keyboard doesn't show. On the second click the keyboard shows, but when dismissing the keyboard the view doesn't adjust back down

**Comment by y4fe1** [comment]
I had the same problem

**Comment by y4fe1** [comment]
This will solve your problem.  https://github.com/hackiftekhar/IQKeyboardManager/issues/1596#issuecomment-531689563
