### ISSUE TITLE
NavigationBar Goes Up As Well?

### ISSUE THREAD

**Issue by rhenz** [hackiftekhar/IQKeyboardManager#180]
Hi. Does navigation bar really goes up as well when the textfield becomes first responder?

**Comment by hackiftekhar** [comment]
Can you please ask your question more clearly and please be specific.

On Wednesday, March 18, 2015, Rhenz <notifications@github.com> wrote:

> Hi. Does navigation bar really goes up as well when the textfield becomes
> first responder?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackiftekhar/IQKeyboardManager/issues/180>.
>


-- 
Sent from My iPhone

**Comment by rhenz** [comment]
Hey. I think it is clear enough already. It is simple as that. I'll add images and hope you get what I mean.

![ios simulator screen shot mar 19 2015 12 03 20 am](https://cloud.githubusercontent.com/assets/7302529/6713018/c58ae8a2-cdca-11e4-92b8-31fe50ff763f.png)
![ios simulator screen shot mar 19 2015 12 03 25 am](https://cloud.githubusercontent.com/assets/7302529/6713019/c58b8c6c-cdca-11e4-8c80-55ff4f629155.png)

**Comment by rhenz** [comment]
I guess this could be tag as enhancement as well.

**Comment by hackiftekhar** [comment]
If you don't want to move navigation bar then you need to do UIScrollView trick described in README.md file. Please check. Let me know if you are asking something else.
