### ISSUE TITLE
Problem with hiding & showing cells in UITableView

### ISSUE THREAD

**Issue by yasserosama07** [hackiftekhar/IQKeyboardManager#1801]
**Describe the bug**
I have a UITableview of fields, in some cases some fields depend on others to show or hide, as shown in the video

**Screenshots**
https://user-images.githubusercontent.com/26869176/111060055-e961c800-84a2-11eb-8897-0e5d96736451.mov

**Expected behavior**
- 1st case the first responder should go directly to the second field as it appeared after entering the first field
- 2nd case the first responder should go to the third field as the second field is no longer there

### Versions
**Xcode:** 12.3
**Mac OS:** 11.2.1
**Simulator/Device:** 14.3
**Simulator/Device Name:** iPhone 8 (all devices)
**Library Version:** 6.5.5

**Comment by hackiftekhar** [comment]
It might be because you are dynamically manipulating the number of textFields shown on that table.

**Comment by hackiftekhar** [comment]
The dynamic manipulation of textfield isn't supported because the next/previous button enabling/disabling based on the siblings textfields.
