### ISSUE TITLE
Keyboard is not shown on iOS14

### ISSUE THREAD

**Issue by nnx2202** [hackiftekhar/IQKeyboardManager#1804]
**Describe the bug**
At login screen, when click password textfield.
 Sometimes, only toolbar is shown. 
Sometimes, keyboard is shown but nothing is shown in character area.
And this only happens on iOS 14. iOS 13 works well
Please see details on screenshots. 
Everyone have the solution for this issue? Thanks
![IMG_2390](https://user-images.githubusercontent.com/31956046/112621613-87b73b80-8e5c-11eb-9a52-26885368b9d5.PNG)
![IMG_2389](https://user-images.githubusercontent.com/31956046/112621624-8ab22c00-8e5c-11eb-9cc0-47e793a11f82.PNG)

### Versions
**Xcode:** 12.3
**Mac OS:** 10.15.4
**Simulator/Device:** 14.3
**Simulator/Device Name:** iPad Mini 4
**Library Version:** 6.5.6

**Comment by SyedRafayAbrar** [comment]
@nnx2202 any solution till yet?

**Comment by nnx2202** [comment]
> @nnx2202 any solution till now?

You can tap back to username field, then tap again to password field. Keyboard will show :v That's something weird

**Comment by SyedRafayAbrar** [comment]
I got it done @nnx2202 .
The issue was an extension of UIIMageView was creating some issue.
