### ISSUE TITLE
IQKeyboardManagerSwift-Swift.h:293:12: 'IQKeyboardManager' has different definitions in different modules; first difference is definition in module 'IQKeyboardManagerSwift.Swift' found 1 referenced protocol

### ISSUE THREAD

**Issue by darmie** [hackiftekhar/IQKeyboardManager#1805]
**Describe the bug**

Showing All Messages
IQKeyboardManagerSwift/IQKeyboardManagerSwift.framework/Headers/IQKeyboardManagerSwift-Swift.h:293:12: 'IQKeyboardManager' has different definitions in different modules; first difference is definition in module 'IQKeyboardManagerSwift.Swift' found 1 referenced protocol

**To Reproduce**

**Expected behavior**
Expected the application to compile

**Screenshots**

**Demo Project**
If applicable, add demo project.

### Versions
**Xcode:** 12.3
**Mac OS:** Big Sur
**Simulator/Device:** iOS 14.3
**Simulator/Device Name:** iPhone 12
**Library Version:** 6.5.6

**Additional context**

**Comment by arunnkumarp** [comment]
Same issue. Any one help to resolve this issue.

**Comment by Hyeman-Samuel** [comment]
What other third party libraries are you using along with IQKeyboardManager?

**Comment by hackiftekhar** [comment]
The IQKeyboardManager does not intended to be used with the third party libraries authors, it only should be used by the project developer since it's the decision of the project developer to use it or not.
