### ISSUE TITLE
Is there a way to prevent this from scrolling subviews?

### ISSUE THREAD

**Issue by nchrisr** [hackiftekhar/IQKeyboardManager#1806]
I am using the Xamarin.ios version of this for my app. I have an issue whereby the page gets scrolled upwards and a subview (which is also scrollable)  moves upward as well, and this prevents the entry fields from being visible. 
See video below.

https://user-images.githubusercontent.com/24297785/114115752-05da0000-98a9-11eb-9b42-80ab33e101f3.mov

I have spend a lot of time trying to fix this but it has been unsuccessful. I am trying to make it so that I am able to specify that the inner views should not scroll, only the outer screen should scroll. Is there some functionality with this that already supports that?

**To Reproduce**
Seeing as it is in Xamarin I would have to provide xamarin code, which is not ideal here.

**Expected behavior**
I expect the entry to still be in view when the keyboard comes up.

**Comment by poisson-natsu** [comment]
I've got the same problems. But I am not sure if the next code would work for you.
subview.shouldIgnoreScrollingAdjustment = true

Good luck.

**Comment by poisson-natsu** [comment]
After the setting, it will find the super-scroll-view as the scrollview to adjust the position when the keyboard is called.

**Comment by hackiftekhar** [comment]
keyboadDistanceFromTextfield default value is 10, you might try setting it to 0.
