### ISSUE TITLE
Done and cancel tool bar buttons are invisible. 

### ISSUE THREAD

**Issue by VaishnaviRathod** [hackiftekhar/IQKeyboardManager#1807]
**Describe the bug**
they are present,they  work but not visible 

**Screenshots**
If applicable, add screenshots to help explain your problem. only on some screens

**Demo Project**
If applicable, add demo project.

### Versions
**Xcode:** 12.o
**Mac OS:** Catlantina
**Simulator/Device:** simulator 14.0 as well as device
**Simulator/Device Name:** iphone 8. os 14.4
![Simulator Screen Shot - iPhone 8 - 2021-04-12 at 13 22 44](https://user-images.githubusercontent.com/26961298/114360086-44660800-9b92-11eb-867b-8b7e5678c6e4.png)

**Library Version:** 6.0.3

**Comment by mccarron** [comment]
@VaishnaviRathod  we were debugging a similar problem today, and it ended up being the `tintColor of the `UITextView` was set to `UIColor.clear` and nothing in this library itself. 

Figured I'd share incase it's helpful to you or anyone else.
