### ISSUE TITLE
开启IQKeyboardManager  侧滑返回collectionview出现重影

### ISSUE THREAD

**Issue by btxXiaoXiao** [hackiftekhar/IQKeyboardManager#1808]
开启IQKeyboardManager。collectionview最底部放一个输入框。抬起的时候多抬了一段距离。并且键盘出现以后侧滑返回时候collectionview上面的cell出现重影问题。 是我设置错了。我就是把enable设置yes

**Comment by hackiftekhar** [comment]
Can you please share the demo project?
