### ISSUE TITLE
ToolBar's RightIterm has problem

### ISSUE THREAD

**Issue by Heisenbean** [hackiftekhar/IQKeyboardManager#181]
Hi! @hackiftekhar 
I used IQKeyboardManager for a few days,and i found the toolBar of the Keyboard have a problem,the "Done" button's color always white. I can't find the way to change the color.
I want the "Done" button's color is black or the other colors is OK.
By the way,I'm a new coder.

![image](https://cloud.githubusercontent.com/assets/7660120/6748811/f8f3c5aa-cf24-11e4-98f1-b668f0b9cda3.png)

Thanks!
Heisen

**Comment by mythodeia** [comment]
@Heisenbean try changing this: ```shouldToolbarUsesTextFieldTintColor ``` to ```YES```

**Comment by Heisenbean** [comment]
like this?
![image](https://cloud.githubusercontent.com/assets/7660120/6764536/b8894844-cfee-11e4-8a32-f542276f0e1b.png)

@mythodeia ,thank u,but it doesn't work TAT

**Comment by mythodeia** [comment]
you should add the options you need in the view you want the IQKeyboard to work:
```
    [[IQKeyboardManager sharedManager] setEnable:YES];
    [[IQKeyboardManager sharedManager] setEnableAutoToolbar:YES];
    [[IQKeyboardManager sharedManager] setShouldResignOnTouchOutside:YES];
    [[IQKeyboardManager sharedManager] setShouldToolbarUsesTextFieldTintColor:YES];
....
```

**Comment by Heisenbean** [comment]
@mythodeia 
thanks again.
I think the problem is not here,because i added the options in the view,the console output these:
![image](https://cloud.githubusercontent.com/assets/7660120/6764560/a8040c0a-cff0-11e4-8025-b441fbdb9d6a.png)
it still doesn't work..

**Comment by mythodeia** [comment]
try this one instead.Put it in your ```didFinishLaunchingWithOptions```
```
    [[UIBarButtonItem appearanceWhenContainedIn:[UIToolbar class], nil] setTintColor:[UIColor redColor]];
```
if this does not work either then @hackiftekhar can be of more assistance

**Comment by hackiftekhar** [comment]
@Heisenbean can you share the demo code so we can debug it?

**Comment by Heisenbean** [comment]
@mythodeia @hackiftekhar 
Thank u guys,i created a demo and the IQKeyboardManager is OK.
I guess maybe some code in my project is conflict with the IQKeyboardManager.I'll check it out.
Thanks a lot.
