### ISSUE TITLE
iOS 14.4   secureTextEntry  attribute makes uitextfield have some problems.

### ISSUE THREAD

**Issue by stoneUoU** [hackiftekhar/IQKeyboardManager#1810]
**Describe the bug**
当UITextField的secureTextEntry=YES时，键盘有时候无法输入英文字母和切换键盘样式
When the securetextentry of uitextfield is yes, sometimes the keyboard cannot input English letters and switch keyboard styles

**To Reproduce**

**Expected behavior**

**Screenshots**
![WechatIMG10](https://user-images.githubusercontent.com/24381761/115673586-64aa7980-a37f-11eb-990c-34ed90ab55a3.jpeg)

https://user-images.githubusercontent.com/24381761/115674942-bdc6dd00-a380-11eb-988a-c65e5b75fbce.mp4

https://user-images.githubusercontent.com/24381761/115675329-14341b80-a381-11eb-9d5e-3cbbbe867e98.mp4

### Versions
**Xcode:** 12.3
**Mac OS:**10.15.7
**Simulator/Device:** xx.x
**Simulator/Device Name:** iPhone 11
**Library Version:** iOS 14.4

**Comment by stoneUoU** [comment]
Uploading Stone 2021-04-04 15.31.20.mp4…

**Comment by stoneUoU** [comment]
https://user-images.githubusercontent.com/24381761/115674568-5f99fa00-a380-11eb-9c49-b0877e6dee42.mp4

**Comment by 627969687** [comment]
您好，请问这个问题解决了么 我也遇到了这个问题

**Comment by stoneUoU** [comment]
自定义密码键盘，其实这是iOS14.4的一个BUG



在 2021-07-30 17:03:28，"Jason" ***@***.***> 写道：

您好，请问这个问题解决了么 我也遇到了这个问题

**Comment by 627969687** [comment]
也不一定要自定义，我发现了只要把该控制器以及该控制器引用的地方把带“register”的字符改其他名字就没问题了
