### ISSUE TITLE
Failure in some cases

### ISSUE THREAD

**Issue by cashgift** [hackiftekhar/IQKeyboardManager#1811]
**Describe the bug**
When my main page contains a tabbar, I jump from the main page to page b, and set hidesBottomBarWhenPushed = yes, the textfield in page b does not work properly, the keyboard will block it, and page b will go up and down every time the keyboard pops up beat, When I set hidesBottomBarWhenPushed = no, the page returns to normal
This only happens on X series iPhones

**Screen recording**
[recording](http://qiniu.biqinglin.com/RPReplay_Final1619419016.MP4)

### Versions
**Xcode:** 12.4 (12D4e)
**Mac OS:** 11.2.3 (20D91)
**Simulator/Device:** X series iPhones
**Library Version:** 6.5.6

**Comment by dx777** [comment]
Same for me

**Comment by hackiftekhar** [comment]
I don't exactly know why this happens, but may be you have set layoutIfNeededOnUpdate to true
