### ISSUE TITLE
Carthage build failed

### ISSUE THREAD

**Issue by Bawenang** [hackiftekhar/IQKeyboardManager#1813]
**Describe the bug**
Failed to build Carthage.

**To Reproduce**
1. Add IQKeyboardManager to Cartfile
2. Type "carthage build --platform ios"
3. Observe

**Expected behavior**
The building of the Carthage dependency is successful.

**Demo Project**
If applicable, add demo project.

### Versions
**Xcode:** 12.4
**Mac OS:** 10.15.7

**Additional context**
The error code goes like this:

```
*** Building scheme "IQKeyboardManager" in IQKeyboardManager.xcodeproj
Build Failed
	Task failed with exit code 1:
	/usr/bin/xcrun lipo -create /Users/bawenang/Library/Caches/org.carthage.CarthageKit/DerivedData/12.4_12D4e/IQKeyboardManager/v6.5.6/Build/Intermediates.noindex/ArchiveIntermediates/IQKeyboardManager/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/IQKeyboardManager.framework/IQKeyboardManager /Users/bawenang/Library/Caches/org.carthage.CarthageKit/DerivedData/12.4_12D4e/IQKeyboardManager/v6.5.6/Build/Products/Release-iphonesimulator/IQKeyboardManager.framework/IQKeyboardManager -output /Users/bawenang/Zyrous/kolibree-ios/Carthage/Build/iOS
/IQKeyboardManager.framework/IQKeyboardManager

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/0t/xl5r053d2237cckk_ttg7slh0000gn/T/carthage-xcodebuild.doacvq.log
```

The logfile suggested it is actually built successfully though. Logfile is attached for your perusal.
[carthage-xcodebuild.doacvq.log](https://github.com/hackiftekhar/IQKeyboardManager/files/6448807/carthage-xcodebuild.doacvq.log)

**Comment by hackiftekhar** [comment]
I can see the build succeeded message on the log. Not sure what's missing.
