### ISSUE TITLE
want to ask this repository are still maintaining ?

### ISSUE THREAD

**Issue by xelven** [hackiftekhar/IQKeyboardManager#1814]
very easy to face crash when just pop keyboard.

<img width="1429" alt="Screen Shot 2021-05-13 at 1 44 52 PM" src="https://user-images.githubusercontent.com/11630321/118083923-5f76a280-b3f2-11eb-8d46-027c48803daa.png">
<img width="1405" alt="Screen Shot 2021-05-13 at 1 51 40 PM" src="https://user-images.githubusercontent.com/11630321/118083944-66051a00-b3f2-11eb-9869-25a57c382e87.png">

lib version: v6.5.6
xcode 12.4 & iOS 11 or iOS 14 device/simulator.

**Comment by giuseppenovielli** [comment]
@hackiftekhar please give a feedback, Thanks!

**Comment by hackiftekhar** [comment]
I'm willing to work on this project since it helped a lot of peoples. However I'm too busy with my work schedule and personal life. So these days I'm unable to look into the project.

**Comment by hackiftekhar** [comment]
I'm not able to reproduce this problem. Can you please try to write steps to reproduce?
