### ISSUE TITLE
whats latest version in carthage ?

### ISSUE THREAD

**Issue by xelven** [hackiftekhar/IQKeyboardManager#1815]
I saw the demo are using v6.5.7

but it seems not available for carthage right? 

*** Checking out IQKeyboardManager at "v6.5.7"
*** Fetching IQKeyboardManager

A shell task (/usr/bin/env git checkout --quiet --force v6.5.7 (launched in /Users/allenchan/Library/Caches/org.carthage.CarthageKit/dependencies/IQKeyboardManager)) failed with exit code 1:
error: pathspec 'v6.5.7' did not match any file(s) known to git

**Comment by hackiftekhar** [comment]
The v6.5.7 has been pushed now.

**Comment by hackiftekhar** [comment]
Will be pushing a new version soon due to some swift package manager problem.
