### ISSUE TITLE
IQkeyboardManager Carthage issue

### ISSUE THREAD

**Issue by Alrassas** [hackiftekhar/IQKeyboardManager#1817]
tried to use use carthage to update IQframework. but can't use downloaded version because of below
Module compiled with Swift 5.1.3 cannot be imported by the Swift 5.4 compiler: /Carthage/Build/iOS/IQKeyboardManagerSwift.framework/Modules/IQKeyboardManagerSwift.swiftmodule/arm64-apple-ios.swiftmodule

**Comment by hackiftekhar** [comment]
Clean and rebuild the library. It should probably solve the problem.
