### ISSUE TITLE
IQKeyboardManagerSwift 6.5.6  Issue

### ISSUE THREAD

**Issue by SummerTimer2016** [hackiftekhar/IQKeyboardManager#1819]
IQKeyboardManager.shared.enableAutoToolbar = true ，
 Go to the page, and if the current page is becomeFirstResponder()，
Using the AutoToolbar done Aciton，
 causes the view to be offset upwards by about one navigationBar height

**Comment by proft** [comment]
Fixed by

```
override func viewDidAppear(_ animated: Bool) {
    super.viewDidAppear(true)
    yourTextField.becomeFirstResponder()
}
```

**Comment by morrischen** [comment]
IQKeyboardManager.shared.layoutIfNeededOnUpdate = true

maybe this code will work

**Comment by hackiftekhar** [comment]
If you do becomeFirstResponder in viewDidLoad or viewWillAppear then you'll encounter this issue because at that time the view might not load properly in the view hierarchy.
