### ISSUE TITLE
Toolbar doesn't appear on UISearchbar

### ISSUE THREAD

**Issue by AngelDev727** [hackiftekhar/IQKeyboardManager#1820]
I am trying to use IQKeyboardManager with UISearchBar.
But it doesn't appear it.
How can I fix it?
![Screen Shot 2021-05-28 at 7 59 19 PM](https://user-images.githubusercontent.com/54489723/119980678-33147600-bfef-11eb-83cd-d98d9cf6f571.png)

**Comment by KuldeepAIP** [comment]
@AngelDev727 , i am having the same issue and got this solution and it works but don't know wether it's proper way or not to do this.

Comment this line **searchBar() == nil** 

**IQUIView+Hierarchy.swift** 

if _IQcanBecomeFirstResponder == true {
        _IQcanBecomeFirstResponder = isUserInteractionEnabled == true &&
         isHidden == false && alpha != 0.0 &&
         isAlertViewTextField() == false &&
         // searchBar() == nil
    }

**Comment by justdan0227** [comment]
Can someone comment on this and if it works why is it not merged into master?

**Comment by justdan0227** [comment]
bump

**Comment by hackiftekhar** [comment]
This is forcefully disabled for search bar because most search bar keyboards doesn't display this for their own reasons.

**Comment by NguyenNgocLe** [comment]
I am having the same issue and i fix this in line code
if IQcanBecomeFirstResponder {
            IQcanBecomeFirstResponder = isUserInteractionEnabled && !isHidden && alpha != 0.0 && !isAlertViewTextField() //&& textFieldSearchBar() == nil
        }
