### ISSUE TITLE
'shared' is unavailable: not available on iOS (App Extension) on Xcode 13 beta 3

### ISSUE THREAD

**Issue by garanda21** [hackiftekhar/IQKeyboardManager#1824]
**Describe the bug**
Not compiling IQKeyboardManager on Xcode 13 beta 3, shows this error: 'shared' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead

**To Reproduce**
1. Open your project using Xcode 13 beta 3
2. Clean project
3. Build Project

**Expected behavior**
Compile successfully 

### Versions
**Xcode:** 13.0 beta 3 (13A5192j)
**Mac OS:** 11.4
**Library Version:** 6.5.6 using SPM

**Additional context**
On swift official forums exists a thread related with issue: [https://forums.swift.org/t/set-application-extension-api-only-on-a-spm-package/39333/17](url)

**Comment by SebastianKumor** [comment]
same issue here

**Comment by LaurentiuUngur** [comment]
Same here, also on Xcode 13.0 beta 4
