### ISSUE TITLE
Previous and Next arrows disabled

### ISSUE THREAD

**Issue by nele-llama** [hackiftekhar/IQKeyboardManager#1826]
Lib integrated as pod (`IQKeyboardManagerSwift (6.5.6)`), imported in `AppDelegate` and setup like in README
I have three custom `UITextFields` named `TextField` (just changing layout for different state) with secure text entry on.

view hierarchy: View -> ScrollView -> View -> StackView (vertical) -> { 
        StackView (horizontal) -> TextField
        StackView (horizontal) -> TextField
        StackView (horizontal) -> TextField
}

when i check `canGoNext` or `canGoPrevious` i get `false`
when start editing text field toolbar is present with `Done` button there are no arrows 
even when set `previousNextDisplayMod = .alwaysShow` arrows are disabled

**Comment by nithincdlt** [comment]
I a also getting the same without previous and next buttons

**Comment by nithincdlt** [comment]
1 month back it was working fine with another project I build.

**Comment by hackiftekhar** [comment]
Add a IQPreviousNextView as container of your stackView, the next previous issue will be solve when they are not direct siblings.
