### ISSUE TITLE
Bug in arrow

### ISSUE THREAD

**Issue by thiagomacauba88** [hackiftekhar/IQKeyboardManager#1828]
**Describe the bug**
In iPhones with small status bar (8,7,6,5), we have a problem when using the arrow.

**Screenshots**
<img src="https://user-images.githubusercontent.com/7560513/128233417-afe5b6b3-46c1-45a7-b004-2584836aec00.png" width=30% height=30%>
<img src="https://user-images.githubusercontent.com/7560513/128233425-ea3b948a-c85a-4e15-bc07-6d3257666995.png" width=30% height=30%>
<img src="https://user-images.githubusercontent.com/7560513/128233430-c1ae8f58-3bbf-45c6-a48b-a4b80e27235e.png" width=30% height=30%>

### Versions
**Xcode:** 12.5
**Mac OS:** 11.2.3
**Simulator/Device:** xx.x
**Simulator/Device Name:** iPhone 7
**Library Version:** 6.5.6

**Comment by hackiftekhar** [comment]
Not sure what you are trying to explain. Can you please explain a little bit more?
