### ISSUE TITLE
Crash on UITextField focus with iOS 15 / Xcode 13

### ISSUE THREAD

**Issue by benjamincombes** [hackiftekhar/IQKeyboardManager#1832]
**Describe the bug**
When using an exiting app, taking focus on a UITextField crashes the app with an EXC_BAD_ACCESS.
No crash on iOS 14 & iOS 15 with app compiled with Xcode 12
This crashes on iOS 15 with app compiled with Xcode 13

**To Reproduce**
1. Compile a working app with Xcode 13.0.0
2. Open the app on iOS 15
3. Tap on a UITextField
4. The app crashes

**Expected behavior**
The app should not crash, as it was on Xcode 12 / iOS 14

### Versions
**Xcode: 13.0 (13A233)
**Mac OS:11.6 (20G165)
**Simulator/Device:Device
**Simulator/Device Name:iPhone 12 mini
**Library Version:** 6.5.0

**Additional context**
Crash occurs on line 2044 of IQKeyboardManager.swift:
```
textField.addKeyboardToolbarWithTarget(target: self, titleText: (shouldShowToolbarPlaceholder ? textField.drawingToolbarPlaceholder: nil), rightBarButtonConfiguration: rightConfiguration, previousBarButtonConfiguration: prevConfiguration, nextBarButtonConfiguration: nextConfiguration)
```
Called from line 1797.

**Comment by AroundPixels** [comment]
Same problem here, I think it is something related to view padding. Did you find any workaround @benjamincombes? Thanks

**Comment by AroundPixels** [comment]
Found the problem: in my case, was an UITextField Extension class with a @IBInspectable vars get/set for padding. I've removed this code and the UITextFields works again as expected with the same version of IQKeyboardManagerSwift library.

**Comment by benjamincombes** [comment]
Hi @AroundPixels, just found my problem too: I had an IDE problem and had to use Carthage instead of SPM for IQKeyboardManager. But I included both IQKeyboardManagerSwift and IQKeyboardManager libraries: I had to keep only one of them.
