### ISSUE TITLE
Can not run in the simulator on Mac with M1 Processor

### ISSUE THREAD

**Issue by jigar007** [hackiftekhar/IQKeyboardManager#1833]
**Describe the bug**
Can not run project with IQKeyboardManager in the simulator on Mac with M1 Processor

Getting below error
Could not find module 'IQKeyboardManagerSwift' for target 'x86_64-apple-ios-simulator'; found: arm64, arm64-apple-ios-simulator

**Expected behavior**
It should work in simulator same as a real device.

**Screenshots**
<img width="1269" alt="Screen Shot 2021-09-29 at 4 54 19 pm" src="https://user-images.githubusercontent.com/9298974/135218268-8e49cbe9-d2fd-4ba3-a5cc-8fa7914e99f2.png">

**Demo Project**
If applicable, add demo project.

### Versions
**Xcode:** 13.0
**Mac OS:** macOS Monterey Version 12.0 Beta (21A5284e)
**Simulator:** iPhone 13 Pro Max
**Library Version:** 6.5.6

**Comment by hackiftekhar** [comment]
Sorry, I don't have the M1 Mac to simulate the scenario.

**Comment by hackiftekhar** [comment]
Any help from others would be appreciated.

**Comment by JhaNviSadhu** [comment]
facing same issue with M1 silicon

**Comment by Kater-auf-Dach** [comment]
Added it via SPM and Xcode (have installed pods for another packages) and didn't get an error on M1
(Xcode 13.1, Monterey 12.0.1, iPhone 13 Pro)

**Comment by hyo961015** [comment]
I found the solution

If you use simulator, follow next step.
1. Move "Targets" -> "Build Settings"
2. Search"Excluded Architectures" in "Build Settings"
3. and then Remove "arm64"

*If you use real device, you shouldn't remove "arm64"

It worked it !

**Comment by mochadwi** [comment]
> I found the solution
> 
> If you use simulator, follow next step.
> 
> 1. Move "Targets" -> "Build Settings"
> 2. Search"Excluded Architectures" in "Build Settings"
> 3. and then Remove "arm64"
> 
> *If you use real device, you shouldn't remove "arm64"
> 
> It worked for me!

This approaches solve our issues partially, but introduce a new ones as https://github.com/googlemaps/google-maps-ios-utils/issues/355 (we use Google SDK that still not supports the M1)

**Comment by assembleMHN** [comment]
So this is just never gonna get solved because developer dont have a M1 mac. If so i think its time to look for other solutions. For now this library can only be build with Rosetta simulator, and at some point Apple are gonne remove the backwards compatibility. My app is using 13 libraries and this one is the only one left still not supporting m1. To bad :(
