### ISSUE TITLE
View does not move up for the first time when tapped on textview

### ISSUE THREAD

**Issue by NalineeSingh01** [hackiftekhar/IQKeyboardManager#1835]
Keyboard covers the view, the first time something is typed in text view. From second time everything works fine.
**To Reproduce**
1. Tap on a textview
2. keyboard shows up but the view does not moves up hence keyboard covers the view.

**Expected behavior**
View should move up showing the text view after the keyboard is up.

**Screenshots**
https://user-images.githubusercontent.com/68046022/135574316-510f9f36-e02a-4e2d-8c50-fc7db966a091.MP4

**Demo Project**
[keyboardIssue.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/7264743/keyboardIssue.zip)

### Versions
**Xcode:** 12.4 (12D4e)
**Mac OS: 11.2.1 
**Device: tested on iPhone 6s  (reproducable on any iPhone device)
**Library Version: IQKeyboardManagerSwift (6.5.6)

**Comment by NalineeSingh01** [comment]
> Happening to me as well.
> Waitin for the update to be live. Our users are facing this issue in our live app now.

Till the new update is out, you can try this -
IQKeyboardManager.Swift -> func textFieldViewDidBeginEditing

look for below comment and code - 

//On textView toolbar didn't appear on first time, so forcing textView to reload it's inputViews.
                        textView.reloadInputViews()


now just below above mentioned code add these two lines to remove the issue

textView.resignFirstResponder()
textView.becomeFirstResponder()

**Comment by zhujian521** [comment]
I also encounter such problem, how does the building Lord solve this problem

**Comment by hackiftekhar** [comment]
I'll need to check the demo project to see if that fixes the problem or not.

**Comment by Merdin** [comment]
@hackiftekhar the problem still occurs, when can we expect a solution?

**Comment by JAGUAR108** [comment]
Проблема всё ещё существует, на iPhone SE 1gen воспроизводится

**Comment by kienwei518** [comment]
In my case, I notice the keyboard will work fine if got some delay by long press or make a debug point when I running my project. So i put this code in my own ViewController without changing any in the library file and it works. 

textView.delegate = self

func textViewDidBeginEditing(_ textView: UITextView) {
        DispatchQueue.main.async {
            textView.reloadInputViews()
        }
    }

**Comment by hackiftekhar** [comment]
I checked the demo project and it looks like it's no longer reproducible with the demo project and with the iPhone SE 1st generation as well.

**Comment by Arya-Wang** [comment]
Hi，This issue still exists in the latest version，
iPhone 6s plus  14.7.1
