### ISSUE TITLE
ios14.8~ios15 偶尔整个app的页面无法跟随键盘上移

### ISSUE THREAD

**Issue by 1518880611** [hackiftekhar/IQKeyboardManager#1837]
ios14.8~ios15
会出现app里面的所有页面都无法跟着键盘出现而上移，需要重新卸载然后去App Store重新下载app，就可以正常使用了。麻烦查一下是不是新系统的适配问题

**Comment by zhangmegntao** [comment]
我也遇到这个问题，我通过debug日志追踪发现
![image](https://user-images.githubusercontent.com/20531909/140452159-b3ac5442-f905-4df6-8ea1-348741643380.png)
经过比对发现：第一次在执行 keyboardDidShow 后，立即执行 keyboardWillHide 的方法。通过代码追踪后，在keyboardWillHide方法中重置了_privateHasPendingAdjustRequest的值，导致不走adjustPosition的方法。
系统似乎发出了相同的事件监听

**Comment by hackiftekhar** [comment]
Can you please let me know what you are trying to explain? I'm not sure what you are trying to point out.
