### ISSUE TITLE
Done button is invisible or clear color

### ISSUE THREAD

**Issue by keegho** [hackiftekhar/IQKeyboardManager#1838]
I tried everything but **Done** button in toolbar is always invisible. Even though it is tappable but not visible. Could be clear color but I have already set the color in the `AppDelegate.swift`

This is my code in the `AppDelegate.swift` file
```
IQKeyboardManager.shared.enable = true
IQKeyboardManager.shared.toolbarTintColor = #colorLiteral(red: 0, green: 0.6666666865, blue: 0.6666666865, alpha: 0.4844929272)
```
Also tried `IQKeyboardManager.shared.toolbarTintColor = .green` same issue.
The up and down arrows are fine. The issues is in the **Done** button only.
XCODE _Version 13.0 (13A233)_

![IMG_1113](https://user-images.githubusercontent.com/16656424/137721347-a16944ce-df2c-40a3-89b1-5568e8abfcb8.jpg)

**Comment by hackiftekhar** [comment]
Have you set any global tintColor of uibarbutton item? May be using Appearance Proxy?
