### ISSUE TITLE
oc 使用6.5.6版本闪退

### ISSUE THREAD

**Issue by JQHxx** [hackiftekhar/IQKeyboardManager#1839]
两个textFiled 来回编辑点击成为第一响应者闪退

**Comment by yasinn** [comment]
这个解决了吗？我也遇到了

**Comment by Mr-Dsg** [comment]
解决了吗，iOS 18.1  iPhone 13 Pro 和 iPhone 13   明文和密文切换必现，其他机型还没发现这个问题
