### ISSUE TITLE
Screen scrolls back to first UITextField when Done is tapped

### ISSUE THREAD

**Issue by OutRunner** [hackiftekhar/IQKeyboardManager#184]
First of all, thank you so much for writing such an amazing library, it has saved me so many headaches!

Now to my problem: I'm creating a relatively long screen of UITextFields that I am generating programmatically and then adding to a UIScrollView so that the user can scroll up and down to see all the fields. If the user uses the IQKeyboardManager's Next/Previous buttons to navigate through the fields and then taps Done, the screen will scroll back to the first UITextField that they tapped. 

It doesn't do it if the user dismisses the keyboard after each field, but using Next/Previous or tapping on the next field each time with the keyboard still open will trigger the scroll. 

So if I tap the last field and then use Previous to work my way back up the form, hitting Done will cause it to scroll to the bottom field, likewise if I start at the top and work my way down it will scroll to the top when I hit Done. Any ideas what I'm doing wrong?

One thing I should mention, my project is in Swift but I'm using the Obj-C version of IQKeyboardManager as I used CocoaPods to install it. I've just noticed there is a Swift version, is it worth me switching to the Swift one, and if I should, is there a CocoaPod install?

Many thanks for your help!

**Comment by hackiftekhar** [comment]
It's good to use obj-c version, swift version has some known issues.

    It's my implementation to scroll-back user to original position of scrollview. For your case, I'll implement a boolean property to let user decide whether scrollview should restore it's original position or not.

**Comment by OutRunner** [comment]
Thank you so much, a boolean to control whether it scrolls back or not sounds perfect!

Cheers!

**Comment by hackiftekhar** [comment]
added shouldRestoreScrollViewContentOffset. Default to NO.

**Comment by OutRunner** [comment]
Thank you! :)
