### ISSUE TITLE
View Misplaced after textField resign

### ISSUE THREAD

**Issue by elliotcz97** [hackiftekhar/IQKeyboardManager#1840]
**Describe the bug**
I have two textfields in one Viewcontroller, the first is in good position ( no adjusting needed) the second needs the adjustment.

When i write something into the textfield, then the SafeArea gets bigger and the Save Button (the big green one), gets misplaced (gets moved down by like 30 pixels):

![IMG_0487](https://user-images.githubusercontent.com/40901589/139286673-564d173f-1497-4989-bb73-5ffdfd20fefb.PNG)

And this is how it should look:

![IMG_0486](https://user-images.githubusercontent.com/40901589/139287192-c4af267a-85a6-45f5-930b-d5b033fa9438.PNG)

EDIT: It works properly when i pin the button from the Top, but when i pin the button from the bottom it gets misplaced

### Versions
Xcode: 13.0
Mac OS: BIg Sur
Simulator/Device: 15.0
Simulator/Device Name: iPhone 12 mini
Library Version: Latest (6.5.6)

**Comment by hackiftekhar** [comment]
From where did you pin the constraint? From safe area or from superview?

**Comment by elliotcz97** [comment]
@hackiftekhar Safe area!

**Comment by hackiftekhar** [comment]
Can you share a demo project with me to see what's the problem with the constraint or the safe area manipulating?

**Comment by i-tengfei** [comment]
I have the same problem

`IQKeyboardManager.shared.layoutIfNeededOnUpdate = true` it works for me

https://github.com/hackiftekhar/IQKeyboardManager/issues/1687#issuecomment-721618667

**Comment by elliotcz97** [comment]
@i-tengfei Thank you! This solved my issue!
