### ISSUE TITLE
IQKeyboardManager:pod install 问题

### ISSUE THREAD

**Issue by garvinbao** [hackiftekhar/IQKeyboardManager#1842]
**Describe the bug**
每次重新pod install 时候都拉不下来报一下错误，其他库顺利导入项目中
![image](https://user-images.githubusercontent.com/41906587/140005944-7fd004fa-2a69-4521-ba8f-ecba01ead98c.png)

pod install之前删了Podfile.lock、Pods以及.workspace

### Versions
**Xcode:13.0
**Mac OS:macOS Big Sur 11.4
**Simulator/Device:iOS 15.0
**Library Version:6.5.6

**Comment by hackiftekhar** [comment]
It looks like some issue with your own system since the cloning looks to be working for me.
