### ISSUE TITLE
Compile errors v6.5.7 SPM

### ISSUE THREAD

**Issue by LaurentiuUngur** [hackiftekhar/IQKeyboardManager#1843]
**Describe the bug**
Compile errors

**To Reproduce**
1. Integrate into a Swift project IQKeyboardManager 6.5.7 using SPM
2. Build project

**Expected behavior**
Build without errors

**Screenshots**
<img width="654" alt="Screenshot 2021-11-06 at 06 38 48" src="https://user-images.githubusercontent.com/13499785/140598073-bdcbaa5d-9679-4dda-9293-1e315a265eae.png">

### Versions
**Xcode:** 13.1
**Mac OS:** 12.0.1
**Swift Version:** 5.x
**Simulator/Device:** Simulator
**Simulator/Device Name:** iPhone 13 Pro
**Library Version:** 6.5.7

**Additional context**
6.5.6 was working without any compile errors

**Comment by LaurentiuUngur** [comment]
Maybe changing into `Package.swift` from `// swift-tools-version:4.0` to `// swift-tools-version:4.2` will fix this

**Comment by hackiftekhar** [comment]
Yup, I changed it to 5.0 now and it compiles well now. Will publish a new version today.

**Comment by piv199** [comment]
I don't have package.swift, but have the same error. Hmmm....
