### ISSUE TITLE
Can't use IQKeyboardManager in iOS AppExtension

### ISSUE THREAD

**Issue by alperkayabasi** [hackiftekhar/IQKeyboardManager#1845]
**Describe the bug**
I can't use the framework in iOS Action Extension.
There was no problem in v6.5.6 but after the last updates, I can't build the project.

**To Reproduce**
1. import IQKeyboardManager in a class which has an "iOS App Extension" target.
2. Try to build the project
3. See error:  IQKeyboardManagerSwift/IQKeyboardManagerSwift.framework/Headers/IQKeyboardManagerSwift-Swift.h:617:41: 'IQToolbar' is unavailable: not available on iOS (App Extension)

### Versions
**Xcode:** 13.0
**Mac OS:** 11.6.1
**Simulator/Device:** 14.8
**Simulator/Device Name:** iPhone 11
**Library Version:** 6.5.8

**Comment by hackiftekhar** [comment]
This issue is now finally fixed. I added a demo extension in the demo project to test the library against the App Extension and solved all compilation issues. This should work now with v6.5.9
