### ISSUE TITLE
Xcode 13.1 + Carthage + IQKeyboardManager 6.5.9 breaks

### ISSUE THREAD

**Issue by andrewrt** [hackiftekhar/IQKeyboardManager#1846]
**Describe the bug**
Xcode 13.1 + Carthage + IQKeyboardManager 6.5.9 fails to compile. 

If i force carthage to use version 6.5.6, it works fine.

**To Reproduce**
Running xcode 13.1, just IQKeyboardManager / Swift in a swift project

**Expected behavior**
Builds

**Screenshots**
*** Fetching IQKeyboardManager
*** Checking out IQKeyboardManager at "v6.5.9"
*** xcodebuild output can be found in /var/folders/qc/h00f5gc545qfc8bq2nb3zg_w0000gn/T/carthage-xcodebuild.RFBYYf.log
*** Building scheme "IQKeyboardManager" in IQKeyboardManager.xcodeproj
*** Building scheme "IQKeyboardManagerSwift" in IQKeyboardManager.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/andrew/code/ios/therma2-util-ios/Therma2\ Util/Carthage/Checkouts/IQKeyboardManager/IQKeyboardManager.xcodeproj -scheme IQKeyboardManagerSwift -configuration Release -derivedDataPath /Users/andrew/Library/Caches/org.carthage.CarthageKit/DerivedData/13.1_13A1030d/IQKeyboardManager/v6.5.9 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive VALIDATE_WORKSPACE=NO -archivePath /var/folders/qc/h00f5gc545qfc8bq2nb3zg_w0000gn/T/IQKeyboardManager SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/andrew/code/ios/therma2-util-ios/Therma2 Util/Carthage/Checkouts/IQKeyboardManager)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/qc/h00f5gc545qfc8bq2nb3zg_w0000gn/T/carthage-xcodebuild.RFBYYf.log

### Versions
**Xcode:** 13.1
**Mac OS:** 11.5.2
**Simulator/Device Name:** iPhone X
**Library Version:** 3.5.9

**Comment by faiqadi** [comment]
same issue here, here i also check my log 

** ARCHIVE FAILED **


The following build commands failed:
	CompileSwift normal arm64 (in target 'IQKeyboardManagerSwift' from project 'IQKeyboardManager')
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'IQKeyboardManagerSwift' from project 'IQKeyboardManager')
	CompileSwiftSources normal armv7 com.apple.xcode.tools.swift.compiler (in target 'IQKeyboardManagerSwift' from project 'IQKeyboardManager')
	CompileSwift normal armv7 (in target 'IQKeyboardManagerSwift' from project 'IQKeyboardManager')
(4 failures)

**Comment by 417-72KI** [comment]
same issue with v6.5.7

**Comment by hackiftekhar** [comment]
This is now fixed and will be available soon.
