### ISSUE TITLE
I also encounter such problem, how does the building Lord solve this problem

### ISSUE THREAD

**Issue by zxj1989** [hackiftekhar/IQKeyboardManager#1847]
I also encounter such problem, how does the building Lord solve this problem

_Originally posted by @zhujian521 in https://github.com/hackiftekhar/IQKeyboardManager/issues/1835#issuecomment-961686128_

**Comment by zhujian521** [comment]
We haven't found a solution yet. SDK may be needed to upgrade

**Comment by zxj1989** [comment]
I use pod 'IQKeyboardManagerSwift', '~> 6.5.9'
but issue is still there

**Comment by zhujian521** [comment]
Maybe the SDK didn't fix this problem and release a new version
