### ISSUE TITLE
Hide Suggestion in Keyboard

### ISSUE THREAD

**Issue by kishan-1211** [hackiftekhar/IQKeyboardManager#1848]
Hello! Team,

How can we hide the suggestions on the keyboard 
![IMG_7084](https://user-images.githubusercontent.com/74966137/144046742-6258f93c-82f1-4383-8ffd-8a0056057929.jpeg)
??

**Comment by hackiftekhar** [comment]
It's in iOS Settings somewhere in keyboard settings. Or programmatically there is a property (probably) in textField and textView to hide suggestions.
