### ISSUE TITLE
only iphoneX and iphone8 plus crash

### ISSUE THREAD

**Issue by xuwenxindeai** [hackiftekhar/IQKeyboardManager#1849]
### Versions
**Xcode:** 12.5
**Mac OS:** xx.xx.x
**Device:** all version
**Device:** iPhone x/iphone8 plus
**Library Version:** 0.0.9.8

**Additional context**
`0
libobjc.A.dylib
_objc_autorelease + 16
1
SpringBoardFoundation
-[UIDevice(ControlCenter) _deviceInfoForKey:] + 28
2
UIKit
___54-[UIDevice(UIDeviceInternal) _keyboardGraphicsQuality]_block_invoke + 128
3
libdispatch.dylib
__dispatch_client_callout + 16
4
libdispatch.dylib
_dispatch_once_f$VARIANT$mp + 60
5
UIKit
-[UIDevice(UIDeviceInternal) _keyboardGraphicsQuality] + 208
6
UIKit
___37+[UIKBRenderFactory _graphicsQuality]_block_invoke + 40
7
libdispatch.dylib
__dispatch_client_callout + 16
8
libdispatch.dylib
_dispatch_once_f$VARIANT$mp + 60
9
UIKit
+[UIKBRenderFactory _graphicsQuality] + 80
10
UIKit
-[UIKBRenderConfig backdropStyle] + 112
11
UIKit
-[UIPeripheralHost inputModeChangedForRenderConfig:] + 120
12
CoreFoundation
___CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 20
13
CoreFoundation
__CFXRegistrationPost + 428
14
CoreFoundation
____CFXNotificationPost_block_invoke + 216
15
CoreFoundation
-[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1408
16
CoreFoundation
__CFXNotificationPost + 384
17
Foundation
-[NSNotificationCenter postNotificationName:object:userInfo:] + 68
18
UIKit
-[UIKeyboardInputModeController currentInputMode] + 68
19
UIKit
+[UIKeyboardImpl sizeForInterfaceOrientation:ignoreInputView:] + 124
20
UIKit
-[UIInputWindowController updateViewConstraints] + 5112
21
UIKit
-[UIView(AdditionalLayoutSupport) _sendUpdateConstraintsIfNecessaryForSecondPass:] + 176
22
UIKit
-[UIView(AdditionalLayoutSupport) _updateConstraintsIfNeededCollectingViews:forSecondPass:] + 1012
23
UIKit
-[UIView(AdditionalLayoutSupport) _updateConstraintsIfNeededCollectingViews:forSecondPass:] + 712
24
Foundation
-[NSISEngine withBehaviors:performModifications:] + 120
25
UIKit
___100-[UIView(AdditionalLayoutSupport) _updateConstraintsIfNeededWithViewForVariableChangeNotifications:]_block_invoke + 92
26
UIKit
-[UIView(AdditionalLayoutSupport) _withUnsatisfiableConstraintsLoggingSuspendedIfEngineDelegateExists:] + 116
27
UIKit
-[UIView(AdditionalLayoutSupport) _updateConstraintsIfNeededWithViewForVariableChangeNotifications:] + 168
28
UIKit
-[UIWindow(UIConstraintBasedLayout) _updateConstraintsIfNeededWithViewForVariableChangeNotifications:] + 100
29
UIKit
-[UIView(AdditionalLayoutSupport) _updateConstraintsAtEngineLevelIfNeededWithViewForVariableChangeNotifications:] + 428
30
UIKit
-[UIView(Hierarchy) _updateConstraintsAsNecessaryAndApplyLayoutFromEngine] + 272
31
UIKit
-[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1420
32
QuartzCore
-[CALayer layoutSublayers] + 184
33
QuartzCore
CA::Layer::layout_if_needed(CA::Transaction*) + 324
34
QuartzCore
CA::Context::commit_transaction(CA::Transaction*) + 320
35
QuartzCore
CA::Transaction::commit() + 580
36
QuartzCore
CA::Transaction::observer_callback(__CFRunLoopObserver*, unsigned long, void*) + 92
37
CoreFoundation
___CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 32
38
CoreFoundation
___CFRunLoopDoObservers + 412
39
CoreFoundation
___CFRunLoopRun + 1436
40
CoreFoundation
_CFRunLoopRunSpecific + 552
41
GraphicsServices
_GSEventRunModal + 100
42
UIKit
_UIApplicationMain + 236
43
ArtVideoWB
main (main.m:20)
44
libdyld.dylib
_start + 4
`

**Comment by adolph-suntao** [comment]
UITableviewCell add input box, tail view using the label by NSMutableAttributedString load HTML string, a cell is overmuch, tail view has not appeared on the screen, click on the input box to collapse。

**Comment by mengxiangjian13** [comment]
> UITableviewCell add input box, tail view using the label by NSMutableAttributedString load HTML string, a cell is overmuch, tail view has not appeared on the screen, click on the input box to collapse。
> 
> Xcode Tips： [CollectionView] An attempt to prepare a layout while a prepareLayout call was already in progress (i.e. reentrant call) has been ignored. Please file a bug. UICollectionView instance is (<UIKBCandidateCollectionView: 0x106a90800; frame = (0 0; 276 38); clipsToBounds = YES; autoresize = W; gestureRecognizers = <NSArray: 0x2827e7360>; layer = <CALayer: 0x2829d2fe0>; contentOffset: {0, 0}; contentSize: {320, 38}; adjustedContentInset: {0, 0, 0, 0}> collection view layout: <UIKeyboardCandidateBarLayout: 0x110e646f0>) *** Assertion failure in -[UICollectionViewData validateLayoutInRect:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKitCore/UIKit-3698.140/UICollectionViewData.m:447

Did your answer relate to this question?

**Comment by hackiftekhar** [comment]
@adolph-suntao your problem is due to your UICollectionView, it has nothing to deal with the library.

@xuwenxindeai I didn't find anything related to the library in crash stack. I suppose it also due to some of your project issue. But I can look into this if you provide me a demo project.
