### ISSUE TITLE
Translate done button text

### ISSUE THREAD

**Issue by mortenholmgaard** [hackiftekhar/IQKeyboardManager#185]
I would be nice if the done text was translated as native keyboard done buttons, but for now I just need a way to write a custom button text for the done button. Maybe add a argument to this method:
`[textField1 addDoneOnKeyboardWithTarget:self action:@selector(doneAction:)];`

**Comment by hackiftekhar** [comment]
This method is perfect for you. It's already present:
 `- (void)addRightButtonOnKeyboardWithText:(NSString*)text target:(id)target action:(SEL)action;`

**Comment by mortenholmgaard** [comment]
Okay - but I also need next and previous buttons - how to get both?

**Comment by hackiftekhar** [comment]
Ok, so probably you need to edit some code of IQUIView+IQKeyboardToolbr.m

**Comment by hackiftekhar** [comment]
Added new methods to add previous/next/rightButtonItem.

**Comment by mortenholmgaard** [comment]
Thanks when will the next release to pods be?
