### ISSUE TITLE
disabledToolbarClasses is not working

### ISSUE THREAD

**Issue by abhijit07cp** [hackiftekhar/IQKeyboardManager#1850]
In latest version of IQKeyboardManagerSwift, there is an issue for disabledToolbarClasses.
disabledToolbarClasses is not working at all and I also found the reason.

in class IQKeyboardManagerSwift -> IQKeyboardManager+Internal

Method name privateIsEnableAutoToolbar

Line numbers 131 to 133

if disabledToolbarClasses.contains(where: { textFieldViewController.isKind(of: $0) }) {
                enableToolbar = true
            }

Here it should return false but it's returning true so disabledToolbarClasses is not working at all

**Comment by sugitatestblue** [comment]
version `6.5.6` works well.
version `6.5.9` doesn't work.

I guess author forgot to the function when s/he refactoring.

**Comment by abhijit07cp** [comment]
@hackiftekhar any update on this issue?

**Comment by vapor-pawelw** [comment]
@hackiftekhar up. Also experiencing this issue, and also found what the original author has written regarding `enableToolbar = true` in the diffs and believe it to be the issue.

**Comment by jingxuelong** [comment]
@hackiftekhar any update on this issue?

**Comment by hackiftekhar** [comment]
@vapor-pawelw That's exactly the problem. I fixed it.
