### ISSUE TITLE
Xcode 13.2 + Carthage + IQKeyboardManager 6.5.9 fails to compile.

### ISSUE THREAD

**Issue by madhusudhanraoch** [hackiftekhar/IQKeyboardManager#1852]
Describe the bug
Xcode 13.2 + Carthage + IQKeyboardManager 6.5.9 fails to compile.
To Reproduce
Running xcode 13.2, just IQKeyboardManager / Swift in a swift project
Expected behavior
Builds
Screenshots
*** Fetching IQKeyboardManager
*** Checking out IQKeyboardManager at "v6.5.9"
*** xcodebuild output can be found in /var/folders/qc/h00f5gc545qfc8bq2nb3zg_w0000gn/T/carthage-xcodebuild.RFBYYf.log
*** Building scheme "IQKeyboardManager" in IQKeyboardManager.xcodeproj
*** Building scheme "IQKeyboardManagerSwift" in IQKeyboardManager.xcodeproj
Build Failed
Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/safuan/Desktop/FifthList/Carthage/Checkouts/IQKeyboardManager/IQKeyboardManager.xcodeproj -scheme IQKeyboardManagerSwift -configuration Release -derivedDataPath /Users/safuan/Library/Caches/org.carthage.CarthageKit/DerivedData/13.2_13C90/IQKeyboardManager/v6.5.9 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive VALIDATE_WORKSPACE=NO -archivePath /var/folders/x8/dnk5cymd3wz1w_ccvz755pr00000gq/T/IQKeyboardManager SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/safuan/Desktop/FifthList/Carthage/Checkouts/IQKeyboardManager)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/x8/dnk5cymd3wz1w_ccvz755pr00000gq/T/carthage-xcodebuild.bzYYVG.log

Versions
Xcode: 13.2
Mac OS: 11.6
Simulator/Device Name: iPhone 12 mini
Library Version: 3.5.9

**Comment by Droppix** [comment]
+1 same

"keyboardShowNotification..."

**Comment by r-plus** [comment]
v6.5.7, v6.5.8 too.

**Comment by gordon7up** [comment]
Same here, any fix on this one?

**Comment by tiskender2** [comment]
same

**Comment by lee5783** [comment]
I got same issue here. I tried to open project inside `Checkout` folder
![image](https://user-images.githubusercontent.com/5806269/150634338-bb38399f-b7a9-4488-a14f-ed9bfc4553d1.png)
It looks like above functions are missing.

**Comment by ianfagundes84** [comment]
Hey Folks, here I could build my project using this line.
I really expected that it helps and works as worked for me.

pod 'IQKeyboardManagerSwift', '~> 6.5.0', :modular_headers => true

My best wishes

**Comment by stherold** [comment]
Any progress here? We also have this problem...

**Comment by alex851209** [comment]
Has anyone solved this? Same issue today...

**Comment by nilshott** [comment]
I had the same issue and fixed it here: https://github.com/nilshott/IQKeyboardManager
As I had to delete a few blocks of backwards compatibility code and introduced a ton of changes by updating the Swift version, I will not create a pull request on the main project.
Use at your own discretion, this is just a quick fix without any understanding of the underlying project.

**Comment by stherold** [comment]
Will there be a new release soonish with this fix @hackiftekhar ?
