### ISSUE TITLE
It will be nice to add custom items to keyboard Toolbar

### ISSUE THREAD

**Issue by darkwind666** [hackiftekhar/IQKeyboardManager#1853]
Hi! It will be nice to add custom items for Toolbar. 
Right now IQKeyboardManager support only 3 items - PreviousBarButtonItem, NextBarButtonItem, DoneBarButtonItem. How i can add fourth item, like Copy&Paste ButtonItem ? I plan to place it on the right side of PreviousBarButtonItem and NextBarButtonItem.

I can create inputAccessoryView like textfield.inputAccessoryView = toolbar, but i want to save 3 items from default IQKeyboardManager toolbar.

**Comment by hackiftekhar** [comment]
This will open too many things to handle that's why I only created a default toolbar for general purposes and open opportunities to set your own inputAccessoryView by using textField.inputAccessoryView = yourOwnToolbar and do your customization by your own way. :)
