### ISSUE TITLE
IQKeyboardManagerSwift Up / Down arrows not shown

### ISSUE THREAD

**Issue by perumal1216** [hackiftekhar/IQKeyboardManager#1855]
**Describe the bug**

I used pod IQKeyboardManagerSwift auto adjust UITextFields.

I have used main stack view and inside used three StackViews in first stack I have UILabel and UITextField, In second one  UILabel , UITextField & last one UILabel , UITextField..

when tap on first textfield keyboard appears toolbar with done button only 

Note - I used throughout the app its working as expected except only below mentioned screen 

**To Reproduce**

**Expected behavior**
When tap on first text field should appear keyboard toolbar with done and up/down arrows.

**Screenshots**
![Simulator Screen Shot - iPhone 12 - 2021-12-24 at 15 43 42](https://user-images.githubusercontent.com/26454153/147344119-faf773b2-ca7e-4a0b-9891-2154f619989e.png)

### Versions
**Xcode:** 13.0
**Mac OS:**  11.6
**Simulator/Device:** both
**Simulator/Device Name:** iPhone 12

**Comment by hackiftekhar** [comment]
This might be because your textfields are not inside same UIView. There might be different containers of your UITextFields.
