### ISSUE TITLE
Bug on iOS 15.x when clicking "done" with bad UI repositioning

### ISSUE THREAD

**Issue by gduh** [hackiftekhar/IQKeyboardManager#1858]
**Describe the bug**

It seems to occurs only with iOS 15.X. Seems to work fine with iOS 14.8.1
UIViewController which contains : UINavigationBar and UITabBar components. And between them, 2 UIVIew, the second one including UITextFields.

On the 2nd view (See screenshot below) the user fill in the UITextViews, then he clicks the done's button . The UI is not OK as the "Top up" button appears under the TabBar. It should appears like the screenshot "UI OK", above the TabBar.
If the user select another tab and then return to the previous, now, the UI is OK.

**To Reproduce**

**Expected behavior**
On "done" the UI should redraw correctly.

**Screenshots**
UI OK:
<img width="430" alt="UI_OK" src="https://user-images.githubusercontent.com/15440947/150313519-24e3749f-0189-4cbf-acef-3bd9a7a22053.png">

UI NOT OK : 
<img width="432" alt="UI_NOTOK" src="https://user-images.githubusercontent.com/15440947/150313603-30d06ce3-21d1-4f39-9445-1d364803f879.png">

**Demo Project**

### Versions
**Xcode:** 13.2.1
**Mac OS:** 12.0.1
**Simulator/Device:** 12
**Simulator/Device Name:** iPhone XR / 12 /  12 PRO
**Library Version:** 6.5.9

**Additional context**

**Comment by kishan-1211** [comment]
Facing the same Issue!

**Comment by himanshu2024** [comment]
Facing The Same Issue.
<img width="490" alt="Screenshot 2022-01-25 at 11 02 35 AM" src="https://user-images.githubusercontent.com/14979943/150917129-b7dd4414-1eab-4a30-ae00-e437cf3e0b77.png">

**Comment by hemant-avaal** [comment]
same issue. For me the textview overlaps with keyboard when goes up and goes a bit down the safe area when DONE is pressed..

When keyboard is up : 
![Screenshot 2022-01-31 at 12 15 35 PM](https://user-images.githubusercontent.com/97078292/151750271-1adb7165-708d-49d2-a041-6892bb72f377.png)

When keyboard goes down : 
![Screenshot 2022-01-31 at 12 15 46 PM](https://user-images.githubusercontent.com/97078292/151750350-7025fcae-2cd9-46e3-8735-2b0bea849921.png)

-----------------------------------------------

Earlier/Expected results : 
![Screenshot 2022-01-31 at 12 15 57 PM](https://user-images.githubusercontent.com/97078292/151750399-432917e6-5c27-4241-8b73-50be003fcbc1.png)

**Comment by jaceklapinski** [comment]
same problem

**Comment by karlmcgeough** [comment]
Also have this issue

**Comment by ClaireRimel** [comment]
idem

**Comment by zahidshaikh795** [comment]
@MuneebaMeer10  where did you write that code in willAppear or didLoad?

**Comment by zahidshaikh795** [comment]
Does anyone find the solution I am facing the same issue?

**Comment by hackiftekhar** [comment]
Can someone share a demo project here?
