### ISSUE TITLE
canAdjustTextView not working

### ISSUE THREAD

**Issue by fahlout** [hackiftekhar/IQKeyboardManager#187]
First of all, love this library!

I set the boolean for canAdjustTextView to true (working with the swift version), but it doesn't do anything different to when it was set to false. My textView is inside a scrollView, but still moves up everything including the navigation bar instead of adjusting the height of the textview to compensate for the keyboard and just scroll the scrollview up.

**Comment by hackiftekhar** [comment]
If your textView is inside scrollView then first priority will be given to scrollView to scroll it to compensate for keyboard.

**Comment by fahlout** [comment]
my textView is inside a scrollView but it has a height larger than the size of the screen that is left when the keyboard is showing, but instead of resizing the textview and scrolling the scrollview to the right position it scrolls the entire view including the navbar, which doesn't seem to be the proper behavior for the canAdjustTextView property

**Comment by hackiftekhar** [comment]
ok, if you are observing it's not a proper behaviour, then could you please create a demo and share with me? So I can also take a look at buggy behaviour.

**Comment by fahlout** [comment]
https://raw.githubusercontent.com/fahlout/Resources/master/keyboardTextViewDemo.mov here is the link to a demo video. Might not show in Safari, but the link worked in Chrome for me. Please let me know what you think about the beahavior. I would like the navbar to stay where it is and the textview to change its height to fit on screen and the scrollview maybe scroll a little bit also to compensate. Thanks!

**Comment by hackiftekhar** [comment]
Thanks for the video, I'll check it bu tomorrow and will let you know my feedback on textView and scrollView behaviour.

**Comment by hackiftekhar** [comment]
I checked the video and found it's not a bug but a feature of IQKeyboardManager. Your textView height is already too big, IQKeyboardManager worries about hiding bottom part of UITextView. That's why IQKeyboardManager tries to show maximum size of textView that current screen can show. If library doesn't up the view, then library break it's own basic principle of moving textField/textView out of the way. Does this all makes sense to you?

**Comment by fahlout** [comment]
I understand what you're saying, but as long as the textview is still big enough to be able to scroll your library shouldn't worry about hiding the bottom part of the textview since a text view basically has a scroll view inside and the user will just be able to scroll the text view if indeed there is more text than what the textview can show.

**Comment by fahlout** [comment]
I just personally don't like the idea of moving the navbar up since it looks a little weird in my opinion

**Comment by hackiftekhar** [comment]
I like your idea of not moving navBar. But still we're human being and answer what looks good and what bad, library is not a human and can't able to decide it will going to look good or bad. I'll try to fix nav bar issue if possible for me. Could you please share a demo code so I'll be able to debug and fix my library?

**Comment by fahlout** [comment]
I understand. Thanks for looking into it. I'll try to have some sample code up as soon as I can.

**Comment by fahlout** [comment]
https://github.com/fahlout/Resources I put a sample project inside this repo. Hope it helps.

**Comment by hackiftekhar** [comment]
Thanks for the demo, I'll try to figure out if I can fix navBar issue.
