### ISSUE TITLE
Difficult to read label on iOS6

### ISSUE THREAD

**Issue by vectorialgradha** [hackiftekhar/IQKeyboardManager#188]
When I run the app on iOS6 simulator I get a very dark grey label for each field title/suggestion. How can I change the color of this label? The color matches iOS7 and 8, so this would require a version conditional.
![captura de pantalla 2015-03-30 a la s 17 19 10](https://cloud.githubusercontent.com/assets/11269962/6899479/173c7c80-d701-11e4-8ce4-a8b955d58c8d.png)

**Comment by hackiftekhar** [comment]
Yes, you're right, I'll try to add iOS5 & iOS6 compatibility, for now, you can take a look on IQPreviousNextSegmentedControl class.

**Comment by vectorialgradha** [comment]
Something like this works of you don't mind not being able to customize the color. I guess that's ok anyway since the disabling of the control disables any color attributes on iOS 7+.
```diff
diff --git a/Pods/IQKeyboardManager/IQKeyBoardManager/IQToolbar/IQTitleBarButtonItem.m b/Pods/IQKeyboardManager/IQKeyBoardManager/IQToolbar/IQTitleBarButtonItem.m
index fb7c0d2..ced81b4 100644
--- a/Pods/IQKeyboardManager/IQKeyBoardManager/IQToolbar/IQTitleBarButtonItem.m
+++ b/Pods/IQKeyboardManager/IQKeyBoardManager/IQToolbar/IQTitleBarButtonItem.m
@@ -23,6 +23,7 @@
 
 #import "IQTitleBarButtonItem.h"
 #import "IQKeyboardManagerConstants.h"
+#import "IQKeyboardManagerConstantsInternal.h"
 
 #import <UIKit/UILabel.h>
 
@@ -46,7 +47,14 @@
         self.title = title;
         
         self.customView = _titleLabel;
-        self.enabled = NO;
+        if (IQ_IS_IOS7_OR_GREATER)
+        {
+            self.enabled = NO;
+        }
+        else
+        {
+            [_titleLabel setTextColor:[UIColor whiteColor]];
+        }
     }
     return self;
 }
```

**Comment by hackiftekhar** [comment]
Fixed internal label font color
