### ISSUE TITLE
Keyboard stops working after changing app language / locale

### ISSUE THREAD

**Issue by bothofusmobiledev** [hackiftekhar/IQKeyboardManager#1880]
**Keyboard stops working after changing app language / locale**
I'm using iOS default localization in my app and after changing language IQKeyboard stops working. No done button and no toolbar appears.

I tried in different iOS versions and devices, I got same issue.

**Comment by hackiftekhar** [comment]
I need more information on this since I'm unable to find out the cause of this issue. May be demo project would be better.
