### ISSUE TITLE
IQKeyboardManager 6.5.9 not work on ios 11.4.1&12.3.1,but work on ios 15.2

### ISSUE THREAD

**Issue by dagundejuzi** [hackiftekhar/IQKeyboardManager#1881]
UI looks like this:
<img width="210" alt="image" src="https://user-images.githubusercontent.com/16382880/155279750-4b809445-060f-4107-9fde-489f403e728b.png">
It's work well on iPhone11 ios15.2，but not work on iPhone8 ios11.4.1.

I found the difference here：
IQKeyboardManager.m, function  keyboardDidShow: 
<img width="672" alt="image" src="https://user-images.githubusercontent.com/16382880/155281057-7ad1538d-369e-4245-bfd5-3802cd356514.png">

Controller's type is a subclass of UITabBarController. On ios15.2,  modalPresentationStyle is UIModalPresentationPageSheet, but on ios11.4.1, controller.modalPresentationStyle is UIModalPresentationFullScreen.
It is here that the textView can not be moved up normally。

**Comment by hackiftekhar** [comment]
I'll see what might be the issue here.

**Comment by caimengnan** [comment]
I got the same issue in keyboardDidShow delegate ，but the problem is my controller`s modalPresentationStyle is UIModalPresentationCustom,so optimizedAdjustPosition function can not be stepped ，I defined the vc`s present style. Maybe this place have to be extended by author.

**Comment by caimengnan** [comment]
> I'll see what might be the issue here.

I got the same issue in keyboardDidShow delegate ，but the problem is my controller`s modalPresentationStyle is UIModalPresentationCustom,so optimizedAdjustPosition function can not be stepped .

**Comment by hackiftekhar** [comment]
@dagundejuzi Can you please share the demo project since I'm unable to understand if you have presented the UITabBarController or using directly. Specially I'm unable to recreate the scenario which you are able to.

**Comment by arunj15** [comment]
Hi
Did you able to fix this problem, I am also facing similar issue in ipad version 12.5.5

**Comment by hackiftekhar** [comment]
I need a demo project to recreate the situation.

**Comment by hackiftekhar** [comment]
Can you please try with the master branch version now? this function got removed recently and might be fix your case.
