### ISSUE TITLE
objc 6.5.9 ios15 : statusbar become transparent when keyboard show

### ISSUE THREAD

**Issue by cosina1985** [hackiftekhar/IQKeyboardManager#1882]
statusbar become transparent when keyboard show,  uitableview content show under statusbar

IOS 15.3.1
IQkeyboardManager 6.5.9  objc

![WechatIMG17](https://user-images.githubusercontent.com/218860/156905590-777906f0-8db5-43a9-83b0-172112e351e8.jpeg)

after keyboard show:
![WechatIMG16](https://user-images.githubusercontent.com/218860/156905588-6e5d4836-ff38-46de-842f-c57a022f7d30.jpeg)

https://user-images.githubusercontent.com/218860/156905535-c9cab113-e7ab-40e6-b05f-04ded748efc6.mp4

**Comment by NourhanHosny** [comment]
@cosina1985  did you find any solution for this ?

**Comment by nguyen703** [comment]
I encountered the same problem with my app. Xcode 13.3, debugged on iOS 15.4.

**Comment by nguyen703** [comment]
> problem

After quitting Xcode and the emulator, when I re-open run the app, the problem seems to be gone. I don't know why but that works for me.

**Comment by hackiftekhar** [comment]
This looks to be an iOS 15 problem with Xcode 13.3 since the navigation bar related API's have been changed in iOS 15.

**Comment by keegho** [comment]
I have this same issue with ios 17.4. Im building a chat app and when the keyboard is pushed for the user to write a message to be displayed in the tableview above the table view is visible from the top status bar. Same as the images sent above. What is the solution for his>??

**Comment by hackiftekhar** [comment]
@keegho You should be using navigation bar related API's to change it's appearance depending on different configurations.
