### ISSUE TITLE
 IQPreviousNextView Is Not Open

### ISSUE THREAD

**Issue by AndyIbanez** [hackiftekhar/IQKeyboardManager#1883]
**Describe the bug**

I have inherited a very old project in which I need to update the dependencies. One of them is to update this dependency to version 6.5.9.

For years, there was a view that inherited from ` IQPreviousNextView`. I cannot compile now because ` IQPreviousNextView` is not marked as `open`. 

```
Cannot inherit from non-open class 'IQPreviousNextView' outside of its defining module
```

I could just send a PR that marks the culprit class as open and move on with my day, but I figure there must be a reason as to why that is no longer inheritable. Is it not really a thing to inherit from `IQPreviousNextView` anymore? What would be the right way to deal with this? Keep in mind this project I inherited uses this code in a lot of screens I have no access to, so I am afraid of breaking something without knowing. Originally, the library was on version 6.5.9.

I also found it odd that the class is an empty class that simply extends from UIView. It doesn't seem to do anything so maybe it isn't necessary anymore?

```swift
@available(iOSApplicationExtension, unavailable)
@objc public class IQPreviousNextView: UIView {

}
```

**To Reproduce**
1. Create a new file (MyView). 
2. Make it inherit from `IQPreviousNextView` (`class MyView: IQPreviousNextView`).
**Expected behavior**
No errors should occur when building the project.

### Versions
**Xcode:** 12.5.1
**Mac OS:** 11.6.5
**Simulator/Device:** 15.4
**Simulator/Device Name:** iPhone 13 Pro Max
**Library Version:** 6.5.9

**Comment by hackiftekhar** [comment]
Sorry for this. I marked it open now and will be available soon.
