### ISSUE TITLE
当弹出输入框的时候，部分机型会crash

### ISSUE THREAD

**Issue by Mamakou** [hackiftekhar/IQKeyboardManager#1886]
当我弹出键盘的时候，就报这个错误了，unrecognized selector [_accessibilityFindSubviewDescendant:] sent to UITextEffectsWindow。根据分析得出的结论：

一下是bugly反馈的情况

04-10 21:53:32.169 [ UIEditingOverlayViewController ] WillAppear
704-10 21:53:32.187 [ UISystemKeyboardDockController ] WillAppear
804-10 21:53:32.222 [ UISystemKeyboardDockController ] WillAppear
904-10 21:53:32.226 [ UICompatibilityInputViewController ] WillAppear
1004-10 21:53:32.226 [ UICompatibilityInputViewController ] WillAppear
1104-10 21:53:32.227 [ UICompatibilityInputViewController ] WillAppear
1204-10 21:53:32.230 [ UICompatibilityInputViewController ] WillAppear
1304-10 21:53:32.230 [ UICompatibilityInputViewController ] WillAppear

**Comment by hackiftekhar** [comment]
Not sure what might be reason, but this function doesn't look to be called from the library. Send more information/evidence if you are sure that this is caused due to library.

**Comment by smallPlant** [comment]
Has this problem been solved? What is the cause of the problem？

**Comment by shijian123** [comment]
I also encountered the same problem😭

**Comment by shijian123** [comment]
I also encountered the same problem😭
