### ISSUE TITLE
How to dismiss keyboard on scroll SwiftUI. Looking for solution in SwiftUI

### ISSUE THREAD

**Issue by chaitanya-neosoft** [hackiftekhar/IQKeyboardManager#1887]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Demo Project**
If applicable, add demo project.

### Versions
**Xcode:** x.x
**Mac OS:** xx.xx.x
**Simulator/Device:** xx.x
**Simulator/Device Name:** iPhone xx
**Library Version:** x.x.x

**Additional context**

**Comment by hackiftekhar** [comment]
I haven't explored SwiftUI yet so can't answer. Sorry! Probably someone else who experience same situation in SwiftUI can answer here.

**Comment by dipkasyap** [comment]
@chaitanya-neosoft  : Can you describe your issue with screen shots if possible .
