### ISSUE TITLE
Stops working after Password AutoFill on a Text Input View

### ISSUE THREAD

**Issue by dipkasyap** [hackiftekhar/IQKeyboardManager#1888]
**To Reproduce**
Steps to reproduce the behaviour:
User Keyboard in password auto-filled enable textfield and after that IQ keyboard stops working 

**Screenshots**
<img width="1174" alt="Screen Shot 2022-05-12 at 9 57 06 am" src="https://user-images.githubusercontent.com/12591229/167978014-2670a018-d901-414e-9045-dac12e4c5b40.png">

### Versions
**Xcode:** 13.3
**Mac OS:** 12.3.1
**Simulator/Device:** ios 14 plus  
**Simulator/Device Name:**  ANY 
**Library Version:**  IQKeyboardManagerSwift (6.5.9)

**Comment by hackiftekhar** [comment]
I need to test with the password autofill text field about how it's behaving in this situation.

**Comment by hackiftekhar** [comment]
Can you please share a demo project with me?

**Comment by hackiftekhar** [comment]
I tested the project with autofill and it doesn't reproduce the isuse.
