### ISSUE TITLE
Issue with ToolBar 

### ISSUE THREAD

**Issue by Shiv-kiwitech** [hackiftekhar/IQKeyboardManager#1889]
I am using Xcode 13.3.1 and we are able to run project on simulator & devices. We are able to create Archive for Xcode. But we try to create ipa from then we getting issue:

** ARCHIVE FAILED **

The following build commands failed:
	CompileC /Users/kiwitech/Library/Developer/Xcode/DerivedData/topfan-2-ios-awbsnhcioizpwxdxesfwysmvcpms/Build/Intermediates.noindex/ArchiveIntermediates/TopFan/IntermediateBuildFilesPath/topfan-2-ios.build/Release-iphoneos/TopFan.build/Objects-normal/arm64/TFPostMessageViewController.o /Users/kiwitech/.jenkins/workspace/TopFan-iOS-Development/topfan-2-ios/TFPostMessageViewController.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'TopFan' from project 'topfan-2-ios')
(1 failure)

The reason by which it's  getting failed due to this line in our one of view controller

   -(void)postAddToolbar {

       UIToolbar* keyboardToolbar = [[UIToolbar alloc] init];
       [keyboardToolbar sizeToFit];
       UIBarButtonItem *flexBarButton = [[UIBarButtonItem alloc]
                                         initWithBarButtonSystemItem:UIBarButtonSystemItemFlexibleSpace
                                         target:nil action:nil];
       UIBarButtonItem *doneBarButton = [[UIBarButtonItem alloc]
                                         initWithBarButtonSystemItem:UIBarButtonSystemItemDone
                                         target:self action:@selector(textViewDoneButtonPressed)];

       [doneBarButton setTitleTextAttributes:@{NSForegroundColorAttributeName:[UIColor blackColor]} forState:UIControlStateNormal];

       keyboardToolbar.items = @[flexBarButton, doneBarButton];
       self.meTextInputView.inputAccessoryView = keyboardToolbar;
   }
   -(void)textViewDoneButtonPressed
   {
       [self.meTextInputView hideKeyboard];
   }

Is there any conflict with your SDK. Please let us  know.
Thanks & Regard
Shiv

**Comment by hackiftekhar** [comment]
This is a native code you wrote. This do not conflict with my library.

**Comment by Shiv-kiwitech** [comment]
Yes, But I do not allow to make archive form Jenkins. As I remove these line of code from project then I am able to create archive from Jenkins.
