### ISSUE TITLE
Ability to call next/previous from code

### ISSUE THREAD

**Issue by Emailrus** [hackiftekhar/IQKeyboardManager#189]
Hi,

From what I see, currently it is not possible to call neither nextAction in IQKeyboardManager nor goToNextResponderOrResign in IQKeyboardReturnKeyHandler. What do you think about having related to those methods in public?
The reason why I'm looking for this is to implement custom inputView for the text field, which should basically call next on user interaction.

Thanks for response and for the library.

**Comment by hackiftekhar** [comment]
Yes, that's a good idea. Will keep in mind and implement something for this.
