### ISSUE TITLE
The text exceeds one line, the input component height is updated, and the page is not moved up

### ISSUE THREAD

**Issue by ff-frida** [hackiftekhar/IQKeyboardManager#1891]
**Describe the bug**
IQKeyboardManagerSwift (6.5.9) & SnapKit 

When the keyboard pops up and moves on the page, the input component exceeds one line. The height of the component is updated through snapkit, but the entire page does not move up. The keyboard covers the bottom of the input component. It can be restored to normal after closing the keyboard and entering again.

**To Reproduce**
1. input
2. change height,Text exceeds one line, update height
self.RSKPlaceholderTextView.snp.updateConstraints { mm in
       mm.height.equalTo(size.height)
}

**Screenshots**

![IMG_8105](https://user-images.githubusercontent.com/18607031/174464278-b644e7be-35ef-45c3-bbc1-2c4626845ddd.PNG)
![IMG_8106](https://user-images.githubusercontent.com/18607031/174464281-defe2f8e-f2b9-49ec-9af8-e59e74a80386.PNG)

### Versions
**Xcode:** 13.4.1
**Mac OS:** 12.3.1
**Simulator/Device:** xx.x
**Simulator/Device Name:** iPhone 6sp 15.4
**Library Version:** IQKeyboardManagerSwift (6.5.9)

**Comment by hackiftekhar** [comment]
For these cases, you have to manually call `reloadLayoutIfNeeded()` of IQKeyboardManager when the textView frame has changed, because the library doesn't know that the component height has been changed. The library only observe initial position and keyboard events.

**Comment by 542604974** [comment]
请问你是怎么修了这个BUG？
