### ISSUE TITLE
TextView OverLapping with Keyboard on iOS 15

### ISSUE THREAD

**Issue by ErAshu** [hackiftekhar/IQKeyboardManager#1893]
TextView OverLapping with Keyboard on iOS 15. This is working fine with TextsFields.
![Simulator Screen Shot - iPhone 11 - 2022-07-02 at 20 20 40](https://user-images.githubusercontent.com/4178384/177005556-182cf8a0-0526-4ade-b8bd-e8e58b120164.png)

**Comment by hackiftekhar** [comment]
@ErAshu, can you please share the demo project with me? It would be helpful for me to debug the issue once I get some time.

**Comment by ErAshu** [comment]
Ok, i will share the demo Project. Give me sometime.

**Comment by ErAshu** [comment]
[KeybordCheck.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/9228487/KeybordCheck.zip)

Run this Project and tap on textview. First Time, Textview will overlapped.

**Comment by hackiftekhar** [comment]
Thanks @ErAshu for the demo. I'll check it soon once I get some time.

**Comment by hackiftekhar** [comment]
I checked the demo with recent version of the library and this is no longer reproducible with the recent version of the library.
