### ISSUE TITLE
IQKeyboardManager.shared.enabled = true throwing error in Xcode

### ISSUE THREAD

**Issue by alexkhazzam** [hackiftekhar/IQKeyboardManager#1896]
` IQKeyboardManager.shared().isEnabled = true` works for some reason whereas `IQKeyboardManager.shared.enabled` is giving the error **Value of type '() -> IQKeyboardManager' has no member 'enabled'**. It is a bit odd that the former code snippet is working, given that it is not present anywhere on the README. Just thought I should point this out! Anyways, thanks for this amazing package.

**Comment by hackiftekhar** [comment]
Are you using Obj-C version in swift?

**Comment by robee9** [comment]
> `IQKeyboardManager.shared().isEnabled = true` works for some reason whereas `IQKeyboardManager.shared.enabled` is giving the error **Value of type '() -> IQKeyboardManager' has no member 'enabled'**. It is a bit odd that the former code snippet is working, given that it is not present anywhere on the README. Just thought I should point this out! Anyways, thanks for this amazing package.

Yes, Just now I came across the same error, but, the line of code "IQKeyboardManager.shared().isEnabled = true" is not showing any error.

**Comment by anvar0522** [comment]
IQKeyboardManager.shared.enable = true
