### ISSUE TITLE
Set the keyboardDistanceFromTextField value to 70, but the distance is greater than 70 after the keyboard pops up and then bounces back

### ISSUE THREAD

**Issue by twisturn** [hackiftekhar/IQKeyboardManager#1898]
Set the keyboardDistanceFromTextField value to 70, but the distance is greater than 70 after the keyboard pops up and then bounces back

iPhone13

https://user-images.githubusercontent.com/17715937/180680657-a0fc1e50-d986-4f6d-aae9-02b72c0ca887.mp4

version：15.1

**Comment by hackiftekhar** [comment]
Can you please share a demo project for this?

**Comment by Ksenia-Ksu** [comment]
I have the same problem, it is very annoying, what can you advice?

**Comment by francuim-d** [comment]
@hackiftekhar I am also experiencing this bug. Perhaps the problem is in this piece of code.
```
let bottomLayoutGuide: CGFloat = (textFieldView is UIScrollView && textFieldView.responds(to: #selector(getter: UITextView.isEditable))) ? 0 : rootController.view.layoutMargins.bottom  //Validation of textView for case where there is a tab bar at the bottom or running on iPhone X and textView is at the bottom.

//  Move positive = textField is hidden.
//  Move negative = textField is showing.
//  Calculating move position.
var move: CGFloat = min(textFieldViewRectInRootSuperview.minY-(topLayoutGuide), textFieldViewRectInWindow.maxY-(window.frame.height-kbSize.height)+bottomLayoutGuide)
```
Here, the height of the keyboard is subtracted from the height of the window, and then the bottomLayoutGuide is added. It turns out that the bottomLayoutGuide is counted twice, because the height of the keyboard already contains the height of the bottomLayoutGuide

**Comment by yusufterzi** [comment]
I have same problem too.

**Comment by Ksenia-Ksu** [comment]
And what about the solution of this problem? Anyone can help?

**Comment by lidorf-gurushots** [comment]
+1 any updates about this bug?

**Comment by big-zZ** [comment]
you can add a _Notification_ to get the Keyboard's frame, then in the selector method to make _Y-axis offset animation_ for related view's by setting _transform_
 **[[NSNotificationCenter defaultCenter] addObserver:self
                                             selector:@selector(keyboardFrameDidChange:)
                                                 name:UIKeyboardWillChangeFrameNotification
                                               object:nil];**

**-(void)keyboardFrameDidChange:(NSNotification*)notice
{
    NSDictionary * userInfo = notice.userInfo;
    NSValue * endFrameValue = [userInfo objectForKey:UIKeyboardFrameEndUserInfoKey];
    CGRect endFrame = endFrameValue.CGRectValue;
_kb_y = endFrame.origin.y;
    
    if (_kb_y < SCREEN_HEIGHT) {
        CGFloat y_interval = _kb_y - NavagationHeight - CGRectGetMaxY(_loginBtn.frame);
        if (y_interval < 0) {
            [RMHelper getKeyWindow].transform = CGAffineTransformTranslate(CGAffineTransformIdentity, 0, y_interval - 10.f);
        }
    } else {
        [RMHelper getKeyWindow].transform = CGAffineTransformIdentity;
    }
}**
This works for me~

**Comment by hackiftekhar** [comment]
> @hackiftekhar I am also experiencing this bug. Perhaps the problem is in this piece of code.
> 
> ```
> // IQKeyboardManager+Position.swift (line 226)
> 
> let bottomLayoutGuide: CGFloat = (textFieldView is UIScrollView && textFieldView.responds(to: #selector(getter: UITextView.isEditable))) ? 0 : rootController.view.layoutMargins.bottom  //Validation of textView for case where there is a tab bar at the bottom or running on iPhone X and textView is at the bottom.
> 
> //  Move positive = textField is hidden.
> //  Move negative = textField is showing.
> //  Calculating move position.
> var move: CGFloat = min(textFieldViewRectInRootSuperview.minY-(topLayoutGuide), textFieldViewRectInWindow.maxY-(window.frame.height-kbSize.height)+bottomLayoutGuide)
> ```
> 
> Here, the height of the keyboard is subtracted from the height of the window, and then the bottomLayoutGuide is added. It turns out that the bottomLayoutGuide is counted twice, because the height of the keyboard already contains the height of the bottomLayoutGuide

I'll see if this is really the problem. You might be correct but I need to verify it once with the code.

**Comment by th-mustache-dk** [comment]
Any progress on this bug? 

I'm experiencing the same problem.

**Comment by hackiftekhar** [comment]
I found out that it was there to fix an animation glitch when we have constraints from the bottom layout guide.
