### ISSUE TITLE
iOS 7.1.2 iPhone 4 swift crash

### ISSUE THREAD

**Issue by markoheyns** [hackiftekhar/IQKeyboardManager#190]
Hi
I have added the swift version to my app and it works great (on simulator and ios8 devices), but when I try to run the app on an iPhone 4 running ios 7.1.2 it crashes initialising (stuck on launch screen) and gives the following error: 
dyld`dyld_fatal_error:
0x2bec60c4:  trap
0x2bec60c8:  nop    

When I try the objective c version of iqkeyboardmanager it works fine on the same device. My app is written in swift so would prefer to use swift version. Do you have any idea what might be causing this issue? Any help will be appreciated.

![screen shot 2015-04-02 at 4 26 19 pm](https://cloud.githubusercontent.com/assets/7879666/6957174/489f8582-d955-11e4-9607-f00740e4a19d.png)

**Comment by markoheyns** [comment]
Has anyone else had a similar problem? Please help

**Comment by mythodeia** [comment]
maybe this can be of assistance https://github.com/hackiftekhar/IQKeyboardManager/issues/111
