### ISSUE TITLE
Keyboard is pushing navigationBar to UP.

### ISSUE THREAD

**Issue by malisanjay5433** [hackiftekhar/IQKeyboardManager#1900]
**Describe the bug**
I have been working on one of project where collecting user information for screen, NavigationBar is custom which has back button, Progress bar for steps, Help button. 

After integrating this library we have faced issue. We want to our navigationBar should be static/Sticky but library pushes up/ moving up. Please find the screen shot. 

Attached demo project ? let me know if there is any idea to fix this issue. ?

Thanks in advance/ 

**Expected behavior**

Should't move navigationBar up, It should static. Only content/Scroll view need to move up 

**Screenshots**
![Simulator Screen Shot - iPhone 8 - 2022-08-02 at 22 42 45](https://user-images.githubusercontent.com/8912602/182435065-33c8dca1-def6-4d2f-ae4b-366210fb9912.png)
![Simulator Screen Shot - iPhone 8 - 2022-08-02 at 22 42 49](https://user-images.githubusercontent.com/8912602/182435086-8a10b735-7517-44cd-8fbd-7c1a2fe07651.png)

**Demo Project**
If applicable, add demo project.
[AnimationExperiment.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/9244384/AnimationExperiment.zip)

> 

### Versions
**Xcode:** x.x
**Mac OS:** xx.xx.x
**Simulator/Device:** xx.x
**Simulator/Device Name:** iPhone xx
**Library Version:** x.x.x

**Additional context**

**Comment by robee9** [comment]
I am experiencing the same behavior.

**Comment by darshanPatel16** [comment]
@malisanjay5433 @robee9
Add your view inside scrollview it will work as expected. 

https://user-images.githubusercontent.com/29564375/182572173-7769b7f6-afc3-4ec8-b2d7-6fa5e932286d.mov

**Comment by max270598** [comment]
try to put this code in ViewDidLoad
extendedLayoutIncludesOpaqueBars = true
this function allows the view to go under the status bar. It is needed because if NavigationBar.isTranslusent = false - IQKeyboardManager will bug

**Comment by robee9** [comment]
> try to put this code in ViewDidLoad()
> extendedLayoutIncludesOpaqueBars = true
> this function allows the view to go under the status bar. It is needed because if NavigationBar.isTranslusent = false - IQKeyboardManager will bug

Thanks max270598,
that code "extendedLayoutIncludesOpaqueBars = true" solved the problem!!

**Comment by Arya-Wang** [comment]
I have encountered the same problem. Is there a solution？

**Comment by CyrilusK** [comment]
Same problem :(

**Comment by hackiftekhar** [comment]
@darshanPatel16 suggested the correct answer for these cases where we have our own custom navigation bar.

**Comment by DDilbilir0700** [comment]
same problem for me too. extendedLayoutIncludesOpaqueBars = true didn't work for my case.
