### ISSUE TITLE
Cells disappears when using UICollectionViewCompositionalLayout and TextView inside cell

### ISSUE THREAD

**Issue by tvrrp** [hackiftekhar/IQKeyboardManager#1901]
**Describe the bug**
I use a UITextField inside a cell. When the cell is at the bottom of the screen, the UICollectionView automatically scrolls to the desired cell when I open the keyboard, but several cells disappear from the screen during the animation.

**To Reproduce**
1. Create CollectionView using UICollectionViewCompositionalLayout. 
2. Create several custom UICollectionViewCells with UITextFields or UITextView. 
3. Choose UITextField near the bottom of the screen.

**Expected behavior**
Cells must not disappear when keyboard is presenting

**Screenshots**
<img width="379" alt="Screenshot 2022-08-05 at 17 44 45" src="https://user-images.githubusercontent.com/36267146/183101570-9f1a22a9-5581-492e-8150-483b6c2d2b06.png">
<img width="490" alt="Screenshot 2022-08-05 at 17 44 40" src="https://user-images.githubusercontent.com/36267146/183101600-6ed29cf0-7540-426b-9a5a-6895a9791bc0.png">

video – https://drive.google.com/file/d/1xoq4YvpnvTVDC4bLu98EzT7OUDnBmEJw/view?usp=sharing

**Demo Project**
If applicable, add demo project.

### Versions
**Xcode:** 13.4.1
**Mac OS:** 12.5
**Simulator/Device:** 15.5
**Simulator/Device Name:** iPhone 8
**Library Version:** 6.5.10

**Additional context**
The problem is also present if we have a sticky header using header.pinToVisibleBounds = true
Video - https://drive.google.com/file/d/11snv48xZN1Jjn01snHmHu_KasGWgMbtR/view?usp=sharing

**Comment by hackiftekhar** [comment]
Got it. I'll see if this issue is fixable.

**Comment by hackiftekhar** [comment]
I found out that this problem is not bound with UICollectionViewCompositionalLayout, it happens with all UICollectionView layouts.
