### ISSUE TITLE
The keyboard does not appear completely

### ISSUE THREAD

**Issue by roritobach** [hackiftekhar/IQKeyboardManager#1902]
Hello guys, 
Sometime when keyboard show up i only see the tab bar and not the keyboard. Actually the keyboard is active because if you click somewhere a letter will be tapped. I show you a screenshot.

I never had this bug on Simulator but only on real device. 

![image0](https://user-images.githubusercontent.com/16644871/183650101-755eec33-6773-42d6-a81e-d2339932f749.png)

Thx for helping

**Comment by jianglanmei** [comment]
你好，光标https://user-images.githubusercontent.com/11780459/205238851-3de7cba8-3e4e-488d-8ba2-fc229578c235.mp4ks，但我不能召唤键盘。

**Comment by hackiftekhar** [comment]
This is a setting in simulator. Using it you can turn on/off software keyboard.
