### ISSUE TITLE
Crash when click to textfield into the UITableview

### ISSUE THREAD

**Issue by quannguyen90** [hackiftekhar/IQKeyboardManager#1903]
**Describe the bug**
i am create Form using UItableview contains UITextfield in multiple uitableviewcell, sometimes user will see crash when input data to form.

Please helps me debugs, thanks

**To Reproduce**

**Screenshots**
<img width="1216" alt="Screen Shot 2022-08-15 at 09 55 25" src="https://user-images.githubusercontent.com/4519199/184569629-bb750032-fbbd-4704-a1ff-191715f6ee29.png">

**Demo Project**
If applicable, add demo project.

### Versions
**Xcode:** x.x
**IOS:** 15.5
**Simulator/Device Name:** iPhone xx

**Library Version:** 6.3.0

**Comment by hackiftekhar** [comment]
I'm unable to find exactly which line of code was crashed. Do you have some more information on it?
