### ISSUE TITLE
iOS 16 NSException: 'Application circumvented Objective-C runtime dealloc initiation for <xxx> object

### ISSUE THREAD

**Issue by luyinuo** [hackiftekhar/IQKeyboardManager#1905]
**Describe the bug**
NSException: Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Application circumvented Objective-C runtime dealloc initiation for <UIViewController> object.'

**Expected behavior**
iOS16 has a "new requirement": because the( UIView / UIViewcontroller) has the initialize method, you can't override the + initialize method in your category,

This will result in not calling_ class_ Setcustomdeallocinitiation ([UIViewcontroller class]), crash will occur. (Xcode 14 compilation is required to reproduce the crash.).

If you must override the + initialize method, you must find a way to call the official method first, and then call your own + initialize method ~ (not recommended)

**Relation Class**
UIView+Hierarchy.m
IQBarButtonItem.m
IQToolbar.m

### Versions
**Xcode:** Xcode14_beta
**Mac OS:** 13.0 Beta
**Simulator/Device:** iOS16_beta8

**Comment by bolo992** [comment]
I have same issue on Xcode 14 RC, is there any fix for this?

**Comment by mapo80** [comment]
Same here!

**Comment by LeoTnT** [comment]
How to solve it

**Comment by zp0708** [comment]
maybe this can solve the problem:

- (UIScrollView*)superScrollView
{
    UIView *superview = self.superview;
    Class UITableViewCellScrollViewClass      = NSClassFromString(@"UITableViewCellScrollView");
    Class UITableViewWrapperViewClass         = NSClassFromString(@"UITableViewWrapperView");
    while (superview)
    {
        //UITableViewWrapperView
        if ([superview isKindOfClass:[UIScrollView class]] && ([superview isKindOfClass:UITableViewCellScrollViewClass] == NO) && ([superview isKindOfClass:UITableViewWrapperViewClass] == NO))
        {
            return (UIScrollView*)superview;
        }
        else    superview = superview.superview;
    }
    
    return nil;
}

**Comment by Platycodon** [comment]
Same here!

**Comment by luyinuo** [comment]
Temporary solution：change method +initialize to +load 
**Relation Class**
UIView+Hierarchy.m
IQBarButtonItem.m
IQToolbar.m

**Comment by keshanf** [comment]
Got the same issue.

**Comment by Platycodon** [comment]
> Same here!

I found when i override + initialize  in UIView(Category) and in any subclass of UIView(I tried UITextField and UIImageView) at the same time.

I changed my own override + initialize  in UIView(Category) to + load. 

And it's good for me.

**Comment by THIEEYHENRY** [comment]
Same here! Can you fix it soon?

**Comment by hackiftekhar** [comment]
I'll install Xcode 14 to see what needs to be done to properly fix this.

**Comment by THIEEYHENRY** [comment]
Thanks you E-mail  ！

**Comment by RookiePyl** [comment]
@hackiftekhar
Thanks. When will this update come to the Pod library?

**Comment by THIEEYHENRY** [comment]
Thanks you E-mail  ！
