### ISSUE TITLE
IQKeyboardManager breaks the Find Selection feature in iOS 16

### ISSUE THREAD

**Issue by HassanTaleb90** [hackiftekhar/IQKeyboardManager#1909]
Using UITextView:
... 
textView.isFindInteractionEnabled = true
...
Using IQKeyboardManager will automatically dismiss the keyboard! and keep the toolbar:
![Simulator Screen Recording - iPhone 14 Pro - 2022-09-19 at 19 51 59](https://user-images.githubusercontent.com/49780321/191071105-77e998b1-6769-470a-9de8-791de55cdc45.gif)

**Comment by hackiftekhar** [comment]
I'll check about this feature.

**Comment by hackiftekhar** [comment]
This is now fixed with caa314afe1ad1ea46d90e2d48184669d9d97e085

**Comment by HassanTaleb90** [comment]
Fixed but there is a weird behavior. All keyboard characters become uppercase for a while.
![Simulator Screen Recording - iPhone 14 Pro - 2022-09-20 at 22 09 50](https://user-images.githubusercontent.com/49780321/191344041-8231523f-eed5-4bed-9d75-49efae1ab4e6.gif)

**Comment by hackiftekhar** [comment]
That is iOS issue, this is reproducible even without the library.
