### ISSUE TITLE
keyboardDistanceFromTextField is not working 

### ISSUE THREAD

**Issue by AllWellNow** [hackiftekhar/IQKeyboardManager#1910]
Hi! 

So I've tried to set keyboardDistanceFromTextField to a different values (from 30 to 300) and the result is still the same

Here's vid and screenshot attached :)

https://user-images.githubusercontent.com/112175849/191386306-bfb3303a-813c-4434-b386-f6d828716702.mp4

<img width="653" alt="Screenshot 2022-09-21 at 2 10 39 AM" src="https://user-images.githubusercontent.com/112175849/191386329-85c415ad-17c2-441a-bbad-e00b571fda60.png">

**Comment by hackiftekhar** [comment]
Can you please provide me a demo project for this?

**Comment by Legitdove** [comment]
> Hi!
> 
> So I've tried to set keyboardDistanceFromTextField to a different values (from 30 to 300) and the result is still the same
> 
> Here's vid and screenshot attached :)
> 
>  Simulator.Screen.Recording.-.iPhone.11.-.2022-09-21.at.02.06.44.mp4 
> 
> <img alt="Screenshot 2022-09-21 at 2 10 39 AM" width="653" src="https://user-images.githubusercontent.com/112175849/191386329-85c415ad-17c2-441a-bbad-e00b571fda60.png">

Yeah I have the same problem. Changing the bottom safe area constraints worked a little bit feels like a very clumsy way to do it and doesn't fully solve the problem. Im not sure what is affecting it

**Comment by CoderJohnhao** [comment]
![image](https://user-images.githubusercontent.com/18332430/201059712-199e0f4f-53b5-4a29-8725-e8dcf1f18d38.png)
iOS14 when UIViewController hidesBottomBarWhenPushed is YES view.frame will be reset by the navigation bar caused by the scrolling failure problem

**Comment by hackiftekhar** [comment]
I'm not sure if you fixed this issue or not, however if it's still reproducible then can you please share a demo project with me?
