### ISSUE TITLE
textview positioning is not accurate in the UITableViewCell 

### ISSUE THREAD

**Issue by AllenYL** [hackiftekhar/IQKeyboardManager#1913]
(1) When the height change of the textview in the UITableViewCell , when reloadLayoutIfNeeded, the contentOffset not accurate . Causes the textview to be obscured by the keyboard.
iPhone X 12.4 is right !

Versions:
Xcode: 13.4.1
Mac OS: 12.5
Simulator/Device Name: iPhone X 15.3.1
Library Version: 6.5.10

<img width="592" alt="截屏2022-09-26 00 44 05" src="https://user-images.githubusercontent.com/16030436/192155120-0db5fc01-e959-46ff-ac3e-b2b16ecf4441.png">

https://user-images.githubusercontent.com/16030436/192155138-9edce9e5-f264-4333-8607-d9dc8543a635.mp4

(2) When the  textview begin edit the contentOffset not accurate . Causes the textview to be obscured by the keyboard.
iPhone X 15.3.1 is right

Versions:
Xcode: 13.4.1
Mac OS: 12.5
Simulator/Device Name: iPhone X 12.4
Library Version: 6.5.10

https://user-images.githubusercontent.com/16030436/192155400-6d01b1c7-9f05-44cf-9a9d-6fbb2d1b9388.mp4

Demo:
[TextDemo.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/9641296/TextDemo.zip)

**Comment by hackiftekhar** [comment]
I'll check the demo project to see if we can apply any fixes for this.

**Comment by hackiftekhar** [comment]
In the demo project it looks to be working. Not sure why you were getting issues at that time.
