### ISSUE TITLE
error on compiling the code

### ISSUE THREAD

**Issue by christopher-18** [hackiftekhar/IQKeyboardManager#1915]
Getting following error while running the code in m2 chip.
<img width="863" alt="Screenshot 2022-09-27 at 20 51 51" src="https://user-images.githubusercontent.com/23613887/192567946-3d458dd4-6529-4aa8-8479-379223eb2675.png">

My laptop is new & xcode version is 13.1. 
Tried below three options as well as deleted derived data.
<img width="751" alt="Screenshot 2022-09-27 at 20 54 22" src="https://user-images.githubusercontent.com/23613887/192568375-699e64aa-dd4d-4bfd-9b22-70d241731ca7.png">

Any help would be appreciated. Stuck since long.

**Comment by BirdArch** [comment]
Did you or could you try Xcode 14? It includes [Swift 5.7](https://developer.apple.com/documentation/xcode-release-notes/xcode-14-release-notes)
