### ISSUE TITLE
xcode 14 with ios16.0.2  error

### ISSUE THREAD

**Issue by JasonScott1990** [hackiftekhar/IQKeyboardManager#1917]
**Describe the bug**
when using xcode14.0.1 with ios16.0.2,  iPhone 8, with iqkeyboardmanager latest version 6.5.10, app will crash when start launch.
In project, we init the library with blowing code:

IQKeyboardManager *keyboardManager = [IQKeyboardManager sharedManager];
keyboardManager.shouldResignOnTouchOutside = YES;
keyboardManager.enableAutoToolbar = NO;

**Screenshots**
![image](https://user-images.githubusercontent.com/10593371/192955360-8dec8d79-8630-444c-a7ca-19573d393eff.png)

### Versions
**Xcode:** 14.0.1
**Mac OS:** 12.6
**Simulator/Device:** 16.0.2
**Simulator/Device Name:** iPhone 8
**Library Version:** 6.5.10

need a solution ASAP.  thanks

**Comment by JosephPoplar** [comment]
+1

**Comment by JosephPoplar** [comment]
Now, I use 6.5.9 and can work

**Comment by JosephPoplar** [comment]
> **Describe the bug** when using xcode14.0.1 with ios16.0.2, iPhone 8, with iqkeyboardmanager latest version 6.5.10, app will crash when start launch. In project, we init the library with blowing code:
> 
> IQKeyboardManager *keyboardManager = [IQKeyboardManager sharedManager]; keyboardManager.shouldResignOnTouchOutside = YES; keyboardManager.enableAutoToolbar = NO;
> 
> **Screenshots** ![image](https://user-images.githubusercontent.com/10593371/192955360-8dec8d79-8630-444c-a7ca-19573d393eff.png)
> 
> ### Versions
> **Xcode:** 14.0.1 **Mac OS:** 12.6 **Simulator/Device:** 16.0.2 **Simulator/Device Name:** iPhone 8 **Library Version:** 6.5.10
> 
> need a solution ASAP. thanks

Now, I use 6.5.9 and can work

**Comment by hukz37** [comment]
@JosephPoplar @JasonScott1990 Is this problem solved? I  test version 6.5.9 and 6.5.10  ，it cannot work

**Comment by jiasongs** [comment]
> @JosephPoplar @JasonScott1990 Is this problem solved? I test version 6.5.9 and 6.5.10 ，it cannot work

https://developer.apple.com/forums/thread/714795?answerId=733147022#733147022

**Comment by JosephPoplar** [comment]
> @JosephPoplar @JasonScott1990 Is this problem solved? I test version 6.5.9 and 6.5.10 ，it cannot work

the reason maybe there are not only one framework that is affected by this problem, just update to Xcode 14.1 can fix this problem.

**Comment by JasonScott1990** [comment]
we recoded relevant view controllers, now the problem solved! thank you for provide these solutions.
