### ISSUE TITLE
UITextView Un-editable Issue

### ISSUE THREAD

**Issue by dlcerva** [hackiftekhar/IQKeyboardManager#192]
I've experienced an issue where I have two UITextFields and finally a UITextView that is not editable. If I navigate to the last UITextField it still has the next button enabled despite the UITextView not being editable. Clicking on it causes the keyboard to disappear and the navbar remain on screen. Selecting 'Done' has no effect.

**Comment by dlcerva** [comment]
The only want to get rid of it is to do the trick you described, setting inputAccessoryView for the UITextView to an empty view. Going this route, I still get a next option, however the navbar does go away now.

**Comment by hackiftekhar** [comment]
ok, I'll debug to reproduce the issue. If found then will try to fix.
