### ISSUE TITLE
IQTextView placeholder值改变没有刷新视图

### ISSUE THREAD

**Issue by AbleLHOne** [hackiftekhar/IQKeyboardManager#1922]
-(void)refreshPlaceholder
{
    if([[self text] length] || [[self attributedText] length])
    {
        if (self.IQ_PlaceholderLabel.alpha != 0) {
            [self.IQ_PlaceholderLabel setAlpha:0];
            [self setNeedsLayout];
            [self layoutIfNeeded];
        }
    }
    else if(self.IQ_PlaceholderLabel.alpha != 1)
    {
        [self.IQ_PlaceholderLabel setAlpha:1];
        [self setNeedsLayout];
        [self layoutIfNeeded];
    }
}

当更新Placeholder 没有触发  [self setNeedsLayout];  [self layoutIfNeeded]; 方法 ，导致视图显示不正常

**Comment by AbleLHOne** [comment]
版本：6.5.10 
复现概率：100%

**Comment by hackiftekhar** [comment]
I don't find that piece of code with the library in latest version. Can you please share a demo project with me?
