### ISSUE TITLE
Not compiling in Physical Device (Signing issue)

### ISSUE THREAD

**Issue by spraveenk91** [hackiftekhar/IQKeyboardManager#1926]
**Describe the bug**
Project is not building on real device and not able to archieve.

**To Reproduce**
I have created a sample project to reproduce this issue. Two of the target has been created. Please, take a look.

**Expected behavior**
Project shouldn't failed when compiling in real device.

**Screenshots**
![Screenshot 2022-11-10 at 4 01 00 PM](https://user-images.githubusercontent.com/3426723/201068276-5d620fc7-e04b-403a-a24b-5b85c0410c01.png)

**Demo Project**
[TestApp.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/9979863/TestApp.zip)

### Versions
**Xcode:** 14.1
**Mac OS:** 12.6.1 (21G217)
**Simulator/Device:** Any iPhone device
**Simulator/Device Name:** Any iPhone device
**Library Version:** 6.5.4

**Comment by spraveenk91** [comment]
Looks like the issue is from XCode 14 and it has been reported already on Cocoapods page below:
https://github.com/CocoaPods/CocoaPods/issues/11534#issuecomment-1273332951

I have another query that why do i get two of the targets in Pod? One for ObjC and another for Swift? And, only swift target is expecting the signing.

**Comment by hackiftekhar** [comment]
It should be your own apple developer account setup. This is off topic I think.
