### ISSUE TITLE
点击系统键盘上的表情按钮切换系统的表情键盘闪退

### ISSUE THREAD

**Issue by xiaowangqinghui** [hackiftekhar/IQKeyboardManager#1928]
<img width="1085" alt="image" src="https://user-images.githubusercontent.com/15713276/203237127-4c81a864-e1f5-4b33-a6d7-2ae9ed60b94e.png">
bu'zhi'doa不知道哪个地方一直被循环调用了

**Comment by wv-y** [comment]
同遇到了类似的报错，但是一直没有复现，请问你这边有解决方案吗？
<img width="530" alt="image" src="https://github.com/hackiftekhar/IQKeyboardManager/assets/58098983/918f76e3-d44a-48b7-a882-eaa3053fff41">

**Comment by hackiftekhar** [comment]
This is not something related to this library.
