### ISSUE TITLE
The keyboard cannot pop up

### ISSUE THREAD

**Issue by jianglanmei** [hackiftekhar/IQKeyboardManager#1929]
I have a problem. Sometimes the keyboard cannot pop up on the iOS16. Do you know the reason?

**Comment by whoisarte** [comment]
Same problem :c

**Comment by jianglanmei** [comment]
> Same problem :c

Hello,this is my problem.Why can't my APP pop up the keyboard? The cursor works, but I can't summon the keyboard. You can see the video

https://user-images.githubusercontent.com/11780459/205238209-d3ba33cf-f3cb-4690-9139-d87f3856b2da.mp4

**Comment by guiyuan-zhang** [comment]
I have the same problem，did you solve it？  help....

**Comment by guiyuan-zhang** [comment]
https://user-images.githubusercontent.com/17865939/208052265-4a0f721b-16f4-49fb-b3d5-d6295b7602cc.mp4

**Comment by guiyuan-zhang** [comment]
> 我也遇到此问题，请问有解决吗？

IQ更新到最新版本后就没有遇到问题了

**Comment by FirstDKS521** [comment]
最新版本6.5.16，也遇到了同样的问题，当遇到键盘无法弹起后，整个APP所有的输入框，都弹不起键盘，不知道怎么处理

**Comment by mushitaosha** [comment]
最新版本6.5.16，iPad上偶尔遇到键盘无法弹起后，整个APP所有的输入框，都弹不起键盘，但是其他app可以，请问怎么解决啊
https://github.com/geekdmm0xff

**Comment by mushitaosha** [comment]
> 升级到 6.5.19 偶尔还是会出现全局键盘不能弹出的问题，老哥怎么解决的？

大佬，请问解决了没呢

**Comment by hackiftekhar** [comment]
Popping keyboard is not related to the library. If this is simulator related issue then the keyboard will not appear if hardware keyboard is attached.

**Comment by FirstDKS521** [comment]
系统问题，暂时没有找到解决方案
