### ISSUE TITLE
Without scrollview or tableview for OS 16 it's not working.

### ISSUE THREAD

**Issue by 1007047** [hackiftekhar/IQKeyboardManager#1931]
iPhone OS version 16 textfiled in bottom a viewcontroller view. Textfiled below the keyboard.

When its scrollview or tableview it's works fine.

**Comment by hackiftekhar** [comment]
I'm unable to reproduce this issue in my demo. If you have some time, then please take some time to prepare a demo for me and then I can look it for you.
