### ISSUE TITLE
'IQKeyboardManager.h' file not found

### ISSUE THREAD

**Issue by mickykro** [hackiftekhar/IQKeyboardManager#1933]
**Describe the bug**
after pod install I am trying to build the project. 
the build fails with 2 errors: 
1 error generated.
<unknown>:0: error: failed to emit precompiled header '/Users/<userName>/Library/Developer/Xcode/DerivedData/customers-bqcsapwamaxzqcaovwildawjgxga/Build/Intermediates.noindex/PrecompiledHeaders/customers-Bridging-Header-swift_3UD1NYAFT0KK3-clang_P8Z3Q0I5KYV9.pch' for bridging header '/Users/<userName>/<projectName>/ios/customers/customers-Bridging-Header.h'
2 errors generated.
'IQKeyboardManager.h' file not found

**Expected behavior**
complete build successfully.

**Screenshots**
![Screen Shot 2022-12-27 at 13 43 50](https://user-images.githubusercontent.com/60981756/209661806-d8f44fa4-902a-4262-abe2-5eb5d57637f9.png)
![Screen Shot 2022-12-27 at 13 44 50](https://user-images.githubusercontent.com/60981756/209661944-b35c3d67-b6ab-4c6d-913b-5aa99d431af9.png)

### Versions
Xcode: Version 14.1 (14B47b)
Mac OS: Monterey 12.5.1 (21G83)
 MacBook Pro (13-inch, M1, 2020)
Library Version: 6.2.1

**Additional context**
running this inside a react-native project.

**Comment by hackiftekhar** [comment]
Are you still getting this problem @mickykro ?
