### ISSUE TITLE
Crash error at startup

### ISSUE THREAD

**Issue by a51095** [hackiftekhar/IQKeyboardManager#1934]
When the program starts, it crashes in the method `application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool`

![error](https://user-images.githubusercontent.com/29021369/210733932-9d05760d-64c9-40b3-bd95-a6e88a19089e.png)

**Comment by monang-iottive** [comment]
I also face this issue

**Comment by hackiftekhar** [comment]
I'm not sure what might be causing this, but it shouldn't happen with a proper setup. Try clean the code and restart the mac should work.
