### ISSUE TITLE
Bug with UITextView inside UIScrollView with edgesForExtendedLayout = .all

### ISSUE THREAD

**Issue by Lakr233** [hackiftekhar/IQKeyboardManager#1935]
View Hierarchy:
```
UIViewController
  > UINavigationController: FromSheet
      > UIViewController
          |> UIView
          -> UIScrollView
             -> UITextView
```

Behavior:
![RPReplay_Final1673013199](https://user-images.githubusercontent.com/25259084/211026161-82007239-ab18-4025-97ab-3cb5908abcd5.gif)

Workaround:
```
UIViewController.edgesForExtendedLayout = []
```

**Comment by Lakr233** [comment]
I havn't have much time to look for a fix inside IQKeyboardManager, and the workaround is acceptable. But I'll try to make a pull request if I got time and fixed it.

**Comment by hackiftekhar** [comment]
I tried same kind of setup but this bug isn't reproducible for me. If you can provide me a demo project then it would be great!

**Comment by Lakr233** [comment]
Here you are. Additionally, a "somehow" frame of the TextView are required to trigger this bug. In the newest release, `UIViewController.edgesForExtendedLayout = []` failed to work.

[bugdemo.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/12812064/bugdemo.zip)

https://github.com/hackiftekhar/IQKeyboardManager/assets/25259084/f1c61cec-ca3d-40cd-a72e-b40558c7f06c

**Comment by hackiftekhar** [comment]
Thanks for the demo, I'll check it.

**Comment by Lakr233** [comment]
Are you sure about this?

Installing IQKeyboardManager (6.5.15) haven't fix the issue.

https://github.com/hackiftekhar/IQKeyboardManager/assets/25259084/466aae52-059f-476c-b02d-d98912fc8810

**Comment by hackiftekhar** [comment]
The current master version have the fixes, this is not released yet.

**Comment by ideviftekhar** [comment]
@Lakr233 6.5.16 has been released. Can you please check with it?

**Comment by Lakr233** [comment]
Upgrading to IQKeyboardManager 6.5.16 (from 6.5.14) seems to have fixed the issue. Thank you for your time! Appreciate it!
