### ISSUE TITLE
切换不同种类的键盘时候，约束冲突

### ISSUE THREAD

**Issue by linnoIt** [hackiftekhar/IQKeyboardManager#1936]
[LayoutConstraints] Unable to simultaneously satisfy constraints.
 	Probably at least one of the constraints in the following list is one you don't want. 
 	Try this: 
 		(1) look at each constraint and try to figure out which you don't expect; 
 		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
 	<NSLayoutConstraint:0x283cd7160 _UIRemoteKeyboardPlaceholderView:0x114852b30.bottom == _UIKBCompatInputView:0x113d6f0f0.top>,
 	<NSLayoutConstraint:0x283cdceb0 TUISystemInputAssistantView:0x114f06170.height == 45>,
 	<NSLayoutConstraint:0x283cd8500 TUISystemInputAssistantView:0x114f06170.bottom == _UIKBCompatInputView:0x113d6f0f0.top>,
 	<NSLayoutConstraint:0x283cdcaf0 TUISystemInputAssistantView:0x114f06170.top == _UIRemoteKeyboardPlaceholderView:0x114852b30.bottom>
)
Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x283cdcaf0 TUISystemInputAssistantView:0x114f06170.top == _UIRemoteKeyboardPlaceholderView:0x114852b30.bottom>
Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.

在同一个界面中，存在多个textfield，每一个textfield的键盘类型不相同，第一个为默认，第二个为密码，第三个为数字。。。
在textfield中切换的时候，会约束冲突。

**Comment by linnoIt** [comment]
冲突主要是来自于inputAccessoryView对于键盘的bottem距离

**Comment by coder321** [comment]
遇到相同问题，请问您是怎么解决的

**Comment by coder321** [comment]
xcode14.3  swift5.2  IQKeyboardManager 6.5.11

**Comment by hackiftekhar** [comment]
This is something we can't fix because this is not due to library.
