### ISSUE TITLE
How can I hide arrows on inputAccessoryView for specific ViewController?

### ISSUE THREAD

**Issue by ekucet** [hackiftekhar/IQKeyboardManager#1941]
**Describe the bug**

**To Reproduce**
1. Go to `IQKeyboardManager.shared.previousNextDisplayMode = .default` on AppDelegate'
2. Click on Set to `IQKeyboardManager.shared.previousNextDisplayMode = .alwaysHide` on Specific ViewController's viewWillAppear method. After set to `IQKeyboardManager.shared.previousNextDisplayMode = .default` on Specific ViewController's viewWillDisappear method'
3. [Click here for error](https://imgur.com/a/gHZt0TU)

### Versions
**Xcode:** 14.2
**Mac OS:** 13.1
**Simulator/Device:** 16.2
**Simulator/Device Name:** iPhone 14
**Library Version:** 6.5.10

**Additional context**
How can I hide arrows on inputAccessoryView for specific ViewController?

**Comment by HussainSatham** [comment]
how did you achieve this?
