### ISSUE TITLE
Not working on Present ViewController

### ISSUE THREAD

**Issue by bhadresh13** [hackiftekhar/IQKeyboardManager#1945]
present view controller but it doesn't goes up but view controller  from where to present  goes up 

https://user-images.githubusercontent.com/19187939/219654556-220722de-bb96-47db-bdf3-470d5bb25ac2.mp4

**Comment by hackiftekhar** [comment]
@bhadresh13 Can you please share a demo project with me?

**Comment by bhadresh13** [comment]
Now its working fine

**Comment by hackiftekhar** [comment]
This reason might happen if library detects a different viewController than expected.

So if this happens then you could override `open func parentIQContainerViewController() -> UIViewController?` function in that viewController and return the correct viewController which should be moved.

**Comment by QIJiyu** [comment]
@bhadresh13 How did you solve it?
