### ISSUE TITLE
iOS16下，UITableView上移后，cell的点击位置没变

### ISSUE THREAD

**Issue by ghost** [hackiftekhar/IQKeyboardManager#1946]
页面中有tableview，点击页面底部的textview，页面位移，但是tableview的cell位置没变，
点击indexpath（0,1）的位置，实际点到的是页面位移前的indexpath（0,0）的cell

### Versions
**Xcode:** 14
**Simulator/Device Name:** iPhone 14pro
**Library Version:** 6.5*

**Comment by fillinse** [comment]
升级到最新就解决了，我现在是升级到6.5.9,就没这个问题了。我是的一个sectionfooter有输入框，开始编辑后输入框上移，然后整个tableView上移，但是点击后，didselectrow触发的却是开始输入前没有向上移动时cell对应的indexPath,即我点击是(0,5),但是返回的却是(0,4),因为之前0-4的这个cell就在这个位置

**Comment by fillinse** [comment]
升级到最新就解决了，我现在是升级到6.5.9,就没这个问题了。我是的一个sectionfooter有输入框，开始编辑后输入框上移，然后整个tableView上移，但是点击后，didselectrow触发的却是开始输入前没有向上移动时cell对应的indexPath,即我点击是(0,5),但是返回的却是(0,4),因为之前0-4的这个cell就在这个位置

**Comment by I-PhuketIsland** [comment]
> 



> 升级到最新就解决了，我现在是升级到6.5.9,就没这个问题了。我是的一个sectionfooter有输入框，开始编辑后输入框上移，然后整个tableView上移，但是点击后，didselectrow触发的却是开始输入前没有向上移动时cell对应的indexPath,即我点击是(0,5),但是返回的却是(0,4),因为之前0-4的这个cell就在这个位置

我的是6.5.11的还是这样。不知道为什么还是这样。

**Comment by fillinse** [comment]
我也不知道我之前的版本，如果最新真的是6.5.11，那我可能没升级。我在podfile里面没有指定版本，用的swift。我这边使用的步骤是，先在podfile里面删掉iqmanager的那行，然后执行podinstall，pod就会自动移除。然后还原podfile，执行podinstall，然后就重新集成了。我翻看了一些最近提出的问题，发现没其他人提出这个问题，那么可能这个跟缓存有关系。反正我这操作下来，就没问题了，我刚才又重新测试了几遍，没再复现这个问题。

> > 
> 
> > 升级到最新就解决了，我现在是升级到6.5.9,就没这个问题了。我是的一个sectionfooter有输入框，开始编辑后输入框上移，然后整个tableView上移，但是点击后，didselectrow触发的却是开始输入前没有向上移动时cell对应的indexPath,即我点击是(0,5),但是返回的却是(0,4),因为之前0-4的这个cell就在这个位置
> 
> 我的是6.5.11的还是这样。不知道为什么还是这样。

**Comment by fillinse** [comment]
我也不知道我之前的版本，如果最新真的是6.5.11，那我可能没升级。我在podfile里面没有指定版本，用的swift。我这边使用的步骤是，先在podfile里面删掉iqmanager的那行，然后执行podinstall，pod就会自动移除。然后还原podfile，执行podinstall，然后就重新集成了。我翻看了一些最近提出的问题，发现没其他人提出这个问题，那么可能这个跟缓存有关系。反正我这操作下来，就没问题了，我刚才又重新测试了几遍，没再复现这个问题。

> > 
> 
> > 升级到最新就解决了，我现在是升级到6.5.9,就没这个问题了。我是的一个sectionfooter有输入框，开始编辑后输入框上移，然后整个tableView上移，但是点击后，didselectrow触发的却是开始输入前没有向上移动时cell对应的indexPath,即我点击是(0,5),但是返回的却是(0,4),因为之前0-4的这个cell就在这个位置
> 
> 我的是6.5.11的还是这样。不知道为什么还是这样。

**Comment by I-PhuketIsland** [comment]
> > 升级到最新就解决了，我现在是升级到6.5.9,就没这个问题了。我是的一个sectionfooter有输入框，开始编辑后输入框上移，然后整个tableView上移，但是点击后，didselectrow触发的却是开始输入前没有向上移动时cell对应的indexPath,即我点击是(0,5),但是返回的却是(0,4),因为之前0-4的这个cell就在这个位置
> 
> 我的是6.5.11的还是这样。不知道为什么还是这样。



> 我也不知道我之前的版本，如果最新真的是6.5.11，那我可能没升级。我在podfile里面没有指定版本，用的swift。我这边使用的步骤是，先在podfile里面删掉iqmanager的那行，然后执行podinstall，pod就会自动移除。然后还原podfile，执行podinstall，然后就重新集成了。我翻看了一些最近提出的问题，发现没其他人提出这个问题，那么可能这个跟缓存有关系。反正我这操作下来，就没问题了，我刚才又重新测试了几遍，没再复现这个问题。
> 
> > > 
> > 
> > 
> > > 升级到最新就解决了，我现在是升级到6.5.9,就没这个问题了。我是的一个sectionfooter有输入框，开始编辑后输入框上移，然后整个tableView上移，但是点击后，didselectrow触发的却是开始输入前没有向上移动时cell对应的indexPath,即我点击是(0,5),但是返回的却是(0,4),因为之前0-4的这个cell就在这个位置
> > 
> > 
> > 我的是6.5.11的还是这样。不知道为什么还是这样。

可能有关系吧，我是直接旧项目pod uodate版本，不知道是否原本就存在这个问题。
我的层级是uiview上分别放了tableview和一个自定义的commonView。
现在只能先监听keybord做处理不响应点击了。

**Comment by hackiftekhar** [comment]
Can you please share a demo project with me?
