### ISSUE TITLE
"Done" button is not showing in my SwiftUI app

### ISSUE THREAD

**Issue by Taimoor20** [hackiftekhar/IQKeyboardManager#1947]
I am using this library in my project and I am not getting "Done" button over my textfield to dismiss the keyboard.

This is my code:

`
@main
struct myMuftiApp: App {
    
    // register app delegate for Firebase setup
    @UIApplicationDelegateAdaptor(AppDelegate.self) var delegate
    
    var body: some Scene {
        WindowGroup {
            
            ContentView()
                .onOpenURL { url in
                    GIDSignIn.sharedInstance.handle(url)
                }
        }
    }
}

class AppDelegate: NSObject, UIApplicationDelegate {
    
    func application(_ application: UIApplication,
                     didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey : Any]? = nil) -> Bool {
        
        IQKeyboardManager.shared.enable = true
        
        FirebaseApp.configure()
        return true
    }
}
`
This is what I am [getting](https://ibb.co/PwxbtGR)

I am using xCode 14.2 and iOS 16.2.

I had also tested on actual device (iPhone 13 pro max) but getting the same result.

**Comment by Shahrukhpatel007** [comment]
I am also getting the same error

**Comment by nithi-k** [comment]
same here

**Comment by hackiftekhar** [comment]
The SwiftUI isn't supported by the library because SwiftUI has it's own mechanism to handle keyboard.

**Comment by Taimoor20** [comment]
@hackiftekhar but before the update of xCode it was working fine.
