### ISSUE TITLE
When the keyboard appears all views go up

### ISSUE THREAD

**Issue by ClaireRimel** [hackiftekhar/IQKeyboardManager#1948]
**Describe the bug**
All views go up when keyboard appears

**Hierarchy of the view**
View
   |
   View
      |
      Scroll View
        |
        Stack View
         |
         TextView
         TextView
         TextView

**Expected behavior**
Scrollview moves when is necessary to keep the TextView visible

**Screenshots**
Screenshot of the Debug View Hierarchy:
![Screenshot 2023-03-08 at 17 15 36](https://user-images.githubusercontent.com/43319552/223776660-1f70e39c-3aa7-4081-b424-512cefcd90e1.png)

https://user-images.githubusercontent.com/43319552/223777252-e0272bd4-8820-4af9-bae7-2a2c47f02f03.MP4

### Versions
**Xcode:** 14.2 
**Mac OS:** 13.2.1 
**Simulator/Device:** iPhone 11 Pro Max iOS 16
**Library Version:** 6.5.11

**Additional context**
With the library Version  6.5.10, it works perfectly 

Screenshot of the Debug View Hierarchy:
![Screenshot 2023-03-08 at 17 10 21](https://user-images.githubusercontent.com/43319552/223777123-ac7fcfbb-c9a9-4334-a84d-df5ba5e7a72d.png)

https://user-images.githubusercontent.com/43319552/223777353-7b4b4472-d299-4065-9808-6b3e26788d7a.MP4

**Comment by hackiftekhar** [comment]
Can you please attach a sample project here?

**Comment by pavelko3lov** [comment]
Seems to be working in `6.4.0`.

**Comment by hackiftekhar** [comment]
I haven't changed anything majorly, but I need a demo project to reproduce the issue if it's still reproducible.
