### ISSUE TITLE
Only Keyboard Toolbar Pops Up

### ISSUE THREAD

**Issue by ZachHandley** [hackiftekhar/IQKeyboardManager#1949]
**Describe the bug**
Title, anywhere I go only the keyboard toolbar pops up. Also my header image moves up as well instead of just the body of my view

**To Reproduce**
1. use IQKeyboardManager
2. Unsure what's causing it, so that's it

**Expected behavior**

I would love for a keyboard to show up

**Screenshots**

<img width="415" alt="Screenshot 2023-03-09 at 1 55 48 PM" src="https://user-images.githubusercontent.com/16495679/224015709-001fcfc8-d3f4-43db-ac33-2f07d6c970e9.png">
<img width="422" alt="Screenshot 2023-03-09 at 1 53 30 PM" src="https://user-images.githubusercontent.com/16495679/224015704-bac14029-c5f1-409f-9a0a-322b549845d2.png">
<img width="446" alt="Screenshot 2023-03-09 at 1 43 39 PM" src="https://user-images.githubusercontent.com/16495679/224015689-e7e4a31c-0f5e-4879-80e0-731a67bb5399.png">

### Versions
**Xcode:** 14.2
**Mac OS:** 13.2.1
**Simulator/Device:** 16.2
**Simulator/Device Name:** iPhone 14 Pro
**Library Version:** Latest

**Additional context**
I read somewhere that it has to do with UITableViewController vs UIViewController, is that what's causing it?

**Comment by Willxones** [comment]
Have you definitely enabled the software keyboard on your simulator?

**Comment by ZachHandley** [comment]
Yes, I actually fixed it there by disabling the hardware keyboard in Simulator but I can't fix it on my login screen with the same trick sadly
