### ISSUE TITLE
如果使用tableview导致位置错位，这样设置即可（不升级情况）

### ISSUE THREAD

**Issue by yl068** [hackiftekhar/IQKeyboardManager#1951]
swift：
self.tableView.shouldIgnoreScrollingAdjustment = true
self.tableView.shouldRestoreScrollViewContentOffset = true
self.tableView.contentInsetAdjustmentBehavior = .never
oc:
self.tableView.shouldIgnoreScrollingAdjustment = YES;
self.tableView.shouldRestoreScrollViewContentOffset = YES;
self.tableView.contentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentNever;

**Comment by hackiftekhar** [comment]
Thanks
