### ISSUE TITLE
keyboardDistanceFromTextField  is disabled

### ISSUE THREAD

**Issue by big-zZ** [hackiftekhar/IQKeyboardManager#1952]
i have set  **_IQKeyboardManager.sharedManager.keyboardDistanceFromTextField = 120.f_**  in AppDelegate
At first it works, but if i make App to be background, and active it again,  **_IQKeyboardManager.sharedManager.keyboardDistanceFromTextField = 120.f_** is disabled
anyone met this?  thanks~

https://user-images.githubusercontent.com/75821787/229770279-671d3d5c-11c7-4b94-b451-cad79e210cc4.MOV

**Comment by hackiftekhar** [comment]
I confirm that it's a known issue. I'll see if I can fix this problem.
