### ISSUE TITLE
Extra space between textfield and keyboard, and in some case it's go up view even it's not necessary

### ISSUE THREAD

**Issue by Mickael-tinytap** [hackiftekhar/IQKeyboardManager#1956]
I have a SwiftUI screen that contains multiple textfields. When I focus on a textfield, the screen moves even though it is not necessary because the keyboard does not hide the textfield.

And when the keyboard hides the textfield, the view is raised too high, leaving extra space between the textfield and the keyboard.

https://user-images.githubusercontent.com/117898922/232332616-31132cce-8a9e-4766-bb34-6428b88bcd5b.mov

**Comment by vishal7738639800** [comment]
hi  @Mickael-tinytap can you elaborate it more clearly
