### ISSUE TITLE
Full text view is not working correctly.

### ISSUE THREAD

**Issue by pashan** [hackiftekhar/IQKeyboardManager#196]
Full text view is not working correctly when you began to type. Cursor go below the keyboard.

**Comment by hackiftekhar** [comment]
Can you please share screenshot or demo for more clear understanding.

**Comment by hackiftekhar** [comment]
Any updates?

**Comment by rajanbalana** [comment]
I have disabled the handling of IQKeyboardManager on a particular ViewController. Sometimes, Toolbar above the Keyboard is visible, sometimes it's not visible. It is randomly happening.

**Comment by hackiftekhar** [comment]
@rajanbalana, I understand what you are trying to explain. But how can I debug the scenario. Do you have any demo code?

**Comment by rajanbalana** [comment]
I don't have the demo code.

**Comment by hackiftekhar** [comment]
So let me know, how can I debug the issue?

**Comment by hackiftekhar** [comment]
Hi @rajanbalana any updates?

**Comment by rajanbalana** [comment]
@hackiftekhar No updates. If you want, You can close the issue.
