### ISSUE TITLE
Unable to add package using SWIFT Package.

### ISSUE THREAD

**Issue by sudhirke** [hackiftekhar/IQKeyboardManager#1960]
**Describe the bug**
Unable to add package using the steps given.

**To Reproduce**
1. Go to 'File > Add Packages'
2. Search for IQKeyboardManager and click on "add" with default settings.
3. See error
<img width="726" alt="image" src="https://github.com/hackiftekhar/IQKeyboardManager/assets/318482/fffb1c2a-52f3-49a2-8d8f-90f8b58afe28">

**Expected behavior**

**Screenshots**
<img width="726" alt="image" src="https://github.com/hackiftekhar/IQKeyboardManager/assets/318482/9ab3b28b-d288-48f1-aa31-975c45b431f0">

**Demo Project**
If applicable, add demo project.

### Versions
**Xcode:** 14.3
**Mac OS:** Ventura 13.3.1
**Simulator/Device:** iPhone 14
**Simulator/Device Name:** iPhone 14
**Library Version:** x.x.x

**Additional context**

**Comment by vincenttsai** [comment]
you can try to choose exact version then type 6.5.11. That works for me.

**Comment by hackiftekhar** [comment]
I tried it but I havn't encountered this problem. The library installed smoothly.
