### ISSUE TITLE
Cant able to disable tool bar in specific controller

### ISSUE THREAD

**Issue by iamvijay7** [hackiftekhar/IQKeyboardManager#1962]
I want to disable the toolbar in one of the controller, I referred the documentation and did exactly but it is not working

Code :
    `    IQKeyboardManager.shared.disabledToolbarClasses.append(SearchViewController.self)`

### Versions
**Xcode:** Version 14.2
**Mac OS:** Version 12.6
**Simulator/Device:** Device
**Simulator/Device Name:** iPhone 7 - 15.7
**Library Version:** 6.5.11

**Comment by hackiftekhar** [comment]
You are doing correct. I'll see why it's not working.

**Comment by hackiftekhar** [comment]
I checked it and it looks to be working for me.
