### ISSUE TITLE
Canceling 'swipe to go back' gesture moves view down

### ISSUE THREAD

**Issue by VisualDeceit** [hackiftekhar/IQKeyboardManager#1963]
**Describe the bug**
Hi!
I have navigation controller within tabBar controller tabs. 
When I perform gesture 'swipe to go back' and then canceled it, presented view moves down. 
If I hided keyboard or `QKeyboardManager.shared.enable = false` before swipe, bag doesn't reproduced. 
 
**To Reproduce**
1. Go to navigation controller
2. Push to another view controller
3. Begin 'swipe to go back' gesture
4. Cancel gesture. 
5. View moves down

**Expected behavior**
View don't moves down after canceling 'swipe to go back' gesture. 

**Screenshots**
![Снимок экрана 2023-06-15 в 08 25 24](https://github.com/hackiftekhar/IQKeyboardManager/assets/38101178/31d3f51f-b5ff-43c3-b35f-9dfd3ff9d886)

### Versions
**Xcode:** 14.3
**Mac OS:** 13..4
**Simulator/Device:** 15.5
**Simulator/Device Name:** iPhone SE (3rd gen)
**Library Version:** 6.5.11

**Additional context**
![Simulator Screen Recording - iPhone SE (3rd generation) - 2023-06-15 at 08 16 31](https://github.com/hackiftekhar/IQKeyboardManager/assets/38101178/f9b41030-f0fd-4c5f-ba21-2770c3ba3246)

**Comment by hackiftekhar** [comment]
It might be due to several reasons.
1) You shouldn't call becomeFirstResponder() on viewDidLoad because at that time the view is not added to the window hierarchy and may cause incorrect calculations for the library.
