### ISSUE TITLE
IQ keyboard serious issues in flutter

### ISSUE THREAD

**Issue by dev-devarsh4** [hackiftekhar/IQKeyboardManager#1965]
IQ keyboard serious issues in flutter

**Comment by dev-devarsh4** [comment]
IQ keyboard doesn't support flutter

If you have keep IQ keyboard pod in your flutter project or use it to app delegate file remove it because it will cause following problems

** If you use IQ keyboard in your flutter app , your physical device keyboard press event will not bind to your text-editing controller , hence data will display to your text filed but will to bind to your text-editing controller and if you pass text-editing controller to api data , posted api data will be blank

88 Just remove IQ Keyboard from every where form your flutter project

**Comment by hackiftekhar** [comment]
This main library doesn't directly support flutter.
