### ISSUE TITLE
UITextView is squeezed out of the screen when it is too high

### ISSUE THREAD

**Issue by lhf19900402** [hackiftekhar/IQKeyboardManager#1966]
**Describe the bug**
iOS16.5.1 UITextView is squeezed out of the screen when it is too high

https://github.com/hackiftekhar/IQKeyboardManager/assets/19975375/bb9a8187-d946-4432-aa60-8ad2b5615af0

**Comment by hackiftekhar** [comment]
It's working as expected for me. Can you please share a demo project with me?

**Comment by Tulleb** [comment]
Same here. Appeared after 6.5.11 update. It was working as expected on 6.5.10.

https://github.com/hackiftekhar/IQKeyboardManager/assets/5658984/8671913b-10e3-4966-a759-9d48e70894f4

**Comment by hackiftekhar** [comment]
@Tulleb It looks like you are doing becomeFirstResponder in viewDidLoad. Can you please try moving it to viewWillAppear or viewDidAppear?

**Comment by Tulleb** [comment]
Sorry @hackiftekhar just noticed your answer.

I am already doing it from `viewWillAppear`.

FYI I had to rollback on the `6.5.10` version to keep it working.
