### ISSUE TITLE
Cursor Position in Centered aligned TextView is wrong

### ISSUE THREAD

**Issue by dimpy-iroid** [hackiftekhar/IQKeyboardManager#1967]
I have a Centered aligned TextView and the problem is Cursor is positioned at center instead of at the beginning of Placeholder text.

TextField with centered alignment working fine, it shows cursor at the beginning but issue is in Centered aligned TextView.

How do I get cursor at the beginning of placeholder text in Centered aligned TextView ? (see attached screenshot - Write Description TextView)
![Simulator Screen Shot - iPhone 12 - 2023-07-03 at 16 37 09](https://github.com/hackiftekhar/IQKeyboardManager/assets/130362429/5d47e0fd-096b-4f79-8798-0d0f475f552b)

**Comment by hackiftekhar** [comment]
Yes, it's definitely a bug. I'll see what I can do to fix this issue.

**Comment by dimpy-iroid** [comment]
Okay !!

**Comment by dimpy-iroid** [comment]
Any Update on this ?

**Comment by hackiftekhar** [comment]
Not yet, I need people's help on this to find out some workarounds.

**Comment by Talha977** [comment]
Hi, @hackiftekhar , I have just requested a PR for the issue please check.

**Comment by hackiftekhar** [comment]
Thank you for fixing it. I'll surely take a look

**Comment by hackiftekhar** [comment]
Thank you so much @Talha977  for making this change. This is so great! I never got a time write such simple fix. You did fabulous job for this library. I really really appreciate your help!

**Comment by Talha977** [comment]
Contributing to this library has been an enlightening experience. 
Thanks a lot for the opportunity to collaborate. I’m excited to contribute more in the future! 
@hackiftekhar
