### ISSUE TITLE
Swift 5.9 10 compiler warnings in XCODE 15 regarding use of pointers to strings

### ISSUE THREAD

**Issue by ptclarke** [hackiftekhar/IQKeyboardManager#1969]
Swift 5.9 issues 70 warnings for IQKeyboardManagerSwift 6.5.10 in extensions which use objc_setAssociatedObject and objc_getAssociated object and pass AssociatedKeys by address;

E.g. the following code 
`        if toolbar == nil {
            toolbar = objc_getAssociatedObject(self, &AssociatedKeys.keyboardToolbar) as? IQToolbar
        }
`
Results in the following warning:
**Forming 'UnsafeRawPointer' to an inout variable of type String exposes the internal representation rather than the string contents.**

I believe this relates to [https://forums.swift.org/t/pitch-constrain-implicit-raw-pointer-conversion-to-bitwise-copyable-values/63314](url) and will be a warning only in Swift 5.9 but may be a fatal error in Swift 6.0.

**Comment by hackiftekhar** [comment]
I'll check with Xcode 17 about what modifications we need to do to fix this issue.

**Comment by ptclarke** [comment]
Thank you Mr Qurashi please let me know if I can assist. It seems that in future Swift will not support adding instance properties to a class in an extension in this way in future so at this point the solution is not obvious to me.

**Comment by hackiftekhar** [comment]
I also think the same @ptclarke. This function served us for long, but I'll see if there is a workaround. I'm still in the process of Installing Xcode 17 on my machine so that I can see what changes I need to make to fix this.

**Comment by WGFcode** [comment]
I have the same problem and look forward to solving it soon

**Comment by hackiftekhar** [comment]
This is fixed with 6.5.13

**Comment by vaghasiya** [comment]
> I'll check with Xcode 17 about what modifications we need to do to fix this issue.

How you get Xcode 17? Still, we have Xcode 15 :)

**Comment by hackiftekhar** [comment]
Thanks for pointing out. I just updated my comments.

**Comment by ptclarke** [comment]
Thank you!
