### ISSUE TITLE
"Done" button practically invisible

### ISSUE THREAD

**Issue by appmagnetics** [hackiftekhar/IQKeyboardManager#197]
![img_2134v2](https://cloud.githubusercontent.com/assets/7034162/7140236/7fd4cc32-e2ca-11e4-9fdf-5afe12efe4d5.png)

Screenshot is done by customer, I cannot provide detailed information with which iOS version it happens. Could it be the known issue? What are the possibilities we have to change the color manually?

**Comment by hackiftekhar** [comment]
There may be white tintColor of your textField or any global which tintColor is forcing done button to change it to white color.

**Comment by appmagnetics** [comment]
I see it included in 3.2.3 but when I switch to this version (from 3.2.0.1), autoscroll on my fields stops working!  Tested several times with clean build. Any regression you had with last commits?

**Comment by hackiftekhar** [comment]
If you mean it by scrolling back to firstTextField from where scrollView starts it's scrolling, then please look into #184. I've added shouldRestoreScrollViewContentOffset and it is defaults to NO.

If you are talking about any other issue which I misunderstood then I would love to know.

**Comment by appmagnetics** [comment]
No, I mean by clicking into text field keboard appears and covers the field, field is not being scrolled (this is actually the main functionality of IQKeyboardManager)

**Comment by hackiftekhar** [comment]
May be hou're pinning some of the textField from top layout guide. Can you please check again?

**Comment by hackiftekhar** [comment]
Can you please check Github repo demo project, is it not working too.

**Comment by appmagnetics** [comment]
I've tried to integrate 3.2.0.1 as source code and manually do the same changes as you fixed in https://github.com/hackiftekhar/IQKeyboardManager/commit/b3642761a93f8e363ac05ad4234d5bf302dceba7#diff-dd3d05f4b44e2fa3c6d4e9f1ba3c546cR1468  - but it does not work, button is not black.  Obviously there is something else contained in the latest release which makes "Done" button black (but disables scrolling). Could you give an advice how to modify 3.2.0.1 for test and make the button black?

**Comment by hackiftekhar** [comment]
Please search shouldToolvarUsesTextFieldTintColor, you'll find [UIColor blackColor] there, I think now you can reach to your goal. Btw can you provide me a demo app, so I can test library for scrolling disable issue.
