### ISSUE TITLE
iOS 17.0 Toolbar wipe out when pressing on next button

### ISSUE THREAD

**Issue by bhautikpatoliya004** [hackiftekhar/IQKeyboardManager#1970]
**Describe the bug**
I have upgraded my project for iOS 17.0 and I'm using IQKeyboardManager for handling the keyboard. But after upgrading the project I got the issue on iOS 17.0 when I press on next button from the toolbar the toolbar is wiped out.

**To Reproduce**
Steps to reproduce the behaviour:
1.  Xcode 15 beta 3
2. Run on iOS 17.0 Simulator.

**Expected behaviour**
The ToolBar should stay on the keyboard.

### Versions
**Xcode:**  15 Beta 3
**Mac OS:** 13.4.1
**Simulator/Device:** iOS 17.0
**Simulator/Device Name:** iPhone 14 Pro
**Library Version:** IQKeyboardManagerSwift 6.5.12

**Additional context**
See the attached video.

https://github.com/hackiftekhar/IQKeyboardManager/assets/114083934/692ed7bc-1fd6-477d-8328-60b26e41397f

**Comment by Saraios** [comment]
I am also facing the same issue.

**Comment by Saraios** [comment]
@hackiftekhar @bhautikpatoliya004 Is there any timeline for this fix?

**Comment by nirav36iOS** [comment]
I am also facing the same issue after upgrading iOS 17.

**Comment by rigor789** [comment]
We're running into the same issue as well, it's especially noticeable in cases where the inputs are otherwise covered by the keyboard, for example:

https://github.com/hackiftekhar/IQKeyboardManager/assets/879060/26374ed7-12ee-4b5a-a8a1-5bdc5f5e6cae

**Comment by sandeepkhade1989** [comment]
I am also facing the jump of the next and done button bar for numeric fields also views going behind the keypad on return key hit

**Comment by Saraios** [comment]
> I am also facing the same issue.

This is fixed iOS 17 beta 4. Thanks.

**Comment by Saraios** [comment]
Others suggest to test in iOS 17 beta 4

iOS & iPadOS 17 Beta 4 Release Notes
Fixed: Buttons in toolbars on iOS have improved metrics but support fewer customizations. (102198062)

**Comment by hackiftekhar** [comment]
I have also done minor changes to forcefully reload the toolbar, so I believe it should fix the issue.
