### ISSUE TITLE
Obtained incorrect view controller

### ISSUE THREAD

**Issue by cjwl0106** [hackiftekhar/IQKeyboardManager#1971]
![image](https://github.com/hackiftekhar/IQKeyboardManager/assets/5037850/1718d3d4-b541-4c72-ad7d-47247c1bade3)
This code obtained the wrong view controller

![image](https://github.com/hackiftekhar/IQKeyboardManager/assets/5037850/88f31fee-edb2-4191-a0da-a8d1ab933e28)
After modification, the correct view controller can be obtained. Will this modification have any bad impact?

**Comment by hackiftekhar** [comment]
I don't know if this will impact something. But I need a demo project to find out why it gets different controllers at different time.

**Comment by hackiftekhar** [comment]
If your view hierarchy is a bit complex and the library is obtaining incorrect view controller then you could also override `open func parentIQContainerViewController() -> UIViewController?` function in that viewController and return the correct one. That will also work as a workaround.
