### ISSUE TITLE
Multiple time calling keyboardWillAppear when IQKeyboardManager disabled

### ISSUE THREAD

**Issue by Nurka11** [hackiftekhar/IQKeyboardManager#1974]
**Describe the bug**
I disabled IQKeyboardManager in some ViewController and subscribed to keyboard notifications
After keyboardWillAppear called two times in the ViewController it caused an effect to my logic 
IQKeyboardManager subscribed to UITextFieldTextDidBeginEditingNotification, UITextViewTextDidBeginEditingNotification notifications and in the handler it will reload textFieldView?.reloadInputViews() (IQKeyboardManager+UITextFieldViewNotification.swift: 125)
it will show keyboard again

**Expected behavior**
When IQKeyboardManager is disabled don't reload inputs

### Versions
**Xcode:** x.x
**Mac OS:** xx.xx.x
**Simulator/Device:** xx.x
**Simulator/Device Name:** iPhone xx
**Library Version:** x.x.x

**Additional context**

**Comment by hackiftekhar** [comment]
It will reload the inputiew's if you have enabled the toolbar. You should be disabling the `enableAutoToolbar` to disable with tweaking with the toolbar.
