### ISSUE TITLE
Double positioning of the viewController

### ISSUE THREAD

**Issue by HayXen** [hackiftekhar/IQKeyboardManager#1977]
When I tap on the textField(or textView) and want to enter text, the keyboard appears, and the view makes double repositions. Below I attached the demo video.
https://github.com/hackiftekhar/IQKeyboardManager/assets/43916183/c463bccb-726b-40b3-a809-5e1cbe1e9ec5

### Versions
**Xcode:** 15.0 beta 6, but this bug is also in the Xcode 14.0+
**Simulator/Device:** on all types
**Simulator/Device Name:** on all types
**Library Version:** 6.5.0

**Comment by hackiftekhar** [comment]
This might be due to the Safe Area. Whenever we change the controller.view.frame to something else, then it's Safe Area get's changed and if we have a textField connected somehow with the Safe Area then this issue might happen.
