### ISSUE TITLE
Cannot override '_' which has been marked unavailable

### ISSUE THREAD

**Issue by erjsatyam** [hackiftekhar/IQKeyboardManager#1978]
Get this error in Xcode 15
class name IQTitleBarButtonItem
Line no - 83
![IQkeyboardManagerError](https://github.com/hackiftekhar/IQKeyboardManager/assets/145646934/8880bfea-802b-4973-8ec8-99f52955b919)

**Comment by hackiftekhar** [comment]
This is now fixed with 6.5.13

c878b6cec31ff1dbf1b8a0eef36d9a52f833fb03

**Comment by erjsatyam** [comment]
thanks @hackiftekhar
