### ISSUE TITLE
can't restore the window to origin look when keyboard was hidden.

### ISSUE THREAD

**Issue by chaoyuan899** [hackiftekhar/IQKeyboardManager#198]
As you see, when the device is horizontal , touch the textField in tableViewCell , the keyboardManager would handle the textField well, but it can't restore it to original look.
![issue](https://cloud.githubusercontent.com/assets/3120858/7156040/12d78f9e-e396-11e4-85b9-0322237ba520.gif)

**Comment by hackiftekhar** [comment]
Can you share the demo project so that I can debug it?

**Comment by chaoyuan899** [comment]
I don’t know why the email send failed, now I try to send it again. hope can help you.

**Comment by hackiftekhar** [comment]
Upload it to dropbox and share link here

**Comment by chaoyuan899** [comment]
demo link:
https://www.dropbox.com/s/3t1ztafgzlqvqtq/IQKeyBoardIssue%23198Demo.zip?dl=0

**Comment by hackiftekhar** [comment]
Thanks, I'll debug it and will let you know my feedback.

**Comment by rjpalermo1** [comment]
+1.  Have same problem with iphone builds.  Have multiple views on screen, pushes them up nicely and everything works fine but when I dismiss the views stay in their up position.
![img_0640](https://cloud.githubusercontent.com/assets/7153565/7196581/bea0f998-e4a2-11e4-83b6-03c38a75993b.PNG)
![img_0641](https://cloud.githubusercontent.com/assets/7153565/7196582/beabe5ec-e4a2-11e4-8d9e-fa76963fa2b6.PNG)
![img_0642](https://cloud.githubusercontent.com/assets/7153565/7196583/beb2a954-e4a2-11e4-9265-a06847cffefc.PNG)

**Comment by hackiftekhar** [comment]
May be something has been broken.

**Comment by rjpalermo1** [comment]
yes - I cannot recall this happening prior to last podUpdate about 2 weeks ago.

**Comment by hackiftekhar** [comment]
On 26 April commit '277729796313' A for loop is removed (TODO: restore scrollView state) mistakenly which was exact fix for the issue.

**Comment by hackiftekhar** [comment]
I'll update library code and cocoapods by tomorrow. Thanks for a major bug report. :)

**Comment by rjpalermo1** [comment]
Your the best!  Thank you.


*Russ Palermo*
Founder | TekTango LLC

office:    866-505-5066 x700
mobile:  317-454-1099
