### ISSUE TITLE
IQPlaceholderable.swift  doest not compile.

### ISSUE THREAD

**Issue by comeonyoh** [hackiftekhar/IQKeyboardManager#1982]
**Describe the bug**
- `IQPlaceholderable.swift` does not compile in a certain environment.
- I encounter the error message `Cannot find type 'UITextField' in scope` because the file does not import the UIKit framework.

### Versions
**Xcode:** Version 15.0 (15A240d)
**Mac OS:**  13.6 (22G120)
**Simulator/Device:** xx.x
**Simulator/Device Name:** iPhone 15(Simulator)
**Library Version:** 6.5.6

**Comment by adeds** [comment]
It happened to me too, solved after changing to exact version 6.5.0.

<img width="411" alt="image" src="https://github.com/hackiftekhar/IQKeyboardManager/assets/23008913/837f3c29-5eca-42bf-a5e4-3a8cd0149887">

<img width="212" alt="image" src="https://github.com/hackiftekhar/IQKeyboardManager/assets/23008913/a6316e4b-bb09-4469-858b-e37de5db941c">

**Comment by hackiftekhar** [comment]
Thanks, I merged the PR and will be releasing a new version soon since it's preventing compilation.

**Comment by hackiftekhar** [comment]
New version was released in the morning. Thanks for the report
