### ISSUE TITLE
[[IQKeyboardManager shared] setEnable:FALSE] Crashes the application on latest version 

### ISSUE THREAD

**Issue by Adnan1990** [hackiftekhar/IQKeyboardManager#1983]
Updated Pods   pod 'IQKeyboardManagerSwift' and shared methods crashed the application

`    [[IQKeyboardManager shared] setEnable:FALSE];
` 

Fatal Error: Called deleted method

Reverted back to    **pod 'IQKeyboardManagerSwift', '6.5.6'** and its working fine

Please fix the issue in latest pods

**Note**: I have tested this on Xcode 14.3.1

**Comment by hackiftekhar** [comment]
I'm unable to reproduce the issue. You also mentioned the code of Objective-C but referring the Swift version.

**Comment by Adnan1990** [comment]
I am using bridging header in my Objective-C legacy project.
