### ISSUE TITLE
Compile issue xcode 15 

### ISSUE THREAD

**Issue by jigs777** [hackiftekhar/IQKeyboardManager#1985]
mkdir -p /Users/drajparmar/Library/Developer/Xcode/DerivedData/test-czxdojspardqkvgjvzwnclajtila/Build/Products/Debug-iphonesimulator/test.app/Frameworks
rsync --delete -av --filter P .*.?????? --links --filter "- CVS/" --filter "- .svn/" --filter "- .git/" --filter "- .hg/" --filter "- Headers" --filter "- PrivateHeaders" --filter "- Modules" "/Users/drajparmar/Library/Developer/Xcode/DerivedData/test-czxdojspardqkvgjvzwnclajtila/Build/Products/Debug-iphonesimulator/IQKeyboardManagerSwift/IQKeyboardManagerSwift.framework" "/Users/drajparmar/Library/Developer/Xcode/DerivedData/test-czxdojspardqkvgjvzwnclajtila/Build/Products/Debug-iphonesimulator/test.app/Frameworks"
building file list ... done
IQKeyboardManagerSwift.framework/IQKeyboardManagerSwift
IQKeyboardManagerSwift.framework/Info.plist
IQKeyboardManagerSwift.framework/_CodeSignature/
rsync: recv_generator: mkdir "/Users/drajparmar/Library/Developer/Xcode/DerivedData/test-czxdojspardqkvgjvzwnclajtila/Build/Products/Debug-iphonesimulator/test.app/Frameworks/IQKeyboardManagerSwift.framework/_CodeSignature" failed: Operation not permitted (1)
*** Skipping everything below this failed directory ***
rsync: mkstemp "/Users/drajparmar/Library/Developer/Xcode/DerivedData/test-czxdojspardqkvgjvzwnclajtila/Build/Products/Debug-iphonesimulator/test.app/Frameworks/IQKeyboardManagerSwift.framework/.IQKeyboardManagerSwift.Mwwu5N" failed: Operation not permitted (1)
rsync: mkstemp "/Users/drajparmar/Library/Developer/Xcode/DerivedData/test-czxdojspardqkvgjvzwnclajtila/Build/Products/Debug-iphonesimulator/test.app/Frameworks/IQKeyboardManagerSwift.framework/.Info.plist.YbsUyB" failed: Operation not permitted (1)

sent 1251906 bytes  received 70 bytes  2503952.00 bytes/sec
total size is 1255388  speedup is 1.00
rsync error: some files could not be transferred (code 23) at /AppleInternal/Library/BuildRoots/98ed8ad3-3356-11ee-9b53-aead88ae2785/Library/Caches/com.apple.xbs/Sources/rsync/rsync/main.c(996) [sender=2.6.9]
Command PhaseScriptExecution failed with a nonzero exit code

**Comment by hackiftekhar** [comment]
This is something related to the cocoapods itself. Please try these solutions or update your cocoapods version by running

`sudo gem update cocoapods`

https://stackoverflow.com/questions/63533819/rsync-error-some-files-could-not-be-transferred-code-23-command-phasescriptex
https://developer.apple.com/forums/thread/727564
