### ISSUE TITLE
Xcode 15: Carthage build task fail with exit code 65

### ISSUE THREAD

**Issue by marcoguevara1** [hackiftekhar/IQKeyboardManager#1987]
Build Failed: Building scheme "IQKeyboardManagerSwift" in IQKeyboardManager.xcodeproj

Run: carthage bootstrap --platform iOS --use-xcframeworks --cache-builds
Result:

*** Building scheme "IQKeyboardManagerSwift" in IQKeyboardManager.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/marcoguevara/ios-frii/Carthage/Checkouts/IQKeyboardManager/IQKeyboardManager.xcodeproj -scheme IQKeyboardManagerSwift -configuration Release -derivedDataPath /Users/marcoguevara/Library/Caches/org.carthage.CarthageKit/DerivedData/15.0_15A240d/IQKeyboardManager/6.5.15 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive VALIDATE_WORKSPACE=NO -archivePath /var/folders/dk/cst3m46s2kx06zcb24kv5br00000gn/T/IQKeyboardManager SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in <PATH>)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/dk/cst3m46s2kx06zcb24kv5br00000gn/T/carthage-xcodebuild.hhpBun.log

### Versions
**Xcode:** 15.0
**Mac OS:** 13.5.2
**Simulator/Device:** Any
**Simulator/Device Name:** Any
**Library Version:** 6.5.15

Note: I already deleted derived data files, cartfile resolved and carthage old builds. Even reinstalling XCode

**Comment by ideviftekhar** [comment]
Can you please tell the reason why project failed to compile?

**Comment by marcoguevara1** [comment]
I got this working using IQKeyboardManager" "v6.5.11"
