### ISSUE TITLE
Don't work well for AutoLayout in UIScrollView and UITableView

### ISSUE THREAD

**Issue by zhw511006** [hackiftekhar/IQKeyboardManager#199]
Hi,

I make a simple demo about scrollview and tableview.

For scroll view, many space at the bottom when scroll.
![ios simulator screen shot apr 16 2015 4 29 00 pm](https://cloud.githubusercontent.com/assets/2869093/7177004/f531beea-e455-11e4-9f80-c9e0a047baa3.png)

For table view, scroll to bottom section5, and then click back button in toolbar, don't show right position.
![ios simulator screen shot apr 16 2015 4 29 28 pm](https://cloud.githubusercontent.com/assets/2869093/7177007/f931afbe-e455-11e4-8127-70c035e5f46a.png)

Maybe, I do something wrong, what your suggestions? Thanks!

**Comment by zhw511006** [comment]
How to upload my demo?  don't support zip file?

**Comment by mythodeia** [comment]
@zhw511006 you can either upload it to your dropbox public folder and share the link or send it directly to his email with link to this issue and some explanation.

**Comment by zhw511006** [comment]
I don't write any code, just make constrains in storyboard. UITableView, I use static cell.

**Comment by mythodeia** [comment]
didn't you say you have a zip file?
if you have a demo project please upload it somewhere people can check it and provide assistance.

**Comment by zhw511006** [comment]
Because have no right to access dropbox in my place, I already have sent my demo to hackiftekhar by email. Thanks!

**Comment by hackiftekhar** [comment]
Can I upload code to dropbox and share link here?

**Comment by zhw511006** [comment]
yes, you can. Do you see my demo? something is wrong?

**Comment by hackiftekhar** [comment]
Busy schedule these days. Didn't get a chance to see the demo. But however I uploaded it to dropbox. Here is the link:-
https://www.dropbox.com/s/guz10g8tmowq4un/SimpleIQKeyboardManagerDemo.zip?dl=0

**Comment by hackiftekhar** [comment]
I tested the demo on Xcode 6.2, and found that it's working fine at my end. I found that previous/next enable disable is working properly as expected. I also found that UIScrollView is also working as expected. I'm not facing any distance issue. May you're modifying 'keyboardDistanceFromTextField' from somewhere in your original code.

 I can see you're using UITableViewController for implementing tableView. I forcefully ignore UITableView position adjustment because it's implemented natively for UITableViewController.(https://developer.apple.com/Library/ios/documentation/StringsTextFonts/Conceptual/TextAndWebiPhoneOS/KeyboardManagement/KeyboardManagement.html).

Let me know if you need any help from me.

**Comment by zhw511006** [comment]
I tested this on iOS8.3 and Xcode6.3. I don't write any code for this, just make constraints on storyboard. how to change "keyboardDistanceFromTextField"? how to ignore UITableView position adjustment?
Can you make a demo like my and upload to dropbox? 
Thanks for your help!

**Comment by hackiftekhar** [comment]
Can you test your project with Xcode 6.2, because I didn't tested it in Xcode 6.3 right now. If you don't find issue with Xcode 6.2 and getting issues with Xcode 6.3 then I need to check it with Xcode 6.3 too (Currently I don't have access to Xcode 6.3 on my Mac).

**Comment by hackiftekhar** [comment]
Now I also tested demo project with Xcode 6.3, and still I don't fine any issues, the demo project works well as expected. Can you test it once more, Can you share a video if possible?

**Comment by zhw511006** [comment]
![a](https://cloud.githubusercontent.com/assets/2869093/7222548/6b873be8-e743-11e4-9038-8134a2f7171b.gif)
![b](https://cloud.githubusercontent.com/assets/2869093/7222549/70ed2f70-e743-11e4-8f26-20e21d62faca.gif)

**Comment by hackiftekhar** [comment]
1) If you look at storyboard you'll find the textField6 is already has 144pt distance from bottom of mainView (UIScrollView). As we all know the Core Logic of IQKeyboardManager is to fix hidden textField issue, and UIScrollView support is added to modify it's contentOffset and contentInset property to fix hidden textField issue it's responsibility of developer to allow user to enable manual scroll or not (Library can't able to decide). Simple if user move scrollView manually then it'll scroll.

2) There is a technical issue with previoius/next and UITableViewx (Dynamic cell loading). For more details you can refer #96 , #106 ,  #81.

**Comment by zhw511006** [comment]
Thank you for help! I understand .

**Comment by hackiftekhar** [comment]
Thanks @zhw511006  for your support. Doing a communication over an issue always help us to keep updated and help to learn new things.
