### ISSUE TITLE
"unrecognized selector sent to instance" Crash when focusing a text field

### ISSUE THREAD

**Issue by Joost-Jens-Luminis** [hackiftekhar/IQKeyboardManager#1991]
**Describe the bug**
While using the IQKeyboardManager we are getting a crash when we focus a text field.
Other then adding the KeyboardManager to our solution we have enabled no additional settings.
I hope you can help.

**To Reproduce**
1. Focus a textfield.

**Expected behavior**
Not to crash

**Stack trace**
ObjCRuntime.ObjCException: 'Objective-C exception thrown.  Name: NSInvalidArgumentException Reason: -[IconTextField viewContainingController]: unrecognized selector sent to instance 0x1836a1e00
Native stack trace:
	0   CoreFoundation                      0x00007ff80048d28d __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007ff800057894 objc_exception_throw + 48
	2   CoreFoundation                      0x00007ff8004a23a3 +[NSObject(NSObject) instanceMethodSignatureForSelector:] + 0
	3   UIKitCore                           0x000000012339dd3c -[UIResponder doesNotRecognizeSelector:] + 266
	4   CoreFoundation                      0x00007ff800491a20 ___forwarding___ + 1459
	5   CoreFoundation                      0x00007ff800493c28 _CF_forwarding_prep_0 + 120
	6   Bronkhorst.FlowControl.iOS          0x000000010c7339c9 -[IQKeyboardManager privateIsEnableAutoToolbar] + 71
	7   Bronkhorst.FlowControl.iOS          0x000000010c739328 -[IQKeyboardManager textFieldViewDidBeginEditing:] + 554
	8   CoreFoundation                      0x00007ff8003b93e0 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 137
	9   CoreFoundation                      0x00007ff8003b9316 ___CFXRegistrationPost_block_invoke + 86
	10  CoreFoundation                      0x00007ff8003b88e5 _CFXRegistrationPost + 536
	11  CoreFoundation                      0x00007ff8003b81db _CFXNotificationPost + 815
	12  Foundation                          0x00007ff800e22af1 -[NSNotificationCenter postNotificationName:object:userInfo:] + 82
	13  UIKitCore                           0x0000000123794205 -[UITextField _notifyDidBeginEditing] + 164
	14  UIKitCore                           0x0000000123793ef4 -[UITextField _becomeFirstResponder] + 262
	15  UIKitCore                           0x000000012339ce6d -[UIResponder becomeFirstResponder] + 804
	16  UIKitCore                           0x0000000123a1b610 -[UIView(Hierarchy) becomeFirstResponder] + 121
	17  UIKitCore                           0x0000000123792a60 -[UITextField becomeFirstResponder] + 182
	18  libxamarin-dotnet-debug.dylib       0x000000010d6dd1cc xamarin_dyn_objc_msgSendSuper + 220
	19  ???                                 0x000000010cf1bea7 0x0 + 4512136871
	20  libmonosgen-2.0.dylib               0x000000010e2c7950 ves_pinvoke_method + 544
	21  libmonosgen-2.0.dylib               0x000000010e2b841c mono_interp_exec_method + 4284
	22  libmonosgen-2.0.dylib               0x000000010e2b5a63 interp_runtime_invoke + 259
	23  libmonosgen-2.0.dylib               0x000000010e39caed mono_runtime_try_invoke + 157
	24  libmonosgen-2.0.dylib               0x000000010e39feae mono_runtime_invoke + 478
	25  Bronkhorst.FlowControl.iOS          0x000000010c7d4e78 _ZL30native_to_managed_trampoline_9P11objc_objectP13objc_selectorPP11_MonoMethodj + 280
	26  Bronkhorst.FlowControl.iOS          0x000000010c81b2f9 -[UIKit_UIControlEventProxy BridgeSelector] + 41
	27  UIKitCore                           0x000000012336c4c6 -[UIApplication sendAction:to:from:forEvent:] + 95
	28  UIKitCore                           0x0000000122a042f3 -[UIControl sendAction:to:forEvent:] + 112
	29  UIKitCore                           0x0000000122a046e8 -[UIControl _sendActionsForEvents:withEvent:] + 334
	30  UIKitCore                           0x0000000122a0074e -[UIButton _sendActionsForEvents:withEvent:] + 148
	31  UIKitCore                           0x0000000122a02f79 -[UIControl touchesEnded:withEvent:] + 485
	32  UIKitCore                           0x00000001233afae8 -[UIWindow _sendTouchesForEvent:] + 1261
	33  UIKitCore                           0x00000001233b1c54 -[UIWindow sendEvent:] + 5284
	34  UIKitCore                           0x0000000123386e6c -[UIApplication sendEvent:] + 772
	35  UIKitCore                           0x0000000123433b99 __dispatchPreprocessedEventFromEventQueue + 8406
	36  UIKitCore                           0x0000000123436455 __processEventQueue + 8414
	37  UIKitCore                           0x000000012342c8d6 __eventFetcherSourceCallback + 163
	38  CoreFoundation                      0x00007ff8003e9d0f __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	39  CoreFoundation                      0x00007ff8003e9c51 __CFRunLoopDoSource0 + 157
	40  CoreFoundation                      0x00007ff8003e944e __CFRunLoopDoSources0 + 215
	41  CoreFoundation                      0x00007ff8003e3b83 __CFRunLoopRun + 919
	42  CoreFoundation                      0x00007ff8003e3409 CFRunLoopRunSpecific + 557
	43  GraphicsServices                    0x00007ff80a650187 GSEventRunModal + 137
	44  UIKitCore                           0x00000001233663a2 -[UIApplication _run] + 972
	45  UIKitCore                           0x000000012336ae10 UIApplicationMain + 123
	46  libxamarin-dotnet-debug.dylib       0x000000010d69747a xamarin_UIApplicationMain + 58
	47  libmonosgen-2.0.dylib               0x000000010e2c8e45 do_icall + 341
	48  libmonosgen-2.0.dylib               0x000000010e2c75d7 do_icall_wrapper + 295
	49  libmonosgen-2.0.dylib               0x000000010e2b82f6 mono_interp_exec_method + 3990
	50  libmonosgen-2.0.dylib               0x000000010e2b5a63 interp_runtime_invoke + 259
	51  libmonosgen-2.0.dylib               0x000000010e39bb68 mono_runtime_invoke_checked + 136
	52  libmonosgen-2.0.dylib               0x000000010e3a333b mono_runtime_exec_main_checked + 107
	53  libmonosgen-2.0.dylib               0x000000010e2081d2 mono_jit_exec + 354
	54  libxamarin-dotnet-debug.dylib       0x000000010d6dbbca xamarin_main + 1898
	55  Bronkhorst.FlowControl.iOS          0x000000010c8688f4 main + 52
	56  dyld                                0x000000010ce8e3ee start_sim + 10
	57  ???                                 0x000000010d43a41f 0x0 + 4517504031

**Demo Project**
If applicable, add demo project.

### Versions
**Xcode:** 15
**Mac OS:** 16.4 and 17

**Additional context**

**Comment by hackiftekhar** [comment]
I'm unable to reproduce this problem in the demo project. Can you please provide a demo?

**Comment by Joost-Jens-Luminis** [comment]
Hi Hackiftekhar,

Thanks for having a quick look. To be honest, I did omit a view details: We are using .Net and are importing a linked .a file from your project. 
This was working so far but stopped working in .Net 8 and xcode 15.
We were hoping you had an idea as to where we could look for this issue, along the lines of "Ah, that is probably this setting".

That said, we have since implemented a very simple version of our own pure in C# code, so this isn't as urgent anymore (even though your library provides better results).

If you want, I can still provide a demo in .Net version probably, else you can close this issue.

**Comment by hackiftekhar** [comment]
@Joost-Jens-Luminis as you are using .Net and importing .a file from this project. I'm now more interested to know that if you are using the Objective-C version of the library or the Swift version of the library? So that I can look specific code.

**Comment by Joost-Jens-Luminis** [comment]
I was using the Objective-C version of the library.

**Comment by Joost-Jens-Luminis** [comment]
As addition, I converted it to a .A library using the following instructions:
 https://learn.microsoft.com/en-us/xamarin/ios/platform/binding-objective-c/walkthrough?tabs=macos#Creating_A_Static_Library

**Comment by hackiftekhar** [comment]
Are you sure you have set the ForceLoad = true?
[assembly: LinkWith ("IQKeyboardManager.a", SmartLink = true, ForceLoad = true)]

**Comment by hackiftekhar** [comment]
I know that there is a problem when having Objective-C category inside static library, the Xcode does not load them by default.

We have to force load it. Some description here:- https://stackoverflow.com/a/3998700

I can see your project is not able to find `viewContainingController` variable which is inside a UIView category in code. So you should be looking relevant option how you can set `-all_load` to the `Other Linker Flags` in your project.

**Comment by Joost-Jens-Luminis** [comment]
That sounds like a clue, I will look into this tomorrow (I don't have my Mac with me at the moment) and get back to you.

**Comment by hackiftekhar** [comment]
Sure! I assume the ForceLoad = true is the same thing which -all_load do in Xcode projects. So try it very first.

**Comment by Joost-Jens-Luminis** [comment]
Unfortunately it didn't solve the issue. We get the same error, the good thing though is that now the exception comes in managed code rather then the unmanaged code, this means we can handle the exception earlier and it doesn't resolve in an unhandled exception. But that doesn't help with solving the error I think.

Due to our internal timelines, we have already put a work around in place (some custom code of our own in C# rather then your library). After internal discussions we have decided to keep this for now rather then to put more resources into finding a solution that works with your library. 

This decision is based on the fact that; .Net 8 isn't released yet (it's in release candidate status at the moment), the current implementation is basically a .Net library which links to a static objective-c library, which contains a copy of your code and a pure C# implementation is better manageable by us (we have no objective-c/ios experts in our team).


That said, if you feel you want to continue the research into this let me know and I will to try and help you out in my spare time, else feel free to close this ticket.

I do want to thank you for your time though. It's much appreciated.
