### ISSUE TITLE
Bug: When use UISheetPresentationController, UI components raised more that i expected

### ISSUE THREAD

**Issue by hyun99999** [hackiftekhar/IQKeyboardManager#1994]
**Describe the bug**
When present `UIViewController` that has `sheetPresentationController` property.
A keyboard raised UI components more that i expected.
I use keyboard `becomeFirstResponder()` in `viewWillAppear()`. **In IQKeyboardManager `6.5.15` normally works, but in `6.5.16` it doesn't works.**

`UISheetPresentationController` supports automatic keyboard avoidance.
Wouldn't it have been a conflict because it played the same role twice?

**To Reproduce**

just present UIViewController that has `sheetPresentationController` property.

**Expected behavior**

<img src="https://github.com/hackiftekhar/IQKeyboardManager/assets/69136340/6f223504-16e0-41c8-b110-3843bfa27f96" width ="200">

**Screenshots**

<img src="https://github.com/hackiftekhar/IQKeyboardManager/assets/69136340/a74b1882-62d0-4926-a786-6b4ee664d505" width ="200">

### Versions
**Xcode:** Version 15.0.1 (15A507)
**Mac OS:** 14.1
**Simulator/Device:** 17.0
**Simulator/Device Name:** iPhone 15
**Library Version:** 6.5.16

**Comment by ideviftekhar** [comment]
It might be. Can you please share the code which needs to be added before presentation to reproduce this issue?

**Comment by hackiftekhar** [comment]
It might be. Can you please share the code which needs to be added before presentation to reproduce this issue?

**Comment by hyun99999** [comment]
Sure why not!
Use next code to present bottom sheet that has medium detent.

```swift
// ViewController has UITextField.
let sheet = ViewController()
        
if let sheet = sheet.sheetPresentationController {
        // set detents
        sheet.detents = [.medium()]
}
 
present(sheet, animated: true)
```

Next, touch UITextField to raise keyboard.
boom, you can meet that it happend.

**Comment by ideviftekhar** [comment]
Thanks, I'll take a look at it.

**Comment by hackiftekhar** [comment]
@hyun99999 This might be because you are writing becomeFirstResponder() in viewWillAppear. When this function is called the view is not added to the window hierarchy.

I would suggest to move becomeFirstResponder(0 to viewDidAppear() because the view is properly configured and appeared in the UI.

**Comment by hyun99999** [comment]
@hackiftekhar And i was checked don't use `becomFirstResponder()`, just touch text field.
The same situation was happend.
Like this.

<img src="https://github.com/hackiftekhar/IQKeyboardManager/assets/69136340/e2ac7996-ded3-48dd-9453-0cac2247beb3" width ="200">

It seems that the problem occurs when I use `UISheetPresentationController`.

**Comment by hackiftekhar** [comment]
I'm unable to reproduce this issue like yours. It looks to be working perfectly fine for me. I need a demo project to debug it.

Once you attach a demo, please reopen the issue.
