### ISSUE TITLE
SwiftUI Keyboard is blocking the bottom of the view in popup 

### ISSUE THREAD

**Issue by hapton** [hackiftekhar/IQKeyboardManager#2003]
**Describe the bug**
SwiftUI Keyboard is blocking the bottom of the view in popup 

pop in https://github.com/exyte/PopupView 2.4.2

**Expected behavior**
SwiftUI Keyboard can not blocking the bottom of the view in popup 

**Screenshots**
![3947573847](https://github.com/hackiftekhar/IQKeyboardManager/assets/1235170/6fbc353c-3e8b-4ef8-b3b4-bb74301336f1)

**Demo Project**

### Versions
**Xcode:15.0.1
**Mac OS:** 14.1.2
**Simulator/Device Name: iPhone 7 （iOS 15.8 ）
**Library Version:** IQKeyboardManager 7.0.0

**Additional context**
debuglog:
IQKeyboardManager|	>>>>> adjustPosition() started >>>>>
IQKeyboardManager|	|	Need to move: 109.0, will be moving up
IQKeyboardManager|	|	Moving Upward
IQKeyboardManager|	|	Set PresentationHostingController<AnyView> origin to: (0.0, -109.0)
IQKeyboardManager|	<<<<< adjustPosition() ended: 0.0012957083526998758 seconds <<<<<
IQKeyboardManager|	>>>>> adjustPosition() started >>>>>
IQKeyboardManager|	|	Need to move: 0.0, will be moving up
IQKeyboardManager|	<<<<< adjustPosition() ended: 5.250005051493645e-05 seconds <<<<<
IQKeyboardManager|	>>>>> adjustPosition() started >>>>>
IQKeyboardManager|	|	Need to move: -44.0, will be moving down
IQKeyboardManager|	|	Moving Downward
IQKeyboardManager|	|	Set PresentationHostingController<AnyView> origin to: (0.0, -65.0)
IQKeyboardManager|	<<<<< adjustPosition() ended: 0.0003160000778734684 seconds <<<<<
IQKeyboardManager|	>>>>> adjustPosition() started >>>>>
IQKeyboardManager|	|	Need to move: -172.0, will be moving down
IQKeyboardManager|	|	Moving Downward
IQKeyboardManager|	|	Set PresentationHostingController<AnyView> origin to: (0.0, 0.0)
IQKeyboardManager|	<<<<< adjustPosition() ended: 0.0003828334156423807 seconds <<<<<

**Comment by hapton** [comment]
[textfieldText.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/13758012/textfieldText.zip)
This is sample，thanks

**Comment by hapton** [comment]
<img width="361" alt="Item-0_和_Item-0_和_Item-0_和_Item-0_和_Item-0" src="https://github.com/hackiftekhar/IQKeyboardManager/assets/1235170/d4a8bacf-dfd5-4dbc-8bd0-7c5da488ba11">
<img width="364" alt="Item-0_和_Item-0_和_Item-0_和_Item-0_和_Item-0" src="https://github.com/hackiftekhar/IQKeyboardManager/assets/1235170/6fcbccd8-50d0-4529-98b2-5bcc6c428a78">

**Comment by hackiftekhar** [comment]
This all happens because the ExytePopupView have their own mechanism to handle keyboard and which is causing conflict with the library. In these kind of cases I would recommend tot disable the IQKeyboardManager before presenting the screen and re-enable it after dismissing the screen.
