### ISSUE TITLE
Multiple commands produce PrivacyInfo.xcprivacy file error in static framework case

### ISSUE THREAD

**Issue by closure11** [hackiftekhar/IQKeyboardManager#2004]
**Describe the bug**

After adding the [privacy manifest](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files) to the app, the following error occurs when compiling:
`Multiple commands produce '/User/Xcode/DerivedData/DemoApp-dqdyrfxccschdiakhuirdvqwblex/Build/Products/Debug-iphoneos/DemoApp.app/PrivacyInfo.xcprivacy'
`

It seems that the library's `PrivacyInfo.xcprivacy` file is put into the app bundle root directory, and then the conflict happened.
 
The privacy file should be added using `resource_bundles` rather than `resources`:

https://github.com/hackiftekhar/IQKeyboardManager/blob/f137f7ffc158c09582574d0abf1ffaf6108ad88e/IQKeyboardManagerSwift.podspec.json#L26

Reference:
https://github.com/CocoaPods/CocoaPods/issues/10325#issuecomment-1718723762

https://developer.apple.com/forums/thread/733537

**To Reproduce**
1. Create a empty app project
2. add a `PrivacyInfo.xcprivacy` file and add it to target membership
3. add IQKeyboardManagerSwift dependency
4. Build app

**Expected behavior**
Build successfully, and after archiving the app, the respective privacy manifest files for the app and library were both added to the app package.

### Versions
**Xcode:** 15.1
**Mac OS:** 14.1.2
**Library Version:** 6.5.16

**Comment by closure11** [comment]
I just found that this error is related to [another library](https://github.com/grab/cocoapods-binary-cache) I use. It prebuilding pod frameworks to cache the CocoaPods library. Without using this prebuilding step, this error disappeared.

**Comment by app4g** [comment]
I've been researching this issue for >half day and not getting anywhere. I can't change to the newest IQKeyboardManagerSwift as I still need to support iOS12. 

How can I back port this change into the existing 6.x branch? (I also do not use caching/prebuilding)

TQ

**Comment by closure11** [comment]
@app4g If you don't mind introducing Obj-C, perhaps you can use `IQKeyboardManager` instead of `IQKeyboardManagerSwift`, which still supports iOS11. This is what I'm doing right now in my own project.

**Comment by app4g** [comment]
@closure11 tx for the suggestion. I'm supporting IOS12 still, but I just tried to use SPM (instead of cocoa pods) and it allowed me to use Version 7.x and I managed to get it working w/o errors and the PrivacyInfo is all  good. Uploaded to Apple and there's no complain yet (automated email stated I need to update the required reasons API)
