### ISSUE TITLE
Hello, issues after changed UIView to ScrollView

### ISSUE THREAD

**Issue by malaimoo** [hackiftekhar/IQKeyboardManager#201]
To avoid the navigationbar hidden issue ,I changed the xib UIView to UIScrollView but the view that on that view just become mess, I dont know how to settle it.

**Comment by hackiftekhar** [comment]
Can you explain it a bit more with some sample screenshot?

**Comment by malaimoo** [comment]
![Uploading 屏幕快照 2015-04-19 上午1.22.06.png . . .]()
![Uploading 屏幕快照 2015-04-19 上午1.22.31.png . . .]()
seems Like autolayout doesn't make use

**Comment by hackiftekhar** [comment]
Didn't you click any textField before all this mess up.

**Comment by malaimoo** [comment]
No, and the autoScroll of your Code is enabled. Did I do something wrong about autolayout?

**Comment by hackiftekhar** [comment]
So this issue doesn't belongs to IQKeyboardManager. It's your Autolayout configuration issue.

**Comment by malaimoo** [comment]
But How can I solve it , I don't have idea....

**Comment by hackiftekhar** [comment]
You need to learn Autolayout first. Here is a good tutorial to understand autolayout http://www.raywenderlich.com/83276/beginning-adaptive-layout-tutorial. But if you're using Autolayout with UIScrollView then you need to extra take care of some more things, Here is a great tutorial I found for UIScrollView with Autolayout http://spin.atomicobject.com/2014/03/05/uiscrollview-autolayout-ios/.
