### ISSUE TITLE
IQKeyboardManager privacy data not found in privacy report

### ISSUE THREAD

**Issue by muzahid59** [hackiftekhar/IQKeyboardManager#2012]
**Describe the bug**
IQKeyboardManager privacy data not found in the application privacy report.

**To Reproduce**
1. Add the dependency.
2. Archive the app.
3. Generate the privacy report and save to disk.
4. Check the report, didn't find the IQKeyboardManager privacy report.

**Expected behavior**
There should be seperate segment for IQKeyboardManager privacy report

**Screenshots**
<img width="1641" alt="demo copy" src="https://github.com/hackiftekhar/IQKeyboardManager/assets/3687168/6d681d39-be04-4dcc-b932-039fa4a05e25">

### Versions
**Xcode: 15**

**Additional context**
[Reference](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests)

**Comment by manicmaniac** [comment]
IQKeyboardManager is included in the list https://developer.apple.com/support/third-party-SDK-requirements/ :eyes:
