### ISSUE TITLE
Can't make a persistend navigation bar

### ISSUE THREAD

**Issue by Gargo** [hackiftekhar/IQKeyboardManager#2015]
**Describe the bug**
Navigation bar always moves top and I don't know how to deal with it.

**To Reproduce**
UIView (or UIScrollView) contains bottom view (bottom bar) and `UITableView` which is scrollable by itself. I don't know what to do with it because if parent is common `UIView` then a navigation bar "runs away". If it is `UIScrollView` then it won't properly work because `UITableView` has its own scroll.

**Expected behavior**
When user opens keyboard view size is decreased and a navigation bar position is not changed.

**Screenshots**
The problem is known, only view's content differs.

**Demo Project**
-

### Versions
**Xcode:** 15.0
**Mac OS:** Sonoma 14.0
**Simulator** 15.5
**Simulator/Device Name:** iPhone X
**Library Version:** 6.5.16 (but it seems the problem doesn't depend on the version)

**Additional context**
-

**Comment by hackiftekhar** [comment]
Are you having something like Chat Screen setup?

**Comment by Gargo** [comment]
@hackiftekhar added a sample project. Don't know if it is the same situation as in my main project but you can start with it.
In this sample navigation bar disappears when table has Y-offset == 0
[test-iqkeyboard.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/14081060/test-iqkeyboard.zip)

**Comment by Gargo** [comment]
I tried to check sources - seems the solution needs to to overwrite base logic of this library. Instead of changing the origin you have to change the view size.

**Comment by hackiftekhar** [comment]
I'll check your demo and will get back to you!

**Comment by hackiftekhar** [comment]
I checked your demo and you are having a chat screen kind of setup. It's a different kind of setup than other normal things, so in this case I mostly recommend to disable IQKeyboardManager in this particular screen by writing something like below thing in AppDelegate and implement your own solution in this screen.

```objc
IQKeyboardManager.shared.disabledDistanceHandlingClasses.append(TestKeyboardViewController.self)
```
