### ISSUE TITLE
Version support issues

### ISSUE THREAD

**Issue by StarsCF** [hackiftekhar/IQKeyboardManager#2016]
**Describe the bug**
The version of the library I'm using is 6.5.12, and I've found that iOS 11, iOS 12 users will not be able to install the apps!

**Expected behavior**
Users who want minimum iOS 11 support install

**Additional context**
[pod](https://github.com/CocoaPods/Specs/blob/master/Specs/8/a/0/IQKeyboardManager/6.5.12/IQKeyboardManager.podspec.json)
platform:iOS 11

I would like to know from which version the library does not support iOS 11, I saw one place on the wiki that says it requires iOS 13 or later, but then there are other places that say it supports iOS 11, which is misleading to me.

**Comment by hackiftekhar** [comment]
6.x.x support from iOS 11 while 7.x.x support from iOS 13
