### ISSUE TITLE
Toolbar disappearing after change language

### ISSUE THREAD

**Issue by LaithAbdo** [hackiftekhar/IQKeyboardManager#2017]
**Describe the bug**
After change application language and trying to holding on any textfield the toolbar will be disappeared but if the user exit from the application and try to open again it will work fine.

**Screenshots**
![Simulator Screenshot - iPhone 15 Pro - 2024-01-31 at 17 58 52](https://github.com/hackiftekhar/IQKeyboardManager/assets/93516455/451c0c7c-86d8-4ea5-ba12-11d751a4614b)

### Versions
**Xcode:** 15.2
**Mac OS:** 14.0
**Simulator/Device:** IPhone 15 pro
**Simulator/Device Name:** IPhone 15 pro
**Library Version:** 6.5.0

**Comment by hackiftekhar** [comment]
Can you please share the demo project with me?
