### ISSUE TITLE
App freezes/hangs when we tap on textField for very first time after installing application

### ISSUE THREAD

**Issue by lallegroo** [hackiftekhar/IQKeyboardManager#2021]
Issue Description:
- The application screen freezes when we tap on textField for the very first time after installing the application.

Steps to Reproduce:
- Install the application on the phone
- Tap on search box textField.

Expected Behavior:
- The keyboard should promptly appear without any delays or freezes.

Versions:

Xcode: 15.2
Mac OS: macOS Ventura
Device: iPhone 12, iOS 17
Library Version: 6.5.17
<img width="1402" alt="Screenshot 2024-02-08 at 8 42 03 PM" src="https://github.com/hackiftekhar/IQKeyboardManager/assets/13975263/b884a62b-4cb9-45f3-8392-7029176f9640">

**Comment by lallegroo** [comment]
@hackiftekhar  could you please assist me with this?"

**Comment by lallegroo** [comment]
Seen same issue here as well https://github.com/hackiftekhar/IQKeyboardManager/issues/1390

**Comment by hackiftekhar** [comment]
@lallegroo  I know there is a very minor lag but if you are facing some noticeable lag than can you please share a demo project?

**Comment by nickp4488** [comment]
Hello @hackiftekhar 
any update on this? I am using latest version but still facing freezing issue.

Thank you,
