### ISSUE TITLE
IQKeyboardManager.shared.toolbarDoneBarButtonItemText = "Готово" don't work

### ISSUE THREAD

**Issue by fury21** [hackiftekhar/IQKeyboardManager#2022]
**Describe the bug**
I use last version 7.0.1

I try to set IQKeyboardManager.shared.toolbarDoneBarButtonItemText = "Готово", but see error "'toolbarDoneBarButtonItemText' has been renamed to 'toolbarConfiguration.doneBarButtonConfiguration.title': To change, please assign a new toolbarConfiguration.doneBarButtonConfiguration"

How to set DoneButton title?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Demo Project**
If applicable, add demo project.

### Versions
**Xcode:** x.x
**Mac OS:** xx.xx.x
**Simulator/Device:** xx.x
**Simulator/Device Name:** iPhone xx
**Library Version:** x.x.x

**Additional context**

**Comment by fury21** [comment]
Somebody know?

**Comment by fury21** [comment]
@hackiftekhar help pls, it's ez question)

**Comment by fury21** [comment]
Somebody, pls :D

**Comment by hackiftekhar** [comment]
> @hackiftekhar help pls, it's ez question)

@fury21 You can simply do like this:-
```swift
                let config = IQBarButtonItemConfiguration(title: "Готово")
                IQKeyboardManager.shared.toolbarConfiguration.doneBarButtonConfiguration = config
```
