### ISSUE TITLE
App not building with Xcode 15.3 when installed via Swift Package Manager

### ISSUE THREAD

**Issue by erwanmace** [hackiftekhar/IQKeyboardManager#2024]
when building with Xcode 15.3, I am not getting the following error:
'placeholderText' is only available in iOS 13.0 or newer

My build target is of course set to iOS 13.0 but I believe we now need to set the build target in the package file as well.

adding the following to the package file may help:

platforms: [
.iOS(.v13)
],

**Comment by vx8** [comment]
Same here

**Comment by caprapaditu** [comment]
same

**Comment by BasilArackal** [comment]
Same here

**Comment by hackiftekhar** [comment]
Thanks for reporting it. I'll take a look at it.

**Comment by stevysmith** [comment]
The fix for this has been merged in

**Comment by hackiftekhar** [comment]
Thanks @stevysmith for the PR
