### ISSUE TITLE
Method center() & setcenter redeclares ObjectiveC method (IQUIView+Hierarchy.swift)

### ISSUE THREAD

**Issue by gokhandilek** [hackiftekhar/IQKeyboardManager#203]
I am trying to run the demo using Xcode Version 6.3 (6D532l) (Swift 1.2)

I had to change the method name from center to incenter to be able to prevent the error and build successfully.

**Comment by hackiftekhar** [comment]
Possibly adding Swift 1.2 support will fix it. #176

**Comment by hackiftekhar** [comment]
For now Fixed compile-time warnings only for Swift 1.2. From now supporting minimum Xcode 6.3 for Swift Version.
