### ISSUE TITLE
Jumping content for the first time

### ISSUE THREAD

**Issue by petrykDima** [hackiftekhar/IQKeyboardManager#2031]
```
IQKeyboardManagerSwift (7.0.1)
```

IOS 17.3 on the real device. On the simulator, it couldn't be reproduced.

I have a view controller inside UINavigationController.
If I activate UITextView it jumps for the first time but works well for the second. 

If I show UIViewController without UINavigationController - everything works well. 

```
func presentCommentsViewController() {
        let st = UIStoryboard(name: "CommentsMain", bundle: nil)
        let vc = st.instantiateViewController(identifier: "CommentsMainViewController") as CommentsMainViewController
        let nvc = UINavigationController(rootViewController: vc)
        nvc.modalPresentationStyle = .fullScreen
        
        self.present(nvc, animated: true)
    }
```

**Comment by petrykDima** [comment]
https://github.com/hackiftekhar/IQKeyboardManager/assets/43542141/27a41964-626c-48d9-a156-7e19f9a095b4

**Comment by hackiftekhar** [comment]
Do you have any demo project for me so that I can check what might be causing it?

**Comment by hackiftekhar** [comment]
This might be because with UITextView, the keyboard becomes visible first and then the textView becomes first responder. When textView becomes first response then we add toolbar to it.
