### ISSUE TITLE
disable IQKeyboardManager inside swiftui

### ISSUE THREAD

**Issue by seniorAyman** [hackiftekhar/IQKeyboardManager#2032]
**Describe the bug**
I want to disable IQKeyboardManager inside swiftui view

**To Reproduce**
1. I write IQKeyboardManager.shared.enable = false in onAppear
2. i get a compiler error "Main actor-isolated class property 'shared' can not be mutated from a non-isolated context"

### Versions
**Xcode:** 15.1
**Mac OS:** 14.2
**Simulator/Device:** 15 pro max
**Simulator/Device Name:** iPhone 14 Pro Max
**Library Version:** 7.0.2

**Additional context**

**Comment by tapan-torinit** [comment]
Hey any update on it? I just install IQKeyboard swift library and getting the same error in UIKit. The same things worked in IQKeyboard obj-c library

**Comment by hackiftekhar** [comment]
Write it inside the task instead of onAppear may fix the issue I believe.

**Comment by alessdiimperio** [comment]
Task { @MainActor in 
// your code here
}
