### ISSUE TITLE
crash [UIView(IQToolbarAddition) addKeyboardToolbarWithTarget:titleText:rightBarButtonConfiguration:previousBarButtonConfiguration:nextBarButtonConfiguration:]

### ISSUE THREAD

**Issue by zhangxueyang** [hackiftekhar/IQKeyboardManager#2034]
**Describe the bug**
App Crash on  [UIView(IQToolbarAddition) addKeyboardToolbarWithTarget:titleText:rightBarButtonConfiguration:previousBarButtonConfiguration:nextBarButtonConfiguration:]

**Expected behavior**
No crash 

**Screenshots**
![Snip20240401_109](https://github.com/hackiftekhar/IQKeyboardManager/assets/14266750/825c4fe6-c865-42e6-8dab-86ac978d175e)
![Snip20240401_107](https://github.com/hackiftekhar/IQKeyboardManager/assets/14266750/afc3a7e4-4aef-430e-ad33-cb16bce43753)

### Versions
**Xcode:** 15.2
**Simulator/Device: 型号：iPad Air (5th generation)
**Library Version:6.5.18

**Comment by hackiftekhar** [comment]
@zhangxueyang I need a demo project in which this issue is reproducible.

**Comment by jiasongs** [comment]
same issue
