### ISSUE TITLE
privacy manifest for major version 6

### ISSUE THREAD

**Issue by slice-varundudeja** [hackiftekhar/IQKeyboardManager#2037]
is it possible to add privacy manifest for major version 6. I dont want to upgrade it to 7 as it causing many compilation errors.
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api

**Comment by zcsyIos** [comment]
If you have any questions about the PrivacyInfo.xcprivacy, please refer to here ：https://www.jianshu.com/p/9a9ec34395e2

**Comment by vpavloviclevi9** [comment]
I would also like to see the privacy manifest for major version 6, since I can't use 7 because of an already reported issue https://github.com/hackiftekhar/IQKeyboardManager/issues/2038

**Comment by geraldkfzteile24** [comment]
Any update on this? I need major version 6 with privacy manifest since I am still supporting iOS 12.

**Comment by ideviftekhar** [comment]
Unfortunately, I don't have any plans to add a privacy manifest for version 6.x.x. Best option for you is to either fork 6.x.x you need and made adjustment as per your need or just download files and directly add to your project.

**Comment by hackiftekhar** [comment]
Unfortunately, I don't have any plans to add a privacy manifest for version 6.x.x. Best option for you is to either fork 6.x.x you need and made adjustment as per your need or just download files and directly add to your project.
