### ISSUE TITLE
IQKeyboardManager version 6.5.18 privacy manifest is different with master

### ISSUE THREAD

**Issue by HaoXianSen** [hackiftekhar/IQKeyboardManager#2039]
Hello， i found the objective-c version IQKeyboardManager last version‘s apple privacy manifest file is different with master branch。
The last version is：
<img width="579" alt="image" src="https://github.com/hackiftekhar/IQKeyboardManager/assets/16781976/28061532-0c96-4820-8f76-5d0891cd59ca">
but， the master is：
<img width="810" alt="image" src="https://github.com/hackiftekhar/IQKeyboardManager/assets/16781976/12c6dfef-c30a-45fb-aa53-26f0add49e33">
and i think the master’s privacy manifest is maybe right。 Will a new version be released that is consistent with master？

**Comment by hackiftekhar** [comment]
New version has been released.
