### ISSUE TITLE
Animation Issue when navigating between UIViewControllers (v3.2.3)

### ISSUE THREAD

**Issue by efremidze** [hackiftekhar/IQKeyboardManager#204]
In v3.2.3, I'm seeing a weird animation when pushing and popping view controllers. I posted a gif showing the odd animation. I'm not seeing this issue in prior releases.

![out](https://cloud.githubusercontent.com/assets/2286277/7286082/0d224f4a-e8fe-11e4-92a9-0e98de13c392.gif)

**Comment by hackiftekhar** [comment]
Can you please check it again after commenting 'setNeedsLayout' and 'layoutIfNeeded' from two places in IQKeyboardManager.m

  May I know autolayout configuration for views or can you bind-up them in a demo?

**Comment by efremidze** [comment]
Works when I comment out `setNeedsLayout ` and `layoutIfNeeded `.

I'm only using a UIViewController with a UITableView. UITableView matches superview's bounds.

**Comment by hackiftekhar** [comment]
So I think, I should add a property like 'setNeedsLayoutOnUpdate' -> BOOL in 'IQKeyboardManager.h'

**Comment by hackiftekhar** [comment]
In your case, you need to set layoutIfNeededOnUpdate to NO. It defaults to YES, because #160 is a more generic issue.

**Comment by efremidze** [comment]
Thanks @hackiftekhar
