### ISSUE TITLE
Keyboard space is not removing insets from the ScrollView correctly

### ISSUE THREAD

**Issue by douglasjunior** [hackiftekhar/IQKeyboardManager#2042]
**Describe the bug**

Hi @hackiftekhar, Douglas here again, the maintainer of React Native Keyboard Manager.

Recently I have updated the `IQKeyboardManager` from 6 to 7.0.2, and we can note several improvements and fixes in the library (including https://github.com/hackiftekhar/IQKeyboardManager/issues/1361 and https://github.com/hackiftekhar/IQKeyboardManager/issues/1422), thank you very much for that!

But also I found a new situation related to ScrollView in React Native, when using in a React Navigation screen.

**To Reproduce**

I dont know if you can run a React Native project, but to reproduce just run the [Sample project branch `7-preview`](https://github.com/douglasjunior/react-native-keyboard-manager/tree/7-preview/Sample) of the React Native Keyboard Manager.

1. Clone the repo
2. `cd Sample`
3. `./install.sh`
4. And go!

**Expected behavior**

We expect that the extra bottom space to be removed when keyboard closes.

**Screenshots**

Version 7.0.2

![keyboard manager](https://github.com/hackiftekhar/IQKeyboardManager/assets/1512341/beffea24-ec74-4f04-ba2d-8967e40324b2)

Version 6.5.16

![keyboard manager version 6](https://github.com/hackiftekhar/IQKeyboardManager/assets/1512341/c130ae1d-398b-47e7-b8da-ffc068a66ea3)

**Demo Project**

- 7.0.2: https://github.com/douglasjunior/react-native-keyboard-manager/tree/7-preview/Sample
- 6.5.16: https://github.com/douglasjunior/react-native-keyboard-manager/tree/master/Sample

### Versions
**Xcode:** 15.2
**Mac OS:** 13.5.1
**Simulator/Device:** Simulator
**Simulator/Device Name:**  iPhone 15 Pro Max - iOS 17.2
**Library Version:** 7.0.2

**Additional context**

Looking to the log, seems that the insets are set wrong when the keyboard closes, I think that the bottom should be set to `0.0` instead of `420.0`:

`IQKeyboardManager|	|	old ContentInset: UIEdgeInsets(top: 0.0, left: 0.0, bottom: 376.0, right: 0.0) new ContentInset: UIEdgeInsets(top: 0.0, left: 0.0, bottom: 420.0, right: 0.0)`

Debug log:

```
-[RTIInputSystemClient remoteTextInputSessionWithID:performInputOperation:]  perform input operation requires a valid sessionID
IQKeyboardManager|	>>>>> restorePosition() started >>>>>
IQKeyboardManager|	|	Restoring contentInset to: UIEdgeInsets(top: 0.0, left: 0.0, bottom: 0.0, right: 0.0)
IQKeyboardManager|	<<<<< restorePosition() ended: 0.002194624999901862 seconds <<<<<
-[RTIInputSystemClient remoteTextInputSessionWithID:performInputOperation:]  perform input operation requires a valid sessionID
IQKeyboardManager|	>>>>> addToolbarIfRequired() started >>>>>
IQKeyboardManager|	|	Found 20 responder sibling(s)
IQKeyboardManager|	<<<<< addToolbarIfRequired() ended: 0.01065550000021176 seconds <<<<<
IQKeyboardManager|	>>>>> adjustPosition() started >>>>>
IQKeyboardManager|	|	Need to move: -327.0, will be moving down
IQKeyboardManager|	|	Saving ScrollView New contentInset: UIEdgeInsets(top: 0.0, left: 0.0, bottom: 0.0, right: 0.0)
and contentOffset: (0.0, 0.0)
IQKeyboardManager|	|	old ContentInset: UIEdgeInsets(top: 0.0, left: 0.0, bottom: 0.0, right: 0.0) new ContentInset: UIEdgeInsets(top: 0.0, left: 0.0, bottom: 376.0, right: 0.0)
IQKeyboardManager|	<<<<< adjustPosition() ended: 0.0005828333341924008 seconds <<<<<
IQKeyboardManager|	>>>>> addToolbarIfRequired() started >>>>>
IQKeyboardManager|	|	Found 20 responder sibling(s)
IQKeyboardManager|	<<<<< addToolbarIfRequired() ended: 0.00037524999970628414 seconds <<<<<
IQKeyboardManager|	>>>>> adjustPosition() started >>>>>
IQKeyboardManager|	|	Need to move: -283.0, will be moving down
IQKeyboardManager|	|	old ContentInset: UIEdgeInsets(top: 0.0, left: 0.0, bottom: 376.0, right: 0.0) new ContentInset: UIEdgeInsets(top: 0.0, left: 0.0, bottom: 420.0, right: 0.0)
IQKeyboardManager|	<<<<< adjustPosition() ended: 0.0003427083320275415 seconds <<<<<

-[RTIInputSystemClient remoteTextInputSessionWithID:performInputOperation:]  perform input operation requires a valid sessionID
```

**Comment by douglasjunior** [comment]
Just to add more information about my debug, If I force the `ignoreContentInsetAdjustment` prop to `true`, then the ScrollView bottom space disappears after keyboard closes and the user scroll the screen.

![image](https://github.com/hackiftekhar/IQKeyboardManager/assets/1512341/357fb6bb-2158-4f9f-932f-d9c174eff088)

**Comment by hackiftekhar** [comment]
Thanks @douglasjunior For all the detail information. I'll see what might be causing the issue and will check what messed up.

**Comment by hackiftekhar** [comment]
@douglasjunior Unfortunately I'm unable to reproduce the issue on my demo and I'm unable to run the react native demo since I don't have much knowledge about react native, so I need your help on this.

**Comment by douglasjunior** [comment]
Easy-peasy, React Native is just a native project with the need of Node JS.

Considering that you already have Xcode and CocoaPods in your setup, you just need to install Node JS version 18 or above, then:

1. Install Node and Yarn

    Install Node JS 18 or 20 using your preferred method, can be `brew`, `nvm` or by downloading in the official website: https://nodejs.org/en/download/package-manager
    
    Example: 
    
    ```sh
    brew install node@20
    ```
    
    Then, using the `npm` installed with Node, install the `Yarn` package:
    
    ```sh
    npm i -g yarn
    ```

1. Clone the project: https://github.com/douglasjunior/react-native-keyboard-manager

1. Change to branch `7-preview`

1. Go to the `Sample` folder and run the `./install.sh` script.

    ```sh
    cd Sample
    ./install.sh
    ```

    > This script just install the JavaScript and Cocoapods dependencies, wait for the conclusion.

1. Start the JavaScript compiler (called `Metro`)

    ```sh
    # still in the Sample directory
    yarn start
    ```

1. On another terminal or using Finder, open the `xcworkspace` from `Sample/ios` with Xcode and run it like a native iOS project.

    ```sh
    # still in the Sample directory
    open ios/ReactNativeKeyboardManagerSample.xcworkspace
    ```

**Comment by hackiftekhar** [comment]
Hi @douglasjunior, I found out the reason and I made required adjustments, however this change needs a bit of testing in different scenarios so if you could test it with multiple different scenarios then it would be great for me.

**Comment by douglasjunior** [comment]
Oh man, thank you so much for your work. I will definitely run the tests.

If you have suggestions for possible scenarios you have in mind, I would also be happy to test them.

**Comment by douglasjunior** [comment]
I've tried to install the version 7.1.0 directly from git, but I can't compile it, I think that is because the new version is using Swift 6 that is available only in Xcode Beta.

In my Podfile:

```ruby
  pod 'IQKeyboardManagerSwift', :git => 'https://github.com/hackiftekhar/IQKeyboardManager.git', :commit => '06d880e31e1b1ffd9c2eb6f8a68a74e8764de15e'
```

The error:

![image](https://github.com/user-attachments/assets/2bd7c960-4465-436a-8f83-fa34ebb8bcfa)

**Comment by hackiftekhar** [comment]
I think so yes. Let me made a minor change in it.

**Comment by hackiftekhar** [comment]
Can you please try 7.1.1 now? I have made a minor change in podspec (Removed 6.0 from swift_versions), I think it should work for you.

**Comment by douglasjunior** [comment]
Seems to be working great now!

![keyboard](https://github.com/user-attachments/assets/f9a0e57a-0943-45b5-88d7-ce26a2e6b8b5)

I've tested with multiple screens using `stack` and `native-stack` navigators too.

You are the best @hackiftekhar!

**Comment by itsramiel** [comment]
Thank you @hackiftekhar for solving issues coming from the react native community. Appreciate your efforts man 🙏

**Comment by hackiftekhar** [comment]
It's my pleasure @itsramiel. I wasn't getting much time in my day to work on the library but finally I did these changes.
