### ISSUE TITLE
Unable to change done button text

### ISSUE THREAD

**Issue by asadkazmi-mset** [hackiftekhar/IQKeyboardManager#2046]
**Describe the bug**
I was using an older version of "IQKeyboardManagerSwift" by Cocoa Pods, now I installed v7.0.3 of IQKeyboardManagerSwift using swift package manager, but I'm unable to change the name of the done button
In the older version, this line was working fine:
`IQKeyboardManager.shared.toolbarDoneBarButtonItemText = "Done"`

After migrating to the newest version Xcode suggested me to change that line to this:
`IQKeyboardManager.shared.toolbarConfiguration.doneBarButtonConfiguration?.title = "Done"`

and start giving me an error that, "Cannot assign to property: 'title' is a 'let' constant"

**To Reproduce**
1- Import IQKeyboardManagerSwift
2- set done button text

**Expected behavior**
Button text should be change

**Screenshots**
n/a

**Demo Project**
n/a

### Versions
**Xcode:** 15.2
**Mac OS:** 14.3 
**Simulator/Device:** Simulator
**Simulator/Device Name:** 15Pro
**Library Version:** 7.0.3

**Additional context**

**Comment by hackiftekhar** [comment]
You have to set doneBarButtonConfiguration = //new configuration variable

**Comment by shaktimilestone** [comment]
I did this 

let conf = IQBarButtonItemConfiguration(title:"Done");
IQKeyboardManager.shared.toolbarConfiguration.doneBarButtonConfiguration = conf;

its giving an error Cannot find 'IQBarButtonItemConfiguration' in scope

**Comment by chenminghong** [comment]
its giving an error Cannot find 'IQBarButtonItemConfiguration' in scope too,  please help me !

**Comment by wilsonmfra** [comment]
@shaktimilestone, @chenminghong please check
https://github.com/hackiftekhar/IQKeyboardManager/blob/17ff1ebd3f95b9be581d8ffb829e70bb0fdf5bd8/Demo/Swift_Demo/ViewController/SettingsViewController.swift#L128
from the demo

verify you import what is need it.

import IQKeyboardManagerSwift
import IQKeyboardToolbar
import IQKeyboardToolbarManager
