### ISSUE TITLE
parentContainerViewController case Page jam

### ISSUE THREAD

**Issue by AndyZZhz** [hackiftekhar/IQKeyboardManager#2047]
I use textfiled to search.

I use this framework by below method
enabledDistanceHandlingClasses
enabledTouchResignedClasses

Just click on the textfield in the project, and a stuck situation will appear. Log as follows

* thread 1, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
    frame 0: 0x0000000185b1ac00 libobjc.A.dylib`objc_retain + 16
  * frame 1: 0x000000011d3e1a3c IQKeyboardManagerSwift`UIView.parentContainerViewController(self=0x00000001280f8200) at IQUIView+Hierarchy.swift:97:13
    frame 2: 0x000000011d3e2378 IQKeyboardManagerSwift`@objc UIView.parentContainerViewController() at <compiler-generated>:0
    frame 3: 0x000000011d3c6ee8 IQKeyboardManagerSwift`IQKeyboardManager.textFieldViewDidBeginEditing(notification=Foundation.Notification @ 0x000000016efcdb10, self=0x000000013c9b3870) at IQKeyboardManager+UITextFieldViewNotification.swift:146:53
    frame 4: 0x000000011d3c77a0 IQKeyboardManagerSwift`@objc IQKeyboardManager.textFieldViewDidBeginEditing(_:) at <compiler-generated>:0
    frame 5: 0x000000018d7674c8 CoreFoundation`__CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 148
    frame 6: 0x000000018d766e90 CoreFoundation`___CFXRegistrationPost_block_invoke + 88
    frame 7: 0x000000018d766dd8 CoreFoundation`_CFXRegistrationPost + 440
    frame 8: 0x000000018d766328 CoreFoundation`_CFXNotificationPost + 724
    frame 9: 0x000000018c702864 Foundation`-[NSNotificationCenter postNotificationName:object:userInfo:] + 92
    frame 10: 0x0000000190a2a998 UIKitCore`-[UITextField _notifyDidBeginEditing] + 140
    frame 11: 0x0000000190a2a6f8 UIKitCore`-[UITextField _becomeFirstResponder] + 196
    frame 12: 0x000000018fad829c UIKitCore`-[UIResponder becomeFirstResponder] + 540
    frame 13: 0x000000018fad8070 UIKitCore`-[UIView(Hierarchy) becomeFirstResponder] + 120
    frame 14: 0x0000000190a297d0 UIKitCore`-[UITextField becomeFirstResponder] + 152
    frame 15: 0x000000018f9f1b00 UIKitCore`-[UIView(Hierarchy) _promoteSelfOrDescendantToFirstResponderIfNecessary] + 104
    frame 16: 0x000000018fa830cc UIKitCore`+[UIView _performBlockDelayingTriggeringResponderEvents:forScene:] + 276
    frame 17: 0x00000001900fecd8 UIKitCore`-[_UINavigationParallaxTransition animateTransition:] + 952
    frame 18: 0x000000018fbecbb8 UIKitCore`___UIViewControllerTransitioningRunCustomTransition_block_invoke_3 + 52
    frame 19: 0x000000018fbecb2c UIKitCore`+[UIKeyboardSceneDelegate _pinInputViewsForKeyboardSceneDelegate:onBehalfOfResponder:duringBlock:] + 96
    frame 20: 0x000000018fbeca90 UIKitCore`___UIViewControllerTransitioningRunCustomTransition_block_invoke_2 + 196
    frame 21: 0x000000018fb3467c UIKitCore`+[UIView(Animation) _setAlongsideAnimations:toRunByEndOfBlock:] + 180
    frame 22: 0x000000018fb33f0c UIKitCore`_UIViewControllerTransitioningRunCustomTransition + 484
    frame 23: 0x000000019004f074 UIKitCore`-[UINavigationController _startCustomTransition:] + 3276
    frame 24: 0x000000018fa73f78 UIKitCore`-[UINavigationController _startDeferredTransitionIfNeeded:] + 496
    frame 25: 0x000000018fa73670 UIKitCore`-[UINavigationController __viewWillLayoutSubviews] + 96
    frame 26: 0x000000018fa735d4 UIKitCore`-[UILayoutContainerView layoutSubviews] + 172
    frame 27: 0x000000018f98e694 UIKitCore`-[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1528
    frame 28: 0x000000018eda41c0 QuartzCore`CA::Layer::layout_if_needed(CA::Transaction*) + 500
    frame 29: 0x000000018eda3d48 QuartzCore`CA::Layer::layout_and_display_if_needed(CA::Transaction*) + 144
    frame 30: 0x000000018edaa278 QuartzCore`CA::Context::commit_transaction(CA::Transaction*, double, double*) + 464
    frame 31: 0x000000018eda3574 QuartzCore`CA::Transaction::commit() + 648
    frame 32: 0x000000018eda321c QuartzCore`CA::Transaction::flush_as_runloop_observer(bool) + 88
    frame 33: 0x000000018fa06974 UIKitCore`_UIApplicationFlushCATransaction + 52
    frame 34: 0x000000018fa0648c UIKitCore`_UIUpdateSequenceRun + 84
    frame 35: 0x000000018fa05b7c UIKitCore`schedulerStepScheduledMainSection + 144
    frame 36: 0x000000018fa05c38 UIKitCore`runloopSourceCallback + 92
    frame 37: 0x000000018d76f31c CoreFoundation`__CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28
    frame 38: 0x000000018d76e598 CoreFoundation`__CFRunLoopDoSource0 + 176
    frame 39: 0x000000018d76cd4c CoreFoundation`__CFRunLoopDoSources0 + 244
    frame 40: 0x000000018d76ba88 CoreFoundation`__CFRunLoopRun + 828
    frame 41: 0x000000018d76b668 CoreFoundation`CFRunLoopRunSpecific + 608
    frame 42: 0x00000001d0b365ec GraphicsServices`GSEventRunModal + 164
    frame 43: 0x000000018fb882b4 UIKitCore`-[UIApplication _run] + 888
    frame 44: 0x000000018fb878f0 UIKitCore`UIApplicationMain + 340
    frame 45: 0x0000000102990db4 QFSAAS`main at AppDelegate.swift:37:7 [opt]
    frame 46: 0x00000001b01bedcc dyld`start + 2240

### Versions
**Xcode:15.3
**Mac OS: 14.4 (23E214)
**Simulator/Device Name: Model: iPhone 12 Pro
**Library Version:  pod 'IQKeyboardManagerSwift', '6.5.16'

**Comment by hackiftekhar** [comment]
Could you please attach a demo project?
