### ISSUE TITLE
Layout breaks after updating to 6.5.15+

### ISSUE THREAD

**Issue by anish190** [hackiftekhar/IQKeyboardManager#2048]
**Describe the bug**
     I developed a reusable bottom sheet to encapsulate dynamic content within it. However, since updating to version 6.5.16 and higher, I'm experiencing layout issues. The previous version, 6.5.15, worked fine.

| V6.5.15  | V6.5.15+  | 
|---|---|
| <video src="https://github.com/hackiftekhar/IQKeyboardManager/assets/7508601/022c1454-dd24-4678-9ffa-5f4add2203ea"> | <video src="https://github.com/hackiftekhar/IQKeyboardManager/assets/7508601/c8e027fa-5562-45d6-8d98-b8d42545a3d9"> | 

### Versions
**Xcode:** 15.0
**Mac OS:** 14.3
**Simulator/Device:** Simulator & Device
**Simulator/Device Name:** iPhone 15 Pro
**Library Version:** 7.0.3

** Sample Project **
[Sample.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/15401479/Sample.zip)

**Comment by ARGAMX** [comment]
Starting 6.5.11 
I having issue with UITextView if it located at the top of the screen near status bar.
On first responder it goes up out of the screen.

**Comment by nguyendai0208** [comment]
the same issue with me

**Comment by ayushraj05** [comment]
Facing the same issue...

**Comment by YannickGagnon** [comment]
Same

**Comment by Blackjacx** [comment]
Similar issues on our side

**Comment by jensonjohn001** [comment]
+1

**Comment by hackiftekhar** [comment]
Thanks for the demo project @anish190, I'll check it soon.

**Comment by hackiftekhar** [comment]
@anish190, you are presenting your screen under BottomDrawer and I checked that BottomDrawer having it's own mechanism to handle keyboard. This is why you are having this issue.

@SherifShokry123 @ARGAMX @nguyendai0208 @ayushraj05 @YannickGagnon @Blackjacx @jandrad If you are having some other setup then please share the demo project with me.
