### ISSUE TITLE
next button on toolbar, textField focus sequence

### ISSUE THREAD

**Issue by xeravim** [hackiftekhar/IQKeyboardManager#205]
Hi, I just want to know how you define the first textfield  and the last textfield on view, because I had some problem with it. The next button indeed working but in my case, the first textfield shows next button on keyboard but not on toolbar button, and the last button shows done button on keyboard  but not on toolbar button ( i have 2 textfields). 

I have implement this on my viewdidload:

   returnKeyHandler = [[IQKeyboardReturnKeyHandler alloc] initWithViewController:self];
    [returnKeyHandler setLastTextFieldReturnKeyType:UIReturnKeyDone];
    returnKeyHandler.toolbarManageBehaviour = IQAutoToolbarByTag;

but tagging the textfield doesn't change the toolbar buttons behaviour. I thought by changing behaviour to IQAutoToolbarByTag will solve my problem above, focusing on textfield in sequence with the tag.

![screen shot 2015-04-23 at 10 53 11 am](https://cloud.githubusercontent.com/assets/5388871/7291994/ab7a4f08-e9c1-11e4-9abb-859981a21c5c.png)

**Comment by hackiftekhar** [comment]
IQKeyboardReturnKeyHandler is for dealing with keyboard return key only. You need to look into 'IQKeyboardManager.h' for changing toolbarManagerBehaviour. Let me know if you need more help.

**Comment by xeravim** [comment]
Hi, thanks for the fast reply!
I have updated the question with a picture, as you can see button next should have been disabled and prev button enabled because its the second/last textfield on the view. How I can solve this?

**Comment by hackiftekhar** [comment]
Next/Previous button is not related to IQKeyboardReturnKeyHandler, it's manage by IQKeyboardManager, so as I previously said you need to change toolbarManageBehaviour to IQAutoToolbarByTag of IQKeyboardManager class object. Let me know if you need more help.

**Comment by xeravim** [comment]
OMG, I got it now.. thank you so much!
