### ISSUE TITLE
@Note: If you want to disable `+ (void)load` method, you can add build setting in configurations. Like that:        `{ 'GCC_PREPROCESSOR_DEFINITIONS' => '$(inherited) IQ_KEYBOARD_MANAGER_LOAD_METHOD_DISABLE=1' }`  */ does not have effect 

### ISSUE THREAD

**Issue by xulidegitHub** [hackiftekhar/IQKeyboardManager#2051]
@Note: If you want to disable `+ (void)load` method, you can add build setting in configurations. Like that:
       `{ 'GCC_PREPROCESSOR_DEFINITIONS' => '$(inherited) IQ_KEYBOARD_MANAGER_LOAD_METHOD_DISABLE=1' }`
 */
does not have effect

**Comment by hackiftekhar** [comment]
It needs to be added on pods project if added via CocoaPods. So due to this, I removed this feature.
