### ISSUE TITLE
iOS18 beta crash

### ISSUE THREAD

**Issue by BlackStarLang** [hackiftekhar/IQKeyboardManager#2052]
iOS18 beta crash when init 
非必现，当APP启动时发生了闪退，iPhone14、15 机型都出现过

<img width="1052" alt="image" src="https://github.com/hackiftekhar/IQKeyboardManager/assets/20508121/6633642c-596a-4239-bbda-3b68b43736bb">

**Comment by DoneLiu** [comment]
我也发现了，偶先问题，目测不会修复了，也不确定是不是beta系统的问题、、、

**Comment by hackiftekhar** [comment]
I'm still not sure as I'm unable to reproduce this issue with Xcode 16 beta.
