### ISSUE TITLE
Infinite Loop

### ISSUE THREAD

**Issue by dtursunov** [hackiftekhar/IQKeyboardManager#2056]
**Describe the bug**

If you use custom navigation controller your app freeze because Library has infinite loop

 
https://github.com/dtursunov/IQKeyboarManagerTest

**To Reproduce**
1. Run demo app
2. Click on textfield
3. 

**Demo Project**
(https://github.com/dtursunov/IQKeyboarManagerTest)

**Comment by dtursunov** [comment]
@hackiftekhar

**Comment by dtursunov** [comment]
Can Anyone help me?)

**Comment by hackiftekhar** [comment]
This is your code causing to make it infinite loop.

![Screenshot 2024-07-16 at 11 33 33 AM](https://github.com/user-attachments/assets/13e3fd49-1cd7-47fe-a18d-edf77815b379)

You shouldn't be doing this
```swift
    // TODO: (e.mironenko) Не работает вместе с IQKeyboardManager. Надо разобрать почему
    open override var navigationController: UINavigationController? {
        self
    }
```

```swift
In MainViewController, write something similar to below code.

    public override func iq_parentContainerViewController() -> UIViewController? {
        return self.navigationController
    }
```

**Comment by dtursunov** [comment]
I can't remove  this code below


open override var navigationController: UINavigationController? {
        self
    }

**Comment by hackiftekhar** [comment]
Then still it's your problem because your code is creating infinite loop, not this library.
