### ISSUE TITLE
Too much contenInset when using nested uistackviews inside scrollView

### ISSUE THREAD

**Issue by tolgaytoklar** [hackiftekhar/IQKeyboardManager#2058]
**Describe the bug**
I need to put two stackviews inside the uiscrollview otherwise my views are filling up the screen. When I put horizontal stackview as alignment set to 'Top' I got what I want. But this causes to wrong contentInsets caused by IQKeyboardManager. After the keyboard opens up you can scroll the scrollview even when there is only one view.

**To Reproduce**
Open the demo app then click on the uitextfield and scroll the screen while the keyboard is visible.

**Expected behavior**
ScrollView should not scroll when there is no need to scroll.

**Demo Project**
[ScrollView Keyboard.zip](https://github.com/user-attachments/files/16350273/ScrollView.Keyboard.zip)

### Versions
**Xcode:** 15.4
**Mac OS:** Sonoma
**Simulator/Device:** Simulator
**Simulator/Device Name:** iPhone SE (17.5)
**Library Version:** 6.5.12 (The latest version still has this issue)

**Comment by tolgaytoklar** [comment]
Thank you so much it fixed. If it is possible to give me some more details because all of the tutorials on the internet suggest to use equal height between scrollview's frame and your content view. I didn't understand why your solution worked.

**Comment by hackiftekhar** [comment]
- If you would like to scroll vertically then add width equal constraint, but don't add height equal constraint. Let it calculate content height by inner constraints.
- If you would like to scroll horizontally then add constraint to make both height equal, but don't add width equal constraint.  Let it calculate content width by inner constraints.
