### ISSUE TITLE
It moves up subview rather than superview

### ISSUE THREAD

**Issue by lusnaow** [hackiftekhar/IQKeyboardManager#206]
I have a UIView in my UIViewController's view, and some buttons in that UIView. The UIView is at the bottom of some UITextField. When I click one UITextField,It moves up subview rather than superview aka  the UIViewController's view. How can I let it move up the UIViewController's view rather than any subView?

**Comment by hackiftekhar** [comment]
May you're pinning your textField from TopLayoutGuide, or pinning some related view from topLayoutGuide. Can you please check storyboard and let me know if this was the issue?

**Comment by lusnaow** [comment]
After I disabled the AutoLayout, it works well now.Thanks a lot.

**Comment by hackiftekhar** [comment]
Autolayout is a powerful tool. I suggest you to go with autolayout (mot disable) with correct configuration.
