### ISSUE TITLE
Cannot show toolbar in iOS18 beta4

### ISSUE THREAD

**Issue by ajunjunandtmac** [hackiftekhar/IQKeyboardManager#2061]
Hi, i found the toolbar issue in iOS 18 beta4, please see below screenshots, Thanks very much!
iOS 17 screenshot:
![iOS17_4](https://github.com/user-attachments/assets/e66e57da-3494-46e1-b396-0d085b60bd23)

iOS 18 screebshot:
![iOS18_beta4](https://github.com/user-attachments/assets/cee8ba40-3ad2-455b-a2d6-ee3d1f5d07b5)

**Comment by hackiftekhar** [comment]
Can you please check again because I can see the toolbar is showing in iOS 18 as well.

**Comment by kayodeadeniyi** [comment]
@hackiftekhar I confirmed that this is not working on iOS 18 beta 7. Kindly help take a look. Thank you

**Comment by hackiftekhar** [comment]
ok, I'll check it once again but in the meantime if you could also provide your demo project then it would be nice to check it there too.

**Comment by ajunjunandtmac** [comment]
> ok, I'll check it once again but in the meantime if you could also provide your demo project then it would be nice to check it there too.

very sorry for the very late reply
about the demo project, i just this your DemoSwift project to reproduce the issue. you just need to find a phone with iOS 18 beta OS system
thanks for your support again!

**Comment by ajunjunandtmac** [comment]
i debug your demo project and found below
the function `static func hasUserDefinedInputAccessoryView(textInputView: some IQTextInputView) -> Bool`
when OS is iOS 17, the `classNameString` is `InputAccessoryHost<InputAccessoryBar>.Type` and the function will return false
when OS is iOS 18, the `classNameString` is `RootUIView.Type` and the function will return true, this cause the toolbar invisible issue

**Comment by ajunjunandtmac** [comment]
Hi thanks for your effort, but it seems that 7.2.0 has not been released yet right? and when will you release it?

**Comment by hackiftekhar** [comment]
I'm planning to release 7.2.0 this week.
