### ISSUE TITLE
 Cannot modify the frame of viewcontroller.view

### ISSUE THREAD

**Issue by m8282823** [hackiftekhar/IQKeyboardManager#2063]
I encountered a very strange problem. When I passed a certain RN page, the View of a ViewController could not be changed, so the keyboard blocked the input box. But only that ViewController can't change the frame. I tried another ViewController, which can change the frame and pop up the keyboard normally. In the end, I had to manually import IQKeyboardManager and modify the source code to only pop up the externally specified view to adapt to this bug.     

**PS:If you don't go through that RN page, it's completely normal.**

system version: 17.6

**Comment by hackiftekhar** [comment]
I may need a demo project to reproduce this issue.
