### ISSUE TITLE
iOS of React Native, textview  sometimes not show.

### ISSUE THREAD

**Issue by xclidongbo** [hackiftekhar/IQKeyboardManager#2064]
**Describe the bug**

"react-native-scrollable-tab-view": "^1.0.0",
"react-native-gifted-chat": "^2.4.0",
"react": "16.13.1",
"react-native": "0.63.5",

**To Reproduce**
1. giftedchat is include in scrollableTabView.
2. InputText sometimes not show, when the keyboard is show.

**Expected behavior**
InputText always update and show, when the keyboard is show.

**Screenshots**
https://github.com/user-attachments/assets/e1616fb0-8e9b-4086-9b1c-f57aa7077635

**Demo Project**
If applicable, add demo project.

### Versions
**Xcode:** 15.4
**Mac OS:** 14.5
**Simulator/Device:** xx.x
**Simulator/Device Name:** iPhone 12
**Library Version:** 6.5.11

**Additional context**

**Comment by hackiftekhar** [comment]
I saw the video, but I can't help much with this because I don't know the react native, preferably if you could do some of help with debugging and found out what might get wrong then it would be great!.
