### ISSUE TITLE
以swift为主体的混编项目，在OC的VC中如何获取Keyboard上面完成按钮的点击事件

### ISSUE THREAD

**Issue by cocoaJson** [hackiftekhar/IQKeyboardManager#2069]
想要在oc的VC中获取Keyboard上面完成按钮的点击事件

**Comment by cocoaJson** [comment]
IQKeyboardManagerSwift (7.1.1)

**Comment by hackiftekhar** [comment]
Hi @cocoaJson. you can't get it directly (as of now). You should be observing the textFieldShouldEndEditing event and take decisions there.

**Comment by cocoaJson** [comment]
感谢回复，谢谢🙏🙏🙏
