### ISSUE TITLE
The top of the keyboard flashes

### ISSUE THREAD

**Issue by null88888** [hackiftekhar/IQKeyboardManager#2073]
Under the iOS17.5.1 system of Apple 12 mobile phone, when a page has an input box and a password box, the top of the keyboard will flash when editing and deleting the font input box, but it will not appear in the iOS12 system of Apple 7P mobile phone, only a single input box or two input boxes without a password input will not flash.

**Comment by AhmedShammala** [comment]
@null88888  what this mean ? how you fix it
