### ISSUE TITLE
iOS 18.0 toolbar cannot display issue

### ISSUE THREAD

**Issue by ajunjunandtmac** [hackiftekhar/IQKeyboardManager#2076]
Hi
I did debug with your demo project and found below
the function `static func hasUserDefinedInputAccessoryView(textInputView: some IQTextInputView) -> Bool`
when OS is iOS 17, the `classNameString` is `InputAccessoryHost<InputAccessoryBar>.Type` and the function will return false
when OS is iOS 18, the `classNameString` is `RootUIView.Type` and the function will return true, this cause the toolbar invisible issue

_Originally posted by @ajunjunandtmac in https://github.com/hackiftekhar/IQKeyboardManager/issues/2061#issuecomment-2317192939_

**Comment by KBog** [comment]
Same here, the toolbar doesn't appear in iOS 18 regardless if the project was compiled on latest Xcode 16.

**Comment by Mickael-tinytap** [comment]
Same here
