### ISSUE TITLE
dont work well on windows

### ISSUE THREAD

**Issue by suqinglin113x** [hackiftekhar/IQKeyboardManager#2078]
**Describe the bug**

i add a alertview on keywindow, but can not resign the keyboard when i click outside.

**Screenshots**
![image](https://github.com/user-attachments/assets/8e9388f8-83a9-437d-b0d9-3df3c33ce763)

### Versions
**Library Version:7.1.1

**Comment by hackiftekhar** [comment]
Adding view directly to UIWindow is not recommended in iOS and also not supported by the library. The TextField must be part of a UIViewController.
