### ISSUE TITLE
Resize window instead of scroll.

### ISSUE THREAD

**Issue by sadiq81** [hackiftekhar/IQKeyboardManager#208]
Hey

I nice feature could be that the full window was put in a scrollview which was resized to fit the remaining screen space, just like when you write an sms.

Sometimes you dont want the top part of the screen to dissappear since you might have content on it.

**Comment by hackiftekhar** [comment]
I assume you don't want to scroll navigationBar, if YES then you can do scrollView trick described in README file in Manual Management->UINavigationBar.

Let me know if it doesn't solve your problem.

**Comment by sadiq81** [comment]
A made a small video demonstrating.

https://www.youtube.com/watch?v=rBi5gR058xc

**Comment by fatuhoku** [comment]
+1 displacing the entire window is a universal solution, but it is also a cop-out solution. Official guidance on how to adjust a text or scrollview is appreciated.

**Comment by hackiftekhar** [comment]
It seems this is a special case for handling chat screens. So in my opinion it's good to disable library for that particular viewController and implement customised logic according to requirement is best. Let me know what you think.

**Comment by tshtrifork** [comment]
I can see your point, if anyone stumbles on this post this is how I accomplished it.

```objective-c
- (void)setupViews {

   ...
    [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(keyboardWillShow:) name:UIKeyboardWillShowNotification object:nil];
    [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(keyboardWillHide:) name:UIKeyboardWillHideNotification object:nil];
}


- (void)keyboardWillHide:(NSNotification *)notification {
    CGFloat duration = [[[notification userInfo] objectForKey:UIKeyboardAnimationDurationUserInfoKey] floatValue];
    int animationCurve = [[[notification userInfo] objectForKey:UIKeyboardAnimationCurveUserInfoKey] integerValue] << 16;

    [self.composeView mas_updateConstraints:^(MASConstraintMaker *make) {
        make.bottom.equalTo(self.view);
    }];

    [UIView animateWithDuration:duration delay:0 options:(animationCurve | UIViewAnimationOptionBeginFromCurrentState) animations:^{
        [self.view layoutIfNeeded];
    }                completion:NULL];
}

- (void)keyboardWillShow:(NSNotification *)notification {
    CGFloat duration = [[[notification userInfo] objectForKey:UIKeyboardAnimationDurationUserInfoKey] floatValue];
    int animationCurve = [[[notification userInfo] objectForKey:UIKeyboardAnimationCurveUserInfoKey] integerValue] << 16;
    CGRect kbFrame = [[[notification userInfo] objectForKey:UIKeyboardFrameEndUserInfoKey] CGRectValue];

    [self.composeView mas_updateConstraints:^(MASConstraintMaker *make) {
        make.bottom.equalTo(self.view).offset(-kbFrame.size.height);
    }];

    [UIView animateWithDuration:duration delay:0 options:(animationCurve | UIViewAnimationOptionBeginFromCurrentState) animations:^{
        [self.view layoutIfNeeded];
    }                completion:NULL];
}
```

**Comment by hackiftekhar** [comment]
Yes, that's the correct way after disabling library on this particular viewController.

**Comment by hackiftekhar** [comment]
Closing this issue because we need to disable IQKeyboardManager and need to do different workaround according to customised requirement.
