### ISSUE TITLE
Intermittent crash in IQKeyboardManager 6.5.19: -[__NSArrayM insertObject:atIndex:]: object cannot be nil

### ISSUE THREAD

**Issue by qius-code** [hackiftekhar/IQKeyboardManager#2080]
Description:
We are experiencing an intermittent crash in our production app when using IQKeyboardManager. The crash occurs seemingly randomly when a text field begins editing, specifically within the IQKeyboardManager's handling of keyboard toolbar addition. We have not been able to reproduce this issue consistently in our development environment.

Environment:
- IQKeyboardManager Version: 6.5.19
- App Version: 1.1.18.1724926494
- Device: iPhone 15 Pro
- iOS Version: 18.0 (22A3354)
- CPU Architecture: arm64-v8a

Crash Details:
Exception Type: NSInvalidArgumentException
Exception Message: *** -[__NSArrayM insertObject:atIndex:]: object cannot be nil

Stack Trace:
0   CoreFoundation                 ___exceptionPreprocess + 164
1   libobjc.A.dylib                objc_exception_throw + 88
2   CoreFoundation                 -[__NSArrayM insertObject:atIndex:] + 1276
3   UIKitCore                      +[UIKeyboardImpl uniqueNumberPadInputModesFromInputModes:forKeyboardType:] + 1524
4   UIKitCore                      -[_UIKeyboardStateManager desirableInputModesWithExtensions:] + 1088
5   UIKitCore                      -[_UIKeyboardStateManager recomputeActiveInputModesWithExtensions:allowNonLinguisticInputModes:] + 188
6   UIKitCore                      -[_UIKeyboardStateManager _setupDelegate:delegateSame:hardwareKeyboardStateChanged:endingInputSessionIdentifier:force:delayEndInputSession:] + 1800
7   UIKitCore                      -[_UIKeyboardStateManager setDelegate:force:delayEndInputSession:] + 632
8   UIKitCore                      -[UIKeyboardSceneDelegate _reloadInputViewsForKeyWindowSceneResponder:force:fromBecomeFirstResponder:] + 2932
9   UIKitCore                      -[UIKeyboardSceneDelegate _reloadInputViewsForResponder:force:fromBecomeFirstResponder:] + 88
10  UIKitCore                      -[UIResponder(UIResponderInputViewAdditions) reloadInputViews] + 84
11  IQKeyboardManager              -[UIView(IQToolbarAddition) addKeyboardToolbarWithTarget:titleText:rightBarButtonConfiguration:previousBarButtonConfiguration:nextBarButtonConfiguration:] + 2960
12  IQKeyboardManager              -[IQKeyboardManager addToolbarIfRequired] + 756
13  IQKeyboardManager              -[IQKeyboardManager textFieldViewDidBeginEditing:] + 440
14  CoreFoundation                 ___CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 148

Additional Information:
- The crash occurs in the foreground after approximately 2 minutes and 57 seconds of app usage.
- This issue has been reported by our crash reporting system in the production environment.
- We have not been able to consistently reproduce this issue in our development environment.

Steps to Reproduce:
Unfortunately, we don't have consistent steps to reproduce this issue. It appears to occur randomly when users interact with text fields in the app.

Questions:
1. Are there any known issues with IQKeyboardManager 6.5.19 on iOS 18.0 or with the iPhone 15 Pro that could lead to this type of crash?
2. Do you have any suggestions for additional debugging steps or logging we could implement to gather more information about this crash when it occurs in production?
3. Are there any specific IQKeyboardManager configurations or best practices that might help prevent this type of issue?
4. Given that this is an intermittent issue in production, do you have any recommendations for safeguards or error handling we could implement to prevent crashes even if this error occurs?

We appreciate any insights or assistance you can provide in helping us understand and resolve this intermittent crash. Thank you for your time and for maintaining this valuable library.

**Comment by hackiftekhar** [comment]
By looking at the crash report, it looks like the crash occurs due to UIKitCore. If the crash was happen due to IQKeyboardManager then [__NSArrayM insertObject:atIndex:] should have been appeared somewhere just near the IQKeyboardManager logs.

Answers:
1. As far as my knowledge, I don't remember same crash with around same logs, however there were previous issues related to crash due to arrays but not exactly the same.
2. As I feels like this is probably an iOS issue so I can't provide any debugging suggestions for it, because from the library side, looks like we are doing everything correctly.
3. Nope, I don't think this is something related to any IQKeyboardManager configuration.
4. I would recommend to try out upgraded version of the library because sometimes a slight code changes may tweak things to iOS.

Thank you for your kind words. I feel very good when I listen these love towards library.

**Comment by anton-plebanovich** [comment]
I do not have `IQKeyboardManager` installed, and have this crash occurring on iPad devices. This is an Apple bug. Since Google search leads to this topic, I leave my comment here for anyone else's information. 

In my case, it is more likely related to keyboard type being decimal pad: `textField.keyboardType = .decimalPad`

OS version: iPadOS 18.3.2
Model: iPad Air (5th generation)
```
          Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x2d5fc __exceptionPreprocess
1  libobjc.A.dylib                0x31244 objc_exception_throw
2  CoreFoundation                 0x28708 -[__NSArrayM insertObject:atIndex:]
3  UIKitCore                      0xf688fc +[UIKeyboardImpl uniqueNumberPadInputModesFromInputModes:forKeyboardType:]
4  UIKitCore                      0x9555a0 -[_UIKeyboardStateManager desirableInputModesWithExtensions:]
5  UIKitCore                      0x95581c -[_UIKeyboardStateManager recomputeActiveInputModesWithExtensions:allowNonLinguisticInputModes:]
6  UIKitCore                      0x93bed0 -[_UIKeyboardStateManager _setupDelegate:delegateSame:hardwareKeyboardStateChanged:endingInputSessionIdentifier:force:delayEndInputSession:]
7  UIKitCore                      0x30dd1c -[_UIKeyboardStateManager setDelegate:force:delayEndInputSession:]
8  UIKitCore                      0x1e3128 -[UIKeyboardSceneDelegate _reloadInputViewsForKeyWindowSceneResponder:force:fromBecomeFirstResponder:]
9  UIKitCore                      0x4190dc -[UIKeyboardSceneDelegate _reloadInputViewsForResponder:force:fromBecomeFirstResponder:]
10 UIKitCore                      0xb1d9c -[UIResponder(UIResponderInputViewAdditions) _reloadInputViewsFromFirstResponder:]
11 UIKitCore                      0x1e20b4 -[UIResponder becomeFirstResponder]
12 UIKitCore                      0x1e4840 -[UIView(Hierarchy) becomeFirstResponder]
13 UIKitCore                      0x142206c -[UITextField becomeFirstResponder]
14 UIKitCore                      0x13e481c -[UITextInteractionAssistant(UITextInteractionAssistant_Internal) setFirstResponderIfNecessaryActivatingSelection:]
15 UIKitCore                      0x13c13c8 -[UITextSelectionInteraction _checkForRepeatedTap:gestureLocationOut:]
16 UIKitCore                      0x13c227c -[UITextSelectionInteraction _handleMultiTapGesture:]
17 UIKitCore                      0x4f13e8 -[UIApplication sendAction:to:from:forEvent:]
18 UIKitCore                      0xc34150 -[UITextMultiTapRecognizer onStateUpdate:]
19 UIKitCore                      0x413650 -[UIGestureRecognizerTarget _sendActionWithGestureRecognizer:]
20 UIKitCore                      0x4134c0 _UIGestureRecognizerSendTargetActions
21 UIKitCore                      0x413280 _UIGestureRecognizerSendActions
22 UIKitCore                      0xc45f8 -[UIGestureRecognizer _updateGestureForActiveEvents]
23 UIKitCore                      0x81a78 _UIGestureEnvironmentUpdate
24 UIKitCore                      0x211150 -[UIGestureEnvironment _deliverEvent:toGestureRecognizers:usingBlock:]
25 UIKitCore                      0x2d667c -[UIGestureEnvironment _updateForEvent:window:]
26 UIKitCore                      0x2d5138 -[UIWindow sendEvent:]
27 UIKitCore                      0x2d408c -[UIApplication sendEvent:]
28 UIKitCore                      0x2c34d0 __dispatchPreprocessedEventFromEventQueue
29 UIKitCore                      0x1c5f8c __processEventQueue
30 UIKitCore                      0x9e8a4 updateCycleEntry
31 UIKitCore                      0x9c710 _UIUpdateSequenceRun
32 UIKitCore                      0x9f040 schedulerStepScheduledMainSection
33 UIKitCore                      0x9cc5c runloopSourceCallback
34 CoreFoundation                 0x73f4c __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
35 CoreFoundation                 0x73ee0 __CFRunLoopDoSource0
36 CoreFoundation                 0x76b40 __CFRunLoopDoSources0
37 CoreFoundation                 0x75d3c __CFRunLoopRun
38 CoreFoundation                 0xc8284 CFRunLoopRunSpecific
39 GraphicsServices               0x14c0 GSEventRunModal
40 UIKitCore                      0x3ee674 -[UIApplication _run]
41 UIKitCore                      0x14e88 UIApplicationMain
42 Divtracker                     0x170e4 main + 19 (AppDelegate.swift:19)
43 ???                            0x1c1cc1de8 (Missing)
        
```

**Comment by mariia-cherniuk** [comment]
Hi @anton-plebanovich I was wondering if you’ve been able to find a solution for this issue.
I'm seeing the same crash reported in Firebase. It seems to occur on iPads when a text field is part of a web view, though unfortunately I haven’t been able to reproduce it locally myself. Were you able to reproduce it in Xcode, or is it showing up for you only in Crashlytics logs as well?
