### ISSUE TITLE
When 7.2.0 will be released

### ISSUE THREAD

**Issue by ajunjunandtmac** [hackiftekhar/IQKeyboardManager#2081]
#2061 was fixed in 7.2.0 and when will this official version will be released? 
The version in remote pod spec is still 7.1.1 right now
thanks very much

**Comment by hackiftekhar** [comment]
I'm planning to release 7.2.0 this week.

**Comment by ajunjunandtmac** [comment]
By the way, should we write the code below right now?
```swift
IQKeyboardManager.shared.enableAutoToolbar = true
IQKeyboardToolbarManager.shared.isEnabled = true
```
Or `IQKeyboardToolbarManager` is just for the future big version, no need to write it in current version?

I have the question because i've tried to use `IQKeyboardToolbarManager.shared.isEnabled = true` only but the toolbar can not display,  if use `IQKeyboardManager.shared.enableAutoToolbar = true`, the toolbar worked

**Comment by mmatiush** [comment]
@hackiftekhar it looks like the commit 3989683f60dfc33df6063f9a8d0fabb50a910e9d causes errors when building the project with 7.2.0 version of IQKeyboardManagerSwift

**Comment by hackiftekhar** [comment]
@mmatiush Could you please provide me screenshots?

**Comment by mbarringer** [comment]
@hackiftekhar When I try to use 7.2.0 with "Up to Next Major Version" or "Exact Version", I get the following error during the package resolution:

> Revision 3989683f60dfc33df6063f9a8d0fabb50a910e9d for iqkeyboardmanager remoteSourceControl https://github.com/hackiftekhar/IQKeyboardManager version 7.2.0 does not match previously recorded value 0d9b0277275b8c5f5cd13daf52e988ff44c8f066

When I pin it to commit `0d9b0277275b8c5f5cd13daf52e988ff44c8f066` or to version 7.1.1, everything is fine.

**Comment by hackiftekhar** [comment]
@mbarringer I don't know what might have cause to introduce this error, however this is not a compilation error and it is something related to the SPM.

**Comment by mbarringer** [comment]
For anyone who comes across the SPM problem - close Xcode, run `rm ~/Library/org.swift.swiftpm/security/fingerprints/iqkeyboardmanager*` in the terminal, start Xcode, and it should work again. Looks like maybe a tag was force pushed or something.

**Comment by mmatiush** [comment]
@mbarringer I had the same error. Your fixe helped. Thank you

**Comment by hackiftekhar** [comment]
> For anyone who comes across the SPM problem - close Xcode, run `rm ~/Library/org.swift.swiftpm/security/fingerprints/iqkeyboardmanager*` in the terminal, start Xcode, and it should work again. Looks like maybe a tag was force pushed or something.

Yeah, I had break down the library to subspecs and created a tag, but due to some misconfiguration the subspecs wasn't passing  (I forgot to lint it before publishing).

So I had deleted the tag immediately and then fix the subspec, lint it and then published the tag again with updated commit.

This might have been caused this issue.

**Comment by hackiftekhar** [comment]
> @hackiftekhar By the way, should we write the code below right now?
> 
> ```swift
> IQKeyboardManager.shared.enableAutoToolbar = true
> IQKeyboardToolbarManager.shared.isEnabled = true
> ```
> 
> Or `IQKeyboardToolbarManager` is just for the future big version, no need to write it in current version?
> 
> I have the question because i've tried to use `IQKeyboardToolbarManager.shared.isEnabled = true` only but the toolbar can not display, if use `IQKeyboardManager.shared.enableAutoToolbar = true`, the toolbar worked

You should be doing this below if you would like to migrate to use IQKeyboardToolbarManager now. This basically tells to disable toolbar handling in IQKeyboardManager and will start using the IQKeyboardToolbarManager for toolbar handling.
> ```swift
> IQKeyboardManager.shared.enableAutoToolbar = false
> IQKeyboardToolbarManager.shared.isEnabled = true
> ```

however the same thing still exist in current version of IQKeyboardManager, so even if you don't use IQKeyboardToolbarManager now and don't modify anything with the current version, it will still work as it was working before, so there is no need to change anything if you would like to opt-out for now. 

But in future version, 8.0.0 these secondary features will be removed from IQKeyboardManager and you had to use the independent libraries like IQKeyboardToolbarManager, IQTextView, IQKeyboardReturnManager etc.

**Comment by ajunjunandtmac** [comment]
> > @hackiftekhar By the way, should we write the code below right now?
> > ```swift
> > IQKeyboardManager.shared.enableAutoToolbar = true
> > IQKeyboardToolbarManager.shared.isEnabled = true
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Or `IQKeyboardToolbarManager` is just for the future big version, no need to write it in current version?
> > I have the question because i've tried to use `IQKeyboardToolbarManager.shared.isEnabled = true` only but the toolbar can not display, if use `IQKeyboardManager.shared.enableAutoToolbar = true`, the toolbar worked
> 
> You should be doing this below if you would like to migrate to use IQKeyboardToolbarManager now. This basically tells to disable toolbar handling in IQKeyboardManager and will start using the IQKeyboardToolbarManager for toolbar handling.
> 
> > ```swift
> > IQKeyboardManager.shared.enableAutoToolbar = false
> > IQKeyboardToolbarManager.shared.isEnabled = true
> > ```
> 
> however the same thing still exist in current version of IQKeyboardManager, so even if you don't use IQKeyboardToolbarManager now and don't modify anything with the current version, it will still work as it was working before, so there is no need to change anything if you would like to opt-out for now.
> 
> But in future version, 8.0.0 these secondary features will be removed from IQKeyboardManager and you had to use the independent libraries like IQKeyboardToolbarManager, IQTextView, IQKeyboardReturnManager etc separately.

OK sir i got it, my appreciate
