### ISSUE TITLE
The toolbar does not always appear, even after fix 0d9b027

### ISSUE THREAD

**Issue by Mickael-tinytap** [hackiftekhar/IQKeyboardManager#2082]
The toolbar does not always appear, even after fix 0d9b027
https://github.com/hackiftekhar/IQKeyboardManager/issues/2076

However, if we force `IQKeyboardManager.shared.enableAutoToolbar = true`, then the toolbar is showed all the time but the property is deprecated and its not the correct behavior because just `IQKeyboardManager.shared.enable = true` should enable it by default.

**Comment by hackiftekhar** [comment]
I can see in my demo that with only `IQKeyboardManager.shared.enable = true` the toolbar is showing in UIKit and SwiftUI
