### ISSUE TITLE
enableAutoToolbar

### ISSUE THREAD

**Issue by gerchicov-vg** [hackiftekhar/IQKeyboardManager#2083]
**Describe the bug**
`IQKeyboardManager.shared.enableAutoToolbar = false` produces a warning:
```
'enableAutoToolbar' is deprecated: Please disable Toolbar using `IQKeyboardManager.shared.enableAutoToolbar = false` and use `IQKeyboardToolbarManager` independently from https://github.com/hackiftekhar/IQKeyboardToolbarManager
```
In other words you should replace `enableAutoToolbar` with the same `enableAutoToolbar`

**To Reproduce**
Just add `IQKeyboardManager.shared.enableAutoToolbar = false`

**Expected behavior**
No warnings

**Screenshots**
-

**Demo Project**
-

### Versions
**Xcode:** any
**Mac OS:** any
**Simulator/Device:** any
**Simulator/Device Name:** any
**Library Version:** 7.2.0 (SPM)

**Additional context**
-

**Comment by hackiftekhar** [comment]
The toolbar related stuffs have been moved to a new library `IQKeyboardToolbarManager` https://github.com/hackiftekhar/IQKeyboardToolbarManager which can be used independently without IQKeyboardManager.

While you can still use the current setup as it is and it should work, however if you could migrate to use `IQKeyboardToolbarManager` for keyboard toolbar related stuffs then that would be great.
