### ISSUE TITLE
Readme states there is a 7.0.0 migration guide, but link leads to a non-existent page in the Wiki

### ISSUE THREAD

**Issue by Digifais** [hackiftekhar/IQKeyboardManager#2084]
The readme states that there should be a 7.0.0 migration guide located here: https://github.com/hackiftekhar/IQKeyboardManager/wiki/IQKeyboardManager-7.0.0-Migration-Guide, but clicking on the link leads you to a non-existent page in the wiki.

**Comment by hackiftekhar** [comment]
These pages moved here
https://github.com/hackiftekhar/IQKeyboardManager/blob/master/Documentation/MIGRATION%20GUIDE%206.0%20TO%207.0.md

https://github.com/hackiftekhar/IQKeyboardManager/blob/master/Documentation/MIGRATION%20GUIDE%207.0%20TO%208.0.md
