### ISSUE TITLE
"enableAutoToolbar" previously  defaulted to true, now it defaults to false unless read first

### ISSUE THREAD

**Issue by dhoerl** [hackiftekhar/IQKeyboardManager#2085]
**Describe the bug**
My app "SalesPro" has been using IQKeyboardManager for years. We use all default settings, and our only direct interaction with it has been to exclude a few classes.

After updating our Swift Package, the inputAccessoryView disappeared - it was as if we had:
   IQKeyboardManager.shared.enableAutoToolbar = false
but we never even referenced that setting.

Turns out that if in AppDelegate, if I simply read that settings:
  let enableAutoToolbar = IQKeyboardManager.shared.enableAutoToolbar
  print("enableAutoToolbar:", enableAutoToolbar)
That magically the inputAccessoryView appears again!

So - your last fixes caused this. Reading that setting must have side effects that cause the actual value to get set.

**To Reproduce**
1. Don't touch enableAutoToolbar
2. Launch an App
3. Open a view with a text field and click in it
4. See that there is no inputAccessoryView

**Expected behavior**
See that there is an inputAccessoryView

### Versions
**Xcode:** 15.4
**Mac OS:** N/A
**Simulator/Device:** 17.5
**Simulator/Device Name:** iPhone 12
**Library Version:** 7.2.0

**Additional context**

**Comment by harsh7703** [comment]
same issue happened to me also.

**Comment by dhoerl** [comment]
Based on Issue #2083, my guess is the way to fix this is to add the IQKeyboardToolbarManager  package to my project, then do this at launch: IQKeyboardToolbarManager.shared.isEnabled = true

There is an issue in that project that reports a slew of warnings, that the author has said he would fix shortly. So going to wait a few days to do this.

**Comment by harsh7703** [comment]
@dhoerl  - Thank you for your prompt reply. We are waiting for the fix that you mentioned above.

**Comment by hackiftekhar** [comment]
You are correct. This is caused due to segregation of the library into smaller part. Unfortunately this can't be fix at the 
moment due to some problems with accessing variables of other modules. You have to add below line in AppDelegate
`IQKeyboardManager.shared.enableAutoToolbar = true`

Or 

`IQKeyboardToolbarManager.shared.isEnabled = true` (If you are using IQKeyboardToolbarManager separately)

**Comment by hackiftekhar** [comment]
This now has been fixed in IQKeyboardToolbarManager library. Thanks
