### ISSUE TITLE
Issue #2085 is not fixed in the current Swift Packages

### ISSUE THREAD

**Issue by dhoerl** [hackiftekhar/IQKeyboardManager#2090]
#2805 was closed as it was fixed. but I just updated all my Swift Packages in latest Xcode, and when I disabled the line that sets the isEnabled flag to on (actually, I just read the flag, that causes the toolbar Done button to appear), no Done button.

Would be great to add a line to the README that says you now need to enable it if that is what we need to do going forward.

**Comment by hackiftekhar** [comment]
This is mentioned in the migration guide.
https://github.com/hackiftekhar/IQKeyboardManager/blob/master/Documentation/MIGRATION%20GUIDE%207.0%20TO%208.0.md
