### ISSUE TITLE
UI/UX suggestion.

### ISSUE THREAD

**Issue by EvgenyKarkan** [hackiftekhar/IQKeyboardManager#21]
Good and useful library. Thanks!

I think it will be more user-friendly to not to hide navigation bar. 
Just make it static and scroll only textfields superview.

Cheers!

**Comment by devkiang** [comment]
cool!

**Comment by Premal-Khetani** [comment]
I am getting still this issue in ios 10

**Comment by hackiftekhar** [comment]
@Premal-Khetani Have you tried navigation bar trick mentioned in manual management guide?

**Comment by Premal-Khetani** [comment]
@hackiftekhar  yes i tried it with adding uiscrollview as a class but still not working

**Comment by hackiftekhar** [comment]
If you are using Autolayout then make sure your UIScrollView is calculating your contentSize properly or if you are using Autoresizing then make sure to set it's contentSize externally.

**Comment by Premal-Khetani** [comment]
@hackiftekhar i am using Autolayout and i am using tableview to show chatting screen and in the bottom of main view i added uitextview but when i set uiscrollview as main class instead of uiview the functionality doesn't work but when i remove uiscrollview and add uiview then it works but then the navigationbar is goes up. :(

**Comment by hackiftekhar** [comment]
ahh, if you are trying to implement something like chatting screen then it would be hard for IQKeyboardManager for managing the things. I would suggest to disable IQKeyboardManager for that particular class and write your own logic there.

**Comment by Premal-Khetani** [comment]
oky But the thing is that it was working fine before ios 10 so i am not getting the point why it is not working  :(

**Comment by hackiftekhar** [comment]
Not sure because I didn't get any issues at my end with iOS10 updates.

**Comment by Premal-Khetani** [comment]
ok let me find out the exact point for that :(
