### ISSUE TITLE
Unable manually to go to the next textfield. 

### ISSUE THREAD

**Issue by pashan** [hackiftekhar/IQKeyboardManager#210]
Is it possible to go to the next textfield programmatically without clicking arrows? same behavior as you click on arrows.

**Comment by hackiftekhar** [comment]
You can check IQKeyboardManager.m, you'll find a property named `canGoNext` and a method named `-(void)goNext`. Same you'll find for previous also, this will do the programmatically trick. Hope this help. :)

**Comment by amorenew** [comment]
i use the library by pod
so is there any way to use these functions by override in my UIViewController ?

**Comment by hackiftekhar** [comment]
This function belongs to IQKeyboardManager class, so if `SearchTextField` class is subclass of UITextField then `-(void)goNext` should work for you.

**Comment by amorenew** [comment]
it's sub of UITextField but not go next 
should i add tags or something in it

**Comment by hackiftekhar** [comment]
Could you please let me know how many other textFields are on same view with your SearchTextField and what kind of action you are doing to go next.

**Comment by amorenew** [comment]
the author of library give me this code and it's worked
IQKeyboardManager.sharedManager().toolbarManageBehaviour = .ByTag
**link to fix**:
https://github.com/apasccon/SearchTextField/issues/1#issuecomment-234249965

**Comment by amorenew** [comment]
i have 2 search SearchTextField and 2 UITextField for date picker
