### ISSUE TITLE
Crash when settings textField appearance autoCorrectionType to NO.

### ISSUE THREAD

**Issue by karadis** [hackiftekhar/IQKeyboardManager#214]
I want to disable auto correction in my app.
like so:
[[UITextField appearance] setAutocorrectionType:UITextAutocorrectionTypeNo];
caused a crash on starting the controller with the a textField.

reason: *** -[__NSArrayM insertObject:atIndex:]: object cannot be nil'.

Is there a way to override this? or hide the autocorrection bar with the manager?
Thanks.

**Comment by hackiftekhar** [comment]
Unfortunately currently I didn't provided any functionality to manage textFields appearance properties.

**Comment by karadis** [comment]
I understand. It can be a nice enhancement for the future.
BTW, setting the textField autoCorrection property to 'NO' in the specific controller worked just fine.

**Comment by hackiftekhar** [comment]
In my opinion if it's managed manually then it would be best. The core functionality of library is to manage textField and keyboard distance and the advanced functionality are that which is related to 'textField and keyboard' distance management, resigning textField, toolbars etc. So It would be good if textField properties are managed automatically.
