### ISSUE TITLE
When UITextBorderStyleNone has a BUG

### ISSUE THREAD

**Issue by orinchen** [hackiftekhar/IQKeyboardManager#216]
When UITextField Border Style is UITextBorderStyleNone，the text will disappear!

**Comment by hackiftekhar** [comment]
Please explain in details or share demo.

**Comment by orinchen** [comment]
just like this
![err less](https://cloud.githubusercontent.com/assets/872492/7697158/69cac1de-fe37-11e4-88c4-a6bcf5c4917c.gif)

**Comment by orinchen** [comment]
Just like this
![iqkeyboardbug](https://cloud.githubusercontent.com/assets/872492/7697272/752ebff2-fe38-11e4-9926-a197e8d71788.gif)

**Comment by hackiftekhar** [comment]
Is it something related with #217?
