### ISSUE TITLE
UITextField text jumps when IQKeyboardManager switches first responder.

### ISSUE THREAD

**Issue by IchabodDee** [hackiftekhar/IQKeyboardManager#217]
I am using Swift 1.2.  Whenever I enter text into a text field and hit the next button on the IQKeyboardManager, the manager works as expected except for an extra jump to the text in the text field that is being resigned. The text moves ~15 pixels above the Textfield, and then flashes back to the expected position.

The text moves out of the frame of the text field for a second.  This behavior will only happen once for a given text field.  Once it has happened, the text settles back into the TextField and does not jump upon further switching of first responder.

I made sure that my Storyboard file is anchored to the view and not the top layout guide.  I also made sure that the sharedManager is enabled in the app delegate.

**Comment by IchabodDee** [comment]
Also the jump does not happen when the Done Button is pressed. 

I was stepping through the KeyboardManager code and could not find anything that would suggest the behavior there.  The Manager does not think that the frame has changed or anything.

**Comment by hackiftekhar** [comment]
May be I need to debug swift version. FYI I always suggest developer to use objC version instead of swift because objC version is updated on a regular basis and swift is updated one or two time in quarterly year.

**Comment by IchabodDee** [comment]
Thanks for the response.

Sorry for being unclear.  The IQKeyboardManager code is all Objc.  My project is in Swift 1.2.

**Comment by hackiftekhar** [comment]
Ok, will check this weekend

**Comment by sokalyambda** [comment]
Confirm this issue!
I also have it, obj-c

**Comment by trungnguyen1791** [comment]
I have same issues with my objective c project.

**Comment by hackiftekhar** [comment]
I Couldn't find anything regarding the issue when I created a demo to reproduce the same issue, can someone send me the demo project.

**Comment by trungnguyen1791** [comment]
This happened to me in this situation:
I have 4 textfields ( using "goNext" function to moves between them). And using "[IQKeyboardManager sharedManager].shouldResignOnTouchOutside = true;"
If you only tap on one text field, type somethings, taps "next" button on keyboard => it work well.

But if you tap on a textfield, type somethings then taps outside to hide keyboard. => The jumps will happened in the next time you tap on that textfield.

**Comment by hackiftekhar** [comment]
Ok, got you. Will try to reproduce in your suggested conditions.

**Comment by hackiftekhar** [comment]
Not able to reproduce with @trungnguyen1791 suggested conditions too, so if someone can provide me demo code then it would be great.

**Comment by hackiftekhar** [comment]
I found that calling 'setNeedsLayout' and 'layoutIfNeeded' from IQKeyboardManager on viewControllers.view causes disorder the internal hierarchy of UITextField when it's border style is UITextBorderStyleNone. Setting 'layoutIfNeededOnUpdate' to NO solve the issue.

FYI from now 'layoutIfNeededOnUpdate is default to NO.

**Comment by nathanielescribano** [comment]
i think I'm still seeing this.
After entering info and clicking on8he next field, i see the previous field jump and disapeapr
Event After setting layoutIfNeededOnUpdate to NO

![screen recording 2015-10-15 at 05 15 pm](https://cloud.githubusercontent.com/assets/183247/10530893/8ad2694c-7360-11e5-8b9e-bcfa2b49e45d.gif)

Any thoughts?

**Comment by hackiftekhar** [comment]
Can you please confirm that it's not jumping when library is removed.

**Comment by nathanielescribano** [comment]
yup. same code with library removed works as expected (without the autoscrolling of course)

**Comment by hackiftekhar** [comment]
Then please teopen this issue and upload demo project here. I'll try to
debug it.

**Comment by w-i-n-s** [comment]
I have some very close issue http://imgur.com/a/XbjcT https://youtu.be/_-FSW_ePZMQ
