### ISSUE TITLE
Gesture of lateral menu not working when using IQKeyboardManager 

### ISSUE THREAD

**Issue by tbaranes** [hackiftekhar/IQKeyboardManager#218]
Hi,

I just found out IQKeyboardManager, this library is just amazing!

However, I'm running in a weir issue: my application has a lateral menu (in my case [SWRevealViewController](https://github.com/John-Lluch/SWRevealViewController)), which enable pan gesture... but when I'm adding IQKeyboardManager (using pods), the pan isn't enable anymore.

Did you never run in this kind of issue? Or any idea about why is that happening?

I could understand if it wasn't working when a UITextField is targeting, or if the keyboard is open... but why is that blocking all the time?

**Comment by hackiftekhar** [comment]
Could you please attach demo code so that I can debug it.

**Comment by tbaranes** [comment]
My bad, after some deeper searching, I found an error in my implementation.

So nothing to change, thanks! :)

**Comment by hackiftekhar** [comment]
Great!
