### ISSUE TITLE
NavigationBar scroll out of screen

### ISSUE THREAD

**Issue by zziazm** [hackiftekhar/IQKeyboardManager#220]
when keyboard show, my navigationbar also move out of screen in some viewControllers, but in other some viewControllers navigationBar do not move when keyboard show, why?

**Comment by zziazm** [comment]
I hane found answer.In viewController adding method 
-(void)loadView
{
    UIScrollView *scrollView = [[UIScrollView alloc] initWithFrame:[[UIScreen mainScreen] bounds]];
    self.view = scrollView;
}

**Comment by wy19901227** [comment]
But  why  must  set self.view=scollview;  why not fix it in code?

**Comment by hackiftekhar** [comment]
Without scrollView I'm not able to scroll the content. and I can't insert a UIScrollView inside self.view. If I do this then developer logic may fail.

**Comment by littlepriest** [comment]
@hackiftekhar Hi, I found a solution to this issue. But I don't know why it works. Can you give me a reply in the near future? Thanks a lot.
The link: https://blog.csdn.net/qq_36905061/article/details/78872874.

**Comment by littlepriest** [comment]
@hackiftekhar Well... He said this issue had a tricky solution. Just remove some codes in function "topMostController" in "IQUIView+Hierarchy.m".  And it works. 😄
