### ISSUE TITLE
constraint to top

### ISSUE THREAD

**Issue by sokalyambda** [hackiftekhar/IQKeyboardManager#221]
I read that it doesn't work when constrained to top layout guide, I have been added constraint like you said, to superviewTop margin but it doesn't work.. What I have to do? thank you!

**Comment by sokalyambda** [comment]
![2015-05-22 09 28 44](https://cloud.githubusercontent.com/assets/12109174/7765299/0d91b71c-0065-11e5-928d-95cb4e7f47b5.png)

Here is an example, I have another view on self.view, there several textFields in it.

**Comment by hackiftekhar** [comment]
Could you please try adding constraint with 'Superview.Top' instead of 'Superview.Top Margin' (Uncheck Constrain to margins)?

**Comment by sokalyambda** [comment]
unfortunately there are no changes...

![2015-05-22 09 47 43](https://cloud.githubusercontent.com/assets/12109174/7765561/d586eee8-0067-11e5-8101-48ca435a90fb.png)
![2015-05-22 09 48 37](https://cloud.githubusercontent.com/assets/12109174/7765562/d5b5920c-0067-11e5-887d-4d85f5f419fe.png)

**Comment by sokalyambda** [comment]
It works for me without top constraint, but I really need it(( thank you!

**Comment by hackiftekhar** [comment]
Thanks, I'll implement something to manage the topLayoutGuide constraint

**Comment by sokalyambda** [comment]
thank you so much! =]
