### ISSUE TITLE
Led to the navigationItem disorder on iOS7

### ISSUE THREAD

**Issue by FutureChen** [hackiftekhar/IQKeyboardManager#222]
I will give you a demo by mail . 

This BUG occurs on my ios7  iPhone

**Comment by FutureChen** [comment]
my email 568600831@qq.com

**Comment by FutureChen** [comment]
![faffa3862882d87fae344750de3e65c7](https://cloud.githubusercontent.com/assets/8944181/7766934/d2765930-00a0-11e5-8ddc-ab7fc9456e98.png)
![7c8390205417a8ff695d1005c93aab13](https://cloud.githubusercontent.com/assets/8944181/7766932/d271d068-00a0-11e5-83c8-3617cdbc422b.png)

![6b014ebd4e0c8126fd60e150ab991bbd](https://cloud.githubusercontent.com/assets/8944181/7766931/d26f51f8-00a0-11e5-8eee-ba78964cfea9.png)

![7d34e0eb163dfcbbf765af7ad8c342be](https://cloud.githubusercontent.com/assets/8944181/7766933/d27259d4-00a0-11e5-9626-df74f79a5755.png)

**Comment by hackiftekhar** [comment]
Great if you can share demo.

**Comment by FutureChen** [comment]
I have been sent to you by email before

**Comment by hackiftekhar** [comment]
It's working fine at my end. Please let me know the steps to reproduce the issue.

**Comment by FutureChen** [comment]
You are on the system of IOS 7.1 run my demo?
The BUG only occurs on my iphone5
 My iPhone 6 system of 8.3 is ok

**Comment by FutureChen** [comment]
at ios 8
![Uploading C5A3218A-2DE4-48D4-BDC1-C11264F6DED1.png…]()
at ios 7
![Uploading Screen Shot 2015-05-28 at 上午9.31.13.png…]()

**Comment by FutureChen** [comment]
at ios 7
![screen shot 2015-05-28 at 9 31 13](https://cloud.githubusercontent.com/assets/8944181/7851226/da598302-051e-11e5-861b-4438a7077e9f.png)
at 
ios8
![c5a3218a-2de4-48d4-bdc1-c11264f6ded1](https://cloud.githubusercontent.com/assets/8944181/7851235/f8d329f0-051e-11e5-9656-64b438a4657a.png)

**Comment by hackiftekhar** [comment]
I done some code research regarding this and found that on iOS7 it's a bug from Apple side.

Workaround:-
Make sure you resign your textField before pushing nextViewController or before popping back to previousViewController.

Let me know it work for you or not.

**Comment by FutureChen** [comment]
Thank you, it is work for me. Only the textField become fitstRespone will  cause a bug.

**Comment by hackiftekhar** [comment]
You should call becomeFirstResponder in viewDidAppear and not in viewWillAppear.
