### ISSUE TITLE
Added library folder and tries to build. Get 20 warnings in different library files.

### ISSUE THREAD

**Issue by xeppen** [hackiftekhar/IQKeyboardManager#223]
I am not really sure if did something wrong but I just added the library folder form the zipped file and tried to build. Got +20 warnings in different library files.

**Comment by hackiftekhar** [comment]
Could you please share screenshot. Let me know the version of your Xcode and also let me know the library language you are trying to build(swift or objC).

**Comment by xeppen** [comment]
This is in Swift. Xcode 6.3.2

![snip20150525_1](https://cloud.githubusercontent.com/assets/5516587/7800130/eba94f26-0310-11e5-9cc3-17533eb229e7.png)
