### ISSUE TITLE
the previous/next button displaying in gray color

### ISSUE THREAD

**Issue by cartmanguo** [hackiftekhar/IQKeyboardManager#225]
Hello,
I have three textfields in a viewcontroller set vertically,
when I start editing the first textfield,the next button on the toolbar is gray,instead the previous button is able to pressed,what causes this problem?
thanks

**Comment by hackiftekhar** [comment]
Check your textField hierarchy, may be your textFields are displaying correctly in UI but mat have difference position in view hierarchy.

**Comment by hackiftekhar** [comment]
This link can really help you:
http://blevolve.com/tab-order-difficulties-iqkeyboardmanager/
