### ISSUE TITLE
Problem with textfields inside of a scroll view

### ISSUE THREAD

**Issue by jaimeat1** [hackiftekhar/IQKeyboardManager#227]
Hi,

Thanks for your nice library, it saves a lot of work!

I'm working in a view controller with a scroll view and a bottom bar as my custom tab bar. The scroll has two views inside, each one with the same width than the screen. When user selects one option in the custom tab bar, scroll view changes its offset to show the relevant view.

The problem is with the second view (the one in the right), where I have some textfields. When they become first responder, they are moved up but then, at the same time, scroll changes its offset to the other view (the one in the left). When I disable IQKeyboardManager, scroll offset is not affected.

Is this a known bug?

Thank you in advanced!

**Comment by hackiftekhar** [comment]
Thanks for your bug report, unfortunately it's a view hierarchy issue (For IQKeyboardManager not for your project) that can't be handle by library. Actually your view's are side by side, and in-general this is not a generic case when you become first responder for one view and moving to second view in the UI.

Waiting for your reply

**Comment by hackiftekhar** [comment]
Any suggestion from your side?

**Comment by hackiftekhar** [comment]
Any updates?

**Comment by jaimeat1** [comment]
Hi,

Finally, I moved the view with the textfields to be the first in scrollview (left side), so I can avoid this weird behaviour.

Thanks for your time!
