### ISSUE TITLE
problem with adjusting the textview's height 

### ISSUE THREAD

**Issue by davidbuhtig** [hackiftekhar/IQKeyboardManager#228]
First of all, this library is really awesome.

I'm working on a viewcontroller with a textview in it. But the height of the textview is not that proper when the keyboard pop up at the first time. After hiding the keyboard and show the keyboard again, the height of the textview is just fine. I noticed that keyboardWillShow: will be called twice at the first time and the heights of the keyboard are not the same.

Here is the demo code: 
- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view.
    
    self.view.backgroundColor = [UIColor whiteColor];
    self.automaticallyAdjustsScrollViewInsets = NO;
    
    [[IQKeyboardManager sharedManager] setEnable:YES];
    [[IQKeyboardManager sharedManager] setCanAdjustTextView:YES];
    
    UITextView *input = [[UITextView alloc]initWithFrame:CGRectMake(10, 70, [UIScreen mainScreen].bounds.size.width-20, [UIScreen mainScreen].bounds.size.height-80)];
    input.backgroundColor = [UIColor greenColor];
    [self.view addSubview:input];
}

And here is the debug info of the breakpoint at keyboardWillShow::
//first time
(lldb) po aNotification
NSConcreteNotification 0x7bfc6450 {name = UIKeyboardWillShowNotification; userInfo = {
    UIKeyboardAnimationCurveUserInfoKey = 7;
    UIKeyboardAnimationDurationUserInfoKey = "0.25";
    UIKeyboardBoundsUserInfoKey = "NSRect: {{0, 0}, {320, 253}}";
    UIKeyboardCenterBeginUserInfoKey = "NSPoint: {160, 606.5}";
    UIKeyboardCenterEndUserInfoKey = "NSPoint: {160, 353.5}";
    UIKeyboardFrameBeginUserInfoKey = "NSRect: {{0, 480}, {320, 253}}";
    UIKeyboardFrameEndUserInfoKey = "NSRect: {{0, 227}, {320, 253}}";
}}
(lldb) c
Process 5646 resuming
(lldb) po aNotification
NSConcreteNotification 0x7c024880 {name = UIKeyboardWillShowNotification; userInfo = {
    UIKeyboardAnimationCurveUserInfoKey = 7;
    UIKeyboardAnimationDurationUserInfoKey = "0.25";
    UIKeyboardBoundsUserInfoKey = "NSRect: {{0, 0}, {320, 297}}";
    UIKeyboardCenterBeginUserInfoKey = "NSPoint: {160, 353.5}";
    UIKeyboardCenterEndUserInfoKey = "NSPoint: {160, 331.5}";
    UIKeyboardFrameBeginUserInfoKey = "NSRect: {{0, 227}, {320, 253}}";
    UIKeyboardFrameEndUserInfoKey = "NSRect: {{0, 183}, {320, 297}}";
}}
(lldb) c
Process 5646 resuming

//second time
(lldb) po aNotification
NSConcreteNotification 0x7bfce200 {name = UIKeyboardWillShowNotification; userInfo = {
    UIKeyboardAnimationCurveUserInfoKey = 7;
    UIKeyboardAnimationDurationUserInfoKey = "0.25";
    UIKeyboardBoundsUserInfoKey = "NSRect: {{0, 0}, {320, 297}}";
    UIKeyboardCenterBeginUserInfoKey = "NSPoint: {160, 628.5}";
    UIKeyboardCenterEndUserInfoKey = "NSPoint: {160, 331.5}";
    UIKeyboardFrameBeginUserInfoKey = "NSRect: {{0, 480}, {320, 297}}";
    UIKeyboardFrameEndUserInfoKey = "NSRect: {{0, 183}, {320, 297}}";
}}
(lldb) c
Process 5646 resuming

Is this a known bug or is there some settings I just missed?
Looking forward to your reply :)

**Comment by hackiftekhar** [comment]
Will look into this, thanks for your detailed information. BTW, have you tried with canAdjustTextView to YES.

**Comment by davidbuhtig** [comment]
Yes, I have tried that but it still didn't work. You can see it in my demo code.
