### ISSUE TITLE
interfaceorientation is deprecated first deprecated in ios 8.0

### ISSUE THREAD

**Issue by kiwo12345** [hackiftekhar/IQKeyboardManager#229]
Thanks for your awesome library!

Using it I get these errors/warnings, is it something I can ignore?

interfaceorientation is deprecated first deprecated in ios 8.0

Line 756:
let interfaceOrientation = (IQ_IS_IOS8_OR_GREATER) ? UIInterfaceOrientation.Portrait : rootController.interfaceOrientation

Line 1208:
let interfaceOrientation = (IQ_IS_IOS8_OR_GREATER) ? UIInterfaceOrientation.Portrait : topController.interfaceOrientation

**Comment by hackiftekhar** [comment]
Unfortunately I'm unable to find-out a solution to suppress deprecated warning in swift. Let me know how should I suppress deprecation warning in swift. I'll add the code.

**Comment by hackiftekhar** [comment]
Any updates? Did you got how to suppress deprecation warnings in swift?

**Comment by bobintornado** [comment]
My solution: 

Line 756:
let interfaceOrientation = (IQ_IS_IOS8_OR_GREATER) ? UIInterfaceOrientation.Portrait :   UIApplication.sharedApplication().statusBarOrientation


Line 1208
let interfaceOrientation = (IQ_IS_IOS8_OR_GREATER) ? UIInterfaceOrientation.Portrait : UIApplication.sharedApplication().statusBarOrientation

**Comment by toohotz** [comment]
@bobintornado this is what I actually did in my PR # 278 so this should take care of this warning once merged in :+1:

**Comment by hackiftekhar** [comment]
This warning only produces when project minimum deployment target is iOS 8. So I added some compile time checks with __IPHONE_OS_VERSION_MIN_REQUIRED to compile only appropriate portion of code. So you'll not see this warning anymore.
