### ISSUE TITLE
Conflict with TextInputBar

### ISSUE THREAD

**Issue by Oniiichan** [hackiftekhar/IQKeyboardManager#230]
I am using ALTextView (https://github.com/AlexLittlejohn/ALTextInputBar/) to dock an inputbar to the bottom of a view (like the iOS Messenger App). The IQKeyboard causes the inputbar to disappear sometimes. I have tried disabling IQKeyboard in the class but it still has issues:

    IQKeyboardManager.sharedManager().disableInViewControllerClass(CommentsViewController)

**Comment by hackiftekhar** [comment]
Thanks for your report. I will check and let you know my feedback.

**Comment by Oniiichan** [comment]
This is what the conflicting view controller looks like:


    class CommentsViewController: UIViewController, UITableViewDelegate, UITableViewDataSource {
        override func viewDidAppear(animated: Bool) {
            super.viewDidAppear(animated)
            NSNotificationCenter.defaultCenter().addObserver(self,
                selector: Selector("keyboardWillShow:"),
                name: UIKeyboardWillShowNotification,
                object: nil)
            NSNotificationCenter.defaultCenter().addObserver(self,
                selector: Selector("keyboardWillHide:"),
                name: UIKeyboardWillHideNotification,
                object: nil)
        }
    
        func keyboardFrameChanged(notification: NSNotification) {
            println("keyboardFrameChanged")
            let userInfo = notification.userInfo
            let key = UIKeyboardFrameEndUserInfoKey
            if let info = userInfo {
                let frameValue = info[key] as! NSValue
                let _frame = frameValue.CGRectValue()
            }
        }
        
        func keyboardWillShow(notification: NSNotification) {
            // adjusts size when keyboard is present
            let info = notification.userInfo!
            var keyboardSize = (info[UIKeyboardFrameEndUserInfoKey] as! NSValue).CGRectValue().size
            tableView.contentInset.bottom = keyboardSize.height
         
            // scroll to the last comment
            if self.photoCommentObjects.count > 0 { // make sure there is at least 1 comment
                var indexPath = NSIndexPath(forRow: self.photoCommentObjects.count - 1, inSection: 0)
                tableView.scrollToRowAtIndexPath(indexPath, atScrollPosition: UITableViewScrollPosition.Bottom, animated: true)
            }
        
        
            if keyboardDismissTapGesture == nil
            {
                println("dismiss")
                keyboardDismissTapGesture = UITapGestureRecognizer(target: self, action: Selector("dismissKeyboard:"))
                keyboardDismissTapGesture!.delegate = self
                self.view.addGestureRecognizer(keyboardDismissTapGesture!)
            }
        }
        
        func keyboardWillHide(notification: NSNotification) {
            // set size back to original after keyboard dismissed
            tableView.contentInset = UIEdgeInsetsZero
            tableView.scrollIndicatorInsets = UIEdgeInsetsZero
        
            println("will hide")
        
        
            if keyboardDismissTapGesture != nil
            {
                println("test2")
                self.view.removeGestureRecognizer(keyboardDismissTapGesture!)
                keyboardDismissTapGesture = nil
            }
        }
        
        func dismissKeyboard(sender: AnyObject) {
            println("dismiss keyboard")
            textInputBar.textView.resignFirstResponder()
        }

**Comment by hackiftekhar** [comment]
Are you using swift version or Obj-C version?

**Comment by Oniiichan** [comment]
Swift version

**Comment by hackiftekhar** [comment]
ok, will check.

**Comment by Oniiichan** [comment]
Thanks for this :+1: . Were you able to take a look?

**Comment by hackiftekhar** [comment]
Works great for me and I didn't find any issues with this. This was my approach:-
1) Downloaded ALTextInputBar.
2) Replaced it's ViewController code with your provided CommentsViewController code and done minor code and storyboard tweaks to fix some compilation errors.
3) Added these lines in AppDelegate:-
        IQKeyboardManager.sharedManager().enable = true
        IQKeyboardManager.sharedManager().disableInViewControllerClass(CommentsViewController)
        

4) And it works for me.

**Comment by Oniiichan** [comment]
Do you know what might be causing the issue with my code then? My textinputbar disappears when the IQKeyboard files are added to the project. When I delete the files, the textinputbar (ALTextView) works.

**Comment by hackiftekhar** [comment]
Can you please share demo project?

**Comment by hackiftekhar** [comment]
Any updates?
