### ISSUE TITLE
Next/Previous button

### ISSUE THREAD

**Issue by gioramies** [hackiftekhar/IQKeyboardManager#231]
Hi.
I'm trying to use the IQKeyboardManager but read that is works only when the TextFields are in the same view. In an stackoverflow question (http://stackoverflow.com/questions/28993716/trouble-with-next-previous-button-with-iqkeyboardmanager) read "From now you can use '-(void)considerToolbarPreviousNextInViewClass:(Class)toolbarPreviousNextConside‌​redClass' method to work it with other sublings too. I'll add a demo functionality in repo code".
I do not know exactly which demo is. Can someone help me?
Thank you.

**Comment by hackiftekhar** [comment]
You can run the demo app project you found in this repository and go to the 'CustomView Exmaple' section to know how you should use these methods.
