### ISSUE TITLE
View positioning issue while keyboard hide

### ISSUE THREAD

**Issue by jintomenachery** [hackiftekhar/IQKeyboardManager#233]
Hi,
Am having an issue when using IQkeyboardManager for a text field when it is put inside a UIScrollView.

When I select text field, it is scrolling up properly, but when i hide keyboard textfield is not positioned to its original place. (Since I don't want to scroll navigation bar, i have kept my text field inside a scroll view.)

Could you check this. I have uploaded sample code following location https://drive.google.com/file/d/0B9RSj9HunIGqekxzWHh0d0dQejA/view?usp=sharing.

Thank you.

**Comment by hackiftekhar** [comment]
Could you please try setting 'shouldRestoreScrollViewContentOffset' to YES. It defaults to NO.

**Comment by jintomenachery** [comment]
thank you @hackiftekhar. You are awesome..!!!
