### ISSUE TITLE
presentViewController with UIModalPresentationCustom in iOS 8.3

### ISSUE THREAD

**Issue by chaoskyme** [hackiftekhar/IQKeyboardManager#237]
When I  present ViewController with `UIModalPresentationCustom` in iOS 8.3, IQKeyboardManager will not scroll in presentViewController but scroll in current view controller.

**Comment by hackiftekhar** [comment]
Please share demo code.

**Comment by chaoskyme** [comment]
Thanks. I have fixed it.

**Comment by hackiftekhar** [comment]
Could you please let me know how you fixed it? It was library issue or your own code logic issue?

**Comment by chaoskyme** [comment]
I new project to test it that can't repeat. 
So I move the textfield up in presentViewController  to fix it.   
My problem is this.
![out](https://cloud.githubusercontent.com/assets/1863204/8246141/f6fb7598-166b-11e5-8015-742e3ef646d3.gif)

**Comment by hackiftekhar** [comment]
Could you please share demo code so that I'll check the problem with the library code?
