### ISSUE TITLE
How to replace Previous/Next button with Cancel Button

### ISSUE THREAD

**Issue by taojigu** [hackiftekhar/IQKeyboardManager#238]
How could I add a Cancel Button at the left part of toolbar , instead the previous/next button?
Thanks

**Comment by hackiftekhar** [comment]
This can not be changed by IQKeyboardManager automatically, however you still have two options:-

Option 1: Add a toolbar manually using the method 'addCancelDoneOnKeyboardWithTarget:' defined in 'IQUIView+IQKeyboardToolbar.h'.

Option2: For global change you can change 'addPreviousNextDoneOnKeyboardWithTarget' method with  'addCancelDoneOnKeyboardWithTarget:' in 'IQKeyboardManger.h' at line number 1600 approx.

**Comment by bj97301** [comment]
Can I haz feature?

**Comment by hackiftekhar** [comment]
@bj97301, not sure what you mean.

**Comment by asssem** [comment]
Any update to replace Previous/Next buttons with cancel ??

**Comment by hackiftekhar** [comment]
> This can not be changed by IQKeyboardManager automatically, however you still have two options:-
> 
> Option 1: Add a toolbar manually using the method 'addCancelDoneOnKeyboardWithTarget:' defined in 'IQUIView+IQKeyboardToolbar.h'.
> 
> Option2: For global change you can change 'addPreviousNextDoneOnKeyboardWithTarget' method with 'addCancelDoneOnKeyboardWithTarget:' in 'IQKeyboardManger.h' at line number 1600 approx.

This is the solution @asssem
