### ISSUE TITLE
In landscape navigation bar can overlap status bar

### ISSUE THREAD

**Issue by ptclarke** [hackiftekhar/IQKeyboardManager#24]
IQKeyboard manager is working very well however have one small problem in landscape where navigation bar is pushed up and overlaps status bar. Please advise any suggestion for preventing this.
![ios simulator screen shot 12 feb 2014 7 15 44 am](https://f.cloud.github.com/assets/5669170/2142017/6349f9ae-935f-11e3-8f27-ddea291aac4f.png)

**Comment by zhiyongXu** [comment]
I copy the code in the readme.md ,but it doesn't work . Do you know the reason ?

**Comment by hackiftekhar** [comment]
I don't know the reason. Did you checked the demo project? It is working there.

**Comment by zhiyongXu** [comment]
Thanks. I will check carefully.

**Comment by zhiyongXu** [comment]
The problem has been saved after I update the verson in my project. Thanks.
