### ISSUE TITLE
CollectionCell Can not come back

### ISSUE THREAD

**Issue by Darkhorse-Fraternity** [hackiftekhar/IQKeyboardManager#241]
Warm 'the item height must be less than the height of the UICollectionView minus the section insets top and bottom values.'

the collection  layout scrollDirection is UICollectionViewScrollDirectionVertical  
 
![e0f2aecb-e0f6-47de-8d73-8857d62924f6](https://cloud.githubusercontent.com/assets/5756752/8425289/dedcec02-1f36-11e5-860e-44adf0009e60.jpg)

**Comment by mythodeia** [comment]
@Darkhorse-Fraternity are you sure that the warning you get is because of this library?

**Comment by Darkhorse-Fraternity** [comment]
yes   and i use 
[[[NSNotificationCenter defaultCenter]rac_addObserverForName:UIKeyboardWillHideNotification object:nil]subscribeNext:^(id x) {
       @strongify(self);
         [self.collectionView.collectionViewLayout invalidateLayout];
    }];

now it‘s ok
