### ISSUE TITLE
Can't change settings

### ISSUE THREAD

**Issue by dimacheverda** [hackiftekhar/IQKeyboardManager#242]
I have installed manager via Cocoapods and successfully used it until I needed to disable it for particular ViewController using following code, but it doesn't worked for me:
```
[[IQKeyboardManager sharedManager] disableToolbarInViewControllerClass:[TCChatViewController class]];
[[IQKeyboardManager sharedManager] disableInViewControllerClass:[TCChatViewController class]];
```

Then I tried to fully disable it in AppDelegate `didFinishLaunchingWithOptions:` :
```
[[IQKeyboardManager sharedManager] setEnableAutoToolbar:NO];
[[IQKeyboardManager sharedManager] setEnable:NO];
```

But it doesn't work neither. 
Here corresponding question on StackOverflow: [Link](http://stackoverflow.com/questions/31003246/iqkeyboardmanager-not-disabling)

**Comment by dimacheverda** [comment]
Also tried to disable Manager like this, but not working: 

```
- (void)viewWillAppear:(BOOL)animated {
    [super viewWillAppear:animated];
    
    [[IQKeyboardManager sharedManager] setEnableAutoToolbar:NO];
    [[IQKeyboardManager sharedManager] setEnable:NO];
}

- (void)viewWillDisappear:(BOOL)animated {
    [super viewWillDisappear:animated];
   
    [[IQKeyboardManager sharedManager] setEnableAutoToolbar:YES];
    [[IQKeyboardManager sharedManager] setEnable:YES];
}
```

**Comment by candyss9185** [comment]
I am having the same problem. IQKeyboardManager seems to conflict with Layer's ATLAS library and I want to disable it for only the ViewControllers using Layer but I am not able to do so. If I disable for a certain viewController, the keyboard behaves in an unexpected way, sometimes showing the keyboard sometimes not showing anything. Did you find a solution?

**Comment by dimacheverda** [comment]
I am using SlackTextViewController, and there was similar issue which seems to work for them, but not for me: [Issue Link](https://github.com/slackhq/SlackTextViewController/issues/155)

**Comment by hackiftekhar** [comment]
Can someone provide me demo project to debug it?

**Comment by candyss9185** [comment]
I have added the following lines of code in the AppDelegate:
    [[IQKeyboardManager sharedManager] setEnable:YES];
    [[IQKeyboardManager sharedManager] disableInViewControllerClass:[PWBaseConversationViewController class]];

and it seems to be working fine for now. There was a bug reported because of the keyboard but I haven't been able to reproduce it, so I'll assume it works for now. Thanks!
