### ISSUE TITLE
considerToolbarPreviousNextInViewClass broken in UITableView PrototypeCells (Swift)

### ISSUE THREAD

**Issue by apocolipse** [hackiftekhar/IQKeyboardManager#243]
Hey there, thanks for a great keyboard manager!
I noticed a bug working in Swift with the prev/next/done buttons not showing up automagically (or even forcibly with `considerToolbarPreviousNextInViewClass`).
I have a LoginViewController backed as a UITableViewController in storyboard with Static Cells (2 cells) each with a UITextField in the contentView.  
<img width="272" alt="screen shot 2015-07-07 at 8 52 22 am" src="https://cloud.githubusercontent.com/assets/260871/8546435/bab2990e-2485-11e5-9e0f-8b6841501a94.png">

<img width="425" alt="screen shot 2015-07-07 at 8 55 18 am" src="https://cloud.githubusercontent.com/assets/260871/8546451/ea0c5168-2485-11e5-80fd-001b3d953b32.png">

I've properly set up the sharedManager attempting to have the toolbar auto-work, no such luck, I then tried to force `considerToolbarPreviousNextInViewClass` for the class, no such luck, I even went so far as to tag each textField (1, and 2 respectively) and set the toolbarManageBehavior to byTag, no such luck either.

```swift
IQKeyboardManager.sharedManager().enable = true
        IQKeyboardManager.sharedManager().toolbarManageBehaviour = IQAutoToolbarManageBehaviour.ByTag
        IQKeyboardManager.sharedManager().considerToolbarPreviousNextInViewClass(LoginViewController)
```

I did manage to get the desired behavior semi-manually with `addPreviousNextDoneOnKeyboardWithTarget` and set up my own prevNext and Done actions, but they seem rudimentarily simple (just assign the other as firstResponder since there are only 2, and done hits my keyboard 'Done' action as usual.)

I turned on debug logging to see if I could figure out what was going on and this is what ensued:
```
IQKeyboardManager: enabled
true
IQKeyboardManager: ****** textFieldViewDidBeginEditing started ******
IQKeyboardManager: Saving <<UITextField: 0x7fa4bc356480; frame = (84 0.5; 228 44); text = ''; clipsToBounds = YES; opaque = NO; autoresize = RM+BM; tag = 1; gestureRecognizers = <NSArray: 0x7fa4bbca11c0>; layer = <CALayer: 0x7fa4bc31cec0>> 0x00007fa4bc356480> Initial frame : (84.0, 0.5, 228.0, 44.0)
IQKeyboardManager: adding UIToolbars if required
IQKeyboardManager: Saving <<Mobile.LoginViewController: 0x7fa4bc324440> 0x00007fa4bc324440> beginning frame : (0.0, 0.0, 375.0, 667.0)
IQKeyboardManager: ****** textFieldViewDidBeginEditing ended ******
IQKeyboardManager: ****** keyboardWillShow started ******
IQKeyboardManager: Saving <<UITextField: 0x7fa4bc356480; frame = (84 0.5; 228 44); text = ''; clipsToBounds = YES; opaque = NO; autoresize = RM+BM; tag = 1; gestureRecognizers = <NSArray: 0x7fa4bbca11c0>; layer = <CALayer: 0x7fa4bc31cec0>> 0x00007fa4bc356480> Initial frame : (84.0, 0.5, 228.0, 44.0)
IQKeyboardManager: UIKeyboard Size : (375.0, 260.0)
IQKeyboardManager: ****** keyboardWillShow ended ******
```
(The `true` on line 2 is from me calling `println(IQKeyboardManager.sharedManager().isConsiderToolbarPreviousNextInViewClass(LoginViewController))`)

It looks like only `tag = 1` is getting added for the autoPrevNext fun and its not treating the view at a higher level.

Is there some config I'm missing or is this perhaps a swift specific bug?  Any more info on further debugging would be useful too.  I /do/ have a working solution but things like this nag at me ;)

**Comment by hackiftekhar** [comment]
Is toolbar appears an d next/prev does not? Or whole toolbar is disappeared?

**Comment by apocolipse** [comment]
The toolbar appears with the "Done" button and the placeholder text in the toolbar.  the "Prev"/"Next" buttons do not.
I'll see if I can replicate the issue in a standalone app.

**Comment by hackiftekhar** [comment]
Have you tried replicating this issue in a standalone app?
