### ISSUE TITLE
 IQDropDownTextField/IQActionSheetPickerView

### ISSUE THREAD

**Issue by lucianovalle** [hackiftekhar/IQKeyboardManager#244]
Hi!
I am new with development of swift and I am facing  some problems.
I am trying to assemble two PickerView with hours and another with date, but I am not succeeding  with the use of IQDropDownTextField to assemble.
Following is the code  I have assembled with researches.

        var myDatePicker: UIDatePicker = UIDatePicker()
        myDatePicker.datePickerMode = UIDatePickerMode.Time // 4- use time only
       
        let currentDate = NSDate()  //5 -  get the current date
       /*
        myDatePicker.minimumDate = currentDate  //6- set the current date/time as a minimum
        myDatePicker.date = currentDate //7 - defaults to current time but shows how to use it.
       */
        //peimeriDoseTextdropDownTextField.isOptionalDropDown = false
        peimeriDoseTextdropDownTextField.datePickerMode = myDatePicker.datePickerMode
        peimeriDoseTextdropDownTextField.date = currentDate

Does anyone could help me with an example? Thank you!

**Comment by hackiftekhar** [comment]
Firstly you should raise IQDropDownTextField related questions here:- https://github.com/hackiftekhar/IQDropDownTextField on issue tracker.

 IQDropDownTextField has 'dropDownMode' property, you should try that one.
