### ISSUE TITLE
Keyboard Shown in front of popup window

### ISSUE THREAD

**Issue by ivangarcialopez** [hackiftekhar/IQKeyboardManager#245]
Hello, thanks a lot for your code. It's really helpful.
I found a problem and I don't know how to proceed. I'm using the IQKeyboardManager and it works perfect between the 2 fields in my login screen.
I added a function in the textFieldShouldReturn delegate which when I have the 2 fields completed and I'm in the last field when I press the return button in the keyboard I log in into the app. 
The problem is when I have a failure in the login a popup message is shown but the keyboard is shown again right after the popup message. But this keyboard is not working at all (nothing when you press done button or next/previous arrow).
I tried with the IQKeyboardManager resignFirstResponder and the self.view.editing(false) in all delegate methods trying to finish the editing and close the keyboard before and after calling the login function but it's not working.

I have attached the screenshot.
![ios simulator screen shot 10 jul 2015 23 38 39](https://cloud.githubusercontent.com/assets/6485021/8632151/1b148ab2-275d-11e5-9887-7fa6bfc25200.png)

**Comment by hackiftekhar** [comment]
That's very strange issue, could you please share demo code so I can debug that what is going on between textField and keyboard?

**Comment by ivangarcialopez** [comment]
Hello, I'm trying to reproduce the error in a demo but It's impossible. I only have the error in our app. Can I upload the full app?

**Comment by hackiftekhar** [comment]
No, you should not share your app source code with anyone. You should share demo code only.

**Comment by diegothucao** [comment]
I met the same problem

**Comment by hackiftekhar** [comment]
Can someone upload a demo project to demonstrate this issue?

**Comment by hackiftekhar** [comment]
@ivangarcialopez @diegothucao could you please upload a demo and share with me?

**Comment by ivangarcialopez** [comment]
Hello, I'm sorry but to make a demo will take me days. I'll try ro reproduce it.

**Comment by hackiftekhar** [comment]
Any updates?
