### ISSUE TITLE
How to disable a certain viewcontroller instance?

### ISSUE THREAD

**Issue by maimake** [hackiftekhar/IQKeyboardManager#246]
I want to disable an instance , instead of class. How ?

**Comment by hackiftekhar** [comment]
Use 'disableInViewControllerClass:' method of 'IQKeyboardManager' to disable it for the ViewController. Else if you have more than one instance of viewcontroller and want to enable/disable on condition then you can use 'enabled' property to decide whether you want to make it enable or not.

**Comment by varun-naharia** [comment]
where is 'disableInViewControllerClass' method in 'IQKeyboardManager' ? I can't find the method
