### ISSUE TITLE
IQKeyboardReturnKeyHandler doesn't work alongside with considerToolbarPreviousNextInViewClass method

### ISSUE THREAD

**Issue by kevinnguy** [hackiftekhar/IQKeyboardManager#247]
When using `[[IQKeyboardManager sharedManager] considerToolbarPreviousNextInViewClass:[CustomView class]];`, IQKeyboardReturnKeyHandler does not work because of how `initWithViewController` works. I can look into how we can handle text fields in custom views.

**Comment by hackiftekhar** [comment]
IQKyboardManagerReturnKeyHandler is totally different from IQKeyboardManager. There are no relationships between them. I need to do something to make relation between IQKeyboardManager and the returnKeyHandler.

**Comment by kevinnguy** [comment]
For now, my workaround is:

```
#pragma mark - UITextFieldDelegate
- (BOOL)textFieldShouldReturn:(UITextField *)textField {
    [[IQKeyboardManager sharedManager] goNext];

    return YES;
}
```

Works without `IQKeyboardReturnKeyHandler`

**Comment by hackiftekhar** [comment]
Mistakenly wrong reference
