### ISSUE TITLE
IQLayoutGuideConstraint not supported in swift code

### ISSUE THREAD

**Issue by huxia1124** [hackiftekhar/IQKeyboardManager#249]
The swift code is not synchronized with OC code. In swift code, some features are missing such as IQLayoutGuideConstraint related things.

**Comment by hackiftekhar** [comment]
Yes that feature is missing in swift. Usually I sync ObjC code with Swift within 2-3 months, unfortunately I didn't get time to sync my code in last 3-4 month.

**Comment by hackiftekhar** [comment]
Added supportfor IQLayoutGuideConstraint on swift. If you're working with Swift2.0 then you can get Swift2.0 version from Swift2 branch.
