### ISSUE TITLE
Text in textView behind keyboard 

### ISSUE THREAD

**Issue by NBibikov** [hackiftekhar/IQKeyboardManager#250]
Hello! Thanks for great library!
I have one problem that i can't fix self
I have textView on UIViewController. For textView i added IQLayoutGuideConstraint
But text still behind keyboard

GIF - http://d.pr/i/1eye6

**Comment by hackiftekhar** [comment]
Can you please try with 'canAdjustTextView' property with YES.

**Comment by NBibikov** [comment]
Unfortunately doesn't work
i use 
[[IQKeyboardManager sharedManager] setEnable:YES];
and tried add
[[IQKeyboardManager sharedManager] setCanAdjustTextView:YES];

http://d.pr/i/13Z3t

**Comment by hackiftekhar** [comment]
I was trying to reproduce it but I'm unable to do so, @NBibikov FYI the gif links has been expired. If you could share a demo and steps to reproduce issue then it would really help me.

**Comment by NBibikov** [comment]
Thanks fro response! I would be very grateful for the help!
https://dl.dropboxusercontent.com/s/0sb98oa335ifqmk/index.html?dl=0

**Comment by hackiftekhar** [comment]
I can confirm that it's a bug and I found that it is calculating wrong move distance and I know how to fix it but it may take some time.
