### ISSUE TITLE
Swift - How to disable IQKeyboardManager in a specific UIViewController 

### ISSUE THREAD

**Issue by diegothucao** [hackiftekhar/IQKeyboardManager#252]
Dear fiiends,
I am using IQKeyboardManager for my Swift Project (iOS 8.4).
Now I want IQKeyboardManager does not affect a specific UIViewController in my projects. How to make it ?

Thanks in advance,

Thu

**Comment by hackiftekhar** [comment]
Use 'disableInViewControllerClass' method to disable it for a viewController.

**Comment by hackiftekhar** [comment]
Use 'disableInViewControllerClass' method to disable it for a viewController.

**Comment by diegothucao** [comment]
It seems does not work

**Comment by diegothucao** [comment]
In Swift, there is no method to get Class, Am I right ?

**Comment by hackiftekhar** [comment]
You should pass class name directly. For example your class name is 'Person' then you should pass 'Person' in the method.

**Comment by raj-android-ios** [comment]
there is no such method like 'disableInViewControllerClass'

**Comment by rjcristy** [comment]
IQKeyboardManager.sharedManager().disabledToolbarClasses = [QuantityPickerDialog.self] //of type UIViewController

**Comment by hackiftekhar** [comment]
Thanks @rjcristy. @raj-android-iOS, they are replaced by properties so now you have to use them like mentioned by @rjcristy.

**Comment by haydenholligan** [comment]
I believe you have to do `IQKeyboardManager.shared().disabledToolbarClasses.add(YourViewController.self)`, as `disabledToolbarClasses` is read-only.

**Comment by bibekdari** [comment]
disabledDistanceHandlingClasses
disabledDistanceHandlingClasses
disabledToolbarClasses
 disabledTouchResignedClasses

**Comment by paresh-navadiya** [comment]
Need to use **disabledDistanceHandlingClasses**. For example 
        IQKeyboardManager.sharedManager().disabledDistanceHandlingClasses.append(YourViewController.self)

**Comment by Henry-** [comment]
Swift 4:
IQKeyboardManager.shared.disabledDistanceHandlingClasses.append(YourViewController.self)

**Comment by surender-initcoders** [comment]
> ```
> IQKeyboardManager.sharedManager().disabledToolbarClasses = [QuantityPickerDialog.self] //of type UIViewController
> ```
@rjcristy  thank you sooo much .... 
actually i am working in chat controller using jsqmessageviewcontroller, and stuck to found the issue of status bar which is transparent when keyboard mic tap  

thank you so much.

**Comment by yudhishtadhayalan** [comment]
> IQKeyboardManager.shared().isEnabled = false
> IQKeyboardManager.shared().isEnableAutoToolbar = false

Thanks Bro...

**Comment by w-i-n-s** [comment]
Nothing works =(
what I did try:
- disabledToolbarClasses etc.
- willAppear -> enable=false, willDissapear -> enable = true. 
    + With or without toolbar

**Comment by AdamNasser2** [comment]
**For Swift 4 and IQKeyboardManager Version 5.00: ** 
_App Delegate.swift:_
 func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        // Override point for customization after application launch.
       IQKeyboardManager.shared().isEnabled = false
       IQKeyboardManager.shared().disabledToolbarClasses.add(CreateController.self)
      IQKeyboardManager.shared().enabledDistanceHandlingClasses.add(SignUpFormController.self)
  }

**Comment by srikanthkumarmailid07** [comment]
Write this code in a particular controller inside of  view did load method
                    
     IQKeyboardManager.shared.disabledToolbarClasses = [ForgotConfirmationvc.self]
     IQKeyboardManager.shared.enable = false
    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(true)
        IQKeyboardManager.shared.enable = true
    }

**Comment by netgfx** [comment]
nothing works... the input keeps scrolling up, even though there is enough space for the keyboard, and I have placed everything mentioned here to disable it.

**Comment by maxim-sargarovschi** [comment]
I added in my VC didLoad method 
`IQKeyboardManager.shared.enable = false`
and in willDesappear
`IQKeyboardManager.shared.enable = false`
and in appDelegate 
`IQKeyboardManager.shared.disabledDistanceHandlingClasses = [myVC.self]`

and in this vc the view still scroll up when keyboard is showing ...

**Comment by Adakhan** [comment]
IQKeyboardManager.shared.disabledTouchResignedClasses = [YourViewController.self]

**Comment by realxnesia** [comment]
`
in your **AppDelegate.swift**
```
  Import IQKeyboardManager 
  func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
          // Override point for customization after application launch.
          IQKeyboardManager.shared().isEnabled = true
          return true
  }
```
  
Then setup like this in your **TargetViewController.swift**
```
    Import IQKeyboardManager 
    override func viewDidLoad() {
                  IQKeyboardManager.shared().isEnabled = false
                  IQKeyboardManager.shared().isEnableAutoToolbar = false
    }
    override func viewWillDisappear(_ animated: Bool) {
            super.viewWillDisappear(animated)
            IQKeyboardManager.shared().isEnabled = true
            IQKeyboardManager.shared().isEnableAutoToolbar = true
    }
```

**Build and Run!!**
### Already tested in 2022

`
