### ISSUE TITLE
Swift iOS 8.4 - How to show Popover when click in UITextView with IQKeyboardManager 

### ISSUE THREAD

**Issue by diegothucao** [hackiftekhar/IQKeyboardManager#253]
Dear Friends,
I want to show popover or customized Warring message when I click on a specific UITextView, I used:

-(BOOL)textFieldShouldBeginEditing:(UITextField *)textField
{
    if (textField == customWorkTextField)
    {
        if (textField.isAskingCanBecomeFirstResponder == NO)
        {
            //Do your work on tapping textField.
            [[[UIAlertView alloc] initWithTitle:@"IQKeyboardManager" message:@"Do your custom work here" delegate:nil cancelButtonTitle:@"OK" otherButtonTitles:nil, nil] show];
        }

        return NO;
    }
    else    return YES;
}

How to do in in Swift and iOS 8.4 ?

Thanks,

Thu

**Comment by hackiftekhar** [comment]
Put conditions just like sample code doing, and show popover where alert view is showing ( //Do your work on tapping textField.).

**Comment by diegothucao** [comment]
textFieldShouldBeginEditing is not existed in Swift

**Comment by hackiftekhar** [comment]
It exists, do you have any reference to point-out that textFieldShouldBeginEditing is not exist in swift?

func textFieldShouldBeginEditing(state: UITextField) -> Bool {
 return false
}

http://stackoverflow.com/questions/11775110/function-textfieldshouldbeginediting-is-not-called

**Comment by hardikdevios** [comment]
@diegothucao you are approaching a Wrong delegate You are using ```UITextView``` and tried to call the delegation of ```UITextField``` but the correct method is,
#### textViewShouldBeginEditing(_:)####
https://developer.apple.com/library/ios/documentation/UIKit/Reference/UITextViewDelegate_Protocol/#//apple_ref/occ/intfm/UITextViewDelegate/textViewShouldBeginEditing:

**Comment by hackiftekhar** [comment]
@hardikdevios You are right! @diegothucao you are using wrong delegate method.

**Comment by diegothucao** [comment]
Thanks for you helps.
I have done with it.

Thank
