### ISSUE TITLE
crashed use UIAlertView 

### ISSUE THREAD

**Issue by XCGit** [hackiftekhar/IQKeyboardManager#254]
## It will crash sometimes on   UIAlertView , which use UIAlertViewStylePlainTextInput style.

crashed   at  IQKeyboardManager.m 

line 326:  [lastScrollView setContentOffset:startingContentOffset animated:YES];

**Comment by hackiftekhar** [comment]
So you mean sometimes it works perfect and sometime it crashed. Right?

**Comment by XCGit** [comment]
yes

**Comment by hackiftekhar** [comment]
Then how can I debug it?

**Comment by hackiftekhar** [comment]
It seems when any other textField is first responder and then try to show UIAlertView with UIAlertViewSTylePlainTextInput then it crashes. If this was the case then you should resign old textField first before showing UIAlertView. Let me know if I'm right.

**Comment by hackiftekhar** [comment]
This issue is not related to library
https://openradar.appspot.com/20615507
