### ISSUE TITLE
Table view Issue in Swift.

### ISSUE THREAD

**Issue by pr0gramm3r8hai** [hackiftekhar/IQKeyboardManager#256]
Hello, 
I am using this manager for table view which contains UITextFields in cell, When i tapped the last text field of cell, it lifts view, thats fine, but on resigning first responder the table view does not regains its original position! Please Replay ASAP ! Hoping to get solution! Thnks in Advance! 
![screen shot 2015-07-30 at 6 19 32 pm](https://cloud.githubusercontent.com/assets/12591229/8983162/9f656bd0-36e7-11e5-8c40-2cfdfa098bd8.png)
![screen shot 2015-07-30 at 6 19 49 pm](https://cloud.githubusercontent.com/assets/12591229/8983168/a5514c4e-36e7-11e5-99e7-6960d18de70f.png)

**Comment by hackiftekhar** [comment]
Could you please share demo project.

**Comment by pr0gramm3r8hai** [comment]
yes! Btw i am just using your class that implements Tableview!

**Comment by pr0gramm3r8hai** [comment]
https://github.com/pr0gramm3r8hai/TableViewWithIQKeyboardManager

**Comment by uzegonemad** [comment]
Not sure if you're still having this issue or not but I was having the same issue on Obj-C.

I set

```objc
[[IQKeyboardManager sharedManager] setShouldRestoreScrollViewContentOffset:YES];
```
and it fixed my issue.

It would be something like this in Swift:
```swift
IQKeyboardManager.sharedManager().shouldRestoreScrollViewContentOffset = true
```

**Comment by serg94** [comment]
+1, please fix, can't use with table view.
in scroll view after appearing keyboard it changes scroll view content size.
