### ISSUE TITLE
How I can keep from hiding NON-default navigation bar?

### ISSUE THREAD

**Issue by spensko** [hackiftekhar/IQKeyboardManager#257]
I have UIViewController with some custom view as navigation bar on it and a tableview with programmatically created textfields in cells. 

* superview
  * tableview (0, 0, width, height) // Y is 0 because I have custom blur on navbar
  * uiview (0, 0, width, 65) // custom navbar on the top of hierarchy

Then some textfield is become active my custom navbar is hiding. Can't figure out how I can prevent it.
Is it possible?

**Comment by hackiftekhar** [comment]
If you have textFiels on tableView then I think it should work just fine. if it's not working then please share demo.

**Comment by hackiftekhar** [comment]
Any updates on this?

**Comment by hackiftekhar** [comment]
Do you have any updated regarding any demo app or any more detailed information?

**Comment by spensko** [comment]
Sorry, was on long holidays. Can't reproduce in clean demo project, so Im closing issue. Thanks!
