### ISSUE TITLE
Crashes at Start: Xcode Claims the Version Pulled from Cocoapods is 1.0.0

### ISSUE THREAD

**Issue by drake1138** [hackiftekhar/IQKeyboardManager#258]
I get this error message when my app attempts to start on my phone:

dyld: Library not loaded: @rpath/IQKeyboardManager.framework/IQKeyboardManager
  Referenced from: /private/var/mobile/Containers/Bundle/Application/48541CD5-9631-44F8-A625-F81F120F386A/NAS Repair.app/NAS Repair
  Reason: Incompatible library version: NAS Repair requires version 3.0.0 or later, but IQKeyboardManager provides version 1.0.0

Strangely, the version the terminal claims to have downloaded is 3.2.4, and the build settings in the pods project say it is 3.2.4.

Here is my podfile to show that I am requesting the correct version. (I even attempted forcing the version to be 3.2.4, but it made no difference)

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.4'
pod 'GoogleMaps'
pod 'IQKeyboardManager'
use_frameworks!
pod 'UzysAssetsPickerController'
xcodeproj '/Users/DSR/Desktop/NAS Repair/NAS Repair.xcodeproj'

This is an extremely frustrating issue I have been having, and any help would be appreciated.

**Comment by hackiftekhar** [comment]
How about removing use_frameworks! option and try again?

**Comment by drake1138** [comment]
When i remove "use_frameworks!" i get this error when building the project.

ld: library not found for -lIQKeyboardManager
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I found out that if i go to the build settings of the pod project IQKeyboardManager target, you can set the compatibility version to be 1, and it will run. I am just wondering if it actually has the correct version, and why it says it is version 1 when running, yet everything else says it is version 3.2.4.

**Comment by hackiftekhar** [comment]
Thanks @drake1138  for sharing this patch for the problem

**Comment by mplorentz** [comment]
I am receiving the same error but @drake1138's fix doesn't fix it for me. It only happens when I try to run the app on my iPhone 5S running iOS 8.4.

**Comment by mplorentz** [comment]
I fixed my issue by deleting my project and re-checking it out from its repository. Maybe there was something in my xcuserdata that was causing it.

**Comment by mplorentz** [comment]
This issue came up again for me and I spent some more time investigating it. Apparently it is an issue with CocoaPods 0.38.2.

The fix is to clean the build folder (Command-Option-Shift-K). You can find more info [here](http://stackoverflow.com/questions/31750603/dyld-library-not-loaded-app-requires-afnetworking-2-0-0-but-provides-version-1).

**Comment by hackiftekhar** [comment]
Thank for sharing the workaround. Thanks again.
