### ISSUE TITLE
Update for Swift 2.0

### ISSUE THREAD

**Issue by SurajSundar** [hackiftekhar/IQKeyboardManager#259]
The current library does not work with Swift 2.0. Please try to provide us with an update of the library for Swift 2.0.

**Comment by hardikdevios** [comment]
@SurajSundar Swift 2.0 is a Beta version and has few issues with the SDK , i suppose if you are developing an App which will be totally going to be the support from swift 2.0 , than you must wait for the primary/ultimate Relese for the Xocde 7 , till than you can user the Bridging header of this lib which i dont think have much issue with that.

**Comment by hackiftekhar** [comment]
Now Swift2.0 library is available in Swift2 branch.

**Comment by SurajSundar** [comment]
How do I add the library to my project in case of Swift?

**Comment by hackiftekhar** [comment]
Could you pleaee confirm you are compiling this in Xcode7?

**Comment by SurajSundar** [comment]
I tried to compile the code using Xcode 7 beta 4. I'm currently downloading the beta 5. I will try with that one too and update you

**Comment by hackiftekhar** [comment]
Apple is constantly updating Swift syntax. That's why I was waiting for Xcode7 official release.

**Comment by hackiftekhar** [comment]
It is fixed now on Swift2 branch. Closing this issue because there is now support for Swift 2.0 on swift2 branch.
