### ISSUE TITLE
No need to do any toolBarButtonInvocation when shouldResignOnTouchOutside=YES

### ISSUE THREAD

**Issue by scorpiohjx** [hackiftekhar/IQKeyboardManager#262]
I think there's no need to do any toolBarButtonInvocation when shouldResignOnTouchOutside is set by YES, including doneAction, cancelAction, previousAction, nextAction, leftAction, rightAction. The reason is simple, I just touch that outside the keyboard, not those UIBarButtonItems or IQBarButtonItems. So, just resign the firstResponder (textField/textView), without do invocation.

Here's my situation where cause the problem:
1.in AppDelegate.m: [IQKeyboardManager sharedManager].shouldResignOnTouchOutside = YES;
2.in ViewController.m: [self.textField setCustomDoneTarget:self action:@selector(doneAction:)];
3.doneAction: simply show a UIAlertView with some message, then resign self.textField.
4.I run the app, and touch that outside the keyboard, then the UIAlertView shows which should not show.

Temporary Solution:
1.in IQKeyboardManager.m, line 1385, add - (void)resignFirstResponderWithoutAnyInvocation:{...}, copying from - (void)resignFirstResponder:{...} but comment the else if {...}.
2.in IQKeyboardManager.m, line 1337, replace [self resignFirstResponder] with [self resignFirstResponderWithoutAnyInvocation].

That works. However, I don't known whether it's completely correct or not. Hope you'll consider adding this enhancement.

**Comment by hackiftekhar** [comment]
When a keyboard resign by touching outside then yes, I should not invoke doneAction. Will take a look and will find the cause of this issue. Thanks for your bug report.

**Comment by scorpiohjx** [comment]
thanks!
