### ISSUE TITLE
IQLayoutGuideConstraint not showing up in "Outlets"

### ISSUE THREAD

**Issue by bobintornado** [hackiftekhar/IQKeyboardManager#268]
[Beginner Question]

I am trying to follow screenshot and "map TopLayoutGuide/BottomLayoutGuide constraint with IQLayoutGuideConstraint", but I am not exactly sure how to map it, as it seems my view controller doesn't have the IQLayoutGuideConstraint outlet. 

![screenshot 2015-08-20 21 55 16](https://cloud.githubusercontent.com/assets/3308031/9385104/1701249a-4787-11e5-98f5-148b6bcae39b.png)

I try manually insert the IQLayoutGuideConstraint into my view controller class but it doesn't seem working. 

Could anyone write a more detailed screenshot walkthrough? Thanks

**Comment by hackiftekhar** [comment]
Could you please confirm you have added 'IQUIViewController+Additions.h' in project?

**Comment by bobintornado** [comment]
@hackiftekhar Gotcha. 

I was using an outdated swift version of IQKeyboardManager, and I guess that version didn't include the IQLayoutGuideConstraint yet. 

I tried switching to the Swift2 version and realise that version is not for Xcode 6.X, and I am not ready to make the Xcode version jump for my production app yet. 

So I fall back to the objective-c version and bridge it back swift 1.2, and it works. 

Thanks for info!

**Comment by hackiftekhar** [comment]
FYI, the current swift version have the IQLayoutGuideConstrainy feature with swift1.2 on master branch. And swift2.0 version on Swift2 beanch.

**Comment by bobintornado** [comment]
@hackiftekhar I see.

Those two branches all have the same folder name "IQKeybordManagerSwift", and I think I must have confused myself.

Maybe on master branch the "IQKeybordManagerSwift" should be renamed to "IQKeybordManagerSwift12" and on the Swift2 branch to be renamed to "IQKeybordManagerSwift2". 

 Just my two cents.

**Comment by hackiftekhar** [comment]
As per me, IQKeyboardManagerSwift on master will always contain the official latest version of swift language. So no need to rename it and on Swift2 branch, there may be a chance to rename branch but not the IQKeyboardManagerSwift folder name because Swift2 branch will be merged in master in near future.

**Comment by fannisuyuti** [comment]
Hi, i'm using swift 2 and IQKeyboardManager 4.0.1 installed from cocoapods, the `IQUIViewController+Additions.swift` already included, but i can't see the outlet. Am i missing something?

**Comment by hackiftekhar** [comment]
Of you don't see outlets then as a tweak you can also set this property programmatically.
