### ISSUE TITLE
Rotating to landscape and back with keyboard open doesn't correct view

### ISSUE THREAD

**Issue by Flyte27** [hackiftekhar/IQKeyboardManager#269]
I've found that when the keyboard is up, and the user rotates the screen to landscape and back, then hits done on the keyboard, the view gets stuck dragged downwards. This only seems to happen when the view was initially pushed upwards so the user could see the textfield.

![img_0814](https://cloud.githubusercontent.com/assets/2347600/9393448/fd0aa3cc-474f-11e5-9fc4-c98632deb24e.jpg)

![img_0815](https://cloud.githubusercontent.com/assets/2347600/9393452/045d2802-4750-11e5-8607-2ee633d104d1.jpg)

As can be seen above, the tableview which was pushed up doesn't properly resize when coming out of the keyboard manager.

**Comment by hackiftekhar** [comment]
Could you please share a demo code to debug it?

**Comment by Flyte27** [comment]
Working on recreating it with a smaller project, though no luck so far. Seems to be rotating from landscape to portrait mode forces the current view to get pushed downwards.

**Comment by Flyte27** [comment]
Got it. This happens when the project is inside a TabBarController. Ill upload the small test project I wrote to a repo

**Comment by hackiftekhar** [comment]
Thanks :) I'll take a look

**Comment by hackiftekhar** [comment]
I checked the demo project and confirmed that it's a bug. I'll try to fix it when get some time. Thanks for the demo project and the bug report.

**Comment by hackiftekhar** [comment]
ohh man, I found that you your demo project has issues with UILayoutGuide. You should read instructions described in `Working with TopLayoutGuide and BottomLayoutGuide:-` section in readme file. Also you have added two BottomLayoutGuide constraints with UITextField and that's second issue. You should remove any one BottomLayoutGuide and assign the other one to IQTopLayoutGuide. Probably doing this should work for you.
