### ISSUE TITLE
"shouldHideTitle" property does not work when UITextField in two different view

### ISSUE THREAD

**Issue by pljhonglu** [hackiftekhar/IQKeyboardManager#272]
![_2015-08-25_ 4_49_08](https://cloud.githubusercontent.com/assets/2472557/9462714/2db4fede-4b4a-11e5-8dc0-dc43785bddfa.png)

The second UITextField set shouldHideTitle=YES, but it does not work.

**Comment by pljhonglu** [comment]
The problem still exists, if the second UITextField set shouldHideTitle = YES, the first UITextField set shouldHideTitle = NO, if I'll click the second UITextField then click on the first one, well, the first one title will not be displayed.

Or, if the first one is the UITextField、second is UITextView, The UITextView can not response "placeholder" methed, so the title of the UITextView will be displayed as UITextField's title.

I think it is better to set inputAccessoryView for every UITextField or UITextView,so the  above problem would not exist ~

I solved this issue by a commit in [pljhonglu/IQKeyboardManager](https://github.com/pljhonglu/IQKeyboardManager/commit/18744bda79d954bac4a55aa339ce1ec31c884a35)

**Comment by hackiftekhar** [comment]
I'll take a look into that

**Comment by hackiftekhar** [comment]
@pljhonglu Thanks for pointing-out UITextView placeholder condition.

 I've modified the library to handle UITextView title too. Also I put some more conditions to update UIToolbar title.

**Comment by pljhonglu** [comment]
Unfortunately, The first problem still exists. If two UITextField in different view, the first UITextField(TF_1) set shouldHideTitle = NO, the second UITextField(TF_2) set shouldHideTitle = YES, if I click TF_2 and then click TF_1, well, TF_1's title will be invisible, because of the toolbar do not have IQTitleBarButtonItem.

![_2015-08-27_ 4_04_16](https://cloud.githubusercontent.com/assets/2472557/9516223/c4711692-4cd9-11e5-8759-501f71cedcc2.png)

**Comment by hackiftekhar** [comment]
I found root cause of the issue as you said 'keyboad toolbar has no IQTitleBarButtonItem'. This was because I was optionally creating IQTitleBarButtonItem by checking 'shouldHideTitle' property in IQUIView+IQKeyboardToolbar. From now, IQTitleBarButtonItem will always be added in IQToolbar items, and we will play with it's title using 'shouldHideTitle' boolean.

Let me know if you still get issues.

**Comment by pljhonglu** [comment]
No more issues，thank you~ :+1:
