### ISSUE TITLE
UITableView - UITextField/UITextView in cell rotation issue

### ISSUE THREAD

**Issue by fahlout** [hackiftekhar/IQKeyboardManager#273]
In my app I have a table view that contains cells with either a UITextField or a UITextView. The keyboard manager mostly works as expected. Sometimes it doesn't go to the next/previous textfield or textview even though the arrows light up. That is a small issue that I hope can be resolved at some point. The bigger issue though is when i have a textview or textfield selected and rotate the device the textfield/textview looses its selection and will no longer be selected after rotation. On top of that the toolbar of the keyboard manager then starts to fly across the screen whenever the device is rotated again. The toolbar that "flies" across the screen seems to be black. I am using Swift 2.0, but I am using the Objective C version of the keyboard manager as I feel like the Swift version still has more problems. Thanks for your time!

**Comment by hackiftekhar** [comment]
Could you please share demo app?

**Comment by fahlout** [comment]
I'll have a sample project ready for you shortly. What I determined is that on just textfields in a uiview, so not using table views, it works fine and does not loose the selected one. The toolbar on top of the keyboard only turns black on rotation on a device running iOS 9, on my device running iOS 8 it does not turn black. I am also not experiencing the bar "flying" across the screen on my iOS 8 device (both iPads), but it still looses the selection, which is the main issue I wanted to bring up. Will post a link to the project in a few minutes or so

**Comment by fahlout** [comment]
Seems like it's something within my project that is causing it to mess up. Made a sample project and it doesn't loose selection on rotation. Will investigate more to see why it is messing up in my actual app.

**Comment by hackiftekhar** [comment]
May be, but I'm not sure actually. There may be a chance to cause by library, so please be sure and try on the demo first.

**Comment by fahlout** [comment]
The issue of the keyboard disappearing had to do with part of my code in my custom tabbar controller. I apologize for that. The issue of the toolbar above the keyboard turning black while rotating is still present on iOS 9.

**Comment by hackiftekhar** [comment]
Thencould you please share tge keyboard turning black issue demo?
