### ISSUE TITLE
Crash when running on device with Swift 1.2, Xcode 6.4

### ISSUE THREAD

**Issue by gluecode** [hackiftekhar/IQKeyboardManager#276]
Using Version 6.4 (6E35b), Swift 1.2, CocoaPods and running on an iOS9 Beta 5 iPhone 6 results in a crash with the following debug info:

dyld: Library not loaded: @rpath/IQKeyboardManager.framework/IQKeyboardManager
  Referenced from: /var/mobile/Containers/Bundle/Application/1657E9F1-46AF-4173-A96B-C6808A24CB70/myapp.app/myapp
  Reason: Incompatible library version: myapp requires version 3.0.0 or later, but IQKeyboardManager provides version 1.0.0
(lldb) 

---

    dyld`dyld_fatal_error:
    ->  0x1200a9088 <+0>: brk    #0x3

---

    dyld`_dyld_start:
        0x1200a9000 <+0>:   mov    x28, sp
        0x1200a9004 <+4>:   and    sp, x28, #0xfffffffffffffff0
        0x1200a9008 <+8>:   movz   x0, #0
        0x1200a900c <+12>:  movz   x1, #0
        0x1200a9010 <+16>:  stp    x1, x0, [sp, #-16]!
        0x1200a9014 <+20>:  mov    x29, sp
        0x1200a9018 <+24>:  sub    sp, sp, #16
        0x1200a901c <+28>:  ldr    x0, [x28]
        0x1200a9020 <+32>:  ldr    x1, [x28, #8]
        0x1200a9024 <+36>:  add    x2, x28, #16
        0x1200a9028 <+40>:  adrp   x4, -1
        0x1200a902c <+44>:  add    x4, x4, #0
        0x1200a9030 <+48>:  adrp   x3, 44
        0x1200a9034 <+52>:  ldr    x3, [x3, #3256]
        0x1200a9038 <+56>:  sub    x3, x4, x3
        0x1200a903c <+60>:  mov    x5, sp
        0x1200a9040 <+64>:  bl     0x1200a908c               ; dyldbootstrap::start(macho_header const*, int, char const**, long, macho_header const*, unsigned long*)
    ->  0x1200a9044 <+68>:  mov    x16, x0
        0x1200a9048 <+72>:  ldr    x1, [sp]
        0x1200a904c <+76>:  cmp    x1, #0
        0x1200a9050 <+80>:  b.ne   0x1200a905c               ; <+92>
        0x1200a9054 <+84>:  add    sp, x28, #8
        0x1200a9058 <+88>:  br     x16
        0x1200a905c <+92>:  mov    x30, x1
        0x1200a9060 <+96>:  ldr    x0, [x28, #8]
        0x1200a9064 <+100>: add    x1, x28, #16
        0x1200a9068 <+104>: add    x2, x1, x0, lsl #3
        0x1200a906c <+108>: add    x2, x2, #8
        0x1200a9070 <+112>: mov    x3, x2
        0x1200a9074 <+116>: ldr    x4, [x3]
        0x1200a9078 <+120>: add    x3, x3, #8
        0x1200a907c <+124>: cmp    x4, #0
        0x1200a9080 <+128>: b.ne   0x1200a9074               ; <+116>
        0x1200a9084 <+132>: br     x16

**Comment by gluecode** [comment]
The following solution actually worked for me:

http://stackoverflow.com/questions/31750603/dyld-library-not-loaded-app-requires-afnetworking-2-0-0-but-provides-version-1

In Xcode 6.4, press Option key and select 'Product' > 'Clean Build Folder' from menu.

**Comment by bobintornado** [comment]
What about running iOS9 Beta 5 iPhone 6 on Xcode 7 Beta?

**Comment by gluecode** [comment]
I am not sure that you are aware of this but Xcode 7 Beta only compiles Swift 2.

**Comment by bobintornado** [comment]
Errr, frankly I didn't know that. 

I am just thinking since you are testing  iOS9 Beta 5 why not just use Xcode 7 Beta with Swift2 version of IQKeyboardManager....... #JustWondering

**Comment by gluecode** [comment]
Ah I see. The transition from Swift 1.2 to 2 with Xcode has been quite a frustrating experience. Good luck on your apps too. Thanks for your notes.

**Comment by hackiftekhar** [comment]
duplicate of #258
