### ISSUE TITLE
Can i recommend something ?

### ISSUE THREAD

**Issue by hardikdevios** [hackiftekhar/IQKeyboardManager#279]
For this Beautiful library can we Add this on Top of ReadMe ?

This Two links integration
https://travis-ci.org/
https://coveralls.io/

i hope you are already known with this and how much it helps for this Lib productivity for future, just try it :) 
thanks mate

**Comment by hackiftekhar** [comment]
Sure! Will do.

**Comment by hackiftekhar** [comment]
Could you please do this:-
- Fork Repo.
- Update ReadMe
- Create a PR.

**Comment by hardikdevios** [comment]
@hackiftekhar sure will do

**Comment by hackiftekhar** [comment]
Do you have any updates regarding pull-request?

**Comment by hackiftekhar** [comment]
Added https://travis-ci.org/
