### ISSUE TITLE
IQKeyboardManagerSwift 3.3.0 hide UINavigationBar when keyboardManager slides up.

### ISSUE THREAD

**Issue by huynhphan89** [hackiftekhar/IQKeyboardManager#281]

**Comment by hackiftekhar** [comment]
Could you please let me know how to reproduce above issue or please share some more details or demo.

**Comment by huynhphan89** [comment]
It happens all the time, so very easy to reproduce.
This is a demo: https://drive.google.com/file/d/0B_xGvhbyxyYUTjFCeEx4aFlaSms/view?usp=sharing

p/s: It works well on v3.2.4

**Comment by hackiftekhar** [comment]
I can see it's working well on V3.2.4 and not working on v3.3.0. I need to investigate the root cause of issue.
