### ISSUE TITLE
NavigationBar getting hidden

### ISSUE THREAD

**Issue by sree127** [hackiftekhar/IQKeyboardManager#282]
Hi Iftekhar,

First let me take a moment to thank you for the time and hard work you have put-up to give us this awesome library.

Coming to the question, how would I not hide the Navbar when the keyboard appears? As mentioned in the Readme I tried changing the UIViewController's view to UIScrollView and also tried doing the same using loadView. But still the NavBar gets hidden when the keyboard comes. 

Please find attached the screenshots : 

![screen shot 2015-09-02 at 11 40 11 am](https://cloud.githubusercontent.com/assets/3157263/9624150/710d09d8-5167-11e5-9585-dd0cbb329e8e.png)

![ios simulator screen shot 02-sep-2015 11 40 56 am](https://cloud.githubusercontent.com/assets/3157263/9624160/8091bbf6-5167-11e5-87bd-fb653fba2ec2.png)

**Comment by hackiftekhar** [comment]
could you please check demo app and confirm if it's working fine. If demo app is working correct and you are not getting same results then could you please share demo.

**Comment by hackiftekhar** [comment]
Is it something related to #281?

**Comment by hackiftekhar** [comment]
Do you have any updates?
