### ISSUE TITLE
Need scroll view only scroll, don't want table view scroll

### ISSUE THREAD

**Issue by mathiarasan24** [hackiftekhar/IQKeyboardManager#285]
Hi @hackiftekhar ,

You did great work!!
Here my need, In this project I need only change scroll view offset, don't want table view.
I am already disable table view scroll but it's still scroll.
In table cell have text fields.

My design like:
self.view
bgscrollview
tableview
customtablecell
cell.textfeld

Rules in this view:
scroll view only scroll.
I am disabled Table view scroll.

Hope it's understandable!!

**Comment by hackiftekhar** [comment]
library logic is to find nearest scrollView from textField. and in your case it's tableView, that is why library chooses tableView to scroll. I need to think something for your case.

**Comment by broncha** [comment]
+1
I have a container view, where a table view is embedded. The scroll in the table view is disabled. But when keyboard is displayed, it scrolls the tableview anyway

**Comment by hackiftekhar** [comment]
Added support to follow `scrollView.scrollEnabled` property to check if scrollView can scroll or not. Probably 34634225fdba162b56cdd3b519fc7d691e22fd2c commit fixed this issue.
