### ISSUE TITLE
Changing the view scrolling when uitextfield becomes firstresponder

### ISSUE THREAD

**Issue by tbaranes** [hackiftekhar/IQKeyboardManager#286]
Hi,

I have a small question: is there any way to change the view scrolling when the keyboard is opening?
In my case, my `UITextField` is embedded in an `UIScrollView` which is embedded itself by the main view. When the `UITextField` becomes first responder, I'd like to have the main view scroll, and not just the scrollview.

Is there to do that? I didn't find any answers on the related issues / readme.

**Comment by hackiftekhar** [comment]
There is no way to ignore UIScrollView for now, because scrollView functionality is added as advantage and on most of the scenarios, changing scrollView contentOffset is better option than scrolling whole view upward.

**Comment by tbaranes** [comment]
Oh, I miss your answer. Thanks for it. I got a solution working well by using `considerToolbarPreviousNextInViewClass`. 

Thanks!
