### ISSUE TITLE
Added dynamc cell in table view Added with incorrect values

### ISSUE THREAD

**Issue by mathiarasan24** [hackiftekhar/IQKeyboardManager#287]
Hi @hackiftekhar ,
If I disable IQKeyboardmanager for a view this dynamic cell load work's fine. Here my code in ```-(void)textFieldDidBeginEditing:(UITextField *)textField```

```Objective-C
int arraycount = (int)pollAnsArray.count;
    if (arraycount - 1 == textField.tag)
    {
        for (int i = 0 ; i < arraycount - 1; i++)
        {
            NSString *temppolansStr = [NSString stringWithFormat:@"%@ %d",[pollAnsArray objectAtIndex:i], i + 1];

            if ([temppolansStr isEqualToString:[NSString stringWithFormat:@"Answer %d", i+ 1]] && arraycount - 1 != i)
                return;
            else if (arraycount - 2 == i)
            {
                [pollAnsArray insertObject:@"Answer" atIndex:arraycount];
                NSIndexPath *indexPath = [NSIndexPath indexPathForRow:arraycount inSection:0];
                [pollansTableView insertRowsAtIndexPaths:@[indexPath] withRowAnimation:UITableViewRowAnimationAutomatic];
                
                tableviewHeightConstraint.constant = pollansTableView.contentSize.height + 40;
            }
        }
    }
```

and in ```cellForRowAtIndexPath``` I am check if that pollAnsArray have other than placeholder value

```Objective-C
NSString *tempTablecellStr = [NSString stringWithFormat:@"%@ %d",[pollAnsArray objectAtIndex:indexPath.row], (int)indexPath.row + 1];
    NSString *tempplaceholderStr = [NSString stringWithFormat:@"Answer %d", (int)indexPath.row + 1];
    
    if (![tempTablecellStr isEqualToString:tempplaceholderStr])
        cell.Testfiled.text = [pollAnsArray objectAtIndex:indexPath.row];
    else
        cell.Testfiled.placeholder = tempplaceholderStr;
```

Without IQKeyboardManager this code will work. If I enable IQKeyboardManager in this view new index placeholder value change to previous pollansArray value. :(

If this code wrong suggest me for good one. I don't know what's wrong with this code when I enable IQKeyboardManager in this view.

**Comment by hackiftekhar** [comment]
You should correct your app logic, BTW, I'm unable to understand what you want to achieve but as a programmer I think your if else conditions should be something like this:-

if (![tempTablecellStr isEqualToString:tempplaceholderStr])
{
        cell.Testfiled.text = [pollAnsArray objectAtIndex:indexPath.row];
        cell.Testfiled.placeholder = tempplaceholderStr;
}

**Comment by mathiarasan24** [comment]
Hello @hackiftekhar ,
I want to create a dynamic cell creation.
In this method ```-(void)textFieldDidBeginEditing:(UITextField *)textField``` Check previous cell should have any value (new values stored in a array using textFieldDidendEditing method) . If all previous cell have a value and then I check it's last cell or not and then add a new cell in table view.

```Objective-C
int arraycount = (int)pollAnsArray.count;
    if (arraycount - 1 == textField.tag)
    {
        for (int i = 0 ; i < arraycount - 1; i++)
        {
            NSString *temppolansStr = [NSString stringWithFormat:@"%@ %d",[pollAnsArray objectAtIndex:i], i + 1];

            if ([temppolansStr isEqualToString:[NSString stringWithFormat:@"Answer %d", i+ 1]] && arraycount - 1 != i)
                return;
            else if (arraycount - 2 == i)
            {
                [pollAnsArray insertObject:@"Answer" atIndex:arraycount];
                NSIndexPath *indexPath = [NSIndexPath indexPathForRow:arraycount inSection:0];
                [pollansTableView insertRowsAtIndexPaths:@[indexPath] withRowAnimation:UITableViewRowAnimationAutomatic];
                
                tableviewHeightConstraint.constant = pollansTableView.contentSize.height + 40;
            }
        }
    }
```

If I create a new text field then it should have a place holder. So I am checking in ``cellForRowAtIndexPath`` with this code

if (![tempTablecellStr isEqualToString:tempplaceholderStr])
        cell.Testfiled.text = [pollAnsArray objectAtIndex:indexPath.row];
    else
        cell.Testfiled.placeholder = tempplaceholderStr;

Still you can't understand this I will update this viewController code. :)

**Comment by hackiftekhar** [comment]
Sorry but, I'm not sure about what you are asking for. If you could attach a demo project and the brief information about the bug, then it would be great.

**Comment by mathiarasan24** [comment]
I am drop a demo project in you gmail account kindly check that.

**Comment by hackiftekhar** [comment]
Here is the demo project link:-
https://www.dropbox.com/s/shm5vladvgn2tbj/IQKeyboardManagerIssue287.zip?dl=0

**Comment by mathiarasan24** [comment]
Do you change anything in that code?
I didn't find any changes and it's still have issues. :(

**Comment by hackiftekhar** [comment]
Nope, I have to investigate. Thanks for the reminder.

**Comment by mathiarasan24** [comment]
Hi, (Reminder) check this [#285](https://github.com/hackiftekhar/IQKeyboardManager/issues/285) issues too with that demo project and Thankss

**Comment by hackiftekhar** [comment]
I checked this code, but still unable to understand what you was trying to achieve?

**Comment by hackiftekhar** [comment]
Any updates? because I'm not able to understand what you are trying to achieve.

**Comment by mathiarasan24** [comment]
Hi @hackiftekhar ,

I did my self move ``textField`` up and down with dynamic cell creation and I forgot, I raised question for that. Just now I saw and make a video for that can you check that video and you will find the issue.

[IQKeyboardDynamicTableCellCreationIssue.mov.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/222073/IQKeyboardDynamicTableCellCreationIssue.mov.zip)

And this what I want and I complete without IQKeyboard.

[DynamicCellCreationWithOutIQKeyboardManager.mov.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/222079/DynamicCellCreationWithOutIQKeyboardManager.mov.zip)

Regard
