### ISSUE TITLE
Issue while dismissing Keyboard using IQKeyboardManager resignFirstResponder

### ISSUE THREAD

**Issue by SyedIsmailAhamed** [hackiftekhar/IQKeyboardManager#290]
I have two test fields, on tap of second textfield am dismissing keyboard in textFieldDidBeginEditing something like this, but its not dismissing the keyboard.
- (void)textFieldDidBeginEditing:(UITextField *)textField 
{
 if (textField==textFieldOne)
{
  [[IQKeyboardManager sharedManager]resignFirstResponder]
}

}

Regards,
Syed Ismail Ahamed

**Comment by hackiftekhar** [comment]
I can't see any differences between your if condition and else if condition. That's a programming mistake.

**Comment by SyedIsmailAhamed** [comment]
even if i have just an if loop, its not dismissing keyboard, please see my updated code

**Comment by hackiftekhar** [comment]
Logically if you click on second textField then first one will automatically dismissed and second textField become first responder. You don't need to explicitly resign your first textField. and please see you checked textField == textFieldOne. and you wrote it inside textFieldDidBeginEditing is a big mistake.

**Comment by srikanthkumarmailid07** [comment]
If you touch anywhere outside of the keyboard on the screen then you to close the keyboard 

Write the following code inside the Appdelegate class didFinishLaunchingWithOptions launch options method.

 **IQKeyboardManager.shared.shouldResignOnTouchOutside = true**
