### ISSUE TITLE
Build fails using Swift on Xcode 7

### ISSUE THREAD

**Issue by anarchicknight** [hackiftekhar/IQKeyboardManager#292]
pod 'IQKeyboardManagerSwift'

pod install

import IQKeyboardManagerSwift in AppDelegate.swift

Build project
Build Failed with 37 issues, 35 of which are errors (too many to list here). Largely things like
do-while not allowed, use repeat-while instead
contains is unavailable, call the contains() method on the sequence
find is unavailable, call the indexOf() method on the collection

**Comment by hackiftekhar** [comment]
They all are changed in swift 2. We have to wait for Xcode 7 for general public (It's still in beta).

**Comment by jkritikos** [comment]
Same here, too many errors with Swift 2.0 - any estimate on when we can get a swift 2.0, xcode7 compatible version ? :)

**Comment by hackiftekhar** [comment]
Today I upload v3.3.2 with Swift 2.0 support. Could you please try v3.3.2.
