### ISSUE TITLE
Navigation bar keeps hiding even if we set UIScrollView V3.3.1

### ISSUE THREAD

**Issue by hardikdevios** [hackiftekhar/IQKeyboardManager#294]
![screen shot 2015-09-19 at 1 07 00 pm](https://cloud.githubusercontent.com/assets/6657591/9975191/2c6b23e8-5ed0-11e5-8980-1b0415e5f40b.png)

![ios simulator screen shot 19-sep-2015 1 09 38 pm](https://cloud.githubusercontent.com/assets/6657591/9975190/2c6a18d6-5ed0-11e5-9ac4-4fd07c2ae75e.png)

![ios simulator screen shot 19-sep-2015 1 09 18 pm](https://cloud.githubusercontent.com/assets/6657591/9975189/2c67a89e-5ed0-11e5-9686-fa7e6ef53230.png)

#### It was working previously now it stops working , Any idea ? Thanks mate, cheers

**Comment by hackiftekhar** [comment]
Nope, I need to investigate. Do you have any demo project to debug it?

**Comment by hardikdevios** [comment]
@hackiftekhar  **Solved by setting a ```BottomlayoutGuideconstraint``` to ```IQLayoutGuideConstraint```**

![ios simulator screen shot 19-sep-2015 2 51 27 pm](https://cloud.githubusercontent.com/assets/6657591/9975573/01ceb24a-5ede-11e5-8606-c734d2a7dd0e.png)


![screen shot 2015-09-19 at 2 53 11 pm](https://cloud.githubusercontent.com/assets/6657591/9975587/58f8e3e2-5ede-11e5-87ed-3d3c9eabaa6e.png)

**Comment by hardikdevios** [comment]
@hackiftekhar can adjust textview not working properly it working on first time in ViewController but not the second time the TextView size its not resizing properly

**Comment by hackiftekhar** [comment]
If you are working with IQLayoutGuideConstraint then I think you don't need to put all content on scrollView. Could you please try once again after removing scrollView trick?

**Comment by hardikdevios** [comment]
Yes i have removed the scroll view and it works with normal UIView, now i need your help suppose i have 4s screen then UITextView getting very small , is it possible to change the UIView frame with IQconstraint and setting the UITextView Just below the Navigation bar and send all other Views upside?

**Comment by hardikdevios** [comment]
![rai8w](https://cloud.githubusercontent.com/assets/6657591/9976579/71b65ab8-5f06-11e5-941c-ca4ebfd77ec9.gif)

#### on first time canAdjustTextview is working but on second time its not resizing

**Comment by hardikdevios** [comment]
@hackiftekhar Any thing you find Bro ?

**Comment by hackiftekhar** [comment]
@hardikdevios Unfortunately I'm a bit busy these days. So not able to get some time for this.

**Comment by hardikdevios** [comment]
@hackiftekhar same here bro lol, Time is money now a days

**Comment by hackiftekhar** [comment]
Could you please give me a demo so that I can play with that to dig into it.

**Comment by hardikdevios** [comment]
Issue resolved automatically cheers bro
