### ISSUE TITLE
when textfield setHidden:YES, toolbar gone

### ISSUE THREAD

**Issue by AbooJan** [hackiftekhar/IQKeyboardManager#296]
remember the old version, when the textfield setHidden is YES, the toolbar still can show,but current version,toolbar is gone,why?
can I custom the toolbar show or hide?
i can't find any info to explain this point?
Thanks!

**Comment by hackiftekhar** [comment]
When textField is hidden then how can you show keyboard over there. I mean, In this case textField is automatically resigned I think. No?

**Comment by AbooJan** [comment]
@hackiftekhar sometimes i want to use the hidden textfield to show custom pickerview. for example , i want to click the button and then show city selection pickerview . my way is put a hidden textfield behind the button, and set the textfield inputview is the custom pickerview, when the button click, i will let the hidden textfield becomeFirstResponder, then pickerview showed.

**Comment by hackiftekhar** [comment]
ok, then I'll try this trick to figure out exact scenario.

**Comment by hackiftekhar** [comment]
You can also set UIPickerView as textField inputView, so when your textField become first responder, then UIPickerView automatically pop-out from bottom like keyboard, and you can listen all the delegate of UIPickerView and change the textField text accordingly. I think you don't need any hidden button to achieve this.
