### ISSUE TITLE
When using a custom Super class, it shall be used also in the return key management

### ISSUE THREAD

**Issue by GUL-** [hackiftekhar/IQKeyboardManager#298]
Using 'considerToolbarPreviousNextInViewClass' I can manage having an autoToolbar working great even if my TextFields are in different superview.
The issue is coming when using Next button on the keyboard, the method 'goToNextResponderOrResign' uses 'responderSiblings' instead of 'responderViews' (see line 280) so it is dismissing the keyboard instead of going to next fields

**Comment by hackiftekhar** [comment]
I understand what you are trying to explain. I need some time to implement it.

**Comment by GUL-** [comment]
I already did it locally
I will fork and send PR if you want or just invite me to your repo

**Comment by hackiftekhar** [comment]
I'll take a look at your repo or just send me a pull request. I'll review it.
