### ISSUE TITLE
Please don't make it enable = YES as default

### ISSUE THREAD

**Issue by CoderJackyHuang** [hackiftekhar/IQKeyboardManager#299]
Sorry to say that, as the title, we want to make the old old code compatible, We just want to make it use only for new controllers. If use +load method to set up, it's affected automatically, but there are many old old pages that we could not modify, so we couldn't use your library.

Sorry again! I have try my best to use English, but may not descript the question correctly. Hope you can understand. Thanks!

**Comment by hackiftekhar** [comment]
You can disable it in didFinishLaunchingWithOptions: method in app delegate. How about this?

**Comment by CoderJackyHuang** [comment]
I want to do it like your suggestion, but when I include your library, other group members think it may still affect old old codes though I do not include it any where, so they deny my behavior.

Now I just use it in new projects, and remove it from old projects.

Thanks for your reply.

**Comment by hackiftekhar** [comment]
You can also use source code directly, and can change code locally according to your requirement.
