### ISSUE TITLE
keyboard become black, and can't see the done button.

### ISSUE THREAD

**Issue by jjksam** [hackiftekhar/IQKeyboardManager#301]
We have a project using this framework, check the attachement.
iOS 9, iPhone 5, iPhone 6 or iOS 8 both have this problem.
![black_done](https://cloud.githubusercontent.com/assets/1285799/10045453/67eff80e-6235-11e5-8314-f725b8512586.png)

**Comment by hackiftekhar** [comment]
May be some other inputAccessoryView is assigned with your textField?

**Comment by hackiftekhar** [comment]
Could you please send me demo project?

**Comment by jjksam** [comment]
I found the problem by using a demo project.
I set the appearance of UIToolbar which will affect all the toolbar.

[[UIToolbar appearance] setBackgroundImage:[[UIImage imageNamed:@"tabbar_bg_semi"] resizableImageWithCapInsets:UIEdgeInsetsMake(0, 0, 0, 0)] forToolbarPosition:UIBarPositionBottom barMetrics:UIBarMetricsDefault];

**Comment by hackiftekhar** [comment]
ok, thanks, I'll do some workaround to handle this.
