### ISSUE TITLE
iPhone 5, iOS 9 keyboard popup too slow.

### ISSUE THREAD

**Issue by jjksam** [hackiftekhar/IQKeyboardManager#302]
I upgraded my iPhone 5 to iOS 9, when using the IQKeyboardManager, I found the soft keyboard pop up very slow.

**Comment by hackiftekhar** [comment]
Then I need some investigation.

**Comment by sany620** [comment]
ios9 using the IQKeyboardManager，Push Viewcontroller, I found the uitoolbar will become black, then normal

**Comment by chepiok** [comment]
iOS9 with IQKeyboardManager. Just the fact to add the IQKeyBoardManager folder to my project (drag and drop) breaks the keyboard appeareance

**Comment by hackiftekhar** [comment]
@chepiok could you please share demo project. Because according to me, drag and drop should not break keyboard appearance.

**Comment by haydenholligan** [comment]
Just wanted to add to this that initializing the keyboard takes quite a long time for my project. I found that in IQBarButtonItem's initialize, all the appearance attributes to nil was slowing it down. I commented them out and it sped up quite a bit, no noticable differences so you might want to see if those are necessary.

**Comment by hackiftekhar** [comment]
Thanks @haydenholligan for letting us know the exact reason of delay.

**Comment by xilin** [comment]
+1 push new viewcontroller and the toolbar part will show as black for a while.

**Comment by vitorventurin** [comment]
I agree. It is really slow.

**Comment by xilin** [comment]
@hackiftekhar Hi, may I ask when will this fix be released in cocoapods?

**Comment by hackiftekhar** [comment]
It is expected to release at the end of dec or at the start of jan

**Comment by xilin** [comment]
@hackiftekhar Thanks.
