### ISSUE TITLE
IQKeyboard does  not work in Swift 2.0

### ISSUE THREAD

**Issue by kunal-arvaan** [hackiftekhar/IQKeyboardManager#304]
Hi 

I am using IQKeyboard in many of my app.  but in swift 2.0 this library is giving so many error. will you please check this and resolve the error.

**Comment by hackiftekhar** [comment]
Swift 2.0 is available with Xcode 7. Are you working in lower version of Xcode?

**Comment by kunal-arvaan** [comment]
I am working on xcode 7.0.

**Comment by beseder42** [comment]
Same for me with newest development environment. I documented it here: http://stackoverflow.com/questions/32921730/build-error-in-iqkeyboardmanager

**Comment by kunal-arvaan** [comment]
For me updated version is working now. Please guys update your version also.

**Comment by beseder42** [comment]
Which Version do you use? I have latest from like 2 hours ago.

**Comment by hackiftekhar** [comment]
I can confirm, latest version is 3.3.2 and it works with Xcode 7.0 (Swift 2.0)

**Comment by beseder42** [comment]
I am sorry, but the problem remains as described on stackoverflow.

**Comment by hackiftekhar** [comment]
I created a demo project and installed 3.3.2 with cocoapods, I got no erros. Don't know why you are getting issues?

**Comment by beseder42** [comment]
I am using the sources, included directly to my project.

**Comment by hackiftekhar** [comment]
There is not much differences either you use source code directly or use cocoapods.
