### ISSUE TITLE
Can I get swift 1.2 version?

### ISSUE THREAD

**Issue by vineethvijayan** [hackiftekhar/IQKeyboardManager#308]
Is there a way to get swift 1.2 version via Cocoapods? or Source code method?

**Comment by sabernar** [comment]
+1

**Comment by hackiftekhar** [comment]
You can force point older pod versions to get swift 1.2

**Comment by vineethvijayan** [comment]
Got it use pod like 

pod 'IQKeyboardManagerSwift', '= 3.3.1'
