### ISSUE TITLE
Long textView in scrollView not moving correctly

### ISSUE THREAD

**Issue by DaiYue** [hackiftekhar/IQKeyboardManager#309]
First of all, great lib!! 

I recently found a little problem: a tableView cell contains a really long textView, let's say 100 lines. When I tap on the 99th row, I would like to edit from here. Unfortunately it automatically scrolls so that the first line shows on top of the screen, therefore the 99th row is way below the keyboard and no where to be seen.

This case may be very rare. I just wonder will there be plan to fix it? If not, I will manually handle keyboard sliding in that particular viewController. The lib works on all the other viewControllers perfectly. Thanks a lot!

By the way, I'm using:

```
- (void)textViewDidChange:(UITextView *)textView {
    [self.tableView beginUpdates];
    [self.tableView endUpdates];
    
    CGFloat cursorPosition;
    if (textView.selectedTextRange) {
        cursorPosition = [textView caretRectForPosition:textView.selectedTextRange.start].origin.y;
    } else {
        cursorPosition = 0;
    }
    CGRect cursorRowFrame = CGRectMake(0, cursorPosition, kScreenWidth, kMinTextViewHeight);
    CGRect textViewFrame = [self.tableView convertRect:cursorRowFrame fromView:textView.superview];
    [self.tableView scrollRectToVisible:textViewFrame animated:YES];
}
```

if that's any help.

**Comment by hackiftekhar** [comment]
In this case, I think users can manually scroll tableView/scrollView with fingers in order to see content. Is there any problem using that?

**Comment by DaiYue** [comment]
Yeah, I guess that makes sense. 

Unfortunately my project manager won't agree. He believes if you want to edit on a certain line, you would tap on it and expect to start editing from here. If it suddenly scrolled to the top of the textView, and you have to manually scroll it back, it's kind of unnatural. And he won't stop nagging me for this.

But I won't trouble you further on this problem, since it's a rare case. I will try to figure out a workaround, it shouldn't be hard. Thank you for the response:)

**Comment by MattFoley** [comment]
I'm actually running into the same issue myself. I'm using my own fork of IQ and making some changes in order to get this working. (Attempting to use `caretRectForPosition` to find the users expected offset) This is for my own project, and I too think that the correct behavior would be to scroll to the position the user has set the caret to. It just makes more sense that way.

Did you ever find a work around?

**Comment by DaiYue** [comment]
@MattFoley I'm sorry I didn't find a workaround inside this lib. I just disabled this lib in that particular viewController and handled scrolling on my own.
