### ISSUE TITLE
Do not scroll a floating view

### ISSUE THREAD

**Issue by jlmendezbonini** [hackiftekhar/IQKeyboardManager#310]
Thanks for this great library.  

Is there a way for `IQKeyboardManager` to allow the keyboard to cover a certain view?  The usage case is for floating buttons that are pinned to the bottom and that you can let the keyboard cover them.

**Comment by hackiftekhar** [comment]
Could you please describe problem in more detail (may be with screenshots or code)

**Comment by jlmendezbonini** [comment]
I closed the issue because I'm not 100% sure whether there's a problem or not and I can't explore it more at the moment.  Roughly, the table view (not part of UITableViewController) would scroll to far or even re-adjust itself after the scrolling the first time.  My setup was more complicated than normal since I had sibling views for the table view containing all the textfields, I'm modifying the table view content inset, and showing/hiding the navigation bar during scrolling.
