### ISSUE TITLE
disableInViewControllerClass(disabledClass: AnyClass) doesn't seem to work for everything?

### ISSUE THREAD

**Issue by dilizarov** [hackiftekhar/IQKeyboardManager#311]
Just a quick note, but I needed to disable IQKeyboardManager in two different ViewControllers where I use a separate implementation due to legacy and due to special ways I control the view.

Long story short, it seemed to not interfere, but whenever I would try to type on the keyboard, it would resign.

Clearly, this was because in my IQKeyboardManager, I have set `IQKeyboardManager.sharedManager().shouldResignOnTouchOutside = true` (I tested that it doesn't happen when i set the value to false), but I was under the impression that by using `disableInViewControllerClass(disabledClass: AnyClass)`, IQKeyboardManager would basically be non-existent in that VC. Apparently, I'm wrong. What exactly is it supposed to achieve then?

Right now, in the VC I have fixed my problems by doing:

    override func viewWillAppear(animated: Bool) {
        super.viewWillAppear(animated)
        
        IQKeyboardManager.sharedManager().enable = false
    }

    override func viewWillDisappear(animated: Bool) {
        super.viewWillDisappear(animated)
    
        IQKeyboardManager.sharedManager().enable = true
    }

I was under the impression I wouldn't have to do this. IDK if it is a bug or intended functionality so just curious.

**Comment by hackiftekhar** [comment]
In AppDelegate.m you can use `disableInViewControllerClass(disabledClass: AnyClass)` method and provide viewController class to let IQKeyboardManager knows that it needs to be disable for that particular viewController's textField.

**Comment by dilizarov** [comment]
That is exactly what I was doing, but it didn't work for disabling the `shouldResignOnTouchOutside`

**Comment by hackiftekhar** [comment]
shouldResignOnTouchOutside is different from disableInViewControllerClass.... method. You have to manually set shouldResignOnTouchOutside to false. If you think it's a bug, then please demo project and describe the steps to reproduce it.

**Comment by dilizarov** [comment]
Alright, that is what I thought. What is the purpose of `disableInViewControllerClass(disabledClass: AnyClass)` then?

The name of the function makes it seem like IQKeyboardManager in its entirety will not work in that VC. It'll be as though IQKeyboardManager doesn't exist.

**Comment by hackiftekhar** [comment]
I seems, you are right. Then I should rename this function to something else. Basically this disable only `moving textField out of the way` feature.
