### ISSUE TITLE
Distance from single UITextField

### ISSUE THREAD

**Issue by michaelstonis** [hackiftekhar/IQKeyboardManager#312]
Is there a way to set the keyboard distance for a single UITextField? The global setting works great, but we have some scenarios where there may be buttons below the text field that need to be shown. Is this currently possible?

**Comment by hackiftekhar** [comment]
Check IQUITextFieldView+Additions.h, there is 'keyboardDistanceFromTextField' property, you can apply this for UITextField/UITextView per object.

**Comment by kuyazee** [comment]
How do I do this for swift? swift2.3
