### ISSUE TITLE
Cursor not moving in sequence, following drag and drop sequence

### ISSUE THREAD

**Issue by Devendranath** [hackiftekhar/IQKeyboardManager#313]
I created 5 text fields. Placed vertically one after another as: 
I drag and dropped one after another. I just jumbled as 

1
3
5
4
2  

When I run the application, The cursor is behaving like. 1, 2,3,4,5. What I want is 1,2,5,4,2.

Cursor is moving the order which I drag and dropped, not top to bottom

Please help me out.

**Comment by mythodeia** [comment]
you can add tags to your textfields and then use the IQAutoToolbarManageBehaviour enum with the IQAutoToolbarByTag option
check [here](https://github.com/hackiftekhar/IQKeyboardManager#iqtoolbar-handling)

**Comment by Devendranath** [comment]
Found the solutions,

In the storyboard, Keep the textfields in a sequence.
Like

>ViewController
    >View
      > TextField1
      > TextField3
      > TextField5
      > TextField4
      > TextField2

Thanks
