### ISSUE TITLE
xcode7.0 ios9.0.2，The upper part of app become black

### ISSUE THREAD

**Issue by MichaelYNWA** [hackiftekhar/IQKeyboardManager#314]
swicth from two textfiled

viewcontroller will move down half of the device_height, and half of the app become black

**Comment by MichaelYNWA** [comment]
ios8 is ok.    This issue appears everytime only after a UIAlertView was showed.

**Comment by MichaelYNWA** [comment]
ios8 is ok.    This issue appears everytime only after a UIAlertView was showed

**Comment by MichaelYNWA** [comment]
![1](https://cloud.githubusercontent.com/assets/3070162/10390552/03f6b602-6eac-11e5-8ec4-219f65278a9c.jpg)

**Comment by hackiftekhar** [comment]
Could you please send a sample app?

**Comment by MichaelYNWA** [comment]
The issus is solved after updating to latest version
