### ISSUE TITLE
Next and Previous arrows are invisible due to same strip colour on iOS 9.0.2

### ISSUE THREAD

**Issue by virengujariya** [hackiftekhar/IQKeyboardManager#315]
So Next and Previous arrows are functioning but due to same background colour as arrows they are not visible.

**Comment by virengujariya** [comment]
When I same background colour, I mean colour of strip where Next, Previous and Done controls are aligned.

**Comment by hackiftekhar** [comment]
Could you pleaae show a screenshot?

**Comment by hackiftekhar** [comment]
Any updates?

**Comment by rjpalermo1** [comment]
Here you go - I have the same issue - the < > works in the toolbar but the arrows are not seen.
![img_0923](https://cloud.githubusercontent.com/assets/7153565/10499714/74354498-72e3-11e5-8010-1d944de17e75.jpg)

**Comment by hackiftekhar** [comment]
Coyld you please give a demo project, so that I can found the possible cause?

**Comment by vijaysanghavi** [comment]
![image](https://cloud.githubusercontent.com/assets/7793810/10571555/f5353792-765d-11e5-9f58-e049b64b9daa.png)
Next and previous arrows are not visible in iOS 9

**Comment by hackiftekhar** [comment]
Any updates regarding demo project?

**Comment by robegamesios** [comment]
same issue on iOS 9, update please. thanks

**Comment by hackiftekhar** [comment]
@robegamesios Could you please share demo project so that I can debug it?

**Comment by robegamesios** [comment]
@hackiftekhar here is a demo of the space above keyboard not adjusting and also a pic of the invisible < > buttons (left of the DONE button in toolbar above keyboard).
https://www.dropbox.com/sh/3wwve31822lfb1h/AACmqcuEnZH8A6KXyW0uD337a?dl=0

I could not replicate the invisible < > button in the demo project so not sure why it's like that on my project.  Also question, I used the IQKeyboardManager 3.3.4, my project was started in Swift (have AppDelegate.swift file), but the classes where i used your pod is in Obj-C.  So not sure if that is an issue of using the wrong pod? thanks for your help.

**Comment by robegamesios** [comment]
@hackiftekhar any updates on the issue :point_up: ? thanks

**Comment by hackiftekhar** [comment]
I found that, when you try to install library using **pods**, sometimes **IQKeyboardManager.bundle** is not added to the project bundle. So library doesn't found any images/icons in project.

**Comment by hackiftekhar** [comment]
Does anyone having any workaround?

**Comment by robegamesios** [comment]
+1 on the workaround please. thanks

**Comment by hackiftekhar** [comment]
Can someone confirm if this issue is still valid?

**Comment by seecoolguy** [comment]
@hackiftekhar as of 4.0.2 it is still an issue, do you have a work around?

**Comment by hackiftekhar** [comment]
I don't have any workaround yet because it works most of the time with cocoapods but sometime it isn't working. Technically `Resource Bundle` which are having next-prev icons isn't being copied to project. That's why we are getting issues. May be something wrong with IQKeyboardManager.podspec file which I don't know.

**Comment by hackiftekhar** [comment]
Today I checked the demo project again without any change and it's working fine for me. It looks looks like an issue with the previoius Xcode version. I'm having Xcode 7.3 now and it's working fine.

**Comment by seecoolguy** [comment]
yeah I ran a pod update and now the arrows are back, I've been running in 7.3.1 :+1:

**Comment by hackiftekhar** [comment]
Even if you don't run `pod update` or `pod install` and just run the sample project, it will work. No changes needed in demo.

**Comment by robegamesios** [comment]
Thanks, I see the arrows too now on 7.3, one thing that causes a crash for me is if I change the inputView to a datepicker. If the datepicker animation is set to YES, it will crash when pressing Previous button too quickly

**Comment by hackiftekhar** [comment]
Hmm, If you could find something useful about crash then let me know.

**Comment by robegamesios** [comment]
I think the issue is the date picker animation is not yet done when the new animation is being called. So it may not be an issue with just pressing the previous or next buttons, but the timing of when to press them.  it would nice to have the previous and next button disabled until all animations are done in the view.  Turning off the date picker animation eliminates the crash. thanks

**Comment by Chr0nisch** [comment]
I got the same issue today in Xcode 9.0 beta 5 (9M202q) with IQKeyboardManager 4.0.11 integrated by cocoa pods . The next and previous buttons are on the view and could be used, but have the same color as the toolbar. Any solution for this problem?

**Comment by monishpainter** [comment]
Any updates?

**Comment by hackiftekhar** [comment]
Can you debug it using the Xcode UI debugging tool to check what's the tintColor of toolbar and the buttons of next/prev?

**Comment by jaften** [comment]
I'm having the same issue :s 
The images seems to be missing...
I uploaded the IQButtonBarArrows with base size because it only had @2 and @3, and I thought that it could be the problem but it's still happening

**Comment by sharath-mtuity** [comment]
Add this line. :)
`        IQKeyboardManager.sharedManager().toolbarTintColor = .white
`

**Comment by jaften** [comment]
I have the code in Objective-C and pods.
And I had set the toolbartintcolor to a kind of green.
Anyway I tried just in case, but it didn’t fix it. :s

I’m pretty sure that the problem is when the pods imports the pictures, because the buttons are there but not the pictures :s

**Comment by grabbou** [comment]
FYI if you are still encountering that issue, make sure you have the `.bundle` in your `Copy resources`.

**Comment by jaften** [comment]
As I said before I can see some of the resources (I'm not sure if all) but there is something wrong in the .bundle file...

**Comment by jaften** [comment]
Thanks, I tried before but nothing happened. Anyway I tried again just in case but nothing new happened :s :s

**Comment by Adakhan** [comment]
Problem is still here, iOS 13, Xcode 11

**Comment by tylerjames** [comment]
Experiencing the same issue but with IQKeyboardManagerSwift installed via Swift Package Manager. I can see that the images are under the Resources folder of the project but they do not show up in the toolbar.

**Comment by Adakhan** [comment]
I solve the problem by putting my own images
           `IQKeyboardManager.shared.toolbarPreviousBarButtonItemImage = UIImage(named: "ArrowUp")
        IQKeyboardManager.shared.toolbarNextBarButtonItemImage = UIImage(named: "ArrowDown")`

**Comment by hackiftekhar** [comment]
@tylerjames the SPM currently does not support resources, so it does not load the assets. @Adakhan solution will work as a workaround.
