### ISSUE TITLE
iOS 9 iPad Only - Keyboard hides the text fields in a presented view controller (must be presented as form sheet)

### ISSUE THREAD

**Issue by ZaeemJintech** [hackiftekhar/IQKeyboardManager#318]

**Comment by hackiftekhar** [comment]
I tested on Xcode7 with my ObjC demo project on iPad2 simulator and it's working fine. If you can share any demo project then it would be great.

**Comment by hackiftekhar** [comment]
Here is the demo project
https://www.dropbox.com/s/kqqtzvmwzof4sxt/TestingKeyboardNotification.zip?dl=0

**Comment by hackiftekhar** [comment]
When I added multiple textField on presented controller, then it doesn't working for first responded textField and then it works for other textField via next/prev button. Surely need to dig into it, because it's hard to findout what is happening there.

**Comment by zaeemzafar** [comment]
Thanks for your response, Will be waiting for possible fix. Thanks.

**Comment by hackiftekhar** [comment]
Actually according to library, it's firing method to change frame of topView, but don't know why topView is not moved or force self to restore. I'm confirming this because it's working in library demo project, but not in our new demos we created 2-4 days before.

**Comment by PowerYang** [comment]
怎样解决楼主提出的问题？就是present了一个controller ,里面有uitextfield,点击后键盘会遮挡的这个问题？

**Comment by hackiftekhar** [comment]
This issue is fixed wtih 68702f0a4d4c13497025d1af1a094850a9f750cf
