### ISSUE TITLE
swift 2.0 Uint convert error and init(control: UIViewController) need public

### ISSUE THREAD

**Issue by zuo305** [hackiftekhar/IQKeyboardManager#319]
1. swift 2.0 Uint convert Int error
2. IQKeyboardReturnKeyHandler could not use init,should be public

**Comment by houmanka** [comment]
Any update on this? I upgraded my Xcode 7.1 and suddenly I am getting your error now.

**Comment by zuo305** [comment]
yes.I changed the code
 public init(controller : UIViewController)

**Comment by manzznam** [comment]
How did you correct the swift 2.0 Uint convert Int error?

**Comment by hackiftekhar** [comment]
This is fixed now e4dd3a4c6575946759b895375f3a66fdbc4318e2. Thanks for reporting
