### ISSUE TITLE
Text Fields Tag

### ISSUE THREAD

**Issue by asifhabib** [hackiftekhar/IQKeyboardManager#322]
1. I gave tags to each text-fields so that on some textfield I stop keyboard to show. But it did not respect the tags given by me and all the keyboard appears to  have same tags. 
2. I compared my  textfield in textFieldShouldBeginEditing textfield. It always returned true. What is the problem. 
Problem: I can not show my custom dialogue on some specific keyboards.

**Comment by hackiftekhar** [comment]
Could you please elaborate your problem. I'm not able to understand it properly. Could you please try  take a look at 'toolbarManageBehaviour' property in IQKeyboardManager?

**Comment by hackiftekhar** [comment]
Any updates?
