### ISSUE TITLE
Cannot convert value of type 'UInt' to expected argument type 'Int' in IQKeyboardReturnKeyHandler.swift

### ISSUE THREAD

**Issue by manzznam** [hackiftekhar/IQKeyboardManager#324]
I get still this compiler error in IQKeyboardReturnKeyHandler.swift in row 89,97,122 and 128.

**Comment by hackiftekhar** [comment]
Are you using Xcode7?

**Comment by manzznam** [comment]
Version 7.1 (7B91b)

**Comment by manzznam** [comment]
and my Podfile String is: 
pod 'IQKeyboardManagerSwift', :git => 'https://github.com/hackiftekhar/IQKeyboardManager.git'

**Comment by hackiftekhar** [comment]
I don't know if there anything deprecated or unavailable while moving from Xcode7 to Xcode7.1. I have to test this in 7.1.

**Comment by manzznam** [comment]
My temporary workaround for the line:

textField.returnKeyType = UIReturnKeyType(rawValue: returnKeyTypeValue.unsignedIntegerValue)!

is:

textField.returnKeyType = UIReturnKeyType(rawValue: Int(returnKeyTypeValue.unsignedIntegerValue))!

**Comment by hackiftekhar** [comment]
I think you shouldn't directly point the master branch, it may contain some bugs due to frequent changes and you should use the tagged/stable version of the library.

**Comment by manzznam** [comment]
should i better use this?
pod 'IQKeyboardManagerSwift'

**Comment by hackiftekhar** [comment]
I think yes, that's the stable version, but for your error, they are not resolvable by this too. because I'm not sure why you are getting those errors?

**Comment by manzznam** [comment]
yes i migrated today from 7.0 to 7.1 and got this error afterwards. Probably this is an Xcode 7.1 related issue ...

**Comment by richardoti** [comment]
I guess, the cast is required as Swift 2.1 made `UInt` not compatible with `Int`. And `UIReturnKeyType` uses `Int` for it's internal value representation:
https://developer.apple.com/library/ios/documentation/UIKit/Reference/UITextInputTraits_Protocol/#//apple_ref/c/tdef/UIReturnKeyType

So, the solution above should be correct.

**Comment by 2075** [comment]
this fixed the problem for me, thx.

**Comment by akinmobile** [comment]
Converting the UInt to Int fixed the issue for me too.
