### ISSUE TITLE
Unnecessary super call in "+(void)load" method (IQKeyboardManager class)

### ISSUE THREAD

**Issue by nikitahils** [hackiftekhar/IQKeyboardManager#326]
From documentation on +load method: 
"In addition:
A class’s +load method is called after all of its superclasses’ +load methods.
A category +load method is called after the class’s own +load method.
"
So you should't worry about calling +load on super class, it is redundant.

PS:
I found it accidentally, because i got a nasty bug.
I have a NSObject category with implemented load method (small swizzling functionality). 
All the time i have only one call of this method, but when i install IQKeyboardManager - i've got 2 call, so it breaks my dispatch_once().

**Comment by hackiftekhar** [comment]
Ohh, thanks for sharing your valuable knowledge with me. Could you please let me know your NSObject category, so that I can also confirm about the +load method call?

**Comment by nikitahils** [comment]
@hackiftekhar, it was simple NSObject category with swizzling for logging dealloced objects.
Load method implementation from this category:

+ (void)load
{
    static dispatch_once_t once_token;
    dispatch_once(&once_token,  ^{
        SEL deallocSelector = NSSelectorFromString(@"dealloc");
        SEL deallocLoggedSelector = @selector(logged_dealloc);
        swizzle([self class], deallocSelector, deallocLoggedSelector);
    });
}

So, when IQKeyboardManager call [super load], it was the first call of NSObject +load method, so [self class] return IQKeyboardManager class and swizzle dealloc method in it, not in NSObject.

**Comment by hackiftekhar** [comment]
Thanks, I removed super call on IQKeyboardManager +load method.
