### ISSUE TITLE
Upgrade to 3.3.3: Crash on iOS7

### ISSUE THREAD

**Issue by sunhr** [hackiftekhar/IQKeyboardManager#328]
This occurs everytime when textfields become first responder on iOS7

    
Date/Time:           2015-10-23 14:54:34.228 +0800
OS Version:          iOS 7.1.1 (11D201)
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Triggered by Thread:  0

Last Exception Backtrace:
0   CoreFoundation                	0x18ce26f50 __exceptionPreprocess + 132
1   libobjc.A.dylib               	0x1996e01fc objc_exception_throw + 60
2   CoreFoundation                	0x18ce26e90 +[NSException raise:format:] + 128
3   UIKit                         	0x19032d540 +[NSObject(UIAppearanceAdditions) _installAppearanceSwizzlesForSetter:] + 488
4   UIKit                         	0x18ff7a994 -[_UIAppearance forwardInvocation:] + 1532
5   CoreFoundation                	0x18ce29740 ___forwarding___ + 416
6   CoreFoundation                	0x18cd495dc _CF_forwarding_prep_0 + 92
7   RuiYun                        	0x1001e64c4 +[IQToolbar initialize] (IQToolbar.m:55)
8   libobjc.A.dylib               	0x1996e0c6c _class_initialize + 600
9   libobjc.A.dylib               	0x1996e6b7c lookUpImpOrForward + 156
10  libobjc.A.dylib               	0x1996f03fc _objc_msgSend_uncached_impcache + 60
11  RuiYun                        	0x10019c6e4 -[UIView(IQToolbarAddition) addPreviousNextDoneOnKeyboardWithTarget:previousAction:nextAction:doneAction:titleText:] (IQUIView+IQKeyboardToolbar.m:429)
12  RuiYun                        	0x10019d1c0 -[UIView(IQToolbarAddition) addPreviousNextDoneOnKeyboardWithTarget:previousAction:nextAction:doneAction:shouldShowPlaceholder:] (IQUIView+IQKeyboardToolbar.m:543)
13  RuiYun                        	0x100168d18 -[IQKeyboardManager addToolbarIfRequired] (IQKeyboardManager.m:1671)
14  RuiYun                        	0x100165824 -[IQKeyboardManager textFieldViewDidBeginEditing:] (IQKeyboardManager.m:1218)
15  CoreFoundation                	0x18cddb5b4 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 20
16  CoreFoundation                	0x18cd28104 _CFXNotificationPost + 2064
17  Foundation                    	0x18d8ba748 -[NSNotificationCenter postNotificationName:object:userInfo:] + 72
18  UIKit                         	0x18fefb6c0 -[UITextField _becomeFirstResponder] + 632
19  UIKit                         	0x18fe74c3c -[UIResponder becomeFirstResponder] + 396
20  UIKit                         	0x18fe74fa4 -[UIView(Hierarchy) becomeFirstResponder] + 124
21  UIKit                         	0x18fefa0fc -[UITextField becomeFirstResponder] + 68
22  UIKit                         	0x18ffac804 -[UITextInteractionAssistant(UITextInteractionAssistant_Internal) setFirstResponderIfNecessary] + 212
23  UIKit                         	0x18ffabf88 -[UITextInteractionAssistant(UITextInteractionAssistant_Internal) oneFingerTap:] + 1796
24  UIKit                         	0x18ff92c64 _UIGestureRecognizerSendActions + 216
25  UIKit                         	0x18fe212a0 -[UIGestureRecognizer _updateGestureWithEvent:buttonEvent:] + 380
26  UIKit                         	0x190220040 ___UIGestureRecognizerUpdate_block_invoke + 60
27  UIKit                         	0x18fde225c _UIGestureRecognizerRemoveObjectsFromArrayAndApplyBlocks + 288
28  UIKit                         	0x18fde0b38 _UIGestureRecognizerUpdate + 212
29  UIKit                         	0x18fe1fb20 -[UIWindow _sendGesturesForEvent:] + 1012
30  UIKit                         	0x18fe1f230 -[UIWindow sendEvent:] + 828
31  UIKit                         	0x18fdf0b68 -[UIApplication sendEvent:] + 256
32  UIKit                         	0x18fdeec58 _UIApplicationHandleEventQueue + 8500
33  CoreFoundation                	0x18cde7644 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
34  CoreFoundation                	0x18cde69a0 __CFRunLoopDoSources0 + 256
35  CoreFoundation                	0x18cde4c38 __CFRunLoopRun + 632
36  CoreFoundation                	0x18cd25c20 CFRunLoopRunSpecific + 452
37  GraphicsServices              	0x1929b5c0c GSEventRunModal + 168
38  UIKit                         	0x18fe56fdc UIApplicationMain + 1156
39  RuiYun                        	0x1001010bc main (main.m:14)
40  libdyld.dylib                 	0x199cd3aa0 start + 4

**Comment by hackiftekhar** [comment]
Thanks for reporting, I'll take a loot at iOS7
