### ISSUE TITLE
`shouldResignOnTouchOutside` for a specific ViewController

### ISSUE THREAD

**Issue by diogowbrito** [hackiftekhar/IQKeyboardManager#330]
There should be a `shouldResignOnTouchOutside` for a specific ViewController. 
Right now, the only way to change this behaviour is through direct change on the ViewController, through the singleton, which may not be safe.

Something like: ```shouldResignOnTouchOutside(disabledViewController: AnyViewController, shouldResign: Bool)```

**Comment by hackiftekhar** [comment]
Great suggestion, will implement soon.
