### ISSUE TITLE
View is not pulled back after rotating and hiding the key board

### ISSUE THREAD

**Issue by saiimons** [hackiftekhar/IQKeyboardManager#331]
Here is how things are :
* I have a view containing my form,
* The view is centered horizontally and vertically
* In portrait, the keyboard pops up and __does not__ hide the view
* In landscape, the keyboard pops up and __does__ hide the view

Order of things :
1. Start from portrait
2. Select a text field
3. (Keyboard pops up)
4. Rotate to landscape
5. Press done
6. (Keyboard hides)
Result : the view is not coming down
# 1 (Portrait)
![img_0034](https://cloud.githubusercontent.com/assets/6832416/10705729/145e5ac4-79ae-11e5-8b6f-6e5ab2179093.jpg)

# 2 & 3 (Select text and kb pops up)
![img_0035](https://cloud.githubusercontent.com/assets/6832416/10705733/186fe024-79ae-11e5-80e2-ef31b2079cd9.jpg)

# 4 (Rotation)
![img_0036](https://cloud.githubusercontent.com/assets/6832416/10705735/1c0895be-79ae-11e5-9dd1-5f1d6e8ba6a4.jpg)

# 5 & 6 (Down and kb hides)
![img_0037](https://cloud.githubusercontent.com/assets/6832416/10705737/2035e556-79ae-11e5-84e9-ef505a8c2379.jpg)

**Comment by saiimons** [comment]
And the Log :

```
IQKeyboardManager: enabled
IQKeyboardManager: ****** textFieldViewDidBeginEditing started ******
IQKeyboardManager: Saving <<UITextField: 0x13ee54f60; frame = (8 36.3333; 358 30); text = ''; clipsToBounds = YES; opaque = NO; autoresize = RM+BM; gestureRecognizers = <NSArray: 0x13ed317f0>; layer = <CALayer: 0x13ee4a390>> 0x000000013ee54f60> Initial frame : (8.0, 36.3333333333333, 358.0, 30.0)
IQKeyboardManager: adding UIToolbars if required
IQKeyboardManager: Saving <<XXX.ViewController: 0x13ee40920> 0x000000013ee40920> beginning frame : (0.0, 0.0, 414.0, 736.0)
IQKeyboardManager: ****** adjustFrame() %@ started ******
IQKeyboardManager: Need to move: -347.666666666667
IQKeyboardManager: ****** adjustFrame() ended ******
IQKeyboardManager: ****** textFieldViewDidBeginEditing ended ******
IQKeyboardManager: ****** keyboardWillShow started ******
IQKeyboardManager: Saving <<UITextField: 0x13ee54f60; frame = (8 36.3333; 358 30); text = ''; clipsToBounds = YES; opaque = NO; autoresize = RM+BM; gestureRecognizers = <NSArray: 0x13ed317f0>; layer = <CALayer: 0x13ee4a390>> 0x000000013ee54f60> Initial frame : (8.0, 36.3333333333333, 358.0, 30.0)
IQKeyboardManager: UIKeyboard Size : (414.0, 315.0)
IQKeyboardManager: ****** adjustFrame() %@ started ******
IQKeyboardManager: Need to move: -32.6666666666667
IQKeyboardManager: ****** adjustFrame() ended ******
IQKeyboardManager: ****** keyboardWillShow ended ******
IQKeyboardManager: ****** willChangeStatusBarOrientation started ******
IQKeyboardManager: ****** willChangeStatusBarOrientation ended ******
IQKeyboardManager: ****** keyboardWillHide started ******
IQKeyboardManager: Restoring <<XXX.ViewController: 0x13ee40920> 0x000000013ee40920> frame to : (0.0, 0.0, 414.0, 736.0)
IQKeyboardManager: ****** keyboardWillHide ended ******
IQKeyboardManager: ****** keyboardDidHide started ******
IQKeyboardManager: ****** keyboardDidHide ended ******
IQKeyboardManager: ****** keyboardWillShow started ******
IQKeyboardManager: Saving <<UITextField: 0x13ee54f60; frame = (8 36.3333; 680 30); text = ''; clipsToBounds = YES; opaque = NO; autoresize = RM+BM; gestureRecognizers = <NSArray: 0x13ed317f0>; animations = { bounds.origin=<CABasicAnimation: 0x13ed98ec0>; bounds.size=<CABasicAnimation: 0x13eda2530>; position=<CABasicAnimation: 0x13ed63770>; }; layer = <CALayer: 0x13ee4a390>> 0x000000013ee54f60> Initial frame : (8.0, 36.3333333333333, 680.0, 30.0)
IQKeyboardManager: Saving <<XXX.ViewController: 0x13ee40920> 0x000000013ee40920> beginning Frame: (0.0, 0.0, 736.0, 414.0)
IQKeyboardManager: UIKeyboard Size : (736.0, 238.0)
IQKeyboardManager: ****** adjustFrame() %@ started ******
IQKeyboardManager: Need to move: 51.3333333333333
IQKeyboardManager: Moving Upward
IQKeyboardManager: Set Optional("<<XXX.ViewController: 0x13ee40920> 0x000000013ee40920>") frame to : (0.0, -51.3333333333333, 736.0, 414.0)
IQKeyboardManager: ****** adjustFrame() ended ******
IQKeyboardManager: ****** keyboardWillShow ended ******
IQKeyboardManager: ****** keyboardWillShow started ******
IQKeyboardManager: Saving <<UITextField: 0x13ee54f60; frame = (8 36.3333; 680 30); text = ''; clipsToBounds = YES; opaque = NO; autoresize = RM+BM; gestureRecognizers = <NSArray: 0x13ed317f0>; layer = <CALayer: 0x13ee4a390>> 0x000000013ee54f60> Initial frame : (8.0, 36.3333333333333, 680.0, 30.0)
IQKeyboardManager: UIKeyboard Size : (736.0, 238.0)
IQKeyboardManager: ****** keyboardWillShow ended ******
IQKeyboardManager: ****** keyboardWillHide started ******
IQKeyboardManager: ****** keyboardWillHide ended ******
IQKeyboardManager: ****** textFieldViewDidEndEditing started ******
IQKeyboardManager: ****** textFieldViewDidEndEditing ended ******
IQKeyboardManager: ****** keyboardDidHide started ******
IQKeyboardManager: ****** keyboardDidHide ended ******
```

**Comment by hackiftekhar** [comment]
It's better to provide me demo code too

**Comment by hackiftekhar** [comment]
Thanks for the report, I'm getting this issue with Swift version, this issue is not happening in ObjC version. I'll look into this. Thanks :)

**Comment by debashreejoshi** [comment]
I am also facing the same issue #331  #1058.

**Comment by kajalsheth** [comment]
I am also facing this issue. Any update for this?

Thanks in advance.

**Comment by runtimelogic** [comment]
I can verify this bug still repros in the current release of this lib under iOS 11.3.  It looks like the problem is that on on orientation change the keyboard is hidden and then shown again.  At some point in that process, likely in adjustFrame() somewhere, the _topViewBeginRect gets set to the rootViewController frame which has the adjusted positioning.

It seems like line 1660 is an attempt to fix this perhaps but the rootViewController frame here is the same as the value already set in _topViewBeginRect at this point and doesn't fix the origin y value being incorrect:

    //frame size needs to be adjusted on iOS8 due to orientation API changes.
    _topViewBeginRect.size = rootViewController.view.frame.size

Since I wasn't able to figure out the correct fix.  I added the following after that line as a work around.  It seems to resolve the incorrect y position of the root controller on keyboard hide post orientation change, for my simple use case (I'm not using the form enhancements): 

    // AJC 5/20/2018 work around incorrect restore value
    if _topViewBeginRect.origin.y < 0 { _topViewBeginRect.origin.y = 0 }
