### ISSUE TITLE
toolbarManageBehaviour not work in different view's subview which is the textField

### ISSUE THREAD

**Issue by litt1e-p** [hackiftekhar/IQKeyboardManager#333]
my view's structure is like:
controllerA's view-->|-->UIView-->UITextField
controllerA's view-->|-->UIView-->UITextField
controllerA's view-->|-->UIView-->UITextField
I have try add different tag on each textField, it didn't work, neither IQAutoToolbarByTag 、IQAutoToolbarBySubviews nor IQAutoToolbarByPosition.
my  environment is Xcode7、iOS9、OC

**Comment by hackiftekhar** [comment]
It looks like you are trying to get next previous arrow there. If yes, then you can try **considerToolbarPreviousNextInViewClass** method. You'll find an example in **CustomViewController** class. If you have any other questions, please ask me here.
