### ISSUE TITLE
App is not passing the validation process Due to Bundle version 3.3.3.1

### ISSUE THREAD

**Issue by hardikdevios** [hackiftekhar/IQKeyboardManager#334]
New Apple rule we can not set Build version more that 3 digits and it must me in integer so it means currently its set 3.3.3.1 which is not allowed as per new rules i dont have the links but it happens to me so i have to quickly changed my version but forget to take the screen shots and i have to remove manually .1 so its passes the validation 3.3.3 , cheers bro please fix this :+1:

**Comment by hackiftekhar** [comment]
Thanks for keeping me update, but I still need any reference link to read something about this new rule of apple.

**Comment by hardikdevios** [comment]
#### Proof 
![screen shot 2015-10-26 at 11 23 11 am](https://cloud.githubusercontent.com/assets/6657591/10967182/aebdcac0-83de-11e5-81b6-63a4e6ba0cfc.png)

http://stackoverflow.com/questions/25418798/cfbundleversion-must-be-a-period-separated-list-of-at-most-three-non-negative-in

**Comment by hackiftekhar** [comment]
Thanks for the link, it looks like that this limitation is checks when uploading build to testflight. And not for third party library releases. Right?

**Comment by hardikdevios** [comment]
Actually its chacking all libs info.plist files so now w3 have to take care, any way you can close the issue now its just reminder to my friend :+1:

**Comment by hackiftekhar** [comment]
From now I'm going to follow 3 digits as per the new rule. So closing this issue in favour of following new rubbish rule.
