### ISSUE TITLE
Alternative to keyboardDistanceFromTextField?

### ISSUE THREAD

**Issue by semireg** [hackiftekhar/IQKeyboardManager#335]
Let's say I want to display my own modal VC that looks like this:

![2015-10-26 at 7 20 pm](https://cloud.githubusercontent.com/assets/1819762/10746252/e07685ea-7c16-11e5-874d-b7d1e6b9636d.png)

Then, when I select the UITextView the keyboard slides out with distance of 44+8 and looks nice.

![2015-10-26 at 7 22 pm](https://cloud.githubusercontent.com/assets/1819762/10746264/012e7720-7c17-11e5-8c26-8be165544ff0.png)

I would like to do this programmatically using IQLayoutGuideConstraint, but it doesn't work... any ideas to be able to pin a different view instead of the bottom of the UITextView?

**Comment by semireg** [comment]
Also, I looked through all of the ViewControllers in the Demo and none I saw utilize IQLayoutGuideConstraint. Am I missing something? An example would be great!

**Comment by hackiftekhar** [comment]
Demo project contains non-autolayout storyboards. You can find IQLayoutGuideConstraint demos in one of the closed issue list.

**Comment by hackiftekhar** [comment]
Is this issue still persist?

**Comment by kevinrenskers** [comment]
I actually have a very similar question. My view looks like this:

<img width="487" alt="screen shot 2016-02-11 at 11 09 54" src="https://cloud.githubusercontent.com/assets/229384/12977625/205f4214-d0cc-11e5-9bed-bdaba4a20657.png">

When the keyboard shows up, it's using the bottom of the text field, instead the entire container view.

<img width="487" alt="screen shot 2016-02-11 at 11 10 33" src="https://cloud.githubusercontent.com/assets/229384/12977626/20850a94-d0cc-11e5-86d1-7b5ece87cb3d.png">

How can I tell IQKeyboardManager to use its container view? I tried pointing the bottom constraint of the container to IQLayoutGuideConstraint, but that didn't do much except that now only that view moves, except of the entire view controller's view (including the nav bar), but that table at the bottom is still hidden.

**Comment by hackiftekhar** [comment]
I got what you are talking about. You can check "IQUITextFieldView+Additions.h" which is category class over UIView and works for UITextField too. There is a property 'keyboardDistanceFromTextField', you can set that property to any distance for you special textField.
Let me know if you still have issues.

**Comment by kevinrenskers** [comment]
Thank you, that work great!
