### ISSUE TITLE
Done button is always black

### ISSUE THREAD

**Issue by tedrog36** [hackiftekhar/IQKeyboardManager#337]
Trying to set appearance for done button so the done title is displayed as white but it always displays as black.

Setting appearance this way:     
[[UIBarButtonItem appearance] setTitleTextAttributes:[NSDictionary dictionaryWithObjectsAndKeys:
                                                          [UIColor whiteColor], NSForegroundColorAttributeName,
                                                          nil] forState:UIControlStateNormal];

Also have tried this:
    [[UIToolbar appearance] setTintColor:[UIColor whiteColor]];

Thanks for any help.  Really enjoying using the library.

Ted

**Comment by hackiftekhar** [comment]
That's explicitly disabled, because most of the users wants to set proxies on UIBarButtons or UIToolbars but don't want to change appearance of keyboard toolbar.

One more thing, they are not UIToolbar or UIBaarButtonIttem in library, they are IQToolbar and IQBarButtonItem (Subclasses).

**Comment by tedrog36** [comment]
Thanks for the response.  What is the recommended way for me to have the button title to be a different color?  The IQ toolbar background takes on the bar tint color I apply to UIToolbar appearance which is a dark blue.  I want the bar button title to be white.

**Comment by tedrog36** [comment]
Ok, I worked around this but not setting appearance for UIToolbar and setting values on individual toolbars.  Would be nice if IQToolbar/IQBarButtonItem either used all appearance settings or no appearance settings so I could use UIToolbar appearance settings.  I hope that made sense.

**Comment by hackiftekhar** [comment]
I agree with you and according to you this all makes sense, but for some other users, this behaviour is wrong. They says toolbar and it's item shouldn't be affected by appearance proxy. You can also check 'toolbarUsesTextfieldTintColor' property.

**Comment by tedrog36** [comment]
I am ok with it not be affected by appearance proxy but the problem I am having is the background of the toolbar is affected by the appearance proxy but the bar button item titles are not.
No problem though, I have worked around this by putting non-keyboard toolbar setup in a base vc class and not using appearance proxy at all.

**Comment by hackiftekhar** [comment]
Thanks :)

**Comment by JovanSeizov** [comment]
I was able to change the done colour using this:
IQBarButtonItem.appearance().setTitleTextAttributes([NSForegroundColorAttributeName : UIColor.mainPurple], forState: .Normal)
