### ISSUE TITLE
TableView with footer not properly scrolled

### ISSUE THREAD

**Issue by tedrog36** [hackiftekhar/IQKeyboardManager#341]
If you have a UITableView with a footer, the UITableView contents are not properly scrolled.  The footer ends up moving on top of the table rows.  The table rows don't scroll up at all.

**Comment by hackiftekhar** [comment]
Could you please share screenshot or demo code and share steps to reproduce it?

**Comment by tedrog36** [comment]
This is work for a client so I don't want to put the screenshot in a public place.  Can I email it to you?

Also, I should have mentioned that it is a section footer.

**Comment by tedrog36** [comment]
Sorry, I just tested on an iPhone4s and what I think I am seeing is standard behavior for a section footer.  It will overlap the cells when space is tight.  So, I am closing this one.  

Sorry for the trouble.

**Comment by EadkennyChan** [comment]
for example, as shown below, the footer "-----123456633" label view
![IMG_0161](https://user-images.githubusercontent.com/3773659/59825887-c48cff00-9367-11e9-9df1-9fde4e12c835.PNG)

it's scroll up when keyboard appeared
![IMG_0162](https://user-images.githubusercontent.com/3773659/59825901-cbb40d00-9367-11e9-837b-2827703d86b5.PNG)
