### ISSUE TITLE
Manually setting the toolbar tintColor

### ISSUE THREAD

**Issue by RTimal** [hackiftekhar/IQKeyboardManager#342]
Is there a way to do this with the current API, or is it planned? Thank you.

**Comment by hackiftekhar** [comment]
Currently it's supported with using 'toolbarUsesTextFieldTintColor' property, in which toolbar use it's textField's tintColor. I think when toolbarUsesTextFieldTintColor=NO then we can add another property to set toolbarTintColor too. Thanks for a suggestion.

**Comment by Weever** [comment]
I set shouldToolbarUsesTextFieldTintColor = YES, and TextField's tintColor is WhiteColor, in iPad, the tintColor is WhiteColor, but in iPhone(4S,iOS9.1), the tintColor is some like grayColor(po textField.tintColor is UIDeviceRGBColorSpace 0.64 0.64 0.6

**Comment by hackiftekhar** [comment]
This feature has been recently implemented c4c3f6bfc8c32496cf1285b59c84bb3263c6cb68.
