### ISSUE TITLE
Trying to use this with Armv7s slice and cannot get to build with Armv7s enabled. Any help?

### ISSUE THREAD

**Issue by krudraiah** [hackiftekhar/IQKeyboardManager#344]
Great component, very slick and easy to use and works great. I have a Xamarin project where I am trying to build it with Armv7s enabled, but the component does not have that slice in it. So downloaded the project and enabled that in xcode settings to make the .a file, but the generated library results in a sharedManager instance being null. Help please

**Comment by hackiftekhar** [comment]
Github Library contains full source files. I don't undersrand why you can't generate armv7s slice. May be somethjng wrong in your project settings.

**Comment by hackiftekhar** [comment]
Are you still getting issues?

**Comment by krudraiah** [comment]
Yes

**Comment by krudraiah** [comment]
I did download the source and enabled armv7s to the settings, after I build and try to use it the shared manager instance is null

**Comment by hackiftekhar** [comment]
There is full source code available at github, don't know why you are getting issue. There must be some issue with you compilation process while converting to binary (.a) file.

**Comment by hackiftekhar** [comment]
Closing this issue in favor of Open Source library and full source code available. This may be an Xcode build settings related issue.
