### ISSUE TITLE
It`s not right when the contentInset is changed.

### ISSUE THREAD

**Issue by yuyedaidao** [hackiftekhar/IQKeyboardManager#346]
[self.collectionView setContentInset:UIEdgeInsetsMake(100, 0, 0, 0)];
    self.titleTF = [[UITextField alloc] init];
    [self.collectionView addSubview:self.titleTF];
    self.titleTF.frame = CGRectMake(10, -90, self.collectionView.bounds.size.width-20, 35);

The focus here is that the titleTF`s origin.y is -90. so,help me,thx.

**Comment by yuyedaidao** [comment]
My English is so bad,could you understand me?😂    我改变了UIScrollView的contentInset属性，然后在contentInset范围内添加了一个UITextField，这时候IQKeyboardManager就不能正确的工作了。

**Comment by hackiftekhar** [comment]
Ok, I'll look at this issue.

**Comment by hackiftekhar** [comment]
I checked and found that UICollectionView internally change contentOffset. You can try it without library and this issue is happening there as well.
