### ISSUE TITLE
IQKeyboardReturnKeyHandler not working for textField inside customViews

### ISSUE THREAD

**Issue by madelman** [hackiftekhar/IQKeyboardManager#347]
The ReturnKeyHandler is not working when textFields are inside different views, although the next/previous buttons are working because we are using considerToolbarPreviousNextInViewClass.

This is because IQKeyboardReturnKeyHandler is using responderSiblings and doesn't take into account the View we added with considerToolbarPreviousNextInViewClass.

**Comment by hackiftekhar** [comment]
I should implement something to work with considerToolbarPreviousNextInViewClass in IQKeyboardReturnKeyHandler.

**Comment by krunalbhavsar** [comment]
Hello Hack,

I've been facing same issue with custom textview (a UITextview inside UIView).
Pl. look into this. (I've send you a mail with sample project).

And thanking you for such a nice library.

**Comment by hackiftekhar** [comment]
Will check when get some time. Thanks :)

**Comment by krunalbhavsar** [comment]
I need to implement this into my live project and going to launch on app store next month.
Request you, to spare your valuable time for this issue as well.

Regards...

**Comment by hackiftekhar** [comment]
Cocoapods Updated!
