### ISSUE TITLE
Use of unresolved identifier "IQKeyboardManager"

### ISSUE THREAD

**Issue by lam560** [hackiftekhar/IQKeyboardManager#350]
error in app delegate with line  IQKeyboardManager.sharedManager().enable = true

Created a new clean project to show the error

http://urlz.fr/2E6W

**Comment by hackiftekhar** [comment]
I tested it and probably you choose wrong "Added folders" options while dragging and dropping library. Please choose the suggested one which is showing on below screenshot

![screen shot 2015-11-06 at 2 20 00 pm](https://cloud.githubusercontent.com/assets/3831495/10993147/97778c48-8492-11e5-8650-243799120942.png)

![screen shot 2015-11-06 at 2 27 25 pm](https://cloud.githubusercontent.com/assets/3831495/10993145/976f25bc-8492-11e5-8cf6-a302e5dbf6dc.png)

![screen shot 2015-11-06 at 2 24 44 pm](https://cloud.githubusercontent.com/assets/3831495/10993146/9770fbd0-8492-11e5-8c1b-88f1340ee5cb.png)

**Comment by lam560** [comment]
ok it works now thx, by default the settings was :

**Comment by shizambles** [comment]
Hi,
    I had exactly the same issue and wasted the better part of an evening figuring it out. Turns out my AppDelegate class had membership under tests while none of the IQKeyboardManager related classes didn't. When I unchecked the tests membership in AppDelegate, the issue was resolved. (http://stackoverflow.com/questions/26099111/swift-compiler-error-use-of-unresolved-identifier-name)

Cheers
S

**Comment by Holliwood100** [comment]
I am still so lost.
