### ISSUE TITLE
Keyboard is not dismissing

### ISSUE THREAD

**Issue by houmanka** [hackiftekhar/IQKeyboardManager#351]
Hi guys,
In my ViewController I have got 5 different UITextFileds. 3 of them have delegates. 

I use this to resign the keyboard: 
`IQKeyboardManager.sharedManager().resignFirstResponder()`

However nothing happens no matter what I do. 

Any help would be appreciate it.

**Comment by hackiftekhar** [comment]
Could you please share demo project?
