### ISSUE TITLE
Unnecessary check for 'iOS'; minimum deployment target ensures guard will always be true

### ISSUE THREAD

**Issue by rosevinod** [hackiftekhar/IQKeyboardManager#352]
Please try to remove this warning : 
Unnecessary check for 'iOS'; minimum deployment target ensures guard will always be true

**Comment by hackiftekhar** [comment]
Your minimum iOS deployment target is iOS8, that's why you are getting this error. I can't remove this check because minimum deployment target for library is iOS7.

**Comment by hardikdevios** [comment]
Link #349

**Comment by omerjanjua** [comment]
I have a swift project with a minimum deployment target of 8.0. To avoid getting this warning I removed `IQKeyBoardManagerSwift` and instead used `IQKeyBoardManager`.

I didn't need to do anything else. i.e. add any initialisation code in the `AppDelegate` or add the IQKeyBoardManager header files in my `Bridging-Header.h` file.

**Comment by hackiftekhar** [comment]
Now supporting iOS8 as minimum deployment target.
