### ISSUE TITLE
how to add customize uiview in inputAccessoryView

### ISSUE THREAD

**Issue by zuil7** [hackiftekhar/IQKeyboardManager#353]
Hi,

How can i add a customize uiview in inputaccessoryview. I want to add something like in facebook comment

something like this 

![screen shot 2015-11-07 at 11 24 06 am](https://cloud.githubusercontent.com/assets/1681118/11013302/2b2d0602-8542-11e5-928a-4198c5cd7f4e.png)

I hope you can assist me on this.By the way great library, i always use your library in mostly all my projects.

Thanks!

**Comment by hackiftekhar** [comment]
You can directly set inputAccessoryView in viewDidLoad.

**Comment by zuil7** [comment]
Hi thanks for the quick response. I set it like this in viewdidload. Is this correct? i wanted to show the customize view in input accessory when the viewcontroller is loaded.
 
UIView *viewIns=[[UIView alloc] initWithFrame:CGRectMake(0, 0, 320, 50)];
[viewIns setBackgroundColor:[UIColor whiteColor]];
    
 UITextField *textfield=[[UITextField alloc] initWithFrame:CGRectMake(5, 5, 250, 30)];
 [textfield setBorderStyle:UITextBorderStyleRoundedRect] ;
    
    UIButton *button = [UIButton buttonWithType:UIButtonTypeCustom];
    [button addTarget:self
               action:@selector(aMethod:)
     forControlEvents:UIControlEventTouchUpInside];
    [button setTitle:@"Post" forState:UIControlStateNormal];
    button.frame = CGRectMake(251,5, 100, 30.0);
    
    [viewIns addSubview:textfield];
    [viewIns addSubview:button];
    textfield.inputAccessoryView = viewIns;
    [textfield becomeFirstResponder];

**Comment by hackiftekhar** [comment]
Yes, this is correct.

**Comment by zuil7** [comment]
Hi,
In connection to the previous one i asked before.

In viewdidload i created a uitextfield programmatically and uivew. i added the uitextfield in the uiview and set input accessory the uiview.

When i press the comment button. I wanted to show the keyboard with the customise input accessory. But problem is keyboard is not showing.

Can you assist me on this.

Thanks!

code:
- (void)viewDidLoad {
    [super viewDidLoad];

     self.inputTextField=[UITextField new];
    [self.inputTextField setPlaceholder:@"Comment"];
    [self.inputTextField setBorderStyle:UITextBorderStyleNone];

    UIView *accessorView=[[UIView alloc]initWithFrame:CGRectMake(0, 0, self.tableView.frame.size.width, 40)];
    [accessorView setBackgroundColor:[UIColor blueColor]];
    [self.inputTextField setFrame:CGRectMake(0, 0, 80, 35)];
    [self.inputTextField setInputAccessoryView:accessorView];
}

-(void) commentPost_touchedup_Inside:(id) sender
{
    NSLog(@"%d",[self.inputTextField canBecomeFirstResponder]);
    if([self.inputTextField canBecomeFirstResponder])
    {
        [self.inputTextField becomeFirstResponder];
    }
}

**Comment by hackiftekhar** [comment]
Could you please test same on your device not on simulator?

**Comment by zuil7** [comment]
I have tried it already. I am trying to add a input accessory view with a uitextfield. Then when i press the comment button it show the keyboard with the uiview i have created.

**Comment by zuil7** [comment]
in the device also it did not show the keyboard with the input accessory

**Comment by hackiftekhar** [comment]
I don't think keyboard should hide in this case, could you please share demo project?

**Comment by alizainprasla** [comment]
How to keep showing accessory view when keyboard dismiss? (eg Chat controller example)
