### ISSUE TITLE
Keyboard background color getting messed up on segue

### ISSUE THREAD

**Issue by Ceryni** [hackiftekhar/IQKeyboardManager#354]
Seems like if the keyboard is pulled up and on screen, if you trigger a segue that pushes a VC on a Navigation VC, then go back, if the keyboard never got dismissed, it shows with a bad coloration. I think it might have to do with the background color but unsure.

If you make sure and resign the first responder before segueing and then reassign it, it works fine.

**Comment by hackiftekhar** [comment]
I'm not able to determine if user wants to dismiss keyboard in this case or don't want to dismiss keyboard while moving to another controller. This issue is specifically related to users app functionality and have to handle separately using manual workaround. Makes sense?

**Comment by Ceryni** [comment]
Fair enough, I'll close it out then as it does work if I dismiss the keyboard and reopen it at the end.
