### ISSUE TITLE
canAdjustTextView not working

### ISSUE THREAD

**Issue by vandilsonlima** [hackiftekhar/IQKeyboardManager#355]
Hi,
I changed canAdjustTextView  to true but textview size doesn't change. Should I do anything else?

thanks!

**Comment by hackiftekhar** [comment]
Sometimes it depends, if you also added IQLayoutGuide to the same controller with textView, otherwise you don't need to change anything and it should just work. Please share demo project if you still get any issues.

**Comment by vandilsonlima** [comment]
didn't work. I've created a demo project 
https://github.com/vandilsonlima/JustATest

**Comment by hackiftekhar** [comment]
Looks like you removed repository.
