### ISSUE TITLE
when I use UITextView in UIViewController for iOS7,just like this.

### ISSUE THREAD

**Issue by Monkshae** [hackiftekhar/IQKeyboardManager#356]
```
iOS8 、iOS9 has good performence. But not in iOS7. The following is a screenshot.
I have used a GCPlaceholderTextView Inherited from UITextView ,the code like this:
    _contentTextView = [[GCPlaceholderTextView alloc] init];
    [self.view addSubview:_contentTextView];
    [_contentTextView setHasCloseButton:YES];
    [_contentTextView setFont:[UIFont systemFontOfSize:14]];
    [_contentTextView setPlaceholderColor:RGBCOLOR_HEX(0x9b9b9b)];
    [_contentTextView setTextColor:RGBCOLOR_HEX(0x333333)];
    [_contentTextView mas_makeConstraints:^(MASConstraintMaker *make) {
        make.left.mas_equalTo(10);
        make.top.mas_equalTo(0);
        make.right.mas_equalTo(-10);
        make.bottom.mas_equalTo(0);
    }];
```

![d02923a765cfbd4b95d24dd29f731111](https://cloud.githubusercontent.com/assets/5210838/11113379/5c8f81de-8957-11e5-93f7-6d7856c57130.png)
![70138cafa43a53596d778d5f432fb930](https://cloud.githubusercontent.com/assets/5210838/11113380/5f5048e0-8957-11e5-97c0-53569cd94c76.png)

**Comment by hackiftekhar** [comment]
May be a tintColor issue?

**Comment by Monkshae** [comment]
The problem setPlaceholderColor: ,but why I set PlaceholderColor can lead to this bug  ,Thanks for your suggestion！

**Comment by hackiftekhar** [comment]
Also I didn't find any property placeholderColor to set in UITextField. Could you please share demo so that I can debug it?

**Comment by Monkshae** [comment]
OK，Thank you very much . Actually,my project has contain a old Library called GCPlaceholderTextView. so GCPlaceholderTextView has  placeholderColor property.
 I create a Demo,also I find this problem already exsit when I don't use  GCPlaceholderTextView and its placeholderColor property.
 Demo LInk : https://github.com/Monkshae/JustForTest.

**Comment by hackiftekhar** [comment]
Thanks, will review it when I get some free time.

**Comment by Monkshae** [comment]
OK

**Comment by hackiftekhar** [comment]
@Monkshae I checked demo but it seems work fine when I mapped bottom Layout Guide constraint to IQLayoutGuideConstraint. However if your issue is only happens with iOS 7 devices then FYI I've removed support for iOS 7 and supporting iOS 8 as minimum deployment target. Thanks :)

**Comment by Monkshae** [comment]
OK,Now my project only surport iOS8.
