### ISSUE TITLE
views not scrolled to the correct position without the scroll view

### ISSUE THREAD

**Issue by dingquan** [hackiftekhar/IQKeyboardManager#358]
Hi, first of all, great library and super easy to use!
I'm not sure whether I'm using the library correctly (I'm relatively new to iOS development), but I couldn't get the views to scroll to the proper position without using a scrollview. The popup keyboard is covering part of the input text field if I just put UITextView or UITextField directly into UIView. If I put a scrollview under the root view of the view controller, then add another UIView as the child of the scroll view and put all real UI elements into the container UIView, then it's able to scroll to the correct position when the soft keyboard is brought up. I see the description of this project saying no UIScrollView is needed. Am I missing some steps?

My project is a swift project. I'm using XCode 7.1, minimum deploy target version is iOS 7.0. I'm on cocoapod 0.39.0. And this is my podfile entry for IQKeyboardManager: `pod 'IQKeyboardManager`. `pod install` gives me IQKeyboardManager version `Installing IQKeyboardManagerSwift (3.3.4)`

**Comment by hackiftekhar** [comment]
It should work even if you don't put your content on UIScrollView. Could you please test it on a demo project. If it's still not work then could you please share that demo project with me?

**Comment by dingquan** [comment]
I couldn't reproduce it in a demo project by copy and paste the views and swift code. :(
Not sure what led to the problem in my real project...
I'll update the issue if I figured it out.

**Comment by hackiftekhar** [comment]
I looks like something wrong in your project.
