### ISSUE TITLE
fatal error: unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by qasimmehboob** [hackiftekhar/IQKeyboardManager#364]
My project is complied successfully with some warnings like "Unnecessary check for 'iOS'; minimum deployment target ensures guard will always be true". My minimum deployment target is 9.0 but at run time i am getting this error "fatal error: unexpectedly found nil while unwrapping an Optional value" in IQUIView+Hierarchy.swift file . i attached screen shot of my Xcode. i am using Xcode 7.1 . 
 i used object-c version of IQKeyboardManager it compile and run perfectly but at some stages it don't slide up textField so thats why i moved to swift version of IQKeyboardManager. i followed your instructions to install IQKeyboardManager in my project. Like i imported IQKeyboardManagerSwift in my AppDelegate and enable it in didFinishLaunchingWithOptions method. 

![iqkeyboardmanager_error](https://cloud.githubusercontent.com/assets/5172242/11358653/704774f0-9296-11e5-9535-54f564542504.jpg)

**Comment by qasimmehboob** [comment]
i think i found the issue. I am also enabling this UIResponder+KeyboardCache (https://github.com/mbrandonw/UIResponder-KeyboardCache) in my didFinishLaunchingWithOptions method. When i comment this then IQKeyboardManager run perfectly.

**Comment by hackiftekhar** [comment]
ok, but it's library issue too. I must not unwrap nextResponder by using '!' sign. I removed unwrapping and I think it should work fine now.
