### ISSUE TITLE
"enableInViewControllerClass" maybe is better than "disableInViewControllerClass"

### ISSUE THREAD

**Issue by shannonchou** [hackiftekhar/IQKeyboardManager#367]
I think it's better to set which ViewControllers need IQKeyboard. 4 reasons:
1. I think in most apps, the ViewControllers contains TextField are in the minority. So, we can write less codes.
2. Considering the teamwork. In fact, I just want to use IQKeyboard in my ViewControllers, I don't want to mess up my colleagues'.
3. Considering an exists project. I import IQKeyboard, because I need it now, not the past. I don't want to find out every old ViewController.
4. Considering third-party library. I don't even know how many ViewControllers they have and what their names are.

**Comment by hackiftekhar** [comment]
ok, now suppose another situation where there are many viewControllers so now developer need to write enableInViewControllerClass for each controller, suppose someone added 2 new viewControllers with some textField and forget to add enableInViewController. Now developer need to write enableInViewController again for new viewController's and library will no longer be called 'Codeless Drop in solution'.

**Comment by shannonchou** [comment]
Your assumption is not rigorous. Someone "forget to add enableInViewController" is in the minority, Because his UI does not response correctly. It's easy to notice this issue during the development process. Every developer has responsibility for his own module. He should make sure his code runs well and won't mess up others'. I think it's easier to notice my own module does not runs correctly, but harder to notice others module does not runs correctly.

```
- (void)configIQKeyboard {
    [IQKeyboardManager sharedManager].enable = YES;
    [IQKeyboardManager sharedManager].keyboardDistanceFromTextField = 40;
    [IQKeyboardManager sharedManager].shouldResignOnTouchOutside = YES;
    for (Class class in @[[JCDetailViewController class],
                          [JCUGCDetailViewController class],
                          [JCInnerBrowserViewController class],
                          [JCUGCEditViewController class],
                          [JCMsgReplyViewController class],
                          [JCPrivateMessageDetailViewController class],
                          [JCPhoneSignupFirstViewController class],
                          [JCPhoneSignupSecondViewController class],
                          [JCUserProfileEditorViewController class],
                          [JCPhoneLoginViewController class]]) {
        [[IQKeyboardManager sharedManager] disableInViewControllerClass:class];
        [[IQKeyboardManager sharedManager] disableToolbarInViewControllerClass:class];
    }
}
```
I think this is not a 'Code less Drop in solution'. I am sure there must be more ViewControllers don't need IQKeyboard I haven't find out. 

More than that, I have some third-party libraries in my project, they are compiled in static library. IQKeyboard messed up their UI. I can not find out the ViewControllers, they are not exposed in .h file. This issue is found by our tester. It's hard to notice during my development process.

**Comment by hackiftekhar** [comment]
If IQKeyboardManager conflict with other third party library then please take a look at my comment on read me file. I'm quoting here for your ease

> If IQKeybaordManager conflicts with other third-party library, then it's developer responsibility to enable/disable IQKeyboardManager when presenting/dismissing third-party library UI. Third-party libraries are not responsible to handle IQKeyboardManager.

So you can achieve the same thing with enable property too when presenting/dismissing third party library.

**Comment by shannonchou** [comment]
Thanks @hackiftekhar . Finally I forked this repository and modified it in my way. Then all I need are these:

```
- (void)configIQKeyboard {
    [IQKeyboardManager sharedManager].enable = YES;
    [IQKeyboardManager sharedManager].keyboardDistanceFromTextField = 40;
    [IQKeyboardManager sharedManager].shouldResignOnTouchOutside = YES;
    for (Class class in @[[JCCashAccountViewController class],
                          [JCCashPhoneViewController class]]) {
        [[IQKeyboardManager sharedManager] enableInViewControllerClass:class];
        [[IQKeyboardManager sharedManager] enableToolbarInViewControllerClass:class];
    }
}
```
I think this the real "Code less and Logic less" solution.
I know the solution in your last comment can work well. But it will intrudes my business code. More than that, sometimes it's difficult to find out all the entrances and exits of third-party views. The views maybe transform in different paths. If you forget one, it will cause strange bug.

**Comment by hackiftekhar** [comment]
That's always a great thing to fork repo and modified it in own way. Thanks :)

**Comment by hackiftekhar** [comment]
Closing because, there is no plan to implement such method like ** enableInViewControllerClass**
