### ISSUE TITLE
Hiding status bar feature

### ISSUE THREAD

**Issue by alvinnguyen** [hackiftekhar/IQKeyboardManager#371]
Hi,

Just wondering whether there is a feature to hide the status bar (to prevent it overlapped with pushed up content) if push-up happens?

Cheers,

**Comment by hackiftekhar** [comment]
Currently there is no feature like you need.

**Comment by hackiftekhar** [comment]
Closing because there is no plan to hide status bar feature. Developer should write there custom code in textFieldDidBeginEditing and textFieldDidEndEditing to achieve the same result.
