### ISSUE TITLE
Assingning to 'UIKeyboardType' from incompatible type 'int_Nullable'

### ISSUE THREAD

**Issue by duanhai** [hackiftekhar/IQKeyboardManager#372]
When import  this to my project,the error happens in IQKeyboardReturnKeyHandler.m
Assingning to 'UIKeyboardType' from incompatible type 'int_Nullable'

**Comment by hackiftekhar** [comment]
Perhaps you are using an older Xcode. Please use Xcode 7.1 or newer.

**Comment by fiattt** [comment]
same issue.
xcode: Version 7.3.1 (7D1014)
version:IQKeyboardManager-4.0.4
build error: Assigning to 'UIKeyboardType' from incompatible type 'long _Nullable'
![image](https://cloud.githubusercontent.com/assets/1531440/17211571/cfd6175e-54fc-11e6-817a-4a4c0f5bbd76.png)

I change 
textField.keyboardType = [dict[kIQTextFieldReturnKeyType] integerValue];
to 
textField.keyboardType = (UIKeyboardType)[dict[kIQTextFieldReturnKeyType] integerValue];

and it works
