### ISSUE TITLE
UINavigtionController nested, cannot see keyboard.

### ISSUE THREAD

**Issue by AndreaStevanato** [hackiftekhar/IQKeyboardManager#373]
Hi, I have a "first" navigation controller with a view controller that have a container view with another navigation controller, in the view controllers of the second controller navigation I cannot see the keyboard if I enable IQKeyboardManager (i see a blank spaces istead the keyboard).

-->"First" NavigationController 
      ----> ViewController with ContainerView 
            ------> "Second" Navigation Controller  
                  --------> **ViewController with table view** <== Keyboard not appear (blank spaces)

**Comment by hackiftekhar** [comment]
Are you testing on simulator?

**Comment by hackiftekhar** [comment]
@AndreaStevanato Any updates?
