### ISSUE TITLE
toolbar become black while pop animating

### ISSUE THREAD

**Issue by MichaelYNWA** [hackiftekhar/IQKeyboardManager#374]
A keyboard is always showed in a viewcontroller in my project.
The toolbar becomes black while pop animating.

IQKeyboardManager 3.3.4
xcode7.1 ios9.0.2

**Comment by MichaelYNWA** [comment]
![img_0027](https://cloud.githubusercontent.com/assets/3070162/11582397/5f1e629c-9a89-11e5-9260-f58b3f13eacf.PNG)

**Comment by MichaelYNWA** [comment]
Here is demo.
[KeyboardTest.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/51665/KeyboardTest.zip)

**Comment by hackiftekhar** [comment]
Updated README.md regarding the issue. Hope you'll find a workaround there. FYI, it's iOS issue.

**Comment by iamleetvin** [comment]
Not perfect fix it，like this:

#import <IQToolbar.h>


[IQToolbar appearance].backgroundColor = UIColorFromRGB(0xf0f0f0);
