### ISSUE TITLE
Small Done button

### ISSUE THREAD

**Issue by mateuszmackowiak** [hackiftekhar/IQKeyboardManager#376]
![img_5250](https://cloud.githubusercontent.com/assets/1284783/11627291/a6e08bc0-9ce9-11e5-8361-c5a5b36c8fec.png)

Without any additional setting in any view controllers if there is only one text field in the screen the default done button (of the inputAccessoryView toolbar) is very small.

**Comment by hackiftekhar** [comment]
ok, could you please share demo project so that I can test? Are you not using english as your primary language in your project?
