### ISSUE TITLE
Bug: IQKeyboardManagerSwift was compiled with optimization - stepping may behave oddly; variables may not be available.

### ISSUE THREAD

**Issue by shuijinliuxi** [hackiftekhar/IQKeyboardManager#378]
Add the UITextfiled on UIApplication.sharedApplication().keyWindow:
UIApplication.sharedApplication().keyWindow?.addSubview(textfiled);

EXC_BAD_INSTRUCTION at :
public func viewController()->UIViewController? {
        
        var nextResponder: UIResponder? = self
        
        repeat {
            nextResponder = nextResponder?.nextResponder()!
            
            if let viewController = nextResponder as? UIViewController {
                return viewController
            }
            
        } while nextResponder != nil
        
        return nil
    }

**Comment by hackiftekhar** [comment]
Optional unwrapping is fixed. But that's a bad programming example of adding a textField directly to a UIWindow. You must add it to a UIViewController's view

**Comment by ShannonMYang** [comment]
not work
