### ISSUE TITLE
How to cover the UITabBar

### ISSUE THREAD

**Issue by shuijinliuxi** [hackiftekhar/IQKeyboardManager#379]
The keyboard is at the top of UITabBar. How can I do make the keyboard cover the UITabBar ?

**Comment by hackiftekhar** [comment]
Could you please share screenshot?

**Comment by shuijinliuxi** [comment]
http://pan.baidu.com/s/1bou7s3l

**Comment by hackiftekhar** [comment]
It looks like, you do something wrong. It's not library mistake. Are you sure you get correct behaviour while removing library?
