### ISSUE TITLE
Change text field with tag not work

### ISSUE THREAD

**Issue by JonyMateos** [hackiftekhar/IQKeyboardManager#380]
Hello, thanks for this great library.

I have the views that are shown in image, selected in green. Inside **view1** are two text fields (with tag 1 and 2), inside **view3** are five text fields (tags 3, 4, 5, 6 and 7, respectively). 

I need to pass from the text field with value **"Suárez" (tag 2)** to text field **"esteban" (tag 3)**.

I tried it with some methods like the next but I have not gotten it working:
```
[[IQKeyboardManager sharedManager] setToolbarManageBehaviour:IQAutoToolbarByTag]; 
```
```
[[IQKeyboardManager sharedManager] considerToolbarPreviousNextInViewClass:[EditarPerfilViewController class]];
```

<img width="349" alt="tags" src="https://cloud.githubusercontent.com/assets/6951670/11684406/a64306a0-9e71-11e5-8fb3-33dc4c581fb4.png">

**Comment by hackiftekhar** [comment]
You should pass the custom view class in method and not the ViewController's class.
