### ISSUE TITLE
Activating hardware keyboard in simulator exposes massive gap in Demo application

### ISSUE THREAD

**Issue by fatuhoku** [hackiftekhar/IQKeyboardManager#381]
![simulator screen shot 9 dec 2015 17 24 19](https://cloud.githubusercontent.com/assets/430233/11693208/7c0f8abe-9e9b-11e5-9d2b-894d40ef2720.png)

**Comment by hackiftekhar** [comment]
I think, It will not be an issue with real devices.

**Comment by hardikdevios** [comment]
@fatuhoku this wont happen in real device i am sure

**Comment by AndrewSB** [comment]
@hackiftekhar any way we can remove this from the simulator as well? Would be a more fully featured library

**Comment by AndrewSB** [comment]
and also won't require the countless developers who run into this issue on the simulator to frantically search the issues on this repo to check on whether or not this will be an issue

**Comment by hackiftekhar** [comment]
Could you please let me know how can I fix the simulator blank gap issue?

**Comment by AndrewSB** [comment]
@hardikdevios @hackiftekhar why doesn't the issue appear on a device? Why does it only appear in the simulator?

**Comment by mthuong** [comment]
If user use a hardware keyboard to connect with the iPad and this issue still happen on the device.
Any suggestion to fix this?

**Comment by hackiftekhar** [comment]
@mthuong Do you know a way to determine if a hardware keyboard is attached with iOS device?
