### ISSUE TITLE
Ambiguos use of 'subscript' (Xcode 7.1)

### ISSUE THREAD

**Issue by rjjohnpatrickcruz** [hackiftekhar/IQKeyboardManager#383]
Hi,

Any help?? Im currently getting error in the library. Please see my screenshot.

Thanks.

<img width="931" alt="screen shot 2015-12-14 at 1 53 52 pm" src="https://cloud.githubusercontent.com/assets/5118009/11773854/591e04ae-a26a-11e5-92de-422f9de5327a.png">

**Comment by rjjohnpatrickcruz** [comment]
Hello, Any help?

**Comment by hackiftekhar** [comment]
Im running Xcode 7.1 too but I'm not getting such errors. Are you sure you are on Xcode 7.1?

**Comment by lucasleongit** [comment]
got the same issue

**Comment by lucasleongit** [comment]
I believe I got these compile errors after I added Realm framework to my project.
Did a simple workaround - changed this infoDict[kIQTextField] -> infoDict.objectForKey(kIQTextField) and now all works fine I think.

**Comment by hackiftekhar** [comment]
I'm not getting such errors. I was on Xcode 7.1 and just upgraded to Xcode 7.2 but didn't get any issues in both Xcode.

**Comment by Tueti** [comment]
I agree with @lucasleongit - after I added the Realm framework, I got the same compile errors. The workaround does the trick, it's working ever since.
I am on Xcode 7.2
