### ISSUE TITLE
How to set the layoutguidconstraint in the super view?

### ISSUE THREAD

**Issue by gabrieltva** [hackiftekhar/IQKeyboardManager#384]
Hello,

When I add a subview in a UIScrollView, and tap the UITextField and active the Keyboard, the content of the Subview scroll up, but this hide the UITextField.

So, I want scroll up the content of Super view (all content of app).

Can you help me?

![captura de tela 2015-12-17 as 15 11 32](https://cloud.githubusercontent.com/assets/5474849/11876355/7bb82996-a4d0-11e5-8ff1-035adf549cf9.png)
![captura de tela 2015-12-17 as 15 11 28](https://cloud.githubusercontent.com/assets/5474849/11876356/7bc59b6c-a4d0-11e5-9cd2-6f28fe7bafd4.png)

**Comment by hackiftekhar** [comment]
Did you tried adding all your content on scrollView?

**Comment by gabrieltva** [comment]
No, but I try init just the UIView (init with the Xib file) in the ScrollView and work.

But when I add the ViewController with the UIView (init viewcontroller with the initWithNibName function) that is the result. The ScrollView (the light blue part) scroll when tap on textfield, but hide the same. 

Exist a function to I block the scroll move of the IQKeyboardManager in the subview, and active just the superview IQLayoutGuideConstraint?

**Comment by hackiftekhar** [comment]
IQLayoutGuideConstraint is a workaround (If you must need LayoutGuideContraint in your view hierarchy). It's not a good approach to use IQLayoutGuideConstraint frequently, it must be used for rare cases. You should also try to avoid add bottom layout constraints to your view hierarchy except if it's extremely necessary.
