### ISSUE TITLE
IQLayoutGuideConstraint & SizeClasses

### ISSUE THREAD

**Issue by nairpic** [hackiftekhar/IQKeyboardManager#386]
Hi,
I don't know if I'm doing something wrong or this is a scenario that is not yet implemented. I'm using SizeClasses because I have a different design for portrait/landscape and iphone/ipad for the LoginScreen. My issue is that I'm not able to make all to work together because after I set IQLayoutGuideConstraint to iPhone portrait(Compact:Regular) and change to landscape mode(Any:Compact) and set again IQLayoutGuideConstraint the setUp will not work anymore for the portrait situation. Do you have any suggestions? I found your library very easy to use and I really hope that I'm doing something wrong. Thanks for your help and your hard work.

**Comment by hackiftekhar** [comment]
I'm not sure if you are doing something wrong. But I can say that if you are reassigning IQLayoutGuideConstraint on portrait/landscape mode, then it may be the issue.

**Comment by nairpic** [comment]
Is there a way to have it functional on both orientations? At this moment works or on portrait or in landscape.

**Comment by hackiftekhar** [comment]
Hmm, may be you can try to resign textField on orientation change and then assign the new IQLayoutGuideConstraint as you are doing now.

**Comment by nairpic** [comment]
worked great ... had some problems with the frames while rotating the screen with the keyboard active, but manage to fix them ... thanks for your suggestion
