### ISSUE TITLE
install sogou typewriting

### ISSUE THREAD

**Issue by JxbSir** [hackiftekhar/IQKeyboardManager#387]
it work not well.   please fix it

![7 pic](https://cloud.githubusercontent.com/assets/9983806/11897681/a4106c9e-a5cc-11e5-8d50-b74be49065ee.jpg)

**Comment by hackiftekhar** [comment]
Please explain

**Comment by JxbSir** [comment]
1.Cursor in third TextField.
2.sogou keyboard did show.
3.The keyboard's toolbar has a blank area on top , resulting in IQKeyboardManager calculation is wrong
4.we can not see text in third TextField

**Comment by hackiftekhar** [comment]
ok, could you please share demo?

**Comment by JxbSir** [comment]
ok，i will create a demo

**Comment by JxbSir** [comment]
sorry, it's my fault. I coded some error autolayout.  so sorry

**Comment by yuyedaidao** [comment]
@JxbSir 你怎么修改的，望不吝赐教
