### ISSUE TITLE
how to disable classes in swift 2.1

### ISSUE THREAD

**Issue by raz969** [hackiftekhar/IQKeyboardManager#389]
I'm trying to disable a separate class in swift 
IQKeyboardManager.disableInViewControllerClass(CLASSNAME)
in app delegate but it won't work, is this a bug or am i doing something wrong?

**Comment by hackiftekhar** [comment]
Looks like you are doing right. If you don't need toolbar too, then there is another method to disable toolbar in a view controller. Is there any other issue you are getting?

**Comment by szxinyu** [comment]
@raz969 disableInViewControllerClass is renamed to disableDistanceHandlingInViewControllerClass.
And you can try my code, just replace the classes in the list. 
let list: [AnyClass] = [Class1.self, Class2.self, Class3.self]
        for aClass in list{
            IQKeyboardManager.sharedManager().disableToolbarInViewControllerClass(aClass)
            IQKeyboardManager.sharedManager().disableDistanceHandlingInViewControllerClass(aClass)
        }

PS: My code doesn't work for me!!! LOL. Please, can someone tell me how to disable the toolbar and distance in a ViewController!!!

**Comment by szxinyu** [comment]
@hackiftekhar Hey I found a BUG!!!. My code above worked for v3.3.5, but it does not work for the later version that has toolbarTintColor property. The disableDistanceHandlingInViewControllerClass in newer version might be broken somewhere

**Comment by hackiftekhar** [comment]
I'm not sure but the demo project works fine for me. Don't know why you are getting issues.

**Comment by hackiftekhar** [comment]
If you can provide me a sample demo project then I'll be able to debug the issue.

**Comment by mortenholmgaard** [comment]
I have the same problem i objective C with disableDistanceHandlingInViewControllerClass and the overall setEnabled both is not working

**Comment by hackiftekhar** [comment]
So @mortenholmgaard If you could provide me a demo then it would be ok for me to debug the issue.

**Comment by mortenholmgaard** [comment]
Sorry - I just figured out that there where som conflicting code that made it look like this problem. I will remove my comment

**Comment by hackiftekhar** [comment]
So if you figured out the reason, then could you post some details here, so that other devs can get an idea about there problems?

**Comment by mortenholmgaard** [comment]
It had nothing to do with this problem - I just had some code that also animated some views up when the keyboard was shown and confused it to be IQKeyboardManagers work.
