### ISSUE TITLE
When trying to manually drag and drop IQKeyboardManagerSwift into xcode, i get "Use of unresolved identifier" in AppDel

### ISSUE THREAD

**Issue by acerts04** [hackiftekhar/IQKeyboardManager#390]
Hello,
Forgive me if this is not the correct place to post this, but i have been struggling with trying to fix this problem. I have been trying to make use of IQKeyboardManagerSwift, but can not enable it in AppDel. Each time i drag the IQKeyboardManagerSwift directory from the demo project into my project, i can not write the code to enable it. I always get a "Use of unresolved identifier error". 

What i did try and do was just drag and dropping the contents of the IQKeyboardManagerSwift directory into my project and that had worked, the code to enable it was finally recognized, but at runtime there were just a lot of errors. 

I also tried dragging and dropping in another project and had the exact same problem. Am i doing something wrong or missing a step? Any help would be appreciated as i am stuck and out of ideas on how to fix this, Thank you.

**Comment by hardikdevios** [comment]
1. Put use_frameworks!
2. Pod 'IQKeyboardManagerSwift'
3. Pod install 
4. import IQKeyboardManagerSwift
5. Add this in didFinishLaunching - > QKeyboardManager.sharedManager().enable = true

#### you are done
##### I hope this will be the easiest things just give it try with PODS buddy

**Comment by hackiftekhar** [comment]
If you are not using pods and are trying to integrate swift library in objective-c project, then you need to use a bridging header file.

**Comment by acerts04** [comment]
Thank you for your replies guys. I figured out the reason why when i drag and dropped it was not being recognized in code and that was because i was choosing Create folder references instead of Create groups. Now it is working.

I did want to use pods, but had some issues with it as well. So i guess i will have to keep coming back here and re-importing whenever updates are released?

**Comment by hackiftekhar** [comment]
Thanks for the updates that you figured out the reason
