### ISSUE TITLE
Disable IQKeyboard in specific view controller using swift

### ISSUE THREAD

**Issue by karthikasdas** [hackiftekhar/IQKeyboardManager#391]
Hi @hackiftekhar ,

First of all Thank you very much for this library. 

I have an issue of disabling IQKeyboard in particular view controller, I am using swift and used the following code:- IQKeyboardManager.sharedManager().disableInViewControllerClass(CircleTableViewController)
where CircleTableViewController is the class in which IQKeyboard is to be disabled. But IQKeyboard is still showing in the CircleTableViewController. Please help!

Thanks,
Karthika

**Comment by hackiftekhar** [comment]
What is showing in CircleTableViewController, the toolbar one?

**Comment by karthikasdas** [comment]
Yes the tool bar one.

On Sunday, 20 December 2015, Mohd Iftekhar Qurashi <notifications@github.com>
wrote:

> What is showing in CircleTableViewController, the toolbar one?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackiftekhar/IQKeyboardManager/issues/391#issuecomment-166125823>
> .
>


-- 
Sent from Gmail Mobile

**Comment by hackiftekhar** [comment]
There is a separate class level method to disable toolbar.

**Comment by raj-android-ios** [comment]
there is no such method "disableInViewControllerClass"

**Comment by warisappify** [comment]
Kindly use following method instead

`IQKeyboardManager.sharedManager().disabledToolbarClasses = [ViewControllerA.self, ViewControllerB.self]`

**Comment by hackiftekhar** [comment]
Thanks @warisappify

**Comment by PrajeetShrestha** [comment]
Hi. This is not working in iOS 11?

**Comment by hackiftekhar** [comment]
What exact behaviour you need @PrajeetShrestha ?
