### ISSUE TITLE
AdjustFrame function causes crashes.

### ISSUE THREAD

**Issue by tranngoclinh88** [hackiftekhar/IQKeyboardManager#392]
I'm using your framework and get some crashes.
Here is the detail.

<img width="963" alt="screen shot 2015-12-22 at 2 34 54 pm" src="https://cloud.githubusercontent.com/assets/1511264/11950269/6bdf0142-a8b9-11e5-8345-ee27bade7b77.png">

**Comment by hackiftekhar** [comment]
I'm not sure what is going wrong. May be something with your view's frame. Because the error message is related to a bounds with Nan value

**Comment by tranngoclinh88** [comment]
I'm using your framework with RETableViewManager. Sometime it crashes here. :(

**Comment by hackiftekhar** [comment]
Not sure, please share demo and steps to reproduce

**Comment by hackiftekhar** [comment]
@tranngoclinh88 Do you have any updates for demo project?

**Comment by tranngoclinh88** [comment]
Sorry, I can not provide you the demo.
This bug seldom happens and I don't know the case to reproduce.

**Comment by hackiftekhar** [comment]
So do you can't provide a demo because you don't know the actual reason. right? May be it's because you are using RETableView. If you can't reproduce then should I close this issue or do you have any plans to provide a demo here?

**Comment by tranngoclinh88** [comment]
Thank @hackiftekhar for your attention. I will close this ticket.
