### ISSUE TITLE
Toolbar will execute animation twice, while I set UIScrollViewKeyboardDismissMode on UIScrollView

### ISSUE THREAD

**Issue by jiyee** [hackiftekhar/IQKeyboardManager#394]
If I set keyboardDismissMode=UIScrollViewKeyboardDismissModeOnDrag on UIScrollView, when keyboard is shown, I drag the scroll view, the toolbar will execute animation twice (call keyboardWillHide method), and the _animationDuration = 0.25. the toolbar behaves like scrolling to bottom of frame first, then scrolling to disappear.

I want to ask if it is a bug or by design.

**Comment by hackiftekhar** [comment]
could you please share demo, so that I can understand what exactly you are trying to explain?

**Comment by jiyee** [comment]
https://github.com/jiyee/IQKeyboardManagerDemo.git

I make this demo, scroll to bottom, focus the textField, popup the keyboard, then drag the scroll view, the toolbar behave like the mention before.

**Comment by hackiftekhar** [comment]
I tried it without the library and I found the same issue without my library too, so I think it's the iOS issue and not producing by the library.

**Comment by CrazySugar** [comment]
You can workaround this by using a category of UIScrollView:

```
@implementation UIScrollView (BUFAutoHideKeyboard)
- (UIScrollViewKeyboardDismissMode)keyboardDismissMode {
            [[IQKeyboardManager sharedManager] resignFirstResponder];
            return UIScrollViewKeyboardDismissModeNone;
}
```
