### ISSUE TITLE
Keyboard always cover TextField

### ISSUE THREAD

**Issue by lbb631160503** [hackiftekhar/IQKeyboardManager#395]
Project login interface is inside the ScrollView the ImageView ImageView and set the View inside the View inside is input box use IQKyboard tripartite library Can only stand the first input box not obscured But the second input box will be obscured, please how to solve

**Comment by hackiftekhar** [comment]
Could you please share demo project?

**Comment by hackiftekhar** [comment]
@lbb631160503 Any updates regarding demo project?
