### ISSUE TITLE
IQKeyboardManager conflicts with AGi18n

### ISSUE THREAD

**Issue by abutalha** [hackiftekhar/IQKeyboardManager#396]
I am using AGi18n library to localize my app. When IQKey... is used AGi18n is not updating localized strings for Xib files. 

I need both, any clue please?

**Comment by hackiftekhar** [comment]
Thanks , will check.

**Comment by hackiftekhar** [comment]
I'm having difficulties with building a project with AGi18n, @abutalha  could you please share a demo project.

**Comment by hackiftekhar** [comment]
Any updates?

**Comment by abutalha** [comment]
I have not tested it again quite a while, will check now and share a demo project soon.

**Comment by hackiftekhar** [comment]
Thank You!

**Comment by hackiftekhar** [comment]
@abutalha Have you written a demo for me?
