### ISSUE TITLE
Doesn't work with AutoLayout

### ISSUE THREAD

**Issue by Nici57** [hackiftekhar/IQKeyboardManager#397]
I am getting this when trying to input something on small devices. I understand that I have to tell IQKeyboardManager about my constraints, but how do I get the popup?
![simulator screen shot 27 12 2015 21 03 03](https://cloud.githubusercontent.com/assets/2128396/12011785/3b0d7062-acdd-11e5-901a-53d8948a3ce2.png)

**Comment by hackiftekhar** [comment]
Make sure you haven't added layout guide constraints which directly or indirectly related to the textfields.

**Comment by Nici57** [comment]
All existing constraints are needed though. If I remove them every object just flies around on the device

**Comment by Nici57** [comment]
Don't I need to add IQLayoutGuideConstraints? But how do I set Multiple?

**Comment by hackiftekhar** [comment]
You can't set multiple top layout guide atm. You can set only one. However if you remove top layout guide and pin your view's with superview then it would be fine I think.
