### ISSUE TITLE
If i manually imported IQKeyboarManagerSwift into my project, any easy way to update?

### ISSUE THREAD

**Issue by acerts04** [hackiftekhar/IQKeyboardManager#398]
Hey all,
If i did not use pods and manually imported into my project, in order to get the latest version of IQKMS do i need to delete the folder in my project then drag and drop the updated one here from Git each time an update is pushed out?

**Comment by hackiftekhar** [comment]
Yes, you have to manually do the things if you are not using cocoapods.

**Comment by acerts04** [comment]
Thanks hack, that is what i figured, i just wanted to make sure.
