### ISSUE TITLE
Wrong ContentSize when TableView is a subview of ViewController.view

### ISSUE THREAD

**Issue by maimake** [hackiftekhar/IQKeyboardManager#399]
I have a tableview added as a subview in a ViewController.view, and the content size of tableView is wrong.

I lookup your code, and I don't know why you set the content size the same as scrollView.frame.size at the end 

```objc
-(void)adjustFrame
{
    ...

    //Maintaining contentSize
    if (_lastScrollView.contentSize.height<_lastScrollView.frame.size.height)
    {
        CGSize contentSize = _lastScrollView.contentSize;
        contentSize.height = _lastScrollView.frame.size.height;
        _lastScrollView.contentSize = contentSize;
    }
    
}
```

when I removed these lines , I got the right content size. 

Need your help, Thanks

**Comment by hackiftekhar** [comment]
This code is written because when scrollView content size is less than it's width and then keyboard comes then user should be able to scroll it's content.

**Comment by DmitryArbuzov** [comment]
But you adjust contentInset.bottom for this purpose. I can't understand meaning of changing contentSize.

**Comment by hackiftekhar** [comment]
@DmitryArbuzov When your scrollView has zero content height but still have a textField, then we got issues when user tries to move scrollView by fingers, and it doesn't handle well with contentInset.bottom property. That's why I wrote this. Do you have any better solution?

**Comment by DmitryArbuzov** [comment]
@hackiftekhar I think, if scrollView has zero content height but still have a textField, it's mean that layout is incorrect. It's not a problem of your library.
And it leads another bug, as i already said.

**Comment by hackiftekhar** [comment]
@DmitryArbuzov I realised that setting contentSize leads to some issues reported in #485 #487 #496, looks like removing that code 28b2d9c0ee8169bd6c4cc3dfbdca8f272d059f7c fixed those issues .
