### ISSUE TITLE
Can you provide an example of how to use the addDoneOnKeyboardWithTarget?

### ISSUE THREAD

**Issue by cbwarz** [hackiftekhar/IQKeyboardManager#40]
Hello,

I'm looking for an example on how to receive events from the Done button, can you please post one?

I have read that is supposed to be done with addDoneOnKeyboardWithTarget, but i had search and can't figure out how.

Thanks for your time.

Carlos

**Comment by 1791422018** [comment]
hey，I am a Chinese ，I want to know the toolbar's Done is a button？ or item？？？ I want to make the “Done” become Chinese

**Comment by hackiftekhar** [comment]
It's `UIBarButtonItem`.

**Comment by 1791422018** [comment]
okay,thank you
