### ISSUE TITLE
how can i use in the situation of a textview as big as the device screen

### ISSUE THREAD

**Issue by michaelmou** [hackiftekhar/IQKeyboardManager#401]
it done't work in a screen big textview. how can i set the manager?

**Comment by hackiftekhar** [comment]
I need to figure out how should we deal with full screen textView's.

**Comment by michaelcameron** [comment]
+1 I just ran into this situation as well

**Comment by kevinrenskers** [comment]
Same here. How do you handle the keyboard on a full screen textview? Right now I am disabling IQKeyboardManager on this view controller and doing the work myself, not exactly ideal.

**Comment by hackiftekhar** [comment]
Added a workaround for UITextView when UITextView size is as big as device screen.

**Comment by cristinaITdeveloper** [comment]
@hackiftekhar I read the full-screen textview guide, but it's with the stoyboard, how can I do it if I use xib?

It works well enough for me, but when I dismiss the keyboard, the textview remains under the navigation bar, and it does not return to its place, how can I fix it?

![schermata 2018-07-02 alle 10 58 54](https://user-images.githubusercontent.com/11472348/42154791-f65d5a80-7de6-11e8-82b0-5dcba0731b8e.png)


Thank you

**Comment by hackiftekhar** [comment]
@cristinaITdeveloper Which version of library you are using right now?

**Comment by cristinaITdeveloper** [comment]
The latest version!
