### ISSUE TITLE
Disable the toolbar

### ISSUE THREAD

**Issue by annietan91** [hackiftekhar/IQKeyboardManager#403]
I have face a problem to disable the toolbar after a added it manually, the code shown below:
- (IBAction)editPressed:(id)sender {
    self.messageTextView.editable = YES;
    [self.messageTextView becomeFirstResponder];
    [self.messageTextView addDoneOnKeyboardWithTarget:self action:@selector(setEditableTextView)];
}

- (void) setEditableTextView {
    self.messageTextView.editable = NO;
    [self.messageTextView resignFirstResponder];

// How can I disable(hide) the toolbar?? so that it won't appear when I highlight the word in textview.
}

**Comment by hackiftekhar** [comment]
According to your code, toolbar should simply show while keyboard is present and you are writing something. After dismissing keyboard toolbar should not be displayed. Is this not the actual behaviour in your project?

**Comment by annietan91** [comment]
I have remove the code: "self.messageTextView.editable", I make it enable to edit and now this issue is fix. Thank you for reply.
