### ISSUE TITLE
The ScrollView ContentOffset Will Wrong When ScrollView.ContentSize is biger than Screen,and the TextField is in the second screen

### ISSUE THREAD

**Issue by Yck-Dakucha** [hackiftekhar/IQKeyboardManager#404]
hello @hackiftekhar : 
  There's a scrollView in my project; and its contentSize is   

    CGFloat scHeight = [UIScreen mainScreen].bounds.size.height;
    CGFloat scWidth = [UIScreen mainScreen].bounds.size.width*2;
    self.scrollView.contentSize = CGSizeMake(scWidth, scHeight); 

  my textField is in the second screen,  when the textFieldDidBeginEditing,  ScrollView.contentOffset  Y is corrent ,but the X will be Zero; we'll see the screen pop to FirstScreen when I touch the textField in the second Screen. 
   my English is poor ,sorry.

**Comment by Yck-Dakucha** [comment]
The First Screen ,
<img width="315" alt="2016-01-07 2 30 02" src="https://cloud.githubusercontent.com/assets/12741176/12163769/4dc8b16e-b54b-11e5-95b1-71b2397b1c81.png">
I Click Button <下一步> the scrollView set contentOffset to secondScreen,Now I touch the First TextFiled
<img width="310" alt="2016-01-07 2 30 19" src="https://cloud.githubusercontent.com/assets/12741176/12163770/4e02a234-b54b-11e5-9707-7153a273e807.png">
The ScrollView Back to First Screen ,Wrong is Here!
<img width="312" alt="2016-01-07 2 30 37" src="https://cloud.githubusercontent.com/assets/12741176/12163772/4e3f2a74-b54b-11e5-893b-322182f0fbaa.png">
I click Done .It cannot Back to Second Screen also.
<img width="309" alt="2016-01-07 2 30 48" src="https://cloud.githubusercontent.com/assets/12741176/12163773/4ee411ce-b54b-11e5-81bc-6d351173b2c2.png">

**Comment by hackiftekhar** [comment]
Moving roght/left is not supported yet. That's not a very common case.

**Comment by Yck-Dakucha** [comment]
Thanks，its my fault because the project is my friend write,it's a Demo so he did not add constraints in the subView, it's well done when i add the constraints ,sorry to my careless and thank you very much.
