### ISSUE TITLE
IQKeyboard manager issue when using navigation bar

### ISSUE THREAD

**Issue by amrit42087** [hackiftekhar/IQKeyboardManager#405]
I am using IQKeyboard manager for my ios App. When I first launch the app, I tap on a button which unhides a view that contains a textfield. On tapping the textfield the IQKeyboard manager shifts the whole view upwards so that the textfield is not hidden by the keyboard. But when I navigate to some other view and come back to the previous view. Now I click the button to unhide a view containing the text field. The IQKeyboard manager doesnot shift the view upwards. I cannot understand the cause. Any suggestions will be appreciated.

**Comment by hackiftekhar** [comment]
Could you please share femo so that I can take a look.

**Comment by hackiftekhar** [comment]
*demo

**Comment by amrit42087** [comment]
Thanks for the efforts mate. But I got the solution. Actually I was disabling the iqkeyboard manager in another class. Reenabling it in viewwillappear fixed my problem. Really appreciate your help.

**Comment by hackiftekhar** [comment]
If you like to disable it for a viewController then you can also take a look at `disableInViewControllerClass:` or `disableDistanceHandlingInViewControllerClass` method. It's more easier than enabling/disabling in viewWillAppear/viewWillDisappear.
