### ISSUE TITLE
Question: Previous/Next button with complex view hierarchy

### ISSUE THREAD

**Issue by a4arpan** [hackiftekhar/IQKeyboardManager#406]
Hi

I have many text fields on my VC thats why I am using scroll view with following view hierarchy 

VC-> UIView -> Scroll View -> UIView -> TextField
VC-> UIView -> Scroll View -> UIView -> TextField
VC-> UIView -> Scroll View -> UIView -> TextField
-------------------------------------------------- -> TextField
-------------------------------------------------- -> TextField
-------------------------------------------------- -> TextField
-------------------------------------------------- -> TextField
VC-> UIView -> Scroll View -> UIView -> TextField

I even tried created a SpecialView (subclass of UIView) as suggested on read.me to have this hierarchy

VC-> UIView -> Scroll View -> SpecialView -> UIView -> TextField
VC-> UIView -> Scroll View -> SpecialView -> UIView -> TextField
VC-> UIView -> Scroll View -> SpecialView -> UIView ->TextField
----------------------------------------------------------------------- -> TextField
----------------------------------------------------------------------- -> TextField
----------------------------------------------------------------------- -> TextField
----------------------------------------------------------------------- -> TextField
VC-> UIView -> Scroll View -> SpecialView -> UIView -> TextField

here are the screenshots:
 
http://cl.ly/44140u2v3Y2Z
http://cl.ly/27161E090k1T

I tried everything but Previous/Next buttons are not showing, Please suggest.

Thanks in Advance

**Comment by hackiftekhar** [comment]
I'm not sure what is wrong with your project, but I think this workaround should work. Could you please share a simple demo demonstrating the issue?

**Comment by daviddelmonte** [comment]
I just installed your control. Many many thanks. It’s brilliant.

David

**Comment by hackiftekhar** [comment]
@a4arpan Do you have any updates regarding the demo project?

**Comment by hackiftekhar** [comment]
@a4arpan Any updates?

**Comment by hackiftekhar** [comment]
Your single specialView should be on top of all textField, there shouldn't be multiple specialView.
