### ISSUE TITLE
Turning off auto correct & inputting capitalized strings

### ISSUE THREAD

**Issue by RyanKim01** [hackiftekhar/IQKeyboardManager#408]
Hi,
I have other 3rd party class which is a subclass of UITextField which initializes textfields and I input below settings:
```
    self.autocorrectionType = UITextAutocorrectionTypeNo;
    self.autocapitalizationType = UITextAutocapitalizationTypeAllCharacters;
```
However, it does not apply the change and I assume this is due to settings in IQKeyboardManager.
In IQKeyboardManagerSwift pod, is there a place where I can make above changes globally over all textfields??

**Comment by hackiftekhar** [comment]
Currently there is no functionality to do the same. I think it is developer responsibility to choose these settings for each textfield separately.
