### ISSUE TITLE
customizing Done button 

### ISSUE THREAD

**Issue by ihomam** [hackiftekhar/IQKeyboardManager#41]
Is there a way to change title of done button or put and image for the button instead of text, by accessing the button object!?

i just need to change it's name from done to hide. no need to change the functionalty 

if i used IQToolbarAddition category methods like addRightButtonOnKeyboardWithText:target:action
i will add my custom button to each textfield.. 

just thinking of doing this to every text filed give me pain :(

**Comment by WinKhantAung** [comment]
I tried to disable toolbar for specific views sth like IQKeyboardManager.sharedManager().disabledToolbarClasses(LoginViewController);.
But it response with an error message "Cannot call value of non-function type '[UIViewController.Type]'.
Any suggestion pls....

**Comment by hackiftekhar** [comment]
You have to use append method to disabledToolbarClasses, you are using this incorrectly.
