### ISSUE TITLE
IQKeyboardManager not working with share extension

### ISSUE THREAD

**Issue by Rotemy** [hackiftekhar/IQKeyboardManager#410]
Hello,

I'm trying to use IQKeyboard with my share extension and for `UIApplication.sharedApplication()` I get "sharedApplication() is unavailable: use view controller based solution where appropriate instead".

Is there anything I can do?

**Comment by hackiftekhar** [comment]
Share Extension is a kind of different thing and not a normal project. You shouldn't use IQKeyboardManager in share extension.

**Comment by Kingofkode** [comment]
Will support for extensions come soon?

**Comment by hackiftekhar** [comment]
Nope, because library is created to support general projects only, there are no plans to extend it for share extensions and other extensions. Thanks :)
