### ISSUE TITLE
Done button change language

### ISSUE THREAD

**Issue by PanMluvci** [hackiftekhar/IQKeyboardManager#411]
Swift: I have an app with different language and i wanna to change string in Done button to "Hotovo". How can I achieve that?

**Comment by hackiftekhar** [comment]
Currently there is no functionality to directly change Done button text, however it will be automatically change depend on the language set in your phone.

**Comment by PanMluvci** [comment]
do i need to somehow set it ? because it keeps being in english...i am developing a Czech app

**Comment by hackiftekhar** [comment]
Unfotunately there is no easy way to do this currently. But I'll add a support later on.

**Comment by burakkoray** [comment]
Hi
Do we have same option in objective c? Is there any chance to change done title ?
Thanks

**Comment by PanMluvci** [comment]
From what i have to do is enable multi language support to get DONE in Czech language. Because it is ENGLISH by default.

**Comment by hackiftekhar** [comment]
There is a `toolbarDoneBarButtonItemText` property and you can change done title by setting a text to the property. It's available in swift and obj-c both.

**Comment by ShivSK3** [comment]
There is a toolbarDoneBarButtonItemText property and you can change done title by setting a text to the property. It's available in swift and obj-c both.

In which version is the above line available?
