### ISSUE TITLE
There is a problem when it's working in StackView.

### ISSUE THREAD

**Issue by yu0winter** [hackiftekhar/IQKeyboardManager#412]
I add textView to stackview.But the textview can not scroll to the right position.

1)this is the view which is added to the stackView
@interface LCMovingTextView : UIView
@property (nonatomic, strong) IWTextView *textView;
@end
2) I set here:
- (void)viewWillAppear:(BOOL)animated{
    [super viewWillAppear:animated];
    [IQKeyboardManager sharedManager].enable = YES;
    [IQKeyboardManager sharedManager].enableAutoToolbar = YES;
    [IQKeyboardManager sharedManager].keyboardDistanceFromTextField = 20;
}

**Comment by hackiftekhar** [comment]
ok, so above was your configuration, but what is the actual problem?

**Comment by yu0winter** [comment]
I add a textView In stackView and then input text into the textView. The cursor will be cover by the keyboard Instead of adjusting the position of cursor.

**Comment by hackiftekhar** [comment]
ahh, ok then I need investigate the internal functionality of StackView.

**Comment by yu0winter** [comment]
(⊙o⊙)… Still Thank you very much!

**Comment by clooth** [comment]
Any progress on this?

**Comment by hackiftekhar** [comment]
Not yet @clooth, I didn't work with UIStackView till now. But thanks for the reminder.

**Comment by hackiftekhar** [comment]
I checked a demo project with UIStackView with UITextView and I didn't observe any problem with that. It is working fine according to me. There may be something wrong with your code.
