### ISSUE TITLE
Thanks for your work, this is a good demo。I find  a little Bug at using it

### ISSUE THREAD

**Issue by stackJolin** [hackiftekhar/IQKeyboardManager#417]
the memory is not the free  when I test it。I don't know what the question。Next is my operation：
1. click textField and make it the first responder
2. click screen and regist the first responder
3. recycle  1,2

the first memory is 37.0M,and after the opetaions,the memory is always rating

**Comment by hackiftekhar** [comment]
@stackJolin I tested it with my demo and I don't find anything much regarding memory issue, if you could provide any demo then it would be great. There may also be a chance that your project is increasing the memory and not the library?

**Comment by hackiftekhar** [comment]
If you could provide any then upload your demo and reopen this issue
