### ISSUE TITLE
Tab ordering or disabling left and right arrows

### ISSUE THREAD

**Issue by girishnair12345** [hackiftekhar/IQKeyboardManager#418]
How do I disable right and left arrows,

I have a layout where there is a textfield at the top and in the bottom there are two other textfields. When the keyboard rises the left and right arrows do not navigate properly. I even shifted the views but could not fix it

It would be nice if some tab ordering could be added or disabling the right and left arrows for some time

**Comment by hackiftekhar** [comment]
You can add a toolbar manually to your textfield to customise your own behaviour. If library found any customised textfield.inputAccessoryView then library doesn't affect that one.

**Comment by hackiftekhar** [comment]
You could also try to play with `toolbarPreviousNextAllowedClasses`.
