### ISSUE TITLE
TextView : Doesn't work with AutoLayout 

### ISSUE THREAD

**Issue by AntMarq** [hackiftekhar/IQKeyboardManager#420]
Hello !

I activate "AutoLayout" in MainSwift.storyboard and I have tried in your demoProject (swift) the left textfield in TextViewSpecialCaseViewController.

With a very long text in the textView, the canAdjustTextView doesn't work. A part of this textview is behind the keyboard.

Can you make an exemple for this in your demo project please ? 

If you need any further information, feel free to contact me.
Thank you in advance.

**Comment by hackiftekhar** [comment]
Are you facing similar issue like #401?

**Comment by hackiftekhar** [comment]
Most of the time `canAdjustTextView` will not work with autolayout, this was build to support Autoresizing and setting frame features. It would be much harder to write a workaround for AutoLayout.
