### ISSUE TITLE
[UIKeyboardlmpl shouldShowCandidataBar] crash bug

### ISSUE THREAD

**Issue by myafer** [hackiftekhar/IQKeyboardManager#421]
I have a  [UIKeyboardlmpl shouldShowCandidataBar] crash bug in my app. Maybe because of IQKeyboardManager
![image](https://cloud.githubusercontent.com/assets/8944018/12633741/0b4eefbe-c5af-11e5-9f98-4e1e6e005b39.png)

**Comment by hackiftekhar** [comment]
Not sure, UIKeyboardImpl is an internal class, and library doesn't use any private API.

**Comment by myafer** [comment]
Thank U

**Comment by myafer** [comment]
I felt that library would affect the internal class function, this bug is hard to find out for me.

**Comment by hackiftekhar** [comment]
I don't think it affect any internal class function, you are the only one who reported this issue, so probably it looks like your app related issues.

**Comment by Batxent** [comment]
i had the same issue

**Comment by myafer** [comment]
I think that you had used this code : 
`
@implementation UIScrollView (UITouch)

- (void)touchesBegan:(NSSet *)touches withEvent:(UIEvent *)event {
    
    [[self nextResponder] touchesBegan:touches withEvent:event];
    [super touchesBegan:touches withEvent:event];
}

-(void)touchesMoved:(NSSet *)touches withEvent:(UIEvent *)event {
    
    [[self nextResponder] touchesMoved:touches withEvent:event];
    [super touchesMoved:touches withEvent:event];
}

- (void)touchesEnded:(NSSet *)touches withEvent:(UIEvent *)event {
    
    [[self nextResponder] touchesEnded:touches withEvent:event];
    [super touchesEnded:touches withEvent:event];
}

@end
`

When people use handwritten Chinese keyboard and associate words the app will crash.

So you should't use this code in your APP.
