### ISSUE TITLE
Use of undeclared  identifierr 'IQ_IS_IOS7_OR_GREATER'

### ISSUE THREAD

**Issue by wff-** [hackiftekhar/IQKeyboardManager#422]
update IQKeyboardManager version 3.3.6

error 

![iq](https://cloud.githubusercontent.com/assets/8870484/12639186/9c80eb12-c5dd-11e5-9cf5-a3fd730117db.png)

**Comment by hackiftekhar** [comment]
This is no longer required in IQKeyboardManager that's why it is removed. Probably you are using IQ_IS_IOS7_OR_GREATER in your project.

**Comment by wff-** [comment]
thanks
