### ISSUE TITLE
when keyboard show,header view cover cell

### ISSUE THREAD

**Issue by RockyYe1993** [hackiftekhar/IQKeyboardManager#424]
hi,hackiftekhar.
I pod iqkeyboard into my project.
these days,i find a problem.and i still can't slove it.
i put a textfield into a cell.when i begin editing the keyboard show.and tableview scorll. it's right.

but the header view scoll too.and the header view cover the cell.

i don't know how to slove it . so if you have some workable solution please tell me .

thank u. and forgive my poor English

![Uploading 屏幕快照 2016-01-29 上午12.23.35.png…]()
![Uploading 屏幕快照 2016-01-29 上午12.23.45.png…]()
![Uploading 屏幕快照 2016-01-29 上午12.25.00.png…]()

**Comment by RockyYe1993** [comment]
<img width="375" alt="2016-01-27 5 31 34" src="https://cloud.githubusercontent.com/assets/13750602/12650773/0d5cdaa8-c61f-11e5-9edc-8bfbf87fc6dc.png">
<img width="371" alt="2016-01-29 12 23 45" src="https://cloud.githubusercontent.com/assets/13750602/12650796/2cb85d6e-c61f-11e5-9c8c-a08fb40e879a.png">
<img width="375" alt="2016-01-29 12 23 35" src="https://cloud.githubusercontent.com/assets/13750602/12650825/494b09cc-c61f-11e5-9023-84b25d4940c6.png">

**Comment by hackiftekhar** [comment]
I'm unable to understand the issue from screenshot you shared. Could you please point out the area in screenshot where the actual issue is?

**Comment by RockyYe1993** [comment]
<img width="372" alt="2016-01-29 12 25 00" src="https://cloud.githubusercontent.com/assets/13750602/12664718/f8661418-c66c-11e5-9ea4-0fc01ed838be.png">
<img width="375" alt="2016-01-29 12 23 35" src="https://cloud.githubusercontent.com/assets/13750602/12664721/fdbeaf24-c66c-11e5-8dee-302db1345a9b.png">

look the area where i mark. head view cover the cell .

thank for your reply.

hope to talk to u again.thank you .

**Comment by hackiftekhar** [comment]
It looks like you are using group tableView. If Yes then could you please share demo. Otherwise it's default behaviour of plain tableView and probably your headerView has transparent background.

**Comment by hackiftekhar** [comment]
Do you have any updates on this?
