### ISSUE TITLE
UITextField in the keyWindow, make crash

### ISSUE THREAD

**Issue by zhmch0329** [hackiftekhar/IQKeyboardManager#425]
I have a UITextField in a view, I must add the view to KeyWindow. But it crash. 

How fix it?

**Comment by hackiftekhar** [comment]
I don't know how you would fix, I don't have much details about the reason of crash to answer your question. If you could get the reason of crash then I can help you with this.

**Comment by hackiftekhar** [comment]
I tested it, and it doesn't crashed. but it doesn't work well. Just as standard, you should add your textfields in one of viewController's view.
