### ISSUE TITLE
 Tell me how to change my name from the button cancel?

### ISSUE THREAD

**Issue by habr** [hackiftekhar/IQKeyboardManager#429]
Please tell me how to change name from the button "Сancel"? in Swift

**Comment by hackiftekhar** [comment]
Which cancel button you are talking about?

**Comment by habr** [comment]
`messageText.addCancelDoneOnKeyboardWithTarget(self, cancelAction: Selector("cancelAction"), doneAction: Selector("doneAction"))`    -   cancelAction

**Comment by habr** [comment]
https://www.evernote.com/l/ABFrFcDQkFBBM5V3Yk3QEsXpr6q6XTwM0ts

**Comment by hackiftekhar** [comment]
You can use different merhod something similar to 'addRightLeft....' To set customised title on your left and right button.

**Comment by habr** [comment]
messageText.addRightLeftOnKeyboardWithTarget(self, leftButtonTitle:"Foto", rightButtonTitle:nil,  leftButtonAction: Selector("funcFoto"), rightButtonAction: nil, titleText: nil)   

Please tell me how to correct?

**Comment by hackiftekhar** [comment]
It looks like you are doing correct.

**Comment by habr** [comment]
Thank you for your work!
