### ISSUE TITLE
How to open IQKeyboardManager black window in Interface Builder

### ISSUE THREAD

**Issue by mrigdon** [hackiftekhar/IQKeyboardManager#431]
How do I open this:

![screen shot 2016-02-11 at 12 00 29 pm](https://cloud.githubusercontent.com/assets/7377110/12988779/3e24c4fa-d0b7-11e5-974b-9cb54c9ab572.png)

in the interface builder?

**Comment by hackiftekhar** [comment]
Could you please re-word your question? I'm unable to understand what is the actual issue.

**Comment by hackiftekhar** [comment]
Any updates? Do you still have anything for me?

**Comment by senseluo** [comment]
I think @mrigdon is asking how to make "IQKeyboardManager" panel showing on storyboard. This is also what I am searching for the answer.
 
I just noticed in the [screenshot](https://raw.githubusercontent.com/hackiftekhar/IQKeyboardManager/v3.3.0/Screenshot/BottomLayoutGuideIndirectMapping.jpg) you provided, there is a black panel named 'IQKeyboardManager', how and where open this panel? looks my storyboard doesn't has it.

**Comment by hackiftekhar** [comment]
Ahh, that's thr title of my ViewController, that's why you are seeing it. That is just the title of My ViewController and nothing more.

**Comment by senseluo** [comment]
thanks
but still in my view controller I can not see an outlets about IQLayoutGuideConstrainint 
I am using 4.0.1 swift version .

**Comment by senseluo** [comment]
Oh~~~~ I got it, just located inside connections inspector.
