### ISSUE TITLE
Manually switching between TextFields

### ISSUE THREAD

**Issue by piv199** [hackiftekhar/IQKeyboardManager#433]
**Prerequisites:** AutoLayout enabled, IQKeyboard enabled, keyboardDistanceFromTextField = 15
**Workflow:** Have a number of different TextFields one by one from top to down. Click second(first not causing sliding) TextField, IQKeyboard adjusts TextField above IQKeyboard. The third field is a bit visible above keyboard. When I tap on third TextField, IQKeyboard doesn't adjust scrollView for this TextField. If it's done with return key everything works fine.

Is it only my problem?

**Comment by hackiftekhar** [comment]
Did you figured-out what was the actual issue?

**Comment by piv199** [comment]
@hackiftekhar actually, not yet, but it works in your demo app.

I have UIView, but when I change to UIScrollView it behaves as it should, hovewer UIScrollView ignores my layout constraints. I use PageMenu and my UIViewController is inside this controller. Resigning and Becoming fistResponder in code gives unexpected result.

**Comment by hackiftekhar** [comment]
Demo storyboard isn't using auto layout. Also for scrollview, we must take extra care about constraints.

**Comment by piv199** [comment]
@hackiftekhar just get a bit of test and totally sure that it's caused by CAPSPageMenu. It's working without it. So need some more tests with childViewControllers and IQKeyboardManager.

**Comment by hackiftekhar** [comment]
ok, let me know if you found any issues with library and then you need my help.
