### ISSUE TITLE
Update prev/next buttons on the fly

### ISSUE THREAD

**Issue by AlexEdunov** [hackiftekhar/IQKeyboardManager#434]
I have two text fields that depend on each other.

By default dayTextField is disabled until I select month:

![simulator screen shot 17 feb 2016 20 23 43](https://cloud.githubusercontent.com/assets/1535700/13118587/00fad5ac-d5b6-11e5-9e3a-9a664bc5fc84.png)

When I select month I update "enabled" property of dayTextField and next button should be enabled too:

![simulator screen shot 17 feb 2016 20 23 50](https://cloud.githubusercontent.com/assets/1535700/13118588/00fae13c-d5b6-11e5-96ea-c7ad8778551b.png)

Is there the way to update next button on the fly without resignFirstResponder/becomeFirstResponder calling?

**Comment by hackiftekhar** [comment]
Currently there is no way to do that, but your scenario is so generic. I'll add something soon.
