### ISSUE TITLE
Can we get the toolbar's bar button item to obey UIAppearance?

### ISSUE THREAD

**Issue by gearoidoceallaigh** [hackiftekhar/IQKeyboardManager#435]
Great library!

Its great that they keyboard comes with a Done button by default but 'Done' is in black text by default. Is it possible to get this to obey the changes made via UIAppearance?

Thanks!

**Comment by hackiftekhar** [comment]
Nope, it isn't possible to work with UIAppearance. However there is `toolbarTintColor` property. You can use it to change done/next/previous button color.
