### ISSUE TITLE
ReturnKeyHandler issue

### ISSUE THREAD

**Issue by cjorth** [hackiftekhar/IQKeyboardManager#436]
hi hack, i have a views hierarchy like that:
UIView 
 |
CustomView - textfield  (account) 
CustomView - textfield (password)

i setup the IQKeyboardReturnKeyHandler like the sample, and set IQToolBar enabled, press the previous/next button on the toolbar that works well, but i press the next button in the  keyboard when 'accountTextfield' is firstResponder, there is very quick moment 'passwordTextField' became firstResponder and resign soon. i found the 'passwordTextField' shouldEndEditing excutes when it's didBeginEditing done. i don't know why it is. need your help. thanks!

**Comment by hackiftekhar** [comment]
It looks like a code logic issue. Could you please share a demo project?

**Comment by cjorth** [comment]
@hackiftekhar thank u hack, I have rechecked my code and make sure it's a issue caused by KVO in ReactiveCocoa when i used the textField.rac_textSignal.
`RAC(viewModel, inputText)     = self.textField.rac_textSignal;`
When I comment this, all things wonderful.
But I don't like the delegate methods to handle it, do you have any better solution?

**Comment by pengxianhe** [comment]
@ghost can you tell me how did you solved this problem
