### ISSUE TITLE
disableInViewControllerClass isn't visible

### ISSUE THREAD

**Issue by gearoidoceallaigh** [hackiftekhar/IQKeyboardManager#437]
Working with the ObjC library, the disableInViewControllerClass method call doesn't seem visible from the singleton. 

At the moment I have to enable/re-enable for each of my VCs but it would be nice to do this up front in the AppDelegate (or perhaps we could provide an optional array to the initialiser for IQKeyboard?) like it says in the docs.

Thanks!

**Comment by hackiftekhar** [comment]
This method is replaced by `disableDistanceHandlingInViewControllerClass` method.

**Comment by hackiftekhar** [comment]
Updated readme, thanks :)
