### ISSUE TITLE
Navigation Bar keeps hiding when keyboard opens

### ISSUE THREAD

**Issue by DantePuglisi** [hackiftekhar/IQKeyboardManager#438]
First of all, I wanted to thank you for this awesome library and I'd hope you could help me with this.
I have a `UITableViewController` with a TextView at the bottom to send new messages. I've tried implementing this code:
```
-(void)loadView
{
    UIScrollView *scrollView = [[UIScrollView alloc] initWithFrame:[[UIScreen mainScreen] bounds]];
    self.view = scrollView;
}
```
but it doesn't work (tableView dissapears and navigation bar keeps going away).
Do you have any idea what I can do if I'm using `UITableViewController`? Thanks

**Comment by hackiftekhar** [comment]
UITableViewController already have their own internal mechanism to move textField out of the way. Library doesn't do anything for moving view only if textFields are inside UITableViewController. Unfortunately you have to implement keyboard notifications and need to write your own logic.

**Comment by hackiftekhar** [comment]
FYI, If you are going to implement something like a chat screen, then generally I would suggest you to disable library in that particular viewController and write your own logic instead.

**Comment by hackiftekhar** [comment]
I've added a workaround `Working with Chat Screen UITableView:-` for Chat Style Screens. Please check README

**Comment by AamirSk** [comment]
I am facing navigation bar hiding issue for long with this library.
Recently I was working with "searchController" & there also I faced the same issue. I found a fix for it by setting flag.

            self.searchController.hidesNavigationBarDuringPresentation = false

I know this is not exact solution for this library but it might be helpful to sort out the issue.
