### ISSUE TITLE
sometime hide toolbar on textfield

### ISSUE THREAD

**Issue by parthibl** [hackiftekhar/IQKeyboardManager#442]
how can i hide/remove toolbar only for some textfield?

**Comment by parthibl** [comment]
i got the solution by:
IQKeyboardManager.sharedManager().enableAutoToolbar = false

but return key not works (mean could not called textfield did end editing event i set delegate for that).

**Comment by hackiftekhar** [comment]
If you want to remove toolbar for some textField the you can add a blank UIView as as textfield inputAccessoryView.

**Comment by parthibl** [comment]
i already tried by setting up mytextfield.inputaccesory = nil.

On Wed, Feb 24, 2016 at 7:43 PM, Mohd Iftekhar Qurashi <
notifications@github.com> wrote:

> If you want to remove toolbar for some textField the you can add a blank
> UIView as as textfield inputAccessoryView.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackiftekhar/IQKeyboardManager/issues/442#issuecomment-188271927>
> .
>



-- 

*By Regards,*
*Parth Dabhi*

**Comment by hackiftekhar** [comment]
FYI, I mean `[[UIView alloc] init]` as a blank UIView, not nil value.

**Comment by hackiftekhar** [comment]
If you want to work with return key then you can look at `IQKeyboardReturnKeyHandler` class.

**Comment by parthibl** [comment]
Thank you! @hackiftekhar
