### ISSUE TITLE
Error message '_BSMachError: (os/kern) invalid capability (20) on Textview

### ISSUE THREAD

**Issue by bluelabeldeveloper1** [hackiftekhar/IQKeyboardManager#444]
If I installed IQKeyboardManager in my project, on press of UITextview when keyboard opens and while typing, I'm getting following two error on my console. Whereas for UITextfield its working fine.
_BSMachError: (os/kern) invalid capability (20)
_BSMachError: (os/kern) invalid name (15)

**Comment by piv199** [comment]
yeah, got this message also, but can't confirm that it's caused by IQKeyboardManager

**Comment by hackiftekhar** [comment]
It's not due to IQKeyboardManager and probably a warning message. However there is nothing wrong functionality-wise.
