### ISSUE TITLE
Misplaced After In-Call Status Bar Disappeared

### ISSUE THREAD

**Issue by madao1237** [hackiftekhar/IQKeyboardManager#446]
## After:    ![after](http://i11.tietuku.com/63774cfee9ae85de.png)

**Comment by madao1237** [comment]
you can see a black bar on top of screen after In-Call StatusBar disappear

**Comment by hackiftekhar** [comment]
Could you please share steps, I tried but it's not reproducing with me.

**Comment by hackiftekhar** [comment]
@madao1237 Could you please update me with demo and exact steps to reproduce?

**Comment by hackiftekhar** [comment]
@madao1237 Could you please let me know steps to reproduce it?

**Comment by madao1237** [comment]
It appeared with version of 3.3.5. And I tried to reproduce it with the latest version, but that can not work anymore.
In simulator, the steps to reproduce is:
```
 *  command +Y(Show In-Call StatusBar)  
 *  Pop  a keyboard
 *  command + Y(Hide StatusBar) 
 *  Resign the keyboard 
```

Here is My code：
```
IQKeyboardManager *manager = [IQKeyboardManager sharedManager];
    manager.enable = YES;
    manager.shouldResignOnTouchOutside = YES;
    manager.shouldToolbarUsesTextFieldTintColor = NO;
    manager.shouldFixTextViewClip = NO;
    manager.keyboardDistanceFromTextField = 50;
    manager.enableAutoToolbar = YES;
```
But here I found some little problems in latest version,follow the steps in your demo:
```
* pop a keyboard
* command + Y
* Click the "Done" button
```
It will show like this:
![little problem](http://7xp8z6.com1.z0.glb.clouddn.com/16-6-24/16035457.jpg)
The black space won't disappear till you hide the In-Call StatusBar

Another problem is also connecting with the In-Call StatusBar:
```
 *  command +Y(Show In-Call StatusBar)  
 *  Pop  a keyboard
 *  command + Y(Hide StatusBar) 
```
Then notice the textfield that you want to focus on will move  back to the origin place.

These problems are not particularly serious.
An easy way to solve these problems is to register UIApplicationWillChangeStatusBarFrameNotification,
and resign your keyboard firstly after received the notification.
Hope you could solve these.

Thank you!

**Comment by hackiftekhar** [comment]
Thanks for the steps. It will really help me to debug the issue. Thanks @madao1237 for great help. I hope I can fix this issue.
