### ISSUE TITLE
Use considerToolbarPreviousNextInViewClass with Former library

### ISSUE THREAD

**Issue by gbmiranda** [hackiftekhar/IQKeyboardManager#447]
You can use the Class "considerToolbarPreviousNextInView" with Former component for iOS?

Link: https://github.com/ra1028/Former/issues

**Comment by hackiftekhar** [comment]
I think you should read `Warning` section of README file. It clearly says `If IQKeybaordManager conflicts with other third-party library, then its developer responsibility to enable/disable IQKeyboardManager when presenting/dismissing third-party library UI. Third-party libraries are not responsible to handle IQKeyboardManager.` So you should disable IQKeyboardManager while working with `Former`.
