### ISSUE TITLE
A Lot of Code Being Deprecated in Swift 3

### ISSUE THREAD

**Issue by aabosh** [hackiftekhar/IQKeyboardManager#450]
After updating to Xcode 7.3 beta 5, the Issue Navigator is showing 46 issues from the IQ library of various methods and parameters being deprecated.

Really appreciate your work with the IQ suite, I love it!

**Comment by hackiftekhar** [comment]
Thanks for letting me know, I'll try to upgrade to Xcode 7.3 as soon as possible.

**Comment by aabosh** [comment]
Thank you!

**Comment by hackiftekhar** [comment]
I can see Xcode 7.3 is still in beta. I can update master branch when Apple release a public version of Xcode 7.3.

**Comment by aabosh** [comment]
Awesome, sounds good.
