### ISSUE TITLE
ReturnKeyHandler "Next" with custom view configuration

### ISSUE THREAD

**Issue by web-melt** [hackiftekhar/IQKeyboardManager#451]
Hi,
when using the `ReturnKeyHandler` in conjunction with `considerToolbarPreviousNextInViewClass`
the previous / next buttons on the toolbar work, but the ReturnKeyHandler defaults to "Return" and closes 
the keyboard.

With 2 fields in the same superview the ReturnKeyHandler works as expected (Next & Return Buttons w/ appropriate functionality)

Any extra configuration neccessary to make ReturnKeyHandler use the same logic as the toolbar?

**Comment by hackiftekhar** [comment]
Could you please share demo code so that I can debug it.

**Comment by hackiftekhar** [comment]
Any updates?

**Comment by web-melt** [comment]
Haven't gotten the chance to build a demo yet. Will do as soon as I can

**Comment by hackiftekhar** [comment]
Thanks :)

**Comment by web-melt** [comment]
Demo repository:
https://github.com/web-melt/IQKeyboardManager451-demo

while assembling the demo one thing caught my eye. It seems to work fine as long as all fields are in the same view. As soon as the view hierarchy becomes multi leveled the returnkeyHandler doesnt work anymore. 

If there is anything I can help you with, lemme know.

**Comment by younanjo** [comment]
@hackiftekhar  This happens with `Demo.xcodeproj` as well. In settings turn on "Should Resign on touch outside" and then in "CustomView Example"  switch on "Consider toolbar..." and try tapping the return key. It doesn't work and keyboard remains open. 

Have you had a chance to look into this?

**Comment by hackiftekhar** [comment]
Not yet, but will look soon

**Comment by hackiftekhar** [comment]
I checked your demo and I found nothing with your demo neither IQKeyboardManager nor any textFields. Could you please check your demo project again?

**Comment by hackiftekhar** [comment]
However I checked your issue with my demo project and looks like it works fine for me. Could you please try with the latest source code of github? If still doesn't work let me provide demo. Your demo project was totally a new project and nothing else.

**Comment by web-melt** [comment]
I'm sorry, did it in a rush, and obviously failed to commit -.-
Anyhow, added the debug code

**Comment by hackiftekhar** [comment]
You are using an older version of pod which is 3.3.4. This issue is already fixed with 4.0.0 and available via pod.
