### ISSUE TITLE
Wrong distance

### ISSUE THREAD

**Issue by yuyedaidao** [hackiftekhar/IQKeyboardManager#453]
![ib 4 j h 3pgb myi2 ue](https://cloud.githubusercontent.com/assets/6354958/13808894/46ef9e3c-eba3-11e5-9180-372ea5199213.jpg)
![de03e4ef-0839-4fd3-8ec2-c81bfa9e35dc](https://cloud.githubusercontent.com/assets/6354958/13808908/55beac5a-eba3-11e5-8f54-aefed5d80770.png)

as you see, the distance between keyboard and toolbar is wrong. Please help me. thx.

**Comment by hackiftekhar** [comment]
Could you please share a demo project? Could you please also let me know your device language.

**Comment by yuyedaidao** [comment]
The demo is yours,but the keyboard in first picture is [Sougou](https://appsto.re/cn/mWOS2.i),the keyboard in second picture is Simplified Chinese jiu gong ge.
![简体拼音九宫格](https://cloud.githubusercontent.com/assets/6354958/13838208/223a4b50-ec4d-11e5-84df-7756325a9071.png)
  My device language is Simplified Chinese.

**Comment by yuyedaidao** [comment]
Sorry,My fault!

**Comment by hackiftekhar** [comment]
No Problem
