### ISSUE TITLE
with UITabBar controller its not working properly 

### ISSUE THREAD

**Issue by komaldaudia** [hackiftekhar/IQKeyboardManager#454]
Hello Kidly check the attched image and help me out, how can i avoid blank part at the bottom of the screen. this UI issue comes only with the IQKeyBoardManager, if i remove this class and use native keyboard issue is not coming.

![simulator screen shot 16-mar-2016 11 37 32 am](https://cloud.githubusercontent.com/assets/11155520/13809203/9775f09a-eb8f-11e5-9e70-c065f1828319.png)

**Comment by hackiftekhar** [comment]
You'll not see this issue with real devices. Believe me that's not an issue.

**Comment by basilmariano** [comment]
Hi,

Im also encountering this issue now and it is also showing in real device.
![simulator screen shot feb 7 2017 12 17 09 am](https://cloud.githubusercontent.com/assets/5466582/22656304/ea9924be-eccd-11e6-8726-248eefa95040.png)

**Comment by basilmariano** [comment]
Hi,

Im also experiencing this issue. I tried in my real device and the issue is still there. Any advice?

**Comment by hackiftekhar** [comment]
Then can you please share demo project so that I can take a look?
