### ISSUE TITLE
Remove "DONE" from specific screen but unknown textfield

### ISSUE THREAD

**Issue by beingshashi** [hackiftekhar/IQKeyboardManager#456]
Hey,

my question looks similar to [question](https://github.com/hackiftekhar/IQKeyboardManager/issues/177)

but there is some difference.
i have smooch called , third party library into my ios project .which creates its own "CHAT UI" , so i have no idea about chat textfield name , so how do i remove "done" toolbar when i click on this chat  text field.

Thanks,

**Comment by hackiftekhar** [comment]
You should enable/disable IQKeyboardManager when presenting/dismissing third party library UI. Keeping IQKeyboardManager Enable for Third Party Library UI is discouraged. Please check **Warning** section in README documentation.

**Comment by vaibhavmane** [comment]
IQKeyboardManager.sharedManager().enable = false you can do like in your particular viewcontroller
