### ISSUE TITLE
shouldChangeCharactersInRange delegate method not calling eventhough delegate is set for textfield

### ISSUE THREAD

**Issue by RMK19** [hackiftekhar/IQKeyboardManager#457]
Hi im using IQKeyboardManagerSwift in my project and in viewDidLoad() i just have the code like below
        passwordTextField.delegate = self
        IQKeyboardManager.sharedManager().enable = true
        keyboardManager = IQKeyboardReturnKeyHandler(controller: self)
        keyboardManager.lastTextFieldReturnKeyType = UIReturnKeyType.Done

but the textfield delegate methods are not calling

**Comment by hackiftekhar** [comment]
If you are using IQKeyboardReturnKeyHandler then you should set IQKeyboardReturnKeyHandler delegate to self. and not the passwordTextField.delegate.
