### ISSUE TITLE
Changing toolbarDoneBarButtonItemText issues

### ISSUE THREAD

**Issue by Intrexion** [hackiftekhar/IQKeyboardManager#459]
When changing the toolbarDoneBarButtonItemText property, the next button in the toolbar does not function. It correctly recognizes the position of the textField (and displays the next/previous buttons right) but both the next and previous buttons go to the previous textfield.

**Comment by hackiftekhar** [comment]
Could you please share a demo project?

**Comment by hackiftekhar** [comment]
Any updates?

**Comment by mccannmax** [comment]
I have this happening as well.  It's on a complex view added via `considerToolbarPreviousNextInViewClass`

**Comment by hackiftekhar** [comment]
Could you please a demo project?

**Comment by mccannmax** [comment]
Will work on one

**Comment by mccannmax** [comment]
[IQKeyboardManagerDemo.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/198239/IQKeyboardManagerDemo.zip)

**Comment by mccannmax** [comment]
very simple example.  Should move upper left to upper right to lower left to lower right.
When setting `toolbarDoneBarButtonItemText` the nexting does not work.

**Comment by hackiftekhar** [comment]
I found that this has been already fixed approx 1 month ago with this commit 4143c4b3eba4b7cba5b67a78a3c0ac4caec6e46d. This fix will be available with next release. Thanks :)

**Comment by mccannmax** [comment]
Awesome, cheers!

**Comment by smindia1988** [comment]
Put below line of code in your appDelegate:

IQKeyboardManager.shared.toolbarDoneBarButtonItemText = "Done".localiz()
