### ISSUE TITLE
Initialize `IQKeyboardManager` with specific scope

### ISSUE THREAD

**Issue by sdduursma** [hackiftekhar/IQKeyboardManager#460]
Currently enabling the `IQKeyboardManager` singleton enables the behaviour for the whole application. IQKeyboardManager conflicts with some existing code in our application. The result is that we have to manually go through the application to find the conflicts and disable IQKeyboardManager for the relevant view controllers. 

I think it would be useful if an `IQKeyboardManager` instance could be initialized with a specific scope, like a view or view controller, to ensure that no conflicts arise in other parts of the application.

**Comment by hackiftekhar** [comment]
Then probably you should reverse your process. Disable in AppDelegate. Then enable/disable only when you need. So this will only work in the scope where you enabled this.

**Comment by sdduursma** [comment]
Thanks for the quick reply. Yes that would improve our situation, but then you still need to remember to disable in `viewDidDisappear(_:)` in every view controller that is using IQKeyboardManager.

**Comment by hackiftekhar** [comment]
So how do you see by "Scope"? How IQKeyboardManager knows the scope? As a developer, you are able to think about your custom "Scope" for your project according to your requirement. But it would be hard for IQKeyboardManager to guess where your custom start and where it ends. Could you please suggest a way to guess custom scope by IQKeyboardManager?

**Comment by sdduursma** [comment]
I think it would be useful if the scope could be limited to a view or a set of views. I imagine an instance of `IQKeyboardManager` could be initialised with a view or a set of views. `IQKeyboardManager` would then iterate over the views and their subviews to find all `UITextField` and `UITextView` instances and subscribe to notifications from only those instances. That way the behaviour is applied explicitly to a specific scope, i.e. the set of views.

**Comment by hackiftekhar** [comment]
I'm working on it and you'll see `enabledDistanceHandlingClasses`, `enabledToolbarClasses`, `toolbarPreviousNextDeniedClasses` like properties soon.

**Comment by sdduursma** [comment]
That's great, thanks

**Comment by hackiftekhar** [comment]
This has been implemented with v4.0.2.
