### ISSUE TITLE
Next / Previous not working propery?

### ISSUE THREAD

**Issue by karthisiva** [hackiftekhar/IQKeyboardManager#462]
I am having more than ten textfields in **UITableview**, i can move next by pressing next icon, for example i am in 5 row and pressed done button the keyboard getting released and again i am trying to start from 5 row by pressing 5 UITextfield, here i cannot go previous like 4,3,2,1...but previous icon showing enable  mode.what would be the problem? is this issue?

**Comment by liulishuo** [comment]
Do you refresh your tableView when your textfield end editing?

**Comment by karthisiva** [comment]
i didn't refresh tableview
- (void)textFieldDidEndEditing:(UITextField *)textField{
    [textValues replaceObjectAtIndex:textField.tag withObject: textField.text];

}

**Comment by liulishuo** [comment]
may be we are not the same issue, you try this
![2016-03-21 16 40 13](https://cloud.githubusercontent.com/assets/6081684/13913625/a15dca40-ef83-11e5-96e7-1b357af87bfa.png)

**Comment by karthisiva** [comment]
@liulishuo thanks for reply..Its not working.

**Comment by hackiftekhar** [comment]
Could you please provide me sample code?

**Comment by karthisiva** [comment]
@hackiftekhar i did not add any code for this.
#pragma mark UITextField Delegates
-(BOOL)textFieldShouldReturn:(UITextField *)textField {
    if ([isSign isEqualToString:sign_in]) {
        checkTextFieldsCount=2;
    }else{
        if ([isSign isEqualToString:sign_up] && [isSingType isEqualToString:sign_up_barber]) {
            checkTextFieldsCount=10;
        }else{
            checkTextFieldsCount=5;
        }
    }
    return YES;
}
- (BOOL)textFieldShouldBeginEditing:(UITextField *)textField {
 
    return YES;
}

- (void)textFieldDidEndEditing:(UITextField *)textField{
    [textValues replaceObjectAtIndex:textField.tag withObject: textField.text];

}

**Comment by karthisiva** [comment]
@hackiftekhar any solution?

**Comment by hackiftekhar** [comment]
@karthisiva Could you please share a demo project? I'm unable to understand why you are getting this issue?

**Comment by karthisiva** [comment]
@hackiftekhar i dont know what is exact reason of this issues, i have checked your samples again, its working fine, but its not working with my project.I have add dependices  through pod file

**Comment by hackiftekhar** [comment]
You are providing me sample code but I'm asking about sample project. I don't know where it is?

**Comment by hackiftekhar** [comment]
Is there any updates?

**Comment by hackiftekhar** [comment]
Looks like this is already fixed with 4143c4b3eba4b7cba5b67a78a3c0ac4caec6e46d. Could you please recheck?
