### ISSUE TITLE
Next/Previous icon disappear?

### ISSUE THREAD

**Issue by GSoftwaretailor** [hackiftekhar/IQKeyboardManager#463]
UIViewController *controller = [[UIViewController alloc]init];
UINavigationController *navigation = [[UINavigationController alloc] initWithRootViewController:controller];
  [self presentViewController:navigation animated:YES completion:nil];

in the controller have five uitextfield. when i input string to the textfield , in to toolbar disappear "next"/"previouse" icon. but "done" icon appear.

**Comment by hackiftekhar** [comment]
Are you sure all textFields are in the same superview

**Comment by NasrullahKhan** [comment]
i am facing same issue on the scroll view.  i have 6 textfield in scroll view , number 3 textfield have keyboardType = PhonePad and that textfield having next/previous icon problem, except number 3 textfield all fields are showing next/previous icon.

**Comment by hackiftekhar** [comment]
May be something wrong has happened. You shouldn't get this issue.

**Comment by NasrullahKhan** [comment]
whether i set 1 or 2 or 4,5,6 textfield as PhonePad i face the same issue.

**Comment by hackiftekhar** [comment]
I'm sure this is not due to library, I checked it with a new demo. There is probably something wrong with your code.
