### ISSUE TITLE
Delegate properties is assign ?

### ISSUE THREAD

**Issue by liulishuo** [hackiftekhar/IQKeyboardManager#465]
@property(nonatomic,assign) id<IQDropDownTextFieldDelegate> delegate;             // default is nil. weak reference

Why not “weak” ?

**Comment by hackiftekhar** [comment]
My dear friend, this is the issue with IQDropDownTextField. You created this issue in IQKeyboardManager. You should post this in IQDropDownTextField repo.

**Comment by liulishuo** [comment]
lol
