### ISSUE TITLE
Using hardware keyboard with iPad exposes large gap

### ISSUE THREAD

**Issue by mthuong** [hackiftekhar/IQKeyboardManager#469]
The hardware keyboard issue is a real issue need to be fixed because if user using a hardware keyboard plugin into the iPad.
When keyboard was show, it will show the toolbar with a large gap.
See attach screenshot
![hardware keyboard with large gap](https://cloud.githubusercontent.com/assets/1086057/14134127/f3b8b564-f67e-11e5-8eaa-c689e4a3d159.png)

**Comment by hackiftekhar** [comment]
@mthuong Do you know a way to determine if a hardware keyboard is attached with iOS device?

**Comment by mthuong** [comment]
@hackiftekhar I saw a solution on stackoverflow by checking the keyboard frame in UIKeyboardWillShowNotification notification
http://stackoverflow.com/questions/31991873/how-to-reliably-detect-if-an-external-keyboard-is-connected-on-ios-9

**Comment by hackiftekhar** [comment]
Thanks Much, I'll check if this link has an answer and I can do something to fix it.

**Comment by mthuong** [comment]
I will check your fix on my device
Thanks you @hackiftekhar

**Comment by hackiftekhar** [comment]
No problem. If you still have any issues then let me know.
