### ISSUE TITLE
the keyboard did Appear , I don't want table view scroll

### ISSUE THREAD

**Issue by memoriesofsnows** [hackiftekhar/IQKeyboardManager#470]
Hi @hackiftekhar ,

You did great work!!
Here my need , the textview at the bottom of the tableview.
The keyboard did Appear , I don't want table view scroll,and the textview only scroll.

Hope it's understandable.
Thanks!

**Comment by hackiftekhar** [comment]
I can understand but I need to think about a solution to overcome with your problem.

**Comment by mkhoshpour** [comment]
I have a tableview inside scrollview, I want the scrollview scrolls when keyboard shows up instead of tableview.

**Comment by hackiftekhar** [comment]
This is probably duplicate of #285 and now I added support to follow `scrollView.scrollEnabled` property to check if scrollView can scroll or not. Probably 34634225fdba162b56cdd3b519fc7d691e22fd2c commit fixed this issue.
