### ISSUE TITLE
Custom function for "done" button in toolbar

### ISSUE THREAD

**Issue by nsekhon** [hackiftekhar/IQKeyboardManager#475]
Is there a way to add a custom function for when the "done" button is pressed in the keyboard toolbar that is a different method for when the "return" key is pressed. For example, pressing "return" would dismiss the keyboard, while pressing "done" would present a view controller.

**Comment by Deepinder-Lakhi** [comment]
Keyboard Return Key Handling:-

If you would like to implement keyboard Return Key as Next/Done button, then you can use IQKeyboardReturnKeyHandler.(#38, #63)

1) Create an instance variable of IQKeyboardReturnKeyHandler and instantiate it in viewDidLoad with ViewController object like this:-

@implementation ViewController
{
    IQKeyboardReturnKeyHandler *returnKeyHandler;
}

- (void)viewDidLoad
{
    [super viewDidLoad];

    returnKeyHandler = [[IQKeyboardReturnKeyHandler alloc] initWithViewController:self];
}
It assign all the responderView delegates to self, and change keybord Return Key to Next key.

2) set instance variable to nil in dealloc method.

-(void)dealloc
{
    returnKeyHandler = nil;
}

**Comment by hackiftekhar** [comment]
If you just would like to get a callback when toolbar done button is pressed then you can check `IQUIView+IQKeyboardToolbar.h`, there is a method `-(void)setCustomDoneTarget:(nullable id)target action:(nullable SEL)action;`. This will not override default behaviour of done button and still dismiss keyboard, but you'll get a callback.

If you would like to get full control over done button then you can add your own UIToolbar to textField. In this case IQKeyboardManager will not override your toolbar and you'll take care of all the responsibility of your toolbar with your methods.

**Comment by arjavlad** [comment]
@Deepinder-Lakhi I used your code. it works in iOS 9 but not working iOS 10.

**Comment by w-i-n-s** [comment]
Try to check text field when keyboard wants hide:
    
    [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(keyboardWillHide:) name:UIKeyboardWillHideNotification object:nil];

**Comment by vinathy** [comment]
@hackiftekhar,Have added  pod 'IQKeyboardManagerSwift', '~> 4.0.6' podfile, working on swift3, am able to find upward, downward arrow and Done button, but in my keypad am not able to next and done button, by default am getting return only, Please help me if any function am i missing, Any help is appreciable. In 
 func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        
        IQKeyboardManager.sharedManager().enable = true
       IQKeyboardManager.sharedManager().enableAutoToolbar = true
          return true
    }
in my ViewController
 override func viewDidLoad() {
        super.viewDidLoad()
        
        textfieldName.delegate = self
        textfieldPassword.delegate = self
        IQKeyboardManager.sharedManager().shouldResignOnTouchOutside = true
    
}

**Comment by neetin** [comment]
@hackiftekhar 
I need to get action of `Done` button. 
There is no `setCustomDoneTarget()` in v5.0.8. Can you please specify which function is there to achieve action of Done button?
BTW, I am using Swift 4 and iOS 11

**Comment by hackiftekhar** [comment]
It's now moved to textField.keyboardToolbar.doneBarButton.setTarget(target:action:), please use this.

**Comment by jlubeck** [comment]
This is not working for me            

`textField.keyboardToolbar.doneBarButton.setTarget(self, action: #selector(action))`

The action never gets called, and it I check `po relationshipField.keyboardToolbar.doneBarButton.target` after that line, I get a `nil` response
