### ISSUE TITLE
Misplace the top header lablel

### ISSUE THREAD

**Issue by dimplebhendarkar** [hackiftekhar/IQKeyboardManager#477]
Typing in textfield and then put the app in the background (keypad keep open in the app) and  now open the app  . The top Header Label move down. It misplaced.[
![thumb_img_0051_1024](https://cloud.githubusercontent.com/assets/8667942/14282672/0b940656-fb5d-11e5-8f91-0d64760b85b4.jpg)
![thumb_img_0052_1024](https://cloud.githubusercontent.com/assets/8667942/14282675/0ebdf1de-fb5d-11e5-9420-e5b1c9645984.jpg)
![thumb_img_0053_1024](https://cloud.githubusercontent.com/assets/8667942/14282676/10812464-fb5d-11e5-8d0a-407fe359452c.jpg)
![thumb_img_0054_1024](https://cloud.githubusercontent.com/assets/8667942/14282677/115b936a-fb5d-11e5-92aa-c2768a60b211.jpg)

](url)

**Comment by hackiftekhar** [comment]
Oops, not sure why this happens? Are you sure it is because of IQKeyboardManager?

**Comment by dimplebhendarkar** [comment]
ya, It is because of IQKeyboardManager. Because I used very basic code to create this.

**Comment by hackiftekhar** [comment]
Could you please share a demo so I can look at what is happening wrong there?

**Comment by hackiftekhar** [comment]
Do you have any updates on this?

**Comment by hackiftekhar** [comment]
Any updates?

**Comment by hackiftekhar** [comment]
I found that this is because you pinned your top label with Top Layout Guide and it's behaving correctly according to iOS.
