### ISSUE TITLE
Use of unresolved identifier 'IQPreviousNextView' in IQKeyboardManager.swift

### ISSUE THREAD

**Issue by appmonk** [hackiftekhar/IQKeyboardManager#478]
When I build v.4.0.1 of IQKeyboardManagerSwift.xcodeproj for simulator I get the error:
MyProjectName/Carthage/Checkouts/IQKeyboardManager/IQKeyboardManagerSwift/IQKeyboardManager.swift:804:68: error: use of unresolved identifier 'IQPreviousNextView'
        toolbarPreviousNextAllowedClasses.insert(NSStringFromClass(IQPreviousNextView))

The Demo.xcodeproj does compile and build and run.

I'm using Xcode Version 7.3 (7D175) and Carthage. My cartfile contains: github "hackiftekhar/IQKeyboardManager" "v4.0.1"

I see you made commit 88c4e8f2ed2215e6a40228dd5846ca340f0df76c just a day ago, where it looks like the bug is introduced.

**Comment by hackiftekhar** [comment]
Ohh, I forget to add this class with carthage target.

**Comment by appmonk** [comment]
I'm glad you found the reason.

**Comment by hackiftekhar** [comment]
This is now fixed with 236980b0631074f6d87898986b2acb20a2df4c71 commit, I'll soon post a new version for you.

**Comment by appmonk** [comment]
Thank you very much.

**Comment by hackiftekhar** [comment]
4.0.2 has now been pushed with the fix via cocoapods.

**Comment by wkwyatt** [comment]
The 4.0.3 release has the same issue I think.  I am getting the same errors

**Comment by hackiftekhar** [comment]
Ok, I'll check.
