### ISSUE TITLE
Next/Previous buttons not working properly

### ISSUE THREAD

**Issue by lfarah** [hackiftekhar/IQKeyboardManager#479]
It's out of order and working on a really strange way. :cry: 
![p7jowx](https://cloud.githubusercontent.com/assets/6511079/14293756/c2f52234-fb22-11e5-9cf7-09061b3b1f97.gif)

Hope you guys can help it! :smile:

**Comment by hackiftekhar** [comment]
Please elaborate or read Github issues or README file for more help.

**Comment by hackiftekhar** [comment]
Please elaborate or read Github issues or README file for more help.

**Comment by hackiftekhar** [comment]
Looks like your textfields are not in a good hierarchy. Please check your storyboard and check if all textfields are put in correct order.

**Comment by lfarah** [comment]
I checked that, but it seems that they are in the correct order!
<img width="745" alt="screen shot 2016-04-05 at 11 48 01 am" src="https://cloud.githubusercontent.com/assets/6511079/14294124/5e9a23b4-fb24-11e5-9575-a5a747ede38e.png">

**Comment by hackiftekhar** [comment]
Did you changed toolbarManageBehaviour to tag? I believe your storyboard configuration should work.

**Comment by hackiftekhar** [comment]
Did you changed toolbarManageBehaviour to tag? I believe your storyboard configuration should work.

**Comment by lfarah** [comment]
I didn't change it, but even if I changed it and added tags in my storyboard, it won't work

**Comment by lfarah** [comment]
Did you find any fix? :cry:

**Comment by hackiftekhar** [comment]
Could you please share a demo project to debug it. Because it's not reproducible in my demo.

**Comment by lfarah** [comment]
I tried to setup a new project and reproduce the bug, but I wasn't able to do it. Will keep trying!

**Comment by hackiftekhar** [comment]
Ok, Let me know when you succeed. May be there is something with your main project.

**Comment by hackiftekhar** [comment]
Any updates?

**Comment by hackiftekhar** [comment]
When you have a working demo project, please reopen this issue.

**Comment by lqcjdx** [comment]
I have the same issue. Next/Previous buttons not working properly and after i clicked Next/Previous button many times then the Done button is also not working properly.

**Comment by hackiftekhar** [comment]
hey @lqcjdx could you please share demo?

**Comment by lqcjdx** [comment]
In my project, each UITableViewCell has a UITextField. I found that when i do "[tableView reloadData]" in "-(void)textFieldDidEndEditing:(UITextField *)textField", it will cause the Next/Previous/Done button not working properly. Could you explain it? Thank you in advance. @hackiftekhar

**Comment by hackiftekhar** [comment]
I'm not gonna explain. It's working in demo and it is as it is. Please check it yourself.

I'm asking for a demo from a long time and peoples are ignoring my messages but don't forget to asking questions from me. How can J answer a question without knowing the reason. I'm feeling very very frustrated.

**Comment by lqcjdx** [comment]
[IQDemo.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/285672/IQDemo.zip)
@hackiftekhar  I am so sorry for that. Now i provide a demo and a GIF.

**Comment by JackWchen2015** [comment]
@lqcjdx  I have  the  same  issue  with you,what's more,I found that,when I  call  the goNext function ,the code  that the nextField becomeFirstResponder return No,that's why I can't understand.

**Comment by lqcjdx** [comment]
@JackWchen2015 You need not call the goNext function yourself. 
My issue is when each UITableViewCell contains a UITextField, if i don't call `` [tableView reloadData]`` function  in ``-(void)textFieldDidEndEditing:(UITextField *)textField`` callback method,  then Next/Previous buttons are work normal.

**Comment by JackWchen2015** [comment]
My issue  is  same  with you，I  talked   where  it's can't work.but i can't  slove it  yet.

**Comment by lfarah** [comment]
>I'm asking for a demo from a long time and peoples are ignoring my messages but don't forget to asking questions from me. How can I answer a question without knowing the reason. I'm feeling very very frustrated.

hey @hackiftekhar, I'm so sorry. I work daily on open source libraries and I know how frustrating it is when people don't answer. I wasn't able to find the bug when creating a new project

**Comment by hackiftekhar** [comment]
@Ifarah I think there is only you who can debug your main project code with my library and fix the bug (If library has somewhere).

**Comment by hackiftekhar** [comment]
@lqcjdx your demo contains UITableView and you are reloading tableView in textFieldDidEndEditing that is causing the issue while in @lfarah gif it looks like an scrollView. @lfarah could you please share your demo?

**Comment by lfarah** [comment]
@hackiftekhar unfortunately I'm just using a normal ViewController. No scrollview.
I can't share this project because of NDA with client. I tried to create a new project but I wasn't able to recreate the bug.

**Comment by hackiftekhar** [comment]
I think you should debug addToolbarIfRequired method to find why the order is incorrect.

**Comment by amitpaliwal87** [comment]
hi hackiftekhar
i found exact reseaon why it is happening . when all textfield drag in stroryboard. then perferct work if you change order textfield then will not work next previous functionality. if again u set in order all text field then this problem will come again . if u remove all textfield then will work . so suggest me why it is happeing

**Comment by amitpaliwal87** [comment]
answer found. if u open xml file of storyboard then set all textfield in order then this problem solved. in story board u  changed again  textfield order this will good appear in storyboard  but will not effect in xml file. so change textfield order in xml file

**Comment by hackiftekhar** [comment]
Could you please let me know how to reproduce it? The app logic is to get all the siblings using textField.superview.subviews (IQAutoToolbarBySubviews is default behaviour of library).

**Comment by LiChangcong** [comment]
[TestKeyBoardManager.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/466847/TestKeyBoardManager.zip)
I reproduce it in a demo project. when a UITableViewCell contains a UITextField,and you call [tableView reload] in textFieldDidEndEditing, then it happens

**Comment by hackiftekhar** [comment]
I need a demo without tableview because @Ifarah is having issue without tableview. If you are calling reloadData then there may be issues.

**Comment by hackiftekhar** [comment]
@lfarah Do you have any demo for us?

**Comment by lfarah** [comment]
@hackiftekhar I abandoned that project and since then I never had a problem with **IQKeyboardManager** again... Everything seems to be working perfectly

**Comment by hackiftekhar** [comment]
@lfarah but still if you have a cooy of project and you can create a demo and reopen this issue and share with us since I don't have any plans to stop my work for this library and continuously trying to improve it.

**Comment by aiyub007** [comment]
@hackiftekhar  same issue here.. if there are too much textfields it jums after 5th textfields to other tagging is also not helpful here.. Try to setup with tag please..

**Comment by hackiftekhar** [comment]
@aiyub007 please share a demo project with me.

**Comment by pandapancake** [comment]
@hackiftekhar Hi! I post a similar question few days ago and found this old question. I reproduce a demo project [here.](https://github.com/pandapancake/textfield_problem_demo) My problem is the textfield order was incorrect and if there's a way to include custom textfield inside tableview cell. (I commented out the tableview part in the demo). If you run the project the order is 1>2>5>3>4. Thanks!
