### ISSUE TITLE
about TextField in KLCPopup

### ISSUE THREAD

**Issue by YzStyle** [hackiftekhar/IQKeyboardManager#480]
I put a TextFiled in the KLCPopup,and the keyboard keeps out the TextField,Can you give me some solution?

**Comment by hackiftekhar** [comment]
Could you please provide me a screenshot of issue.

**Comment by YzStyle** [comment]
Like this.

![simulator screen shot 2016 4 8 9 33 36](https://cloud.githubusercontent.com/assets/16829182/14371839/fcd341a0-fd6d-11e5-9ed3-ca84de196f11.png)
![simulator screen shot 2016 4 8 9 33 54](https://cloud.githubusercontent.com/assets/16829182/14371852/1362e5e2-fd6e-11e5-8080-2bbe57311894.png)

**Comment by YzStyle** [comment]
the  ".shouldResignOnTouchOutside" is effective

**Comment by hackiftekhar** [comment]
Ok, I'll check, but generally I doesn't support third party library. For more info please check readme.

**Comment by YzStyle** [comment]
Thx for respond,maybe it have something wrong about third party library

**Comment by hackiftekhar** [comment]
If you found something then let me know, if you found issue with the library then let me know and share a demo. I'll check the demo project.
