### ISSUE TITLE
IQKeyboardManager turns on automatically even if no line of code is written for it when included via Pods.

### ISSUE THREAD

**Issue by Ankit8946** [hackiftekhar/IQKeyboardManager#482]
As mentioned above it automatically turns on and if try to disable it for a particular view controller it doesn't turn off.

Could it be because of other libraries I am using..?
I am using the following libraries...

source 'https://github.com/CocoaPods/Specs.git'

platform :ios, :deployment_target => "8.0"

pod 'SVProgressHUD', :git => 'https://github.com/TransitApp/SVProgressHUD.git'
pod 'FormatterKit'
pod 'AFNetworking', '2.4.1'
pod 'MMDrawerController'
pod 'CocoaLumberjack', '= 2.0.0-beta4'
pod 'FrameAccessor', '~> 1.3.2'
pod 'Google/SignIn'
pod 'GoogleAnalytics-iOS-SDK', '3.0.9'
pod 'Mantle', '1.5.1'
pod 'TimesSquare', :git => "https://github.com/abhisheksengar/objc-TimesSquare.git"
pod 'IDMPhotoBrowser'
pod 'hpple', '~> 0.2.0'
pod 'Cloudinary', '~> 1.0'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'MDHTMLLabel'
pod 'pop', '~> 1.0'
pod 'KeenClient'
pod 'MagicalRecord'
pod 'Google-Mobile-Ads-SDK', '~> 7.0'
pod 'Masonry'
pod 'Branch'
pod 'SWTableViewCell', '~> 0.3.7'
pod 'CleverTap-iOS-SDK'
pod 'AppsFlyer-SDK'
pod 'QRCodeReaderViewController', '~> 3.5.2'
pod 'MZFormSheetPresentationController'
pod 'GoogleAppIndexing'
pod 'IQKeyboardManager'
pod 'INTULocationManager'
pod 'Crashlytics'
pod 'Fabric'

**Comment by hackiftekhar** [comment]
If you want to disable it then please disable this in App Delegate.m. You should set `enabled` property to `NO` and `enableAutoToolbar` property to NO.

**Comment by Ankit8946** [comment]
That doesn't seem to work. I am not sure how come the project just includes
IQKeyboardManager, even though I have not made any calls to it. I mean the
singleton object is even not initialised once.

Could it be because of some categories..? How can I stop it..?

**Comment by hackiftekhar** [comment]
I already gave you answer in above message. For more details please check readme.

**Comment by toohotz** [comment]
@Ankit8946 Can you show us what your ```AppDelegate``` file looks like? As @hackiftekhar suggested, the keyboard should only turn on whenever you actually enable it.  Even including the framework inside of your project would not activate it unless you import and enable it.

**Comment by hackiftekhar** [comment]
@toohotz I suggested to _disable_ it in _AppDelegate_. The developer who use **IQKeyboardManager** should read **README** file first. If you are installing **IQKeyboardManager** then it's already enabled and _doesn't need any code to enable it_. If developer explicitly wants to disable it then they can do it within the app. For @Ankit8946 I suggested to disable it in AppDelegate

**Comment by Ankit8946** [comment]
I can't share my code base with you or else I have shown it. I am disabling
it explicitly in app delegate and the specific view controllers in which I
don' t want to enable it, but it still works. Maybe I will create a sample
and send it to you.

**Comment by hackiftekhar** [comment]
Sure! You can share a demo project here.

**Comment by hackiftekhar** [comment]
Any updates on demo?

**Comment by Ankit8946** [comment]
Sorry I haven't had the time. I am not using the library anymore.
Resorted to implementing everything on my own.
You can close the issue if you like.

Thanks
Ankit Srivastava

**Comment by hackiftekhar** [comment]
Thanks for getting back to me. :)

**Comment by vinner2112** [comment]
Dear, 
As I understood from your last message you were looking for some information  , I think this is it <http://honest.fightframe.com/e4wlh>
Sincerely yours, vinner_2112
