### ISSUE TITLE
Is there a way to 'reload' the previous / next / done calculation (dynamic UITableView)?

### ISSUE THREAD

**Issue by Japspre** [hackiftekhar/IQKeyboardManager#484]
Hi,

First off, pretty cool framework you build.
I had a look at the current open & closed tickets but couldn't really find something which resembles my problem:

I have a UITableView which has a dynamic amount of sections. 
Each section could have 3-4 UITextFields.
Some sections can be manipulated by the action of a UISwitch - kind of a 'As Above' functionality.

In my example below I have 2 sections:
Section 1: HeaderView, UITableViewCell (3 UITextFields)
Section 2: HeaderView, UITableViewCell (UISwitch), UITableViewCell (3 UITextFields)

When the UISwitch is active section 2 will become:
Section 2: HeaderView, UITableViewCell (UISwitch)

The initial state of my form has the UISwitch active. IQKeyboardManager shows the correct previous / next / done state

When I enable the UISwitch and thus show the extra UITableViewCell IQKeyboardManager shows the correct previous / next / done state.

When I disable the UISwitch again, and thus hide extra UITableViewCell IQKeyboardManager still shows me the state as when the UISwitch would be enabled.

I have tried to enable / disable after the UISwitch action but it didn't solve my problem:
```
[IQKeyboardManager sharedManager].enable = NO;
[IQKeyboardManager sharedManager].enableAutoToolbar = NO;
[IQKeyboardManager sharedManager].enable = YES;
[IQKeyboardManager sharedManager].enableAutoToolbar = YES;
```
My question is, is there a way to force IQKeyboardManager to reload / recalculate the available UITextFields.

I couldn't really find such method inside the header file.

If you have any extra questions, let me know.
Thanks in advance, Jasper.

**Comment by hackiftekhar** [comment]
#434 is the closed ticket you are looking for. There is `reloadInputViews` method in `IQKeyboardManager` class which do exactly like you need. However you should not call this very frequently(scrollViewDidScroll), because this may lead performance issue. I suggest you to call this on `scrollViewDidEndDecelerating` which may not lead much performance overhead for your app.

**Comment by Japspre** [comment]
Thanks for the quick reply.
Unfortunately I still need iOS7 support, so I'm stuck with ~> 3.3 and thats why I couldn't find it in the header file.
Any chance you could add it to the 3.3.7 version?

**Comment by hackiftekhar** [comment]
Hmm, unfortunately that's not possible for me to add support for a property for older versions, they all are released with git tag feature. :(

**Comment by Japspre** [comment]
I see. Well I know the solution, I'll try to come up with something myself.

Thanks!
