### ISSUE TITLE
IQKeyboardManager Adding Empty Space Below UIScrollViews?

### ISSUE THREAD

**Issue by aabosh** [hackiftekhar/IQKeyboardManager#485]
Hi,

I noticed that when IQKeyboardManger (Swift) is enabled, when scrolling below a UITextField, there is a lot of extra empty space. This does not happen when IQKeyboardManger is disabled. Is it possible to adjust the amount of space or remove it?
![demo](https://cloud.githubusercontent.com/assets/7517009/14449206/9a1c9e84-003e-11e6-87b0-34c9b6f47781.png)

Thank you for your work!

Regards,
Andrew

**Comment by abellee** [comment]
happened on iOS 7 too.

**Comment by hackiftekhar** [comment]
I need to look into this issue. I feels that there is already a ticket for something similar issue. Btw, now library doesn't support iOS7. Minimum iOS version should be iOS8.

**Comment by abellee** [comment]
I use the version 3.3.7

**Comment by abellee** [comment]
I found another question, if I use addTextFieldViewDidBeginEditingNotificationName to add a custom notification, and also set disableInViewControllerClass for a viewcontroller. But if I second time click the textview, it will show up again.

**Comment by abellee** [comment]
Can I updated this commit via CocoaPods?

**Comment by hackiftekhar** [comment]
It will take some time to available this via cocoapods. However you can refer repository master branch to get current code via cocoapods.

**Comment by abellee** [comment]
OK thanks

**Comment by plastus** [comment]
I just downloaded the latest version of IQKeyboardManager, but I am still experiencing this issue. Scroll view has no empty space at bottom before keyboard appears. Once it is dismissed, a large empty space at the bottom of the UIScrollView exists. Any suggestions on how to address this bug?

**Comment by hackiftekhar** [comment]
I think this shouldn't be an issue after the fix. Could you please share a demo if you still experiencing the issue. I'm sure I removed the code from library to change contentSize.

**Comment by hugobisson** [comment]
Hello,

I'm using [Eureka](https://github.com/xmartlabs/Eureka) to create forms and sometime i still get this issue. When i click on a textField and once keyboard is dismissed, a white space appear bellow the scrollview.

**Comment by ios-right-solutions** [comment]
This issue is still there in the latest version. I am using the version 6.0.4. I Have a screen with a number of textfields which are inside a scrollview. When IQKeyboardManager moves the position of textfield and then I dismiss the keyboard a big space is created. This is only happening after using IQKeyboardManager.

**Comment by ajith936** [comment]
This issue is still there in the latest version. I am using the version 6.0.4. I Have a screen with a number of textfields which are inside a scrollview. When IQKeyboardManager moves the position of textfield and then I dismiss the keyboard a big space is created. This is only happening after using IQKeyboardManager.

**Comment by ronaldofortini** [comment]
Someone?

**Comment by ronaldofortini** [comment]
The problem remains with iOS12 ... Can someone help? I tried 
IQKeyboardManager.shared.preventShowingBottomBlankSpace = true
but is deprecated..

**Comment by ajith936** [comment]
I don't know how it got solved properly. What I did was I removed my pod for IQKeyboardManager swift and added pod for IQKeyboardManager objective C. Then the issue was not there. In iOS 12 also the issue is not found. Try using objective c pod. This might solve this issue as it done for me.
