### ISSUE TITLE
Hello,When i use IQKey and MFMessage

### ISSUE THREAD

**Issue by laughing25** [hackiftekhar/IQKeyboardManager#486]
When i use IQKey and MFMessage, the MFMessage click cancel, the navigation will jump many times。my english is not good, if you can use google, this is my chinese "当我使用IQ和IOS系统短信功能MFMessage时，在弹出MFMessage时，IQ的键盘监听影响到了MFMessage的退出，在点击取消按钮的时候"

**Comment by hackiftekhar** [comment]
If you are presenting some third party library UI to do your things, then it's developer responsibility to enable/disable IQKeyboardManager when dismissing/presenting third party library UI. IQKeyboardManger will not be responsible to handle third party library issues. For more you can check `Warning` section in README file.

**Comment by laughing25** [comment]
thanks!
