### ISSUE TITLE
How to stop extra scrolling when keyboard is visible.

### ISSUE THREAD

**Issue by sinhagaurav010** [hackiftekhar/IQKeyboardManager#487]
Thanks for your great work..!!
When keyboard is visible, screen is scrollable with a high contentSize.
Is there any way to stop this extra scrolling? I only want screen to scroll till the UITextField set just above keyboard.

**Comment by abellee** [comment]
I have the same problem on iOS 7.

**Comment by hackiftekhar** [comment]
Looks like a duplicate of #485. Could you please confirm?
