### ISSUE TITLE
Selected field scrolls too much (gets covered)

### ISSUE THREAD

**Issue by edgarjs** [hackiftekhar/IQKeyboardManager#488]
Hi, awesome library.

I found there're some cases where it doesn't work properly though. I have a UITableView with many sections and some fields in each section. When I select a field, it gets scrolled all the way up, too much that it even gets covered. I'm not sure if I'm doing something wrong or it's a bug. I don't have any special setting enabled or anything.

![1604145w3tx](https://cloud.githubusercontent.com/assets/12443/14546540/9d2d4aa4-026b-11e6-94a0-c543ae704bf3.png)

**Comment by hackiftekhar** [comment]
This shouldn't happen. I'll check this with my demo.

**Comment by hackiftekhar** [comment]
It's working good with my demo, if you could share a demo project with me then it would be great.

**Comment by edgarjs** [comment]
Sorry for the delay. Here's the repo with the demo. And a gif showcasing it.

https://github.com/edgarjs/IQKeyboardManagerBugDemo

![Bug Gif](http://i.giphy.com/l41YtzKPZa290LQ9q.gif)

**Comment by hackiftekhar** [comment]
Thanks, I'll review the demo when I get some time. Thanks :)

**Comment by hackiftekhar** [comment]
I found that you've added UITableViewController and the IQKeyboardManager doesn't do anything in case of textField is inside a UITableViewController because of it's internal implementation of handilng textFields. For more information see Notes section about UITableViewController here:- https://developer.apple.com/library/ios/documentation/StringsTextFonts/Conceptual/TextAndWebiPhoneOS/KeyboardManagement/KeyboardManagement.html

**Comment by edgarjs** [comment]
So I could disable IQKeyboardManager and the behaviour will be the same?

**Comment by hackiftekhar** [comment]
Yup, because IQKeyboardManager ignore UITableViewController because of it's internal implementation of handling keyboard.

**Comment by edgarjs** [comment]
Hm interesting. But it's weird native behaviour does hide the textfield, probably is kind of clashing with IQKeyboardManager? I'll do some tests, thanks for the help!

**Comment by hackiftekhar** [comment]
For a testing purpose, you can remove library and then you can try. You'll find same behaviour because I already checked that in your demo and found that library is doing nothing.
