### ISSUE TITLE
ipad ios9.3 textfield textview cant respone 

### ISSUE THREAD

**Issue by shaojiankui** [hackiftekhar/IQKeyboardManager#489]
the viewcontrooler isaddsubview a rootviewcontroller,all textfield textview cantinput anything and cant respond click,not 100%happed

**Comment by hackiftekhar** [comment]
If it's tapping issue then you are responsible for it. If it's not then could you please explain your issue with some more details?

**Comment by hackiftekhar** [comment]
Any updates?
