### ISSUE TITLE
UITableViewController :: Xcode 7.3 (7D175) :: iOS 9.3.1

### ISSUE THREAD

**Issue by dillidon** [hackiftekhar/IQKeyboardManager#490]
It does not work in UITableViewController but still works in UIViewController after updating Xcode to version Version 7.3 (7D175) and iOS 9.3.1..... Could you fix it?

**Comment by hackiftekhar** [comment]
UITableViewController has native support for moving view when a textField become first responder.

**Comment by dillidon** [comment]
As I sad, IQKeyboard works in UITableViewController w\o becoming first responder of UITextFiled before Xcode update. How can I manage it?

**Comment by hackiftekhar** [comment]
I'm not sure, I need to look into it.

**Comment by hackiftekhar** [comment]
Looks like it's an iOS issue and I'm unable to do anything for this.
