### ISSUE TITLE
App crashed while resign first responder

### ISSUE THREAD

**Issue by billychen2014** [hackiftekhar/IQKeyboardManager#491]
screenshot as below:

![2016-04-19 10 01 00](https://cloud.githubusercontent.com/assets/7981655/14625446/aa1381ea-0615-11e6-9db6-7b98dbcb0257.png)

**Comment by hackiftekhar** [comment]
Hmm, looks like some internal issue with UIKit framework. Could you please confirm you are getting this issue everytime? Or it's rarely reproducible?

**Comment by billychen2014** [comment]
yes, it's corner case. i only  encountered this problem twice. it looks like the UIKit framework is changing something..

**Comment by hackiftekhar** [comment]
Looks like Baidu Mobile SDK is sending some events, doesn't seem to be an issue with library.
