### ISSUE TITLE
Exist a way for listen done click but without change the design

### ISSUE THREAD

**Issue by jose920405** [hackiftekhar/IQKeyboardManager#492]
Currently the design is

![screen shot 2016-04-20 at 4 43 45 pm](https://cloud.githubusercontent.com/assets/12536184/14691482/13141446-0717-11e6-8681-efca6b7ee080.png)

But when i want listen the done action. I'm using `myTextfield.addDoneOnKeyboardWithTarget(self, action: "doneAction")`

and the design is

![screen shot 2016-04-20 at 4 43 22 pm](https://cloud.githubusercontent.com/assets/12536184/14691471/055788c4-0717-11e6-8fe0-b5e85933611a.png)

i want know if is possible mantain the next and preview buttons in the keyboard. Thanks.

![screen shot 2016-04-20 at 4 44 31 pm](https://cloud.githubusercontent.com/assets/12536184/14691526/4aa1e80c-0717-11e6-8c98-8bb51716a842.png)

**Comment by hackiftekhar** [comment]
Please check IQUIView+IQToolbar.h, there is a method
-(void)setCustomDoneTarget:(nullable id)target action:(nullable SEL)action;

But please be sure to read document comments first.

**Comment by jose920405** [comment]
@hackiftekhar 

Thanks, and sorry i search but not found that method.

Works perfect.

**Comment by hackiftekhar** [comment]
Np

**Comment by Piyush08** [comment]
How to get call back for Swift?

**Comment by hackiftekhar** [comment]
There is same method in swift too.

**Comment by ChanchalW** [comment]
I can't find this method in v4.0.13. I was using v4.0.8 and I implemented that but now it shows no methods founds.

**Comment by hackiftekhar** [comment]
I know I didn't do a good versioning this time, however for your question the methods has been changed to these:-
```
    [textField.keyboardToolbar.previousBarButton setTarget:self action:@selector(previousAction:)];
    [textField.keyboardToolbar.nextBarButton setTarget:self action:@selector(nextAction:)];
    [textField.keyboardToolbar.doneBarButton setTarget:self action:@selector(doneAction:)];
```

**Comment by ChanchalW** [comment]
Thanks, @hackiftekhar  I got these before your reply.

**Comment by christiygag** [comment]
I am searching for this method from the morning, in docs still this info not updated.
Finally got the method.
Thanks @hackiftekhar

**Comment by hackiftekhar** [comment]
Documentation updated! Thanks for pointing our @christiygag
