### ISSUE TITLE
In April the import does not support the tableView, but support in March

### ISSUE THREAD

**Issue by XHJiang** [hackiftekhar/IQKeyboardManager#493]
In April the import does not support the tableView, but support in March

**Comment by hackiftekhar** [comment]
Please elaborate

**Comment by XHJiang** [comment]
In march, when I wrote the test engineering support to achieve the tableView click blank keyboard recovered, but I import project is not support in April, I wrote a new test project, using SDK in March is good, but not a new imported SDK in April. I use cocopods import

**Comment by hackiftekhar** [comment]
It looks like Xcode settings or Obj-C<->Swift header linking issue and not caused by the library. May be you've upgraded Xcode.
