### ISSUE TITLE
Update keyboard position on multiline UITextView

### ISSUE THREAD

**Issue by zishanj** [hackiftekhar/IQKeyboardManager#494]
I am using a custom component for multiline UITextView where the newline is created after pressing the return key. Due to this custom developed feature, the newline then get under the keyboard. **Is there any supporting function that refreshes the keyboard position after the layout get outdated?**

**Comment by PuneetKohli** [comment]
This happens to me as well

**Comment by hackiftekhar** [comment]
Library doesn't have anything like that yet. But probably I need to expose some methods in public header to refreshes the view position to uncover textView from keyboard.

**Comment by hackiftekhar** [comment]
I've added `reloadLayoutIfNeeded` method for you, Please check and let me know if it works for you.

**Comment by jiazil** [comment]
how can i insert this function to react native textview?

**Comment by aquintiliano** [comment]
I want to use this on React Native as well, any ideas?
