### ISSUE TITLE
How do I import the framework?

### ISSUE THREAD

**Issue by simonbarker** [hackiftekhar/IQKeyboardManager#495]
Feeling quite stupid at the moment, I want to use IQKeyboardManager in my project as it looks great but I can't get it run at all.

I've downloaded and run the demo and that works fine. I've then copied the IQKeyboardManagerSwift folder into the project. When I compile the app builds fine but IQKM isn't doing anything, when I try to reference the class IQKeyboardManager I just get an unresolved identifier error.

If I add `import IQKeyboardManager` I get the error "No such module IQKeyboardManager"

I'm sure I've missed a simple and obvious step but reading the ReadMe isn't shining any light on this.

Any help would be great.

**Comment by simonbarker** [comment]
I've managed to get the project to recognise the class so I can now instantiate the object (I had to move it out of it's main folder and put the first level of the directory into the project) however I've got 96 errors stoping me compiling now the first is

`if let textFieldViewController = _textFieldView?.viewController() ` on line 77of IQKeyboardManager.swift. Since others can compile I assume I've really managed to screw up importing this.

**Comment by simonbarker** [comment]
Solved it!

I had to select "Create Groups" when importing rather than "Create folder references" when adding the files

**Comment by hackiftekhar** [comment]
If you are adding Swift library then you need to enable it in appDelegate. If you are using ObjC version then you don't need to do it another other than just including the library folder.
