### ISSUE TITLE
view misplacement

### ISSUE THREAD

**Issue by tospery** [hackiftekhar/IQKeyboardManager#496]
I need to use IQKeyboardManager in the nib（enable auto layout）, and the navigation bar is translucent. When closing the keyboard, the view will misplacement. The bug is in 3.3.7 and 4.0.2 version, you can download the demo to reproduce this. thanks.
Download Demo:  http://pan.baidu.com/s/1hshNTqO

**Comment by hackiftekhar** [comment]
Looks like the demo project doesn't exist there. If you can upload demo project on dropbox and share like with me or email me the demo at hack.iftekhar@gmail.com then it would be great.

**Comment by hackiftekhar** [comment]
Got your demo

[IQDemo.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/265185/IQDemo.zip)

**Comment by hackiftekhar** [comment]
This isn't a bug, but you should write
`    _scrollView.shouldRestoreScrollViewContentOffset = YES;`

In ViewDidLoad. You may need to import required files using
`#import <IQKeyboardManager/IQUIScrollView+Additions.h>`

**Comment by hackiftekhar** [comment]
But it looks like, IQKeyboardManager is doing some contentSize change in between, that's why some empty space is showing at the bottom.

**Comment by tospery** [comment]
Thanks, so i need use UIKeyboardWillHideNotification to reset contentSize, like demo, right?

**Comment by hackiftekhar** [comment]
For now, you may have to write a workaround. But I think I need to remove the code to change content size of ScrollView.
