### ISSUE TITLE
textView when paste many words the cursor will dismissing to outside the textview

### ISSUE THREAD

**Issue by lmh0921** [hackiftekhar/IQKeyboardManager#502]
i set the textView's height is 85,and when i input words,the textview will bounce and bounce...then i code:self.automaticallyAdjustsScrollViewInsets = NO;..........and then when i paste many words,about 1000,the cursor will go out of the textview to top where i can't see,and i pull down the textview's scrollview,the cursor show and become normol......when i delete iqkeyboardmanager from my project,these problem has gone........i don't know why

**Comment by lmh0921** [comment]
there is bug!! I added: [IQKeyboardManager sharedManager].shouldFixTextViewClip = NO; then it worked. you set it YES as default

**Comment by hackiftekhar** [comment]
btw, shouldFixTextViewClip was added to fix a known issue with UITextView in iOS7 http://stackoverflow.com/questions/18966675/uitextview-in-ios7-clips-the-last-line-of-text-string. Now as we are supporting iOS8 as minimum OS version, so I removed this property permanently with 2d27f52e02b9816d3b1c0dbae5b87d1c44ede659 commit .
