### ISSUE TITLE
Not working with UITextField as the subviews of 2 views on single screen

### ISSUE THREAD

**Issue by nikitasharmasahu** [hackiftekhar/IQKeyboardManager#503]
I have two views in a single screen and each contains textfields but screen is not scrolling up for textfields in the below view.

**Comment by hackiftekhar** [comment]
Could you please explain why it's not working? Are you sure you haven't pinned topLayoutConstraint or bottomLayoutConstraint with view.

**Comment by hackiftekhar** [comment]
@nikitasharmasahu If you are talking about next/prev button then you can check IQPreviousNextView. It will help you to populate next/prev button on keyboard.

**Comment by nikitasharmasahu** [comment]
@hackiftekhar Thanks for the help. I will try this next time.
