### ISSUE TITLE
When inputAccessoryView is initialized as UIView(), it takes multiple tries to get the scrollview to scrollup

### ISSUE THREAD

**Issue by ziyuanliu** [hackiftekhar/IQKeyboardManager#507]
the scrollview is not scrolled above the keyboard on the first try, it does, however, after a few tries.

**Comment by ziyuanliu** [comment]
also does it conflict with textViewDidBeginEditing in the view controller?

**Comment by hackiftekhar** [comment]
Are you using UITableViewController?

**Comment by ziyuanliu** [comment]
Yes I am, it's actually the same chat uiviewcontroller demonstrated in the readme

**Comment by hackiftekhar** [comment]
Ahh, If you are using UITableViewController then it's not handled by library.  Please go to https://developer.apple.com/library/ios/documentation/StringsTextFonts/Conceptual/TextAndWebiPhoneOS/KeyboardManagement/KeyboardManagement.html and search for UITableViewController, you'll find a note that it automatically handles it, this is why I forcefully ignore UITableViewController. If it isn't working correctly with you then it is probably UITableViewController's bug.

**Comment by ziyuanliu** [comment]
@hackiftekhar thank you very much! I disabled the library for my specific viewcontroller and implemented what apple suggested -- it works flawlessly!
