### ISSUE TITLE
Exception after installing via pods

### ISSUE THREAD

**Issue by appcelerate** [hackiftekhar/IQKeyboardManager#509]
I get this 

*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Please file a radar on UIKit if you see this assertion.'

*** First throw call stack:
(
	0   CoreFoundation                      0x0000000112d4fd85 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x00000001127c3deb objc_exception_throw + 48
	2   CoreFoundation                      0x0000000112d4fbea +[NSException raise:format:arguments:] + 106
	3   Foundation                          0x000000010f1ece1e -[NSAssertionHandler handleFailureInFunction:file:lineNumber:description:] + 169
	4   UIKit                               0x0000000111321209 PushNextClassForSettingIMP + 469
	5   UIKit                               0x00000001113217de TaggingAppearanceObjectSetterIMP + 37
	6   Eve                                 0x000000010c1740bb -[UIView(TLView) tlsw_setBackgroundColor:] + 74
	7   UIKit                               0x0000000110dfa3a1 -[UIImageView setBackgroundColor:] + 156
	8   UIKit                               0x0000000110d0dc8c -[_UINavigationBarBackground updateBackgroundImage] + 4324
	9   UIKit                               0x0000000110d0df68 -[_UINavigationBarBackground didMoveToSuperview] + 102
	10  UIKit                               0x0000000110c93715 __45-[UIView(Hierarchy) _postMovedFromSuperview:]_block_invoke + 590
	11  UIKit                               0x0000000110c93461 -[UIView(Hierarchy) _postMovedFromSuperview:] + 544
	12  UIKit                               0x0000000110ca126c -[UIView(Internal) _addSubview:positioned:relativeTo:] + 1967
	13  UIKit                               0x0000000110cd8df9 -[UINavigationBar _commonNavBarInit] + 341
	14  UIKit                               0x0000000110cd9383 -[UINavigationBar initWithCoder:] + 962
	15  UIKit                               0x000000011118ae8a UINibDecoderDecodeObjectForValue + 705
	16  UIKit                               0x000000011118abc0 -[UINibDecoder decodeObjectForKey:] + 278
	17  UIKit                               0x0000000110ccfa3c -[UINavigationItem initWithCoder:] + 793
	18  UIKit                               0x000000011118ae8a UINibDecoderDecodeObjectForValue + 705
	19  UIKit                               0x000000011118abc0 -[UINibDecoder decodeObjectForKey:] + 278
	20  UIKit                               0x0000000110d7fc59 -[UIViewController initWithCoder:] + 429
	21  UIKit                               0x0000000110fb3095 -[UIClassSwapper initWithCoder:] + 241
	22  UIKit                               0x000000011118ae8a UINibDecoderDecodeObjectForValue + 705
	23  UIKit                               0x000000011118b04b UINibDecoderDecodeObjectForValue + 1154
	24  UIKit                               0x000000011118abc0 -[UINibDecoder decodeObjectForKey:] + 278
	25  UIKit                               0x0000000110d80027 -[UIViewController initWithCoder:] + 1403
	26  UIKit                               0x0000000110db4652 -[UINavigationController initWithCoder:] + 66
	27  UIKit                               0x000000011118ae8a UINibDecoderDecodeObjectForValue + 705
	28  UIKit                               0x000000011118b04b UINibDecoderDecodeObjectForValue + 1154
	29  UIKit                               0x000000011118abc0 -[UINibDecoder decodeObjectForKey:] + 278
	30  UIKit                               0x0000000110d80027 -[UIViewController initWithCoder:] + 1403
	31  UIKit                               0x0000000110ddbd30 -[UITabBarController initWithCoder:] + 66
	32  UIKit                               0x0000000110fb3095 -[UIClassSwapper initWithCoder:] + 241
	33  UIKit                               0x000000011118ae8a UINibDecoderDecodeObjectForValue + 705
	34  UIKit                               0x000000011118abc0 -[UINibDecoder decodeObjectForKey:] + 278
	35  UIKit                               0x0000000110fb2d6b -[UIRuntimeConnection initWithCoder:] + 180
	36  UIKit                               0x000000011118ae8a UINibDecoderDecodeObjectForValue + 705
	37  UIKit                               0x000000011118b04b UINibDecoderDecodeObjectForValue + 1154
	38  UIKit                               0x000000011118abc0 -[UINibDecoder decodeObjectForKey:] + 278
	39  UIKit                               0x0000000110fb1f7d -[UINib instantiateWithOwner:options:] + 1255
	40  UIKit                               0x000000011132c314 -[UIStoryboard instantiateViewControllerWithIdentifier:] + 181
	41  UIKit                               0x000000011132c467 -[UIStoryboard instantiateInitialViewController] + 69
	42  UIKit                               0x0000000110be989f -[UIApplication _loadMainStoryboardFileNamed:bundle:] + 94
	43  UIKit                               0x0000000110be9bcf -[UIApplication _loadMainInterfaceFile] + 260
	44  UIKit                               0x0000000110be83ef -[UIApplication _runWithMainScene:transitionContext:completion:] + 1392
	45  UIKit                               0x0000000110be5714 -[UIApplication workspaceDidEndTransaction:] + 188
	46  FrontBoardServices                  0x00000001142d88c8 __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ + 24
	47  FrontBoardServices                  0x00000001142d8741 -[FBSSerialQueue _performNext] + 178
	48  FrontBoardServices                  0x00000001142d8aca -[FBSSerialQueue _performNextFromRunLoopSource] + 45
	49  CoreFoundation                      0x0000000112c75301 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	50  CoreFoundation                      0x0000000112c6b22c __CFRunLoopDoSources0 + 556
	51  CoreFoundation                      0x0000000112c6a6e3 __CFRunLoopRun + 867
	52  CoreFoundation                      0x0000000112c6a0f8 CFRunLoopRunSpecific + 488
	53  UIKit                               0x0000000110be4f21 -[UIApplication _run] + 402
	54  UIKit                               0x0000000110be9f09 UIApplicationMain + 171
	55  Eve                                 0x000000010b9f715f main + 111
	56  libdyld.dylib                       0x00000001137dc92d start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

i just install it via cocoa pods and try to run the application.

if i remove this pod its working fine!

**Comment by hackiftekhar** [comment]
Not sure because from stack trace, I don't find any function calling from library. Looks like an issues with TLView because it is on the top of callstack.

**Comment by hackiftekhar** [comment]
hey @appcelerate, are you still getting issues?

**Comment by jacky007** [comment]
Hi have the same problem. Below is debug info:
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'An instance 0x7d297e00 of class UITableView was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x7f749860> (
<NSKeyValueObservance 0x7f7397a0: Observer: 0x7f730ef0, Key path: contentOffset, Options: <New: YES, Old: NO, Prior: NO> Context: 0x0, Property: 0x7afdae20>
<NSKeyValueObservance 0x7f74a8e0: Observer: 0x7f730ef0, Key path: contentInset, Options: <New: YES, Old: NO, Prior: NO> Context: 0x0, Property: 0x7afddcf0>
<NSKeyValueObservance 0x7f74f2a0: Observer: 0x7f730ef0, Key path: frame, Options: <New: YES, Old: NO, Prior: NO> Context: 0x0, Property: 0x7afe1720>
<NSKeyValueObservance 0x7b001370: Observer: 0x7f730ef0, Key path: panGestureRecognizer.state, Options: <New: YES, Old: NO, Prior: NO> Context: 0x0, Property: 0x7afe29b0>
)'
*** First throw call stack:
(
	0   CoreFoundation                      0x01e17494 __exceptionPreprocess + 180
	1   libobjc.A.dylib                     0x014aee02 objc_exception_throw + 50
	2   CoreFoundation                      0x01e173bd +[NSException raise:format:] + 141
	3   Foundation                          0x010e7097 NSKVODeallocate + 353
	4   UIKit                               0x03ca0348 -[UIView(UIKitManual) release] + 142
	5   CoreFoundation                      0x01cc6df7 CFRelease + 727
	6   CoreFoundation                      0x01cdcbfe -[__NSArrayM dealloc] + 142
	7   libobjc.A.dylib                     0x014c2060 _ZN11objc_object17sidetable_releaseEb + 238
	8   libobjc.A.dylib                     0x014c1361 objc_release + 65
	9   libobjc.A.dylib                     0x014c252d _ZN12_GLOBAL__N_119AutoreleasePoolPage3popEPv + 371
	10  CoreFoundation                      0x01ce78a8 _CFAutoreleasePoolPop + 24
	11  CoreFoundation                      0x01d1f43c __CFRunLoopRun + 2364
	12  CoreFoundation                      0x01d1e846 CFRunLoopRunSpecific + 470
	13  CoreFoundation                      0x01d1e65b CFRunLoopRunInMode + 123
	14  GraphicsServices                    0x08eed664 GSEventRunModal + 192
	15  GraphicsServices                    0x08eed4a1 GSEventRun + 104
	16  UIKit                               0x033b0eb9 UIApplicationMain + 160
	17  EasyWorld                           0x001a8c21 main + 145
	18  libdyld.dylib                       0x05beca25 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by hackiftekhar** [comment]
Looks like you are using a third party UIView category (UIKitManual) which is xausing the issue.

**Comment by jacky007** [comment]
I didn't see any library that create category UIKitManual, so how can we fix it?

**Comment by hackiftekhar** [comment]
I'm not sure but it doesn't look like IQKeyboardManager issue.

**Comment by hackiftekhar** [comment]
Closing because this issue is not relavant to library bug.
