### ISSUE TITLE
Archive failed due to code signing

### ISSUE THREAD

**Issue by lazyprogram** [hackiftekhar/IQKeyboardManager#510]
Its working in my iphone, but if try to archive its nor working. 

PhaseScriptExecution Embed\ Pods\ Frameworks /Users/samye/Library/Developer/Xcode/DerivedData/JBot-eacnlmgocwhxcbbdfkackcofyyvi/Build/Intermediates/ArchiveIntermediates/JBot/IntermediateBuildFilesPath/JBot.build/Release-iphoneos/JBot.build/Script-4CA56E0435E0170D8EAC4C20.sh
    cd /Users/samye/Documents/Projects/jbot-ios
    /bin/sh -c /Users/samye/Library/Developer/Xcode/DerivedData/JBot-eacnlmgocwhxcbbdfkackcofyyvi/Build/Intermediates/ArchiveIntermediates/JBot/IntermediateBuildFilesPath/JBot.build/Release-iphoneos/JBot.build/Script-4CA56E0435E0170D8EAC4C20.sh

mkdir -p /Users/samye/Library/Developer/Xcode/DerivedData/JBot-eacnlmgocwhxcbbdfkackcofyyvi/Build/Intermediates/ArchiveIntermediates/JBot/BuildProductsPath/Release-iphoneos/JBot.app/Frameworks
Symlinked...
rsync -av --filter "- CVS/" --filter "- .svn/" --filter "- .git/" --filter "- .hg/" --filter "- Headers" --filter "- PrivateHeaders" --filter "- Modules" "/Users/samye/Library/Developer/Xcode/DerivedData/JBot-eacnlmgocwhxcbbdfkackcofyyvi/Build/Intermediates/ArchiveIntermediates/JBot/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/IQKeyboardManager.framework" "/Users/samye/Library/Developer/Xcode/DerivedData/JBot-eacnlmgocwhxcbbdfkackcofyyvi/Build/Intermediates/ArchiveIntermediates/JBot/BuildProductsPath/Release-iphoneos/JBot.app/Frameworks"
building file list ... done
IQKeyboardManager.framework/
IQKeyboardManager.framework/IQKeyboardManager
IQKeyboardManager.framework/Info.plist
IQKeyboardManager.framework/IQKeyboardManager.bundle/
IQKeyboardManager.framework/IQKeyboardManager.bundle/IQButtonBarArrowLeft.png
IQKeyboardManager.framework/IQKeyboardManager.bundle/IQButtonBarArrowLeft@2x.png
IQKeyboardManager.framework/IQKeyboardManager.bundle/IQButtonBarArrowLeft@3x.png
IQKeyboardManager.framework/IQKeyboardManager.bundle/IQButtonBarArrowRight.png
IQKeyboardManager.framework/IQKeyboardManager.bundle/IQButtonBarArrowRight@2x.png
IQKeyboardManager.framework/IQKeyboardManager.bundle/IQButtonBarArrowRight@3x.png
IQKeyboardManager.framework/IQKeyboardManager.bundle/de.lproj/
IQKeyboardManager.framework/IQKeyboardManager.bundle/de.lproj/IQKeyboardManager.strings
IQKeyboardManager.framework/IQKeyboardManager.bundle/en.lproj/
IQKeyboardManager.framework/IQKeyboardManager.bundle/en.lproj/IQKeyboardManager.strings
IQKeyboardManager.framework/IQKeyboardManager.bundle/es.lproj/
IQKeyboardManager.framework/IQKeyboardManager.bundle/es.lproj/IQKeyboardManager.strings
IQKeyboardManager.framework/IQKeyboardManager.bundle/fr.lproj/
IQKeyboardManager.framework/IQKeyboardManager.bundle/fr.lproj/IQKeyboardManager.strings
IQKeyboardManager.framework/IQKeyboardManager.bundle/zh-Hans/
IQKeyboardManager.framework/IQKeyboardManager.bundle/zh-Hans/IQKeyboardManager.strings
IQKeyboardManager.framework/IQKeyboardManager.bundle/zh-Hant/
IQKeyboardManager.framework/IQKeyboardManager.bundle/zh-Hant/IQKeyboardManager.strings
IQKeyboardManager.framework/_CodeSignature/
IQKeyboardManager.framework/_CodeSignature/CodeResources

sent 1387378 bytes  received 404 bytes  2775564.00 bytes/sec
total size is 1385762  speedup is 1.00
Code Signing /Users/samye/Library/Developer/Xcode/DerivedData/JBot-eacnlmgocwhxcbbdfkackcofyyvi/Build/Intermediates/ArchiveIntermediates/JBot/BuildProductsPath/Release-iphoneos/JBot.app/Frameworks/IQKeyboardManager.framework with Identity iPhone Distribution: Palanisamy Easwaramoorthy (V35CT655L6)
/usr/bin/codesign --force --sign 05DC670CAA7257E79710ED22C5169E48073BFA1C --preserve-metadata=identifier,entitlements "/Users/samye/Library/Developer/Xcode/DerivedData/JBot-eacnlmgocwhxcbbdfkackcofyyvi/Build/Intermediates/ArchiveIntermediates/JBot/BuildProductsPath/Release-iphoneos/JBot.app/Frameworks/IQKeyboardManager.framework"
05DC670CAA7257E79710ED22C5169E48073BFA1C: no identity found
Command /bin/sh failed with exit code 1

**Comment by hackiftekhar** [comment]
This isn't library related issue, may be there is something wrong with your Xcode settings.

**Comment by SwiftNie** [comment]
how do you solve this problem，I also met
