### ISSUE TITLE
Disable autoscrolling when selecting text field if keyboard is already on screen

### ISSUE THREAD

**Issue by v-ken** [hackiftekhar/IQKeyboardManager#511]
Was wondering if this is an issue to anyone else? When the keyboard is already on screen, shouldn't the auto scrolling be disabled as there is no longer a chance for the keyboard to be covering the editing field (unless user hits 'next' button in toolbar). Moving the screen on every field change when the keyboard is already on screen can be quite unpleasant for the user.

If it is an issue, I can work on a fix.

**Comment by hackiftekhar** [comment]
I believe that this is user dependent. A user may want to disable scrolling when keyboard is up, and may be another user may want to still scroll when keyboard is up. So I'm not sure if it's an issue.

For a workaround a developer may listen for notification and may enable/disable scrolling of scrollView.
