### ISSUE TITLE
map a constraint with IQLayoutGuideConstraint 

### ISSUE THREAD

**Issue by ritesh-nitw** [hackiftekhar/IQKeyboardManager#512]
As mentioned in docs Working with TopLayoutGuide and BottomLayoutGuide section:

> To fix it, just let IQKeyboardManager know the constraint which is pinned with TopLayoutGuide/BottomLayoutGuide, just map TopLayoutGuide/BottomLayoutGuide constraint with IQLayoutGuideConstraint.

How can I map a constraint with IQLayoutGuideConstraint using interface builder or programatically?

I am using objective C and installed the  module using pods.

I tried including `#import "IQUIViewController+Additions.h" `and I tried replacing NSLayoutConstraint with  IQLayoutGuideConstraint: `@property (weak, nonatomic) IBOutlet NSLayoutConstraint *tfaSubViewToBottomLayoutGuideConstraint;`

But it throws an error- uknown type

**Comment by hackiftekhar** [comment]
Programmatically youshould only say
`
Self.IQLayoutGuideConstraint = self.tfaSubViewToBottomLayoutGuideConstraint`

And this should work.
