### ISSUE TITLE
Can't set IQLayoutGuideConstraint

### ISSUE THREAD

**Issue by cecgsn** [hackiftekhar/IQKeyboardManager#513]
I downloaded and installed IQKeyboardManager via carthage and currently using v4.0.3. Automatically the keyboard appears, but now I want to manually specify an IQLayoutGuideConstraint outlet to a constraint, but the IQLayoutGuideConstraint outlet doesn't appear into my list of available outlets in any window.
![captura de pantalla 2016-05-21 a las 2 50 11 p m](https://cloud.githubusercontent.com/assets/16824188/15450991/5dd9bdbe-1f63-11e6-950e-2cb5168da011.png)

**Comment by hackiftekhar** [comment]
It library is added then option should appear. I need to check it with carthage.

**Comment by hackiftekhar** [comment]
I can confirm that this issue is happening with carthage framework.

**Comment by hackiftekhar** [comment]
For now I think you can do this by programmatically (as a workaround). Closing this ticket for now as their are issues with the the carthage and IBDesignable/IBOutlets.
