### ISSUE TITLE
Using the top keys on keyboard to cycle through textfields not working when textfields inside uiStackView?

### ISSUE THREAD

**Issue by KodiKraig** [hackiftekhar/IQKeyboardManager#514]
I have textfields in two separate stacks. When the the keyboard comes up, there is no option to cycle to the next textfield. Is there a workaround other than just not using stack views?

**Comment by hackiftekhar** [comment]
I believe this should all work fine without issue. Mabe you have a containerView for your textField?

**Comment by KodiKraig** [comment]
I am using 'TextFieldEffects'. I am not exactly sure how that is implemented. It works fine when I have the textfields outside the stack views, just not inside of them.

**Comment by hackiftekhar** [comment]
I added UIStackView demo in github demo project. So you can take a look and library is working there.
