### ISSUE TITLE
Does't work on keyWindow Subview

### ISSUE THREAD

**Issue by quhaoran007** [hackiftekhar/IQKeyboardManager#515]
If a view is added by keyWindow (keyWindow addSubview:aView), and keyboard covers the aView's textField or textView, the frame will not be adjusted.

**Comment by hackiftekhar** [comment]
This is the issue with your layout. View shouldn't be added directly to key window. There is already a closed ticket for this.

**Comment by quhaoran007** [comment]
So do you mean any UIView should not add on to keyWindow or ?  I've tried to search the closed ticket in this repository, but I couldn't find. Can you pls tell me the keyword or link for it? Thank you

**Comment by hackiftekhar** [comment]
I remembered that this issue was raised in the past however I'm also having difficulties finding that ticket number. Probably I probably remind this one https://github.com/hackiftekhar/IQKeyboardManager/issues/378.
