### ISSUE TITLE
Weird new API with exposed disabledDistanceHandlingClasses property

### ISSUE THREAD

**Issue by DivineDominion** [hackiftekhar/IQKeyboardManager#516]
Instead of a method on `IQKeyboardManager` that hides implementation details users are now encouraged to violate the object's boundaries and mutate one of its properties directly with `IQKeyboardManager.sharedManager().disabledDistanceHandlingClasses.addObject(...)`.

I would understand the other way 'round, but what's the rationale behind this move?

**Comment by hackiftekhar** [comment]
I exposed those properties because I found it's easy to manage.

**Comment by DivineDominion** [comment]
On the client side or on the library's?

**Comment by hackiftekhar** [comment]
Both side, but more on the library's side.
