### ISSUE TITLE
IQTextView delegate issue (Swift only)

### ISSUE THREAD

**Issue by hardikdevios** [hackiftekhar/IQKeyboardManager#518]
Hello mate,
I think you are missing something in `IQTextView.swift`.

**Your Code**
  ```
override public var delegate : UITextViewDelegate? {
        
        get {
            refreshPlaceholder()
            return super.delegate
        }
        
        set {
        }
    }
```

**Hot Fix**

```
  override public var delegate : UITextViewDelegate? {
        
        get {
            refreshPlaceholder()
            return super.delegate
        }
        
        set {
            super.delegate = newValue //You miss this buddy but this is important
        }
    }
```

Because no delegate fire, if you set your delegate from code. need PR for this ? :)

**Comment by hardikdevios** [comment]
is this path updated in latest Pod ? or you planning to release  this after few more fixes ?

**Comment by hackiftekhar** [comment]
This isn't ipdated to pod. Generally I release a new version after couple of fixes.

**Comment by hardikdevios** [comment]
No problem

**Comment by KodiKraig** [comment]
After you added "super.delegate = newValue", did your delegate methods start working? Still cannot get mine to fire. Did the change you suggested but still same result. Here is my class:

`import Foundation
import IQKeyboardManagerSwift

class TextViews: IQKeyboardReturnKeyHandler {
    
    init(view: IQTextView) {
        super.init()
        view.delegate = self
    }
    
    override func textViewDidBeginEditing(textView: UITextView) {
        print("didRun")
    }
    
}`
