### ISSUE TITLE
Programatiaclly Next or previous textfield

### ISSUE THREAD

**Issue by Ankish** [hackiftekhar/IQKeyboardManager#519]
Need a way to programatically resign current and set next/previous responder.

**Comment by hackiftekhar** [comment]
That you can do it with natural programming logic, there is no need to do anything with library, you should just call `becomeFirstResponse` on next button when resigning previous. However there are also some methods like `goPrevious` `goNext` which you can use to navigate programmatically thought textFields.

**Comment by Ankish** [comment]
👍  . I found that was just going to close it . Thanks a lot !
