### ISSUE TITLE
iOS7 crash because of iOS8 api:[UIImage imageNamed:inBundlecompatibleWithTraitCollection:]

### ISSUE THREAD

**Issue by mengmakies** [hackiftekhar/IQKeyboardManager#520]
In IQUIView+IQKeyboardToolbar.h line 531,532,626,627,717,718

(UIImage *)imageNamed:(NSString *)name inBundle:(NSBundle *)bundle compatibleWithTraitCollection:(UITraitCollection *)traitCollection NS_AVAILABLE_IOS(8_0);

I'm replace with below code：
UIImage *imageLeftArrow = [UIImage imageNamed:@"IQKeyboardManager.bundle/IQButtonBarArrowLeft"];
    UIImage *imageRightArrow = [UIImage imageNamed:@"IQKeyboardManager.bundle/IQButtonBarArrowRight"];

**Comment by hackiftekhar** [comment]
Library support iOS8 as minimum deployment target.
