### ISSUE TITLE
IQLayoutGuideConstraint doesn't appear in Storyboard

### ISSUE THREAD

**Issue by harshvishu** [hackiftekhar/IQKeyboardManager#521]
I am using `pod 'IQKeyboardManager'` updated to version '4.0.3'.
The `IQLayoutGuideConstraint` doesn't appear in the storyborad.

Xcode version: V7.2
iOS/OSX version: OS X El Captain 10.11.4 (15E65)

**Comment by hackiftekhar** [comment]
Not sure because it's appearing with my Xcode v7.3, btw when I was working with Xcode 7.2 it was showing there too.

**Comment by hackiftekhar** [comment]
I think you are using carthage. Right?

**Comment by hackiftekhar** [comment]
Could you please confirm about the carthage? There is similar ticket like you here #513 you can also take a look at it.

**Comment by harshvishu** [comment]
Sorry for late reply. I am using Cocoapods. The ticket '#513 ' seems similar to mine.

**Comment by hackiftekhar** [comment]
Could you please let me know whigh language version you are using? Mean ObjC or Swift version?

**Comment by harshvishu** [comment]
Swift version

**Comment by hackiftekhar** [comment]
ok, I'll check and will let you know.

**Comment by hackiftekhar** [comment]
For now I think you can do this by programmatically (as a workaround). Closing this ticket for now as their are issues with the the carthage and IBDesignable/IBOutlets.
