### ISSUE TITLE
Switch Perdicvtive

### ISSUE THREAD

**Issue by CarlGitHub** [hackiftekhar/IQKeyboardManager#523]
-[UIWindow endDisablingInterfaceAutorotationAnimated:] called on <UITextEffectsWindow: 0x7fc2917f89f0; frame = (0 0; 414 736); opaque = NO; autoresize = W+H; layer = <UIWindowLayer: 0x7fc2917f9010>> without matching -beginDisablingInterfaceAutorotation. Ignoring.
![simulator screen shot 2016 5 31 12 00 06](https://cloud.githubusercontent.com/assets/5214718/15653976/f7196ba8-26c2-11e6-8019-ac7a55e5131d.png)

**Comment by hackiftekhar** [comment]
I'm not much sure but looks like it is the inputAccessoryView. Could you please try with setting `textView.inputAccessoryView = [[UIView alloc] init];`
