### ISSUE TITLE
Next/Previous buttons not showing if two text fields are there.

### ISSUE THREAD

**Issue by sinhagaurav010** [hackiftekhar/IQKeyboardManager#524]
When there are two text fields on U.I, then next/previous buttons not shown to navigate between two text fields.
Could you please look into this.? I am using iphone 6s with iOS 9.3.

**Comment by sinhagaurav010** [comment]
Mistake was on my side. I was using two different views having single textfield on each view on main UIView.

**Comment by hackiftekhar** [comment]
You can now check IQPreviousNextView feature if you need your textFields within different view and still need previous/next button.

**Comment by AQadar** [comment]
hey dear how to fix this issue of next and previous button i have multiple views in each view their is one textbox for signUp page?

**Comment by developer-mobile-apple** [comment]
How to use `IQPreviousNextView` feature to navigate between textfields if the textfields are in different views but in the single main of the viewcontroller?

**Comment by developer-mobile-apple** [comment]
Looking at the issue list I'm able to find the solution.
Here is it : https://github.com/hackiftekhar/IQKeyboardManager/issues/1140#issuecomment-345601606
@hackiftekhar : Please close these both issues. Thanks.
