### ISSUE TITLE
IQDropDownTextField on click textfield method mannually call

### ISSUE THREAD

**Issue by shahrukh-61** [hackiftekhar/IQKeyboardManager#527]
I am using IQDropDownTextfield in storyboard so i am facing a issue how to click listner call in textfield method because not single textfield Delegate method call.

**Comment by hackiftekhar** [comment]
Not sure what you are asking. Could you please provide some details that what you are trying to achieve?

**Comment by shahrukh-61** [comment]
1)I am drag UITextfield in sotryboard
2)Set uitextfield class change to IQDropDownTextfield.
3) call in viewwillappear
-(void)setDataIQDropDownTextField:(NSArray *)arr :(IQDropDownTextField *)textfield
{
    textfield.isOptionalDropDown = YES;
    [textfield setItemList:arr];
}
 whenever i am click in IQDropDownTextfield Pickerview is Open 
so now this all good But my problem is 

Problem: this uitextfield delegate method not call when i click on IQDropDownTextfield.


- (BOOL)textFieldShouldBeginEditing:(UITextField *)textField;        // return NO to disallow editing.
- (void)textFieldDidBeginEditing:(UITextField *)textField;           // became first responder
- (BOOL)textFieldShouldEndEditing:(UITextField *)textField;          // return YES to allow editing to stop and to resign first responder status. NO to disallow the editing session to end
- (void)textFieldDidEndEditing:(UITextField *)textField;             // may be called if forced even if shouldEndEditing returns NO (e.g. view removed from window) or endEditing:YES called

- (BOOL)textField:(UITextField *)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString *)string;   // return NO to not change text

- (BOOL)textFieldShouldClear:(UITextField *)textField;               // called when clear button pressed. return NO to ignore (no notifications)
- (BOOL)textFieldShouldReturn:(UITextField *)textField;              // called when 'return' key pressed. return NO to ignore.

**Comment by shahrukh-61** [comment]
If you are not getting or understanding  my problem so i have to rewrite again.
 When i click UITextField this methd is called  
(void)textFieldDidBeginEditing:(UITextField *)textField; // became first responder


 When i click IQDropDownTextfield this methd is not called  
(void)textFieldDidBeginEditing:(UITextField *)textField; // became first responder

**Comment by hackiftekhar** [comment]
ahh, so you mean it's native delegate methods are not getting called. Make sure you are using the IQDropDownTextField classes from here https://github.com/hackiftekhar/IQDropDownTextField and not from the IQKeyboardManager repo, this will probably fix your problem. IQKeyboardManager has old version of IQDropDownTextField. If you still having issues then you should open an issue here https://github.com/hackiftekhar/IQDropDownTextField/issues and not in this repo.
