### ISSUE TITLE
Not Workin in All views for some iPhones

### ISSUE THREAD

**Issue by MuhammedFareed** [hackiftekhar/IQKeyboardManager#528]
I have used the swift version , I have many views in my app in which the IQKeyboard is working fine, however there is one view with one text box , on the iphone 6, 6s , 6 plus , 6s plus it is working and the IQKeyboard is shown , on the 5, 5s , 4s for the same view the IQKeyboard is not showing

**Comment by hackiftekhar** [comment]
Could you please share demo?

**Comment by MuhammedFareed** [comment]
![screen shot 2016-06-07 at 3 37 42 pm](https://cloud.githubusercontent.com/assets/16104978/15859584/6cca6cf6-2cce-11e6-8ddd-987e96dcad2c.png)
this what i gets ,, it is only in this view ,, for the iphone 4s ,5 and 5s it is working in the other views
I have followed the usage tutorial , I Added the IQKeyboardmanager.sharedManager().enable=true to my App delegate .
I have no pin constraints in that view that has the problem

**Comment by hackiftekhar** [comment]
Did you tested on real devices? This is probably because you enabled hardware keyboard in iOS simulator.

**Comment by MuhammedFareed** [comment]
I tested it on a real 5s , the same problem ,, It is just weird because it is working fine all over the app, it is just this view actually

**Comment by hackiftekhar** [comment]
I don't know the actual reason that is it a but in library or is there any other issues with your view hierarchy. Could you please share a demo so that I can debug it?

**Comment by MuhammedFareed** [comment]
I will check my view once again , if nothing new happened i will send you a copy of the view to debug it

**Comment by hackiftekhar** [comment]
You may check if you pinned any of your views with either TopLayoutGuide or BottomLayoutGuide.

**Comment by MuhammedFareed** [comment]
I have checked my views many times, the funny thing it turns out that the library did not start at all , while i'm debugging the library works fine , but is not working after i submit to the store and install my app on other device

**Comment by MuhammedFareed** [comment]
I have checked my views many times , no Top or Bottom LayoutGuide used , and still the IQKeyboard is not working , I was mistaken earlier the IQKeyboard doesn't start at all in any of the views of the app. Some of my team mebmers confused it with the keyboard of the iphone and thought the problem was only in one or two views. It turned out that the IQKeyboard doesn't actually shows up , although Using eh IQKeyboardManager.sharedManage().enable=true in the App Delegate

**Comment by hackiftekhar** [comment]
Ahh, so you are using swift version. Swift version needs to be enable in AppDelegate due to some swift language limitations.

**Comment by hackiftekhar** [comment]
So it's working fine now. Right?

**Comment by MuhammedFareed** [comment]
Yeah , now it is working fine .. I checked the code again and everything is fine , i just thaught the problem was with the IQKeyboard as it was working fine then it stopped workin suddenly
