### ISSUE TITLE
Possible to override Placeholder text? and Override Next button?

### ISSUE THREAD

**Issue by RZR666** [hackiftekhar/IQKeyboardManager#529]
Hi,

Is it possible to set a different text for a specific input field instead of the placeholder?

Also it possible to set a custom next button action for a specific field?

Thanks

**Comment by hackiftekhar** [comment]
For placeholder, you can check 'IQUIView+IQToolbar.h', there is a property 'placeholderText'.
For custom next action, you can register for a callback using `-(void)setCustomNextTarget:(nullable id)target action:(nullable SEL)action;` method in same file. However you can't change the default implementation of going next. If you want full control then you can add toolbar using methods defined in same file and you'll have all control in your hand.
