### ISSUE TITLE
Problem with disabling toolbar in specific class

### ISSUE THREAD

**Issue by acerts04** [hackiftekhar/IQKeyboardManager#530]
Hello, 
I am attempting to disable the toolbar in a specific class using IQKeyboardManager.sharedManager().disabledToolbarClasses  , but doing so does not disable the toolbar in the class i want it to. Only the deprecated line of code does.
IQKeyboardManager.sharedManager().disableToolbarInViewControllerClass(OutputViewController)

**Comment by hackiftekhar** [comment]
Could you please check the demo app once? Looks like it is working fine there.

**Comment by acerts04** [comment]
Thanks for the reply, hack. I will take a look, is it ok to use disableToolbarInViewControllerClass for now as that is working no problem for me?
