### ISSUE TITLE
Be Ready for Swift 3

### ISSUE THREAD

**Issue by hardikdevios** [hackiftekhar/IQKeyboardManager#531]
I know its still very much early to post but just want you to take a look of changes of Swift 3 in this lib

![screen shot 2016-06-11 at 2 09 25 pm](https://cloud.githubusercontent.com/assets/6657591/15984150/69a65824-2fde-11e6-8f04-51f62f807c06.png)

you can close it but if you like you can try **Swift 3 toolchain** just to check how much changes are there, i know they will give code converter but some code need to be fixed by us, i guess.

**Comment by hackiftekhar** [comment]
Thanks @hardikdevios for the update, will surely look. Thanks 🙂

**Comment by hvtor** [comment]
Hey @hackiftekhar I'd love to be able to help with the upgrades to Swift 3. How can I help?

**Comment by hackiftekhar** [comment]
@hardikdevios @hvtor I created `swift3` branch for you guys. You all can start creating pull requests pointing to `swift3` branch.

**Comment by Tulleb** [comment]
I am currently working on the Beta 6 compatibility, but there is a lot of issues caused by the update [27639935](http://adcdownload.apple.com/Developer_Tools/Xcode_8_beta_6/Release_Notes_for_Xcode_8_beta_6.pdf)...
