### ISSUE TITLE
Swift disabledToolbarClasses is not working

### ISSUE THREAD

**Issue by topchiyev** [hackiftekhar/IQKeyboardManager#532]
IQKeyboardManager.sharedManager().disabledToolbarClasses.insert(CustomTableViewController)
error: 
Cannot convert value of type '(CustomTableViewController).Type' (aka 'CustomTableViewController.Type') to expected argument type 'String'

IQKeyboardManager.sharedManager().disabledToolbarClasses.insert(**"CustomTableViewController"**)
No error, But in runtime generates lots of broken LayoutConstraint errors. And does not actually hide the toolbar.

**Comment by hackiftekhar** [comment]
Are you using pods version or the latest master source code?

**Comment by topchiyev** [comment]
pod 'IQKeyboardManagerSwift', '4.0.3'

**Comment by hackiftekhar** [comment]
I think your this line `IQKeyboardManager.sharedManager().disabledToolbarClasses.insert("CustomTableViewController")` should work but not sure why it's not working for you.

**Comment by hackiftekhar** [comment]
I checked it with demo
project and it's working as expected. I'm not sure about the current version 3.0.4. But if there are any issues then it will be solve in next release.
