### ISSUE TITLE
I have a requirement， I want to disabled toolbar in some textfield，but don't effect other textfield?

### ISSUE THREAD

**Issue by bianxiang** [hackiftekhar/IQKeyboardManager#533]
Hello！I have a requirement， I want to disabled toolbar in some textfield，but don't effect other textfield? how to？

**Comment by hackiftekhar** [comment]
You can set `textField.inputAccessoryView = [[UIView alloc] init];` for those textFields whome you want to disable toolbar and this will work for you.

**Comment by bianxiang** [comment]
I have try ,but don't take effect ~~ can you give it a try   or tell me when to set （textField.inputAccessoryView = [[UIView alloc] init];）
![img_0539](https://cloud.githubusercontent.com/assets/16380379/16075960/b8d300e4-3323-11e6-823a-dd37579a0bc3.PNG)
![image](https://cloud.githubusercontent.com/assets/16380379/16075981/d4e6aec0-3323-11e6-99f3-7acacc65eba7.png)

**Comment by hackiftekhar** [comment]
Give a try to `tf.inputAccessoryView = UIView();` You are currently writing it with optional `?`

**Comment by bianxiang** [comment]
AHa ，thank you!
