### ISSUE TITLE
Problem with IQTextView delegate (and possible fix)

### ISSUE THREAD

**Issue by tkallioras** [hackiftekhar/IQKeyboardManager#535]
In a Swift 2.2 XCode project, the IQTextView delegate does not work (no calls to the UITextViewDelegate are made). After some tries, I removed the `get` `set` properties, and I used a `didSet` property, where I just call the `refreshPlaceholder` function. It seems to be working now.

**Comment by hackiftekhar** [comment]
I checked with my demo and the previous logic works for me by mapping from storyboard and also by setting delegate programmatically. I updated demo here 7d1dcdd9e3f23cf0d43b9c828778662904bd5e5a please check. I don't think this needs any changes. btw are you using `IQKeyboardReturnKeyHandler` for that class?

**Comment by tkallioras** [comment]
I do not use `IQKeyboardReturnKeyHandler'
I am mapping the delegate both from storyboard and programmatically, and it is still not working.
I may be wrong but the delegate is a stored property and not a computed property, isn't it? Because `get` and `set` in Swift only work with computed properties. For any other case `disSet` and `willSet` are used to "override" the default implementation.

**Comment by hackiftekhar** [comment]
I override `delegate` property and it's `get` observer to refresh placeholder text show/hide. I observed that the `delegate` `get` observer is always called if there are any changes with the textView. It was necessary for me to override `set` property too because it's readwrite.
