### ISSUE TITLE
Need to change Keyboard barItem's Language.

### ISSUE THREAD

**Issue by Prit-Singh** [hackiftekhar/IQKeyboardManager#538]
Great Work done by you,
But i face one issue. When i try to change language of my app within the app. App language is changed except Keyboard barItem. I need to change this too. 
I initialise  IQKeyboardManager in AppDelegate and change the language from any class.Please let me know how to change language of keyboard Item bar. 

Thank you..

**Comment by hackiftekhar** [comment]
Do you want to change done button text on the fly? I mean when you change your app language from app then keyboard done button should also be change immediately? If YES, then you can take a look at `toolbarDoneBarButtonItemText` and you can change done button text on the fly. Let me know if you need more help.

**Comment by Prit-Singh** [comment]
Thank you @hackiftekhar your suggestion is working for me. I access toolbarDoneBarButtonItemText in my class and change language with NSLocalizedString. Its working fine now.
