### ISSUE TITLE
Previous, Next, Done button are set to White Color by default ?

### ISSUE THREAD

**Issue by bhavya-kothari** [hackiftekhar/IQKeyboardManager#54]
Hi Mohd Iftekhar Qurashi,
I would to congratulate for making such an excellent control.
However when i set color using appearance class.

Previous, Next, Done buttons appears in white color.

I have attached screen shot as follows for the same:

![ios_simulator_screen_shot_jul_2__2014__11_11_25_am](https://cloud.githubusercontent.com/assets/6544244/3452202/45107d52-01ad-11e4-811c-335b2a49519f.png)

AppDelegate.m

```
 - (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
 {
   if (SYSTEM_VERSION_GREATER_THAN_OR_EQUAL_TO(@"7.0")) {

    [[UINavigationBar appearance]setBarTintColor:[UIColor whiteColor]];
  [[UIBarButtonItem appearance] setTintColor:[UIColor whiteColor]];
    } else {

        [[UINavigationBar appearance]setTintColor:[UIColor whiteColor]];

   }

     [[UINavigationBar appearance]setBackgroundImage:[UIImage  imageNamed:@"invite_friend_notify_bar"] forBarMetrics:UIBarMetricsDefault];


    NSDictionary *attributes = [NSDictionary dictionaryWithObjectsAndKeys:
                            [UIFont fontWithName:@"Helvetica-Light" size:20],  NSFontAttributeName,
                                [UIColor whiteColor], NSForegroundColorAttributeName, nil];

     [[UINavigationBar appearance] setTitleTextAttributes:attributes];


      [[UIBarButtonItem appearance] setTintColor:[UIColor whiteColor]];
 }
```

**Comment by muhammedkarakul** [comment]
Hi @hackiftekhar i have the same issue. I use 6.5.6 version of IQKeyboardManager via Cocopods. Keyboard toolbar items and cursor color have white tint color. I know issue closed but maybe some development affected this situation. Can you check it?
