### ISSUE TITLE
UITextFields inside different UIViews

### ISSUE THREAD

**Issue by ish3lan** [hackiftekhar/IQKeyboardManager#540]
I have 5 text fields in my ViewController, each is inside a UIView along with a label.

![screen shot 2016-06-24 at 11 36 28 pm](https://cloud.githubusercontent.com/assets/7420284/16349981/7f1e49d8-3a64-11e6-9d08-f5453dca922d.png)

How can I manage to have the functionality working? now it deals with each view (the container of UILabel and UITextField) as a separate thing, I want it to deal with all textViews in a UIViewController as if they were subviews of the outer UIView

**Comment by ish3lan** [comment]
I was able to solve this by building the constraints from the bottom of the ViewController, I had an upper constraint between the first View(container) and the outer View, this constraint was making the trouble

**Comment by hackiftekhar** [comment]
Previous next button only works with textField siblings, by default it will not work if your text Fields are in different views. But there is a workaround and you can take a look at IQPreviousNextView in demo project. Hope this help.

**Comment by ish3lan** [comment]
@hackiftekhar I am sorry to say this, I could not understand how this is supposed to be done,

What I have done?
1. search for IQPreviousNextView in the demo app,
2. What I figured out was { I have IQPreviousNextView that will be switched on and off, but not sure how to use it to solve my problem}
Your help is really appreciated 
Thank you

**Comment by hackiftekhar** [comment]
@ish3lan I'm updating doc here https://github.com/hackiftekhar/IQKeyboardManager/blob/master/MANUAL%20MANAGEMENT.md please take a look

**Comment by ish3lan** [comment]
@hackiftekhar Thank you for the neat solution, it works absolutely fine now 👍🏻
