### ISSUE TITLE
How can I close IQKyeboardManager in a special viewcontroller?

### ISSUE THREAD

**Issue by liaodalin19903** [hackiftekhar/IQKeyboardManager#541]
How can I close IQKyeboardManager in a special viewcontroller? in my project I have a controller does not need IQKeyboardManager,how can I close IQKeyboardManager in that viewcontroller?

**Comment by hackiftekhar** [comment]
You could take a look at this property

`@property(nonatomic, strong, nonnull, readonly) NSMutableSet<Class> *disabledDistanceHandlingClasses;`

Hope this helps.
