### ISSUE TITLE
Can you fix the screenshots in MANUAL MANAGEMENT.md?

### ISSUE THREAD

**Issue by Sweeper777** [hackiftekhar/IQKeyboardManager#545]
I am learning how to use the library but I saw that some screenshots are missing. Can you fix it? I really want to know how to work with Bottom Layout Guide constraints.

Specifically, these screenshots:

<img width="905" alt="screen shot 2016-06-28 at 10 58 21 pm" src="https://cloud.githubusercontent.com/assets/13585047/16420417/d73710b0-3d83-11e6-869d-cd00755aa093.png">

**Comment by hackiftekhar** [comment]
Dure! Will do today!

**Comment by Sweeper777** [comment]
Thanks, please tell me when it is fixed.

**Comment by hackiftekhar** [comment]
Screenshot is restored
