### ISSUE TITLE
How can I hide all the things but the done button in the toolbar?

### ISSUE THREAD

**Issue by Sweeper777** [hackiftekhar/IQKeyboardManager#546]
If I set `enableAutoToolbar` to `true`, the toolbar will have the < > buttons, the placeholder, and the done button. But I only want the Done button.

I found out I can set `shouldShowTextFieldPlaceholder` to hide the placeholder, but how can I hide the < > buttons as well?

**Comment by hackiftekhar** [comment]
There is another property to hide previousNext button, you should use shouldHidePreviousNext for this.

**Comment by Sweeper777** [comment]
Oh yes! My eyesight is kind of bad... Maybe you can put it in the PROPERTIES AND FUNCTIONS.md?

**Comment by hackiftekhar** [comment]
You probably correct. I need to update **PROPERTIES AND FUNCTIONS.md** docs. I hasn't updated it from a long time.
