### ISSUE TITLE
Resizeable textView inside scrollView issues

### ISSUE THREAD

**Issue by r00li** [hackiftekhar/IQKeyboardManager#547]
Hi!
I have an issues with using IQKeyboard manager in combination with a textView and a scrollView.

Basically I have a slightly larger form that doesn't normally fit on a screen. So I am using a scrollview to display it. In that form I have a bunch of textfields and a single textview. I have scrolling disabled for the textview because I want the textview to resize when I enter multiline text.

And here is the issue. When a line break happens inside the textview, the whole thing resizes as it shoutd. But instead of the view scrolling to display the new line of text, the view jumps in the wrong direction and the keyboard obscures the text being entered. And when I enter another character the view jumps to the correct position and everything works as it should. Until the next line break.

I am attaching a sample project where this issue can be seen. I was running the project on an iPhone 5S with iOS 9.3. 
[IssueTest.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/340945/IssueTest.zip)

**Comment by hackiftekhar** [comment]
Thanks @r00li for demo project, I'll test it and will let you know my feedback.

**Comment by hackiftekhar** [comment]
I checked and I think it's an special case where textView height is dynamic when keyboard is appearing. You could listen to textChange notifications and make a call to `reloadLayoutIfNeeded` method of IQKeyboardManager to refresh view positions. This may be an expensive call so you could check that if a line break is added or not and then choose to call `reloadLayoutIfNeeded` or not.

**Comment by r00li** [comment]
I actually tried that:
`    func textViewDidChange(textView: UITextView) {
        IQKeyboardManager.sharedManager().reloadLayoutIfNeeded()
    }`

Adding this (and connecting the textview delegate of course) helps a bit, but doesn't actually fix the issue. It just makes it less severe. Still looks ugly though.

**Comment by hackiftekhar** [comment]
So before making a call to reloadLayoutIfNeeded, the textView frame should be updated, if it's not getting updated before the call then this may be the issue.

**Comment by ealeksandrov** [comment]
This solves everything for me:

```swift
func textViewDidChange(textView: UITextView) {
    textView.layoutIfNeeded()
}
```

**Comment by kajalsheth** [comment]
func textViewDidChange(_ textView: UITextView) {
IQKeyboardManager.shared().reloadLayoutIfNeeded()
            textView.layoutIfNeeded()
        }
