### ISSUE TITLE
Remove next/previous arrows

### ISSUE THREAD

**Issue by idokleinman** [hackiftekhar/IQKeyboardManager#548]
Is there a way to programmatically remove the next/previous arrows for a specific viewcontroller?

**Comment by hackiftekhar** [comment]
Nope, there is no way to remove it for specific viewController. You must have to use the global property.

**Comment by idokleinman** [comment]
What's the global property for removing those?

**Comment by hackiftekhar** [comment]
You can find that property in IQKeyboardManager.h.

**Comment by idokleinman** [comment]
Got it, thanks
