### ISSUE TITLE
iPad Issue : portrait to landscape

### ISSUE THREAD

**Issue by maulikpat** [hackiftekhar/IQKeyboardManager#553]
Hi,

I found one issue in iPad. In your demo code, in portrait select Present and select the last text filed so keyboard will be displayed and view will scrolls up.

![simulator screen shot jul 5 2016 12 39 40 pm](https://cloud.githubusercontent.com/assets/2304770/16576565/9e1ef2aa-42ad-11e6-85e9-b23de22f6228.png)

Now change the orientation. Text filed will be covered by keyboard. 

![simulator screen shot jul 5 2016 12 39 45 pm](https://cloud.githubusercontent.com/assets/2304770/16576567/a5e13412-42ad-11e6-9739-f4dc9e7ce6c5.png)

Any suggestion to solve this ?

**Comment by hackiftekhar** [comment]
Will look into this Thanks for letting me know

**Comment by walker-ll** [comment]
I found  the codes download from git is different from cocoaPods ~

**Comment by hackiftekhar** [comment]
@walker-ll So what's the issue with this? CocoaPods has stable version while git->master branch is the development branch.

**Comment by hackiftekhar** [comment]
@maulikpat I checked this issue and I found that iOS internally changing view's frame and not respecting the frame I explicitly set in library, so probably this cannot be fix.
