### ISSUE TITLE
Keyboard is covering up textfield inside a subview

### ISSUE THREAD

**Issue by vinnyoodles** [hackiftekhar/IQKeyboardManager#554]
I placed my textfields in a container view and when I open the keyboard, it covers up the textfields.

**Comment by vinnyoodles** [comment]
![demo](https://cloud.githubusercontent.com/assets/8698599/16605588/50da82f6-42fe-11e6-8beb-47437309f933.gif)

**Comment by vinnyoodles** [comment]
It fixed itself when I removed it from the container view

**Comment by hackiftekhar** [comment]
You've pinned your view with topLayoutGuide that's why it's behaving like this and it's expected behavior according to iOS.
