### ISSUE TITLE
IQKeyboardManager can't move downwards of scroll view

### ISSUE THREAD

**Issue by yslforrest** [hackiftekhar/IQKeyboardManager#555]
In my view controller, I have a navigation bar on the top and a tool bar at the bottom. In the middle, I have 4 UITextFields and 1 UITextView in a view. And I'm working with AutoLayout. 
In order not to move upwards the navigation bar, I have changed my view controller's view to UIScrollView in the storyboard. But then another problem jumped up, when the pointer moved upwards, IQKeyboardManager didn't move downwards of the scroll view.

**Comment by yslforrest** [comment]
I'm pinning my UITextfield/UITextView contained view with TopLayoutGuide/BottomLayoutGuide. And I followed the IQKeyboardManager document to map TopLayoutGuide/BottomLayoutGuide constraint with IQLayoutGuideConstraint. But It still doesn't work.

**Comment by hackiftekhar** [comment]
I believeyour UIScrollView is not getting proper contentSize. Could you please try adding a scrollView in your view hierarchy (not changing main UIView class to UIScrollView) and put all your textField inside it with proper autolayout constraint?

**Comment by yslforrest** [comment]
I tried to add a scrollView in my view hierarchy and give it proper autolayout constraints and it works. Thank you.
