### ISSUE TITLE
Keyboard bug

### ISSUE THREAD

**Issue by king129** [hackiftekhar/IQKeyboardManager#556]
When I was in other application pop-up keyboard Return my current when the keyboard out of the application of step down again

**Comment by hackiftekhar** [comment]
Can't understand, please explain.

**Comment by king129** [comment]
Aapp is my project One of the pages have pop-up keyboard events, but I did not trigger it

At that time I double click the HOME switch to Bapp after Bapp pop-up keyboard In double click HOME to return to the Aapp

At this time the Aapp appeared a keyboard pops up and step down Can you understand what I mean

**Comment by hackiftekhar** [comment]
I got a basic understand what you are trying to explain. Could you please share screenshot of your A app when you come back to it at last?

**Comment by king129** [comment]
Mainly Aapp listening to the keyboard Bapp notice, I think it's not your framework

**Comment by hackiftekhar** [comment]
In iOS A App is completely different from B App, generally not possible to exchange any kind of messages or notifications directly between different apps.

**Comment by king129** [comment]
Is indeed had received other applications of the keyboard!  
I added the following code application state judgment is not that kind of problem.

`- (void)_keyboardWillShow:(NSNotification*)sender
{
    FALogRed(@"应用状态 %ld",[UIApplication sharedApplication].applicationState)
    if ([UIApplication sharedApplication].applicationState != UIApplicationStateActive)  return;
    
    NSValue* keyboardBounds = sender.userInfo[UIKeyboardFrameEndUserInfoKey];
    CGFloat keyboardHeight = [keyboardBounds CGRectValue].size.height ;

    [UIView animateWithDuration:0.3 animations:^{
        self.backgroundView.alpha = 0.5 ;
        self.inputView.bottom = self.inputViewSuperView.height - (keyboardHeight) ;
    }];
}
- (void)_keyboardDidChanged:(NSNotification*)sender
{
    if ([UIApplication sharedApplication].applicationState != UIApplicationStateActive)  return;
    
    NSValue* keyboardBounds = sender.userInfo[UIKeyboardFrameEndUserInfoKey];
    CGFloat keyboardHeight = [keyboardBounds CGRectValue].size.height ;
    [UIView animateWithDuration:0.3 animations:^{
        self.inputView.bottom = self.inputViewSuperView.height - (keyboardHeight ) ;
    }];
}
- (void)_keyboardWillHide:(NSNotification*)sender
{
    if ([UIApplication sharedApplication].applicationState != UIApplicationStateActive)  return;
    
    [UIView animateWithDuration:0.3 animations:^{
        self.backgroundView.alpha = 0 ;
        self.inputView.top = self.inputViewSuperView.height  ;
    }];
    
}`

**Comment by SPkay** [comment]
I had this problem too.
My solution is: 
`- (void)applicationWillResignActive:(UIApplication *)application {
    [[UIApplication sharedApplication].keyWindow endEditing:YES];
}`

**Comment by king129** [comment]
@SPkay You also have a good solution

**Comment by hackiftekhar** [comment]
Yeah, @king129 and I think it's developer responsibility to take appropriate action when application goes/comeback to background/foreground.
