### ISSUE TITLE
how to change the Toolbar's done button 's name

### ISSUE THREAD

**Issue by resand** [hackiftekhar/IQKeyboardManager#557]
how to change the Toolbar's done button 's name en Swift??
<img width="321" alt="captura de pantalla 2016-07-07 a las 1 58 27 p m" src="https://cloud.githubusercontent.com/assets/5307015/16665915/e77c25e6-444a-11e6-989a-463c0e7ab3d8.png">

**Comment by hackiftekhar** [comment]
There  is a property exposed with IQKeyboardManager class to change Done button text.

**Comment by resand** [comment]
look but found, as it is called property?

**Comment by hackiftekhar** [comment]
It's toolbarDoneBarButtonItemText`

**Comment by alfredolucomav** [comment]
Hi @hackiftekhar I'm trying to set done button's text but is not working. There's my code:

```
    [[IQKeyboardManager sharedManager] setEnable:YES];
    [IQKeyboardManager sharedManager].toolbarDoneBarButtonItemText = @"Ok";
```

Best Regards

**Comment by resand** [comment]
@alfredolucomav It works for me in Swift, this is my code:
       `IQKeyboardManager.sharedManager().toolbarDoneBarButtonItemText = "Ok"
        IQKeyboardManager.sharedManager().enable = true`

**Comment by resand** [comment]
@alfredolucomav It works for me in Swift, this is my code:

```
IQKeyboardManager.sharedManager().toolbarDoneBarButtonItemText = "Ok"
IQKeyboardManager.sharedManager().enable = true
```

Try to reverse the order of the lines, possibly when initializing the pod add the additional configuration.

**Comment by alfredolucomav** [comment]
@resand but It does not woriking on Objective-c's library. Any Suggestion?

Best Regards

**Comment by resand** [comment]
@alfredolucomav Personally I don't know any other capsules or library. You can perform your own implementation of a custom view with a general xib.

**Comment by resand** [comment]
@alfredolucomav Personally I don't know any other pod or library. You can perform your own implementation of a custom view with a general xib.

**Comment by SMalagic** [comment]
You can edit from pod files. Just go to **1952**. line in IQKeyboardManager.m file
