### ISSUE TITLE
Error: Value of type 'Set<String>' has no member 'append'

### ISSUE THREAD

**Issue by younanjo** [hackiftekhar/IQKeyboardManager#560]
Hi Guys,

All of a sudden I'm getting a compile time error on following line:

`IQKeyboardManager.sharedManager().toolbarPreviousNextAllowedClasses.append(RootView)`

Error says:
`Value of type 'Set<String>' has no member 'append'`

Compiles fine on Simulator, but gives compile time errors as above when building on "Generic iOS device" or on real device? Any ideas what's going on here? 

http://stackoverflow.com/questions/38301502/swift-compile-error-based-on-what-device-build-is-happening-on

**Comment by hackiftekhar** [comment]
Which Xcode version you are using?

**Comment by younanjo** [comment]
OSX El Capitan, Xcode 7.3.1

**Comment by hackiftekhar** [comment]
@younanjo Do you think you are still getting issues with this method?
