### ISSUE TITLE
Not work in Swift

### ISSUE THREAD

**Issue by cconecode** [hackiftekhar/IQKeyboardManager#561]
when I use in swift, then in Appdelegate set enable = true, but isn't work. I used 4.0.3

![2016-07-12 17 04 17](https://cloud.githubusercontent.com/assets/14048405/16761426/b75c3a84-4852-11e6-8912-290176674936.png)

**Comment by hackiftekhar** [comment]
May be you are pinning your view to top layout guide.

**Comment by cconecode** [comment]
yeah, I'm pinning to top layout guide, so must pinning to bottom ?

**Comment by hackiftekhar** [comment]
It doesn't directly wirk with layout guide constraint, please check documentation.
