### ISSUE TITLE
showing the keyboard pulls the form down!

### ISSUE THREAD

**Issue by IsmailHassanein** [hackiftekhar/IQKeyboardManager#562]
As in the screenshot, when I showed the keyboard the form has been scrolled down till the active field is just above the keyboard!
![screen shot 2016-07-12 at 10 04 04](https://cloud.githubusercontent.com/assets/8446961/16761965/5fd654bc-481a-11e6-9cc3-d6f19e5c0eb7.png)

**Comment by hackiftekhar** [comment]
How was your view looking before presenting showing keyboard?

**Comment by IsmailHassanein** [comment]
![screen shot 2016-07-12 at 11 20 02](https://cloud.githubusercontent.com/assets/8446961/16763926/44f6d9c4-4823-11e6-8797-af87bbf847a8.png)

**Comment by hackiftekhar** [comment]
Hmm, ok, could you please share a demo app so I can check it?

**Comment by IsmailHassanein** [comment]
Actually I don't know how this happens to reproduce it.  it behaves as expected all over the project except for this form. The only different thing here is it presented modally as Form sheet. 
I have tried to change one of the segues to modal form sheet in your demo but It had no problem. 

I will investigate it properly and let you know.
Thanks.

**Comment by hackiftekhar** [comment]
I believe that the issue is there but I don't know the exact configuration by which I can reproduce, if you can give it a try then it would be great, thanks :)

**Comment by stefz** [comment]
@hackiftekhar It appens when the presented form sheet is the root view controller of a UINavigationController. Take a look to my example..
[TestIQKeyboardManager.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/396375/TestIQKeyboardManager.zip)

**Comment by hackiftekhar** [comment]
Thanks for the example project. I'll check.
