### ISSUE TITLE
Hello, often can appear the keyboard according to the phenomenon of blank, this is a kind of what problem, two projects have emerged,

### ISSUE THREAD

**Issue by hzx157** [hackiftekhar/IQKeyboardManager#564]
Hello, often can appear the keyboard according to the phenomenon of blank, this is a kind of what problem, two projects have emerged,
![2c42e5391611c8bcb1f14a7642952d2d](https://cloud.githubusercontent.com/assets/5343996/16839253/b7ce9e58-4a00-11e6-8347-5165ffba5fed.png)

**Comment by hzx157** [comment]
mainly on the UITextView appeared this problem

**Comment by hackiftekhar** [comment]
It looks like you have customised keyboard. right?

**Comment by hzx157** [comment]
是系统自带的键盘，偶尔会出现键盘显示空白，

**Comment by hzx157** [comment]
Is the keyboard system, occasionally there will be a keyboard displayed blank,

**Comment by hackiftekhar** [comment]
Btw I'm not sure if it's library issue or not.

**Comment by hzx157** [comment]
Yes, I've tested if no library won't appear, may also is also linked to other classification,

**Comment by hackiftekhar** [comment]
ok, so it's probably library issue according to you. Could you please provide a demo so that I can look into it?

**Comment by hackiftekhar** [comment]
@hzx157 Could you please provide a demo to debug it?
