### ISSUE TITLE
when the keyboard appeared,it cover the inputview 

### ISSUE THREAD

**Issue by Mr-Luxry** [hackiftekhar/IQKeyboardManager#565]
yes,most time ,the IQKeyboardManager works well and i like it very much.but today i have meet a problem when use it.i have a project which was combined with ios native project and unity-ios project,and the unity-ios project is main. when i touched a textview,the keyboard appeared,but the textview donot change it frame,so the keyboard covered it.i have tried many times,but it still dosenot worked,so i come here to look for your help.
look forward to your replay!
thanks

**Comment by hackiftekhar** [comment]
I haven't tested my library with unity-ios, could you please share demo project so I can take a look?

**Comment by hackiftekhar** [comment]
@Mr-Luxry could you please share demo project?
