### ISSUE TITLE
IQTitleBarButtonItem has no member kIQBarTitleInvocationTarget

### ISSUE THREAD

**Issue by hadiyazdi** [hackiftekhar/IQKeyboardManager#566]
I added IQKeyboardManagerSwift manually to my project, and at first startup I got this error

IQTitleBarButtonItem has no member kIQBarTitleInvocationTarget

**Comment by hackiftekhar** [comment]
Yeah, you was correct, this happens due do recent changes I made yesterday. btw this is fixed now.

**Comment by hadiyazdi** [comment]
Thank you, it works perfectly
