### ISSUE TITLE
Enable IQKeyboardManager only for one ViewController

### ISSUE THREAD

**Issue by sinhagaurav010** [hackiftekhar/IQKeyboardManager#568]
Hi there

I want IQKeyBoardManager to get enabled only for one ViewController, remain disabled for rest.
Could you please help me in this.?

**Comment by hackiftekhar** [comment]
- set NO to global `enable` property.
- Add your ViewController class to `enabledDistanceHandlingClasses` set.

**Comment by damboscolo** [comment]
Not working for me.
