### ISSUE TITLE
Not Wroking in Swift 2.2 and Xcode 7.3 by cocoapods

### ISSUE THREAD

**Issue by dipsvaishnav** [hackiftekhar/IQKeyboardManager#569]
i use IQKeyboardManager but still is not working all device iPhone 4,5,6 and plus
![screen shot 2016-07-15 at 8 06 31 pm](https://cloud.githubusercontent.com/assets/8614189/16877872/d6c93634-4ac7-11e6-9844-c9be346b6780.png)

**Comment by hackiftekhar** [comment]
Please check these things:-
1) Enable in AppDelegate (Swift only)
2) Have you pinned TopLayoutGuie or BottomLayoutGuie with any of the views?

**Comment by ManjulShresth** [comment]
I am having the same issue. The view just wont move up. A quick fix would be appreciated.

**Comment by dipsvaishnav** [comment]
i resolve this issue problem my side remove first uitextfield up constraints

Deepak Kumar Vaishnav

**Comment by ManjulShresth** [comment]
How will it work if you remove first UITextField up constraints. Like how will it know what Y coordinate should first textfield be from?

**Comment by dipsvaishnav** [comment]
can i see your screen

Deepak Kumar Vaishnav

**Comment by ManjulShresth** [comment]
You sure can. Have a look. 
![simulator screen shot aug 1 2016 10 39 47 am](https://cloud.githubusercontent.com/assets/19974269/17283885/3b69ae38-57d5-11e6-8055-c5d95e37627b.png)

The first is search bar with button on it. Second is UITableView and then the TextFields start to come.

**Comment by dipsvaishnav** [comment]
please share me your skype id if u don't mind

Deepak Kumar Vaishnav

**Comment by dipsvaishnav** [comment]
Deepak Kumar Vaishnav

**Comment by dipsvaishnav** [comment]
u See first Uitextfiled constraints

Deepak Kumar Vaishnav

**Comment by dipsvaishnav** [comment]
Hello r u there

Deepak Kumar Vaishnav
