### ISSUE TITLE
react native

### ISSUE THREAD

**Issue by yuyangdexue** [hackiftekhar/IQKeyboardManager#571]
react native  and IQKeyboardManager  load uitextfield  text jump

**Comment by hackiftekhar** [comment]
Could you please share a demo?

**Comment by snowjade** [comment]
maybe I meet the same problem .
![image](https://cloud.githubusercontent.com/assets/11959369/18122484/4be8c602-6f9c-11e6-921b-dc5edd0599c5.png)

![image](https://cloud.githubusercontent.com/assets/11959369/18122440/21e4e7d2-6f9c-11e6-821b-42cfaf319274.png)

**Comment by snowjade** [comment]
this is the main code .
![image](https://cloud.githubusercontent.com/assets/11959369/18122571/b9411e70-6f9c-11e6-843e-f0cc07e0096d.png)
![image](https://cloud.githubusercontent.com/assets/11959369/18122587/c5c7db02-6f9c-11e6-9e0a-20e290efd507.png)

**Comment by yuyangdexue** [comment]
copy 4.04  (iOS 8.0 +)  private pod

**Comment by snowjade** [comment]
@yuyangdexue  sorry, what you mean?  what you say is the problem or the   solution?

**Comment by yuyangdexue** [comment]
@snowjade   我们这个问题是因为 RN 和 IQKeyBoardManager 起冲突了 导致文字抖动 具体是哪 不知道 因为 7.0以上版本不能安装最新的  试了一下 8.0 以上的库 改了一下 这个问题就被解决了 自己做一个私有pod   供内部使用

**Comment by snowjade** [comment]
@yuyangdexue 好的，谢谢。

**Comment by hackiftekhar** [comment]
Not sure what action should I take here. Can you guys let me know.

**Comment by zb1006801184** [comment]
请问如何解决这个问题的？

**Comment by zb1006801184** [comment]
@yuyangdexue  请问如何解决这个问题的
