### ISSUE TITLE
field in multiple stack views  has no previous and next buttons

### ISSUE THREAD

**Issue by RNB-IT** [hackiftekhar/IQKeyboardManager#573]
[KeyBoardTest.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/368138/KeyBoardTest.zip)
Hi 
First of all thanks for the perfect framework!
When we use the IQKeyboardManager with field that's placed in one stackview it works perfect.
But when place the field with one label in another stackview, and that's placed also in a stackview, than the buttons previous and next disappears. 
See the attached test project.  Page one is not working , Page two is just perfect.  What can we do?

Thanks

**Comment by hackiftekhar** [comment]
Thanks for the demo, I'll check.

**Comment by hackiftekhar** [comment]
This is because the second stackView textField's have direct siblings and next/previous logic is written to find direct siblings. The first stackView have different textFields within different stackView which isn't a direct siblings. You can find my answer in #549 issue.
