### ISSUE TITLE
Disable plugin on specify ViewController

### ISSUE THREAD

**Issue by antons81** [hackiftekhar/IQKeyboardManager#574]
How Can I disable IQKeyboardManager on specific controller IQKeyboardManager.sharedManager().enableAutoToolbar = false IQKeyboardManager.sharedManager().enable = false
doesn't work for me

**Comment by hackiftekhar** [comment]
Please take a look at #572 looks like you are looking for this

**Comment by antons81** [comment]
This doesn't help I have tried it as well

  IQKeyboardManager.sharedManager().disabledToolbarClasses.addObject(self)
        IQKeyboardManager.sharedManager().enableAutoToolbar = false
        IQKeyboardManager.sharedManager().enable = false
        
        IQKeyboardManager.sharedManager().disabledDistanceHandlingClasses.addObject(self)

**Comment by hackiftekhar** [comment]
ok, then could you please take a look at demo project? It's implemented there.
