### ISSUE TITLE
It's crash In my Phone.

### ISSUE THREAD

**Issue by MillerJiang538** [hackiftekhar/IQKeyboardManager#578]
This is my code.
 [[IQKeyboardManager sharedManager] disableDistanceHandlingInViewControllerClass:NSClassFromString(@"ReportErrorController")];

This is my debug log.
-[IQKeyboardManager disableDistanceHandlingInViewControllerClass:]: unrecognized selector sent to instance 0x12cd28fb0

Why it's crash In my phone?Thanks!

**Comment by louis-cai** [comment]
which version are you using？

**Comment by hackiftekhar** [comment]
This is replaced by `disabledDistanceHandlingClasses` NSMutableSet with latest version.
