### ISSUE TITLE
View is not restoring to it's normal state when keyboard is dismissed by clicking on webview

### ISSUE THREAD

**Issue by mr746866** [hackiftekhar/IQKeyboardManager#580]
I have a UITextField and a UIWebView in my ViewController. When I click on the UITextField, the view goes up to accommodate the keyboard as expected. Then I click on the UIWebView which dismisses the keyboard but the view is not restored to the initial state. As a result there is a white space below my view and my title bar is not visible.

**Comment by hackiftekhar** [comment]
Secondtime did you coicjed on a textFiekd of UIWebView?

**Comment by mr746866** [comment]
No the UITextField and UIWebView are completely separate. There is a container UIView which is the parent of UIWebView. This UIView and the UITextField are siblings.

**Comment by hackiftekhar** [comment]
But how tapping on the webView dismiss the keyboard?

**Comment by mr746866** [comment]
Same way if I press the Done button on keyboard, except the view does not restore to it's initial state.

**Comment by Rachel829** [comment]
I got the same question with you    i set the shouldResignOnTouchOutside value with 'NO' ;  and  it doesn't work.

**Comment by vbresults** [comment]
@hackiftekhar Thank you for this wonderful plugin (:

This issue is a showstopper :(

**Comment by vbresults** [comment]
@hackiftekhar Any updates?

**Comment by hackiftekhar** [comment]
@vbresults There is no update yet, but it's a bug I know which needs to be fix.

**Comment by hackiftekhar** [comment]
@vbresults, @Rachel829 @mr746866  Just fixed, please check

**Comment by vbresults** [comment]
@hackiftekhar Just ran the new version from cocoapods, works like a charm, thank you (:

**Comment by hackiftekhar** [comment]
Grrat @vbresults
