### ISSUE TITLE
Crash after orientation switch

### ISSUE THREAD

**Issue by OktayGardener** [hackiftekhar/IQKeyboardManager#582]
Yo.

I downloaded your library and tried to use it in my project, works fine except:

User taps the UITextField, gets focus. Switch orientation counter clock wise - crash.

Version 8.0 beta 3 (8S174r)
Objective-C.

#import statement in Appdelegate.m with the following line in didFinihsLaunchingWithOptions:

`    [IQKeyboardManager sharedManager].enable = YES;`

**Comment by hackiftekhar** [comment]
So why are you trying this with iOS8 beta 3? you should try this against final release version. Could you please let me know the details of crash because it doesn't happening in my demo.

**Comment by hackiftekhar** [comment]
@OktayGardener Could you please provide any crash details?

**Comment by OktayGardener** [comment]
Hey man. I decided not to use your lib because of tableview + autolayout problems. I don't remember specific details, but maybe you should check how your library behaves with iOS 10 + Xcode 8

**Comment by hackiftekhar** [comment]
I never tested with iOS10 yet, will definitly try.

**Comment by hackiftekhar** [comment]
I tested with iOS10 and it doesn't crash for me.

**Comment by OktayGardener** [comment]
Awesome. Thanks for closing, I have not had time until now to reach out regarding this.
