### ISSUE TITLE
change donebuttontitle based on textfield

### ISSUE THREAD

**Issue by srikanthraju** [hackiftekhar/IQKeyboardManager#584]
Not working         
      phoneTextfield.doneButtonText = "Continue"

**Comment by srikanthraju** [comment]
I'm not able to add right button of textfields

 phoneTextfield.addRightButtonOnKeyboardWithText("Check", target: self, action: #selector(validate))

**Comment by hackiftekhar** [comment]
There is no such functionality like `phoneTextfield.doneButtonText = "Continue"` but `phoneTextfield.addRightButtonOnKeyboardWithText("Check", target: self, action: #selector(validate))` should work for you.
