### ISSUE TITLE
Subscribe to "done" button action

### ISSUE THREAD

**Issue by hamsternik** [hackiftekhar/IQKeyboardManager#585]
I using your library and a few times ago i found a small problem, making interaction with my screen more problematically. So, i think that's would be great to subscribe, for example, on action for **done** default button in the keyboard toolbar (so, do smth when i pressed on it).

So, the question is - whether implemented this functional? I don't find anything about what i wrote above or about toolbar button actions.

**Comment by oliverfoggin** [comment]
I was just about to ask the same thing :D

**Comment by hackiftekhar** [comment]
IQKeyboardManager class uses `IQUIView+IQKeyboardToolbar` category to add keyboard toolbar. There are two possible ways for you.
1) Subscribe for done button actions but this doesn't let you to override default done button functionality and it will always perform it's default action and you'll only get notify when done is pressed. Please check `Get notified when tapping on previous/next/done button for specific UITextField/UITextView` section here https://github.com/hackiftekhar/IQKeyboardManager/blob/master/MANUAL%20MANAGEMENT.md

2) Add toolbar for your own and handle all the things yourself. You can use `IQUIView+IQKeyboardToolbar` category methods to easily add toolbar over your textFields. Please check `Full customise control over previous/next/done button for specific UITextField/UITextView` here https://github.com/hackiftekhar/IQKeyboardManager/blob/master/MANUAL%20MANAGEMENT.md

**Comment by hamsternik** [comment]
Yep. That's what i actually searched: https://github.com/hackiftekhar/IQKeyboardManager/blob/master/MANUAL%20MANAGEMENT.md#get-notified-when-tapping-on-previousnextdone-button-for-specific-uitextfielduitextview

**Comment by himanthmaddi** [comment]
Page not found on GitHub. Can you please provide new link
