### ISSUE TITLE
Getting Crash when keyboard appear in UItableview cell textfield

### ISSUE THREAD

**Issue by zaptechtusharpatel** [hackiftekhar/IQKeyboardManager#589]
![screen shot 2016-08-02 at 12 38 16 pm](https://cloud.githubusercontent.com/assets/20788848/17319918/77e643f6-58ae-11e6-81e2-254a2ae57f13.png)

**Comment by hackiftekhar** [comment]
Did you get crash only a single time or it is frequently reproducible?

**Comment by zaptechtusharpatel** [comment]
Hello,

It’s frequently reproduced.

Thanks
Tushar Patel

**Comment by hackiftekhar** [comment]
Can you wrap up all this in a demo project?

**Comment by hackiftekhar** [comment]
@zaptechtusharpatel could you please provide any demo project?

**Comment by zaptechtusharpatel** [comment]
Hello,

Sorry for inform you,I had resolve this issue.it was created due to other third party code.

Thank You.
Tushar

**Comment by hackiftekhar** [comment]
Thanks
