### ISSUE TITLE
content sliding under status bar with overlap.

### ISSUE THREAD

**Issue by jamesdo** [hackiftekhar/IQKeyboardManager#592]
Does anyone have a concise workaround for this?

<img width="377" alt="screen shot 2016-08-02 at 3 29 22 pm" src="https://cloud.githubusercontent.com/assets/5696001/17342176/f0c1298c-58c5-11e6-9faa-5f6cce8389fd.png">

**Comment by hackiftekhar** [comment]
Nope, this should be handle manually because library doesn't know if you have any content overlapping statusbar, otgerwise you should put your content in a screollview.

**Comment by jaltying-developer** [comment]
@hackiftekhar Did you exposed some properties that could identify how far did the view moved in Y axis?

**Comment by hackiftekhar** [comment]
@jaltying-developer currently there is ni propery to know about view position movement. But now I think there should be a readonly property to expose this info.

**Comment by apwelsh** [comment]
how do I know when the keyboard is dismissed?

**Comment by hackiftekhar** [comment]
you can add global UIKeyboard notifications provided by UIKit frameworks.
