### ISSUE TITLE
Not working in horizontal UICollectionView inside UITableView

### ISSUE THREAD

**Issue by chika-kasymov** [hackiftekhar/IQKeyboardManager#593]
I have a problem to show keyboard in horizontal `UICollectionView` which is inside `UITableViewCell`.

When I press `UITextField` which is in `UICollectionViewCell`, `UICollectionView` changes it's insets or offsets and disappear from `UITableViewCell`, but keyboard not appear at all.

Can you guide how to solve this issue?

**Comment by chika-kasymov** [comment]
I sovled problem with `UIKeyboard`, it was not showing because I did `[self.tableView reloadData];` in my `keyboardWillShow:` observer. Now keyboard showing, but distance handling is wrong.
When I press `UITextField`, library scrolls `UICollectionView` instead of `UITableView`.

**Comment by hackiftekhar** [comment]
Ok, please provide a demo, I'll check when I'll get some time.

**Comment by chika-kasymov** [comment]
@hackiftekhar I created demo project with my layout structure, you can download it from this [link](https://www.dropbox.com/s/qwiivatwtwreacu/IQTest.zip?dl=0).

**Comment by hackiftekhar** [comment]
Thanks, I'll check it when I get dome free time.

**Comment by hackiftekhar** [comment]
Thanks, I'll check it when I'll get some free time.

**Comment by chika-kasymov** [comment]
I noticed that without using `IQKeyboardManager``UITableView` will scroll automatically to current row with active `UITextField` which is inside `UICollectionView`. Maybe this behaviour makes you library works wrong.

**Comment by ignotusverum** [comment]
Having same issue, been struggling with it for quite some time. Disabling IQKeyboardManager for specific text input would be perfect. Any updates on this issue ?

Thanks !

**Comment by hackiftekhar** [comment]
@chika-kasymov If it's inside UITableViewController then library ignore to scroll and respect default behaviour of UITableViewController.

**Comment by hackiftekhar** [comment]
@ignotusverum This issue exists due to tableview and collectionview cell reusing logic.

**Comment by ignotusverum** [comment]
Got it, thanks for heads up @hackiftekhar.

**Comment by hackiftekhar** [comment]
@chika-kasymov I checked your demo and as I say the issue exists due to the tableview and collectionview cell reusing logic, I cannot do anything with it.

**Comment by chika-kasymov** [comment]
@hackiftekhar ok, I understood. For now this behaviour do not break anything and is sufficient. Thanks for help!

**Comment by brar07** [comment]
I have a similar issue. I have a textfield inside the header(reusableview) of uicollectionview which is inside the footer of uitableview. And, it is not working. Any solutions?
