### ISSUE TITLE
clicked clear button in UITextfield with IQKyeboardManager will fail

### ISSUE THREAD

**Issue by shiyong-zhong** [hackiftekhar/IQKeyboardManager#596]
Seems that IQKyeboardManager captured the button click action ,then keyboard was hidden while the input text in field would not be cleared.

**Comment by hackiftekhar** [comment]
Library generally doesn't capture clear button action, but I'll checkiuf there is anything I can help you with. Keyboard shouldn't be dismiss by library if user tap clear button on text field. Are you sure that you are not dismissing it when clear button tap by user?
