### ISSUE TITLE
UITextView禁用编辑，可选择文本拷贝，这时会有问题

### ISSUE THREAD

**Issue by TheBloodElf** [hackiftekhar/IQKeyboardManager#597]
视图中其他响应者弹起键盘，此时长按UITextView，键盘消失，视图不下降，下面会有黑边。

**Comment by TheBloodElf** [comment]
View other responder bounce keyboard, then press UITextView, keyboard disappears, the view does not drop, the following will be black bars.

**Comment by hackiftekhar** [comment]
Not understand, please share demo.
