### ISSUE TITLE
Sometimes, TextField text frame error when textFieldViewDidBeginEditing

### ISSUE THREAD

**Issue by tigerZhang86** [hackiftekhar/IQKeyboardManager#598]
IQKeyboardManager (3.3.2)

Sometimes,i find textfield's text frame is incorrect  when textFieldViewDidBeginEditing, it would be normal when  textFieldViewDidEndEditing.
What should I do for this?

ps:because upload screenshot fail ,so i paste links :
http://ww1.sinaimg.cn/large/005zmieUjw1f6onze18fdj30hs0qo0t7.jpg
http://ww3.sinaimg.cn/large/005zmieUjw1f6onzz2gg5j30hs0qoaa8.jpg

**Comment by hackiftekhar** [comment]
I got this issue sometime but couldn't identify why this is happening.
