### ISSUE TITLE
Keyboard covers textfield/textview

### ISSUE THREAD

**Issue by rabehssera** [hackiftekhar/IQKeyboardManager#599]
Hello

I have a view controller with 2 views in it. 1 is a static view, the other one is a scroll view. Inside the scroll view, there's a textview. When I tap in it, the keyboard appears, its top being at the top of the scrollview.

So, the keyboard covers the textview.

Can you help me ?

Thanks

**Comment by hackiftekhar** [comment]
I'll check it, if you could provide a demo then it would be great.

**Comment by hackiftekhar** [comment]
@rabehssera Could you please provide a demo?
