### ISSUE TITLE
Can you public keyboard property ?

### ISSUE THREAD

**Issue by Whirlwind** [hackiftekhar/IQKeyboardManager#600]
Sometimes, I need get the properties of the keyboard, e.g. Frame, Size, isShowing ...

I know that I can add observer to the keyboard notification, but I hope get the information without observer.

Can you public the properties about the keyboard?

**Comment by hackiftekhar** [comment]
I can think about making some information public.

**Comment by hackiftekhar** [comment]
For getting keyboard information I think the best way to add notifications. For `isShowing` and `movedDistance` I exposed properties.
