### ISSUE TITLE
Doesn't work correctly for container view

### ISSUE THREAD

**Issue by MJason23** [hackiftekhar/IQKeyboardManager#601]
I have a view controller contains another view controller's view within a container view, and that contained view controller has 3 UITextField, keyboard will cover those text field when I try to input. What should I do for this?

**Comment by hackiftekhar** [comment]
I'll check it with a demo, because it should work with you situation too.

**Comment by MJason23** [comment]
Well, it works now after I embed all of those textfields in a stack view, and place that stack view onto a scroll view. Thanks anyway~
