### ISSUE TITLE
Swift - IQKeyboardManager.sharedManager() ignored

### ISSUE THREAD

**Issue by lecksfrawen** [hackiftekhar/IQKeyboardManager#602]
Hi. When I use the following function...
``` swift
aTextField.addPreviousNextDoneOnKeyboardWithTarget(_:previousAction:nextAction:doneAction:shouldShowPlaceholder:)
```  
... in any UITextField, the IQKeyboardManager.sharedManager() object properties are ignored for that UITextField.

This is what happens:
![Example](https://d3dr1ze7164817.cloudfront.net/items/3W0D3u1V2N2h1c0s3V1J/Screen%20Recording%202016-08-10%20at%2001.30%20PM.gif)

Am I missing something?

I'm setting the following properties in AppDelegate:
![AppDelegate.swift](https://d3dr1ze7164817.cloudfront.net/items/2P0M421v130G1P0a1I3T/Image%202016-08-10%20at%203.56.16%20PM.png)

1. The first UITextField is using addPreviousNextDoneOnKeyboardWithTarget. Shows black labels.
2. The second UITextField is not. Shows white labels.

I'm using: Swift 2.2, IQKeyboardManagerSwift 4.0.4
Testing in: iOS 9.3

**Comment by hackiftekhar** [comment]
Using `addPreviousNextDoneOnKeyboardWithTarget` method is purely manual, you have to handle all the things. It's just a convenient method to add UIToolbar and easily add callback functions only.

**Comment by lecksfrawen** [comment]
I see. Thanks for the quick reply.
