### ISSUE TITLE
Can't reload input toolbar to enable next btn after unhiding textField

### ISSUE THREAD

**Issue by MaximusMcCann** [hackiftekhar/IQKeyboardManager#603]
Demo & video attached.
I have UITextFields that start off as hidden.  Then an action unhides them.  I have been unable to figure out how to refresh the autoToolbar on IQKeyboard manager.  Please help.

![iqkeyboardmanagerdemo](https://cloud.githubusercontent.com/assets/1643285/17575495/37f52168-5f2f-11e6-8a33-28a5bccd92d3.gif)

[IQKeyboardManagerDemo.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/412353/IQKeyboardManagerDemo.zip)

**Comment by hackiftekhar** [comment]
There is a method to in IQKeyboardManager to reload inputViews, please call that method to reload UI at your convenience.

**Comment by MaximusMcCann** [comment]
Have tried variations of this method to toggle the buttons:
```
  func toggleViews() {
    dispatch_async(dispatch_get_main_queue()) {
      [self.tf3, self.tf4].forEach { $0.hidden = !$0.hidden }
      [self.tf1, self.tf2].forEach { $0.reloadInputViews() } // Thought this would do it...

      IQKeyboardManager.sharedManager().layoutIfNeededOnUpdate = true // tried this as well 
      IQKeyboardManager.sharedManager().reloadLayoutIfNeeded()
      }
  }
```

I have looked through IQKeyboardManager.swift, but am not seeing a specific method to call to update the input view.  I clearly must be missing something :/
Have tried setting `layoutIfNeededOnUpdate = true`
Have tried `reloadLayoutIfNeeded()`
Have updated to make sure I'm using v4.0.4
I see `textFieldViewDidBeginEditing` calls `reloadInputViews()`, but that appears to be the only method.

Appreciate your help

**Comment by MaximusMcCann** [comment]
This is my gross solution:
```
  func toggleViews() {
    [self.tf3, self.tf4].forEach { $0.hidden = !$0.hidden }
    
    UIView.animateWithDuration(0.0001, animations: {
      IQKeyboardManager.sharedManager().enableAutoToolbar = false
      }, completion: { (complete) in
        IQKeyboardManager.sharedManager().enableAutoToolbar = true // Retriggers the private method addToolbarIfRequired()
        self.tf2.reloadInputViews() // Actually reload the view
    })
  }
```

**Comment by hackiftekhar** [comment]
`- (void)reloadInputViews` is the main function which reload inputViews. Now I think I should also trigger addToolbarIfRequired method in reloadInputViews method.

**Comment by hackiftekhar** [comment]
Swift version is missing `- (void)reloadInputView` method in IQKeyboardManager class while it is there in Objective-C version. I'm adding it.
