### ISSUE TITLE
Library is changing text appearance

### ISSUE THREAD

**Issue by funkydev** [hackiftekhar/IQKeyboardManager#605]
When I'm setting up text programmatically for text fields it's changing text appearance randomly. Eg. it's
* setting up non-serif, bigger text
* centering text in control

**Comment by hackiftekhar** [comment]
I don't think library is changing text appearance, looks like it is your app issue. If not then please share a demo project to demonstrate the issue.

**Comment by funkydev** [comment]
It's changing when I'm setting up text programmatically, eg. in didBeginEditing outlet method. I'll prepare application to demonstrate bug. 

I don't exclude my mistake, but I had this bug in three applications.
I hope we solve the problem.

**Comment by hackiftekhar** [comment]
Ok, tgen could you please share a demo project?

**Comment by hackiftekhar** [comment]
@funkydev Could you please share a demo?

**Comment by funkydev** [comment]
This is problem with system textfield control, not library. 
I checked it again in new demo project.

Sorry for wasted time.

**Comment by hackiftekhar** [comment]
np
