### ISSUE TITLE
Placeholder vs title

### ISSUE THREAD

**Issue by Alex293** [hackiftekhar/IQKeyboardManager#606]
Is it possible to have a different values for the bar title over the keyword and the place holder in the textview ?
I would like for example to place "email" in the title and a sample email like "test@mydomaine.com" in the content. Would be a nice feature to have.

**Comment by hackiftekhar** [comment]
It's possible, please check #529 issue.

**Comment by Alex293** [comment]
Thank for your quick answer I didn't noticed the difference between placeholderText and placeHolder !
