### ISSUE TITLE
键盘回收问题

### ISSUE THREAD

**Issue by randongjun** [hackiftekhar/IQKeyboardManager#607]
有时候键盘弹出后无法回收，好像框架会失效

**Comment by randongjun** [comment]
Sometimes can't recovery, after the keyboard pops up like framework will fail

**Comment by hackiftekhar** [comment]
Can you please provide any examples? I can't figure out whats the actual issue. Please be specific.

**Comment by randongjun** [comment]
When I use the real machine test, sometimes textField bring up the keyboard cannot be recycled, but the recovery method of keyboard I have calls

**Comment by randongjun** [comment]
//1.设置点击背景收回键盘
    [IQKeyboardManager sharedManager].shouldResignOnTouchOutside = YES;
    //2.隐藏键盘上的工具条
    //[IQKeyboardManager sharedManager].enableAutoToolbar = NO;
    [IQKeyboardManager sharedManager].enable = YES;
    [IQKeyboardManager sharedManager].shouldToolbarUsesTextFieldTintColor = YES;

**Comment by randongjun** [comment]
have probblem?

**Comment by hackiftekhar** [comment]
Not sure, please share a demo project and steps to reproduce.
