### ISSUE TITLE
When keyboard show, how to setup make scrollview scroll up, not it's subview(uicollectionview) scroll up

### ISSUE THREAD

**Issue by carya** [hackiftekhar/IQKeyboardManager#608]
I made a UICollectionView on UIScrollView，and a UITextField as UICollectionView's SectionFooterView, when the keyboard showing, I want the UIScrollView scroll up，not the UICollectionView, how could I do?

**Comment by carya** [comment]
And the UICollectionView's scrollEnabled value is NO

**Comment by hackiftekhar** [comment]
I think your UIScrollView should scroll in this case but I'm not sure about the actual caused. Can you share all this in a quick demo? I can check it when I got some time.
