### ISSUE TITLE
Xcode 8 Beta 6 compatibility

### ISSUE THREAD

**Issue by Tulleb** [hackiftekhar/IQKeyboardManager#609]
I'll submit a PR asap.

**Comment by hackiftekhar** [comment]
It's already an issue open for this #531, we are also maintaining a `swift3` for Xcode 8. If you found any compilation issue with swift3 branch then I'm ok with your PR pointing to `swift3`.

**Comment by Tulleb** [comment]
@hackiftekhar sorry for the duplicate then. I thought you would like a different issue for every Xcode beta incompatibilities (they is different issues every time obviously).

FYI: I've already submit the previous #587 PR that you merged a few days ago. I am having quite some trouble with the Beta 6 update which has a lot of changes.

I'll comment in #531 from now on.

Closed.
