### ISSUE TITLE
Why SearchBar Do not work?

### ISSUE THREAD

**Issue by ghost** [hackiftekhar/IQKeyboardManager#61]
I have a searchbar,  i find that iqkeyboardmanager do not deal mask.  but textfield is right. how can i to do ?

**Comment by galileoguzman** [comment]
If I'm ussing IQKeyboardManager with CocoaPods, exists the possibility to can rise some issue if I'll add code on pods folder?

**Comment by hackiftekhar** [comment]
If you think there is a bug then you cqn make pull-request
