### ISSUE TITLE
the "Done" button in keyboard is Invalid

### ISSUE THREAD

**Issue by zljkevin** [hackiftekhar/IQKeyboardManager#611]
"Done" button in tool bar overlaps the function of the "Done" button in keyboard, so when I kick the "Done" button in keyboard ,there's no response.

**Comment by hackiftekhar** [comment]
You have to implement textFieldShouldReturn and handle the return key yourself. Library cannot override keyboard done button due to some limitations.

**Comment by zljkevin** [comment]
I have implement textFieldShouldReturn method, but it did not work!  It's  weird.

**Comment by hackiftekhar** [comment]
You have to wring your own logic there.

**Comment by zljkevin** [comment]
I find something wrong in my code, thanks.
