### ISSUE TITLE
use MFMessageComposeViewController with IQKeyboardManager in project 

### ISSUE THREAD

**Issue by zhouzhongguang** [hackiftekhar/IQKeyboardManager#612]
When i use MFMessageComposeViewController to send message in my project, the IQKeyboardManager is in use alose, i find the animation to dismiss the MFMessageComposeViewController is weirdly.
And i remove IQKeyboardManager from my project, the animation works crrectly.

this is my code，you can 
/**
 *  调取短信发送页面
 *
 *  @param phoneNumber 号码
 */
- (void)displaySMSComposerSheetWithPhone:(NSString *)phoneNumber{
    //设备可以发送短信
    if ([MFMessageComposeViewController canSendText]) {
        MFMessageComposeViewController *messageComposeViewController = [[MFMessageComposeViewController alloc] init];
        messageComposeViewController.messageComposeDelegate = self;
        messageComposeViewController.recipients = @[phoneNumber];
        messageComposeViewController.body = @"";
    
        HIKLog(@"%ld", (long)self.navigationController.navigationBar.barStyle);
        messageComposeViewController.navigationBar.barStyle = self.navigationController.navigationBar.barStyle;
        [self presentViewController:messageComposeViewController animated:YES completion:^{
        }];
    } else {//设备不支持短信功能
        [self showTipText:@"此设备不支持短信功能"];
    }
}

#pragma mark - MFMessageComposeViewControllerDelegate

- (void)messageComposeViewController:(MFMessageComposeViewController *)controller didFinishWithResult:(MessageComposeResult)result{
    [self dismissViewControllerAnimated:YES completion:NULL];
}

**Comment by hackiftekhar** [comment]
Thanks for letting me know, I'll check it.

**Comment by zhouzhongguang** [comment]
Today i test the problem on system iOS8.4.1 also, the animation is ok. So the animation weird problem is on iOS9.3.4. 

Another problem, the device sytem version is also iOS9.3.4, when show keyboard in viewDidLoad method, the tool bar on
![screen shot 2016-08-18 at 6 17 51](https://cloud.githubusercontent.com/assets/10241716/17770506/c23f4f00-6570-11e6-814a-8cdda86abeba.png)
 the top of keyboard is black at the beginning, soon turn to ok.

code:
- (void)viewDidLoad {
    [super viewDidLoad];
    [self.textField becomeFirstResponder];
}
![screen shot 2016-08-18 at 6 17 51](https://cloud.githubusercontent.com/assets/10241716/17770516/d89fcee6-6570-11e6-9ea8-8d23228d5150.png)

**Comment by hackiftekhar** [comment]
I checked my library with MFMessageComposeViewController and MFMailComposeViewController and it all animation looks ok to me. Regarding the black bar issue can you please share demo?
