### ISSUE TITLE
Nex previous works incorrectly when there is textfield in tablesection

### ISSUE THREAD

**Issue by mihirpmehta** [hackiftekhar/IQKeyboardManager#617]
I have multiple UITextField in UITableViewCell as Well as textfields in Table Section Header. 

When last text field of last row is become first responder 

1> Next button is shown as enabled 
2> pressing next goes to first textfield of first section header. 

Any idea on quick fix ?

**Comment by mihirpmehta** [comment]
Here is the demo project for the same. 

Click on the last textfield of the UItableViewCell (kr placeholder) and click next.

**Comment by hackiftekhar** [comment]
Thanks for the demo, I'll check

**Comment by mihirpmehta** [comment]
Is there any chance i will get this in pod ? so that i can update my pod

**Comment by hackiftekhar** [comment]
I just updated Obj-C version v4.0.5 about an hour ago. I'm updating swift version.

**Comment by mihirpmehta** [comment]
Super cool, you're unbelievably fast ... :)

**Comment by hackiftekhar** [comment]
Actually I was planning to update CocoaPods from couple of days, so today I updated it with this fix.

**Comment by mihirpmehta** [comment]
Thanks man, I updated the code and it works like a charm.  👍
