### ISSUE TITLE
PayPal-iOS-SDK with IQKeyboardManager ~> 4.0.5 crash under iOS 9 only

### ISSUE THREAD

**Issue by pcicp** [hackiftekhar/IQKeyboardManager#618]
hi guys

i use PayPal-iOS-SDK. it's PayPalPaymentViewController will present a internal PPAuthViewController if user isn't remembered. 

PPAuthViewController is a view controller with login/password input and will trigger 'becomeFirstResponder' (in my option), then project will crash. Here app no response, console no log, in debug session will see cpu about 99%, memory continuously increase.

this bug only appear under iOS 9. iOS 8 and iOS 10 are ok.  and i tested IQKeyboardManager 4.0.4 is full ok.

also i try to use 'disabledToolbarClasses' to disable IQKeyboardManager in PPAuthViewController. it failed.

regards

**Comment by hackiftekhar** [comment]
Ok, please provide a demo and I'll check

**Comment by pcicp** [comment]
i update the demo, please check
[Demo.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/440959/Demo.zip)

**Comment by hackiftekhar** [comment]
Thanks :)

**Comment by pcicp** [comment]
@hackiftekhar i tested again PayPal-iOS-SDK (2.15.1) + IQKeyboardManager (4.0.6). it seems bug only under ios9, ios8 and ios10 are ok.

**Comment by hackiftekhar** [comment]
hmm, thanks for the more info @pcicp btw I was having some issues with presenting PayPal SDK that's why I couldn't get much time to fix it and check the demo.

**Comment by hackiftekhar** [comment]
Not sure what is the actual issue but writing this

> IQKeyboardManager *manager = [IQKeyboardManager sharedManager];
> [manager.disabledToolbarClasses addObject:NSClassFromString(@"PPAuthViewController")];
> [manager.disabledDistanceHandlingClasses addObject:NSClassFromString(@"PPAuthViewController")];

Solve my issue.

**Comment by hackiftekhar** [comment]
@pcicp I can't understand why it doesn't work with 4.0.5 and 4.0.6 (iOS 8 and 9) but it does work correctly with 4.0.7 (iOS9 and iOS10 I checked).
