### ISSUE TITLE
How to hide lable of field showing on keyboard layout ?

### ISSUE THREAD

**Issue by kaviyarasu7** [hackiftekhar/IQKeyboardManager#619]
Pls find the attached image
![image1](https://cloud.githubusercontent.com/assets/5144291/18089715/efade07e-6ede-11e6-8c55-457b5aac00de.PNG)

**Comment by hackiftekhar** [comment]
If you would like to hide for all, then set shouldShowTextFieldPlaceholder=YES of IQKeyboardManager property. If you would like to hide it for just this textField then set shouldHidePlaceholderText=YES (IQUIView+IQKeyboardToolbar.h) of textField.

**Comment by kaviyarasu7** [comment]
Thanks for the quick response

**Comment by PrithiviMelio** [comment]
I need to stop all fields of the app.

Which i need to modify IQUIView+IQKeyboardToolbar.h or IQUIView+IQKeyboardToolbar.m

**Comment by PrithiviMelio** [comment]
How to avoid IQKeyboardManager for particular view

**Comment by hackiftekhar** [comment]
You cannot remove it from a particular ViewController but you can remove it from a view controller, please read Manual Management guidelines.
