### ISSUE TITLE
No keyboard show on iOS 8

### ISSUE THREAD

**Issue by hugo53** [hackiftekhar/IQKeyboardManager#62]
Hi,

I've tried with iOS 8 and see that no keyboard showing. Please check the attached image for more details.

Hope it will be fixed soon.

Cheers,
Hugo

![ios simulator screen shot aug 21 2014 15 01 52](https://cloud.githubusercontent.com/assets/1033299/3993220/780dba0c-2909-11e4-8b6f-75808905d4e7.png)

**Comment by Heisenbean** [comment]
这样啊,我也是连接了电脑键盘才导致这样了...
谢谢解答
A Coder From China:)
