### ISSUE TITLE
Force Auto Toolbar to reload Textfields

### ISSUE THREAD

**Issue by xiaodoudou** [hackiftekhar/IQKeyboardManager#621]
Hi,

I am facing an issue on my current project.
I am using a UITableView, when the field ends the edit, we have to reload the data of the table as some field are under some conditions to be displayed or not...

The conditions are trigger by a UIPickerView when it matchs specifics values.
By doing such things, (reloadData the UITableView) the current fields inside the toolbar doesn't exist anymore, so clicking the next arrow button of the bar will throw that the next textfield did refuse to become first responder (yeah, he is gone so that is normal).

So I am wondering if the following things:
- is there a way to force the toolbar to refresh its textfield list?
- is there a way to close the toolbar inside the textFieldDidEndEditing method?

PS: My current work around is to leave the toolbar for the purpose of the done button, but to hide the previous and next arrows.

Thank you for your help,

**Comment by hackiftekhar** [comment]
You can use the IQUIView toolbar category in library to add your own toolbar and can add your own selector. This way all the controls will goes to you.
