### ISSUE TITLE
UITextField in UINavigationBar's titleView with UITableView content

### ISSUE THREAD

**Issue by TadeasKriz** [hackiftekhar/IQKeyboardManager#622]
I can't seem to get working this scenario. I have a `UITextField` as a `titleView` for searching. The content of the controller pushed into the `UINavigationController` is a `UITableView` with results. The problem is, that when I click on the text field and keyboard opens, the `UITableView` still shows content behind the keyboard. I tried the `IQLayoutGuideConstraint`, but it does not work because the `UITextField` is considered to be a child of the `UINavigationController` and not the pushed one. Any ideas? Thanks.

**Comment by hackiftekhar** [comment]
This is because your textField isn't inside UITableView so the library think that all is going good. It's a user special case which cannot be handled by library, you must move your tableView contentInset or it's frame in order to fix UITableView scrolling issue.
