### ISSUE TITLE
Automatic scroll suddenly not working.

### ISSUE THREAD

**Issue by Rashesh-Bosamiya** [hackiftekhar/IQKeyboardManager#623]
I have tableView containing lots of textboxes, IQKeyboardManager was handling the auto scroll of tableView.

But now suddenly auto scrolling doesn't working.

what should I do?

**Comment by hackiftekhar** [comment]
You mean it was working before and suddenly stopped working?

**Comment by Rashesh-Bosamiya** [comment]
Yes

**Comment by Rashesh-Bosamiya** [comment]
Maybe, I've upgraded the  version

**Comment by hackiftekhar** [comment]
May be, probably you could debug to know the reason why it qas working before and stopped working now.

**Comment by Rashesh-Bosamiya** [comment]
Where I do debug? In which file?

Even, I have refreshed the pod file and installed `pod 'IQKeyboardManagerSwift', '4.0.0'` version.
But scroll still not working.

**Comment by Rashesh-Bosamiya** [comment]
I just found that scrolling working in `UIViewController` but not working in `UITableViewController`

**Comment by hackiftekhar** [comment]
Ahh, then you probably not calling [super viewWillAppear:animated];, there are some other closed issue you can find related to UITableViewController

**Comment by Rashesh-Bosamiya** [comment]
Ok Thanks

**Comment by nileshpol18** [comment]
Same issue happening with me. It was working fine until I updated pods yesterday and suddenly none of the TableView's textfields are moving up. Fields are getting hidden behind keyboard.

Unable to understand where to debug? Please help @hackiftekhar
