### ISSUE TITLE
UITextField subviews does not listed in -deepResponderViews

### ISSUE THREAD

**Issue by VladKorzun** [hackiftekhar/IQKeyboardManager#625]
In case when UITextField contain responder subviews they won't be listed by -deepResponderViews method. Proposition: remove 'else' from condition inside for loop than if textfield will have respondable subviews they will be included to final deep responder views array. Attaching corrected code below.
`- (NSArray*)deepResponderViews
{
    NSMutableArray *textFields = [[NSMutableArray alloc] init];
    
    for (UIView *textField in self.subviews)
    {
        if ([textField _IQcanBecomeFirstResponder])
        {
            [textFields addObject:textField];
        }
        //Sometimes there are hidden or disabled views and textField inside them still recorded, so we added some more validations here (Bug ID: #458)
        if (textField.subviews.count && [textField isUserInteractionEnabled] && ![textField isHidden] && [textField alpha]!=0.0)
        {
            [textFields addObjectsFromArray:[textField deepResponderViews]];
        }
    }`

**Comment by hackiftekhar** [comment]
Generally textField or textView doesn't contain a view which can become first responder. Could you please let me k ow your user case?

**Comment by VladKorzun** [comment]
In my particular case textField's left and right views can become first responder and I would like to see them in deepResponderViews hierarchy.

**Comment by hackiftekhar** [comment]
Then you could trying using IQPreviousNextView example, it may help you a lot.

**Comment by VladKorzun** [comment]
All my textFields are already embedded in IQPreviousNextView. Wrapping this particular textField in another one IQPreviousNextView does not help, it just breaks previous/next logic so when you reach this textField you cant go "<" or ">"

**Comment by hackiftekhar** [comment]
All textField should be inside same IQPreviousNextView. You are putting all textField inside different IQPreviousNextView.

**Comment by VladKorzun** [comment]
In my original case I have IQPreviousNextView with several UITextFields inside and one of this TextFields has left and right views that can became first responder too. So when 'deepResponderViews' method reaches this if statement:

```
if ([textField _IQcanBecomeFirstResponder])
{
      [textFields addObject:textField];
}
        //Sometimes there are hidden or disabled views and textField inside them still recorded, so we added some more validations here (Bug ID: #458)
        else if (textField.subviews.count && [textField isUserInteractionEnabled] && ![textField isHidden] && [textField alpha]!=0.0)
        {
            [textFields addObjectsFromArray:[textField deepResponderViews]];
        }

```

it finds that textField can become first responder but because of 'if -> else if' statement it can't go further to check if textField's subviews also can become first responders too. That's why I offer to remove the 'else' to let this method search deeply even if the superview can become first responder.

The code I've provided in first message handles this situation just fine.

**Comment by look1n** [comment]
Upvoting on this, i believe that library can expanded to enlist all views that can become first responders. We have a control that can become first responder and placed as right view of UITextField, when it becomes first responder it show UIPicker to select values and that resigns first responder, so i think it will be reasonable to include left and right views to -deepResponderViews

**Comment by look1n** [comment]
We can create pull request if you wish ;)

**Comment by hackiftekhar** [comment]
@look1n okay, I think we can include this support, but I should have to check some more scenarios so it would be better if I do change from my own and it would take some time. :)

**Comment by look1n** [comment]
Great, thank you!

**Comment by maqoo** [comment]
Well this is broken now in iOS 13 because UITextField has UIFieldEditor instance as a subview which cannot become first responder. I think there needs to be another mechanism to nest first reponders in UITextField (or others) and this else shoould be brought back to how it was.
