### ISSUE TITLE
Swift 3 for Xcode 8 GM support!

### ISSUE THREAD

**Issue by IsmailHassanein** [hackiftekhar/IQKeyboardManager#629]

**Comment by X901** [comment]
I have same problem i hope IQKeyboardManagerSwift support Swift 3 soon

**Comment by erusso1** [comment]
Same! The migration assistant isn't as smooth as I had hoped to be.

**Comment by kevinnguy** [comment]
https://github.com/hackiftekhar/IQKeyboardManager/issues/531
