### ISSUE TITLE
  “Use Legacy Swift Language Version” with  pod 'IQKeyboardManagerSwift' on XCode 8

### ISSUE THREAD

**Issue by anilios** [hackiftekhar/IQKeyboardManager#631]
I have to convert my project from XCode 7 to 8. I have following in my pod file: pod 'IQKeyboardManagerSwift'

And i get this error on compilation.

“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

How to fix this.

**Comment by xuanzi23** [comment]
me too having this problem also

**Comment by ReFiRnE** [comment]
` post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
  end`
put this at the end of your pod file if you use cocoa pods
