### ISSUE TITLE
Error Ambiguous use of 'textView(:shouldInteractWith:in:)'

### ISSUE THREAD

**Issue by MathisDetourbet** [hackiftekhar/IQKeyboardManager#632]
Hi,

I've just installed Swift 3 and Xcode 8. I updated IQKeyboardManager (v 4.0.5) and i have this following error :
![capture d ecran 2016-09-14 a 18 07 01](https://cloud.githubusercontent.com/assets/5748462/18519947/11ac5778-7aa6-11e6-819b-d448b320f6d6.png)

Thanks for your help !

**Comment by hackiftekhar** [comment]
Swift 3  ersiin will be release soon via CocoaPods.
