### ISSUE TITLE
Xcode8 + Carthage + IQKeyboardManager v4.0.5

### ISSUE THREAD

**Issue by OmarCaf** [hackiftekhar/IQKeyboardManager#633]
Carthage Build fail, the log is below:

The following build commands failed:
	Check dependencies
(1 failure)
A shell task (/usr/bin/xcrun xcodebuild -project /Users/omarcafini/Documents/Code/xxx-user/Carthage/Checkouts/IQKeyboardManager/IQKeyboardManager.xcodeproj -scheme IQKeyboardManagerSwift -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** CLEAN FAILED **

**Comment by RomanVolkov** [comment]
I opened IQKeyboardManager manually and updated swift version and target (XCode ask you about it, plus, check swift version).
Then make carthage build --platform ios (not update). 

As temporary solution - fine.
