### ISSUE TITLE
IQKeyboard Manager - v(4.0.5)

### ISSUE THREAD

**Issue by tlandsmancars** [hackiftekhar/IQKeyboardManager#635]
I upgraded to XCode 8 and updated my pods using Cocoapods.
I got 443 build errors for IQKeyboardManager
<img width="376" alt="screen shot 2016-09-14 at 9 35 38 pm" src="https://cloud.githubusercontent.com/assets/17576176/18536507/6fd9e2bc-7ac3-11e6-8ac7-1a11748f3396.png">

**Comment by anilios** [comment]
Same issue here.

**Comment by siryu8888** [comment]
same issue.. please help anyone?

**Comment by tristandarwent** [comment]
I'm having the same issue. Comparing the branches, it doesn't seem to be updating the file through pods correctly.

**Comment by parasdaff** [comment]
Same issues....Please do some help.

**Comment by bdrelling** [comment]
Same issues... This is pretty crazy.

**Comment by hackiftekhar** [comment]
Wait some minutes, I'm releasing Xcode8 compatible version soon.

**Comment by bdrelling** [comment]
How long does this take to propagate for CocoaPods properly? I have to manually do the following for it to work right now:

`pod 'IQKeyboardManagerSwift', :git => 'https://github.com/hackiftekhar/IQKeyboardManager.git', :tag => 'v4.0.6'`

**Comment by hackiftekhar** [comment]
Just pushed

**Comment by siryu8888** [comment]
Thx..
