### ISSUE TITLE
IQKeyboardManger in swift3

### ISSUE THREAD

**Issue by jeroen-develop** [hackiftekhar/IQKeyboardManager#636]
When enabling the manager the black toolbar appears, but the view doesn't move up.
The source files are imported in the project.

unfortunately no errors are thrown to debug the issue.

**Comment by singhmanpreet1** [comment]
Same for me. Its not working in Swift 3.0 and iOS 10.0

**Comment by OmarCaf** [comment]
Idem, yesterday in the branch "swift3" it worked
