### ISSUE TITLE
Textfield and textview under keyboard when return back to controller

### ISSUE THREAD

**Issue by Raghvendra7** [hackiftekhar/IQKeyboardManager#637]
Hi
Actually i m using ur library.I have screen in which there are multiple textfield and textview in scrollview,Library working fine (field move above keyboard) but in a case from one textfield i have to move to new controller,when i pop back to previous screen and tap on email textfield in move behind the keyboard,i m attaching screenshot for the same
![img_0151](https://cloud.githubusercontent.com/assets/10459999/18548454/665a6524-7b66-11e6-8b7c-670af59d034f.PNG)
I dont understand how to resolve the issue,also i m facing same issue for the textview below the email textfield.Since the issue arises only when i pop back to the screen and works fine when it first time load,Any suggestion

**Comment by hackiftekhar** [comment]
Hmm, you could try endEditing at your viewWillDisappear. Let me know if this solve your problem otherwise please share demo and I'll check.

**Comment by Raghvendra7** [comment]
@hackiftekhar i have already done that but problem not solved i dont understand why the problem is for only bottom email textfield and detail textview as all other working fine

**Comment by hackiftekhar** [comment]
Then you need to share a demo @Raghvendra7 and I'll check.

**Comment by hackiftekhar** [comment]
@Raghvendra7 Can you share a demo?

**Comment by hackiftekhar** [comment]
@Raghvendra7 If you do not share a demo with me then how can I check the scenario and understand your user case? Unfortunately I don't have much time to reproduce the demo so that's why I'm asking from you.
