### ISSUE TITLE
Is there a Swift 2.3 version compatible ?

### ISSUE THREAD

**Issue by yangzhixiao** [hackiftekhar/IQKeyboardManager#638]
RT

**Comment by parasdaff** [comment]
is it compatible with swift 2.3?

**Comment by yangzhixiao** [comment]
and which version what i should pod use cocospod ?
4.0.5?

**Comment by hackiftekhar** [comment]
There is no official supported
version for swift2.3 of IQKeyboardManager,

**Comment by EstebanVallejo** [comment]
Version 4.0.5 already supports Swift 2.3

**Comment by hackiftekhar** [comment]
4.0.5 was built over Xcode7.3 and In my knowledge Xcode7.3 support Swift2.2.1. Correct me if I'm wrong.

**Comment by EstebanVallejo** [comment]
@hackiftekhar - Yes, you are right, but v4.0.5 compiles without problem in Xcode 8 and Swift 2.3 (setting the "Use Legacy Swift Language Version" to YES in pod's build target) even thought it was built using Xcode 7.3 with Swift 2.2.1 ...

That's why I say that v4.0.5 already supports Swift 2.3

**Comment by hackiftekhar** [comment]
That's great @EstebanVallejo then I can assume swift2.3 has very less syntax changes as compared to swift2.3 and doesn't affect our library.

**Comment by ltlombardi** [comment]
To my knowledge Swift2.3 has no syntax change, but some of the objects returned by apple core APIs are Optionals in 2.3, so you'll have to add some exclamation marks....

I would recommend changing the version of the Swif3 release... and stating clearly what version supports 2.3 and what has to be done.

**Comment by zhigang1992** [comment]
Here is a fork if you just want to grab it.

```
github "HackPlan/IQKeyboardManager" "swift23"
```

It basically branched off `v4.0.5` and update those flags to make it work with swift2.3.

**Comment by mayckxavier** [comment]
@zhigang1992, how could I install this swift23 version?

**Comment by zhigang1992** [comment]
@mayckxavier I'm guessing you're using cocoapods?

```ruby
  pod 'IQKeyboardManager', :git => 'https://github.com/HackPlan/IQKeyboardManager', :branch => 'swift23'
```

**Comment by mayckxavier** [comment]
Thanks, @zhigang1992!
I was so inside my project that  didn't thank you.
