### ISSUE TITLE
How to prevent auto-hide of keyboard if there are textfield errors

### ISSUE THREAD

**Issue by snydersaurus** [hackiftekhar/IQKeyboardManager#639]
I would like to prevent the hiding of the keyboard on 'Done' if there is a problem with the text entry (e.g. an invalid email address). 

I cannot find a way to override this (unfortunately 'textFieldShouldReturn' doesnt work).

Has anyone figured this out?

**Comment by hackiftekhar** [comment]
You could either remove toolbar for that field kr add your own toolbar, so that you'll have full control over there.

**Comment by hackiftekhar** [comment]
Yoh could probably wrote some logics in textFieldShouldEndEditing too.

**Comment by snydersaurus** [comment]
Ah yes, handling textFieldShouldEndEditing is a good strategy. Thanks.
