### ISSUE TITLE
UItextView Handling Issue

### ISSUE THREAD

**Issue by Rahulgupta-cdnsol** [hackiftekhar/IQKeyboardManager#640]
HI,

I have taken UItextview and when I click on that IQkeyboardmanager nothing handles.

Can you please let me know what need to do so it works for UItextview.

Thanks

**Comment by hackiftekhar** [comment]
Could you please send more info? what isn't handled?

**Comment by hackiftekhar** [comment]
@Rahulgupta-cdnsol Could you please send more info?
