### ISSUE TITLE
IQKeyboardManger in swift3

### ISSUE THREAD

**Issue by jeroen-develop** [hackiftekhar/IQKeyboardManager#641]
Using the latest version (4.0.6) in swift 3,xcode 8, the view does not move for hidden textFields.

Tried a new project with a bunch of textFields, imported the source files but still no luck.

enabled the manager like this:

`  func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        // Override point for customization after application launch.
        IQKeyboardManager.sharedManager().enable = true
        return true
    }`

**Comment by hackiftekhar** [comment]
Could you please share demo app?

**Comment by jeroen-develop** [comment]
Recreated the project from scratch.
The previous project I tried to use the pods, then I used the source files.

The new project I only imported the source files and by miracle everything works like it's supposed to work.

**Comment by hackiftekhar** [comment]
Tgat's great!
