### ISSUE TITLE
Toolbar cursor buttons not updated when changing enabled

### ISSUE THREAD

**Issue by ujikol** [hackiftekhar/IQKeyboardManager#642]
I dynamically set enabled for next text field in editing changed callback. This works fine. But the cursor button in the toolbar of the keyboard are not updated.

To give an example:
At the begin only the email field is enabled. When the user starts to edit it the keyboard shows the cursor keys grayed out. Once the contents of the text field looks like a valid email address the password field is enabled. The user could immediately tap there. But the cursor buttons are still disabled. Expected behavior: The down button becoming enabled while still editing the email field.

**Comment by hackiftekhar** [comment]
there is a method in IQKeyboardManager to reload inputView, you should call that method at appropriate time to reload toolbar button state.

**Comment by ujikol** [comment]
Thanks. That works if there are more than 1 text fields enabled when editing starts.

In case of a single enabled text field no curser are show (instead of disabled ones), and reloadInputView don't show them even when another text field became enabled.

**Comment by hackiftekhar** [comment]
Hmm, that I can check for single ehabled textField.

**Comment by ujikol** [comment]
any news?

**Comment by hackiftekhar** [comment]
Not yet @ujikol I didn't get free time to check this.
