### ISSUE TITLE
becomeFirstResponder Does Not Trigger IQKeyboardManager

### ISSUE THREAD

**Issue by vbresults** [hackiftekhar/IQKeyboardManager#644]
When you call becomeFirstResponder on a TextField programmatically, instead of in response to a tap event, this plugin is not triggered and the default behavior occurs where the field is covered.

Is there a specific way this should be done programmatically?

**Comment by vbresults** [comment]
ping @hackiftekhar

**Comment by hackiftekhar** [comment]
@vbresults I don't think that this should happen, but will check this.

**Comment by vbresults** [comment]
This was an issue with my layout's constraints somewhere; it seems to only show the bug when the field focus is invoked programmatically, not in response to an actual tap.

Anyway, not an issue, thank you @hackiftekhar for helping me pin this down (:

**Comment by danielhauagge** [comment]
I'm running into a similar issue here. I'm not sure what @vbresults means when he says that his bug was related to a layout constraint. Is there some specific manner in which auto layout should be setup?

**Comment by vbresults** [comment]
@danielhauagge I never resolved the issue of it not invoking programmatically, so I've had to resort to only responding to taps

**Comment by cameronwebbable** [comment]
For me, I tried wrapping "becomeFirstResponder" in gcd call and things started working as expected. Yippie! 

Example: 
```swift           
DispatchQueue.global(qos: .userInitiated).async {
    DispatchQueue.main.async {
        textField.becomeFirstResponder()
    }
 }
```

I know this issue is a few months old & is closed, but in the event someone else comes here looking for things to try, wanted to share 😄 .

**Comment by hackiftekhar** [comment]
Thanks for sharing @cameronwebbable that definitely help the community.

**Comment by GavinRoman** [comment]
Thanks @cameronwebbable , but it doesn't work if it has UITextView.

**Comment by erayalparslan** [comment]
> For me, I tried wrapping "becomeFirstResponder" in gcd call and things started working as expected. Yippie!
> 
> Example:
> 
> ```swift
> DispatchQueue.global(qos: .userInitiated).async {
>     DispatchQueue.main.async {
>         textField.becomeFirstResponder()
>     }
>  }
> ```
> 
> I know this issue is a few months old & is closed, but in the event someone else comes here looking for things to try, wanted to share 😄 .

You saved my day
