### ISSUE TITLE
How can  i hide  top toolbar of the keyboard

### ISSUE THREAD

**Issue by Sunxb** [hackiftekhar/IQKeyboardManager#645]
thanks

**Comment by hackiftekhar** [comment]
If you want to hide it for only one textField then it is explained here https://github.com/hackiftekhar/IQKeyboardManager/blob/master/MANUAL%20MANAGEMENT.md in **Hide UIToolbar for specific UITextField/UITextView** section. If you want to hide it for all textField then there is a property something like `enableAutoToolbar` and you can set it to NO.

**Comment by Sunxb** [comment]
@hackiftekhar Thank you!
