### ISSUE TITLE
Does Not Adjust for Form Sheet

### ISSUE THREAD

**Issue by Treverr** [hackiftekhar/IQKeyboardManager#646]
Is this supposed to help adjust with form sheets?

I have a UITableViewController inside a UINavigationController which is presented in a Form Sheet and it doesn't adjust anything like I thought it would.

Is there anything i need to do?

**Comment by hackiftekhar** [comment]
Library also handle FormSheet case but if you are using UITableViewController then it has own logic for moving tableView to show content. So library ignore moving anything and respect UITableViewController default behaviour. For more please see **Note:** at **Moving Content That Is Located Under the Keyboard** section https://developer.apple.com/library/content/documentation/StringsTextFonts/Conceptual/TextAndWebiPhoneOS/KeyboardManagement/KeyboardManagement.html
