### ISSUE TITLE
Swift3 Please Use @discardableResult in some methods

### ISSUE THREAD

**Issue by hardikdevios** [hackiftekhar/IQKeyboardManager#647]
**For example** 

```
 IQKeyboardManager.sharedManager().goPrevious()
 IQKeyboardManager.sharedManager().goNext()
 IQKeyboardManager.sharedManager().resignFirstResponder()
```

So it gives warning result of this function result is not used, but it also not required to use so i Hope you should put `@discardableResult`

**e.g**

```
@discardableResult
 public func goPrevious()-> Bool {
        
}
```

This is how we don't have to write something like this everytime
`let _ = IQKeyboardManager.sharedManager().goNext() 👎 
`

**Comment by hackiftekhar** [comment]
That's great :) Can you make a pull request with these changes?
