### ISSUE TITLE
Doesn't return to start position when using TextView

### ISSUE THREAD

**Issue by dizialina** [hackiftekhar/IQKeyboardManager#649]
I'm using 4.0.6 version with Swift 3. IQKeyboardManager works fine with TextField. But when i try to enter text in TextView my keyboard appears and view going up - all is fine, but when my keyboard hide - my view do not return to start position (look screenshot). How can I fix it?
![alt tag](http://i66.tinypic.com/2rd7ms1.png)

**Comment by hackiftekhar** [comment]
@dizialina can you please share a demo project?

**Comment by hackiftekhar** [comment]
@dizialina Any updates on demo?
