### ISSUE TITLE
changing font doesn't reflect on input for 3rd party app

### ISSUE THREAD

**Issue by rahthakor** [hackiftekhar/IQKeyboardManager#651]
Hi,

I have tried to use keyboard as extension with Raleway Font(Google) but I'm not able to see displaying Raleway font on input control. It uses same system font.

Is it possible to do so to change font of textfield or textarea of any 3rd Party app.

Thanks in advance

Regards,
rAhul

**Comment by hackiftekhar** [comment]
Not sure what you exactly asking. Please elaborate.

**Comment by rahthakor** [comment]
I have created keyboard extension with reference to this repo.

What I have changed is system font to Raleway Font(Google)  which are displayed on keyboard buttons without any problem. But When I press any button on keyboard that particular button title is display or textfield or wherever I'm typing but with system font not with font which I'm using in my keyboard title.

As you might know insertText method takes only string without any attributes so I can not tell system to render it in Raleway font. This scenario happens only when I'm using keyboard as extension not within host containing app.

I want o achieve something like this
![fancy keyboard screenshot](https://cloud.githubusercontent.com/assets/8470553/18707239/c48a1ad0-8012-11e6-9a3b-fdfa283190fc.png)

**Comment by hackiftekhar** [comment]
Looks like this question isn't related to library. Are you sure that it's related to IQKeyboardManager?

**Comment by rahthakor** [comment]
@hackiftekhar Yeah actually I show your code more deeply than I found out that what I was looking for might be not available in your repo. 
You have used your toolbar on top of system keyboard. I basically you haven't created an extension which I guessing.

Any which ways thank you.
you can close this issue.
