### ISSUE TITLE
about the datasource

### ISSUE THREAD

**Issue by Vicktor0616** [hackiftekhar/IQKeyboardManager#652]
hi,when i use a switch that can change the datasource,i mean that maybe the next tf is hidded,then the IQ 's nextbutton won't work...

**Comment by hackiftekhar** [comment]
Please elaborate. I didn't understand it properly.

**Comment by Vicktor0616** [comment]
![qq20160926-0](https://cloud.githubusercontent.com/assets/15155110/18820573/628ff850-83d1-11e6-9dfb-9dbc5f565329.png)
![qq20160926-1](https://cloud.githubusercontent.com/assets/15155110/18820576/6a32d46a-83d1-11e6-9c77-10a5e896ec9d.png)
![qq20160926-2](https://cloud.githubusercontent.com/assets/15155110/18820578/6ccabbc0-83d1-11e6-9f55-7a79237194e1.png)
In the picture two,i changed the switch's state,and then there's one cell was removed,then in the picture 3,I pressed the nextbutton, it didn't work~

**Comment by Vicktor0616** [comment]
![qq20160926-3](https://cloud.githubusercontent.com/assets/15155110/18830152/1117e352-8412-11e6-944d-ce14dec81055.png)

**Comment by Vicktor0616** [comment]
i fond the similar bug in #434,but i have to use it in iOS 7.0~~~ how can i do

**Comment by hackiftekhar** [comment]
I think you are probably looking for `reloadInputViews` methods of `IQKeyboardManager`.
