### ISSUE TITLE
How to disable the IQKeyboardManager in somewhere

### ISSUE THREAD

**Issue by sec7et** [hackiftekhar/IQKeyboardManager#656]
I used this way to disable the IQKeyboardManager, but it doesn’t work:
- (void)viewDidAppear:(BOOL)animated {
    [super viewDidAppear:animated];
    
    [IQKeyboardManager sharedManager].enable = NO;
}

And I also try to use another method, it doesn't work, too:
[[[IQKeyboardManager sharedManager] disabledDistanceHandlingClasses] addObject:[XXXX class]];

How can I disable the IQKeyboardManager when I enter the special ViewController ？

**Comment by zxshang** [comment]
I found the same problem. it's not working what ever enable is YES or NO...  I just want some page use IQKeyboardManager and other handle myself. sign...

**Comment by hackiftekhar** [comment]
@sec7et are you asking about disabling toolbar too?

**Comment by angelmic** [comment]
I have same issue in UITableViewController.
