### ISSUE TITLE
Next and previous button not appear in react-native project

### ISSUE THREAD

**Issue by JuoCode** [hackiftekhar/IQKeyboardManager#658]
Is there any implement of IQPreviousNextView for react-native?

**Comment by hackiftekhar** [comment]
Yup, you can add your own view class to toolbarPreviousNextAllowedClasses NSet to work same like as IQPreviousNextView.

**Comment by JuoCode** [comment]
Thanks for your reply, i will try later.

**Comment by JuoCode** [comment]
```
[[IQKeyboardManager sharedManager].toolbarPreviousNextAllowedClasses addObject:[RCTView class]];
```

It not work, which view should i add to toolbarPreviousNextAllowedClasses?

**Comment by hackiftekhar** [comment]
This should be the top view of all, means next/prev will show for all inner textFields inside this view. For example

RCTView
-UIView
--UITextField
--UITextField
-UIView
--UITextField
-UITextField
-UITextField

So with this, next/previous will show for all 5 textFields to navigate between them.

**Comment by douglasjunior** [comment]
[My library](https://github.com/douglasjunior/react-native-keyboard-manager/) implements IQKeyboardManager to react-native, just use:

```javascript
KeyboardManager.setToolbarPreviousNextButtonEnable(true);
```
