### ISSUE TITLE
Touch outside of the keyboard , the keyboard did not hide

### ISSUE THREAD

**Issue by sabertoothPaste** [hackiftekhar/IQKeyboardManager#659]
I build a headerView with some TextFields for UITableViewController through StoryBoard as a extern view, and return it in the "
- tableView:viewForHeaderInSection:" function. But the keyboard didn't hide when I touch outside of the keyboard. I already set shouldResignOnTouchOutside = YES.

**Comment by sabertoothPaste** [comment]
<img width="439" alt="2016-09-27 4 56 26" src="https://cloud.githubusercontent.com/assets/13805289/18866622/6437d0f8-84d3-11e6-8efd-dadf1f3afa49.png">

**Comment by hackiftekhar** [comment]
@sabertoothPaste Please share an example project.

**Comment by tatimagdalena** [comment]
I'm having this issue as well.

In my case, I'm using a UITableViewController with static table view and one of it's cells has a UITextField, all in storyboard.

In my code, on viewDidLoad, I do as following:
`IQKeyboardManager.sharedManager().enableAutoToolbar = true`
`IQKeyboardManager.sharedManager().shouldResignOnTouchOutside = true`
`IQKeyboardManager.sharedManager().shouldShowTextFieldPlaceholder = false`
`IQKeyboardManager.sharedManager().toolbarDoneBarButtonItemText = "Pronto"`

Everything works fine, except for the `shouldResignOnTouchOutside`.

**Comment by hackiftekhar** [comment]
@tatimagdalena I tried to reproduce this in my demo by adding header view, but it works perfectly, touching outside does resign the responder. Make sure you are not touching a UIControl subclass (UITextField, UISwitch, UIButton, UISegmentControl etc) and UINavigationBar. Those both kind of classes is explicitly disabled in favor of responding to their own touch behaviour.

**Comment by ajjumehra** [comment]
Want to hide keyboard on a touch of button

**Comment by Mahmoud-Abdelwahab** [comment]
IQKeyboardManager.sharedManager().shouldResignOnTouchOutside = true 
this works for me i have a tableview and search bar above it 
- another solution you can add a view above the table view when you open the keyboard and apply touch gesture on it when user click on it you can dismiss the keyboard view.endEditing(true)
