### ISSUE TITLE
Content insets are wrong

### ISSUE THREAD

**Issue by damirstuhec** [hackiftekhar/IQKeyboardManager#660]
We have a `UIViewController` with `UITableView` and a `UIButton` at the bottom.
`UITableView` is constrained to the bottom layout guide with `52` constant, which equals to the height of the button at the bottom.

In the table view, we have quite a few cells with `UITextField`s and when we give focus to the last `UITextField` the table view insets are wrong.

We are moving the bottom button up along with the keyboard, and to take the button height into the account we are adding an extra `52` to the `keyboardDistanceFromTextField`.

The result is that the bottom button covers the text field when in focus.

We debugged this quite a lot and there seems to be an issue here: https://github.com/hackiftekhar/IQKeyboardManager/blob/master/IQKeyboardManagerSwift/IQKeyboardManager.swift#L1101

I have attached the sample project so that you can try it out for yourself. The hot-fix around this is to add a `52` high footer to the `UITableView` and change its bottom constraint constant to 0 instead. So basically, instead of having a constraint constant compensate for the bottom button height, we are doing that by adding the table footer view with the same height.

[IQKMTest.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/498149/IQKMTest.zip)

cc @hackiftekhar

**Comment by hackiftekhar** [comment]
Thank You for the explanation, I'll definitely take a look at this issue.

**Comment by hackiftekhar** [comment]
hmm, @damirstuhec I checked this and library is doing correct, technically library doesn't know that there is a button which is hiding the textField. So I think your tableFooterView workaround is the best thing for now to overcome with this situation.
