### ISSUE TITLE
Not Working With UITextView in ios 9 and as well as 10

### ISSUE THREAD

**Issue by Premal-Khetani** [hackiftekhar/IQKeyboardManager#662]
Hello, I am using it with HPGrowingTextView. In ios 8 it was working but don't know whats happning it's not working in ios 9 and ios 10.  when keyboard appears the textview doesn't go up from the bottom and stick to bottom of view only. although the tool bar is showing but the textview is hidden behind the keyboard. please help me asap as i am using it in live project. 
Thank you.

**Comment by hackiftekhar** [comment]
I think it's your responsibility to check @Premal-Khetani for the issue if it's something related to your project, if you find something related to IQKeyboardManager then it's my responsibility to check, I can help you for sure!
