### ISSUE TITLE
Textfield hiding behind the keyboard in Popover ViewController

### ISSUE THREAD

**Issue by irshadqureshi** [hackiftekhar/IQKeyboardManager#663]
I had added multiple TextField in the popover and while calling a popover the library is not working properly for the top most TextField and for the bottom most TextField when the screen orientation is landscape but it works fine with portrait orientation, Please have a look at the example project I am adding and let me know if there is a solution for it.

FYI: This is an iPad Project and I am facing issue in the Landscape Orientation.
[PopupTextFieldExample.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/508258/PopupTextFieldExample.zip)

Thanks

**Comment by hackiftekhar** [comment]
Thanks for the adding demo project @irshadqureshi

**Comment by jkerrwilson** [comment]
I'm not sure if this is a related issue, but I'm having problems in a similar situation.

When using IQKeyboard with a project containing a web view, the keyboard manager works fine except  for inputs in modals. Specifically we are using angular-bootstrap within the web view, and any text inputs inside a presented angular modal are not properly handled by the keyboard manager. Note that these situations are correctly handled by safari.

Angular bootstrap with modal documentation: https://angular-ui.github.io/bootstrap/

Again, I'm not sure if this is the same issue as the above though it does seem similar, I'd be happy to make a separate issue if you think its unrelated.

**Comment by zhjuncai** [comment]
Looks like IQKeyboardManager doesn't handle popover case


```swift
if _textFieldView != nil &&
            (topMostController?.modalPresentationStyle == UIModalPresentationStyle.formSheet || topMostController?.modalPresentationStyle == UIModalPresentationStyle.pageSheet) &&
            _textFieldView?.isAlertViewTextField() == false {
            
            //In case of form sheet or page sheet, we'll add adjustFrame call in main queue to perform it when UI thread will do all framing updation so adjustFrame will be executed after all internal operations.
            OperationQueue.main.addOperation {
                self.adjustFrame()
            }
        }
```

**Comment by hackiftekhar** [comment]
Today I again checked it and found that popover case cannot be handle for all cases because when keyboard appears then Popover changes it's position/frame which might affect library logic.
