### ISSUE TITLE
Unable to hide Keyboard for specific fields

### ISSUE THREAD

**Issue by soumil-chugh** [hackiftekhar/IQKeyboardManager#665]
Hi,
I want to hide keyboard for a specific text field.When i switch to next field using keyboard, in the  func textFieldDidBeginEditing(textField: UITextField) i have a check for that specific field and i set self.view  .endEditing=true.
I have also tried other options like textField.resignFirstResponder() but with no success.
Kindly provide some solution and help me to resolve this issue.

**Comment by hackiftekhar** [comment]
So why don't you implement textFieldShouldBeginEditing and return NO for that special textfield.

**Comment by soumil-chugh** [comment]
Yes that would resolve the issue but I want the user to go to that field using the next button keyboard functionality provided.
I am able to resolve the issue by adding a delay before self.view.endEditing=true.
Thanks for your input.

**Comment by Piyush08** [comment]
@hackiftekhar I am also experiencing same issue when i am using IQPreviousNextView.
Can you please help me?
