### ISSUE TITLE
4.0.6  Crash on iOS7

### ISSUE THREAD

**Issue by beginlove** [hackiftekhar/IQKeyboardManager#666]
-[UIView(IQToolbarAddition) addPreviousNextDoneOnKeyboardWithTarget:previousAction:nextAction:doneAction:titleText:] (in axd) (IQUIView+IQKeyboardToolbar.m:541)

======================================

+[UIImage imageNamed:inBundle:compatibleWithTraitCollection:]: unrecognized selector sent to class 0x39555af0
(null)
((
	0   CoreFoundation                      0x2e08efeb <redacted> + 154
	1   libobjc.A.dylib                     0x38907ccf objc_exception_throw + 38
	2   CoreFoundation                      0x2e092873 <redacted> + 202
	3   CoreFoundation                      0x2e091253 <redacted> + 706
	4   CoreFoundation                      0x2dfe07b8 _CF_forwarding_prep_0 + 24
	5   axd                                 0xa0bb1 axd + 641969
	6   axd                                 0xa0f1b axd + 642843
	7   axd                                 0x38b2a1 axd + 3699361
	8   axd                                 0x388f3d axd + 3690301
	9   CoreFoundation                      0x2e0511f1 <redacted> + 12
	10  CoreFoundation                      0x2dfc553f _CFXNotificationPost + 1718
	11  Foundation                          0x2e9afa3d <redacted> + 76
	12  Foundation                          0x2e9b431b <redacted> + 30
	13  UIKit                               0x309a70dd <redacted> + 584
	14  UIKit                               0x30929147 <redacted> + 362
	15  UIKit                               0x30929407 <redacted> + 106
	16  UIKit                               0x309a5c37 <redacted> + 46
	17  UIKit                               0x30a4a243 <redacted> + 174
	18  UIKit                               0x30c86595 <redacted> + 156
	19  UIKit                               0x30a3100d <redacted> + 196
	20  UIKit                               0x308dc503 <redacted> + 1138
	21  UIKit                               0x30c83af5 <redacted> + 48
	22  UIKit                               0x308a3373 <redacted> + 218
	23  UIKit                               0x308a1abb <redacted> + 282
	24  UIKit                               0x308dad69 <redacted> + 772
	25  UIKit                               0x308da68f <redacted> + 666
	26  UIKit                               0x308af8ed <redacted> + 196
	27  UIKit                               0x308adf97 <redacted> + 7102
	28  CoreFoundation                      0x2e05a25b <redacted> + 14
	29  CoreFoundation                      0x2e05972b <redacted> + 206
	30  CoreFoundation                      0x2e057f1f <redacted> + 622
	31  CoreFoundation                      0x2dfc2f0f CFRunLoopRunSpecific + 522
	32  CoreFoundation                      0x2dfc2cf3 CFRunLoopRunInMode + 106
	33  GraphicsServices                    0x32f1b663 GSEventRunModal + 138
	34  UIKit                               0x3090e16d UIApplicationMain + 1136
	35  axd                                 0xb1311 axd + 709393
	36  libdyld.dylib                       0x38e14ab7 <redacted> + 2
)

dSYM UUID: CDCAD12A-D64A-30E3-9EBA-B52087E927C4
CPU Type: armv7
Slide Address: 0x00004000
Binary Image: axd
Base Address: 0x00030000

**Comment by hackiftekhar** [comment]
iOS7 isn't supported by latest version. 3.3.7 is the last supported version for iOS7
