### ISSUE TITLE
Hi everybody when I touch textfield my context view go down and my window gets black, size of keyboard

### ISSUE THREAD

**Issue by NVAT** [hackiftekhar/IQKeyboardManager#667]

**Comment by hackiftekhar** [comment]
Hello @NVAT you have not provided enough detail to debug this issue.

**Comment by NVAT** [comment]
@hackiftekhar This is screenshot for this problem.After submit content view scrolling down.Thank You.
![7c5bbf7e-8fc2-11e6-9e89-3f65d13f1650](https://cloud.githubusercontent.com/assets/16933227/19269158/f24458f2-8fc9-11e6-9fec-2c9aa9767810.png)

**Comment by hackiftekhar** [comment]
Looks strange, could you please share a demo so that I can debug it?

**Comment by hackiftekhar** [comment]
Also make sure you are not changing view frame from your own code.

**Comment by hackiftekhar** [comment]
@NVAT Any updates for a demo?

**Comment by reidmain** [comment]
I am having this same issue on my app. It is pretty ingrained into our app code so I am having some difficulty replicating this in a standalone demo app. Also it doesn't seem to be happening everywhere with IQKeyboardManager, other forms we have are continuing to work properly.

What is happening in my scenario is we are displaying a UIAlertController with a UITextField in it. Whenever the user dismisses that alert the frame of the navigation controller that was behind it then gets shifted downwards. The interesting thing is that it is not shifted a set amount every time. It seems to be variable dependent on how much information was being shown inside the UITableView on the current view controller.

If I figure out anything else out during my debugging I'll be sure to report back here.

**Comment by reidmain** [comment]
So the issue appeared to be caused by the fact that a UISearchField was the first responder at the time that the UIAlertController with the UITextField was displayed.

When the UIAlertController is shown the UITextField would automatically become the first responder. But then when the alert was dismissed the text field would resign its first responder status and for some reason that would cause the frame of the view controller that presented it to be updated

I worked around this by making my UISearchField resign first responder before the UIAlertController was displayed. It is a hack I know but it seems to be a decent work around.

**Comment by hackiftekhar** [comment]
Yeah, it's a workaround but good findings that you at least figureout a scenario.

**Comment by NVAT** [comment]
Hi Everybody I can't solve this problem when will be new `IQKeyboardManagerSwift` version?
Previous version  `IQKeyboardManager` works fine.
Thank You

**Comment by hackiftekhar** [comment]
@NVAT I asked you for a demo couple of days ago, how about that?

**Comment by NVAT** [comment]
Hi Mohd Iftekhar Qurashi ,I send You Demo version.This problem comes only with UIAlertViewcontroller.
Best regards
Artur Sahakyan
[Demo-IQ.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/571420/Demo-IQ.zip)

**Comment by hackiftekhar** [comment]
Thanks for the demo, I'll take a look at it on this weekend.

**Comment by hackiftekhar** [comment]
Able to reproduce easily. Checking what may be the wrong with this.

**Comment by NVAT** [comment]
Thank you,this version work on my demo versoin that I had sent you,but still not working on my real version

**Comment by hackiftekhar** [comment]
Are you using pods? Is this why it isn't working?

**Comment by hackiftekhar** [comment]
@NVAT btw this version works in my demo too, and if are still having issues then you have to reproduce issue in the demo anyhow.

@reidmain You was also having same issues, Could you please confirm if above commit is also working for you now?

**Comment by NVAT** [comment]
Yes I'm using pods,but when I did pod update nothing to changed I replaced via hand

**Comment by hackiftekhar** [comment]
Pod isn't updated yet.

**Comment by hackiftekhar** [comment]
@NVAT If you still want to use pods and want to use latest master branch code then you can point master branch of the repo in podfile to do the same.

**Comment by NVAT** [comment]
Hello I done copy paste latest commit in may cod but nothing's the same problem.

**Comment by hackiftekhar** [comment]
Then please share a new demo with reproducing the bug.

**Comment by NVAT** [comment]
I couldn't send you other Demo version,the problem is appears in my real version If you have opportunity can you connect via teamviewer?

**Comment by NVAT** [comment]
@hackiftekhar thank you its already ok for me,I recreate my pod file and manualy copy paste commit files then my problem solved.

**Comment by hackiftekhar** [comment]
Thanks :)

**Comment by Zeeker** [comment]
Is there any chance this will be included in a Swift 2.2 support branch?

**Comment by hackiftekhar** [comment]
@zeeker nope, we are going ahead but not backward. So we improve the things in later versions.
