### ISSUE TITLE
iPad in landscape mode.

### ISSUE THREAD

**Issue by alucarders** [hackiftekhar/IQKeyboardManager#668]
Hi!

I'm using IQKeyboardManager for the app that supports only landscape mode. I have 2 textfields in a stackview and everything works fine for the top textfield but it fails for the bottom textfield.
I'm using Swift 3, iPad simulator with iOS 10 and IQKeyboardManagerSwift v.4.0.6.

Setting `keyboardDistanceFromTextField` to some bigger values doesn't help either.

![screen shot 2016-10-11 at 12 33 30](https://cloud.githubusercontent.com/assets/10694577/19265868/cad1c76a-8faf-11e6-9530-9e9cb5ef110f.png)

**Comment by hackiftekhar** [comment]
Have you pinned your constraints with top layout guide or bottom layout guide?

**Comment by alucarders** [comment]
@hackiftekhar I'm using constraints pinned to the top layout guide. Should I pin 'em to the bottom?

**Comment by alucarders** [comment]
Hmmm, it seems that pinning to the bottom layout guide did solve the problem :)

**Comment by hackiftekhar** [comment]
Not sure but I think this souldn't solve the problem and you should avoid pinning to top/bottom layout guide (If this doesn't required). And if this extremely required then please see manual management guide to know a workaround with layout guides.
