### ISSUE TITLE
How to disable IQKeyboardManager in some textfield ?

### ISSUE THREAD

**Issue by X901** [hackiftekhar/IQKeyboardManager#669]
Hi , 
I have AlertviewController with textfield , I want to disable IQKeyboardManager from only this textfield

**Comment by hackiftekhar** [comment]
Please read manual management guide and you'll find something for you to disable for that particular viewController. Currenly There is no way to disable for particular textField.

**Comment by X901** [comment]
Thank you , It work fine

**Comment by MikeFighting** [comment]
What is the solution? Can you show me the code or the text ?

**Comment by heyehao2008** [comment]
[[IQKeyboardManager sharedManager] disableInViewControllerClass:[ViewController class]];
use this to disable for that particular viewController
no way to disable for particular textField

**Comment by mrugeshtank** [comment]
Here is solution, how you can disable for some specific textField.
`textField.inputAccessoryView = UIView()`

**Comment by hardikdarji** [comment]
textField.inputAccessoryView = UIView()

not works

**Comment by hackiftekhar** [comment]
@hardikdarji Currently there is no way to disable for a particular textfield, however it can be disable for a viewController

**Comment by abdulmanan-whizpool** [comment]
> Here is solution, how you can disable for some specific textField.
> `textField.inputAccessoryView = UIView()`

this worked for me  Thanks

**Comment by alirzaeram** [comment]
How to disable that in SwiftUI?

**Comment by fredriccliver** [comment]
`
let toolBar = UIToolbar()
textView.inputAccessoryView = toolBar
`

**Comment by bonniejaiswal** [comment]
If you uncheck enabled state for the textfield it works, It also disabled the toolbar next previous for it.
<img width="249" alt="Screen Shot 2022-07-07 at 11 55 21 PM" src="https://user-images.githubusercontent.com/1404994/177934493-18484099-6423-4bb0-a4e2-401d67b0906b.png">
