### ISSUE TITLE
If there is table section footer, footer will cover the textfield in tableviewcell

### ISSUE THREAD

**Issue by interchen** [hackiftekhar/IQKeyboardManager#67]
In my project, I put a UITextField into UITableViewCell, and there is a section footer title in table view.
When this UITextField became the first responser, the section footer view will cover the UITextField control.

![2014-09-15 09 24 05](https://cloud.githubusercontent.com/assets/2597576/4266200/0f312970-3c77-11e4-8472-0dfddadbcc96.png)

**Comment by RogerFanFan** [comment]
Hi hackiftekhar:

I use tableView with UITableViewStyle.plain
There are two sections in tableView.
2nd section has a textField and footer.
Footer will be a floating view on the bottom of tableView.

When textField's Cell has a footer (like 2nd section),  I also has this problem.
Footer will move up with the keyboard and textField is covered by footer.
But if textField's Cell does not have a footer, it's no problem.

How can I do for this issue?
Thanks very much

**Comment by RomuloVHSYS** [comment]
I'm using a workaround to get away of this bug

**For swift 4.2**

in `viewDidLoad`:
        
       ```
 NotificationCenter.default.addObserver(self, selector: #selector(MyTableViewController.keyboardWillShow), name: Notification.Name.UIKeyboardWillShow, object: nil)
        NotificationCenter.default.addObserver(self, selector: #selector(MyTableViewController.keyboardWillHide), name: Notification.Name.UIKeyboardWillHide, object: nil)
```

And implement these two methods on your class:


    ```
@objc func keyboardWillShow(notification: Notification) {
        self.tableView.footerView(forSection: 0)?.alpha = 0.0
    }
```
    
    ```
@objc func keyboardWillHide(notification: Notification) {
        self.tableView.footerView(forSection: 0)?.alpha = 1.0
    }
```
    
That will hide the "Floating footerView", but if you manually scroll to the footer and then scroll up again the "Floating footerView" will appear again.

**Comment by swiftserieschannel** [comment]
I have use only two lines to tackle the same issue in my project under viewDidLoad of your view controller.

IQKeyboardManager.shared.keyboardDistanceFromTextField = 40
self.tableViewObj.shouldIgnoreScrollingAdjustment = true
