### ISSUE TITLE
How to enable IQKeyboardManager in a particular class?

### ISSUE THREAD

**Issue by gopaldevra** [hackiftekhar/IQKeyboardManager#670]
Hi

This tool is really fantastic. I just want to use this class in the particular view controller. Is it possible. Please let me know.

**Comment by hackiftekhar** [comment]
Please read manual management guide and you'll find how to disable it for a particular view controller.

**Comment by gopaldevra** [comment]
Thanks @hackiftekhar, but I want to enable it for the particular class.

**Comment by hackiftekhar** [comment]
@gopaldevra there is also the documentation about enabling for a particular View controller.

**Comment by gopaldevra** [comment]
Thank you @hackiftekhar, I got it.

**Comment by NikKovIos** [comment]
For someone who searched it like me:
```IQKeyboardManager.sharedManager().disabledDistanceHandlingClasses.append(SignInViewController.self)```
