### ISSUE TITLE
Does not seem to work with Swift 3.0

### ISSUE THREAD

**Issue by BlaineOmega** [hackiftekhar/IQKeyboardManager#671]
I tried to use this with Swift 3.0 and xCode 8 and had no luck. I was told that I had to convert the syntax and then I had over 325 errors.

**Comment by quicken** [comment]
I also had this issue, the trick is to do the conversion. click save. See lots of errors, clean your build folder and compile again. You may now see a warning to update project setting. Accept Xcode recommendations after that you may need to do another clean your build folder. After that it works. I had to do the above with a bunch of other PODs as well.

I definitely works, I litterally just configured this library and OMG its awesome!

**Comment by hackiftekhar** [comment]
Make sure you are using 4.0.6 version.it's swift3 compatible.

**Comment by MVakas** [comment]
Just tried the newer version, it’s compatible with Swift 3.0

**Comment by Andre113** [comment]
Installed the newer version right now, its working.

**Comment by hackiftekhar** [comment]
Great!
