### ISSUE TITLE
IQKeyboardManagerhad no effect on iOS 10

### ISSUE THREAD

**Issue by tan2547** [hackiftekhar/IQKeyboardManager#673]
IQKeyboardManager had no effect on  iOS 10.

**Comment by hackiftekhar** [comment]
@tan2547 Please share more info

**Comment by hackiftekhar** [comment]
@tan2547 Could you please explain what isn't working correctly?

**Comment by love-Apricot** [comment]
hi, 
iOS10,I click on the input box to crash.

**Comment by hackiftekhar** [comment]
@love-Apricot Please share more info or demo.
