### ISSUE TITLE
Autogrowing UITextView

### ISSUE THREAD

**Issue by mradzinski** [hackiftekhar/IQKeyboardManager#677]
Hey @hackiftekhar, first and foremost, thanks for building this. My question is related to my app itself. I have a ```UITextView``` which grows depending on the amount of entered text. I noticed that IQKeyboardManager does not seem to handle this cases out of the box (In the sense that my ```UITextView``` grows and gets hidden behind the keyboard without IQKeyboardManage adjusting the position). 

So, is there any way I can force IQKeyboardManager to detect this kind of layout changes (height of the view) and adjust the Y position itself so that my ```UITextView``` remains visible despite of its growth?

<img width="331" alt="captura de pantalla 2016-10-20 a las 12 58 17" src="https://cloud.githubusercontent.com/assets/4214209/19567664/f7419bba-96c4-11e6-9a35-839ee72bdace.png">
Without growth

<img width="332" alt="captura de pantalla 2016-10-20 a las 12 58 32" src="https://cloud.githubusercontent.com/assets/4214209/19567674/fcbc2b8c-96c4-11e6-9fb0-28705f5bb166.png">
UITextView grew, but IQKeyboardManager didn't adjust

**Comment by hackiftekhar** [comment]
Yes @mradzinski you can do that using `reloadLayoutIfNeeded` method of IQKeyboardManager. Even there is a demo in repo demo app demo strating same functionality as exactly you need.

**Comment by mradzinski** [comment]
reloadLayoutIfNeeded() is not working for this scenario, I actually tried it before opening up the issue

**Comment by mradzinski** [comment]
After using ```reloadLayoutIfNeeded()```. Same outcome

<img width="335" alt="captura de pantalla 2016-10-20 a las 13 34 32" src="https://cloud.githubusercontent.com/assets/4214209/19568923/fad96db6-96c9-11e6-8308-60b677662a33.png">

**Comment by hackiftekhar** [comment]
Have you checked repo demo and find out how it is implemented?

**Comment by mradzinski** [comment]
Yes, you have it implemented in a button:
```
    @IBAction func reloadLayoutAction (_ sender : UIButton) {
        IQKeyboardManager.sharedManager().reloadLayoutIfNeeded()
    }
```

Autogrowing UITextView cannot have this implementation on a button, the Keyboard should adust itself whenevert the field grows, and the field grows not because of a stepper but because o entered text.

**Comment by hackiftekhar** [comment]
Then you should detect where your textView height changes and make a call to `reloadLayoutIfNeeded`. Generally speaking library is not responsible if your textView grows dynamically, it's the developer who responsible for textView grow, so as a developer I added standard method so that app developer can call according to their convenience if they need.

So your job is to find exact time where you should call `reloadLayoutIfneeded` method and do a call to this.

**Comment by ManagerLi** [comment]
How did you solve it?

**Comment by mradzinski** [comment]
@ManagerLi, can't remember exactly, but I'm 99.9% sure a call to ```reloadLayoutIfNeeded``` at some specific points of my code solved it.
