### ISSUE TITLE
Not Working with SearchBar

### ISSUE THREAD

**Issue by leminhtuan2015** [hackiftekhar/IQKeyboardManager#680]
I installed with pod ok, And already follow your introduction 

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {

```
var window: UIWindow?

func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {

  IQKeyboardManager.sharedManager().enable = true

  return true
}
```

}

I got no error but nothing happend when I focus on searchbar .

I am using Swift 3, Xcode 8, Please take a look for this issue, Thank you sir!

**Comment by MHX792** [comment]
Same here. Any solutions?

**Comment by hackiftekhar** [comment]
Could you guys let me know what exactly isn't working with UISearchBar?

**Comment by lcccch** [comment]
The toolbar is not shown when focus on UISearchBar.
Swift 3, Xcode 8.

**Comment by hackiftekhar** [comment]
Toolbar in searchBar is explicitly disabled. Because in most of the searchBar the boyyom search button enable/disable to dismiss keyboard.

**Comment by MHX792** [comment]
Any way to manually enable it? When you have life filtering the search button is kind of useless and a done button would be more user friendly.

**Comment by hackiftekhar** [comment]
You could probably try to add your own inputAccessoryView for searchBar?

**Comment by NirajCapermint** [comment]
Any solution for this ? @hackiftekhar
