### ISSUE TITLE
why it do not work with xcode8,what should I do?

### ISSUE THREAD

**Issue by JustToBeBetter** [hackiftekhar/IQKeyboardManager#681]
I build my project with xcode 8 and i add the IQKeyboardManager to my project,but it do not work,and only show the toolbar,what should i do

**Comment by hackiftekhar** [comment]
Please read the README file first, you may probably missing somethjng. Still if your problem doesn't reaolve then please read Manual Management guide.

**Comment by JustToBeBetter** [comment]
thanks
