### ISSUE TITLE
Hiding toolbar for specific views

### ISSUE THREAD

**Issue by WinKhantAung** [hackiftekhar/IQKeyboardManager#682]
I tried to disable toolbar for specific views sth like IQKeyboardManager.sharedManager().disabledToolbarClasses(LoginViewController);.
But it response with an error message "Cannot call value of non-function type '[UIViewController.Type]'.
Any suggestion pls....

**Comment by hackiftekhar** [comment]
You have to use append method to disabledToolbarClasses, you are using this incorrectly.

**Comment by WinKhantAung** [comment]
I got it...👍 Thanks for your reply
