### ISSUE TITLE
Textfield delegate doesn't work in swift 3 

### ISSUE THREAD

**Issue by AnilKuadejaSa** [hackiftekhar/IQKeyboardManager#683]
Hi There,

After implementing IQKeyboardmanager for swift 3 textfield delegate doesn't work at all.

If i will comment a code of IQKeyboardmanager then it starts working and calling it's delegate method. 

Anyone has faced same issue..?

Thanks

**Comment by iostd** [comment]
Just declare IQKeyboardmanager in AppDelegate You don't need to put in every view controller

**Comment by hackiftekhar** [comment]
Could you please let us know what exactly you are doung there with IQKeyboardManager?

**Comment by aelzohry** [comment]
I'm facing same issue in both (Swift 2.2+Xcode 7.3) and (Swift 3+Xcode 8)

my issue: I'm using collection of textFields (something like a form) and using delegate for few textFields of them and fire some code in shouldBeginEditing method depending on tag of textField... when enabling IQKeyboardManager, delegate called for all textFields include ones that doesn't belong to delegate and fire code that doesn't belong to that textField....

**Comment by hackiftekhar** [comment]
@aelzohry  Please read Manual Management guide, there are some workarounds to overcome with this situation.

**Comment by aelzohry** [comment]
@hackiftekhar thanks
