### ISSUE TITLE
Search bar customisation

### ISSUE THREAD

**Issue by Alex293** [hackiftekhar/IQKeyboardManager#684]
Hi, 

How to customise the keyboard of a search bar ?
I'd like to be able to change the search button text and selector if possible

searchBar.addRightButtonOnKeyboardWithText("Add", target: self, action: #selector(test), shouldShowPlaceholder: true)

doesn't do anything is it supposed to ?

**Comment by hackiftekhar** [comment]
Nope, this is not supported by library and you have to manually do it yourself.
