### ISSUE TITLE
 Empty Space Below UIScrollViews

### ISSUE THREAD

**Issue by hdoria** [hackiftekhar/IQKeyboardManager#685]
Hi,

I'm having some problems with IQKeyboardManager and UIScrollView (using Storyboard). I have the same setup as described [here](http://stackoverflow.com/a/28586598/1028009) and [here](http://mokagio.github.io/tech-journal/2015/06/24/ios-scroll-view-and-interface-builder.html):

My interface setup:

-VIew
--UIScrollView
---UIView
----Images, Labels and Text Fields

The problems is exactly the same as described here: https://github.com/hackiftekhar/IQKeyboardManager/issues/485

There is a lot of extra empty space when the keyboard appears and the textfield scrolls. This does not happen when IQKeyboardManger is disabled.

Swift 3.0.1, Xcode 8.1, Carthage and IQKeyboardManagerSwift here.

**Comment by hackiftekhar** [comment]
Then can you please share a demo with me because this shouldn't be an issue after that fix.

**Comment by hdoria** [comment]
@hackiftekhar link for the demo:

https://github.com/hdoria/IQKeyboardManagerDemo

**Comment by hackiftekhar** [comment]
Thanks @hdoria

**Comment by hdoria** [comment]
@hackiftekhar were you able to reproduce the problem? Do you need something else?

**Comment by hackiftekhar** [comment]
I didn't get a chance to check demo @hdoria, but will try to get some time from my schedule.

**Comment by betraying** [comment]
same problem

**Comment by hackiftekhar** [comment]
@hdoria Library is doing correct. You can check that before showing keyboard, your scrollView height is too big due to your constraints and library is doing nothing to add any empty space. But your constraints are calculating that amount of height so if you cold make adjustments to your constraint to calculate exact height of your scrollView then problem will be solved.

@betraying I'm suggesting same suggestion to you as well. If you have different issue than the demo, let me know.

**Comment by hdoria** [comment]
@hackiftekhar ok. Just a quick question: but what's wrong with the constraints? My scrollView is using the superview bounds. How should I add my constraints in the case? I've tried everything. Also, I've followed the guides from my first post.

**Comment by hackiftekhar** [comment]
@hdoria Your scrollView contentSize is equal to the screen bounds and that's the actual issue. But it's Content ends at NEXT button. So you should remove Equal to screen bound constraint and make your NEXT button bottom constraint equal to 10 or something like that. So your scrollView bound will be equal to something like `NEXT.frame.origin.y+NEXT.frame.size.height+10` and that would work.
