### ISSUE TITLE
When disabling, Auto Toolbar continues to show.

### ISSUE THREAD

**Issue by JuanPabloBoero** [hackiftekhar/IQKeyboardManager#686]
Version 4.0.5

I am using the manager in only one view controller, on `viewDidLoad` i do `IQKeyboardManager.sharedManager().enable = true` , and in my `viewWillDisappear` i do `IQKeyboardManager.sharedManager().enable = false` , so in my other views when i tap on a `textField` the autoToolBar continues to show.

Currently i am using a work around:
```
        IQKeyboardManager.sharedManager().enableAutoToolbar = false
        IQKeyboardManager.sharedManager().enable = false
```

**Comment by hackiftekhar** [comment]
You are doing correct, Autotoolbar is managed by enableAutoToolbar and not by enable property.
