### ISSUE TITLE
Does not seem to working in 10.1?

### ISSUE THREAD

**Issue by Siriss** [hackiftekhar/IQKeyboardManager#688]
I have been using IQKeyboardManager for a while now, but with 10.1, it does not seem to be working anymore. Below are two pictures, the first is my textView before I start editing, and afterwards is the textView covered by the keyboard. I am pretty sure this used to work pre 10.1 update. Am I doing it wrong?

<img width="776" alt="screen shot 2016-11-01 at 4 18 02 pm" src="https://cloud.githubusercontent.com/assets/2783547/19909881/47fc4a1c-a04f-11e6-8338-93e6a5dbb62b.png">
<img width="778" alt="screen shot 2016-11-01 at 4 18 16 pm" src="https://cloud.githubusercontent.com/assets/2783547/19909882/47ffaec8-a04f-11e6-8b97-4bb689404f7f.png">

**Comment by hackiftekhar** [comment]
@siriss, Can you run the demo project in Xcode8.1 and let me know if demo works for you or not.

**Comment by Siriss** [comment]
Everything in the demo seems to work. If I add viewWillAppear to my TableViewController, I can scroll past the keyboard, but it does not do it automatically.

A side note, you lose your navigation bar when demoing the YYTextView.

**Comment by hackiftekhar** [comment]
If you use UITableViewController, then library us explicitly disabled for that.

**Comment by hackiftekhar** [comment]
@Siriss Could you please update me here if you find something useful for me?

**Comment by Siriss** [comment]
I have found that if I add viewWillAppear based on this post http://stackoverflow.com/questions/38768966/iqkeyboardmanager-not-working-when-uitableview-embedded-in-a-container-view
I can scroll past the keyboard, but it does not automatically move when I select the textView.
I will be doing a lot more testing this coming week, and will post back with a more detailed description. Thanks!

**Comment by hackiftekhar** [comment]
@Siriss Could you please let me know if you  are using UITableViewController?

**Comment by Siriss** [comment]
Sorry for the delay. I am using a UITableViewController inside a container view inside a UIViewController. It seems to only reliably happen with my UITextView in the tableView footer.

**Comment by hackiftekhar** [comment]
So if it's UITableViewController then library ignore adjusting in favour of UITableViewController default behaviour of textField and keyboard handling.
