### ISSUE TITLE
If the context of the input box is in Chinese, context up occurs when loses focus

### ISSUE THREAD

**Issue by peakerWu** [hackiftekhar/IQKeyboardManager#689]
If the context of the input box is in Chinese, context up occurs when loses focus

**Comment by hackiftekhar** [comment]
Please share a video or screenshot.

**Comment by peakerWu** [comment]
![56d06016-4801-447a-99a8-61965552b07b](https://cloud.githubusercontent.com/assets/16396005/19917556/2e0c0b78-a0ff-11e6-8861-65e90e545a57.png)
in simulator maybe correct.but in iPhone 6p( iOS10) is error.
demo: [https://github.com/peakerWu/IQKeyboardManagerTest.git](https://github.com/peakerWu/IQKeyboardManagerTest.git)

**Comment by peakerWu** [comment]
only set "text.borderStyle = UITextBorderStyleNone;" happen this. And  if text is English or Arabic numerals also right

**Comment by hackiftekhar** [comment]
Ok, I'll check demo when I get some free time.

**Comment by peakerWu** [comment]
Ok, Thank you.

**Comment by hackiftekhar** [comment]
@peakerWu I checked in simulator and it works fine and I don't have real iPhone 6p device to test it. Could you please suggest how should I move or will you try to debug what may be wrong with this.

**Comment by peakerWu** [comment]
First,You should set the system language is Chinese,
Second,You must  input Chinese  in any real iPhone.
Third,You should set UITextField property borderStyle = UITextBorderStyleNone.

do this,The above error may occur

**Comment by hackiftekhar** [comment]
Is this reproducible with iPhone5S device or iOS simulators?

**Comment by peakerWu** [comment]
Only in real iPhone happen this, iOS simulators is right.

**Comment by hackiftekhar** [comment]
Then I don't have real iPhone6p device. I'm having iPhone 5S. Is this reproducible with this device?

**Comment by peakerWu** [comment]
Yes,you can have a try

**Comment by hackiftekhar** [comment]
It is reproducible, but if you remove library and then do the same thing then this is still reproducible. So I guess it's the iOS bug and not the library once. Could you please check at your end if this still reproducible after removing library in demo?

**Comment by peakerWu** [comment]
OK I know it,thank you very much
