### ISSUE TITLE
where is the "addTextFieldViewDidBeginEditingNotificationName" in swift?

### ISSUE THREAD

**Issue by abellee** [hackiftekhar/IQKeyboardManager#691]
where is the method "addTextFieldViewDidBeginEditingNotificationName" in swift version?
still existing?

**Comment by abellee** [comment]
I have found it, it's "registerTextFieldViewClass"

**Comment by hackiftekhar** [comment]
Ahh, Tganks, probably I forget to rebame this in swift. Keeping this card open.

**Comment by hackiftekhar** [comment]
I checked. It's already renamed to `registerTextFieldViewClass` both languages.
