### ISSUE TITLE
Changing views height instead of moving

### ISSUE THREAD

**Issue by DarthRamone** [hackiftekhar/IQKeyboardManager#692]
Let's suppose that we have pinned to top UITextField, and UITableView below that field and pinned to bottom of screen, kinda UISearchController. Is there any way to change UITableView's height instead of overlapping it by keyboard? In case user wants to see whole table, not part of it.

**Comment by hackiftekhar** [comment]
As a user @DarthRamone It's an app specific special requirement and I think this should be done by your own logic by adding an observer or something like that. It's would be very hard for library to find what is overlapping keyboard and to move them above the keyboard.

**Comment by DarthRamone** [comment]
Thank you. That's all I wanted to hear.

**Comment by hackiftekhar** [comment]
Great! Have a good day!
