### ISSUE TITLE
Next and Previous buttons not displayed

### ISSUE THREAD

**Issue by kumaresan-cgvak** [hackiftekhar/IQKeyboardManager#693]
Next and Previous buttons are not displayed when the textfield is nested inside UIStackView

**Comment by hackiftekhar** [comment]
Have you checked demo app demonstrating UIStackView?

**Comment by kumaresan-cgvak** [comment]
Yes.. 

Upon research i found that.. previous and next buttons are displayed, if a single stackview contains multiple text field.

unfortunately, if parent stackview is nested with child stack view and where each child stack view have single text field, then previous and next buttons are not displayed

**Comment by hackiftekhar** [comment]
Then have you checked demo app demonstrating IQPreviousNextView? 😆

**Comment by kumaresan-cgvak** [comment]
Perfect .. Thank You :grin:
