### ISSUE TITLE
UI issue

### ISSUE THREAD

**Issue by jinthreek89** [hackiftekhar/IQKeyboardManager#694]
This is critical issue.
I am experiencing this issue when I will behavior follow as these step.
 - 1. Press text field. then it will show keyboard.
 - 2. Press Home button of Device. then app will go to background mode.
 - 3. Open app again from background thread.
 - 4. Press out of textfield. then keyboard will be hide.
**In this case, UIView is cutting like as keyboard height**
Please see this video 
https://drive.google.com/file/d/0BwE-Pzk0GuEeUVpaOGltdVp4VTQ/view?usp=sharing

**Comment by hackiftekhar** [comment]
hi @jinthreek89 Can you please share a demo project with me so that I can take a look and will try to fix it?

**Comment by jinthreek89** [comment]
Do you want to source code?
 * note : I used IQKeyboardManager with [LGSideMenuController](https://github.com/Friend-LGA/LGSideMenuController)

**Comment by hackiftekhar** [comment]
Ok, I'll check when I'll have some free time and most probably in weekend.

**Comment by hackiftekhar** [comment]
@jinthreek89 I don't need your actual source code you are working on, but I need a standalone demo project where this issue is reproducible.

**Comment by jinthreek89** [comment]
[ForIQKeyboard.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/587088/ForIQKeyboard.zip)
This is simple project.
Please reference this [video link](https://drive.google.com/file/d/0BwE-Pzk0GuEeUVpaOGltdVp4VTQ/view?usp=sharing)

**Comment by hackiftekhar** [comment]
Thanks, I'll take a look.

**Comment by hackiftekhar** [comment]
@jinthreek89 This issue is due to Top/Bottom Layout constraints and there are some issues with library due to this and you can do some workaround to fix it.
1 - Remove Top/Bottom Layout constraints and make constraint to your view.
2 - Please read Manual Management guide for how to work with Top/Bottom Layout constraints
3 - Set `layoutIfNeededOnUpdate` to `YES`.

Let me know if this issue is solved for you or not.

**Comment by jinthreek89** [comment]
Okay, great.
I have solved problem by remove and rearrange top constraint with super view(not top layout guide).
So, I would like to know one.
This is issue of IQKeyboardManager or it should be must only to arrange with super view?
I think we will solve this issue in featre.
Thank you so much.

**Comment by hackiftekhar** [comment]
Technically this isn't an issue with anythin , neitger with library nor with your code. The thing is that Layout Guide Constraint works differently than normal constraints. That's why it sometimes mess-up the things when layouting hierarchy.
