### ISSUE TITLE
UI Issue 

### ISSUE THREAD

**Issue by Milosfs** [hackiftekhar/IQKeyboardManager#696]
When textFields are embedded in scrollView and keyboard pops out it pushes active field to an invisible point that needs to be scrolled down manually so user can see active textField.

Reproduction sample provided below.

[IQKeyboardScrollviewBug.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/582770/IQKeyboardScrollviewBug.zip)

**Comment by hackiftekhar** [comment]
This is because you've set scrollView.contentInset bottom as 400 that's why it's behaving weird. If you comment that line then it will work perfect.

However why are you trying to put your scrollView inside UICollectionView cell?

**Comment by Milosfs** [comment]
Oh tnx, my bad, however i need that scroll inside so all fields can be reached on all devices and on click to next it should scroll horizontal to next cell..
