### ISSUE TITLE
Conflict with UITableViewController gestures！

### ISSUE THREAD

**Issue by FelixBubble** [hackiftekhar/IQKeyboardManager#697]
Hello, I use the "IQKeyboardManager" when found in the UITableViewController click on the blank area, the keyboard can not be properly recovered (in UIViewController normal). This should be how to solve it?

XCode:8.1
IQKeyboardManager:4.0.5

[IQKeyboardManagerTestOC.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/584921/IQKeyboardManagerTestOC.zip)

**Comment by hackiftekhar** [comment]
Library totally ignore UITableViewController with respect to it's own implementation of handling keyboard, so if there is an issue then it's either an issue with your code or with UITableViewController handling.
