### ISSUE TITLE
Next and Previous arrows on keyboard toolbar

### ISSUE THREAD

**Issue by bilzz** [hackiftekhar/IQKeyboardManager#699]
Hey! thanks for this owsem library.
But i am facing issue about next and previous arrows on toolbar of keyboard from last one year. I have do every possible things on my end but failed to get those arrows. These arrows are working perfect in one of my application but after that i can't able to get those arrows on toolbar. **Please fix that issue as soon as possible.**

![simulator screen shot 13-nov-2016 2 50 37 am](https://cloud.githubusercontent.com/assets/7510476/20242314/12d1278a-a94c-11e6-88d7-a8a2188c4f42.png)

**Comment by hackiftekhar** [comment]
Are you joking? You are facing this from last one year?

However please be sure that both textFields are on same view and not on different view. If Yes then you have 2 options:-
1) Check how to use IQPreviousNextView.
2) restructure hierarchy to make sure they bith have on same view.

**Comment by bilzz** [comment]
hey thanks for your responce.
if the text fields are on different views then how can we show next and previous button?
is there any way for that?

**Comment by hackiftekhar** [comment]
Use IQPreviousNextView. Xgeck demo app for how to use it or read Manual Management guide in repo.

**Comment by bilzz** [comment]
thanks iftikhar.

**Comment by sal123** [comment]
thanks iftikhar.
