### ISSUE TITLE
Text filed hiding on Landscap mode for iPad in Present view controller

### ISSUE THREAD

**Issue by maulikpat** [hackiftekhar/IQKeyboardManager#700]
Hi,

The old issue is still present in new release. 
From your demo code Follow below steps to reproduce it : 

Be in Portrait mode.
1. Select 1st option in 1st screen
![screen shot 2016-11-14 at 2 08 39 pm](https://cloud.githubusercontent.com/assets/2304770/20258094/e36b93c6-aa73-11e6-9c39-20340b613906.png)

2. Then click on Push 
3. Then Present 
4. Select last Text filed and change the orientation. 

![simulator screen shot nov 14 2016 2 05 14 pm](https://cloud.githubusercontent.com/assets/2304770/20258142/24dc3eaa-aa74-11e6-94bb-2e3ee93e796c.png)

Changing orientation creates this issue.

Any suggestion ?

**Comment by hackiftekhar** [comment]
Need to check what may be wrong
