### ISSUE TITLE
Wrong uitextfielddelegate

### ISSUE THREAD

**Issue by Vanilil** [hackiftekhar/IQKeyboardManager#701]
I have a uitableviewcell with some uitextfield and some custom views which are uiscrollview with  some uviews and one uitextfield subviews.
My issue is that classic uitextfield call the uitextfield delegate in customview class after the classic uitextfield delegate.

**Comment by hackiftekhar** [comment]
Are you asking about textFieldShouldBeginEditing?

**Comment by Vanilil** [comment]
Yes

**Comment by hackiftekhar** [comment]
Please read Manual Management guide, there is some limitations about delegate methods.

**Comment by Vanilil** [comment]
Nothing works without adding dependency in the third-party library for the custom view.

**Comment by hackiftekhar** [comment]
@vanilil not sure what you are trying to explain? Could you please reword your sentence?
