### ISSUE TITLE
Deprication warning

### ISSUE THREAD

**Issue by phenomen2277** [hackiftekhar/IQKeyboardManager#703]
I manually added the swift package (current & 4.0.7) to my project. I'm getting 2 deprecation warnings

/Users/...IQKeyboardManagerSwift/IQKeyboardReturnKeyHandler.swift:642:32: 'textView(_:shouldInteractWith:in:)' was deprecated in iOS 10.0: Use textView:shouldInteractWithURL:inRange:forInteractionType: instead

/Users/j.../IQKeyboardManagerSwift/IQKeyboardReturnKeyHandler.swift:661:32: 'textView(_:shouldInteractWith:in:)' was deprecated in iOS 10.0: Use textView:shouldInteractWithTextAttachment:inRange:forInteractionType: instead

Thank you and keep up the great work!!!!

**Comment by hackiftekhar** [comment]
Do you know a way of conditional compiling like ObjC?
Do you know a way to hide this warnings like we can do in ObjC?

If yoo know then let me know.

**Comment by brunomoreiraw** [comment]
Would be great to eliminate this warnings. Thanks for the great work!

**Comment by hackiftekhar** [comment]
@brunomoreiraw @phenomen2277 could you please fix this and make a pull request if you know how to fix it?

**Comment by phenomen2277** [comment]
I was compiling for iOS 10. That is why i got the deprecation warnings. If you go to the 2 delegate functions causing the warning, upon them there is the new implementation for iOS 10. 

To fix the warnings, I just removed the 2 delegate functions causing the warning. As I said, I'm compiling for iOS 10.

**Comment by hackiftekhar** [comment]
How about others who are compiling against lower version? As a library author, I also need to support lower iOS versions.

**Comment by phenomen2277** [comment]
You solve this issue by either validity checking or different branches fro different targets. Happy holidays!

**Comment by hackiftekhar** [comment]
Can you please let me know how can I do validity checking? Can you please open a pull request? Make sure at least iOS8 should be supported.
