### ISSUE TITLE
UITextField inside UICollectionViewCell with cell size set programmatically problem

### ISSUE THREAD

**Issue by nhantrivinh** [hackiftekhar/IQKeyboardManager#704]
Problem Demo:
https://youtu.be/cZFzLwvENio

The cell doesn't come back down after keyboard appear. I programmatically set up the collection view cell for dynamic sizing. I want it to reverse what it does when done editing.

**Comment by hackiftekhar** [comment]
Looks like you are using UIScrollView. In IQUIScrollView+Additions.h you'll find a property shouldRestoreScrollViewContentOffset, set it to YES for that particular scrollView.
