### ISSUE TITLE
IQToolBar is missing when the IQKeyboardReturnKeyHandler delegate is set in the Swift version

### ISSUE THREAD

**Issue by tertullianus** [hackiftekhar/IQKeyboardManager#705]
If you set the IQKeyboardReturnKeyHandler delegate to the view controller, the tool bar for going to the next field is missing, unless you implement all of the UITextField delegate callbacks. In addition the Next key does not work. This happens only in the Swift version. IQKeyboardReturnKeyHandler behaves normally in the Objective-C version when the delegate is set.

You can reproduce this bug in the sample swift file CustomViewController.swift by adding the following line returnHandler.delegate = self after returnHandler.lastTextFieldReturnKeyType = .done is set.

You can see what happens in the attached screen shot.

![image](https://cloud.githubusercontent.com/assets/1121279/20387433/08403118-ac8e-11e6-812a-d32a3cae5980.png)

**Comment by hackiftekhar** [comment]
Thanks for the report, I'll check.
