### ISSUE TITLE
UIRequiredDeviceCapabilities is invalid for frameworks

### ISSUE THREAD

**Issue by hdoria** [hackiftekhar/IQKeyboardManager#706]
I can't submit an app that uses IQKeyboardManager to the App Store.

[Transporter Error Output]: ERROR ITMS-90689: "Invalid Info.plist key. The key 'UIRequiredDeviceCapabilities' in bundle MyApp.app/Frameworks/IQKeyboardManagerSwift.framework is invalid for frameworks"

Deleting the UIRequiredDeviceCapabilities key from the Demo/Swift_Demo/Resources/Info.plist file fixed the problem.

**Comment by DesmondDAI** [comment]
Same problem. Does any one knows why this would happen even I haven't change the framework? Thanks!

**Comment by hackiftekhar** [comment]
Merged!
