### ISSUE TITLE
Weird animation of text change in collectionView

### ISSUE THREAD

**Issue by icodesign** [hackiftekhar/IQKeyboardManager#708]
You can check the demo of collectionView. Repro steps:
1. Enable auto toolbar;
2. Input text in the first text field;
3. Go to next;
4. You can see the text in the first text field jumps with an animation;

**Comment by hackiftekhar** [comment]
Ok, I'll check.

**Comment by hackiftekhar** [comment]
I checked it and yeah, it jumps but it looks to be iOS issue and not due to library.

**Comment by icodesign** [comment]
Sorry to hear that. Thanks @hackiftekhar though.
