### ISSUE TITLE
textView 

### ISSUE THREAD

**Issue by TWH-KKK** [hackiftekhar/IQKeyboardManager#711]
I used textView  and textView is not full screen  and viewControl.view is a ScrollView ;
the keyboard distance is not adjust;
![53e4377ce54b3120f3bd236ab9ead1f5](https://cloud.githubusercontent.com/assets/11454692/20587953/4ef1e9c6-b24c-11e6-9a4c-d6519cbfb690.png)

**Comment by rickyjwhong** [comment]
similar issue. looks like the textview is growing and when i exit and try again, then it works as normal. just not the first time

**Comment by hackiftekhar** [comment]
Make sure your ScrollView content size is returning correct value, may be you havn't set contentSize or not using autolayout to calculate it's contentSize.
