### ISSUE TITLE
UI Not Responding when touching UITextField

### ISSUE THREAD

**Issue by sina-kh** [hackiftekhar/IQKeyboardManager#712]
UI not responding when touching UITextField unexpectedly, and I don't have any idea why this happens...?

My ui structure is something like this:

Custom ViewController
--> Custom View
        --> UIScrollView
                --> UITextField

**Comment by sina-kh** [comment]
@hackiftekhar could you help me please?

**Comment by sina-kh** [comment]
After debugging, I found out that i had an extension for UIView in my codes that had `viewController` function, and It had a bug, too! So when I was tapping UITextField, it was running that function with an infinite loop!!

**Comment by hackiftekhar** [comment]
Cheers! I think I should rename viewController property to something else since most of the library keep same name and it conflict with my own version of viewController property.
