### ISSUE TITLE
There is no Animation on Keyboard hide method!

### ISSUE THREAD

**Issue by dipkasyap** [hackiftekhar/IQKeyboardManager#714]
Hiding keyboard seems quite Strange, i should be animated so that it feels smooth.
Swift 3

**Comment by hackiftekhar** [comment]
Please share a demo because library does smooth animation.

**Comment by hackiftekhar** [comment]
@dipkasyap If you were seeing strange in simulator then it's ok, if you see strange animation in device then reopen this pull request.
