### ISSUE TITLE
Mobile phone installed third party input method leading to crash in iOS 10

### ISSUE THREAD

**Issue by love-Apricot** [hackiftekhar/IQKeyboardManager#716]

**Comment by hackiftekhar** [comment]
Then this must be an issue with third party keyboard. Could you please let me know more details that why app crashed?

**Comment by love-Apricot** [comment]
*** Assertion failure in -[UICGColor encodeWithCoder:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit/UIKit-3512.60.12/UIColor.m:1457
libc++abi.dylib: terminate_handler unexpectedly threw an exception

App Name:搜狗输入法-Sogou Keyboard

**Comment by hackiftekhar** [comment]
Sp how can you say that it's related to IQKeyboardManager? Crash log doesn't say a single word with regards to IQKeyboardManager library.

**Comment by love-Apricot** [comment]
Sorry, I found out that it might have been a reference to other libraries in my project.
