### ISSUE TITLE
Keyboard Covers When Switching Between Two UITextFields on Same Line

### ISSUE THREAD

**Issue by LeakedDave** [hackiftekhar/IQKeyboardManager#718]
I have 2 UITextFields, equal widths (each about half the width of the screen), more than halfway down the screen. When I tap the first one, the screen pans perfectly so the UITextField sits right above the keyboard. However, if I tap the UITextField to the right of it, or hit the next button, the keyboard shifts above and covers the new responder UITextField.

Not sure what is causing this to happen, but the right UITextField has a constraints to Align Vertical Center with the left UITextField. The same issue happens if I tap the UITextField on the right, and then when I tap the UITextField on the left, the keyboard covers both of the TextFields again.

I can post screenshots if that will help.

**Comment by LeakedDave** [comment]
So one thing I've determined is that whenever a UITextField resigns first responder, viewWillLayoutSubviews() and viewDidLayoutSubviews() are getting called on my UIViewController. This is likely causing the entire frame to reset, and the newly selected UITextField is being pushed underneath the keyboard.

Any idea why this is suddenly happening or any proposed fix?

**Comment by hackiftekhar** [comment]
Looks like it may be some issue with your constraint or layout. Make sure you havn't pinned top/bottom layout constraints with those textFields.
