### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by RomanVolkov** [hackiftekhar/IQKeyboardManager#719]
Please, add carthage support

**Comment by hackiftekhar** [comment]
It's already available for carthage, I need add documentstion for that. If you send a OR then it would be great!

**Comment by peterfennema** [comment]
I am using Carthage with Swift 3, works fine.
Add this line to your [CartFile](https://github.com/Carthage/Carthage/blob/master/Documentation/Artifacts.md#cartfile):

github "hackiftekhar/IQKeyboardManager"

**Comment by RomanVolkov** [comment]
Thanks. Yep, I tried to add it via Carthage and it works fine. 
It could be great to add it into installation section

**Comment by hackiftekhar** [comment]
Yeah,sure! Will add in Installation Section.

**Comment by hackiftekhar** [comment]
Added!
