### ISSUE TITLE
keyboardShowing is always YES

### ISSUE THREAD

**Issue by Whirlwind** [hackiftekhar/IQKeyboardManager#721]
I find that if I disable it, the `keyboardShowing` always return YES!

I check the code, I find that:

```
-(void)keyboardWillShow:(NSNotification*)aNotification
{
    ...
    _keyboardShowing = YES;
    
	if ([self privateIsEnabled] == NO)	return;
   ....
}

/*  UIKeyboardWillHideNotification. So setting rootViewController to it's default frame. */
- (void)keyboardWillHide:(NSNotification*)aNotification
{
   ...
    if ([self privateIsEnabled] == NO)	return;
   ...

    _keyboardShowing = NO;
    ....
}
```

When `[self privateIsEnabled]` return NO, the `_keyboardShowing` will not be set to NO!

**Comment by hackiftekhar** [comment]
Correct, this should be fix.

**Comment by Whirlwind** [comment]
Could you fix it?

**Comment by hackiftekhar** [comment]
@Whirlwind Can you make a Pull-Request with the fix?

**Comment by Whirlwind** [comment]
#725

**Comment by hackiftekhar** [comment]
I think there are some conditions in library which depends on this variable, so if we move this from will hide to dud hide method then thus may have some side effect.

**Comment by Whirlwind** [comment]
I think that the variable has small effect from will hide move did hide. And the bug should be fixed.

**Comment by hackiftekhar** [comment]
I'll check how it may effect the logic.

**Comment by hackiftekhar** [comment]
Fixed manually
