### ISSUE TITLE
Bottom TextViewCell jumps if resizing using autolayout 

### ISSUE THREAD

**Issue by zeiteisen** [hackiftekhar/IQKeyboardManager#722]
![ezgif com-optimize](https://cloud.githubusercontent.com/assets/861496/20977827/0342cf62-bca7-11e6-8c22-f15a699031f9.gif)

This happens if a TextView is inside a TableViewCell at the bottom of a TableView and the TextView resizes with 
```
tableView.beginUpdates()
tableView.endUpdates()
```

**Comment by zeiteisen** [comment]
I made a sample project 
[keyboard.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/637305/keyboard.zip)

**Comment by hackiftekhar** [comment]
Ok, I'll check.

**Comment by hackiftekhar** [comment]
I checked sample project and tested with iPhone SE iOS10.2 Simulator using Xcode 8.2 but the issue isn't reproducible. Could you please confirm if issue is reproducible with the attached sample project? If YES then could you please let me know your configuration?

**Comment by zeiteisen** [comment]
You can reproduced on a iOS 10.0 or iOS 9.3 simulator with the sample project

**Comment by hackiftekhar** [comment]
I checked and found that tableview trigger setContextOffset on end updates, so this must be iOS side issue and not by library.
