### ISSUE TITLE
Moving view when keyboard appears

### ISSUE THREAD

**Issue by Ponf** [hackiftekhar/IQKeyboardManager#724]
Hello, my screen is very similar to this example: 
[Working with chat screen](https://github.com/hackiftekhar/IQKeyboardManager/blob/master/MANUAL%20MANAGEMENT.md#working-with-chat-screen-uitableview), but instead of uitextfield in the bottom I have custom UIView. I want to have same appearance: 
- view is always visible
- view scrolls up with keyboard

I have attached bottom constraint to `IQLayoutGuideConstraint`, but view doesn't scrolls up. I think the problem is that my UITextView which I'm tapping is inside UITableView.

How can I move my custom view with keyboard?

**Comment by hackiftekhar** [comment]
In this case make sure you pinned your view with bottom layout guide and not from superView and connect that constraint with IQLayoutGuideConstraint, I believe it should work.

**Comment by Ponf** [comment]
@hackiftekhar I have made everything exactly like in example, so autolayout is pinned to bottom layout guide and it's connected to `IQLayoutGuideConstraint`. 

I think this logic doesn't work because my firstResponder is outside of attached view.

**Comment by hackiftekhar** [comment]
That may be the case because library isn't aware of each and every case and can only handle general cases like most of the users have. However if you made it exactly like example then it should work.
