### ISSUE TITLE
tableView scrol con`t end Keyboard

### ISSUE THREAD

**Issue by XHJiang** [hackiftekhar/IQKeyboardManager#726]
From April , if a textView on a tableViewcell, it can not end the keyboard when I scrol the tableView.
But in Mar, It work,Please

**Comment by hackiftekhar** [comment]
Not understand

**Comment by XHJiang** [comment]
A textView in a tableViewCell, zhe keyboard show,I scrol zhe tableView,zhe keyboard con not dismiss
