### ISSUE TITLE
Trying to change Toolbar Manage Behavior Setting in Swift Demo cause crash

### ISSUE THREAD

**Issue by mrfonda** [hackiftekhar/IQKeyboardManager#727]
I didn't try to investigate what exactly cause the crash. I attached a screen recording that showing the issue. 
[crash.mov.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/643641/crash.mov.zip)

**Comment by hackiftekhar** [comment]
Do you have any crash logs?
