### ISSUE TITLE
Bug : when no scrollview , the navBar will move up .

### ISSUE THREAD

**Issue by Allennes** [hackiftekhar/IQKeyboardManager#728]
Bug : when no scrollview,the navBar will move up .

I think here have some problems ，This should return a UIViewController, but not.
```
while (matchController != nil && [controllersHierarchy containsObject:matchController] == NO)
    {
        do
        {
            matchController = [matchController nextResponder];
            
        } while (matchController != nil && [matchController isKindOfClass:[UIViewController class]] == NO);
    }

```

and  the style "!= nil   and   == NO" is bad.

**Comment by RangerZz** [comment]
I have the same problem. According to the Reveal display，The UILayoutContainerView move up with its subviews.

**Comment by hackiftekhar** [comment]
So what may be the solution? Can someone explain a solution technically?

**Comment by liuxu0718** [comment]
i have the same problem.begin input status，and then navigationBar move up so that only display statusBar.... when end editing，navigationBar normal.

**Comment by hackiftekhar** [comment]
It's expected that the main UIView move up, if we try to not move navigation bar then it would be very tricky.
