### ISSUE TITLE
IQKeyboardManager how to registe DTRichTextEditorView

### ISSUE THREAD

**Issue by kakukeme** [hackiftekhar/IQKeyboardManager#730]

**Comment by hackiftekhar** [comment]
You can try these methods:

-(void)registerTextFieldViewClass:(nonnull Class)aClass
  didBeginEditingNotificationName:(nonnull NSString *)didBeginEditingNotificationName
    didEndEditingNotificationName:(nonnull NSString *)didEndEditingNotificationName;

But still I'm not sure if this can work.
