### ISSUE TITLE
Can not click the done button on the keyboard after click the up or down button.

### ISSUE THREAD

**Issue by liaodalin19903** [hackiftekhar/IQKeyboardManager#732]
<img width="253" alt="c117379b-10f0-4344-b879-e90f2c12a4f2" src="https://cloud.githubusercontent.com/assets/12727582/21217426/1d5b3358-c2e7-11e6-86ef-acdca10d05e1.png">

The picture is 

My project is mixed by `oc` and `swift` .
the IQKeyboardManager version is : 

In the `podfile`:

    pod 'IQKeyboardManager', '~>  4.0.6'
    pod 'IQKeyboardManagerSwift', '~> 4.0.7'

Question:

 1)  Could I hide the `up` and `down` button in my code ?   
 2) In the  iPhone `5`, the `down` and `up` button will not show, because it is out of the screen.

**Comment by hackiftekhar** [comment]
First of all, use only one version. Secondly please check if your shouldBeginEditing delegate return NO or anything which may prevent stopping done button to resign.

**Comment by liaodalin19903** [comment]
@hackiftekhar Hi,bro, could I hide the `up` and `down` button in my code? if yes, how to do with that?

**Comment by hackiftekhar** [comment]
If you are using v4.0.7 then set `shouldHidePreviousNext` to `YES`
If you are using the master branch code then change `previousNextDisplayMode` to `IQPreviousNextDisplayModeAlwaysHide`

**Comment by liaodalin19903** [comment]
@hackiftekhar I am sure I  did not set  `shouldBeginEditing`, I searched the `.swift` with `shouldBeginEditing `, found nothing.

**Comment by hackiftekhar** [comment]
You searched incorrect text.
