### ISSUE TITLE
Textfield Placeholder is misplaced

### ISSUE THREAD

**Issue by SriramKrishnan8** [hackiftekhar/IQKeyboardManager#733]
The placeholder text in the textfield moves a bit towards the left on tapping the textfield. I didn't modify any code but kept the textfield's alignment as centre. On tapping the textfield, the text is moved 3 or 4 spaces to the left along with the cursor. On dismissing the keyboard, the typed text/placeholder comes back to the centre position.

**Comment by hackiftekhar** [comment]
I think it's the internal but since linrary doesn't change any UI of internal placeholder of UItextField.
