### ISSUE TITLE
keyboardDistanceFromTextField not working in Swift 3 (with UITextField in UITableViewCell)

### ISSUE THREAD

**Issue by timothybrandspencer** [hackiftekhar/IQKeyboardManager#734]
Any help appreciated..

My view structure is:

UIViewController
    -> UIView (container view)
        -> UITableView
    -> UIButton

In my UITableViewCell I have a text field with keyboardDistanceFromTextField set to 180 but for some reason it has no affect.

Setting keyboardDistanceFromTextField globally in AppDelegate has no affect either: IQKeyboardManager.shared().keyboardDistanceFromTextField

Given it doesn't work globally either, is there something I am not doing to enable this behaviour?

The basic behaviour for keyboard avoidance seems to be working across my app, so it's just this setting which has no affect.

**Comment by hackiftekhar** [comment]
Could you ease confirm if you are using UITableViewController?

**Comment by timothybrandspencer** [comment]
Yes, the table view is a UITableViewController.

**Comment by hackiftekhar** [comment]
UITableViewController has it's own default behaviour for managing textField and keyboard, so library ignore managing distance in case of UITableViewController and respect it's own default handling.

**Comment by timothybrandspencer** [comment]
Thanks very much! Changing to a plain old UITableView fixed the issue (luckily I didn't really need the UITableViewController).
