### ISSUE TITLE
Unrecognized selector sent to instance 

### ISSUE THREAD

**Issue by eestein** [hackiftekhar/IQKeyboardManager#735]
Hi, it was working fine until I updated to the new Xcode 8.2 and iOS 10.2. I'm really not sure it's related to that, but only after that it started to happen. I read #104, #578 and #717 but since no answer was provided there I decided to post here. Please let me know if there's a way to continue using the component... I really don't want to stop using it. But if I leave it enabled it breaks all the other text components. Whenever I click on any other text component the app crashes.

This is the error:

`2016-12-15 22:33:10.265 ClaimsMobileiPhone[699:134807] -[UITextField _IQDescription]: unrecognized selector sent to instance 0x10565aab0`

**Comment by hackiftekhar** [comment]
Make sure you added IQUIView+Hierarchy.m in your target.

**Comment by eestein** [comment]
@hackiftekhar Hi and thanks for this pretty cool lib :) I'm using an adaptation of your lib for Xamarin.iOS. And as I said it was working before iOS 10.2. Would you mind expanding on that? I might try to create my own bindings, but it's better if I understand what you mean by that. Thanks.

**Comment by hackiftekhar** [comment]
@eestein the method **_IQDescription** is written in that file I mentioned earlier, so I guess the above file is not added to your target. Thus simply means it's not included in you compile files list, that's why app cannot find that method at runtime and app gets a crash due to unrecognized method.

**Comment by eestein** [comment]
@hackiftekhar sorry about the huge delay. I still haven't figured out this one yet. Would you know why did it stop working after 10.2? The same library was working before. Thanks!

**Comment by hackiftekhar** [comment]
@eestein could you please let me know what you have tried till now?

**Comment by eestein** [comment]
@hackiftekhar as I said I was using a bindings library for Xamarin.iOS. But it's all good now, I'm going to create my own implementation of this behavior to avoid issues. Thank you for your time!

**Comment by sumit-unikove** [comment]
App crashing on launch, i Just added the files only.
-[IQKeyboardManager deepResponderViews]: unrecognized selector sent to instance 0x7fb7dc5022c0

**Comment by sumit-chauhan** [comment]
Same issue
