### ISSUE TITLE
 isScrollEnabled = false 影响判断,导致superView取值失败

### ISSUE THREAD

**Issue by gushenmeiying** [hackiftekhar/IQKeyboardManager#736]
`//set isScrollEnabled = false 影响判断,导致superView取值失败

override func viewDidLoad()
 {
        super.viewDidLoad()
        //supper scrollView
        let scrollView = UIScrollView(frame: CGRect(x: 0, y: 0, width: screenWidth, height: screenHeight))
        scrollView.backgroundColor = UIColor.red
        scrollView.contentSize = CGSize(width: 0, height: screenHeight * 2)
        view.addSubview(scrollView)
        
        //middle scrollView
        let scroll1 = UIScrollView(frame: CGRect(x: 0, y: 0, width: screenWidth, height: screenHeight))
        scroll1.backgroundColor = UIColor.yellow
        scroll1.contentSize = CGSize(width: 0, height: screenHeight * 2)
        scroll1.isPagingEnabled = true
        scrollView.addSubview(scroll1)

        //tableView
        let table = UITableView(frame: CGRect(x: CGFloat(0) * screenWidth, y: 0, width: screenWidth, height: scrollView.height), style: .plain)
        table.dataSource = self
        table.delegate = self
        
        //set isScrollEnabled = false 影响判断,导致superView取值失败
        /**
         
         while (superView)
         {
            if (superView.isScrollEnabled)
            {
                superScrollView = superView;
                break;
            }
            else
            {
                //  Getting it's superScrollView.   //  (Enhancement ID: #21, #24)
                superView = (UIScrollView*)[superView superviewOfClassType:[UIScrollView class]];
            }
         }
         
         */
        table.isScrollEnabled = false
        scroll1.addSubview(table)
        table.backgroundColor = UIColor.blue
    }`

**Comment by hackiftekhar** [comment]
@gushenmeiying Where is your textField in the demo code @gushenmeiying?
