### ISSUE TITLE
How to change Title of right button in accessoryView?

### ISSUE THREAD

**Issue by NikKovIos** [hackiftekhar/IQKeyboardManager#738]
In viewDidLoad i use    
`textField.addRightButtonOnKeyboardWithText("My text", target: self, action: #selector(action))`

but when i touch textField - `addRightButtonOnKeyboardWithText` method called again and button setted title from ` IQKeyboardManager.sharedManager().toolbarDoneBarButtonItemText = "WrongTitle"`

How can i make the unique title for right button in accessoryView above textField for only current textField?

**Comment by hackiftekhar** [comment]
I think if you are adding accessoryView using `addRightButton....` then library shouldn't change the title. Could you please provide a demo project demonstrating the issue? So that I can check?

**Comment by NikKovIos** [comment]
I can't share code, but there is a queue how it called.
![2016-12-19 15 21 36](https://cloud.githubusercontent.com/assets/16647690/21312728/e3682834-c5fe-11e6-9574-48806b64eb91.png)

**Comment by hackiftekhar** [comment]
I'm asking for a demo app and not your actual source code.

**Comment by hackiftekhar** [comment]
@NikKovIos I checked it with my ManualToolbarViewController demo, and it's working fine there and I didn't found any issues.
