### ISSUE TITLE
iOS 10 Severe Distortion

### ISSUE THREAD

**Issue by vbresults** [hackiftekhar/IQKeyboardManager#740]
In iOS 10, if the screen locks while the IQKeyboardManager is open, and then the device is unlocked, the layout is severely distorted by IQKeyboardManager.

Haven't tried on iOS 8/9 so I'm not sure it's iOS-10 specific or not

**Comment by hackiftekhar** [comment]
Ha you pinned any top layout or bottom layout constraint?

**Comment by vbresults** [comment]
Not to my knowledge, but my layout engine may do it

**Comment by hackiftekhar** [comment]
I checked and it's working fine for me. You could check if you pinned top/bottom layout guide directly or indirectly to text field.
