### ISSUE TITLE
Sometimes the IQKeyboardManager's keyboard placeholder is incorrect

### ISSUE THREAD

**Issue by liaodalin19903** [hackiftekhar/IQKeyboardManager#741]
I am using : 

    pod 'IQKeyboardManagerSwift', '~> 4.0.7'

In the `Appdelegate.swift`: 

    IQKeyboardManager.shared().isEnabled = true
    IQKeyboardManager.shared().shouldHidePreviousNext = true

The issue is, the keyboard's placeholder is not correct, sometimes:

![3db93c2d65c504873c7983dd9d00bf3a](https://cloud.githubusercontent.com/assets/12727582/21492238/d96d752e-cc3d-11e6-9cd8-ba662c87647a.png)
![4f18e244a174fba34bb617a268b5d7fb](https://cloud.githubusercontent.com/assets/12727582/21492240/d9cc2df8-cc3d-11e6-9589-20ee61b37c97.png)
![6714bff461cf47da2f0a8a389bdc6c7b](https://cloud.githubusercontent.com/assets/12727582/21492239/d9cad6ba-cc3d-11e6-8c6a-9fa807b3e45e.png)

Where is the issue? Or, could we hide the keyboard's placeholder ?

**Comment by hackiftekhar** [comment]
You can hide keyboard placeholder, there is a property to do so, however if you could share a demo project demonstrating the issue then it would be great to debug this issue.

**Comment by liaodalin19903** [comment]
@hackiftekhar ， thanks, could leave your email ？

**Comment by hackiftekhar** [comment]
You can also upload here and other people can also try to figure out. Make sure you didn't upload any of your private content. It should be just a demo project.

**Comment by liaodalin19903** [comment]
I have sent your email.

**Comment by hackiftekhar** [comment]
@liaodalin19903 If you could upload a demo project here then it would be great, please reopen the issue when you upload the demo.
