### ISSUE TITLE
setting IQKeyboardReturnKeyHandler not work in UITableView

### ISSUE THREAD

**Issue by peakerWu** [hackiftekhar/IQKeyboardManager#742]
I dont know when setting this code  in 'TableViewInContainerViewController.m' (you demo) 
- (void)viewDidLoad
{
    [super viewDidLoad];
    
    handler = [[IQKeyboardReturnKeyHandler alloc] initWithViewController:self];
    handler.lastTextFieldReturnKeyType = UIReturnKeyDone;
    
}
- (void)dealloc
{
    handler = nil;
}
 the Return dont become Next in Keyboard， Thank you.

**Comment by hackiftekhar** [comment]
I checked my 'NavigationBarViewController' demo and it's working fine there. Using return key handler only work with static fields, if any textfield added after initializing then it should be added manually using **addTextFieldView:** method.
