### ISSUE TITLE
How can i hide the up and down arrow

### ISSUE THREAD

**Issue by pprevalon** [hackiftekhar/IQKeyboardManager#743]
How can i hide the up and down arrow

**Comment by m1ch14l** [comment]
In Appdelegate.swift:

`IQKeyboardManager.shared().shouldHidePreviousNext = true`

**Comment by birbay** [comment]
IQKeyboardManager.shared().previousNextDisplayMode = .alwaysHide

**Comment by Mohd-Maruf** [comment]
How can I hide the ups and down button on any specific Controller only.

**Comment by hackiftekhar** [comment]
Currently the is no way @Mohd-Maruf.
