### ISSUE TITLE
Misplaced when In-Call Status Bar is Active  

### ISSUE THREAD

**Issue by MohamedAbden** [hackiftekhar/IQKeyboardManager#744]
Before open keyboard : 
<img width="487" alt="screen shot 2017-01-02 at 11 51 55 am" src="https://cloud.githubusercontent.com/assets/24872609/21586509/ea53e7fc-d0e2-11e6-8b46-e6b62054690b.png">

When keyboard is Active : (view is moved down even for the first TextField) :
<img width="487" alt="screen shot 2017-01-02 at 11 52 09 am" src="https://cloud.githubusercontent.com/assets/24872609/21586544/58bc7ff6-d0e3-11e6-8ede-eaed72beb036.png">

After dismiss keyboard : (View still moved down)
<img width="487" alt="screen shot 2017-01-02 at 11 52 13 am" src="https://cloud.githubusercontent.com/assets/24872609/21586552/6c7ab062-d0e3-11e6-9592-3643beab00c4.png">

Any help ?

**Comment by hackiftekhar** [comment]
@MohamedAbden Can you please provide demo project because all works fine with my demo app.

**Comment by Magnat12** [comment]
Setting `shouldFixInteractivePopGestureRecognizer` to **NO** helps me to resolve this problem
`[IQKeyboardManager sharedManager].shouldFixInteractivePopGestureRecognizer = NO;`
