### ISSUE TITLE
interactivePopGestureRecognizer question

### ISSUE THREAD

**Issue by sany620** [hackiftekhar/IQKeyboardManager#745]
Can appear when used after push interactivePopGestureRecognizer return this problem, how to solve? IQKeyboardManager (3.3.7)
![123567](https://cloud.githubusercontent.com/assets/5379144/21591519/eab70780-d13f-11e6-9df8-95fd6cf94417.png)

**Comment by hackiftekhar** [comment]
@sany620 This is fixed with #464 in v4.0.4
