### ISSUE TITLE
contentview will more height when show keyboard.

### ISSUE THREAD

**Issue by tospery** [hackiftekhar/IQKeyboardManager#746]
Hi hack,
   In the Test, when hide keyboard, you can scroll the contentview up/down freedom. But, when show keyboard, the contentview will have more height. How can fixed this issue, thanks.
[Test.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/681576/Test.zip)

**Comment by hackiftekhar** [comment]
@tospery I checked it and it's working as expected. The contentView height is same all and user can scroll see all the content by scrolling.
