### ISSUE TITLE
Request: Can I add a textview on the keyboard toolbar itself?

### ISSUE THREAD

**Issue by pardypanda** [hackiftekhar/IQKeyboardManager#748]
Hi,

Can I add a textview and a send button on the keyboard toolbar itself? If yes, how do I manage it?

I have a chat app where the text input needs to happen on the keyboard toolbar itself and then clicking on "Send" on the toolbar should send the message. I'm using JSQMessagesViewController for the chat UI

**Comment by hackiftekhar** [comment]
@pardypanda I would suggest you to disable IQKeyboardManager when using JSQMessageViewController because IQKeyboardManager doesn't work well with chat UI.
