### ISSUE TITLE
Set cell position back to where it was on keyboard dismiss

### ISSUE THREAD

**Issue by pardypanda** [hackiftekhar/IQKeyboardManager#749]
Hi, 

IQKeyboard works really well. I have a table view where each cell has a textview for input.

Right now, clicking on any textview on any cell does bring it up or pull it down to above the keyboard when keyboard is shown. This behaviour is correct and works really well. 

However, on keyboardWillBeHidden, I want to set the cell position back to what it was before keyboard was shown. How to do that?

**Comment by pardypanda** [comment]
Hi @hackiftekhar,

Can you please help me on this one?

Thanks.

**Comment by hackiftekhar** [comment]
@pardypanda There is a UIScrollView category and have a property `shouldRestoreScrollViewContentOffset` just set it to YES on your UITableView object.

**Comment by pardypanda** [comment]
Perfect! 

Thanks (y)
