### ISSUE TITLE
in webview  toolbar  can not hide

### ISSUE THREAD

**Issue by Sunny-guangge** [hackiftekhar/IQKeyboardManager#750]
[IQKeyboardManager sharedManager].enable = NO;
    [IQKeyboardManager sharedManager].enableAutoToolbar = NO;
 set like this

**Comment by hackiftekhar** [comment]
@Sunny-guangge WebView doesn't have native UITextField/UITextView and in webView their are html controls, it does have their own mechanism to handle html textfields and library does have no control over there.

**Comment by iexercise** [comment]
I have encountered such a problem, the first load will appear layout problems, html TextField was hide by toolbar

**Comment by hackiftekhar** [comment]
The library doesn't effect any toolbars with WebViews since they are not UITextField. It's handled by webview itself.

**Comment by iexercise** [comment]
But in the webview page of the inputview this library file into effect,I tried in the demo I used the wkwebview

**Comment by iexercise** [comment]
Open the google home page and enter the toolbar where the library file will appear

**Comment by luotengotos** [comment]
@iexercise   Excuse me, have you solved this problem? I met this problem, too. 
and, print too many  error message about constraint config.

<NSAutoresizingMaskLayoutConstraint:0x13bbd0860 _UIToolbarContentView:0x137dea5b0.width == UIToolbar:0x13b95dda0.width>,
	<NSLayoutConstraint:0x13b968f40 _UIButtonBarStackView:0x13b9627f0.leading == _UIToolbarContentView:0x137dea5b0.leading + 8>,
	<NSLayoutConstraint:0x13b969090 _UIButtonBarStackView:0x13b9627f0.trailing == _UIToolbarContentView:0x137dea5b0.trailing>

**Comment by hackiftekhar** [comment]
The library doesn't and cant' handle WebView textFields since they aren't UITextField or UITextView but they are webview objects.
