### ISSUE TITLE
Does not scroll when clicking on textfield that will be behind keyboard

### ISSUE THREAD

**Issue by CyberMew** [hackiftekhar/IQKeyboardManager#751]
This is how it looks like at the start:![screen shot 2017-01-09 at 6 08 41 pm](https://cloud.githubusercontent.com/assets/4715911/21763043/d201aaae-d696-11e6-8ffa-21c7abd2713c.png)

If I click on the 1st textfield and press tab/arrow next then it works:![screen shot 2017-01-09 at 6 08 58 pm](https://cloud.githubusercontent.com/assets/4715911/21763060/e52c4c2e-d696-11e6-8560-7d7c29d4ea6c.png)

If I click on the 3rd textfield, it doesn't care for some reason: 
![screen shot 2017-01-09 at 6 09 07 pm](https://cloud.githubusercontent.com/assets/4715911/21763083/027335b8-d697-11e6-9d59-e4cfd4b85902.png)

Any idea why? The only thing I did was I made the `UIView` a `UIScrollView` instead, so that the whole `UINavigationController` doesn't scroll up. So this is the format:
Topmost `UIView` -> `UIView` -> `UIScrollView` -> `UITextFields`

I have not tested it on Simulator iOS 10 or on an actual device yet, though I expect them to behave the same.

**Comment by viral105** [comment]
I am having similar problem.
My text field inside the uicollectionview and class is presented modally with form sheet presentation.

Whenever I am pressing last text field of view, this text field shows behind the key board and not able to scroll to see that text field.

If I press next or previous button scroll till last text field is working fine.

I am using pod 'IQKeyboardManagerSwift', ‘4.0.0’

**Comment by hackiftekhar** [comment]
@CyberMew Make sure your scrollView does have correct autolayout constraint to calculate it's contentSize

**Comment by CyberMew** [comment]
The whole layout has autolayout applied and there wasn't any errors in the storyboard. I will double check again when I have time! Maybe @viral105 can verify in the meantime too

**Comment by hackiftekhar** [comment]
Please check in viewDidAppear that what contentOffset property of your ScrollView does have.

**Comment by viral105** [comment]
@hackiftekhar I have double checked my view and its constraints its ok. No issue with that.
Also I didn't written viewDidAppear in my VC and in all class i didn't set contentOffSet property.

**Comment by hackiftekhar** [comment]
ohh, very sorry @viral105 I mean contentSize, my bad.

**Comment by viral105** [comment]
`override func prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?) {
        if segue.identifier == "MyVC" {
            let obj: MyVC = segue.destinationViewController as! MyVC
            obj.preferredContentSize = CGSizeMake(900, 650)
        }
    }`

This is what i have written in view controller from where I am presenting MyVC.

**Comment by viral105** [comment]
Also one more thing I have notice that, problem occurs only if presenting vc. When you push vc in that case it is working properly for me.

**Comment by hackiftekhar** [comment]
I'm asking to set **contentSize** of **UIScrollView**, not **preferredContentSize**.

**Comment by viral105** [comment]
My All textfields inside the uicollectionview. Not in uiscrollview.

**Comment by hackiftekhar** [comment]
@viral105 Do you have any special configuration? Have you checked collection view demo on the demo project?

**Comment by viral105** [comment]
@hackiftekhar As a special configuration i can say that my presentation style is "Form Sheet" if it is "Default" then no issues. Yes, I checked collection view demo.

**Comment by hackiftekhar** [comment]
@viral105 Can you provide the demo project since I'm unable to reproduce the issue?

**Comment by viral105** [comment]
@hackiftekhar I fond the problem.
`override func viewDidLayoutSubviews(){
        self.mycollectionviewobj.collectionViewLayout.invalidateLayout()
    }`
This lines of code are causing the problem.
Commenting this line "IQKeyboardManagerSwift" working fine for me in form sheet presentation style.

**Comment by hackiftekhar** [comment]
Thank You! 👍

**Comment by CyberMew** [comment]
Sorry for the delay, I was busy with other stuffs. I manage to create sample project with this problem. Please let me know what is wrong and what I can do to fix it.
[keyboardbug.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/753897/keyboardbug.zip)

**Comment by CyberMew** [comment]
Any theories so far as to why it isn't working? Let me know if the sample project is not clear enough to illustrate the problem and I'll see what I can do.

**Comment by hackiftekhar** [comment]
@cybermew, sorry I'm too busy these days, but will check your demo when I get some time.

**Comment by CyberMew** [comment]
No problem. That would be great. Appreciate it.

**Comment by CyberMew** [comment]
Hey @hackiftekhar how are you these days? Still busy?

**Comment by hackiftekhar** [comment]
Hello @CyberMew I checked the project and I found that it's because you changed UIView class to UIScrollView. If you need scrollView then drag and drop a UIScrollView to storyboard (don't change UIView class to UIScrollView).

The thing is that your scrollView doesn't have correct contentSize and you are not getting any layout errors in storyboard because storyboard considering that view as UIView and it was ok for UIView, but for UIScrollView the constraints are wrong.

Hope you'll fix it soon.
