### ISSUE TITLE
Incompatible with third party typewriting

### ISSUE THREAD

**Issue by fisland** [hackiftekhar/IQKeyboardManager#752]
Hi,
IQkeyboard is very good, but after iOS10, it had a bug that it was incompatible with third party typewriting. 
when the third party typewriting keyboard appear, the keyboard  height isn't right, and sometime it will switch to iOS keyboard

**Comment by hackiftekhar** [comment]
The library extract keyboard height from keyboard notifications, so it's dynamic and doesnt' have any issues with any height third party keyboard. If there is any then there might be issue with the third party keyboard or iOS.
