### ISSUE TITLE
Toolbar's size is extended and become very long after removing and readding all window's subview

### ISSUE THREAD

**Issue by csooi** [hackiftekhar/IQKeyboardManager#753]
Hi, 

I encounter a problem here. I used the following codes to update my UI components once my theme color changes. However, whenever I used this following codes to remove my window's subviews and add them back subsequently, my toolbar seems to extended it's length once I let any textfield becomefirstresponder. I can't reach my "Done" button anymore.

```
for (UIWindow *window in [UIApplication sharedApplication].windows) {
        for (UIView *view in window.subviews) {
                [view removeFromSuperview];
                [window addSubview:view];
            
        }
    }
```

![simulator screen shot 13 jan 2017 6 38 51 pm](https://cloud.githubusercontent.com/assets/8664497/21927388/86cbaec2-d9c0-11e6-9ad2-f5be14f94e1d.png)

I always have to dismiss this input view (picker) first and then open up this input view again to have it returned back to the normal size.

![simulator screen shot 13 jan 2017 6 39 03 pm](https://cloud.githubusercontent.com/assets/8664497/21927389/86cbd334-d9c0-11e6-864f-fa88f66ec0db.png)

Is there advice about this or is there anything can I do to reload the toolbar to prevent this happen?

**Comment by hackiftekhar** [comment]
@csooi Please share a demo project so that I can look into it.

**Comment by csooi** [comment]
@hackiftekhar Thanks for the quick reply. I just created a new demo project to address this problem. You can find it from https://github.com/csooi/DemoIQToolbarProblemWithThemeChanged

Thanks a lot!

**Comment by hackiftekhar** [comment]
Thanks @csooi, I'll check when get some free time.

**Comment by hackiftekhar** [comment]
@csooi I checked the demo and found that the iOS internally changing the toolbar frame and library does nothing in this case. So this looks to be iOS side issues and not by the library.
