### ISSUE TITLE
Does not work on presentViewController

### ISSUE THREAD

**Issue by pprevalon** [hackiftekhar/IQKeyboardManager#755]
I present a viewControler modally, for some odd reason the keyboard manager only move the previous view controller not the new viewController that was presented modally. how can this be fixed. Thank you in advance

**Comment by hackiftekhar** [comment]
Can you please provide tge democode because it works in all hierarchy configuration, not sure what maybe the issue with your code.

**Comment by ajithrnayak** [comment]
So, on an iPad, I'm presenting a popover with textfield and button. I'm presenting a view controller over the context when button is tapped.
- make textfield first responder by tapping it.
- Without dismissing keyboard, present another view controller (over the context in my case)
possibly, keyboard resigning and resetting layout affects newly presented view controller.

**Comment by hackiftekhar** [comment]
I'm still a but confise with the configuration that's why I asked you the demo. Btw I can say that there may be some issues with the popover, so if you afe getting any then it needs to be fix.

**Comment by TechLoveVN** [comment]
@hackiftekhar  I am getting same issue, please give me your email, I will send you my source code.
thanks!

**Comment by hackiftekhar** [comment]
@TechLoveVN Can you please attach a demo project here instead of sending source code since we all don't have much time to go through all the project source code?

**Comment by Nododo** [comment]
hi all
i meet the same issue, i solve it by becomeFirstResponder after delay
```
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(0.2 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
        [_phoneField becomeFirstResponder];
    });
```
