### ISSUE TITLE
When with NagaitionBar, topLayoutGuide seems is not correct

### ISSUE THREAD

**Issue by an-ttt** [hackiftekhar/IQKeyboardManager#756]
I set scollView in UIViewController that navigationBar do not go up. After that:

-(void)adjustFrame,
{
...
    CGRect statusBarFrame = [[UIApplication sharedApplication] statusBarFrame];
...
    CGFloat topLayoutGuide = CGRectGetHeight(statusBarFrame);
...
    //  Checking if there is bottomLayoutGuide attached (Bug ID: #250)
    if (layoutGuidePosition == IQLayoutGuidePositionBottom)
    {
        //  Calculating move position.
        move = CGRectGetMaxY(textFieldViewRect)-(CGRectGetHeight(keyWindow.frame)-kbSize.height);
    }
    else
    {
        //  Calculating move position. Common for both normal and special cases.
        move = MIN(CGRectGetMinY(textFieldViewRect)-(topLayoutGuide+5), CGRectGetMaxY(textFieldViewRect)-(CGRectGetHeight(keyWindow.frame)-kbSize.height));
    }
}

The scroll view's contentOffset should contain navigationBar height, but it's not. Pls let me know How to fix it, thanks a lot!
Ps: I use two YYTextView in it and click next will see that the scroll view contentOffset is wrong.

**Comment by hackiftekhar** [comment]
Can you please provide demo project?
