### ISSUE TITLE
textfield in tableview,keyboard display has some error

### ISSUE THREAD

**Issue by DevilMrTank** [hackiftekhar/IQKeyboardManager#759]
A viewcontroller, has a UIView and a UITableView.UIView is above UITableView. UITableView has some UITextField.
When click on UITextField,keyboard show.UITableView's content will scroll some space,but UITableView's position will not change.So the viewcontroller seems so strange。
[screenshot](http://tieba.baidu.com/p/4947298724?pid=102855306408&cid=0#102855306408)

**Comment by hackiftekhar** [comment]
@DevilMrTank Screenshot is missing.
