### ISSUE TITLE
UITextView in UITableViewController not behaving properly

### ISSUE THREAD

**Issue by hardikdevios** [hackiftekhar/IQKeyboardManager#76]
##### when i select UITextView and going to type something it scrolles more than usual on top.

ScreenShot 1:-
![ios simulator screen shot 26-sep-2014 6 37 36 pm](https://cloud.githubusercontent.com/assets/6657591/4420898/6e997c36-457e-11e4-9312-81181546103a.png)

ScreenShot 2:-Red Rectangle
![ios simulator screen shot 26-sep-2014 6 37 43 pm](https://cloud.githubusercontent.com/assets/6657591/4420983/658f6758-457f-11e4-802e-685acc2405ad.png)

> Note:-
> My UITextView Height is 350 and i am running in iOS 7 5s simulator the same issue is in iOS 8.
> This is working Fine if i use UITextView in UIView

**Comment by GauravT9l** [comment]
As per the Apple Doc.  

> Note that UITableViewController automatically resizes and repositions its table view when there is inline editing of text fields. 

They are not talking about Text View . and then there is problem with me as neither apple nor you are managing UItextView in UITableViewController
