### ISSUE TITLE
the tapGesture will conflict with   barHideOnSwipeGestureRecognizer

### ISSUE THREAD

**Issue by tpctt** [hackiftekhar/IQKeyboardManager#761]
PRE: Set      [IQKeyboardManager sharedManager].shouldResignOnTouchOutside = YES;
1. set     self.navigationController.hidesBarsOnSwipe = NO;
2. input with textfield and touch on other area,  the keyboard will hide
3.   set     self.navigationController.hidesBarsOnSwipe = YES;
4. input with textfield and touch on other area,  the keyboard will  not hide ,

**Comment by hackiftekhar** [comment]
I checked and yeah they both conflicts, but it's a very hard thing to create dependency between them.
