### ISSUE TITLE
keyBoardDistanceFromTextField not working

### ISSUE THREAD

**Issue by AtharvaVaidya** [hackiftekhar/IQKeyboardManager#762]
I am setting keyboardDistanceFromTextField like so in App Delegate: 

`
[[IQKeyboardManager sharedManager] setEnable:YES];
[[IQKeyboardManager sharedManager] setKeyboardDistanceFromTextField:100];
`

I have a UITextField and another view in a tableViewCell in a UITableView in a UIViewController. How do I override the distance so that IQKeyboardManager calculates it as the height of the tableViewCell instead of just the textField?

**Comment by hackiftekhar** [comment]
Nope, it's not possible right now because it's a user specific requirement and not a general one and I believe you may have to write some workaround to overcome with this @AtharvaVaidya.
