### ISSUE TITLE
Feature Request: Expose properties to allow theming of keyboards and inputAccessoryView/UIToolbar without forking

### ISSUE THREAD

**Issue by JohnTheBastard** [hackiftekhar/IQKeyboardManager#763]
It would be useful if was possible to configure the IQKeyboardManager to set a color theme for all instances of keyboards, numeric pads, and inputAccessoryViews/UIToolbar. (It would also be great if I could change the font of the letters and numbers on the keys, but I'm not sure Apple allows this.) Here are some mockup examples of the keyboard/numeric pad:  

![keyboards](https://cloud.githubusercontent.com/assets/4441293/22346324/8b61459e-e3b8-11e6-837f-2d9a3044367c.png)  

There are also specific things not currently possible for the inputAccessoryView:  

![pickers](https://cloud.githubusercontent.com/assets/4441293/22346394/c542c1d4-e3b8-11e6-8b14-bf86ccc77647.png)
(these are screenshots, not mockups)

There doesn't seem to be a way to set the opacity of the toolbar without reimplementing it on the textfield. Also, there seems to be no way to specify the color of a button when it's disabled, or the 1pt divider line between the toolbar than the picker. In the screenshot, both are grey, but nothing else in our app is grey. I'd like to be able to set them to light blue and make the background of the toolbar opaque.

**Comment by hackiftekhar** [comment]
I believe it's not possible to change keyboard color with public API's so I don't think we can expose any properties to do the same.
