### ISSUE TITLE
Xcode 8.3 beta compatibility

### ISSUE THREAD

**Issue by Tulleb** [hackiftekhar/IQKeyboardManager#764]
The master branch is presenting issues when compiling with Xcode 8.3 beta.

Maybe because of Swift 3.1 version?

Errors are:
IQUIView+IQKeyboardToolbar.swift:91:47: Cannot assign value of type 'String?!' to type 'String?'
IQUIView+IQKeyboardToolbar.swift:111:34: Cannot convert return expression of type 'String?!' to return type 'String?'
IQUIView+IQKeyboardToolbar.swift:70:47: Cannot assign value of type 'String?!' to type 'String?'

**Comment by hackiftekhar** [comment]
beta versions aren't compatible, library will update when public version will be available for users.

**Comment by Tulleb** [comment]
@hackiftekhar Ok but don't you have a branch / fork to start supporting the incoming versions? 😳

**Comment by hackiftekhar** [comment]
If I'm going to support incoming feature then I'll have to do it everytime, and I'm not sure if I can maintain it all the time. So easiest solution is to don't do it. If developer wants to do it then please fork the repo and add support for the upcoming features. :)

**Comment by Tulleb** [comment]
I understand :)
Thank you for all your work anyway.

**Comment by hackiftekhar** [comment]
@Tulleb However if you would like to make a pull-request with the new features in a new branch, just let me know, I'll create a branch and you can open a pull request to point that branch.

**Comment by Tulleb** [comment]
@hackiftekhar I will if the next beta version still present those errors. I don't want to dive to much as well into those new "String??" and "String?!" types too quick if it gets removed after 😁
