### ISSUE TITLE
if textView.isEditable = false and text is selected Toolbar becomes visible without keyboard

### ISSUE THREAD

**Issue by RolandasRazma** [hackiftekhar/IQKeyboardManager#765]
How to replicate:
textView.isEditable = true
<select text>
view.endEditing(true)
textView.isEditable = false
<select text>

Some info:
This might be iOS 10 bug (didn't tested other versions) as -[IQKeyboardManager keyboardWillShow:] is triggered

po aNotification
NSConcreteNotification {name = UIKeyboardWillShowNotification; userInfo = {
    UIKeyboardAnimationCurveUserInfoKey = 7;
    UIKeyboardAnimationDurationUserInfoKey = "0.25";
    UIKeyboardBoundsUserInfoKey = "NSRect: {{0, 0}, {375, 44}}";
    UIKeyboardCenterBeginUserInfoKey = "NSPoint: {187.5, 689}";
    UIKeyboardCenterEndUserInfoKey = "NSPoint: {187.5, 645}";
    UIKeyboardFrameBeginUserInfoKey = "NSRect: {{0, 667}, {375, 44}}";
    UIKeyboardFrameEndUserInfoKey = "NSRect: {{0, 623}, {375, 44}}";
    UIKeyboardIsLocalUserInfoKey = 1;
}}

![img_4506](https://cloud.githubusercontent.com/assets/1027187/22592052/c0b776ca-ea0f-11e6-97d0-d92d978668e2.PNG)

**Comment by hackiftekhar** [comment]
I think it's the expected behaviour since keyboard notification return this two keys
`UIKeyboardFrameBeginUserInfoKey` = "NSRect: {{0, 667}, {375, 44}}";
UIKeyboardFrameEndUserInfoKey = "NSRect: {{0, 623}, {375, 44}}";
`
and this is why you see the toolbar
