### ISSUE TITLE
Issue with UISearchController

### ISSUE THREAD

**Issue by kientux** [hackiftekhar/IQKeyboardManager#767]
This is a very simple setup of an `UIViewController`:

```swift
class SearchController: UIViewController, UISearchControllerDelegate {

    var tableView: UITableView!
    var searchController: UISearchController!
    
    override func viewDidLoad() {
        super.viewDidLoad()

        // Do any additional setup after loading the view.

        tableView = UITableView(frame: CGRect(x: 0, y: 0, width: 320, height: 480))
        view.addSubview(tableView)

        searchController = UISearchController(searchResultsController: nil)
        searchController.delegate = self
        tableView.tableHeaderView = searchController.searchBar
    }

    func didPresentSearchController(_ searchController: UISearchController) {
        print(tableView.contentInset)
    }
}
```

This is what printed out in the console:

```
UIEdgeInsets(top: 64.0, left: 0.0, bottom: 0.0, right: 0.0)
UIEdgeInsets(top: 108.0, left: 0.0, bottom: 0.0, right: 0.0)
UIEdgeInsets(top: 152.0, left: 0.0, bottom: 0.0, right: 0.0)
UIEdgeInsets(top: 196.0, left: 0.0, bottom: 0.0, right: 0.0)
```

Because each time search controller is presented, top inset of table view is increased, this is the result when dismiss search controller:

![simulator screen shot feb 4 2017 11 45 35 am](https://cloud.githubusercontent.com/assets/4200743/22615808/ae19b148-eacf-11e6-915d-70f4978cf5ce.png)

This won't happen if:

- `automaticallyAdjustsScrollViewInsets = false` OR
- Use `UITableViewController` OR
- `searchController.hidesNavigationBarDuringPresentation = false` OR
- Disable `IQKeyboardManager`

Currently I can fix this by reset `contentInset`:

```
func didPresentSearchController(_ searchController: UISearchController) {
        print(tableView.contentInset)
        tableView.contentInset = UIEdgeInsets(top: topLayoutGuide.length,
                                              left: 0,
                                              bottom: bottomLayoutGuide.length,
                                              right: 0)
}
```

but that's mean `automaticallyAdjustsScrollViewInsets` is useless.

**Comment by hasanmainul** [comment]
@kientux 
Did you try your workaround with a scoped searchBar? 

Didn't work for me. I had to disable `IQKeyboardManager`

FYI, I meant this
```
func didPresentSearchController(_ searchController: UISearchController) {
        print(tableView.contentInset)
        tableView.contentInset = UIEdgeInsets(top: topLayoutGuide.length,
                                              left: 0,
                                              bottom: bottomLayoutGuide.length,
                                              right: 0)
}
```

**Comment by kientux** [comment]
@hasanmainul I don't understand. Are you having the same problem? Currently I placed the search bar on navigation bar so I don't have this problem, but it's just a issue report. That block of code is what I've done to (temporary) fix this. I don't use a scoped search bar.

**Comment by hasanmainul** [comment]
@kientux I have the same problem. `tableView.contentInset` giving me unexpected result.
I've tried your temporary fix which didn't work for me when I used it with scoped search.

**Comment by Dingo203** [comment]
I also have the same problem, and I config the tableView.contentInset when begin active search to fix this problem, but it will present a flop animation which I don't expect.

**Comment by hackiftekhar** [comment]
With the new logic implementation, I'm not able to reproduce this issue. Please take a look.
