### ISSUE TITLE
Control "Tab key" same as while Next Previous

### ISSUE THREAD

**Issue by Nirav08** [hackiftekhar/IQKeyboardManager#771]
How can I defined order while Tab key is press to move next textfield?

 func textFieldShouldBeginEditing(textField: UITextField) -> Bool {
        
        if (textField == txtCustom) {
            if(textField.isAskingCanBecomeFirstResponder == false) {
                let alertController = UIAlertController(title: "IQKeyboardManager", message: "Do your custom work here", preferredStyle: .Alert)
                alertController.addAction(UIAlertAction(title: "OK", style: .Cancel, handler: nil))
                self.presentViewController(alertController, animated: true, completion: nil)
                //self.present(alertController, animated: true, completion: nil)
            }
            
            return false
        } else {
            return true
        }
    }

**This will present Alert everytime you press Tab key.**

**Comment by hackiftekhar** [comment]
Tab key work differently than normal sofware keyboard and we cannot handle it directly. You must return Yes/No only from method. For workaround you can add tap gesture or any other touch event to your text field to get callback.
