### ISSUE TITLE
Remove custom done button action?

### ISSUE THREAD

**Issue by mathiarasan24** [hackiftekhar/IQKeyboardManager#773]
Hi,

I am using `UITableViewCell` with `UITextField`. Add and remove text field based on few condition. Some text field input view as `UIDatePicker` or `UIPickerView`. For these kind of picker view only I need [custom done button action](https://github.com/hackiftekhar/IQKeyboardManager/blob/master/MANUAL%20MANAGEMENT.md#get-notified-when-tapping-on-previousnextdone-button-for-specific-uitextfielduitextview) other text fields like numeric and email etc., I don't need that custom button action. Table view reuse text field so those done button action keep follow other text fields which doesn't have input view.

I am using this to remove.
`[TextField setCustomDoneTarget:nil action:@selector(doneAction:)];`
Is any other way to remove that? like we do for `NSNotificationCenter` `removeObserve`?

**Comment by hackiftekhar** [comment]
You are doing correct to remove done actions, however you also get callback with textFieldDidEndEditing so why you need this custom done button action?

**Comment by mathiarasan24** [comment]
For `UIDatePickerView` and `UIPickerView`. User doesn't change anything in picker view and select done button it's should fill current selected picker index into `UITextfield`.

**Comment by hackiftekhar** [comment]
@mathiarasan24 if user doesn't change anything and press done, then library work is to dismiss the keyboard (input view) only, you'll have to write logic for selecting currently selected text to textfield.

**Comment by mathiarasan24** [comment]
Yes, I did that (logic). Those method only for picker only not for number and text keyboard. That's why I need some clarification for that is that correct method or did I miss anything.
