### ISSUE TITLE
Split storyboard demo in multiple storyboards

### ISSUE THREAD

**Issue by tbaranes** [hackiftekhar/IQKeyboardManager#777]
`IQKeyboardManager`'s `Main.storyboard` makes literally freeze my MBP 😬
Once that storyboard opened, I have no choice than remove `IQKeyboardManager` to make sure that Xcode won't reopen it.

Since iOS9 we can use storyboard reference, it should be an easy task and great improvement to use your demo!

If I could, I would have made a PR, but... that's not possible 👎

**Comment by hackiftekhar** [comment]
@tbaranes I observed that the issue with storyboard start happening with Xcode8, it was working fine with Xcode7. I need some time to move controller's to different storyboards.

**Comment by hackiftekhar** [comment]
storyboard updated @tbaranes
