### ISSUE TITLE
Issue when textfield is embedded in UIStackView which is embedded in ContainerView

### ISSUE THREAD

**Issue by tbaranes** [hackiftekhar/IQKeyboardManager#778]
Thanks for that great framework! It solves me in a lot of project.

I'm struggling with that context, not sure if that's a bug or a bad usage from me. Here the structure:
UIViewController -> ContainerView -> (child)UIViewController -> UIStackView (with top constraints) ->  a few UITextFields.
(where "->" means embed in)

Also, the `UIStackView` superview (main view of the `UIViewController`) is an `UIScrollView` as explained in the [manual management](https://github.com/hackiftekhar/IQKeyboardManager/blob/master/MANUAL%20MANAGEMENT.md#keep-uinavigationbar-at-the-top-dont-scroll-with-keyboard)

Any idea what am I missing? 

You will find below a storyboard example to reproduce my case. You can use it by replacing the current `Main.storyboard` in the swift demo by this one, then run the project.

[MainSwift.storyboard.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/792626/MainSwift.storyboard.zip)

**Comment by hackiftekhar** [comment]
@tbaranes ok, I'll check it however are you sure your UIScrollView is calculating correct content size?

**Comment by tbaranes** [comment]
I ended up with a workaround, so can't confirm this anymore... You can either keep that issue open (to check if there's really an issue) or not, up to you 👍

**Comment by hackiftekhar** [comment]
@tbaranes I'm curious to know what was your workaround.

**Comment by tbaranes** [comment]
Well, it's more than a workaround, but globally, I change my structure to make it works. No more `UIStackView`...

**Comment by hackiftekhar** [comment]
Thanks:)

**Comment by hackiftekhar** [comment]
Thanks:)
