### ISSUE TITLE
Non-translucent navigation bar is pushed outside the screen

### ISSUE THREAD

**Issue by pjuzeliunas** [hackiftekhar/IQKeyboardManager#779]
Non-translucent navigation bar is pushed outside the screen in a controller with single full-screen text view. Issue does not happen if navigation bar is translucent.

### Steps:

1. Create single view application from Xcode menu.
2. Add IQKeyboardManager to codebase and enable it in app delegate.
3. Create the following view hierarchy in app storyboard: `UINavigationController` → (root) → `ViewController`.
4. (Optional) set some title on `ViewController`'s navigation item.
5. Add `UITextView` to `ViewController`. Make it full-screen and centered using layout constraints.
Storyboard should look like this:
![region capture 2](https://cloud.githubusercontent.com/assets/6682061/23211860/4dfcb484-f904-11e6-97db-9e42314d5349.png)
6. Select navigation bar in Navigation Controller Scene:
![region capture 3](https://cloud.githubusercontent.com/assets/6682061/23211685/883208b2-f903-11e6-847f-90cd413f1688.png)
7. In Attributes Inspector, remove checkmark on `Translucent` property.
![region capture 5](https://cloud.githubusercontent.com/assets/6682061/23212062/3dbec476-f905-11e6-89fa-0988d39464d2.png)
8. Run the app on iPhone simulator. Tap on text view to make it a responder.

Issue: navigation bar is pushed outside screen boundaries:
![simulator screen shot 22 feb 2017 13 42 09](https://cloud.githubusercontent.com/assets/6682061/23211965/c004d304-f904-11e6-8b24-619b488ef570.png)

Issue does not happen if you ignore step 7, i.e. when navigation bar is translucent.

**Comment by stachon** [comment]
Have you tried the steps from https://github.com/hackiftekhar/IQKeyboardManager/blob/master/MANUAL%20MANAGEMENT.md ?

**Comment by hackiftekhar** [comment]
@pjuzeliunas @stachon I'll try to check what might be the issue with translucent navigation bar.

**Comment by iosApem** [comment]
I've got this problem, too.
Hoping the solution!

**Comment by burkaslarry** [comment]
Still not fixed ?

**Comment by hackiftekhar** [comment]
It's fixed with new solution.

**Comment by usuf1990** [comment]
@hackiftekhar still not fixed

**Comment by hackiftekhar** [comment]
Which version you are using @usuf1990?
