### ISSUE TITLE
Arrow directions in iOS 9 vs iOS 10

### ISSUE THREAD

**Issue by korovyev** [hackiftekhar/IQKeyboardManager#782]
On iOS 9 devices, the keyboard arrows are horizontal. On iOS 10 devices, they are vertical. I am wondering why this is?
I have been asked to have the arrows horizontal for both iOS 9 & 10 - and I'd like to know the reason why this change was made before I think about creating a PR to have the option. (I don't really mind myself, so if theres a good reason for the change that I can use to push back on this, that would be great)

```
if #available(iOS 10.0, *) {
        imageLeftArrow = UIImage(named: "IQButtonBarArrowUp", in: bundle, compatibleWith: nil)
        imageRightArrow = UIImage(named: "IQButtonBarArrowDown", in: bundle, compatibleWith: nil)
} else {
        imageLeftArrow = UIImage(named: "IQButtonBarArrowLeft", in: bundle, compatibleWith: nil)
        imageRightArrow = UIImage(named: "IQButtonBarArrowRight", in: bundle, compatibleWith: nil)
}
```

**Comment by hackiftekhar** [comment]
If you see textfield of WebView (Safari or WKWebKit) then on iOS9 you'll see left/right arrow on keyboard, for iOS10 you'll see up/down arrow, that's why I make it dependent on iOS.

**Comment by korovyev** [comment]
Good enough for me, thanks!
