### ISSUE TITLE
Screen freezing in iOS 10.2

### ISSUE THREAD

**Issue by aisgirish** [hackiftekhar/IQKeyboardManager#783]
Hello I am developing iOS app into which I had added IQKeyboardManager for keyboard show & hide. It is working fine in iOS 9. But when I run into iOS 10.2 (iPhone 6 & 6s), app is freezing in following situation.

APP FREEZE

Open App with Login page.
Goto next page without touch on any textfields. (Username or password).
App Freeze. Not any control on Navigation bar is also not working.
APP NOT FREEZE

Open App with Login page.
Touch Username or password. Hide keyboard.
Goto next page.
Any suggestion will be most appreciated.

**Comment by hackiftekhar** [comment]
@aisgirish You'll need to debug why it's freezing. You could stop rinning by tapping pause debugging icon and check your threads hierarchy.

**Comment by hackiftekhar** [comment]
If you find something useful for me then let me know.

**Comment by aisgirish** [comment]
Actually, there is weird problem. I am not sure that IQKeyboardManager create this issue. 
Because, I put alert message and auto dismiss it.
And it is not freezing.
