### ISSUE TITLE
enabledDistanceHandlingClasses does not work well

### ISSUE THREAD

**Issue by lingzlu** [hackiftekhar/IQKeyboardManager#784]
I have IQKeyboardManager enable turn off and add a specific ViewController with UITextViews. 

I set the break points in `keyboardWillShow` and `textFieldViewDidBeginEditing` in IQKeyboardManager.swift, and find that `keyboardWillShow` gets call before `textFieldViewDidBeginEditing`. `privateIsEnabled()` in keyboardWillShow return false because `_textFieldView` is `nil` , thus `_kbSize` was never computed. When `keyboardDidShow` gets call, `privateIsEnabled` return true, it goes in `adjustFrame()` as expect, but due to `_kbSize`, the frame 's not adjusted correctly. Is this issue being fixed or still unknown?  Thanks

**Comment by hackiftekhar** [comment]
Marking this as duplicate since #772 does have a demo project.
