### ISSUE TITLE
IQKeyboardManagerSwift causes UITableviewDelegate didSelected return wrong Indexpath

### ISSUE THREAD

**Issue by lforme** [hackiftekhar/IQKeyboardManager#787]
First of all thank you very much for creating such a useful keyboard manager.
We have used it in almost every project.
Recently we found an interesting question: 
When I use IQKeyboardManagerSwift and I customize the cell, it will cause my tableIveView the indexpath to get confused.
My Customize cell with UITextView, and I set this in AppDelegate:
IQKeyboardManager.sharedManager().enable = true
IQKeyboardManager.sharedManager().shouldResignOnTouchOutside = true

There is a simple demo here: 
https://github.com/lforme/IQKeyboardManagerSwiftTest

**Comment by lforme** [comment]
We test this case use OC, there is no problem

**Comment by lforme** [comment]
We test this case use OC version, there is no issue

**Comment by ahmadabudawod** [comment]
I have the same issue bug , when use UITableViewController

**Comment by lforme** [comment]
@ahmadabudawod Temporary solution is the version of oc

**Comment by ahmadabudawod** [comment]
Sorry , what do you mean by ( version of oc )

**Comment by lforme** [comment]
@ahmadabudawod I user 'pod IQKeyboardManager' instead of  'pod IQKeyboardManagerSwift'

**Comment by hackiftekhar** [comment]
@ahmadabudawod I updated @lforme comments, by oc he means obj-c.

**Comment by hackiftekhar** [comment]
@ahmadabudawod I can understand your concern, however I cannot do anything. regarding tableview, it's all doing correct.

Technically when user tap outside, library dismiss keyboard and after dismissing keyboard touch is passed to table view and table exactly click where user touched but the thing is that the cell position is adjusted due to keyboard dismiss.

**Comment by JustinDSN** [comment]
@ahmadabudawod, did you ever come to a solution that worked for you?  We encountered a similar issue, our solution was:

In the ViewController that has a table view, listen to keyboard did show and did hide events.  When the keyboard is shown, we disable selection on the table view.  When the keyboard hides, we enable selection again.

What this gives us is an acceptable work around.  Tapping into a cell with a text field in it makes the text field become first responder and the keyboard appears (disabling selection on table view).  When the user taps out side, the IQKeyboardManager dismisses the keyboard and scrolls the table view back (and the cell is not selected).  The user can then select a different cell by tapping again.

cc: @hackiftekhar

**Comment by hackiftekhar** [comment]
This is the most satisfied workaround I believe for this issue. Thanks @JustinDSN for sharing this with us.
