### ISSUE TITLE
Clicking next/previous button flickers the screen but does not reposition it

### ISSUE THREAD

**Issue by varijkapil13** [hackiftekhar/IQKeyboardManager#792]
Hi,
First thank you for this awesome library. I use it in almost all projects now.
But I am having a problem with my recent project. This is my first project in swift 3 and maybe I am doing something wrong.

With a screen that have 4 to 5 textfields, clicking on individual textfields separately produces the desired functionality of lifting up the screen to the textfield height, but If I want to navigate with the help of next/previous buttons on the toolbar, it won't lift up the view.

Instead, for the textfields that are behind the keyboard, the view flickers for a moment, the textfield becomes the firstresponder, but it the view remains as it was and the textfield is still behind the keyboard.

Thanks

**Comment by Thanhnc85** [comment]
I have same issue

**Comment by hackiftekhar** [comment]
I think you've pinned either top layout constraint or bottom layout constraint. If this is the case then please read manual management guide for workarounds.

**Comment by varijkapil13** [comment]
I checked the top layout and bottom layout contraints, but the textfields do not have these contraints. But the top textfield have a vetical spacing constraint to an image and the image then have a top layout constraint. So maybe it is because of this layout, so according to the guide you have a IQKeyboard manager object in the interface builder, to add contraints to it.
Can you tell me how to do that?

**Comment by hackiftekhar** [comment]
@varijkapil13 That's the issue, your textfields are indirectly related to the top layout constraints, if you replace it by something else then you'll be done, please also check that your textfields are not related to the bottom layout constraint.
