### ISSUE TITLE
Issue with UITableViewCell selection

### ISSUE THREAD

**Issue by dimovskidamjan** [hackiftekhar/IQKeyboardManager#793]
I have a `UITextField` which shows a small `UITableView` underneath it as the user starts typing. There is an issue when the user taps on one of the cells of this table view, because IQKeyboardManager's tapGestureRecognizer catches the tap and the delegate's `didSelectRow` method is not called. Is there a way to prevent this? I can see that in the `shouldReceive touch` method there is a check for UIControl and UINavigationBar, but a UITableViewCell is neither of these. Can this be extended somehow?

**Comment by hackiftekhar** [comment]
Then I think you should disable shouldResignOnTouchOutside to prevent this.

**Comment by dimovskidamjan** [comment]
No, because I want to keep the touch outside functionality for the surrounding area. It would be better if there was some sort of array where you could define which classes should not respond to the tap gesture, like you have added UIControl and UINavigation bar, so that everyone could tailor the behavior to their specific needs.

**Comment by hackiftekhar** [comment]
I like your idea @dimovskidamjan.

**Comment by hackiftekhar** [comment]
Thanks a lot @dimovskidamjan. You gave me idea to improve things to be in a better shape.

**Comment by dimovskidamjan** [comment]
Have you updated this for Swift?

**Comment by hackiftekhar** [comment]
Yes. But new version isn't pushed yet.

**Comment by dimovskidamjan** [comment]
When do you expect to push a new version for swift?

**Comment by hackiftekhar** [comment]
Pushed v4.0.9 today!
