### ISSUE TITLE
value of type "anyObject " has no member drawingplaceholdertext

### ISSUE THREAD

**Issue by BahaeddinSagar** [hackiftekhar/IQKeyboardManager#794]
Hello, 

When I try to archive the program which uses this keyboard, i get this error (value of type "anyObject " has no member drawingplaceholdertext)

-----------------------------------------------------------------------------------------------

public var shouldHidePlaceholderText: Bool {
        get {
            let aValue: AnyObject? = objc_getAssociatedObject(self, &kIQShouldHidePlaceholderText) as AnyObject?
            
            if let unwrapedValue = aValue as? Bool {
                return unwrapedValue
            } else {
                return false
            }
        }
        set(newValue) {
            objc_setAssociatedObject(self, &kIQShouldHidePlaceholderText, newValue, objc_AssociationPolicy.OBJC_ASSOCIATION_RETAIN_NONATOMIC)
            
            if let toolbar = self.inputAccessoryView as? IQToolbar {
                if self.responds(to: #selector(getter: UITextField.placeholder)) {
                    let textField = self as AnyObject
                    toolbar.title = textField.drawingPlaceholderText   //*********** the error is here************
                }
            }
        }
    }
-----------------------------------------------------------------------------------------------------

however when I compile it for simulated iPhone 5s it runs perfectly

any ideas why this happens ?

Thanks

**Comment by hackiftekhar** [comment]
First of all, with my library there is no line saying `toolbar.title = textField.drawingPlaceholderText`
However in my library it does have
`toolbar.title = self.drawingPlaceholderText`

I don't know why you are casting self as AnyObject that's why it gives you error, You should cast it to a UIView to fix the issue.

**Comment by kikoso** [comment]
The version 4.0.4 contains this error inside (`toolbar.title = textField.drawingPlaceholderText` instead of `toolbar.title = self.drawingPlaceholderText`). It is required to use 4.0.5 instead. I recommend you updating the README or the Cocoapod corresponding with that version.

**Comment by samtheson** [comment]
@kikoso You life-saver you! 💪
