### ISSUE TITLE
Missing headers in umbrella file

### ISSUE THREAD

**Issue by mattchen** [hackiftekhar/IQKeyboardManager#802]
hey, I was using Carthage with IQKeyboardManager, after @import the framework, xcode cant find class IQKeyboardReturnKeyHandler class. After I add IQKeyboardReturnKeyHandler.h into IQKeyboardManager.h, it stopped complain.
And also, there are some build warnings like 'Umbrella header for module IQKeyboardManager does not include header IQBarButtonItem.h', maybe we should add all the header files into the main header file?

I'm kind of new to Carthage, maybe I'm using it incorrectly, hope it helps. thank you.

**Comment by hackiftekhar** [comment]
@mattchen I checked and found that we are already adding those files to carthage frameworks, not sure why you got those errors.
