### ISSUE TITLE
IQ toolbar not appear in keyboard when click in textView , sometimes no appear in textFiled too

### ISSUE THREAD

**Issue by GithubXkw1573** [hackiftekhar/IQKeyboardManager#804]
![Uploading IMG_1386.PNG…]()
![Uploading D0DC36B2CCE8A21E5A1EB074BC98181C.png…]()

toolbar not appear in keyboard always and uitableview do not scroll for adjust position

**Comment by hackiftekhar** [comment]
@GithubXkw1573 Can you please attach images again?
