### ISSUE TITLE
Swift 3.1 Update

### ISSUE THREAD

**Issue by otymartin** [hackiftekhar/IQKeyboardManager#806]
@hackiftekhar 
Afew changes are needed for swift 3.1
` override open class func initialize()`

`//method initialize() defines Objective-c class method initialize, which is not guaranteed to be invoked by swift and will be disallowed in future versions`

**Comment by hackiftekhar** [comment]
Will update soon.

**Comment by tamutti** [comment]
This isn't fixed. Just updated to latest and this message still appears for IQbarButtonItem.swift and IQToolbar.swift.
