### ISSUE TITLE
superView  is UIScrollView,IQKeyboard is bad

### ISSUE THREAD

**Issue by JackShengBin** [hackiftekhar/IQKeyboardManager#808]
![2017-03-30 2 25 30](https://cloud.githubusercontent.com/assets/19474665/24490346/cb179800-1554-11e7-8f44-7b5f5eb6b849.png)

**Comment by hackiftekhar** [comment]
@JackShengBin Can you explain what's the issue? Just for your information, if you are using UIScrollView then make sure it does have proper constraint to calculate it's contenteSize.
