### ISSUE TITLE
AutoToolbar hide some of textView.

### ISSUE THREAD

**Issue by JsonFu** [hackiftekhar/IQKeyboardManager#812]
I create tableViewCell by xib, and  there is a UITextView on cell's contentView. When I edit on textView and keyboard showed, but the AutoToolbar will hide textView's bottom.Then when I second edit on textView,it was normal. I  guess  that IQKeyboardManager miss the toolbar's height when calculate the offset.

**Comment by hackiftekhar** [comment]
For UITextView, it's NSNotifications work differently then UITextField. For UITextField, first we get UITextField notifications and then Keyboard notifications. But for UITextView, first we get Keyboard notifications and then get UITextView notifications and in this case UITextView doesn't have it's toolbar in place and it get's normal in second edit.
