### ISSUE TITLE
TableView gets unexpected contentInsets after keyboard hides

### ISSUE THREAD

**Issue by MobDeveloper163** [hackiftekhar/IQKeyboardManager#813]
Here is the weird thing. If I register keyboard open notification, everythg just works fine, even I do nothing in `keyboardWillShow ` method.
```
[[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(keyboardWillShow:) name:UIKeyboardDidShowNotification object:nil];
```
but if I uncomment the code, the tableview gets unexpected contentInsets. 
![unexpected contentInsets](https://thumbnail0.baidupcs.com/thumbnail/37c0bf7bafc5edf9c3132ddef9e6e003?fid=2368850984-250528-322851082458440&time=1491638400&rt=sh&sign=FDTAER-DCb740ccc5511e5e8fedcff06b081203-meQTTVW7KAQzH6gY2bx0eZmAl3M%3D&expires=8h&chkv=0&chkbd=0&chkpc=&dp-logid=2265679321560534057&dp-callid=0&size=c710_u400&quality=100)

**Comment by hackiftekhar** [comment]
@MobDeveloper163 that's weird, can you please share a demo?

**Comment by hackiftekhar** [comment]
@MobDeveloper163 Can you please share a demo, also can you please also attach the image?
