### ISSUE TITLE
iPad Keyboard Issue

### ISSUE THREAD

**Issue by developweb10** [hackiftekhar/IQKeyboardManager#815]
When i try to compile same library in iPad then this do not work and not getting any effect on click of textfield so please provide me solution to use this library in iPA.

**Comment by hackiftekhar** [comment]
you will not get any keyboard in simulator. Could you please confirm in which device you are testing?

**Comment by hackiftekhar** [comment]
@developweb10 Can you please let me know what you are trying to achieve?
