### ISSUE TITLE
Toolbar is not showing when in-call status bar is active

### ISSUE THREAD

**Issue by ayrap** [hackiftekhar/IQKeyboardManager#816]
I have a UIScrollView with textfields. The toolbar works fine.  However, the toolbar is not showing when in-call status bar is active as seen in the image below.

![screen shot 2017-04-10 at 8 53 57 pm](https://cloud.githubusercontent.com/assets/2392984/24862739/7edd3d5c-1e30-11e7-9f04-beefc1caa674.png)

**Comment by ayrap** [comment]
Any chance checking this?

**Comment by hackiftekhar** [comment]
@ayrap It does work for me in demo project? not sure what you are missing in your project. Can you please try the same with my demo project?

**Comment by hackiftekhar** [comment]
@ayrap any updates?
