### ISSUE TITLE
IQKeyboardManager calls UITextFieldDelegate when using UITextView

### ISSUE THREAD

**Issue by OlivierScalais** [hackiftekhar/IQKeyboardManager#817]
When using UITextField and UITextView in same view, UITextFieldDelegate textFieldShouldBegintEditing is called when tapping UITextView.

**Comment by OlivierScalais** [comment]
When commenting

`            if textField.subviews.count != 0  && isUserInteractionEnabled == true && isHidden == false && alpha != 0.0 {
                for deepView in textField.deepResponderViews() {
                   textfields.append(deepView)
                }
            }`

in `public func deepResponderViews() -> [UIView]` in `IQUIView+Hierarchy.swift` it works as expected.

**Comment by hackiftekhar** [comment]
I don't think `textFieldShouldBeginEditing` should be called in v4.0.9 because `canBecomeFirstResponder` call has been removed in v4.0.9. If you are using old version then there was this issue. Could you please confirm which version you are using?

**Comment by shahnewaz469** [comment]
@hackiftekhar 
Using IQKeyboardManagerSwift (4.0.9)
same issue for me

**Comment by hackiftekhar** [comment]
@shahnewaz469 Can you provide a demo project?

**Comment by shahnewaz469** [comment]
Sure @hackiftekhar 
here it is: https://drive.google.com/open?id=0B0RjmvyystA4VVFxYmVQTGpsdDQ

**Comment by hackiftekhar** [comment]
@shahnewaz469 I don't have access to the drive. Can you please attach the demo project zip here?

**Comment by shahnewaz469** [comment]
[TestSwift.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/982664/TestSwift.zip)
@hackiftekhar here it is.

**Comment by hackiftekhar** [comment]
@shahnewaz469 I checked the demo and found that this issue is already addressed and fixed in master branch already. I'm planning to release that one in couple of weeks.

Technically this was due to canBecomeFirstResponder call.

**Comment by maxmumford** [comment]
Can confirm fixed in v4.0.10 👍
