### ISSUE TITLE
Does not work on first install

### ISSUE THREAD

**Issue by riyanpratama** [hackiftekhar/IQKeyboardManager#818]
Hi, thanks for this great library. 

I have a little problem here, after initialize IQKeyboardManager in `didFinishLaunchingWithOptions` with `[[IQKeyboardManager sharedManager] setEnable:YES];`. At first install, it didn't work. But after we close the app, it works well. 

Any idea? Thank you!

**Comment by hackiftekhar** [comment]
No idea @riyanpratama, this should work as expected. However for first time keyboard might take a bit of time to populate.
