### ISSUE TITLE
UITextFiled not scrolling to keyboard position.

### ISSUE THREAD

**Issue by subratpadhi007** [hackiftekhar/IQKeyboardManager#822]
This is components placement and when textfield is active it is not scrolling up, when u click on toolbar arrows next UITextFiled is scrolling to keyboard position.

![simulator screen shot 15-apr-2017 8 12 29 pm](https://cloud.githubusercontent.com/assets/19999243/25064610/56119abe-221b-11e7-9363-47abeb1f2ce6.png)

**Comment by hackiftekhar** [comment]
@subratpadhi007 You men it doesn't work for first time and then works for second textField when tapping next/prev?
