### ISSUE TITLE
Fatal Exception: NSInvalidArgumentException -[UIImage imageFlippedForRightToLeftLayoutDirection]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by tomoyuki28jp** [hackiftekhar/IQKeyboardManager#823]
## Versions
- IQKeyboardManagerSwift (4.0.8)
- Xcode 8.3 + Swift
- iPhone 9

# StackTrace
```
Fatal Exception: NSInvalidArgumentException
-[UIImage imageFlippedForRightToLeftLayoutDirection]: unrecognized selector sent to instance 0x1808fb90
 Raw Text
0
CoreFoundation	
__exceptionPreprocess
1	libobjc.A.dylib	
objc_exception_throw
2	CoreFoundation	
__methodDescriptionForSelector
3	CoreFoundation	
___forwarding___
4
CoreFoundation	
_CF_forwarding_prep_0
5	IQKeyboardManagerSwift	
IQUIView+IQKeyboardToolbar.swift line 820
specialized UIView.addPreviousNextDoneOnKeyboardWithTarget(AnyObject?, previousAction : Selector, nextAction : Selector, doneAction : Selector, titleText : String?) -> ()
6	IQKeyboardManagerSwift	
IQUIView+IQKeyboardToolbar.swift line 0
@objc UIView.addPreviousNextDoneOnKeyboardWithTarget(AnyObject?, previousAction : Selector, nextAction : Selector, doneAction : Selector, titleText : String?) -> ()
7	IQKeyboardManagerSwift	
IQUIView+IQKeyboardToolbar.swift line 0
@objc UIView.addPreviousNextDoneOnKeyboardWithTarget(AnyObject?, previousAction : Selector, nextAction : Selector, doneAction : Selector) -> ()
8	IQKeyboardManagerSwift	
IQKeyboardManager.swift line 0
IQKeyboardManager.init() -> IQKeyboardManager
9	IQKeyboardManagerSwift	
IQKeyboardManager.swift line 159
globalinit_33_1804EA4A44CDC62F5B66EAD58B4692DC_func2
```

**Comment by tomoyuki28jp** [comment]
https://github.com/hackiftekhar/IQKeyboardManager/commit/4143c4b3eba4b7cba5b67a78a3c0ac4caec6e46d

Why are they different?

## Objc
`if ([UIImage instancesRespondToSelector:@selector(imageFlippedForRightToLeftLayoutDirection)])`

## Swift
`if #available(iOS 9.0, *)`

**Comment by hackiftekhar** [comment]
@tomoyuki28jp I don't this this should crash because I already added validation, make sure you didn't changed anything in code. Regarding your question, this is because swift does have availability check feature while ObjC doesn't have this feature directly that's why we validate by asking `instancesRespondToSelector`.

**Comment by tomoyuki28jp** [comment]
@hackiftekhar Thanks for your reply! We didn't change any code, but it seems happened in jailbroken devices :(

So I close this issue now. Please let me know if you find any way to avoid this crash.
