### ISSUE TITLE
Textview Showing Textfield Placeholder

### ISSUE THREAD

**Issue by VictorASebastian** [hackiftekhar/IQKeyboardManager#824]
Once i clicked some textfield and then moved to any Textview, the keyboard toolbar placeholder for the  textview showing the placeholder of the earlier textfield..

**Comment by QIcareful** [comment]
Textview displays placeholders for earlier text boxes

**Comment by hackiftekhar** [comment]
@VictorASebastian @QIcareful This might be the issue however I need a demo project to debug it well and fix the issue.

**Comment by hackiftekhar** [comment]
@VictorASebastian @QIcareful Can one of you send a demo project?
