### ISSUE TITLE
becomeFirstResponder not work

### ISSUE THREAD

**Issue by Jinkeycode** [hackiftekhar/IQKeyboardManager#826]
When I raise the keyboard by becomeFirstResponder, the textField will not move.How can I fix this problem

**Comment by hackiftekhar** [comment]
Please check if you havn't pinned your top layout constraint or bottom layout constraint.

**Comment by Jinkeycode** [comment]
@hackiftekhar I have add the bottom layout constraint to toolbar. The textField will only move when I click the textfield in toolbar, but no response while using ‘ becomeFirstResponder’
![image](https://cloud.githubusercontent.com/assets/12148377/25233328/12520f30-2611-11e7-9d6d-a68110233790.png)

**Comment by hackiftekhar** [comment]
Can you replace your bottom layout constraint with superview?

**Comment by Jinkeycode** [comment]
is there anything eroor？

**Comment by hackiftekhar** [comment]
@Jinkeycode Can you please check you are returning YES in textFieldShouldBeginEditing method for that textfield?
