### ISSUE TITLE
UICollectionView with UITextField inside UICollectionViewCell

### ISSUE THREAD

**Issue by lucacasula91** [hackiftekhar/IQKeyboardManager#827]
When i set IQKeyboardManager enable and enter text inside a UITextField, the text jump up and then go back to original position.
See this video: https://goo.gl/I9q4Dm

**Comment by hackiftekhar** [comment]
Can you please try doing the same without using IQKeyboardManger (Just to check) if it works? I also get the same issue in my past but it was looking iOS issue at that time.
