### ISSUE TITLE
Change font of "Done" button

### ISSUE THREAD

**Issue by quangnn041291** [hackiftekhar/IQKeyboardManager#828]
How can I change the font of "Done" button in Toolbar? It's seem to be "bold".

**Comment by hackiftekhar** [comment]
Nope, there is no way to set "Done" button font at this time, but will think about adding support for this.

**Comment by LiangyongFShen** [comment]
Can add setting keyboradReturnKeyType' s button font ?

**Comment by jameswwwebster** [comment]
This is something we'd find useful too.

**Comment by mohpor** [comment]
Better yet, I wish you could add `toolbarDoneBarButtonItemAttributedText`.
