### ISSUE TITLE
IQKeyboardManager is not working and throwing this error when I click a text field

### ISSUE THREAD

**Issue by miguelef** [hackiftekhar/IQKeyboardManager#830]
[MC] System group container for systemgroup.com.apple.configurationprofiles path is /Users/user/Library/Developer/CoreSimulator/Devices/**/data/Containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
 [MC] Reading from private effective user settings.

And it doesn't display the IQKeyboard . I've installed it adding it to the project by drag and drop. and then adding this line in the delegate :

`        IQKeyboardManager.sharedManager().enable = true`
Any help will be really appreciated.

**Comment by hackiftekhar** [comment]
I think the above solution should work, however the error was not related to the library, also keyboard will not appear in simulator and you have to toggle software keyboard from simulator menu.
