### ISSUE TITLE
I don't want to hide the default UINavigationBar Of UINavigationController when keyboardManager slides up the view,What should I do?

### ISSUE THREAD

**Issue by asd8855** [hackiftekhar/IQKeyboardManager#832]

**Comment by asd8855** [comment]
use xib

**Comment by amitg02** [comment]
connect view controller bottom constant to **IQLayoutGuideConstant**  @asd8855

**Comment by asd8855** [comment]
my keybord likes wechat keybord

**Comment by hackiftekhar** [comment]
You should use UIScrollView instead of UIView if you don't want to hide UINavigation bar. The second solution is to disable library for that view controller and implement your own customized solution.

**Comment by asd8855** [comment]
xib I use UIScrollView instead of UIVIew ,but my view  According to insanity
