### ISSUE TITLE
Keyboard is not Showing

### ISSUE THREAD

**Issue by syedrazackimran** [hackiftekhar/IQKeyboardManager#834]
![simulator screen shot apr 25 2017 11 12 43 am](https://cloud.githubusercontent.com/assets/15051045/25368646/238ba7e4-29a8-11e7-9368-f2c9004b24b2.png)

  let KeyboardManager = IQKeyboardManager.sharedManager()
   KeyboardManager.enable = true
   KeyboardManager.enableAutoToolbar = false

when i tap textfield keyboard is not showing . but keyboard is in becomeresponder it called delegate methods everything . my problem is keyboard is not showing when i tap textfield 

IQKeyboardManager: ****** addToolbarIfRequired() started ******
IQKeyboardManager: ****** addToolbarIfRequired() ended: 0.0466376979984489 seconds ******
IQKeyboardManager: enableAutoToolbar: Yes
IQKeyboardManager: ****** textFieldViewDidBeginEditing started ******
IQKeyboardManager: ****** addToolbarIfRequired() started ******
IQKeyboardManager: ****** textFieldViewDidEndEditing started ******
IQKeyboardManager: ****** textFieldViewDidEndEditing ended: 1.84264158199949 seconds ******
IQKeyboardManager: Found 3 responder sibling(s)
IQKeyboardManager: ****** addToolbarIfRequired() ended: 5.81790556399937 seconds ******
IQKeyboardManager: Saving <<UINavigationController: 0x7f99b2009200> 0x00007f99b2009200> beginning frame : (0.0, 0.0, 375.0, 667.0)
IQKeyboardManager: ****** textFieldViewDidBeginEditing ended: 11.0077482380002 seconds ******

**Comment by JuanPabloBoero** [comment]
Have you tried un-selecting "Connect Hardware Keyboard" in the simulator option? the shortcut is shift+cmd+k

**Comment by syedrazackimran** [comment]
yes i tired but its not showing !! some fields works fine .. some fields doing trouble !

**Comment by lastMove** [comment]
Try on a real device

**Comment by hackiftekhar** [comment]
You have to toggle Software keyboard in order to see keyboard in simulator.
