### ISSUE TITLE
Abnormal re-arrangement of Scroll offset

### ISSUE THREAD

**Issue by AabanTariq** [hackiftekhar/IQKeyboardManager#835]
Everything working good in start. I'm clicking on fields, tableview scrolls properly as needed.
But when I played a little with my textfields in UITableCell displayed on screen. Scroll Offset first reduces to right value, then jerks back to wrong value.

**Comment by hackiftekhar** [comment]
@AabanTariq Can you share a demo project and steps to reproduce?
