### ISSUE TITLE
Fields behaving strange if there are multiple fields in single section of table view

### ISSUE THREAD

**Issue by mubashirhussain55** [hackiftekhar/IQKeyboardManager#836]
I have multiple sections in table view and in one section I have 4 fields when I start editing field the view is moved to some different offset not focussing the current field. 

XCode - 8, Swift 3 with the latest IQKeyboardManager version

**Comment by ambujshukla-cdn** [comment]
Hi,
Did you find the solution for this issue.

**Comment by AalokParikh** [comment]
> I have multiple sections in table view and in one section I have 4 fields when I start editing field the view is moved to some different offset not focussing the current field.
> 
> XCode - 8, Swift 3 with the latest IQKeyboardManager version

I have the same issue with Xcode 10.1 & Swift 4.2

**Comment by hackiftekhar** [comment]
Can someone send me the demo?
