### ISSUE TITLE
textview hide under the done toolbar in keyboard

### ISSUE THREAD

**Issue by amitg02** [hackiftekhar/IQKeyboardManager#841]
in this screen, there is tab bar under textview's height is 0 or 50 based on tab bar is shown or hidden on click of attachment button. when the tab bar is open and the click on textview then KB is above the textview.

```
if isAttachButtonClick {
			isAttachButtonClick = false
			viewAttachmentHeightConstraint.constant = 0
			tabBar.isHidden = true
		} else {
			isAttachButtonClick = true
			viewAttachmentHeightConstraint.constant = 50
			tabBar.isHidden = false
		}
```

when hide change then keyboard hides textview
![screen shot 2017-04-28 at 8 17 59 pm](https://cloud.githubusercontent.com/assets/19693287/25534055/51d5a2b2-2c50-11e7-9569-e304ec3b011b.png)
![screen shot 2017-04-28 at 8 18 57 pm](https://cloud.githubusercontent.com/assets/19693287/25534057/53237c48-2c50-11e7-9ad9-412f87761545.png)

**Comment by hackiftekhar** [comment]
Your screen looks like chat screen, and it's not a good idea to show the toolbar with done button, if you want to hide that then please set textView.inputAccessoryView = [UIView new].

Regarding your question, I'm not fully aware of what configuration you have. Can you please elaborate?
