### ISSUE TITLE
Textview not scrolling properly when keyboard appears

### ISSUE THREAD

**Issue by rlaurb** [hackiftekhar/IQKeyboardManager#842]
IQKeyboardManagerSwift. The IQKeyboardManager is enabled in AppDelegate, but no other code changes were implemented.

I have a UISplitViewController. The detail view contains a UINavigationView. 

Two cases:
1. **Standard Implementation**: The scene contain a UIView which contains the UITextView in question. In this case, tapping in the UITextView causes the keyboard to appear, and the entire view (including navigation bar) to scroll upwards. The tapped location is visible above the keyboard toolbar.

2. **Changed the class of the UIView to UIScrollView**. In this case, tapping in the UITextView causes the keyboard to appear, and the text view scrolls (leaving the Navigation Bar visible (which is what I want). **However, the text view does not scroll enough.** The new insertion point in the UITextView is still hidden behind the keyboard's toolbar (by an amount which appears to be roughly equal to the height of the toolbar).

I've included the storyboard.

If this is my problem, please let me know what to do to fix it.

[Main.storyboard.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/968710/Main.storyboard.zip)

Thanks,

Rick Aurbach

**Comment by rlaurb** [comment]
More information: In the case where the UITextView is contained in a UIScrollView (and tapping in a portion of the text view that will be hidden by the keyboard, it appears that the calculation of how far to move does not account for the height of the keyboard's toolbar (i.e., the TextView's inputAccessoryView).

**Comment by rlaurb** [comment]
I have verified that this issue is not due to the existence of the inputAccessoryView, because I can set `IQKeyboardManger.sharedManager().enableAutoToolbar = false` and the problem persists.

The enclosed screenshot shows the keyboard present, but the textview not properly scrolled...
![simulator screen shot may 5 2017 11 56 47 am](https://cloud.githubusercontent.com/assets/6610193/25756135/409b9426-318b-11e7-95d3-81dc35606e16.png)

**Comment by rlaurb** [comment]
Sorry, closed this by accident.

**Comment by Venkat1128** [comment]
I have a same problem ,
@rlaurb please let me know if you find the solution.

Thanks,
Venkat

**Comment by rlaurb** [comment]
Venkat,

It took me a while to realize it, but the solution was actually documented in the document “MANUAL MANAGEMENT.md”. Look at the section entitled “Working with Full Screen UITextView” and follow those instructions. The setting of constraints is pretty obvious, but the key is the following sentence:

"Connect bottom layout guide constraint with IQLayoutGudeConstraint and that’s all.”

To do that, you need to burrow down into IQUIViewController+Additions.swift to make the connection. See the attached screenshot.



Connecting the bottom of the textView to the bottom layout guide AND IQUIViewController_Additions:IQLayoutGuideContraint is absolutely key to making this work.

Cheers,

Rick Aurbach
