### ISSUE TITLE
Two  TextFields，their first superView are diferent, the  toolbar don't have next and previous

### ISSUE THREAD

**Issue by daishuyi** [hackiftekhar/IQKeyboardManager#844]
Can I appooint their defined superView？

**Comment by hackiftekhar** [comment]
You can add them to a single IQPreviousNextView and next/prev will appear.

**Comment by daishuyi** [comment]
OK, Thanks ！

**Comment by mansa-dev** [comment]
Great! I think, it would be of big help to people, if mentioned in readme.

**Comment by hackiftekhar** [comment]
It's already there @mansa-dev 
https://github.com/hackiftekhar/IQKeyboardManager/blob/master/MANUAL%20MANAGEMENT.md

**Comment by douglasjunior** [comment]
[My library](https://github.com/douglasjunior/react-native-keyboard-manager/) implements IQKeyboardManager to react-native, just use:

```javascript
KeyboardManager.setToolbarPreviousNextButtonEnable(true);
```
