### ISSUE TITLE
Is there any way to Disable next/previous buttons for specify TextView?

### ISSUE THREAD

**Issue by vahids** [hackiftekhar/IQKeyboardManager#845]
Hi, I have some textviews in a tableView
and some of theme is hidden by set Height constraint to 0 and will be visible with setting Height constraint to 70.

Issue:
When user editing a visible TextView and press ">" next the curser will be go to the next TextView that is Invisible!

Is there any way to handle ">" and "<" actions? or completely disable "<" and ">" ?

**Comment by hackiftekhar** [comment]
You should play with isEditable property, if it's not editable then library will not see that textView.
