### ISSUE TITLE
What if i don't want i drop down the view?

### ISSUE THREAD

**Issue by JavenZ** [hackiftekhar/IQKeyboardManager#846]
I'm sorry to bother you，when i click the 1st textfield, the tableview will be drop down, left a lot of white space. how can i avoid this situation?
![qq20170505-161544](https://cloud.githubusercontent.com/assets/17868438/25738314/f4e551e2-31ae-11e7-9d8d-3a82bf2612f0.gif)

**Comment by hackiftekhar** [comment]
Sorry, I don't understand @JavenZ what you are trying to explain. Could you please reword?

**Comment by JavenZ** [comment]
I don't the tableview be pull down，like this
![48e46bc6-3a05-4b68-90a6-86b16103a5ab](https://cloud.githubusercontent.com/assets/17868438/25787938/40469652-33d8-11e7-94d4-51e3d8002a98.png)

**Comment by apsmilefokus** [comment]
i think he would like to freeze  textfield when keyboard on show.

**Comment by hackiftekhar** [comment]
hmm @JavenZ I understand what you are trying to explain. I'll try to fix that issue.

**Comment by hackiftekhar** [comment]
@JavenZ I found that there were some technical limitations that's why I was keeping thing as it is.
