### ISSUE TITLE
Manually tapping the lower textview

### ISSUE THREAD

**Issue by ndduong97** [hackiftekhar/IQKeyboardManager#851]
I have two text views, one on top and one at the bottom. When the first textview is selected and then the second text view is tapped then the whole scroll view is shifted up. However, when the keyboard is not shown (the first text view is not selected), and I try to directly tap the second textview, the scroll view does not shift up.

Is there a way I can achieve the scroll view shifting up effect by manually tapping the second textview without selecting the first textview?

**Comment by hackiftekhar** [comment]
I think this should work in both cases but if it isn't working then can you share a demo project?

**Comment by ndduong97** [comment]
I just fixed it by doing the scroll manually myself. Not sure why it didn't work automatically.
