### ISSUE TITLE
iqkeyboardmanger is not working with textview and uidatepicker

### ISSUE THREAD

**Issue by vuppalasivakumar** [hackiftekhar/IQKeyboardManager#852]
hi bro it is working excellent with textbox but incase of textview and datepicker it is not working.
I had seen an issue similar to it in 2015 but still now. U didn't update the pod can please fix as soon as possible.

however thank u bro for ur pod.

**Comment by hackiftekhar** [comment]
Can you please elaborate what exactly isn't working with textview and uidatepicker?

**Comment by vuppalasivakumar** [comment]
As i said in issue, coming to textview when user clicks on text view
keyboard comes out and  covering the textview. keyboard is not lifting view
and coming to uidate picker when user clicks on date picker text box date
picker is coming out and but view is not lifting up and the background
design is getting disturbed.


but for texfield it is working fine.

**Comment by vuppalasivakumar** [comment]
As i said in issue, coming to textview when user clicks on text view keyboard comes out and  covering the textview. keyboard is not lifting view
and coming to uidate picker when user clicks on date picker text box date picker is coming out and but view is not lifting up and the background design is getting disturbed.


but for texfield it is working fine.

**Comment by vanditmehta** [comment]
I'm using picker view and number key pad and having same issue as @vuppalasivakumar , Key pad is not hiding 

thank you for your pod.

**Comment by hackiftekhar** [comment]
Can you guys be sure that you haven't pinned top/bottom layout guide directly or indirectly with textfield/textview?

**Comment by vuppalasivakumar** [comment]
no we done properly

**Comment by hackiftekhar** [comment]
Then not sure what might be the cause of issue. Can you please provide more information?

**Comment by vuppalasivakumar** [comment]
As i said in issue, coming to textview when user clicks on text view
keyboard comes out and  covering the textview. keyboard is not lifting view
and coming to uidate picker when user clicks on date picker text box date
picker is coming out and but view is not lifting up and the background
design is getting disturbed.

**Comment by hackiftekhar** [comment]
Can you please share a demo because I think it's hard to understand the problem with text messages.

**Comment by fparkar** [comment]
Same happening with me too

**Comment by NalineeSingh01** [comment]
Facing same issue with textview. First time the view doesn't move up and when clicked again second time in textview the view moves up properly, not sure the reason for it.
