### ISSUE TITLE
Using both `IQKeyboardManager` and `IQKeyboardManagerSwift`

### ISSUE THREAD

**Issue by KimDarren** [hackiftekhar/IQKeyboardManager#853]
I'm is using both Objective-C and Swift in a project.
Is that enable to using both `IQKeyboardManager` and `IQKeyboardManagerSwift` (via cocoapods) in a project?

Or else, what is the best way to use IQKeyboardManager via cocoapdos in the project using both Objective-C and Swift?

**Comment by hackiftekhar** [comment]
You cannot use both pods at a time since both have same kind of logic and result in undefined behaviour. Use only one library in a project.
