### ISSUE TITLE
IQKeyboardManager not working properly with UITextfield and UITextView

### ISSUE THREAD

**Issue by ankushbhatia1347** [hackiftekhar/IQKeyboardManager#855]
I am facing an issue with the library as i am using UITableview for the input form on the controller. There are two types of cell each for UITextfield and for UITextview. As soon as textfield becomes first responder, both the UITextfield and UITextview delegates are getting called.

**Comment by DheerajDhamija** [comment]
Hi @ankushbhatia1347 I am facing same issue..

**Comment by SURYAKANTSHARMA** [comment]
Yes i had seen this problem both UITextField and UITextView delegates called simultaneously inside the cell of tableView when textField get clicked. @hackiftekhar please look into this.

**Comment by hackiftekhar** [comment]
It's already fixed with latest version.

**Comment by SURYAKANTSHARMA** [comment]
Thanks @hackiftekhar .
