### ISSUE TITLE
not working in popup !

### ISSUE THREAD

**Issue by AzAli71** [hackiftekhar/IQKeyboardManager#857]
hi , 
IQKyboardManager not working when i have textfield that it is in popup I use KLCPopup and I have popup that hast a textfield IQKyboard scroll the behind view (self.view) not the popup view

**Comment by hackiftekhar** [comment]
The library requires a hierarchy of viewController's. I'm not sure how KLCPopup works, but if it's directly added to window then library will not work in this case.

**Comment by gopaldevra** [comment]
@hackiftekhar thanks to making this fantastic library.
Please let me know how to use in the popup.

**Comment by hackiftekhar** [comment]
There is no logic currently exist to handle this condition

**Comment by gopaldevra** [comment]
ok thanks @hackiftekhar

**Comment by hackiftekhar** [comment]
It's a very difficult task to handle to handle if textField is directly part of UIWindow. It must be part of a UIViewController. @gopaldevra if you have some time then could you please investigate and provide me a solution?
