### ISSUE TITLE
textFieldDidEndEditing not called when using IQKeyboardReturnKeyHandler

### ISSUE THREAD

**Issue by asrivastav973** [hackiftekhar/IQKeyboardManager#858]
textFieldDidEndEditing not working when using IQKeyboardReturnKeyHandler. Other delegate methods are working fine. I can share a demo project if you want.

**Comment by hackiftekhar** [comment]
I verified that it's properly getting called with IQKeyboardReturnKeyHandler. You might be missing something. Make sure you assign textfield delegate and wrote same method name.
