### ISSUE TITLE
UITextView inside a UITableView does not scroll up and overlapping with keyboard

### ISSUE THREAD

**Issue by samantha-frost** [hackiftekhar/IQKeyboardManager#859]
I'm using **IQKeyboardManager** 4.0.9. when i tap on the **UiTextView** which contains inside a **UITableView** it does not scroll up and show the text view over the key board, instead the keyboard **overlaps** the **UITextView** and cover it up. should I use **IQTextView** instead of **UITextView**. for UITextFields the scrolling thing works properly.

and also previous and next buttons in keyboard works fine for UITextFields but they are not working properly when it comes to UITextViews.

**Comment by hackiftekhar** [comment]
@samantha-frost Could you please let me know if you was using UITableViewController or your UITableView was inside a UIViewController?
