### ISSUE TITLE
Change toolbar's barTintColor

### ISSUE THREAD

**Issue by Faydee1220** [hackiftekhar/IQKeyboardManager#863]
Hello, I found that there's toolbarTintColor to change the toolbar's button color, but is any way to change the toolbar's backgroundcolor? Like toolbar.barTintColor?

**Comment by hackiftekhar** [comment]
Currently there is no feature to set this property.

**Comment by hackiftekhar** [comment]
Feature will be available in this weekend.

**Comment by trickpirata** [comment]
Any updates on this?
