### ISSUE TITLE
Install Swift library via Carthage 

### ISSUE THREAD

**Issue by LiborZ** [hackiftekhar/IQKeyboardManager#864]
Hi, I tried to add IQKeyboardManagerSwift via Carthage and I get error:
```
...
*** Cloning IQKeyboardManagerSwift
A shell task (/usr/bin/env git clone --bare --quiet https://github.com/hackiftekhar/IQKeyboardManagerSwift.git /Users/liborzapletal/Library/Caches/org.carthage.CarthageKit/dependencies/IQKeyboardManagerSwift) failed with exit code 128:
fatal: could not read Username for 'https://github.com': terminal prompts disabled
```

What's wrong? How can I fix it? Thanks for help

**Comment by LiborZ** [comment]
The problem is only with this library. Anyone knows how to fix this?

**Comment by hackiftekhar** [comment]
https://github.com/hackiftekhar/IQKeyboardManagerSwift.git isn't a git repo. Correct repo is https://github.com/hackiftekhar/IQKeyboardManager.git
