### ISSUE TITLE
Toolbar has not disappeared when I gesture to return

### ISSUE THREAD

**Issue by Jayxiang** [hackiftekhar/IQKeyboardManager#867]
How to solve?  
![Toolbar](http://i1.piimg.com/1949/30f3d09750804b9c.png)

**Comment by hackiftekhar** [comment]
It does work fine for me. How did you reproduce the issue. Is there certain steps?

**Comment by Jayxiang** [comment]
Yes, first of all, I added a third party libraries - "FDFullscreenPopGesture", and then I click on the blank keyboard back, then I quickly gesture return, will appear this kind of situation.You can see the GIF.
![123](http://i1.piimg.com/1949/8e82c9f90512dcb3.gif)

**Comment by aimm** [comment]
Have you solved this ?

**Comment by hackiftekhar** [comment]
hmm, so @Jayxiang it only happens when you have ** FDFullscreenPopGesture** in project. right?

**Comment by aimm** [comment]
I have the same issue , and i have FDFullscreenPopGesture in project too.

**Comment by Jayxiang** [comment]
@aimm Haven't solve
@hackiftekhar yes,it only happens when I have FDFullscreenPopGesture in project.
