### ISSUE TITLE
keyboard doesn't scroll below textfield when pressed next button, but it will scroll below when i clicked it manually

### ISSUE THREAD

**Issue by tribeAppMobile** [hackiftekhar/IQKeyboardManager#869]
this is the form input
![screen shot 2017-06-04 at 11 09 02 am](https://cloud.githubusercontent.com/assets/25948128/26758878/924d52b2-4916-11e7-997a-d1d231e42a5d.png)

when  i clicked it manually it won't block my refferal code input
![screen shot 2017-06-04 at 11 09 26 am](https://cloud.githubusercontent.com/assets/25948128/26758883/b3428b86-4916-11e7-9ac8-5f063568e9e7.png)

but when i press next button from retype password to my refferal code, it won't scroll below my refferal code textfield

![screen shot 2017-06-04 at 11 09 36 am](https://cloud.githubusercontent.com/assets/25948128/26758885/dac38b10-4916-11e7-8e82-5d0868291842.png)

**Comment by hackiftekhar** [comment]
sorry for being late, but I think this might be because you the scrollView might not be getting correct content size. @tribeAppMobile can you please confirm?
