### ISSUE TITLE
how to change the Toolbar's done button 's name

### ISSUE THREAD

**Issue by KimBin** [hackiftekhar/IQKeyboardManager#87]
hi,i am a chinese coder, i want to change the Toolbar ' done into chinese that "确认", how i make it, thank you very much.

**Comment by adromil** [comment]
Can you create an API for this so instead of modifying your class we can change it via method.

**Comment by hackiftekhar** [comment]
There is already a property now to change done button text. Please check IQKeyboardManager.h

**Comment by ARGAMX** [comment]
This property called "toolbarDoneBarButtonItemText".
You can set it:
`[IQKeyboardManager sharedManager].toolbarDoneBarButtonItemText = @"Супер";`
