### ISSUE TITLE
Guideline 2.5.1 - Performance - Software Requirements

### ISSUE THREAD

**Issue by lenovodns** [hackiftekhar/IQKeyboardManager#870]
2017年6月7日 上午2:01
发件人 Apple
2. 5 Performance: Software Requirements
Guideline 2.5.1 - Performance - Software Requirements

Your app still uses or references the following non-public APIs:

- ‘_UINavigationBarBackground’ 

The use of non-public APIs is not permitted on the App Store because it can lead to a poor user experience should these APIs change.

Next Steps

To resolve this issue, please revise your app to remove any non-public APIs. If you have defined methods in your source code with the same names as the above-mentioned APIs, we suggest altering your method names so that they no longer collide with Apple's private APIs to avoid your app being flagged in future submissions.

Additionally, if you are using third-party libraries, please update to the most recent version of those libraries. If you do not have access to the libraries' source, you may be able to search the compiled binary using the "strings" or "otool" command line tools. The "strings" tool can output a list of the methods that the library calls and "otool -ov" will output the Objective-C class structures and their defined methods. These tools can help you narrow down where the problematic code resides. You could also use the "nm" tool to verify if any third-party libraries are calling these APIs.

Resources

For information on the "nm" tool, please review the "nm tool" Xcode manual page.

If there are no alternatives for providing the functionality your app requires, you can file an enhancement request.

**Comment by hackiftekhar** [comment]
Hey @lenovodns I think this is not due to my library now, because IQKeybaordManager isn't referencing **_UINavigationBarBackground** class. Can you please search this in your project if it's references by another library or your own code? Can you please also check you are not using any static library (.a .framework), if yes then please search this reference inside that static library using nm tool.

**Comment by lenovodns** [comment]
IQKeybaordManager v4.0.10

https://github.com/hackiftekhar/IQKeyboardManager/blob/master/IQKeyboardManager/IQToolbar/IQBarButtonItem.m

[ +(void)initialize {...} ]

**Comment by hackiftekhar** [comment]
@Legoless I do not find where I'm using private API at that part of code.
