### ISSUE TITLE
 Guideline 2.3.1 - Performance   Guideline 2.5.1 - Performance - Software Requirements

### ISSUE THREAD

**Issue by HTMLParser** [hackiftekhar/IQKeyboardManager#871]
2017年6月8日 上午3:30
发件人 Apple

    2. 3 Performance: Accurate Metadata
    2. 5 Performance: Software Requirements

Guideline 2.3.1 - Performance

Thank you for resubmitting your app. We have continued the review and would like to provide our findings.

We noticed that your app contains hidden features. Specifically, the use of UIToolbarButton and UIToolbarTextButton.

You will experience a delayed review process if you deliberately disregard the App Store Review Guidelines, ignore previous rejection feedback in future app submissions, or use your app to mislead or deceive users.

Additional Information

We want to provide a safe experience for users to get apps and a great opportunity for all developers to be successful.

Deliberate disregard of the App Store Review Guidelines and attempts to deceive users or undermine the review process is a direct violation of section 3.2(f) of the Apple Developer Program License Agreement. Continuing to violate the Terms & Conditions of the Apple Developer Program will result in the termination of your account, as well as any related or linked accounts, and the removal of all your associated apps from the App Store.

If you believe we have misunderstood or misinterpreted the intent of your app, you may submit an appeal for consideration or provide additional clarification by responding directly to this message in Resolution Center in iTunes Connect.

Guideline 2.5.1 - Performance - Software Requirements

Your app uses or references the following non-public APIs:

UIToolbarButton, UIToolbarTextButton

The use of non-public APIs is not permitted on the App Store because it can lead to a poor user experience should these APIs change.

Next Steps

To resolve this issue, please revise your app to remove any non-public APIs. If you have defined methods in your source code with the same names as the above-mentioned APIs, we suggest altering your method names so that they no longer collide with Apple's private APIs to avoid your app being flagged in future submissions.

Additionally, if you are using third-party libraries, please update to the most recent version of those libraries. If you do not have access to the libraries' source, you may be able to search the compiled binary using the "strings" or "otool" command line tools. The "strings" tool can output a list of the methods that the library calls and "otool -ov" will output the Objective-C class structures and their defined methods. These tools can help you narrow down where the problematic code resides. You could also use the "nm" tool to verify if any third-party libraries are calling these APIs.

Resources

For information on the "nm" tool, please review the "nm tool" Xcode manual page.

If there are no alternatives for providing the functionality your app requires, you can file an enhancement request.

**Comment by hackiftekhar** [comment]
hello @HTMLParser, I've already fixed this kind of issue with 4.0.10, this version removed the use of UIToolbarButton, UISearchBarTextField, private API usage.
@HTMLParser could you please let me know which version of library you submitted with app?

**Comment by HTMLParser** [comment]
4.0.7

**Comment by hackiftekhar** [comment]
That's why you get issue, please update to 4.0.10

**Comment by hackiftekhar** [comment]
I've also converted some of other private API calls using public API with this commit 96b0f077a78efdc68e30fbb53af0e993db97be24 so it would be better if you try with the master branch code.
