### ISSUE TITLE
2017年6月8日 Guideline 2.5.1 - Performance - Software Requirements    Performance: Software Requirements

### ISSUE THREAD

**Issue by meetWang** [hackiftekhar/IQKeyboardManager#872]
Dear sir,please read this mail from Apple which we received this morning, could you give us some tips to resolve this question?Look forward to your soonest reply。

Guideline 2.5.1 - Performance - Software Requirements

Your app uses or references the following non-public APIs:

UIToolbarButton, UISearchBarTextField UIPeripheralHostView
The use of non-public APIs is not permitted on the App Store because it can lead to a poor user experience should these APIs change.

Next Steps

To resolve this issue, please revise your app to remove any non-public APIs. If you have defined methods in your source code with the same names as the above-mentioned APIs, we suggest altering your method names so that they no longer collide with Apple's private APIs to avoid your app being flagged in future submissions.

Additionally, if you are using third-party libraries, please update to the most recent version of those libraries. If you do not have access to the libraries' source, you may be able to search the compiled binary using the "strings" or "otool" command line tools. The "strings" tool can output a list of the methods that the library calls and "otool -ov" will output the Objective-C class structures and their defined methods. These tools can help you narrow down where the problematic code resides. You could also use the "nm" tool to verify if any third-party libraries are calling these APIs.

Resources

For information on the "nm" tool, please review the "nm tool" Xcode manual page.

If there are no alternatives for providing the functionality your app requires, you can file an enhancement request.

**Comment by hackiftekhar** [comment]
hello @meetWang, I've already fixed this kind of issue with 4.0.10, this version removed the use of UIToolbarButton, UISearchBarTextField, private API usage. However UIPeripheralHostView doesn't looks to ve due to my library, please check if any other library is using this API.

**Comment by hackiftekhar** [comment]
@meetWang could you please let me know which version of library you submitted with app?

**Comment by meetWang** [comment]
I check it again,UIPeripheralHostView is not in this library. The version of it is not the latest,i will update it now.Thank you very much!
