### ISSUE TITLE
The toolbar is displayed when text is selected

### ISSUE THREAD

**Issue by satorumpen** [hackiftekhar/IQKeyboardManager#873]
Make the editable UITextView uneditable, then select the text, the toolbar will be displayed. See the capturing below. Pressing the edit button toggles the edit mode of UITextView. When the background is yellow, it is editable.

![output](https://user-images.githubusercontent.com/1177346/26927706-ec9406ec-4c8d-11e7-96eb-7e18b81ed07a.gif)

The sample code is as follows.
```
import UIKit
import IQKeyboardManagerSwift

class ViewController: UIViewController {
    @IBOutlet weak var textView: UITextView!
    @IBAction func tapEditButton(_ sender: UIButton) {
        textView.isEditable = !textView.isEditable
        textView.backgroundColor = textView.isEditable ? .yellow : .white
        sender.setTitle(textView.isEditable ? "Done" : "Edit", for: .normal)
    }

    override func viewDidLoad() {
        super.viewDidLoad()
        let manager = IQKeyboardManager.sharedManager()
        manager.enable = true
        manager.enableAutoToolbar = true
        //manager.enableDebugging = true
    }
}

```

Thanks

**Comment by hackiftekhar** [comment]
This is a known issue but this cannot be fix automatic by library due to some limitation. However this can be fix by developer, when you change isEditing property then please set textView.inputAccessoryView = nil; this will solve the issue.
