### ISSUE TITLE
Cannot enter

### ISSUE THREAD

**Issue by HanYaZhou1990** [hackiftekhar/IQKeyboardManager#874]
I use this tool on iOS8.1~8.4,Main page has two textField, push to the next page with the two textField, then I press home to the desktop, open other APP, wait for 30 seconds, press home to the desktop, click the icon to enter my APP, then found the keyboard after pop cannot enter the contents of each textField keyboard will disappear

**Comment by hackiftekhar** [comment]
Then it might be related to the iOS, because library isn't observing any event related to app foreground/background states.
