### ISSUE TITLE
IQKeyboardManager fails to work when applied with autolayout in Swift3

### ISSUE THREAD

**Issue by Abbiee** [hackiftekhar/IQKeyboardManager#875]
IQKeyboardManager doesn't moves the text fields up when it is used in swift3. Please have a look at it.
![screen shot 2017-06-11 at 6 12 05 pm](https://user-images.githubusercontent.com/5746432/27011632-8a154d9e-4edd-11e7-9f46-a6723f1823f5.png)

[LoginLayout-master 2.zip](https://github.com/hackiftekhar/IQKeyboardManager/files/1066483/LoginLayout-master.2.zip)

**Comment by hackiftekhar** [comment]
It doesn't work because you've added top layout guide constraint with the logo, and it's indirectly affecting the whole view to move up. If you would like to know how to deal with this situation then please read Manual Management guide.
