### ISSUE TITLE
Denied feedback on shelves

### ISSUE THREAD

**Issue by createname** [hackiftekhar/IQKeyboardManager#877]
2017年6月13日 上午1:38
发件人 Apple
2. 5 Performance: Software Requirements
Guideline 2.5.1 - Performance - Software Requirements

Your app uses or references the following non-public APIs:

UIToolbarButton, UIToolbarTextButton, UITableViewWrapperView, UISearchBarTextField, UITransitionView, _UIAlertControllerTextField

The use of non-public APIs is not permitted on the App Store because it can lead to a poor user experience should these APIs change.

**Comment by qq245168586** [comment]
Mee too

**Comment by hackiftekhar** [comment]
Please use latest master branch code, it contains all the fixes.
