### ISSUE TITLE
IQUIView+Hierarchy.swift Crash

### ISSUE THREAD

**Issue by Deepakapptunix17** [hackiftekhar/IQKeyboardManager#878]
There is an issue in the class - IQUIView+Hierarchy.swift on Line 68.

I am facing random crash on Line 68 of the class IQUIView+Hierarchy.swift which is in blow method :

public func viewController()->UIViewController? {
        
        var nextResponder: UIResponder? = self
        
        repeat {
            **nextResponder = nextResponder?.nextResponder()!**
            
            if let viewController = nextResponder as? UIViewController {
                return viewController
            }
            
        } while nextResponder != nil
        
        return nil
    }

I got this on the Fabric. Is there anything which I can do to resolve this crash because it is totally random crash.

Thanks

**Comment by hackiftekhar** [comment]
With current version, we currently have `nextResponder = nextResponder?.next` line and probably app will not crash with latest version.

**Comment by Deepakapptunix17** [comment]
@hackiftekhar You may be right Iftekhar but the problem is that the project I have is made in Swift 2.3 and I don't think I can convert it to Swift 3 right now as its very big project. Could you please spare 20-30 mins for and can we find a solution so that we can fix it for Swift 2.3.

Any Help will be much appreciated. Thanks a lot for you reply.

**Comment by hackiftekhar** [comment]
The problem is that I was unwrapping a value which may be nil

nextResponder()!

That's why sometime yiu fet crash. If you remove unwrap and fix compilation issue then it would be great.
