### ISSUE TITLE
_kbSize not being cleared if managed disabled

### ISSUE THREAD

**Issue by batkov** [hackiftekhar/IQKeyboardManager#879]
Hi, I found an issue regarding the fact that if you are playing around enable/disable state of IQKeyboard manager we could have following situation:

If IQKeyboardManager is DISABLED
In method `-(void)keyboardWillShow:(NSNotification*)aNotification`
we will set `_kbSize`
`_kbSize = intersectRect.size;`
and then
we return from this method
`if ([self privateIsEnabled] == NO)	return;`

Afterwards `- (void)keyboardWillHide:(NSNotification*)aNotification` is being called,
but we return from this method on line
`if ([self privateIsEnabled] == NO)	return;`
before clearing `_kbSize`

We need either **not to set _kbSize** if we are disabled, or **to clear it** even if we disabled.

**Comment by hackiftekhar** [comment]
hmm, you might be correct, I initialize it intentionally regardless if library is enable or not. Because if user enable library when keyboard was showing then it help to manage keyboard textfield distance on the fly.

It's better to clear it in keyboardWillHide: method.

**Comment by batkov** [comment]
Hi, @hackiftekhar 
Thanks for quick response, how long to wait for version with fix? It is something important for our project.

**Comment by hackiftekhar** [comment]
I can fix it soon, but next release might take some time bexause it's a rare condition and not much critical.
