### ISSUE TITLE
Toolbar Title Color

### ISSUE THREAD

**Issue by ajf-sp** [hackiftekhar/IQKeyboardManager#880]
Hi, thanks so much for this library! I know there's a way to set the toolbar title (the one where it copies the textfield placeholder) font. Was just wondering if there's a way to change the color? Right now it's always light gray.

**Comment by hackiftekhar** [comment]
Sorry, currently there is no way to do this.

**Comment by junweimah** [comment]
Hi

You know anyway I can disable the title text? Current my toolbar copy the placeholder of my textfield, which I dont want

**Comment by hackiftekhar** [comment]
@junweimah set `shouldShowToolbarPlaceholder = NO`

**Comment by evgeniagaletskaya** [comment]
@ajf-sp You can find IQTitleBarButtonItem file in your project and in method initWithTitle change the color that is set by default(lightGray)to any you want. Unfortunately, that will affect the color of title in all screens. That the only way I've found.
