### ISSUE TITLE
Disable IQKeyboardManager keyboard in specific Storyboard 

### ISSUE THREAD

**Issue by Naveentp** [hackiftekhar/IQKeyboardManager#881]
I have two storyboards in my project. In one of these storyboards I want default keyboard. Is there any way to disable the IQKeyboardManager to specific storyboard. If not, suggest any work arounds to resolve this. Need help.

**Comment by hackiftekhar** [comment]
yes, there is ways, please check manual management guide for workaround.

**Comment by Naveentp** [comment]
I have gone through the doc,

All I found is these methods,
```
IQKeyboardManager.sharedManager().disabledToolbarClasses.append(LoadMoneyVC.self)
IQKeyboardManager.sharedManager().disabledDistanceHandlingClasses.append(LoadMoneyVC.self)
IQKeyboardManager.sharedManager().disabledTouchResignedClasses.append(LoadMoneyVC.self)
```

I have almost 20 VC's in the storyboard and many more to come. If I have a chance to disable for whole storyboard would be helpful. If there, please provide the work around/Code snippet in this thread only.

**Comment by hackiftekhar** [comment]
There is no way to do that. However here are some of the things which can easy your task according to your requirement.
- If you would like to enable it for all except some view controllers then set **enabled=true** for library and use enablexxxClasses.append(viewController.self) method for blacklisting controllers.
- If you would like to disable it for all except some view controllers set **enabled=false** for library and use enablexxxClasses.append(viewController.self) method for whitelisting controllers.

**Comment by apwelsh** [comment]
Wait, is this right?  enable=true, then use enable___Classes to blacklist?  This seems backwards.  What would the enabled=true be in Objective-C?  Maybe that is where I am confused

**Comment by hackiftekhar** [comment]
@apwelsh ohh, sorry, you are correct. enable for whitelisting and disable for blacklisting. My bad.
