### ISSUE TITLE
The older version "canAdjustTextView", now  it was replaced? 

### ISSUE THREAD

**Issue by IPOSDai** [hackiftekhar/IQKeyboardManager#882]
I use UITextView, but there are some problems。I  look over the older version IQ, canAdjustTextView can  adjust textView's frame when it is too big in height.

the older code
//TextView handling

/*!
    @property canAdjustTextView

    @abstract Adjust textView's frame when it is too big in height. Default is NO.
 */
@property(nonatomic, assign) BOOL canAdjustTextView;

**Comment by hackiftekhar** [comment]
Now it's internally managed by setting contentInset of textView. So there is no need of this property, that's why it's removed.

**Comment by IPOSDai** [comment]
I understand, Thanks very much!
