### ISSUE TITLE
React-Native version

### ISSUE THREAD

**Issue by douglasjunior** [hackiftekhar/IQKeyboardManager#883]
Hi!

I want to thank for the incredible work in this library, and to inform that I create a version for React-Native: https://github.com/douglasjunior/react-native-keyboard-manager

I also referred to the IQKeyboardManager MIT license: https://github.com/douglasjunior/react-native-keyboard-manager#iqkeyboardmanager-license

Thank you again

**Comment by hackiftekhar** [comment]
Thanks for the kind word @douglasjunior
