### ISSUE TITLE
Not working when updating a label in TextView

### ISSUE THREAD

**Issue by phithapacl** [hackiftekhar/IQKeyboardManager#885]
in the event textViewDidChange I update a label text with the character count of the text view, but when updating the label the scroll stops woking and acts weird.

```
    func textViewDidChange(_ textView: UITextView) {
        
        self.currentSizeTextLabel.text =  String.init(format: "%i/%i", arguments: [textView.text.characters.count,maxLength])
    }
```

when I remove the line:
`     self.currentSizeTextLabel.text =  String.init(format: "%i/%i", arguments: [textView.text.characters.count,maxLength])`

it works fine, any ideas?

**Comment by hackiftekhar** [comment]
No idea since it's a simple change and shouldn't affect scrolliing
