### ISSUE TITLE
Not working on iPad 10.2

### ISSUE THREAD

**Issue by junestchick** [hackiftekhar/IQKeyboardManager#886]
Hi, my prob is it works my other devices and simu but not on my ipad with ios 10.2, the keyboard is cover textfields. I am using IQKeyboradManager 4.0.10.
Here is my login xib. 
http://imgur.com/fgAwKHg
The app is landscape. Thank for reading, sorry for my bad English!

**Comment by hackiftekhar** [comment]
Make sure any top layout guide or bottom layout guide constraints aren't attached directly or indirectly with the textFields.
