### ISSUE TITLE
Text View scrolling up even if cursor is not below keyboard

### ISSUE THREAD

**Issue by rakdev7** [hackiftekhar/IQKeyboardManager#887]
I have a text field at the top of the view controller and a text view is right below the text field. If I start typing in the text view, it automatically scrolls the whole view up by some pixels(like 100) there by hiding my text field.

How to prevent the view from scrolling up if the cursor is way above the keyboard? @hackiftekhar

**Comment by hackiftekhar** [comment]
You can set `keyboardDistanceFromTextField` on your textView object to appropriate value.
