### ISSUE TITLE
[UIKeyboardTaskQueue waitUntilAllTasksAreFinished] may only be called from the main thread.

### ISSUE THREAD

**Issue by kunal189** [hackiftekhar/IQKeyboardManager#888]
When i press a button to hit an api of updating my data on server before hiding the IQKeyBoard, app crashes once the response comes back from server and throughs this exception.
If is use IQKeyboardManager.sharedManager().resignFirstResponder() after pressing the button and before hitting the web service then it works fine.

**Comment by hackiftekhar** [comment]
I'm not sure why this issue happen but looks like this isn't related to my library.
