### ISSUE TITLE
EXC_BREAKPOINT IQUIView+IQKeyboardToolbar.swift line 0 specialized UIView.addPreviousNextDoneOnKeyboardWithTarget(AnyObject?, previousAction : Selector, nextAction : Selector, doneAction : Selector, titleText : String?) -> ()

### ISSUE THREAD

**Issue by pengkun** [hackiftekhar/IQKeyboardManager#890]
version:  4.0.8

Crashed: com.apple.main-thread
0  libdispatch.dylib              0x197de4cac _dispatch_dispose + 184
1  libdispatch.dylib              0x197de14a4 -[OS_dispatch_object _xref_dispose] + 60
2  libdispatch.dylib              0x197de14a4 -[OS_dispatch_object _xref_dispose] + 60
3  libdispatch.dylib              0x197de1868 -[OS_dispatch_source _xref_dispose] + 60
4  UIFoundation                   0x1940170f8 -[_UICache dealloc] + 144
5  UIKit                          0x18b8658a8 -[_UIAssetManager dealloc] + 100
6  UIKit                          0x18b85a818 -[_UIAssetManager initWithName:inBundle:idiom:] + 696
7  UIKit                          0x18b854b38 +[_UIAssetManager assetManagerForBundle:] + 212
8  UIKit                          0x18ba9b780 +[UIImage imageNamed:inBundle:compatibleWithTraitCollection:] + 92
9  IQKeyboardManagerSwift         0x10116807c specialized UIView.addPreviousNextDoneOnKeyboardWithTarget(AnyObject?, previousAction : Selector, nextAction : Selector, doneAction : Selector, titleText : String?) -> () (IQUIView+IQKeyboardToolbar.swift)
10 IQKeyboardManagerSwift         0x101163a28 @objc UIView.addPreviousNextDoneOnKeyboardWithTarget(AnyObject?, previousAction : Selector, nextAction : Selector, doneAction : Selector, titleText : String?) -> () (IQUIView+IQKeyboardToolbar.swift)
11 IQKeyboardManagerSwift         0x101133ff0 IQKeyboardManager.init() -> IQKeyboardManager (IQKeyboardManager.swift:784)
12 IQKeyboardManagerSwift         0x101142740 globalinit_33_1804EA4A44CDC62F5B66EAD58B4692DC_func2 (IQKeyboardManager.swift:159)
13 libdispatch.dylib              0x197de136c _dispatch_client_callout + 16
14 libdispatch.dylib              0x197de2244 dispatch_once_f + 96
15 IQKeyboardManagerSwift         0x101130688 static IQKeyboardManager.sharedManager() -> IQKeyboardManager (IQKeyboardManager.swift:163)
16 APPNAME                           0x100390bf0 specialized AppDelegate.setupConfig([UIApplicationLaunchOptionsKey : Any]?) -> () (AppDelegate.swift:83)
17 APPNAME                           0x10039136c specialized AppDelegate.application(UIApplication, didFinishLaunchingWithOptions : [UIApplicationLaunchOptionsKey : Any]?) -> Bool (AppDelegate.swift)
18 APPNAME                           0x10038f214 @objc AppDelegate.application(UIApplication, didFinishLaunchingWithOptions : [UIApplicationLaunchOptionsKey : Any]?) -> Bool (AppDelegate.swift)
19 UIKit                          0x18b86200c -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 304
20 UIKit                          0x18ba78fd4 -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 2284
21 UIKit                          0x18ba7b754 -[UIApplication _runWithMainScene:transitionContext:completion:] + 1480
22 UIKit                          0x18ba79dec -[UIApplication workspaceDidEndTransaction:] + 184
23 FrontBoardServices             0x18f2ad62c __31-[FBSSerialQueue performAsync:]_block_invoke + 28
24 CoreFoundation                 0x186ff6a28 __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 20
25 CoreFoundation                 0x186ff5b30 __CFRunLoopDoBlocks + 312
26 CoreFoundation                 0x186ff4154 __CFRunLoopRun + 1756
27 CoreFoundation                 0x186f210a4 CFRunLoopRunSpecific + 396
28 UIKit                          0x18b85b3c8 -[UIApplication _run] + 552
29 UIKit                          0x18b8563c0 UIApplicationMain + 1488
30 APPNAME                           0x1001b105c main (AppStoreUpdateRequest.swift:15)
31 libdyld.dylib                  0x197e0aa08 start + 4

**Comment by hackiftekhar** [comment]
Not sure why it's crashed. Do you know anything about this? Is this happening everytime?
