### ISSUE TITLE
When turning off autotoolbar - there is no way to dismiss the keyboard or see content behind it

### ISSUE THREAD

**Issue by grantkemp** [hackiftekhar/IQKeyboardManager#893]
Error: 
When disabling autotoolbar in code - the keyboard pushes the view up- covering part of the screen but there is no possible way to dismiss the keyboard. or see whats behind the keyboard.

Expected: 
When disabling the autotoolbar in code - then the current functionality where the view is pushed up to make way for the keyboard should work otherwise we should be able to click outside of the keyboard to dismiss it. 

Repeat: 
1. Add the following code to your appdelegate to enable this plugin, but get the autosuggest toolbar to not show
```IQKeyboardManager.sharedManager().enableAutoToolbar = false
        IQKeyboardManager.sharedManager().enable = true
```
2. Try dismiss they keyboard or select content behind it.

**Comment by hackiftekhar** [comment]
If developer disable autotoolbar then it's his responsibility to make some otger way to dismiss keyboard.
