### ISSUE TITLE
UITextView does not scroll automatically when subclassed

### ISSUE THREAD

**Issue by miltonleung** [hackiftekhar/IQKeyboardManager#896]
I have two UITextView subclasses in one UIScrollView. The problem is it when typing, the scroll view does not shift up, so the text is hidden behind the keyboard. In order to achieve the self-sizing text views, they have scrolling off.

I have tried using just UITextView without subclassing and it works fine, so I investigated the Subclass example in the sample project. This is what I have in the view controller: 
```
override internal class func initialize() {
    super.initialize()
    IQKeyboardManager.sharedManager().registerTextFieldViewClass(MyTextView.self, didBeginEditingNotificationName: Notification.Name.MyTextViewTextDidBeginEditingNotification.rawValue, didEndEditingNotificationName: Notification.Name.MyTextViewTextDidEndEditingNotification.rawValue)
  }

func textViewDidBeginEditing(_ textView: UITextView) {
    textView.reloadInputViews()
    IQKeyboardManager.sharedManager().reloadLayoutIfNeeded()
  }
```
 
And inside MyTextView class, I have 
```
  override func becomeFirstResponder() -> Bool {
    let becomeFirstResponder = super.becomeFirstResponder()
    NotificationCenter.default.post(name: Notification.Name.MyTextViewTextDidBeginEditingNotification, object: self)
    return becomeFirstResponder
  }

  override func resignFirstResponder() -> Bool {
    let resignFirstResponder = super.resignFirstResponder()
    NotificationCenter.default.post(name: Notification.Name.MyTextViewTextDidEndEditingNotification, object: self)
    return resignFirstResponder
  }
}

extension Notification.Name {
  static let MyTextViewTextDidBeginEditingNotification = Notification.Name("MyTextViewTextDidBeginEditing")
  static let MyTextViewTextDidEndEditingNotification = Notification.Name("MyTextViewTextDidEndEditing")
}
```

Am I missing anything here? Thanks

**Comment by hackiftekhar** [comment]
I don't know what you might be missing but if MyTextView is subclass of UITextView then you don't need to use `registerTextFieldViewClass` since it's for those subclasses which inherit from UIView and add purely it's own implementation for text input.

**Comment by miltonleung** [comment]
You're right. I noticed my subclass changes lineFragmentPadding and lineSpacing. Any idea on why that is? I actually set `    IQKeyboardManager.sharedManager().keyboardDistanceFromTextField = 200` in the AppDelegate too

**Comment by miltonleung** [comment]
this is a link to the demo project: https://github.com/miltonleung/keyboardTest
thanks!

**Comment by hackiftekhar** [comment]
@miltonleung you have to give a call to `reloadLayoutIfNeeded` method. Let's see if that works.
