### ISSUE TITLE
when I register keyboardWillShowWithNotification，and It failed

### ISSUE THREAD

**Issue by sandychales** [hackiftekhar/IQKeyboardManager#898]
when I register keyboardWillShowWithNotification to define my own inputVAccessoryView, it failed。  Xcode logs show that  "if we're in the real pre-commit handler we can't actually add any new fences due to CA restriction" which makes my observe failed。 How can I fix that problem? I 
 still failed even if I set enabel to IQKeyboardManager。

**Comment by hackiftekhar** [comment]
`if we're in the real pre-commit handler we can't actually add any new fences due to CA restriction` isn't due to my library and no relation with IQKeyboardManager. Now can you please explain what's the actual issue?
