### ISSUE TITLE
Please add your code to cocoapods

### ISSUE THREAD

**Issue by nathan-alden-sr** [hackiftekhar/IQKeyboardManager#9]
It would be handy if this library were available as a pod.

**Comment by blackchena** [comment]
I install it from cocoapod , but when I build it  ,I receive 
"Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_IQKeyboardManager", referenced from:
      objc-class-ref in UPAppDelegate.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)"
error . How should I do?

**Comment by hackiftekhar** [comment]
Could you please confirm you're getting this error by creating new project and install via cocoapods. FYI, this is cocoapods issue and not from the library.

**Comment by youbinbin** [comment]
3.3.7 is the last iOS 7 supported version.
ld: embedded dylibs/frameworks are only supported on iOS 8.0 and later (@rpath/IQKeyboardManager.framework/IQKeyboardManager) for architecture arm64

**Comment by nhatlee** [comment]
@hackiftekhar have any solution for work around?

**Comment by nhatlee** [comment]
@youbinbin go to `Build Phrases` -> `Link Binary With Libraries` then add `IQKeyboardManager.framework`. Then it's worked.
