### ISSUE TITLE
CollectionView did not scroll when using with UISearchBar

### ISSUE THREAD

**Issue by Amefuri** [hackiftekhar/IQKeyboardManager#901]
Hi,

I used IQKeyboardManagerSwift version 4.0.10
when I input text with UISearchBar, the collectionView didn't scroll even content was behind the keyboard.

I already enable IQKeyboardManagerSwift in AppDelegate and It work fine in another ViewController.

Thank you,

![simulator screen shot jul 17 2560 be 10 59 21 am](https://user-images.githubusercontent.com/1732314/28255272-271d243c-6adf-11e7-972a-89cdfe460e86.png)

**Comment by hackiftekhar** [comment]
This case cannot be fixed and you have to do some workaround by your own.

The library makes it's best effort to handle scenarios which are under control. But the thing with your case is that the library doesn't know that there is a collectionView which needs to be scroll. Library only know about the UISearchBar.

**Comment by Amefuri** [comment]
Thank you @hackiftekhar 
This clear me up about where did I need to handle it on my own.
