### ISSUE TITLE
Wrong view frame

### ISSUE THREAD

**Issue by loveforgeter** [hackiftekhar/IQKeyboardManager#902]
The frame view to be scroll maybe wrong when the view controller's `modalPresentationStyle` is `UIPresentaionCustom`, and its presentationController's frameOfPresentedViewInContainerView frame orgin is not CGPoint.zero. The frame adjust is wrong.

**Comment by hackiftekhar** [comment]
Hmm, ok. Can you please share a demo project so that I can take a look and modify library code to support this?
