### ISSUE TITLE
How can I hide the toolbar when an external keyboard is attached?

### ISSUE THREAD

**Issue by jlubeck** [hackiftekhar/IQKeyboardManager#903]
Basically what the title says 😄 

Thanks!

**Comment by jlubeck** [comment]
I found a way to find how to detect external keyboard, but I'm running 
```
[IQKeyboardManager sharedManager].enableAutoToolbar = NO;
```
And it is not removing it. 
I put a breakpoint on your code and `removeToolbarIfRequired` is being called, and `textField.inputAccessoryView = nil;` as well. But the toolbar is still there.

**Comment by hackiftekhar** [comment]
Are you sure you are't using your own inputAccessoryView?

**Comment by jlubeck** [comment]
Yes, completely sure. I don't use a custom inputAccesoryView anywhere in my code

**Comment by hackiftekhar** [comment]
Probably textField needs to use `reloadInputView` method.
