### ISSUE TITLE
Changing done button name for specific textView/textField

### ISSUE THREAD

**Issue by neokree** [hackiftekhar/IQKeyboardManager#905]
Hello,

It would be awesome to have a method for setting up the done button name instead of using the default one in the `addDoneOnKeyboardWithTarget` method.
For example I have a view with a textField that doesn't have a "Save" button, so I would use "Save" instead of "Done" for this method, and automatically call the save once the done button is pressed.

Let me know what you think about it

**Comment by hackiftekhar** [comment]
There is already a method `addRightButtonOnKeyboardWithText...` to provide custom name.

**Comment by neokree** [comment]
I didn't see it. 
Thank you for support
