### ISSUE TITLE
Constraints issue on Source compiled from xcode 9 beta 4. with swift 3.2

### ISSUE THREAD

**Issue by dipkasyap** [hackiftekhar/IQKeyboardManager#906]
Hello, There is constraints issue , when i compiled the code with Xcode 9 , Here is the screen shot 
![screen shot 2017-07-26 at 11 11 05 am](https://user-images.githubusercontent.com/12591229/28605876-9d73fff0-71f3-11e7-8c47-f0513d58dee2.png)

**Comment by narendra-r** [comment]
Happens for me also, on Xcode 9 beta 4 with Swift 3.2.

**Comment by ArthurAlvarez** [comment]
I also met this problem on Xcode 9 beta 4

**Comment by ryanvg** [comment]
I’m having the same problem with both Swift 3 and 4 using XCode 9, but it only appears in iOS 11.

**Comment by jaymathew** [comment]
same problem.  Xcode 9 beta 4

**Comment by shengdayan** [comment]
same problem . xcode 9 beta 5
