### ISSUE TITLE
IQKeyboardManagerSwift Conflict

### ISSUE THREAD

**Issue by qaisershehzad** [hackiftekhar/IQKeyboardManager#908]
I am using  IQKeyboardManagerSwift swift in my project. But now I am integrating a 3rd party SDK that has dependency on  DAKeyboardControl. My textfields toolbar not appearing when I add pod for DAKeyboardControl. After some digging I found this conflict 
Can you please advise what should I do?

IQKeyboardManager with DAKeyboardControl generate conflict.https://github.com/danielamitay/DAKeyboardControl

**Comment by hackiftekhar** [comment]
If that's the case then it would be better to use either one of the library for keyboard handling. The decision is upto you by checkingg how mugh you'll need according to current architecture.
