### ISSUE TITLE
TextView moves out of screen in FormSheet iPad

### ISSUE THREAD

**Issue by harshvishu** [hackiftekhar/IQKeyboardManager#909]
### _This is only happening on iPad_

When using a `TextView` in a `UIViewController` presented as **FormSheet**. The `TextView` moves up out of the screen.
I've attached a [Gif](http://www.giphy.com/gifs/xUn3C8iADSfPnDQI0w) displaying the issue

IQKeyboardManagerSwift: v 4.0
Swift: v 3.1
Xcode: V 8.3.3 (8E3004b)

**Comment by cs-joao-souza** [comment]
Same issue

**Comment by sryze** [comment]
I have the same problem with IQKeyboardManager 4.0.3 on iOS 11 GM - half of my navigation bar goest out of screen when keyboard opens, looks pretty ugly:

![screen shot 2017-09-14 at 10 59 38](https://user-images.githubusercontent.com/4525736/30412787-da26e402-993b-11e7-8a92-c6cb00b7fb15.png)

**Comment by hackiftekhar** [comment]
Thanks for sharing gif, I'll try to reproduce this issue.

**Comment by lingzlu** [comment]
Same problem here, is the fix on the way? I had to disable the IQKeyboardManger and manually handle keyboard :(

**Comment by hackiftekhar** [comment]
It will go out of the screen because library push the viewcontroller's view above to show full textView. However this situation needs some more optimization.
