### ISSUE TITLE
The whole layout jump right after user starts to type

### ISSUE THREAD

**Issue by s1ddok** [hackiftekhar/IQKeyboardManager#910]
The problem is that IQKeyboardManager seems to work fine, but until the moment the user actually starts typing. 

After first symbol is typed, the UI jumps down. Any hints on how to overcome this? I'm on iOS11, XCode 9b4.

**Comment by mnelso12** [comment]
Same issue

**Comment by renan-neb** [comment]
Same issue as well. iOS 10, Xcode 8

**Comment by okaris** [comment]
Can confirm iOS11 Beta 10

**Comment by Adelmaer** [comment]
Same iOS 11

**Comment by hackiftekhar** [comment]
Can someone attach any demo project so that I can look if this problem is due to this library?
