### ISSUE TITLE
TextView jumps and leaves a big white space above it 

### ISSUE THREAD

**Issue by BasantAshraf** [hackiftekhar/IQKeyboardManager#911]
TextView jumps and leaves a big white space above it .

This case happens in a textview inside a tableview that is inside a parallax scrollview
and textview typing without reaching the end of scrollview.

<img width="311" alt="screen shot 2017-07-29 at 9 49 39 pm" src="https://user-images.githubusercontent.com/14275187/28747793-de52bda2-74a7-11e7-8957-4920efcbee62.png">

**Comment by hackiftekhar** [comment]
It's fixed with new solution, changes are in `master` branch now. Let me know if it doesn't work for you.
