### ISSUE TITLE
Found nil while unwrapping an Optional value 

### ISSUE THREAD

**Issue by askari01** [hackiftekhar/IQKeyboardManager#915]
Selecting textfield causes the app to crash 
<img width="1280" alt="screen shot 2017-08-02 at 7 00 45 pm" src="https://user-images.githubusercontent.com/6830947/28877212-1bc630a0-77b5-11e7-9618-883ad9e8f702.png">

**Comment by hackiftekhar** [comment]
It's with your nurseAvailability class
