### ISSUE TITLE
Build Failed with exit code 1

### ISSUE THREAD

**Issue by livefreeor** [hackiftekhar/IQKeyboardManager#916]
I am getting this swift complier Error when building. I have tried alt+cmd+shift+k cleaning, also tried restarting Xcode but didn't work. What is wrong here? Thanks for your help.

Command  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1

**Comment by hackiftekhar** [comment]
I don't know what might be the cause, but looks like it's not due to my library.

**Comment by livefreeor** [comment]
thanks for your quick reply. Can you give me any other alternative solution like yours because normally my app builds successfully but it doesn't after installing your library and gives me above mentioned error. Thanks a lot again.

**Comment by hackiftekhar** [comment]
You should check build logs in Xcode. You'll probably see something useful there.
