### ISSUE TITLE
Done/Next Button offscreen/invisible

### ISSUE THREAD

**Issue by likeaj6** [hackiftekhar/IQKeyboardManager#917]
For some reason, my Done button + the Next/Previous buttons are hidden and/or offscreen. 

In the picture below, the done button is only off screen, but in my other textfield, it just doesn't appear at all. The action would still go through If I press a few times in its general area(where it's supposed to be).

 It's the same case with the next button, except it is not appearing either but still works if I press in the general vicinity.

Running on iOS11, Swift 3.1 and Xcode 9 beta

![img_7879](https://user-images.githubusercontent.com/13268856/28943187-ad34bab4-7852-11e7-8314-a3250cde67bb.jpg)

**Comment by hackiftekhar** [comment]
Currently iOS11 isn't supported.

**Comment by krunalbhavsar** [comment]
I'm also facing same problem. 
Please look into dear. 

Beta 5 is launched 2 days ago and now there will be GMSeed release.

You are really doing a great job.
