### ISSUE TITLE
isAskingCanBecomeFirstResponder is removed

### ISSUE THREAD

**Issue by ahmadabudawod** [hackiftekhar/IQKeyboardManager#918]
After i update my Cocoapods , this field is isAskingCanBecomeFirstResponder removed . How i can open Another view when click on UITextfield?

**Comment by hackiftekhar** [comment]
Please see release notes, now you can do with the approach as we did in otger project. You can also check demo app.

**Comment by perlasivakrishna** [comment]
could u please give me an idea for alternative to "isAskingCanBecomeFirstResponder" ?

**Comment by SebastianKumor** [comment]
@perlasivakrishna how did you replace `isAskingCanBecomeFirstResponder`?

**Comment by perlasivakrishna** [comment]
@SebastianKumor. Now no need to use "isAskingCanBecomeFirstResponder". The textfield should begin editing called only once.

**Comment by SebastianKumor** [comment]
@perlasivakrishna alright, thanks for response

**Comment by ZHSY** [comment]
if there three textField， i only need two of them can response  ‘goBefore: '<',‘goNext’: '>' button can u help me how to use this lib do it

**Comment by hackiftekhar** [comment]
hmm @ZHSY, actually this isn't supported currently because current library logic is to find all textFields which are in same subview, but it's a good idea to add a BOOL property to ignore any textField.

**Comment by hackiftekhar** [comment]
@ZHSY I'm adding `ignoreSwitchingByNextPrevious` BOOL to a UIView cateogory class, so you'll have the ability to to ignore any textfield or textview seeing by the library.

**Comment by ZHSY** [comment]
thanks for response
