### ISSUE TITLE
if textview is on uitableviewcell, the content is covered by the keybord

### ISSUE THREAD

**Issue by theHeroisBack** [hackiftekhar/IQKeyboardManager#920]
my textview's height

 is auto changing ,but when the words is too much,it will be covered by the keyboard,how can i fix this bug.

thank you .
ps:i come from China,  My English sucks 。。。

**Comment by jaja-digitalspaceexplorer** [comment]
Does your textview covers the entire screen? If so, you can refer to this [Sample](https://github.com/hackiftekhar/IQKeyboardManager/blob/master/MANUAL%20MANAGEMENT.md#working-with-full-screen-uitextview)

**Comment by theHeroisBack** [comment]
thank you bro,but this sample is not working for me .

i creat a tableview with custom(use code, not xib)  UITableViewCell, so I put a YYTxetView in this  UITableViewCell, and I make the cell'height is auto changing with the YYTextView'text, I did it success. like this 
![img_2325](https://user-images.githubusercontent.com/30762999/29556114-621451de-8757-11e7-8337-caaa8163ca1c.PNG)
![img_2326](https://user-images.githubusercontent.com/30762999/29556124-6b73d1a0-8757-11e7-822b-6bd07a794fce.PNG)

but when i insert more text like this :


![img_2327](https://user-images.githubusercontent.com/30762999/29556615-ec6baa48-8758-11e7-8ef7-c9d1bf13ba69.PNG)
![img_2328](https://user-images.githubusercontent.com/30762999/29556614-ec6a139a-8758-11e7-9c9b-1f1b6898043f.PNG)
![img_2329](https://user-images.githubusercontent.com/30762999/29556616-ed1b74fa-8758-11e7-8f9a-60b398f48370.PNG)


like the photos, the textview is covered by the keyboard, do you have any ideas to fix it ??

**Comment by Jayxiang** [comment]
@theHeroisBack  你试试reloadLayoutIfNeeded 可以吗

**Comment by daizhipeng** [comment]
UITableView中，每个cell中都有一个TextView（滚动禁用，高度根据文字变化），当TextView内容上至导航栏底部，下至键盘顶部时。TextView换行时会抖动有办法吗？

**Comment by hackiftekhar** [comment]
Can you please provide me any demo project to debug this issue?

**Comment by annjawn** [comment]
I am facing the same issue. I have pretty much the same layout with tableview cells with `UITextView` in them. The tableview cell will increase in height as the user types text into it, but eventually the typed text ends up being hidden by the keyboard at which point you will need to scroll it back up. Not sure how to resolve this.

**Comment by annjawn** [comment]
#1240 solved the issue.

**Comment by mehmetkoca** [comment]
I am having a similar problem. When I press the return key, the screen moves to the new line, but the screen does not move up. Is there a solution to this problem?

**Comment by mehmetkoca** [comment]
I am having a similar problem. When I press the return key, the screen moves to the new line, but the screen does not move up. Is there a solution to this problem?
