### ISSUE TITLE
ViewControllers does not rotate with keyboard

### ISSUE THREAD

**Issue by sweetdream0729** [hackiftekhar/IQKeyboardManager#923]
Thanks for your good stuff.
btw, when I rotate device on status keyboard is showed, keyboard does rotate.
But viewcontroller does not rotate and after hide keyboard whole app does not rotate eventhough app works for rotation before show keyboard.
Looking forward to hear from you.

**Comment by hackiftekhar** [comment]
hmm, I'm not sure if it's related to the library, can you please try removing library and then try to reproduce the issue?

If issue has will not reproduce after removing library then let me know.

**Comment by sweetdream0729** [comment]
If I remove keyboard library, viewcontroller works for rotation.

**Comment by hackiftekhar** [comment]
@sweetdream0729 can you please share a demo project?
