### ISSUE TITLE
Keyboard still covers a focused UITextField

### ISSUE THREAD

**Issue by noordawod** [hackiftekhar/IQKeyboardManager#924]
Hi there.

Thanks for a wonderful piece of software!

I began using the library today and noticed that if there's a UITextField situated in the lower part of the screen (where the keyboard would show when engaged), that field would still be hidden behind the keyboard.

Only after I press Back and then Next (arrow buttons to navigate between fields) that the screen panes correctly and shows the field.

I'm using this piece of code called from the relevant `application(didFinishLaunchingWithOptions:)` methods:

```swift
  func setupKeyboardManager() {
      let keyboardMgr = IQKeyboardManager.sharedManager()
      keyboardMgr.enable = true
      keyboardMgr.shouldResignOnTouchOutside = true
      keyboardMgr.layoutIfNeededOnUpdate = true
  }
```

Also, just having `IQKeyboardManager.sharedManager().enable = true` doesn't work either.

What am I doing wrong?

**Comment by noordawod** [comment]
I activated debugging, and here's the log when I tap the UITextField positioned at the bottom of the screen:

```
IQKeyboardManager: ****** textFieldViewDidBeginEditing started ******
IQKeyboardManager: ****** addToolbarIfRequired() started ******
IQKeyboardManager: Found 2 responder sibling(s)
IQKeyboardManager: ****** addToolbarIfRequired() ended: 0.0492719582980499 seconds ******
IQKeyboardManager: Saving <<iPhoneApp.IntroViewController: 0x14cd808b0> 0x000000014cd808b0> beginning frame : (0.0, 0.0, 320.0, 568.0)
IQKeyboardManager: ****** textFieldViewDidBeginEditing ended: 0.055076333344914 seconds ******
IQKeyboardManager: UIKeyboard Size : (320.0, 297.0)
IQKeyboardManager: ****** keyboardWillShow started ******
IQKeyboardManager: ****** adjustFrame() started ******
IQKeyboardManager: Need to move: 164.5
IQKeyboardManager: Saving <<SCScrollView: 0x14d030000; baseClass = UIScrollView; frame = (0 0; 320 568); autoresize = W+H; gestureRecognizers = <NSArray: 0x14ce30d60>; layer = <CALayer: 0x14ce2b5b0>; contentOffset: {0, 0}; contentSize: {320, 0}> 0x000000014d030000> contentInset : UIEdgeInsets(top: 0.0, left: 0.0, bottom: 0.0, right: 0.0) and contentOffset : (0.0, 0.0)
IQKeyboardManager: Adjusting -164.5 to <<SCScrollView: 0x14d030000; baseClass = UIScrollView; frame = (0 0; 320 568); autoresize = W+H; gestureRecognizers = <NSArray: 0x14ce30d60>; layer = <CALayer: 0x14ce2b5b0>; contentOffset: {0, 0}; contentSize: {320, 0}> 0x000000014d030000> ContentOffset
IQKeyboardManager: Remaining Move: 0.0
IQKeyboardManager: <<SCScrollView: 0x14d030000; baseClass = UIScrollView; frame = (0 0; 320 568); autoresize = W+H; gestureRecognizers = <NSArray: 0x14ce30d60>; animations = { bounds.origin=<CASpringAnimation: 0x14e172d50>; bounds.size=<CASpringAnimation: 0x14e172e10>; }; layer = <CALayer: 0x14ce2b5b0>; contentOffset: {0, 164.5}; contentSize: {320, 0}> 0x000000014d030000> old ContentInset : UIEdgeInsets(top: 0.0, left: 0.0, bottom: 0.0, right: 0.0)
IQKeyboardManager: <<SCScrollView: 0x14d030000; baseClass = UIScrollView; frame = (0 0; 320 568); autoresize = W+H; gestureRecognizers = <NSArray: 0x14ce30d60>; animations = { bounds.origin=<CASpringAnimation: 0x14e172d50>; bounds.size=<CASpringAnimation: 0x14e172e10>; bounds.origin-2=<CASpringAnimation: 0x14e20cde0>; bounds.size-2=<CASpringAnimation: 0x14e20c520>; }; layer = <CALayer: 0x14ce2b5b0>; contentOffset: {0, 0}; contentSize: {320, 0}> 0x000000014d030000> new ContentInset : UIEdgeInsets(top: 0.0, left: 0.0, bottom: 297.0, right: 0.0)
IQKeyboardManager: Moving Upward
IQKeyboardManager: Set Optional("<<iPhoneApp.IntroViewController: 0x14cd808b0> 0x000000014cd808b0>") frame to : (0.0, 0.0, 320.0, 568.0)
IQKeyboardManager: ****** adjustFrame() ended: 0.00808599998708814 seconds ******
IQKeyboardManager: ****** keyboardWillShow ended: 0.00833320827223361 seconds ******
IQKeyboardManager: ****** keyboardDidShow started ******
IQKeyboardManager: ****** keyboardDidShow ended: 0.000365541665814817 seconds ******
```

As I mentioned earlier, the view doesn't move and the keyboard continues to cover the field.

**Comment by hackiftekhar** [comment]
This might be because your SCScrollView doesn't correctly calculating it's Content Height, if you see in logs then you'll find `contentSize: {320, 0}` which means your scrollView content have 0 height but it should be something else I assume.

Can you please try adding correct constraint in order to calculate scrollView contentSize properly? If you are dealing programmatically then can you please try setting it's contentSize?

**Comment by noordawod** [comment]
I don't use a UIScrollView.

**Comment by ARGAMX** [comment]
The same problem.
This is the video how 'IQKeyboardManager', '4.0.10' works on iOS 10.3.3 iPhone 6S.
https://youtu.be/DXhhZOuM6YM

**Comment by noordawod** [comment]
Since yesterday when I reported this, I already switched to my own solution. If you're interested in this, @ARGAMX, head over to this Gist:

https://gist.github.com/noordawod/24d32b2ce8363627ea73d7e5991009a0

**Comment by hackiftekhar** [comment]
@noordawod, you are having UIScrollView somewhere, logs clearly says that. Please check your view hierarchy once again. Yoo are having `SCScrollView` somewhere in hierarchy.

**Comment by noordawod** [comment]
Maybe I have. For the time being, though, I decided to just roll with my own solution which fits my needs perfectly. I may have had a scroll view somewhere, but that's history now. I don't use any now.

**Comment by hackiftekhar** [comment]
Okay, great!

**Comment by ashish-naik** [comment]
@hackiftekhar I am facing the issue and here is my debug log. i am using scroll view and it is calculating the size. 

Pls suggest what could be the poblem. is "Need to move: -380.0" causing problem?

===================================================================

IQKeyboardManager: ****** textFieldViewDidBeginEditing started ******
IQKeyboardManager: ****** addToolbarIfRequired() started ******
IQKeyboardManager: Found 10 responder sibling(s)
IQKeyboardManager: ****** addToolbarIfRequired() ended: 0.00368506700033322 seconds ******
IQKeyboardManager: Saving <<UITabBarController: 0x7ff7f001c000> 0x00007ff7f001c000> beginning frame : (0.0, 0.0, 320.0, 568.0)
IQKeyboardManager: ****** textFieldViewDidBeginEditing ended: 0.0042934749944834 seconds ******
IQKeyboardManager: UIKeyboard Size : (320.0, 44.0)
IQKeyboardManager: ****** keyboardWillShow started ******
IQKeyboardManager: ****** adjustFrame() started ******
IQKeyboardManager: _**Need to move: -380.0**_
IQKeyboardManager: Saving <<UIScrollView: 0x7ff7ee93d000; frame = (0 64; 320 504); clipsToBounds = YES; autoresize = RM+BM; gestureRecognizers = <NSArray: 0x604000e44dd0>; layer = <CALayer: 0x600000a2a480>; **contentOffset: {0, 0}; contentSize: {320, 608};** adjustedContentInset: {0, 0, 0, 0}> 0x00007ff7ee93d000> contentInset : UIEdgeInsets(top: 0.0, left: 0.0, bottom: 0.0, right: 0.0) and contentOffset : (0.0, 0.0)
IQKeyboardManager: <<UIScrollView: 0x7ff7ee93d000; frame = (0 64; 320 504); clipsToBounds = YES; autoresize = RM+BM; gestureRecognizers = <NSArray: 0x604000e44dd0>; layer = <CALayer: 0x600000a2a480>; contentOffset: {0, 0}; contentSize: {320, 608}; adjustedContentInset: {0, 0, 0, 0}> 0x00007ff7ee93d000> old ContentInset : UIEdgeInsets(top: 0.0, left: 0.0, bottom: 0.0, right: 0.0)
IQKeyboardManager: <<UIScrollView: 0x7ff7ee93d000; frame = (0 64; 320 504); clipsToBounds = YES; autoresize = RM+BM; gestureRecognizers = <NSArray: 0x604000e44dd0>; layer = <CALayer: 0x600000a2a480>; contentOffset: {0, 0}; contentSize: {320, 608}; adjustedContentInset: {0, 0, 44, 0}> 0x00007ff7ee93d000> new ContentInset : UIEdgeInsets(top: 0.0, left: 0.0, bottom: 44.0, right: 0.0)
IQKeyboardManager: Moving Downward
IQKeyboardManager: Set Optional("<<UITabBarController: 0x7ff7f001c000> 0x00007ff7f001c000>") frame to : (0.0, 0.0, 320.0, 568.0)
IQKeyboardManager: ****** adjustFrame() ended: 0.00233334499353077 seconds ******
IQKeyboardManager: ****** keyboardWillShow ended: 0.00244621098681819 seconds ******
IQKeyboardManager: ****** keyboardDidShow started ******
IQKeyboardManager: ****** keyboardDidShow ended: 0.000180125003680587 seconds ******
IQKeyboardManager: ****** textFieldViewDidEndEditing started ******
IQKeyboardManager: ****** textFieldViewDidEndEditing ended: 0.000119132004329003 seconds ******
IQKeyboardManager: ****** keyboardWillHide started ******
IQKeyboardManager: Restoring <<UIScrollView: 0x7ff7ee93d000; frame = (0 64; 320 504); clipsToBounds = YES; autoresize = RM+BM; gestureRecognizers = <NSArray: 0x604000e44dd0>; layer = <CALayer: 0x600000a2a480>; contentOffset: {0, 0}; contentSize: {320, 608}; adjustedContentInset: {0, 0, 0, 0}> 0x00007ff7ee93d000> contentInset to : UIEdgeInsets(top: 0.0, left: 0.0, bottom: 0.0, right: 0.0) and contentOffset to : (0.0, 0.0)
IQKeyboardManager: Restoring <<UITabBarController: 0x7ff7f001c000> 0x00007ff7f001c000> frame to : (0.0, 0.0, 320.0, 568.0)
IQKeyboardManager: ****** keyboardWillHide ended: 0.00106576300458983 seconds ******
IQKeyboardManager: ****** textFieldViewDidBeginEditing started ******
IQKeyboardManager: ****** addToolbarIfRequired() started ******
IQKeyboardManager: Found 10 responder sibling(s)
IQKeyboardManager: ****** addToolbarIfRequired() ended: 0.0089126410020981 seconds ******
IQKeyboardManager: ****** textFieldViewDidBeginEditing ended: 0.00913635100005195 seconds ******
IQKeyboardManager: ****** keyboardDidHide started ******
IQKeyboardManager: ****** keyboardDidHide ended: 3.66619933629408e-05 seconds ******
IQKeyboardManager: UIKeyboard Size : (320.0, 44.0)
IQKeyboardManager: ****** keyboardWillShow started ******
IQKeyboardManager: Saving <<UITabBarController: 0x7ff7f001c000> 0x00007ff7f001c000> beginning Frame: (0.0, 0.0, 320.0, 568.0)
IQKeyboardManager: ****** adjustFrame() started ******
IQKeyboardManager: Need to move: -265.0
IQKeyboardManager: Saving <<UIScrollView: 0x7ff7ee93d000; frame = (0 64; 320 504); clipsToBounds = YES; autoresize = RM+BM; gestureRecognizers = <NSArray: 0x604000e44dd0>; layer = <CALayer: 0x600000a2a480>; contentOffset: {0, 0}; contentSize: {320, 608}; adjustedContentInset: {0, 0, 0, 0}> 0x00007ff7ee93d000> contentInset : UIEdgeInsets(top: 0.0, left: 0.0, bottom: 0.0, right: 0.0) and contentOffset : (0.0, 0.0)
IQKeyboardManager: <<UIScrollView: 0x7ff7ee93d000; frame = (0 64; 320 504); clipsToBounds = YES; autoresize = RM+BM; gestureRecognizers = <NSArray: 0x604000e44dd0>; layer = <CALayer: 0x600000a2a480>; contentOffset: {0, 0}; contentSize: {320, 608}; adjustedContentInset: {0, 0, 0, 0}> 0x00007ff7ee93d000> old ContentInset : UIEdgeInsets(top: 0.0, left: 0.0, bottom: 0.0, right: 0.0)
IQKeyboardManager: <<UIScrollView: 0x7ff7ee93d000; frame = (0 64; 320 504); clipsToBounds = YES; autoresize = RM+BM; gestureRecognizers = <NSArray: 0x604000e44dd0>; layer = <CALayer: 0x600000a2a480>; contentOffset: {0, 0}; contentSize: {320, 608}; adjustedContentInset: {0, 0, 44, 0}> 0x00007ff7ee93d000> new ContentInset : UIEdgeInsets(top: 0.0, left: 0.0, bottom: 44.0, right: 0.0)
IQKeyboardManager: Moving Downward
IQKeyboardManager: Set Optional("<<UITabBarController: 0x7ff7f001c000> 0x00007ff7f001c000>") frame to : (0.0, 0.0, 320.0, 568.0)
IQKeyboardManager: ****** adjustFrame() ended: 0.00140542500594165 seconds ******
IQKeyboardManager: ****** keyboardWillShow ended: 0.00168993300758302 seconds ******
IQKeyboardManager: ****** keyboardDidShow started ******
IQKeyboardManager: ****** keyboardDidShow ended: 0.000192331994185224 seconds ******
IQKeyboardManager: ****** textFieldViewDidEndEditing started ******
IQKeyboardManager: ****** textFieldViewDidEndEditing ended: 0.000114290000055917 seconds ******
IQKeyboardManager: ****** textFieldViewDidBeginEditing started ******
IQKeyboardManager: ****** addToolbarIfRequired() started ******
IQKeyboardManager: Found 10 responder sibling(s)
IQKeyboardManager: ****** addToolbarIfRequired() ended: 0.00262819899944589 seconds ******
IQKeyboardManager: ****** adjustFrame() started ******
IQKeyboardManager: Need to move: -15.0
IQKeyboardManager: Adjusting 15.0 to <<UIScrollView: 0x7ff7ee93d000; frame = (0 64; 320 504); clipsToBounds = YES; autoresize = RM+BM; gestureRecognizers = <NSArray: 0x604000e44dd0>; layer = <CALayer: 0x600000a2a480>; contentOffset: {0, 90}; contentSize: {320, 608}; adjustedContentInset: {0, 0, 44, 0}> 0x00007ff7ee93d000> ContentOffset
IQKeyboardManager: Remaining Move: 0.0
IQKeyboardManager: <<UIScrollView: 0x7ff7ee93d000; frame = (0 64; 320 504); clipsToBounds = YES; autoresize = RM+BM; gestureRecognizers = <NSArray: 0x604000e44dd0>; animations = { bounds.origin=<CABasicAnimation: 0x604000c2af40>; bounds.size=<CABasicAnimation: 0x604000c2b220>; }; layer = <CALayer: 0x600000a2a480>; contentOffset: {0, 75}; contentSize: {320, 608}; adjustedContentInset: {0, 0, 44, 0}> 0x00007ff7ee93d000> old ContentInset : UIEdgeInsets(top: 0.0, left: 0.0, bottom: 44.0, right: 0.0)
IQKeyboardManager: <<UIScrollView: 0x7ff7ee93d000; frame = (0 64; 320 504); clipsToBounds = YES; autoresize = RM+BM; gestureRecognizers = <NSArray: 0x604000e44dd0>; animations = { bounds.origin=<CABasicAnimation: 0x604000c2af40>; bounds.size=<CABasicAnimation: 0x604000c2b220>; }; layer = <CALayer: 0x600000a2a480>; contentOffset: {0, 75}; contentSize: {320, 608}; adjustedContentInset: {0, 0, 44, 0}> 0x00007ff7ee93d000> new ContentInset : UIEdgeInsets(top: 0.0, left: 0.0, bottom: 44.0, right: 0.0)
IQKeyboardManager: Moving Upward
IQKeyboardManager: Set Optional("<<UITabBarController: 0x7ff7f001c000> 0x00007ff7f001c000>") frame to : (0.0, 0.0, 320.0, 568.0)
IQKeyboardManager: ****** adjustFrame() ended: 0.00122614500287455 seconds ******
IQKeyboardManager: ****** textFieldViewDidBeginEditing ended: 0.00407692199223675 seconds ******
IQKeyboardManager: UIKeyboard Size : (320.0, 44.0)
IQKeyboardManager: ****** keyboardWillShow started ******
IQKeyboardManager: ****** keyboardWillShow ended: 3.67739994544536e-05 seconds ******
IQKeyboardManager: ****** keyboardDidShow started ******
IQKeyboardManager: ****** keyboardDidShow ended: 9.07009962247685e-05 seconds ******
IQKeyboardManager: UIKeyboard Size : (320.0, 260.0)
IQKeyboardManager: ****** keyboardWillShow started ******
IQKeyboardManager: ****** adjustFrame() started ******
IQKeyboardManager: Need to move: 216.0
IQKeyboardManager: Adjusting -216.0 to <<UIScrollView: 0x7ff7ee93d000; frame = (0 64; 320 504); clipsToBounds = YES; autoresize = RM+BM; gestureRecognizers = <NSArray: 0x604000e44dd0>; layer = <CALayer: 0x600000a2a480>; contentOffset: {0, 75}; contentSize: {320, 608}; adjustedContentInset: {0, 0, 44, 0}> 0x00007ff7ee93d000> ContentOffset
IQKeyboardManager: Remaining Move: 0.0
IQKeyboardManager: <<UIScrollView: 0x7ff7ee93d000; frame = (0 64; 320 504); clipsToBounds = YES; autoresize = RM+BM; gestureRecognizers = <NSArray: 0x604000e44dd0>; animations = { bounds.origin=<CASpringAnimation: 0x604000c2ffc0>; bounds.size=<CASpringAnimation: 0x604000c2f5c0>; }; layer = <CALayer: 0x600000a2a480>; contentOffset: {0, 291}; contentSize: {320, 608}; adjustedContentInset: {0, 0, 44, 0}> 0x00007ff7ee93d000> old ContentInset : UIEdgeInsets(top: 0.0, left: 0.0, bottom: 44.0, right: 0.0)
IQKeyboardManager: <<UIScrollView: 0x7ff7ee93d000; frame = (0 64; 320 504); clipsToBounds = YES; autoresize = RM+BM; gestureRecognizers = <NSArray: 0x604000e44dd0>; animations = { bounds.origin=<CASpringAnimation: 0x604000c2ffc0>; bounds.size=<CASpringAnimation: 0x604000c2f5c0>; }; layer = <CALayer: 0x600000a2a480>; contentOffset: {0, 291}; contentSize: {320, 608}; adjustedContentInset: {0, 0, 260, 0}> 0x00007ff7ee93d000> new ContentInset : UIEdgeInsets(top: 0.0, left: 0.0, bottom: 260.0, right: 0.0)
IQKeyboardManager: Moving Upward
IQKeyboardManager: Set Optional("<<UITabBarController: 0x7ff7f001c000> 0x00007ff7f001c000>") frame to : (0.0, 0.0, 320.0, 568.0)
IQKeyboardManager: ****** adjustFrame() ended: 0.00191578599333297 seconds ******
IQKeyboardManager: ****** keyboardWillShow ended: 0.00200358800066169 seconds ******
IQKeyboardManager: ****** keyboardDidShow started ******
IQKeyboardManager: ****** keyboardDidShow ended: 8.24360031401739e-05 seconds ******

**Comment by ashish-naik** [comment]
Well i had some mistake in my code. 

Distance between text fields and keyboard is maintained as expected.

**Comment by amrboxit4me** [comment]
`         self.textField.attributedPlaceholder = NSAttributedString(string:self.textField.placeholder != nil ? self.textField.placeholder! : textField.placeholder!, attributes:[NSAttributedStringKey.foregroundColor: self.placeHolderColorValue,NSAttributedStringKey.font : UIFont().textFieldText()])
`
