### ISSUE TITLE
Next and Previous Button is disappear when use it in UITableViewController

### ISSUE THREAD

**Issue by sw-tt-sandipprajapati** [hackiftekhar/IQKeyboardManager#926]
Hello @hackiftekhar,

I have used this library and I have found the Next and Previous Button is disappear when use it in UITableViewController. Is there any way to resolve this.

Thanks.

**Comment by sw-tt-harishmistry** [comment]
I have also faced this issue, in case of UITableViewController, it just hides the Previous and Next buttons from InputAccessory view of Keyboard but however it shows the Done button over there.

Its kind of a weird issue here. Is there any class that we need to assign o Tablview or any other solution that you can provide, will be helpful.

Thank you.

**Comment by sw-tt-vanditmehta** [comment]
I have faced same issue once,

I have used it in one of my project with UITableViewController, where i have 15 static cells having UITextField - It showing me toolbar with done button but not getting "next" and "previous" button

**Comment by hackiftekhar** [comment]
@sw-tt-sandipprajapati, @sw-tt-harishmistry I'm not sure why you guys are getting next/previous button issues with UITableViewController however it's working just fine in my demo app UITableViewController example.

**Comment by arjavlad** [comment]
In iOS 11 (15A5362a) working fine
in iOS 10.3.3  App Crashes at
            if (siblings[0] == textField)
File: IQKeyboardManager.m
line: 1876
Method: addToolbarIfRequired

*** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndex:]: index 0 beyond bounds for empty array'

**Comment by hackiftekhar** [comment]
@arjavlad it's already fixed with latest version.

**Comment by arjavlad** [comment]
Yeah, It's working.
