### ISSUE TITLE
Swift 4 Xcode 9 beta 3 giving erros

### ISSUE THREAD

**Issue by KevinMac123** [hackiftekhar/IQKeyboardManager#927]
Please provide support of swift 4. Currently it is giving 48 errors when build project with Xcode 9 beta 3.

**Comment by thankmelater23** [comment]
I'm getting the same thing, and for some reason, I tried reverting back to older versions, and I'm still getting errors.😡

**Comment by mekarpatx** [comment]
Did you use the automatic swift conversion tool?

**Comment by thankmelater23** [comment]
Yes im on swift 4

**Comment by mekarpatx** [comment]
You dont have to convert to swift4. Swift 3 and 4 can work in the same project. 
I think problem is with the conversion tool. Dont use it until it gets better or iqkeyboardmanager releases a swift4 version. Hope this helps

**Comment by KevinMac123** [comment]
@mekarpatx  I haven't used conversion tool. As i am developing project from scratch.

**Comment by hackiftekhar** [comment]
I convert our project to swift4 and pushed changes in swift4 branch, once we get the public release of Xcode then we'll push another CocoaPods version

**Comment by ashchan** [comment]
@hackiftekhar The recent `swift4` branch seems to have new errors on Xcode beta 5.

It's about `UILayoutPriority.RawValue`.

```
 ../IQKeyboardManager/IQKeyboardManagerSwift/IQToolbar/IQTitleBarButtonItem.swift:111:78: Type 'UILayoutPriority' (aka 'Float') has no member 'RawValue'
```

**Comment by hackiftekhar** [comment]
I converted it using the beta 5, not sure why this happens to you. btw I used Xcode conversion tool to convert it.

**Comment by ashchan** [comment]
@hackiftekhar Sorry but after migrating the main project to Swift 4 the error went away. The migration tool has some issue to build and convert automatically.

**Comment by AalokParikh** [comment]
I got compile time errors for

**IQKeyboardManagerSwift/Categories/IQUIWindow+Hierarchy.swift :: Declarations in extensions cannot override yet**

**IQKeyboardManagerSwift/Categories/IQUIWindow+Hierarchy.swift :: Ambiguous use of 'topMostController()'**

For Xcode 9 beta 6

How to solve this issue?
![screen shot 2017-09-04 at 3 13 26 pm](https://user-images.githubusercontent.com/1628260/30021060-a9103a4a-9183-11e7-8382-efd6c24b68c3.png)

**Comment by aurora14** [comment]
@hackiftekhar I'm encountering the same error as @AalokParikh 

After some research, it seems like it's a more strict enforcement of the following rule by the compiler:
"Extensions can add new functionality to a type, but they cannot override existing functionality."
https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/Extensions.html

Some of the suggested fixes for overriding the topMostController() include subclassing UIWindow. 

However I could be wrong. Any suggestions on how to deal with this on our end? Or would this be something updated for the official Swift 4 release?
