### ISSUE TITLE
textfiled遮挡问题

### ISSUE THREAD

**Issue by ZClee128** [hackiftekhar/IQKeyboardManager#928]
在tableview 中键盘还是会挡住texfiled，不会上移

**Comment by hackiftekhar** [comment]
Please use english

**Comment by ZClee128** [comment]
In tableview, the keyboard will block texfiled and will not move up

**Comment by hackiftekhar** [comment]
Not sure why but it works in my demo. Can you please elaborate more?

**Comment by ZClee128** [comment]
Sometimes the tableview on the textfiled cannot move up, and the keyboard blocks textfiled

**Comment by hackiftekhar** [comment]
Are you using UITableViewController?

**Comment by ZClee128** [comment]
NO，using UITableView ，add in UIViewController

**Comment by ZClee128** [comment]
hello，man？

**Comment by ZClee128** [comment]
Can you solve my problem?

**Comment by hackiftekhar** [comment]
Not sure what might be the reason. Can you please check the demo app with table view examples and see if it works correctly?
