### ISSUE TITLE
Done button invisible.

### ISSUE THREAD

**Issue by Jaydeepvadalia** [hackiftekhar/IQKeyboardManager#929]
i install IQKeyboardManager via pod. Done button is not showing up on each keyboard. that is invisible.

set IQKeyboardManager.shared().isEnabled = true at appDelegate.swift file

Here blow is my screen
![screen shot 2017-08-15 at 1 47 23 am](https://user-images.githubusercontent.com/13176109/29290011-3f1177bc-815c-11e7-93f9-5d7b5f65a40d.png)

**Comment by Chr0nisch** [comment]
I got the same issue in Xcode 9.0 beta 5 (9M202q) with IQKeyboardManager 4.0.11 integrated by cocoa pods . The next, previous and done buttons are on the view and could be used, but have the same color as the toolbar in iOS11.

**Comment by linbx08** [comment]
Hi, were you able to solve this issue?

**Comment by hackiftekhar** [comment]
It's already fixed with latest version.

**Comment by linbx08** [comment]
Ah Fantastic!  in the new version `4.0.13` i have settled the problem, thank you very much

**Comment by dachev** [comment]
Any plans to fix this for Objective-C ?
