### ISSUE TITLE
Showing black space between UIKeyboard and View due to Sliding up Keyboard above View position.

### ISSUE THREAD

**Issue by hackiftekhar** [hackiftekhar/IQKeyboardManager#93]

**Comment by dongmai** [comment]
Seems it doesn't work on iOS 9.3.

**Comment by hackiftekhar** [comment]
Could you please share an screenshot of issue you are getting?

**Comment by dongmai** [comment]
![simulator screen shot apr 15 2016 10 33 13 am](https://cloud.githubusercontent.com/assets/3855966/14550738/7fe1eff6-02f5-11e6-82b8-127590c132b6.png)

**Comment by hackiftekhar** [comment]
Hmm, looks like you set `keyboardDistanceFromTextField` to something about 100-200, but still this shouldn't happen.

**Comment by dongmai** [comment]
No, I didn't touch `keyboardDistanceFromTextField` property.

**Comment by dongmai** [comment]
I used a ScrollView there to make it scrollable to select fields.

**Comment by hackiftekhar** [comment]
Are you sure your scrollView is calculating correct contentSize?

**Comment by dongmai** [comment]
Actually I didn't touch contentSize, I do auto layout config all on Storyboard. It displays fine when keyboard isn't showing. Weird!!!

**Comment by hackiftekhar** [comment]
Then could you please share a demo project?

**Comment by forsan** [comment]
Same issue here. iOS 9.3 before this version its working correctly.

<img width="761" alt="screen shot 2016-06-27 at 8 57 16 pm" src="https://cloud.githubusercontent.com/assets/1745621/16390104/c404265c-3ca9-11e6-850a-26d3ba5f32fd.png">
![simulator screen shot jun 27 2016 8 56 51 pm](https://cloud.githubusercontent.com/assets/1745621/16390103/c403796e-3ca9-11e6-9c9e-8e6e944e5888.png)

**Comment by hackiftekhar** [comment]
@forsan @dongmai Could you please share a demo project so that I can debug it?

**Comment by NikKovIos** [comment]
Same issue still exists.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/16647690/29619827-c6699784-8824-11e7-97b7-a095bd622b91.gif)

**Comment by ankitjaiswal1994** [comment]
IQKeyboardManager.sharedManager().canAdjustAdditionalSafeAreaInsets = true

Adding this to appdelegate resolved my problem.

**Comment by pradnyadikle4** [comment]
https://stackoverflow.com/questions/4374436/how-to-detect-when-keyboard-is-shown-and-hidden/27087733#27087733
and

    @objc func keyboardWillAppear() {
        //Do something here
        
        self.payTextView.frame.origin.y += self.view.safeAreaInsets.bottom
    }

    @objc func keyboardWillDisappear() {
        //Do something here
        self.payTextView.frame.origin.y -= self.view.safeAreaInsets.bottom

    }
fixed my issue.
