### ISSUE TITLE
Compile error: Xcode 8.3.3 / iOS Target 8

### ISSUE THREAD

**Issue by Blog404DE** [hackiftekhar/IQKeyboardManager#930]
Hi,

i’ve just updated the your library via pod update and got some compile error:

> IQKeyboardManager.m:200:52: error: assignment to readonly property
            strongSelf.resignFirstResponderGesture = [[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(tapRecognized:)];

After looking into IQKeyboardManager.h, the property seems really to be read-only:

```smalltalk
@property(nonnull, nonatomic, strong, readonly) UITapGestureRecognizer  *resignFirstResponderGesture;
```

I’ve configured the toolbar as followed:
```smalltalk
    [[IQKeyboardManager sharedManager] setEnableAutoToolbar:YES];
    [[IQKeyboardManager sharedManager] setShouldShowToolbarPlaceholder:NO];
    [[IQKeyboardManager sharedManager] setShouldToolbarUsesTextFieldTintColor:NO];
    [[IQKeyboardManager sharedManager] setShouldPlayInputClicks:YES];
    [[IQKeyboardManager sharedManager] setShouldResignOnTouchOutside:YES];
```
Did somebody got the same problem?

**Comment by wangdachui** [comment]
Yes, i got the same problem.

**Comment by hackiftekhar** [comment]
Can you guys try now?
