### ISSUE TITLE
未做越界判断

### ISSUE THREAD

**Issue by 90candy** [hackiftekhar/IQKeyboardManager#931]
以下问题是通过在github上面直接下载的Demo，并非使用CocoaPods导入
1， IQKeyboardManager.h  的第187行的resignFirstResponderGesture为可读属性，但是在IQKeyboardManager.m 的第200行初始化时报错

2，IQKeyboardManager.m 的1876行
 如果siblings数组为零时，会导致程序崩溃（与环信同在的时候，在环信自定义UI的搜索框就会触发siblings为空数组）
  if (siblings[0] == textField) { 。。。} //这里空数组直接判断就炸了

**Comment by hackiftekhar** [comment]
Issue 1 is fixed.

Issue 2 will never happen since if there is a textFieldView then siblings will also contain the textField, so there will be at least 1 siblings if textFieldView isn't nil, however I'll change that code with firstObject] method.

**Comment by hackiftekhar** [comment]
Issue2 is fixed now.
