### ISSUE TITLE
想设置某个页面禁用这个第三方库无法生效

### ISSUE THREAD

**Issue by yan2750** [hackiftekhar/IQKeyboardManager#932]
亲爱的开发人员：
我想在某些页面将你们这个库禁用了，但是用了文档中的方法都没有生效，请问是什么原因？
如果你们能解答我这个问题，我会灰常高兴的~~~
还有我的英文不太好，如果你们不看中文来信，请通知我~谢谢~

**Comment by hackiftekhar** [comment]
Can you please check how it's working with project demo app? If it's working in demo then either you might be making some mistakes or you might have a very special hierarchy configuration.

**Comment by Jayxiang** [comment]
@yan2750 我用的方法 都可以呀  你把写的代码贴一下
