### ISSUE TITLE
Multilanguage for Done button

### ISSUE THREAD

**Issue by nlhdung** [hackiftekhar/IQKeyboardManager#933]
Hi,
Thanks for your QKeyboardManager. I want to change "Done" button to my native language (Vietnamese), what should I change in your code/classes?

**Comment by sudhakarvarma** [comment]
@nlhdung Just follow 
#import "IQUIView+IQKeyboardToolbar.h"
in your viewDidLoad
[yourtextfield addRightButtonOnKeyboardWithText:@"LOGIN" target:self action:@selector(barButtonLoginAction:) titleText:@"Click Login to proceed"];

-(void)barButtonLoginAction:(id)sender{
//write your code after action
}

**Comment by hackiftekhar** [comment]
@nlhdung there is a property in IQKeyboardManager class to provide done button title, you can use that one to make global changes.

**Comment by danchokobo** [comment]
> @nlhdung there is a property in IQKeyboardManager class to provide done button title, you can use that one to make global changes.
HOW?????
