### ISSUE TITLE
The seacrhBar problem on the navigationItem

### ISSUE THREAD

**Issue by PromiscuousYouth** [hackiftekhar/IQKeyboardManager#937]
`UIView *titleView = [[UIView alloc] initWithFrame:CGRectMake(0, 0, 300, 30)];
    UISearchBar *searchBar = [[UISearchBar alloc] initWithFrame:titleView.bounds];
    searchBar.placeholder = @"Test";
    [titleView addSubview:searchBar];
    self.navigationItem.titleView = titleView;`

I'll crash in `IQKeyboardManager.m` 1876 line ,
What do I need to do?
Before that, need to set it to NO?
`[[IQKeyboardManager sharedManager] setEnable:NO];`

**Comment by hackiftekhar** [comment]
Can you please check with v4.0.13 now if this fix the issue? If it still doesn't fix the issue then probably you should disabled the library with the code you provided.

**Comment by PromiscuousYouth** [comment]
Thank you, v4.0.13 did fix the issue.

**Comment by whisper-bye** [comment]
It has been fixed, but not work any more

```swift
func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
    IQKeyboardManager.sharedManager().enable = true

    return true
}
```

**Comment by masuhara** [comment]
Why this closed??
