### ISSUE TITLE
Issue on UITapGestureRecognizer on IQKeyboardManager class version (4.0.12)

### ISSUE THREAD

**Issue by ramanocs1145** [hackiftekhar/IQKeyboardManager#938]
After update my pods and compile it, I have faced this kind of issue on IQKeyBoardManager class.

> Declaration of 'UITapGestureRecognizer` must be imported from module `UIKit.UITapGestureRecognizer` before it is required.

It's happening on When I compile on Simulator iPhone 6 (10.3.1) version, XCode 8.3.3
How can it fixed ?

Kindly suggest me.

**Comment by hackiftekhar** [comment]
Just pushed v4.0.13 with some bug fixes including this.

**Comment by Sam-iOS** [comment]
Declaration of 'UITapGestureRecognizer' must be imported from module 'UIKit.UITapGestureRecognizer' before it is required

i am working on iOS 9.  After update my pods and compile it, i have faced model issues error and its in 
i saw Declaration of 'UITapGestureRecognizer' must be imported from module 'UIKit.UITapGestureRecognizer' before it is required.

how this solve it

**Comment by hackiftekhar** [comment]
Please use v5.0.7
