### ISSUE TITLE
fatal error: attempt to bridge an implicitly unwrapped optional containing nil

### ISSUE THREAD

**Issue by prasenraj** [hackiftekhar/IQKeyboardManager#942]
public var shouldHideTitle: Bool? {
        get {
            let aValue: AnyObject? = objc_getAssociatedObject(self, &kIQShouldHideTitle) as AnyObject
            
            if aValue == nil {
                return false
            } else {
                return aValue as? Bool
            }
        }

i am getting error         let aValue: AnyObject? = objc_getAssociatedObject(self, &kIQShouldHideTitle) as AnyObject

how to fix it in swift 3.0

**Comment by hackiftekhar** [comment]
I'm not able to reproduce this crash.
