### ISSUE TITLE
IQKeyboardManager leads to a memory leaks

### ISSUE THREAD

**Issue by MsXMZ** [hackiftekhar/IQKeyboardManager#943]
xcode version 8.3.2, i use instruments to check,there is a leak on  file <IQTitleBarButtonItem.m> , 
leaks on the define  IQ_IS_IOS11_OR_GREATER,i don't know why

**Comment by hackiftekhar** [comment]
Thanks for the information, I'll try to take a look what may be wrong.

**Comment by hackiftekhar** [comment]
I've fixed most of the memory issues with v5.0.8 but due to a memory leak with iOS for it's UITextField, some objects might lead to memory leaks.
