### ISSUE TITLE
Avoid inner scrollView to scroll

### ISSUE THREAD

**Issue by cs-joao-souza** [hackiftekhar/IQKeyboardManager#945]
Hi,

I have an inner UICollectionView into a inner UIScrollView and the cells inside de CollectionView have textFields. I override the arrows actions in toolbar to have a customized navigation into my textsFields. But when i click in one of those arrows, the content inside my UICollectionView moves up and i have know ideia why.

Can you know how can i fix it? Actually i want to avoid my inner UICollectionView to respond to IQKeyboardManager events.

Thanks

**Comment by hackiftekhar** [comment]
There is no direct way. However you can set scrollEnabled=NO to not scroll your UICollectionView.

**Comment by cs-joao-souza** [comment]
But i need to scoll this collection horizontally. So it is not possible?

**Comment by hackiftekhar** [comment]
Then there is a problem. In this case I would suggest you to disable library and implement your own solution on that particular ViewControllwr.

**Comment by hackiftekhar** [comment]
Now there is a property `shouldIgnoreScrollingAdjustment` on `IQUIScrollView+Additions.h` category which should be set to YES to scrollView object to avoid scrolling by library.

**Comment by cs-joao-souza** [comment]
So, it will block all inner scrollviews to scroll?

**Comment by hackiftekhar** [comment]
Nope, @cs-joao-souza it will only avoid the scrollView you set shouldIgnoreScrollingAdjustment=YES

**Comment by cs-joao-souza** [comment]
But what scrollview does it ignore? Because the problem was if you have more than one scrollview and you select a textField inside the scrollview

**Comment by hackiftekhar** [comment]
It will ignore the scrollView you set `shouldIgnoreScrollingAdjustment=YES`. It depends on you about which scrollview you would like to avoid.

**Comment by cs-joao-souza** [comment]
Nice! Now i got it. Nicely done.

**Comment by hackiftekhar** [comment]
Thanks

**Comment by light-bo** [comment]
Nice!:smile:

**Comment by dilizarov** [comment]
shouldIgnoreScrollingAdjustment is what I've been looking for for the past few hours. Absolutely amazing.
