### ISSUE TITLE
textfield dosn't move 

### ISSUE THREAD

**Issue by AllenShan** [hackiftekhar/IQKeyboardManager#946]
Hello~
when i do appDelegate.window?.addSubview(av)
the textfield not move 

<img width="686" alt="2017-08-28 11 43 12" src="https://user-images.githubusercontent.com/12624936/29758435-218879fe-8be6-11e7-905d-f52521b0d9ca.png">

**Comment by hackiftekhar** [comment]
Library does not support textField directly added to UIWindow.
