### ISSUE TITLE
Placeholder text floating in upper left hand corner of screen...

### ISSUE THREAD

**Issue by MaximusMcCann** [hackiftekhar/IQKeyboardManager#947]
In a presented `viewController`, I select the `textField` and the keyboard & toolbar pops up, as expected, with the `Done` btn, but the placeholder text appears in the upper left hand corner of the entire screen.  This only happens on an actual Device, the simulator displays as expected :(.
This view hides the status bar, fwiw.
ios 11, iPhone 6
I believe this is only due to TestFlight builds that are built with Xcode 8 as I cannot get it to reproduce when using the actual xcode 9 beta 6 locally.  At the same time I cannot build for the iOS 11 device with Xcode 8.  Nutz

**Comment by hackiftekhar** [comment]
Can you please send me a demo project so that I can look what might be the cause?

**Comment by kikogo** [comment]
I've the same issue:
![img_1767](https://user-images.githubusercontent.com/705778/30154870-817f61ba-93bb-11e7-8da9-0e4a3deac850.jpg)

**Comment by MaximusMcCann** [comment]
Only on iOS 11 device using TestFlight.  Building on the Xcode beta shows everything working correctly. 
![img_0035](https://user-images.githubusercontent.com/1643285/30294224-f6c88e1c-9701-11e7-8d85-ea0899aeb0f5.jpg)

**Comment by chenhuaizhe** [comment]
run in Xcode 8 will case this problem.

**Comment by chenhuaizhe** [comment]
run in Xcode 8 will case this problem.

**Comment by chenhuaizhe** [comment]
run in Xcode 8 will case this problem.</br>But in Xcode 9 it will be OK .</br>Mybe you should set like below:</br>```IQKeyboardManager*  iqkeyBoard=[IQKeyboardManager sharedManager];iqkeyBoard.shouldShowToolbarPlaceholder=NO;```

**Comment by pageone123** [comment]
Did you solve this problem?

**Comment by chenhuaizhe** [comment]
I just hide the  ToolbarPlaceholder .
Like this: iqkeyBoard.shouldShowToolbarPlaceholder=NO;

**Comment by hackiftekhar** [comment]
Actually I'm not able to debug it since this isn't reproducible with debug mode but reproducing in Testflight build.

**Comment by playscforever** [comment]
i can reproducible in debug mode @hackiftekhar

**Comment by hackiftekhar** [comment]
I already got whats the issue and already fixed with https://github.com/hackiftekhar/IQKeyboardManager/commit/c38b6c11acb375292412695e47a7bbdbf980cc1b. Problem caused when we compile app with Xcode 8.3.3 or below and then install app via TestFlight in iOS11 device.
