### ISSUE TITLE
IQKeyboardManager cause app to Crash with GMSAutocompleteViewController 

### ISSUE THREAD

**Issue by embassem** [hackiftekhar/IQKeyboardManager#948]
i use    - IQKeyboardManager (4.0.12) with . Google maps and Google places and   GooglePlacePicker

the app start to crash when present  GMSAutocompleteViewController 
after debug  i found that it was a IQKeyboardManager which crash the app 
here is a call stack :
`Client[16513:1632140] *** Terminating app due 
 to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM 
 objectAtIndex:]: index 0 beyond bounds for empty array'
 *** First throw call stack:
 (
    0   CoreFoundation                      0x000000010b9d6b0b 
  __exceptionPreprocess + 171
    1   libobjc.A.dylib                     0x000000010b2a8141 
  objc_exception_throw + 48
    2   CoreFoundation                      0x000000010b90bffb -
  [__NSArrayM objectAtIndex:] + 203
    3   IQKeyboardManager                   0x000000010804bfe3 -
  [IQKeyboardManager addToolbarIfRequired] + 3539
    4   IQKeyboardManager                   0x0000000108047642 -
    [IQKeyboardManager textFieldViewDidBeginEditing:] + 1234
    5   CoreFoundation                      0x000000010b975c2c _ . 
 _CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
    6   CoreFoundation                      0x000000010b975b29 
   _CFXRegistrationPost + 425
    7   CoreFoundation                      0x000000010b975892 
  ___CFXNotificationPost_block_invoke + 50
    8   CoreFoundation                      0x000000010b939102 -
   [_CFXNotificationRegistrar find:object:observer:enumerator:] + 1826
    9   CoreFoundation                      0x000000010b938261 
     _CFXNotificationPost + 673
    10  Foundation                          0x0000000107a91ca4 -
    [NSNotificationCenter postNotificationName:object:userInfo:] + 66
    11  UIKit                               0x000000010a1cf913 -
    [UITextField _becomeFirstResponder] + 692
    12  UIKit                               0x0000000109afeb0d -
    [UISearchBarTextField _becomeFirstResponder] + 94
        13  UIKit                               0x000000010a1cf4f5 -
    [UITextField __resumeBecomeFirstResponder] + 52
    14  UIKit                               0x0000000109afee72 __45-
     [UISearchBarTextField _becomeFirstResponder]_block_invoke + 381
    15  UIKit                               0x0000000109afecf3 -
     [UISearchBarTextField _becomeFirstResponder] + 580
    16  UIKit                               0x00000001098e6171 -
      [UIResponder becomeFirstResponder] + 436
        17  UIKit                               0x000000010977f647 -
    [UIView(Hierarchy) becomeFirstResponder] + 137
    18  UIKit                               0x000000010a1ce8c6 -
    [UITextField becomeFirstResponder] + 50
    19  UIKit                               0x0000000109afb9cc -
    [UISearchBar(UISearchBarStatic) becomeFirstResponder] + 48
    20  Client                              0x0000000104939085 -
    [GMSAutocompleteContentViewController viewWillAppear:] + 159
    21  UIKit                               0x0000000109878bad -
    [UIViewController _setViewAppearState:isAnimating:] + 447
    22  UIKit                               0x00000001098793c3 -
    [UIViewController __viewWillAppear:] + 147`

**Comment by hackiftekhar** [comment]
This probably already fixed with the latest version.
