### ISSUE TITLE
4.0.13 broke backwards compatibility

### ISSUE THREAD

**Issue by Emailrus** [hackiftekhar/IQKeyboardManager#950]
`- (void)setEnablePrevious:(BOOL)isPreviousEnabled next:(BOOL)isNextEnabled;`

Used to be a public method, that is no longer there and semantic versioning states states, that "PATCH version when you make backwards-compatible bug fixes".
 I would suggest marking that method as deprecated until 5.0.0 is released

**Comment by hackiftekhar** [comment]
There is another way now to do this something like `keyboardToolbar.previousBarButton.enabled=true`

**Comment by hackiftekhar** [comment]
You can find this in project demo.

**Comment by Emailrus** [comment]
The issue is not about how can someone disable buttons, it's about how libraries are distributed via Cocoapods. 
See here https://guides.cocoapods.org/making/making-a-cocoapod.html#library-versioning 

Basically what happened is :
We used to have  `pod 'IQKeyboardManager', '~> 4.0'` in our project, so we could receive all fixes and non breaking changes from you up until 5.0.0 (excluding). After pod update we had non-compilable project due to changes in API and had to froze pod to a specific version until someone would investigate the issue.

In any case we greatly appreciate your work and this library is awesome =)

**Comment by hackiftekhar** [comment]
Ahh, ok I got you. Will keep in my mind next time.
