### ISSUE TITLE
iOS 11 Beta Animation issue

### ISSUE THREAD

**Issue by pateljinal1844** [hackiftekhar/IQKeyboardManager#952]
Helllo,

I have installed iOS 11 beta in my iphone. But when i make any textfiled to becomefirstResponder, it make scrollview to scroll down to screen instead of setting it's proper content offset.

**Comment by pateljinal1844** [comment]
Here i am attaching screenshot for above issue. 
Pl check and suggest any solution.

![img_2458](https://user-images.githubusercontent.com/31406498/30012412-2b2b0ec8-915d-11e7-8a8d-ce3993ae87a4.PNG)

**Comment by fss1994** [comment]
i have the same problem as u

**Comment by sudhakar-varma** [comment]
once try becomefirstResponder code in -(void)viewWillAppear:(BOOL)animated

**Comment by fss1994** [comment]
`once try becomefirstResponder code in -(void)viewWillAppear:(BOOL)animated`
it can not resolve my problem

**Comment by linbx08** [comment]
i have the same issue,  hope  settled the question. thanks a lot

**Comment by pateljinal1844** [comment]
once try becomefirstResponder code in -(void)viewWillAppear:(BOOL)animated

I cant do this.... as i need to set becomeFirstResponder() on save click of button.
So if possible suggest any other solution.

**Comment by fss1994** [comment]
i  have settled the problem, my code can not scroll because i set the tableView.scrollEnable = NO, in iOS 11, it can be someThing wrong(in iOS 10 , it's ok), and i choose  delete the "tableView.scrollEnable = NO", and it works. maybe my problem is not same as yours, but it works for me.  i also found in iOS 11, the DONE button in toolBar above keyboard is hidden, the i found my version is '4.0.10',and in '4.0.13' the DONE button is show,that's all

**Comment by linbx08** [comment]
thanks a lot. in the new version `4.0.13` i have settled the problem ,the DONE button is show appear again,  thank you very much

**Comment by pateljinal1844** [comment]
In my demo, i did not false scrollenable property. So this suggestion is not useful to me.

**Comment by pateljinal1844** [comment]
Anyone found any solution?

**Comment by hackiftekhar** [comment]
@pateljinal1844 can you share any demo project with me so that I can take a look.

**Comment by pateljinal1844** [comment]
I have updated version to 4.0.13...Now i am not facing any issue.

**Comment by SerxLee** [comment]
try this 
[self.searchTextField performSelector:@selector(becomeFirstResponder) withObject:nil afterDelay:0]
