### ISSUE TITLE
Crash on Done button tap

### ISSUE THREAD

**Issue by dethell** [hackiftekhar/IQKeyboardManager#954]
I know there are previous, older issues about this, but I'm having this issue with the latest source code and no changes. On certain devices (no obvious common theme because it happens on iPhone 6, iPad Mini 1, iPhone 7, etc) the app crashes when you press the Done button. It is happening on line 2003, which is the barButton.invocation call in this function:

```
/**     doneAction. Resigning current textField. */
-(void)doneAction:(IQBarButtonItem*)barButton
{
    //If user wants to play input Click sound. Then Play Input Click Sound.
    if (_shouldPlayInputClicks)
    {
        [[UIDevice currentDevice] playInputClick];
    }

    BOOL isResignedFirstResponder = [self resignFirstResponder];

    if (isResignedFirstResponder == YES && barButton.invocation)
    {
        [barButton.invocation invoke];
    }
}
```
Is there any solution to this? If I comment out the last if block I am able to use the library without a crash. Is there any harm in not having the barButton.invocation code present?

Thanks for your help.

**Comment by hackiftekhar** [comment]
It does, actually it dismiss the textField.

**Comment by hieuphq** [comment]
I got the same issue. I used Carthage to add IQKeyboardManager to my project. I got an error at:

IQKeyboardManager.m:1999

I attached my error log file:

[com.dwarvesf.griffinsurvey_issue_1_crash_40ec32f3655c4c7991d778446ba3f81e_5d36fbeb93a911e7b32456847afe9799_0_v2.txt](https://github.com/hackiftekhar/IQKeyboardManager/files/1284075/com.dwarvesf.griffinsurvey_issue_1_crash_40ec32f3655c4c7991d778446ba3f81e_5d36fbeb93a911e7b32456847afe9799_0_v2.txt)

**Comment by hieuphq** [comment]
I think I found out something wrong. I don't follow this step:

```
Run carthage to build the frameworks and drag the appropriate framework (IQKeyboardManager.framework or IQKeyboardManagerSwift.framework) into your Xcode project according to your need. Make sure to add only one framework and not both.
```

I used swift to build my app. So I only added  IQKeyboardManagerSwift.framework. Finally, I worked.

**Comment by tariq235** [comment]
@hackiftekhar  @hieuphq  How to add only IQKeyboardManagerSwift ? If I add only swift project then i get crash 

```
dyld: Library not loaded: @rpath/IQKeyboardManager.framework/IQKeyboardManager
  Referenced from: /var/containers/Bundle/Application/E48B458F-1375-4903-B107-BFC1C29DDA81/MSFrontend.app/MSFrontend
  Reason: image not found
```
I have to add both in Embed Framework to get rid of this crash. Please help!

**Comment by hackiftekhar** [comment]
That's why I said you shouldn't add both. Remove IQKeyboardManager.framework if you are using IQKeyboardManagerSwift.framework.

**Comment by 9SumeetMourya** [comment]
Hello, 
I have mix classes in my project.
I have used only IQKeyboardManagerSwift then in ObjectiveC class Viewcontroller don't have the toolBar for hide the keyboard and If add both the IQKeyboardManagerSwift and IQKeyboardManager then I toolbar with done button but when I tap my application is crashed.

**Comment by hackiftekhar** [comment]
You shouldn't add both library at all, you should only add one, can you please check if you are changing enableAutoToolbar property to NO?

**Comment by 9SumeetMourya** [comment]
Thanks for reply, I got the solution, I am using only one library now, **IQKeyboardManagerSwift**.
I made some mistake for using IQKeyboardManagerSwift in objectiveC class, I resolve that.
