### ISSUE TITLE
Ref to 806 - initialize in objective-c

### ISSUE THREAD

**Issue by tamutti** [hackiftekhar/IQKeyboardManager#955]
This hasn't been completely fixed. Just updated to latest and this message still appears for IQbarButtonItem.swift and IQToolbar.swift for swift 3.1 on xcode 8.

IQKeyboardManagerSwift/IQKeyboardManagerSwift/IQToolbar/IQBarButtonItem.swift:29:30: Method 'initialize()' defines Objective-C class method 'initialize', which is not guaranteed to be invoked by Swift and will be disallowed in future versions

IQKeyboardManagerSwift/IQKeyboardManagerSwift/IQToolbar/IQToolbar.swift:33:30: Method 'initialize()' defines Objective-C class method 'initialize', which is not guaranteed to be invoked by Swift and will be disallowed in future versions

**Comment by hackiftekhar** [comment]
Which version of library you are using?

**Comment by tamutti** [comment]
Bundle version is 4.0.7, otherwise it is the primary grabbed by way of pod without a version specified (pod ‘IQKeyboardManagerSwift’). Grabbed this less than 2 weeks ago.

**Comment by hackiftekhar** [comment]
The latest version doesn't have this issue and it has been fixed already.

**Comment by tamutti** [comment]
Running the pod like so

pod ‘IQKeyboardManagerSwift’,'4.0.10'

resolves the problems. Running it without the version as it is also specified in the instructions as an "or" results in not the latest but 4.0.7. Not sure were the disconnect is.

**Comment by hackiftekhar** [comment]
run pod update then
