### ISSUE TITLE
Can this also work not to hide UIButtons under the keyboard?

### ISSUE THREAD

**Issue by ninoguba** [hackiftekhar/IQKeyboardManager#957]
For example, my view is the usual login screen with the customary email and password text fields and the login button.  This works for making sure the email and password fields are always above the keyboard when shown.   Is there a way to make sure all fields and the button appear above the keyboard?

**Comment by hackiftekhar** [comment]
You can set custom distance from textField as your desired value using `keyboardDistanceFromTextField` property defined in `IQUITextFieldView+Additions.h` it will make a workaround
