### ISSUE TITLE
The latest version has this issue 

### ISSUE THREAD

**Issue by liunianhuaguoyanxi** [hackiftekhar/IQKeyboardManager#958]
about objective-c in IQKeyboardManager.m ,if siblings.count ==0 it will crash
-(void)addToolbarIfRequired
{
    CFTimeInterval startTime = CACurrentMediaTime();
    [self showLog:[NSString stringWithFormat:@"****** %@ started ******",NSStringFromSelector(_cmd)]];
    
    //	Getting all the sibling textFields.
    NSArray *siblings = [self responderViews];

   // if siblings.count =0 it will crash
   //I think should add such codes
    if (siblings.count<=0) {
        return;
    }

**Comment by hackiftekhar** [comment]
This is already fixed with lateset version.
