### ISSUE TITLE
In iOS11 test no problem, but submitted to the App Store after the problem

### ISSUE THREAD

**Issue by pageone123** [hackiftekhar/IQKeyboardManager#963]
placeHolderLabel position went to the (0,0) position, and hope that you can see me after the big God to see, our online products there is such a problem and hope that developers can repair loopholes as soon as possible, be grateful!
[picture](http://od2isuzb1.bkt.clouddn.com/WechatIMG116.png)

**Comment by hackiftekhar** [comment]
Hello @pageone123 I'm not sure why this happens sometime, I know some users are getting this issue but I'm unable to reproduce this issue with my demo. I believe this is something with the Xcode settings or the iOS version.
