### ISSUE TITLE
Crash on UITextField enter

### ISSUE THREAD

**Issue by Yetispapa** [hackiftekhar/IQKeyboardManager#964]
I updated the newest IQKeyboardManager with carthage:

`github "hackiftekhar/IQKeyboardManager"`

When I enter a UITextField with a tap gesture I get the EXC_BAD_ACCESS error on the following line:

```
default:
toolbar.barStyle = UIBarStyle.default

```

The only thing which I call from IQKeyboardManager is the following line:

`IQKeyboardManager.sharedManager().enable = true`

Can someone give me any advie here?

**Comment by jimmyWJJ** [comment]
我也有相同的问题,希望能解决

**Comment by gb-6k-house** [comment]
v4.0.13 did fix the issue.
