### ISSUE TITLE
Ignorable UIScrollView classes for nested ScrollViews

### ISSUE THREAD

**Issue by leesherwood** [hackiftekhar/IQKeyboardManager#965]
If you have your text field inside a UIScrollView that is not the UIScrollView that you want to adjust, this can cause problems.

In my own specific instance, My TextView was embedded in a UIScrollView for auto-growing (I used [this library](https://github.com/muukii/NextGrowingTextView)). This meant that IQKeyboardManager was detecting the TextField wrapper that library uses, instead of the main Scroll view, and causing issues.

I've implemented a very simple `var ignoreUIScrollViewObjects: Set<String> = []` with the relevant superview check in my own fork of this library, that allows me to do the following:

`        IQKeyboardManager.sharedManager().ignoreUIScrollViewObjects = Set(["NextGrowingTextView"])`

or using a helper method:
`IQKeyboardManager.sharedManager().setIgnoredScrollViewObjects([NextGrowingTextView.self])`

I'm not sure if this is considered "out of scope" for this library, but it would be great if such function was available in the original library, just in the rare scenarios where it would be really useful. It's simple to implement too :)

I'd be happy to PR it if you want, but i'm probably breaking all of your own programming style guidelines.

At least if you don't want such a thing in your library, people should be able to find this issue now and see how they can do it themselves if they really want too :)

Here's the commit of my changes:

https://github.com/leesherwood/IQKeyboardManager/commit/5e4a015a2fc9678654ee74e36536ca78741983bb

**Comment by hackiftekhar** [comment]
Hey @leesherwood your changes is good, however most of the developer doesn't subclass UIScrollView, so I made a better solution by adding another property to UIScrollView category.
