### ISSUE TITLE
How to install IQKeyboardManager on iOS 11 with Swift 4?

### ISSUE THREAD

**Issue by Adelmaer** [hackiftekhar/IQKeyboardManager#966]
Hello, I've been using IQKeyboardManager for iOS 10.
It stopped working correctly after the update of my app to iOS 11 and migrating to Swift 4.
Can you please tell me, is there any version that I can install via CocoaPods that supports Swift 4?
Or maybe you can provide a workaround?

**Comment by hackiftekhar** [comment]
There is no CocoaPods version which support Swift4 for now, but will be pushing Swift4 version soon. For now you might try using swift4 branch.

**Comment by alexwillingham** [comment]
I've got some errors in Xcode 9 GM Seed with the Swift4 branch.  Looks like a tiny fix.  Working on a PR.

**Comment by alexwillingham** [comment]
https://github.com/hackiftekhar/IQKeyboardManager/pull/970

**Comment by BalintDezso** [comment]
@alexwillingham Even with the fix you have I still get the error. Any idea when the swift 4 version will be ready @hackiftekhar?

**Comment by alexwillingham** [comment]
Strange.  Did you unlock the file and make the change manually yourself, or switch to my branch in cocoapods?  If you switched to my branch with cocoapods, `pod install` may have succeeded without downloading my code due to caching.  Would try clearing cache, https://gist.github.com/mbinna/4202236#gistcomment-1814665

**Comment by hackiftekhar** [comment]
I'm working on pushing swift4 version to CocoaPods, but it might take 1-2 days since I'm checking all existing issues with swift4 & iOS11 and trying to fix those before pushing a new version.

**Comment by hackiftekhar** [comment]
@alexwillingham Due to the method name conflict between two categories, I renamed UIWindow category method name.

**Comment by hackiftekhar** [comment]
**Just released 5.0.0 via CocaPods**
- **swift4** support
- Backward compatibility till **swift3**.
- Support **iOS11** as well, however there might be issues with **iOS11** I'm not much aware of. But it's the best version for now with **iOS11** support.

Cheers!
