### ISSUE TITLE
Not working on iOS 11

### ISSUE THREAD

**Issue by lawgimenez** [hackiftekhar/IQKeyboardManager#967]
This library is not working properly anymore on iOS 11, completely removed it and used other solutions on StackOverflow.

**Comment by Adelmaer** [comment]
@lawgimenez can't you recommend any similar libraries?

**Comment by linbx08** [comment]
The problem with this?

**Comment by kumararvind** [comment]
Incredible! in the new version 4.0.13 the problem has be solved, thank you very much

**Comment by hackiftekhar** [comment]
@lawgimenez @Adelmaer @linbx08 @kumararvind I'm working on fixing all existing issues with swift4 and iOS11 before pushing a new version of library.
