### ISSUE TITLE
Not working on iOS 11

### ISSUE THREAD

**Issue by YurchukV** [hackiftekhar/IQKeyboardManager#968]
The inscription is not displayed correctly,
when using pod 'IQKeyboardManagerSwift', '4.0.11' there is no such error![img_0fb8944e0ff1-1](https://user-images.githubusercontent.com/6242240/30529777-e8f71144-9c62-11e7-9b00-500890577d7d.jpeg)

**Comment by sudhakar-varma** [comment]
same issue.. this issue is with latest version.. '4.0.12' works fine

**Comment by hackiftekhar** [comment]
@sudhakar-varma @YurchukV from couple of users, if looks like the error is happening with testflight build. If you having this issue with the debugging environment then can you please share the demo project?

**Comment by alexwillingham** [comment]
I've got this issue with all 4.x versions of IQKeyboardManager.  Tried with 4.0.8, 4.0.12, 4.0.13.  I can not use 5.x because I can't build my project in Xcode 9 yet, due to some other dependencies which are not yet built only with Swift 3.1 still.

**Comment by hackiftekhar** [comment]
@alexwillingham I made 5.0.x compatible for swift 3.0, can you please check if this works for you?

**Comment by alexwillingham** [comment]
I can build, but crash immediately, when using `5.0.2` of this library in my app in `Xcode 8.3.3 (8E3004b)`

![image](https://user-images.githubusercontent.com/3759688/30968144-546600c2-a42c-11e7-853a-69042372dc4a.png)

I have discovered however, that 5.0.0 does run in Xcode 8.3.3.  So it seems there's a regression in version > 5.0.0 for Xcode 8.3.3, swift 3, compatibility.  Unfortunately, with the 5.0.0 version built under Xcode 8.3.3, this bug still persists.  The hint text does not sit in the keyboard accessory view, but floats in the top left of the screen as in this ticket's original post.

**Comment by smithparkar** [comment]
<img width="192" alt="screen shot 2017-10-04 at 1 29 34 pm" src="https://user-images.githubusercontent.com/26294355/31165347-65d63864-a908-11e7-8a23-86d4b1c7265d.png">

Not Working with iOS 11 
I am using this IQKeyboardManager objective c Pod .
