### ISSUE TITLE
Issue in iOS 11 (running from XCode 9)

### ISSUE THREAD

**Issue by Bharath-MallowTech** [hackiftekhar/IQKeyboardManager#969]
In Keyboard toolbar the Done button is not appearing. Reference image attached below,

![image](https://user-images.githubusercontent.com/16458195/30592538-cd6a9d62-9d64-11e7-9cb1-5ea3fbf860e3.png)

**Comment by Baiyongyu** [comment]
I also appeared the same problem, please repair.

**Comment by fanyuecheng911006** [comment]
update to 4.0.13

**Comment by niting007** [comment]
for 4.0.13 version getting following error 
module compiled with Swift 3.1 cannot be imported in Swift 3.2: /Users/nitingaikwad/Library/Developer/Xcode/DerivedData/BDK-dwzwydsgdjfosobicotneskqxttq/Build/Products/Debug-iphoneos/IQKeyboardManagerSwift/IQKeyboardManagerSwift.framework/Modules/IQKeyboardManagerSwift.swiftmodule/arm64.swiftmodule

**Comment by asd8855** [comment]
I also appeared the same problem, 4.0.13

**Comment by wutao66** [comment]
me too

**Comment by a714857512** [comment]
me too

**Comment by james02300** [comment]
me too

**Comment by monishpainter** [comment]
Did you find solution ?

**Comment by eviltofu** [comment]
For the "compiled with Swift 3.1 cannot import to Swift 3.2" error, have you tried cleaning and recompiling?

**Comment by arekotto** [comment]
me too

**Comment by luchaoqun123** [comment]
me too

**Comment by ahmedraad** [comment]
me too

**Comment by DevZaid** [comment]
me too

**Comment by kumararvind** [comment]
me too facing same issue

**Comment by Shahbaz-Akram** [comment]
facing same issue

**Comment by Shahbaz-Akram** [comment]
any one find solution?

**Comment by kumararvind** [comment]
Incredible! in the new version 4.0.13 the problem has be solved, thank you very much

**Comment by Shahbaz-Akram** [comment]
None of your spec sources contain a spec satisfying the dependency: `IQKeyboardManagerSwift (~> 4.0.13)`.

**Comment by kumararvind** [comment]
I just download the sourcecode version 4.0.13 and copy the IQKeyboardManagerSwift folder in my project and now it works charm.

**Comment by niting007** [comment]
After downloading the final version of xcode its working like charm but not working on GM Seed 9 version

**Comment by GouWeiBaCao** [comment]
me too ,   the done button was hidden ,other is ok in toolbar ,when the done button is selected it appears,  xcode9  ios 11 pod 4.0.13

**Comment by chengsam** [comment]
#914

**Comment by hackiftekhar** [comment]
@Bharath-MallowTech this issue is already been fixed with 4.0.13.

**Comment by hackiftekhar** [comment]
@niting007 you have to clear module cache. Can you please try?

**Comment by asd8855** [comment]
@hackiftekhar  I've cleared the cache，but problems remain

**Comment by asd8855** [comment]
@hackiftekhar  oc  4.0.13

**Comment by chengsam** [comment]
Hi all, it works for me on iOS 11 using 4.0.13 now. I don't know why it happens suddenly but cleaning the project or reinstalling the pod may help.

**Comment by asd8855** [comment]
I found the reason for the problem of our project. We set the following code
    UIBarButtonItem *appearance = [UIBarButtonItem appearance];
    NSMutableDictionary *textAttrs = [NSMutableDictionary dictionary];
    textAttrs[NSForegroundColorAttributeName] = [UIColor whiteColor];
    textAttrs[NSFontAttributeName] = [UIFont systemFontOfSize:15];
    [appearance setTitleTextAttributes:textAttrs forState:UIControlStateNormal];

The author is also using UIBarButtonItem *appearance = [UIBarButtonItem appearance];
It's also set up.So it's always white

**Comment by Baiyongyu** [comment]
4.0.13? Why do I use cocoapods search detection, the latest version is still 4.0.10.

**Comment by asd8855** [comment]
@Baiyongyu  clear cache.pod update repo

**Comment by Baiyongyu** [comment]
@asd8855  Thank u.

**Comment by Bharath-MallowTech** [comment]
Thank you, Its working fine with the version 4.0.13.
![image](https://user-images.githubusercontent.com/16458195/30730911-e204b1d4-9f87-11e7-8803-f97e310d278a.png)

**Comment by Shahbaz-Akram** [comment]
thanks it is working fine.

**Comment by techverx** [comment]
Yes, it is working with 4.0.13

**Comment by parveen17** [comment]
Yes, it is working with 4.0.13

**Comment by zivato** [comment]
How do I get version 4.0.13

**Comment by hackiftekhar** [comment]
Via cocoapods or downloading from tag.
