### ISSUE TITLE
My appearance, following the upgrade, iOS11, xcoe9, toobar, the button on both sides disappeared

### ISSUE THREAD

**Issue by smilelifu** [hackiftekhar/IQKeyboardManager#974]
![default](https://user-images.githubusercontent.com/29700174/30677922-4d2fe0cc-9ec1-11e7-957c-d0559a0c6f4d.png)

**Comment by heavenbird2016** [comment]
Me too.

**Comment by daiguayuzhutou** [comment]
pod update, The issue has been resolved.

**Comment by smilelifu** [comment]
Thank you

**Comment by liuxz656** [comment]
the newest version is 4.0.11?

**Comment by liuxz656** [comment]
me too.

**Comment by hackiftekhar** [comment]
The newest version is 4.0.13 fixed the issue. Let me know if someone still getting this issue.
