### ISSUE TITLE
打开调试每次都会被断点到这里

### ISSUE THREAD

**Issue by 643824979** [hackiftekhar/IQKeyboardManager#975]
warning: could not execute support code to read Objective-C class data in the process. This may reduce the quality of type information available.
![ad578370-ddbb-4ebd-9351-1a997aa35cc5](https://user-images.githubusercontent.com/7730311/30680590-24afbc2c-9e66-11e7-9082-3d45452e5685.png)

**Comment by ETHANAIR** [comment]
same problem in iOS 11

**Comment by hackiftekhar** [comment]
@643824979 क्या आप इंग्लिश में हमें बताएँगे की आपको क्या दिक्कत जा रही है?

**Comment by yuwuchaio** [comment]
Run The Project  in Xcode 9 with  a 'Exception breakpoint' .It will happen Every time. v4.0.13 @hackiftekhar

**Comment by WilYoung** [comment]
Same problem.V5.0.6

**Comment by ShowHandAce** [comment]
Xcode9 +1

**Comment by focuswei** [comment]
maybe submit breakpoint in this version 5.0.6 ,must be ignore xcuserdatad when pull request?

**Comment by iTofu** [comment]
@643824979 
@ETHANAIR 
@hackiftekhar 
@yuwuchaio 
@WilYoung 
@ShowHandAce 
@focuswei 

Do this:
Edit Breakpoint... -> Exception -> ObjC only
It works for me, good luck guys :)

**Comment by kelvin943** [comment]
same problem in iOS 11

**Comment by iOSCuriosity** [comment]
same problem v5.0.3 in iOS 11

**Comment by zvving** [comment]
@iTofu Thx! Work for me.

**Comment by WilYoung** [comment]
@iTofu Thanks!Work for me.
