### ISSUE TITLE
Issues   IQKeyboardManager 4.0.13    iOS11   Xcode9

### ISSUE THREAD

**Issue by qiuseruxin** [hackiftekhar/IQKeyboardManager#976]
When I click on the green button to submit the data
 [self. tableview  reloadData]；
problem  GIF：

![untitled1](https://user-images.githubusercontent.com/19419747/30684070-5f9efcb8-9ee2-11e7-9029-ea3c88e026ed.gif)

When the keyboard disappears, the view moves with an exception It's normal to re-enter the viewcontroller

**Comment by ETHANAIR** [comment]
same problem in iOS 11
but I think you can try to set  

> self.automaticallyAdjustsScrollViewInsets = NO;

**Comment by hackiftekhar** [comment]
hmm, looks strange. @qiuseruxin can you please provide me a demo project?

**Comment by qiuseruxin** [comment]
Thank you for your reply but I have already set it up, or it will happen @ETHANAIR

**Comment by bendary** [comment]
try to set scrollView.contentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentNever;?

**Comment by hackiftekhar** [comment]
I feel `contentInsetAdjustmentBehavior` is the worst property added to UIKit ever. It breaks most of the app.

**Comment by qiuseruxin** [comment]
Still not good after modification @bendary

**Comment by hackiftekhar** [comment]
Can you provide a demo project @qiuseruxin ?

**Comment by qiuseruxin** [comment]
Thank you for your reply. Please give me some time. I have a lot of work to do now @hackiftekhar

**Comment by qiuseruxin** [comment]
I'm sorry to have kept you waiting for so many days, I have already written a demo and  recorded a GIF images in the project. it git address is 
https://github.com/qiuseruxin/IQKeyboardManagerBugDemo.git
Thank you very much @hackiftekhar

**Comment by yashvyas29** [comment]
@qiuseruxin 

I have added

`self.tableview.contentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentNever;`

at the end of your TestViewController.m -> createTableView method and its working fine.
@bendary is correct at his point.

<img width="1440" alt="screen shot 2017-10-07 at 12 16 23 pm" src="https://user-images.githubusercontent.com/5429210/31305531-897b2722-ab59-11e7-9422-080b5cca1da6.png">

**Comment by qiuseruxin** [comment]
Thank you very much, but there will be problems with other controllers. @yashvyas29

**Comment by Lovyom** [comment]
Facing the same issue, and tried the below solution 
self.tableview.contentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentNever 

But nothing has changed. Still getting screen with the white space :(

**Comment by sudhakar-varma** [comment]
add the tableview and bottom input bar to view and add that view to scroll view it will work.. It worked for me

**Comment by qiuseruxin** [comment]
It works, But I don't understand why this works  @sudhakar-varma

**Comment by sudhakar-varma** [comment]
As per my understanding IQKeyboardManager library is totally related/depend on scroll view, so this might work properly with scroll view.

**Comment by yashvyas29** [comment]
@sudhakar-varma  It generates issue in chat. The new chats will not be visible when keyboard is visible when there are no previous chats and double scroll will be there because of extra scrollview.

**Comment by sudhakar-varma** [comment]
@yashvyas29 even i faced the same issue but resolved. Set delagates to scroll view and tableview then  `- (void)scrollViewWillBeginDragging:(UIScrollView *)scrollView` hide your keyboard in this. So when scrolling begins keyboard will dismiss.

**Comment by sudhakar-varma** [comment]
@yashvyas29 you can also use this objc `scrollView.keyboardDismissMode = UIScrollViewKeyboardDismissModeOnDrag;` swift `scrollView.keyboardDismissMode = .onDrag`

**Comment by yashvyas29** [comment]
@sudhakar-varma I am not asking about the keyboard dismiss process on scroll or drag.

When we already don't have any messages and keyboard is also visible. In that case if someone sends any message then that will not be visible before keyboard will dismiss.

Its generating because scroll view content size will be same when keyboard appears but the scroll view frame will be changed by IQKeyboardManager.

**Comment by hackiftekhar** [comment]
@qiuseruxin Demo project link isn't working. Are you sure you the demo project is there?

**Comment by qiuseruxin** [comment]
I have updated the latest edition IQKeyboardManager，I find that you have solved the problem，So I deleted the demo. @hackiftekhar
