### ISSUE TITLE
Not working in ios 11 . Done button goes out of screen . (issue #914 reopened)

### ISSUE THREAD

**Issue by zeeshansuleman** [hackiftekhar/IQKeyboardManager#977]

**Comment by liuxz656** [comment]
me too .. OC?

**Comment by hackiftekhar** [comment]
@zeeshansuleman Have you tried with 4.0.13? This version has the fix.

**Comment by MrVokie** [comment]
haven't deployed on CocoaPods.

**Comment by xiaopin** [comment]
I have updated to version 4.0.13, but done button color is white, not is black?

**Comment by hackiftekhar** [comment]
Are you setting any appearance property?

**Comment by xiaopin** [comment]
Yes

UIBarButtonItem *barButtonItem = [UIBarButtonItem appearance];
    NSDictionary *dict = @{
                           NSFontAttributeName: [UIFont systemFontOfSize:15.0],
                           NSForegroundColorAttributeName: [UIColor whiteColor]
                           };
    [barButtonItem setTitleTextAttributes:dict forState:UIControlStateNormal];

**Comment by hackiftekhar** [comment]
That’s why you are getting this issue, because you are setting bar button item color as white.

**Comment by hackiftekhar** [comment]
I tried checking appearance proxy and It looks to be an issue from UIKit, because I tried setting my own subclass of UIBarButonItem which is `IQBarButtonItem` appearance proxy and the appearance proxies aren't working with my subclass.

**Comment by chefil** [comment]
My done button is gone, and the last one and the next button is gone too, why? just on ios11

**Comment by hackiftekhar** [comment]
Please update to latest version of library which is 5.0.2 at this time

**Comment by MrVokie** [comment]
great!

**Comment by arrrnas** [comment]
@hackiftekhar did you find the solution for https://github.com/hackiftekhar/IQKeyboardManager/issues/977#issuecomment-331439056?

**Comment by hackiftekhar** [comment]
Nope, there is no solution found for this. Because applying appearance proxy on UIBarButtonItem also applying appearance proxy on IQBarButtonItem and overwriting appearance proxy of IQBarButtonItem doesn't work.
