### ISSUE TITLE
Not working in iOS11.0  I can not change the DoneButton's tintColor, default is white. 

### ISSUE THREAD

**Issue by liuxz656** [hackiftekhar/IQKeyboardManager#978]

**Comment by hackiftekhar** [comment]
@liuxz656 can you please share the demo project since it does work with my demo and default tintColor is black as far as I know.

**Comment by 287291867** [comment]
I also is white, but click effect is, how to change

**Comment by hackiftekhar** [comment]
Probably you are setting UIBarButtonItem appearance proxy.

It looks to be an issue from UIKit, because I tried setting my own subclass of UIBarButonItem which is IQBarButtonItem and the appearance proxies aren't working with my subclass.

**Comment by Calvix-Xu** [comment]
In our project, This problem has happened,because our project change the appearance,it like this
 [[UIBarButtonItem appearance] setTitleTextAttributes:@{
                                                           NSFontAttributeName : [UIFont systemFontOfSize:14],
                                                           NSForegroundColorAttributeName : [UIColor whiteColor],
                                                           }
                                                forState:UIControlStateNormal];
}
don't change the appearance has work for us. hope this can help for you.

**Comment by Calvix-Xu** [comment]
It's helpful.Setting the UIBarButtonItem appearance has cause this problem in our project.Ths
