### ISSUE TITLE
SetCustomDoneTarget is missing in branch 4.0.13

### ISSUE THREAD

**Issue by CK11FOR333** [hackiftekhar/IQKeyboardManager#979]
I can't find this method in "IQUIView+Hierarchy.h".
Should I use [textField1 addDoneOnKeyboardWithTarget:self action:@selector(doneAction:)] instead ??

**Comment by arerbol** [comment]
me too

**Comment by ongyoo** [comment]
me too

**Comment by hackiftekhar** [comment]
It's still there in `IQUIView+IQKeyboardToolbar.h` file. You are searching in wrong file my brother @CK11FOR333

**Comment by misheral** [comment]
I have got the same problem.Cann't find SetCustomDoneTarget in  IQUIView+IQKeyboardToolbar.h file. How could I get the input source UITextField?

**Comment by hackiftekhar** [comment]
@misheral Now there is another way to do it, replace your method like this:-
[textField.keyboardToolbar.doneBarButton setTarget:self action:@selector(doneAction:)];
[textField.keyboardToolbar.previousBarButton setTarget:self action:@selector(prevAction:)];
[textField.keyboardToolbar.nextBarButton setTarget:self action:@selector(nextAction:)];
