### ISSUE TITLE
Not Showing Done Button and others in Latest iOS 11.0 Version

### ISSUE THREAD

**Issue by errabelli09** [hackiftekhar/IQKeyboardManager#980]
Previously it's working well but in Latest version changes making some issues with IQKeyboardManager. Done, up and down buttons not showing

**Comment by ArthurAlvarez** [comment]
I'm having the same problem. I managed to get it done by manually adding the UP/Down/Done buttons using the function:
`yourTextField.addPreviousNextRightOnKeyboardWithTarget`

However now I cant change the Done button label :(

**Comment by dejanskledar** [comment]
Yep, same here.

**Comment by errabelli09** [comment]
Its Working with Latest pod updation
