### ISSUE TITLE
branch swift4: has building error in Xcode 9, Swift 4

### ISSUE THREAD

**Issue by JenkinDU** [hackiftekhar/IQKeyboardManager#983]
IQUIWindow+Hierarchy.swift
IQKeyboardManager.swift
some error like
"Declarations in extensions cannot override yet"
"Ambiguous use of 'topMostController()'"

am I do somethings wrong?

**Comment by hackiftekhar** [comment]
I'm converting master branch to support final swift4+iOS11 release. I hope this will fix all existing issue with iOS11 and swift4.

**Comment by hackiftekhar** [comment]
**Just released 5.0.0 via CocaPods**
- **swift4** support
- Backward compatibility till **swift3**.
- Support **iOS11** as well, however there might be issues with **iOS11** I'm not much aware of. But it's the best version for now with **iOS11** support.

Cheers!
