### ISSUE TITLE
error  Use of unresolved identifier 'IQKeyboardManager'

### ISSUE THREAD

**Issue by davestucky** [hackiftekhar/IQKeyboardManager#985]
@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {

    var window: UIWindow?

    private func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
        
        IQKeyboardManager.sharedManager().enable = true (I get this error)Use of unresolved identifier 'IQKeyboardManager'
        
        return true
    }

    func applicationWillResignActive(_ application: UIApplication) {
        // Sent when the application is about to move from active to inactive state. This can occur for certain types of temporary interruptions (such as an incoming phone call or SMS message) or when the user quits the application and it begins the transition to the background state.
        // Use this method to pause ongoing tasks, disable timers, and throttle down OpenGL ES frame rates. Games should use this method to pause the game.
    }

**Comment by iOSUjjwal** [comment]
Try building the app. If still issue, try pod update command.

**Comment by davestucky** [comment]
I tried building  - no joy. I did not use pod and just copied IQKeyboardManager.swift folder to my project. It worked under IOS 10

**Comment by hackiftekhar** [comment]
You might have to @import framework.
