### ISSUE TITLE
Update the pod with Swift 4 support.

### ISSUE THREAD

**Issue by Neney22** [hackiftekhar/IQKeyboardManager#986]
I keep getting a lot of different errors with swift 4

**Comment by hackiftekhar** [comment]
Will try to do in weekend.

**Comment by hackiftekhar** [comment]
**Just released 5.0.0 via CocaPods**
- **swift4** support
- Backward compatibility till **swift3**.
- Support **iOS11** as well, however there might be issues with **iOS11** I'm not much aware of. But it's the best version for now with **iOS11** support.

Cheers!

**Comment by siyavash4812** [comment]
I just installed it through pod and it gives me 37 errors! Most of them are about @objc. Any solution ?

@hackiftekhar
