### ISSUE TITLE
iOS 11 have two compatibility problems

### ISSUE THREAD

**Issue by VolitationXiaoXing** [hackiftekhar/IQKeyboardManager#987]
iOS 11 have two compatibility problems，This is what you see here.
![c35b035d-4d23-46b2-8326-b6f582caccd1](https://user-images.githubusercontent.com/10832078/30725527-fb6c01a0-9f77-11e7-8003-b80f3fa50fe9.png)
![957f0c90-aeca-4084-aebc-4cf016262d53](https://user-images.githubusercontent.com/10832078/30725531-0437afaa-9f78-11e7-940b-3a35a411cdd7.png)

**Comment by jiliuliu** [comment]
I meet the same problems . What should I do ?

**Comment by heavenbird2016** [comment]
@VolitationXiaoXing  To upgrade to the Version 4.0.13  .

**Comment by Rachel829** [comment]
@heavenbird2016  你好，我直接pod update 的版本 还是4.0.10  指定版本 4.0.13 又提示找不到 请问您是如何更新的

**Comment by ravi6880** [comment]
update the pod file and it will remove all error
