### ISSUE TITLE
xcode9运行完成按钮没见了

### ISSUE THREAD

**Issue by 287291867** [hackiftekhar/IQKeyboardManager#988]

**Comment by iosprogram** [comment]
Xcode9运行完,弹出键盘，键盘上方Tool，右边的完成按钮没有了。

**Comment by hackiftekhar** [comment]
Sorry, I don’t undrstand chinese

**Comment by Rachel829** [comment]
in Xcode 9  iOS 11 the "done" button doesn't appear

**Comment by hackiftekhar** [comment]
Please update to 4.0.13

**Comment by Rachel829** [comment]
@hackiftekhar  fixed  thx~
