### ISSUE TITLE
How to modify DoneButton  color?

### ISSUE THREAD

**Issue by Levofloxacin** [hackiftekhar/IQKeyboardManager#991]
In my project DoneButton default color is green.
How to modify this color.
thank you..

**Comment by bakeddean** [comment]
You could try
```
 IQKeyboardManager.sharedManager().toolbarTintColor = .red
```
This sets the tint color of all buttons on the toolbar.

**Comment by Levofloxacin** [comment]
` IQKeyboardManager.sharedManager().toolbarTintColor = .red`
This is not possible
Only previous and next buttons changed the color.
