### ISSUE TITLE
update to 4.0.13; toolbar done button still disappear

### ISSUE THREAD

**Issue by bendary** [hackiftekhar/IQKeyboardManager#992]
![img_4216](https://user-images.githubusercontent.com/8757985/30733252-cc14d180-9fa8-11e7-8bab-e4fc390c8e86.PNG)

**Comment by bendary** [comment]
Actually the done button is on the toolbar and it can response doneAction; but disappear

**Comment by Levofloxacin** [comment]
UIScrollView *scrollView = [UIScrollView new];
    scrollView.showsVerticalScrollIndicator = NO;
    scrollView.backgroundColor = [UIColor clearColor];
    [self.view addSubview:scrollView];

`    IQPreviousNextView *IQView = [[IQPreviousNextView alloc] init];
    IQView.frame = self.view.frame;
    [scrollView addSubview:IQView];`

   [IQView addSubview:inputView];

**Comment by bendary** [comment]
@Levofloxacin thank you; 
but can u tell me something about your code ?

**Comment by Levofloxacin** [comment]
说中文吧看着累.

**Comment by Levofloxacin** [comment]
`IQPreviousNextView *IQView = [[IQPreviousNextView alloc] init];
IQView.frame = self.view.frame;
[scrollView addSubview:IQView];`
试着把这个加到父视图,然后子空间加到该视图上.

或者,试着改变下颜色
`    [IQKeyboardManager sharedManager].toolbarTintColor = [UIColor redColor];
`

**Comment by bendary** [comment]
@Levofloxacin 
哈哈哈，我也敲着累。。边敲边有道翻译。
我先试试第一个吧；
这个改变颜色无效的。试过
[IQKeyboardManager sharedManager].toolbarTintColor = [UIColor redColor];
还有试过这个toolbarBarTintColor，竟然报unrecognicze selector.
先谢了

**Comment by Levofloxacin** [comment]
@bendary 我之前是没有左右箭头. 
`IQPreviousNextView *IQView = [[IQPreviousNextView alloc] init];

  IQView.frame = self.view.frame;
  [scrollView addSubview:IQView];`
加入这个后就可以了

**Comment by hackiftekhar** [comment]
From the screenshot, it looks like you are still using older version of library.

**Comment by rohit-skycap** [comment]
Is release 4.0.13 available on cocoa pods ?

**Comment by hackiftekhar** [comment]
Yes

**Comment by rohit-skycap** [comment]
will pod 'IQKeyboardManagerSwift' is installing (4.0.10).
and pod 'IQKeyboardManagerSwift', '~> 4.0.13' doesnot work.

**Comment by hackiftekhar** [comment]
try pod update

**Comment by bendary** [comment]
@hackiftekhar thk;
i have update cocos pod and it print "Using IQKeyboardManager (4.0.13)"

**Comment by hackiftekhar** [comment]
Great!

**Comment by bendary** [comment]
@hackiftekhar but still have the question  😂

**Comment by hackiftekhar** [comment]
This version should fix the toolbar issue. Didn't worked?

**Comment by hackiftekhar** [comment]
**Just released 5.0.0 via CocaPods**
- **swift4** support
- Backward compatibility till **swift3**.
- Support **iOS11** as well, however there might be issues with **iOS11** I'm not much aware of. But it's the best version for now with **iOS11** support.

Cheers!

**Comment by bendary** [comment]
@hackiftekhar maybe something wrong in my project; 
i used it in other project, it work!
is there something make it wrong?

**Comment by bendary** [comment]
@hackiftekhar thk for your help
i will check my code again

**Comment by bendary** [comment]
![06223581-b70e-48a7-b110-dffdff658eaf](https://user-images.githubusercontent.com/8757985/30757209-64f040fe-a000-11e7-81e3-242d343180fa.png)
![wx20170923-014745](https://user-images.githubusercontent.com/8757985/30757453-64cbf130-a001-11e7-9c20-959a4340fec6.png)
![wx20170923-014846](https://user-images.githubusercontent.com/8757985/30757468-68b9747a-a001-11e7-9d00-04ab7a02161a.png)
i found that button width is 0. Do u know why ?
@hackiftekhar

**Comment by hackiftekhar** [comment]
Can you please try clearing module cache, sometimes xcode uses old cache copy of library.

**Comment by bendary** [comment]
@hackiftekhar 
oh ！！！！！
it is the answer!
thank u for your help !!!
thank u!
