### ISSUE TITLE
ios 11 toolbarTintColor can not set DoneButton color.

### ISSUE THREAD

**Issue by Levofloxacin** [hackiftekhar/IQKeyboardManager#993]
`    [IQKeyboardManager sharedManager].toolbarTintColor = [UIColor redColor];
`

In ios 11 previous and next button color is red.    "Done Button"  is not red..
In ios 10 previous and next button and done button is red.
Please tell me why..
Thank you .

![color](https://user-images.githubusercontent.com/20067385/30735223-c95c73aa-9fb0-11e7-85ea-8aba3ca0fd15.jpg)

**Comment by Marcello168** [comment]
我也想知道啊

**Comment by Marcello168** [comment]
who can tell me ，

**Comment by Levofloxacin** [comment]
@Marcello168 你也有这个问题?

**Comment by Levofloxacin** [comment]
你也有这个问题么.

**Comment by Levofloxacin** [comment]
这个问题已经解决了.
是我本地代码的问题..
谢谢..
