### ISSUE TITLE
Updated to 4.0.13,but cann't find setCustomDoneTarget: in IQUIView+IQKeyboardToolbar.h

### ISSUE THREAD

**Issue by misheral** [hackiftekhar/IQKeyboardManager#994]
For showing the Done UIBarButtionItem in iOS 11 ,updated to  4.0.13,but cann't find setCustomDoneTarget: in IQUIView+IQKeyboardToolbar.h

**Comment by hackiftekhar** [comment]
@misheral Now there is another way to do it, replace your method like this:-
```
[textField.keyboardToolbar.doneBarButton setTarget:self action:@selector(doneAction:)];
[textField.keyboardToolbar.previousBarButton setTarget:self action:@selector(prevAction:)];
[textField.keyboardToolbar.nextBarButton setTarget:self action:@selector(nextAction:)];
```

**Comment by misheral** [comment]
This method has param  with type of  IQBarButtonItem, but what i need is UITextField/UITextView, just like  setCustomDoneTarget .How can i get it?

**Comment by hackiftekhar** [comment]
hmm, okay, let me see what I can do

**Comment by hackiftekhar** [comment]
I can confirm, that's a bug. I'll try to fix it by today.

**Comment by misheral** [comment]
Okay.

**Comment by monkiyang** [comment]
the bug still exists in v5.0.7. the selector wasn't  be called when i clicked done button. the code is
`[_searchBar.keyboardToolbar.doneBarButton setTarget:self action:@selector(doneItemClicked:)];`

 I set a breakpoint in the method `doneAction:` and debugged step by step. I found that the barButton's invocation is nil.

**Comment by hackiftekhar** [comment]
Actually the library isn't optimized to handle this case for searchBar. It might be because searchBar internally contains a UITextField and the settings wasn't affecting internal textField object.

**Comment by monkiyang** [comment]
Thanks for your reply and the library. I hope it will be optimized in the future version.
