### ISSUE TITLE
The IQKeyboardManager  in tabelviewCell  also is have  problem

### ISSUE THREAD

**Issue by myl9361** [hackiftekhar/IQKeyboardManager#995]
ios11 xcode9  ，更新到了4.0.13，  但是在tableViewCell上的textfield ，如果位置在下面键盘遮挡的部分  点击，还是会有问题    有时候键盘都弹不出来，或者弹出来下不去了   tableview 也不会向上面滑动
![img_1941 20170922-175330](https://user-images.githubusercontent.com/18493926/30739531-5003b580-9fc0-11e7-8668-653b2bc02a97.jpg)
  例如 画圈这个位置的textfield 这个位置的根本不行，上面两个位置不会被遮盖的都没问题  求解决！！！！谢谢

**Comment by CK11FOR333** [comment]
same problem also happened in iOS 8

**Comment by hackiftekhar** [comment]
Can someone let me know if you are using UIViewController or UITableViewController on this particular screen?
