### ISSUE TITLE
error Use of unresolved identifier 'IQKeyboardManager' #985 by davestucky was closed 3 hours ago 

### ISSUE THREAD

**Issue by davestucky** [hackiftekhar/IQKeyboardManager#996]
you closed me out. Sorry, what did you mean @import framework?

**Comment by hackiftekhar** [comment]
You should do `@import IQKeyboardManager

**Comment by davestucky** [comment]
Still not working still have error "Use of unresolved identifier 'IQKeyboardManager'". Even tried using pod and got error.  HELP!!

**Comment by hackiftekhar** [comment]
Can you try with a fresh project?

**Comment by davestucky** [comment]
I did that also. I am new to swift programming and have spent two years developing this app for tracking doves and events. Kind of pieced together the app as I went. The IQKeyboard worked great under Swift 3 and then poof. Really want this to work. I just don’t get it. seems no matter what i do it just doesn’t recognize the framework.

Thanks

Dave

**Comment by hackiftekhar** [comment]
So what's the result with a fresh project? Have you installed via cocoa-pods or manually?

**Comment by davestucky** [comment]
Both and it keeps saying unresolved IQKeyboardManager

**Comment by hackiftekhar** [comment]
That's not good, but at last I can say if this is happening then it must be due to some Xcode settings or Xcode version you are using and isn't much related to library.

**Comment by davestucky** [comment]
Kinda what I thought. OK I will press on and see if I can find the challenge. Thank you for your time and energy. Great framework though, you did a great job. You may show this as closed.

Thanks again,
Dave

**Comment by Sam-iOS** [comment]
after pod i am facing this problems:-

No profiles for 'com.iftekhar.IQKeyboardManagerSwift' were found
Xcode couldn't find any iOS App Development provisioning profiles matching 'com.iftekhar.IQKeyboardManagerSwift'.
 how solve this problem please help me..

**Comment by hackiftekhar** [comment]
If you are running on device, then you should use your own provisioning profiles and certificates.
