### ISSUE TITLE
UITextField doesn't slide up when keyboard appears on iOS 11 

### ISSUE THREAD

**Issue by gokhanakkurt** [hackiftekhar/IQKeyboardManager#997]
Hey,

I'm using the latest version of the library `5.0.0` but textfields remain under the keyboard when they are focused.

![simulator 23-09-2017](https://user-images.githubusercontent.com/3924230/30765251-6d204d86-9ff7-11e7-88d0-92e9372cc4d4.gif)

PS: To replicate this scenario, place a `UITextField` at the bottom of `UIScrollView`.

**Comment by hackiftekhar** [comment]
There might be two issues:-
- If you are using UIScrollView as container then you should add such constraints by which UIScrollView know it’s Content Size.
Please be sure that you haven’t added top layout guide and/or bottom layout guide which directly/indirectly affect textField position.

**Comment by gokhanakkurt** [comment]
These were not the issues related with my problem.  For further readers, following steps may be helpful.

I had a structure like following in my storyboard which is `UIScrollView` is the root view in view controller.

![screen shot 2017-09-23 at 12 33 09](https://user-images.githubusercontent.com/3924230/30771960-6cb392d6-a05b-11e7-8359-83f40c4a890d.png)

I've changed this structure by adding `UIView` to the root and making `UIScrollView` child of this.

![screen shot 2017-09-23 at 12 31 17](https://user-images.githubusercontent.com/3924230/30771982-1135ed0e-a05c-11e7-9b51-6361332d6aec.png)

Now it's working as expected!

**Comment by uc-dpt** [comment]
I am also getting same issue, i am using uitableview instead of scrollview.
