### ISSUE TITLE
Xcode 9: Swift 4 Carthage build task fail with exit code 65

### ISSUE THREAD

**Issue by acerts04** [hackiftekhar/IQKeyboardManager#998]
Hello, 

I saw in an earlier issue that this was a bug causing this to happen in Carthage, but did not see a way to fix it. I am getting this error when building scheme for IQKeyboardManager. Any way to resolve this? Thank you

**Comment by hackiftekhar** [comment]
Can you try v5.0.1 latest version? it support Swift4

**Comment by acerts04** [comment]
Thank you for your reply. v5.0.1 is the version i am trying to use. Seems carthage begins to build the scheme for IQKeyboardManagerSwift, then IQKeyboardManager then fails with exit code 65.

**Comment by damianabraham** [comment]
Hello, same error to me using v5.0.1.
Finally I built with version 5.0.0, which builds the Swift version first without errors.

**Comment by haithngn** [comment]
*** Fetching IQKeyboardManager
*** Checking out IQKeyboardManager at "v5.0.0"
*** xcodebuild output can be found in /var/folders/tp/7qwgtnw57p9fkr_0z_8sx0fr0000gn/T/carthage-xcodebuild.hc5aUw.log
*** Building scheme "IQKeyboardManager" in IQKeyboardManager.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Volumes/Store/Workspace/up4.0/Carthage/Checkouts/IQKeyboardManager/IQKeyboardManager.xcodeproj -scheme IQKeyboardManager -configuration Release -derivedDataPath /Users/neo/Library/Caches/org.carthage.CarthageKit/DerivedData/9.0_9A235/IQKeyboardManager/v5.0.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES build (launched in /Volumes/Store/Workspace/up4.0/Carthage/Checkouts/IQKeyboardManager)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/tp/7qwgtnw57p9fkr_0z_8sx0fr0000gn/T/carthage-xcodebuild.hc5aUw.log

**Comment by haithngn** [comment]
@hackiftekhar I also tried with both version 5.0.0 and 5.0.1 the Carthage alway build failed

**Comment by MatanGuttman** [comment]
In my case, in cartfile.resolved the version was 4.x. I removed the entry and ran: carthage update IQKeyboardManager --platform iOS --no-use-binaries

**Comment by hackiftekhar** [comment]
I got the problem. It should work now with v5.0.2.

**Comment by acerts04** [comment]
@hackiftekhar v5.0.2 worked within Carthage. I have added the IQKeyboardManagerSwift.framework into Linked frameworks and libraries, but i am getting an "image not found error"  for IQKeyboardManagerSwift.framework when running the project. Is this a known issue?
