### ISSUE TITLE
Use of '@import' when C++ modules are disabled, consider using fmodules and fcxx-modules

### ISSUE THREAD

**Issue by JeasonL** [hackiftekhar/IQKeyboardManager#999]
![1506146948506](https://user-images.githubusercontent.com/8176138/30770668-c8dfea98-a068-11e7-87ec-fb3603e9cacf.jpg)

How can I solve this problem?

**Comment by huzhiqin** [comment]
me too. Please tell me why?How to resolve it?

**Comment by hackiftekhar** [comment]
okay, then I think it doesn't work perfectly with some projects. Let me revert that change
